/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a,b,c,d,e,h,k,f){this.Init(a,b,c,d,e,h,k,f)}function c(a,b){this.Init(a,b)}function d(a){this.Init(a.u(),a.bg,a);this.yg=a}function e(){this.Init({skyros:e.lh,alta:e.mf,next:e.pv})}function f(a){this.yg=a;this.Nf=this.yg.F();this.xv=this.yg.sp()}a.Rj=function(){};a.v.D(a.Rj,a.Ie);a.Rj.newInstance=function(b,c,d){var e=new a.Rj;e.Init(b,c,d);return e};a.Rj.Jr=function(a){return(new e).Jr(a)};a.Rj.prototype.Init=function(b,h,k){a.Rj.C.Init.call(this,b,h,k);this.Xg=new e;this.I=
new d(this);this.I.Qf(this);a.B.Wa()||this.I.Xr(new c(this.I,this));this.we=null};a.Rj.WS=10;a.Rj.prototype.vf=function(a){a?this.W="off"==a.rendered?a:this.Xg.en(a):this.W||(this.W=this.NF())};a.Rj.prototype.ht=function(a,b,c){this.vf(a);return k.ht(this,b,c)};a.Rj.prototype.ta=function(b,c,d,e,h){this.Bc.KQ();this.vf(b);this.Gx=[];this.xb=c;this.Jb=d;this.Hl();e||(e=0);h||(h=0);k.ta(this,new a.Z(e,h,c,d))};a.Rj.prototype.ela=function(a){(null!=a.Qg()||null!=a.Ch()||a.jk())&&this.Gx.push(a)};a.Rj.prototype.AI=
function(){return 0<this.Gx.length};a.Rj.prototype.qM=function(){return null!=this.I?this.I.jf():null};a.Rj.prototype.Pfa=function(b,c){if(null!=this.I){for(var d=this.Gx,e=b.getId(),h=!1,k=0;k<d.length;k++){var f=d[k].getId();if(e instanceof Array&&f instanceof Array&&a.na.Fe(e,f)||e===f){this.I.Su(d[k]);h=!0;c&&d[k].Sf();break}}h||this.I.Su(this.I.Cb.jI(d));if(d=this.qM())e=d.Sa(),e.Gd("label",d.Ed()),this.u().NI(e)}};a.Rj.prototype.bg=function(a,b){this===b&&this.dispatchEvent(a)};a.Rj.prototype.sp=
function(){return this.Gi};a.Rj.prototype.y6a=function(a){this.Gi=a};a.Rj.prototype.getWidth=function(){return this.xb};a.Rj.prototype.getHeight=function(){return this.Jb};a.Rj.prototype.fla=function(a){this.we=a};a.Rj.prototype.ph=function(){return new f(this)};var h={};a.v.D(h,a.v);h.W7="tickLabel";h.GDa="title";a.v.D(f,a.Rd);f.prototype.zn=function(b){var c=this.yg.ab().mb(b);if(c&&c instanceof a.yi){if(c.Er.type==h.GDa)return"title";if(this.Nf.groups){b=c.Er.level;for(var c=this.xv.eA(c.Er.index,
b),d="",e=0;e<=b;e++)for(var k=this.xv.iq(this.yg.u(),e),f=0;f<k.length;f++){var x=this.xv.sM(k[f]);this.xv.eA(x,e)<=c&&this.xv.kM(x,e)>=c&&(d+="["+this.xv.ui(x,e)+"]")}if(0<d.length)return"item"+d}}return null};f.prototype.qh=function(b){if("title"==b){if(b=this.xv.pC())return b.Ua()}else if(this.xv instanceof a.Ke)for(var c=b.split("[").length-1-1,d=0,e=0,h=0;h<=c;h++){var k=b.indexOf("]"),f=b.substring(b.indexOf("[")+1,k);b=b.substring(k+1);for(var k=this.xv.iq(this.yg.u(),h),v,A=0;A<k.length;A++)if(v=
this.xv.sM(k[A]),this.xv.eA(v,h)==e){d=v;break}for(A=d;A<k.length;A++)if(v=this.xv.sM(k[A]),this.xv.ui(v,h)==f){if(0==b.length)return k[A].Ua();e=this.xv.eA(v,h);break}}return null};a.v.D(e,a.bb);e.pv={skin:a.j.pv,layout:{titleGap:6}};e.mf={axisLine:{lineColor:"#9E9E9E"},majorTick:{lineColor:"rgba(196,206,215,0.4)",baselineColor:"auto"},minorTick:{lineColor:"rgba(196,206,215,0.2)"},tickLabel:{style:new a.j(a.bb.Pm)},titleStyle:new a.j(a.bb.ar)};e.lh={position:null,baselineScaling:"zero",axisLine:{lineColor:"#8A8DAC",
lineWidth:1,rendered:"on"},majorTick:{lineColor:"rgba(138,141,172,0.4)",lineWidth:1,rendered:"auto",lineStyle:"solid"},minorTick:{lineColor:"rgba(138,141,172,0.20)",lineWidth:1,rendered:"off",lineStyle:"solid"},tickLabel:{scaling:"auto",style:new a.j(a.bb.It+"font-size: 11px; color: #333333;"),rotation:"auto",rendered:"on"},titleStyle:new a.j(a.bb.It+"font-size: 11px; color: #737373;"),startGroupOffset:0,endGroupOffset:0,layout:{titleGap:4,radialLabelGap:5,insideLabelGapWidth:4,insideLabelGapHeight:2,
hierarchicalLabelGapHeight:8,hierarchicalLabelGapWidth:15},_locale:"en-us"};e.Dh=function(b,c,d){b=Math.min(a.Ca.cF(b,c.tickLabel.style)/14,1);return Math.ceil(d*b)};a.v.D(d,a.I);d.n4=function(a,b,c,d){return{type:a,id:b,index:c,level:d}};d.prototype.Jk=function(){return this.yg};d.prototype.Tj=function(a){d.C.Tj.call(this,a);var b=this.mb(a.target);b&&this.QM(b)&&a.stopPropagation()};d.prototype.Sw=function(a){var b=this.mb(a.target);b&&(a=a.Jxa,this.QM(b)&&a&&a.preventDefault())};d.prototype.QM=
function(c){return c&&c.Ch&&c.Ch()?(this.nl(a.Za.FI("action",c.Ch(),c.getId()),this.yg),!0):c instanceof b&&c.jk()?(this.nl(a.Za.efa(c.getId(),null,c.bh()),this.yg),!0):!1};d.prototype.z4=function(){return!0};d.prototype.AN=function(){var a=this.Df.rB;return a instanceof b&&null!=a.bh()?"groups":null};d.prototype.YY=function(){var a=this.Df.rB;return a instanceof b?[{id:a.getId(),group:a.bh(),label:a.ge().lf()}]:[]};a.v.D(c,a.Cb);c.prototype.Init=function(a,b){c.C.Init.call(this,a);this.yg=b};c.prototype.mk=
function(b){var d=b.keyCode,e=this.yb.jf(),h=null;d==a.KeyboardEvent.Qh?(e&&(a.I.sc(b),h=e),d=this.yg.Gx,0<d.length&&(a.I.sc(b),h=this.jI(d))):d==a.KeyboardEvent.Zi?e&&(this.yb.QM(e),a.I.sc(b)):h=c.C.mk.call(this,b);return h};var k={};a.v.D(k,a.v);k.dFa=3;k.ht=function(b,c,d){var e=k.AHa(b,new a.Z(0,0,c,d)),h=b.u(),f=b.F(),x="top"==f.position||"bottom"==f.position;if("off"==f.rendered||0>=c||0>=d)return x?new a.yj(c,0):new a.yj(0,d);var v=k.TTa(h,f,.8*(x?c:d),.8*(x?d:c)),v=0!=v?v+k.gKa(b):0;"on"==
f.tickLabel.rendered&&"inside"!=f.tickLabel.position&&(x?(f=a.Ca.cF(h,f.tickLabel.style),e instanceof a.Fi?v+=f:e instanceof a.Fb?v+=null!=e.iq(h,1)?2*f:f:e instanceof a.Ke&&(v=k.wJa(b,e,v,d,x))):e instanceof a.Fi?v+=a.Ca.cA(e.iq(h)).a:e instanceof a.Fb?(b=e.iq(h),b=a.Ca.cA(b).a,e=e.iq(h,1),e=null!=e?a.Ca.cA(e).a:0,v+=Math.max(b,e)):e instanceof a.Ke&&(v=k.wJa(b,e,v,c,x)));return x?new a.yj(c,Math.min(v,d)):new a.yj(Math.min(v,c),d)};k.ta=function(a,b){var c=k.AHa(a,b);"off"!=a.F().rendered&&(a.fla(b.clone()),
k.Gr(a,b),k.mQ(a,c,b),k.b2(a,c,b))};k.AHa=function(b,c){var d=a.sf.newInstance(b.u(),b.F(),c);b.y6a(d);return d};k.gKa=function(a){var b=a.F();return e.Dh(a.u(),b,b.layout.titleGap)};k.Gr=function(b,c){var d=b.F();if(d.dnd){var e=d.dnd.drop;if(0<Object.keys(e.xAxis).length||0<Object.keys(e.yAxis).length||0<Object.keys(e.y2Axis).length)d=d.position,d=(e="top"==d||"bottom"==d)?4:10,e=e?10:4,d=new a.Rect(b.u(),c.x-e,c.y-d,c.a+2*e,c.b+2*d),d.Wb(),b.A(d),b.Bc.Yh("background",d)}};k.mQ=function(b,c,e){var f=
b.F();if(f.title){var p=f.position;if("radial"!=p&&"tangential"!=p){var w="top"==f.position||"bottom"==f.position,x=w?e.a:e.b,w=w?e.b:e.a,v=f.titleStyle,A=k.zC(v);if(f=k.h9a(b.ab(),b,f.title,v,x,w,d.n4(h.GDa),A))x=k.gKa(b),w=(c.h4()-c.y3())/2,b=a.B.da(b.u()),v=a.Ca.qR(f),f.Yf(),"top"==p?(f.Fa(e.x+w+e.a/2),f.jb(e.y),e.y+=v+x,e.b-=v+x):"bottom"==p?(f.Fa(e.x+w+e.a/2),f.jb(e.y+e.b-v),e.b-=v+x):"left"==p?(f.Ng(),f.zp(b?Math.PI/2:3*Math.PI/2),f.Ma(e.x+v/2,e.y+e.b/2),e.x+=v+x,e.a-=v+x):"right"==p&&(f.Ng(),
f.zp(b?Math.PI/2:3*Math.PI/2),f.Ma(e.x+e.a-v/2,e.y+e.b/2),e.a-=v+x),c.Psb(f)}}};k.b2=function(a,b,c){var d=a.F();"on"==d.tickLabel.rendered&&(d=d.position,"top"==d||"bottom"==d?k.Yeb(a,b,c):"tangential"==d?k.Zeb(a,b,c):k.$eb(a,b,c),k.Seb(a,b))};k.Yeb=function(c,f,k){for(var r=c.u(),p=c.F(),w=p.position,x="inside"==p.tickLabel.position,v=a.B.da(r),A=f instanceof a.Ke,u=A&&1<f.pI(),D=u?0:null,B=f.iq(r,D),C=u?e.Dh(r,p,p.layout.hierarchicalLabelGapHeight):0;B;){for(var z=0,G=0,y=0;y<B.length;y++){var E=
B[y];if(null!=E){z=E instanceof a.Zb||E instanceof a.em;if(f.ER(D)){if((!z||z&&!E.zC())&&!a.Ca.kd(E,k.b,k.a,c))continue;v?E.Vh():E.Wh();u?(z=a.Ca.yea(E),E.wa(k.b-z),G=Math.max(G,z)):E.wa(k.y)}else{if(!x&&a.Ca.Pj(E).b-1>k.b)continue;u&&"bottom"==w?E.jb(k.b):"bottom"==w?E.jb(k.y):E.jb(k.y+k.b);!u&&("bottom"==w&&!x||"top"==w&&x)?E.np():u&&"top"==w?E.np():E.Oq();if(u)G=Math.max(G,a.Ca.Pj(E).b);else if(x){var C=e.Dh(r,p,p.layout.insideLabelGapWidth);v?E.Wh():E.Vh();E.Fa(E.Va()+C*(v?-1:1))}}var z=A?f.sM(E):
y,M=f.Qg(z,D),S=E.Uq(),O=f.Ch(z,D),fa=f.jk(z,D),ga=f.bh(z,D);c.ab().lb(E,new b(c,E,ga,O,fa,S,M,d.n4(h.W7,E.lf(),z,D)));u?f.vWa(D):G=Math.max(G,a.Ca.Pj(E).b);c.A(E)}}if(u){for(y=0;y<B.length;y++)E=B[y],null!=E&&(z=f.ER(D),M=D<f.pI()-1,!z&&M?(E.jb(k.b-G/2),E.Ng()):E.wa(k.b-G));k.y+=G+C;k.b-=G+C;D++;B=f.iq(c.u(),D)}else k.y+=G,k.b-=G,B=null}if(f instanceof a.Fb&&(B=f.iq(c.u()),r=f.iq(c.u(),1),p=0,null!=r))for(y=0;y<r.length;y++)E=r[y],null==E||a.Ca.Pj(E).b-1>k.b||(c.ab().lb(E,new a.yi(null,null,null,
d.n4(h.W7,E.lf()))),u=A=0,w=f.F()._maxOverflowCoord,x=f.F()._minOverflowCoord,null!=B[y]&&(p=B[y].Pc().a/2,A=f.ypa[y],u=f.zpa[y]),0==A&&0==u?(A=E.Va(),E.Fa(v?A+p<=w?A+p:w:A-p>=x?A-p:x)):0>A?E.Fa(x):0<A&&E.Fa(w),E.np(),E.jb(k.y),c.A(E))};k.$eb=function(c,f,k){function r(B,r){var M=B instanceof a.Zb||B instanceof a.em,M=!M||M&&!B.zC();if(!(G&&a.Ca.cA(D).a-1>k.a)&&(G||u||!M||a.Ca.kd(B,k.a,k.b,c))){r=z?f.sM(B):r;var M=f.Qg(r,y),S=B.Uq(),ea=f.Ch(r,y),ia=f.jk(r,y),T=f.bh(r,y);c.ab().lb(B,new b(c,B,T,ea,
ia,S,M,d.n4(h.W7,B.lf(),r,y)));G?(B.Wh(),B.Fa(v?k.a:k.x+C),f.vWa(y)):(B.Fa(E),A||"right"!=w?B.Wh():B.Vh(),u&&(B.Oq(),B.jb(B.ib()-e.Dh(x,p,p.layout.insideLabelGapHeight))),"radial"==w&&(M=B.ib(),B.jb(k.y+k.b/2-M),S=B.aa(),ea=.15*S.b,ea=a.P.VM(S.x-ea,S.y,S.a+2*ea,S.b,2,2,2,2),ea=new a.vb(c.u(),ea),ia=B.Jd().M(a.j.Lb),M=M+S.b/2>f.$Q()&&"circle"==c.F().polarGridShape?1:.3,ia?ea.fb(ia):ea.fb("#FFFFFF",M),c.A(ea)));c.A(B)}}var p=c.F(),w=p.position,x=c.u(),v=a.B.da(x),A=f instanceof a.Fi,u="inside"==p.tickLabel.position,
D,B,C,z=f instanceof a.Ke,G=z&&1<f.pI(),y=G?0:null;D=f.iq(c.u(),y);var E=0;G?(B=e.Dh(x,p,p.layout.hierarchicalLabelGapWidth),C=a.Ca.cA(D).a):"radial"==w?(B=e.Dh(x,p,p.layout.radialLabelGap),E=k.x+k.a/2,E=v?E+(B+a.Ca.cA(D).a):E-B):"left"==w?(E=k.x+k.a,A&&u&&(E+=a.Ca.cA(D).a)):(E=k.x,A&&!u&&(E+=a.Ca.cA(D).a));for(;D;){for(var M=0;M<D.length;M++){var S=D[M];null!=S&&r(S,M)}if(G)k.x+=C+B,k.a-=C+B,y++,C=(D=f.iq(c.u(),y))?a.Ca.cA(D).a:null;else break}if(f instanceof a.Fb&&(B=f.iq(c.u(),1),null!=B))for(M=
0;M<B.length;M++)S=B[M],null!=S&&r(S,M)};k.Zeb=function(c,e,f){for(var k=e.iq(c.u()),p=0;p<k.length;p++){var w=k[p];if(null!=w){var x=f.a/2-Math.abs(w.Va()),v=f.b/2-Math.abs(w.ib());if(a.Ca.kd(w,x,v,c)){var x=e instanceof a.Ke?e.sM(w):p,v=e.Qg(x),A=w.Uq(),u=e.Ch(x),D=e.jk(x),B=e.bh(x);c.ab().lb(w,new b(c,w,B,u,D,A,v,d.n4(h.W7,w.lf(),x)));w.ga(f.x+f.a/2);w.wa(f.y+f.b/2);c.A(w)}}}};k.h9a=function(b,c,d,e,f,h,x,v){v?(d=new a.Zb(c.u(),d,0,0),d.eY(k.dFa),d.$I(f,h,1)):d=new a.ca(c.u(),d,0,0);d.Bb(e);return a.Ca.kd(d,
f,h,c)?(b.lb(d,new a.yi(d.Uq(),null,null,x)),d):null};k.Seb=function(b,c){if(c instanceof a.Ke&&c.r7a&&!(1>=c.pI()||0>=c.Faa))for(var d=b.F(),f=d.position,f="top"==f||"bottom"==f,h=b.u(),w=a.B.da(h),x=new a.ya(c.Vua(),1,1),v=0,h=f?e.Dh(h,d,d.layout.hierarchicalLabelGapHeight):e.Dh(h,d,d.layout.hierarchicalLabelGapWidth),A=d.startGroupOffset,d=d.endGroupOffset,u,D,B,C,z,G=c.Faa;0<=G;G--){var y=c.iq(b.u(),G);u=a.Ca.cA(y);var E=c.ER(G),M=E||!f?u.a:u.b;if(0!=M){var S=!1,O=null;if(G<c.Faa)for(var fa=0;fa<
y.length;fa++){var ga=y[fa];if(null!=ga){var aa=c.sM(ga),ea=0==c.Sda(aa,G).length;if(!ea){var ia=ea&&0==G&&(0==aa||aa==y.length-1),T=ga&&null==y[aa-1],Z=ga&&null==y[aa+1];z=c.eA(aa,G);var W=c.kM(aa,G);if(f){if(ga&&(C=ga instanceof a.Zb||ga instanceof a.em?ga.Eea():ga.ib(),u=c.uj(z-A),D=E?C+.5*v:C-M/2-.5*v-h,B=c.uj(W+d),C=E?C+M+v+2*h:C,ea&&ia||0!=S||null==u||k.iK(b,x,u,C,u,D),null==B||ia||k.iK(b,x,B,C,B,D)),!ea){if(ga)var R=E?a.Ca.qR(ga):a.Ca.yea(ga);u=T&&0==O?c.g4():c.Gm(z-A);S=c.Sda(aa+1,G);B=Z&&
S&&0<S.length?c.$Q():c.Gm(W+d);D=ga?w?ga.Va()+.5*R:ga.Va()-.5*R:c.Gm(W+d);z=ga?w?ga.Va()-.5*R:ga.Va()+.5*R:c.Gm(z-A);ga&&(E?k.iK(b,x,u,C,B,C):(Z=w?.5*-a.Ca.qR(ga):.5*a.Ca.qR(ga),W=w?z+Z>B:z+Z<B,(w?u>D-Z:u<D-Z)&&k.iK(b,x,u,C,D-Z,C),W&&k.iK(b,x,z+Z,C,B,C)))}}else ga&&(u=w?ga.Va()-M-.5*h:ga.Va()+.5*h,D=c.uj(z-A),B=w?ga.Va()+.5*h:ga.Va()-M-.5*h,C=c.uj(W+d),(!ea&&0==S||0==aa&&ea&&0!=G)&&null!=D&&k.iK(b,x,u,D,B,D),null==C||ia||k.iK(b,x,B,C,u,C)),ea||(D=T&&0==O?0:c.Gm(z-A),S=c.Sda(aa+1,G),C=Z&&S&&0<S.length?
c.$Q():c.Gm(W+d),ga&&k.iK(b,x,B,D,B,C));S=!ea&&null!=ga;O=null!=ga||null==ga&&ea}}}}v=M}};k.iK=function(b,c,d,e,h,f){d=new a.Gc(b.u(),d,e,h,f);d.Ga(c);d.md();b.A(d)};k.wJa=function(b,c,d,h,f){var k=b.u(),x=b.F();b=c.pI();for(var x=1<b?e.Dh(k,x,x.layout[f?"hierarchicalLabelGapHeight":"hierarchicalLabelGapWidth"]):0,v=0;v<b;v++){var A=c.iq(k,v);f?(A=a.Ca.cA(A),A=c.ER(v)?A.a:A.b):A=a.Ca.cA(A).a;if(d+A<=h)d+=A+x;else{0==v&&(d=h);break}}0!=v&&(d-=x);return d};k.TTa=function(b,c,d,e){var h=0;c.title&&(k.zC(c.titleStyle)?
(b=new a.Zb(b,c.title,0,0),b.eY(k.dFa),b.Bb(c.titleStyle),b.$I(d,e,1),h=b.aa().b):h=a.Ca.cF(b,c.titleStyle));return h};k.zC=function(b){b=b.M(a.j.n2a);return"nowrap"==b||"noWrap"==b?!1:!0};a.sf=function(){};a.v.D(a.sf,a.v);a.sf.newInstance=function(b,c,d){return c.timeAxisType&&"disabled"!=c.timeAxisType?new a.Fb(b,c,d):c._isGroupAxis?new a.Ke(b,c,d):new a.Fi(b,c,d)};a.sf.prototype.Init=function(b,c,d){this.Aa=b;this.fg=c.position;this.Os=c._radius;this.Vn=null;"top"==this.fg||"bottom"==this.fg?(this.Uj=
d.x,this.ml=d.x+d.a):"left"==this.fg||"right"==this.fg?(this.Uj=d.y,this.ml=d.y+d.b):"radial"==this.fg?(this.Uj=0,this.ml=this.Os):"tangential"==this.fg&&(a.B.da(b)?(this.Uj=2*Math.PI,this.ml=0):(this.Uj=0,this.ml=2*Math.PI));this.as=this.fv=this.ds=this.es=this.Oh=this.ff=null;this.Nw=this.fx=0;null==c.leftBuffer&&(c.leftBuffer=Infinity);null==c.rightBuffer&&(c.rightBuffer=Infinity);this.W=c};a.sf.prototype.u=function(){return this.Aa};a.sf.prototype.F=function(){return this.W};a.sf.prototype.iq=
function(){return null};a.sf.prototype.pC=function(){return this.Vn};a.sf.prototype.Psb=function(a){this.Vn=a};a.sf.prototype.$W=function(){return[]};a.sf.prototype.dX=function(){return[]};a.sf.prototype.Wz=function(){return null};a.sf.prototype.vR=function(a){if(null==a)return null;var b=Math.max(this.Uj,this.ml);return a<Math.min(this.Uj,this.ml)||a>b?null:this.vI(a)};a.sf.prototype.uj=function(a){return null==a?null:a<this.ff||a>this.Oh?null:this.rh(a)};a.sf.prototype.Dda=function(a){if(null==
a)return null;var b=Math.min(this.Uj,this.ml),c=Math.max(this.Uj,this.ml);a<b?a=b:a>c&&(a=c);return this.vI(a)};a.sf.prototype.Gm=function(a){if(null==a)return null;a<this.ff?a=this.ff:a>=this.Oh&&(a=this.Oh);return this.rh(a)};a.sf.prototype.vI=function(){return null};a.sf.prototype.rh=function(){return null};a.sf.prototype.Qg=function(){return null};a.sf.prototype.Ch=function(){return null};a.sf.prototype.jk=function(){return null};a.sf.prototype.Wz=function(){return null};a.sf.prototype.ER=function(){return!1};
a.sf.prototype.UC=function(b,c,d,e,h){if("tangential"==this.fg){h=16/180*Math.PI;var f=1/180*Math.PI,k=.5*this.fy(),v=this.Os+k;if(d<f||d>2*Math.PI-f)v+=k;k=Math.round(v*Math.sin(d));v=Math.round(-v*Math.cos(d));b=e?new a.He(b,c,k,v,e):new a.ca(b,c,k,v);d<f||Math.abs(d-Math.PI)<f||d>2*Math.PI-f?b.Yf():d<Math.PI?b.Vh():b.Wh();Math.abs(d-Math.PI/2)<h||Math.abs(d-3*Math.PI/2)<h?b.Ng():d<Math.PI/2||d>3*Math.PI/2?b.Oq():b.np()}else h?b=e?new a.em(b,c,d,d,e):new a.Zb(b,c,d,d):(b=e?new a.He(b,c,d,d,e):new a.ca(b,
c,d,d),b.Ng()),b.Yf();(b instanceof a.ca||b instanceof a.Zb)&&b.Bb(this.W.tickLabel.style);return b};a.sf.prototype.GN=function(b,c){if(!b||0>=b.length)return!1;for(var d="left"==this.fg||"right"==this.fg||"radial"==this.fg,e=a.B.da(this.u()),h=this.Oha(),f,k,v,A,u=0;u<b.length;u+=c+1)if(null!=b[u])if(null==f||null==k)d?(f=b[u].y,k=b[u].y+b[u].b):(f=b[u].x,k=b[u].x+b[u].a);else{if(d){if(v=b[u].y,A=b[u].y+b[u].b,v>=f&&v-h<k||v<f&&A+h>f)return!0}else if(v=b[u].x,A=b[u].x+b[u].a,!e&&v-h<k||e&&A+h>f)return!0;
f=v;k=A}return!1};a.sf.prototype.wBa=function(a,b){if(!a||!b)return!1;var c=a.y,d=a.y+a.b,e=a.x,h=a.x+a.a,f=b.y,k=b.y+b.b,A=b.x,u=b.x+b.a;return(e<=A&&A<=h||e<=u&&u<=h||A<=e&&e<=u||A<=h&&h<=u)&&(f>=c&&f<d||f<=c&&k>=c)};a.sf.prototype.Oha=function(){var b=this.fy(),c=this instanceof a.Ke?.24*b:.79*b,b=this instanceof a.Ke?.08*b:.28*b;return"left"==this.fg||"right"==this.fg||"radial"==this.fg||this.ER()?b:c};a.sf.prototype.fy=function(){return a.Ca.cF(this.u(),this.W.tickLabel.style)};a.sf.prototype.T7=
function(a,b){for(var c=0,d=this.GN(b,c);d;)c++,d=this.GN(b,c);if(0<c){for(var d=[],e=0;e<a.length;e+=c+1)d.push(a[e]);return d}return a};a.sf.prototype.I1a=function(a,b){var c=[],d=a.length,e=null;if(1<d){for(var h,f=0;f<d;f++)b[f]&&(!h||h&&!this.wBa(h,b[f]))&&(e||(e=b[f]),c.push(a[f]),h=b[f]);this.wBa(h,e)&&c.pop();return c}return a};a.sf.prototype.MS=function(a,b){for(var c=[],d=0;d<a.length;d++){var e=a[d];null==e?c.push(null):(e=e.Pc(b),e.a&&e.b?c.push(e):c.push(null))}return c};a.sf.prototype.dZ=
function(b,c,d,e){var f=[];"undefined"==typeof d&&(d=1);for(var h=0;h<b.length;h++){var k=b[h];if(null==k)f.push(null);else{c.A(k);var v=a.Ca.Pj(k),A=v.a*d,v=v.b;c.removeChild(k);k=this.ER(e)?new a.Z(k.qa()-v/2,k.pa()-A/2,v,A):new a.Z(k.Va()-A/2,k.ib()-v/2,A,v);f.push(k)}}return f};a.sf.prototype.XSa=function(){return null};a.sf.prototype.gTa=function(){return null};a.sf.prototype.WSa=function(){return null};a.sf.prototype.cX=function(){return 0};a.sf.prototype.g4=function(){return this.Uj};a.sf.prototype.$Q=
function(){return this.ml};a.sf.prototype.h4=function(){return this.fx};a.sf.prototype.y3=function(){return this.Nw};a.sf.prototype.lI=function(){return 0};a.sf.prototype.bh=function(){return null};a.sf.prototype.Ou=function(a){return a};a.sf.prototype.dn=function(a){return a};a.Fi=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Fi,a.sf);a.Fi.M4a=10;a.Fi.P4a=2;a.Fi.O4a=64;a.Fi.prototype.Init=function(b,c,d){a.Fi.C.Init.call(this,b,c,d);"top"==this.fg||"bottom"==this.fg?("off"!=c.tickLabel.rendered&&"off"!=
c.rendered&&(this.fx=Math.max(a.Rj.WS-c.leftBuffer,0),this.Nw=Math.max(a.Rj.WS-c.rightBuffer,0)),a.B.da(b)?(this.mL=this.ml-this.Nw,this.rV=this.Uj+this.fx):(this.mL=this.Uj+this.fx,this.rV=this.ml-this.Nw)):"tangential"==this.fg||"radial"==this.fg?(this.mL=this.Uj,this.rV=this.ml):(this.mL=this.ml,this.rV=this.Uj);this.fv=c.dataMin;this.as=c.dataMax;this.eL="log"==c.scale&&0<this.fv&&0<this.as;this.pi=this.dn(c.min);this.fj=this.dn(c.max);this.Sn=null==c.viewportMin?this.pi:this.dn(c.viewportMin);
this.Ao=null==c.viewportMax?this.fj:this.dn(c.viewportMax);this.Gv=this.dn(this.fv);this.cu=this.dn(this.as);this.Tp=this.dn(c.step);this.vV=this.dn(c.minorStep);this.Hcb=this.dn(c.minStep);this.Dz=c._majorTickCount;this.e1=c._minorTickCount;this.sW=!this.eL&&"zero"==c.baselineScaling;this.Mp=null;null!=c.tickLabel&&(this.Mp=c.tickLabel.converter);this.X7a();this.es=this.Ou(this.pi);this.ds=this.Ou(this.fj);this.ff=this.Ou(this.Sn);this.Oh=this.Ou(this.Ao)};a.Fi.prototype.O3=function(){return this.sW||
"on"==this.W._continuousExtent&&null==this.W.min?Math.ceil(this.Sn/this.Tp)*this.Tp:Math.ceil((this.Sn-this.pi)/this.Tp)*this.Tp+this.pi};a.Fi.prototype.iq=function(b,c){if(c&&0<c)return null;var d=[],e=[],e=b.Oe;if(this.W.tickLabel&&this.W.tickLabel.scaling){var f=this.W.tickLabel.autoPrecision?this.W.tickLabel.autoPrecision:"on";this.h_=new a.Sj(b,this.Sn,this.Ao,this.Tp,this.W.tickLabel.scaling,f)}for(var h=0;h<=this.Dz;h++){var k=h*this.Tp+this.O3();if(k>this.Ao)break;var v=this.u0(k);if(this.W._skipHighestTick){if(k==
this.Ao)continue;if("tangential"!=this.fg&&Math.abs(v-this.rV)<this.fy())continue}this.eL&&(k=this.Ou(k),this.h_=new a.Sj(b,k,k,k,this.W.tickLabel.scaling,f));k=this.k$a(k);v=this.UC(b,k,v);d.push(v)}"tangential"!=this.fg&&(e=this.MS(d,e),d=this.T7(d,e));return d};a.Fi.prototype.$W=function(){for(var a=[],b=0;b<=this.Dz;b++){var c=b*this.Tp+this.O3();if(c>this.Ao)break;this.W._skipHighestTick&&c==this.Ao||a.push(this.u0(c))}return a};a.Fi.prototype.dX=function(){for(var b=[],c=-1;c<=this.Dz;c++){var d=
c*this.Tp+this.O3();if(this.eL&&1==this.Tp&&1==this.vV)for(var e=2;9>=e;e++){var h=d+a.Math.log10(e);if(h>this.Ao)break;h<this.Sn||(h=this.u0(h),b.push(h))}else for(e=1;e<this.e1;e++){h=d+e*this.vV;if(h>this.Ao)break;h<this.Sn||(h=this.u0(h),b.push(h))}}return b};a.Fi.prototype.Wz=function(){return this.eL?this.mL:this.Gm(0)};a.Fi.prototype.vI=function(a){return null==a?null:this.Ou(this.Sn+(a-this.mL)/(this.rV-this.mL)*(this.Ao-this.Sn))};a.Fi.prototype.rh=function(a){return this.u0(this.dn(a))};
a.Fi.prototype.u0=function(a){return null==a?null:this.mL+(a-this.Sn)/(this.Ao-this.Sn)*(this.rV-this.mL)};a.Fi.prototype.k$a=function(b){if(this.Mp&&(this.Mp.getAsString||this.Mp.format)){if(this.h_)return this.h_.format(b,this.Mp);if(this.Mp.getAsString)return this.Mp.getAsString(b);if(this.Mp.format)return this.Mp.format(b)}else return this.h_?this.h_.format(b):b.toFixed(Math.max(Math.ceil(-a.Math.log10(this.Tp)),0))};a.Fi.prototype.b8a=function(b){this.Tp||(this.Tp=this.Dz?(this.Ao-this.Sn)/this.Dz:
Math.max(b,this.Hcb));this.Dz||(this.Dz=(this.Ao-this.Sn)/this.Tp);this.e1||(this.e1=this.vV?this.Tp/this.vV:this.eL?this.Tp:a.Fi.P4a);this.vV||(this.vV=this.Tp/this.e1)};a.Fi.prototype.X7a=function(){var b="on"==this.W._continuousExtent;this.sW&&(this.Gv=Math.min(0,this.Gv),this.cu=Math.max(0,this.cu));var c=this.UGa(null!=this.pi?this.pi:this.Gv,null!=this.fj?this.fj:this.cu);this.Gv==this.cu&&(0==this.Gv?this.cu+=5*c:(this.Gv-=2*c,this.cu+=2*c));if(null==this.pi){if(this.sW&&0<=this.Gv)this.pi=
0;else if(b)this.pi=this.Gv-.1*(this.cu-this.Gv);else if(this.sW||null==this.fj)this.pi=(Math.ceil(this.Gv/c)-1)*c;else for(this.pi=this.fj;this.pi>=this.Gv;)this.pi-=c;0<=this.Gv&&(this.pi=Math.max(this.pi,0))}if(null==this.fj){if(this.Dz)this.fj=this.pi+this.Dz*c;else if(this.sW&&0>=this.cu)this.fj=0;else if(b)this.fj=this.cu+.1*(this.cu-this.Gv);else if(this.sW)this.fj=(Math.floor(this.cu/c)+1)*c;else for(this.fj=this.pi;this.fj<=this.cu;)this.fj+=c;0>=this.cu&&(this.fj=Math.min(this.fj,0))}this.fj==
this.pi&&(this.fj=100,this.pi=0,c=(this.fj-this.pi)/a.Fi.M4a);null==this.Sn&&(this.Sn=this.pi);null==this.Ao&&(this.Ao=this.fj);if(this.Sn!=this.pi||this.Ao!=this.fj)c=this.UGa(this.Sn,this.Ao);this.pi>this.Sn&&(this.pi=this.Sn);this.fj<this.Ao&&(this.fj=this.Ao);this.b8a(c)};a.Fi.prototype.UGa=function(b,c){if(this.Tp)return this.Tp;var d=c-b;if(this.eL)return Math.floor(d/8)+1;if(0==d)return 0==b?10:Math.pow(10,Math.floor(a.Math.log10(b))-1);if(this.Dz){var d=d/this.Dz,e=Math.pow(10,Math.ceil(a.Math.log10(d)-
1)),d=d/e,d=1<d&&1.5>=d?1.5:5<d?10:Math.ceil(d);return d*e}e=Math.pow(10,Math.ceil(a.Math.log10(d))-2);d=Math.round(d/e);return(10<=d&&14>=d?2:15<=d&&19>=d?3:20<=d&&24>=d?4:25<=d&&45>=d?5:46<=d&&80>=d?10:20)*e};a.Fi.prototype.XSa=function(){return this.Dz};a.Fi.prototype.gTa=function(){return this.e1};a.Fi.prototype.WSa=function(){return this.Ou(this.Tp)};a.Fi.prototype.cX=function(){return(this.fj-this.pi)/a.Fi.O4a};a.Fi.prototype.h4=function(){return"top"!=this.fg&&"bottom"!=this.fg||!a.B.da(this.u())?
this.fx:this.Nw};a.Fi.prototype.y3=function(){return"top"!=this.fg&&"bottom"!=this.fg||!a.B.da(this.u())?this.Nw:this.fx};a.Fi.prototype.Ou=function(a){return null==a?null:this.eL?Math.pow(10,a):a};a.Fi.prototype.dn=function(b){return null==b?null:this.eL?0<b?a.Math.log10(b):null:b};a.Ke=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Ke,a.sf);a.Ke.cFa=3;a.Ke.qFa=12;a.Ke.prototype.Init=function(b,c,d){a.Ke.C.Init.call(this,b,c,d);var h=a.B.da(b),f="top"==this.fg||"bottom"==this.fg;if(f&&h){var w=this.Uj;
this.Uj=this.ml;this.ml=w}this.Zk=[];this.w0=this.WIa(c.groups,0,this.Zk,0);this.Lq=this.Zk.length;this.r7a="on"==c.groupSeparators.rendered;this.Hfb=c.groupSeparators.color;this.Faa=null;this.UO=c.drilling;var w=0<c.endGroupOffset?Number(c.endGroupOffset):0,x=0<c.startGroupOffset?Number(c.startGroupOffset):0;this.fv=0;this.as=this.w0-1;this.es=null==c.min?this.fv-x:c.min;this.ds=null==c.max?this.as+w:c.max;var v=this.ik(c.viewportStartGroup),A=this.ik(c.viewportEndGroup);-1!=v&&(this.ff=v-x);-1!=
A&&(this.Oh=A+w);null!=c.viewportMin&&(this.ff=c.viewportMin);null!=c.viewportMax&&(this.Oh=c.viewportMax);null==this.ff&&(this.ff=this.es);null==this.Oh&&(this.Oh=this.ds);this.es>this.ff&&(this.es=this.ff);this.ds<this.Oh&&(this.ds=this.Oh);this.UK=c._groupWidthRatios;this.HNa();this.ePa=h?c.rightBuffer:c.leftBuffer;this.wIa=h?c.leftBuffer:c.rightBuffer;this.dpa=[];for(h=0;h<this.Lq;h++)this.dpa.push(!1);this.eOa=c._renderGridAtLabels;this.Rn=null;this.tH=f?d.b:d.a;"off"!=c.rendered&&(d=k.TTa(b,
c,f?d.a:d.b,f?d.b:d.a),this.tH-=0!=d?d+e.Dh(b,c,c.layout.titleGap):0);this.tV=a.Ke.cFa};a.Ke.prototype.HNa=function(){if(!this.UK||2>this.UK.length)this.UK=null;else{for(var b=0,c,d,e=0;e<this.w0;e++)c=0==e?this.ff:Math.max(e-.5,this.ff),d=e==this.w0-1?this.Oh:Math.min(e+.5,this.Oh),d>c&&(b+=(d-c)*this.UK[e]);var h=this.ml-this.Uj;this.fP=a.na.map(this.UK,function(a){return a*h/b});this.gB=[];for(e=0;e<this.UK.length-1;e++)this.gB.push(e+.5);this.az=[];c=Math.min(Math.max(Math.round(this.ff),0),this.gB.length-
1);this.az[c]=this.Uj+(this.gB[c]-this.ff)*this.fP[c];for(e=c+1;e<this.gB.length;e++)this.az[e]=this.az[e-1]+this.fP[e];for(e=c-1;0<=e;e--)this.az[e]=this.az[e+1]-this.fP[e+1]}};a.Ke.prototype.wra=function(b,c,d,e){var h,f=this.u(),x=a.B.da(f),v=1<this.Lq;null==e&&(e=this.Lq-1);this.dpa[e]=!0;v||this.o2(d,d,b);for(var A=0;A<b.length;A++)if(d=b[A],null!=d){h=d.Va();if(d instanceof a.Zb||d instanceof a.em){var u=this.lI()*(this.kM(A,e)-this.eA(A,e)+1);2*d.UE()<u?d.$I(this.tH,d.UE()*a.Ke.cFa,1):d.gga(!1)}d.Fa(0);
d.jb(0);x?d.zp(Math.PI/2):d.zp(3*Math.PI/2);d.ga(h)}x=this.dZ(b,c,null,e);k.zC(this.W.tickLabel.style)&&this.yOa(f,x,b,!0,v)&&(x=this.dZ(b,c,null,e));return this.T7(b,x)};a.Ke.prototype.yOa=function(b,c,d,h,f){c=this.j8a(c,d,h);for(var k=0,x=0;x<d.length;x++){var v=d[x];if(v){var A=v instanceof a.Zb||v instanceof a.em;c&&A&&v.zC()&&v.$I(this.tH,v.UE()*this.tV,1);f&&(k=Math.max(k,a.Ca.yea(v)));v.Ng()}}f&&(this.tH-=k+e.Dh(b,this.W,h?this.W.layout.hierarchicalLabelGapHeight:this.W.layout.hierarchicalLabelGapWidth));
return c};a.Ke.prototype.j8a=function(b,c,d){for(var e=!1;this.GN(b,0)&&1<this.tV;){for(var e=!0,h=0;h<c.length;h++){var f=c[h];(f instanceof a.Zb||f instanceof a.em)&&f.XW()==this.tV&&(f=f.UE(),d?b[h].a-=f:(b[h].y+=.5*f,b[h].b-=f))}this.tV--}return e};a.Ke.prototype.ER=function(a){null==a&&(a=this.Lq-1);return this.dpa[a]};a.Ke.prototype.o2=function(b,c,d){b=Math.max(b-this.ePa,0);c=Math.max(c-this.wIa,0);d=a.B.da(this.u());this.Uj+=(b-this.fx)*(d?-1:1);this.ml-=(c-this.Nw)*(d?-1:1);this.HNa();for(var e=
0;e<this.Lq;e++){d=this.Rn[e];for(var h=0;h<d.length;h++){var f=d[h];if(f){var k=this.GJa(e,this.sM(f));f.Fa(k)}}}this.fx=b;this.Nw=c};a.Ke.prototype.iq=function(a,b){null==b&&(b=this.Lq-1);this.Rn||this.Fna(a);return this.Rn[b]};a.Ke.prototype.GJa=function(a,b){var c=this.eA(b,a),d=this.kM(b,a);if(null==c||null==d)return null;c<this.ff&&d>this.ff&&(c=this.ff);d>this.Oh&&c<this.Oh&&(d=this.Oh);return this.uj(d?c+(d-c)/2:c)};a.Ke.prototype.Fna=function(b){var c=[];this.Rn=[];for(var d=b.Oe,h="top"==
this.fg||"bottom"==this.fg,f=a.B.da(b),w=1<this.Lq,x=this.lI(),v=this.tH,A=w?e.Dh(b,this.W,this.W.layout[h?"hierarchicalLabelGapHeight":"hierarchicalLabelGapWidth"]):0,u="auto"==this.W.tickLabel.rotation&&h,D=!w&&u&&x<a.Ke.qFa,B=this.W.tickLabel.style,B=k.zC(this.W.tickLabel.style)&&"tangential"!=this.fg&&x>a.Ca.cF(b,B),C,z,G,y,E,M=0;M<this.Lq;M++){for(var S=this.Zk[M],O=D?Math.max(1,Math.floor(a.Ke.qFa/(2*Math.max(1,x)))):1,fa=0;fa<S.length;fa+=O)if(S[fa])if(C=this.Sda(fa,M),""==C||!C&&0!=C)c.push(null);
else if(E=this.GJa(M,fa),null!=E){y=this.ylb(fa,M);var ga=!D&&B&&"number"!=typeof C&&0<=C.indexOf(" ");E=this.UC(b,C,E,y,ga);var aa=x*(this.kM(fa,M)-this.eA(fa,M)+1);ga&&this.jcb(b,C,y,u,h?aa:v)?h?E.$I(aa,v,1,!0):E.$I(v,E.UE()*this.tV,1,!1):ga&&!h&&E.gga(!1);E.fp=fa;c.push(E);z||0!=M||(z=E);0==M&&(G=E)}else c.push(null);else c.push(null);if(B&&w){for(C=y=0;C<c.length;C++)c[C]&&(S=c[C].Pc(),y=Math.max(y,h?S.b:S.a));v-=y+A}this.Rn.push(c);c=[]}c=this.Rn[this.Lq-1];x=[];if(z)if("tangential"==this.fg)x=
this.MS(c,d),this.Rn[0]=this.I1a(c,x);else for(z=z.Pc(),h&&(null!=this.W._startOverflow&&null!=this.W._endOverflow?(M=this.W._startOverflow,f=this.W._endOverflow):(G=G.Pc(),M=f?z.a+z.x-this.Uj:this.Uj-z.x,f=f?this.ml-G.x:G.a+G.x-this.ml),!D&&(M>this.ePa||f>this.wIa)&&this.o2(M,f,c)),M=0;M<this.Lq;M++)if(c=this.Rn[M],D)this.Rn[M]=this.wra(c,d,z.b/2,M);else if(f=this.dZ(c,d,.3,M),G=this.dZ(c,d,null,M),this.GN(G,0)||(this.Rn[M]=c),h)if(u)if(this.GN(f,0))this.Rn[M]=this.wra(c,d,z.b/2,M);else if(x=this.MS(c,
d),this.GN(x,0))this.Rn[M]=this.wra(c,d,z.b/2,M);else{if(this.Rn[M]=c,w){for(C=c=0;C<x.length;C++)x[C]&&(c=Math.max(c,x[C].b));this.tH-=c+A}}else x=this.MS(c,d),this.Rn[M]=this.T7(c,x);else B&&this.yOa(b,G,c,!1,w)&&(G=this.dZ(c,d,null,M)),this.Rn[M]=this.T7(c,G)};a.Ke.prototype.$W=function(){for(var a=[],b,c="tangential"==this.fg?this.kg():this.kg()-1,d=0;d<this.Zk[0].length;d++)if(this.Zk[0][d]){b=this.eA(d,0);var e=this.kM(d,0);b=this.eOa?this.uj(b+.5*(e-b)):e+.5<c?this.uj(e+.5):null;null!=b&&a.push(b)}return a};
a.Ke.prototype.dX=function(){var a=[],b;if(!this.Zk[1])return a;for(var c=0;c<this.Zk[1].length;c++)if(this.Zk[1][c]){b=this.eA(c,1);var d=this.kM(c,1);b=this.eOa?this.uj(b+.5*(d-b)):d+.5<this.kg()-1?this.uj(d+.5):null;null!=b&&a.push(b)}return a};a.Ke.prototype.vI=function(a){if(null==a)return null;if(this.UK){for(var b=this.az.length,c=0;c<this.az.length;c++)if(a<=this.az[c]){b=c;break}return 0==b?this.gB[0]-(this.az[0]-a)/this.fP[0]:this.gB[b-1]+(a-this.az[b-1])/this.fP[b]}return this.ff+(a-this.Uj)/
((this.ml-this.Uj)/(this.Oh-this.ff))};a.Ke.prototype.rh=function(a){if(null==a)return null;if(this.UK){for(var b=this.gB.length,c=0;c<this.gB.length;c++)if(a<=this.gB[c]){b=c;break}return 0==b?this.az[0]-this.fP[0]*(this.gB[0]-a):this.az[b-1]+this.fP[b]*(a-this.gB[b-1])}return this.Uj+(this.ml-this.Uj)/(this.Oh-this.ff)*(a-this.ff)};a.Ke.prototype.Sda=function(a,b){null==b&&(b=this.Lq-1);a=Math.round(a);if(0>a)return null;var c=this.Zk[b]&&this.Zk[b][a]?this.Zk[b][a].item:null;c&&(c.name?c=c.name:
null!=c.id&&(c=""));return c};a.Ke.prototype.dlb=function(a,b){null==b&&(b=this.Lq-1);a=Math.round(a);if(0>a)return null;var c=this.Zk[b]&&this.Zk[b][a]?this.Zk[b][a].item:null;if(c){if(c.id)return c.id;if(c.name||""==c.name)return c.name}return c};a.Ke.prototype.ylb=function(b,c){var d=this.O$(b,c,"labelStyle");return d?(d=new a.j(d),d.M("font-size")||d.fa("font-size",this.W.tickLabel.style.M("font-size")),d):null};a.Ke.prototype.Qg=function(a,b){return this.O$(a,b,"shortDesc")};a.Ke.prototype.Ch=
function(a,b){return this.O$(a,b,"action")};a.Ke.prototype.jk=function(a,b){var c=this.O$(a,b,"drilling");return"on"==c?!0:"off"==c?!1:"on"==this.UO||"groupsOnly"==this.UO};a.Ke.prototype.bh=function(a,b){if(0>a||a>this.kg()-1)return null;var c=[];null==b&&(b=this.Lq-1);for(var d=this.eA(a,b),e=0;e<=b;e++)for(var h=this.Zk[e],f=0;f<h.length;f++)this.eA(f,e)<=d&&this.kM(f,e)>=d&&c.push(this.dlb(f,e));return 0<c.length?1==c.length?c[0]:c:null};a.Ke.prototype.ik=function(b){if(null==b)return-1;for(var c=
-1,d=0;d<this.w0;d++){var e=this.bh(d);if(b instanceof Array&&e instanceof Array?a.na.Fe(b,e):b==e){c=d;break}}return c};a.Ke.prototype.cX=function(){return 1};a.Ke.prototype.lI=function(){return Math.abs(this.ml-this.Uj)/Math.abs(this.Oh-this.ff)};a.Ke.prototype.kg=function(){return this.w0};a.Ke.prototype.pI=function(){return this.Lq};a.Ke.prototype.WIa=function(a,b,c,d){for(var e=0;e<a.length;e++)if(c[b]||(c[b]=[]),c[b].push({item:a[e],start:d,end:d,position:e}),a[e]&&a[e].groups){d=c[b].length-
1;var h=this.WIa(a[e].groups,b+1,c,c[b][d].start);c[b][d].end=h-1;d=h}else d++;return d};a.Ke.prototype.O$=function(a,b,c){null==b&&(b=this.Lq-1);return(a=this.Zk[b]&&this.Zk[b][a]?this.Zk[b][a].item:null)?a[c]:null};a.Ke.prototype.Vua=function(){return this.Hfb};a.Ke.prototype.eA=function(a,b){null==b&&(b=this.Lq-1);return this.Zk[b]&&this.Zk[b][a]?this.Zk[b][a].start:null};a.Ke.prototype.kM=function(a,b){null==b&&(b=this.Lq-1);return this.Zk[b]&&this.Zk[b][a]?this.Zk[b][a].end:null};a.Ke.prototype.ui=
function(a,b){null==b&&(b=this.Lq-1);return this.Zk[b]&&this.Zk[b][a]?this.Zk[b][a].position:null};a.Ke.prototype.vWa=function(a){this.Faa=a};a.Ke.prototype.sM=function(a){return 0<=a.fp?a.fp:null};a.Ke.prototype.jcb=function(b,c,d,e,h){b=a.Ca.xea(b,c,d);return b>=h&&(b/this.tV<h||!e)?!0:!1};a.v.D(b,a.yi);b.prototype.Init=function(a,c,d,e,h,f,k,v){b.C.Init.call(this,f,k,null,v);this.yg=a;this.Ec=c;this.v0=d;this.Vt=e;this.Iv=h;(this.Vt||this.Iv)&&c.setCursor("pointer");a.ela(this)};b.prototype.ge=
function(){return this.Ec};b.prototype.getId=function(){return this.v0};b.prototype.Ch=function(){return this.Vt};b.prototype.jk=function(){return this.Iv};b.prototype.bh=function(){return this.v0};b.prototype.Fd=function(b){return b.type==a.MouseEvent.Be?this:a.Cb.Fd(this,b,this.yg.Gx)};b.prototype.rf=function(b){return this.Ec?this.Ec.aa(b):new a.Z(0,0,0,0)};b.prototype.Sa=function(){return this.Ec};b.prototype.Jm=function(){return this.Ec?this.Ec.Ua():null};b.prototype.Sf=function(){this.dd=!0;
if(this.Ec){var b=this.rf();this.J1=new a.Rect(this.yg.u(),b.x,b.y,b.a,b.b);this.J1.Vb(a.B.bua());this.J1.Wb();this.yg.A(this.J1)}};b.prototype.Qd=function(){this.dd=!1;this.Ec&&(this.yg.removeChild(this.J1),this.J1=null)};b.prototype.Kd=function(){return this.dd};b.prototype.Ed=function(){var b;this.jk()&&(b=[a.H.Bf(this.yg.F(),"stateDrillable",a.H.Ha,"STATE_DRILLABLE")]);if(null!=this.Qg())return a.oa.Ik(this.Qg(),b);if(null!=b)return a.oa.Ik(this.ge().lf(),b)};b.prototype.Zl=function(){return!0};
b.prototype.Im=function(){return[this.getId()]};b.prototype.Zs=function(){return[this.Sa()]};a.Sj=function(a,b,c,d,e,h){this.Init(a,b,c,d,e,h)};a.v.D(a.Sj,a.v);a.Sj.j1a="none";a.Sj.g1a="auto";a.Sj.l1a="thousand";a.Sj.i1a="million";a.Sj.h1a="billion";a.Sj.m1a="trillion";a.Sj.k1a="quadrillion";a.Sj.n1a=3;a.Sj.prototype.Init=function(a,b,c,d,e,h){this.Aa=a;this.AOa={};this.RB=[];this.EIa={};this.x_a();this.w_a(b,c,d,e,h)};a.Sj.prototype.x_a=function(){function b(c,d,e){var h;e&&(h=a.H.va(a.H.Ha,e));
e={HC:d,$ob:h};this.AOa[c]=e;this.RB.push(e);this.EIa[d]=e}var c=a.Sj.n1a;b.call(this,a.Sj.j1a,0*c);b.call(this,a.Sj.l1a,1*c,"SCALING_SUFFIX_THOUSAND");b.call(this,a.Sj.i1a,2*c,"SCALING_SUFFIX_MILLION");b.call(this,a.Sj.h1a,3*c,"SCALING_SUFFIX_BILLION");b.call(this,a.Sj.m1a,4*c,"SCALING_SUFFIX_TRILLION");b.call(this,a.Sj.k1a,5*c,"SCALING_SUFFIX_QUADRILLION");this.RB.sort(function(a,b){return a.HC<b.HC?-1:a.HC>b.HC?1:0})};a.Sj.prototype.w_a=function(a,b,c,d,e){var h=!1,f,k=!1;"off"!==e&&(k=!0);d=this.Lab(d);
"number"!==typeof d&&(h=!0);h&&(d=this.Z9a(this.eoa(Math.max(Math.abs(a),Math.abs(b)))));!0===k&&(0==c&&a==b?(a=d-this.eoa(b),f=0>=a?Math.max(a+3,0):Math.max(a,4)):f=Math.max(d-this.eoa(c),0));this.Fgb=k;this.Cra=d;this.R_=f};a.Sj.prototype.Z9a=function(a){var b=0;if(a<=this.RB[0].HC)b=this.RB[0].HC;else if(a>=this.RB[this.RB.length-1].HC)b=this.RB[this.RB.length-1].HC;else for(var c=this.RB.length-1;0<=c;c--)if(this.RB[c].HC<=a){b=this.RB[c].HC;break}return b};a.Sj.prototype.Lab=function(b){b||(b=
a.Sj.g1a);var c;if(b=this.AOa[b])c=b.HC;return c};a.Sj.prototype.format=function(a,b){var c=parseFloat(a);if(isNaN(c))return a;var d;if(0<this.Cra){for(d=0;d<this.Cra;d++)c/=10;d=this.EIa[this.Cra].$ob}if(b&&b.getAsString)c=b.getAsString(c);else if(b&&b.format)c=b.format(c);else{var e=this.Aa.qTa({minimumFractionDigits:this.R_,maximumFractionDigits:this.R_});e&&e.format?c=e.format(c):this.Fgb&&!isNaN(parseFloat(c))&&(c=parseFloat((new Number(c)).toFixed(this.R_)),c=this.g$a(c))}"string"===typeof d&&
0!=a&&(c+=d);return c};a.Sj.prototype.g$a=function(b){b=b.toString();if(-1!=b.indexOf("e"))return b;var c=".",c=a.H.va(a.H.Ha,"NUMBER_FORMAT_DECIMAL_SEPARATOR");if(0<this.R_)for(b=-1==b.indexOf(".")?b+c:b.replace(".",c),c=b.substring(b.indexOf(c)+1).length;c<this.R_;)b+="0",c++;return b};a.Sj.prototype.eoa=function(a){a=0<=a?a:-a;var b=0;if(1E-15>a)return 0;if(Infinity==a)return Number.MAX_VALUE;if(10<=a)for(;10<=a;)b+=1,a/=10;else if(1>a)for(;1>a;)--b,a*=10;return b};a.Fb=function(a,b,c){this.Init(a,
b,c)};a.v.D(a.Fb,a.sf);a.Fb.MZ=1E3;a.Fb.kD=60*a.Fb.MZ;a.Fb.$N=60*a.Fb.kD;a.Fb.jD=24*a.Fb.$N;a.Fb.oT=28*a.Fb.jD;a.Fb.R1a=31*a.Fb.jD;a.Fb.NZ=365*a.Fb.jD;a.Fb.S1a=366*a.Fb.jD;a.Fb.prototype.Init=function(b,c,d){a.Fb.C.Init.call(this,b,c,d);"top"==this.fg||"bottom"==this.fg?(c._isOverview||"on"!=c.tickLabel.rendered||(this.fx=Math.max(a.Rj.WS-c.leftBuffer,0),this.Nw=Math.max(a.Rj.WS-c.rightBuffer,0)),a.B.da(b)?(this.YB=this.ml-this.Nw,this.tm=this.Uj+this.fx):(this.YB=this.Uj+this.fx,this.tm=this.ml-
this.Nw)):(this.YB=this.Uj,this.tm=this.ml);this.opa=(d=null!=c.tickLabel?c.tickLabel.converter:null)&&d[0]?d[0]:d;this.ppa=d&&d[1]?d[1]:null;this.pB=b.L3().dateToIsoConverter;this.vm=c.groups;b=c.timeAxisType;this.xQ="skipGaps"==b;this.bMa="mixedFrequency"==b;this.fv=c.dataMin;this.as=c.dataMax;this.AD=1<this.vm.length?(this.as-this.fv)/(this.vm.length-1):0<this.as-this.fv?this.as-this.fv:6*a.Fb.kD;this.Mx=c.step;b=0<c.endGroupOffset?c.endGroupOffset*this.AD:0;d=0<c.startGroupOffset?c.startGroupOffset*
this.AD:0;this.es=null!=c.min?c.min:this.fv-d;this.ds=null!=c.max?c.max:this.as+b;null!=c.viewportStartGroup&&(this.ff=c.viewportStartGroup-d);null!=c.viewportEndGroup&&(this.Oh=c.viewportEndGroup+b);null!=c.viewportMin&&(this.ff=c.viewportMin);null!=c.viewportMax&&(this.Oh=c.viewportMax);null==this.ff&&(this.ff=this.es);null==this.Oh&&(this.Oh=this.ds);this.es>this.ff&&(this.es=this.ff);this.ds<this.Oh&&(this.ds=this.Oh);this.Us=this.Oh-this.ff;this.Jaa=this.rP=this.vLa=this.P0=null;this.epa=!0;
this.ypa=[];this.zpa=[];this.iL=c._locale.toLowerCase();this.Ypa=[a.H.va(a.H.Ha,"MONTH_SHORT_JANUARY"),a.H.va(a.H.Ha,"MONTH_SHORT_FEBRUARY"),a.H.va(a.H.Ha,"MONTH_SHORT_MARCH"),a.H.va(a.H.Ha,"MONTH_SHORT_APRIL"),a.H.va(a.H.Ha,"MONTH_SHORT_MAY"),a.H.va(a.H.Ha,"MONTH_SHORT_JUNE"),a.H.va(a.H.Ha,"MONTH_SHORT_JULY"),a.H.va(a.H.Ha,"MONTH_SHORT_AUGUST"),a.H.va(a.H.Ha,"MONTH_SHORT_SEPTEMBER"),a.H.va(a.H.Ha,"MONTH_SHORT_OCTOBER"),a.H.va(a.H.Ha,"MONTH_SHORT_NOVEMBER"),a.H.va(a.H.Ha,"MONTH_SHORT_DECEMBER")]};
a.Fb.q$a=function(a){if("en-au"==a||"en-ie"==a||"en-ph"==a)return"am";if("en-gb"==a)return"";switch(a.substring(0,2)){case "en":return"AM";case "ar":return"\u0635";case "el":return"\u03c0\u03bc";case "ko":return"\uc624\uc804";case "zh":return"\u4e0a\u5348";default:return""}};a.Fb.Bab=function(a){if("en-au"==a||"en-ie"==a||"en-ph"==a)return"pm";if("en-gb"==a)return"";switch(a.substring(0,2)){case "en":return"PM";case "ar":return"\u0645";case "el":return"\u03bc\u03bc";case "ko":return"\uc624\ud6c4";
case "zh":return"\u4e0b\u5348";default:return""}};a.Fb.p$a=function(a){a=a.substring(0,2);return"ko"==a||"zh"==a?!0:!1};a.Fb.nJa=function(a){var b=a.substring(0,2);return"en-us"==a||"en-ph"==a?"MDY":"fa"==b||"hu"==b||"ja"==b||"ko"==b||"lt"==b||"mn"==b||"zh"==b?"YMD":"DMY"};a.Fb.Zab=function(a){return 0==a.indexOf("ja")||0==a.indexOf("zh")?"\u5e74":0==a.indexOf("ko")?"\ub144":""};a.Fb.K$a=function(a){return 0==a.indexOf("ja")||0==a.indexOf("zh")?"\u65e5":0==a.indexOf("ko")?"\uc77c":""};a.Fb.prototype.Fjb=
function(b){b=this.Cna(new Date(b),null,!0);return null!=b[1]?"YMD"==a.Fb.nJa(this.iL)||this.Us<a.Fb.oT&&this.Mx<a.Fb.jD?b[1]+" "+b[0]:b[0]+" "+b[1]:b[0]};a.Fb.prototype.RIa=function(a,b,c){if(c){var d=null,e=null;c.getAsString?(d=c.getAsString(a),e=c.getAsString(b)):c.format&&(d=c.format(this.pB?this.pB(a):a),e=c.format(this.pB?this.pB(b):b));if(e!=d)return d}return null};a.Fb.prototype.Cna=function(b,c,d){var e=null,h=null,f="left"==this.fg||"right"==this.fg;if(this.opa||this.ppa)return this.opa&&
(e=this.RIa(b,c,this.opa)),this.ppa&&(h=this.RIa(b,c,this.ppa)),[e,h];if(this.Mx>=a.Fb.NZ||this.Us>=6*a.Fb.NZ)e=this.vB(b,!1,!1,!0);else if(this.Mx>=a.Fb.oT||this.Us>=6*a.Fb.oT){if(null==c||c.getMonth()!=b.getMonth())e=this.vB(b,!1,!0,!1);if(null==c||c.getYear()!=b.getYear())h=this.vB(b,!1,!1,!0)}else if(this.Mx>=a.Fb.jD||this.Us>=6*a.Fb.jD)if(d)e=this.vB(b,!0,!0,!0);else{if(null==c||c.getDate()!=b.getDate())e=this.vB(b,!0,!1,!1);null==c||c.getYear()!=b.getYear()?h=this.vB(b,!1,!0,!0):c.getMonth()!=
b.getMonth()&&(h=this.vB(b,!1,!0,!1))}else{if(this.Mx>=a.Fb.$N||this.Us>=6*a.Fb.$N){if(null==c||c.getHours()!=b.getHours())e=this.Dna(b,!1,!1)}else if(this.Mx>=a.Fb.kD||this.Us>=6*a.Fb.kD){if(null==c||c.getMinutes()!=b.getMinutes())e=this.Dna(b,!0,!1)}else if(null==c||c.getSeconds()!=b.getSeconds())e=this.Dna(b,!0,!0);if(f){if(null==c||c.getDate()!=b.getDate())h=this.vB(b,!0,!0,!1)}else null==c||c.getYear()!=b.getYear()?h=this.vB(b,!0,!0,!0):c.getMonth()!=b.getMonth()?h=this.vB(b,!0,!0,!1):c.getDate()!=
b.getDate()&&(h=this.vB(b,!0,!1,!1))}return[e,h]};a.Fb.prototype.vB=function(b,c,d,e){var h="th"==this.iL.substring(0,2)&&"jet"!=this.W._environment?b.getFullYear()+543:b.getFullYear(),f;f=this.Ypa&&12<=this.Ypa.length?this.Ypa[b.getMonth()]:b.toString().split(" ")[1];b=b.getDate();h+=a.Fb.Zab(this.iL);b+=a.Fb.K$a(this.iL);for(var k=a.Fb.nJa(this.iL),v="",A=0;A<k.length;A++)c&&"D"==k[A]?v+=b+" ":d&&"M"==k[A]?v+=f+" ":e&&"Y"==k[A]&&(v+=h+" ");return 0<v.length?v.slice(0,v.length-1):v};a.Fb.prototype.Dna=
function(b,c,d){var e=b.getHours(),h=b.getMinutes();b=b.getSeconds();var f=a.Fb.q$a(this.iL),k=a.Fb.Bab(this.iL),v=a.Fb.p$a(this.iL),A=""!=f&&""!=k,u,D="";a.B.da(this.u())&&(D="\u200f");if(A){if(12>e?(u=f,0==e&&(e=12)):(u=k,12<e&&(e-=12)),D+=e,c||0!=h)D+=":"+this.w$(h)}else D+=this.w$(e)+":"+this.w$(h);d&&(D+=":"+this.w$(b));return A?v?u+" "+D:D+" "+u:D};a.Fb.prototype.w$=function(a){return 10>a?"0"+a:""+a};a.Fb.prototype.MJa=function(){return this.Us>=6*a.Fb.NZ?a.Fb.NZ:this.Us>=6*a.Fb.oT?a.Fb.oT:
this.Us>=6*a.Fb.jD?a.Fb.jD:this.Us>=a.Fb.jD?3*a.Fb.$N:this.Us>=6*a.Fb.$N?a.Fb.$N:this.Us>=a.Fb.$N?15*a.Fb.kD:this.Us>=30*a.Fb.kD?5*a.Fb.kD:this.Us>=6*a.Fb.kD?a.Fb.kD:this.Us>=a.Fb.kD?15*a.Fb.MZ:this.Us>=30*a.Fb.MZ?5*a.Fb.MZ:a.Fb.MZ};a.Fb.Yna=function(b,c,d){var e=new Date(b);e.setMonth(0,1);e.setHours(0,0,0,0);var e=e.getTime(),h=[];if(d>=a.Fb.NZ&&d<=a.Fb.S1a){for(;e<b;)e=a.Fb.WFa(e);for(;e<=c;)h.push(e),e=a.Fb.WFa(e)}else if(d>=a.Fb.oT&&d<=a.Fb.R1a){for(;e<b;)e=a.Fb.VFa(e);for(;e<=c;)h.push(e),e=
a.Fb.VFa(e)}else for(e+=Math.ceil((b-e)/d)*d;e<=c;)h.push(e),e+=d;return h};a.Fb.WFa=function(a){a=new Date(a);a.setFullYear(a.getFullYear()+1);return a.getTime()};a.Fb.VFa=function(a){a=new Date(a);a.setMonth(a.getMonth()+1);return a.getTime()};a.Fb.prototype.Fna=function(b){var c=[],d=[],e=[],h=[],f=[],k=null,v=0,A=0,u=b.Oe,D=a.B.da(b),B="left"==this.fg||"right"==this.fg,C="off"!=this.W.zoomAndScroll,z=!0,G=0;B&&a.B.vX()&&(G=.16*this.fy());var y=[];if(null!=this.Mx)y=a.Fb.Yna(this.ff,this.Oh,this.Mx);
else if(this.bMa)this.Mx=this.MJa(),y=a.Fb.Yna(this.ff,this.Oh,this.Mx);else{for(var E=0;E<this.vm.length;E++)this.vm[E]>=this.ff&&this.vm[E]<=this.Oh&&y.push(this.vm[E]);this.Mx=this.AD;this.xQ||(E=new a.ca(b,this.Cna(new Date(y[0]))[0],0,0),((B?a.Ca.Pj(E).b:E.Pc().a)+this.Oha())*(y.length-1)>Math.abs(this.tm-this.YB)&&(this.Mx=this.MJa(),y=a.Fb.Yna(this.ff,this.Oh,this.Mx)))}0==y.length&&(y=[this.ff]);for(E=0;E<y.length;E++){var M=y[E],S=this.uj(M);if(null!=S){var M=new Date(M),O=this.Cna(M,k),
k=O[0],O=O[1];null!=k?(e.push({text:k,bda:null!=O?S+G:S}),h.push(S),v++):(e.push(null),h.push(null));c.push(null);C&&z&&(S=this.ff?this.uj(this.ff):S);z=!1;null!=O?(k=this.UC(b,O,null!=O?S-G:S),f.push(S),B||(D?k.Wh():k.Vh()),d.push(k),this.epa=!1,A++):(d.push(null),f.push(null));k=M}}v=this.agb(e,c,u);if(!C&&1<A&&v<1.5*A){c=d;d=null;for(b=0;b<c.length;b++)null!=c[b]&&c[b].Yf();this.ZOa(c,this.MS(c,u),!1,D)}else A=this.ZOa(d,this.MS(d,u),!0,D),0==A&&(d=null);B&&null!=d&&this.bgb(c,d);this.P0=c;this.vLa=
d;this.rP=h;this.Jaa=f};a.Fb.VKa=function(a,b,c,d,e){return c>=a&&c-e<b||c<a&&d+e>a?!0:!1};a.Fb.prototype.HJa=function(a,b,c,d){var e=a-(c?d?b:0:.5*b);if(e<this.W._minOverflowCoord)return Math.floor(e-this.W._minOverflowCoord);a+=c?d?0:b:.5*b;return a>this.W._maxOverflowCoord?Math.ceil(a-this.W._maxOverflowCoord):0};a.Fb.prototype.ZOa=function(b,c,d,e){if(!c||0>=c.length)return!1;for(var h="left"==this.fg||"right"==this.fg,f=this.fy(),f=h?.08*f:.24*f,k=0,v,A,u,D=Math.abs(this.tm-this.YB),B=0;B<c.length;B++)if(this.zpa.push(0),
null!=b[B]){u=b[B];var C=a.Ca.yea(u);c[B].a>D?b[B]=null:(C=this.HJa(u.Va(),C,d,e),this.zpa[B]=C,0!=C&&(u.Fa(u.Va()-C),c[B].x-=C))}for(B=0;B<c.length;B++)null!=c[B]&&(h?(d=c[B].y,e=c[B].y+c[B].b):(d=c[B].x,e=c[B].x+c[B].a),null!=v&&null!=A&&a.Fb.VKa(v,A,d,e,f)&&(b[B]=null),null!=b[B]&&(v=d,A=e,k++));return k};a.Fb.prototype.agb=function(a,b,c){function d(a){if(null==h[a])if(e[a].label=u.UC(c.u(),e[a].text,e[a].bda),h[a]=e[a].label.Pc(c),h[a].a>f)e[a].label=null,h[a].a=0,h[a].b=0;else{var b=u.HJa(e[a].bda,
h[a].a,!1,!1);0!=b&&(e[a].bda-=b,h[a].x-=b,e[a].label.Fa(e[a].label.Va()-b),u.ypa[a]=b)}return A?h[a].b:h[a].a}for(var e=[],h=[],f=Math.abs(this.tm-this.YB),k=0;k<a.length;k++)null!=a[k]&&(e.push(a[k]),h.push(null),this.ypa.push(0));for(var A="left"==this.fg||"right"==this.fg,u=this,k=(d(0)+this.Oha())*(e.length-1),D=0<f?Math.ceil(k/f)-1:0,k=!0;k;){for(k=0;k<e.length;k++)0==k%(D+1)?(d(k),e[k].OWa=!1):e[k].OWa=!0;k=this.GN(h,D);D++}for(k=D=0;k<a.length;k++)null==a[k]||a[k].OWa||(b[k]=a[k].label,D++);
return D};a.Fb.prototype.bgb=function(b,c){function d(b,c){return a.Fb.VKa(b.y,b.y+b.b,c.y,c.y+c.b,e)}for(var e=.08*this.fy(),h=null,f=!1,k=0;k<b.length;k++)if(b[k]&&c[k]){b[k].np();c[k].Oq();if(h&&d(h,c[k].Pc())){f=!0;break}h=b[k].Pc()}else if(b[k]||c[k]){var v=b[k]?b[k]:c[k];if(h&&d(h,v.Pc())){f=!0;break}h=v.Pc()}if(f)for(var v=f=h=null,A,k=0;k<b.length;k++)c[k]?(b[k]=null,c[k].Ng(),A=c[k].Pc(),f&&d(f,A)&&(b[h]=null),v=A):b[k]&&(A=b[k].Pc(),v&&d(v,A)?b[k]=null:(f=A,h=k))};a.Fb.prototype.iq=function(a,
b){if(b&&1<b)return null;this.P0||this.Fna(a);return 1==b?this.vLa:this.P0};a.Fb.prototype.$W=function(){var a=[];if(this.epa)for(var b=0;b<this.rP.length;b++)null!=this.rP[b]&&null!=this.P0[b]&&a.push(this.rP[b]);else for(b=1;b<this.Jaa.length;b++)null!=this.Jaa[b]&&a.push(this.Jaa[b]);return a};a.Fb.prototype.dX=function(){if(this.epa)return[];for(var a=[],b=0;b<this.rP.length;b++)null!=this.rP[b]&&null!=this.P0[b]&&a.push(this.rP[b]);return a};a.Fb.prototype.vI=function(a){if(null==a)return null;
a=(a-this.YB)/(this.tm-this.YB);if(this.xQ){var b=this.fW(this.ff);return this.maa(b+a*(this.fW(this.Oh)-b))}return this.ff+a*(this.Oh-this.ff)};a.Fb.prototype.rh=function(a){if(null==a)return null;if(this.xQ){var b=this.fW(this.ff);a=(this.fW(a)-b)/(this.fW(this.Oh)-b)}else a=(a-this.ff)/(this.Oh-this.ff);return this.YB+a*(this.tm-this.YB)};a.Fb.prototype.Ou=function(a){return null==a?null:this.xQ?this.maa(a):a};a.Fb.prototype.dn=function(a){return null==a?null:this.xQ?this.fW(a):a};a.Fb.prototype.fW=
function(a){for(var b=this.vm.length,c=0;c<this.vm.length;c++)if(a<=this.vm[c]){b=c;break}var c=b-1,d=void 0!==this.vm[c]?this.vm[c]:this.vm[0]-this.AD;return c+(a-d)/((void 0!==this.vm[b]?this.vm[b]:this.vm[this.vm.length-1]+this.AD)-d)};a.Fb.prototype.maa=function(a){var b=Math.min(Math.max(Math.ceil(a),0),this.vm.length),c=b-1,d=void 0!==this.vm[c]?this.vm[c]:this.vm[0]-this.AD;return d+(a-c)*((void 0!==this.vm[b]?this.vm[b]:this.vm[this.vm.length-1]+this.AD)-d)};a.Fb.prototype.lI=function(){return this.xQ?
Math.abs(this.rh(this.maa(1))-this.rh(this.maa(0))):Math.abs(this.rh(this.ff+this.AD)-this.rh(this.ff))};a.Fb.prototype.cX=function(){return this.xQ?1:this.bMa?Math.min((this.ds-this.es)/8,this.AD):this.AD};a.Fb.prototype.h4=function(){return"top"!=this.fg&&"bottom"!=this.fg||!a.B.da(this.u())?this.fx:this.Nw};a.Fb.prototype.y3=function(){return"top"!=this.fg&&"bottom"!=this.fg||!a.B.da(this.u())?this.Nw:this.fx}})(dvt);
  return dvt;
});
