/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit', './DvtPanZoomCanvas'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
function vl(a){this.Init(a)}ba("DvtDiagramLayoutContext",vl);dvt.v.D(vl,dvt.v,"DvtDiagramLayoutContext");
vl.prototype.Init=function(a){this.fi=a?a.fi:null;this.xr=a?a.xr:null;this.Hx=a?a.Hx:0;this.Q0=a?a.Q0:0;this.kx=a?a.kx:!1;this.qma=a?a.qma:null;this.ah=a?a.ah:null;this.As=a?a.As:null;this.bi=a?a.bi:null;this.oc={};this.$d={};this.tG=[];this.e_=[];if(a){for(var b=0;b<this.Hx;b++){var c=new wl(a.tG[b]);this.tG.push(c);this.oc[c.getId()]=c}for(var d in a.oc)this.oc[d]||(this.oc[d]=new wl(a.oc[d]));for(b=0;b<this.Q0;b++)c=new xl(a.e_[b]),this.e_.push(c),this.$d[c.getId()]=c;for(var e in a.$d)this.$d[e]||
(this.$d[e]=new xl(a.$d[e]))}};vl.prototype.yp=function(a){this.fi=a};vl.prototype.ug=function(){return this.fi};vl.prototype.getLayout=vl.prototype.ug;vl.prototype.yt=function(a){this.xr=a};vl.prototype.ln=function(){return this.xr};vl.prototype.getLayoutAttributes=vl.prototype.ln;vl.prototype.ZL=function(a){this.ka(a.getId())||(this.Hx++,this.tG.push(a));this.oc[a.getId()]=a};vl.prototype.ka=function(a){return this.oc[a]};vl.prototype.getNodeById=vl.prototype.ka;vl.prototype.ZE=function(a){return this.tG[a]};
vl.prototype.getNodeByIndex=vl.prototype.ZE;vl.prototype.Bg=function(){return this.Hx};vl.prototype.getNodeCount=vl.prototype.Bg;function ob(a,b){a.pd(b.getId())||(a.Q0++,a.e_.push(b));a.$d[b.getId()]=b}vl.prototype.pd=function(a){return this.$d[a]};vl.prototype.getLinkById=vl.prototype.pd;vl.prototype.tM=function(a){return this.e_[a]};vl.prototype.getLinkByIndex=vl.prototype.tM;vl.prototype.Ju=function(){return this.Q0};vl.prototype.getLinkCount=vl.prototype.Ju;
vl.prototype.Zob=function(a,b){for(var c=b,d=new sd(0,0);c;)if(d.x+=c.sN.x+c.ui().x,d.y+=c.sN.y+c.ui().y,c=c.As){if((c=this.ka(c))&&c.Ab()){var e=c.rp();e&&(d.x+=e.left,d.y+=e.top)}}else c=null;return new sd(a.x+d.x,a.y+d.y)};vl.prototype.localToGlobal=vl.prototype.Zob;vl.prototype.sob=function(){return this.kx};vl.prototype.isLocaleR2L=vl.prototype.sob;vl.prototype.vkb=function(){return this.qma};vl.prototype.getComponentSize=vl.prototype.vkb;vl.prototype.Usb=function(a){this.ah=a};
vl.prototype.setViewport=vl.prototype.Usb;vl.prototype.xI=function(){return this.ah};vl.prototype.getViewport=vl.prototype.xI;vl.prototype.Ffa=function(a){this.As=a};vl.prototype.Qta=function(){return this.As};vl.prototype.getContainerId=vl.prototype.Qta;vl.prototype.pF=function(a,b,c,d){this.As&&(this.bi={},"number"!==typeof a&&"string"!==typeof a&&(d=a.left,b=a.right,c=a.bottom,a=a.top),this.bi.top=a,this.bi.right=b,this.bi.bottom=c,this.bi.left=d)};vl.prototype.setContainerPadding=vl.prototype.pF;
vl.prototype.rp=function(){return this.bi};vl.prototype.getContainerPadding=vl.prototype.rp;vl.prototype.zkb=function(){return this.hz};vl.prototype.getCurrentViewport=vl.prototype.zkb;vl.prototype.ukb=function(a,b){function c(a,b){for(var c=[],d=b.ka(a)?b.ka(a).As:null;d;)c.push(d),d=b.ka(d)?b.ka(d).As:null;c.reverse();return c}for(var d=c(a,this),e=c(b,this),f=null,h=0;h<d.length&&h<e.length&&d[h]==e[h];h++)f=d[h];return f};vl.prototype.getCommonContainer=vl.prototype.ukb;
function xl(a){this.Init(a)}ba("DvtDiagramLayoutContextLink",xl);dvt.v.D(xl,dvt.v,"DvtDiagramLayoutContextLink");xl.prototype.Init=function(a){this.xc=a?a.xc:null;this.ZV=a?a.ZV:null;this.BU=a?a.BU:null;this.zl=a?a.zl:null;this.oP=a?a.oP:null;this.xz=a?a.xz:null;this.Ov=a?a.Ov:null;this.nP=a?a.nP:null;this.xr=a?a.xr:null;this.esa=a?a.esa:0;this.tna=a?a.tna:0;this.xP=a?a.xP:1;this.Lg=a?a.Lg:!1;this.Qn=a?a.Qn:null;this.$m=a?a.$m:null;this.bj=a?a.bj:!1;this.As=a?a.As:null};
xl.prototype.setId=function(a){this.xc=a};xl.prototype.getId=function(){return this.xc};xl.prototype.getId=xl.prototype.getId;xl.prototype.mY=function(a){this.ZV=a};xl.prototype.Re=function(){return this.ZV};xl.prototype.getStartId=xl.prototype.Re;xl.prototype.XX=function(a){this.BU=a};xl.prototype.Ad=function(){return this.BU};xl.prototype.getEndId=xl.prototype.Ad;xl.prototype.be=function(a){this.zl="string"==typeof a?dvt.P.T2(a):a};xl.prototype.setPoints=xl.prototype.be;xl.prototype.ad=function(){return this.zl};
xl.prototype.getPoints=xl.prototype.ad;xl.prototype.Dg=function(a){this.oP=a};xl.prototype.setLabelPosition=xl.prototype.Dg;xl.prototype.kf=function(){return this.oP};xl.prototype.getLabelPosition=xl.prototype.kf;xl.prototype.Tu=function(a){this.nP=a};xl.prototype.tg=function(){return this.nP};xl.prototype.getLabelBounds=xl.prototype.tg;xl.prototype.f4=function(){return this.esa};xl.prototype.getStartConnectorOffset=xl.prototype.f4;xl.prototype.x3=function(){return this.tna};
xl.prototype.getEndConnectorOffset=xl.prototype.x3;xl.prototype.ZM=function(a){this.xP=a};xl.prototype.bA=function(){return this.xP};xl.prototype.getLinkWidth=xl.prototype.bA;xl.prototype.yt=function(a){this.xr=a};xl.prototype.ln=function(){return this.xr};xl.prototype.getLayoutAttributes=xl.prototype.ln;xl.prototype.kc=function(a){this.Lg=a};xl.prototype.Tua=function(){return this.Lg};xl.prototype.getSelected=xl.prototype.Tua;xl.prototype.TI=function(a){this.Qn=a};
xl.prototype.setLabelRotationAngle=xl.prototype.TI;xl.prototype.SE=function(){return this.Qn};xl.prototype.getLabelRotationAngle=xl.prototype.SE;xl.prototype.uF=function(a){this.$m=a};xl.prototype.setLabelRotationPoint=xl.prototype.uF;xl.prototype.TE=function(){return this.$m};xl.prototype.getLabelRotationPoint=xl.prototype.TE;xl.prototype.WI=function(a){this.bj=a};xl.prototype.NUa=function(){return this.bj};xl.prototype.isPromoted=xl.prototype.NUa;xl.prototype.yxa=function(a){this.xz=a};
xl.prototype.setLabelValign=xl.prototype.yxa;xl.prototype.xxa=function(a){this.Ov=a};xl.prototype.setLabelHalign=xl.prototype.xxa;xl.prototype.qua=function(){return this.xz};xl.prototype.getLabelValign=xl.prototype.qua;xl.prototype.WW=function(){return this.Ov};xl.prototype.getLabelHalign=xl.prototype.WW;xl.prototype.Hrb=function(a){this.M_=a};xl.prototype.setCoordinateSpace=xl.prototype.Hrb;xl.prototype.wkb=function(){return this.M_};xl.prototype.getCoordinateSpace=xl.prototype.wkb;
xl.prototype.setData=function(a){this.Nb=a};xl.prototype.getData=function(){return this.Nb};xl.prototype.getData=xl.prototype.getData;function wl(a){this.Init(a)}ba("DvtDiagramLayoutContextNode",wl);dvt.v.D(wl,dvt.v,"DvtDiagramLayoutContextNode");
wl.prototype.Init=function(a){this.xc=a?a.xc:null;this.we=a?a.we:null;this.L_=a?a.L_:null;this.zL=a?a.zL:null;this.oP=a?a.oP:null;this.nP=a?a.nP:null;this.xz=a?a.xz:null;this.Ov=a?a.Ov:null;this.xr=a?a.xr:null;this.Nla=a?a.Nla:!1;this.As=a?a.As:null;this.Lg=a?a.Lg:!1;this.Qn=a?a.Qn:null;this.$m=a?a.$m:null;this.bi=a?a.bi:null;this.Uv=a?a.Uv:null;this.Vv=a?a.Vv:null;this.Sm=a?a.Sm:!1;this.rN=a?a.Na():null;this.aD=!0;this.sN=new sd(0,0)};wl.prototype.setId=function(a){this.xc=a};
wl.prototype.getId=function(){return this.xc};wl.prototype.getId=wl.prototype.getId;wl.prototype.Rf=function(){!this.aD&&this.rN&&this.rN.MI(this);return this.we};wl.prototype.getBounds=wl.prototype.Rf;wl.prototype.hi=function(){!this.aD&&this.rN&&this.rN.MI(this);return this.L_};wl.prototype.getContentBounds=wl.prototype.hi;wl.prototype.setPosition=function(a){this.zL=a;yl(this,this)};wl.prototype.setPosition=wl.prototype.setPosition;wl.prototype.ui=function(){return this.zL};
wl.prototype.getPosition=wl.prototype.ui;wl.prototype.qmb=function(a){var b=this.FBa;if(b){for(var c=new sd(0,0),d=this,e=!1;d;){var f=d.As;if(f){var h=b.ka(f);h&&this.rN&&!h.aD&&this.rN.MI(h)}c.x+=d.sN.x+d.ui().x;c.y+=d.sN.y+d.ui().y;if(f!=a)if((d=b.ka(f))&&d.Ab()){if(f=d.rp())c.x+=f.left,c.y+=f.top}else d=null;else e=!0,d=null}e||(c=null);return c}};wl.prototype.getRelativePosition=wl.prototype.qmb;wl.prototype.Dg=function(a){this.oP=a};wl.prototype.setLabelPosition=wl.prototype.Dg;
wl.prototype.kf=function(){return this.oP};wl.prototype.getLabelPosition=wl.prototype.kf;wl.prototype.Tu=function(a){this.nP=a};wl.prototype.tg=function(){return this.nP};wl.prototype.getLabelBounds=wl.prototype.tg;wl.prototype.yt=function(a){this.xr=a};wl.prototype.ln=function(){return this.xr};wl.prototype.getLayoutAttributes=wl.prototype.ln;wl.prototype.xF=function(a){this.Nla=a};wl.prototype.BX=function(){return this.Nla};wl.prototype.isReadOnly=wl.prototype.BX;
wl.prototype.Ffa=function(a){this.As=a};wl.prototype.Qta=function(){return this.As};wl.prototype.getContainerId=wl.prototype.Qta;wl.prototype.kc=function(a){this.Lg=a};wl.prototype.Tua=function(){return this.Lg};wl.prototype.getSelected=wl.prototype.Tua;wl.prototype.TI=function(a){this.Qn=a};wl.prototype.setLabelRotationAngle=wl.prototype.TI;wl.prototype.SE=function(){return this.Qn};wl.prototype.getLabelRotationAngle=wl.prototype.SE;wl.prototype.uF=function(a){this.$m=a};
wl.prototype.setLabelRotationPoint=wl.prototype.uF;wl.prototype.TE=function(){return this.$m};wl.prototype.getLabelRotationPoint=wl.prototype.TE;wl.prototype.pF=function(a,b,c,d){this.Ab()&&(this.bi={},"number"!==typeof a&&"string"!==typeof a&&(d=a.left,b=a.right,c=a.bottom,a=a.top),this.bi.top=a,this.bi.right=b,this.bi.bottom=c,this.bi.left=d,this.Uv&&(this.we=new xb(this.Uv.x,this.Uv.y,this.Uv.w+d+b,this.Uv.h+a+c)),this.Vv&&(this.L_=new xb(this.Vv.x,this.Vv.y,this.Vv.w+d+b,this.Vv.h+a+c)))};
wl.prototype.setContainerPadding=wl.prototype.pF;wl.prototype.rp=function(){return this.bi};wl.prototype.getContainerPadding=wl.prototype.rp;wl.prototype.Di=function(a){this.Sm=a};wl.prototype.Ab=function(){return this.Sm};wl.prototype.isDisclosed=wl.prototype.Ab;wl.prototype.Y4=function(a){this.o8a=a};wl.prototype.ze=function(){return this.o8a};wl.prototype.getChildNodes=wl.prototype.ze;wl.prototype.ZR=function(a){this.oE=a};wl.prototype.kq=function(){return this.oE};wl.prototype.getParentNode=wl.prototype.kq;
function yl(a,b){var c=b.kq();c&&c.aD&&(c.aD=!1,yl(a,c))}wl.prototype.yxa=function(a){this.xz=a};wl.prototype.setLabelValign=wl.prototype.yxa;wl.prototype.xxa=function(a){this.Ov=a};wl.prototype.setLabelHalign=wl.prototype.xxa;wl.prototype.qua=function(){return this.xz};wl.prototype.getLabelValign=wl.prototype.qua;wl.prototype.WW=function(){return this.Ov};wl.prototype.getLabelHalign=wl.prototype.WW;wl.prototype.setData=function(a){this.Nb=a};wl.prototype.getData=function(){return this.Nb};
wl.prototype.getData=wl.prototype.getData;function sd(a,b){this.Init(a,b)}ba("DvtDiagramPoint",sd);dvt.v.D(sd,dvt.v,"DvtDiagramPoint");sd.prototype.Init=function(a,b){this.x=null===a||isNaN(a)?0:a;this.y=null===b||isNaN(b)?0:b};function xb(a,b,c,d){this.Init(a,b,c,d)}ba("DvtDiagramRectangle",xb);dvt.v.D(xb,dvt.v,"DvtDiagramRectangle");xb.prototype.Init=function(a,b,c,d){this.x=null===a||isNaN(a)?0:a;this.y=null===b||isNaN(b)?0:b;this.w=null===c||isNaN(c)?0:c;this.h=null===d||isNaN(d)?0:d};
dvt.cc={};dvt.v.D(dvt.cc,dvt.v);dvt.cc.Qwb=function(a,b,c){a&&b&&a instanceof ya&&b instanceof ya?dvt.cc.h2a(a,b,c):a&&b&&a instanceof dvt.ue&&b instanceof dvt.ue?dvt.cc.g2a(a,b,c):a&&b&&dvt.cc.VDa(a,b,c)};dvt.cc.h2a=function(a,b,c){dvt.cc.vgb(a,b,c);var d=a.fd?a.fd():null,e=b.fd?b.fd():null;c&&(a.Va()!=b.Va()&&c.N(dvt.G.V,a,a.Va,a.Fa,b.Va()),a.ib()!=b.ib()&&c.N(dvt.G.V,a,a.ib,a.jb,b.ib()),d&&e&&d instanceof dvt.$b&&e instanceof dvt.$b&&d.ic()!=e.ic()&&c.N(dvt.G.po,a,a.fd,a.ra,e))};
dvt.cc.VDa=function(a,b,c){var d=a.aa(a.u().Oe),e=b.aa(b.u().Oe),f=a.fd?a.fd():null,h=b.fd?b.fd():null,k=a.Ud?a.Ud():null,l=b.Ud?b.Ud():null;if(c){var m=b=1;d.a!=e.a&&(b=e.a/d.a);d.b!=e.b&&(m=e.b/d.b);var n=0,r=0;d.x!=e.x&&(n=e.x-d.x);d.y!=e.y&&(r=e.y-d.y);f&&h&&f instanceof dvt.$b&&h instanceof dvt.$b&&f.ic()!=h.ic()&&c.N(dvt.G.po,a,a.fd,a.ra,h);k&&l&&k instanceof dvt.ya&&l instanceof dvt.ya&&k.ic()!=l.ic()&&c.N(dvt.G.UJ,a,a.Ud,a.Ga,l);if(0!=n||0!=r||1!=b||1!=m)e=new dvt.Tb,e.translate(-d.x,-d.y),
e.scale(b,m),e.translate(d.x,d.y),e.translate(n,r),d=a.sb().clone(),d.concat(e),c.N(dvt.G.aj,a,a.sb,a.rb,d)}};dvt.cc.vgb=function(a,b,c){if(c){var d=dvt.cc.o0(a);b=dvt.cc.o0(b);d.Fe(b)||(d=dvt.cc.o0(a.getParent()),d.fF(),b.concat(d),c.N(dvt.G.aj,a,a.sb,a.rb,b))}};dvt.cc.o0=function(a){var b=[a];for(a=a.getParent();a;)b.push(a),a=a.getParent();a=new dvt.Tb;for(var c=0;c<b.length;c++)a.concat(b[c].sb());return a};
dvt.cc.g2a=function(a,b,c){var d=dvt.cc.tHa(a),e=dvt.cc.tHa(b);if(d&&e){a!=d&&(dvt.cc.ufb(a,d),a=d);var d=a.fd?a.fd():null,f=b.fd?b.fd():null;c&&(d&&f&&d instanceof dvt.$b&&f instanceof dvt.$b&&d.ic()!=f.ic()&&c.N(dvt.G.po,a,a.fd,a.ra,f),b=dvt.cc.o0(b),dvt.cc.B7a(a,e,c,b))}else dvt.cc.VDa(a,b,c)};dvt.cc.tHa=function(a){if(a instanceof dvt.vb)return a;var b=dvt.cc.Dab(a);return b?new dvt.vb(a.u(),b):null};
dvt.cc.ufb=function(a,b){var c=a.fd(),d=a.Ud(),e=a.sb(),f=a.getParent().Bi(a);a.getParent().Ib(b,f);a.ra(null);a.Ga(null);a.rb(null);b.ra(c);b.Ga(d);b.rb(e);c=a.Rb();for(d=0;d<c;d++)b.A(a.hb(0));a.getParent().removeChild(a);a.xa&&a.xa()};
dvt.cc.Dab=function(a){var b;if(a instanceof dvt.Rect){var c=a.it(),d=a.Lu(),e=a.Va(),f=a.ib(),h=a.getWidth(),k=a.getHeight();if(c&&d){a=.5*Math.PI;var l=Math.cos(.5*a),m=Math.sin(.5*a),n=l,r=-m,p=(4-l)/3,w=(1-l)*(3-l)/(3*m);b=p;var x=-w,l=new dvt.R(l,m),n=new dvt.R(n,r),p=new dvt.R(p,w),x=new dvt.R(b,x),w=new dvt.Tb;w.rotate(.5*a);w.scale(c,d);a=w.ef(p);var l=w.ef(x),v=e+h-c,A=f+d;b=["M",e+c,f,"L",e+h-c,f,"C",v+a.x,A-a.y,v+l.x,A-l.y,e+h,f+d];A=f+k-d;b.push("L",e+h,f+k-d,"C",v+l.x,A+l.y,v+a.x,A+a.y,
e+h-c,f+k);v=e+c;b.push("L",e+c,f+k,"C",v-a.x,A+a.y,v-l.x,A+l.y,e,f+k-d);A=f+d;b.push("L",e,f+d,"C",v-l.x,A-l.y,v-a.x,A-a.y,e+c,f,"Z")}else b=["M",e,f,"L",e+h,f,"L",e+h,f+k,"L",e,f+k,"Z"]}else if(a instanceof dvt.Yw||a instanceof dvt.mi){if(c=a.ad()){b=[];for(f=0;f<c.length;f+=2)0==f?b.push("M",c[f],c[f+1]):b.push("L",c[f],c[f+1]);a instanceof dvt.mi&&b.push("Z")}}else if(a instanceof dvt.Gc)b=["M",a.Qr(),a.Rr(),"L",a.nt(),a.ot()];else if(a instanceof dvt.Nm){v=a.gk();A=a.hk();a instanceof dvt.nv?
(c=a.it(),d=a.Lu()):d=c=a.Yn();e=-.5*Math.PI;a=2*Math.PI/4;l=Math.cos(.5*a);m=Math.sin(.5*a);n=l;r=-m;p=(4-l)/3;w=(1-l)*(3-l)/(3*m);b=p;x=-w;l=new dvt.R(l,m);n=new dvt.R(n,r);p=new dvt.R(p,w);x=new dvt.R(b,x);b=[];for(f=0;4>f;f++)w=new dvt.Tb,w.rotate(e+f*a),w.scale(c,d),0==f&&(h=w.ef(n),b.push("M",v+h.x,A+h.y)),h=w.ef(x),k=w.ef(p),w=w.ef(l),b.push("C",v+h.x,A+h.y,v+k.x,A+k.y,v+w.x,A+w.y);b.push("Z")}else a instanceof dvt.mg&&(c=a.Rx()*dvt.Math.dG,d=a.gq()*dvt.Math.dG,b=["M",a.gk()+a.it()*Math.cos(c),
a.hk()-a.Lu()*Math.sin(c),"A",a.it(),a.Lu(),"0",180<Math.abs(a.gq())?"1":"0",0<a.gq()?"0":"1",a.gk()+a.it()*Math.cos(c+d),a.hk()-a.Lu()*Math.sin(c+d)],a.IO===dvt.mg.nS?b.push("Z"):a.IO===dvt.mg.Jia&&b.push("L",a.gk(),a.hk(),"Z"));return b};dvt.cc.cH=function(a,b){for(;b<a.length&&!isNaN(a[b]);)b++;return b};dvt.cc.MU=function(a,b){for(;-1<b&&!isNaN(a[b]);)b--;return b};dvt.cc.zHa=function(a){for(var b=0,c=0;c<a.length;c++)isNaN(a[c])&&b++;return b};
dvt.cc.Ccb=function(a,b){var c=dvt.cc.zHa(a),d=dvt.cc.zHa(b);if(c!=d){var e=0,f=0;c>d?(e=c-d,f=d,c=b):(e=d-c,f=c,c=a);d=Math.floor(f/e);1>d&&(d=1);f=Math.floor(e/f);1>f&&(f=1);for(var h=-1,k=0;k<c.length;k++)if(isNaN(c[k])){if(h==d)for(var l=h=0;l<f;l++)c.splice(k++,0,"tmp"),e--;h++}for(k=0;k<e;k++)"Z"==c[c.length-1]?c.splice(c.length-1,0,"tmp"):c.push("tmp")}};dvt.cc.cMa=function(a){return 2<a.length&&"Z"==a[a.length-1]?(a.splice(a.length-1,1),a.push("L",a[1],a[2]),!0):!1};
dvt.cc.B7a=function(a,b,c,d){b=dvt.cc.ORa(a.VQ(),b.VQ());var e=dvt.cc.o0(a);e&&dvt.cc.IPa(b.Sxa,e);a.rb(null);d&&dvt.cc.IPa(b.Rxa,d);a.ut(b.Sxa);c.N(dvt.G.lm,a,a.VQ,a.ut,b.Rxa)};
dvt.cc.ORa=function(a,b){var c=dvt.na.copy(a),d=dvt.na.copy(b),e=[],f=[];dvt.cc.ILa(c);dvt.cc.ILa(d);dvt.cc.LLa(c);dvt.cc.LLa(d);dvt.cc.MLa(c);dvt.cc.MLa(d);dvt.cc.NLa(c);dvt.cc.NLa(d);var h=dvt.cc.QGa(c),k=dvt.cc.QGa(d);dvt.cc.$Oa(h);dvt.cc.$Oa(k);for(var l=0;l<Math.max(h.length,k.length);l++){var m=[],n=[],r=null,p=null;l<h.length?r=h[l]:(r=["M",c[1],c[2]],"Z"==k[l][k[l].length-1]&&r.push("Z"));l<k.length?p=k[l]:(p=["M",d[1],d[2]],"Z"==h[l][h[l].length-1]&&p.push("Z"));dvt.cc.C7a(r,p,m,n);f=f.concat(m);
e=e.concat(n)}return{Sxa:f,Rxa:e}};dvt.cc.QGa=function(a){for(var b=[],c=0,d=1;d<a.length;d++)if("M"==a[d]||"m"==a[d])b.push(a.slice(c,d)),c=d;1>b.length?b.push(a):c<a.length&&b.push(a.slice(c));return b};dvt.cc.$Oa=function(a){a.sort(dvt.cc.u8a)};dvt.cc.u8a=function(a,b){var c=dvt.cc.WGa(a),d=dvt.cc.WGa(b);return c>d?-1:d>c?1:0};
dvt.cc.WGa=function(a){for(var b=0,c=0,d=0,e=0,f=0,h=0,k=0,l=0;l<a.length;){switch(a[l]){case "M":f=a[l+1];h=a[l+2];break;case "L":b=a[l+1];c=a[l+2];break;case "C":b=a[l+5];c=a[l+6];break;case "Q":b=a[l+3];c=a[l+4];break;case "A":b=a[l+6];c=a[l+7];break;case "Z":b=f,c=h}k+=Math.sqrt((b-d)*(b-d)+(c-e)*(c-e));l=dvt.cc.cH(a,l+1);d=b;e=c}return k};
dvt.cc.C7a=function(a,b,c,d){var e=dvt.cc.cMa(a),f=dvt.cc.cMa(b);if(e||a[a.length-2]==a[1]&&a[a.length-1]==a[2])a=dvt.cc.KLa(a),a=dvt.cc.JLa(a);if(f||b[b.length-2]==b[1]&&b[b.length-1]==b[2])b=dvt.cc.KLa(b),b=dvt.cc.JLa(b);dvt.cc.Ccb(a,b);dvt.cc.A7a(a,b,c,d);e&&a.push("Z");f&&b.push("Z")};
dvt.cc.A7a=function(a,b,c,d){for(var e=0,f=0,h=0,k=0,l=0,m=0,n=!1,r=!1;-1<e||-1<f;){var p=-1<e?a[e]:null,w=-1<f?b[f]:null,x=-1<e?dvt.cc.cH(a,e+1):-1,v=-1<f?dvt.cc.cH(b,f+1):-1;if(p==w){for(;f<v;f++)d.push(b[f]);for(f=e;f<x;f++)c.push(a[f])}else p&&"tmp"!=p?w&&"tmp"!=w?"L"==p?"Q"==w?(d.push("Q",b[f+1],b[f+2],b[f+3],b[f+4]),c.push("Q",h+.5*(a[e+1]-h),k+.5*(a[e+2]-k),a[e+1],a[e+2])):"C"==w?(d.push("C",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6]),c.push("C",h+.5*(a[e+1]-h),k+.5*(a[e+2]-k),h+.5*(a[e+1]-
h),k+.5*(a[e+2]-k),a[e+1],a[e+2])):"A"==w?(d.push("L",l,m,"A",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6],b[f+7]),c.push("L",a[e+1],a[e+2],"A",0,0,b[f+3],b[f+4],b[f+5],a[e+1],a[e+2])):"Z"==w&&(n=!0,d.push("L",l,m),c.push("L",a[e+1],a[e+2])):"Q"==p?"L"==w?(d.push("Q",l+.5*(b[f+1]-l),m+.5*(b[f+2]-m),b[f+1],b[f+2]),c.push("Q",a[e+1],a[e+2],a[e+3],a[e+4])):"C"==w?(d.push("C",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6]),c.push("C",a[e+1],a[e+2],a[e+1],a[e+2],a[e+3],a[e+4])):"A"==w?(d.push("Q",l,m,l,m,"A",
b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6],b[f+7]),c.push("Q",a[e+1],a[e+2],a[e+3],a[e+4],"A",0,0,b[f+3],b[f+4],b[f+5],a[e+3],a[e+4])):"Z"==w&&(n=!0,d.push("Q",l,m,l,m),c.push("Q",a[e+1],a[e+2],a[e+3],a[e+4])):"C"==p?"L"==w?(d.push("C",l+.5*(b[f+1]-l),m+.5*(b[f+2]-m),l+.5*(b[f+1]-l),m+.5*(b[f+2]-m),b[f+1],b[f+2]),c.push("C",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6])):"Q"==w?(d.push("C",b[f+1],b[f+2],b[f+1],b[f+2],b[f+3],b[f+4]),c.push("C",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6])):"A"==w?(d.push("C",
l,m,l,m,l,m,"A",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6],b[f+7]),c.push("C",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6],"A",0,0,b[f+3],b[f+4],b[f+5],a[e+5],a[e+6])):"Z"==w&&(n=!0,d.push("C",l,m,l,m,l,m),c.push("C",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6])):"A"==p?"L"==w?(d.push("L",b[f+1],b[f+2],"A",0,0,a[e+3],a[e+4],a[e+5],b[f+1],b[f+2]),c.push("L",h,k,"A",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6],a[e+7])):"Q"==w?(d.push("Q",b[f+1],b[f+2],b[f+3],b[f+4],"A",0,0,a[e+3],a[e+4],a[e+5],b[f+3],b[f+4]),
c.push("Q",h,k,h,k,"A",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6],a[e+7])):"C"==w?(d.push("C",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6],"A",0,0,a[e+3],a[e+4],a[e+5],b[f+5],b[f+6]),c.push("C",h,k,h,k,h,k,"A",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6],a[e+7])):"Z"==w&&(n=!0,d.push("A",0,0,a[e+3],a[e+4],a[e+5],l,m),c.push("A",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6],a[e+7])):"Z"==p&&(r=!0,"L"==w?(d.push("L",b[f+1],b[f+2]),c.push("L",h,k)):"Q"==w?(d.push("Q",b[f+1],b[f+2],b[f+3],b[f+4]),c.push("Q",h,k,
h,k)):"C"==w?(d.push("C",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6]),c.push("C",h,k,h,k,h,k)):"A"==w&&(d.push("A",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6],b[f+7]),c.push("A",0,0,b[f+3],b[f+4],b[f+5],h,k))):"L"==p?(d.push("L",l,m),c.push("L",a[e+1],a[e+2])):"Q"==p?(d.push("Q",l,m,l,m),c.push("Q",a[e+1],a[e+2],a[e+3],a[e+4])):"C"==p?(d.push("C",l,m,l,m,l,m),c.push("C",a[e+1],a[e+2],a[e+3],a[e+4],a[e+5],a[e+6])):"A"==p?(d.push("A",0,0,a[e+3],a[e+4],a[e+5],l,m),c.push("A",a[e+1],a[e+2],a[e+3],a[e+4],
a[e+5],a[e+6],a[e+7])):"Z"==p&&(d.push("Z"),c.push("Z")):"L"==w?(d.push("L",b[f+1],b[f+2]),c.push("L",h,k)):"Q"==w?(d.push("Q",b[f+1],b[f+2],b[f+3],b[f+4]),c.push("Q",h,k,h,k)):"C"==w?(d.push("C",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6]),c.push("C",h,k,h,k,h,k)):"A"==w?(d.push("A",b[f+1],b[f+2],b[f+3],b[f+4],b[f+5],b[f+6],b[f+7]),c.push("A",0,0,b[f+3],b[f+4],b[f+5],h,k)):"Z"==w&&(d.push("Z"),c.push("Z"));-1<x&&"Z"!=p&&"tmp"!=p&&(h=a[x-2],k=a[x-1]);-1<v&&"Z"!=w&&"tmp"!=w&&(l=b[v-2],m=b[v-1]);e=x;
f=v;if(e>=a.length||0>e)e=-1;if(f>=b.length||0>f)f=-1}if(r||n)d.push("Z"),c.push("Z")};
dvt.cc.JLa=function(a){if(!dvt.cc.dcb(a)){for(var b=["M"],c=dvt.cc.MU(a,a.length-1);-1<c;){var d=a[c];switch(d){case "M":b.push(a[c+1],a[c+2]);break;case "L":b.push(a[c+1],a[c+2]);b.push(d);break;case "Q":b.push(a[c+3],a[c+4]);b.push(d);b.push(a[c+1],a[c+2]);break;case "C":b.push(a[c+5],a[c+6]);b.push(d);b.push(a[c+3],a[c+4]);b.push(a[c+1],a[c+2]);break;case "A":b.push(a[c+6],a[c+7]),b.push(d),b.push(a[c+1],a[c+2],a[c+3],a[c+4]),b.push(0==a[c+5]?1:0)}c=dvt.cc.MU(a,c-1)}return b}return a};
dvt.cc.dcb=function(a){for(var b=[],c=0,d=Number.MAX_VALUE,e=Number.MAX_VALUE,f=dvt.cc.MU(a,a.length-1),h=1;h<f;){h=dvt.cc.cH(a,h);if(0<h-2&&"Z"!=a[h-1]){var k=a[h-2],l=a[h-1];b.push(k,l);if(l<e||l==e&&k<d)d=k,e=l,c=b.length-2}h+=1}k=h=f=a=0;0<c?(a=b[c-2],f=b[c-1]):(a=b[b.length-2],f=b[b.length-1]);c<b.length-2?(h=b[c+2],k=b[c+3]):(h=b[0],k=b[1]);return 0>d*k+a*e+f*h-(f*d+e*h+a*k)?!1:!0};
dvt.cc.KLa=function(a){for(var b=0,c=Number.MAX_VALUE,d=Number.MAX_VALUE,e=0,f=dvt.cc.MU(a,a.length-1),h=1;h<f;){var k=dvt.cc.cH(a,h);if(0<k-2&&"Z"!=a[k-1]){var h=a[k-2],l=a[k-1];if(l<d||l==d&&h<c)c=h,d=l,b=e}h=k+1;e=k}return 0<b?(k=dvt.cc.cH(a,b+1),b=["M"],c=a.slice(k-2,a.length),b=b.concat(c),c=a.slice(3,k),b=b.concat(c)):a};
dvt.cc.vab=function(a){switch(a){case "H":case "h":case "V":case "v":return 1;case "M":case "m":case "L":case "l":case "T":case "t":return 2;case "Q":case "q":case "S":case "s":return 4;case "C":case "c":return 6;case "A":case "a":return 7}return 0};
dvt.cc.ILa=function(a){for(var b=0;b<a.length;){var c=a[b],d=dvt.cc.vab(c);switch(c){case "M":b+d+1<a.length&&!isNaN(a[b+d+1])&&a.splice(b+d+1,0,"L");break;case "m":b+d+1<a.length&&!isNaN(a[b+d+1])&&a.splice(b+d+1,0,"l");break;case "Z":case "z":break;default:b+d+1<a.length&&!isNaN(a[b+d+1])&&a.splice(b+d+1,0,c)}b+=d+1}};
dvt.cc.LLa=function(a){for(var b=0,c=0,d=0,e=0,f=0;f<a.length;){switch(a[f]){case "m":a[f]="M";0<f&&(a[f+1]=b+a[f+1],a[f+2]=c+a[f+2]);b=a[f+1];c=a[f+2];d=b;e=c;break;case "l":a[f]="L";a[f+1]=b+a[f+1];a[f+2]=c+a[f+2];b=a[f+1];c=a[f+2];break;case "h":a[f]="H";a[f+1]=b+a[f+1];b=a[f+1];break;case "v":a[f]="V";a[f+1]=c+a[f+1];c=a[f+1];break;case "c":a[f]="C";a[f+1]=b+a[f+1];a[f+2]=c+a[f+2];a[f+3]=b+a[f+3];a[f+4]=c+a[f+4];a[f+5]=b+a[f+5];a[f+6]=c+a[f+6];b=a[f+5];c=a[f+6];break;case "s":a[f]="S";a[f+1]=
b+a[f+1];a[f+2]=c+a[f+2];a[f+3]=b+a[f+3];a[f+4]=c+a[f+4];b=a[f+3];c=a[f+4];break;case "q":a[f]="Q";a[f+1]=b+a[f+1];a[f+2]=c+a[f+2];a[f+3]=b+a[f+3];a[f+4]=c+a[f+4];b=a[f+3];c=a[f+4];break;case "t":a[f]="T";a[f+1]=b+a[f+1];a[f+2]=c+a[f+2];b=a[f+1];c=a[f+2];break;case "a":a[f]="A";a[f+6]=b+a[f+6];a[f+7]=c+a[f+7];b=a[f+6];c=a[f+7];break;case "z":a[f]="Z";b=d;c=e;break;case "M":b=a[f+1];c=a[f+2];d=b;e=c;break;case "L":b=a[f+1];c=a[f+2];break;case "H":b=a[f+1];break;case "V":c=a[f+1];break;case "C":b=a[f+
5];c=a[f+6];break;case "S":b=a[f+3];c=a[f+4];break;case "Q":b=a[f+3];c=a[f+4];break;case "T":b=a[f+1];c=a[f+2];break;case "A":b=a[f+6];c=a[f+7];break;case "Z":b=d,c=e}f=dvt.cc.cH(a,f+1)}};
dvt.cc.MLa=function(a){for(var b=0,c=0,d=0,e=0,f=0;f<a.length;){switch(a[f]){case "M":b=a[f+1];c=a[f+2];d=b;e=c;break;case "L":b=a[f+1];c=a[f+2];break;case "H":b=a[f+1];a[f]="L";a.splice(f+2,0,c);break;case "V":c=a[f+1];a[f]="L";a.splice(f+1,0,b);break;case "C":b=a[f+5];c=a[f+6];break;case "S":var h=dvt.cc.MU(a,f-1),k=b,l=c;"C"==a[h]&&(l=a[h+4],k=b+(b-a[h+3]),l=c+(c-l));a[f]="C";a.splice(f+1,0,k,l);b=a[f+5];c=a[f+6];break;case "Q":b=a[f+3];c=a[f+4];break;case "T":h=dvt.cc.MU(a,f-1);k=b;l=c;"Q"==a[h]&&
(l=a[h+2],k=b+(b-a[h+1]),l=c+(c-l));a[f]="Q";a.splice(f+1,0,k,l);b=a[f+3];c=a[f+4];break;case "A":b=a[f+6];c=a[f+7];break;case "Z":b=d,c=e}f=dvt.cc.cH(a,f+1)}};dvt.cc.NLa=function(a){for(var b=0,c=0,d=0;d<a.length;d++)"Z"==a[d]?d+1<a.length&&"M"!=a[d+1]&&"m"!=a[d+1]&&a.splice(d+1,0,"M",b,c):"M"==a[d]&&(b=a[d+1],c=a[d+2])};
dvt.cc.IPa=function(a,b){for(var c=null,d=0;d<a.length;){switch(a[d]){case "M":case "L":c=b.ef(new dvt.R(a[d+1],a[d+2]));a[d+1]=c.x;a[d+2]=c.y;break;case "Q":c=b.ef(new dvt.R(a[d+1],a[d+2]));a[d+1]=c.x;a[d+2]=c.y;c=b.ef(new dvt.R(a[d+3],a[d+4]));a[d+3]=c.x;a[d+4]=c.y;break;case "C":c=b.ef(new dvt.R(a[d+1],a[d+2]));a[d+1]=c.x;a[d+2]=c.y;c=b.ef(new dvt.R(a[d+3],a[d+4]));a[d+3]=c.x;a[d+4]=c.y;c=b.ef(new dvt.R(a[d+5],a[d+6]));a[d+5]=c.x;a[d+6]=c.y;break;case "A":var c=b.ef(new dvt.R(0,0)),e=b.ef(new dvt.R(a[d+
1],0)),f=b.ef(new dvt.R(0,a[d+2])),f=Math.sqrt((f.x-c.x)*(f.x-c.x)+(f.y-c.y)*(f.y-c.y));a[d+1]=Math.sqrt((e.x-c.x)*(e.x-c.x)+(e.y-c.y)*(e.y-c.y));a[d+2]=f;c=b.ef(new dvt.R(a[d+6],a[d+7]));a[d+6]=c.x;a[d+7]=c.y}d=dvt.cc.cH(a,d+1)}};function ja(a,b,c){this.Init(a,b,c)}ba("DvtBaseDiagram",ja);dvt.v.D(ja,dvt.fc,"DvtBaseDiagram");q=ja.prototype;
q.Init=function(a,b,c){ja.C.Init.call(this,a,b,c);this.u().Oe.Ua().setAttributeNS(null,"text-rendering","geometricPrecision");this.M0;this.iV=this.yr=null;this.D0;this.Kla=!0;this.Sp=new dvt.la(a);this.xl=new dvt.la(a);this.Oz=new dvt.la(a);this.Ml=dvt.rd.Uya;this.uBa()};q.VS=function(){var a=this.Qa;a.MC(this.oI());a.xA(this.WE());a.IC(this.ob());a.Oa.A(this.Sp);a.Oa.A(this.xl);a.Oa.A(this.Oz)};q.IC=function(a){this.Ml=a;this.Qa&&this.Qa.IC(a)};q.ob=function(){return this.Ml};
q.xA=function(a){this.DB=a;this.Qa&&this.Qa.xA(a)};q.WE=function(){return this.DB};q.MC=function(a){this.FB=a;this.Qa&&this.Qa.MC(a)};q.oI=function(){return this.FB};q.uBa=function(){this.xA(2);this.MC(0)};q.ka=function(){return null};q.pd=function(){return null};q.oJ=function(){return[]};q.pJ=function(){return[]};q.Bg=function(){return this.pJ().length};ja.prototype.getNodeCount=ja.prototype.Bg;ja.prototype.Ju=function(){return this.oJ().length};ja.prototype.getLinkCount=ja.prototype.Ju;
function tb(a,b){if(b&&a.Vm)a.JK?(a.JK.Fa(a.xb/2),a.JK.jb(a.Jb/2),dvt.Ca.kd(a.JK,a.getWidth()-2*dvt.Ca.mha,Infinity,a)):a.JK=a.Oya(a.Vm);else if(a.JK){var c=a.JK.getParent();c&&c.removeChild(a.JK);a.JK=null}}q=ja.prototype;q.Oya=function(a){var b=this.F();return dvt.Ca.vp(this,a,new dvt.Z(0,0,this.getWidth(),this.getHeight()),this.ab(),b._statusMessageStyle)};q.d5=function(a){this.Vm=a};q.VI=function(a){this.rba=a;this.Qa&&this.Qa.VI(a)};q.qI=function(){return this.rba};q.g5=function(a){this.D0=a};
ja.prototype.setInitAnim=ja.prototype.g5;q=ja.prototype;q.Xh=function(){return this.Yc};q.py=function(a){this.Yc="single"==a?new dvt.Rc(dvt.Rc.Sy):"multiple"==a?new dvt.Rc(dvt.Rc.Ry):null;this.ab().zA(this.Yc)};function Ea(a){return a.Yc?a.Yc.he():null}q.Oo=function(){return this.Yc?!0:!1};function vb(a){var b=new vl,c=dvt.B.da(a.u());b.kx=c;a=new xb(0,0,a.getWidth(),a.getHeight());b.qma=a;return b}
q.Lw=function(a,b,c,d){var e=new wl;e.setId(a.getId?a.getId():a.getData().getId());var f=Kd.LQ(a.Sg());e.we=f;e.Uv=f;f=Kd.LQ(a.hi());e.L_=f;e.Vv=f;b=a.ln?a.ln(b):a.getData();e.yt(b);e.setData(b);e.Tu(Kd.LQ(a.tg()));e.Dg(Kd.TQa(a.kf()));e.kc(1==a.wb());a.Ab()&&(e.Di(!0),b=wb(a.rp()),e.Ab()&&(e.bi=b))&&(e.Uv&&(e.Uv=new xb(e.Uv.x,e.Uv.y,e.Uv.w-(b.left+b.right),e.Uv.h-(b.top+b.bottom))),e.Vv&&(e.Vv=new xb(e.Vv.x,e.Vv.y,e.Vv.w-(b.left+b.right),e.Vv.h-(b.top+b.bottom))));e.Ffa(a.Bd());e.rN=this;e.aD=!c;
e.FBa=d;return e};q.jJ=function(a,b,c,d,e){var f=new xl;f.setId(a.getId?a.getId():a.getData().getId());f.mY(b?b:a.getData().Re());f.XX(c?c:a.getData().Ad());b=a.ln?a.ln(d):a.bj?a.getData()._links:a.getData();f.yt(b);f.setData(b);f.Tu(Kd.LQ(a.tg()));f.Dg(Kd.TQa(a.kf()));b=a.f4();f.esa=b;b=a.x3();f.tna=b;f.ZM(a.bA());f.kc(1==a.wb());f.WI(1==a.bj);f.FBa=e;return f};
q.AF=function(a,b,c){var d=a.rp();if(d){var e=a.As;e&&(e=this.ka(e))&&e.pF(qd(d),b)}for(var f=e=Number.MAX_VALUE,d=0;d<a.Bg();d++){var h=a.ZE(d),k=this.ka(h.getId()),l=h.ui();l&&(e=Math.min(e,l.x),f=Math.min(f,l.y));var m=h.tg(),h=h.kf();m&&h&&(e=Math.min(e,h.x+m.x),f=Math.min(f,h.y+m.y))}for(d=0;d<a.Ju();d++){var h=a.tM(d),n=this.pd(h.getId());if(l=h.ad())for(m=$e.Aha(l),k=0;k<m.length;k++)l=m[k],e=Math.min(e,l.x),f=Math.min(f,l.y);m=h.tg();h=h.kf();m&&h&&(e=Math.min(e,h.x+m.x),f=Math.min(f,h.y+
m.y))}m=this.Kya(-e,-f);e=m.x;f=m.y;for(d=0;d<a.Bg();d++)h=a.ZE(d),h.sN=new sd(m.x,m.y),k=this.ka(h.getId()),(l=h.ui())&&k.gD(l.x+e,l.y+f,b),zl(h,k,Kd.SQa(l),b),k.Ab()&&(h=h.rp())&&k.pF(qd(h),b);if(!this.AG)for(d=0;d<a.Ju();d++){var h=a.tM(d),n=this.pd(h.getId()),k=this.qAa(n,h,m,b),r=k.x,p=k.y;if(l=h.ad()){0<l.length&&!isNaN(l[0])&&(l=$e.c6(l));for(var w=[],k=0;k<l.length;)isNaN(l[k])?(w.push(l[k]),k++):(w.push(l[k]+r),w.push(l[k+1]+p),k+=2);b&&n.ad()?0<w.length&&isNaN(w[0])?(k=dvt.cc.ORa(n.ad(),
w),n.be(k.Sxa),b.N(dvt.G.lm,n,n.ad,n.be,k.Rxa),dvt.eb.Mb(b,function(){n.be(w)})):b.N(dvt.G.Tt,n,n.ad,n.be,w):n.be(w)}zl(h,n,new dvt.R(-r,-p),b)}if(b=a.xI())this.yr=new dvt.Z(b.x+e,b.y+f,b.w,b.h),this.iV=a.As;c&&(this.M0=new dvt.R(e,f))};q.qAa=function(a,b,c,d){var e=new dvt.R(0,0);if(!a.Bd())e=c;else if(a.Bd()!=b.M_){b=b.M_;for(a=this.ka(a.Bd());a;){var f=a.rp();e.x-=f.left-ud(a,d).x;e.y-=f.top-ud(a,d).y;a=a.Bd();a=a!=b?this.ka(a):null}b||(e.x+=c.x,e.y+=c.y)}return e};
function Pa(a,b){var c;if(a.yr&&(c=new dvt.Z(a.yr.x,a.yr.y,a.yr.a,a.yr.b),a.iV))for(var d=a.ka(a.iV);d;){var e=d.qa(),f=d.pa();if(b){var h=b.$f(d,d.qa),k=b.$f(d,d.pa);if(h||0==h)e=h;if(k||0==k)f=k}c.x+=e;c.y+=f;d=(d=d.Bd())?a.ka(d):null}return c}q.Kya=function(a,b){return new dvt.R(a,b)};q.PC=function(a,b){if(0==this.oI()){var c=this.Qa,d=b?b:Na(this,a,void 0,void 0);c.MC(this.rAa()*Math.min(Al(this,d),c.WE()));return d}return null};q.rAa=function(){return 1};
function Al(a,b){if(!b)return 0;var c=a.Qa;return Math.min((a.xb-2*c.Px)/b.a,(a.Jb-2*c.Px)/b.b)}
function Na(a,b,c,d){var e=null,f,h,k,l,m=a.Qa.Oa;c||(c=a.pJ());for(var n=0;n<c.length;n++)if(f=c[n],(l=a.ka(f))&&l.nc&&!l.ig){var r=l,p=b;f=r.Sg();h=new dvt.Z(f.x,f.y,f.a,f.b);k=null;p&&(k=p.$f(r,r.kf));k||(k=r.kf());var w=null,x=null;p&&(w=p.$f(r,r.SE),x=p.$f(r,r.TE));null==w&&(w=r.Qn);x||(x=r.$m);r=r.tg();k&&r&&(null!=w&&(r=Bl(r,w,x)),h.x=Math.min(f.x,r.x+k.x),h.y=Math.min(f.y,r.y+k.y),h.a=Math.max(f.x+f.a,r.x+k.x+r.a)-h.x,h.b=Math.max(f.y+f.b,r.y+k.y+r.b)-h.y);f=h;k=h=null;b&&(h=b.$f(l,l.qa),
k=b.$f(l,l.pa));null==h&&(h=l.qa());null==k&&(k=l.pa());f.x+=h;f.y+=k;if(h=l.Bd())h=l.getParent(),l=ld(new dvt.R(f.x,f.y),h,b),l=md(l,m,b),h=ld(new dvt.R(f.x+f.a,f.y+f.b),h,b),h=md(h,m,b),f.x=l.x,f.y=l.y,f.a=h.x-l.x,f.b=h.y-l.y;e?(l=e.x,h=e.y,e.x=Math.min(e.x,f.x),e.y=Math.min(e.y,f.y),e.a=Math.max(l+e.a,f.x+f.a)-e.x,e.b=Math.max(h+e.b,f.y+f.b)-e.y):e=f}d||(d=a.oJ());for(n=0;n<d.length;n++)if(c=d[n],(c=a.pd(c))&&c.nc){l=c;h=b;f=new dvt.Z(Number.MAX_VALUE,Number.MAX_VALUE,-Number.MAX_VALUE,-Number.MAX_VALUE);
k=null;h&&(k=h.$f(l,l.ad));k||(k=l.ad());if(k){k=$e.Aha(k);for(var v=void 0,v=r=x=w=void 0,p=0;p<k.length;p++)v=k[p],w=Math.max(f.x+f.a,v.x),x=Math.max(f.y+f.b,v.y),r=Math.min(f.x,v.x),v=Math.min(f.y,v.y),f.x=r,f.y=v,f.a=w-r,f.b=x-v}k=new dvt.Z(f.x,f.y,f.a,f.b);w=null;h&&(w=h.$f(l,l.kf));null==w&&(w=l.kf());r=x=null;h&&(x=h.$f(l,l.SE),r=h.$f(l,l.TE));null==x&&(x=l.Qn);r||(r=l.$m);l=l.tg();w&&l&&(null!=x&&(l=Bl(l,x,r)),k.x=Math.min(f.x,l.x+w.x),k.y=Math.min(f.y,l.y+w.y),k.a=Math.max(f.x+f.a,l.x+w.x+
l.a)-k.x,k.b=Math.max(f.y+f.b,l.y+w.y+l.b)-k.y);f=k;if(h=c.Bd())c=c.getParent(),l=ld(new dvt.R(f.x,f.y),c,b),l=md(l,m,b),h=ld(new dvt.R(f.x+f.a,f.y+f.b),c,b),h=md(h,m,b),f.x=l.x,f.y=l.y,f.a=h.x-l.x,f.b=h.y-l.y;e?(l=e.x,h=e.y,e.x=Math.min(e.x,f.x),e.y=Math.min(e.y,f.y),e.a=Math.max(l+e.a,f.x+f.a)-e.x,e.b=Math.max(h+e.b,f.y+f.b)-e.y):e=f}return e}
function Bl(a,b,c){if(null==b&&!c)return a;var d=new dvt.R(a.x,a.y),e=new dvt.R(a.x+a.a,a.y),f=new dvt.R(a.x,a.y+a.b);a=new dvt.R(a.x+a.a,a.y+a.b);var h=new dvt.Tb;null!=b&&(c&&h.translate(-c.x,-c.y),h.rotate(b),c&&h.translate(c.x,c.y));b=h.ef(d);e=h.ef(e);f=h.ef(f);a=h.ef(a);h=Math.min(Math.min(b.x,e.x),Math.min(f.x,a.x));c=Math.min(Math.min(b.y,e.y),Math.min(f.y,a.y));return new dvt.Z(h,c,Math.max(Math.max(b.x,e.x),Math.max(f.x,a.x))-h,Math.max(Math.max(b.y,e.y),Math.max(f.y,a.y))-c)}
function md(a,b,c){for(var d=b.Z3(),e=a,f=d.length-1;0<=f;f--){b=d[f];a=b.sb().clone();var h=null,k=null;c&&(h=c.$f(b,b.qa),k=c.$f(b,b.pa));null!=h&&(a.le=h);null!=k&&(a.fe=k);a.fF();e=a.ef(e)}return e}function ld(a,b,c){for(var d=b.Z3(),e=a,f=0;f<d.length;f++){b=d[f];a=b.sb().clone();var h=null,k=null;c&&(h=c.$f(b,b.qa),k=c.$f(b,b.pa));null!=h&&(a.le=h);null!=k&&(a.fe=k);e=a.ef(e)}return e}
q.EY=function(a,b,c,d,e){var f=this.Qa,h=f.pe().a/2,k=f.pe().b/2;c=h-(c+a)*e;d=k-(d+b)*e;a=h-a*e;b=k-b*e;this.yr&&(k=Pa(this),-k.x*e<c?(h=c+k.x*e,c-=h,a+=h):-k.x*e>a&&(h=-k.x*e-a,c-=h,a+=h),-k.y*e<d?(e=d+k.y*e,d-=e,b+=e):-k.y*e>b&&(e=-k.y*e-b,d-=e,b+=e));f.hY(c);f.iY(d);f.fY(a);f.gY(b)};function qd(a){var b={};b.top=a.top;b.right=a.right;b.bottom=a.bottom;b.left=a.left;return b}function wb(a){var b={};b.top=a.top;b.right=a.right;b.bottom=a.bottom;b.left=a.left;return b}q.MI=function(){};
function rd(a,b){var c=b.Ab()?b.rp():null;c&&a.pF(c.top,c.right,c.bottom,c.left);c=Kd.LQ(b.Sg());a.we=c;a.Uv=c;c=Kd.LQ(b.hi());a.L_=c;a.Vv=c;a.Tu(Kd.LQ(b.tg()));a.aD=!0}
function zl(a,b,c,d){var e=a.tg(),e=Kd.qib(e),f=a.kf();if(e&&f){c=new dvt.R(f.x-c.x,f.y-c.y);var f=a.Qn,h=Kd.SQa(a.$m);d?(d.N(dvt.G.mD,b,b.tg,b.Tu,e),b.kf()?d.N(dvt.G.lG,b,b.kf,b.Dg,c):b.Dg(c),null!=f&&d.N(dvt.G.V,b,b.SE,b.TI,f),h&&(b.$m?d.N(dvt.G.lG,b,b.TE,b.uF,h):b.uF(h))):(b.Tu(e),b.Dg(c),b.Rfa(a.WW(),a.xz),null!=f&&b.TI(f),h&&b.uF(h))}}function Fg(a,b){this.Init(a,b)}dvt.v.D(Fg,dvt.QN,"DvtBaseDiagramKeyboardHandler");q=Fg.prototype;q.Init=function(a,b){Fg.C.Init.call(this,a,b);this.L=a};
q.Na=function(){return this.L};q.iF=function(a){return a.keyCode==dvt.KeyboardEvent.Qh?!1:this.Vi(a)&&!a.ctrlKey};q.Nu=function(a){return a.keyCode==dvt.KeyboardEvent.ni&&a.ctrlKey};q.TW=function(a,b,c){b=b.keyCode;if(!c||1>c.length||!a)return null;var d=c[0];a=a.rf();a=a.x+a.a/2;for(var e=0;e<c.length;e++){var f=c[e],h=f.rf(),h=h.x+h.a/2;if(b==dvt.KeyboardEvent.TA&&h<=a||b==dvt.KeyboardEvent.FA&&h>=a){d=f;break}}return d};
q.dea=function(a,b,c,d){if(!d)return null;if(!b)return d[0];if(!a)return b;for(var e=0;e<d.length;e++){var f=d[e],h=f,k=a,l=f,m=this.CN(l.Re?l.Re():l.getData().Re()),l=this.CN(l.Ad?l.Ad():l.getData().Ad()),m=k==m?l:m,k=Cl(k),m=Cl(m),k=Math.atan2(m.y-k.y,m.x-k.x),k=0>k?k+2*Math.PI:k;h.Yka=k;m=h=f;k=this.CN(m.Re?m.Re():m.getData().Re());m=this.CN(m.Ad?m.Ad():m.getData().Ad());k=Cl(k);m=Cl(m);h.lO=Math.sqrt(Math.pow(m.x-k.x,2)+Math.pow(m.y-k.y,2));h=f;f=a==this.CN(f.Ad?f.Ad():f.getData().Ad())?1:0;h.ZZ=
f}d.sort(Dl());for(a=0;a<d.length;a++)e=d[a],e.Yka=void 0,e.lO=void 0,e.ZZ=void 0;c=c.keyCode==dvt.KeyboardEvent.Tf?!0:!1;for(e=a=0;e<d.length;e++)if(d[e]===b){a=c?e==d.length-1?0:e+1:0==e?d.length-1:e-1;break}return d[a]};q.CN=function(){return null};function Cl(a){a=a.rf();return new dvt.R(a.x+a.a/2,a.y+a.b/2)}function Dl(){return function(a,b){var c=a.Yka,d=b.Yka,e=-1;!El(c,d)&&c>d?e=1:El(c,d)&&(a.lO>b.lO?e=1:b.lO==a.lO&&a.ZZ>b.ZZ?e=1:b.lO==a.lO&&a.ZZ==b.ZZ&&(e=0));return e}}
function El(a,b){var c=1E-7>=Math.abs(a-b);c||(c=1E-7>=Math.abs(2*Math.PI+Math.min(a,b)-Math.max(a,b)));return c}function ie(a,b,c){this.Init(a,b,c)}dvt.v.D(ie,dvt.la,"DvtBaseDiagramNode");q=ie.prototype;q.Init=function(a,b,c){ie.C.Init.call(this,a,null,b);this.L=c;this.Lg=this.Sm=!1;this.pQ=!0;this.Eb;this.I0;this.Qn;this.$m;this.Cr;this.On};q.Na=function(){return this.L};q.getData=function(){return null};q.Sg=function(){return this.hi()};q.hi=function(){return new dvt.Z(0,0,this.getWidth(),this.getHeight())};
q.Dg=function(a){if(a){this.I0=a;var b=this.Eb;this.tg();b&&(a=bf(a,this.Qn,this.$m),b.rb(a))}};q.kf=function(){return this.I0};q.tg=function(){return null};q.Tu=function(){};q.rp=function(){return null};q.pF=function(){};q.Ab=function(){return this.Sm};q.Di=function(a){this.Sm=a};q.wb=function(){return this.Lg};ie.prototype.isSelected=ie.prototype.wb;q=ie.prototype;q.kc=function(a){this.Lg=a};q.mj=function(a){this.pQ=a};q.tb=function(){return this.Na().Oo()&&this.pQ};q.f5=function(a){this.ig=a};
q.lob=function(){return this.ig};q.TI=function(a){this.Qn=a;var b=this.Eb;this.tg();b&&(a=bf(this.kf(),a,this.$m),b.rb(a))};q.SE=function(){return this.Qn};q.uF=function(a){this.$m=a;var b=this.Eb;this.tg();b&&(a=bf(this.kf(),this.Qn,a),b.rb(a))};q.TE=function(){return this.$m};function bf(a,b,c){var d=new dvt.Tb;null!=b&&(c&&d.translate(-c.x,-c.y),d.rotate(b),c&&d.translate(c.x,c.y));a&&d.translate(a.x,a.y);return d}
q.gD=function(a,b,c){c?(c.N(dvt.G.V,this,this.qa,this.ga,a),c.N(dvt.G.V,this,this.pa,this.wa,b)):this.Ma(a,b)};function ud(a,b){var c,d;b&&(c=b.$f(a,a.qa),d=b.$f(a,a.pa));null==c&&(c=a.qa());null==d&&(d=a.pa());return new dvt.R(c,d)}q.Fd=function(){return null};q.rf=function(a){var b=this.hi(a);a=this.Ld(new dvt.R(b.x,b.y));b=this.Ld(new dvt.R(b.x+b.a,b.y+b.b));return new dvt.Z(a.x,a.y,b.x-a.x,b.y-a.y)};q.Jm=function(){return this.Ua()};q.Sf=function(){};q.Qd=function(){};q.Kd=function(){};q.Xd=function(){return null};
function Eb(a,b){a.Cr||(a.Cr=[]);a.Cr.push(b)}function Fb(a,b){a.On||(a.On=[]);a.On.push(b)}q.Rfa=function(){};q.Bd=function(){return null};function td(a,b){if(a.qc){var c=b?b.$f(a.qc,a.qc.qa,!0):a.qc.qa(),d=b?b.$f(a.qc,a.qc.pa,!0):a.qc.pa();return new dvt.R(c,d)}return null}function Md(a,b,c){this.Init(a,b,c)}dvt.v.D(Md,dvt.la,"DvtBaseDiagramLink");q=Md.prototype;
q.Init=function(a,b,c){Md.C.Init.call(this,a,null,b);this.L=c;this.uG;this.zl;this.MB;this.Eb;this.I0;this.Qn;this.$m;this.Lg=!1;this.pQ=!0;this.ba;this.Ej;this.Kj};q.Na=function(){return this.L};q.e5=function(){};q.at=function(){return null};q.q5=function(){};q.Omb=function(){return this.Kj};Md.prototype.getStartConnector=Md.prototype.Omb;Md.prototype.Xkb=function(){return this.Ej};Md.prototype.getEndConnector=Md.prototype.Xkb;q=Md.prototype;q.XI=function(a){this.ba=a};q.Mc=function(){return this.ba};
q.TI=function(a){this.Qn=a;var b=this.Eb;this.tg();b&&(a=Fl(this.kf(),a,this.$m),b.rb(a))};q.SE=function(){return this.Qn};q.uF=function(a){this.$m=a;var b=this.Eb;this.tg();b&&(a=Fl(this.kf(),this.Qn,a),b.rb(a))};q.TE=function(){return this.$m};q.kf=function(){return this.I0};q.Dg=function(a){if(a){this.I0=a;var b=this.Eb;this.tg();b&&(a=Fl(a,this.Qn,this.$m),b.rb(a))}};q.tg=function(){return null};q.Tu=function(){};q.f4=function(){return 0};q.x3=function(){return 0};q.mj=function(a){this.pQ=a};
q.tb=function(){return this.Na().Oo()&&this.pQ};q.wb=function(){return this.Lg};Md.prototype.isSelected=Md.prototype.wb;q=Md.prototype;q.kc=function(a){this.Lg=a};q.WI=function(a){this.bj=a};q.NUa=function(){return this.bj};q.ZM=function(){};q.bA=function(){return 1};Md.prototype.getLinkWidth=Md.prototype.bA;q=Md.prototype;q.cY=function(){};q.vM=function(){return"solid"};q.bY=function(){};q.VE=function(){return null};q.Gu=function(){return null};q.xha=function(){return this.vM()};q.JA=function(){return this.bA()};
q.bAa=function(){return this.VE()};function Rd(a,b,c,d,e){if(c||e){var f;e||(f=a.ba.Ud().clone(),f.bo(dvt.Xc.Qt),f.If(!1));if(c=Sd.Nya(a.u(),c,e,f,a))a.ba.A(c),Sd.rT(c,0,e,b,d);return c}}
q.be=function(a){this.uG=a;$e.e7(a)?(this.MB=a,this.zl=$e.Mya(a)):(this.zl=a,this.MB=$e.c6(a));this.ba&&this.ba instanceof dvt.vb&&(this.ba.ut(this.MB),this.Ej?Sd.rT(this.Ej,this.at(),this.Gu(Sd.CS),this.zl,1):this.Ej=Rd(this,this.zl,this.at(),1,this.Gu(Sd.CS)),this.Kj?Sd.rT(this.Kj,this.Mu(),this.Gu(Sd.jT),this.zl,0):this.Kj=Rd(this,this.zl,this.Mu(),0,this.Gu(Sd.jT)));var b=a=null;this.Kg&&this.Kg.WL instanceof dvt.vb&&this.Kg.WL.ut(this.MB);this.Kg&&(a=this.Kg.Qz)&&Sd.rT(a,this.Mu(),this.Gu(Sd.jT),
this.zl,0);this.Kg&&(b=this.Kg.Pz)&&Sd.rT(b,this.at(),this.Gu(Sd.CS),this.zl,1);this.wx&&this.wx.WL instanceof dvt.vb&&this.wx.WL.ut(this.MB);this.YV&&this.YV.setPosition(Vd(this));this.AU&&this.AU.setPosition(Wd(this))};q.ad=function(){return this.uG};function Vd(a){return a.zl?new dvt.R(a.zl[0],a.zl[1]):null}function Wd(a){if(!a.zl)return null;var b=a.zl.length;return new dvt.R(a.zl[b-2],a.zl[b-1])}
function Fl(a,b,c){var d=new dvt.Tb;null!=b&&(c&&d.translate(-c.x,-c.y),d.rotate(b),c&&d.translate(c.x,c.y));a&&d.translate(a.x,a.y);return d}q.MY=function(a,b,c){b||0==b||(b=1);c||0==c||(c=0);c=this.JA()+c;a=new dvt.ya(a,b,c);return new Gl(this.u(),this.MB,a)};
function Pd(a,b,c,d){b=a.MY(b,c,d);a.Kj&&a.Mu()&&(c=a.Mu(),d=Hl(b,a.zl,c,a.Gu(Sd.jT),a,0),b.Qz&&b.removeChild(b.Qz),b.Qz=d,b.vsa=c,b.A(b.Qz));a.Ej&&a.at()&&(c=a.at(),a=Hl(b,a.zl,c,a.Gu(Sd.CS),a,1),b.Pz&&b.removeChild(b.Pz),b.Pz=a,b.usa=c,b.A(b.Pz));return b}q.tY=function(a,b){var c=this.xha(),c=$e.FY(c);a.bo(c,$e.F6(c,b),$e.G6(c,b))};
function Od(a,b){if(a){var c=null;b.ic&&(c=b.ic());if(c){var d=a.Ud()?a.Ud().clone():null,e=a.fd()?a.fd().clone():null;d&&d.Ew&&(d.Ew(c),a.Ga(d));e&&e.Ew&&(e.Ew(c),a.ra(e))}}}q.Fd=function(){return null};q.rf=function(a){return this.aa(a)};q.Jm=function(){return this.Ua()};q.Sf=function(){};q.Qd=function(){};q.Kd=function(){};q.Xd=function(){return null};q.Rfa=function(){};q.Bd=function(){return null};var Kd={};dvt.v.D(Kd,dvt.v,"DvtDiagramLayoutUtils");
Kd.Fnb=function(a){for(var b=Kd.Mlb(a),c=Math.max(b.w,b.h),b=a.Bg(),d=a.Ju(),e=Math.floor(Math.sqrt(b)),f=0,f=(f=a.ln())&&f.padding?f.padding:0<d?c:.25*c,c=c+f,d=-(Math.ceil(b/e)-1)*c/2,f=-(e-1)*c/2,h=0;h<b;h++)Kd.eib(a.ZE(h),d+c*Math.floor(h/e),f+h%e*c)};Kd.Mlb=function(a){for(var b=a.Bg(),c=0,d=0,e=0;e<b;e++){var f=a.ZE(e),h=f.Rf(),c=Math.max(h.w,c),d=Math.max(h.h,d);if(f=f.tg())c=Math.max(f.w,c),d=Math.max(h.h+f.h,d)}return new xb(0,0,c,d)};
Kd.eib=function(a,b,c){var d=a.hi();a.setPosition(new sd(b-d.x-.5*d.w,c-d.y-.5*d.h));Kd.Qpb(a)};Kd.Qpb=function(a){var b=a.Rf(),c=a.ui(),d=a.tg();d&&a.Dg(new sd(b.x+c.x+.5*(b.w-d.w),b.y+c.y+b.h))};Kd.LQ=function(a){return void 0===a||null==a?null:new xb(a.x,a.y,a.a,a.b)};Kd.TQa=function(a){return void 0===a||null==a?null:new sd(a.x,a.y)};Kd.qib=function(a){return a?new dvt.Z(a.x,a.y,a.w,a.h):null};Kd.SQa=function(a){return a?new dvt.R(a.x,a.y):null};
function Gl(a,b,c){Gl.C.Init.call(this,a);this.Init(a,b,c)}dvt.v.D(Gl,dvt.la,"DvtDiagramLinkUnderlay");Gl.prototype.Init=function(a,b,c){b||(b=["M",0,0,"L",1,0]);this.Ss=c;this.Ss||(this.Ss=new dvt.ya("#ffffff",1,1));this.WL=new dvt.vb(a,b);this.WL.Ga(c);this.WL.ra(null);this.A(this.WL);this.usa=this.Pz=this.vsa=this.Qz=null};function Hl(a,b,c,d,e,f){a=Sd.Nya(a.u(),c,d,a.Ss,e);Sd.rT(a,0,d,b,f);return a}
Gl.prototype.Ga=function(a,b){this.Ss=a;dvt.B.Wa()&&dvt.B.mq()&&1==dvt.B.YQ()&&a.If(!0);this.WL.Ga(a);if(this.Qz){var c=a.clone();c.bo(dvt.Xc.Qt);c.If(!1);if(this.vsa==Sd.R5||this.vsa==Sd.S5)c.Xa(b),this.Qz.fb(a.ic());this.Qz.Ga(c)}if(this.Pz){c=a.clone();c.bo(dvt.Xc.Qt);c.If(!1);if(this.usa==Sd.R5||this.usa==Sd.S5)c.Xa(b),this.Pz.fb(a.ic());this.Pz.Ga(c)}};Gl.prototype.Ud=function(){return this.Ss};var $e={};dvt.v.D($e,dvt.v,"DvtDiagramLinkUtils");
$e.FY=function(a){var b=dvt.Xc.Qt;switch(a){case "dash":b=dvt.Xc.VC;break;case "dot":b=dvt.Xc.PY;break;case "dashDot":b=dvt.Xc.Yga}return b};$e.F6=function(a,b){if(dvt.Xc.Qt==a)return null;if(dvt.Xc.VC==a)return b?"8,2":"6,4";if(dvt.Xc.PY==a)return b?"4,1":"2,3";if(dvt.Xc.Yga==a)return b?"10,1,4,1":"8,3,2,3"};$e.G6=function(a,b){return b&&dvt.Xc.Qt!=a?1:null};$e.Rmb=function(a){var b=$e.FY(a);return{_type:a,strokeDasharray:$e.F6(b,void 0),strokeDashoffset:$e.G6(b,void 0)}};
$e.fqb=function(a){return a?(a=a.split(/[\s,]+/),0<a.length%2&&(a=a.concat(a)),a.toString()):a};$e.Ckb=function(a){if(a){a=a.split(/[\s,]+/);for(var b="",c=0;c<a.length;c++){var d=dvt.j.pk(dvt.Nd.trim(a[c])),b=b+(0==c%2?d+2:2<=d?d-2:0);c<a.length-1&&(b+=", ")}return b}return null};$e.c6=function(a){var b=[];if(a)for(var c=0;c<a.length;c+=2)0==c?b.push("M"):b.push("L"),b.push(a[c]),b.push(a[c+1]);return b};$e.Mya=function(a){var b=[];if(a)for(var c=0;c<a.length;c++)isNaN(a[c])||b.push(a[c]);return b};
$e.e7=function(a){return a&&0<a.length?isNaN(a[0]):!1};$e.Aha=function(a){var b=[];a=$e.e7(a)?$e.Mya(a):a;for(var c=0;c<a.length;c+=2)b.push(new dvt.R(a[c],a[c+1]));return b};var Sd={};dvt.v.D(Sd,dvt.v,"DvtDiagramLinkConnectorUtils");Sd.CS="endConnector";Sd.jT="startConnector";Sd.Cya="arrowOpen";Sd.R5="arrow";Sd.S5="arrowConcave";Sd.Eya="rectangle";Sd.Fya="rectangleRounded";Sd.Dya="circle";
Sd.Nya=function(a,b,c,d,e){if(c)return Sd.gYa(c,e);c=e.JA();switch(b){case Sd.R5:return Sd.hYa(a,c,e.VE());case Sd.S5:return Sd.iYa(a,c,e.VE());case Sd.Cya:return Sd.nYa(a,c,d);case Sd.Dya:return Sd.fYa(a,c,d);case Sd.Eya:return Sd.Sya(a,c,d);case Sd.Fya:return Sd.tYa(a,c,d)}return null};Sd.rT=function(a,b,c,d,e){b=Sd.TXa(a,c,d,e);a.rb(b)};
Sd.TXa=function(a,b,c,d){var e=-1,f=0,h=0,k=0;c&&(f=c.length,1===d?(2<=f&&(h=c[f-2],k=c[f-1]),4<=f?(e=c[f-4],f=c[f-3]):(e=h-1E-4,f=k)):(2<=f&&(h=c[0],k=c[1]),4<=f?(e=c[2],f=c[3]):(e=h+1E-4,f=k)));c=h;d=k;e=Sd.SXa(e,f,h,k);h=a.x8a;h||(h=a.sb().clone(),a.x8a=h);k=new dvt.Tb;b&&(b=Sd.fJa(a),f=a.oe(),a=a.Ae(),k.translate(-.5*b.a*f,-.5*b.b*a));k.rotate(e);k.translate(c,d);k.concat(h);return k};Sd.fJa=function(a){var b=a.W7a;b||(b=a.aa(),a.W7a=b);return b};
Sd.SXa=function(a,b,c,d){return Math.atan2(d-b,c-a)};Sd.iYa=function(a,b,c){b=6*Sd.V$(b);var d=.8*b;a=new dvt.mi(a,[-.22*b,-.5*d,.78*b,0,-.22*b,.5*d,0,0]);a.fb(c);return a};Sd.hYa=function(a,b,c){b=5*Sd.V$(b);var d=.8*b;a=new dvt.mi(a,[0,-.5*d,b,0,0,.5*d]);a.fb(c);return a};Sd.V$=function(a){return 1>=a?a:1+.5*(a-1)};Sd.nYa=function(a,b,c){b*=3;var d=c.getWidth();a=new dvt.Yw(a,[-b+d*Math.sqrt(2)/2,-b,d*Math.sqrt(2)/2,0,-b+d*Math.sqrt(2)/2,b]);a.Ga(c);a.ra(null);return a};
Sd.gSa=function(a){return 2*a};Sd.BTa=function(a){return 3*a};Sd.fYa=function(a,b,c){b=Sd.gSa(b);a=new dvt.Nm(a,b,0,b);a.Ga(c);a.ra(null);return a};Sd.Sya=function(a,b,c){b=Sd.BTa(b);a=new dvt.Rect(a,0,-b/2,b,b);a.Ga(c);a.ra(null);return a};Sd.tYa=function(a,b,c){a=Sd.Sya(a,b,c);a.JC(b);return a};Sd.gYa=function(a,b){var c=za(b.Na()),d=b.getData().Np;c.qx=d;c.QI(b,b.e3);d=b.pR();c.Nx=d;return K.KR(c,a,b)};Sd.hAa=function(a,b,c,d,e){return c?(b=Sd.fJa(a),a=a.oe(),.5*b.a*a):Sd.cva(b,e.JA(),d.getWidth())};
Sd.cva=function(a,b,c){switch(a){case Sd.Cya:return c*Math.sqrt(2);case Sd.R5:return a=Sd.V$(b),5*a;case Sd.S5:return a=Sd.V$(b),4.68*a;case Sd.Dya:return 2*Sd.gSa(c)+c/2;case Sd.Eya:case Sd.Fya:return Sd.BTa(c)+c/2;default:return 0}};
dvt.eg=function(a,b,c){this.Init(a,b,c)};ba("dvt.Diagram",dvt.eg);dvt.v.D(dvt.eg,ja);dvt.eg.prototype.Init=function(a,b,c){dvt.eg.C.Init.call(this,a,b,c);this.Xg=new Il;this.I=new Jl(a,this.bg,this);this.I.Qf(this);dvt.B.Wa()||this.I.Xr(new Kl(this,this.I));this.oc={};this.Aq=[];this.wG=[];this.$d={};this.ZA=[];this.V_=this.Kz=0};dvt.eg.newInstance=function(a,b,c){return new dvt.eg(a,b,c)};dvt.eg.newInstance=dvt.eg.newInstance;q=dvt.eg.prototype;
q.fT=function(){!this.Ks&&this.mh&&("none"!=this.qU&&(this.Bo={id:this.getId(),getId:function(){return this.id},options:this.F(),getOptions:function(){return this.options},panZoomMatrix:this.Qa.Oa.sb(),getPanZoomMatrix:function(){return this.panZoomMatrix},nodes:this.oc?Ll(this):{},roots:this.wG?Ml(this):[],links:this.$d?Nl(this):[],linkIds:this.oJ(),getNodes:function(){return this.nodes},getRoots:function(){return this.roots},getLinks:function(){return this.links},getLinkIds:function(){return this.linkIds}},
this.Bo.F=this.Bo.getOptions,this.Bo.gmb=this.Bo.getPanZoomMatrix,this.Bo.getId=this.Bo.getId,this.Bo.pTa=this.Bo.getNodes,this.Bo.smb=this.Bo.getRoots,this.Bo.VSa=this.Bo.getLinks,this.Bo.Dlb=this.Bo.getLinkIds),this.hz=this.Qa.xI(),this.mh=!1,this.xV=this.Qa);this.Ks||this.lja()};q.lja=function(){this.Sp=new dvt.la(this.u());this.xl=new dvt.la(this.u());this.Oz=new dvt.la(this.u());this.oc={};this.Aq=[];this.wG=[];this.$d={};this.ZA=[];this.iU=this.CL=this.YD=null};
q.Tv=function(){this.di&&(this.removeChild(this.di),this.di.xa());this.di=null;this.lc&&this.ab().Qf(this);this.wn||this.qs();this.lc=null;this.wn=!1};q.sg=function(a,b){var c=new dvt.gd(this.u(),null,a.ob()),d=b.gmb(),e=this.Qa.Oa.sb();d.Fe(e)||(this.Qa.Oa.rb(d),c.ja.N(dvt.G.aj,this.Qa.Oa,this.Qa.Oa.sb,this.Qa.Oa.rb,e));a.Io(b.smb(),this.wG?Ml(this):[]);a.Io(b.VSa(),this.$d?Nl(this):[]);a.add(c,1)};
function Ol(a,b){var c=b.nodes,d=b.id;if(c&&Pl(a,d))if(c instanceof Function&&(c=c()),Array.isArray(c))for(d=0;d<c.length;d++)Ol(a,c[d]);else if(c.then){a.V_++;var e=a.Kz;c.then(function(c){Ql(a,e,b,c)},function(){Ql(a,e,b,null)})}}function Ql(a,b,c,d){if(b===a.Kz){a.V_--;c.nodes=d;if(Array.isArray(d))for(b=0;b<d.length;b++)Ol(a,c.nodes[b]);0===a.V_&&a.Pt()}}
q.Fn=function(){dvt.eg.C.Fn.call(this);this.VS();this.V_=0;if(!this.mh&&!this.Ks){this.Kz++;var a=this.F().nodes;if(a)for(var b=0;b<a.length;b++)Ol(this,this.F().nodes[b])}0===this.V_&&this.Pt()};
q.Pt=function(a){var b=!1;if(!this.mh&&!this.Ks){Rl(this);Sl(this);var c=[],d;for(d in this.oc)c.push(d);b=0===c.length;this.u().YM([this])}if(b)Tl(this,a,b);else{this.contains(this.xV)||this.A(this.xV);var c=this.Bw(a),e=this,f=this.Kz;c.then(function(){f===e.Kz&&Tl(e,a,b)},function(){f===e.Kz&&(e.removeChild(e.xV),e.xV=null,e.mh=!0,this.hz=null)})}};
function Tl(a,b,c){var d;if(!c){a.removeChild(a.xV);a.EH();a.NB();a.dC();if(d=null==a.rm)a.rm=Na(a,b,void 0,void 0);var e=a.Qa;if(a.mh)a.Ks&&(f=a.PC(b,a.rm),h=a.yr?Pa(a):f?f:a.rm,e.hga(!0),e.Dt(null,h),e.hga(a.$H));else{a.PC(b,a.rm);if(!a.Ks){var f=a.yr?!0:!1,h=f?Pa(a):a.rm;f&&e.LWa();e.Dt(null,h)}e.NC(a.LB);e.VI(a.qI());e.oY(a.$H);e.hga(a.$H)}}a.xV=null;a.mh||(a.fr(!0),dvt.B.xj()&&a.D0&&!a.Bo?a.lc=dvt.pc.RE(a.u(),a.D0,a,null,a.ob()):"none"!=a.qU&&a.Bo&&(a.di=new dvt.la(a.u(),"Delete Container"),
a.A(a.di),e=new Ul(a.u(),a.di,a.Bo,a),e.Io([a.Bo],[a]),a.lc=e.nw()),a.lc?(a.ab().qe(),a.ab().ll(a),a.lc.lg(a.Tv,a),a.lc.play()):a.Tv());a.mh=!0;a.hz=null;tb(a,c);a.LB&&(c=a.rm,null!=c&&(b=a.Qa.wg(b),a.EY(c.x,c.y,c.a,c.b,b)));a.yr=null;a.iV=null;d&&(a.rm=null)}
q.vf=function(a){dvt.eg.C.vf.call(this,a);this.wwa(this.W);this.LB="none"!=this.W.panning;this.$H="none"!=this.W.zooming;this.Ifa("hidden");this.qU=this.W.animationOnDataChange;this.g5("auto"==this.W.animationOnDisplay?dvt.pc.OC:null);this.py(this.W.selectionMode);this.d5(this.W.emptyText?this.W.emptyText:dvt.H.Bf(this.W,"labelNoData",dvt.H.Ha,"NO_DATA"))};dvt.eg.Jr=function(a){return(new Il).Jr(a)};q=dvt.eg.prototype;q.WE=function(){var a=this.F().maxZoom,a=parseFloat(a);return 0<a?a:1};
q.oI=function(){var a=this.F().minZoom;if(a){var b=parseFloat(a);0<b&&(a=Math.min(b,this.WE()));return a}return 0};q.qI=function(){return this.F().panDirection};q.ob=function(){return dvt.Ta.Pr(this.F().styleDefaults.animationDuration)/1E3};q.bg=function(a){var b=a.type;"categoryHighlight"==b?this.EH(!0):"selection"==b&&(this.F().selection=a.selection);a&&this.dispatchEvent(a)};function Rl(a){var b=a.F().nodes;b&&(Vl(a,null,b),a.gv||(b=a.F().expanded,a.gv=b?"all"===b?a.Aq:b:[]))}
function Sl(a){var b=a.F().links;if(b){var c=a.F().styleDefaults.linkDefaults;Wl(c);c.style=dvt.ac.Vd(c.style,c._style);for(var d=0;d<b.length;d++){var e=b[d],f;f=a;var h=e,k=f.ka(h.startNode),l=f.ka(h.endNode);if(k&&l||!f.iU)f=!1;else if(k=k?k.getId():Xl(f,h.startNode),l=l?l.getId():Xl(f,h.endNode),k&&l&&k!==l){var m="_plL"+k+"_L"+l;f.CL||(f.CL={});f.CL[m]?f.CL[m]._links.push(h):f.CL[m]={id:m,startNode:k,endNode:l,_links:[h]};f=!0}else f=!1;f||(Wl(e),e=dvt.ac.Vd(e,c),e=new Yl(a.u(),a,e,!1),f=e.getId(),
a.ZA.push(f),e.Ova()||(h=a.ka(e.Re()),k=a.ka(e.Ad()),Eb(h,f),Fb(k,f),e.ta(),a.$d[f]=e))}if(a.CL){b=a.F().styleDefaults.promotedLink;Wl(b);b.style=dvt.ac.Vd(b.style,b._style);for(var n in a.CL)e=a.CL[n],e=dvt.ac.Vd(e,b),e=new Yl(a.u(),a,e,!0),f=e.getId(),h=a.ka(e.Re()),k=a.ka(e.Ad()),Eb(h,f),Fb(k,f),e.ta(),a.ZA.push(f),a.$d[f]=e}}}function Wl(a){a&&null!=a.style&&(a.style instanceof Object?null==a.style._type&&(a.style._type="customStyle"):a.style=$e.Rmb(a.style))}
q.Bw=function(a){for(var b=this.F().layout,c=vb(this),d={},e=0;e<this.wG.length;e++){var f=this.wG[e];if(this.ka(f)){d[f]=!0;var h=this.Lw(this.ka(f),null,this.mh?!1:!0,c);Zl(this,this.ka(f),h,c,d);c.ZL(h)}}for(var k in this.$d)if(e=this.pd(k))f=e.getData().startNode,h=e.getData().endNode,d[f]&&d[h]&&ob(c,this.jJ(e,f,h,null,c));this.hz&&(d=this.hz,k=this.M0?this.M0:new dvt.R(0,0),d=new xb(d.x-k.x,d.y-k.y,d.a,d.b),c.hz=d);if(b&&"function"==typeof b){var l=this;(b=b(c))||(b={then:function(a){a()}});
this.Afa(0);var m=this.Kz;b.then(function(){if(l.Kz===m||l.Ks){l.Afa(1);for(var b=c.Bg(),d=0;d<b;d++)l.MI(c.ZE(d));l.AF(c,a,!0)}},function(){});return b}this.JN("dvt.Diagram: Layout function is not defined",1)};q.Afa=function(a){this.mh||(this.Sp.T(a),this.xl.T(a))};q.ka=function(a){return this.oc[a]};q.pd=function(a){return this.$d[a]};q.oJ=function(){return this.ZA};function Nl(a){var b=[],c;for(c in a.$d)b.push(a.$d[c]);return b}q.pJ=function(){return this.Aq};
function Ll(a){var b={},c;for(c in a.oc)b[c]=a.oc[c];return b}function $l(a){var b=[],c;for(c in a.oc)b.push(a.oc[c]);return b}function Ml(a){for(var b=[],c=0;c<a.wG.length;c++){var d=a.oc[a.wG[c]];d&&b.push(d)}return b}
q.uk=function(a){dvt.eg.C.uk.call(this,a);switch(a.Zn()){case dvt.xd.H7:if(this.LB){var b=a.GB,c=this.rm?this.rm:Na(this,a.ja,void 0,void 0);this.EY(c.x,c.y,c.a,c.b,b)}break;case dvt.xd.L7:this.yr||(c=this.rm?this.rm:Na(this,a.ja,void 0,void 0),a.KWa(c));break;case dvt.xd.QJ:if(this.F().zoomRenderer&&a.sL!==a.GB)for(b in this.oc){var c=this.ka(b),d=a;if(c.L.F().zoomRenderer){var e=c.um(d.sL),d=c.um(d.GB);am(c,c.L.F().zoomRenderer,d,e)}}}};q.HVa=function(){};
q.XE=function(a){var b=[],c;for(c in this.$d){var d=this.pd(c),e=d.Re(),f=d.Ad();e!=a&&f!=a||!d.nc||b.push(d)}return b};q.gm=function(){return dvt.H.va(dvt.H.Ha,"DIAGRAM")};q.NB=function(){if(this.W.selection&&this.Oo()){var a=[],b;for(b in this.oc)a.push(this.ka(b));for(var c in this.$d)a.push(this.pd(c));this.Xh().tt(this.W.selection,a)}};
q.EH=function(a){a&&this.I.ll(this);this.YD&&(this.K2(!1,this.YD),this.YD=null);var b=this.W.highlightedCategories;if(b&&0!==b.length){var c="any"==this.W.highlightMatch;this.YD={};var d=[],e;for(e in this.oc){var f=this.ka(e),h=c?dvt.na.yw(f.Xd(),b):dvt.na.p4(f.Xd(),b);h&&(this.YD[f.getId()]=f,d.push(f))}bm(this,d);var d=[],k;for(k in this.$d)if(e=this.pd(k),h=c?dvt.na.yw(e.Xd(),b):dvt.na.p4(e.Xd(),b))this.YD[e.getId()]=e,d.push(e);"linkAndNodes"==this.W.linkHighlightMode&&cm(this,d);this.K2(!0,
this.YD);if(a){var l=this;setTimeout(function(){l.ab().Qf(l)},0)}}else a&&this.I.Qf(this)};function bm(a,b){var c=a.W.nodeHighlightMode;if("node"!=c){for(var d="nodeAndIncomingLinks"==c||"nodeAndLinks"==c,c="nodeAndOutgoingLinks"==c||"nodeAndLinks"==c,e=[],f=0;f<b.length;f++)for(var h=b[f],k=d&&h.On?h.On:[],k=c&&h.Cr?k.concat(h.Cr):k,h=0;h<k.length;h++){var l=k[h];a.YD[l]=a.pd(l);e.push(a.pd(l))}cm(a,e)}}
function cm(a,b){for(var c=0;c<b.length;c++){var d=b[c],e=d.Re(),d=d.Ad();a.YD[e]=a.ka(e);a.YD[d]=a.ka(d)}}
q.K2=function(a,b){var c;if(this.Aq.length==this.wG.length){c=a?this.W.styleDefaults._highlightAlpha:1;this.Sp.T(c);this.xl.T(c);for(var d in b)a?this.Oz.A(b[d]):b[d]instanceof Yl?this.Sp.A(b[d]):b[d]instanceof dm&&this.xl.A(b[d])}else if(a){c=this.W.styleDefaults._highlightAlpha;var e={};for(d in b)b[d].T(1),e[d]=!0;for(var f in this.oc)e[f]||this.ka(f).T(c);for(var h in this.$d)e[h]||this.pd(h).T(c)}else{for(f in this.oc)this.ka(f).T(1);for(h in this.$d)this.pd(h).T(1)}};
q.Ve=function(a){this.W.highlightedCategories=dvt.ac.clone(a);this.EH()};dvt.eg.prototype.highlight=dvt.eg.prototype.Ve;dvt.eg.prototype.select=function(a){this.W.selection=dvt.ac.clone(a);this.NB()};dvt.eg.prototype.select=dvt.eg.prototype.select;dvt.eg.prototype.ph=function(){this.Rd||(this.Rd=new em(this));return this.Rd};dvt.eg.prototype.getAutomation=dvt.eg.prototype.ph;
dvt.eg.prototype.JN=function(a,b){var c=this.F()._logger;if(c)switch(b){case 1:c.error&&c.error(a);break;case 2:c.warn&&c.warn(a);break;case 3:c.info&&c.info(a);break;default:c.log&&c.log(a)}};dvt.eg.prototype.ky=function(a,b){var c=this.ka(a);c&&c.ky(b)};dvt.eg.prototype.processDefaultHoverEffect=dvt.eg.prototype.ky;dvt.eg.prototype.II=function(a,b){var c=this.ka(a);c&&c.II(b)};dvt.eg.prototype.processDefaultSelectionEffect=dvt.eg.prototype.II;
dvt.eg.prototype.FC=function(a,b){var c=this.ka(a);c&&c.FC(b)};dvt.eg.prototype.processDefaultFocusEffect=dvt.eg.prototype.FC;dvt.eg.prototype.MI=function(a){if(!a.aD){var b=this.ka(a.getId());if(b.Ab()){for(var c=vb(this),d=a.ze(),e=0;e<d.length;e++){var f=d[e];this.MI(f);c.ZL(f)}this.AF(c)}b.ta();rd(a,b)}};
function Vl(a,b,c){var d=a.F().styleDefaults.nodeDefaults;fm(d,"backgroundStyle");fm(d,"containerStyle");for(var e=0;e<c.length;e++){var f=c[e];fm(f,"backgroundStyle");fm(f,"containerStyle");var f=dvt.ac.Vd(f,d),h=new dm(a.u(),a,f),k=h.getId();if(b){var l=b,m=k;l.dj||(l.dj=[]);l.dj.push(m);h.RI(b.getId())}else a.wG.push(k);a.Aq.push(k);f.nodes&&(Pl(a,k)?(h.Di(!0),Vl(a,h,f.nodes)):(f=a,l=h,f.iU||(f.iU=[]),f.iU.push(l)));h.Ova()||(b&&b.YC()?b.YC().A(h):a.xl.A(h),a.oc[k]=h)}}
function fm(a,b){!a||null==a[b]||a[b]instanceof Object||(a[b]=dvt.j.OQ(a[b]))}dvt.eg.prototype.UI=function(a,b){var c=-1;this.gv&&(c=dvt.na.kb(this.gv,a));(!b&&-1<c||b&&0>c)&&this.dispatchEvent(new dvt.Za.Ih(b?"beforeExpand":"beforeCollapse",a))};dvt.eg.prototype.expand=function(a){this.gv||(this.gv=[]);0>dvt.na.kb(this.gv,a)&&(this.gv.push(a),this.ta(this.F(),this.xb,this.Jb),this.dispatchEvent(new dvt.Za.Ih("expand",a)))};dvt.eg.prototype.expand=dvt.eg.prototype.expand;
dvt.eg.prototype.collapse=function(a){var b=-1;this.gv&&(b=dvt.na.kb(this.gv,a));-1<b&&(this.gv.splice(b,1),this.ta(this.F(),this.xb,this.Jb),this.dispatchEvent(new dvt.Za.Ih("collapse",a)))};dvt.eg.prototype.collapse=dvt.eg.prototype.collapse;function Zl(a,b,c,d,e){if(b.Ab()){b=b.dj;for(var f=[],h=0;h<b.length;h++){var k=a.ka(b[h]);if(k.nc){e[k.getId()]=!0;var l=a.Lw(k,null,a.mh?!1:!0,d),m=l;d.oc[m.getId()]=m;l.ZR(c);f.push(l);Zl(a,k,l,d,e)}}c.Y4(f)}}
function Pl(a,b){var c=a.gv?a.gv:a.F().expanded;return c&&-1<dvt.na.kb(c,b)||c&&-1<dvt.na.kb(c,"all")}function Xl(a,b){function c(a,b){if(a)for(var d=0;d<a.length;d++)if(a[d].id===b||c(a[d].nodes,b))return!0;return!1}for(var d=0;d<a.iU.length;d++){var e=a.iU[d];if(c(e.getData().nodes,b))return e.getId()}return null}dvt.eg.prototype.dC=function(){var a=this.ab().jf(),b=!1;if(a){var c;a instanceof dm?c=this.ka(a.getId()):a instanceof Yl&&(c=this.pd(a.getId()));b=a.Kd();c&&b&&c.Sf();this.ab().Fw(c)}};
dvt.eg.prototype.iib=function(){this.gv=null};dvt.eg.prototype.clearDisclosedState=dvt.eg.prototype.iib;dvt.H.fC(dvt.H.k6,{PROMOTED_LINK:"{0} link",PROMOTED_LINKS:"{0} links",PROMOTED_LINK_ARIA_DESC:"Indirect"});function gm(a,b){gm.C.constructor.call(this,a,b);this.Zrb();this.L=b}dvt.v.D(gm,dvt.vh,"DvtDiagramCategoryRolloverHandler");gm.prototype.Lha=function(a){return dvt.v.ti(this,function(){this.Kja(!0);this.L.bg(a)})};gm.prototype.Kha=function(a){return dvt.v.ti(this,function(){this.Lja();this.L.bg(a)})};
function Il(){this.Init({skyros:hm,alta:im})}dvt.v.D(Il,dvt.bb,"DvtDiagramDefaults");
var hm={skin:dvt.j.mf,emptyText:null,selectionMode:"none",animationOnDataChange:"none",animationOnDisplay:"none",maxZoom:1,highlightMatch:"all",nodeHighlightMode:"node",linkHighlightMode:"link",panning:"none",touchResponse:"auto",zooming:"none",_statusMessageStyle:new dvt.j(dvt.bb.Pm),styleDefaults:{animationDuration:500,hoverBehaviorDelay:200,_highlightAlpha:.1,nodeDefaults:{_containerStyle:new dvt.j("border-color:#abb3ba;background-color:#f9f9f9;border-width:.5px;border-radius:1px;padding-top:20px;padding-left:20px;padding-bottom:20px;padding-right:20px;"),labelStyle:dvt.bb.v6+
"color:#383A47",hoverInnerColor:"rgb(255,255,255)",hoverOuterColor:"rgba(0,0,0, .3)",selectionColor:"rgb(0,0,0)",icon:{width:10,height:10,fillPattern:"none",shape:"circle"}},linkDefaults:{startConnectorType:"none",endConnectorType:"none",width:1,_style:{_type:"solid"},hoverInnerColor:"rgb(255,255,255)",hoverOuterColor:"rgba(0,0,0, .3)",selectionColor:"rgb(0,0,0)",labelStyle:dvt.bb.v6+"color:#383A47",_hitDetectionOffset:4},promotedLink:{startConnectorType:"none",endConnectorType:"none",width:1,_style:{_type:"dot",
strokeDasharray:"2,3"},color:"#778999",hoverInnerColor:"rgb(255,255,255)",hoverOuterColor:"rgba(0,0,0, .3)",selectionColor:"rgb(0,0,0)",_hitDetectionOffset:4}}},im={};function Ul(a,b,c,d){this.Init(a,b,c,d)}dvt.v.D(Ul,dvt.sq,"DvtDiagramDataAnimationHandler");Ul.prototype.Init=function(a,b,c,d){Ul.C.Init.call(this,a,b);this.eqa=c;this.Kcb=d};Ul.prototype.ob=function(){return dvt.Ta.Pr(this.eqa.F().styleDefaults.animationDuration)/1E3};
Ul.prototype.Io=function(a,b){var c=!1;b&&0<b.length&&(c=b[0]instanceof Yl);if(c&&!this.u().B4()){var c=jm(a),d=jm(b),e,f,h={},k;for(k in c)if(e=c[k],f=d[k])if(!e.bj&&!f.bj||e.bj&&f.bj&&e.getId()==f.getId())f.sg(this,e);else{var l=e.bj?e.getData()._links.length:1,m=f.bj?f.getData()._links.length:1;l>m&&!h[e.getId()]?km(this,e,d,h,!0):l<m&&!h[f.getId()]&&km(this,f,c,h,!1)}else-1==dvt.na.kb(this.Kcb.oJ(),e.getId())&&e.Mj(this);for(k in d)e=c[k],f=d[k],e||-1!=dvt.na.kb(this.eqa.Dlb(),f.getId())||f.Ri(this)}else Ul.C.Io.call(this,
a,b)};function km(a,b,c,d,e){for(var f=[],h=b.getData()._links,k=0;k<h.length;k++){var l=c[h[k].id];l&&-1===dvt.na.kb(f,l)&&f.push(l)}if(0<f.length){if(e){if(f&&0!=f.length)for(c=0;c<f.length;c++)f[c].sg(a,b)}else if(f&&0!=f.length)for(c=dvt.na.copy(b.ad()),b.sg(a,f[0]),e=1;e<f.length;e++)h={id:"_fakeLink"+e+b.getId()},h=dvt.ac.Vd(h,b.getData()),h=new Yl(b.Na().u(),b.Na(),h,!0),h.ta(),h.be(c),h.sg(a,f[e],!0);d[b.getId()]=!0}}
function jm(a){for(var b={},c=0;c<a.length;c++){var d=a[c];if(d.bj)for(var e=d.getData()._links,f=0;f<e.length;f++)b[e[f].id]=d;else b[d.getId()]=d}return b}function Jl(a,b,c){this.Init(a,b,c);this.L=c}dvt.v.D(Jl,dvt.I,"DvtDiagramEventManager");q=Jl.prototype;q.uq=function(a,b,c){a=this.L.F();"dim"==a.hoverBehavior&&(b=b.Xd?b.Xd():[],a.highlightedCategories=c?b.slice():null,c=dvt.Za.GI(a.highlightedCategories,c),b=dvt.Ta.Pr(a.styleDefaults.hoverBehaviorDelay),this.KJ.bg(c,$l(this.L),b,"any"==a.highlightMatch))};
q.Nga=function(a,b){return new gm(a,b)};q.ol=function(a){var b=!0,c=a.keyCode,d=this.jf(),e=d instanceof dm?d.Ev:null;c!=dvt.KeyboardEvent.Qh&&this.CD?(e.JW(a),a.preventDefault()):c==dvt.KeyboardEvent.Qh&&e instanceof dvt.Ie?!a.shiftKey&&d.Kd()?(d.Qd(),e.JW(a),a.preventDefault(),this.CD=!0):(a.shiftKey&&this.CD?(this.mT(a,d),a.preventDefault()):(this.CD&&d.Sf(),b=Jl.C.ol.call(this,a)),this.CD=!1):c==dvt.KeyboardEvent.ni&&a.ctrlKey&&a.shiftKey?d&&d.hm&&d.hm(a):b=Jl.C.ol.call(this,a);return b};
q.LA=function(){var a=this.L.F();return"none"!==a.panning||"none"!==a.zooming?dvt.I.jG:a.touchResponse===dvt.I.Qy?dvt.I.Qy:dvt.I.QZ};q.Sw=function(a){return this.io(a,dvt.Sd.wN)};q.hD=function(a){return a==dvt.Sd.wN?!1:Jl.C.hD.call(this,a)};function Kl(a,b){this.Init(a,b)}dvt.v.D(Kl,Fg,"DvtDiagramKeyboardHandler");
Kl.prototype.Vi=function(a){var b=!1;switch(a.keyCode){case dvt.KeyboardEvent.Tw:case dvt.KeyboardEvent.cv:b=!0;break;case dvt.KeyboardEvent.TA:case dvt.KeyboardEvent.FA:b=a.altKey?!0:!1;break;default:b=Kl.C.Vi.call(this,a)}return b};Kl.prototype.mk=function(a){if(a.keyCode==dvt.KeyboardEvent.Qh){var b=this.yb.jf();if(b)return dvt.I.sc(a),b;b=Ml(this.Na());if(0<b.length)return dvt.I.sc(a),this.jI(b)}return Kl.C.mk.call(this,a)};Kl.prototype.CN=function(a){return this.Na().ka(a)};
function Yl(a,b,c,d){this.Init(a,b,c,d)}dvt.v.D(Yl,Md,"DvtDiagramLink");q=Yl.prototype;q.Init=function(a,b,c,d){Yl.C.Init.call(this,a,c.id,b);this.Nb=c;this.WI(d);this.L.Oo()&&this.setCursor("pointer");this.RI(lm(this,b))};q.getData=function(){return this.Nb};q.getId=function(){return this.getData().id};q.Re=function(){return this.getData().startNode};q.Ad=function(){return this.getData().endNode};q.tg=function(){var a=null;this.Eb&&(a=this.Eb.aa());return a};q.vM=function(){return this.getData().style};
q.bA=function(){return this.getData().width};q.VE=function(){return this.getData().color};q.Mu=function(){return this.getData().startConnectorType};q.at=function(){return this.getData().endConnectorType};q.f4=function(){return this.Mu()?Sd.cva(this.Mu(),this.JA(),this.JA()):0};q.x3=function(){return this.at()?Sd.cva(this.at(),this.JA(),this.JA()):0};
q.ta=function(){var a=this.Na(),b=this.Bd(),c=a.ka(this.Re()).Bd(),d=a.ka(this.Ad()).Bd();if(b){var e=a.ka(b).YC();b==c&&b==d?e.Ib(this,0):e.A(this)}else c||d?a.xl.A(this):a.Sp.A(this);b=this.getData();c=dvt.B.da(a.u())?dvt.ca.Kl:dvt.ca.Dp;b.label&&(d=b.labelStyle,e=dvt.ca.jr,a=new dvt.ca(a.u(),b.label,0,0),a.Bb(new dvt.j(d)),a.oy(c),a.AA(e),b=dvt.j.pk((new dvt.j(b.labelStyle)).getWidth()),0<b&&dvt.Ca.kd(a,b,Infinity,this)||this.A(a),this.Eb=a);this.cg("img");this.ir();this.L.ab().lb(this,this)};
q.be=function(a){!this.MB&&a&&mm(this.Na(),this.getData(),this);Yl.C.be.call(this,a)};
function mm(a,b,c){var d=c.MB;d||(d=["M",0,0,"L",0,0]);var e=b.id,f=b.color,h=b.width;a=b.style;c.wx=c.MY("#000000",0,b._hitDetectionOffset);c.Ib(c.wx,0);f=new dvt.ya(f,1,h);dvt.B.Wa()&&dvt.B.mq()&&1==dvt.B.YQ()&&f.If(!0);d=new dvt.vb(c.u(),d,e);d.ra(null);d.Ue(b.className);if(a&&a instanceof Object){b=dvt.Xc.Qt;"customStyle"==a._type?a.strokeDasharray&&(b=dvt.Xc.VC,a.strokeDasharray=$e.fqb(a.strokeDasharray)):b=$e.FY(a._type);f.bo(b,a.strokeDasharray,a.strokeDashoffset);var k=dvt.ac.clone(a);dvt.na.forEach(["_type",
"strokeDasharray","strokeDashoffset"],function(a){delete k[a]});d.fa(k)}else b=$e.FY(a),f.bo(b,$e.F6(b),$e.G6(b));d.Ga(f);c.XI(d);c.Ib(d,1)}q.kc=function(a){Yl.C.kc.call(this,a);a?this.WB(this.Qp,!0):this.hH();this.ir()};q.tb=function(){return this.Na().Oo()&&"off"!=this.getData().selectable};
q.WB=function(a,b){if(a){this.Tl||(this.Tl=this.Mc().Ud());var c=this.Mc().Ud().clone();c.Ew&&c.Ew(this.getData().hoverInnerColor);this.Mc().Ga(c);Od(this.Kj,c);Od(this.Ej,c)}else this.Tl&&(this.Mc().Ga(this.Tl),Od(this.Kj,this.Tl),Od(this.Ej,this.Tl),this.Tl=null);this.Kg||(this.Kg=Pd(this,"#000000",1,0),this.Ib(this.Kg,0));var c=b?this.getData().selectionColor:this.getData().hoverOuterColor,d=this.Kg.Ud().clone();d.Ew(c);d.Xa(2+this.JA());this.tY(d,!0);this.Kg.Ga(d,2)};
q.hH=function(){this.Tl&&(this.Mc().Ga(this.Tl),Od(this.Kj,this.Tl),Od(this.Ej,this.Tl),this.Tl=null);this.Kg&&(this.removeChild(this.Kg),this.Kg.xa&&this.Kg.xa(),this.Kg=null)};q.tY=function(a,b){var c=this.xha();if(c&&c instanceof Object)if("customStyle"==c._type){var d=null!=c.strokeDashoffset?dvt.j.pk(c.strokeDashoffset)+1:1;a.bo(dvt.Xc.VC,$e.Ckb(c.strokeDasharray),d)}else c=$e.FY(c._type),a.bo(c,$e.F6(c,b),$e.G6(c,b));else Yl.C.tY.call(this,a,b)};
q.qd=function(){this.Qp||(this.Qp=!0,this.WB(!0,this.wb()))};q.Nc=function(){this.wb()?this.WB(!1,!0):this.hH();this.Qp=!1};q.Qg=function(){var a=this.Na().F().tooltip;return(a=a?a.renderer:null)?this.Na().u().Af().Xx(a,this.hn()):this.me()};q.me=function(){return this.bj?1<this.getData()._links.length?dvt.H.Bf(this.Na().F(),"promotedLinks",dvt.H.k6,"PROMOTED_LINKS",this.getData()._links.length):dvt.H.Bf(this.Na().F(),"promotedLink",dvt.H.k6,"PROMOTED_LINK",this.getData()._links.length):this.getData().shortDesc};
q.hn=function(){return{id:this.getId(),type:this.bj?"promotedLink":"link",label:this.getData().label,data:this.bj?this.getData()._links:this.getData(),component:this.Na().F()._widgetConstructor}};q.Ed=function(){var a=[];this.tb()&&a.push(dvt.H.va(dvt.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));this.bj&&a.push(dvt.H.va(dvt.H.k6,"PROMOTED_LINK_ARIA_DESC"));return dvt.oa.Ik(this.me(),a)};q.ir=function(){if(!dvt.B.kj()){var a=this.Ed();a&&this.Gd("label",a)}};
q.Fd=function(a){if(a.keyCode==dvt.KeyboardEvent.ni&&a.ctrlKey)return this;if(a.keyCode==dvt.KeyboardEvent.kh||a.keyCode==dvt.KeyboardEvent.Tf){var b=this.cV;b||(b=this.Na().ka(jd(this.Na(),this)));var c=this,d=this.Na().XE(b.getId()),e=this.Na().ab().Cb;e&&e.dea&&(c=e.dea(b,this,a,d));c.cV=b;return c}return a.keyCode==dvt.KeyboardEvent.uf||a.keyCode==dvt.KeyboardEvent.Jf?(a=this.Xaa(a.keyCode)?this.Re():this.Ad(),this.Na().ka(a)):a.type==dvt.MouseEvent.Be?this:null};
q.Xaa=function(a){var b=Vd(this),c=Wd(this),b=b.x<c.x?!0:!1;return a==dvt.KeyboardEvent.uf&&b||a==dvt.KeyboardEvent.Jf&&!b?!1:!0};q.Sf=function(){this.dd=!0;this.qd()};q.Qd=function(){this.dd=!1;this.Nc()};q.Kd=function(){return this.dd};q.Xd=function(){return this.getData().categories?this.getData().categories:[this.getId()]};q.Ova=function(){var a=this.Na().F().hiddenCategories;return a&&dvt.na.yw(a,this.Xd())||!this.Na().ka(this.Re())||!this.Na().ka(this.Ad())?!0:!1};
q.sg=function(a,b,c){var d=b.ad(),e=this.ad(),f=new dvt.gd(this.u(),null,a.ob());dvt.na.Fe(d,e)||(this.be(d),d=dvt.G.Tt,0<e.length&&isNaN(e[0])&&(d=dvt.G.lm),f.ja.N(d,this,this.ad,this.be,e));b.Eb&&this.Eb&&(e=b.Eb.sb(),d=this.Eb.sb(),e.Fe(d)||(this.Eb.rb(e),f.ja.N(dvt.G.aj,this.Eb,this.Eb.sb,this.Eb.rb,d)));b.Mc()&&this.Mc()&&(b=b.Mc().Ud(),e=this.Mc().Ud(),b&&e&&b instanceof dvt.ya&&e instanceof dvt.ya&&(b.ic()!=e.ic()||b.getWidth()!=e.getWidth())&&(this.Mc().Ga(b),f.ja.N(dvt.G.UJ,this.Mc(),this.Mc().Ud,
this.Mc().Ga,e)));if(c){var h=this;dvt.eb.Mb(f,function(){h.getParent().removeChild(h)})}a.add(f,1)};q.Mj=function(a){this.Na().Sp.A(this);var b=this,c=new dvt.Xi(this.u(),this,a.ob());dvt.eb.Mb(c,function(){b.getParent().removeChild(b);b.xa()});a.add(c,0)};q.Ri=function(a){this.T(0);a.add(new dvt.ih(this.u(),this,a.ob()),2)};
q.Rfa=function(a,b){a&&(a==dvt.ca.Dp?this.Eb.Vh():a==dvt.ca.Mk?this.Eb.Yf():a==dvt.ca.Kl&&this.Eb.Wh());b&&(b==dvt.ca.jr?this.Eb.np():b==dvt.ca.zi?this.Eb.Ng():b==dvt.ca.$o?this.Eb.Oq():"baseline"==b&&this.Eb.HE())};q.RI=function(a){this.zB=a};q.Bd=function(){return this.zB};
function lm(a,b){function c(a,b){for(var c=[],d=b.ka(a)?b.ka(a).Bd():null;d;)c.push(d),d=b.ka(d)?b.ka(d).Bd():null;return c}for(var d=c(a.Re(),b),e=c(a.Ad(),b),f=0;f<d.length;f++)if(-1<dvt.na.kb(e,d[f]))return d[f];return null}function dm(a,b,c){this.Init(a,b,c)}dvt.v.D(dm,ie,"DvtDiagramNode");q=dm.prototype;q.Init=function(a,b,c){dm.C.Init.call(this,a,c.id,b);this.Nb=c;this.L.Oo()&&this.setCursor("pointer")};q.getData=function(){return this.Nb};q.getId=function(){return this.Nb.id};q.hi=function(){return this.nB};
q.tg=function(){var a=null;this.Eb&&(a=this.aE?this.aE:this.Eb.aa());return a};q.kc=function(a){var b=this.um();dm.C.kc.call(this,a);this.L.F().selectionRenderer?am(this,this.L.F().selectionRenderer,this.um(),b):this.II(a);this.ir()};q.II=function(a){this.kt()&&this.kt().kc(a)};q.tb=function(){return this.Na().Oo()&&"off"!=this.getData().selectable};q.$Y=function(){return this.ba};
q.ta=function(){var a=this.getData();if(this.L.F().renderer){if(am(this,this.L.F().renderer,this.um(),null),this.Ab()){var b=this.Ua().getBoundingClientRect(),c=this.qc?this.qc.Ua().getBoundingClientRect():null;this.bi={left:c.left-b.left,right:b.right-c.right,top:c.top-b.top,bottom:b.bottom-c.bottom}}}else{if(this.Ab())nm(this.L,a,this);else if(om(this.L,a,this),b=this.L,c=a.icon){var d=c.width,e=c.height,f=c.color,h=c.borderRadius,b=c.source?new dvt.Ef(b.u(),d/2,e/2,d,e,h,c.source,c.sourceSelected,
c.sourceHover,c.sourceHoverSelected):new dvt.za(b.u(),c.shape,dvt.j.mf,d/2,e/2,d,e,h);"none"!=c.fillPattern?b.ra(new dvt.wc(c.fillPattern,f,f)):b.fb(f);null!=c.opacity&&b.T(c.opacity);c.borderColor&&b.Ga(new dvt.ya(c.borderColor,c.borderWidth));b.fa(c.style).Ue(c.className);this.A(b);this.ba=b;if(this.Gb){var c=a.icon,f=this.Gb.getWidth(),d=this.Gb.getHeight(),e=c.width,h=c.height,k=.5*(f-e),l=.5*(d-h);if(void 0!==c.positionX)k=parseFloat(c.positionX),dvt.B.da(this.u())&&(k=f-k-e);else{var m=c.halign;
"start"==m?m=dvt.B.da(this.u())?"right":"left":"end"==m&&(m=dvt.B.da(this.u())?"left":"right");k="left"==m?0:"right"==m?f-e:k}void 0!==c.positionY?l=parseFloat(c.positionY):"top"==c.valign?l=0:"bottom"==c.valign&&(l=d-h);this.ba.Ma(k,l)}this.Gb||this.cN(b)}pm(this.kt(),a)}d=this.L;b=dvt.B.da(d.u())?dvt.ca.Kl:dvt.ca.Dp;a.label&&(c=a.labelStyle,f=dvt.ca.jr,d=new dvt.ca(d.u(),a.label,0,0),d.Bb(new dvt.j(c)),d.oy(b),d.AA(f),b=dvt.j.pk((new dvt.j(a.labelStyle)).getWidth()),0<b&&dvt.Ca.kd(d,b,Infinity,
this)||this.A(d),this.Eb=d);b=null;this.Ev?this.Ev instanceof dvt.Ie?(c=this.Ev.aa())&&(b=new dvt.Z(c.x,c.y,c.a,c.b)):(c=this.Ev.getBBox())&&(b=new dvt.Z(c.x,c.y,c.width,c.height)):this.Ab()?b=this.jU.sJ(this):(b=this.Gb?this.Gb.sJ(this):null)&&this.ba?b=b.wj(this.ba.sJ(this)):!b&&this.ba&&(b=this.ba.sJ(this));this.nB=b;b=this.L;this.mB&&(this.removeChild(this.mB),this.mB=null);a.nodes&&"off"!=a.showDisclosure&&(c=b.F(),this.Ab()?(a=c._resources.collapse_ena,f=c._resources.collapse_ovr,d=c._resources.collapse_dwn):
(a=c._resources.expand_ena,f=c._resources.expand_ovr,d=c._resources.expand_dwn),c=new dvt.Image(b.u(),a.src,0,0,a.width,a.height),f=new dvt.Image(b.u(),f.src,0,0,f.width,f.height),d=new dvt.Image(b.u(),d.src,0,0,d.width,d.height),c=new dvt.ia(b.u(),c,f,d,null,null,this.Inb,this),this.A(c),this.nB&&(a=dvt.B.da(b.u())?this.nB.x+this.nB.a-a.width:this.nB.x,c.Ma(a,this.nB.y)),this.mB=c);this.cg("img");this.ir();this.L.ab().lb(this,this)};
function am(a,b,c,d){var e=a.L.F()._contextHandler;if(e){var f=a.getData(),h=null;if(a.Ab())var h=a.YC(),k=h.aa(),h={element:h.Ua(),w:k?k.a-k.x:null,h:k?k.b-k.y:null};c=e(a.Ua(),a.Ev,h,f,c,d);b=b(c);a.Ev&&b!=a.Ev&&(a.Ev.namespaceURI===dvt.K.JZ?a.s3().removeChild(a.Ev):a.removeChild(b),a.Ev=null);b&&b.namespaceURI===dvt.K.JZ?a.Ev||(dvt.K.pf(a.s3(),b),a.Ev=b):b instanceof dvt.Ie?a.Ev||(a.A(b),a.Ev=b):b&&a.L.JN("dvt.Diagram: could not add custom node content for the node "+a.getId()+b,1)}else a.L.JN("dvt.Diagram: could not add custom node content - context handler is undefined",
1)}function om(a,b,c){var d=dvt.ac.clone(b.backgroundStyle),e=[dvt.j.qo,dvt.j.fs,dvt.j.Lb,dvt.j.ub,dvt.j.Yi,dvt.j.dg],f=qm(d,b._backgroundStyle,e);if(!f.BUa()){var h=dvt.j.pk(f.M(dvt.j.qo)),k=dvt.j.pk(f.M(dvt.j.fs)),l=f.M(dvt.j.Lb),m=f.M(dvt.j.ub),n=dvt.j.pk(f.M(dvt.j.Yi)),f=dvt.j.pk(f.M(dvt.j.dg));a=new dvt.Rect(a.u(),0,0,h,k);a.fb(l);f&&(a.ii(f),a.wi(f));m&&a.Ga(new dvt.ya(m,1,n));d&&dvt.na.forEach(e,function(a){delete d[dvt.j.bM(a)]});a.fa(d).Ue(b.backgroundClassName);c.A(a);c.cN(a);c.Gb=a}}
function pm(a,b){var c=b.hoverInnerColor,d=b.hoverOuterColor,e=b.selectionColor,f=new dvt.ya(c,1,4);f.If(!0);d=new dvt.ya(d,1,8);d.If(!0);var h=new dvt.ya(e,1,2);h.If(!0);var k=new dvt.ya(e,1,4);k.If(!0);c=new dvt.ya(c,1,4);c.If(!0);e=new dvt.ya(e,1,8);e.If(!0);a.xt(f,d).At(h,k).Uu(c,e)}q.cN=function(a){this.qQ=a};q.kt=function(){if(!this.qQ&&this.nB){var a=new dvt.Rect(this.L.u(),this.nB.x,this.nB.y,this.nB.a,this.nB.b);a.Wb();this.cN(a);this.Ib(a,0);pm(a,this.getData());this.qQ=a}return this.qQ};
q.qd=function(){var a=this.um();this.Qp=!0;this.L.F().hoverRenderer?am(this,this.L.F().hoverRenderer,this.um(),a):this.ky(!0)};q.Nc=function(){var a=this.um();this.Qp=!1;this.L.F().hoverRenderer?am(this,this.L.F().hoverRenderer,this.um(),a):this.ky(!1)};q.ky=function(a){this.kt()&&(a?this.kt().qd():this.kt().Nc())};q.Qg=function(){var a=this.Na().F().tooltip;return(a=a?a.renderer:null)?this.Na().u().Af().Xx(a,this.hn()):this.me()};q.me=function(){return this.getData().shortDesc};
q.hn=function(){return{id:this.getId(),type:"node",label:this.getData().label,data:this.getData(),component:this.Na().F()._widgetConstructor}};q.Ed=function(){var a=[];this.tb()&&a.push(dvt.H.va(dvt.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));this.getData().nodes&&a.push(this.Ab()?dvt.H.va(dvt.H.Ha,"STATE_EXPANDED"):dvt.H.va(dvt.H.Ha,"STATE_COLLAPSED"));return dvt.oa.Ik(this.me(),a)};q.ir=function(){if(!dvt.B.kj()){var a=this.Ed();a&&this.Gd("label",a)}};
q.Fd=function(a){var b=null;if(a.keyCode==dvt.KeyboardEvent.ni&&a.ctrlKey)b=this;else if((a.keyCode==dvt.KeyboardEvent.TA||dvt.KeyboardEvent.FA)&&a.altKey){var c=this.Na().XE(this.getId()),d=this.Na().ab().Cb;d&&d.TW&&(b=d.TW(this,a,c));b?b.cV=this:b=this}else a.keyCode==dvt.KeyboardEvent.Tw?b=this.Ab()?this.ze()[0]:this:a.keyCode==dvt.KeyboardEvent.cv?b=(b=this.Bd()?this.Na().ka(this.Bd()):null)?b:this:a.type==dvt.MouseEvent.Be?b=this:(b=(b=this.Bd()?this.Na().ka(this.Bd()):null)?b.ze():Ml(this.Na()),
b=dvt.Cb.YE(this,a,b));return b};q.hm=function(a){a.keyCode==dvt.KeyboardEvent.ni&&a.ctrlKey&&a.shiftKey&&this.getData().nodes&&this.Na().UI(this.getId(),!this.Ab())};q.Sf=function(){var a=this.um();this.dd=!0;this.L.F().focusRenderer?am(this,this.L.F().focusRenderer,this.um(),a):this.FC(!0)};q.Qd=function(){this.Kd()&&(this.um(),this.dd=!1,this.L.F().focusRenderer?am(this,this.L.F().focusRenderer,this.getData(),this.um()):this.FC(!1))};q.FC=function(a){this.ky(a)};q.Kd=function(){return this.dd};
q.Xd=function(){return this.getData().categories?this.getData().categories:[this.getId()]};q.Ova=function(){var a=this.Na().F().hiddenCategories;return a&&dvt.na.yw(a,this.Xd())?!0:!1};
q.sg=function(a,b){var c=new dvt.gd(this.u(),null,a.ob());if(this.Ab()||b.Ab())if(this.Ab()&&b.Ab())if(this.L.F().renderer)rm(this,a,b);else{sm(c,b,this);var d=b.jU,e=this.jU;e&&d&&(c.ja.N(dvt.G.po,e,e.fd,e.ra,e.fd()),e.ra(d.fd()),c.ja.N(dvt.G.V,e,e.getWidth,e.Xa,e.getWidth()),e.Xa(d.getWidth()),c.ja.N(dvt.G.V,e,e.getHeight,e.qb,e.getHeight()),e.qb(d.getHeight()));dvt.B.da(this.u())&&b.mB&&this.mB&&(d=b.mB.qa(),e=this.mB.qa(),d!=e&&(this.mB.ga(d),c.ja.N(dvt.G.V,this.mB,this.mB.qa,this.mB.ga,e)));
for(var d=[],e=[],f=this.dj,h=0;h<f.length;h++)d.push(this.Na().ka(f[h]));for(var f=b.dj,k=a.eqa.pTa(),h=0;h<f.length;h++)e.push(k[f[h]]);a.Io(e,d)}else rm(this,a,b);else sm(c,b,this),b.ba&&this.ba&&(c.ja.N(dvt.G.mD,this.ba,this.ba.Yz,this.ba.OI,this.ba.Yz()),this.ba.OI(b.ba.Yz())),b.Eb&&this.Eb&&(d=b.Eb.sb(),e=this.Eb.sb(),d.Fe(e)||(this.Eb.rb(d),c.ja.N(dvt.G.aj,this.Eb,this.Eb.sb,this.Eb.rb,e))),tm(c,b.Gb,this.Gb),tm(c,b.ba,this.ba);a.add(c,1)};
function rm(a,b,c){var d=c.hi(),e=a.hi();if(d.Fe(e)){var f=new dvt.gd(a.u(),null,b.ob());sm(f,c,a);b.add(f,1)}else{a.getParent().A(c);var h=e.a/d.a,k=d.a/e.a,f=new dvt.gd(a.u(),null,b.ob()),l=new dvt.R(a.qa()+.5*e.a,a.pa()+.5*e.b);f.ja.N(dvt.G.V,c,c.qa,c.ga,l.x-d.a*h*.5);f.ja.N(dvt.G.V,c,c.pa,c.wa,l.y-d.b*h*.5);var d=new dvt.R(c.qa()+.5*d.a,c.pa()+.5*d.b),l=a.qa(),m=a.pa();a.ga(d.x-e.a*k*.5);a.wa(d.y-e.a*k*.5);f.ja.N(dvt.G.V,a,a.qa,a.ga,l);f.ja.N(dvt.G.V,a,a.pa,a.wa,m);b.add(f,1);e=new dvt.dJ(a.u(),
c,new dvt.R(h,h),b.ob());b.add(e,1);e=new dvt.Xi(a.u(),c,b.ob());b.add(e,1);dvt.eb.Mb(e,function(){a.getParent().removeChild(c)});a.uh(k);a.gh(k);k=new dvt.dJ(a.u(),a,new dvt.R(1,1),b.ob());b.add(k,1);a.T(0);k=new dvt.ih(a.u(),a,b.ob());b.add(k,1)}}function sm(a,b,c){if(c&&b){var d=b.qa();b=b.pa();var e=c.qa(),f=c.pa();d!=e&&(c.ga(d),a.ja.N(dvt.G.V,c,c.qa,c.ga,e));b!=f&&(c.wa(b),a.ja.N(dvt.G.V,c,c.pa,c.wa,f))}}function tm(a,b,c){b&&c&&(a.ja.N(dvt.G.po,c,c.fd,c.ra,c.fd()),c.ra(b.fd()))}
q.Mj=function(a){this.Na().xl.A(this);var b=this,c=new dvt.Xi(this.u(),this,a.ob());dvt.eb.Mb(c,function(){b.getParent().removeChild(b);b.xa()});a.add(c,0)};q.Ri=function(a){this.T(0);a.add(new dvt.ih(this.u(),this,a.ob()),2)};q.um=function(a){return{hovered:this.Qp,selected:this.wb(),focused:this.dd,zoom:a?a:this.Na().Qa.wg(),expanded:this.Ab()}};
q.Rfa=function(a,b){a&&(a==dvt.ca.Dp?this.Eb.Vh():a==dvt.ca.Mk?this.Eb.Yf():a==dvt.ca.Kl&&this.Eb.Wh());b&&(b==dvt.ca.jr?this.Eb.np():b==dvt.ca.zi?this.Eb.Ng():b==dvt.ca.$o?this.Eb.Oq():"baseline"==b&&this.Eb.HE())};
q.rp=function(){if(!this.bi&&this.L.F().renderer){var a=this.Ua().getBoundingClientRect(),b=this.qc?this.qc.Ua().getBoundingClientRect():null;this.bi={left:b.left-a.left,right:a.right-b.right,top:b.top-a.top,bottom:a.bottom-b.bottom}}else this.bi||(a=qm(this.Nb.containerStyle,this.Nb._containerStyle,["padding-left","padding-right","padding-top","padding-bottom"]),this.bi={left:a.Tg("padding-left"),right:a.Tg("padding-right"),top:a.Tg("padding-top"),bottom:a.Tg("padding-bottom")});return this.bi};
q.ze=function(){for(var a=[],b=this.dj?this.dj.length:-1,c=0;c<b;c++){var d=this.Na().ka(this.dj[c]);d&&a.push(d)}return a};q.RI=function(a){this.zB=a};q.Bd=function(){return this.zB};q.YC=function(){this.qc||(this.qc=new dvt.la(this.u()),this.A(this.qc));return this.qc};q.Inb=function(a){dvt.I.sc(a);this.L.UI(this.getId(),!this.Ab())};
function nm(a,b,c){c.jU&&(c.removeChild(c.jU),c.jU=null);var d=dvt.ac.clone(b.containerStyle),e=[dvt.j.Lb,dvt.j.ub,dvt.j.Yi,dvt.j.dg],f=qm(d,b._containerStyle,e),h=f.M(dvt.j.Lb),k=f.M(dvt.j.ub),l=dvt.j.pk(f.M(dvt.j.Yi)),f=dvt.j.pk(f.M(dvt.j.dg)),m=c.YC(),n=c.rp();m.Ma(n.left,n.top);m=m.hq();a=new dvt.Rect(a.u(),0,0,m.a+n.left+n.right,m.b+n.top+n.bottom);a.fb(h);f&&(a.ii(f),a.wi(f));k&&a.Ga(new dvt.ya(k,1,l));d&&dvt.na.forEach(e,function(a){delete d[dvt.j.bM(a)]});a.fa(d).Ue(b.containerClassName);
c.Ib(a,0);c.cN(a);c.jU=a}function qm(a,b,c){var d=new dvt.j;dvt.na.forEach(c,function(c){var f=null,h=dvt.j.bM(c);a&&null!=a[h]?f=a[h]:b&&(f=b.M(c));d.fa(c,f)});return d}function em(a){this.Init(a)}ba("DvtDiagramAutomation",em);dvt.v.D(em,dvt.Rd,"DvtDiagramAutomation");em.prototype.Init=function(a){this.L=a};em.prototype.zn=function(a){return(a=this.L.ab().mb(a))&&a instanceof dm?"node["+this.L.pJ().indexOf(a.getId())+"]":a&&a instanceof Yl?"link["+this.L.oJ().indexOf(a.getId())+"]":null};
em.prototype.qh=function(a){if(a==dvt.Rd.lD)return this.RF(this.L);var b=this.cQ(a);a=b.component;var b=b.index,c=null;"node"==a?c=this.Zj(b):"link"==a&&(c=um(this,b));return c?c.Ua():null};em.prototype.getDomElementForSubId=em.prototype.qh;em.prototype.cQ=function(a){var b=a,c=-1,d=a.substring(0,a.indexOf("["));d&&(b="node"==d||"link"==d?d:null,c=parseInt(a.substring(a.indexOf("[")+1,a.indexOf("]"))));return{component:b,index:c}};em.prototype.Bg=function(){return this.L.Bg()};
em.prototype.getNodeCount=em.prototype.Bg;em.prototype.Ju=function(){return this.L.Ju()};em.prototype.getLinkCount=em.prototype.Ju;em.prototype.ud=function(a){if(a=this.Zj(a)){var b={};b.id=a.getId();b.selected=a.wb();b.tooltip=a.me();b.label=a.getData().label;var c=a.getData().backgroundStyle;c&&c instanceof Object&&(c=dvt.j.dta(c));b.background=c;b.icon=this.r0(a.$Y());b.expanded=a.Ab();return b}return null};em.prototype.getNode=em.prototype.ud;
em.prototype.ZW=function(a){if(a=um(this,a)){var b={};b.id=a.getId();b.selected=a.wb();b.tooltip=a.me();b.label=a.getData().label;b.color=a.VE();b.width=a.bA();b.style=vm(a.vM());b.startNode=a.Re();b.endNode=a.Ad();b.startConnectorType=a.Mu();b.endConnectorType=a.at();return b}return null};em.prototype.getLink=em.prototype.ZW;
em.prototype.mmb=function(a,b){var c=this.Zj(a),d=this.Zj(b);if(!c||!d)return null;c=c.getId();d=d.getId();return(d=this.L.pd("_plL"+c+"_L"+d))?(c={},c.id=d.getId(),c.selected=d.wb(),c.tooltip=d.me(),c.color=d.VE(),c.width=d.bA(),c.style=vm(d.vM()),c.startNode=d.Re(),c.endNode=d.Ad(),c.startConnectorType=d.Mu(),c.endConnectorType=d.at(),c.count=d.getData()._links.length,c):null};em.prototype.getPromotedLink=em.prototype.mmb;
function vm(a){return a&&a instanceof Object?"customStyle"==a._type?(a=dvt.ac.clone(a),delete a._type,dvt.j.dta(a)):a._type:a}em.prototype.Ykb=function(){return this.L.gv};em.prototype.getExpanded=em.prototype.Ykb;em.prototype.r0=function(a){if(a){var b={};b.shape=a instanceof dvt.za?a.he():"none";a.fd()&&(b.color=a.fd().ic());return b}return null};em.prototype.Zj=function(a){var b=this.L.pJ();return 0<=a&&a<b.length?this.L.ka(b[a]):null};
function um(a,b){var c=a.L.oJ();return 0<=b&&b<c.length?a.L.pd(c[b]):null};
  return dvt;
});
