/**
 * Copyright (c) 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit', './DvtTimeComponent', './DvtTimeAxis'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a,b,c){this.Init(a,b,c)}function c(a,b,c,d){this.Init(a,b,c,d)}function d(){}function e(a,b){this.Init(a,b)}function f(a){f.C.constructor.call(this,a)}function h(){this.Init({alta:h.lh})}function k(a){this.Wf=a}function l(a,b,c,d,e,h){this.Init(a,b,c,d,e,h)}function m(a,b,c,d,e,h,f){this.Init(a,b,c,d,e,h,f)}a.KF=function(){};a.v.D(a.KF,a.v);a.KF.Zgb=function(b,c){var d,e;null!=c&&null!=b&&(d=a.K.El(b,"class"),e=a.KF.Nna(d,c),-1==e&&a.K.Y(b,"class",d?c+" "+d:c))};a.KF.Dwb=function(b,
c){var d,e,h;d=!1;null!=c&&null!=b&&(e=a.K.El(b,"class"),h=a.KF.Nna(e,c),-1!=h&&(d=h+c.length,h=0==h?null:e.substring(0,h),e=d==e.length?null:e.substring(d+1),a.K.Y(b,"class",null==h?null==e?"":e:null==e?h:h+e),d=!0));return d};a.KF.Mvb=function(b,c){return null!=c&&null!=b?-1!=a.KF.Nna(b.className,c):!1};a.KF.Nna=function(a,b){var c,d,e,h,f,k;if(!a||!a.indexOf)return-1;if(b===a)return 0;c=b.length;d=a.length;e=a.indexOf(b);if(0<=e){h=0==e||" "==a.charAt(e-1);f=e+c;f=f==d||" "==a.charAt(f);if(h&&
f)return e;k=a.lastIndexOf(b);if(k!=e)return h=a.charAt(k-1),f=k+c,f=f==d||" "==a.charAt(f),h&&f?k:a.indexOf(" "+b+" ")}return-1};a.v.D(m,a.vb);m.prototype.Init=function(b,c,d,e,h,f,k){this.zc=c;this.ed=d;this.Vs=e;this.gP=h;this.GH=null!=f?f:0;this.fcb=a.B.da(b);m.C.Init.call(this,b,this.vta(this.zc,this.ed,this.Vs,this.gP,this.GH),k)};m.prototype.vta=function(a,b,c,d,e){return this.fcb?"M"+(a-e)+" "+b+" H"+(a-c+e)+" A"+e+" "+e+" 0 0 0 "+(a-c)+" "+(b+e)+" V"+(b+d-e)+" A"+e+" "+e+" 0 0 0 "+(a-c+e)+
" "+(b+d)+" H"+(a-e)+" A"+e+" "+e+" 0 0 0 "+a+" "+(b+d-e)+" V"+(b+e)+" A"+e+" "+e+" 0 0 0 "+(a-e)+" "+b:"M"+(a+e)+" "+b+" H"+(a+c-e)+" A"+e+" "+e+" 0 0 1 "+(a+c)+" "+(b+e)+" V"+(b+d-e)+" A"+e+" "+e+" 0 0 1 "+(a+c-e)+" "+(b+d)+" H"+(a+e)+" A"+e+" "+e+" 0 0 1 "+a+" "+(b+d-e)+" V"+(b+e)+" A"+e+" "+e+" 0 0 1 "+(a+e)+" "+b};m.prototype.getWidth=function(){return this.Vs};m.prototype.Xa=function(a){this.Vs=a;this.nk(this.vta(this.zc,this.ed,this.Vs,this.gP,this.GH))};m.prototype.getHeight=function(){return this.gP};
m.prototype.qb=function(a){this.gP=a;this.nk(this.vta(this.zc,this.ed,this.Vs,this.gP,this.GH))};m.prototype.Va=function(){return this.qa()};m.prototype.Fa=function(a){this.ga(a)};m.prototype.ib=function(){return this.pa()};m.prototype.jb=function(a){this.wa(a)};a.v.D(l,a.ca);l.prototype.Init=function(a,b,c,d,e,h){l.C.Init.call(this,a,b,c,d,h);this.Ebb=e;a=this.gy();this.HE();this.AA(a)};l.prototype.Pc=function(b){var c=null!=this.lf()?this.lf():"",d=this.Qq(),e=this.gy();l.Bc||(l.Bc=new a.Cache);
var h=this.Jd(),f=null!=h?h.Jea():"",f=0<c.length?c+f:"",k=l.Bc.get(f);if(null==k){a.B.ae()||this.Vh();this.HE();var n=k="normal",m=this.u().FK,z=this.u().EK;if(null!=h){var G=h.M(a.j.cs);G&&(z=G);(G=h.M(a.j.ji))&&(m=G);(G=h.M(a.j.ES))&&(k=G);(h=h.M(a.j.zN))&&(n=h)}h=k+" normal "+n+" "+m+" / normal "+z;k=this.Ebb.getContext("2d");k.font=h;c=k.measureText(c);a.B.ae()||this.oy(d);this.AA(e);k=new a.Z(this.Va(),this.ib(),c.width,a.Ca.Pj(this).b);l.Bc.put(f,k)}d===a.ca.Kl?k.x-=k.a:d===a.ca.Mk&&(k.x-=
k.a/2);e===a.ca.jr?k.y-=0:e===a.ca.$o?k.y-=k.b:e===a.ca.zi&&(k.y-=k.b/2);return b&&b!==this?this.nj(k,b):k};var n={};a.v.D(n,a.v);n.t3a="height: 3px; color: #9E9E9E; background-color: #F0F0F0";n.Y3a="width: 3px; color: #9E9E9E; background-color: #F0F0F0";n.pD="#ffffff";n.qD="#d6d7d8";n.aK=31;n.UZ=10.5;n.VZ=9;n.S3a=5;n.T3a=5;n.k3a=23;n.u5a=a.B.Wa()?8:4;n.hlb=function(){return n.t3a};n.fnb=function(){return n.Y3a};n.wea=function(){return n.T3a};n.QTa=function(){return n.S3a};n.dF=function(){return n.k3a};
n.ITa=function(){return n.u5a};n.Wmb=function(a){return(a=a._resources)?a.taskLabelFontProp:""};n.kkb=function(b){if(b=b._resources)if(b=b.chartArea)if(b=b.strokeWidth)return a.j.pk(b);return 1};n.jua=function(b){return b._resources?a.j.pk(b._resources.horizontalGridlineWidth):1};a.$c=function(a,b,c){this.Init(a,b,c)};a.v.D(a.$c,a.Lf);a.$c.newInstance=function(b,c,d){return new a.$c(b,c,d)};a.$c.prototype.Init=function(b,c,d){a.$c.C.Init.call(this,b,c,d);this.Xg=new h;this.I=new f(this);this.I.Qf(this);
a.B.Wa()?this.$D=null:(this.$D=new e(this,this.I),this.I.Xr(this.$D))};a.$c.prototype.vf=function(b){a.$c.C.vf.call(this,b);this.py(this.W.selectionMode)};a.$c.prototype.ph=function(){this.Rd||(this.Rd=new k(this));return this.Rd};a.$c.prototype.Fy=function(a){var b=this.u().styleClasses;return null!=b?b[a]:a};a.$c.prototype.eD=function(a){this.Yv=new d;return this.Yv.parse(a)};a.$c.prototype.uv=function(b){this.UT=b.zQa;this.dw=b.TR;this.Cbb=b.rUa;this.Hgb=b.cXa;this.yc=b.Uxa;this.Td=b.Txa;this.Afb=
b.rows;this.bpa=b.Qva;this.Vbb=b.Kva;a.$c.C.uv.call(this,b)};a.$c.prototype.F9=function(a,b){var c=this.jj;c.axisClass=this.Fy(b);c.axisSeparatorClass=this.Fy(b+"Ticks");c.axisLabelClass=this.Fy(b+"Labels");c={start:a.start,end:a.end,_resources:c,shortDesc:a.shortDesc,orientation:"horizontal"};if(a[b]){var d=a[b];d.scale&&(c.scale=d.scale);d.converter&&(c.converter=d.converter);d.zoomOrder&&(c.zoomOrder=d.zoomOrder)}return c};a.$c.prototype.dH=function(b,c){return new a.yj(b,c)};a.$c.prototype.ta=
function(b,c,d){if(b){this.vf(b);a.$c.C.ta.call(this,b,c,d);c=this.UT;if(b.minorAxis){d=this.F9(this.W,"minorAxis");null==this.Xp&&(this.Xp=new a.Ub(this.u(),null,null),"top"==c?this.Xp.RX(!1,!1,!0,!1):this.Xp.RX(!0,!1,!1,!1),this.Rv=this.Xp);this.Xp.ixa();var e=this.Xp.lea(d,this.Uf)}if(b=b.majorAxis)b.scale?(d=this.F9(this.W,"majorAxis"),null==this.Ar&&(this.Ar=new a.Ub(this.u(),null,null),"top"==c?this.Ar.RX(!1,!1,!0,!1):this.Ar.RX(!0,!1,!1,!1),this.Rs=this.Ar),this.Ar.ixa(),b=this.Ar.lea(d,this.Uf),
e&&b>e&&(this.Rv=this.Ar,this.Rs=this.Xp,e=b)):this.Ar=null;e&&this.qF(e);(this.Xp||this.Ar)&&this.lfa();this.Ndb();r.Kqb(this);this.Lxa();this.hr();this.ro="none";this.lc||this.qs()}else this.eH(c,d)};a.$c.prototype.Ndb=function(){this.fr();this.ro="none";this.Ml=.5;if(this.W._resources){var b=this.W._resources.animationDuration;b&&(this.Ml=a.Ta.Pr(b)/1E3)}this.nh?this.Vbb&&(this.ro="dataChange"):this.bpa&&(this.ro="onDisplay");"onDisplay"===this.ro?(this.oBa=[],this.gia=this.yK(a.Je.kF)):"dataChange"===
this.ro&&(this.PVa=[],this.tfa=[],this.shb=this.yK(a.Je.kF),this.Rca=[],this.UM=[],this.jVa=this.yK(a.Je.kF),this.xUa=this.yK(a.Je.V2),this.yUa=this.yK(a.Je.V2),this.dxa=this.yK(a.Je.kF),this.lwa=this.yK(a.Je.kF),this.vda=[],this.nwa=this.yK(a.Je.kF))};a.$c.prototype.yK=function(b){var c=new a.gd(this.u(),this,this.Ml);c.wp(b);return c};a.$c.prototype.Lxa=function(){this.fr();var b=this.u();if("onDisplay"===this.ro){var c=[this.gia,new a.ih(b,this.oBa,this.Ml,0)];this.lc=b=new a.Gg(b,c,this.Ml,0)}else if("dataChange"===
this.ro){var c=new a.Xi(b,this.PVa,this.Ml,0),d=new a.Xi(b,this.tfa,this.Ml,0),c=new a.Gg(b,[c,d],this.Ml,0),d=new a.ih(b,this.Rca,this.Ml,0);this.zNa(this.Rca,d);var d=new a.Gg(b,[this.shb,d],this.Ml,0),e=new a.Xi(b,this.UM,this.Ml,0);this.Mdb();a.eb.Mb(e,this.rqa,this);var e=new a.Gg(b,e,this.Ml,0),h=new a.Gg(b,[this.yUa,this.xUa,this.dxa,this.jVa,this.lwa],this.Ml,0),f=new a.ih(b,this.vda,this.Ml,0);this.zNa(this.vda,f);var f=new a.Gg(b,[this.nwa,f],this.Ml,0),k=[];0<this.UM.length&&k.push(e);
k.push(h);0<this.vda.length&&k.push(f);e=new a.oo(b,k);b=new a.Gg(b,[c,d,e],this.Ml,0);a.eb.Mb(b,this.cdb,this);this.lc=b}this.lc&&(this.I.ll(this),a.eb.Mb(this.lc,this.Tv,this),this.lc.play())};a.$c.prototype.Mdb=function(){for(var a=0;a<this.UM.length;a++){var b=this.UM[a];"refurbished"===b.Sk&&b.vQa()}};a.$c.prototype.rqa=function(){for(var a=0;a<this.UM.length;a++){var b=this.UM[a];"delete"===b.Sk&&b.getParent()?b.getParent().removeChild(b):"refurbished"===b.Sk&&b.tQa()}};a.$c.prototype.cdb=function(){for(var a=
0;a<this.tfa.length;a++){var b=this.tfa[a];b.getParent()&&b.getParent().removeChild(b)}};a.$c.prototype.zNa=function(a,b){for(var c=0;c<a.length;c++){var d=a[c];d.JRa&&"new"!==d.Sk||b.NA(d)}};a.$c.prototype.Tv=function(){this.wn||this.qs();this.I.Qf(this);this.lc=null;this.wn=!1};a.$c.prototype.eZ=function(b,c){b.type==a.rv.xe&&(b=this.Dba(b,c));b&&this.dispatchEvent(b)};a.$c.prototype.Dba=function(a,b){var c=a.j1,d=a.lMa;b==this.cm&&(this.yc=c,this.Td=d,this.yA(this.je/(this.Ic-this.Yb)*(this.Yb-
this.yc)),this.AW(),c=this.Tz(),this.dispatchEvent(c));b==this.fo&&this.TG.wa(d)};a.$c.prototype.Tz=function(){return a.Za.opb(this.yc,this.Td,this.Rs?this.Rs.nf:null,this.BM().nf)};a.$c.prototype.eH=function(a,b){this.xb=a;this.Jb=b;this.IE();this.lfa();r.Gr(this);r.mOa(this);if(this.hy()){this.wfa(this.nh);this.$Wa();var c=this.Ul;r.Zqa(this,c);r.kra(this,c);r.e2(this);r.WPa(this);r.Rba(this)}else r.JH(this)};a.$c.prototype.IE=function(){var b=a.B.da(this.u()),c=n.ITa();this.Tk=n.kkb(this.W);var d=
2*this.Tk;this.Hca=0;this.aga(this.Tk);this.GWa(this.Tk);this.jga=new a.j(n.hlb());this.kga=new a.j(n.fnb());this.Zt=this.xb;this.Yy=this.Jb;this.Yy=this.Yy-a.j.pk(this.jga.getHeight())-3*c;c*=3;this.Zt=this.Zt-a.j.pk(this.kga.getWidth())-c;b&&(this.Hca=c-this.Tk,this.aga(this.Hca+this.Tk));this.Uf=this.Zt-d;this.cj=this.Yy-d};a.$c.prototype.$Wa=function(){var a=this.Kx;if(null!=a){r.QPa(this,this.TG);for(var b=0;b<a.length;b++)a[b].ta(this.TG)}};a.$c.prototype.xR=function(b,c,d,e,h){if(!h||h.ctrlKey||
a.B.Wa()){b>this.Rv.qV?(b=this.Rv.qV,this.cM(!0)):this.oda(!0);this.Uf>b?(b=this.Uf,this.cM(!1)):this.oda(!1);h=this.je<=b;a.$c.C.xR.call(this,b,c,d,e);b=this.Rv.tW;if(h)for(;0<this.Rv.mp&&(this.Rs?0<this.Rs.mp:1);)if(c=b[this.Rv.mp-1],this.je>=c)this.Rv.eS(this.Rv.mp-1),this.Rv.hta(),this.Rs&&(this.Rs.eS(this.Rs.mp-1),this.Rs.hta());else break;else for(;this.Rv.mp<b.length-1&&(this.Rs?this.Rs.mp<this.Rs.tW.length-1:1);)if(c=b[this.Rv.mp],this.je<c)this.Rv.eS(this.Rv.mp+1),this.Rv.Eva(),this.Rs&&
(this.Rs.eS(this.Rs.mp+1),this.Rs.Eva());else break;this.cm.Lm(this.yc,this.Td);r.Zqa(this,this.Ul);this.$Wa();r.kra(this,this.Ul);e&&(e=this.Tz(),this.dispatchEvent(e))}else this.Wi(0,-(10*h.wheelDelta))};a.$c.prototype.ssb=function(a){this.Tcb=a};a.$c.prototype.BM=function(){return this.Xp?this.Xp:this.Ar};a.$c.prototype.Jrb=function(a){this.TG=a};a.$c.prototype.lWa=function(a){this.ND=a};a.$c.prototype.Tsb=function(a){this.$ab=a};a.$c.prototype.d5=function(a){this.Vm=a};a.$c.prototype.yqb=function(){this.Vm&&
this.Vm.getParent()&&(this.Vm.getParent().removeChild(this.Vm),delete this.Vm,this.Vm=null)};a.$c.prototype.Isb=function(a){this.Kx=a};a.$c.prototype.Irb=function(a){this.o9a=a};a.$c.prototype.zda=function(){return n.dF()};a.$c.prototype.Ti=function(){return this.Yb};a.$c.prototype.hl=function(){return this.Ic};a.$c.prototype.C3=function(){return"none"};a.$c.prototype.Pva=function(){return"visible"==this.Cbb};a.$c.prototype.Lob=function(){return"visible"==this.Hgb};a.$c.prototype.NE=function(){return this.z8a};
a.$c.prototype.Erb=function(a){this.z8a=a};a.$c.prototype.i3=function(){if(null==this.sGa){var a=0;this.Ar&&(a+=this.Ar.pe());this.Xp&&(a+=this.Xp.pe());this.sGa=a}return this.sGa};a.$c.prototype.erb=function(a){var b=this.i3(),c=this.Ul,d=a.qa(),e=a.pa(),h=a.getWidth();a=a.getHeight();var c=0-c.qa(),f=0-(this.TG.pa()-this.ND),k=this.Uf,b=this.cj-b,n=0,z=0;d<c?n=d-c:d+h>c+k&&(n=d+h-(c+k));e<f?z=e-f:e+a>f+b&&(z=e+a-(f+b));this.Wi(n,z,!0)};a.$c.prototype.Wi=function(b,c,d){d="undefined"!==typeof d?
d:!1;0!=b&&(d||Math.abs(b)>Math.abs(c))&&a.$c.C.Wi.call(this,b,0);if(0!=c&&(d||Math.abs(c)>Math.abs(b))){d=b=this.ND;var e=0;this.NE()+this.ND>=this.cj&&("bottom"==this.UT&&(e=this.i3()),d=-(this.NE()-this.cj+e));c=this.TG.pa()-c;c<d?c=d:c>b&&(c=b);this.TG.wa(c);this.fo.Lm(c-(this.cj-this.ND-e),c)}this.cm.Lm(this.yc,this.Td)};a.$c.prototype.JQ=function(b,c){a.$c.C.JQ.call(this,b,c);this.r9a=this.yc;this.q9a=this.Td};a.$c.prototype.dI=function(b,c){this.r9a==this.yc&&this.q9a==this.Td&&(this.VH=!1);
a.$c.C.dI.call(this,b,c)};a.$c.prototype.HWa=function(a,b){var c=this.Kx;if(null!=c)for(var d=0;d<c.length;d++){var e=c[d].fA();if(null!=e)for(var h=0;h<e.length;h++)a!=e[h]&&(b?e[h].Yib():e[h].Ohb())}};a.$c.prototype.hy=function(){var a=this.Ar?this.Ar.hy():!0,b=this.Xp&&this.Xp.hy(),c=this.Yb&&this.Ic&&this.Ic>this.Yb,d=this.yc&&this.Td?this.Td>this.yc:!0,e=this.yc?this.yc>=this.Yb&&this.yc<this.Ic:!0,h=this.Td?this.Td>this.Yb&&this.Td<=this.Ic:!0;return a&&b&&c&&d&&e&&h};a.$c.prototype.gm=function(){return a.H.Bf(this.F(),
"componentName",a.H.Ha,"GANTT")};a.$c.prototype.Xh=function(){return this.Yc};a.$c.prototype.Oo=function(){return this.Yc?!0:!1};a.$c.prototype.py=function(b){this.Yc="single"==b?new a.Rc(a.Rc.Sy):"multiple"==b?new a.Rc(a.Rc.Ry):null;this.ab().zA(this.Yc)};a.$c.prototype.NB=function(){if(null!=this.Kx&&0!=this.Kx.length){var a=this.W.selection;if(a&&this.Oo()){for(var b=[],c=0;c<this.Kx.length;c++){var d=this.Kx[c].fA();if(null!=d&&0<d.length)for(var e=0;e<d.length;e++)b.push(d[e])}this.Xh().tt(a,
b)}}};a.$c.prototype.hZ=function(){};a.v.D(k,a.Rd);k.prototype.zn=function(a){var c=this.Wf.ab().mb(a);if(c&&c instanceof b){var d=c.Tq();a=this.Wf.Kx.indexOf(d);c=d.fA().indexOf(c);return"taskbar["+a+"]["+c+"]"}return null};k.prototype.qh=function(a){var b=a.indexOf("[");if(-1<b){if("taskbar"!=a.substring(0,b))return null;var c=parseInt(a.substring(b+1,a.indexOf("]")));if(isNaN(c))return null;b=a.indexOf("[",b+1);if(-1<b){a=parseInt(a.substring(b+1,a.indexOf("]",b+1)));if(isNaN(a))return null;b=
this.Wf.Kx;if(null!=b&&b.length>c&&(c=b[c].fA(),null!=c&&c.length>a&&(c=c[a].oi,null!=c)))return c.Ua()}}return null};a.v.D(h,a.bb);h.lh={axisPosition:"top",animationOnDataChange:"none",animationOnDisplay:"none",scrollbar:{horizontal:"off",vertical:"off"},gridlines:{horizontal:"hidden",vertical:"visible"},selectionMode:"none",taskDefaults:{labelPosition:"end",borderRadius:2,height:22}};a.v.D(f,a.ai);f.prototype.Fw=function(a){f.C.Fw.call(this,a);this.Li.erb(a)};a.v.D(e,a.dO);e.prototype.Init=function(a,
b){e.C.Init.call(this,b);this.Wf=a};e.yna=function(a,b,c){b=b.fA();return null==b||0==b.length?0==c?null:e.yna(a,a[c-1],c-1):b[b.length-1]};e.wna=function(a,b,c){b=b.fA();return null==b||0==b.length?c==a.length-1?null:e.wna(a,a[c+1],c+1):b[0]};e.Fd=function(c,d,h){if(d instanceof b){var f=d.Tq(),k=c.Kx,n=f.fA();if(null==n||0==n.length)return;c=a.B.da(c.u());f=k.indexOf(f);switch(h.keyCode){case c?a.KeyboardEvent.uf:a.KeyboardEvent.Jf:d=n.indexOf(d);if(0==d){if(0<f)return e.yna(k,k[f-1],f-1)}else return n[d-
1];break;case c?a.KeyboardEvent.Jf:a.KeyboardEvent.uf:d=n.indexOf(d);if(d==n.length-1){if(f<k.length-1)return e.wna(k,k[f+1],f+1)}else return n[d+1];break;case a.KeyboardEvent.kh:if(0<f&&(d=e.yna(k,k[f-1],f-1),null!=d))return d.Tq().fA()[0];break;case a.KeyboardEvent.Tf:if(f<k.length-1&&(d=e.wna(k,k[f+1],f+1),null!=d))return d.Tq().fA()[0]}}return null};e.prototype.mk=function(b){if(b.keyCode==a.KeyboardEvent.Qh){var c=this.yb.jf();if(c)return a.I.sc(b),c;c=this.Wf.Kx;if(null!=c&&0<c.length&&(c=c[0].fA(),
null!=c&&0<c.length))return a.I.sc(b),this.jI(c)}return e.C.mk.call(this,b)};a.v.D(d,a.v);d.prototype.parse=function(a){var b={};b.start=(new Date(a.start)).getTime();b.end=(new Date(a.end)).getTime();b.rows=a.rows;a.viewportStart&&(b.Uxa=(new Date(a.viewportStart)).getTime());a.viewportEnd&&(b.Txa=(new Date(a.viewportEnd)).getTime());b.zQa="top";null!=a.axisPosition&&(b.zQa=a.axisPosition);b.TR="none";null!=a.selectionMode&&(b.TR=a.selectionMode);b.rUa="hidden";b.cXa="hidden";null!=a.gridlines&&
(null!=a.gridlines.horizontal&&(b.rUa=a.gridlines.horizontal),null!=a.gridlines.vertical&&(b.cXa=a.gridlines.vertical));b.cm="off";b.fo="off";a.scrollbars&&(a.scrollbars.horizontal&&(b.cm=a.scrollbars.horizontal),a.scrollbars.vertical&&(b.fo=a.scrollbars.vertical));b.Qva="auto"==a.animationOnDisplay;b.Kva="auto"==a.animationOnDataChange;b.Lwb=a.className;b.tX=a.style;return b};var r={};a.v.D(r,a.v);r.Kqb=function(a){var b=a.u();a.eF||(a.sX=document.createElement("canvas"),a.sX.width=0,a.sX.height=
0,a.sX.style.width=0,a.sX.style.height=0,a.eF=document.createElement("div"),a.eF.style.fontFamily=b.EK,a.eF.style.fontSize=b.FK,a.eF.style.width=0,a.eF.style.height=0,a.eF.style.visibility="hidden",a.eF.setAttribute("aria-hidden","true"),a.eF.appendChild(a.sX));b.Xv.contains(a.eF)||b.Xv.appendChild(a.eF);r.Gr(a);r.mOa(a);r.c2(a);"onDisplay"===a.ro&&a.oBa.push(a.nh);a.yqb();a.hy()?(a.wfa(a.nh),b=a.Ul,r.Zqa(a,b),r.kra(a,b),r.mfb(a,b),r.e2(a),r.WPa(a),a.NB(),r.Rba(a)):r.JH(a)};r.Nqa=function(b,c,d){var e=
d.a,h=a.j.pk(b.jga.getHeight());b.cm=new a.ts(b.u(),b.eZ,b);c.A(b.cm);a.Dn.position(d,"bottom",b.cm,e,h,0);return new a.yj(e,h)};r.Oqa=function(b,c,d){var e=a.j.pk(b.kga.getWidth()),h=d.b;b.fo=new a.ts(b.u(),b.eZ,b);c.A(b.fo);a.Dn.position(d,a.B.da(b.u())?"left":"right",b.fo,e,h,0);return new a.yj(e,h)};r.Rba=function(b){var c=b.TG;if(null!=c){var d=b.ND,e=b.u(),h=b.getParent(),f=n.ITa();null==h.k2?(h.k2=new a.la(e,"sbCanvas"),h.A(h.k2)):h.k2.Hl();var k=b.Uf,l=b.Jb-f,e=r.Nqa(b,h.k2,new a.Z(0,0,k,
l)),k=b.xb-f,l=b.cj-b.i3(),h=r.Oqa(b,h.k2,new a.Z(0,0,k,l));b.cm&&(f={},f.color=b.jga.M(a.j.mc),f.backgroundColor=b.jga.M(a.j.Lb),f.min=b.Yb,f.max=b.Ic,f.isHorizontal=!0,f.isReversed=a.B.da(b.u()),b.cm.ga(b.bn),b.cm.ta(f,e.a,e.b),b.cm.Lm(b.yc,b.Td));b.fo&&(f={},f.color=b.kga.M(a.j.mc),f.backgroundColor=b.kga.M(a.j.Lb),f.min=-(Math.max(b.NE(),h.b)-d),f.max=d,f.isHorizontal=!1,f.isReversed=!0,b.fo.wa(d+b.Un),b.fo.ta(f,h.a,h.b),e=0,"bottom"==b.UT&&(e=b.i3()),b.fo.Lm(c.pa()-(b.cj-d-e),c.pa()))}};r.Gr=
function(b){var c=b.Zt,d=b.Yy;b.Gb?(b.Gb.te(null),b.Gb.Xa(c),b.Gb.qb(d)):b.Gb=new a.Rect(b.u(),b.Hca,0,c,d,"bg");b.Gb.Ok("style","stroke-width:"+2*b.Tk+"px");a.K.Y(b.Gb.Ua(),"class",b.Fy("databody"));b.Gb.md();b.Gb.setCursor("move");var e=new a.Cd;e.Pe(b.Hca,0,c,d);b.Gb.te(e);b.Gb.getParent()!=b&&b.A(b.Gb)};r.mOa=function(b){var c=b.Uf;b.GL?b.GL.Xa(c):b.GL=new a.Rect(b.u(),b.bn,b.Un,c,0);a.K.Y(b.GL.Ua(),"class",b.Fy("row"));b.GL.md();var d=new a.Cd;d.Pe(b.bn,b.Un,c,b.cj);b.GL.te(d);b.GL.getParent()!=
b&&b.A(b.GL)};r.WPa=function(b){var c=b.Kx;if(null!=c&&0<c.length){var d=0;b.Pva()&&(d=n.jua(b.F()));var e=b.GL;e.jb(b.ND);c=c[c.length-1].bC+c[c.length-1].HL+d;"dataChange"===b.ro?b.lwa.ja.N(a.G.V,e,e.getHeight,e.qb,c):e.qb(c)}};r.c2=function(b){b.nh||(b.nh=new a.la(b.u(),"canvas"),b.A(b.nh))};r.Zqa=function(a,b){var c=a.Ar,d=a.Xp;if("top"==a.UT){var e=0;c&&(r.IH(a,b,c,e,a.zda()),e+=c.pe());d&&(r.IH(a,b,d,e,a.zda()),e+=d.pe());a.lWa(e)}else e=a.cj,c&&(r.IH(a,b,c,null,a.zda()),e-=c.pe(),r.AL(c,e)),
d&&(r.IH(a,b,d,e,a.zda()),e-=d.pe(),r.AL(d,e)),a.lWa(0)};r.IH=function(a,b,c,d,e){c.getParent()!==b&&b.A(c);c.ta(null,a.je,e);null!=d&&r.AL(c,d)};r.AL=function(b,c){var d=new a.Tb(1,0,0,1,0,c);b.rb(d)};r.e2=function(b){var c=b.u(),d=a.B.da(c),e=b.BM(),h=n.pD,f=n.qD,k=a.Ah.mt(c,b.jj.zoomIn,h,f),l=a.Ah.mt(c,b.jj.zoomIn_h,h,f),m=a.Ah.mt(c,b.jj.zoomIn_a,h,f),z=a.Ah.mt(c,b.jj.zoomIn_d,h,f);null==b.Jh?(b.Jh=new a.Ah(c,k,l,m,z,b.I,b.I.iZ),b.I.lb(b.Jh,b.Jh)):(b.Jh.zF(k),b.Jh.vF(l),b.Jh.sF(m),b.Jh.Z4(z));
k=a.Ah.mt(c,b.jj.zoomOut,h,f);l=a.Ah.mt(c,b.jj.zoomOut_h,h,f);m=a.Ah.mt(c,b.jj.zoomOut_a,h,f);z=a.Ah.mt(c,b.jj.zoomOut_d,h,f);null==b.Kh?(b.Kh=new a.Ah(c,k,l,m,z,b.I,b.I.jZ),b.I.lb(b.Kh,b.Kh)):(b.Kh.zF(k),b.Kh.vF(l),b.Kh.sF(m),b.Kh.Z4(z));b.Jh.tn(a.H.va(a.H.Ha,"ZOOM_IN",null));b.Kh.tn(a.H.va(a.H.Ha,"ZOOM_OUT",null));b.Jh.Vq();b.Kh.Vq();a.Ub.vn()&&(a.K.Y(b.Jh.Ua(),"role","button"),a.K.Y(b.Jh.Ua(),"aria-label",a.H.va(a.H.Ha,"ZOOM_IN",null)),a.K.Y(b.Kh.Ua(),"role","button"),a.K.Y(b.Kh.Ua(),"aria-label",
a.H.va(a.H.Ha,"ZOOM_OUT",null)));c=b.bn+n.UZ;d=d?c:b.Zt-c-n.aK;b.Jh.ga(d);b.Kh.ga(d);d=b.Un+n.UZ;c="top"==b.UT?d:b.Yy-d;b.Jh.wa(d);b.Kh.wa(d+n.aK+n.VZ);"top"==b.UT?(b.Jh.wa(c),b.Kh.wa(c+n.aK+n.VZ)):(b.Jh.wa(c-2*n.aK-n.VZ),b.Kh.wa(c-n.aK));b.Jh.getParent()!=b.nh&&b.nh.A(b.Jh);b.Kh.getParent()!=b.nh&&b.nh.A(b.Kh);d=b.je;d>=e.qV&&b.cM(!0);b.Uf>=d&&b.cM(!1)};r.JH=function(b){var c=a.H.va(a.H.Ha,"NO_DATA",null),c=a.Ca.vp(b.nh,c,new a.Z(0,0,b.Zt,b.Yy),b.I,null);a.K.Y(c.Ua(),"class",b.Fy("nodata"));b.d5(c)};
r.Jeb=function(b,c){var d=b.TG;null==d&&(d=new a.la(b.u(),"db"),c.A(d),b.Jrb(d));d.wa(b.ND);r.QPa(b,d)};r.QPa=function(b,c){var d=b.cj,e=b.Ar,h=b.Xp;e&&(d-=e.pe());h&&(d-=h.pe());e=new a.Cd;e.Pe(0,b.ND,b.je,d);c.te(e)};r.kra=function(b,c){var d=b.$ab;null!=d&&d.Hl();if(b.Lob()){null==d&&(d=new a.la(b.u()),c.A(d),b.Tsb(d));var e=b.Fy("vgridline"),h=b.Ar;if(null==h||b.F().minorGridline)h=b.Xp;for(var h=h.Ua().getElementsByTagName("line"),f=0;f<h.length;f++){var k=a.K.El(h[f],"x1"),k=new a.Gc(b.u(),
k,b.ND,k,b.ND+b.cj-b.i3());k.md();a.K.Y(k.Ua(),"class",e);d.A(k)}}};r.mfb=function(a,b){var d=a.F(),e=d.rows,h=r.Qdb(e);if(0!=e.length&&h){r.Jeb(a,b);var h=0,f=a.TG,k=0;a.Pva()&&(k=n.jua(d));d={};if(a.Kx)for(l=r.o$a(a),m=0;m<l.length;m++)z=l[m],z.ega(h),z.ta(f),d[z.getId()]=z,h=h+z.HL+k;else for(var l=[],m=0;m<e.length;m++){var z=new c(a,e[m],m,h);z.ta(f);l.push(z);d[z.getId()]=z;h=h+z.HL+k}h-=k;a.ssb(d);a.Isb(l);a.Erb(h)}else r.JH(a)};r.Qdb=function(a){for(var b=0;b<a.length;b++){var c=a[b];if(null==
c.id){var d=c.tasks;if(1==d.length)c.id=d[0].id;else return!1}}return!0};r.o$a=function(b){for(var d=b.Kx,e=b.Tcb,h="dataChange"===b.ro,f={},k={},n=[],l={},m=b.Afb,z=b.F().taskDefaults,G=0;G<m.length;G++){for(var y=m[G],E=y.id,M=y.tasks,r=0;r<M.length;r++){var O=M[r];k[O.id]={rowId:E,taskProps:a.ac.Vd(O,z)}}(r=e[E])?(r.k5(y),r.eUa(),r.oF("same"),n.push(r),f[E]=r,delete e[r.getId()]):(n.push(0),l[G]=y,f[E]=!0)}var r=Object.keys(e),fa;for(fa in l)l.hasOwnProperty(fa)&&(y=l[fa],0<r.length?(G=r.pop(),
G=e[G],G.k5(y),G.eUa(),G.oF("refurbished"),G.remove()):G=new c(b,y,0),f[y.id]=G,n[fa]=G);for(G=0;G<r.length;G++)b=e[r[G]],b.oF("delete"),b.remove();b={};for(G=0;G<d.length;G++)for(l=d[G],y=l.fA(),r=0;r<y.length;r++)fa=y[r],fa.Wqb(),(z=k[fa.getId()])?l.getId()==z.rowId&&l.dwa(z.taskProps)?(fa.k5(z.taskProps),fa.oF("same"),delete k[fa.getId()]):(fa.oF("moved"),h&&(b[fa.getId()]=fa.ova()),e[l.getId()]||l.gQa(fa)):e[l.getId()]||(fa.oF("refurbished"),fa.MVa(),l.gQa(fa));for(var ga in k)if(k.hasOwnProperty(ga)){d=
k[ga];G=d.taskProps;e=f[d.rowId];d=e.Ala;if(0<d.length){if(e.dwa(G)){var aa=d.pop();aa.k5(G)}}else(aa=e.kRa(G))&&e.whb(aa);h&&aa&&b[ga]&&(aa.MVa(b[ga]),aa.oF("migrate"))}for(G=0;G<m.length;G++)for(y=m[G],E=y.id,h=f[E],d=h.Ala;0<d.length;)k=d.pop(),h.Cqb(k),k.remove();return n};a.v.D(c,a.la);c.prototype.Init=function(a,b,d,e){c.C.Init.call(this,a.u(),null,b.id);this.Wf=a;this.Pf=b;this.fp=d;this.bC=e;this.HL=0;this.Ala=[];this.Sk="new"};c.prototype.k5=function(a){this.Pf=a};c.prototype.kb=function(){return this.fp};
c.prototype.ega=function(a){this.bC=a};c.prototype.getId=function(){return this.Pf.id};c.prototype.ge=function(){return this.Pf.label};c.prototype.kf=function(){return this.Pf.labelPosition};c.prototype.gQa=function(a){this.Ala.push(a)};c.prototype.dwa=function(a){var b=this.Wf.Ti(),c=this.Wf.hl();a.start=this.qJa(a.start);a.end=this.qJa(a.end);return null==a.start&&null==a.end||a.start&&a.end&&((a.end?a.end:a.start)<b||a.start>c)?!1:!0};c.prototype.ge=function(){return this.Pf.label};c.prototype.kf=
function(){return this.Pf.labelPosition};c.prototype.kRa=function(a){return this.dwa(a)?new b(this.Wf,this,a):null};c.prototype.fA=function(){var b=this.Pf.tasks;if(b&&null==this.ZB){this.ZB=[];for(var c=0;c<b.length;c++){var d=b[c],d=a.ac.Vd(d,this.Wf.F().taskDefaults);(d=this.kRa(d))&&this.ZB.push(d)}this.PWa()}return this.ZB};c.prototype.whb=function(a){null==this.ZB?this.ZB=[a]:this.ZB.push(a)};c.prototype.Cqb=function(a){null!=this.ZB&&(a=this.ZB.indexOf(a),-1<a&&this.ZB.splice(a,1))};c.prototype.PWa=
function(){null!=this.ZB&&this.ZB.sort(function(a,b){return(a.Ti()?a.Ti():a.hl())-(b.Ti()?b.Ti():b.hl())})};c.prototype.ta=function(a){this.PWa();var c=this.fA();if(null!=c)for(var d=[],e=0;e<c.length;e++){var h=0,f=c[e],k=d.length,n=null;if(0===k)d.push(f);else{for(var l=!0,z=0;z<k;z++){var G=d[z];if(b.wob(G,f))h+=G.iua();else{n=d[z];d[z]=f;l=!1;break}}l&&d.push(f)}f.ega(h);f.ta(this,n)}this.getParent()!=a&&a.A(this);this.Ueb(this.Wf,this,this)};c.prototype.Ueb=function(b,c,d){if(b.Pva())if(this.Hs){c=
this.bC+this.HL;this.Hs.un(b.je);var e=this.Sk;"dataChange"===b.ro?"refurbished"===e?(b.Rca.push(this.Hs),this.Hs.Il(c),this.Hs.Jl(c)):"same"===e?(b=b.lwa.ja,b.N(a.G.V,this.Hs,this.Hs.Rr,this.Hs.Il,c),b.N(a.G.V,this.Hs,this.Hs.ot,this.Hs.Jl,c)):(this.Hs.Il(c),this.Hs.Jl(c)):(this.Hs.Il(c),this.Hs.Jl(c))}else{var e=b.Fy("hgridline"),h=n.jua(b.F())%2*.5;d=d.bC+d.HL+h;d=new a.Gc(b.u(),0,d,b.je,d);d.md();a.K.Y(d.Ua(),"class",e);c.A(d);this.Hs=d;"dataChange"===b.ro&&"new"===this.Sk&&b.Rca.push(this.Hs)}};
c.prototype.oF=function(a){this.Sk=a};c.prototype.JRa=function(){return this.Sk};c.prototype.remove=function(){"dataChange"===this.Wf.ro?"refurbished"===this.Sk?this.Wf.PVa.push(this):"delete"===this.Sk?this.Wf.tfa.push(this):this.getParent()&&this.getParent().removeChild(this):this.getParent().removeChild(this)};c.prototype.Hsb=function(a){a>this.HL&&(this.HL=a)};c.prototype.eUa=function(){this.HL=0};c.prototype.qJa=function(a){return null==a?null:a.getTime?a.getTime():isNaN(a)?(new Date(a)).getTime()+
0:a};a.v.D(b,a.la);b.LF=2;b.dza=.35;b.prototype.Init=function(a,c,d){b.C.Init.call(this,a.u(),null,d.id);this.Wf=a;this.yra=c;this.Pf=d;this.BIa=!1;this.Sk="new"};b.prototype.Wqb=function(){this.wb()&&this.kc(!1);this.oF("new")};b.prototype.k5=function(a){this.Pf=a};b.prototype.Tq=function(){return this.yra};b.prototype.getId=function(){return this.Pf.id};b.prototype.Ti=function(){return this.Pf.start};b.prototype.hl=function(){return this.Pf.end};b.prototype.ge=function(){return this.Pf.label};b.prototype.kf=
function(){return this.IU("labelPosition")};b.prototype.nI=function(){return this.IU("labelStyle")};b.prototype.SQ=function(){return this.IU("borderRadius")};b.prototype.getHeight=function(){return this.IU("height")};b.prototype.iua=function(){return this.getHeight()+2*n.wea()};b.prototype.M=function(){return this.IU("style")};b.prototype.Vx=function(){return this.IU("className")};b.prototype.Xa=function(a){this.zb=a};b.prototype.getWidth=function(){return this.zb};b.prototype.ega=function(a){this.bC=
a};b.prototype.iI=function(){return this.oi.getWidth()};b.prototype.Yjb=function(){return this.oi.getHeight()};b.prototype.UR=function(a){this.oi.Xa(a);this.Mz&&this.Mz.Xa(a+2*b.LF);this.Nn&&this.Nn.Xa(a+2*b.LF)};b.prototype.trb=function(a){this.oi.qb(a);this.Mz&&this.Mz.qb(a+2*b.LF);this.Nn&&this.Nn.qb(a+2*b.LF)};b.prototype.ct=function(){null==this.ur&&(this.ur=b.Y$a(this.Wf,this.oi));return this.ur};b.prototype.esb=function(a){this.bE=a};b.prototype.oF=function(a){this.Sk=a};b.prototype.JRa=function(){return this.Sk};
b.prototype.IU=function(a){return this.Pf[a]};b.prototype.remove=function(){"dataChange"===this.Wf.ro&&"moved"!==this.Sk?(this.oF("delete"),this.Wf.UM.push(this)):this.yra&&this.yra.removeChild(this)};b.prototype.ta=function(c,d){this.getParent()!=c&&c.A(this);this.cg("img");a.Ub.vn()&&this.Hr(this.Tq().kb());"dataChange"===this.Wf.ro&&("refurbished"===this.Sk&&this.Wf.UM.push(this),"new"!==this.Sk&&"refurbished"!==this.Sk||this.Wf.vda.push(this));b.veb(this.Wf,this);b.KH(this.Wf,this,d);this.BIa||
(this.Wf.ab().lb(this,this),this.BIa=!0);if("dataChange"===this.Wf.ro)if("refurbished"===this.Sk)this.Swa();else if("migrate"===this.Sk){this.Swa();this.vQa();var e=this.Wf.jVa.ja,h=this.Wf.xUa.ja;e.N(a.G.V,this,this.iI,this.UR,this.DK.bar.width);e.N(a.G.V,this,this.Yjb,this.trb,this.DK.bar.height);h.N(a.G.V,this,this.qa,this.ga,this.DK.task.translateX);h.N(a.G.V,this,this.pa,this.wa,this.DK.task.translateY);h=this.bE;e.N(a.G.V,h,h.Va,h.Fa,this.DK.label.x);e.N(a.G.V,h,h.ib,h.jb,this.DK.label.y);a.eb.Mb(e,
function(){this.tQa()},this)}};b.prototype.ova=function(){var a=this.oi,b=this.bE;return{task:{width:this.getWidth(),top:this.bC,translateX:this.qa(),translateY:this.pa()},bar:{width:a.getWidth(),height:a.getHeight()},label:{textString:b.lf(),x:b.Va(),y:b.ib()}}};b.prototype.wQa=function(a){var b=this.oi,c=this.bE,d=a.task;this.Xa(d.width);this.ega(d.top);this.ga(d.translateX);this.wa(d.translateY);d=a.bar;b.Xa(d.width);b.qb(d.height);a=a.label;c.xg(a.textString);c.Fa(a.x);c.jb(a.y)};b.prototype.MVa=
function(a){this.Sdb=a?a:this.ova()};b.prototype.vQa=function(){this.wQa(this.Sdb)};b.prototype.Swa=function(a){this.DK=a?a:this.ova()};b.prototype.tQa=function(){this.wQa(this.DK)};b.wob=function(a,b){var c=a.Ti(),d=a.hl();null==c?c=d:null==d&&(d=c);var e=b.Ti(),h=b.hl();null==e?e=h:null==h&&(h=e);return c<h&&e<d};b.poa=function(b,c,d){var e=b.Ti(),h=b.hl();b=b.je;var f=c.Ti();c=c.hl();null==f?f=c:null==c&&(c=f);f=a.Ub.bf(e,h,f,b);e=a.Ub.bf(e,h,c,b);d&&(f=b-f,e=b-e);return{hN:f,fI:e}};b.veb=function(c,
d){var e=a.B.da(c.u()),h=b.poa(c,d,e),e=h.hN,f=d.bC,h=Math.max(0,Math.abs(h.fI-e)),k=d.oi;if(k)"dataChange"===c.ro?"same"!==d.Sk&&d.UR(h):d.UR(h);else{var k=c.u(),l=d.SQ();"onDisplay"===c.ro?(k=new m(k,0,n.wea(),0,d.getHeight(),l),c.gia.ja.N(a.G.V,d,d.iI,d.UR,h)):k=new m(k,0,n.wea(),h,d.getHeight(),l);(l=d.M())&&a.K.Y(k.Ua(),"style",l);var l=c.Fy("task"),B=d.Vx();B?a.K.Y(k.Ua(),"class",l+" "+B):a.K.Y(k.Ua(),"class",l);d.A(k);d.oi=k}k=d.Tq();k.Hsb(f+d.iua());d.Xa(h);"dataChange"===c.ro?"same"===d.Sk?
(l=c.yUa.ja,l.N(a.G.V,d,d.qa,d.ga,e),l.N(a.G.V,d,d.pa,d.wa,k.bC+f),c.dxa.ja.N(a.G.V,d,d.iI,d.UR,h)):"new"===d.Sk||"refurbished"===d.Sk?(d.ga(e),d.wa(k.bC+f),d.UR(0),c.nwa.ja.N(a.G.V,d,d.iI,d.UR,h)):(d.ga(e),d.wa(k.bC+f)):(d.ga(e),d.wa(k.bC+f))};b.KH=function(c,d,e){var h=d.bE,f=d.kf(),k=a.B.da(c.u());if(null==h){var m=d.ge();null!=m&&(h=new l(c.u(),m,0,0,c.sX),a.K.Y(h.Ua(),"class",c.Fy("taskLabel")),k&&h.Wh(),d.esb(h),d.A(h))}var m=new a.j(n.Wmb(c.F())),B=d.nI();null!=B&&(m.lj(B),"string"===typeof B?
h.Ua().style.cssText=B:a.K.Y(h,"style",B));h.Bb(m);b.wgb(d,e);m=a.Ca.Pj(h);h.jb((d.iua()-m.b)/2);e=n.QTa();switch(f){case "start":k?h.Vh():h.Wh();f=-e;break;case "end":k?h.Wh():h.Vh();f=d.getWidth()+e;break;case "innerStart":k?h.Wh():h.Vh();f=e;break;case "innerEnd":f=d.getWidth();m.a<f?(k?h.Vh():h.Wh(),f=d.getWidth()-e):(k?h.Wh():h.Vh(),m=h.aa(),f=Math.max(e,f-m.a-e));break;case "innerCenter":f=d.getWidth();m.a<f?(h.Yf(),f=d.getWidth()/2):(k?h.Wh():h.Vh(),m=h.aa(),f=Math.max(e,(f-m.a)/2));break;
default:k?h.Vh():h.Wh(),f=-e}k&&(f=-f);"onDisplay"===c.ro?(h.Fa(0),c.gia.ja.N(a.G.V,h,h.Va,h.Fa,f)):"dataChange"===c.ro?"same"===d.Sk?c.dxa.ja.N(a.G.V,h,h.Va,h.Fa,f):"new"===d.Sk||"refurbished"===d.Sk?(h.Fa(0),c.nwa.ja.N(a.G.V,h,h.Va,h.Fa,f)):h.Fa(f):h.Fa(f)};b.wgb=function(c,d){var e=c.kf(),h=c.bE;h.ao()&&h.xg(h.Uq());var f=n.QTa();if("innerStart"==e||"innerEnd"==e||"innerCenter"==e){a.Ca.kd(h,c.getWidth()-f,c.getHeight(),c,1);var k=a.O.Wl(c.ct());null!=k&&h.ra(new a.$b(k))}else{var l=c.Wf,m=l.Ti(),
C=l.hl(),z=l.je,G=b.poa(l,c,!1);if(d){var y=d.kf(),k=d.bE,E=b.poa(l,d,!1);"end"==y&&k.ao()&&k.xg(k.Uq())}if("start"==e){l=a.Ub.bf(m,C,m,z)+f;d&&(l="end"==y?(G.hN-f-(E.fI+f))/2+f:E.fI+f);var M=G.hN-f-l}else"end"==e&&(l=a.Ub.bf(m,C,C,z)-f,M=l-(G.fI+f));h=a.Ca.kd(h,M,c.getHeight(),c,1);d&&"end"==y&&(l="start"==e?(G.hN-f-(E.fI+f))/2-f:G.hN-f,M=l-(E.fI+f),(h=a.Ca.kd(k,M,d.getHeight(),d,1))&&"migrate"===d.Sk&&(e=d.DK,e.label.textString=k.lf(),d.Swa(e)))}};b.Y$a=function(a,b){if(null==b)return null;var c=
b.Ua().cloneNode(!1),d=a.u().Ob;d.appendChild(c);try{var e=window.getComputedStyle(c).fill;if(String.prototype.startsWith?!e.startsWith("url("):0!=e.indexOf("url("))return e}finally{d.removeChild(c)}return null};b.prototype.Tta=function(a){if(null==a)return"";a=new Date(a);var b=this.Wf.Xp.nf;return"hours"==b||"minutes"==b||"seconds"==b?a.toLocaleString():a.toLocaleDateString()};b.prototype.$s=function(b,c){var d=this.Wf.F(),e=c-b,h=this.Wf.Xp.nf;if("hours"==h||"minutes"==h||"seconds"==h)return e=
Math.round(e/36E5*100)/100,a.H.Bf(d,"accessibleDurationHours",a.H.Ha,"DURATION_HOURS",[e]);e=Math.round(e/864E5*100)/100;return a.H.Bf(d,"accessibleDurationDays",a.H.Ha,"DURATION_DAYS",[e])};b.prototype.Ed=function(b){var c=[],d=this.Wf.F();this.tb()&&c.push(a.H.Bf(d,this.wb()?"stateSelected":"stateUnselected",a.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));var e=this.Ti(),h=this.hl();if(null==e||null==h||e==h)var f=a.H.Bf(d,"accessibleMilestoneInfo",a.H.Ha,"MILESTONE_INFO",[this.Tta(null!=
e?e:h)]);else var f=this.Tta(e),k=this.Tta(h),e=this.$s(e,h),f=a.H.Bf(d,"accessibleTaskInfo",a.H.Ha,"TASK_INFO",[f,k,e]);k=this.ge();null!=k&&(f=k+", "+f);k=this.Tq().getId();if(this.Wf.o9a!=k){if(null==b)for(k=this.Tq().Ua(),e=k.parentNode.childNodes,h=0;h<e.length;h++)if(e[h]==k){b=h;break}f=a.H.Bf(d,"accessibleRowInfo",a.H.Ha,"ROW_INFO",[b+1])+", "+f}b=a.oa.Ik(f,c);c=this.Qjb();return null!=c&&-1<c.indexOf(b)?null:b};b.prototype.Hr=function(a){this.Gd("label",this.Ed(a));this.sQa()};b.prototype.tb=
function(){return"none"!=this.Wf.F().selectionMode};b.prototype.wb=function(){return this.Lg};b.prototype.kc=function(a){this.Lg=a;this.Tdb(a);this.Hr();this.Wf.Irb(this.Tq().getId())};b.prototype.Tdb=function(a){a?null==this.Mz&&(a=this.GHa("selected"),this.Ib(a,0),this.Mz=a):(null!=this.Mz&&this.removeChild(this.Mz),this.Mz=null)};b.prototype.GHa=function(c){var d=a.B.da(this.Wf.u())?b.LF:-b.LF,e=n.wea()-b.LF,h=this.oi.getWidth()+2*b.LF,f=this.oi.getHeight()+2*b.LF,k=this.SQ(),d=new m(this.Wf.u(),
d,e,h,f,k);a.K.Y(d.Ua(),"class",this.Wf.Fy("task"));a.K.Y(d.Ua(),"style","fill:none");a.KF.Zgb(d.Ua(),this.Wf.Fy(c));return d};b.prototype.qd=function(){if(null==this.Nn){var b=this.GHa("hover");this.Ib(b,0);this.Nn=b;var c=this.ct();null!=c&&b.Ga(a.Rt.Pib(c));"dim"==this.Wf.C3()&&this.Wf.HWa(this,!0)}};b.prototype.Nc=function(){null!=this.Nn&&(this.removeChild(this.Nn),this.Nn=null);"dim"==this.Wf.C3()&&this.Wf.HWa(null,!1)};b.prototype.Yib=function(){null!=this.oi&&this.oi.T(b.dza);null!=this.Mz&&
this.Mz.T(b.dza)};b.prototype.Ohb=function(){null!=this.oi&&this.oi.T(1);null!=this.Mz&&this.Mz.T(1)};b.prototype.Fd=function(b){var c=this.Wf.ab().Cb;return b.type==a.MouseEvent.Be||c.Nu(b)?this:c.Vi(b)?e.Fd(this.Wf,this,b):null};b.prototype.rf=function(a){return this.aa(a)};b.prototype.Jm=function(){return this.oi.Ua()};b.prototype.Sf=function(){this.dd=!0;this.qd()};b.prototype.Qd=function(){this.Kd()&&(this.dd=!1,this.Nc())};b.prototype.Kd=function(){return this.dd};a.Ia(a,"Gantt",a.$c);a.Ia(a.$c,
"newInstance",a.$c.newInstance);a.Ia(a.$c.prototype,"destroy",a.$c.prototype.xa);a.Ia(a.$c.prototype,"getAutomation",a.$c.prototype.ph);a.Ia(a.$c.prototype,"render",a.$c.prototype.ta);a.Ia(k.prototype,"getDomElementForSubId",k.prototype.qh);a.Ia(k.prototype,"GetSubIdForDomElement",k.prototype.zn)})(dvt);
  return dvt;
});
