/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit', './DvtAxis'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a){this.Init(a.u(),a.dispatchEvent,a);this.Ig=a}function c(a){this.Init();this.Ig=a}function d(){this.Init({skyros:d.lh,alta:d.mf})}function e(a){this.Init(a)}function f(){this.Init({skyros:f.lh,alta:{}})}function h(a,b,c,d,e,h){this.Init(a,b,c,d,e,h)}function k(a,b,c,d,e,h){this.Init(a,b,c,d,e,h)}function l(){this.Init({skyros:l.lh,alta:l.mf})}function m(){this.Init({skyros:m.lh,alta:{}})}function n(a,b){this.Init(a,b)}function r(a){this.Init(a.u(),a.dispatchEvent,a);this.Ig=
a;this.ks=!1}function p(){}function w(a){this.Ig=a}function x(){}a.v.D(x,a.Ie);x.Xub=0;x.Wub=100;x.prototype.Init=function(b,c,d,e){x.C.Init.call(this,b,c,d);this.Rla=e;this.Rla||(this.I=this.uS(),this.I.Qf(this),a.B.Wa()||this.I.Xr(this.TC(this.I)),this.setId("gauge1000"+Math.floor(1E9*Math.random())),this.WO=new a.Rect(b,0,0),this.WO.Wb(),this.A(this.WO));this.Pla=this.rK=!1;this.w1=null};x.prototype.vf=function(b){this.W=b;a.B.xj()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange=
"none")};x.prototype.ta=function(b,c,d){b?this.vf(b):this.W||this.vf(null);this.W.thresholds&&(this.W.thresholds=this.W.thresholds.sort(x.mgb));isNaN(c)||isNaN(d)||(this.Pla=0!=this.xb&&this.xb!=c||0!=this.Jb&&this.Jb!=d?!0:!1,this.xb=c,this.Jb=d);d=this.rG;this.rG=[];c=new a.la(this.u());this.Ib(c,0);this.Fn(c,this.xb,this.Jb);this.Jfb(c,null!=b,d,this.xb,this.Jb);this.WO&&(this.WO.Xa(this.xb),this.WO.qb(this.Jb),this.ab().lb(this.WO,this.DT(),!0));this.hr();this.Rla||this.W.readOnly||(c.cg("slider"),
c.Gd("valuemin",this.W.min),c.Gd("valuemax",this.W.max),b=u.Ko(this.W.value,this),c.Gd("valuenow",b),d=u.Bea(this),a.B.Wa()&&(this.Ea.Gd("live","assertive"),b!=d&&(d=b+a.H.va(a.H.Ha,"ARIA_LABEL_DESC_DELIMITER")+d)),b!=d&&c.Gd("label",d),this.Kz=null!=this.Kz?this.Kz+1:0,b=this.getId()+"_"+this.Kz,c.setId(b),this.u().NI(c));this.W._selectingCursor&&this.setCursor("pointer");this.lc||this.qs()};x.prototype.DT=function(){var b=this.W.tooltip,c=b?b.renderer:null,b=A.ic(this);if(c){var d={component:this.W._widgetConstructor,
label:u.Ko(this.W.value,this),color:b};return new a.kJ(this.u().Af(),c,b,d)}c=u.Bea(this);return new a.yi(null,c,b)};x.prototype.Fn=function(){};x.prototype.Jfb=function(b,c,d,e,h){this.fr();var f=!1,k=this.rK||this.Pla?"none":this.F().animationOnDataChange,z=this.rK||this.Pla?"none":this.F().animationOnDisplay,n=a.Ta.Pr(this.F().animationDuration)/1E3;if(z||k)e=new a.Z(0,0,e,h),h=this.u(),this.Ea||"none"===z||null==this.rG[0]?this.Ea&&"none"!=k&&c&&null!=this.rG[0]&&((this.lc=a.pc.gM(h,k,this.Ea,
b,e,n))?f=!0:this.lc=this.dYa(d,this.rG,n)):(this.lc=a.pc.RE(h,z,b,e,n),this.lc||(this.lc=this.Mga(this.rG,z,n))),!f&&this.Ea&&(this.removeChild(this.Ea),this.Ea.xa()),this.lc&&(this.lc.play(),this.lc.lg(this.Tv,this)),f&&(this.Hj=this.Ea),this.Ea=b};x.prototype.Mga=function(){return null};x.prototype.dYa=function(b,c,d){for(var e=[],h=0;h<b.length;h++){var f=c[h],k=b[h].qf(),z=f.qf();f.df(k);k=new a.gd(this.u(),f,d);k.ja.N(a.G.wf,f,f.qf,f.df,z);e.push(k)}return new a.Gg(this.u(),e)};x.prototype.uJ=
function(){return null};x.prototype.WVa=function(){this.ta();this.hka(this.Ea)};x.prototype.hka=function(b,c){c=u.Ko(c?c:this.W.value,this);b.Gd("valuenow",c);a.B.Wa()&&b.Gd("label",c)};x.prototype.Tv=function(){this.Hj&&(this.removeChild(this.Hj),this.Hj.xa(),this.Hj=null);this.wn||this.qs();this.lc=null;this.wn=!1};x.prototype.E8=function(a,b){this.rK=!0;this.w1=this.W.value;this.HT(a,b)};x.prototype.HT=function(b,c){null!=this.w1&&(this.W.value=u.Tca(this.W,this.uJ(b,c)),this.WVa(),this.dispatchEvent(a.Za.MM(this.w1,
this.W.value,!1)))};x.prototype.dla=function(b,c){this.HT(b,c);if(a.B.Wa()){var d=u.Ko(this.W.value,this),e=u.Bea(this);d!=e&&(e=d+a.H.va(a.H.Ha,"ARIA_LABEL_DESC_DELIMITER")+e,this.Ea.Gd("label",e))}this.dispatchEvent(a.Za.MM(this.w1,this.W.value,!0));this.rK=!1;this.w1=null};x.prototype.m6a=function(){if(!this.W.readOnly){var b=this.W.value;this.W.value=null!=this.W.step?u.Tca(this.W,this.W.value+this.W.step):Math.min(Math.max(this.W.value+(this.W.max-this.W.min)/100,this.W.min),this.W.max);this.ta();
this.dispatchEvent(a.Za.MM(b,this.W.value,!0))}};x.prototype.g6a=function(){if(!this.W.readOnly){var b=this.W.value;this.W.value=null!=this.W.step?u.Tca(this.W,this.W.value-this.W.step):Math.min(Math.max(this.W.value-(this.W.max-this.W.min)/100,this.W.min),this.W.max);this.ta();this.dispatchEvent(a.Za.MM(b,this.W.value,!0))}};x.prototype.uS=function(){return new r(this)};x.mgb=function(a,b){return null!=a.max&&null!=b.max?a.max-b.max:a.max?-Infinity:Infinity};x.prototype.ph=function(){return new w(this)};
x.prototype.TC=function(a){return new n(a,this)};x.prototype.gm=function(){return a.H.Bf(this.F(),"componentName",a.H.Ha,"GAUGE")};x.prototype.hr=function(){if(!this.Rla){var b=u.Bea(this);this.d7()?this.W.readOnly?(this.u().cg("img"),this.u().U4(a.H.va(a.H.Ha,"COLON_SEP_LIST",[a.H.va(a.H.Ha,"DATA_VISUALIZATION"),a.oa.Ik(a.Nd.HI(this.gm()),b?[b]:null)]))):(this.u().cg("application"),this.u().U4(a.H.va(a.H.Ha,"COLON_SEP_LIST",[a.H.va(a.H.Ha,"DATA_VISUALIZATION"),a.Nd.HI(this.gm())]))):this.W.readOnly&&
(this.cg("img"),this.Gd("label",a.oa.Ik(a.Nd.HI(this.gm()),b?[b]:null)))}};a.v.D(w,a.Rd);w.prototype.qh=function(b){if(b==a.Rd.lD)return this.RF(this.Ig);if(0==b.indexOf("item")){var c=b.indexOf("["),d=b.indexOf("]");if(0<c&&0<d&&(b=this.Ig.JFa(b.substring(c+1,d))))return b.Ua()}return null};w.prototype.zn=function(a){for(var b=this.Ig.F(),c=0;c<b.max;c++)if(this.Ig.JFa(c)==a)return"item["+c+"]";return null};w.prototype.getValue=function(){return this.Ig.F().value};w.prototype.Nlb=function(){return u.Ko(this.getValue(),
this.Ig)};a.H.fC(a.H.wZa,{});a.v.D(p,a.bb);p.mf={skin:a.j.mf,color:"#393737",metricLabel:{style:new a.j(a.bb.Pm)},_statusMessageStyle:new a.j(a.bb.Pm),title:{style:new a.j(a.bb.Pm)},_thresholdColors:["#ed6647","#fad55c","#68c182"]};p.lh={skin:a.j.Hg,min:0,max:100,center:{},color:"#313842",borderColor:null,visualEffects:"auto",emptyText:null,animationOnDataChange:"none",animationOnDisplay:"none",animationDuration:500,readOnly:"true",metricLabel:{rendered:"auto",scaling:"auto",style:new a.j(a.bb.It),
textType:"number"},_statusMessageStyle:new a.j(a.bb.It),title:{style:new a.j(a.bb.It),position:"auto"},_thresholdColors:["#D62800","#FFCF21","#84AE31"],__layout:{outerGap:1,labelGap:5}};p.prototype.Init=function(b){b={skyros:a.ac.Vd(b.skyros,p.lh),alta:a.ac.Vd(b.alta,p.mf)};p.C.Init.call(this,b)};p.rA=function(b){return b.F().skin==a.j.Hg};var v={};a.v.D(v,a.v);v.rC=function(a){var b=a.F();return b&&null!=b.value&&v.mUa(a)};v.mUa=function(a){a=a.F();return Number(a.min)<Number(a.max)};v.wR=function(a,
b){var c=a.F(),d=null!=b?b:c.value,c=c.thresholds;if(!c)return-1;for(var e=0;e<c.length;e++)if(d<=c[e].max)return e;return c.length-1};v.lX=function(a,b){var c=a.F().thresholds;return c&&0<=b&&b<c.length?c[b]:null};v.$vb=function(a,b){var c=a.F().referenceLines;return c&&0<=b&&b<c.length?c[b]:null};a.v.D(r,a.I);r.prototype.mo=function(a){if(!1===this.Ig.F().readOnly){this.ks=!0;this.qe();var b=this.QF(a.pageX,a.pageY);this.Ig.E8(b.x,b.y);a.preventDefault()}else r.C.mo.call(this,a)};r.prototype.Uo=
function(a){this.ks?(this.ks=!1,a=this.QF(a.pageX,a.pageY),this.Ig.dla(a.x,a.y)):r.C.Uo.call(this,a)};r.prototype.Ly=function(a){if(this.ks){var b=this.QF(a.pageX,a.pageY);this.Ig.HT(b.x,b.y)}!this.hia()&&this.ks||r.C.Ly.call(this,a)};r.prototype.hia=function(){return!1};r.prototype.EZ=function(b){if(a.TouchEvent.$i===b.type&&!1===this.Ig.F().readOnly){this.ks=!0;var c=this.QF(b.touches[0].pageX,b.touches[0].pageY);this.Ig.E8(c.x,c.y);b.preventDefault()}else a.TouchEvent.Xo===b.type&&this.ks?(c=this.QF(b.touches[0].pageX,
b.touches[0].pageY),this.Ig.HT(c.x,c.y),b.preventDefault()):a.TouchEvent.Rm===b.type&&this.ks&&(this.ks=!1,c=this.QF(b.changedTouches[0].pageX,b.changedTouches[0].pageY),this.Ig.dla(c.x,c.y),b.preventDefault());this.ks&&!this.hia()||r.C.EZ.call(this,b)};r.prototype.ol=function(b){if(!this.Cb)return!1;this.Cb.mk(b);var c=b.keyCode;if(c==a.KeyboardEvent.kh||c==a.KeyboardEvent.Jf||c==a.KeyboardEvent.Tf||c==a.KeyboardEvent.uf||c==a.KeyboardEvent.Qh)c=this.Ig.u().nC(),this.TN(b,c.x,c.y,this.Ig.DT(),this.Ig);
return!1};r.prototype.BJ=function(a){r.C.BJ.call(this,a);this.qe()};r.prototype.QF=function(a,b){var c=this.u().eh(a,b);return this.Ig.Md(c)};r.prototype.nD=function(){};a.v.D(n,a.Cb);n.prototype.Init=function(a,b){n.C.Init.call(this,a);this.Ig=b};n.prototype.mk=function(b){var c=b.keyCode,d=a.B.da(this.Ig.u());if(c==a.KeyboardEvent.kh||c==(d?a.KeyboardEvent.Jf:a.KeyboardEvent.uf))this.Ig.m6a(),a.I.sc(b);else if(c==a.KeyboardEvent.Tf||c==(d?a.KeyboardEvent.uf:a.KeyboardEvent.Jf))this.Ig.g6a(),a.I.sc(b)};
var A={};a.v.D(A,a.v);A.ovb=["#ed6647","#fad55c","#68c182"];A.nvb=["#D62800","#FFCF21","#84AE31"];A.u2a={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:80,y:86,width:40,height:34},indicatorLength:.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};A.v2a={startAngle:202.5,angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};A.x2a={startAngle:202.5,
angleExtent:225,anchorX:100,anchorY:103,metricLabelBounds:{x:83,y:86,width:34,height:34},indicatorLength:.85,tickLabelHeight:20,tickLabelWidth:30,radius:60,majorTickCount:6};A.D2a={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:82,y:133,width:36,height:34},indicatorLength:.85,tickLabelHeight:20,tickLabelWidth:30,radius:61,majorTickCount:6};A.E2a={startAngle:195.5,angleExtent:210.8,anchorX:100,anchorY:100,metricLabelBounds:{x:84,y:135,width:32,height:35},indicatorLength:.98,
tickLabelHeight:20,tickLabelWidth:30,radius:63,majorTickCount:6};A.G2a={startAngle:207.6,angleExtent:235,anchorX:100,anchorY:95.8,metricLabelBounds:{x:83,y:125,width:34,height:40},indicatorLength:1.05,tickLabelHeight:20,tickLabelWidth:30,radius:64,majorTickCount:6};A.B4a={startAngle:220.5,angleExtent:261.1,anchorX:100,anchorY:100,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:.82,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};A.C4a={startAngle:201,angleExtent:222,
anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:70,width:41,height:39},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};A.E4a={startAngle:211,angleExtent:242,anchorX:100,anchorY:91.445,metricLabelBounds:{x:78,y:75,width:44,height:38},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};A.d3a={startAngle:220.5,angleExtent:261.5,metricLabelBounds:{x:80,y:82,width:40,height:40},indicatorLength:.85,tickLabelHeight:20,tickLabelWidth:30,
radius:60,majorTickCount:6};A.e3a={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:89,metricLabelBounds:{x:80,y:73,width:40,height:36},indicatorLength:1.23,tickLabelHeight:20,tickLabelWidth:30,radius:56,majorTickCount:6};A.g3a={startAngle:201,angleExtent:222,anchorX:100.2,anchorY:99.5,metricLabelBounds:{x:80,y:83,width:41,height:36},indicatorLength:1.1,tickLabelHeight:20,tickLabelWidth:30,radius:58,majorTickCount:6};A.F2a={anchorX:42,anchorY:510};A.w2a={anchorX:187,anchorY:388};A.D4a={anchorX:227,
anchorY:425};A.f3a={anchorX:227,anchorY:425};A.ic=function(b){var c=b.F(),d=v.wR(b),e=v.lX(b,d);return!e||b instanceof a.Wo&&!(b instanceof a.Wo&&"onIndicator"==c.thresholdDisplay)?c.color:A.k4(b,e,d)};A.Xn=function(b){var c=b.F(),d=v.wR(b);return(d=v.lX(b,d))&&d.borderColor&&(!(b instanceof a.Wo)||b instanceof a.Wo&&"onIndicator"==c.thresholdDisplay)?d.borderColor:c.borderColor};A.yTa=function(b){var c=b.F(),d=v.wR(b),e=v.lX(b,d);return!e||b instanceof a.Wo&&!(b instanceof a.Wo&&"onIndicator"!=c.thresholdDisplay)?
c.plotArea.color:A.k4(b,e,d)};A.xTa=function(b){var c=b.F(),d=c.plotArea.borderColor;return b instanceof a.Wo&&"circular"!=c.orientation&&null==d?"skyros"==c.skin?"#C6C6C6":"#D6DFE6":d};A.k4=function(a,b,c){if(b.color)return b.color;a=a.F();return a._thresholdColors[c%a._thresholdColors.length]};A.Ikb=function(a){return"rectangleAlta"===a?A.x2a:"domeAlta"===a?A.v2a:"circleAntique"===a?A.D2a:"rectangleAntique"===a?A.G2a:"domeAntique"===a?A.E2a:"circleLight"===a?A.B4a:"rectangleLight"===a?A.E4a:"domeLight"===
a?A.C4a:"circleDark"===a?A.d3a:"rectangleDark"===a?A.g3a:"domeDark"===a?A.e3a:A.u2a};A.Jkb=function(a){return"needleAntique"===a?A.F2a:"needleLight"===a?A.D4a:"needleDark"===a?A.f3a:A.w2a};A.rX=function(a){return!!a.title.text};var u={};a.v.D(u,a.v);u.vp=function(b,c,d){var e=b.F(),h=e.emptyText;h||(h=a.H.Bf(e,"labelNoData",a.H.Ha,"NO_DATA",null));v.mUa(b)||(h=a.H.Bf(e,"labelInvalidData",a.H.Ha,"INVALID_DATA",null));e=e._statusMessageStyle;e.M("font-size")||e.fa("font-size","13px");if(b instanceof
a.Wo){var f=e.M("color");e.fa("color",f?f:"#333333")}a.Ca.vp(c,h,new a.Z(d.x,d.y,d.a,d.b),b.ab(),e)};u.Ko=function(a,b){var c=b.F();return c.metricLabel.text?c.metricLabel.text:u.SIa(a,b,c.metricLabel.converter,c.metricLabel.scaling,c.metricLabel.autoPrecision?c.metricLabel.autoPrecision:"on","percent"==c.metricLabel.textType)};u.uta=function(a,b){var c=b.F(),d=null,e="percent"==c.tickLabel.textType;"on"==c.tickLabel.rendered&&c.tickLabel.converter&&(d=c.tickLabel.converter);var h=null;"on"==c.tickLabel.rendered&&
c.tickLabel.scaling&&(h=c.tickLabel.scaling);return u.SIa(a,b,d,h,c.tickLabel.autoPrecision?c.tickLabel.autoPrecision:"on",e)};u.SIa=function(b,c,d,e,h,f){var k=c.F(),z=k.min,n=k.max,l=n-z,m=null;isNaN(l)||(m=l/(1E3>l?100:1E3));f&&(b=u.z3(k,k.min,b,!0));c=new a.Sj(c.u(),z,n,m,e,h);b=d&&d.getAsString?c.format(b,d):d&&d.format?c.format(b,d):f?Math.round(100*b):c.format(b);return f?String(b)+"%":b};u.z3=function(a,b,c,d){a=(c-b)/(a.max-a.min);return a=d?a:Math.min(Math.max(0,a),1)};u.Bea=function(b){var c=
b.F(),d=v.wR(b),d=v.lX(b,d);b=u.Ko(c.value,b);return d&&null!=d.shortDesc?d.shortDesc:null!=c.shortDesc?c.shortDesc:c.title.text?a.H.va(a.H.Ha,"COLON_SEP_LIST",[c.title.text,b]):b};u.vfa=function(b,c,d,e,h,f,k){var z=b.F(),n=!1;if("on"==z.metricLabel.rendered||k&&"off"!=z.metricLabel.rendered){k=u.Ko(z.value,b);var n=u.Ko(z.min,b),l=u.Ko(z.max,b);b=new a.ca(b.u(),k,d.x+d.a/2,d.y+d.b/2);b.Bb(z.metricLabel.style);z=(z=z.metricLabel.style.M("font-size"))?parseInt(z):null;z||(z=u.Yca([k,n,l],b,d),b.xg(k),
b.fh(z));"top"==f?(b.jb(d.y),b.np()):"middle"==f?a.Ca.BW(b,d.y+d.b/2):"bottom"==f&&(b.jb(d.y+d.b),b.Oq());"center"==h?b.Yf():"left"==h?(b.Fa(d.x),b.Vh()):"right"==h&&(b.Fa(d.x+d.a),b.Wh());null!=e&&b.fb(e);n=a.Ca.kd(b,d.a,d.b,c)}return n};u.Zwa=function(b,c,d,e,h){var f=b.F(),k=!1;if(A.rX(f)){var k=f.title.text,z=f.title.style,f=new a.Zb(b.u(),k),n=z.clone();f.Bb(z);var l=z.M("font-size"),l=l?parseInt(l):null;l||(k=new a.ca(b.u(),k,0,0),k.Bb(z),l=k.lC(d),n.fh("font-size",l.toString()));null!=e&&n.fa("color",
e);f.Bb(n);k=a.Ca.kd(f,d.a,d.b,b);b=a.Ca.qR(f);"top"==h?f.jb(d.y):"bottom"==h?f.jb(d.y+d.b-b):f.jb(d.y+d.b/2-b/2);f.Fa(d.x+d.a/2);f.Yf();c.A(f)}return k};u.Yca=function(a,b,c){for(var d=0,e=null,h=0,f=0;f<a.length;f++)b.xg(a[f]),h=b.Pc().a,h>d&&(e=a[f],d=h);b.xg(e);return b.lC(c)};u.Tca=function(a,b){var c=Number(a.step);if(c&&0<c){var d=(b-a.min)/c;return.5<d?Math.max(Math.min(a.max,Math.round(d)*c+a.min),a.min):a.min}return b};a.PA=function(){};a.v.D(a.PA,x);a.PA.newInstance=function(b,c,d,e){var h=
new a.PA;h.Init(b,c,d,e);return h};a.PA.prototype.Init=function(b,c,d,e){a.PA.C.Init.call(this,b,c,d,e);this.Xg=new m};a.PA.prototype.vf=function(b){a.PA.C.vf.call(this,this.Xg.en(b));"auto"==this.W.animationOnDisplay&&(this.W.animationOnDisplay="zoom");"auto"==this.W.animationOnDataChange&&(this.W.animationOnDataChange="alphaFade");this.W.readOnly=!0};a.PA.prototype.Fn=function(a,b,c){D.ta(this,a,b,c)};a.v.D(m,p);m.lh={type:"circle"};var D={};a.v.D(D,a.v);D.E5a="M-42,36.6Q-50,36.6,-46.54,28.6L-4,-43.07Q0,-50,4,-43.07L46.54,28.6Q50,36.6,42,36.6Z";
D.y5a=[-50,36.6,0,-50,50,36.6];D.F5a=[-50,36.6,0,-50,50,36.6];D.D5a=[-13.05,-12.94,-50,-11.13,-21.06,11.9,-30.74,47.6,.1,27.18,31.06,47.44,21.17,11.79,50,-11.39,13.05,-13.01,-.06,-47.59];D.Qka=[-50,-11.22,-16.69,-17.94,0,-47.55,16.69,-17.94,50,-11.22,26.69,13.8,30.9,47.56,0,33.42,-30.9,47.56,-26.69,13.8];D.B5a="M0,45L21,45Q24.414,44.414,25,41L25,10L42,10Q48.5,9.1,45,4L2,-38Q0,-39,-2,-38L-45,4Q-48.5,9.1,-42,10L-25,10L-25,41Q-24.414,44.414,-21,45Z";D.w5a=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];
D.C5a=[25,48,25,8,47.5,8,0,-39,-47.5,8,-25,8,-25,48];D.x5a="M -0.06059525142297417 -50.86842065108466 C -11.4496388584463 -50.86842065108466 -20.708163169810554 -39.024253028220556 -20.708163169810554 -24.413724255650386 C -20.708163169810554 -9.803195483080515 -11.4496388584463 2.040972139783591 -0.06059525142297417 2.040972139783591 C 11.328499974520241 2.040972139783591 20.586972666964613 -9.803195483080515 20.586972666964613 -24.413724255650386 C 20.586972666964613 -39.024253028220556 11.328499974520241 -50.86842065108466 -0.06059525142297417 -50.86842065108466 z M -23.93434565705865 -2.959610715450779 C -30.908061721494278 3.3998402034127153 -42.00096758564793 18.817121073473572 -38.77478509839983 33.65756051481475 C -20.651382358034887 47.30044101688934 14.372054723529814 49.13162219665128 39.298831093003386 32.85101489300273 C 40.26410489318826 16.477493533721187 32.34060070450674 4.7883891459240715 23.167918656763206 -2.959610715450779 C 11.553661702670112 21.074158341552575 -11.029615708066558 16.237465556670102 -23.93434565705865 -2.959610715450779 z ";
D.ta=function(b,c,d,e){if(v.rC(b)){var h=b.F(),f=h.__layout.outerGap,k=h&&(0<=h.size||1>h.size)?Math.sqrt(h.size):1;e=new a.Z(f+(d-2*f)*(1-k)/2,f+(e-2*f)*(1-k)/2,(d-2*f)*k,(e-2*f)*k);D.d2(b,c,e);D.lra(b,c,e);f=!1;d=a.O.Wl(A.ic(b));A.rX(h)&&(f="middle",k=D.FJa(b,e),"on"==h.metricLabel.rendered&&(k.y+=.6*k.b,k.b*=.4,f="top"),f=a.B.GM()||null==h.title.style.M("color")?u.Zwa(b,c,k,d,f):u.Zwa(b,c,k,null,f));"on"==h.metricLabel.rendered&&(e=D.FJa(b,e),k="middle",f&&(e.b*=.55,k="bottom"),a.B.GM()||null==
h.metricLabel.style.M("color")?u.vfa(b,c,e,d,"center",k):u.vfa(b,c,e,null,"center",k))}else u.vp(b,c,new a.Z(0,0,d,e))};D.d2=function(b,c,d){var e=b.u(),h=b.F(),f=h.type,k=A.ic(b),z=A.Xn(b),n=d.x+d.a/2,l=d.y+d.b/2,m=Math.min(d.a,d.b)/2,B=p.rA(b);D.Bc||(D.Bc=new a.Cache(50));var v=Math.min(d.a/100,d.b/100);"square"==f?n=new a.Rect(e,n-m,l-m,2*m,2*m):"rectangle"==f?n=new a.Rect(e,d.x,d.y,d.a,d.b):"diamond"==f?n=new a.mi(e,[n-m,l,n,l-m,n+m,l,n,l+m]):"circle"==f?n=new a.Nm(e,n,l,m):("star"==f?n=B?D.D5a:
D.Qka:"triangle"==f?n=B?D.E5a:D.y5a:"arrow"==f?n=B?D.B5a:D.w5a:"human"==f?n=D.x5a:(n=D.Bc.get(f),n||(n=new a.vb(e,f),n=a.Mh.v3(e,n),l=100/Math.max(n.a,n.b),n=a.P.Kxa(f,-l*(n.x+n.a/2),-l*(n.y+n.b/2),l,l),D.Bc.put(f,n))),(B||"triangle"!=f&&"arrow"!=f)&&"star"!=f?(n=a.P.Kxa(n,d.x+d.a/2,d.y+d.b/2,v,v),n=new a.vb(e,n)):(n=a.no.scale(n,v,v),n=a.no.translate(n,d.x+d.a/2,d.y+d.b/2),n=new a.mi(e,n)));B||"none"==h.visualEffects?n.fb(k):(e=[a.O.Em(k,-.09,.04),a.O.Em(k,-.04,-.05)],k=h&&0==h.rotation%90?h.rotation:
0,n.ra(new a.bd("arrow"==f||"star"==f||"triangle"==f?k-90:270,e,[1,1],[0,1])));z&&n.Vb(z);n.Ue(h.className);n.fa(h.style);(k=B?h.rotation+90:h.rotation)&&("arrow"==f||"triangle"==f||n instanceof a.vb&&"human"!=f)&&(n=D.ura(b,c,n,d));c.A(n)};D.ura=function(b,c,d,e){var h=b.F();b=new a.la(b.u());c.A(b);b.A(d);c=h&&0==h.rotation%90?h.rotation:0;h=new a.Tb;h.rotate(Math.PI*c/180);d.rb(h);c=b.aa();d=e.x+e.a/2-(c.x+c.a/2);e=e.y+e.b/2-(c.y+c.b/2);c=new a.Tb;c.translate(d,e);b.rb(c);return b};D.lra=function(a,
b,c){var d=a.F(),e=d.type;"none"!=d.visualEffects&&p.rA(a)&&("circle"==e?D.ffb(a,b,c):"diamond"==e?D.gfb(a,b,c):"triangle"==e?D.ifb(a,b,c):"arrow"==e?D.efb(a,b,c):D.hfb(a,b,c))};D.hfb=function(b,c,d){var e=.04*d.a,h=.04*d.b;d=new a.Z(d.x+e,d.y+h,d.a-2*e,d.b-2*h);b=new a.Rect(b.u(),d.x,d.y,d.a,d.b);b.nb(!1);c.A(b);c=new a.bd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[.75,.5,.15,0,.2,.4,.2],[0,.05,.4,.6,.8,.9,1]);b.ra(c)};D.gfb=function(b,c,d){var e=.05*d.a,h=.05*d.b,
h=new a.Z(d.x+e,d.y+h,d.a-2*e,d.b-2*h);d=h.x+h.a/2;e=h.y+h.b/2;h=Math.min(h.a,h.b)/2;b=new a.mi(b.u(),[d-h,e,d,e-h,d+h,e,d,e+h]);b.nb(!1);c.A(b);c=new a.bd(270,"#FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF #FFFFFF".split(" "),[.75,.5,.15,0,.2,.4,.2],[0,.05,.4,.6,.8,.9,1]);b.ra(c)};D.ifb=function(b,c,d){var e=.05*d.a,h=.05*d.b,f=p.rA(b),e=new a.Z(d.x+e,d.y+h,d.a-2*e,d.b-2*h),h=D.F5a,k=Math.min(e.a/100,e.b/100),h=a.no.scale(h,k,k),h=a.no.translate(h,d.x+d.a/2,d.y+d.b/2);d=new a.mi(b.u(),h);h=(h=
b.F())&&0==h.rotation%90?h.rotation:0;f=new a.bd(f?h-90:360-h,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF"],[.3,.55,0,.25,.1],[0,.05,.4,.9,1]);d.ra(f);d=D.ura(b,c,d,e);d.nb(!1);c.A(d)};D.efb=function(b,c,d){var e=.05*d.a,h=.05*d.b,f=p.rA(b),e=new a.Z(d.x+e,d.y+h,d.a-2*e,d.b-2*h),h=D.C5a,k=Math.min(e.a/100,e.b/100),h=a.no.scale(h,k,k),h=a.no.translate(h,d.x+d.a/2,d.y+d.b/2);d=new a.mi(b.u(),h);h=(h=b.F())&&0==h.rotation%90?h.rotation:0;f=new a.bd(f?h-90:360-h,["#FFFFFF","#FFFFFF","#FFFFFF","#FFFFFF",
"#FFFFFF"],[.3,.55,0,.25,.1],[0,.05,.4,.9,1]);d.ra(f);d=D.ura(b,c,d,e);d.nb(!1);c.A(d)};D.ffb=function(b,c,d){var e=.05*d.a,h=.05*d.b;d=new a.Z(d.x+e,d.y+h,d.a-2*e,d.b-2*h);var e=d.x+d.a/2,h=d.y+d.b/2,f=Math.min(d.a,d.b)/2,k=new a.Nm(b.u(),e,h,f);k.nb(!1);c.A(k);var z=new a.Vo(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,.25,.5],[.15,.7,.95],e,h-.6*f,1.5*f,[d.x,d.y,d.a,d.b]);k.ra(z);k=.6*f;f*=.4;h-=.3*f;b=new a.nv(b.u(),e,h-f,k,f);b.nb(!1);c.A(b);c=new a.Vo(["#FFFFFF","#FFFFFF","#FFFFFF"],[0,.2,.5],[.6,.8,
1],e,h,k,[d.x,d.y,d.a,d.b]);b.ra(c)};D.FJa=function(b,c){var d=b.F(),e=d.type,d=0==d.rotation%90?d.rotation:0,h=Math.min(c.a,c.b),f=c.x+c.a/2-h/2,k=c.y+c.b/2-h/2,z=h,n=h;"triangle"==e?0==d?(f+=.2*h,k+=.25*h,z-=.4*h,n-=.3*h):90==d?(f+=.05*h,k+=.2*h,z-=.3*h,n-=.4*h):180==d?(f+=.2*h,k+=.05*h,z-=.4*h,n-=.3*h):270==d&&(f+=.25*h,k+=.2*h,z-=.3*h,n-=.4*h):"arrow"==e?0==d?(f+=.2*h,k+=.2*h,z-=.4*h,n-=.4*h):90==d?(f+=.05*h,k+=.2*h,z-=.28*h,n-=.4*h):180==d?(f+=.2*h,k+=.2*h,z-=.4*h,n-=.4*h):270==d&&(f+=.23*h,
k+=.2*h,z-=.28*h,n-=.4*h):"star"==e?(f+=.25*h,k+=.25*h,z-=.5*h,n-=.4*h):"diamond"==e?(f+=.15*h,k+=.15*h,z-=.3*h,n-=.3*h):"rectangle"==e?(f+=.1*h,k+=.1*h,z-=.2*h,n-=.2*h):(f+=.15*h,k+=.15*h,z-=.3*h,n-=.3*h);return new a.Z(f,k,z,n)};a.Wo=function(){};a.v.D(a.Wo,x);a.Wo.newInstance=function(b,c,d){var e=new a.Wo;e.Init(b,c,d);return e};a.Wo.prototype.Init=function(b,c,d){a.Wo.C.Init.call(this,b,c,d);this.Xg=new l;this.Zka=null};a.Wo.prototype.vf=function(b){a.Wo.C.vf.call(this,this.Xg.en(b))};a.Wo.prototype.Fn=
function(a,b,c){B.ta(this,a,b,c)};a.Wo.prototype.Mga=function(b,c,d){c=[];for(var e=0;e<b.length;e++){var h=b[e],f=h.qf();"horizontal"==this.W.orientation?h.df([f[0],f[0],f[2],f[3]]):"vertical"==this.W.orientation?h.df([f[0],f[1],f[3],f[3]]):"circular"==this.W.orientation&&h.df([f[0],f[1],0,f[3],f[4]]);var k=new a.gd(this.u(),h,d);k.ja.N(a.G.wf,h,h.qf,h.df,f);k.ja.wp(function(b){return a.Je.R2(b,.7)});c.push(k)}return new a.Gg(this.u(),c)};a.Wo.prototype.uJ=function(b,c){var d=this.W,e=a.B.da(this.u());
if("horizontal"==d.orientation)return this.Zka.Dda(b);if("vertical"==d.orientation)return this.Zka.Dda(c);if("circular"==d.orientation){var h=d.angleExtent,f=Math.atan2(c-this.kw,b-this.jw),e=e?180-(a.Math.LX(f)-d.startAngle):a.Math.LX(f)-(360-d.startAngle),e=(e+720)%360,f=d.min,d=d.max,f=e/h*(d-f)+f;e>h&&(f=.5<(e-h)/(360-h)?0:d);return f}};a.v.D(l,p);l.mf={color:"#393737",metricLabel:{style:new a.j(a.bb.Pm)},plotArea:{color:"#E4E8EA"}};l.lh={angleExtent:360,borderRadius:"auto",color:"#313842",indicatorSize:1,
innerRadius:.7,metricLabel:{style:new a.j(a.bb.It),position:"auto"},orientation:"horizontal",plotArea:{color:"#AAAAAA",rendered:"auto",borderRadius:"auto"},startAngle:90,thresholdDisplay:"onIndicator"};var B={};a.v.D(B,a.v);B.ta=function(b,c,d,e){if(v.rC(b)){var h=b.F(),f=h.__layout.outerGap;d=new a.Z(f,f,d-2*f,e-2*f);"horizontal"==h.orientation||"vertical"==h.orientation?(B.zoa(h)&&B.Xeb(b,c,d),B.d2(b,c,d)):"circular"==h.orientation&&B.Geb(b,c,d)}else u.vp(b,c,new a.Z(0,0,d,e))};B.Geb=function(b,
c,d){var e=b.F(),h=d.clone(),f=a.B.da(b.u()),k=0,z=null,n=e.value,l=e.innerRadius,m=e.thresholds,v,p=null,C=a.Math.Hn-a.Math.Cu(e.startAngle),r=a.Math.Cu(e.angleExtent),w=(C+r)%(2*Math.PI);b.jw=d.a/2;b.kw=d.b/2;r!=2*Math.PI&&(z=B.O6a(b,l,C,r,w,d,f),p=b.hpb);v=v?v:Math.min(d.a,d.b);var f=.5*v*l,w=.5*v,D=e.indicatorSize;if(D&&1<D)var x=(1-1/D)/2*(w-f),f=f+x,w=w-x;x="middle";z||(p=Math.min(d.a,d.b)*l,z=new a.Z(d.x+d.a/2-3/7*p,d.y+d.b/2-2.5/7*p,6/7*p,5/7*p));var oa=!1;if(A.rX(e)){var oa="middle",Q=new a.Z(z.x,
z.y,z.a,z.b);"off"!=e.metricLabel.rendered&&(Q.y+=.6*Q.b,Q.b*=.4,oa="top");(oa=u.Zwa(b,c,Q,null,oa))&&"off"!=e.metricLabel.rendered&&(z.b*=.55,x="bottom")}u.vfa(b,c,z,null,"center",x,!0);x=C;k*=r;z=A.xTa(b);if(m&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(oa=0;oa<m.length;oa++){var Q=A.k4(b,m[oa],oa),k=m[oa].max<e.max?m[oa].max:e.max,V=0==oa?e.min:m[oa-1].max,x=C+r*u.z3(e,e.min,V),k=u.z3(e,V,k),k=k*r,V=m[oa].borderColor;B.ina(b,c,d,x,k,f,w,Q,!0,V?V:z)}else"off"!=e.plotArea.rendered&&
"all"!=e.thresholdDisplay&&(m=A.yTa(b),B.ina(b,c,d,C,r,f,w,m,!0,z));f=v*l*.5;w=.5*v;D&&1>D&&(l=(1-D)/2*(w-f),f+=l,w-=l);k=u.z3(e,e.min,n);B.ina(b,c,d,C,k*r,f,w,A.ic(b),!1);if(l=e.referenceLines)for(v=0;v<l.length;v++)m=l[v].color?l[v].color:"black",f=l[v].lineWidth?l[v].lineWidth:2,w=l[v].lineStyle,n=l[v].value,B.J9a(b,c,d,C+u.z3(e,e.min,n)*r,m,f,w);e.center.renderer&&B.Eeb(b,e,d,h,p)};B.d2=function(b,c,d){var e=b.F(),h=a.B.da(b.u()),f="vertical"==e.orientation,z={layout:{}};z.layout.gapRatio=0;z.timeAxisType=
"disabled";z.position=f?"left":"bottom";z.min=e.min;z.max=e.max;z.dataMin=e.min;z.dataMax=e.max;z.tickLabel={rendered:"off"};z=a.sf.newInstance(b.u(),z,d);b.Zka=z;var n=0;0>=e.max?n=e.max:0<=e.min&&(n=e.min);var l=z.uj(n);"off"==e.plotArea.rendered||"auto"==e.plotArea.rendered&&"onIndicator"==e.thresholdDisplay||(l=z.rh(e.min));var m=z.rh(e.value),m=f?Math.max(d.y,Math.min(d.y+d.b,m)):Math.max(d.x,Math.min(d.x+d.a,m)),v=e.indicatorSize,C,r,u,w,D,x,L=0,L=1>v?1:v;u=1<v?1:v;f?(n=d.x+(1-u)/2*d.a+.5,C=
d.x+d.a*(1+u)/2-.5,u=l-.5,r=m+.5,w=d.x+(1-1/L)/2*d.a,D=d.x+d.a*(1+1/L)/2,x=d.y,L=d.y+d.b):(n=h?l-.5:l+.5,C=h?m+.5:m-.5,r=d.y+(1-u)/2*d.b+.5,u=d.y+d.b*(1+u)/2-.5,w=d.x,D=d.x+d.a,x=d.y+(1-1/L)/2*d.b,L=d.y+d.b*(1+1/L)/2);v=!0;m==l&&(f?r=u:n=C,v=!1);var oa=A.Xn(b),Q=A.xTa(b),V=e.thresholds,m=f?0:270;if(V&&"off"!=e.plotArea.rendered&&"all"==e.thresholdDisplay)for(l=V.length-1;0<=l;l--){var ua=l,g=B.zK(b,b.u(),w,D,x,L),F=new a.Cd("pacp"+b.getId());if(l==V.length-1)!f&&h?F.Pe(z.rh(e.max)+1,0,d.a+2,d.b+2,
0,0):F.Pe(0,0,d.a+2,d.b+2,0,0);else if(f)F.Pe(0,z.rh(e.max),d.a+2,1*(e.max-V[V.length-2-ua].max)/Math.abs(e.min-e.max)*d.b,0,0);else if(h){var da=null==V[V.length-2-ua].max?100:V[V.length-2-ua].max;F.Pe(z.rh(e.max),0,1*(e.max-da)/Math.abs(e.min-e.max)*d.a,d.b+2,0,0)}else F.Pe(0,0,1*(V[ua].max-e.min)/Math.abs(e.min-e.max)*d.a,d.b+2,0,0);g.te(F);if(h||f)ua=V.length-1-l;g.fb(A.k4(b,V[ua],ua));F=V[ua].borderColor;g.Vb(F?F:Q);B.lOa(b,c,g,A.k4(b,V[ua],ua),m)}else"off"==e.plotArea.rendered||"auto"==e.plotArea.rendered&&
"onIndicator"==e.thresholdDisplay||"all"==e.thresholdDisplay||(g=f?B.zK(b,b.u(),w,D,z.rh(e.max),z.rh(e.min)):B.zK(b,b.u(),z.rh(e.min),z.rh(e.max),x,L),l=A.yTa(b),g.fb(l),g.Vb(Q),B.lOa(b,c,g,l,m));l=new k(b,b.u(),n,C,r,u);b.rG.push(l);h=A.ic(b);p.rA(b)||"none"==e.visualEffects?l.fb(h):(Q=[a.O.Em(h,-.09,.04),a.O.Em(h,-.04,-.05)],Q=new a.bd(m,Q,[1,1],[0,1]),l.ra(Q));oa&&l.Vb(oa);l.Ue(e.className);l.fa(e.style);v&&c.A(l);l=B.zK(b,b.u(),n,C,r,u);B.lra(b,c,l,v,m);if(m=e.referenceLines)for(l=0;l<m.length;l++)oa=
m[l].color?m[l].color:"white",V=m[l].value,v=e.indicatorSize,f?(g=((1-v)/2+v)*d.a,Q=d.x+(1-v)/4*d.a,v=z.rh(V),v=new a.Gc(b.u(),Q,v,Q+g,v)):(g=((1-v)/2+v)*d.b,Q=z.rh(V),v=d.y+(1-v)/4*d.b,v=new a.Gc(b.u(),Q,v,Q,v+g)),oa=new a.ya(oa,1,m[l].lineWidth?m[l].lineWidth:2),m[l].lineStyle&&oa.fa(a.Xc.Qx(m[l].lineStyle)),v.Ga(oa),c.A(v),a.B.ae()||"none"==e.visualEffects||(oa=new a.qv(a.O.EI(0,0,0,.8),.75,3,3,50,1,2,!1,!1,!1),v.YL(oa));f=e.metricLabel.position;"on"!=e.metricLabel.rendered||B.zoa(e)||A.rX(e)?
A.rX(e)&&B.mQ(b,c,d,f):B.bra(b,c,d,h,f,{ry:n,Yr:C,dm:r,qq:u},{ry:w,Yr:D,dm:x,qq:L})};B.zK=function(b,c,d,e,h,f){var k=Math.min(d,e),z=Math.min(h,f);d=Math.abs(d-e);h=Math.abs(f-h);f=b.F();e="vertical"==f.orientation?d:h;b=p.rA(b)?"25%":"15%";k=a.P.OR(k,z,d,h,"auto"!=f.plotArea.borderRadius?f.plotArea.borderRadius:f.borderRadius,e,b);return new a.vb(c,k)};B.lra=function(b,c,d,e,h){"none"!=b.F().visualEffects&&p.rA(b)&&(h=new a.bd(h,["#FFFFFF","#FFFFFF","#FFFFFF"],[.5,.3125,0],[0,.3,1]),d.ra(h),b.rG.push(d),
d.nb(!1),e&&c.A(d))};B.lOa=function(b,c,d,e,h){var f=b.F();d.nb(!1);c.A(d);"none"!=f.visualEffects&&(p.rA(b)?(b=[a.O.Ir(e,.1),e,a.O.qp(e,.7)],h=new a.bd(h,b,[1,1,1],[0,.04,.73])):(b=[a.O.Em(e,-.04,-.05),a.O.Em(e,-.09,.04)],h=new a.bd(h,b,[1,1],[0,1])),d.ra(h),d.Ue(f.plotArea.className),d.fa(f.plotArea.style))};B.Xeb=function(b,c,d){var e=b.F(),h=a.B.da(b.u()),f="vertical"==e.orientation,k=new a.ca(b.u(),""),z=u.Ko(e.value,b),n=e.__layout.labelGap,l=e.metricLabel.style,m=l.M("color"),m=m?m:"#333333",
B=null;k.Bb(l);k.fb(m);if(f&&"on"==e.metricLabel.rendered){var v=0<e.max?e.max:e.min,v=u.Ko(v,b),B=new a.ca(b.u(),v);B.Bb(l);e=new a.Z(d.x,d.y+.8*d.b,d.a,.2*d.b);f=(f=l.M("font-size"))?parseInt(f):B.lC(e);B=B.Pc();d.b-=B.b;v=B.a;k.fh(f);k.xg(z);k.Fa(d.x+d.a/2);k.jb(d.y+d.b);d.b-=n;k.Yf();a.Ca.kd(k,d.a,d.b,c)}else if(!f&&"on"==e.metricLabel.rendered){f=l.M("font-size");m=u.Ko(e.min,b);B=u.Ko(e.max,b);void 0===f&&18>d.b&&(f=u.Yca([z,m,B],k,d));f=f?parseInt(f):13;k.fh(f);var C;if(0<e.max||"off"!=e.plotArea.rendered||
"auto"!=e.plotArea.rendered||"onIndicator"!=e.thresholdDisplay)v=0<e.max?e.max:e.min,v=u.Ko(v,b),B=new a.ca(b.u(),v),B.Bb(l),B.fh(f),B=B.Pc(),B.a=Math.min(B.a,d.a),C=h?d.x+B.a:d.x+d.a,v=B.a,h&&(d.x+=B.a+n),d.a-=B.a+n;if(0>e.min&&"on"!=e.plotArea.rendered&&("auto"!=e.plotArea.rendered||"onIndicator"!=e.thresholdDisplay)){B=u.Ko(e.min,b);m=new a.ca(b.u(),B);m.Bb(l);m.fh(f);l=m.Pc();if(0>e.value||0>=e.max)C=h?d.x+d.a:d.x+l.a,v=l.a;h||(d.x+=l.a+n);d.a-=l.a+n}k.xg(z);k.Fa(C);a.Ca.BW(k,d.y+d.b/2);k.Wh();
a.Ca.kd(k,v,d.b,c)}};B.bra=function(b,c,d,e,h,f,k,z){var n=b.F(),l=a.B.da(b.u()),m="vertical"==n.orientation,v="on"==n.plotArea.rendered,C="center",p="middle",r=new a.Z(Math.min(f.ry,f.Yr),Math.min(f.dm,f.qq),Math.abs(f.Yr-f.ry),Math.abs(f.qq-f.dm)),n=n.metricLabel.style.M("color");"center"==h?(n=n?n:a.O.Wl(e),m?(r.b-=r.a,r.y+=r.a/2):(r.a-=r.b,r.x+=r.b/2)):"insideIndicatorEdge"==h?(n=n?n:a.O.Wl(e),m?(r.b-=r.a,r.y+=r.a/2,p=!v&&f.dm>f.qq?"bottom":"top"):(r.a-=r.b,r.x+=r.b/2,C=l?!v&&f.ry<f.Yr?"right":
"left":!v&&f.ry>f.Yr?"left":"right")):"outsideIndicatorEdge"==h&&(m?(r.b=Math.abs(k.dm-f.dm)-r.a,r.y=k.dm+r.a/2,p="bottom",!v&&f.dm>f.qq&&(r.b=Math.abs(k.dm-f.dm)-r.a,r.y=f.dm+r.a/2,p="top")):l?!v&&f.ry<f.Yr?(r.a=Math.abs(k.Yr-f.Yr)-r.b,r.x=f.Yr+r.b/2,C="left"):(r.a=Math.abs(k.ry-f.Yr)-r.b,r.x=k.ry+r.b/2,C="right"):!v&&f.ry>f.Yr?(r.a=Math.abs(k.ry-f.Yr)-r.b,r.x=k.ry+r.b/2,C="right"):(r.a=Math.abs(k.Yr-f.Yr)-r.b,r.x=f.Yr+r.b/2,C="left"));u.vfa(b,c,r,n,C,p)||z||("outsideIndicatorEdge"==h?B.bra(b,c,
d,e,"insideIndicatorEdge",f,k,!0):"insideIndicatorEdge"!=h&&"center"!=h||B.bra(b,c,d,e,"outsideIndicatorEdge",f,k,!0))};B.mQ=function(b,c,d){var e=a.B.da(b.u()),h=b.F(),f="vertical"==h.orientation,k=new a.Z(d.x,d.y,f?d.a:d.a-d.b,f?d.b-d.a:d.b),z=h.title.text;if(!B.zoa(h)&&"on"==h.metricLabel.rendered)var n=u.Ko(h.value,b),z=a.H.va(a.H.Ha,"COLON_SEP_LIST",[z,n]);var l=h.title.style,n=l.clone(),m=l.M("font-size");m||(m=new a.ca(b.u(),z,0,0),m.Bb(l),m.xg(z),m=f?m.lC(new a.Z(k.x,k.y,k.a,Number.MAX_VALUE)):
m.lC(new a.Z(k.x,k.y,Number.MAX_VALUE,k.b)));z=new a.Zb(b.u(),z);n.fh("font-size",m.toString());z.Bb(n);a.Ca.kd(z,k.a,k.b,b);"center"==h.title.position||"auto"==h.title.position&&f?(a.Ca.BW(z,d.y+d.b/2),z.Fa(d.x+d.a/2),z.Yf()):(a.Ca.BW(z,d.y+d.b/2),!f&&e)?(z.Fa(d.x+d.a-k.b/2),z.Wh()):f||e?f&&(z.jb(d.y+d.b-z.aa().b-k.a/2),z.Fa(d.x+d.a/2),z.Yf()):(z.Fa(d.x+k.b/2),z.Vh());c.A(z)};B.Um=function(a,b,c){return{x:Math.cos(c)*b+a.a/2+a.x,y:Math.sin(c)*b+a.b/2+a.y}};B.ina=function(b,c,d,e,f,k,z,n,l,m){var v=
b.u();a.B.da(b.u())&&(e=Math.PI-e-f,e=0<e?e:e+2*Math.PI);l?d=new a.vb(v,B.XQa(d,e,f,k,z)):(d=new h(v,d,e,f,k,z),b.rG.push(d));d.fb(n);(n=A.Xn(b))&&!l?d.Vb(n):l&&m&&d.Vb(m);b=b.F();d.Ue(l?b.plotArea.className:b.className);d.fa(l?b.plotArea.style:b.style);c.A(d)};B.J9a=function(b,c,d,e,h,f,k){var z=b.u(),n=Math.min(d.a,d.b),l=.275*n,n=.5*n;a.B.da(b.u())&&(e=Math.PI-e,e=0<e?e:e+2*Math.PI);b=B.Um(d,l,e);d=B.Um(d,n,e);z=new a.Gc(z,b.x,b.y,d.x,d.y);h=new a.ya(h,1,f);k&&h.fa(a.Xc.Qx(k));z.Ga(h);c.A(z)};
B.XQa=function(b,c,d,e,h){var f,k,z;d<a.Math.Hn?(f=B.Um(b,h,c),k=B.Um(b,h,c+d),z=B.Um(b,e,c+d),b=B.Um(b,e,c),h=a.P.moveTo(f.x,f.y)+a.P.arcTo(h,h,d,1,k.x,k.y)+a.P.lineTo(z.x,z.y)+a.P.arcTo(e,e,d,0,b.x,b.y)+a.P.closePath()):(f=B.Um(b,h,c),k=B.Um(b,h,c+d/2),z=B.Um(b,e,c),b=B.Um(b,e,c+d/2),h=a.P.moveTo(f.x,f.y)+a.P.arcTo(h,h,d/2,1,k.x,k.y)+a.P.arcTo(h,h,d/2,1,f.x,f.y),0<e&&(h+=a.P.moveTo(b.x,b.y)+a.P.arcTo(e,e,d/2,0,z.x,z.y)+a.P.arcTo(e,e,d/2,0,b.x,b.y)),h+=a.P.closePath());return h};B.IRa=function(b,
c){var d=1;if(c)b>=a.Math.DN&&b<Math.PI?d=2:b>=Math.PI&&b<1.5*Math.PI?d=3:b>=1.5*Math.PI&&b<a.Math.Hn&&(d=4);else if(b>a.Math.DN&&b<=Math.PI)d=2;else if(b>Math.PI&&b<=1.5*Math.PI)d=3;else if(b>1.5*Math.PI&&b<a.Math.Hn||0==b)d=4;return d};B.zoa=function(a){var b=a.metricLabel.position;return"auto"==b||"outsidePlotArea"==b||"withTitle"==b&&!A.rX(a)};B.O6a=function(b,c,d,e,h,f,k){var z=null,n=B.IRa(d,!0),l=B.IRa(h,!1),m=f.a,v=f.b,r=m/2,C=v/2,p;if(n==l&&e<=a.Math.DN)if(d=2*Math.min(f.a,f.b),f.a+=d/2,
f.b+=d/2,p=d*c,!k&&1==n||k&&2==n)f.x-=d/2,f.y-=d/2,r=m/2-d/4+1,C=v/2-d/4+1,z=new a.Z(f.x+f.a/2-1,f.y+f.b/2-1,3/7*p-2,2.5/7*p-2);else if(!k&&2==n||k&&1==n)f.y-=d/2,r=m/2+d/4-1,C=v/2-d/4+1,z=new a.Z(f.x+f.a/2-3/7*p+1,f.y+f.b/2-1,3/7*p-2,2.5/7*p-2);else if(!k&&3==n||k&&4==n)r=m/2+d/4-1,C=v/2+d/4-1,z=new a.Z(f.x+f.a/2-3/7*p+1,f.y+f.b/2-2.5/7*p+1,3/7*p-2,2.5/7*p-2);else{if(!k&&4==n||k&&3==n)f.x-=d/2,r=m/2-d/4+1,C=v/2+d/4-1,z=new a.Z(f.x+f.a/2-1,f.y+f.b/2-2.5/7*p+1,3/7*p-2,2.5/7*p-2)}else n%4+1==l&&e<=
Math.PI?1==n||3==n?(d=Math.min(f.a,2*f.b),p=d*c,f.a>f.b&&(z=new a.Z(f.x+f.a/2-3/7*p,f.y+f.b-(f.b-d/2)/2-2.75/7*p,6/7*p,2.5/7*p),1==n?(z.y=f.y+(f.b-d/2)/2+.5/7*p,f.y-=d/2-(f.b-d/2)/2,C=v/2-d/4+1):(f.y+=(f.b-d/2)/2,C=v/2+d/4-1),f.b=d)):(d=Math.min(2*f.a,f.b),p=d*c,f.a<f.b&&(z=new a.Z(f.x+f.a-(f.a-d/2)/2-3.25/7*p,f.y+f.b/2-2.5/7*p,3/7*p,5/7*p),!k&&4==n||k&&2==n?(z.x=f.x+(f.a-d/2)/2+.25/7*p,f.x-=d/2-(f.a-d/2)/2,r=m/2-d/4+1):(f.x+=(f.a-d/2)/2,r=m/2+d/4-1),f.a=d)):l%4+1==n&&e>Math.PI&&(1==n&&f.b>f.a?(d=
Math.min(f.a/(Math.cos(d)+1)*2,f.a/(Math.sin(h-1.5*Math.PI)+1)*2,f.b),p=d*c,c=3/7*p*(2*f.a/d-1),k?(z=new a.Z(f.x+f.a-d/2-c,f.y+f.b/2-2.5/7*p,3/7*p+c,5/7*p),f.x-=d-f.a,r=-d/2+m):(z=new a.Z(f.x+d/2-3/7*p,f.y+f.b/2-2.5/7*p,3/7*p*(1+(2*f.a/d-1)),5/7*p),r=d/2),f.a=d):2==n&&f.b<f.a?(d=Math.min(f.b/(Math.cos(d-a.Math.DN)+1)*2,f.b/(Math.sin(h)+1)*2,f.a),p=d*c,z=new a.Z(f.x+f.a/2-3/7*p,f.y+d/2-2.5/7*p,6/7*p,2.5/7*p*(1+(2*f.b/d-1))),f.b=d,C=d/2):3==n&&f.b>f.a?(d=Math.min(f.a/(Math.cos(d-Math.PI)+1)*2,f.a/(Math.sin(h-
a.Math.DN)+1)*2,f.b),p=d*c,c=3/7*p*(2*f.a/d-1),k?(z=new a.Z(f.x+d/2-3/7*p,f.y+f.b/2-2.5/7*p,3/7*p*(1+(2*f.a/d-1)),5/7*p),r=d/2):(z=new a.Z(f.x+f.a-d/2-c,f.y+f.b/2-2.5/7*p,3/7*p+c,5/7*p),f.x-=d-f.a,r=-d/2+m),f.a=d):4==n&&f.b<f.a&&(d=Math.min(f.b/(Math.cos(d-1.5*Math.PI)+1)*2,f.b/(Math.sin(a.Math.Hn-h)+1)*2,f.a),p=d*c,c=2.5/7*p*(2*f.b/d-1),z=new a.Z(f.x+f.a/2-3/7*p,f.y+f.b-d/2-c,6/7*p,2.5/7*p+c),f.y-=d-f.b,f.b=d,C=-d/2+v));b.jw=r;b.kw=C;b.hpb=p;return z};B.Eeb=function(b,c,d,e,h){var f=new a.Z(d.x+
.5*(d.a-h),d.y+.5*(d.b-h),h,h),f=f.CSa(e);d=new a.Z(d.x+.5*(d.a-h/Math.sqrt(2)),d.y+.5*(d.b-h/Math.sqrt(2)),h/Math.sqrt(2),h/Math.sqrt(2));d=d.CSa(e);if(e=c.center.renderer)if(d={outerBounds:{x:f.x,y:f.y,width:f.a,height:f.b},innerBounds:{x:d.x,y:d.y,width:d.a,height:d.b},metricLabel:u.Ko(c.value,b),component:c._widgetConstructor},c=b.u(),f=c.Xv,(h=b.dib)&&f.removeChild(h),d=e(d))e=c.gRa(),e.appendChild(d),b.dib=e,f.appendChild(e),(b=c.XMa)&&b(e)};a.v.D(k,a.vb);k.prototype.Init=function(a,b,c,d,e,
h){k.C.Init.call(this,b);this.Ig=a;this.WM(c,d,e,h)};k.prototype.WM=function(b,c,d,e){this.Mg=b;this.rg=c;this.XH=d;this.YH=e;var h=Math.min(b,c),f=Math.min(d,e);b=Math.abs(b-c);d=Math.abs(e-d);e=this.Ig.F();c="vertical"==e.orientation?b:d;var k=p.rA(this.Ig)?"25%":"15%",h=a.P.OR(h,f,b,d,e.borderRadius,c,k);this.nk(h)};k.prototype.qf=function(){return[this.Mg,this.rg,this.XH,this.YH]};k.prototype.df=function(a){a&&4==a.length&&this.WM(a[0],a[1],a[2],a[3])};a.v.D(h,a.vb);h.prototype.Init=function(a,
b,c,d,e,f){h.C.Init.call(this,a);this.FWa(b,c,d,e,f)};h.prototype.FWa=function(b,c,d,e,h){b&&b instanceof a.Z?this.we=b:b=this.we;this.qg=c;this.hg=d;this.gp=e;this.an=h;this.nk(B.XQa(b,c,d,e,h))};h.prototype.qf=function(){return[this.we,this.qg,this.hg,this.gp,this.an]};h.prototype.df=function(a){a&&5==a.length&&this.FWa(a[0],a[1],a[2],a[3],a[4])};a.$q=function(){};a.v.D(a.$q,x);a.$q.newInstance=function(b,c,d){var e=new a.$q;e.Init(b,c,d);return e};a.$q.prototype.Init=function(b,c,d){a.$q.C.Init.call(this,
b,c,d);this.Xg=new f;this.Xka=null};a.$q.prototype.vf=function(b){var c=b.background,d=b.indicator;"string"===typeof c&&(b.background=A.Ikb(c),b.background.images=b._backgroundImages);"string"===typeof d&&(b.indicator=A.Jkb(d),b.indicator.images=b._indicatorImages);a.$q.C.vf.call(this,this.Xg.en(b))};a.$q.prototype.Fn=function(a,b,c){C.ta(this,a,b,c)};a.$q.prototype.WVa=function(){C.stb(this,this.Ea,this.xb,this.Jb);var a=this.ab();a&&a.lb(this.WO,this.DT(),!0);this.hka(this.Ea)};a.$q.prototype.Mga=
function(b,c,d){c=[];for(var e=0;e<b.length;e++){var h=b[e],f=h.qf(),k=C.j6a(this);h.bm(k);k=new a.gd(this.u(),h,d);k.ja.N(a.G.wf,h,h.qf,h.df,f);k.ja.wp(function(b){return a.Je.R2(b,.7)});c.push(k)}return new a.Gg(this.u(),c)};a.$q.prototype.uJ=function(b,c){var d=a.Math.LX(Math.atan2(c-this.Xka.y,b-this.Xka.x));0>=d&&(d+=360);var e=a.B.da(this.u()),h=this.F().background,f=e?180+h.startAngle:360-h.startAngle,h=h.angleExtent,k=f+h;if(e)for(k=f,f-=h;0>f;)f+=360,k+=360;d+360>=f&&d+360<=k?d+=360:d>=f&&
d<=k||(d=d>k?f+360-d<d-k?f:k:f-d<d+360-k?f:k);d=(d-f)/h;e&&(d=1-d);e=this.W.min;return d*(this.W.max-e)+e};a.v.D(f,p);f.lh={background:{startAngle:180,angleExtent:180,indicatorLength:.7},metricLabel:{style:new a.j(a.bb.Pm)},tickLabel:{scaling:"auto",style:new a.j(a.bb.Pm)}};var C={};a.v.D(C,a.v);C.ta=function(b,c,d,e){v.rC(b)?(d=new a.Z(0,0,d,e),C.d2(b,c,d),C.KH(b,c,d)):u.vp(b,c,new a.Z(0,0,d,e))};C.stb=function(b,c,d,e){b.n6a.bm(C.loa(b,b.F().value));c.removeChild(b.p6a);C.KH(b,c,new a.Z(0,0,d,e))};
C.d2=function(b,c,d){var h=b.F(),f=C.L8a(b,d);c.A(f);h.background.majorTickCount&&h.background.radius&&C.sfb(b,c,d);var f=C.X8a(b,d),k=new a.la(b.u()),z=new e(b.u());c.A(k);k.A(z);z.A(f);var n=f.aa(),h=C.loa(b,h.value);c=C.cJa(b,d);var l=C.dab(b,n);d=C.eab(b,d,n);n=new a.Tb;n.translate(-l.x,-l.y);n.scale(d,d);f.rb(n);z.bm(h);n=new a.Tb;n.translate(c.x,c.y);k.rb(n);b.rG.push(z);b.n6a=z;b.Xka=c};C.L8a=function(b,c){var d=b.F().background,e=a.B.da(b.u()),h=a.B.Wa(),f=h?2*c.a:c.a,k=h?2*c.b:c.b,z=d.images;
if(z&&0<z.length){var n,l,m,h=[];for(n=0;n<z.length;n++){var B="rtl"==z[n].dir;e&&B?h.push(z[n]):e||B||h.push(z[n])}z=0<h.length?h:z;for(n=0;n<z.length;n++){var v=z[n],B=v.src,h=v.width,v=v.height,p=B&&-1<B.search(".svg");0==n&&(l=h,m=v);if(p||h>=f&&v>=k||n==z.length-1){var f=new a.Image(b.u(),B,0,0,h,v),r=new a.Tb,k=Math.min(c.a/h,c.b/v),z=(c.a-k*h)/2;n=(c.b-k*v)/2;r.scale(k,k);r.translate(z,n);f.rb(r);p&&a.B.yC()&&(B=a.js.Ur(b.u(),B,a.v.ti(f,f.gla)))&&f.gla(B);c.x+=z;c.y+=n;c.a=k*h;c.b=k*v;isNaN(d.anchorX)||
isNaN(d.anchorY)||(d._anchorX=e?c.x+c.a-c.a*d.anchorX/l:c.x+c.a*d.anchorX/l,d._anchorY=c.y+c.b*d.anchorY/m);d.metricLabelBounds&&(h={},h.width=c.a*d.metricLabelBounds.width/l,h.height=c.b*d.metricLabelBounds.height/m,h.y=c.y+c.b*d.metricLabelBounds.y/m,h.x=e?c.x+c.a-c.a*d.metricLabelBounds.x/l-h.width:c.x+c.a*d.metricLabelBounds.x/l,d._metricLabelBounds=h);d._radius=d.radius*Math.min(c.a/l,c.b/m);d._tickLabelHeight=d.tickLabelHeight*c.b/m;d._tickLabelWidth=d.tickLabelWidth*c.a/l;return f}}}return null};
C.X8a=function(b,c){var d=b.F().indicator,e=C.yJa(b,c),h=a.B.Wa()?2*e:e,f,k,z=d.images;if(z&&0<z.length)for(var n=0;n<z.length;n++){var l=z[n],e=l.src,m=l.width,l=l.height,B=e&&-1<e.search(".svg");0==n&&(f=m,k=l);if(B||l>=h||n==z.length-1)return h=new a.Image(b.u(),e,0,0,m,l),B&&a.B.yC()&&a.js.Ur(b.u(),e,a.v.ti(h,h.gla))&&(h.Xa(m),h.qb(l)),isNaN(d.anchorX)||isNaN(d.anchorY)||(d._anchorX=d.anchorX*m/f,d._anchorY=d.anchorY*l/k),h}return null};C.j6a=function(b){var c=b.F().background;b=a.B.da(b.u())?
180-c.startAngle:c.startAngle;return Math.PI*(90-b)/180};C.loa=function(b,c){var d=b.F(),e=d.background,h=d.min,d=d.max;c=Math.max(Math.min(c,d),h);h=(c-h)/(d-h);d=a.B.da(b.u());return Math.PI*(90-((d?180-e.startAngle:e.startAngle)-h*(d?-e.angleExtent:e.angleExtent)))/180};C.cJa=function(b,c){var d=b.F().background,e=d._anchorX,d=d._anchorY;return isNaN(e)||isNaN(d)?new a.R(c.x+c.a/2,c.y+c.b/2):new a.R(e,d)};C.yJa=function(a,b){var c=Math.min(b.a,b.b)/2;return a.F().background.indicatorLength*c};
C.dab=function(b,c){var d=b.F().indicator,e=d._anchorX,d=d._anchorY;return isNaN(e)||isNaN(d)?new a.R(c.x+c.a/2,c.y+c.b):new a.R(e,d)};C.eab=function(a,b,c){return C.yJa(a,b)/c.b};C.KH=function(b,c,d){var e=b.F();if("on"==e.metricLabel.rendered){var h=u.Ko(e.value,b),f=u.Ko(e.min,b),k=u.Ko(e.max,b),z=d.x+d.a/2,n=d.y+d.b/2,l=d.a,m=d.b,B=e.background._metricLabelBounds;B&&(z=B.x+B.width/2,n=B.y+B.height/2,d.a=B.width,d.b=B.height);z=new a.ca(b.u(),h,z,n);!e.metricLabel.style.M("color")&&e.background._isDark&&
e.metricLabel.style.fa("color","#CCCCCC");z.Bb(e.metricLabel.style);e=(e=parseInt(e.metricLabel.style.kI()))?parseInt(e):null;e||(e=u.Yca([h,f,k],z,d),z.xg(h),z.fh(e));z.Yf();z.Ng();a.Ca.kd(z,l,m,c)&&(b.p6a=z)}};C.sfb=function(b,c,d){var e=b.F(),h=a.B.da(b.u());if(e.background.radius&&e.background.majorTickCount){var f=e.background._radius,k=e.min,z=e.max,n=e.background.majorTickCount,l=12,m=new a.Z(A,p,d.a,d.b),B=e.metricLabel.style.M("font-size");e.background._tickLabelHeight&&!B&&(m.b=e.background._tickLabelHeight);
e.background._tickLabelWidth&&!B&&(m.a=e.background._tickLabelWidth);if(!B)var v=new a.ca(b.u(),"",A,p),l=u.Yca([u.uta(e.max,b),u.uta(e.min,b)],v,m);for(B=0;B<n;B++){A=k+Math.abs(z-k)*B/(n-1);h&&(A=k+Math.abs(z-k)*(n-1-B)/(n-1));var v=u.uta(A,b),p=C.loa(b,A),r=C.cJa(b,d),A=r.x+f*Math.cos(p-Math.PI/2),p=r.y+f*Math.sin(p-Math.PI/2),v=new a.ca(b.u(),v,A,p);!e.tickLabel.style.M("color")&&e.background._isDark&&e.tickLabel.style.fa("color","#CCCCCC");v.Bb(e.tickLabel.style);e.tickLabel.style.M("font-size")||
v.fh(l);v.Yf();v.Ng();a.Ca.kd(v,m.a+.5,m.b+.5,c)}}};a.v.D(e,a.la);e.prototype.bm=function(b){var c=new a.Tb;c.rotate(b);this.rb(c);this.Z6a=b};e.prototype.qf=function(){return[this.Z6a]};e.prototype.df=function(a){a&&1==a.length&&this.bm(a[0])};a.Hp=function(){};a.v.D(a.Hp,x);a.Hp.newInstance=function(b,c,d){var e=new a.Hp;e.Init(b,c,d);return e};a.Hp.prototype.Init=function(b,c,e){a.Hp.C.Init.call(this,b,c,e);this.Xg=new d};a.Hp.prototype.vf=function(b){a.Hp.C.vf.call(this,this.Xg.en(b))};a.Hp.prototype.Fn=
function(b,c,d){var e=this.W.__layout.outerGap,h=this.W.max,f="vertical"==this.W.orientation,k="none"!=this.W.preserveAspectRatio;this.W.selectedState.source&&k?a.js.Ur(this.u(),this.W.selectedState.source,a.v.ti(this,function(k){a.B.ae()&&11==a.B.wI()&&k&&0==k.width&&0==k.height&&(k.width=1,k.height=1);k&&k.width&&k.height&&(k=k.width/k.height,this.XA=f?Math.min(c-2*e,(d-2*e)*k/h):Math.min((d-2*e)*k,(c-2*e)/h),this.qG=this.XA/k,this.Gf=f?new a.Z(e,(d-this.qG*h)/2,c-2*e,this.qG*h):new a.Z((c-this.XA*
h)/2,e,this.XA*h,d-2*e),z.ta(this,b,c,d))})):(k?this.qG=this.XA=f?Math.min(c-2*e,(d-2*e)/h):Math.min(d-2*e,(c-2*e)/h):(this.XA=f?c-2*e:(c-2*e)/h,this.qG=f?(d-2*e)/h:d-2*e),this.Gf=f?new a.Z(e,(d-this.qG*h)/2,c-2*e,this.qG*h):new a.Z((c-this.XA*h)/2,e,this.XA*h,d-2*e),z.ta(this,b,c,d))};a.Hp.prototype.DT=function(){var b=this.W.tooltip,b=b?b.renderer:null,d=A.ic(this);if(b){var e={component:this.W._widgetConstructor,label:u.Ko(this.W.value,this),color:d};return new a.kJ(this.u().Af(),b,d,e)}return new c(this)};
a.Hp.prototype.uJ=function(b,c){var d="vertical"==this.W.orientation?this.qG:this.XA;if(v.rC(this)){if("vertical"==this.W.orientation)c=Math.max(Math.min(c,this.Gf.y+this.Gf.b),this.Gf.y),e=Math.max((this.Gf.y+this.Gf.b-c)/d,this.W.min);else{b=Math.max(Math.min(b,this.Gf.x+this.Gf.a),this.Gf.x);var e=0,e=a.B.da(this.u())?Math.max((this.Gf.x+this.Gf.a-b)/d,this.W.min):Math.max((b-this.Gf.x)/d,this.W.min)}return u.Tca(this.W,e)}return null};a.Hp.prototype.t6a=function(){this.hla(this.W.value,"render");
this.dispatchEvent(a.Za.MM(this.W.value,this.W.value,!1))};a.Hp.prototype.E8=function(a,b){this.HT(a,b)};a.Hp.prototype.HT=function(b,c){var d=this.uJ(b,c);this.hla(d,"hover");this.dispatchEvent(a.Za.MM(this.W.value,d,!1))};a.Hp.prototype.dla=function(b,c){var d=this.W.value;this.W.value=this.uJ(b,c);this.W.changed=!0;this.ta();this.dispatchEvent(a.Za.MM(d,this.W.value,!1));this.dispatchEvent(a.Za.MM(d,this.W.value,!0))};a.Hp.prototype.hla=function(b,c,d){if(v.rC(this)){d||(d=this.Ea);var e=a.B.da(this.u()),
h="vertical"==this.W.orientation,f=h?this.qG:this.XA;b=Math.max(Math.min(b,this.W.max),0);var k=0,z=b*f,n=b*f;"render"==c&&(k=b*f,z=0);if(h){if(c=d.hb(0),e=new a.Cd,e.Pe(this.Gf.x,this.Gf.y,this.Gf.a,this.Gf.b-n),c.te(e),c=d.hb(1),e=new a.Cd,e.Pe(this.Gf.x,this.Gf.y+this.Gf.b-k,this.Gf.a,k),c.te(e),k=d.hb(2))c=new a.Cd,c.Pe(this.Gf.x,this.Gf.y+this.Gf.b-z,this.Gf.a,z),k.te(c)}else if(e){if(c=d.hb(0),e=new a.Cd,e.Pe(this.Gf.x,this.Gf.y,this.Gf.a-n,this.Gf.b),c.te(e),c=d.hb(1),e=new a.Cd,e.Pe(this.Gf.x+
this.Gf.a-n,this.Gf.y,k,this.Gf.b),c.te(e),k=d.hb(2))c=new a.Cd,c.Pe(this.Gf.x+this.Gf.a-n,this.Gf.y,z,this.Gf.b),k.te(c)}else if(c=d.hb(0),e=new a.Cd,e.Pe(this.Gf.x+n,this.Gf.y,this.Gf.a-n,this.Gf.b),c.te(e),c=d.hb(1),e=new a.Cd,e.Pe(this.Gf.x,this.Gf.y,k,this.Gf.b),c.te(e),k=d.hb(2))c=new a.Cd,c.Pe(this.Gf.x,this.Gf.y,z,this.Gf.b),k.te(c);this.hka(d,b)}};a.Hp.prototype.JFa=function(a){return this.Ea.hb(0).hb(a)};a.Hp.prototype.uS=function(){return new b(this)};a.v.D(d,p);d.mf={unselectedState:{shape:"star",
color:"#C4CED7",borderColor:null},selectedState:{shape:"star",color:"#F8C15A",borderColor:null},hoverState:{shape:"star",color:"#007CC8",borderColor:null},changedState:{shape:"star",color:"#ED2C02",borderColor:null}};d.lh={min:0,max:5,orientation:"horizontal",unselectedState:{shape:"star",color:"#F2F2F2",borderColor:"#B6B6B6"},selectedState:{shape:"star",color:"#F8C15A",borderColor:"#F5A700"},hoverState:{shape:"star",color:"#66A7DA",borderColor:"#4A86C5"},changedState:{shape:"star",color:"#F8C15A",
borderColor:"#959595"},preserveAspectRatio:"meet",step:1};a.v.D(c,a.yi);c.prototype.Qg=function(a,b,c){a=this.Ig.F();b=this.Ig.ab().ks?v.wR(this.Ig,this.Ig.uJ(b,c)):v.wR(this.Ig);return(b=v.lX(this.Ig,b))&&b.shortDesc?b.shortDesc:a.shortDesc};var z={};a.v.D(z,a.v);z.ta=function(b,c,d,e){if(v.rC(b)){d=b.F();e=v.wR(b);e=v.lX(b,e);var h=d.selectedState.color,f=d.changedState.color,k=d.selectedState.borderColor,n=d.changedState.borderColor;e&&e.color&&(f=h=e.color);e&&e.borderColor&&(n=k=e.borderColor);
e={value:0,type:d.unselectedState.shape,color:d.unselectedState.color,borderColor:d.unselectedState.borderColor,visualEffects:d.visualEffects,source:d.unselectedState.source,className:d.unselectedState.className,style:d.unselectedState.style};h={value:0,type:d.selectedState.shape,color:h,borderColor:k,visualEffects:d.visualEffects,source:d.selectedState.source,className:d.selectedState.className,style:d.selectedState.style};f={value:0,type:d.changedState.shape,color:f,borderColor:n,visualEffects:d.visualEffects,
source:d.changedState.source,className:d.changedState.className,style:d.changedState.style};n={value:0,type:d.hoverState.shape,color:d.hoverState.color,borderColor:d.hoverState.borderColor,visualEffects:d.visualEffects,source:d.hoverState.source,className:d.hoverState.className,style:d.hoverState.style};"dot"==d.unselectedState.shape&&(e.type="circle",e.visualEffects="none",e.size=.05);z.Lma(b,c,e);z.Lma(b,c,d.changed?f:h);d.readOnly||z.Lma(b,c,n);b.hla(d.value,"render",c)}else u.vp(b,c,new a.Z(0,
0,d,e))};z.Lma=function(b,c,d){var e=b.u(),h=new a.la(e);c.A(h);c=b.F();var f=b.Gf,k=b.XA;b=b.qG;var z;d.source?(z=new a.Ef(e,k/2,b/2,k,b,null,d.source),z.Dxa("none")):"none"!=d.type&&(z=a.PA.newInstance(e,null,null,!0),z.ta(d,k,b));for(d=0;d<c.max;d++){var n,l;"vertical"==c.orientation?(n=f.x+f.a/2-k/2,l=f.y+f.b-(d+1)*b):(n=a.B.da(e)?f.x+f.a-(d+1)*k:f.x+d*k,l=f.y+f.b/2-b/2);z&&(z.Ue(c.className),z.fa(c.style),n=new a.Ty(e,n,l,z),h.A(n))}};a.v.D(b,r);b.prototype.My=function(a){if(!1===this.Ig.F().readOnly){var c=
this.QF(a.pageX,a.pageY);this.Ig.E8(c.x,c.y);this.ks=!0}b.C.My.call(this,a)};b.prototype.To=function(a){!1===this.Ig.F().readOnly&&(this.QF(a.pageX,a.pageY),this.Ig.t6a(),this.ks=!1);b.C.To.call(this,a)};b.prototype.Ly=function(a){var c=this.QF(a.pageX,a.pageY);!1!==this.Ig.F().readOnly||this.ks||this.Ig.F().value==this.Ig.uJ(c.x,c.y)||(this.ks=!0);b.C.Ly.call(this,a)};b.prototype.mo=function(a){r.C.mo.call(this,a)};b.prototype.ol=function(a){this.ks=!1;return b.C.ol.call(this,a)};b.prototype.hia=
function(){return!0};a.Ia(a,"DialGauge",a.$q);a.Ia(a,"LedGauge",a.PA);a.Ia(a,"RatingGauge",a.Hp);a.Ia(a,"StatusMeterGauge",a.Wo);a.Ia(a.$q,"DialGauge",a.$q);a.Ia(a.$q,"LedGauge",a.PA);a.Ia(a.$q,"RatingGauge",a.Hp);a.Ia(a.$q,"StatusMeterGauge",a.Wo);a.Ia(x.prototype,"getAutomation",x.prototype.ph);a.Ia(x.prototype,"destroy",x.prototype.xa);a.Ia(x.prototype,"render",x.prototype.ta);a.Ia(w.prototype,"getDomElementForSubId",w.prototype.qh);a.Ia(w.prototype,"getValue",w.prototype.getValue);a.Ia(w.prototype,
"getMetricLabel",w.prototype.Nlb);a.HBa=D})(dvt);
  return dvt;
});
