/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a,b,c,d,e,h){this.Init(a,b,c,d,e,h)}function c(a,b){this.Init(a,b)}function d(a){this.Init(a.u(),a.bg,a);this.Ac=a}function e(){this.Init({skyros:e.lh,alta:e.mf,next:e.pv})}function f(a){this.Ac=a;this.Nf=this.Ac.F()}a.tf=function(){};a.v.D(a.tf,a.Ie);a.tf.newInstance=function(b,c,d){var e=new a.tf;e.Init(b,c,d);return e};a.tf.Jr=function(a){return(new e).Jr(a)};a.tf.prototype.Init=function(b,c,h){a.tf.C.Init.call(this,b,c,h);this.setId("legend1000"+Math.floor(1E9*Math.random()));
this.Xg=new e;this.I=new d(this);this.I.Qf(this);this.Zv=[];this.Gx=[];this.we=null;this.qsa=[]};a.tf.prototype.vf=function(a){this.Bk.KQ();a?(this.W=this.Xg.en(a),this.GPa(this.W.sections)):this.W||(this.W=this.NF())};a.tf.prototype.ht=function(b,c,d){this.vf(b);this.F().isLayout=!0;b=h.ta(this,new a.Z(0,0,c,d));this.F().isLayout=!1;return new a.yj(b.a,b.b)};a.tf.prototype.ta=function(b,d,e){this.Bc.KQ();this.vf(b);isNaN(d)||isNaN(e)||(this.xb=d,this.Jb=e);this.F().isLayout=!1;this.Hl();this.Zv=
[];this.Gx=[];this.we=null;this.qsa=[];a.B.Wa()||this.I.Xr(new c(this.I,this));this.hr();this.uma=h.ta(this,new a.Z(0,0,this.xb,this.Jb));(b=this.F().highlightedCategories)&&0<b.length&&this.Ve(b);this.qs();return this.uma};a.tf.prototype.Ve=function(b){this.F().highlightedCategories=b&&0<b.length?b.slice():null;a.vh.Ve(b,this.Zv,!0)};a.tf.prototype.bg=function(a,b){var c=a.type;if("categoryHighlight"==c&&"dim"==this.F().hoverBehavior){var d=this.Zv;this!=b&&this.Ve(a.categories);for(var e=0;e<d.length;e++)if(d[e].getId()==
a.categories){this.RQa.scrollIntoView(d[e].Qe()[0]);break}}this!=b&&"adfShowPopup"!=c&&"adfHidePopup"!=c||this.dispatchEvent(a)};a.tf.prototype.ela=function(b){if(b.Qe()[0]instanceof a.ia)this.Gx.push(b);else{var c=this.F().hideAndShowBehavior;(null!=b.Qg()||null!=b.Ch()||b.jk()||"none"!=c&&"off"!=c)&&this.Gx.push(b);this.Zv.push(b)}};a.tf.prototype.fla=function(a){this.we=a.clone()};a.tf.prototype.u6a=function(a){this.qsa.push(a)};a.tf.prototype.ph=function(){return new f(this)};a.tf.prototype.qM=
function(){return null!=this.I?this.I.jf():null};a.tf.prototype.Pfa=function(a,b){if(null!=this.I){for(var c=this.Gx,d=0;d<c.length;d++)if(c[d].getId()==a.getId()){this.I.Su(c[d]);b&&c[d].Sf();break}if(c=this.qM())d=c.Qe()[0],d.Gd("label",c.Ed()),this.u().NI(d)}};a.tf.prototype.aa=function(b){var c=new a.Z(0,0,this.xb,this.Jb);return b&&b!==this?this.nj(c,b):c};a.tf.prototype.jC=function(a){return a&&a!==this?this.nj(this.uma,a):this.uma};a.tf.prototype.gm=function(){return a.H.va(a.H.Ha,"LEGEND")};
a.tf.prototype.GPa=function(b){if(b&&!(0>=b.length))for(var c=this.F().hiddenCategories,d=0;d<b.length;d++){var e=b[d];e.sections&&(c=this.GPa(e.sections));if((e=e.items)&&!(0>=e.length))for(var f=0;f<e.length;f++){var p=e[f],w=h.Qda(p);"hidden"==p.categoryVisibility&&0>a.na.kb(c,w)&&c.push(w);p.categoryVisibility=null}}};a.tf.prototype.hr=function(){if(this.d7()){var b=this.F(),c=b.hideAndShowBehavior;if("off"!=c&&"none"!=c||"dim"==b.hoverBehavior)this.u().cg("application"),this.u().U4(a.H.va(a.H.Ha,
"COLON_SEP_LIST",[a.H.va(a.H.Ha,"DATA_VISUALIZATION"),a.Nd.HI(this.gm())]))}};a.tf.prototype.AI=function(){return 0<this.Gx.length};a.tf.pM=function(b){var c=b.Bk.Kk("itemsCount");if(null!=c)return c;for(var c=0,d=b.F().sections,e=0;e<d.length;e++)c+=a.tf.JTa(d[e]);b.Bk.Yh("itemsCount",c);return c};a.tf.JTa=function(b){var c=0;b.items&&(c+=b.items.length);if(b.frb){b=b.frb;for(var d=0;d<b.length;d++)c+=a.tf.JTa(b[d])}return c};a.v.D(f,a.Rd);f.prototype.zn=function(a){return(a=this.Ac.ab().mb(a))&&
a instanceof b&&(a=a.getData(),a=this.zJa(a,this.Nf))?"section"+a:null};f.prototype.zJa=function(a,b){if(b.sections&&0<b.sections.length){for(var c=0;c<b.sections.length;c++){if(b.sections[c]==a)return"["+c+"]";var d=this.zJa(a,b.sections[c]);if(d)return"["+c+"]"+d}return null}if(b.items&&0<b.items.length){for(c=0;c<b.items.length;c++)if(b.items[c]==a)return":item["+c+"]";return null}};f.prototype.BSa=function(a,b){if(b.sections&&0<b.sections.length){for(var c=0;c<b.sections.length;c++){var d=this.BSa(a,
b.sections[c]);if(d)return"["+c+"]"+d}return null}if(b.items&&0<b.items.length){for(c=0;c<b.items.length;c++)if(b.items[c].text==a.name)return":item["+c+"]";return null}};f.prototype.sua=function(a,b){var c=b.indexOf("["),d=b.indexOf("]");if(0<=c&&0<=d){var c=b.substring(c+1,d),e=b.indexOf(":");b=b.substring(d+1);d=b.indexOf("]");return 0<=b.indexOf("[")&&0<=d?this.sua(a.sections[c],b):0==e?a.items[c]:a.sections[c]}};f.prototype.qh=function(b){if(b==a.Rd.lD)return this.RF(this.Ac);b=this.sua(this.Nf,
b);for(var c=this.Ac.Zv,d=0;d<c.length;d++){var e=c[d].getData();if(b==e)return c[d].Qe()[0].Ua()}return null};f.prototype.pC=function(){return this.Nf.title};f.prototype.getItem=function(a){for(var b,c=a.shift(),d=this.Nf;void 0!=c;)0<a.length?d=d.sections[c]:b=d.items[c],c=a.shift();return b?{text:b.text?b.text:null}:null};f.prototype.Amb=function(a){for(var b,c=a.shift(),d=this.Nf;void 0!=c;)0<a.length?d=d.sections[c]:b=d.sections[c],c=a.shift();return{title:b.title?b.title:null,items:b.items?
this.UIa(b.items):null,sections:b.sections?this.XIa(b.sections):null}};f.prototype.UIa=function(a){for(var b=[],c=0;c<a.length;c++)b.push({text:a[c].text});return b};f.prototype.XIa=function(a){for(var b=[],c=0;c<a.length;c++)b.push({title:a[c].title?a[c].title:null,items:a[c].items?this.UIa(a[c].items):null,sections:a[c].sections?this.XIa(a[c].sections):null});return b};a.v.D(e,a.bb);e.pv={skin:a.j.pv,titleStyle:new a.j("color: #737373;"),_sectionTitleStyle:new a.j("color: #737373;"),layout:{titleGapWidth:17,
titleGapHeight:9,symbolGapWidth:7,symbolGapHeight:4,rowGap:4,columnGap:10,sectionGapHeight:16,sectionGapWidth:24}};e.mf={skin:a.j.mf,textStyle:new a.j(a.bb.Pm),titleStyle:new a.j(a.bb.xN+"color: #333333;"),_sectionTitleStyle:new a.j(a.bb.xN+"color: #333333;")};e.lh={skin:a.j.Hg,orientation:"vertical",position:null,backgroundColor:null,borderColor:null,textStyle:new a.j(a.bb.It+"font-size: 11px; color: #333333;"),titleStyle:new a.j(a.bb.It+"font-size: 12px; color: #003d5b;"),titleHalign:"start",hiddenCategories:[],
hideAndShowBehavior:"off",hoverBehavior:"none",hoverBehaviorDelay:200,scrolling:"asNeeded",halign:"start",valign:"top",drilling:"off",_color:"#a6acb1",_markerShape:"square",_lineWidth:3,layout:{outerGapWidth:3,outerGapHeight:3,titleGapWidth:8,titleGapHeight:3,symbolGapWidth:5,symbolGapHeight:4,rowGap:0,columnGap:8,sectionGapHeight:6,sectionGapWidth:15},isLayout:!1};e.Dh=function(b,c){var d=Math.min(a.Ca.cF(b.u(),b.F().textStyle)/14,1);return Math.ceil(c*d)};e.prototype.zua=function(){return{sections:{items:{_dataContext:!0}}}};
a.v.D(d,a.I);d.prototype.Tj=function(a){d.C.Tj.call(this,a);var b=this.mb(a.target);if(b){var c=this.Lwa(b),b=this.rva(b,a);(c||b)&&a.stopPropagation()}};d.prototype.My=function(b){d.C.My.call(this,b);if(b=this.mb(b.target)){var c=b instanceof a.yi?b.Er:null;c&&c.isCollapsible&&c.button&&c.button.Z2();this.nD(b)}};d.prototype.To=function(b){d.C.To.call(this,b);(b=this.mb(b.target))&&(b=b instanceof a.yi?b.Er:null)&&b.isCollapsible&&b.button&&b.button.KE()};d.prototype.Sw=function(a){var b=this.mb(a.target);
if(b){var c=a.Jxa,d=this.Lwa(b);a=this.rva(b,a);(d||a)&&c&&c.preventDefault()}};d.prototype.Lwa=function(b){var c=this.Ac.F().hideAndShowBehavior;if("none"==c||"off"==c)return!1;var d=b.Xd?b.Xd():null;if(!d||0>=d.length)return!1;for(var e=b.Xd()[0],c=this.Ac.F().hiddenCategories||[],c=c.slice(),f=b.Qe(),p=0;p<f.length;p++){var w=f[p];w instanceof a.za?w.SI(b.ic()):w instanceof a.Rect&&b.Oxa()}b=d[0];h.Mea(e,this.Ac)?(c.splice(a.na.kb(c,e),1),b=a.Za.mpb(b,c)):(c.push(e),b=a.Za.lpb(b,c));this.Ac.F().hiddenCategories=
c;this.nl(b,this.Ac);return!0};d.prototype.rva=function(c,d){if(c&&c.Ch&&c.Ch())return this.nl(a.Za.FI("action",c.Ch(),c.getId()),this.Ac),!0;if(c instanceof b&&c.jk()){var e=c.getId();this.nl(a.Za.efa(e,e,null),this.Ac);return!0}return(e=c instanceof a.yi?c.Er:null)&&e.isCollapsible?(this.XWa(d,e.id),!0):!1};d.prototype.uq=function(b,c,d){b=this.Ac.F();"none"==b.hoverBehavior||c.Qe&&c.Qe()[0]instanceof a.ia||(c=c.Xd?c.Xd():[],b.highlightedCategories=d?c.slice():null,d=a.Za.GI(b.highlightedCategories,
d),b=a.Ta.Pr(b.hoverBehaviorDelay),this.KJ.bg(d,this.Ac.Zv,b,!0))};d.prototype.pwa=function(a,b){var c=b.getId();this.XWa(a,c)};d.prototype.XWa=function(b,c){for(var d=this.Ac.F(),e=0;e<c.length;e++)d=d.sections[c[e]];d.expanded="off"==d.expanded?"on":"off";b.type==a.MouseEvent.Be&&(d=this.mb(this.ne(b)),d.Fd&&this.Su(d.Fd(b)));e=(d=this.Ac.qM())?d.Kd():!1;this.Ac.ta();d&&this.Ac.Pfa(d,e);this.qe();d=this.Ac.jC();this.nl(new a.Gn(d.a,d.b,d.x,d.y),this.Ac)};d.prototype.LA=function(){return this.Ac.F()._isScrollingLegend?
a.I.jG:a.I.Qy};d.prototype.Jk=function(){return this.Ac};d.prototype.z4=function(){return!0};d.prototype.AN=function(){var a=this.Df.rB;return a instanceof b&&null!=a.getData()._dataContext?"series":null};d.prototype.YY=function(){var a=this.Df.rB;return a instanceof b?[a.getData()._dataContext]:[]};d.prototype.JS=function(a){a=this.Ac.Md(this.u().eh(a.pageX,a.pageY));return this.Ac.we.Nj(a.x,a.y)?"legend":null};d.prototype.Dha=function(){return{}};d.prototype.Mja=function(a){if("legend"==this.JS(a)){a=
this.Ac.F()._dropColor;var b=this.Ac.Bc.Kk("background");b&&b.fb(a)}};d.prototype.Iga=function(){var a=this.Ac.Bc.Kk("background");if(a){var b=this.Ac.F().backgroundColor;b?a.fb(b):a.Wb()}};a.v.D(c,a.Cb);c.prototype.Init=function(a,b){c.C.Init.call(this,a);this.Ac=b};c.prototype.mk=function(b){var d=b.keyCode,e=this.yb.jf(),h=e&&e.Qe()[0]instanceof a.ia,f=null;null==e&&d==a.KeyboardEvent.Qh?(d=this.Ac.Gx,0<d.length&&(a.I.sc(b),f=this.jI(d))):e&&(d==a.KeyboardEvent.Qh?(a.I.sc(b),f=e):d==a.KeyboardEvent.Zi||
d==a.KeyboardEvent.ni?(d==a.KeyboardEvent.Zi&&this.yb.rva(e,b),h?this.yb.pwa(b,e.Qe()[0]):this.yb.Lwa(e),a.I.sc(b)):!h||d!=a.KeyboardEvent.Jf&&d!=a.KeyboardEvent.uf?f=c.C.mk.call(this,b):(this.yb.pwa(b,e.Qe()[0]),a.I.sc(b)));f&&this.Ac.RQa.scrollIntoView(f.Qe()[0]);return f};a.v.D(b,a.v);b.prototype.Init=function(a,b,c,d,e,f){this.Ac=a;this.Ag=b;this.Pn=c;this.xc=(this.CO=h.Qda(this.Pn))?this.CO:c.title;this.Vt=c.action;this.Iv=f;this.dgb=c._spb;this.Vl=d;this.o$=e;this.dd=!1;if(this.Vt||this.Iv)for(a=
0;a<this.Ag.length;a++)this.Ag[a].setCursor("pointer")};b.lb=function(a,c,d,e,h,f){if(!a||!d)return null;d=new b(c,a,d,e,h,f);c.ela(d);for(e=0;e<a.length;e++)c.ab().lb(a[e],d);return d};b.prototype.getData=function(){return this.Pn};b.prototype.ic=function(){return this.Pn.color};b.prototype.getId=function(){return this.xc};b.prototype.Qe=function(){return this.Ag};b.prototype.Xd=function(){return null!=this.CO?[this.CO]:null};b.prototype.Ch=function(){return this.Vt};b.prototype.jk=function(){return this.Iv};
b.prototype.zf=function(){return this.dgb};b.prototype.Ed=function(){var b=[],c=this.Ac.F(),d=this.Ac.F().hideAndShowBehavior,e=h.Mea(this.CO,this.Ac),f=this.getData();if(this.Ag[0]instanceof a.ia)return b.push(a.H.va(a.H.Ha,"off"==f.expanded?"STATE_COLLAPSED":"STATE_EXPANDED")),a.oa.Ik(f.title,b);"off"!=d&&"none"!=d&&b.push(a.H.va(a.H.Ha,e?"STATE_HIDDEN":"STATE_VISIBLE"));this.jk()&&b.push(a.H.Bf(c,"stateDrillable",a.H.Ha,"STATE_DRILLABLE"));return null!=f.shortDesc?a.oa.Ik(f.shortDesc,b):0<b.length?
a.oa.Ik(f.text,b):null};b.prototype.Oxa=function(){!a.B.kj()&&this.Ag[0]&&this.Ag[0].Gd("label",this.Ed())};b.prototype.Fd=function(b){return b.type==a.MouseEvent.Be?this:a.Cb.Fd(this,b,this.Ac.Gx,!0)};b.prototype.rf=function(b){return this.Ag[0]?this.Ag[0].aa(b):new a.Z(0,0,0,0)};b.prototype.Jm=function(){return this.Ag[0]?this.Ag[0].Ua():null};b.prototype.Sf=function(){this.dd=!0;this.Ag[0]&&(this.Ag[0]instanceof a.ia?this.Ag[0].Z2():this.Ag[0].Vb(a.B.bua()))};b.prototype.Qd=function(){this.dd=
!1;this.Ag[0]&&(this.Ag[0]instanceof a.ia?this.Ag[0].KE():this.Ag[0].Ga(null))};b.prototype.Kd=function(){return this.dd};b.prototype.Ui=function(){return this.Vl};b.prototype.Qg=function(){return this.o$};b.prototype.Xl=function(){return this.Pn.color};b.prototype.Zl=function(){return!0};b.prototype.Im=function(){return[this.getId()]};b.prototype.Zs=function(){return this.Qe()};var h={};a.v.D(h,a.v);h.yka=2;h.aFa=.6;h.EEa=10;h.ql=12;h.WZ=2;h.ta=function(b,c){var d=b.F(),f=b.u(),r=a.B.da(f);b.fla(c);
d.isLayout||h.Gr(b,c);var p=new a.Ph(f,c.a,c.b),w=new a.la(f);p.Ea.A(w);b.A(p);b.RQa=p;var x=e.Dh(b,d.layout.outerGapWidth),v=e.Dh(b,d.layout.outerGapHeight);c.x+=x;c.y+=v;c.a-=2*x;c.b-=2*v;if(0>=c.a||0>=c.b)return new a.yj(0,0);f=h.Heb(b,w,new a.Z(c.x,c.y,c.a,c.b));if(0==f.a||0==f.b)return new a.yj(0,0);p.P4();f.b>c.b?(f.b=c.b,d._isScrollingLegend=!0):d._isScrollingLegend=!1;var A=p=0,u=null!=d.hAlign?d.hAlign:d.halign;"center"==u?p=c.x-f.x+(c.a-f.a)/2:"end"==u&&(p=r?c.x-f.x:c.x-f.x+c.a-f.a);r=null!=
d.vAlign?d.vAlign:d.valign;"middle"==r?A=c.y-f.y+(c.b-f.b)/2:"bottom"==r&&(A=c.y-f.y+c.b-f.b);r=new a.Z(f.x+p-x,f.y+A-v,f.a+2*x,f.b+2*v);if(d.isLayout)return r;(p||A)&&w.Ma(p,A);d=b.qsa;for(w=0;w<d.length;w++)a.Dn.align(f,d[w].Hnb,d[w].text,d[w].text.Pc().a);return r};h.Heb=function(a,b,c){var d=a.F();c=c.clone();var f=h.mQ(a,b,d.title,c,null,!0);if(f){var p=f.Pc(),w=e.Dh(a,d.layout.titleGapHeight);c.y+=p.b+w;c.b-=Math.floor(p.b+w)}a=h.oOa(a,b,d.sections,c,[]);return f?p.wj(a):a};h.Gr=function(b,
c){var d=b.F(),e=d.backgroundColor,h=d.borderColor,d=d.dnd?d.dnd.drop.legend:{};if(e||h||0<Object.keys(d).length)d=new a.Rect(b.u(),c.x,c.y,c.a,c.b),e?d.fb(e):d.Wb(),h&&(d.Vb(h),d.md()),b.A(d),b.Bc.Yh("background",d)};h.mQ=function(b,c,d,e,h,f,w,x){var v=b.F(),A=c.u(),u=a.B.da(A);if(!d)return null;d=new a.ca(A,d,e.x,e.y);A=v.titleStyle;h&&h.titleStyle?A=new a.j(h.titleStyle):h&&v._sectionTitleStyle&&(A=v._sectionTitleStyle);d.Bb(A);return a.Ca.kd(d,e.a,Infinity,c)?(u&&d.Fa(e.x+e.a-d.Pc().a),v.isLayout?
c.removeChild(d):(c={id:w,button:x},c.isCollapsible=h&&("on"==h.collapsible||1==h.collapsible),b.ab().lb(d,new a.yi(d.Uq(),null,null,c)),f&&b.u6a({text:d,Hnb:h&&h.titleHalign?h.titleHalign:v.titleHalign})),d):null};h.oOa=function(b,c,d,f,r){var p=b.F();null==p.symbolWidth&&null==p.symbolHeight?(p.symbolWidth=h.EEa,p.symbolHeight=h.EEa):(null==p.symbolWidth?p.symbolWidth=p.symbolHeight:null==p.symbolHeight&&(p.symbolHeight=p.symbolWidth),p.symbolWidth=parseInt(p.symbolWidth),p.symbolHeight=parseInt(p.symbolHeight));
for(var w=e.Dh(b,p.layout.sectionGapHeight),x=e.Dh(b,p.layout.titleGapHeight),v=e.Dh(b,p.layout.sectionGapWidth),A=h.Kab(b),p="vertical"!=p.orientation,u=null,D=f.clone(),B,C=0;C<d.length;C++){var z=r.concat([C]),G="off"==d[C].expanded||0==d[C].expanded?x:w;p?(B=h.fOa(b,c,d[C],D,A),B.a>D.a?(D.a<f.a&&(f.y+=B.b+G,f.b-=B.b+G),B=B.a<=f.a?h.fOa(b,c,d[C],f,A):h.rOa(b,c,d[C],f,A,z,!0),f.y+=B.b+G,f.b-=B.b+G,D=f.clone()):(D.a-=B.a+v,a.B.da(b.u())||(D.x+=B.a+v))):(B=h.rOa(b,c,d[C],f,A,z,!1),f.y+=B.b+G,f.b-=
B.b+G);u=u?u.wj(B):B}return u};h.N8a=function(c,d,e,f,r,p,w,x,v,A,u){var D=h.Cma(c,f,r+"Enabled",p,w),B=h.Cma(c,f,r+"Over",p,w);f=h.Cma(c,f,r+"Down",p,w);c=new a.ia(c,D,B,f,null,v,A,u);d=b.lb([c],d,e,x,null,!1);c.cg("button");d.Oxa();return c};h.Cma=function(b,c,d,e,f){var p=a.B.da(b)?"RTL":"";b=new a.Image(b,c[d+p]?c[d+p]:c[d],e,f,h.ql,h.ql);b.Wb();return b};h.rOa=function(b,c,d,f,r,p,w){if(d){var x=b.F(),v=e.Dh(b,x.layout.symbolGapWidth),A=e.Dh(b,x.layout.rowGap),u=e.Dh(b,x.layout.columnGap),D=
b.u(),B=a.B.da(D);f=f.clone();"off"!=x.scrolling&&(f.b=Infinity);var C,z="on"==d.collapsible||1==d.collapsible,G;if(z){C=B?f.x+f.a-h.ql:f.x;if(!x.isLayout){var y="off"==d.expanded||0==d.expanded;G=y?"closed":"open";var y=a.H.va(a.H.Ha,y?"EXPAND":"COLLAPSE",null),E=b.ab();G=h.N8a(D,b,d,x._resources,G,C,f.y,y,p,E.pwa,E);c.A(G)}C=new a.Z(C,f.y,h.ql,h.ql);D=e.Dh(b,x.layout.symbolGapWidth);B||(f.x+=h.ql+D);f.a-=h.ql+D}D=(D=h.mQ(b,c,d.title,f,d,!z&&1>=p.length,p,G))?D.Pc():new a.Z(B?f.x+f.a:f.x,f.y,0,0);
D=C?D.wj(C):D;if(!d.items&&!d.sections||"off"==d.expanded||0==d.expanded)return D;0<D.b&&(z=e.Dh(b,x.layout.titleGapHeight),f.y+=D.b+z,f.b-=D.b+z);d.sections&&(p=h.oOa(b,c,d.sections,f,p),D=D.wj(p));if(!d.items)return D;z=h.Z7a(b,f,r,d.items,w);w=z.numCols;p=z.numRows;z=z.width;C=f.y;if(0==p||0==w)return D;G=Math.min(w*(z+u)-u,f.a);D=D.wj(new a.Z(B?f.x+f.a-G:f.x,f.y,G,p*(r+A)-A));if(x.isLayout)return D;x=z-x.symbolWidth-v;v=0;G=1;y=d.items.length;for(E=0;E<y&&(h.N_(b,c,d.items[E],f,x,r,E),f.y+=r+
A,v++,v===p&&G!==w&&(f.y=C,f.a-=z+u,B||(f.x+=z+u),v=0,G++),v!==p);E++);return D}};h.fOa=function(b,c,d,f,r){if(d){var p=b.F(),w=p.symbolWidth,x=e.Dh(b,p.layout.symbolGapWidth),v=e.Dh(b,p.layout.columnGap),A=e.Dh(b,p.layout.titleGapWidth),u=d.items.length,D=a.B.da(b.u()),B=f.clone(),C=h.mQ(b,c,d.title,f,d,!1),z=C?C.Pc():new a.Z(D?f.x+f.a:f.x,f.y,0,0);if(!d.items)return z;0<z.a&&(B.a-=z.a+A,D||(B.x+=z.a+A));var A=[],G=f.a-B.a,y,E;for(E=0;E<u;E++)y=d.items[E],y=Math.ceil(a.Ca.xea(b.u(),y.text,p.textStyle)),
G+=y+w+x+v,A.push(y);0<u&&(G-=v);z=new a.Z(D?f.x+f.a-G:f.x,f.y,G,Math.max(r,z.b));if(p.isLayout||G>f.a)return c.removeChild(C),z;for(E=0;E<u;E++)y=d.items[E],h.N_(b,c,y,B,A[E],r,E),f=A[E]+w+x,B.a-=f+v,D||(B.x+=f+v);return z}};h.Z7a=function(b,c,d,h,f){for(var p=b.F(),w=100<a.tf.pM(b),x=0,v=0;v<h.length;v++){var A=h[v];w?(A=new a.ca(b.u(),A.text),A.Bb(p.textStyle),A=a.Ca.Pj(A).a):A=a.Ca.xea(b.u(),A.text,p.textStyle);A>x&&(x=A)}w=p.symbolWidth;A=e.Dh(b,p.layout.symbolGapWidth);v=e.Dh(b,p.layout.rowGap);
b=e.Dh(b,p.layout.columnGap);x=Math.ceil(w+A+x);f?(f=Math.min(Math.floor((c.a+b)/(x+b)),h.length),d=Math.min(Math.floor((c.b+v)/(d+v)),Math.ceil(h.length/f)),f=Math.ceil(h.length/d),d=Math.ceil(h.length/f)):Infinity==c.b?(f=1,d=h.length):(d=Math.min(Math.floor((c.b+v)/(d+v)),h.length),f=Math.ceil(h.length/d),d=Math.ceil(h.length/f));c=Math.min(x,(c.a-b*(f-1))/f);return c<w?{width:0,numCols:0,numRows:0}:{width:c,numCols:f,numRows:d}};h.Kab=function(b){var c=b.F(),d=new a.ca(b.u(),"Test");d.Bb(c.textStyle);
d.Ng();d=a.Ca.Pj(d).b;b=c.symbolHeight+e.Dh(b,c.layout.symbolGapHeight);return Math.ceil(Math.max(d,b))};h.N_=function(c,d,f,n,r,p){var w=c.F(),x=c.u(),v=a.B.da(x),A=w.symbolWidth,u=e.Dh(c,w.layout.symbolGapWidth),D=v?n.x+n.a-A:n.x,B=v?n.x+n.a-A-u:n.x+A+u,C=h.Y8a(c,D,n.y,p,f),z=f.text,G;z&&(G=h.Z8a(d,r,z,w.textStyle))&&(G.Fa(B),a.Ca.BW(G,n.y+p/2),v&&G.Wh());d.A(C);n=new a.Rect(x,v?B-r-h.WZ:D-h.WZ,n.y-h.WZ,A+u+r+2*h.WZ,p+2*h.WZ);n.Wb();w=w.hideAndShowBehavior;"none"!=w&&"off"!=w&&n.setCursor("pointer");
d.A(n);d=[n,C];null!=G&&d.push(G);G=b.lb(d,c,f,null!=G?G.Uq():null,f.shortDesc,h.bcb(c,f));h.Mea(h.Qda(f),c)&&(C.SI(G.ic()),C.fa().Ue());if("none"!=w&&"off"!=w||null!=f.shortDesc)n.cg("img"),G.Oxa()};h.bcb=function(a,b){return"on"==b.drilling?!0:"off"==b.drilling?!1:"on"==a.F().drilling};h.Z8a=function(b,c,d,e){d=new a.ca(b.u(),d);d.Bb(e);return d=a.Ca.kd(d,c,Infinity,b)?d:null};h.Y8a=function(b,c,d,e,f){var p=b.F(),w=b.u(),x=null!=f.type?f.type:f.symbolType;f.markerShape||(f.markerShape=p._markerShape);
f.color||(f.color=p._color);f.lineWidth||(f.lineWidth="lineWithMarker"==x?h.yka:p._lineWidth);var v=p.symbolWidth,p=p.symbolHeight,A=d+e/2,u=c+v/2;"line"==x?w=h.LHa(w,c,d,v,e,f):"lineWithMarker"==x?(w=h.LHa(w,c,d,v,e,f),h.Mea(h.Qda(f),b)||w.A(h.fz(b,u,A,v*h.aFa,p*h.aFa,f))):"image"==x?w=h.Ema(b,c,d,v,p,e,f):"_verticalBoxPlot"==x?(p=Math.max(4*Math.round(p/4),4),w=new a.la(w),w.A(h.fz(b,u,A+p/4,v,p/2,h.K$(f,"q2"))),w.A(h.fz(b,u,A-p/4,v,p/2,h.K$(f,"q3")))):"_horizontalBoxPlot"==x?(c=a.B.da(w),v=Math.max(4*
Math.round(v/4),4),c=v/4*(c?1:-1),w=new a.la(w),w.A(h.fz(b,u+c,A,v/2,p,h.K$(f,"q2"))),w.A(h.fz(b,u-c,A,v/2,p,h.K$(f,"q3")))):w=h.fz(b,u,A,v,p,f);return w};h.Ema=function(b,c,d,e,f,h,w){return new a.Ef(b.u(),c+e/2,d+h/2,e,f,null,w.source)};h.fz=function(b,c,d,e,f,h){var w=b.u(),x=b.F();b=h.markerShape;var v=h.markerColor?h.markerColor:h.color,A=h.markerStyle?h.markerStyle:h.style,u=h.markerClassName?h.markerClassName:h.className,D=h.pattern;D&&"none"!=D?(e=new a.za(w,b,x.skin,0,0,e,f,null,null,!0),
e.ra(new a.wc(D,v,"#FFFFFF")),e.Ma(c,d)):(e=new a.za(w,b,x.skin,c,d,e,f,null,null,!0),e.fb(v));h.borderColor&&e.Vb(h.borderColor,null,h._borderWidth?h._borderWidth:1);"square"!=b&&"rectangle"!=b||e.md();e.Ue(u).fa(A);return e};h.LHa=function(b,c,d,e,f,h){d+=f/2;b=new a.Gc(b,c,d,c+e,d);c=new a.ya(h.color,1,h.lineWidth);e=h.lineStyle;"dashed"==e?c.bo(a.Xc.Qx(e),"4,2,4"):"dotted"==e&&c.bo(a.Xc.Qx(e),"2");b.Ue(h.className).fa(h.style);b.Ga(c);b.md();return b};h.K$=function(a,b){return{markerShape:"rectangle",
color:a._boxPlot[b+"Color"],pattern:a._boxPlot["_"+b+"Pattern"],className:a._boxPlot[b+"ClassName"],style:a._boxPlot[b+"Style"]}};h.Qda=function(a){var b=null;return b=a.categories&&0<a.categories.length?a.categories[0]:a.id?a.id:a.text};h.Mea=function(b,c){var d=c.F().hiddenCategories;return!d||0>=d.length?!1:-1!==a.na.kb(d,b)};a.Ia(a,"Legend",a.tf);a.Ia(a.tf,"newInstance",a.tf.newInstance);a.Ia(a.tf.prototype,"destroy",a.tf.prototype.xa);a.Ia(a.tf.prototype,"getAutomation",a.tf.prototype.ph);a.Ia(a.tf.prototype,
"getPreferredSize",a.tf.prototype.ht);a.Ia(a.tf.prototype,"highlight",a.tf.prototype.Ve);a.Ia(a.tf.prototype,"render",a.tf.prototype.ta);a.Ia(f.prototype,"getDomElementForSubId",f.prototype.qh);a.Ia(f.prototype,"getItem",f.prototype.getItem);a.Ia(f.prototype,"getSection",f.prototype.Amb);a.Ia(f.prototype,"getTitle",f.prototype.pC)})(dvt);
  return dvt;
});
