/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a){this.Init(a.u(),a.bg,a);this.ee=a}function c(a){this.Init(a)}a.Hi={};a.Hi.vn=function(){return a.B.Wa()};a.v.D(a.Hi,a.v);a.Hi.bf=function(a,b,c,h){c=(c-a)*h;a=b-a;return 0==c||0==a?0:c/a};a.Hi.Si=function(a,b,c,h){b=c*(b-a);return 0==b||0==h?a:b/h+a};a.Db=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Db,a.la);a.Db.S_a=10;a.Db.IYa=40;a.Db.DYa=20;a.Db.I6=20;a.Db.DEa=5;a.Db.FEa=1;a.Db.prototype.Init=function(c,e,f){a.Db.C.Init.call(this,c);this.Cc=e;this.pb=f;this.gL=this.CR()?
7:6;if(null!=this.Cc||null!=this.pb)this.I=new b(this),this.I.Qf(this),a.Hi.vn()?(this.Ya(a.TouchEvent.$i,this.hZ,!1,this),this.Ya(a.TouchEvent.Xo,this.dBa,!1,this),this.Ya(a.TouchEvent.Rm,this.Y6,!1,this),this.Ya(a.MouseEvent.Be,this.EN,!1,this)):(this.Ya(a.MouseEvent.zj,this.U6,!1,this),this.Ya(a.MouseEvent.xi,this.T6,!1,this),this.Ya(a.MouseEvent.Be,this.EN,!1,this),this.Ya(a.KeyboardEvent.ls,this.SS,!1,this),this.Ya(a.KeyboardEvent.lv,this.Xha,!1,this));this.Ooa=0};a.Db.prototype.Lm=function(a,
b,c){null==c&&(c=this.xb);a=this.bf(a);var h=this.bf(b);a<this.zz||h>this.Yda()||(b=Math.max(h-a,this.$da()),0<b&&0<=a&&h<=c&&(h=this.lt(),this.Wq()?this.fN(h,c-(a+b)):this.fN(h,a),this.$fa(h,b),this.O7()))};a.Db.prototype.BR=function(){return null==this.F$?!1:-1!=a.na.kb(this.F$,"zoom")};a.Db.prototype.cob=function(){return"off"!==this.j7a};a.Db.prototype.ta=function(b,c,f){if(null==b){var h=this.Yb,k=this.Ic,l=this.lt(),m=this.uw(l);null!=l&&0!=m&&(this.qOa=a.Hi.Si(h,k,m,this.xb));this.Hl()}null!=
c&&null!=f&&(this.xb=c,this.Jb=f);b&&(b=this.eD(b),this.uv(b));b=null!=this.Cc||null!=this.pb;this.VQa(c,f);b&&this.Qib(c,f);this.Atb(c,f);this.Npb(c,f);this.rtb(c,f);this.xwa(c,f);b&&(this.sib(c,f),this.CR()&&(this.IV=this.Mib()),this.ztb());null!=this.FKa&&(this.Ooa=Math.max(0,a.Hi.bf(this.Yb,this.Ic,this.FKa,this.zb)));0<this.Ooa&&this.apb(this.Ooa)};a.Db.prototype.vTa=function(){return new c(this)};a.Db.prototype.eD=function(a){return this.vTa(a).parse(a)};a.Db.prototype.uv=function(a){this.Yb=
a.start;this.Ic=a.end;this.zb=a.width;this.qOa=a.Ywa;this.Rma=a.currentTime;this.FKa=a.Znb;this.j7a=a.qQa;this.zz=Math.max(0,a.Sob);this.KV=Math.max(0,a.arb);isNaN(this.zz)&&(this.zz=0);isNaN(this.KV)&&(this.KV=0);this.UP=a.orientation;this.ndb=a.vVa;this.hcb=a.Xva;null!=a.ARa&&(this.F$=a.ARa.split(" "));null!=a.jwa&&0<a.jwa&&(this.aMa=a.jwa);this.T7a=a.Mhb;this.B2=a.WWa;null!=a.WWa&&(this.A2=this.B2.htb);this.Ena=a.Gjb;this.U7a=a.borderTopStyle;this.Xla=a.borderTopColor;this.Ica=a.Vxa;this.Kgb=a.eXa;
this.Sgb=a.cya;this.Qgb=a.aya;this.Mgb=a.Xxa;this.Ogb=a.Zxa;this.Rgb=a.bya;this.Pgb=a.$xa;this.Lgb=a.Wxa;this.Ngb=a.Yxa;this.obb=a.vva;this.x0=a.sva;this.voa=a.YTa;this.qKa=a.aUa;this.lKa=a.ZTa;this.mdb=a.twa;this.p9a=a.eta;this.qgb=a.Hxa;this.ogb=a.UWa;this.pgb=a.VWa;this.uLa=a.XUa;this.wcb=a.WUa;this.vOa=a.ZVa;this.yfb=a.YVa};a.Db.prototype.bf=function(b){return Math.max(0,a.Hi.bf(this.Yb,this.Ic,b,this.wM()))+this.zz};a.Db.prototype.Si=function(b){return a.Hi.Si(this.Yb,this.Ic,Math.max(0,b-this.zz),
this.wM())};a.Db.prototype.No=function(){return"true"==this.hcb};a.Db.prototype.Wq=function(){return this.No()&&!this.Sb()};a.Db.prototype.Sb=function(){return"vertical"==this.UP};a.Db.prototype.Wea=function(){return"above"==this.ndb};a.Db.prototype.wM=function(){return this.Sb()?this.Jb-this.zz-this.KV:this.xb-this.zz-this.KV};a.Db.prototype.Yda=function(){return this.Sb()?this.Jb-this.KV:this.xb-this.KV};a.Db.prototype.$da=function(){return null!=this.Tpa?this.Tpa:null!=this.aMa?this.Tpa=a.Hi.bf(this.Yb,
this.Ic,this.Yb+this.aMa,this.wM()):a.Db.S_a};a.Db.prototype.Oda=function(){return a.Hi.vn()?this.UW()/2:0};a.Db.prototype.UW=function(){return a.Hi.vn()?30:10};a.Db.prototype.DR=function(a){var b=a.getId();return"lh"==b||"rh"==b||"lhb"==b||"rhb"==b||"grpy"==b||"lbgrh"==b||"rbgrh"==b||null!=a.getParent()&&"grpy"==a.getParent().getId()};a.Db.prototype.sR=function(){if(null==this.B2)return 0;if(null==this.C2){var b=parseInt(this.B2.width,10);this.C2=!isNaN(b)&&b<this.xb?b:a.Db.IYa}return this.C2};a.Db.prototype.dF=
function(){if(null==this.B2)return 0;if(null==this.tPa){var b=parseInt(this.B2.height,10);this.tPa=!isNaN(b)&&b<this.Jb?b:a.Db.DYa}return this.tPa};a.Db.prototype.iea=function(b){return a.Hi.vn()&&null!=b.targetTouches?0<b.targetTouches.length?b.targetTouches[0].pageX:null:b.pageX};a.Db.prototype.jea=function(b){return a.Hi.vn()&&null!=b.targetTouches?0<b.targetTouches.length?b.targetTouches[0].pageY:null:b.pageY};a.Db.prototype.xC=function(){return!1};a.Db.prototype.lt=function(){return this.hb(1)};
a.Db.prototype.Uda=function(){return this.xC()?this.hb(3):null};a.Db.prototype.c4=function(){return this.xC()?this.hb(4):null};a.Db.prototype.PSa=function(){return this.xC()&&!this.BR()?this.hb(5):null};a.Db.prototype.Nua=function(){return this.xC()&&!this.BR()?this.hb(6):null};a.Db.prototype.rua=function(){return this.hb(this.Rb()-this.gL)};a.Db.prototype.Oua=function(){return this.hb(this.Rb()-(this.gL-1))};a.Db.prototype.QSa=function(){return this.hb(this.Rb()-(this.gL-2))};a.Db.prototype.FTa=
function(){return this.hb(this.Rb()-(this.gL-3))};a.Db.prototype.WRa=function(){return this.hb(this.Rb()-(this.gL-4))};a.Db.prototype.UTa=function(){return this.hb(this.Rb()-(this.gL-5))};a.Db.prototype.aY=function(a,b,c){this.Sb()?(-1!=b&&a.Il(b),-1!=c&&a.Jl(c)):(-1!=b&&a.eo(b),-1!=c&&a.un(c))};a.Db.prototype.I3=function(a){return this.Sb()?a.Rr():a.Qr()};a.Db.prototype.FU=function(a){a=a.target;if(null!=a){var b=a.getId();if(null==b)return null;if("_border"==b.substr(b.length-7))return this.Nta(a);
if("tick"!=b.substr(0,4)&&"ltb"!=b&&"rtb"!=b&&"bb"!=b&&"tab"!=b)return a}return null};a.Db.prototype.IUa=function(a){return"window"==a.getId()||"ftr"==a.getId()||"sta"==a.getId()||this.DR(a)?!0:!1};a.Db.prototype.CR=function(){return window&&window.CR};a.Db.prototype.VQa=function(b,c){var f=new a.Rect(this.u(),0,0,b,c,"bg");f.fb(this.mdb);f.md();this.A(f);return f};a.Db.prototype.Qib=function(b,c){var f=this.Sb(),h=f?new a.Rect(this.u(),0,0,b,0,"window"):new a.Rect(this.u(),0,0,0,c,"window");h.fb(this.Ica,
this.Kgb);h.md();if(!this.BR()){var k=this.UW(),l=this.Oda();if(f){var m=(b-36)/2,n=a.P.moveTo(m,0)+a.P.We(m+3,6,m+8,8)+a.P.lineTo(m+28,8)+a.P.We(m+33,6,m+36,0);a.P.closePath();var r=a.P.moveTo(m,0)+a.P.We(m+3,-6,m+8,-8)+a.P.lineTo(m+28,-8)+a.P.We(m+33,-6,m+36,0);a.P.closePath();var p=new a.Rect(this.u(),0,0,b,k,"lhb"),k=new a.Rect(this.u(),0,0,b,k,"rhb"),w="row-resize";if(this.voa)var x=this.gda(b,10),m=this.gda(b,10);else x=this.fda(m),m=this.fda(m)}else m=(c-36)/2,n=a.P.moveTo(0,m)+a.P.We(6,m+
3,8,m+8)+a.P.lineTo(8,m+28)+a.P.We(6,m+33,0,m+36),a.P.closePath(),r=a.P.moveTo(0,m)+a.P.We(-6,m+3,-8,m+8)+a.P.lineTo(-8,m+28)+a.P.We(-6,m+33,0,m+36),a.P.closePath(),p=new a.Rect(this.u(),0-l,0,k,c,"lhb"),k=new a.Rect(this.u(),l,0,k,c,"rhb"),w="col-resize",this.voa?(x=this.gda(10,c),m=this.gda(10,c)):(x=this.fda(m),m=this.fda(m));p.fb(this.Ica,0);k.fb(this.Ica,0);p.md();k.md();n=new a.vb(this.u(),n,"lh");r=new a.vb(this.u(),r,"rh");n.fb(this.x0);n.Vb(this.x0);r.fb(this.x0);r.Vb(this.x0);this.Ica==
this.x0&&(n.md(),r.md());p.setCursor(w);k.setCursor(w);n.setCursor(w);r.setCursor(w);x.setCursor(w);m.setCursor(w);h.A(p);h.A(n);h.A(x);h.A(k);h.A(r);h.A(m)}h.setCursor("move");this.A(h);h=f?this.No()?new a.Gc(this.u(),this.sR(),0,this.sR(),c,"tab"):new a.Gc(this.u(),b-this.sR(),0,b-this.sR(),c,"tab"):this.Wea()?new a.Gc(this.u(),0,this.dF(),b,this.dF(),"tab"):new a.Gc(this.u(),0,c-this.dF(),b,c-this.dF(),"tab");h.Vb(this.ogb,this.pgb);h.md();this.uPa=h;this.A(h);this.xC()&&(f?(h=new a.Rect(this.u(),
0,0,b,0,"lbg"),p=new a.Rect(this.u(),0,0,b,0,"rbg")):(h=new a.Rect(this.u(),0,0,0,c,"lbg"),p=new a.Rect(this.u(),0,0,0,c,"rbg")),h.fb(this.uLa,this.wcb),this.A(h),p.fb(this.vOa,this.yfb),this.A(p),a.Hi.vn()&&void 0!=l&&(this.Oda(),f?(f=new a.Rect(this.u(),0,0,b,l,"lbgrh"),l=new a.Rect(this.u(),0,0,b,l,"rbgrh")):(f=new a.Rect(this.u(),0,0,l,c,"lbgrh"),l=new a.Rect(this.u(),0,0,l,c,"rbgrh")),f.fb(this.uLa,0),this.A(f),l.fb(this.vOa,0),this.A(l)))};a.Db.prototype.gda=function(b,c){var f=new a.Image(this.u(),
this.voa,(b-this.qKa)/2,(c-this.lKa)/2,this.qKa,this.lKa,"grpy");f.nb(!1);return f};a.Db.prototype.fda=function(b){var c=new a.la(this.u(),"grpy"),f=this.obb;if(this.Sb()){var h=8+b;b=3;for(var k=0;9>k;k++){var l=new a.Gc(this.u(),h+2*k,b,h+2*k+1,b,"dot1"+k);l.Vb(f);c.A(l);b+=2;l=new a.Gc(this.u(),h+1+2*k,b,h+1+2*k+1,b,"dot2"+k);l.Vb(f);c.A(l);b+=2;l=new a.Gc(this.u(),h+2*k,b,h+2*k+1,b,"dot3"+k);l.Vb(f);c.A(l);b=3}l=new a.Gc(this.u(),h+18,b,h+18+1,b,"dot4");l.Vb(f);c.A(l);b+=4;l=new a.Gc(this.u(),
h+18,b,h+18+1,b,"dot5")}else{h=3;b=8+b;for(k=0;9>k;k++)l=new a.Gc(this.u(),h,b+2*k,h,b+2*k+1,"dot1"+k),l.Vb(f),c.A(l),h+=2,l=new a.Gc(this.u(),h,b+1+2*k,h,b+1+2*k+1,"dot2"+k),l.Vb(f),c.A(l),h+=2,l=new a.Gc(this.u(),h,b+2*k,h,b+2*k+1,"dot3"+k),l.Vb(f),c.A(l),h=3;l=new a.Gc(this.u(),h,b+18,h,b+18+1,"dot4");l.Vb(f);c.A(l);h+=4;l=new a.Gc(this.u(),h,b+18,h,b+18+1,"dot5")}l.Vb(f);c.A(l);c.md();return c};a.Db.prototype.ztb=function(){var b=this.Sb(),c=this.lt(),f=this.wM(),h=b?this.Jb:this.xb,k=this.zb,
l=this.Yb,m=this.Ic,b=this.qOa,n=a.Hi.Si(l,m,0,k),k=a.Hi.Si(l,m,h,k),n=this.bf(n),h=Math.min(h,this.bf(k)),b=this.bf(b),h=h-n;this.Wq()?this.fN(c,f-b-h):this.fN(c,b);this.$fa(c,h);this.O7();this.UU=this.Yhb(f)};a.Db.prototype.sib=function(b,c){var f=this.lt(),h=a.Db.FEa/2;if(this.Sb())var k=f.ib(),l=k+h,m=k+f.getHeight(),n=m-h,r=0,p=h,w=b-h,h=new a.Gc(this.u(),r,l,b,l,"lh"),x=new a.Gc(this.u(),r,n,b,n,"rh"),v=new a.Gc(this.u(),p,0,p,k,"ltb"),A=new a.Gc(this.u(),p,m,p,c,"rtb"),n=new a.Gc(this.u(),
w,k,w,m,"bb"),k=new a.Gc(this.u(),p,k,p,m,"tb");else k=0,l=k+h,m=c,n=m-h,r=f.Va(),p=r+h,f=r+f.getWidth(),w=f-h,h=new a.Gc(this.u(),p,k,p,m,"lh"),x=new a.Gc(this.u(),w,k,w,m,"rh"),v=new a.Gc(this.u(),0,l,r+1,l,"ltb"),A=new a.Gc(this.u(),f-1,l,b,l,"rtb"),n=new a.Gc(this.u(),r,n,f,n,"bb"),k=new a.Gc(this.u(),r,l,f,l,"tb");h.md();x.md();v.md();A.md();n.md();k.md();"none"!=this.Ogb&&h.Vb(this.Ngb);this.A(h);"none"!=this.Qgb&&x.Vb(this.Pgb);this.A(x);"none"!=this.U7a&&this.Xla&&(v.Vb(this.Xla),A.Vb(this.Xla));
this.A(v);this.A(A);"none"!=this.Mgb&&n.Vb(this.Lgb);this.A(n);"none"!=this.Sgb&&k.Vb(this.Rgb);this.A(k)};a.Db.prototype.Mib=function(){var b=this.Sb()?a.P.moveTo(6,0)+a.P.lineTo(0,5)+a.P.lineTo(5,5)+a.P.lineTo(5,17)+a.P.lineTo(0,17)+a.P.lineTo(6,22)+a.P.lineTo(12,17)+a.P.lineTo(7,17)+a.P.lineTo(7,5)+a.P.lineTo(12,5)+a.P.closePath():a.P.moveTo(5,0)+a.P.lineTo(0,6)+a.P.lineTo(5,12)+a.P.lineTo(5,7)+a.P.lineTo(17,7)+a.P.lineTo(17,12)+a.P.lineTo(22,6)+a.P.lineTo(17,0)+a.P.lineTo(17,4)+a.P.lineTo(5,4)+
a.P.lineTo(5,0)+a.P.closePath(),b=new a.vb(this.u(),b,"arr");b.fb("#ffffff");b.Vb("#000000");b.Jc(!1);this.A(b);return b};a.Db.prototype.ey=function(a){return this.Sb()?a.getHeight():a.getWidth()};a.Db.prototype.Fsb=function(a,b){this.Sb()?a.qb(b):a.Xa(b)};a.Db.prototype.uw=function(a){return this.Sb()?a.pa():a.qa()};a.Db.prototype.fN=function(b,c){c=Math.max(0,c);this.Sb()?b.wa(c):b.ga(c);if(this.xC()){this.Uda().Xa(c);var f=c+this.d4(b),h=this.c4();h.Fa(f);h.Xa(Math.max(0,this.xb-f));a.Hi.vn()&&
!this.BR()&&(h=this.Oda(),this.PSa().Fa(c-h),this.Nua().Fa(f))}};a.Db.prototype.d4=function(a){return this.ey(a)};a.Db.prototype.$fa=function(b,c){c=Math.max(this.$da(),c);c=Math.min(this.Sb()?this.Jb:this.xb,c);this.Fsb(b,c);if(this.xC()){var f=this.uw(b)+c,h=this.c4();h.Fa(f);h.Xa(Math.max(0,this.xb-f));a.Hi.vn()&&!this.BR()&&this.Nua().Fa(f)}if(!this.BR()){var f=b.hb(3),h=b.hb(4),k=b.hb(5);this.Sb()?(h.wa(c),f.wa(c-this.UW()),k.wa(c-10)):(h.ga(c),f.ga(c-this.UW()),k.ga(c-10))}};a.Db.prototype.Yhb=
function(b){var c=this.zb,f=this.Yb,h=this.Ic,k=a.Hi.Si(f,h,1,b);b=a.Hi.Si(f,h,2,b);k=a.Hi.bf(f,h,k,c);return a.Hi.bf(f,h,b,c)-k};a.Db.prototype.Atb=function(b,c){if(null!=this.A2)for(var f=this.Sb(),h=this.wM(),k=0;k<this.A2.length;k++){var l=this.A2[k],m=this.bf(parseInt(l.time,10)),l=l.label,n=0,n=k+1<this.A2.length?this.bf(parseInt(this.A2[k+1].time,10))-m:h-m;this.Wq()&&(m=h-m);f&&(n=this.xb);n-=2*a.Db.DEa;this.Gsa(m,b,c,"tick"+k);this.Fsa(m,l,b,c,n,"label"+k)}};a.Db.prototype.Gsa=function(b,
c,f,h){b=this.Sb()?new a.Gc(this.u(),0,b,c,b,h):new a.Gc(this.u(),b,0,b,f,h);c=new a.ya(this.qgb);c.fa(a.Xc.VC,3);b.Ga(c);b.md();this.A(b)};a.Db.prototype.Fsa=function(b,c,f,h,k,l,m){m=m||new a.j("font-weight:bold");this.Sb()?(c=new a.ca(this.u(),c,4,b,l),c.Bb(m),this.No()&&(this.A(c),m=c.aa(),this.removeChild(c),c.Fa(Math.max(4,this.xb-m.a-4)))):(h=this.Wea()?2:h-this.dF()+2,f=a.Db.DEa,c=new a.ca(this.u(),c,b+f,h,l),c.Bb(m),this.Wq()&&(this.A(c),m=c.aa(),this.removeChild(c),c.Fa(b-Math.min(m.a,k)-
f)));a.Ca.kd(c,k,Infinity,this);c.ieb=c.Uq()};a.Db.prototype.rtb=function(b,c){if(null!=this.Rma&&!isNaN(this.Rma)){var f=this.bf(this.Rma);this.Sb()?f=new a.Gc(this.u(),0,f,b,f,"ocd"):(this.No()&&(f=b-f),f=new a.Gc(this.u(),f,0,f,c,"ocd"));f.Vb(this.p9a);f.md();this.A(f)}};a.Db.prototype.Npb=function(a,b){if(null!=this.Ena)for(var c=0;c<this.Ena.length;c++)this.ihb(this.Ena[c],a,b)};a.Db.prototype.ihb=function(b,c,f){var h=parseInt(b.rs,10),k=parseInt(b.re,10);b=b.c;if(null!=h&&null!=k){var l=this.wM(),
h=this.bf(h),k=this.bf(k)-h;this.Wq()&&(h=l-h-k);c=this.Sb()?new a.Rect(this.u(),0,h,c-this.sR(),k,"ftr"):new a.Rect(this.u(),h,this.Wea()?this.dF():0,k,f-this.dF(),"ftr");null!=b&&c.fb(b,.4);c.setCursor("move");c.md();this.A(c)}};a.Db.prototype.xwa=function(){};a.Db.prototype.Jsa=function(b){var c=this.lt();c.hb(3);c.hb(4);c.hb(5);if(b!=this.uw(c)){var f=this.rua(),h=this.Oua(),k=this.QSa(),l=this.FTa(),m=this.WRa(),n=this.UTa();if(this.Sb())var r=c.pa,p=c.wa,w=f.Rr,x=f.Il,v=f.ot,A=f.Jl,u=h.Rr,D=
h.Il,B=h.ot,C=h.Jl,z=k.ot,G=k.Jl,y=l.Rr,E=l.Il,M=m.Rr,S=m.Il,O=m.ot,fa=m.Jl,ga=n.Rr,aa=n.Il,ea=n.ot,ia=n.Jl;else r=c.qa,p=c.ga,w=f.Qr,x=f.eo,v=f.nt,A=f.un,u=h.Qr,D=h.eo,B=h.nt,C=h.un,z=k.nt,G=k.un,y=l.Qr,E=l.eo,M=m.Qr,S=m.eo,O=m.nt,fa=m.un,ga=n.Qr,aa=n.eo,ea=n.nt,ia=n.un;var T=this.zz,Z=this.Yda(),W=this.d4(c);b=Math.max(T,Math.min(Z-W,b));T=this.cob()?new a.G(this.u(),.5,0,a.Je.kF):null;this.Ws(T,c,r,p,b);this.Ws(T,f,w,x,b);this.Ws(T,f,v,A,b);this.Ws(T,h,u,D,b+W);this.Ws(T,h,B,C,b+W);this.Ws(T,k,
z,G,b+1);this.Ws(T,l,y,E,b+W-1);this.Ws(T,m,M,S,b);this.Ws(T,n,ga,aa,b);this.Ws(T,m,O,fa,b+W);this.Ws(T,n,ea,ia,b+W);this.xC()&&(c=this.Uda(),this.Ws(T,c,c.getWidth,c.Xa,b),W=b+W,c=this.c4(),f=c.getWidth,h=c.Xa,k=c.Va,l=c.Fa,m=this.Sb()?this.Jb:this.xb,this.Ws(T,c,f,h,m-W),this.Ws(T,c,k,l,W),a.Hi.vn()&&!this.BR()&&(c=this.Oda(),f=this.PSa(),h=f.Va,k=f.Fa,l=this.Nua(),m=l.Va,n=l.Fa,this.Ws(T,f,h,k,b-c),this.Ws(T,l,m,n,W)));null!=T&&T.play()}};a.Db.prototype.Ws=function(b,c,f,h,k){null!=b?b.N(a.G.V,
c,f,h,k):h.call(c,k)};a.Db.prototype.U6=function(b){var c=this.FU(b);if(c&&"bg"!=c.getId()&&"ocd"!=c.getId())if("label"==c.getId().substr(0,5)&&(c instanceof a.ca||c instanceof a.He))c.ao()&&this.u().Af().pY(b.pageX,b.pageY,c.ieb,"#000000");else if(null!=this.IV&&this.DR(c)&&(b=this.u().eh(b.pageX,b.pageY),b=this.Md(b),this.Sb()?this.IV.Ma(b.x+6,b.y-10):this.IV.Ma(b.x-6,b.y-20),this.IV.Jc(!0)),"window"==c.getId()||"ftr"==c.getId()||"arr"==c.getId()||this.DR(c))this.CR()&&this.setCursor("move");else return c};
a.Db.prototype.T6=function(a){null==this.ku&&this.setCursor("default");a=this.FU(a);if(null!=a)return this.DR(a)&&null!=this.IV&&this.IV.Jc(!1),a};a.Db.prototype.EN=function(b,c,f){b.stopPropagation();var h=this.FU(b);if(h&&"window"!=h.getId()&&!this.DR(h))if("bg"==h.getId()||"label"==h.getId().substr(0,5)||"ocd"==h.getId()||"lbg"==h.getId()||"rbg"==h.getId()){void 0==c&&(c=b.pageX);void 0==f&&(f=b.pageY);b=this.u().eh(c,f);b=this.Md(b);this.Sb()?(f=b.y,h=this.Jb):(f=b.x,h=this.xb);b=this.lt();c=
f-this.ey(b)/2;this.Jsa(c);this.Wq()&&(f=this.xb-f);var k=this.Si(f);f=new a.Qc(a.Qc.IZ);f.setTime(k);c=Math.max(0,Math.min(c,h-this.ey(b)));this.Wq()?(h=this.Si(this.xb-(c+this.ey(b))),b=this.Si(this.xb-c)):(h=this.Si(c),b=this.Si(c+this.ey(b)));f.Xfa(h);f.Wfa(b);this.dispatchEvent(f)}else return h};a.Db.prototype.JQ=function(b,c,f){b=this.FU(b);if(null!=b&&this.IUa(b)){if("ftr"==b.getId()||"sta"==b.getId())b=this.lt();this.naa=c;this.EKa=f;if(this.DR(b)){c=this.lt();this.Wq()?(this.fqa=this.xb-
c.Va(),this.oqa=this.fqa-c.getWidth()):(this.oqa=c.Va(),this.fqa=this.oqa+c.getWidth());"grpy"==b.getParent().getId()&&(b=b.getParent());f=b.getId();"grpy"==f&&(b=c.o3(b),f=b.getId());if("lh"==f||"rh"==f)b=c.o3(b),f=b.getId();"lbgrh"==f&&(b=c.hb(0));"rbgrh"==f&&(b=c.hb(c.Rb()-3));a.Hi.vn()||(this.Sb()?(b.jb(0-a.Db.I6),b.qb(2*(b.getHeight()+a.Db.I6))):(b.Fa(0-a.Db.I6),b.Xa(2*(b.getWidth()+a.Db.I6))));this.Epb(b.getCursor())}this.ku=b;b=new a.Qc(a.Qc.Eja);this.dispatchEvent(b);return!0}return!1};a.Db.prototype.Epb=
function(a){var b=this.lt();null!=b&&b.setCursor(a);if(this.xC()){var b=this.Uda(),c=this.c4();null!=b&&null!=c&&(b.setCursor(a),c.setCursor(a))}};a.Db.prototype.Uqb=function(){var a=this.lt();null!=a&&a.setCursor("move");if(this.xC()){var a=this.Uda(),b=this.c4();null!=a&&null!=b&&(a.setCursor("default"),b.setCursor("default"))}};a.Db.prototype.dI=function(){null!=this.ku&&("window"==this.ku.getId()?this.DRa(0,0):this.DR(this.ku)&&(this.qta(),a.Hi.vn()||(this.Sb()?(this.ku.jb(0),this.ku.qb(this.UW())):
(this.ku.Fa(0),this.ku.Xa(this.UW()))),this.Uqb()),this.ku=null,this.naa=-1)};a.Db.prototype.S2=function(a,b,c){if(null!=this.ku&&-1!=this.naa){var h=b-this.naa,k=c-this.EKa;this.naa=b;this.EKa=c;"window"==this.ku.getId()?this.bUa(0,h,k):"lh"==this.ku.getId()||"lhb"==this.ku.getId()?this.Jnb(a,h,k):"rh"!=this.ku.getId()&&"rhb"!=this.ku.getId()||this.tva(a,h,k)}};a.Db.prototype.hZ=function(a){var b=a.touches;this.lW=b[0].pageX;this.DQ=b[0].pageY;2==b.length&&(a.preventDefault(),this.mW=b[1].pageX,
this.G2=b[1].pageY,20>Math.abs(this.DQ-this.G2)?this.oB=0:this.G2=this.mW=this.DQ=this.lW=null)};a.Db.prototype.dBa=function(a){a.preventDefault();a=a.touches;if(null!=this.mW&&null!=this.G2)50>this.oB?this.oB++:(this.tva(null,a[1].pageX-this.mW,0),this.mW=a[1].pageX,this.oB=0);else{var b=Math.abs(this.DQ-a[0].pageY);if(3<Math.abs(this.lW-a[0].pageX)||3<b)this.DQ=this.lW=null}};a.Db.prototype.Y6=function(a){null!=this.mW&&null!=this.G2?this.qta():null!=this.lW&&null!=this.DQ&&this.EN(a,this.lW,this.DQ);
this.G2=this.mW=this.DQ=this.lW=null};a.Db.prototype.SS=function(b){var c=b.keyCode;if(c===a.KeyboardEvent.Jf||c===a.KeyboardEvent.uf)c=c===a.KeyboardEvent.Jf?-1:1,(b.shiftKey?this.tva:this.bUa).call(this,b,c,c)};a.Db.prototype.Xha=function(b){var c=b.keyCode;if(c===a.KeyboardEvent.Jf||c===a.KeyboardEvent.uf)c=c===a.KeyboardEvent.Jf?-1:1,(b.shiftKey?this.qta:this.DRa).call(this,c,c)};a.Db.prototype.apb=function(a){a/=this.UU;this.Wq()&&(a=0-a);this.Jsa(a)};a.Db.prototype.bUa=function(b,c,f){this.ERa(a.Qc.Fja,
c,f)};a.Db.prototype.DRa=function(b,c){this.ERa(a.Qc.iDa,b,c)};a.Db.prototype.ERa=function(b,c,f){var h=this.lt(),k=this.uw(h),l=this.ey(h),m=this.zz,n=this.Yda();c=this.Sb()?f:c;k+c<=m?(this.fN(h,m),l=this.Wq()?a.Qc.s6:a.Qc.F7):k+l+c>=n?(this.fN(h,n-l),l=this.Wq()?a.Qc.F7:a.Qc.s6):(this.fN(h,k+c),l=this.Wq()?(n-l-k-this.zz)*this.UU:(k-this.zz)*this.UU);this.O7();b=new a.Qc(b);b.setPosition(l);this.Wq()?(l=this.Si(this.xb-(k+this.ey(h))),h=this.Si(this.xb-k)):(l=this.Si(k),h=this.Si(k+this.ey(h)));
b.Xfa(l);b.Wfa(h);this.dispatchEvent(b)};a.Db.prototype.Jnb=function(a,b,c){this.$Ta(a,b,c,!0)};a.Db.prototype.tva=function(a,b,c){this.$Ta(a,b,c,!1)};a.Db.prototype.$Ta=function(b,c,f,h){var k=this.wM();f=this.Sb()?f:c;if(0!=f){c=this.lt();var l=this.uw(c),m=this.d4(c);if(h){if(m-f<=this.$da()||l+f<=this.zz)return;b=this.Sb()?this.u().eh(this.iea(b),this.jea(b)).y:this.u().eh(this.iea(b),this.jea(b)).x;b=this.Md(b);if(0<f&&b<=l||0>f&&b>=l)return;this.fN(c,l+f);this.$fa(c,m-f)}else{if(m+f<=this.$da()||
l+m+f>=this.Yda())return;b=this.Sb()?this.u().eh(this.iea(b),this.jea(b)).y:this.u().eh(this.iea(b),this.jea(b)).x;b=this.Md(b);if(0<f&&b<=l+m||0>f&&b>=l+m)return;this.$fa(c,m+f)}this.O7();b=this.Si(this.d4(c));b=k*(this.Ic-this.Yb)/(b-this.Yb);k=new a.Qc(a.Qc.hDa);k.AWa(b);k.Srb(this.Wq()?h:!h);h?k.oWa(0>f):k.oWa(0<f);this.Wq()?(h=this.Si(this.xb-(this.uw(c)+this.ey(c))),c=this.Si(this.xb-this.uw(c))):(h=this.Si(this.uw(c)),c=this.Si(this.uw(c)+this.ey(c)));k.Xfa(h);k.Wfa(c);this.dispatchEvent(k)}};
a.Db.prototype.qta=function(){var b=this.Yb,c=this.Ic,f=this.zb,h=this.wM(),k=this.lt(),l=this.Si(this.ey(k)),b=h*(c-b)/(l-b),c=this.Si(this.oqa),h=this.Si(this.fqa);this.Wq()?(l=this.Si(this.xb-(this.uw(k)+this.ey(k))),k=this.Si(this.xb-this.uw(k))):(l=this.Si(this.uw(k)),k=this.Si(this.uw(k)+this.ey(k)));var m=new a.Qc(a.Qc.J7);m.tsb(f);m.AWa(b);m.usb(c);m.rsb(h);m.Xfa(l);m.Wfa(k);this.dispatchEvent(m)};a.Db.prototype.O7=function(){var b=this.lt(),c=a.Db.FEa/2,f=this.uw(b),h=f+c,b=f+this.d4(b)-
c,c=this.rua(),k=this.Oua(),l=this.QSa(),m=this.FTa(),n=this.WRa(),r=this.UTa();this.aY(c,h,h);this.aY(k,b,b);this.aY(l,-1,f);this.aY(m,this.I3(k),-1);this.aY(n,this.I3(c),this.I3(k));this.aY(r,this.I3(c),this.I3(k))};a.Db.prototype.dispatchEvent=function(b){a.IA.dispatchEvent(this.Cc,this.pb,this,b)};a.Db.prototype.xa=function(){this.I&&(this.I.ll(this),this.I.xa(),this.I=null);a.Hi.vn()?(this.jc(a.TouchEvent.$i,this.hZ,!1,this),this.jc(a.TouchEvent.Xo,this.dBa,!1,this),this.jc(a.TouchEvent.Rm,this.Y6,
!1,this),this.jc(a.MouseEvent.Be,this.EN,!1,this)):(this.jc(a.MouseEvent.zj,this.U6,!1,this),this.jc(a.MouseEvent.xi,this.T6,!1,this),this.jc(a.MouseEvent.Be,this.EN,!1,this),this.jc(a.KeyboardEvent.ls,this.SS,!1,this),this.jc(a.KeyboardEvent.lv,this.Xha,!1,this));a.Db.C.xa.call(this)};a.v.D(c,a.v);c.prototype.Init=function(a){this.ha=a};c.prototype.parse=function(a){return this.CZ(a)};c.prototype.CZ=function(b){var c={};c.qQa=b.animationOnClick;null!=b.startTime&&(c.start=b.startTime);null!=b.endTime&&
(c.end=b.endTime);null==c.start&&(c.start=(new Date).getTime());if(null==c.end||c.end<=c.start)c.end=c.start+864E5;null!=b.currentTime&&(c.currentTime=b.currentTime);null!=b.initialFocusTime&&(c.Znb=b.initialFocusTime);c.orientation="horizontal";null!=b.orientation&&(c.orientation=b.orientation);c.ARa=b.featuresOff;c.jwa=b.minimumWindowSize;c.Sob=b.leftMargin;c.arb=b.rightMargin;if(null!=b.viewportEndTime){var f=b.viewportEndTime,h=c.start;null!=b.viewportStartTime&&b.viewportStartTime<f&&(h=b.viewportStartTime);
c.width=null!=b.viewportEndPos?this.KQa(c.start,c.end,h,f,b.viewportEndPos):this.KQa(c.start,c.end,h,f,this.ha.xb);c.Ywa=h}else c.Ywa=c.start;0==c.width&&(c.width=1E3);c.vVa="below";c.TR="none";c.Xva=a.B.da(this.ha.u()).toString();null!=b.rtl&&(c.Xva=b.rtl.toString());c.sva="#FFFFFF";c.vva="#B3C6DB";c.Vxa="#FFFFFF";c.eXa=1;c.cya="solid";c.aya="solid";c.Xxa="solid";c.Zxa="solid";c.bya="#4F4F4F";c.$xa="#4F4F4F";c.Wxa="#4F4F4F";c.Yxa="#4F4F4F";c.twa="#E6ECF3";c.eta="#C000D1";c.Hxa="#BCC7D2";c.UWa="#e5e5e5";
c.VWa=1;c.XUa="#FFFFFF";c.WUa=.7;c.ZVa="#FFFFFF";c.YVa=.7;null!=b.style&&(null!=b.style.handleFillColor&&(c.sva=b.style.handleFillColor),null!=b.style.handleTextureColor&&(c.vva=b.style.handleTextureColor),null!=b.style.handleBackgroundImage&&(c.YTa=b.style.handleBackgroundImage),null!=b.style.handleWidth&&(c.aUa=b.style.handleWidth),null!=b.style.handleHeight&&(c.ZTa=b.style.handleHeight),null!=b.style.windowBackgroundColor&&(c.Vxa=b.style.windowBackgroundColor),null!=b.style.windowBackgroundAlpha&&
(c.eXa=b.style.windowBackgroundAlpha),null!=b.style.windowBorderTopStyle&&(c.cya=b.style.windowBorderTopStyle),null!=b.style.windowBorderRightStyle&&(c.aya=b.style.windowBorderRightStyle),null!=b.style.windowBorderBottomStyle&&(c.Xxa=b.style.windowBorderBottomStyle),null!=b.style.windowBorderLeftStyle&&(c.Zxa=b.style.windowBorderLeftStyle),null!=b.style.windowBorderTopColor&&(c.bya=b.style.windowBorderTopColor),null!=b.style.windowBorderRightColor&&(c.$xa=b.style.windowBorderRightColor),null!=b.style.windowBorderBottomColor&&
(c.Wxa=b.style.windowBorderBottomColor),null!=b.style.windowBorderLeftColor&&(c.Yxa=b.style.windowBorderLeftColor),null!=b.style.overviewBackgroundColor&&(c.twa=b.style.overviewBackgroundColor),null!=b.style.currentTimeIndicatorColor&&(c.eta=b.style.currentTimeIndicatorColor),null!=b.style.timeIndicatorColor&&(c.Hxa=b.style.timeIndicatorColor),null!=b.style.leftFilterPanelColor&&(c.XUa=b.style.leftFilterPanelColor),null!=b.style.leftFilterPanelAlpha&&(c.WUa=b.style.leftFilterPanelAlpha),null!=b.style.rightFilterPanelColor&&
(c.ZVa=b.style.rightFilterPanelColor),null!=b.style.rightFilterPanelAlpha&&(c.YVa=b.style.rightFilterPanelAlpha));return c};c.prototype.KQa=function(a,b,c,h,k){a=k*(b-a);c=h-c;return 0==a||0==c?0:a/c};a.Qc=function(b){this.Init(a.Qc.xe);this.Ts=b};a.v.D(a.Qc,a.Vg);a.Qc.xe="overview";a.Qc.Eja="dropCallback";a.Qc.IZ="scrollTime";a.Qc.Fja="scrollPos";a.Qc.iDa="scrollEnd";a.Qc.J7="rangeChange";a.Qc.hDa="rangeChanging";a.Qc.FDa="time";a.Qc.pCa="pos";a.Qc.d0a="oldSize";a.Qc.V_a="newSize";a.Qc.e0a="oldStartTime";
a.Qc.YBa="newStartTime";a.Qc.c0a="oldEndTime";a.Qc.XBa="newEndTime";a.Qc.hZa="expand";a.Qc.gZa="endHandle";a.Qc.F7=-1;a.Qc.s6=-2;a.Qc.prototype.Zn=function(){return this.Ts};a.Qc.prototype.setTime=function(b){this.dl(a.Qc.FDa,b)};a.Qc.prototype.getTime=function(){return this.Sq(a.Qc.FDa)};a.Qc.prototype.tsb=function(b){this.dl(a.Qc.d0a,b)};a.Qc.prototype.AWa=function(b){this.dl(a.Qc.V_a,b)};a.Qc.prototype.usb=function(b){this.dl(a.Qc.e0a,b)};a.Qc.prototype.Xfa=function(b){this.dl(a.Qc.YBa,b)};a.Qc.prototype.yua=
function(){return this.Sq(a.Qc.YBa)};a.Qc.prototype.rsb=function(b){this.dl(a.Qc.c0a,b)};a.Qc.prototype.Wfa=function(b){this.dl(a.Qc.XBa,b)};a.Qc.prototype.xua=function(){return this.Sq(a.Qc.XBa)};a.Qc.prototype.oWa=function(b){this.dl(a.Qc.hZa,b)};a.Qc.prototype.Srb=function(b){this.dl(a.Qc.gZa,b)};a.Qc.prototype.setPosition=function(b){this.dl(a.Qc.pCa,b)};a.Qc.prototype.ui=function(){return this.Sq(a.Qc.pCa)};a.v.D(b,a.I);b.prototype.Qf=function(c){b.C.Qf.call(this,c);a.Aj.P2(this.ee,this.TP,this.SP,
this.RP,this)};b.prototype.TP=function(b){return a.B.Wa()?this.C1(b):this.z1(b)};b.prototype.SP=function(b){return a.B.Wa()?this.B1(b):this.y1(b)};b.prototype.RP=function(b){return a.B.Wa()?this.A1(b):this.x1(b)};b.prototype.Oi=function(b,c){this.Dm||(this.Dm=this.Aa.nC());return new a.R(b-this.Dm.x,c-this.Dm.y)};b.prototype.z1=function(b){if(b.button!=a.MouseEvent.$ia){var c=this.Oi(b.pageX,b.pageY);a.I.sc(b);this.u().Oe.nG.parentNode.focus();return this.ee.JQ(b,c.x,c.y)}return!1};b.prototype.y1=
function(a){var b=this.Oi(a.pageX,a.pageY);a.stopPropagation();this.ee.S2(a,b.x,b.y);return!0};b.prototype.x1=function(a){a.stopPropagation();this.ee.dI();this.Dm=null};b.prototype.C1=function(a){var b=a.touches;a.stopPropagation();return 1==b.length?(b=this.Oi(b[0].pageX,b[0].pageY),a.preventDefault(),this.ee.JQ(a,b.x,b.y)):!1};b.prototype.B1=function(a){var b=a.touches;1==b.length&&(b=this.Oi(b[0].pageX,b[0].pageY),this.ee.S2(a,b.x,b.y),a.preventDefault());a.stopPropagation()};b.prototype.A1=function(b){this.ee.dI();
a.I.sc(b);this.Dm=null};a.Ia(a,"Overview",a.Db);a.Ia(a.Db.prototype,"render",a.Db.prototype.ta)})(dvt);
  return dvt;
});
