/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(c,d,e,f,h,k,l){b.C.Init.call(this,c.u(),"none"==d?null:d,a.j.mf,e,f,h,k,null,!0,l);this.ij=c}function c(a){this.Init(a)}function d(a,b){this.Init(a,b)}function e(a,b,c,d,f,h,k,l,u,D){e.C.Init.call(this,a.u(),b,c,d,f,null,h,k,l,u,D);this.ij=a}function f(){this.Init({alta:f.lh})}function h(a){this.Init(a.u(),a.dispatchEvent,a);this.ij=a}function k(a){this.ij=a}a.Ii=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Ii,a.Ie);a.Ii.newInstance=function(b,c,d){return new a.Ii(b,c,d)};a.Ii.prototype.Init=
function(b,d,e){a.Ii.C.Init.call(this,b,d,e);this.I=new h(this);this.I.Qf(this);a.B.Wa()||this.I.Xr(new c(this.I));this.Xg=new f;this.dc=[]};a.Ii.prototype.dH=function(b,c){if(!b||!c){var d=l.sp(this,b,c);this.Noa=d;b||(b=d.items?d.QQa*d.ada:0);c||(c=d.items?d.$Va*d.zfa:0)}return new a.yj(b,c)};a.Ii.prototype.ta=function(b,c,d){this.Hj=this.Ea;var e=this.ju,f=this.xb?this.xb:0,h=this.Jb?this.Jb:0;this.I.qe();this.dc=[];this.ju=[];this.Noa=null;this.Vm&&(this.Ea.removeChild(this.Vm),this.Vm=null);
this.fr();this.vf(b);var k=this.u();if(c||d)this.xb=c,this.Jb=d;else if(k.Ob.style.display="block",c=this.dH(),a.K.s5(k,c.a,c.b),d=a.K.Gua(k),c.a==d.a&&c.b!=d.b?(this.Jb=d.b,c=this.dH(null,this.Jb),a.K.s5(k,c.a,this.Jb),this.xb=a.K.Gua(k).a):c.a!=d.a&&c.b==d.b?(this.xb=d.a,c=this.dH(this.xb,null),a.K.s5(k,this.xb,c.b),this.Jb=a.K.Gua(k).b):(this.xb=d.a,this.Jb=d.b),this.xb!=c.a||this.Jb!=c.b)this.Noa=null;this.Ea=new a.la(k);this.A(this.Ea);l.ta(this,this.Ea,new a.Z(0,0,this.xb,this.Jb),this.Noa);
this.Hj?"none"!=this.W.animationOnDataChange&&b&&(b=new a.sq(k,null),b.Io(e,this.ju),this.lc=b.nw()):this.lc=this.s$a();this.lc?(a.K.s5(k,Math.max(f,this.xb),Math.max(h,this.Jb)),this.I.ll(this),this.Vm&&this.Ea.removeChild(this.Vm),this.lc.lg(this.fba,this),this.lc.play()):this.fba()};a.Ii.prototype.vf=function(b){b?this.W=this.Xg.en(b):this.W||(this.W=this.NF());a.B.xj()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange="none");b=this.W.selectionMode;this.Yc="single"==b?new a.Rc(a.Rc.Sy):
"multiple"==b?new a.Rc(a.Rc.Ry):null;this.I.zA(this.Yc)};a.Ii.prototype.fba=function(){this.Hj&&(this.removeChild(this.Hj),this.Hj.xa(),this.Hj=null);this.lc&&(this.I.Qf(this),this.Vm&&this.Ea.A(this.Vm));a.K.s5(this.u(),this.xb,this.Jb);for(var b,c=0;c<this.dc.length&&(b=this.dc[c],"none"==b.Mc());c++);this.I.Su(b);this.Yc&&this.Yc.tt(this.W.selection,this.dc);a.vh.Ve(this.W.highlightedCategories,this.dc,"any"==this.W.highlightMatch);this.hr();this.wn||this.qs();this.lc=null;this.wn=!1};a.Ii.prototype.Twa=
function(a){this.dc=a};a.Ii.prototype.il=function(){return this.dc};a.Ii.prototype.sqb=function(a){this.ju.push(a)};a.Ii.prototype.rqb=function(a){this.Vm=a};a.Ii.prototype.dnb=function(){for(var a=0,b=0;b<this.dc.length;b++)a+=this.dc[b].getCount();return a};a.Ii.prototype.ob=function(){return a.Ta.Pr(this.W.animationDuration)/1E3};a.Ii.prototype.s$a=function(){var b=this.W.animationOnDisplay,c=this.ob(),d=this.u(),e=new a.Z(0,0,this.xb,this.Jb);if(a.pc.isSupported(b))return a.pc.RE(d,b,this.Ea,
e,c);var f=[];if("popIn"==b)for(b=0;b<this.ju.length;b++){var h=this.ju[b];f.push(new a.Ft(d,h,!0,c))}else if("none"!=b){for(b=0;b<this.ju.length;b++){var h=this.ju[b],k=new a.gd(d,h,c),A,u;l.Sb(this)?(A=l.Wva(this)?this.xb:0,u=h.gk(),h.vt(A),k.ja.N(a.G.V,h,h.gk,h.vt,u)):(A=l.Vva(this)?this.Jb:0,u=h.hk(),h.wt(A),k.ja.N(a.G.V,h,h.hk,h.wt,u));f.push(k)}f.push(a.pc.RE(d,a.pc.OC,this.Ea,e,c))}return 0<f.length?new a.Gg(d,f):null};a.Ii.prototype.Ve=function(b){var c=this.F();c.highlightedCategories=a.ac.clone(b);
a.vh.Ve(b,this.il(),"any"==c.highlightMatch)};a.Ii.prototype.select=function(b){this.F().selection=a.ac.clone(b);this.Yc&&this.Yc.tt(b,this.il())};a.Ii.prototype.gm=function(){return a.H.Bf(this.F(),"componentName",a.H.Ha,"PICTOCHART")};a.Ii.prototype.ph=function(){this.rGa||(this.rGa=new k(this));return this.rGa};a.v.D(k,a.Rd);k.prototype.zn=function(a){return(a=this.ij.ab().mb(a))&&a instanceof d?"item["+this.ij.il().indexOf(a)+"]":null};k.prototype.qh=function(b){if(b==a.Rd.lD)return this.RF(this.ij);
var c=b.indexOf("[");return 0<c&&"item"===b.substring(0,c)&&(b=parseInt(b.substring(c+1,b.length-1)),b=this.ij.il()[b])?b.Ua():null};k.prototype.getItem=function(a){if(a=this.ij.il()[a]){var b={};b.color=a.Xl();b.tooltip=a.me();b.id=a.getId();b.name=a.getName();b.count=a.getCount();b.selected=a.wb();return b}return null};k.prototype.pM=function(){return this.ij.il().length};a.v.D(h,a.I);h.prototype.uq=function(b,c,d){b=this.ij.F();"none"!=b.hoverBehavior&&(c=c.Xd?c.Xd():[],b.highlightedCategories=
d?c.slice():null,d=a.Za.GI(b.highlightedCategories,d),c=a.Ta.Pr(b.hoverBehaviorDelay),this.KJ.bg(d,this.ij.il(),c,"any"==b.highlightMatch))};h.prototype.aT=function(a){(a=this.mb(a.target))&&(a.tb&&a.tb()||this.ly(a))};h.prototype.aG=function(a){(a=this.mb(a.target))&&a.tb&&a.tb()&&this.ly(a)};h.prototype.gZ=function(a){(a=this.mb(a.target))&&(a.tb&&a.tb()||this.ly(a))};h.prototype.Sw=function(a){(a=this.mb(a.target))&&(a.tb&&a.tb()||this.ly(a))};h.prototype.wJ=function(a){var b=this.mb(a.target);
b&&b.tb&&b.tb()&&(a.preventDefault(),a.stopPropagation(),this.ly(b))};h.prototype.ly=function(b){b instanceof d&&b.jk()&&this.nl(a.Za.ffa(b.getId()))};a.v.D(f,a.bb);f.lh={animationOnDisplay:"none",animationOnDataChange:"none",animationDuration:750,drilling:"off",hiddenCategories:[],highlightedCategories:[],highlightMatch:"all",hoverBehavior:"none",hoverBehaviorDelay:200,layout:"horizontal",layoutOrigin:"topStart",selection:[],selectionMode:"none",_defaultColor:"#a6acb1",_noneShapeColor:"rgba(255,255,255,0)",
_defaultSize:32,_defaultShape:"rectangle",_gapRatio:.25,_textStyle:new a.j(a.bb.u6+"color: #252525;"),_statusMessageStyle:new a.j(a.bb.u6+"color: #252525;"),_tooltipStyle:new a.j("border-collapse: separate; border-spacing: 1px"),_tooltipLabelStyle:new a.j("color: #666666; padding: 0px 2px"),_tooltipValueStyle:new a.j("color: #333333; padding: 0px 2px")};a.v.D(e,a.Ef);e.prototype.sg=function(b,c){var d=new a.gd(this.u(),this,.75*this.ij.ob()),e=d.ja,f=this.Yk();this.Cm(c.Yk());e.N(a.G.wf,this,this.Yk,
this.Cm,f);c.T(0);b.add(d,1)};e.prototype.Mj=function(b){b.add(new a.Xi(this.u(),this,.5*this.ij.ob()),0)};e.prototype.Ri=function(b){this.T(0);b.add(new a.ih(this.u(),this,.5*this.ij.ob()),2)};e.prototype.Yk=function(){return[this.gk(),this.hk(),this.getWidth(),this.getHeight()]};e.prototype.Cm=function(a){this.vt(a[0]);this.wt(a[1]);this.Xa(a[2]);this.qb(a[3])};a.v.D(d,a.la);d.oB=0;d.prototype.Init=function(b,c){d.C.Init.call(this,b.u(),null,c.id);this.ij=b;this.Pn=c;this.xc=null!=c.id?c.id:null!=
c.name?c.name:"_defaultId"+d.oB;d.oB++;this.lP="none"==c.shape;this.dd=this.Ql=!1;this.dV=new a.R(0,0);(this.tb()||this.jk())&&this.setCursor("pointer");b.ab().lb(this,this)};d.prototype.hSa=function(){var a=this.Pn.columnSpan;return null!=a&&0<=a?a:1};d.prototype.HTa=function(){var a=this.Pn.rowSpan;return null!=a&&0<=a?a:1};d.prototype.getCount=function(){var a=this.Pn.count;return null!=a?Math.max(a,0):1};d.prototype.Mc=function(){return this.Pn.shape||this.ij.F()._defaultShape};d.prototype.ic=
function(){return this.lP?this.ij.F()._noneShapeColor:this.Pn.color||this.ij.F()._defaultColor};d.prototype.Xn=function(){return this.Pn.borderColor};d.prototype.Pg=function(){return this.Pn.borderWidth};d.prototype.Vx=function(){return this.Pn.className};d.prototype.M=function(){return this.Pn.style};d.prototype.e4=function(){return this.Pn.source};d.prototype.ava=function(){return this.Pn.sourceSelected};d.prototype.Zua=function(){return this.Pn.sourceHover};d.prototype.$ua=function(){return this.Pn.sourceHoverSelected};
d.prototype.getName=function(){return this.Pn.name};d.prototype.getId=function(){return this.xc};d.prototype.me=function(){return this.Pn.shortDesc};d.prototype.jk=function(){if(this.lP)return!1;var a=this.Pn.drilling;return a&&"inherit"!=a?"on"==a:"on"==this.ij.F().drilling};d.prototype.kl=function(){return this.tb()&&this.jk()&&!this.lP};d.prototype.ptb=function(){this.cg("img");this.Hr()};d.prototype.Qg=function(){if(this.lP)return"";var b=this.ij.F(),c=this.ij.F().tooltip;if(c=c?c.renderer:null){var b=
this.ij.u().Af(),d={id:this.getId(),name:this.getName(),count:this.getCount(),color:this.ic()};return b.Xx(c,d)}if(null!=this.me())return this.me();c="";(d=this.getName())&&(c=a.Le.HW("td",b._tooltipLabelStyle)+d+"\x3c/td\x3e");d=a.B.da(this.ij.u());b._tooltipLabelStyle.fa(a.j.iG,d?"left":"right");b._tooltipValueStyle.fa(a.j.iG,d?"right":"left");return a.Le.HW("table",b._tooltipStyle)+"\x3ctr\x3e"+c+a.Le.HW("td",b._tooltipValueStyle)+this.Pna()+"\x3c/td\x3e\x3c/tr\x3e\x3c/table\x3e"};d.prototype.Xl=
function(){return this.ic()};d.prototype.Pna=function(){return a.H.Bf(this.ij.F(),"labelCountWithTotal",a.H.Ha,"COUNT_WITH_TOTAL",[this.getCount(),this.ij.dnb()])};d.prototype.tb=function(){return"none"!=this.ij.F().selectionMode&&!this.lP};d.prototype.wb=function(){return this.Ql};d.prototype.kc=function(a){this.Ql=a;this.Hr();for(var c=0;c<this.Rb();c++){var d=this.hb(c);(d instanceof b||d instanceof e)&&d.kc(a)}};d.prototype.qd=function(){for(var a=0;a<this.Rb();a++){var c=this.hb(a);(c instanceof
b||c instanceof e)&&c.qd()}};d.prototype.Nc=function(){for(var a=0;a<this.Rb();a++){var c=this.hb(a);(c instanceof b||c instanceof e)&&c.Nc()}};d.prototype.Qe=function(){return[this]};d.prototype.Ed=function(){var b=[],c=this.ij.F();this.tb()&&b.push(a.H.Bf(c,this.wb()?"stateSelected":"stateUnselected",a.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));this.jk()&&b.push(a.H.Bf(c,"stateDrillable",a.H.Ha,"STATE_DRILLABLE"));c=this.getName();c=null!=this.me()?this.me():null==c?this.Pna():a.H.va(a.H.Ha,
"COLON_SEP_LIST",[c,this.Pna()]);return a.oa.Ik(c,b)};d.prototype.Hr=function(){a.B.kj()||this.Gd("label",this.Ed())};d.prototype.Xd=function(){return this.Pn.categories||[this.getId()]};d.prototype.Fd=function(b){var d=this.ij.ab().Cb;return b.type==a.MouseEvent.Be||d.Nu(b)?this:d.Vi(b)?c.Fd(this.ij,this,b):null};d.prototype.rf=function(a){return this.aa(a)};d.prototype.Jm=function(){return this.Ua()};d.prototype.Sf=function(){this.lP||(this.dd=!0,this.qd())};d.prototype.Qd=function(){this.lP||(this.dd=
!1,this.Nc())};d.prototype.Kd=function(){return this.dd};d.prototype.Qfa=function(a){this.dV=a};d.prototype.Rda=function(){return this.dV};a.v.D(c,a.Cb);c.prototype.iF=function(a){return this.Vi(a)&&!a.ctrlKey};c.prototype.Nu=function(b){return b.keyCode==a.KeyboardEvent.ni&&b.ctrlKey};c.Fd=function(b,d,e,f){var h=b.il();f||(f=d);if("none"==d.Mc()&&d!=f){var k=a.na.kb(h,d);if(0==k||k==h.length-1)return f}var v=l.Wva(b),A=l.Vva(b),u=l.Sb(b),k=d,v=e.keyCode==a.KeyboardEvent.Jf&&v||e.keyCode==a.KeyboardEvent.uf&&
!v||e.keyCode==a.KeyboardEvent.kh&&A||e.keyCode==a.KeyboardEvent.Tf&&!A,u=e.keyCode==a.KeyboardEvent.Jf&&u||e.keyCode==a.KeyboardEvent.uf&&u||e.keyCode==a.KeyboardEvent.kh&&!u||e.keyCode==a.KeyboardEvent.Tf&&!u,v=a.na.kb(h,d)+(v?1:-1);u?k=a.Cb.Fd(d,e,h):v<h.length&&0<=v&&(k=h[v]);"none"==k.Mc()&&(k=k!=d?c.Fd(b,k,e,f):f);return k};c.prototype.mk=function(b){var d=this.yb.jf();return d&&b.keyCode==a.KeyboardEvent.Zi?(this.yb.ly(d),a.I.sc(b),d):c.C.mk.call(this,b)};a.v.D(b,a.za);b.prototype.sg=function(b,
c){var d=new a.gd(this.u(),this,.75*this.ij.ob()),e=d.ja,f=this.fd();this.ra(c.fd().clone());e.N(a.G.po,this,this.fd,this.ra,f);f=this.Yk();this.Cm(c.Yk());e.N(a.G.wf,this,this.Yk,this.Cm,f);c.T(0);b.add(d,1)};b.prototype.Mj=function(b){b.add(new a.Xi(this.u(),this,.5*this.ij.ob()),0)};b.prototype.Ri=function(b){this.T(0);b.add(new a.ih(this.u(),this,.5*this.ij.ob()),2)};b.prototype.Yk=function(){return[this.gk(),this.hk(),this.getWidth(),this.getHeight()]};b.prototype.Cm=function(a){this.vt(a[0]);
this.wt(a[1]);this.Xa(a[2]);this.qb(a[3])};var l={};a.v.D(l,a.v);l.ta=function(c,d,f,h){var k=c.u(),x=new a.Rect(k,f.x,f.y,f.a,f.b);x.Wb();d.A(x);h||(h=l.sp(c,f.a,f.b));if(h.items){c.Twa(h.items);for(var x=c.F()._gapRatio,v=l.Sb(c),A=l.Vva(c),u=l.Wva(c),D=new a.KN,B=0,C=0,z=0,G=0;G<h.items.length;G++){for(var y=h.items[G],E=y.hSa(),M=y.HTa(),S=E*h.ada,O=M*h.zfa,fa=y.getCount(),ga=0,aa=!0,ea;0<fa;){if(E!=B||M!=C)z=0;0==z&&(ea=l.OIa(D,E,M,h.QQa,h.$Va,v));if(null==ea)break;var ia=ea.Vsa*h.ada+S/2,T=
ea.axa*h.zfa+O/2,ia=f.x+(u?f.a-ia:ia),T=f.y+(A?f.b-T:T),Z=Math.min(1-z,fa),W,R,X,U;v?(W=ia-S/2,R=A?T+O*(.5-Z-z):T+O*(z-.5),X=S,U=O*Z):(W=u?ia+S*(.5-Z-z):ia+S*(z-.5),R=T-O/2,X=S*Z,U=O);var L;1==Z?(L=y.getId()+"_"+ga,ga++):L=Math.random();if(y.e4())L=new e(c,ia,T,S,O,y.e4(),y.ava(),y.Zua(),y.$ua(),L+"_I");else{var oa=new a.Rect(k,W,R,X,U);oa.Wb();y.A(oa);L=new b(c,y.Mc(),ia,T,S-h.ada*x,O-h.zfa*x,L+"_S");L.fb(y.ic());L.Vb(y.Xn(),null,y.Pg());L.TX(y.ic());L.Ue(y.Vx());L.fa(y.M())}1>Z&&(oa=new a.Cd,oa.Pe(W,
R,X,U),L.te(oa));aa&&(y.Qfa(new a.R(ia,T)),aa=!1);y.A(L);c.sqb(L);fa-=Z;z=(z+Z)%1}d.A(y);y.ptb();B=E;C=M}}else l.vp(c,d,f)};l.sp=function(b,c,e){var f=b.F(),h=f.items;if(!h)return{};for(var k=a.na.MQ(f.hiddenCategories),v=[],A=0,u=1,D=1,B=0;B<h.length;B++)if(null!=h[B]){var C=new d(b,h[B]);if(!k||!a.na.qX(k,C.Xd())){var z=C.hSa(),G=C.HTa();z>u&&(u=z);G>D&&(D=G);A+=z*G*C.getCount();v.push(C)}}if(0==A)return{};h=f.columnWidth;k=f.rowHeight;c&&e||(h||(h=k?k:f._defaultSize),k||(k=h));b=l.Sb(b);B=f.columnCount;
f=f.rowCount;B||f||(c&&e?b?f=l.eU(Math.sqrt(A*e/c),D):B=l.eU(Math.sqrt(A*c/e),u):c?B=Math.max(Math.floor(c/h),1):e?f=Math.max(Math.floor(e/k),1):b?f=l.eU(Math.sqrt(A),D):B=l.eU(Math.sqrt(A),u));B?f||(f=l.eU(A/B,D)):B=l.eU(A/f,u);c&&e&&(h||(h=k?k:Math.min(c/B,e/f)),k||(k=h));return 0>=B||0>=f||0>=h||0>=k?{}:{items:v,QQa:B,$Va:f,ada:h,zfa:k}};l.eU=function(a,b){return Math.ceil(a/b)*b};l.OIa=function(a,b,c,d,e,f){if(f)return(a=l.OIa(a,c,b,e,d,!1))?{Vsa:a.axa,axa:a.Vsa}:null;for(f=0;f<e-c+1;f++)for(var h=
0;h<d-b+1;h++)if(l.q7a(a,h,f,b,c))return l.Pcb(a,h,f,b,c),{Vsa:h,axa:f};return null};l.q7a=function(a,b,c,d,e){for(var f=0;f<e;f++)for(var h=0;h<d;h++)if(a.get(b+h,c+f))return!1;return!0};l.Pcb=function(a,b,c,d,e){for(var f=0;f<e;f++)for(var h=0;h<d;h++)a.put(b+h,c+f,!0)};l.vp=function(b,c,d){var e=b.F(),f=a.H.Bf(e,"labelNoData",a.H.Ha,"NO_DATA");c=a.Ca.vp(c,f,d.clone(),b.ab(),e._statusMessageStyle);b.rqb(c)};l.Sb=function(a){return"vertical"==a.F().layout};l.Vva=function(a){a=a.F().layoutOrigin;
return"bottomStart"==a||"bottomEnd"==a};l.Wva=function(b){var c=b.F().layoutOrigin,c="topEnd"==c||"bottomEnd"==c;return a.B.da(b.u())?!c:c};a.Ia(a,"PictoChart",a.Ii);a.Ia(a.Ii,"newInstance",a.Ii.newInstance);a.Ia(a.Ii.prototype,"destroy",a.Ii.prototype.xa);a.Ia(a.Ii.prototype,"getAutomation",a.Ii.prototype.ph);a.Ia(a.Ii.prototype,"highlight",a.Ii.prototype.Ve);a.Ia(a.Ii.prototype,"render",a.Ii.prototype.ta);a.Ia(a.Ii.prototype,"select",a.Ii.prototype.select);a.Ia(k.prototype,"getDomElementForSubId",
k.prototype.qh);a.Ia(k.prototype,"getItem",k.prototype.getItem);a.Ia(k.prototype,"getItemCount",k.prototype.pM)})(dvt);
  return dvt;
});
