/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a,b,c){this.Init(a,b,c)}function c(a){this.Init(c.xe);this.Ts=a}function d(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)}function e(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)}a.Wg=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Wg,a.la);a.Wg.n4a=100;a.Wg.d4a=100;a.Wg.prototype.Init=function(b,c,d){a.Wg.C.Init.call(this,b,null,c);this.Ka=d;this.Baa=[];this.dc=[];this.DPa=[];this.cw=0;this.Ola=this.x9=!1;this.Qpa=new a.Z(0,0,0,0);this.fL=new a.Z(0,0,0,0);this.aC=b.Af();this.ipa=a.B.Wa();this.jg=this.WQa(c+
"_cl");this.A(this.jg);this.K_=new a.la(b);this.K_.nb(!1);this.A(this.K_);this.Coa=new a.Rh(b,a.Wg.n4a,this.PZa,this,1);this.WMa=new a.Rh(b,a.Wg.d4a,this.WZa,this,1);this.lna=!1};a.Wg.prototype.o5=function(a){this.cw=a;this.x9||this.ika();this.vZa(a)};a.Wg.prototype.WQa=function(b){b=new a.ia(this.u(),this.Sib(b),this.yib(b),this.Fib(b),null,b);b.Ru(this.fZ,this);this.ipa||b.Ya(a.MouseEvent.Ro,this.DAa,!1,this);b.t5();return b};a.Wg.prototype.Sib=function(b){var c=this.u();b=new a.Rect(c,0,0,this.fL.a,
this.fL.b,b+"_up");b.JC(a.U.aja);b.Wb();b.A(a.Wg.jha(c,b.getWidth(),b.getHeight()));return b};a.Wg.prototype.Fib=function(b){var c=this.u();b=new a.Rect(c,0,0,this.fL.a,this.fL.b,b+"_up");b.JC(a.U.aja);b.Vb(a.U.ub);b.ra(new a.bd(0,[a.U.Yza,a.U.Zza]));b.A(a.Wg.jha(c,b.getWidth(),b.getHeight()));return b};a.Wg.prototype.yib=function(b){var c=this.u();b=new a.Rect(c,0,0,this.fL.a,this.fL.b,b+"_up");b.Vb(a.U.ub);b.ra(new a.bd(0,[a.U.Zza,a.U.Yza]));b.JC(a.U.aja);b.A(a.Wg.jha(c,b.getWidth(),b.getHeight()));
return b};a.Wg.prototype.Nsb=function(a,b,c){this.jg.zF(a);this.jg.sF(c);this.jg.vF(b);this.x9=!0};a.Wg.prototype.aI=function(b,c,d,e,f){b.nb(!1);this.dc.push(b);this.DPa.push(c);c=a.U.Kv(this.u(),d?d:b);var r=this.Qpa;c.a>r.a&&(r.a=c.a,this.fL.a=c.a+16);c.b>r.b&&(r.b=c.b,this.fL.b=c.b);this.Qpa=r;c=null;d&&e&&f&&(c=[],c[a.ia.od]=d,c[a.ia.Yd]=e,c[a.ia.Hd]=f);this.Baa.push(c);this.x9||(this.removeChild(this.jg),this.jg=this.WQa(b.getId()),this.Ib(this.jg,0),this.ika())};a.Wg.prototype.getItem=function(a){return this.dc[a]};
a.Wg.prototype.pM=function(){return this.dc.length};a.Wg.prototype.Uua=function(){var a=this.cw;return 0>a||a>this.dc.length-1?null:this.dc[a]};a.Wg.prototype.vZa=function(b){b=new a.Cp(a.Cp.Aja,b);this.Te(b)};a.Wg.prototype.fZ=function(b){a.I.sc(b);this.Ola&&this.$0a();b=this.u();this.kz=this.Bib();var c=a.U.Kv(b,this.kz);this.A(this.kz);var d=this.jg.aa(),c=a.B.da(b)?-c.a+1*d.a/4:3*d.a/4;this.kz.Ma(c,3*d.b/4);this.jg.nb(!1);this.jg.Wu(!0);this.Te(new a.Cp(a.Cp.B1a));(b=b.Oe)&&(this.ipa?b.Ya(a.TouchEvent.$i,
this.V6,!0,this):b.Ya(a.MouseEvent.So,this.V6,!0,this))};a.Wg.prototype.PZa=function(){this.eia();this.x9||this.ika()};a.Wg.prototype.V6=function(){this.lna=!1;this.WMa.reset();this.WMa.start()};a.Wg.prototype.WZa=function(){this.lna||(this.Coa.reset(),this.Coa.start())};a.Wg.prototype.Bib=function(){function b(a){return{jh:function(a){D.OZa(a)},TF:function(){D.DAa()},Ui:function(){return a}}}for(var c=this.Ka?this.Ka.comboBox:null,d=a.Ta.M(c,a.ua.Dga,0),e=a.Ta.M(c,a.ua.W5,0),f=a.Ta.M(c,a.ua.Jya,
0),r=a.Ta.M(c,a.ua.QXa,0),p=a.Ta.M(c,a.ua.V5,0),w=d,x=this.u(),v,A,u,d=new a.la(x,"__dd"),D=this,B=0;B<this.dc.length;B++)u=this.dc[B],v=a.U.Kv(x,u),A=new a.la(x,"__it"+B),A.Ma(e,w),A.A(u),u.nb(!0),u.setCursor("pointer"),w+=v.b+p,this.yb&&this.yb.lb(u,b(this.DPa[B])),d.A(A);c=a.U.cjb(x,this.Qpa.a+e+r,w+f-p,c);c.A(d);e=a.Ta.M(this.Ka,a.j.ub,null);f=a.Ta.M(this.Ka,a.ua.Cy,1);r=a.Ta.M(this.Ka,a.j.Lb,null);p=a.Ta.M(this.Ka,a.ua.kN,1);c.Vb(e,f);r&&c.fb(r,p);return c};a.Wg.prototype.DAa=function(){a.I.sc()};
a.Wg.prototype.OZa=function(b){this.lna=!0;this.Coa.stop();a.I.sc(b);b=a.Wg.rmb(b.target);var c;if(this.kz&&b){var d=this.kz.hb(0);d&&(c=d.Bi(b))}this.eia();this.o5(c)};a.Wg.rmb=function(b){for(var c,d;b;){if((d=b.getId())&&b instanceof a.la&&"__it"==d.substr(0,4)){c=b;break}b=b.getParent()}return c};a.Wg.prototype.eia=function(){this.kz&&(this.kz.Jc(!1),this.jg.Wu(!1),this.Te(new a.Cp(a.Cp.w1a)),this.Ola=!0);var b=this.u().Oe;b&&(this.ipa?b.jc(a.TouchEvent.$i,this.V6,!0,this):b.jc(a.MouseEvent.So,
this.V6,!0,this));this.jg.nb(!0)};a.Wg.prototype.$0a=function(){this.Ola=!1;this.kz&&(this.kz.Jc(!1),this.kz.getParent().removeChild(this.kz),this.kz=null)};a.Wg.prototype.aa=function(){return null!=this.jg?this.jg.aa():new a.Z(0,0,0,0)};a.Wg.prototype.il=function(){return this.dc};a.Wg.prototype.ika=function(){var b=!0,c=this.cw;this.Baa&&this.Baa.length>c&&(c=this.Baa[c])&&2<c.length&&(this.jg.zF(c[a.ia.od]),this.jg.vF(c[a.ia.Yd]),this.jg.sF(c[a.ia.Hd]),b=!1);b&&(0<this.K_.Rb()&&this.K_.my(0),this.K_.A(this.Uua()))};
a.Wg.jha=function(b,c,d){var e=[];e.push(c-12,d/2-2);e.push(c-4,d/2-2);e.push(c-8,d/2+2);e.push(c-12,d/2-2);b=new a.mi(b,e,null);b.Vb(a.U.ub);b.fb(a.U.ub);b.nb(!1);return b};a.Wg.prototype.mib=function(){this.eia()};a.Wg.prototype.Mfa=function(a){this.yb=a};a.v.D(e,a.Rect);e.prototype.Init=function(b){a.Rect.C.Init.call(this,b)};a.Cp=function(a,b){this.Init(a,b)};a.Cp.xe="comboBoxEvent";a.Cp.Aja="cbItemChange";a.Cp.B1a="cbShowDropdown";a.Cp.w1a="cbHideDropdown";a.v.D(a.Cp,a.v);a.Cp.prototype.Init=
function(b,c){this.type=a.Cp.xe;void 0===c&&(c=-1);this.qY=b;this.fp=c};a.Cp.prototype.kb=function(){return this.fp};d.mCa=50;d.H0a=1E3/d.mCa*2;a.v.D(d,a.la);d.prototype.Init=function(b,c,e,f,n,r){d.C.Init.call(this,b);this.eNa=new a.Rh(b,d.mCa,this.f_a,this);this.aC=b.Af();this.t_=!1;this.Qa=f;this.pba=new a.R(20,20);this.mx=n?n:a.ua.nN;c.A(e);e&&(this.Dr=e,this.Dr.Jc(!1),this.Dr.Ya(a.TouchEvent.$i,this.OAa,!1,this),a.B.Wa()||(this.Dr.Ya(a.MouseEvent.Be,this.OAa,!1,this),this.Dr.Ya(a.MouseEvent.Ro,
this.XZa,!1,this),this.Dr.Ya(a.MouseEvent.So,this.a_a,!1,this),this.Dr.Ya(a.MouseEvent.zj,this.$Za,!1,this),this.Dr.Ya(a.MouseEvent.xi,this.ZZa,!1,this)),this.Dr.Ya(a.MouseEvent.Mt,this.YZa,!1,this));this.Wv=c;this.Wv.Ya(a.TouchEvent.$i,this.PAa,!1,this);a.B.Wa()||(this.Wv.Ya(a.MouseEvent.Be,this.PAa,!1,this),this.Wv.Ya(a.MouseEvent.Ro,this.b_a,!1,this),this.Wv.Ya(a.MouseEvent.So,this.QAa,!1,this),this.Wv.Ya(a.MouseEvent.zj,this.e_a,!1,this),this.Wv.Ya(a.MouseEvent.xi,this.d_a,!1,this),this.Wv.Ya(a.MouseEvent.Mt,
this.c_a,!1,this));this.nE=a.U.Gib(b,r);this.nE.A(this.Wv);this.A(this.nE)};d.prototype.PAa=function(b){a.I.sc(b)};d.prototype.b_a=function(b){a.I.sc(b);this.t_=!0;this.Dr&&this.Dr.Jc(!1);b=this.Qa.OS(b);b=this.Wv.Md(b);this.xra(b.x,b.y,this.Wv.Fm);this.Eqa=new a.R(b.x,b.y);this.eNa.start();this.fNa=0};d.prototype.QAa=function(b){this.t_&&(a.I.sc(b),this.t_=!1,this.Dr&&this.Dr.Jc(!0),this.eNa.stop());this.Wv.nL(b);this.aC.qe()};d.prototype.e_a=function(b){this.Dr&&this.Dr.Jc(!0);this.aC.x5(b.pageX,
b.pageY,a.H.va(a.H.yh,"CONTROL_PANEL_PAN"),b.target)};d.prototype.d_a=function(a){this.QAa(a);this.Dr&&this.Dr.Jc(!1)};d.prototype.c_a=function(b){a.I.sc(b);b=this.Qa.OS(b);b=this.Wv.Md(b);this.t_?(this.xra(b.x,b.y,this.Wv.Fm),this.Eqa=new a.R(b.x,b.y)):this.xra(b.x,b.y,this.Wv.rn)};d.prototype.f_a=function(){if(this.t_){var a=Math.atan2(this.pba.y-this.Eqa.y,this.pba.x-this.Eqa.x),b=Math.cos(a),a=Math.sin(a),c=15;this.fNa++;this.fNa>d.H0a&&(c*=3);this.Qa.Wi(c*b,c*a)}};d.prototype.OAa=function(b){a.I.sc(b);
this.Qa.lga()};d.prototype.XZa=function(b){a.I.sc(b)};d.prototype.a_a=function(b){a.I.sc(b);this.aC.qe()};d.prototype.$Za=function(b){this.aC.x5(b.pageX,b.pageY,a.H.va(a.H.yh,"CONTROL_PANEL_ZOOMANDCENTER"),b.target);this.Dr.Jc(!0);a.I.sc(b)};d.prototype.ZZa=function(b){this.aC.qe();a.I.sc(b)};d.prototype.YZa=function(b){a.I.sc(b)};d.prototype.xra=function(a,b,c){c.zp(Math.atan2(b-this.pba.y,a-this.pba.x)-Math.PI/4)};a.v.D(c,a.Vg);c.xe="dvtPZCPExpand";c.PJ="show";c.kT="hide";c.prototype.Zn=function(){return this.Ts};
a.ua=function(a,b,c){this.Init(a,b,c)};a.v.D(a.ua,a.la);a.ua.XN=1;a.ua.MJ=2;a.ua.nN=16777215;a.ua.Ztb=1;a.ua.dv=16;a.ua.pN=256;a.ua.oN=4097;a.ua.aub=[0,.25,.5,.75,1];a.ua.MXa="controlPanelBehavior";a.ua.kN="backgroundAlpha";a.ua.I5="backgroundHoverAlpha";a.ua.tya="backgroundDragAlpha";a.ua.Cy="borderAlpha";a.ua.x6="borderHoverAlpha";a.ua.vha="borderDragAlpha";a.ua.qN="buttonWidth";a.ua.U5="buttonHeight";a.ua.Kw="openCloseButtonWidth";a.ua.BY="tabSize";a.ua.Dga="paddingTop";a.ua.RXa="paddingSide";
a.ua.Jya="paddingBottom";a.ua.W5="paddingLeft";a.ua.QXa="paddingRight";a.ua.V5="paddingInner";a.ua.AY="panelDrawerStyles";a.ua.PXa="imageWidth";a.ua.OXa="imageHeight";a.ua.NXa="centerButtonDisplayed";a.ua.prototype.Init=function(c,d,e){a.ua.C.Init.call(this,c);this.Mla=this.t9=!1;this.Qa=d.Qa;this.mx=d.PO;this.ys=d.hc();this.aC=c.Af();this.Ka=null;if(this.ha=d)this.Ka=this.ha.vw(),this.Ka[a.ua.NXa]||(this.mx&=~a.ua.dv,this.ha.rF(this.mx));this.Av=!1;this.Bq=this.Ka[a.ua.kN];this.yb=new b(c,null,d);
this.yb.bI(a.ua);this.yb.Qf(this);this.yb.lb(this,this);this.Th=e;this.md()};a.ua.prototype.kwa=function(){this.t9=!0;this.Gb.nb(!1);this.oh.nb(!1);this.Gb.T(this.Ka[a.ua.tya]);this.oh.T(this.Ka[a.ua.vha])};a.ua.prototype.iVa=function(){this.t9=!1;this.Gb.nb(!0);this.oh.nb(!0);this.Mla?this.Hy(null):this.kv(null)};a.ua.prototype.CX=function(){return!0};a.ua.prototype.ww=function(){var b=0,b=this.CX()?a.Wc.Cea():a.Wc.ww(),c=a.Ta.M(this.Ka,a.ua.BY,0);return Math.max(c,b)};a.ua.prototype.mva=function(){return a.Ta.M(this.Ka,
a.ua.BY,0)};a.ua.prototype.OCa=function(){var b=this.u(),c=new a.la(b),d=this.ww(),e=a.B.da(b);this.Gb=a.Wc.aRa(b,d,this.Ka,e);this.oh=a.Wc.$sa(b,d,this.Ka,e);this.r8a=a.U.Kv(b,this.oh);this.De=a.U.eda(this.u(),this.ys,this.ww(),this.Ka,e?a.U.ho:a.U.HA);this.De.Ru(this.fZ,this);this.De.tn(a.H.va(a.H.yh,"CONTROL_PANEL"));this.yb.lb(this.De,this.De);this.oh.A(this.De);c.A(this.Gb);c.A(this.oh);return c};a.ua.prototype.N6a=function(b,c){if(0!=(this.mx&a.ua.pN)){var d=a.Ta.M(this.Ka.vbar,a.ua.V5,0),e=
a.Ta.M(this.Ka.vbar,a.ua.W5,0);this.Rz=a.U.Vib(this.u(),this.ys,this.Ka);this.Rz.Ma(e,this.Rz.pa()+c);this.Rz.Ru(this.k_a,this);this.Rz.tn(a.H.va(a.H.yh,"CONTROL_PANEL_ZOOMTOFIT"));this.yb.lb(this.Rz,this.Rz);e=a.U.Kv(this.u(),this.Rz);b.A(this.Rz);c+=e.b;c+=d}return c};a.ua.prototype.M6a=function(b,c){var d=a.Ta.M(this.Ka.vbar,a.ua.V5,0),e=a.Ta.M(this.Ka.vbar,a.ua.W5,0);if(0!=(this.mx&a.ua.oN)){this.Au=a.U.Tib(this.u(),this.ys,this.Ka);this.Au.Ma(e,this.Au.pa()+c);this.Au.Ru(this.iZ,this);this.Au.tn(a.H.va(a.H.yh,
"CONTROL_PANEL_ZOOMIN"));this.yb.lb(this.Au,this.Au);var f=a.U.Kv(this.u(),this.Au);b.A(this.Au);c+=f.b+d;this.Bu=a.U.Uib(this.u(),this.ys,this.Ka);this.Bu.Ma(e,this.Bu.pa()+c);this.Bu.Ru(this.jZ,this);this.Bu.tn(a.H.va(a.H.yh,"CONTROL_PANEL_ZOOMOUT"));this.yb.lb(this.Bu,this.Bu);f=a.U.Kv(this.u(),this.Bu);b.A(this.Bu);c+=f.b;this.tjb()}return c};a.ua.prototype.k9a=function(b,c,d,e){var f=this.u();if(c){var r=c.Rb(),r=1<r||null==this.Rz||1<d||0<d&&1==r,p=null;this.Ka&&this.Ka[a.ua.AY]&&(p=0<d?a.Wc.zia:
a.Wc.yia);b=a.U.Kv(f,b);e+=4;e=r?e:Math.max(b.b,e);b=a.Ta.M(this.Ka.vbar,a.ua.Jya,0);e+=b;b=a.Wc.Iqb(f,e,this.Ka,p,this.ww());f=a.Wc.Hqb(f,e,r,this.Ka,p,this.ww());b.Ma(c.qa(),c.pa());this.Gb.A(b);c.Ib(f,0)}};a.ua.prototype.Ldb=function(b,c){var d=this.u(),e=a.B.da(d),f=a.Ta.M(this.Ka,a.ua.Kw,0);this.YA||0!=(this.mx&a.ua.dv)?e&&c&&(d=a.U.Kv(d,b),e=this.mva(),b.ga(0),c.ga(d.a+d.x-e)):e?(b.ga(0-b.qa()),b.wa(0),c&&(b.ga(b.qa()-f),c.wa(0))):c?(d=this.mva(),c.Ma(0,0),b.Ma(b.qa()+d,0)):b.Ma(b.qa(),0)};
a.ua.prototype.V8a=function(b){var c=0,d=this.u(),e=this.CX();0!=(this.mx&a.ua.dv)&&(this.nE=a.U.Hib(d,this.Qa,this.mx,this.ys,this.Ka),e&&(this.DH=a.U.hRa(d,this.Ka),this.K1=a.U.hRa(d,this.Ka),b.A(this.K1),b.A(this.DH)),b.A(this.nE),c++);return c};a.ua.prototype.S8a=function(b,c){this.YA=new a.la(this.u());this.DZ(this.YA);0<this.YA.Rb()?(b.A(this.YA),c++):this.YA=null;return c};a.ua.prototype.U8a=function(b){this.Kn=a.U.cda(this.u(),this.ys,this.ww(),this.Ka,a.B.da(this.u())?a.U.ho:a.U.HA);this.Kn.Ru(this.Tha,
this);this.Kn.tn(a.H.va(a.H.yh,"CONTROL_PANEL"));this.yb.lb(this.Kn,this.Kn);b.A(this.Kn)};a.ua.prototype.Fdb=function(b,c){var d=this.Aa,e=null,f=a.Ta.M(this.Ka,a.ua.Kw,0),r=a.Ta.M(this.Ka,a.ua.qN,0),p=this.mva(),w=this.ww(),x=a.Ta.M(this.Ka.hbar,a.ua.W5,0),v=a.Ta.M(this.Ka.hbar,a.ua.V5,0);b?(this.Kn.ga(0),c+=f,this.YA&&(e=a.U.Kv(d,this.YA),c+=v,this.YA.Ma(c,(w-e.b)/2),c+=Math.max(e.a,r)),this.nE&&(c+=v,e=3.5,this.nE.Ma(c,e),this.DH&&this.DH.Ma(c,e),this.K1&&this.K1.Ma(c,e),e=a.U.Kv(d,this.nE),c+=
e.a),c+=x):(this.nE&&(c+=x,e=3.5,this.nE.Ma(x,e),this.DH&&this.DH.Ma(x,e),this.K1&&this.K1.Ma(x,e),e=a.U.Kv(d,this.nE),c+=v+e.a,c+=1),this.YA&&(e=a.U.Kv(d,this.YA),0==c&&(c+=x),this.YA.Ma(c,(w-e.b)/2),c+=e.a,c=Math.max(c+v,p)),this.Kn.ga(c),c+=f);return c};a.ua.prototype.T8a=function(b,c,d,e,f){var r=this.Aa,p=a.Ta.M(this.Ka,a.ua.Kw,0),w=a.Ta.M(this.Ka,a.ua.BY,0),x=a.Ta.M(this.Ka,a.ua.AY,null);f=x?f:f-p;var v=this.ww(),A=0,u=0;x?x&&0==d&&(u=e?-w:w):(A=e?p:0,u=e?p:0);if(0<d||x){var D=p=null,D=parseInt(a.Ta.M(this.Ka,
a.j.dg,0));x?(c=0<d&&null!=c?a.Wc.wia:a.Wc.xia,p=a.Wc.eVa(r,D,f,v,c,w),D=a.Wc.eVa(r,D,f,v,c,w)):(p=a.Wc.bRa(r,f,this.ww(),!e,this.Ka),D=a.Wc.bRa(r,f,this.ww(),!e,this.Ka));p.Vb(a.Ta.M(this.Ka,a.j.ub,null));p.ra(null);p.Ma(b.qa()+A,b.pa());b.Ib(p,0);D.fb(a.Ta.M(this.Ka,a.j.Lb,null));D.Ma(b.qa()+u,b.pa());this.Gb.A(D)}};a.ua.prototype.QCa=function(){var b=this.u(),c=new a.la(b);this.Gb=new a.la(b);this.oh=new a.la(b);c.A(this.Gb);c.A(this.oh);var d=a.B.da(b),e=0,f=new a.la(b),r;r=this.V8a(f);this.U8a(f);
r=this.S8a(f,r);var e=this.Fdb(d,e),p=null,w=this.Wab(r);this.CX()&&0!=(this.mx&a.ua.dv)&&(w+=a.Wc.ww()-this.ww());if(0!=(this.mx&a.ua.pN)||0!=(this.mx&a.ua.oN))p=new a.la(b),p.wa(f.pa()+this.ww()),w=this.N6a(p,w),w=this.M6a(p,w),this.oh.A(p);this.T8a(f,p,r,d,e);this.oh.A(f);this.Ldb(f,p);this.k9a(f,p,r,w);this.S9a=a.U.Kv(b,c);return c};a.ua.prototype.DZ=function(){};a.ua.prototype.A5=function(){this.Av||(this.Th===a.ua.MJ?this.QO():this.Th===a.ua.XN&&this.a0())};a.ua.prototype.fZ=function(b){a.I.sc(b);
this.Av||(this.a0(),this.aC.qe())};a.ua.prototype.a0=function(){this.Av=!0;this.nb(!1);var a=this.QCa();this.A(a);this.gGa();this.ltb(this.hb(0),a);this.Ajb()};a.ua.prototype.gGa=function(){var a=!1;this.u().Oe&&(a=!0);a?this.iGa():this.hGa()};a.ua.prototype.Tha=function(b){a.I.sc(b);this.Av||this.QO()};a.ua.prototype.QO=function(){this.Av=!0;var a=this.OCa();this.A(a);this.gGa();this.ktb(this.hb(0),a);this.zjb()};a.ua.prototype.ltb=function(b,c){var d=b.aa(),e=a.Ta.M(this.Ka,a.ua.Kw,0);if(d&&0!=
d.a){var f=c.aa(),r=new a.G(this.u(),.25);b.T(1);c.T(0);r.N(a.G.V,b,b.Ra,b.T,0);r.N(a.G.V,c,c.Ra,c.T,1);c.uh(d.a/f.a);r.N(a.G.V,c,c.oe,c.uh,1);if(a.B.da(this.u())){c.ga(b.qa());var p=f.a+f.x;r.N(a.G.V,c,c.qa,c.ga,b.qa()+e-p)}c.gh(d.b/f.b);r.N(a.G.V,c,c.Ae,c.gh,1);r.lg(function(){b.getParent().removeChild(b);this.Av=!1;this.nb(!0);this.Th=a.ua.MJ},this);r.play()}else this.Th=a.ua.MJ,b.getParent().removeChild(b),this.vCa(c)};a.ua.prototype.vCa=function(b){var c;if(a.B.da(this.u())){c=a.Ta.M(this.Ka,
a.ua.Kw,0);var d=a.Mh.jn(this.u(),b);c-=Math.floor(d.a+d.x)}else c=0;b.Ma(c,0)};a.ua.prototype.ktb=function(b,c){var d=new a.G(this.u(),.25);b.T(1);c.T(0);d.N(a.G.V,b,b.Ra,b.T,0);d.N(a.G.V,c,c.Ra,c.T,1);var e=this.r8a,f=this.S9a;d.N(a.G.V,b,b.oe,b.uh,e.a/f.a);a.B.da(this.u())&&d.N(a.G.V,b,b.qa,b.ga,c.qa());d.N(a.G.V,b,b.Ae,b.gh,e.b/f.b);d.lg(function(){b.getParent().removeChild(b);this.Av=!1;this.Th=a.ua.XN},this);d.play()};a.ua.prototype.Ajb=function(){var a=new c(c.PJ);this.Te(a)};a.ua.prototype.zjb=
function(){var a=new c(c.kT);this.Te(a)};a.ua.prototype.Hy=function(){this.Mla=!0;this.t9||this.iGa()};a.ua.prototype.kv=function(){this.Mla=!1;this.t9||this.hGa()};a.ua.prototype.iGa=function(){this.Gb.T(this.Ka[a.ua.I5]);this.oh.T(this.Ka[a.ua.x6]);this.DH&&this.DH.T(this.Ka[a.ua.I5])};a.ua.prototype.hGa=function(){this.Gb.T(this.Bq);this.oh.T(this.Ka[a.ua.Cy]);this.DH&&this.DH.T(this.Bq)};a.ua.prototype.aa=function(){this.du||(this.du=a.ua.C.aa.call(this));return this.du};a.ua.prototype.Dw=function(){var b;
this.Th==a.ua.XN?b=this.OCa():(b=this.QCa(),this.vCa(b));this.Gb.T(this.Bq);this.oh.T(this.Ka[a.ua.Cy]);this.A(b)};a.ua.prototype.Tx=function(){return this.ys};a.ua.prototype.Wab=function(b){return this.mx&a.ua.dv||this.Ka&&this.Ka[a.ua.AY]&&0==b?a.Ta.M(this.Ka.vbar,a.ua.Dga,0):0};a.ua.prototype.tjb=function(){var a=this.Qa.wg(),b=this.Qa.jTa(a),c=this.Qa.zTa(a);this.Au&&this.Au.sn(a!=b);this.Bu&&this.Bu.sn(a!=c)};a.ua.prototype.pda=function(a){this.Au&&this.Au.sn(a)};a.ua.prototype.qda=function(a){this.Bu&&
this.Bu.sn(a)};a.ua.prototype.iZ=function(){var b=this.Qa.wg(),b=this.Qa.jTa(b),c=new a.G(this.u(),this.Qa.ob());this.Qa.Ct(b,void 0,void 0,c);c.play()};a.ua.prototype.jZ=function(){var b=this.Qa.wg(),b=this.Qa.zTa(b),c=new a.G(this.u(),this.Qa.ob());this.Qa.Ct(b,void 0,void 0,c);c.play()};a.ua.prototype.k_a=function(){var b=new a.G(this.u(),this.Qa.ob());this.Qa.Dt(b);b.play()};a.ua.prototype.ab=function(){return this.yb};a.ua.prototype.Ab=function(){return this.Th==a.ua.MJ};a.ua.prototype.mw=function(a){if("disclosure"==
a)return this.Ab()?this.Kn:this.De;if(this.Ab()){if("zoomToFit"==a&&this.Rz&&this.Rz.isEnabled())return this.Rz;if("zoomIn"==a&&this.Au&&this.Au.isEnabled())return this.Au;if("zoomOut"==a&&this.Bu&&this.Bu.isEnabled())return this.Bu}return null};var f={};a.v.D(f,a.v);f.mf={"fill-type":"solid",backgroundAlpha:1,backgroundDragAlpha:1,borderDragAlpha:1,panelDrawerStyles:!0,buttonWidth:42,buttonHeight:42,buttonRadius:0,openCloseButtonWidth:42,tabSize:42,paddingTop:15,paddingSide:-1,imageWidth:24,imageHeight:24,
centerButtonDisplayed:!1,scrollbarBackground:"linear-gradient(bottom, #dce2e7 0%, #f8f8f8 8%)",scrollbarBorderColor:"#dce2e7",scrollbarHandleColor:"#abb0b4",scrollbarHandleHoverColor:"#333333",scrollbarHandleActiveColor:"#333333",comboBox:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0,itemHeight:30,imagePadding:0,itemPadding:10},vbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,paddingInner:0},hbar:{paddingTop:0,paddingBottom:0,paddingLeft:0,paddingRight:0,
paddingInner:0}};f.Hg={"fill-type":"solid"};f.DEFAULT={"fill-type":"gradient","border-color":"#ffffff","background-color":"#ffffff","border-radius":6,backgroundAlpha:.5,backgroundHoverAlpha:1,backgroundDragAlpha:.5,borderAlpha:1,borderHoverAlpha:1,borderDragAlpha:.5,tabSize:26,buttonWidth:22,buttonHeight:22,buttonRadius:3,paddingTop:5,paddingSide:5,imageWidth:22,imageHeight:20,openCloseButtonWidth:10,centerButtonDisplayed:!0,comboBox:{paddingTop:2,paddingBottom:6,paddingLeft:3,paddingRight:3,paddingInner:2,
itemHeight:22,radius:4,imagePadding:2,itemPadding:7},vbar:{paddingTop:2.5,paddingBottom:2.5,paddingLeft:2,paddingRight:2,paddingInner:2},hbar:{paddingTop:2,paddingBottom:2,paddingLeft:3,paddingRight:3,paddingInner:2}};f.en=function(b){var c=f.Sna(b);return b?a.ac.Vd(b,c):c};f.Sna=function(b){var c=null;return c=b&&"skyros"===b.skin?a.ac.Vd(f.Hg,f.DEFAULT):b&&"alta"===b.skin?a.ac.Vd(f.mf,f.DEFAULT):a.ac.clone(f.DEFAULT)};a.v.D(b,a.I);b.prototype.mo=function(a){var c=this.mb(this.ne(a));b.C.mo.call(this,
a);c&&(c.TF&&c.TF(a),a.stopPropagation())};b.prototype.Uo=function(a){var c=this.mb(this.ne(a));b.C.Uo.call(this,a);c&&(c.TS&&c.TS(),a.stopPropagation())};b.prototype.To=function(a){var c=this.mb(this.ne(a));b.C.To.call(this,a);c&&(c.R6&&c.R6(),a.stopPropagation())};b.prototype.Tj=function(a){var c=this.mb(this.ne(a));b.C.Tj.call(this,a);c&&(c.jh&&c.jh(a),a.stopPropagation())};b.prototype.cG=function(a){b.C.cG.call(this,a);var c=this.mb(this.ne(a));c&&c.Hy&&c.Hy(a)};b.prototype.bG=function(a){b.C.bG.call(this,
a);var c=this.mb(this.ne(a));c&&c.kv&&c.kv(a)};b.prototype.CJ=function(a){var b=this.mb(this.ne(a));b&&(b.jh&&b.jh(a),a.stopPropagation())};b.prototype.RS=function(b){b.$L();a.I.sc(b)};a.Wc={};a.v.D(a.Wc,a.v);a.Wc.zia="top";a.Wc.yia="right";a.Wc.xia="left";a.Wc.wia="bottom";a.Wc.ZDa=47;a.Wc.YDa=26;a.Wc.xh=Math.sin(Math.PI/4);a.Wc.zh=Math.tan(Math.PI/8);a.Wc.ww=function(){return a.Wc.ZDa};a.Wc.Cea=function(){return a.Wc.YDa};a.Wc.bRa=function(b,c,d,e,f){c||(c=86);d||(d=47);void 0===e&&(e=!0);f=parseInt(a.Ta.M(f,
a.j.dg,0));return a.Wc.cpb(b,f,c-2*f,d-2*f,e)};a.Wc.cpb=function(b,c,d,e,f){var r=d+c,p=e+c,w=a.P.moveTo(r+c,p+c),w=w+a.P.lineTo(r-d,p+c),r=r-d,w=w+a.P.lineTo(r-c,p+c),w=w+a.P.lineTo(r-c,p-e),p=p-e;f?(w+=a.P.We(-c+r,-a.Wc.zh*c+p,-a.Wc.xh*c+r,-a.Wc.xh*c+p)+a.P.We(-a.Wc.zh*c+r,-c+p,r,-c+p)+a.P.lineTo(r,-c+p),w+=a.P.lineTo(r+d+c,-c+p),w+=a.P.lineTo(r+d+c,p+e)):(w+=a.P.lineTo(r-c,-c+p),w+=a.P.lineTo(r+d,-c+p),r+=d,w+=a.P.We(a.Wc.zh*c+r,-c+p,a.Wc.xh*c+r,-a.Wc.xh*c+p)+a.P.We(c+r,-a.Wc.zh*c+p,c+r,p)+a.P.lineTo(r+
c,p+e));w+=a.P.closePath();return new a.vb(b,w)};a.Wc.aRa=function(b,c,d,e){c||(c=47);var f=parseInt(a.Ta.M(d,a.j.dg,0)),r=a.Ta.M(d,a.ua.Kw,0);c=Math.max(c,a.Ta.M(d,a.ua.U5,c));e=a.U.yha(r,c,f,e);e=e.concat("Z");b=new a.vb(b,e,"cls_shape");(e=a.Ta.M(d,a.ea.U7,null))||(e=a.Ta.M(d,a.j.Lb,null));b.fb(e);return b};a.Wc.$sa=function(b,c,d,e){c||(c=47);var f=parseInt(a.Ta.M(d,a.j.dg,0)),r=a.Ta.M(d,a.ua.Kw,0);c=Math.max(c,a.Ta.M(d,a.ua.U5,c));e=a.U.yha(r,c,f,e);e=e.concat("Z");b=new a.vb(b,e,"cls_shape");
b.Vb(a.Ta.M(d,a.j.ub,null));b.ra(null);return b};a.Wc.Iqb=function(b,c,d,e,f){c||(c=137);var r=parseInt(a.Ta.M(d,a.j.dg,0)),p=a.Ta.M(d,a.ua.BY,0),w=p-2*r,x=c+7-2*r;b=e&&f?a.Wc.gVa(b,r,p,c,e,f):a.Wc.fVa(b,r,w,x);b.fb(a.Ta.M(d,a.j.Lb,null));return b};a.Wc.Hqb=function(b,c,d,e,f,r){c||(c=137);d||(d=!0);var p=parseInt(a.Ta.M(e,a.j.dg,0)),w=a.Ta.M(e,a.ua.BY,0),x=w-2*p,v=c+7-2*p,A=null,A=f&&r?a.Wc.gVa(b,p,w,c,f,r):a.Wc.fVa(b,p,x,v,d);A.Vb(a.Ta.M(e,a.j.ub,null));A.ra(null);return A};a.Wc.fVa=function(b,
c,d,e,f){f||(f=!0);var r=d+c,p=e,w=a.P.moveTo(r+c,p),w=f?w+(a.P.We(c+r,a.Wc.zh*c+p,a.Wc.xh*c+r,a.Wc.xh*c+p)+a.P.We(a.Wc.zh*c+r,c+p,r,c+p)+a.P.lineTo(r,c+p)):w+a.P.lineTo(r+c,p+c),w=w+a.P.lineTo(r-d,c+p),r=r-d,w=w+(a.P.We(-a.Wc.zh*c+r,c+p,-a.Wc.xh*c+r,a.Wc.xh*c+p)+a.P.We(-c+r,a.Wc.zh*c+p,-c+r,p)+a.P.lineTo(-c+r,p)+a.P.lineTo(-c+r,p-e)),p=p-e,w=w+(a.P.lineTo(r+d+c,p)+a.P.lineTo(r+d+c,p+e)+a.P.closePath());return new a.vb(b,w)};a.Wc.gVa=function(b,c,d,e,f,r){c=a.Wc.wAa(b,d,e,c,f,r);return new a.vb(b,
c)};a.Wc.eVa=function(b,c,d,e,f,r){c=a.Wc.wAa(b,d,e,c,f,r);return new a.vb(b,c)};a.Wc.wAa=function(b,c,d,e,f,r){var p;b=a.B.da(b);f!=a.Wc.zia||b||(p=["M",c,0,"L",c,d-e,"A",e,e,0,0,1,c-e,d,"L",0,d,"L",0,0]);f==a.Wc.zia&&b?p=["M",c,0,"L",c,d,"L",e,d,"A",e,e,0,0,1,0,d-e,"L",0,0]:f!=a.Wc.yia||b?f==a.Wc.yia&&b?p=["M",0,0,"L",c,0,"L",c,d,"L",e,d,"A",e,e,0,0,1,0,d-e,"L",0,r]:f!=a.Wc.xia||b?f==a.Wc.xia&&b?p=["M",c,d,"L",e,d,"A",e,e,0,0,1,0,d-e,"L",0,e,"A",e,e,0,0,1,e,0,"L",c,0]:f!=a.Wc.wia||b?f==a.Wc.wia&&
b&&(p=["M",c,d,"L",c,0,"L",e,0,"A",e,e,0,0,0,0,e,"L",0,d-e,"A",e,e,0,0,0,e,d,"L",c-r,d]):p=["M",0,d,"L",0,0,"L",c-e,0,"A",e,e,0,0,1,c,e,"L",c,d-e,"A",e,e,0,0,1,c-e,d,"L",r,d]:p=["M",0,0,"L",c-e,0,"A",e,e,0,0,1,c,e,"L",c,d-e,"A",e,e,0,0,1,c-e,d,"L",0,d]:p=["M",c,r,"L",c,d-e,"A",e,e,0,0,1,c-e,d,"L",0,d,"L",0,0,"L",c,0];return p};a.fc=function(a,b,c){this.Init(a,b,c)};a.v.D(a.fc,a.Ie);a.fc.L5="box-shadow";a.fc.gJ="initCollapsed";a.fc.Aga="initExpanded";a.fc.GF="hidden";a.fc.I0a="panZoomInfo";a.fc.iT=
"skin";a.fc.rEa="inlineStyle";a.fc.nEa="cpBackgroundColor";a.fc.oEa="cpBorderColor";a.fc.qEa="cpBoxShadow";a.fc.pEa="cpBorderRadius";a.fc.sEa="tabBgColorInactive";a.fc.tEa="tabBorderColorInactive";a.fc.CBa="isLegendDisclosed";a.fc.prototype.Init=function(b,c,d){a.fc.C.Init.call(this,b,c,d);this.sHa=a.fc.gJ;this.PO=a.rd.xYa;this.Cj=!a.B.zw()&&!(a.B.ae()&&11>=a.B.wI());this.kPa=this.mra=null;this.ke=""};a.fc.prototype.hc=function(){this.mra||(this.mra=this.W?this.W._resources:{});return this.mra};a.fc.prototype.vw=
function(){return this.kPa};a.fc.prototype.wwa=function(b){var c=(new a.j(b[a.fc.rEa])).M(a.j.Lb);c&&this.sDa(c);var c={},d=b[a.fc.iT];d&&(this.ROa(d),c[a.fc.iT]=d,"undefined"!=typeof a.ea&&(a.Ta.fa(c,a.j.Lb,b[a.fc.nEa]),a.Ta.fa(c,a.j.ub,b[a.fc.oEa]),a.Ta.fa(c,a.j.dg,b[a.fc.pEa]),a.Ta.fa(c,a.fc.L5,b[a.fc.qEa]),a.Ta.fa(c,a.ea.U7,b[a.fc.sEa]),a.Ta.fa(c,a.ea.Oja,b[a.fc.tEa])),this.bga(f.en(c)))};a.fc.prototype.Mpb=function(b){var c=(new a.j(b.X(a.fc.rEa))).M(a.j.Lb);c&&this.sDa(c);var c={},d=b.X(a.fc.iT);
d&&(this.ROa(d),c[a.fc.iT]=d);"undefined"!=typeof a.ea&&(a.Ta.fa(c,a.j.Lb,b.X(a.fc.nEa)),a.Ta.fa(c,a.j.ub,b.X(a.fc.oEa)),a.Ta.fa(c,a.j.dg,b.X(a.fc.pEa)),a.Ta.fa(c,a.fc.L5,b.X(a.fc.qEa)),a.Ta.fa(c,a.ea.U7,b.X(a.fc.sEa)),a.Ta.fa(c,a.ea.Oja,b.X(a.fc.tEa)));this.bga(f.en(c))};a.fc.prototype.ta=function(a,b,c){this.xb=b;this.Jb=c;this.Ks=!a;if(!this.Ks||this.Qa)this.fT(),this.Ks||("object"==typeof a?this.vf(a):this.zcb(a)),this.Fn(a,b,c),this.hr()};a.fc.prototype.Ifa=function(a){this.sHa=a};a.fc.prototype.rF=
function(a){this.PO=a};a.fc.prototype.B6=function(){var b=this.rJ();return b!=a.fc.GF?new a.ua(this.u(),this,b==a.fc.gJ?a.ua.XN:a.ua.MJ):null};a.fc.prototype.rJ=function(){return this.sHa};a.fc.prototype.cZ=function(){return null};a.fc.prototype.KZa=function(){return new a.fO(this.u())};a.fc.prototype.$C=function(){};a.fc.prototype.uk=function(){};a.fc.prototype.fT=function(){};a.fc.prototype.Fn=function(){if(this.yIa||!this.ke)this.ED||(this.ED=new a.Rect(this.u(),0,0,0,0),this.A(this.ED)),this.ED.Xa(this.getWidth()),
this.ED.qb(this.getHeight()),this.ED.ra(this.w$a(this.yIa));if(this.Ks)this.Qa.Vu(this.getWidth(),this.getHeight());else{this.Qa&&(this.removeChild(this.Qa),this.Qa=null);this.Qa=new a.rd(this.u(),this.getWidth(),this.getHeight(),this);this.Qa.Ya(a.wh.xe,this.$C,!1,this);this.Qa.Ya(a.xd.xe,this.uk,!1,this);this.A(this.Qa);var b=this.B6();b&&(b.Ya(c.xe,this.dbb,!1,this),this.Qa.Grb(b));this.Qa.Dw()}b=new a.Cd("comp");b.Pe(this.qa(),this.pa(),this.getWidth(),this.getHeight());this.te(b)};a.fc.prototype.sDa=
function(a){this.yIa=a};a.fc.prototype.vf=function(a){this.W=this.Xg?this.Xg.en(a):a};a.fc.prototype.w$a=function(b){var c=1;if(b&&"#7396C8"!=b){var c=a.O.Ra(b),d=(a.O.Ug("#AECDEA")-a.O.Ug("#7396C8"))/(255-a.O.Ug("#7396C8")),e=(a.O.Rg("#AECDEA")-a.O.Rg("#7396C8"))/(255-a.O.Rg("#7396C8")),f=(a.O.Og("#AECDEA")-a.O.Og("#7396C8"))/(255-a.O.Og("#7396C8")),r=a.O.Ug(b),p=a.O.Rg(b),w=a.O.Og(b),d=a.O.DI(Math.round(r+d*(255-r)),Math.round(p+e*(255-p)),Math.round(w+f*(255-w)));b=a.O.Or(b);b=["#FFFFFF","#FFFFFF",
d,b]}else b=["#FFFFFF","#FFFFFF","#AECDEA","#7396C8"];f=this.xb;d=1.7*f*1.7;e=1.7*this.Jb;f=0+(f-d)/2;return new a.Vo(b,[c,c,c,c],[0,45/255,190/255,1],f+d/2,-35+e/2,1.5*Math.min(d/2,e/2),[f,-35,d,e])};a.fc.prototype.dbb=function(b){b=a.Za.am(a.ua.MXa,b.Zn()==c.PJ?a.fc.Aga:a.fc.gJ);this.dispatchEvent(b)};a.fc.prototype.zcb=function(a){if(null!=a&&0!=a.length){var b=this.KZa();b&&(a=b.parse(a))&&("r"===a.getName()&&(a=a.getFirstChild()),a&&this.cZ().cVa(a))}};a.fc.prototype.ROa=function(a){this.ke=
a};a.fc.prototype.bga=function(a){this.kPa=a};a.fc.prototype.lab=function(b,c){var d=c;if(!b)return d;d=a.Nd.trim(b);a.Nd.endsWith(d,"%")?(d=a.Nd.trim(d.replace(/\%$/,"")),isNaN(parseFloat(d))||(d=parseFloat(d)/100*c)):a.Nd.endsWith(d,"px")&&(d=d.replace(/px$/,""));d=isNaN(parseFloat(d))?c:parseFloat(d);return Math.min(d,c)};a.fc.prototype.xa=function(){this.Qa&&(this.Qa.xa(),this.Qa=null);a.fc.C.xa.call(this)};a.rd=function(a,b,c,d){this.Init(a,b,c,d)};a.v.D(a.rd,a.la);a.rd.GYa=15;a.rd.JYa=.05;a.rd.Uya=
.5;a.rd.xYa=a.ua.nN;a.rd.prototype.Init=function(b,c,d,e){a.rd.C.Init.call(this,b);this.ha=e;this.lp=c;this.Pp=d;this.gE=this.fE=this.FH=this.gQ=0;this.CP=this.EP=this.BP=this.DP=null;this.FB=.1;this.DB=1;this.sba=a.rd.GYa;this.M2=a.rd.JYa;this.Px=20;this.Ze=null;this.zv=!0;this.rba="auto";this.HGa=this.fB=!0;this.ED=new a.Rect(this.u(),0,0,this.lp,this.Pp);this.A(this.ED);this.ED.Wb();this.Oa=new a.la(this.u());this.A(this.Oa);this.Oa.rb(new a.Tb);this.Ml=a.rd.Uya;this.yb=new a.Sd(b,this.Te,this);
this.yb.Qf(this);this.qDa(c,d);this.vO=!1;this.Fs=null};a.rd.prototype.Vu=function(a,b,c){this.lp=a;this.Pp=b;c||(this.ED.Xa(a),this.ED.qb(b),this.Ze&&this.uCa(),this.qDa(a,b))};a.rd.prototype.pe=function(){return new a.yj(this.lp,this.Pp)};a.rd.prototype.qDa=function(b,c){var d=new a.Cd("pzc");d.Pe(this.qa(),this.pa(),b,c);this.te(d)};a.rd.prototype.iWa=function(a){this.Oa=a};a.rd.prototype.QW=function(a){return a&&(a=a.$f(this.Oa,this.Oa.sb))?a:this.Oa.sb()};a.rd.prototype.wg=function(a){return this.QW(a).gg};
a.rd.prototype.$x=function(a){return this.QW(a).le};a.rd.prototype.ay=function(a){return this.QW(a).fe};a.rd.prototype.LWa=function(){this.Px=0};a.rd.prototype.Wi=function(b,c,d){if(this.zv){var e=this.$x(d),f=this.ay(d),r="y"==this.qI()?e:this.Z5(e+b),p="x"==this.qI()?f:this.a6(f+c);c=r-e;var w=p-f;b=null;d&&(b=d.$f(this.Oa,this.Oa.sb))&&(b=b.clone());b||(b=this.Oa.sb().clone());b.translate(c,w);var x=this;c=function(){x.z6(a.wh.dDa,r,p,e,f,d)};w=function(){x.z6(a.wh.Cja,r,p,e,f,d)};d?(d.N(a.G.aj,
this.Oa,this.Oa.sb,this.Oa.rb,b),a.eb.Hwa(d,c),a.eb.Mb(d,w)):(c(),this.Oa.rb(b),w())}};a.rd.prototype.EC=function(a,b,c){this.zv&&(a-=this.$x(c),b-=this.ay(c),this.Wi(a,b,c))};a.rd.prototype.BA=function(b,c,d,e){if(this.fB){c||0===c||(c=this.lp/2);d||0===d||(d=this.Pp/2);var f=this.wg(e),r=this.b6(f*b);this.Ahb(r);if(a.rd.VCa(f)!=a.rd.VCa(r)){var p=r/f;b=null;e&&(b=e.$f(this.Oa,this.Oa.sb))&&(b=b.clone());b||(b=this.Oa.sb().clone());b.scale(p,p,c,d);var w=this.Z5(b.le)-b.le,x=this.a6(b.fe)-b.fe;this.XC(a.xd.H7,
r,f,e,null,c,d,w,x);w=this.Z5(b.le)-b.le;x=this.a6(b.fe)-b.fe;b.translate(w,x);var v=this,p=function(){v.XC(a.xd.K7,r,f,e,null,c,d,w,x)},A=function(){v.XC(a.xd.QJ,v.wg(),f,e,null,c,d,w,x)};e?(e.N(a.G.aj,this.Oa,this.Oa.sb,this.Oa.rb,b),a.eb.Hwa(e,p),a.eb.Mb(e,A)):(p(),this.Oa.rb(b),A())}}};a.rd.prototype.Ct=function(a,b,c,d){this.fB&&(a/=this.wg(d),this.BA(a,b,c,d))};a.rd.prototype.LQa=function(a,b){var c=this.zv,d=this.qI();this.NC(!0);this.VI("auto");var e=b;e||(e=this.Oa.aa());var f=(e.x+e.a/2)*
this.wg(),e=(e.y+e.b/2)*this.wg();this.EC(this.lp/2-f,this.Pp/2-e,a);this.NC(c);this.VI(d)};a.rd.prototype.Dt=function(b,c){if(this.HGa){var d=this.zv,e=this.qI(),f=this.fB;this.NC(!0);this.VI("auto");this.oY(!0);try{var r=c?c:this.Oa.aa();if(r=this.XC(a.xd.L7,null,null,b,r).uW){var p=Math.min((this.lp-2*this.Px)/r.a,(this.Pp-2*this.Px)/r.b),p=this.b6(p),w=this.lp/2-(r.x+r.a/2)*p,x=this.Pp/2-(r.y+r.b/2)*p,v=this,A=function(){v.XC(a.xd.lDa,null,null,b,r)},u=function(){v.XC(a.xd.M7,null,null,b,r)};
b?a.eb.Hwa(b,A):A();this.Ct(p,0,0,b);this.EC(w,x,b);b?a.eb.Mb(b,u):u()}}finally{this.NC(d),this.VI(e),this.oY(f)}}};a.rd.prototype.Whb=function(b){b||(b=this.Oa.aa());b=this.XC(a.xd.L7,null,null,null,b).uW;b=Math.min((this.lp-2*this.Px)/b.a,(this.Pp-2*this.Px)/b.b);return b=this.b6(b)};a.rd.prototype.xI=function(){var b=this.Ld(new a.R(0,0)),c=this.Ld(new a.R(this.lp,this.Pp)),b=this.Oa.Md(b),c=this.Oa.Md(c);return new a.Z(b.x,b.y,c.x-b.x,c.y-b.y)};a.rd.prototype.lT=function(b){if(this.vO=b)this.Fs&&
(this.Fs.Km()&&this.Fs.stop(),this.Fs=null);else{b=this.$x();var c=this.ay(),d=this.wg();this.f9=b!=this.Z5(b)||c!=this.a6(c);this.g9=d!=this.b6(d);if(this.f9||this.g9)this.Fs=new a.G(this.u(),.4),this.Fs.wp(a.Je.lRa),this.g9&&this.BA(1,.5*this.lp,.5*this.Pp,this.Fs),this.f9&&this.Wi(0,0,this.Fs),a.eb.Mb(this.Fs,this.P9a,this),this.f9&&this.z6(a.wh.HZ,null,null,null,null,this.Fs),this.g9&&this.XC(a.xd.HZ,null,null,null,null,this.Fs),this.Fs.play()}};a.rd.prototype.P9a=function(){this.Fs=null;this.f9&&
this.z6(a.wh.zja);this.g9&&this.XC(a.xd.zja)};a.rd.prototype.qba=function(a,b){return Math.sqrt(.04*b*a)};a.rd.prototype.dQa=function(a,b){return Math.sqrt(.008*b*a)};a.rd.prototype.Z5=function(a){null!=this.DP&&a<this.DP&&(this.vO?(a=this.DP-a,a=this.DP-this.qba(a,this.lp)):a=this.DP);null!=this.BP&&a>this.BP&&(this.vO?(a-=this.BP,a=this.BP+this.qba(a,this.lp)):a=this.BP);return a};a.rd.prototype.a6=function(a){null!=this.EP&&a<this.EP&&(this.vO?(a=this.EP-a,a=this.EP-this.qba(a,this.Pp)):a=this.EP);
null!=this.CP&&a>this.CP&&(this.vO?(a-=this.CP,a=this.CP+this.qba(a,this.Pp)):a=this.CP);return a};a.rd.prototype.b6=function(a){a=Math.max(0,a);this.FB&&a<this.FB&&(this.vO?(a=this.FB-a,a=this.FB-this.dQa(a,this.DB-this.FB)):a=this.FB);this.DB&&a>this.DB&&(this.vO?(a-=this.DB,a=this.DB+this.dQa(a,this.DB-this.FB)):a=this.DB);return a};a.rd.VCa=function(a){return Math.round(1E5*a)};a.rd.prototype.Dw=function(){var a=this.Ze;a&&(this.A(a),this.uCa(),a.Dw())};a.rd.prototype.Grb=function(a){this.Ze=
a};a.rd.prototype.uCa=function(){var b=this.ha.vw(),c=a.Ta.M(b,a.ua.RXa,0),d=a.Ta.M(b,a.ua.Dga,0),b=a.Ta.M(b,a.ua.Kw,0),c=a.B.da(this.u())?this.lp-b-c:c;this.Ze.Ma(c,d)};a.rd.prototype.OS=function(a){return this.u().eh(a.pageX,a.pageY)};a.rd.prototype.z6=function(b,c,d,e,f,r){b=new a.wh(b,c,d,e,f,r);this.Te(b)};a.rd.prototype.XC=function(b,c,d,e,f,r,p,w,x){b=new a.xd(b,c,d,e,f,new a.R(r,p),w,x);this.Te(b);return b};a.rd.prototype.lga=function(){this.XC(a.xd.Hja)};a.rd.prototype.jTa=function(a){a+=
this.M2;a>this.WE()&&(a=this.WE());return a};a.rd.prototype.zTa=function(a){a-=this.M2;a<this.oI()&&(a=this.oI());return a};a.rd.prototype.MC=function(a){this.FB=a};a.rd.prototype.oI=function(){return this.FB};a.rd.prototype.xA=function(a){0>a&&(a=1);this.DB=a};a.rd.prototype.WE=function(){return this.DB};a.rd.prototype.hY=function(a){this.DP=a};a.rd.prototype.fY=function(a){this.BP=a};a.rd.prototype.iY=function(a){this.EP=a};a.rd.prototype.gY=function(a){this.CP=a};a.rd.prototype.IC=function(a){this.Ml=
a};a.rd.prototype.ob=function(){return this.Ml};a.rd.prototype.NC=function(a){this.zv=a};a.rd.prototype.VI=function(a){this.rba=a};a.rd.prototype.qI=function(){return this.rba};a.rd.prototype.oY=function(a){this.fB=a};a.rd.prototype.hga=function(a){this.HGa=a};a.rd.prototype.Ahb=function(a){if(this.Ze){var b=this.wg();a==this.oI()&&a==this.WE()?(this.Ze.pda(!1),this.Ze.qda(!1)):b<=a&&a==this.WE()?(this.Ze.pda(!1),this.Ze.qda(!0)):b>=a&&a==this.oI()?(this.Ze.pda(!0),this.Ze.qda(!1)):(this.Ze.pda(!0),
this.Ze.qda(!0))}};a.rd.prototype.mxa=function(a){this.m9a=a};a.rd.prototype.xp=function(a){a?this.yb.Qf(this):this.yb.ll(this)};a.rd.prototype.xa=function(){this.Fs&&(this.Fs.stop(!0),this.Fs=null);this.yb&&(this.yb.ll(this),this.yb.xa(),this.yb=null);a.rd.C.xa.call(this)};a.Sd=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Sd,a.I);a.Sd.wN="panned";a.Sd.prototype.Init=function(b,c,d){a.Sd.C.Init.call(this,b,c,d);this.Id=d;this.eC=null;this.j_=this.eB=this.u9=this.YT=!1;this.s9=!0};a.Sd.jO="panTouch";
a.Sd.pG="zoomTouch";a.Sd.fFa=50;a.Sd.prototype.Qf=function(b){a.Sd.C.Qf.call(this,b);b.Ya(a.MouseEvent.YF,this.cD,!1,this)};a.Sd.prototype.ll=function(b){a.Sd.C.ll.call(this,b);b.jc(a.MouseEvent.YF,this.cD,!1,this)};a.Sd.prototype.mo=function(b){this.u9=this.j_=!1;b.button!=a.MouseEvent.$ia&&(b=this.pb.OS(b),this.fE=b.x,this.gE=b.y,this.gQ=this.fE,this.FH=this.gE,this.Ela=!0,this.iba=this.pb.$x(),this.jba=this.pb.ay(),this.kba=this.pb.wg(),this.s9&&(this.f$=(new Date).getTime()));this.Yp&&this.Yp.Km()&&
(this.Yp.stop(),this.Yp.reset())};a.Sd.prototype.Ly=function(b){var c=this.pb.OS(b);if((c.x!==this.gQ||c.y!==this.FH)&&this.Ela){this.j_=!0;var c=this.pb.OS(b),d=c.x,c=c.y;b.ctrlKey?(this.eB||(this.Cc.call(this.pb,new a.xd(a.xd.I7)),this.eB=!0,this.Id.Ze&&this.Id.Ze.kwa(),this.pb.lT(!0)),b=this.kba*Math.pow(1+.01*(this.FH>=c?1:-1),Math.abs(this.FH-c)),this.pb.zv?this.pb.Ct(b,this.gQ,this.FH):this.pb.Ct(b,null,null)):this.nKa(d,c);this.fE=d;this.gE=c}};a.Sd.prototype.Uo=function(b){this.j_=this.Ela=
!1;this.YT&&this.mKa();this.eB&&this.rKa();a.Sd.C.Uo.call(this,b)};a.Sd.prototype.Tj=function(b){if(this.j_||this.u9)this.u9=this.j_=!1,a.I.sc(b)};a.Sd.prototype.To=function(b){this.Ela&&(this.YT||this.eB)&&(b.relatedTarget&&null!=b.relatedTarget||this.Uo(b));a.Sd.C.To.call(this,b)};a.Sd.prototype.cD=function(b){if(b.wheelDelta&&0!==b.wheelDelta&&this.pb.fB){var c=this.pb.wg();this.eC&&(c=this.eC,this.eC.stop(),c=this.pb.wg(c),this.eC=null);this.eC=null;var d=b.wheelDelta,c=c*(1+this.pb.M2*d/Math.abs(d)),
d=this.pb.OS(b);this.u().ZQ().cib(b);this.pb.zv?this.pb.Ct(c,d.x,d.y,this.eC):this.pb.Ct(c,null,null,this.eC);this.eC&&(a.eb.Mb(this.eC,this.q8a,this),this.eC.play())}};a.Sd.prototype.q8a=function(){this.eC=null};a.Sd.prototype.jbb=function(){};a.Sd.prototype.kbb=function(){var a=1-.04*this.Xpa,a=a*a,b=this.Yp.Voa,c=a*this.Icb*b,a=a*this.Jcb*b;this.Vpa+=c;this.Wpa+=a;var b=this.iba+this.fE-this.gQ+this.Vpa,d=this.jba+this.gE-this.FH+this.Wpa;this.pb.EC(b,d);var e=!1;if(24<=this.Xpa)e=!0;else{var f=
this.pb.$x(),p=this.pb.ay(),w=this.Id.qI();if(Math.abs(f-b)>Math.abs(c)&&"y"!=w||Math.abs(p-d)>Math.abs(a)&&"x"!=w)e=!0}e?(this.Yp.stop(),this.Yp.reset(),this.pb.lT(!1)):this.Xpa++};a.Sd.prototype.RS=function(a){this.pb.fB&&this.Pa.LR(a,this.q2a,this);this.pb.zv&&this.Pa.LR(a,this.L0a,this)};a.Sd.prototype.N6=function(b){this.pb.fB&&this.Pa.IX(b,a.Sd.pG);this.pb.zv&&this.Pa.IX(b,a.Sd.jO);(this.pb.fB||this.pb.zv)&&b.preventDefault()};a.Sd.prototype.M6=function(b){this.pb.fB&&this.Pa.HX(b,a.Sd.pG);
this.pb.zv&&this.Pa.HX(b,a.Sd.jO)};a.Sd.prototype.q2a=function(b,c){var d=this.Pa.qC(a.Sd.pG);1>=d.length&&(this.Pa.QX(c.identifier,a.Sd.pG,a.Sd.pG,a.Sd.pG,this.p2a,this.o2a,this),this.fE=c.pageX,this.gE=c.pageY,this.gQ=this.fE,this.FH=this.gE,this.iba=this.pb.$x(),this.jba=this.pb.ay(),this.kba=this.pb.wg(),this.hba=null,d=this.Pa.qC(a.Sd.pG),this.pb.mxa(this.Pa.dva(d)));this.Yp&&this.Yp.Km()&&(this.Yp.stop(),this.Yp.reset())};a.Sd.prototype.p2a=function(){var b=this.Pa.qC(a.Sd.pG);if(2==b.length){var c=
this.Pa.Plb(b);if(c){this.eB||(this.eB=!0,this.Pa.$L(),this.Cc.call(this.pb,new a.xd(a.xd.I7)),this.Id.Ze&&this.Id.Ze.kwa());this.pb.lT(!0);null==this.hba&&(this.hba=c.wRa-c.ojb);var d=c.wRa/this.hba*this.kba,e=this.Id.u().eh(c.jw,c.kw);this.qe();this.pb.mxa(this.Pa.dva(b));this.pb.Ct(d,e.x,e.y);this.pb.Wi(c.$ib,c.ajb)}}};a.Sd.prototype.o2a=function(){this.eB&&(this.hba=null,this.Pa.mtb(),this.rKa());var b=this.Pa.qC(a.Sd.pG);this.pb.mxa(this.Pa.dva(b));0==b.length&&this.Cc.call(this.pb,new a.xd(a.xd.kDa))};
a.Sd.prototype.L0a=function(b,c){!this.eB&&1>=this.Pa.qC(a.Sd.jO).length&&(this.Pa.QX(c.identifier,a.Sd.jO,a.Sd.jO,a.Sd.jO,this.K0a,this.J0a,this),this.fE=c.pageX,this.gE=c.pageY,this.gQ=this.fE,this.FH=this.gE,this.iba=this.pb.$x(),this.jba=this.pb.ay(),this.kba=this.pb.wg(),this.s9&&(this.f$=(new Date).getTime()));this.Yp&&this.Yp.Km()&&(this.Yp.stop(),this.Yp.reset())};a.Sd.prototype.K0a=function(b,c){if(!this.eB&&1==this.Pa.qC(a.Sd.jO).length){var d=c.pageX,e=c.pageY;this.nKa(d,e);this.fE=d;this.gE=
e}};a.Sd.prototype.J0a=function(a){!this.eB&&this.YT&&(this.mKa(),this.km(a,"panned",!0))};a.Sd.prototype.rKa=function(){this.Cc.call(this.pb,new a.xd(a.xd.yja));this.eB=!1;this.Id.Ze&&this.Id.Ze.iVa();this.pb.lT(!1)};a.Sd.prototype.nKa=function(b,c){this.YT||(this.Cc.call(this.pb,new a.wh(a.wh.NJ)),this.YT=!0,this.Id.Ze&&this.Id.Ze.kwa(),this.pb.lT(!0),this.s9&&(this.sO=[]));this.pb.EC(this.iba+b-this.gQ,this.jba+c-this.FH);this.s9&&(this.qcb=this.f$,this.f$=(new Date).getTime(),this.vH?(this.vH.Km()&&
this.vH.stop(),this.vH.reset()):this.vH=new a.Rh(this.Aa,a.Sd.fFa,this.jbb,this,1),this.sO.push({fjb:this.f$-this.qcb,ijb:b-this.fE,ljb:c-this.gE}),5<this.sO.length&&this.sO.splice(0,1),this.vH.start())};a.Sd.prototype.mKa=function(){this.Cc.call(this.pb,new a.wh(a.wh.OJ));this.YT=!1;this.u9=!0;this.Id.Ze&&this.Id.Ze.iVa();if(this.vH&&this.vH.Km()){this.vH.stop();this.vH.reset();this.Yp?this.Yp.reset():this.Yp=new a.Rh(this.Aa,a.Sd.fFa,this.kbb,this);for(var b=0,c=0,d=0,e=this.sO.length;0<this.sO.length;)var f=
this.sO.pop(),b=b+f.fjb,c=c+f.ijb,d=d+f.ljb;this.sO=null;this.Icb=c/b;this.Jcb=d/b;this.Yp.setInterval(Math.ceil(b/e));this.Xpa=1;this.Wpa=this.Vpa=0;this.Id.zv&&this.Yp.start()}else this.pb.lT(!1)};a.Sd.prototype.LA=function(){return this.Id.zv||this.Id.fB?a.I.jG:a.I.QZ};a.Sd.prototype.hD=function(b){return b==a.Sd.wN?!1:a.Sd.C.hD.call(this,b)};a.QN=function(a,b){this.Init(a,b)};a.v.D(a.QN,a.Cb);a.QN.prototype.Init=function(b,c){a.QN.C.Init.call(this,c);this.v8a=b};a.QN.prototype.mk=function(b){var c=
b.keyCode,d=this.v8a.Qa;if(c==a.KeyboardEvent.Iia)b.ctrlKey||b.shiftKey?d.Wi(d.sba,0):d.Wi(0,d.sba);else if(c==a.KeyboardEvent.Hia)b.ctrlKey||b.shiftKey?d.Wi(-d.sba,0):d.Wi(0,-d.sba);else if(c==a.KeyboardEvent.Mza)(b=d.Ze)&&b.A5();else if(a.KeyboardEvent.CUa(b)||a.KeyboardEvent.Xea(b))d.Ct(d.wg()+d.M2);else if(a.KeyboardEvent.Uea(b)||a.KeyboardEvent.SUa(b))d.Ct(d.wg()-d.M2);else{if(c!=a.KeyboardEvent.ZERO&&c!=a.KeyboardEvent.l7||b.ctrlKey||b.shiftKey)return a.QN.C.mk.call(this,b);d.Dt()}};a.Fc=function(a,
b,c,d,e,f,p,w){this.Init(a,b,c,d,e,f,p,w)};a.Fc.zY="col_northeast";a.Fc.Aya="col_southeast";a.Fc.FF="col_northwest";a.Fc.fJ="col_southwest";a.Fc.oga=.25;a.Fc.Stb="#EBEFF5";a.Fc.Rub=10;a.Fc.Qub=10;a.Fc.RC=25;a.Fc.EXa=10;a.Fc.oD=5;a.v.D(a.Fc,a.la);a.Fc.prototype.Init=function(b,c,d,e,f,r,p,w){a.Fc.C.Init.call(this,b);this.wl=c;this.wm=d;this.Brb(e);this.ys=f;this.lH=w?w:a.B.zw();this.Xt=this.F_=this.j0=null;this.Ka=r;this.or=a.Ta.M(this.Ka,a.j.ub,null);this.Vj=parseInt(a.Ta.M(this.Ka,a.j.dg,null));
this.GG=a.Ta.M(this.Ka,a.j.Lb,null);this.Bq=a.Ta.M(this.Ka,a.ua.kN,1);this.N9=void 0!==p?!p:!1;this.lU=new a.la(b);this.A(this.lU);this.lU.Ma(a.Fc.oD,a.Fc.oD);this.Ya(a.MouseEvent.zj,this.KAa,!1,this);this.Ya(a.MouseEvent.xi,this.R6,!1,this)};a.Fc.prototype.I9a=function(){if(!this.lH){this.Tm=a.Wc.$sa(this.u(),a.Fc.RC,this.Ka,!1);this.Tm.T(this.Ka[a.ua.Cy]);this.A(this.Tm);var b=this.Ln==a.Fc.FF||this.Ln==a.Fc.fJ;this.isCollapsed()?this.cp=a.U.eda(this.u(),this.ys,a.Fc.RC,this.Ka,b?a.U.HA:a.U.ho):
this.cp=a.U.cda(this.u(),this.ys,a.Fc.RC,this.Ka,b?a.U.HA:a.U.ho);this.Tm.A(this.cp);this.Tm.ga(b?this.zb:-a.Fc.EXa);a.B.Wa()?this.cp.Ya(a.TouchEvent.$i,this.$S,!1,this):(this.cp.Ya(a.MouseEvent.Be,this.$S,!1,this),this.cp.Ya(a.MouseEvent.zj,this.Dia,!1,this),this.cp.Ya(a.MouseEvent.xi,this.Cia,!1,this))}};a.Fc.prototype.wrb=function(a,b){this.j0=a;this.F_=b};a.Fc.prototype.chb=function(b){this.lU.A(b);b.Ya(a.Gn.IJ,this.h_a,!1,this);b=this.lU.aa();this.zb=Math.min(this.wl,b.a+2*a.Fc.oD);this.Qb=Math.min(this.wm,
b.b+2*a.Fc.oD);this.Gb?(this.Gb.nk(this.boa(this.zb,this.Qb)),b=this.Ln==a.Fc.FF||this.Ln==a.Fc.fJ,this.Tm&&b&&this.Tm.ga(this.zb)):(this.Gb=this.f9a(this.zb,this.Qb),this.Ib(this.Gb,0),this.I9a());this.N9&&this.lHa(!1)};a.Fc.prototype.h_a=function(b){var c=b.getWidth()+2*a.Fc.oD;b=b.getHeight()+2*a.Fc.oD;this.Gb.nk(this.boa(c,b));var d=this.Ln==a.Fc.FF||this.Ln==a.Fc.fJ;this.Tm&&d&&this.Tm.ga(c);this.Te(new a.Gn(c,b,0,0))};a.Fc.prototype.isCollapsed=function(){return this.N9};a.Fc.prototype.jxa=
function(b){this.N9!=b&&(this.N9=b,this.lHa(!0),this.Te(new a.GA(b?a.GA.kT:a.GA.PJ)))};a.Fc.prototype.Brb=function(b){this.Ln=b?b:a.Fc.zY;a.B.da(this.u())&&(this.Ln==a.Fc.zY?this.Ln=a.Fc.FF:this.Ln==a.Fc.FF?this.Ln=a.Fc.zY:this.Ln==a.Fc.Aya?this.Ln=a.Fc.fJ:this.Ln==a.Fc.fJ&&(this.Ln=a.Fc.Aya))};a.Fc.prototype.N3=function(){return this.wl-2*a.Fc.oD};a.Fc.prototype.aX=function(){return this.wm-2*a.Fc.oD};a.Fc.prototype.joa=function(b,c){return this.isCollapsed()?b:c?new a.R(1/b.x,1/b.y):new a.R(-b.x,
-b.y)};a.Fc.prototype.lHa=function(b){this.Xt&&this.Xt.stop(!0);var c=this.Ln==a.Fc.FF||this.Ln==a.Fc.zY,d=this.Ln==a.Fc.FF||this.Ln==a.Fc.fJ,e=d?0:this.zb,f=c?0:this.Qb,r=new a.R(1/this.zb,1/this.Qb),e=new a.R(e,f),c=new a.R(d?-this.zb:this.zb,f-(c?0:a.Fc.RC));b||(this.Gb.T(0),this.Tm&&this.Tm.T(0));r=new a.sY(this.u(),this.Gb,this.joa(r,!0),b?a.Fc.oga:1E-5);c=new a.CA(this.u(),this.Tm,this.joa(c),b?a.Fc.oga:1E-5);b=new a.CA(this.u(),this.Gb,this.joa(e),b?a.Fc.oga:1E-5);this.Xt=new a.Gg(this.u(),
r,c,b),this.u().Af().qe(),this.jc(a.MouseEvent.zj,this.KAa,!1,this),this.jc(a.MouseEvent.xi,this.R6,!1,this),this.cp&&(this.cp.jc(a.TouchEvent.$i,this.$S,!1,this),this.cp.jc(a.MouseEvent.Be,this.$S,!1,this),this.cp.jc(a.MouseEvent.zj,this.Dia,!1,this),this.cp.jc(a.MouseEvent.xi,this.Cia,!1,this)),this.isCollapsed()&&this.lU.T(0),this.Xt.lg(this.Uw,this),this.Xt.play()};a.Fc.prototype.f9a=function(b,c){var d=new a.vb(this.u(),this.boa(b,c)),e=this.Ka[a.ua.Cy];d.fb(this.GG,this.Bq);d.Vb(this.or,e);
return d};a.Fc.prototype.boa=function(b,c){var d=this.Vj,e,f=this.Ln==a.Fc.FF||this.Ln==a.Fc.fJ;c<=a.Fc.RC&&(c=a.Fc.RC);e=this.lH||f?a.P.moveTo(d,0):a.P.moveTo(0,0);e+=a.P.lineTo(b-d,0);!this.lH&&f?(e+=a.P.lineTo(b,0),e+=a.P.lineTo(b,d)):e+=a.P.We(b,0,b,d);!this.lH&&c==a.Fc.RC&&f?e+=a.P.lineTo(b,c):(e+=a.P.lineTo(b,c-d),e+=a.P.We(b,c,b-d,c));e+=a.P.lineTo(d,c);e=this.lH||c!=a.Fc.RC||f?e+a.P.We(0,c,0,c-d):e+a.P.lineTo(0,c);if(this.lH||f)e+=a.P.lineTo(0,d),e+=a.P.We(0,0,d,0);return e+=a.P.closePath()};
a.Fc.prototype.Uw=function(){this.Xt=null;var b=this.Gb.Ud().clone();b.T(this.Ka[a.ua.Cy]);this.Gb.Ga(b);var b=this.Ka[a.ua.Rtb],c=this.Gb.fd().clone();c.T(b);this.Gb.ra(c);this.Tm&&this.Tm.T(this.Ka[a.ua.Cy]);this.isCollapsed()||this.lU.T(1);b=this.Ln==a.Fc.FF||this.Ln==a.Fc.fJ;this.cp&&(this.isCollapsed()?this.cp=a.U.eda(this.u(),this.ys,a.Fc.RC,this.Ka,b?a.U.HA:a.U.ho):this.cp=a.U.cda(this.u(),this.ys,a.Fc.RC,this.Ka,b?a.U.HA:a.U.ho),this.Tm.A(this.cp),this.Tm.my(0),a.B.Wa()?this.cp.Ya(a.TouchEvent.$i,
this.$S,!1,this):(this.cp.Ya(a.MouseEvent.Be,this.$S,!1,this),this.cp.Ya(a.MouseEvent.zj,this.Dia,!1,this),this.cp.Ya(a.MouseEvent.xi,this.Cia,!1,this)))};a.Fc.prototype.$S=function(){this.u().Af().qe();this.jxa(!this.isCollapsed())};a.Fc.prototype.Dia=function(a){var b=this.isCollapsed()?this.j0:this.F_;null!=b&&this.u().Af().x5(a.pageX,a.pageY,b,this.cp,!0)};a.Fc.prototype.Cia=function(){this.u().Af().qe()};a.Fc.prototype.KAa=function(){var b=this.Gb.Ud().clone();b.T(this.Ka[a.ua.x6]);this.Gb.Ga(b);
var b=this.Ka[a.ua.I5],c=this.Gb.fd().clone();c.T(b);this.Gb.ra(c);this.Tm&&this.Tm.T(this.Ka[a.ua.x6])};a.Fc.prototype.R6=function(){var b=this.Gb.Ud().clone();b.T(this.Ka[a.ua.Cy]);this.Gb.Ga(b);b=this.Gb.fd().clone();b.T(this.Bq);this.Gb.ra(b);this.Tm&&this.Tm.T(this.Ka[a.ua.Cy])};a.GA=function(b){this.Init(a.GA.xe);this.Ts=b};a.v.D(a.GA,a.Vg);a.GA.xe="dvtCollapsiblePanelEvent";a.GA.kT="hide";a.GA.PJ="show";a.GA.prototype.Zn=function(){return this.Ts};a.zJ={};a.v.D(a.zJ,a.v);a.zJ.DX=function(b,
c){var d=new a.Image(b,c);d.nb(!1);a.js.Ur(b,c,function(a){null!=a&&a.width&&a.height&&(d.Xa(a.width),d.qb(a.height))});return d};a.U={};a.v.D(a.U,a.v);a.U.jub=-6;a.U.Iya=23;a.U.Hya=21;a.U.Sub=20;a.U.zub=22;a.U.yub=20;a.U.ZDa=47;a.U.YDa=26;a.U.xh=Math.sin(Math.PI/4);a.U.zh=Math.tan(Math.PI/8);a.U.ub="#7C8191";a.U.Yza="#E0E1E1";a.U.Zza="#F0F1F2";a.U.aja=8;a.U.yYa="solid";a.U.Zga="#7BA0D9";a.U.aha="#3474D3";a.U.Xya="#BFD8FB";a.U.W5a="zoominUp";a.U.X5a="zoominOver";a.U.V5a="zoominDown";a.U.U5a="zoominDisabled";
a.U.c6a="zoomtofitUp";a.U.d6a="zoomtofitOver";a.U.b6a="zoomtofitDown";a.U.$5a="zoomoutUp";a.U.a6a="zoomoutOver";a.U.Z5a="zoomoutDown";a.U.Y5a="zoomoutDisabled";a.U.e5a="pandialUp";a.U.f5a="pandialOver";a.U.d5a="pandialDown";a.U.n5a="recenterUp";a.U.o5a="recenterOver";a.U.m5a="recenterDown";a.U.oFa="resetUp";a.U.q5a="resetOver";a.U.p5a="resetDown";a.U.HEa="drillupUp";a.U.c4a="drillupOver";a.U.b4a="drillupDown";a.U.GEa="drilldownUp";a.U.a4a="drilldownOver";a.U.$3a="drilldownDown";a.U.gvb="maxUp";a.U.hvb=
"maxOver";a.U.fvb="maxDown";a.U.lvb="restoreUp";a.U.mvb="restoreOver";a.U.kvb="restoreDown";a.U.xEa="collapseEna";a.U.yEa="collapseOvr";a.U.wEa="collapseDwn";a.U.LEa="expandEna";a.U.MEa="expandOvr";a.U.KEa="expandDwn";a.U.i5a="quickQueryEna";a.U.j5a="quickQueryOvr";a.U.h5a="quickQueryDwn";a.U.Y2a="clearResultsEna";a.U.Z2a="clearResultsOvr";a.U.X2a="clearResultsDwn";a.U.S5a="Up";a.U.b5a="Over";a.U.Z3a="Down";a.U.v5a="Sel";a.U.k5a="_r";a.U.K5a="synchronize";a.U.ho="right";a.U.HA="left";a.U.Hib=function(b,
c,e,f,n){var r=a.U.Ima(b,f[a.U.e5a],n),p=new a.la(b);p.Ma(20,20);var w=a.U.Ima(b,f[a.U.d5a],n);w.Ma(-20,-20);p.A(w);w=new a.la(b);w.Ma(20,20);var x=a.U.Ima(b,f[a.U.f5a],n);x.Ma(-20,-20);w.A(x);r=new a.ia(b,r,w,p);if(0<(e&a.ua.dv)){var v=new a.ia(b,a.U.Jma(b,f[a.U.n5a],n),a.U.Jma(b,f[a.U.o5a],n),a.U.Jma(b,f[a.U.m5a],n));v.Ma(9,9)}return new d(b,r,v,c,e,n)};a.U.Aib=function(b,c,d){var e=a.U.Pl(b,a.ia.od,c[a.U.HEa],d),f=a.U.Pl(b,a.ia.Yd,c[a.U.c4a],d),r=a.U.Pl(b,a.ia.Hd,c[a.U.b4a],d);c=a.U.Pl(b,a.ia.od,
c[a.U.HEa],d,null,null,.4);return new a.ia(b,e,f,r,c)};a.U.zib=function(b,c,d){var e=a.U.Pl(b,a.ia.od,c[a.U.GEa],d),f=a.U.Pl(b,a.ia.Yd,c[a.U.a4a],d),r=a.U.Pl(b,a.ia.Hd,c[a.U.$3a],d);c=a.U.Pl(b,a.ia.od,c[a.U.GEa],d,null,null,.4);return new a.ia(b,e,f,r,c)};a.U.Lib=function(b,c,d){var e=a.U.Pl(b,a.ia.od,c[a.U.oFa],d),f=a.U.Pl(b,a.ia.Yd,c[a.U.q5a],d),r=a.U.Pl(b,a.ia.Hd,c[a.U.p5a],d);c=a.U.Pl(b,a.ia.od,c[a.U.oFa],d);return new a.ia(b,e,f,r,c)};a.U.Vib=function(b,c,d){var e=a.U.Pl(b,a.ia.od,c[a.U.c6a],
d),f=a.U.Pl(b,a.ia.Yd,c[a.U.d6a],d);c=a.U.Pl(b,a.ia.Hd,c[a.U.b6a],d);return new a.ia(b,e,f,c)};a.U.Tib=function(b,c,d){var e=a.U.Pl(b,a.ia.od,c[a.U.W5a],d),f=a.U.Pl(b,a.ia.Yd,c[a.U.X5a],d),r=a.U.Pl(b,a.ia.Hd,c[a.U.V5a],d);c=a.U.Pl(b,a.ia.Oy,c[a.U.U5a],d);return new a.ia(b,e,f,r,c)};a.U.Uib=function(b,c,d){var e=a.U.Pl(b,a.ia.od,c[a.U.$5a],d),f=a.U.Pl(b,a.ia.Yd,c[a.U.a6a],d),r=a.U.Pl(b,a.ia.Hd,c[a.U.Z5a],d);c=a.U.Pl(b,a.ia.Oy,c[a.U.Y5a],d);return new a.ia(b,e,f,r,c)};a.U.Dib=function(b,c,d,e,f){var r=
a.Ta.M(f,"buttonRadius",0),p=a.Ta.M(f,a.ua.qN,0),w=a.Ta.M(f,a.ua.qN,0),x=a.U.Bma(b,r,p,w,f);a.U.Qra(d,x,p,w+2*r,f,!0);c=a.U.Zna(b,d,c);(b=a.U.GLa(b,e[c],p,w))&&x.A(b);return x};a.U.Zna=function(b,c,d,e){var f="";c==a.ia.od?c=a.U.S5a:c==a.ia.Yd?c=a.U.b5a:c==a.ia.Hd&&(c=a.U.Z3a);e&&(d+=a.U.v5a,a.B.da(b)&&(f=a.U.k5a));return d+(c+f)};a.U.bta=function(b,c,d,e){var f=a.U.Zna(b,c,a.U.K5a,!0);return a.U.Pl(b,c,e[f],d)};a.U.Iib=function(b,c,d,e,f){var r=a.Ta.M(f,"buttonRadius",0);b=a.U.Bma(b,r,d,e,f);a.U.Qra(c,
b,d,e+2*r,f,!0);return b};a.U.uib=function(b,c,d,e,f){c=a.U.Zna(b,d,c);return a.U.Pl(b,d,e[c],f)};a.U.eda=function(b,c,d,e,f){var r=f==a.U.ho;f=a.U.nU(b,a.ia.od,d,r?c[a.U.xEa]:c[a.U.LEa],e,r);var p=a.U.nU(b,a.ia.Yd,d,r?c[a.U.yEa]:c[a.U.MEa],e,r);c=a.U.nU(b,a.ia.Hd,d,r?c[a.U.wEa]:c[a.U.KEa],e,r);return new a.ia(b,f,p,c)};a.U.cda=function(b,c,d,e,f){var r=f==a.U.ho;f=a.U.nU(b,a.ia.od,d,r?c[a.U.LEa]:c[a.U.xEa],e,r);var p=a.U.nU(b,a.ia.Yd,d,r?c[a.U.MEa]:c[a.U.yEa],e,r);c=a.U.nU(b,a.ia.Hd,d,r?c[a.U.KEa]:
c[a.U.wEa],e,r);return new a.ia(b,f,p,c)};a.U.Kib=function(b,c){var d=a.U.oU(b,c[a.U.i5a]),e=a.U.oU(b,c[a.U.j5a]),f=a.U.oU(b,c[a.U.h5a]);return new a.ia(b,d,e,f)};a.U.tib=function(b,c){var d=a.U.oU(b,c[a.U.Y2a]),e=a.U.oU(b,c[a.U.Z2a]),f=a.U.oU(b,c[a.U.X2a]);return new a.ia(b,d,e,f)};a.U.Pl=function(b,c,d,e,f,r,p){var w=a.Ta.M(e,"buttonRadius",0);if("undefined"===f||null==f)f=a.Ta.M(e,a.ua.qN,0);if("undefined"===r||null==r)r=a.Ta.M(e,a.ua.qN,0);c=a.U.H9a(b,c,w,f,r,e);if(b=a.U.GLa(b,d,f,r))null!=p&&
b.T(p),c.A(b);return c};a.U.GLa=function(b,c,d,e){var f=new a.Image(b,c);f.nb(!1);a.js.Ur(b,c,function(a){null!=a&&a.width&&a.height&&(f.Xa(a.width),f.qb(a.height),f.Ma(d/2-a.width/2,e/2-a.height/2))});return f};a.U.Ima=function(b,c,d){var e=new a.la(b),f=new a.Nm(b,20,20,20);f.T(0);d=a.Ta.M(d,a.j.Lb,null);f.fb(d);e.A(f);(b=a.zJ.DX(b,c))&&e.A(b);return e};a.U.Jma=function(b,c,d){var e=new a.la(b),f=new a.Nm(b,11,11,8);f.T(0);d=a.Ta.M(d,a.j.Lb,null);f.fb(d);e.A(f);(b=a.zJ.DX(b,c))&&e.A(b);return e};
a.U.nU=function(b,c,d,e,f,r){d||(d=47);c=a.U.L9a(b,c,d,f,r);if(b=a.zJ.DX(b,e))r=a.Ta.M(f,a.ua.PXa,0),e=a.Ta.M(f,a.ua.OXa,0),c.A(b),f=(a.Ta.M(f,a.ua.Kw,0)-r)/2,b.Ma(f,(d-e)/2);return c};a.U.oU=function(b,c){var d=a.zJ.DX(b,c);d.nb(!0);return d};a.U.Gib=function(b,c){var d=a.U.nIa(b),e=a.Ta.M(c,a.j.Lb,null),f=a.Ta.M(c,a.j.ub,null);"solid"==a.Ta.M(c,a.j.hd,null)?(d.Vb(f),d.fb(e)):(d.Ga(new a.Gp(36,["#8D93A5","#E0EAEB",f],[1,1,1],[0,125/255,1],[0,0,40,40],1)),d.ra(new a.bd(90,[e,e,"#5A83BE",e],[.9,.1,
0,.7],[0,105/255,150/255,1],[0,0,40,40])));return d};a.U.hRa=function(b,c){var d=a.U.nIa(b),e=a.Ta.M(c,a.j.Lb,null);d.Vb(e);d.fb(e);return d};a.U.nIa=function(b){var c=a.P.moveTo(40,20)+a.P.We(40,20*a.U.zh+20,20*a.U.xh+20,20*a.U.xh+20)+a.P.We(20*a.U.zh+20,40,20,40)+a.P.We(20*-a.U.zh+20,40,20*-a.U.xh+20,20*a.U.xh+20)+a.P.We(0,20*a.U.zh+20,0,20)+a.P.We(0,20*-a.U.zh+20,20*-a.U.xh+20,20*-a.U.xh+20)+a.P.We(20*-a.U.zh+20,0,20,0)+a.P.We(20*a.U.zh+20,0,20*a.U.xh+20,20*-a.U.xh+20)+a.P.We(40,20*-a.U.zh+20,
40,20)+a.P.closePath();return new a.vb(b,c,"draw_pan_button")};a.U.ica=function(b,c,d,e,f){b.Vb("#FFFFFF");b.Ga(new a.Gp(63,["#8D93A5","#E0EAEB","#FFFFFF"],[1,1,1],[0,155/255,1],[e,f,c,d],1))};a.U.Qra=function(b,c,d,e,f,r){if(a.Ta.M(f,a.ua.AY,null))!r||r&&b==a.ia.od?c.Wb():b!=a.ia.Yd&&b!=a.ia.Hd||c.ra(new a.$b("#EBECED"));else if(f[a.fc.iT]==a.j.Hg)switch(b){case a.ia.Yd:c.ra(new a.$b("#FFFFFF",.7));c.Ga(new a.ya(a.Ta.M(f,a.j.ub,null)));break;case a.ia.Hd:c.ra(new a.$b("#B3C6DB"));c.Ga(new a.ya(a.Ta.M(f,
a.j.ub,null)));break;default:c.Wb()}else{var p,w,x;switch(b){case a.ia.Oy:case a.ia.od:p=["#5B868A","#FFFFFF","#FFFFFF","#5B868A"];w=[.01,0,.05,.01];x=[0,120/255,130/255,1];break;case a.ia.Yd:a.U.ica(c,d,e,0,0);p=["#FFFFFF","#4671B0","#4671B0","#FFFFFF"];w=[.5,.2,.1,.7];x=[0,120/255,130/255,1];break;case a.ia.Hd:a.U.ica(c,d,e,0,0),p=["#E0EAEB","#5B868A","#4671B0"],w=[.1,.3,.6],x=[0,130/255,1]}c.ra(new a.bd(90,p,w,x,[0,0,d,e]))}};a.U.Rfb=function(b,c,d,e,f){if(a.Ta.M(f,a.ua.AY,null))c.Wb();else{var r,
p=a.Ta.M(f,a.j.hd,null);r=a.Ta.M(f,a.j.ub,null);if("solid"==p){d=a.Ta.M(f,a.j.Lb,null);var w,x;switch(b){case a.ia.od:w=a.Ta.M(f,a.ua.kN,1);x=a.Ta.M(f,a.ua.Cy,1);break;case a.ia.Hd:case a.ia.Yd:w=a.Ta.M(f,a.ua.I5,1),x=a.Ta.M(f,a.ua.x6,1)}b=new a.$b(d,w);r=new a.ya(r,x)}else{var v,A,u;switch(b){case a.ia.od:v=["#FFFFFF","#5B868A","#5B868A"];A=[0,.2,.3];u=[0,130/255,1];break;case a.ia.Yd:v=["#FFFFFF","#FFFFFF","#4671B0","#4671B0"];A=[.1,.2,.1,.6];u=[0,120/255,130/255,1];break;case a.ia.Hd:v=["#4671B0",
"#5B868A","#5B868A"],A=[.5,.2,.4],u=[0,130/255,1]}b=new a.bd(0,v,A,u,[0,0,d,e]);r=new a.ya(r,1,.8)}c.Ga(r);c.ra(b)}};a.U.Cvb=function(b,c,d,e,f,r){var p,w,x;switch(b){case a.ia.od:c.Vb("#FFFFFF",1,.25);p=["#FFFFFF","#4671B0","#E0EAEB","#FFFFFF"];w=[.6,.3,.3,.8];x=[0,125/255,130/255,1];break;case a.ia.Yd:a.U.ica(c,d,e,f,r);p=["#4671B0","#FFFFFF","#FFFFFF","#FFFFFF"];w=[.4,.3,.7,1];x=[0,70/255,200/255,1];break;case a.ia.Hd:a.U.ica(c,d,e,f,r),p=["#FFFFFF","#4671B0","#E0EAEB"],w=[.6,.5,.8],x=[0,130/255,
1]}c.ra(new a.bd(90,p,w,x,[f,r,d,e]))};a.U.yha=function(a,b,c,d){return d?["M",a,0,"L",c,0,"A",c,c,0,0,0,0,c,"L",0,b-c,"A",c,c,0,0,0,c,b,"L",a,b]:["M",0,0,"L",a-c,0,"A",c,c,0,0,1,a,c,"L",a,b-c,"A",c,c,0,0,1,a-c,b,"L",0,b]};a.U.L9a=function(b,c,d,e,f){d||(d=47);var r=parseInt(a.Ta.M(e,a.j.dg,0)),p=a.Ta.M(e,a.ua.Kw,0);d=Math.max(d,a.Ta.M(e,a.ua.U5,d));b=new a.vb(b,a.U.yha(p,d,r,f));a.U.Rfb(c,b,p,d,e);return b};a.U.H9a=function(b,c,d,e,f,r){b=a.U.Bma(b,d,e,f,r);a.U.Qra(c,b,e,f+2*d,r);return b};a.U.Bma=
function(b,c,d,e,f){if(f[a.fc.iT]==a.j.Hg)return new a.Rect(b,0,0,d,e);d-=2*c;e-=2*c;f=d+c;var r=e+c,p=a.P.moveTo(f+c,r)+a.P.We(c+f,a.U.zh*c+r,a.U.xh*c+f,a.U.xh*c+r)+a.P.We(a.U.zh*c+f,c+r,f,c+r)+a.P.lineTo(f,r+c)+a.P.lineTo(f-d,c+r);f-=d;p+=a.P.We(-a.U.zh*c+f,c+r,-a.U.xh*c+f,a.U.xh*c+r)+a.P.We(-c+f,a.U.zh*c+r,-c+f,r)+a.P.lineTo(f-c,r)+a.P.lineTo(f-c,r-e);r-=e;p+=a.P.We(-c+f,-a.U.zh*c+r,-a.U.xh*c+f,-a.U.xh*c+r)+a.P.We(-a.U.zh*c+f,-c+r,f,-c+r)+a.P.lineTo(f,-c+r)+a.P.lineTo(f+d,-c+r);f+=d;p+=a.P.We(a.U.zh*
c+f,-c+r,a.U.xh*c+f,-a.U.xh*c+r)+a.P.We(c+f,-a.U.zh*c+r,c+f,r)+a.P.lineTo(f+c,r+e)+a.P.closePath();return new a.vb(b,p)};a.U.cjb=function(b,c,d,e){e=a.Ta.M(e,"radius",0);c-=2*e;d-=e;var f=c+e,r=d,p=a.P.moveTo(f+e,r)+a.P.We(e+f,a.U.zh*e+r,a.U.xh*e+f,a.U.xh*e+r)+a.P.We(a.U.zh*e+f,e+r,f,e+r)+a.P.lineTo(f,e+r)+a.P.lineTo(f-c,e+r),f=f-c,p=p+(a.P.We(-a.U.zh*e+f,e+r,-a.U.xh*e+f,a.U.xh*e+r)+a.P.We(-e+f,a.U.zh*e+r,-e+f,r)+a.P.lineTo(-e+f,r)+a.P.lineTo(-e+f,r-d)),r=r-d,p=p+(a.P.lineTo(f+c+e,r)+a.P.lineTo(f+
c+e,r+d)+a.P.closePath());return new a.vb(b,p)};a.U.Kv=function(b,c){c instanceof a.ia&&(c=c.hb(0));return a.Mh.v3(b,c)};a.U.Awa=function(b,c){var d=a.U.yYa,e=a.U.Zga,f=a.U.aha,r;c&&(c.M(a.j.hd)&&(d=c.M(a.j.hd)),c.M(a.j.ub)&&(e=c.M(a.j.ub)),c.M(a.j.Lb)&&(f=c.M(a.j.Lb)),c.M(a.j.Zr)&&(r=c.M(a.j.Zr)));var e=new a.ya(e),p;if("solid"==d)p=new a.$b(f);else{var w,x,v;if(r&&0<=r.indexOf("linear-gradient")){if(d=a.tc.NM(r))v=d.fq(),p=d.zq,w=d.yq,x=d.vG}else p=f,w=a.U.Xya,p!=a.U.aha&&(w=a.O.iy(a.U.aha,a.U.Xya,
p)),p=[p,w],w=[.6,.8],x=[0,1],v=-270;p=new a.bd(v,p,w,x)}b.ra(p);b.Ga(e)};a.Ia(a.fc.prototype,"render",a.fc.prototype.ta)})(dvt);
  return dvt;
});
