/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a){this.Init(b.xe);this.type=this.he();this.fp=a}function c(){this.Init({skyros:c.lh,alta:c.mf})}function d(a,b){this.Init(a,b)}function e(a,b,c){this.Init(a,b,c)}function f(a,b,c,d){this.Init(a,b,c,d)}function h(a,b){this.Init();this.xc=a;this.l_=!1;this.ej=b}function k(a,b,c,d){this.Init(b,c,d);this.$t=a}a.H5=function(){};a.v.D(a.H5,a.v);a.H5.prototype.get=function(){};a.AS=function(){this.i2=[]};a.v.D(a.AS,a.H5);a.AS.prototype.add=function(a,b,c){this.i2.push({group:a,Gnb:b,
vwa:c})};a.AS.prototype.get=function(a){if(null===a)return null;for(var b=0;b<this.i2.length;b++)if(this.i2[b].group==a)return this.i2[b].vwa;return null};a.AS.prototype.Jlb=function(){return this.i2.slice(0)};a.iJ=function(a,b,c,d,e){this.Sn=a;this.Ao=b;this.Gcb=c?c:this.Sn;this.Dcb=d?d:this.Ao;this.X1=e;this.RNa=this.Ao-this.Sn};a.v.D(a.iJ,a.H5);a.iJ.prototype.get=function(a){if(isNaN(a)||null===a)return null;a=0<this.RNa?(a-this.Sn)/this.RNa:.5;a=Math.max(Math.min(a,1),0);a*=this.X1.length-1;return a===
Math.round(a)?this.X1[a]:this.f8a(this.X1[Math.floor(a)],this.X1[Math.ceil(a)],a-Math.floor(a))};a.iJ.prototype.ATa=function(){return this.X1.slice(0)};a.iJ.prototype.O3=function(){return this.Gcb};a.iJ.prototype.f8a=function(b,c,d){return a.O.u4(b,c,d)};a.Nk=function(){};a.v.D(a.Nk,a.v);a.Nk.A4a=.4;a.Nk.zEa=1;a.Nk.BEa=50;a.Nk.AEa=10;a.Nk.tka=5;a.Nk.y4a=11;a.Nk.YEa="#636363";a.Nk.evb="#333333";a.Nk.Vwa=function(b,c,d,e,f,h,k){var l=null;h&&(h instanceof a.iJ?l=a.Nk.qeb(b,c,d,e,h,k):h instanceof a.AS&&
(l=a.Nk.reb(b,d,e,f,h,k)));return l};a.Nk.qeb=function(b,c,d,e,f,h){var k=a.B.da(b),l=a.Nk.AEa/2+a.Nk.zEa,m=new a.la(b);d.A(m);d=f.O3();var B=new a.ca(b,d,0,l);B.Bb(h.AC);B.Ng();m.A(B);var C=new a.Rect(b,0,a.Nk.zEa,a.Nk.BEa,a.Nk.AEa),z=k?f.ATa().slice().reverse():f.ATa();C.ra(new a.bd(0,z));h.borderColor&&C.Vb(h.borderColor);m.A(C);z=a.Nk.BEa+a.Nk.tka;f=f.Dcb;b=new a.ca(b,f,0,l);b.Bb(h.AC);b.Ng();m.A(b);k?(h=b.Pc().a+a.Nk.tka,C.ga(h),B.Fa(h+z)):(h=B.Pc().a+a.Nk.tka,C.ga(h),b.Fa(h+z));c.lb(C,new a.yi(d+
" - "+f));m.aa().a>e&&(m.removeChild(B),m.removeChild(b),C.ga(0));return m};a.Nk.reb=function(b,c,d,e,f,h){var k=new a.la(b);c.A(k);c=[];f=f.Jlb();for(var l=0;l<f.length;l++){var m=f[l];c.push({text:m.Gnb,color:m.vwa.color,pattern:m.vwa.pattern,borderColor:h.borderColor})}h={sections:[{items:c}],orientation:"horizontal",layout:{outerGapWidth:0,outerGapHeight:0},textStyle:h.AC.toString()};c=a.tf.newInstance(b);c.setId(null);k.A(c);e=c.ht(h,d,e*a.Nk.A4a);c.ta(h,d,e.b);d=c.jC();b=new a.Rect(b,0,0,d.a,
e.b);b.Wb();k.Ib(b,0);return k};a.lN=function(b){this.Init(a.lN.xe);this.xc=b};a.v.D(a.lN,a.Vg);a.lN.xe="breadcrumbsDrill";a.lN.prototype.getId=function(){return this.xc};a.rq=function(a,b,c,d){this.Init(a,b,c,d)};a.v.D(a.rq,a.la);a.rq.prototype.Init=function(b,c,d,e){a.rq.C.Init.call(this,b);this.vsb(e);this.mz=new k(this,b,c,d);this.mz.Qf(this);this.setId("breadcrumbs1000"+Math.floor(1E9*Math.random()));this.CK=-1;this.Oma=this.mpa=null};a.rq.prototype.vsb=function(a){this.Nf=l.en(a)};a.rq.prototype.ta=
function(b,c){this.Nb=b?a.ac.clone(b):this.Nb;this.Hl();this.rDa(null);m.ta(this,this,c)};a.rq.prototype.IFa=function(){return this.Nb?this.Nb:{}};a.rq.prototype.ab=function(){return this.mz};a.rq.prototype.Qd=function(){var a=this.CK;this.CK=-1;this.dC(a,this.CK)};a.rq.prototype.qtb=function(a){var b=this.CK;this.CK=this.Vab(b,!a);this.dC(b,this.CK);return this.CK};a.rq.prototype.Vab=function(a,b){return-1==a?b?0:this.Nb.items.length-2:b?a==this.Nb.items.length-2?-1:++a:0==a?-1:--a};a.rq.prototype.dC=
function(b,c){var d=this.mpa,e=null,f=this.t3(c);if(f){var h=this.mz.mb(f);h&&h.jk&&h.jk()?(e=this.u(),h=f.aa(),f=f.sb(),this.mpa=e=new a.im(e,this,h,f)):this.mpa=null}d&&d.Vq();e&&e.show()};a.rq.prototype.t3=function(a){var b=this.Oma;return 0>a||!b||a>=b.length?null:b[a]};a.rq.prototype.nSa=function(a){for(var b=this.Oma,c=0;c<b.length;c++)if(b[c]==a)return c};a.rq.prototype.rDa=function(a){this.Oma=a};var l={};a.v.D(l,a.v);l.lh={labelStyle:a.bb.xN+"color: #003286;",disabledLabelStyle:a.bb.xN,C8:2,
q6a:"\x3e"};l.en=function(b){var c=l.Sna(b);return b?a.ac.Vd(b,c):c};l.Sna=function(){return a.ac.clone(l.lh)};l.Dh=function(a,b){return Math.ceil(b*a.layout.gapRatio)};a.v.D(k,a.I);k.prototype.Tj=function(a){k.C.Tj.call(this,a);this.Rqa(this.mb(a.target))};k.prototype.Sw=function(a){this.Rqa(this.mb(a.target))};k.prototype.Rqa=function(b){b&&b instanceof h&&b.jk()&&(b=new a.lN(b.getId()),this.nl(b,this.$t))};k.prototype.xw=function(b){var c=!0,d=b.keyCode;d==a.KeyboardEvent.Qh?(d=this.$t.qtb(b.shiftKey),
-1==d?c=!1:this.nD(this.$t.t3(d))):d==a.KeyboardEvent.Zi&&this.Rqa(this.mb(this.$t.t3(this.$t.CK)));c&&a.I.sc(b);return c};a.v.D(h,a.yi);h.prototype.getId=function(){return this.xc};h.prototype.jk=function(){return this.l_};h.prototype.rxa=function(a){this.l_=a};h.prototype.Sa=function(){return this.ej};var m={};a.v.D(m,a.v);m.fK=3;m.ta=function(b,c,d){for(var e=b.u(),f=b.IFa().items?b.IFa().items:[],k=b.Nf,l=b.ab(),u=[],D=[],B=0;B<f.length;B++){var C=f[B];if(C){var z=m.HO(e,C.label?C.label:"",k,
B<f.length-1);u.push(z);C=new h(C.id,z);l.lb(z,C);D.push(C);B<f.length-1&&C.rxa(!0)}}b.rDa(u);a.B.da(e)?m.Jdb(b,c,d,u,D):m.Idb(b,c,d,u,D)};m.b$=function(b,c,d){c=new a.ca(b,c,0,0);c.nb(!1);c.Bb(d);var e=d.Tg(a.j.Ww),f=d.Tg(a.j.ns),h=d.Tg(a.j.Vw),k=d.Tg(a.j.Ot),l=a.Mh.jn(b,c);b=new a.Rect(b,0,0,l.a+k+f,l.b+e+h);b.Wb();b.Bb(d);c.Ma(k,e);b.A(c);return b};m.HO=function(b,c,d,e){if(e&&(d.gwa||d.fwa)){var f=new a.j(d.AC);e=new a.j(d.gwa);d=new a.j(d.fwa);f=m.b$(b,c,f);e=m.b$(b,c,e);d=m.b$(b,c,d);b=new a.ia(b,
f,e,d);b.cg("link");b.Gd("label",c)}else e=new a.j(e?d.AC:d.tRa),e.Tg(a.j.Ot)||e.Tg(a.j.ns)||e.Tg(a.j.Ww)||e.Tg(a.j.Vw)?b=m.b$(b,c,e):(b=new a.ca(b,c,0,0),b.Bb(e));return b};m.IJa=function(b){if(b instanceof a.ia)return b=b.pq.hb(0),b.lf();b instanceof a.Rect&&(b=b.hb(0));return b.lf()};m.LPa=function(b,c){if(b instanceof a.ia){var d=b.pq.hb(0);a.Ca.kd(d,Math.max(c-d.qa(),0),Infinity,d.getParent());d=b.rn.hb(0);a.Ca.kd(d,Math.max(c-d.qa(),0),Infinity,d.getParent());d=b.Fm.hb(0);a.Ca.kd(d,Math.max(c-
d.qa(),0),Infinity,d.getParent())}else b instanceof a.Rect?(d=b.hb(0),a.Ca.kd(d,Math.max(c-d.qa(),0),Infinity,d.getParent())):a.Ca.kd(b,c,Infinity,b.getParent())};m.Idb=function(b,c,d,e,f){for(var h=b.Nf,k=b.ab(),l=[],D=0,B=0;B<e.length;B++){c.A(e[B]);var C=e[B].aa();l[B]=C;D=Math.max(C.b,D);c.removeChild(e[B])}for(var z=0,B=0;B<e.length;B++){c.A(e[B]);C=l[B];e[B].Ma(z,.5*(D-C.b));if(a.B.Wa()){var G=new a.Rect(c.u(),-m.fK,-m.fK,C.a+2*m.fK,C.b+2*m.fK);G.Wb();e[B].A(G);B<f.length&&k.lb(G,f[B])}if(z+
C.a>d){b=m.IJa(e[B]);m.LPa(e[B],d-z);B<f.length?f[B].tn(b):k.lb(e[B],new a.yi(b));break}else z+=C.a+h.C8;if(B<e.length-1){C=m.mMa(b);c.A(C);G=C.aa();C.Ma(z,.5*(D-G.b));G=G.a;if(z+G>d){c.removeChild(C);break}z+=G+h.C8}}};m.Jdb=function(b,c,d,e,f){for(var h=b.Nf,k=b.ab(),l=0;l<e.length;l++){c.A(e[l]);var D=e[l].aa();if(a.B.Wa()){var B=new a.Rect(c.u(),-m.fK,-m.fK,D.a+2*m.fK,D.b+2*m.fK);B.Wb();e[l].A(B);l<f.length&&k.lb(B,f[l])}if(0>d-D.a){b=m.IJa(e[l]);m.LPa(e[l],d);e[l].ga(0);l<f.length?f[l].tn(b):
k.lb(e[l],new a.yi(b));break}else e[l].ga(d-D.a),d-=D.a+h.C8;if(l<e.length-1)if(D=m.mMa(b),c.A(D),B=D.aa().a,0>d-B){c.removeChild(D);break}else D.ga(d-B),d-=B+h.C8}};m.mMa=function(b){var c=b.Nf;b=new a.ca(b.u(),c.q6a,0,0);b.Bb(new a.j(c.AC));return b};a.ps=function(b,c){this.Init(a.ps.xe);this.Ts=b;this.D6a=c};a.v.D(a.ps,a.Vg);a.ps.xe="dvtPanelDrawerEvent";a.ps.kT="hide";a.ps.PJ="show";a.ps.prototype.Zn=function(){return this.Ts};a.ea=function(a,b,c,d){this.Init(a,b,c,d)};a.v.D(a.ea,a.la);a.ea.HA=
"left";a.ea.ho="right";a.ea.m6="top";a.ea.OY="bottom";a.ea.Bka=15;a.ea.Eka=0;a.ea.Qk=42;a.ea.N5a=2;a.ea.N2a="#ffffff";a.ea.ZJ="#bbc7d0";a.ea.l8=.25;a.ea.oD=10;a.ea.K2a=1;a.ea.qka=1;a.ea.L2a=1;a.ea.uT=1;a.ea.R2a=1;a.ea.L5a="#dee4e7";a.ea.M5a="#c1cede";a.ea.vT=1.25;a.ea.Yub="alta";a.ea.Nh=24;a.ea.vZ="legend";a.ea.p7="palette";a.ea.ON="search";a.ea.wZ="overview";a.ea.F0a="searchEna";a.ea.G0a="searchOvr";a.ea.E0a="searchDwn";a.ea.Gub="searchTip";a.ea.C0a="paletteEna";a.ea.D0a="paletteOvr";a.ea.B0a="paletteDwn";
a.ea.Fub="paletteTip";a.ea.kCa="legendEna";a.ea.lCa="legendOvr";a.ea.jCa="legendDwn";a.ea.Dub="legendTip";a.ea.z0a="overviewEna";a.ea.A0a="overviewOvr";a.ea.y0a="overviewDwn";a.ea.Eub="overviewTip";a.ea.kN="backgroundAlpha";a.ea.U7="tab-color-inactive";a.ea.Oja="tab-border-color-inactive";a.ea.prototype.Init=function(b,c,f,h){a.ea.C.Init.call(this,b,null,"panelDrawer"+h);this.$fb=h;this.yb=new e(b,c,f);this.yb.Qf(this);this.yb.bI(a.ea);this.yb.lb(this,this);a.B.Wa()||this.yb.Xr(new d(this.yb,this));
this.Cc=c;this.pb=f;this.M1={};this.Ix=[];this.wm=this.wl=Number.MAX_VALUE;this.Fx=5;this.c1=0;this.Z_;this.zH;this.Av=this.Sm=!1;this.Oa;this.IT;this.Ni;this.tma;this.Mn;this.yo;this.xE={};this.GK=a.ea.HA;this.RO=a.ea.m6;this.lH=!1;this.Ka=null;f&&(this.Ka=f.vw());this.Bq=a.Ta.M(this.Ka,a.ea.kN,a.ea.K2a);this.or=a.Ta.M(this.Ka,a.j.ub,a.ea.ZJ);this.Vj=parseInt(a.Ta.M(this.Ka,a.j.dg,a.ea.N5a));this.GG=a.Ta.M(this.Ka,a.j.Lb,a.ea.N2a);this.LGa=a.Ta.M(this.Ka,a.ea.U7,a.ea.L5a);this.NGa=a.Ta.M(this.Ka,
a.ea.Oja,a.ea.M5a);this.md();this.lx=a.ea.oD};a.ea.prototype.yW=function(b,c,d,e,f,h){this.M1[h]={panel:b,iconUp:c,iconOver:d,iconDown:e,tooltip:f};this.Ix.push(h);this.c1=a.ea.Bka+this.Ix.length*(a.ea.Qk+a.ea.Eka)};a.ea.prototype.Wrb=function(a){this.lH=a};a.ea.prototype.wA=function(a){this.wl=a};a.ea.prototype.Frb=function(){this.lx=0};a.ea.prototype.N3=function(){return this.wl-2*this.lx};a.ea.prototype.j5=function(a){this.wm=a};a.ea.prototype.aX=function(){return this.wm-2*this.lx};a.ea.prototype.Lfa=
function(a){this.GK=a};a.ea.prototype.nWa=function(a){this.RO=a};a.ea.prototype.bZ=function(a){return this.M1[a].panel};a.ea.prototype.$Y=function(a){return this.M1[a].icon};a.ea.prototype.yAa=function(a){return this.M1[a].tooltip};a.ea.prototype.BN=function(a){return this.xE[a]};a.ea.prototype.a5=function(a,b,c){this.zH=this.Z_;this.Z_=a;this.Ab()&&(this.CY(),this.Lya(a,b,c));this.zH=null};a.ea.prototype.QE=function(){var a=this.Z_;return!a&&0<this.Ix.length?this.Ix[0]:a};a.ea.prototype.Di=function(a,
b,c){if(!this.Av){var d=this.Sm;this.Sm=a;d!=a&&(this.Av=!0,a?this.SYa(b,c):this.RYa(b,c))}};a.ea.prototype.Ab=function(){return this.Sm};a.ea.prototype.Dw=function(){this.Oa||(this.Oa=new a.la(this.u(),"pd_contentPane"),this.A(this.Oa),this.IT=new a.la(this.u(),"pdcp_activeContent"),this.Oa.A(this.IT));this.b1a()};a.ea.prototype.b1a=function(){if(!this.lH){var b=-a.ea.Qk;this.GK==a.ea.ho&&(b=0);var c=a.ea.Bka;if(this.RO==a.ea.m6)for(var d=0;d<this.Ix.length;d++){var e=this.Ix[d],e=this.SCa(e);e.Ma(b,
c);c+=a.ea.Qk+a.ea.Eka}else if(this.RO==a.ea.OY)for(c=-a.ea.Bka-a.ea.Qk,d=this.Ix.length-1;0<=d;d--)e=this.Ix[d],e=this.SCa(e),e.Ma(b,c),c-=a.ea.Qk+a.ea.Eka}};a.ea.prototype.IZa=function(){var b;switch(this.GK){case a.ea.ho:b=["M",0,0,"L",a.ea.Qk-this.Vj,0,"A",this.Vj,this.Vj,0,0,1,a.ea.Qk,this.Vj,"L",a.ea.Qk,a.ea.Qk-this.Vj,"A",this.Vj,this.Vj,0,0,1,a.ea.Qk-this.Vj,a.ea.Qk,"L",0,a.ea.Qk];break;default:b=["M",a.ea.Qk,0,"L",this.Vj,0,"A",this.Vj,this.Vj,0,0,0,0,this.Vj,"L",0,a.ea.Qk-this.Vj,"A",this.Vj,
this.Vj,0,0,0,this.Vj,a.ea.Qk,"L",a.ea.Qk,a.ea.Qk]}return b};a.ea.prototype.SCa=function(b){var c=this.IZa(),d=new f(this.u(),c,b,this);d.md();d.setCursor("pointer");this.Oa.Ib(d,0);d.fb(this.LGa,this.Bq);d.Vb(this.NGa,a.ea.uT,1);var e=this.M1[b],h=new a.vb(this.u(),c);h.Wb();e.iconUp.Ma(.5*(a.ea.Qk-a.ea.Nh),.5*(a.ea.Qk-a.ea.Nh));h.A(e.iconUp);var k=new a.vb(this.u(),c);k.Wb();e.iconOver.Ma(.5*(a.ea.Qk-a.ea.Nh),.5*(a.ea.Qk-a.ea.Nh));k.A(e.iconOver);c=new a.vb(this.u(),c);c.Wb();e.iconDown.Ma(.5*(a.ea.Qk-
a.ea.Nh),.5*(a.ea.Qk-a.ea.Nh));c.A(e.iconDown);h=new a.ia(this.u(),h,k,c);h.t5();e.icon=h;d.A(h);this.xE[b]=d;var l=this;this.yb.lb(d,{jh:function(){l.j_a(b)},Ui:function(){return l.yAa(b)}});d.hw();return d};a.ea.prototype.j_a=function(b){function c(){var a=e.u().Af();a&&a.qe()}this.zH=this.QE();this.Z_=b;var d=this.BN(b).Kd(),e=this;this.Ab()?this.zH==b?this.Di(!1,!1,c):(this.CY(),this.Lya(b,!1)):(this.Di(!0,!1,c),this.jN());this.zH=null;this.Te(new a.ps(this.Ab()?a.ps.PJ:a.ps.kT,this.Z_));d&&this.u().SX(this)};
a.ea.prototype.Lya=function(b,c,d){var e=null;c||(e=new a.G(this.u(),a.ea.l8));this.zH&&(c=this.bZ(this.zH))&&this.oz.removeChild(c);this.kza(b,e);e?(this.jN(),d&&a.eb.Mb(e,d),e.play()):d&&d()};a.ea.prototype.SYa=function(b,c){this.kza(this.QE());var d=-(1/a.ea.vT*this.Ni.getWidth());this.GK==a.ea.ho&&(d=-d,this.Ni.Fa((1/a.ea.vT-1)*this.Ni.getWidth()));if(b)this.Oa.ga(d),c&&c(),this.Av=!1;else{var e=new a.G(this.u(),a.ea.l8);e.wp(a.Je.R2);e.N(a.G.V,this.Oa,this.Oa.qa,this.Oa.ga,d);c&&a.eb.Mb(e,c);
if(e){var f=this;a.eb.Mb(e,function(){f.Av=!1});e.play()}}this.CY()};a.ea.prototype.RYa=function(b,c){if(b)this.Oa.ga(0),this.KCa(),c&&c(),this.CY(),this.Av=!1;else{var d=new a.G(this.u(),a.ea.l8);d.wp(a.Je.Osa);d.N(a.G.V,this.Oa,this.Oa.qa,this.Oa.ga,0);a.eb.Mb(d,this.KCa,this);a.eb.Mb(d,this.CY,this);c&&a.eb.Mb(d,c);var e=this;a.eb.Mb(d,function(){e.Av=!1});d.play()}};a.ea.prototype.KCa=function(){this.Ni&&(this.tma=null,this.oz.Hl(),this.IT.MX(),this.Ni.xa(),this.IT.removeChild(this.Ni),this.yo=
this.Mn=this.oz=this.Ni=null)};a.ea.prototype.kza=function(b,c){this.Ni||(this.Ni=new a.Rect(this.u(),0,0,1,1,"pdcp_expandedContent"),this.IT.A(this.Ni),this.Ni.fb(this.GG,this.Bq),this.oz=new a.la(this.Aa),this.Ni.A(this.oz),this.oz.Ma(this.lx,this.lx));var d=this.bZ(b);if(d){this.oz.A(d);if(this.zH){var e=this.bZ(this.zH);e&&e.jc(a.Gn.IJ,this.TAa,!1,this)}d.Ya(a.Gn.IJ,this.TAa,!1,this)}this.Mn||(this.Mn=new a.vb(this.u(),["M",0,0,"L",1,1],"pdcp_expandedBorder"),this.yo=new a.vb(this.u(),["M",0,
0,"L",1,1],"pdcp_expandedBorderResizable"),this.Ni.A(this.Mn),this.Ni.A(this.yo),this.Mn.Vb(this.or,a.ea.uT),this.Mn.ra(null),this.yo.Vb(this.or,a.ea.uT),this.yo.ra(null),this.Mn.md(),this.yo.md());this.Z0a(b,c)};a.ea.prototype.TAa=function(b){var c=new a.G(this.u(),a.ea.l8),d=b.getWidth(),e=b.getHeight(),d=this.nAa(d),e=this.Eha(e),f=b.Va()?b.Va():0;b=b.ib()?b.ib():0;this.VNa(this.QE(),c,d,e,f,b);c.play()};a.ea.prototype.Z0a=function(a,b){var c=this.bZ(a),d=2*this.lx,e=2*this.lx,f=0,h=0;c&&(c=c.jC?
c.jC():c.hq(),d=this.nAa(c.a),e=this.Eha(c.b),f=c.x,h=c.y);this.VNa(a,b,d,e,f,h)};a.ea.prototype.VNa=function(b,c,d,e,f,h){var k=this.bZ(b);c?c.N(a.G.V,k,k.qa,k.ga,-f):k.ga(-f);c?c.N(a.G.V,k,k.pa,k.wa,-h):k.wa(-h);f=new a.Z(this.lx,this.lx,d-2*this.lx,e-2*this.lx);h=a.ea.vT*d;c?(c.N(a.G.V,this.Ni,this.Ni.getWidth,this.Ni.Xa,h),c.N(a.G.V,this.Ni,this.Ni.getHeight,this.Ni.qb,e),c.N(a.G.mD,this,this.I$a,this.KOa,f),this.GK==a.ea.HA?c.N(a.G.V,this.Oa,this.Oa.qa,this.Oa.ga,-d):this.GK==a.ea.ho&&(c.N(a.G.V,
this.Oa,this.Oa.qa,this.Oa.ga,d),c.N(a.G.V,this.Mn,this.Mn.qa,this.Mn.ga,d),c.N(a.G.V,this.yo,this.yo.qa,this.yo.ga,d),c.N(a.G.V,this.Ni,this.Ni.qa,this.Ni.ga,-d)),this.RO==a.ea.OY&&(c.N(a.G.V,this.Mn,this.Mn.pa,this.Mn.wa,e),c.N(a.G.V,this.yo,this.yo.pa,this.yo.wa,e),c.N(a.G.V,this.Ni,this.Ni.pa,this.Ni.wa,-e))):(this.Ni.Xa(h),this.Ni.qb(e),this.GK==a.ea.ho&&(this.Ni.ga(-d),this.Mn.ga(d),this.yo.ga(d)),this.RO==a.ea.OY&&(this.Ni.wa(-e),this.Mn.wa(e),this.yo.wa(e)),this.KOa(f));f=this.BN(b);var l;
b=d;this.GK==a.ea.ho&&(b=-d);this.RO==a.ea.m6?f?(l=["M",0,0,"L",0,f.pa(),"M",0,f.pa()+a.ea.Qk],d=this.BN(this.Ix[this.Ix.length-1]),l.push("L",0,d.pa()+a.ea.Qk),this.Mn.ut(l),b*=a.ea.vT,l=["M",0,d.pa()+a.ea.Qk,"L",0,e,"L",b,e]):(l=["M",0,0,"L",0,e,"L",b,e],this.Mn.ut(l)):this.RO==a.ea.OY&&(f?(l=["M",0,0,"L",0,f.pa()+a.ea.Qk,"M",0,f.pa()],d=this.BN(this.Ix[0]),l.push("L",0,d.pa()),this.Mn.ut(l),b*=a.ea.vT,l=["M",0,d.pa(),"L",0,-e,"L",b,-e]):(l=["M",0,0,"L",0,-e,"L",b,-e],this.Mn.ut(l)));c?c.N(a.G.lm,
this.yo,this.yo.VQ,this.yo.ut,l):this.yo.ut(l)};a.ea.prototype.KOa=function(b){if(this.oz&&b){var c=new a.Cd("pdcp"+this.$fb);c.Pe(b.x,b.y,b.a,b.b);this.oz.te(c)}this.tma=b};a.ea.prototype.I$a=function(){return this.tma};a.ea.prototype.nAa=function(a){a+=2*this.lx;(this.Fx||0==this.Fx)&&a<this.Fx&&(a=this.Fx);this.wl&&a>this.wl&&(a=this.wl);return a};a.ea.prototype.Eha=function(a){a+=2*this.lx;(this.c1||0==this.c1)&&a<this.c1&&(a=this.c1);this.wm&&a>this.wm&&(a=this.wm);return a};a.ea.prototype.F5=
function(a){if(this.Ni){var b=this.Ni.fd().clone();b.T(a);this.Ni.ra(b)}for(var c in this.xE){var d=this.xE[c];d&&(b=d.fd().clone(),b.T(a),d.ra(b))}};a.ea.prototype.qya=function(a){if(this.Mn){var b=this.Mn.Ud().clone();b.T(a);this.Mn.Ga(b)}this.yo&&(b=this.yo.Ud().clone(),b.T(a),this.yo.Ga(b));for(var c in this.xE){var d=this.xE[c];d&&(b=d.Ud().clone(),b.T(a),d.Ga(b))}};a.ea.prototype.gta=function(){this.nb(!1);this.F5(a.ea.qka);this.qya(a.ea.R2a);this.oz&&this.oz.T(a.ea.qka);for(var b in this.xE){var c=
this.$Y(b);c&&c.T(a.ea.qka)}};a.ea.prototype.fta=function(){this.nb(!0);this.F5(this.Bq);this.qya(a.ea.uT);this.oz&&this.oz.T(1);for(var b in this.xE){var c=this.$Y(b);c&&c.T(1)}this.kv(null)};a.ea.prototype.Hy=function(){this.jN()};a.ea.prototype.kv=function(){this.wO||this.tga()};a.ea.prototype.jN=function(){this.F5(a.ea.L2a)};a.ea.prototype.tga=function(){this.F5(this.Bq)};a.ea.prototype.CY=function(){for(var b in this.xE){var c=this.xE[b];c&&(b==this.QE()&&this.Ab()?(c.fb(this.GG,this.Bq),c.Vb(this.or,
a.ea.uT),c.Di(!0)):(c.fb(this.LGa,this.Bq),c.Vb(this.NGa,a.ea.uT),c.Di(!1)));var d=this.Ab()&&b==this.QE(),e=this.$Y(b);e&&e.Wu(d);d?this.IT.A(c):this.Oa.Ib(c,0)}};a.ea.prototype.Vfa=function(a){if(!this.Opa||this.Opa<a)this.Opa=a};a.ea.prototype.Klb=function(){return this.Eha(this.Opa)};a.ea.prototype.aa=function(b){b=a.ea.C.aa.call(this,b);b.a/=a.ea.vT;return b};a.ea.prototype.ab=function(){return this.yb};a.v.D(f,a.vb);f.prototype.Init=function(a,b,c,d){f.C.Init.call(this,a,b);this.Sc=d;this.kP=
!1;this.sdb=c};f.prototype.hm=function(b){var c=b.keyCode;if(c==a.KeyboardEvent.Zi||c==a.KeyboardEvent.ni){var c=this.Sc.ab(),d=this.Ld(new a.R(0,0));b=a.yn.PQ(b,this.Aa,a.MouseEvent.Be,d.x,d.y);b.target=this;c.eT(b)}};f.prototype.Ab=function(){return this.kP};f.prototype.Di=function(a){this.kP!=a?(this.kP=a,this.Nxa()):this.kP=a};f.prototype.Ed=function(){var b=[];b.push(this.Ab()?a.H.va(a.H.Ha,"STATE_EXPANDED"):a.H.va(a.H.Ha,"STATE_COLLAPSED"));return a.oa.Ik(this.Sc.yAa(this.sdb),b)};f.prototype.hw=
function(){this.cg("button");a.B.kj()||this.Gd("label",this.Ed())};f.prototype.Nxa=function(){a.B.kj()||this.Gd("label",this.Ed())};f.prototype.rf=function(a){return this.aa(a)};f.prototype.Jm=function(){return this.Ua()};f.prototype.Sf=function(){this.dd=!0;this.Jq||this.d$();this.Jq.show();this.Aa.NI(this)};f.prototype.Qd=function(){this.dd=!1;this.Jq||this.d$();this.Jq.Vq()};f.prototype.Kd=function(){return this.dd};f.prototype.Fd=function(a){return this.Sc.ab().Cb.Fd(this,a)};f.prototype.d$=function(){var b=
this.aa();this.Jq=new a.im(this.u(),this,new a.Z(b.x+1,b.y+1,b.a-2,b.b-2),null,null,!0)};a.v.D(e,a.I);e.prototype.Tj=function(a){var b=this.mb(this.ne(a));e.C.Tj.call(this,a);b&&(b.jh&&b.jh(a),a.stopPropagation())};e.prototype.aG=function(a){var b=this.mb(this.ne(a));b&&(b.kl&&b.kl()&&b.jv&&b.jv(a),a.stopPropagation())};e.prototype.cG=function(a){e.C.cG.call(this,a);var b=this.mb(this.ne(a));b&&b.Hy&&b.Hy(a)};e.prototype.bG=function(a){e.C.bG.call(this,a);var b=this.mb(this.ne(a));b&&b.kv&&b.kv(a)};
e.prototype.CJ=function(a){var b=this.mb(this.ne(a));e.C.CJ.call(this,a);b&&(b.jh&&b.jh(a),a.stopPropagation())};a.v.D(d,a.Cb);d.prototype.Init=function(a,b){d.C.Init.call(this,a);this.Sc=b};d.prototype.mk=function(b){var c=b.keyCode,e=this.yb.jf();return c==a.KeyboardEvent.Qh?(c=null,a.I.sc(b),c=e?e:this.Sc.BN(this.Sc.Ix[0])):c==a.KeyboardEvent.Zi||c==a.KeyboardEvent.ni?(e.hm(b),null):d.C.mk.call(this,b)};d.prototype.Fd=function(b,c){if(c.keyCode!=a.KeyboardEvent.Tf&&c.keyCode!=a.KeyboardEvent.kh)return b;
for(var d=b,e=c.keyCode==a.KeyboardEvent.Tf?!0:!1,f=this.Sc.Ix,h=-1,k=0;k<f.length;k++)if(b==this.Sc.BN(f[k])){h=e?k==f.length-1?-1:k+1:0==k?-1:k-1;break}0<=h&&(d=this.Sc.BN(f[h]));return d};a.Lh=function(a,b,c,d,e,f,h){this.Init(a,b,c,d,e,f,h)};a.v.D(a.Lh,a.la);a.Lh.yya="sectionColEna";a.Lh.zya="sectionColOvr";a.Lh.xya="sectionColDwn";a.Lh.Bza="sectionExpEna";a.Lh.Cza="sectionExpOvr";a.Lh.Aza="sectionExpDwn";a.Lh.prototype.Init=function(b,d,e,f,h,k,l){a.Lh.C.Init.call(this,b,null,d);this.vr=k;this.Ka=
(new c).en(l);this.COa={};this.TB=[];this.wl=e;this.Fx=0;this.wm=f;this.h9=this.Dla=!1;this.yb=h};a.Lh.prototype.mQa=function(b,c,d,e){e||(e="accordion_"+b.replace(/ /g,"_")+Math.floor(1E9*Math.random()));b=new a.Ei(this.u(),c,b,d,!0,this,this.yb,e,this.vr,this.Ka);this.COa[e]=b;this.TB.push(e);this.A(b)};a.Lh.prototype.ta=function(){for(var a=this.eTa(),b=!1,c=0;c<this.TB.length;c++){var d=this.zM(c);d.ta(a);b&&!this.h9&&d.setActive(!1);d.yx&&d.zR()&&(b=!0)}!b&&0<this.TB.length&&!this.Dla&&this.zM(0).setActive(!0);
this.pIa()};a.Lh.prototype.j5=function(a){this.wm=a};a.Lh.prototype.wA=function(a){this.wl=a};a.Lh.prototype.msb=function(a){this.Fx=a};a.Lh.prototype.update=function(a){a=this.Sua(a);var b=a.yx;if(b)b&&this.l8a(a)&&a.setActive(!1);else{if(!this.h9)for(b=0;b<this.TB.length;b++)this.zM(b).setActive(!1);a.setActive(!0)}this.pIa()};a.Lh.prototype.eTa=function(){if(!this.VLa){for(var a=0,b=this.Ka.paddingX,c=0;c<this.TB.length;c++){var d=this.zM(c),e=d.JZa();e.a>a&&(a=e.a);d=d.jC().a+2*b;d>a&&(a=d)}a=
Math.min(a,this.wl);this.VLa=a=Math.max(a,this.Fx)}return this.VLa};a.Lh.prototype.$ta=function(){if(!this.wm){for(var a=0,b=0,c=0;c<this.TB.length;c++){var d=this.zM(c),e=d.Zkb().b;if(d.zR()&&e>a)a=e;else if(!d.zR()||this.h9)b+=e}this.wm=a+b}return this.wm};a.Lh.prototype.zM=function(a){return 0<=a&&a<this.TB.length?this.Sua(this.TB[a]):null};a.Lh.prototype.Sua=function(a){return this.COa[a]};a.Lh.prototype.Vrb=function(){this.h9=!0};a.Lh.prototype.Arb=function(){this.Dla=!0};a.Lh.prototype.l8a=
function(a){if(a.zR()){if(this.Dla)return!0;for(var b=0,c=0;c<this.TB.length;c++)a=this.zM(c),a.yx&&b++;return 1<b}return!1};a.Lh.prototype.pIa=function(){for(var b=0,c=0;c<this.TB.length;c++){var d=this.zM(c);d.wa(b);d.yx?(d.expand(),b+=d.hq().b,b+=this.Ka.paddingY):(d.collapse(),b+=this.Ka.sectionHeader.headerHeight)}b=this.hq();this.Te(new a.Gn(b.a,b.b,0,0))};a.Lh.prototype.oea=function(){for(var a=[],b=0;b<this.TB.length;b++)a.push(this.zM(b));return a};a.Ei=function(a,b,c,d,e,f,h,k,l,m){this.Init(a,
b,c,d,e,f,h,k,l,m)};a.v.D(a.Ei,a.la);a.Ei.prototype.Init=function(b,c,d,e,f,h,k,l,m,B){a.Ei.C.Init.call(this,b,null,l);this.Ck=h;this.vr=m;this.Vn=d;this.xc=l;this.al=c;this.lB=this.tB=null;this.yx=(this.Tbb=f)?e:!0;this.yb=k;this.Ka=B;this.hP=this.Ka.sectionHeader.headerHeight;this.mba=this.Ka.paddingX;this.nba=this.Ka.paddingY;this.xPa=this.Ka.sectionHeader.styleEna;this.DKa=this.Ka.sectionHeader.imageWidth;this.Hbb=this.Ka.sectionHeader.imageHeight;this.lgb=this.Ka.sectionHeader.textPadding};a.Ei.prototype.getId=
function(){return this.xc};a.Ei.prototype.pC=function(){return this.Vn};a.Ei.prototype.setActive=function(a){this.yx=a};a.Ei.prototype.zR=function(){return this.Tbb};a.Ei.prototype.jC=function(){var a=null;0>this.Bi(this.al)?(this.A(this.al),a=this.al.aa(),this.removeChild(this.al)):a=this.al.aa();return a};a.Ei.prototype.Zkb=function(){var a=null;0>this.Bi(this.al)?(this.A(this.al),this.al.ga(this.mba),this.al.wa(this.hP+this.nba),a=this.hq(),this.removeChild(this.al)):a=this.hq();return a};a.Ei.prototype.ta=
function(a){this.W8a(a,this.hP);this.zR()?this.yx?(this.Ib(this.tB,0),this.A(this.al),this.al.ga(this.mba),this.al.wa(this.hP+this.nba)):this.A(this.lB):(this.Ib(this.Aoa,0),this.A(this.al),this.al.ga(this.mba),this.al.wa(this.hP+this.nba))};a.Ei.prototype.collapse=function(){this.zR()&&(0<=this.Bi(this.tB)&&this.removeChild(this.tB),0<=this.Bi(this.al)&&this.removeChild(this.al),this.A(this.lB),this.setActive(!1),this.Kd()&&this.Sf())};a.Ei.prototype.expand=function(){0<=this.Bi(this.lB)&&this.removeChild(this.lB);
this.A(this.tB);this.A(this.al);this.al.ga(this.mba);this.al.wa(this.hP+this.nba);this.setActive(!0);this.Kd()&&this.Sf()};a.Ei.prototype.JZa=function(){if(!this.gW){var b=new a.ca(this.Aa,this.Vn);b.Bb(this.xPa);if(b=b.Pc())b.a=b.a+this.DKa+this.lgb;this.gW=b}return this.gW};a.Ei.prototype.G1a=function(a){if(!this.gW||this.gW.a<a.a||this.gW.b<a.b)this.gW=a};a.Ei.prototype.W8a=function(b,c){if(this.zR()){var d,e,f;this.vr.X?(d=this.ez(a.ia.od,this.vr.X(a.Lh.Bza),this.Vn,b,c),e=this.ez(a.ia.Yd,this.vr.X(a.Lh.Cza),
this.Vn,b,c),f=this.ez(a.ia.Hd,this.vr.X(a.Lh.Aza),this.Vn,b,c)):(d=this.ez(a.ia.od,this.vr[a.Lh.Bza],this.Vn,b,c),e=this.ez(a.ia.Yd,this.vr[a.Lh.Cza],this.Vn,b,c),f=this.ez(a.ia.Hd,this.vr[a.Lh.Aza],this.Vn,b,c));this.tB=new a.ia(this.Aa,d,e,f);this.tB.cg("button");d=a.oa.Ik(this.Vn,[a.H.va(a.H.Ha,"STATE_EXPANDED")]);this.tB.Gd("label",d);this.vr.X?(d=this.ez(a.ia.od,this.vr.X(a.Lh.yya),this.Vn,b,c),e=this.ez(a.ia.Yd,this.vr.X(a.Lh.zya),this.Vn,b,c),f=this.ez(a.ia.Hd,this.vr.X(a.Lh.xya),this.Vn,
b,c)):(d=this.ez(a.ia.od,this.vr[a.Lh.yya],this.Vn,b,c),e=this.ez(a.ia.Yd,this.vr[a.Lh.zya],this.Vn,b,c),f=this.ez(a.ia.Hd,this.vr[a.Lh.xya],this.Vn,b,c));this.lB=new a.ia(this.Aa,d,e,f);this.lB.cg("button");d=a.oa.Ik(this.Vn,[a.H.va(a.H.Ha,"STATE_COLLAPSED")]);this.lB.Gd("label",d);this.yb.lb(this.tB,this);this.yb.lb(this.lB,this)}else d=this.DHa(a.ia.Oy,b,c),e=this.EHa(this.Vn),this.Aoa=new a.la(this.Aa),this.Aoa.A(d),this.Aoa.A(e)};a.Ei.prototype.ez=function(b,c,d,e,f){var h=this.DKa,k=this.Hbb,
l=(this.hP-k)/2,m=new a.la(this.Aa);b=this.DHa(b,e,f);m.A(b);(c=c?new a.Image(this.Aa,c,0,l,h,k):null)&&m.A(c);d=this.EHa(d,e-h-0,f,m);a.B.da(this.Aa)?(f=d.Pc(),d.ga(e-f.a-h),c&&c.ga(e-h)):d.ga(h);this.Jq||this.d$(c?c:d);return m};a.Ei.prototype.EHa=function(b,c,d,e){var f=null;b&&(f=new a.ca(this.Aa,b),f.Bb(this.xPa),a.Ca.kd(f,c,d,e),b=f.Pc(),this.G1a(b),f.wa((this.hP-b.b)/2));return f};a.Ei.prototype.DHa=function(b,c,d){var e=null;switch(b){case a.ia.Yd:e=this.Ka.sectionHeader.styleOvr;break;case a.ia.Hd:e=
this.Ka.sectionHeader.styleDwn;break;case a.ia.Oy:e=this.Ka.sectionHeader.styleDis;break;default:e=this.Ka.sectionHeader.styleEna}b=new a.Rect(this.Aa,0,0,c,d);b.Ga(a.Ei.Qab(e));b.ra(a.Ei.X$a(e));return b};a.Ei.X$a=function(b){var c=b.M(a.j.Lb);b=b.NW();var d=null;if(b&&b instanceof a.Gt){var c=b.zq,d=b.yq,e=b.vG;b=b.fq();d=new a.bd(b,c,d,e)}else c&&(d=new a.$b(c,1));return d};a.Ei.Qab=function(b){b=b.M(a.j.ub);return new a.ya(b,1,1)};a.Ei.prototype.rf=function(){var b=this.yx?this.tB:this.lB,c=b.aa(),
d=b.Ld(new a.R(c.x,c.y)),b=b.Ld(new a.R(c.x+c.a,c.y+c.b));return new a.Z(d.x,d.y,b.x-d.x,b.y-d.y)};a.Ei.prototype.Jm=function(){return(this.yx?this.tB:this.lB).Ua()};a.Ei.prototype.Sf=function(){this.dd=!0;this.Jq.show();this.Aa.NI(this.yx?this.tB:this.lB)};a.Ei.prototype.Qd=function(){this.dd=!1;this.Jq.Vq()};a.Ei.prototype.Kd=function(){return this.dd};a.Ei.prototype.Fd=function(a){return this.yb.Cb.Fd(this,a)};a.Ei.prototype.d$=function(b){var c=b.aa(),d=b.qa()||c.x;b=b.pa()||c.y;this.Jq=new a.im(this.u(),
this,new a.Z(d,b,c.a,c.b),null,null,!0)};a.v.D(c,a.bb);c.lh={skin:a.j.mf,sectionHeader:{styleEna:new a.j(a.bb.yN+"color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleOvr:new a.j(a.bb.yN+"color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleDwn:new a.j(a.bb.yN+"color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),styleDis:new a.j(a.bb.yN+"color:#252525;border-color:#D9DFE3;background-color:#F5F5F5;"),headerHeight:33,imageWidth:24,imageHeight:24,textPadding:5},
paddingX:0,paddingY:0};c.mf={};a.pg=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};a.v.D(a.pg,a.la);a.pg.X1a="dvtTrain";a.pg.Gza="#c0cbd5";a.pg.ub="#5d7891";a.pg.q1a="#61bde3";a.pg.p1a="#0066ff";a.pg.FXa=8;a.pg.l2a=1;a.pg.BAa=3;a.pg.od=0;a.pg.u1a=1;a.pg.G7=2;a.pg.prototype.Init=function(b,c,d,e,f,h){a.pg.C.Init.call(this,b,null,f);this.aC=b.Af();this.Rn=d;this.uK=e;this.X9=d.length;this.HG=Array(this.X9);this.cw=0;this.Qbb=h;this.VN(c)};a.pg.prototype.o5=function(a){0<=a&&a<this.X9&&this.pDa(this.cw,
a)};a.pg.prototype.jh=function(b){a.I.sc(b);for(var c=0;c<this.HG.length;c++){var d=b.target;if(this.HG[c]===d||this.HG[c]===d.getParent()){b=this.cw;this.pDa(b,c);b!=c&&this.Bjb();break}}};a.pg.prototype.pDa=function(a,b){this.cw=b;var c=this.HG[a];c&&(c.rn&&c.rn.setCursor("pointer"),c.Fm&&c.Fm.setCursor("pointer"),c.Wu(!1));if(c=this.HG[b])c.rn&&c.rn.setCursor("default"),c.Fm&&c.Fm.setCursor("default"),c.Wu(!0)};a.pg.prototype.yhb=function(b,c){this.Ya(a.pg.X1a,b,!1,c)};a.pg.prototype.Bjb=function(){var a=
new b(this.cw);this.Te(a,!1)};a.pg.prototype.VN=function(b){for(var c=a.B.da(this.u()),d=this.z$a(),e=0;e<this.X9;e++){var f;f=this.SC(d,e==this.cw,this.Rn[e]);this.Ygb(f);var h=e;c&&(h=this.X9-1-e);b&&b.lb(f,f);f.Ma(h*(d+a.pg.BAa),this.Qbb?0:a.pg.l2a);this.A(f);this.HG[e]=f}};a.pg.prototype.UYa=function(b,c){var d,e,f,h;c?(h=0,f=a.pg.q1a,e=a.pg.p1a,this.uK&&(d=this.uK[a.pg.G7])):(h=1,f=a.pg.Gza,e=a.pg.ub,this.uK&&(d=this.uK[a.pg.od]));d&&(d.M(a.j.ub)&&(e=d.M(a.j.ub)),d.M(a.j.Lb)&&(f=d.M(a.j.Lb)));
d=new a.Rect(this.u(),h,h,b-2*h,b-2*h);d.fb(f);d.Vb(e);return d};a.pg.prototype.Ygb=function(b){b.Ya(a.TouchEvent.$i,this.jh,!1,this);a.B.Wa()||b.Ya(a.MouseEvent.Be,this.jh,!1,this)};a.pg.prototype.z$a=function(){if(!this.G9){if(this.uK){var b=this.uK[0];b&&(this.G9=a.j.pk(b.getWidth()))}this.G9||(this.G9=a.pg.FXa)}return this.G9};a.pg.prototype.Ay=function(b,c){return new a.Image(this.u(),b,0,0,c,c)};a.pg.prototype.sia=function(b,c,d){var e=this.uK?this.uK[c]:null;b=(e=e?e.ASa():null)?this.Ay(e,
b):this.UYa(b,c==a.pg.G7);b.setCursor(c==a.pg.od||d?"default":"pointer");return b};a.pg.prototype.SC=function(b,c,d){b=new a.ia(this.u(),this.sia(b,a.pg.od,c),this.sia(b,a.pg.u1a,c),this.sia(b,a.pg.G7,c),null);b.tn(d);b.t5();c&&b.Wu(c);return b};a.v.D(b,a.Vg);b.xe="dvtTrain";b.prototype.kb=function(){return this.fp};a.Fg=function(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)};a.v.D(a.Fg,a.la);a.Fg.lka="viewport-bg-color";a.Fg.mka="viewport-border-color";a.Fg.$Ba="isOverviewDisclosed";a.Fg.prototype.Init=function(b,
c,d,e,f,h){a.Fg.C.Init.call(this,b,null,c);this.zc=d;this.ed=e;this.lp=f;this.Pp=h;this.NL=null};a.Fg.prototype.ta=function(){this.a1=!1;this.Dqa=!0;this.ee&&(a.B.Wa()?(this.ee.jc(a.TouchEvent.$i,this.Uaa,!1,this),this.ee.jc(a.TouchEvent.Xo,this.Vaa,!1,this),this.ee.jc(a.TouchEvent.Rm,this.g1,!1,this)):(this.ee.jc(a.MouseEvent.Ro,this.Uaa,!1,this),this.ee.jc(a.MouseEvent.Mt,this.Vaa,!1,this),this.ee.jc(a.MouseEvent.So,this.g1,!1,this),this.ee.jc(a.MouseEvent.xi,this.fMa,!1,this)),this.ee.te(null));
this.Hl();this.ee=this.ah=null;var b=new a.Cd(this.getId());b.Pe(0,0,this.lp,this.Pp);this.ee=new a.Rect(this.Aa,0,0,this.lp,this.Pp);this.ee.te(b);this.ee.Wb();this.A(this.ee);this.ah=new a.Rect(this.Aa,0,0,0,0,this.getId()+":viewport");b=this.tea(a.Fg.lka);this.ah.Vb(this.tea(a.Fg.mka),null,2);this.ah.fb(b);this.ah.nb(!1);this.ee.A(this.ah);a.B.Wa()?(this.ee.Ya(a.TouchEvent.$i,this.Uaa,!1,this),this.ee.Ya(a.TouchEvent.Xo,this.Vaa,!1,this),this.ee.Ya(a.TouchEvent.Rm,this.g1,!1,this)):(this.ee.Ya(a.MouseEvent.Ro,
this.Uaa,!1,this),this.ee.Ya(a.MouseEvent.Mt,this.Vaa,!1,this),this.ee.Ya(a.MouseEvent.So,this.g1,!1,this),this.ee.Ya(a.MouseEvent.xi,this.fMa,!1,this))};a.Fg.prototype.Yob=function(a){this.kP="true"==a.X("disclosed")};a.Fg.prototype.Ab=function(){return this.kP};a.Fg.prototype.Di=function(a){this.kP=a};a.Fg.prototype.mSa=function(){return this.jC().a};a.Fg.prototype.lSa=function(){return this.jC().b};a.Fg.prototype.jC=function(){return new a.Z(this.zc,this.ed,this.lp,this.Pp)};a.Fg.prototype.dS=
function(b,c){var d=this.TDa(b.x,b.y,c),e=this.TDa(b.x+b.a,b.y+b.b,c),f=d.x,h=d.y,k=e.x-d.x,d=e.y-d.y;c?(c.N(a.G.V,this.ah,this.ah.Va,this.ah.Fa,f),c.N(a.G.V,this.ah,this.ah.ib,this.ah.jb,h),c.N(a.G.V,this.ah,this.ah.getWidth,this.ah.Xa,k),c.N(a.G.V,this.ah,this.ah.getHeight,this.ah.qb,d)):(this.ah.Fa(f),this.ah.jb(h),this.ah.Xa(k),this.ah.qb(d))};a.Fg.prototype.nva=function(){var b=this.i8(this.ah.Va(),this.ah.ib()),c=this.i8(this.ah.Va()+this.ah.getWidth(),this.ah.ib()+this.ah.getHeight());return new a.Z(b.x,
b.y,c.x-b.x,c.y-b.y)};a.Fg.prototype.Drb=function(a){var b=this.nva();this.sm&&this.ee.removeChild(this.sm);this.sm=a;this.ee.Ib(a,0);this.dS(b)};a.Fg.prototype.Uaa=function(b){if(!this.a1&&this.Dqa){this.a1=!0;var c=this.Oi(b);b=new a.WJ(this.nva(),this.lJa(c),b);this.Te(b)}};a.Fg.prototype.Vaa=function(b){if(this.a1&&this.Dqa){var c=this.Oi(b);b=new a.WJ(this.nva(),this.lJa(c),b);this.Te(b)}};a.Fg.prototype.g1=function(){this.a1&&this.Dqa&&(this.a1=!1)};a.Fg.prototype.fMa=function(){this.g1()};
a.Fg.prototype.Oi=function(b){var c,d;a.B.Wa()?(b=b.touches,0<b.length&&(c=b[0].pageX,d=b[0].pageY)):(c=b.pageX,d=b.pageY);return this.Aa.eh(c,d)};a.Fg.prototype.i8=function(b,c){var d=0,e=0,f=1,h=1;this.sm&&(d=this.sm.qa(),e=this.sm.pa(),f=this.sm.oe(),h=this.sm.Ae());return new a.R((b-d)/f,(c-e)/h)};a.Fg.prototype.TDa=function(b,c,d){var e=0,f=0,h=1,k=1;this.sm&&(e=d?d.$f(this.sm,this.sm.qa,!0):this.sm.qa(),f=d?d.$f(this.sm,this.sm.pa,!0):this.sm.pa(),h=d?d.$f(this.sm,this.sm.oe,!0):this.sm.oe(),
k=d?d.$f(this.sm,this.sm.Ae,!0):this.sm.Ae());return new a.R(b*h+e,c*k+f)};a.Fg.prototype.iX=function(){return this.NL};a.Fg.prototype.$R=function(a){this.NL=a};a.Fg.prototype.tea=function(a){return this.NL&&"undefined"!=this.NL[a]?this.NL[a]:null};a.Fg.prototype.lJa=function(b){var c=this.ee.Ld(new a.R(0,0)),d=this.ah.aa(),e=b.x-c.x-d.a/2,c=b.y-c.y-d.b/2;b=this.i8(e,c);d=this.i8(e+d.a,c+d.b);return new a.Z(b.x,b.y,d.x-b.x,d.y-b.y)};a.Fg.prototype.xDa=function(a){this.ah.Fa(a.x);this.ah.jb(a.y);this.ah.Xa(a.a);
this.ah.qb(a.b)};a.Fg.prototype.Qha=function(){return new a.Z(this.ah.Va(),this.ah.ib(),this.ah.getWidth(),this.ah.getHeight())};a.Fg.prototype.aa=function(b){var c=new a.Z(0,0,this.lp,this.Pp);return b&&b!==this?this.nj(c,b):c};a.Fg.prototype.hq=function(a){return this.aa(a)};a.H.fC(a.H.yh,{CONTROL_PANEL:"Control Panel",CONTROL_PANEL_ZOOMANDCENTER:"Zoom and Center",CONTROL_PANEL_PAN:"Pan",CONTROL_PANEL_LAYOUT:"Layout",CONTROL_PANEL_LAYOUT_VERT_TOP:"Vertical, Top Down",CONTROL_PANEL_LAYOUT_VERT_BOTTOM:"Vertical, Bottom Up",
CONTROL_PANEL_LAYOUT_HORIZ_START:"Horizontal, Start-to-End",CONTROL_PANEL_LAYOUT_HORIZ_LEFT:"Horizontal, Left-to-Right",CONTROL_PANEL_LAYOUT_HORIZ_RIGHT:"Horizontal, Right-to-Left",CONTROL_PANEL_LAYOUT_RADIAL:"Radial",CONTROL_PANEL_LAYOUT_TREE:"Tree",CONTROL_PANEL_LAYOUT_CIRCLE:"Circle",CONTROL_PANEL_SYNC:"View",CONTROL_PANEL_ZOOMTOFIT:"Zoom to Fit",CONTROL_PANEL_ZOOMIN:"Zoom In",CONTROL_PANEL_ZOOMOUT:"Zoom Out",CONTROL_PANEL_RESET:"Reset Map",CONTROL_PANEL_DRILLUP:"Drill Up",CONTROL_PANEL_DRILLDOWN:"Drill Down",
LEGEND:"Legend",OVERVIEW:"Overview",PALETTE:"Palette",SEARCH:"Search",SEARCH_TEXT:"Search",SEARCH_TEXT_ALTA:"Find",SEARCH_RESULTS:"Search Results [{0}]",SEARCH_RESULTS_ALTA:"{0} Results",SEARCH_RESULTS_CLOSE:"Close",SEARCH_RESULTS_NO_DATA:"No results to display"})})(dvt);
  return dvt;
});
