/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit', './DvtTimeAxis', './DvtOverview', './DvtTimeComponent'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a){this.ee=a}function c(a){this.Init(c.xe);this.Ts=a}function d(a,b){this.Init(a,b)}function e(a){this.Init(a)}a.Hb=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Hb,a.Db);a.Hb.mJ="_";a.Hb.LZa="_h";a.Hb.mja="_s";a.Hb.mga="_as";a.Hb.Iw="bs";a.Hb.ub="bc";a.Hb.Yi="bw";a.Hb.bub="dbs";a.Hb.jza="dbc";a.Hb.PYa="dbw";a.Hb.K5="bof";a.Hb.yXa="bo";a.Hb.zZa="gc";a.Hb.AZa="go";a.Hb.Gza="fc";a.Hb.newInstance=function(b,c,d){return new a.Hb(b,c,d)};a.Hb.prototype.Init=function(b,c,d){a.Hb.C.Init.call(this,
b,c,d);b=[a.O.xM(a.O.qp("#aadd77",.35)),"#aadd77",a.O.xM(a.O.Ir("#aadd77",.5))];a.Hi.vn()&&(b=["#aadd77"]);this.Zma=b;this.RLa=a.$b.uX();this.Ez=12};a.Hb.prototype.ta=function(b,c,d){"string"===typeof b?a.Hb.C.ta.call(this,this.J$a(b),c,d):a.Hb.C.ta.call(this,b,c,d)};a.Hb.prototype.J$a=function(b){var c={},d=(new a.fO(this.u())).parse(b);b=d.getAttributes();for(var e=0;e<b.length;e++){var m=b[e];c[m.name]=m.value}for(var n=d.ze(),r=[],p=n[0].ze(),e=0;e<p.length;e++){var w={};b=p[e].getAttributes();
for(d=0;d<b.length;d++)m=b[d],w[m.name]=m.value;r.push(w)}c.axisTicks=r;r=[];p=n[1].ze();for(e=0;e<p.length;e++){w={};b=p[e].getAttributes();for(d=0;d<b.length;d++)m=b[d],w[m.name]=m.value;r.push(w)}c.markers=r;if(2<n.length){r=[];n=n[2].ze();for(e=0;e<n.length;e++){p={};b=n[e].getAttributes();for(d=0;d<b.length;d++)m=b[d],p[m.name]=m.value;r.push(p)}c.formattedTimeRanges=r}return c};a.Hb.prototype.vTa=function(){return new e(this)};a.Hb.prototype.uv=function(b){a.Hb.C.uv.call(this,b);this.dw=b.TR;
this.ju=b.gpb;this.EOa=b.krb;this.ana=b.qRa;this.mna="#267DB3 #68C182 #FAD55C #ED6647 #8561C8 #6DDBDB #FFB54D #E371B2 #47BDEF #A2BF39 #A75DBA #F7F37B".split(" ");b.AC&&(this.Pv=new a.j(b.AC));b="solid"==this.M(a.Hb.mJ,a.Hb.Iw)?parseInt(this.M(a.Hb.mJ,a.Hb.K5),10):1;var c="solid"==this.M(a.Hb.mga,a.Hb.Iw)?parseInt(this.M(a.Hb.mga,a.Hb.K5),10):1,d="solid"==this.M(a.Hb.mja,a.Hb.Iw)?parseInt(this.M(a.Hb.mja,a.Hb.K5),10):1;this.Y0=this.Sea()?Math.max(c,d,b,1)/2+1:1;this.T_=this.Sb()?0:.75;this.bIa=[this.T_,
this.T_,this.T_];this.heb=new a.bd(250,this.Zma,this.bIa);this.xcb=new a.bd(180,this.Zma,this.bIa);b=this.Sb()?0:1;this.P7a=new a.ya("#aadd77",b)};a.Hb.prototype.KTa=function(){return null==this.EOa?null:this.EOa.split(" ")};a.Hb.prototype.Fsa=function(b,c,d,e,m,n){a.Hb.C.Fsa.call(this,b,c,d,e,m,n,this.Pv)};a.Hb.prototype.Sea=function(){return"none"!=this.dw};a.Hb.prototype.Ida=function(a){var b="_mrk_"+a;a="_drn_"+a;for(var c=this.Rb(),d=0;d<c;d++){var e=this.hb(d);if(null!=e&&(b==e.getId()||a==
e.getId()))return e}return null};a.Hb.prototype.dR=function(a){return a.getId().substr(5)};a.Hb.prototype.M=function(a,b){return this.T7a[a+b]};a.Hb.prototype.Va=function(a){return null!=a.yd?a.yd.Va():a.sb().le};a.Hb.prototype.ib=function(a){return null!=a.yd?a.yd.ib():a.sb().fe};a.Hb.prototype.oe=function(a){a=a.oe();null==a&&(a=this.Sb()?(this.xb-this.sR()-4)/2:1);return a};a.Hb.prototype.Ae=function(a){a=a.Ae();null==a&&(a=1);return a};a.Hb.prototype.xwa=function(b,c){a.Hb.C.xwa.call(this,b,c);
if(null!=this.ju){for(var d=this.IQa(this.Yb,this.Ic,b,c,this.Ez),e=[],m=0;m<this.ju.length;m++){var n=this.ju[m];null==n.MK?this.nhb(n,d):e[e.length]=n}this.Gwa(e);this.hhb(e);this.Ez=d}};a.Hb.prototype.Gwa=function(a){this.Ppa=0;var b=null;null==this.yU&&(this.yU={});for(var c=0;c<a.length;c++){var d=a[c],e=d.getId(),n=e.substring(e.indexOf(":")+1,e.length),n=n.substring(0,n.indexOf(":"));n!=b&&(this.JD=0,b=n);d.lz=this.HQa(d,a);null==d.XG&&(null==this.yU[e]?(this.yU[e]=this.JD,d.XG=this.mna[this.JD],
this.JD++,this.JD==this.mna.length&&(this.JD=0)):d.XG=this.mna[this.yU[e]])}};a.Hb.prototype.Vkb=function(){return this.yU?this.yU:null};a.Hb.prototype.IQa=function(b,c,d,e,m){for(var n={max:1,Ksa:[]},r=this.Sb()?e:d,p=0;p<this.ju.length;p++){var w=this.ju[p];if(null!=w.MK){var x=a.Hi.bf(b,c,w.getTime(),r);this.Wq()&&(x=r-x);w.Fa(x)}else if(this.aib(w,b,c,r,m/2,n,e),n.max>e)break}return n.max>e&&1<m?this.IQa(b,c,d,e,m-1):m};a.Hb.prototype.nhb=function(b,c){var d="_mrk_"+b.getId(),e=b.ic(),m=b.toa,
n=b.Dua();null==n&&(n=this.T_,0==n&&null!=e&&(n=1));var r=this.oe(b),p=this.Ae(b),w=b.Mc();if(this.Sb())var w=a.za.Zw,r=2*r,p=2*p,x=b.ib()+r/2,v=b.Va()+p/2;else r*=c,p*=c,x=b.Va()+r/2,v=b.ib()+p/2;d=new a.za(this.u(),w,null,x,v,r,p,null,null,null,d);d.yd=b;null==e&&n==this.T_&&null==m?(m=w==a.za.Qo?this.heb:this.xcb,e=this.P7a):(r=this.Zma,null!=e&&(a.Hi.vn()?r=[e]:(r=a.O.qp(e,.5),p=a.O.Ir(e,.5),r=[r,e,p])),p=[n,n,n],m=null==m?w==a.za.Qo?new a.bd(250,r,p):new a.bd(180,r,p):new a.$b(e,p[0]),e=new a.ya(e,
n));d.ra(m);d.Ga(e);this.Sea()&&d.mj(!0);e=this.Rb();n=this.hb(e-1);e>this.gL&&("tb"==n.getId()||"arr"==n.getId())?this.Ib(d,e-this.gL):this.A(d);b.th(d);this.Pq(d,a.Hb.mJ);!this.Sb()&&w!=a.za.Zw&&w!=a.za.tN&&w!=a.za.TJ&&w!=a.za.SJ&&w!=a.za.PN||"false"==this.ana.Bwa||d.md()};a.Hb.prototype.hhb=function(b){for(var c=this.u(),d=this.Ppa;0<d;d--)for(var e=0;e<b.length;e++){var m=b[e];if(d==m.lz){var n=a.Hi.bf(this.Yb,this.Ic,m.getTime(),this.Sb()?this.Jb:this.xb),r="_drn_"+m.getId(),p=9+5*m.lz,w=a.Hi.bf(this.Yb,
this.Ic,m.hl(),this.Sb()?this.Jb:this.xb),n=this.Sb()?this.No()?new a.Rect(c,0,n,p,w-n,r):new a.Rect(c,this.xb-p,n,p,w-n,r):this.No()?new a.Rect(c,this.xb-w,this.Jb-p-20,w-n,p,r):new a.Rect(c,n,this.Jb-p-20,w-n,p,r);n.ra(new a.$b(m.XG));r=new a.ya(this.M(a.Hb.mJ,a.Hb.jza),1,1);n.Ga(r);n.md();n.yd=m;this.A(n);m.xU=n;m.vvb=p-2}}this.removeChild(this.uPa);this.A(this.uPa)};a.Hb.prototype.aib=function(b,c,d,e,m,n,r){var p=m*this.oe(b)+this.Y0,w=m*this.Ae(b)+this.Y0;c=a.Hi.bf(c,d,b.getTime(),e);this.Wq()&&
(c=e-c-2*p);if(this.Sb())m=0,"solid"==this.M(a.Hb.mJ,a.Hb.Iw)&&(m=parseInt(this.M(a.Hb.mJ,a.Hb.Yi),10)),e=this.No()?m+4:this.xb-2*this.oe(b)-m-4;else{e=3;this.Wea()&&(e+=this.dF());var x=0;d=[];for(var v=0;v<n.Ksa.length;v++){var A=n.Ksa[v],u=A.Va(),D=this.oe(A);Math.abs(c-u)<m*D+this.Y0+p&&d.push(A)}for(v=0;v<d.length;v++)if(A=this.bib(d,b.Mc(),c,e,p,w,x,m,r),x=A.maxy,A.cy==e){e=A.cy;break}else e=A.cy}b.Fa(c);b.jb(e);n.Ksa.push(b);x>n.max&&(n.max=x)};a.Hb.prototype.bib=function(b,c,d,e,m,n,r,p,w){for(var x=
0;x<b.length;x++){var v=b[x],A=v.Va(),u=v.ib(),D=v.Mc(),B=this.oe(v),v=this.Ae(v);c==a.za.Qo&&D==a.za.Qo&&m==n&&B==v?(A=Math.abs(d-A),B=p*B+this.Y0+m,B=Math.sqrt(B*B-A*A)):B=p*v+this.Y0+n;if(B>Math.abs(e-u)&&(e=u+B,r=Math.max(r,e+B),1<=p&&void 0!=w&&r>w))break}return{cy:e,maxy:r}};a.Hb.prototype.HQa=function(a,b){var c=b.length,d=a.getTime(),e=a.lz;null==e&&(e=1);for(var n=0;n<c;n++){var r=b[n];if(r!=a){var p=r.hl();if(null!=p){var w=r.getTime(),r=r.lz;null==r&&(r=1);d>=w&&d<=p&&e==r&&(e=r+1,a.lz=
e,e=this.HQa(a,b))}}}e>this.Ppa&&(this.Ppa=e);return e};a.Hb.prototype.U6=function(b){var d=a.Hb.C.U6.call(this,b);if(null!=d){if(null!=d.yd){var e=d.yd.sU;null!=e&&this.u().Af().pY(b.pageX,b.pageY,e,"#000000");this.CR()&&this.setCursor("pointer")}if(this.Sea()){b=!1;if(null!=this.Co)for(e=0;e<this.Co.length;e++)if(d==this.Co[e]){b=!0;break}b||(b=this.dR(d),e=new c(c.x1a),e.wxa(b),this.dispatchEvent(e),this.qUa(d))}}};a.Hb.prototype.T6=function(b){b=a.Hb.C.T6.call(this,b);if(null!=b&&!this.IUa(b)){this.u().Af().qe();
var d=!1;if(null!=this.Co)for(var e=0;e<this.Co.length;e++)if(b==this.Co[e]){d=!0;break}d||(d=this.dR(b),e=new c(c.C1a),e.wxa(d),this.dispatchEvent(e),this.YWa(b))}};a.Hb.prototype.EN=function(b,c,d){c=a.Hb.C.EN.call(this,b,c,d);null!=c&&this.JAa(c,b.ctrlKey||b.shiftKey||a.B.Wa())};a.Hb.prototype.JAa=function(a,b){if(this.Sea()){this.hrb(a,b);var d=a.yd.getTime();if(null!=d){var e=new c(c.IZ);e.setTime(d);this.dispatchEvent(e);d=this.lt();d=this.Sb()?this.Va(a)-d.getHeight()/2:this.Va(a)-d.getWidth()/
2;this.Jsa(d)}}};a.Hb.prototype.Wnb=function(a){a=this.Ida(a);null!=a&&this.qUa(a)};a.Hb.prototype.otb=function(a){a=this.Ida(a);null!=a&&this.YWa(a)};a.Hb.prototype.qUa=function(b){if(null!=this.Co)for(var c=0;c<this.Co.length;c++)if(b==this.Co[c])return;this.Pq(b,a.Hb.LZa)};a.Hb.prototype.YWa=function(b){if(null!=this.Co)for(var c=0;c<this.Co.length;c++)if(b==this.Co[c])return;this.Pq(b,a.Hb.mJ)};a.Hb.prototype.aWa=function(a){a=this.Ida(a);null!=a&&this.uhb(a)};a.Hb.prototype.grb=function(a){a=
this.Ida(a);null!=a&&this.Bqb(a)};a.Hb.prototype.hrb=function(a,b){var d=this.dR(a),e=new c(c.A1a);e.wxa(d);e.psb(b);this.dispatchEvent(e)};a.Hb.prototype.uhb=function(b){null==this.Co&&(this.Co=[]);var c=null;0<this.Co.length&&(c=this.Co[this.Co.length-1]);this.Co.push(b);null!=c&&this.Pq(c,a.Hb.mja);this.Pq(b,a.Hb.mga)};a.Hb.prototype.Bqb=function(b){if(null!=this.Co){for(var c=-1,d=0;d<this.Co.length;d++)if(b==this.Co[d]){c=d;break}-1!=c&&(this.Pq(b,a.Hb.mJ),this.Co.splice(c,1))}};a.Hb.prototype.Pq=
function(b,c){if(b instanceof a.za){var d=!1,e=!1;if("solid"==this.M(c,a.Hb.Iw)){var d=!0,m=this.M(c,a.Hb.ub);null==m&&(m="#000000");var n=this.M(c,a.Hb.zZa);null!=n&&"none"!=n&&(e=!0)}var r=b.OGa,p=b.roa;d||null==r?e||null==p||(this.removeChild(p),b.roa=null):(this.removeChild(r),b.OGa=null,null!=p&&(this.removeChild(p),b.roa=null));var w=b.he();if(d){var d=parseInt(this.M(c,a.Hb.Yi),10),x=parseInt(this.M(c,a.Hb.K5),10);if(null==r){if(w==a.za.Qo){this.CR()&&(x=0);var v=(b.aa().a+2*x)*b.oe(),A=(b.aa().b+
2*x)*b.Ae(),u=this.Va(b)-x+v/2,D=this.ib(b)-x+A/2}else this.Sb()?(v=(b.aa().a+(d+1))*b.oe(),A=(b.aa().b+(d+1))*b.Ae(),u=this.ib(b)-(d+1)/2+v/2,D=this.Va(b)-(d+1)/2+A/2):(v=(b.aa().a+2*x)*b.oe(),A=(b.aa().b+2*x)*b.Ae(),u=this.Va(b)-x+v/2,D=this.ib(b)-x+A/2);r=new a.za(this.u(),w,null,u,D,v,A,null,null,null,b.getId()+"_border");this.Ib(r,this.Bi(b));b.OGa=r;r.ra(this.RLa)}m=new a.ya(m,this.M(c,a.Hb.yXa),d);r.Ga(m);!this.Sb()&&w!=a.za.Zw&&w!=a.za.tN&&w!=a.za.TJ&&w!=a.za.SJ&&w!=a.za.PN||"false"==this.ana.Bwa||
r.md();e&&(null==p&&(p=x-d,w==a.za.Qo?(this.CR()&&(p=0),v=(b.aa().a+2*p)*b.oe(),A=(b.aa().b+2*p)*b.Ae(),u=this.Va(b)-p+v/2,D=this.ib(b)-p+A/2):this.Sb()?(v=(b.aa().a+3)*b.oe(),A=(b.aa().b+3)*b.Ae(),u=this.ib(b)+v/2,D=this.Va(b)-1+A/2):(v=(b.aa().a+2*p)*b.oe(),A=(b.aa().b+2*p)*b.Ae(),u=this.Va(b)-p+v/2,D=this.ib(b)-p+A/2),p=new a.za(this.u(),w,null,u,D,v,A,null,null,null,b.getId()+"_glow"),this.Ib(p,this.Bi(r)),b.roa=p,p.ra(this.RLa)),n=new a.ya(n,this.M(c,a.Hb.AZa),4),p.Ga(n),!this.Sb()&&w!=a.za.Zw&&
w!=a.za.tN&&w!=a.za.TJ&&w!=a.za.SJ&&w!=a.za.PN||"false"==this.ana.Bwa||p.md())}}else(w=b.getId())&&"_drn_"==w.substring(0,5)&&this.Chb(b,c)};a.Hb.prototype.Chb=function(b,c){var d=this.M(c,a.Hb.jza);null==d&&(d="#000000");var e=parseInt(this.M(c,a.Hb.PYa),10);b.Ga(new a.ya(d,1,e))};a.Hb.prototype.ph=function(){this.vEa||(this.vEa=new b(this));return this.vEa};a.v.D(e,a.v);e.prototype.Init=function(b){this.ha=b;this.Yv=new a.fO(b.u())};e.prototype.parse=function(a){var b=this.CZ(a);b.WWa=this.Bdb(a.axisTicks);
b.gpb=this.Iqa(a.markers,b.qRa);b.Gjb=a.formattedTimeRanges;return b};e.prototype.CZ=function(a){var b={};b.start=parseInt(a.start);b.end=parseInt(a.end);b.width=parseInt(a.width);b.Ywa=parseInt(a.renstart);b.currentTime=parseInt(a.ocd);b.orientation=a.orn;b.vVa=a.ovp;b.TR=a.selmode;b.Xva=a.rtl;b.borderTopStyle=a._bts;b.borderTopColor=a._btc;b.krb=a.sid;b.qQa=a._aoc;var c={};c.shape=a._ds;c.RR=a._dsx;c.SR=a._dsy;c.opacity=a._do;c.color=a._fc;c.Bwa=a._ph;b.qRa=c;b.sva=a._hfc;b.vva=a._htc;b.YTa=a._hbi;
b.aUa=a._hw;b.ZTa=a._hh;b.Vxa=a._wbc;b.cya=a._wbts;b.aya=a._wbrs;b.Xxa=a._wbbs;b.Zxa=a._wbls;b.bya=a._wbtc;b.$xa=a._wbrc;b.Wxa=a._wbbc;b.Yxa=a._wblc;b.twa=a._obc;b.eta=a._ctic;b.Hxa=a._tic;b.UWa=a._tabc;b.VWa=a._tabo;b.AC=a._ls;c={};c._bs=a._bs;c._bc=a._bc;c._bw=a._bw;c._bof=a._bof;c._bo=a._bo;c._gc=a._gc;c._go=a._go;c._dbs=a._dbs;c._dbc=a._dbc;c._dbw=a._dbw;c._hbs=a._hbs;c._hbc=a._hbc;c._hbw=a._hbw;c._hbof=a._hbof;c._hbo=a._hbo;c._hgc=a._hgc;c._hgo=a._hgo;c._hdbs=a._hdbs;c._hdbc=a._hdbc;c._hdbw=
a._hdbw;c._sbs=a._sbs;c._sbc=a._sbc;c._sbw=a._sbw;c._sbof=a._sbof;c._sbo=a._sbo;c._sgc=a._sgc;c._sgo=a._sgo;c._sdbs=a._sdbs;c._sdbc=a._sdbc;c._sdbw=a._sdbw;c._asbs=a._asbs;c._asbc=a._asbc;c._asbw=a._asbw;c._asbof=a._asbof;c._asbo=a._asbo;c._asgc=a._asgc;c._asgo=a._asgo;c._asdbs=a._asdbs;c._asdbc=a._asdbc;c._asdbw=a._asdbw;b.Mhb=c;return b};e.prototype.Iqa=function(a,b){if(a){for(var c=[],e=0;e<a.length;e++){var m=this.Ria(a[e],b),m=new d(this.ha,m);c.push(m)}return c}return null};e.prototype.Ria=
function(a,b){var c={},d="true"==a._sd;c.id=a.tid;c.brb=a.rk;c.time=a.t;c.endTime=a.et;c.shape=a.s;d&&null==c.shape&&(c.shape=b.shape);c.ida=a.d;c.color=a.c;c.mda=a.dfc;d&&null==c.color&&(c.color=b.color);c.RR=a.sx;d&&null==c.RR&&(c.RR=b.RR);c.SR=a.sy;d&&null==c.SR&&(c.SR=b.SR);c.Enb=a.g;c.opacity=a.o;d&&null==c.opacity&&(c.opacity=b.opacity);return c};e.prototype.Bdb=function(a){if(a){var b={width:null,height:null};b.htb=a;return b}return null};a.v.D(d,a.v);d.prototype.Init=function(b,c){this.ha=
b;this.xc=c.id;this.ngb=parseInt(c.time);this.MK=null==c.endTime?null:parseInt(c.endTime);this.ba=a.za.Qo;"square"==c.shape?this.ba=a.za.Zw:"plus"==c.shape?this.ba=a.za.PN:"diamond"==c.shape?this.ba=a.za.tN:"triangleUp"==c.shape?this.ba=a.za.TJ:"triangleDown"==c.shape&&(this.ba=a.za.SJ);this.sU=c.ida;this.ep=c.color;this.toa=c.Enb;null!=c.opacity&&(this.edb=parseFloat(c.opacity));null!=c.RR&&(this.Efb=parseFloat(c.RR));null!=c.SR&&(this.Ffb=parseFloat(c.SR));null!=c.mda&&(this.XG=c.mda)};d.prototype.getId=
function(){return this.xc};d.prototype.getTime=function(){return this.ngb};d.prototype.hl=function(){return this.MK};d.prototype.oe=function(){return this.Efb};d.prototype.Ae=function(){return this.Ffb};d.prototype.ic=function(){return this.ep};d.prototype.Mc=function(){return this.ba};d.prototype.Dua=function(){return this.edb};d.prototype.Sa=function(){return this.ej};d.prototype.th=function(a){this.ej=a};d.prototype.Va=function(){return this.zc};d.prototype.Fa=function(a){this.zc=a};d.prototype.ib=
function(){return this.ed};d.prototype.jb=function(a){this.ed=a};a.v.D(c,a.Qc);c.xe="timeline";c.x1a="highlight";c.C1a="unhighlight";c.A1a="selection";c.IZ=a.Qc.IZ;c.Fja=a.Qc.Fja;c.J7=a.Qc.J7;c.hDa="rangeChanging";c.Mub=a.Qc.Eja;c.pBa="itemId";c.NBa="multiSelect";c.F7=a.Qc.F7;c.s6=a.Qc.s6;c.prototype.wxa=function(a){this.dl(c.pBa,a)};c.prototype.dR=function(){return this.Sq(c.pBa)};c.prototype.psb=function(a){this.dl(c.NBa,a)};c.prototype.tob=function(){var a=this.Sq(c.NBa);return null!=a?a:!1};a.v.D(b,
a.Rd);b.ZS="marker";b.dEa="range_window";b.cDa="range_start_handle";b.zza="range_end_handle";b.oya=-1;b.nya=0;b.prototype.zn=function(c){var d=c.getId();if(c instanceof a.za){c=d.split(":");if(4!=c.length)return null;d=this.ee.KTa();if(null!=d&&(d=a.na.kb(d,c[1]),-1<d))return"marker["+d+"]["+c[2]+"]"}else{if("window"==d)return b.dEa;if("lh"==d||"lhb"==d||"lbgrh"==d)return b.cDa;if("rh"==d||"rhb"==d||"rbgrh"==d)return b.zza;if("grpy"==d)return c=c.getParent().o3(c),this.zn(c)}return null};b.prototype.qh=
function(a){var c=b.uHa(a);if(c&&3==c.length&&c[0]==b.ZS){if(a=this.ee.KTa(),null!=a){var d=parseInt(c[1],10);if(-1<d&&d<a.length)return(c=b.NIa(this.ee.ju,a[d],c[2]))?c.Sa().Ua():null}}else{if(a==b.dEa)return this.ee.lt().Ua();if(a==b.cDa)return this.ee.rua().Ua();if(a==b.zza)return this.ee.Oua().Ua()}return null};b.prototype.click=function(a){this.gqb(a,b.nya)};b.prototype.gqb=function(a,c){void 0===c&&(c=b.oya);if(null!=a&&c!=b.oya&&c==b.nya){var d=b.uHa(a);d&&3==d.length&&d[0]==b.ZS&&(d=b.NIa(this.ee.ju,
d[1],d[2]))&&this.ee.JAa(d.Sa(),!1)}};b.uHa=function(a){a=a.split("[");for(var b=a.length,c=1;c<b;c++){var d=a[c],d=d.substr(0,d.length-1),e=parseFloat(d),d=isNaN(e)?d:e;a[c]=d}return a};b.NIa=function(a,b,c){b="tl1:"+b+":"+c+":";for(c=0;c<a.length;c++){var d=a[c],e=d.getId();if(null!=e&&0==e.indexOf(b))return d}return null};a.Ia(a,"TimelineOverview",a.Hb);a.Ia(a.Hb,"newInstance",a.Hb.newInstance);a.Ia(a.Hb.prototype,"render",a.Hb.prototype.ta);a.Ia(a.Hb.prototype,"getAutomation",a.Hb.prototype.ph);
a.Ia(a.Hb.prototype,"getDurationColorMap",a.Hb.prototype.Vkb);a.Ia(b.prototype,"getDomElementForSubId",b.prototype.qh)})(dvt);
(function(a){function b(){}function c(a,b,c){this.Init(a,b,c)}function d(a,b){this.Init(a,b)}function e(a,b,c){this.Init(a,b,c)}function f(){}function h(){this.Init({alta:h.lh})}function k(a){this.Ho=a}function l(a){l.C.constructor.call(this,a)}function m(a){this.Init(a)}var n={vn:function(){return a.B.Wa()}};a.v.D(n,a.v);n.bf=function(a,b,c,d){c=(c-a)*d;a=b-a;return 0==c||0==a?0:c/a};n.Si=function(a,b,c,d){b=c*(b-a);return 0==b||0==d?a:b/d+a};a.v.D(m,a.dO);m.Fd=function(b,c,d){var e=b.vi(),f=b.Fh(),
h=a.B.da(e.u()),e=e.Sb(),k=1<d.length;if(!h&&a.KeyboardEvent.uf==c.keyCode||h&&a.KeyboardEvent.Jf==c.keyCode){if(!e)return m.bea(b,d[f],!0);if(k&&1!=f)return m.Gda(b,d[1])}else if(!h&&a.KeyboardEvent.Jf==c.keyCode||h&&a.KeyboardEvent.uf==c.keyCode){if(!e)return m.bea(b,d[f],!1);if(k&&0!=f)return m.Gda(b,d[0])}else if(a.KeyboardEvent.Tf==c.keyCode){if(e)return m.bea(b,d[f],!0);if(k&&1!=f)return m.Gda(b,d[1])}else if(a.KeyboardEvent.kh==c.keyCode){if(e)return m.bea(b,d[f],!1);if(k&&0!=f)return m.Gda(b,
d[0])}return null};m.bea=function(b,c,d){b=a.na.kb(c,b)+(d?1:-1);return 0<=b&&b<c.length?c[b]:null};m.Gda=function(a,b){if(0<b.length){for(var c=b[0],d=a.CB,e=Math.abs(d-c.CB),f=1;f<b.length;f++){var h=Math.abs(d-b[f].CB);h<e&&(e=h,c=b[f])}return c}return null};a.v.D(l,a.ai);l.prototype.Qf=function(b){l.C.Qf.call(this,b);!a.B.Wa()&&a.B.ae()&&(b=this.u().Oe,b.Ya("mouseenter",this.eCa,!1,this),b.Ya("mouseleave",this.fCa,!1,this))};l.prototype.ll=function(b){l.C.ll.call(this,b);!a.B.Wa()&&a.B.ae()&&
(b=this.u().Oe,b.jc("mouseenter",this.eCa,!1,this),b.jc("mouseleave",this.fCa,!1,this))};l.prototype.u7=function(b){this.ip&&this.ip.Km()&&this.ip.stop();l.C.u7.call(this,b);a.B.ae()||this.Vea||(this.Vea=!0,this.Li.Hva()||this.Li.w5())};l.prototype.eCa=function(){this.ip&&this.ip.Km()&&this.ip.stop();this.Vea||(this.Vea=!0,this.Li.Hva()||this.Li.w5())};l.prototype.fCa=function(){this.ip||(this.ip=new a.Rh(this.u(),10,this.eba,this,1));this.ip.reset();this.ip.start()};l.prototype.t7=function(b){l.C.t7.call(this,
b);a.B.ae()||(this.ip||(this.ip=new a.Rh(this.u(),10,this.eba,this,1)),this.ip.reset(),this.ip.start())};l.prototype.eba=function(){this.Vea=!1};l.prototype.Wi=function(a,b){var c=this.jf();c&&(this.Li.Wk=c.Tc);l.C.Wi.call(this,a,b)};a.Zd=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Zd,a.Lf);a.Zd.m7="vertical";a.Zd.newInstance=function(b,c,d){return new a.Zd(b,c,d)};a.Zd.prototype.Init=function(b,c,d){a.Zd.C.Init.call(this,b,c,d);this.Xg=new h;this.I=new l(this);this.I.Qf(this);a.B.Wa()?this.$D=null:
(this.$D=new m(this.I),this.I.Xr(this.$D))};a.Zd.prototype.eD=function(a){this.Yv=new f;return this.Yv.parse(a)};a.Zd.prototype.uv=function(b){var c=this.W.orientation;this.de=c&&c==a.Zd.m7?!0:!1;this.vx=b.Pnb;this.yc=b.Uxa;this.Td=b.Txa;this.dw=b.TR;this.Rc="single"==this.dw?new a.Rc(a.Rc.Sy):"multiple"==this.dw?new a.Rc(a.Rc.Ry):null;this.I.zA(this.Rc);this.pu=b.Gxa;this.kQ=b.qqb;this.ou=b.lrb;this.BQ=b.Ixa;this.ou?(this.Ifb=b.irb,this.Mq=new a.Ub(this.u(),null,null),this.Mq.uWa(this.de),this.Mq.zt(this.ou),
this.Mq.jWa(this.Ifb),this.rQ=b.jrb,this.iz=this.Mq.iz,this.de?(this.Mq.bo("short",this.iz),this.Mq.Kfa(this.jj.converterVert)):(this.Mq.bo("long",this.iz),this.Mq.Kfa(this.jj.converter)),this.BQ&&this.Mq.IWa(this.BQ)):this.Mq=null;this.z9a=[!1,!0];this.pcb=b.VUa;this.xo=b.X2;this.PG=b.W2;this.nf=b.scale;a.Zd.C.uv.call(this,b)};a.Zd.prototype.BM=function(){return this.ck};a.Zd.prototype.gva=function(){return this.ck.pe()};a.Zd.prototype.rR=function(a){return this.vx||1!=a?this.gva():this.gva()-this.ck.Pg()};
a.Zd.prototype.select=function(b){this.W.selection=a.ac.clone(b);this.Rc&&this.uQa()};a.Zd.prototype.F9=function(a){this.CE={start:a.start,end:a.end,_resources:a._resources,shortDesc:a.shortDesc,_tzo:a._tzo,_ip:a._ip,_cts:this.xo,_cfs:this.PG,orientation:a.orientation};var b=this.CE._resources;b&&(b.borderTopVisible=!0,b.borderRightVisible=!0,b.borderBottomVisible=!0,b.borderLeftVisible=!0);a.styleDefaults&&a.styleDefaults.minorAxis&&(b=a.styleDefaults.minorAxis,this.CE.backgroundColor=b.backgroundColor,
this.CE.borderColor=b.borderColor,this.CE.separatorColor=b.separatorColor,this.CE.labelStyle=b.labelStyle);a.minorAxis&&(a=a.minorAxis,this.CE.scale=a.scale,this.CE.converter=a.converter,this.CE.zoomOrder=a.zoomOrder,this.CE.style=a.style)};a.Zd.prototype.ta=function(b,c,d){b?(this.vf(b),this.W&&(this.jj=this.W._resources,null==this.jj&&(this.jj=[])),this.xb=c,this.Jb=d,b=this.eD(this.W),this.uv(b),this.qz=0,this.Jv=this.de?d:c,this.W.styleDefaults&&(this.Bcb=this.W.styleDefaults.majorAxis,this.sQ=
this.W.styleDefaults.series),this.nf&&(this.F9(this.W),this.Wca(),this.ck||(this.ck=new a.Ub(this.u(),null,null),this.ck.RX(!0,!0,!0,!0)),this.ck.ixa(),c=this.ck.lea(this.CE,this.Uf),this.qF(c),this.lfa()),this.Cdb(),r.Oqb(this),this.hr(),this.u().YM([this])):this.eH(c,d)};a.Zd.prototype.Tnb=function(){for(var a=0;a<this.dca.length;a++){var b=this.dca[a];if(b.items)for(var c=0;c<b.items.length;c++){var d=b.items[c],e=(new Date(d.start)).getTime();if(!e||d.hasOwnProperty("end")&&(d=(new Date(d.end)).getTime(),
!(d&&d>=e)))return!1}}return!0};a.Zd.prototype.hy=function(){var b=this.nf&&-1!=a.na.kb(a.Ub.Wka,this.nf),c=this.nf&&this.xo&&this.xo[this.nf],d=this.Yb&&this.Ic&&this.Ic>this.Yb,e=this.Tc&&0<this.Tc.length,f=e?this.Tnb():!1,h=this.ou?-1!=a.na.kb(a.Ub.Wka,this.ou):!0,k=this.ou?this.xo&&this.xo[this.ou]:!0,l=this.yc&&this.Td?this.Td>this.yc:!0,n=this.yc?this.yc>=this.Yb&&this.yc<this.Ic:!0,m=this.Td?this.Td>this.Yb&&this.Td<=this.Ic:!0;return(b||c)&&(h||k)&&d&&e&&f&&l&&n&&m};a.Zd.prototype.gm=function(){return this.pu?
this.pu:a.H.va(a.H.Ha,"TIMELINE")};a.Zd.prototype.Hva=function(){for(var a=0;a<this.Tc.length;a++)if(this.Tc[a].taa)return!0;return!1};a.Zd.prototype.w5=function(b){if(this.hy()){for(var c=new a.G(this.u(),p.ySa(),0,a.Je.kF),d=0;d<this.KL.length;d++){var e=this.KL[d],f=e.getId(),h=!0;this.je<=this.Uf&&("lhs"==f||"rhs"==f)&&(h=!1);var k=e.getParent().getId();k&&(k=k.substring(k.length-1),null!=b&&b!=k&&(h=!1),this.Tc[k].$k<=this.Qi&&("ths"==f||"bhs"==f)&&(h=!1));h&&c.N(a.G.V,e,e.Ra,e.T,p.nlb())}a.eb.Mb(c,
this.Unb,this);c.play()}};a.Zd.prototype.Unb=function(){var b=this.KL.length;if(0!=b){for(var c=new a.G(this.u(),p.ySa(),0,a.Je.kF),d=0;d<b;d++){var e=this.KL[d];c.N(a.G.V,e,e.Ra,e.T,0)}c.play()}};a.Zd.prototype.IE=function(){this.Gk=new a.j(p.Zmb());if(this.W.styleDefaults){var b=this.W.styleDefaults.borderColor;b&&this.Gk.lj("border-color:"+b+";")}if(this.vx&&(this.vL=this.de?p.dmb():p.Hua(),b=this.W.overview.style))for(var b=b.split(";"),c=0;c<b.length;c++){var d=b[c];if(d&&0<d.length){var e=d.indexOf(":");
if(-1<e){var f=a.Nd.trim(d.substring(0,e));if(this.de&&"width"==f||!this.de&&"height"==f){this.vL=parseInt(a.Nd.trim(d.substring(e+1)),10);break}}}}a.Zd.C.IE.call(this);b=this.Gk.Pg();c=2*b;this.Gk.lj("border:"+c+"px;");this.aga(b);this.GWa(b);this.Zt=this.xb;this.Yy=this.Jb;this.de?(this.Uf=this.Yy-c,this.vx?(this.cj=this.Zt-this.vL-c,this.No()&&this.aga(b+this.vL)):this.cj=this.Zt-c):(this.Uf=this.Zt-c,this.cj=this.vx?this.Jb-this.vL-c:this.Jb-c)};a.Zd.prototype.Wca=function(){if(this.sQ&&this.sQ.backgroundColor){var b=
this.sQ.backgroundColor;a.O.Ug(b);a.O.Rg(b);a.O.Og(b)}};a.Zd.prototype.Cdb=function(){var a=this.W.series;if(a){var b=Math.min(a.length,2);this.dca=[];if(this.Tc){if(b!=this.Tc.length){for(var c=0;c<this.Tc.length;c++)this.Ul.removeChild(this.Tc[c]);this.Tc=[]}}else this.Tc=[];for(c=0;c<b;c++){var d=a[c];d.start=this.Yb;d.end=this.Ic;d.inverted=this.z9a[c];d.orientation=this.W.orientation;d.referenceObjects=this.kQ;d.timeline=this;d.index=c;d.animationOnDisplay=this.W.animationOnDisplay;d.animationOnDataChange=
this.W.animationOnDataChange;this.W.majorAxis&&(d.scale=this.W.majorAxis.scale,d.timeAxis=this.Mq,d._cfs=this.rQ);if(d.styleDefaults=this.W.styleDefaults)d.seriesStyleDefaults=this.sQ,d.axisStyleDefaults=this.Bcb;d._isRandomItemLayout="random"==this.pcb;d._cts=this.W._cts;this.dca.push(d);null==this.Tc[c]&&(d=new e(this.u(),this.eZ,this),this.Tc.push(d))}}else this.Tc=[]};a.Zd.prototype.Apb=function(){a.B.xj()&&this.w5()};a.Zd.prototype.Aab=function(){var a={};a.start=this.Yb;a.end=this.Ic;a.renstart=
this.yc;a.width=this.je;a.ovp="below";a.selmode=this.dw;a.rtl=this.No();a.sid="ts1";a._bts="none";a._btc="#4f4f4f";a._fc="#aadd77";a._do="0";var b=p.emb(this.W);a._wbc=b;a._hfc=b;b=p.fmb(this.W);a._wbtc=b;a._wbrc=b;a._wbbc=b;a._wblc=b;a._wbts="solid";a._wbrs="solid";a._wbbs="solid";a._wbls="solid";a._ls=p.cmb(this.W).toString();a._obc=p.bmb(this.W);a._ctic=p.CTa(this.W);a._tic="#BCC7D2";a._tabc="#D9DFE3";a._tabo="0";a._bs="solid";a._bc="#648BAF";a._bw="1px";a._bof="0px";a._dbs="solid";a._dbc="#648BAF";
a._dbw="1px";a._hbs="solid";a._hbc="#85bbe7";a._hbw="2px";a._hbof="0px";a._hgc="#ebeced";a._hgo="1";a._hdbs="solid";a._hdbc="#85bbe7";a._hdbw="2px";a._sbs="solid";a._sbc="#000000";a._sbw="2px";a._sbof="0px";a._sbo="1";a._sdbs="solid";a._sdbc="#000000";a._sdbw="2px";a._asbs="solid";a._asbc="#000000";a._asbw="2px";a._asbof="0px";a._asbo="1";a._asgc="#e4f0fa";a._asgo="1";a._asdbs="solid";a._asdbc="#000000";a._asdbw="2px";a._aoc="off";this.kQ&&0<this.kQ.length&&this.kQ[0]&&(a.ocd=this.kQ[0].getTime());
this.de?(a.orn="vertical",(b=this.jj.overviewHandleVert)?(a._hbi=b,a._hw="15",a._hh="3"):a._htc=p.uTa()):(a.orn="horizontal",(b=this.jj.overviewHandleHor)?(a._hbi=b,a._hw="3",a._hh="15"):a._htc=p.uTa(),a._ds="square",a._dsx="1.3d",a._dsy="0.9d");a.axisTicks=this.yab();a.markers=this.zab();return a};a.Zd.prototype.yab=function(){var b=[];if(this.Mq){var c,d;if(this.xo&&this.xo[this.ou])d=this.xo[this.ou],c=d.times,d=d.labels;else if(this.rQ&&this.rQ[this.ou])d=this.rQ[this.ou],c=d.times,d=d.labels;
else{c=[];d=[];for(var e=this.Yb,f=this.Ic,h=this.de?this.Jb:this.xb,k=a.Ub.Si(e,f,this.qz,h),k=this.Mq.zW(k),l=a.Ub.bf(e,f,k,h);l<this.Jv;)d.push(this.Mq.tta(k)),c.push(k.getTime()),k=this.Mq.eX(k.getTime()),l=a.Ub.bf(e,f,k,h)}for(e=0;e<d.length;e++)f={},f.time=c[e],f.label=d[e],b.push(f)}return b};a.Zd.prototype.zab=function(){if(this.Tc){for(var a=[],b=this.Tc.length,c=0;c<b;c++)for(var d=this.Tc[c].dc,e=0;e<d.length;e++){var f=d[e],h={};h.rk=e;h.tid=f.getId();h.t=f.Ti();h._sd="true";var k=f.hl();
k&&(h.et=k,(f=f.XG)&&(h.dfc=f));a.push(h)}return a}};a.Zd.prototype.Tz=function(){return a.Za.mVa(this.yc,this.Td,this.ck.nf)};a.Zd.prototype.hZ=function(a){if(1==a.touches.length){if(this.Wk=this.l0(a.target))var b=this.Tc[0]==this.Wk?0:1;this.w5(b)}};a.Zd.prototype.xR=function(b,c,d,e){b>this.ck.qV?(b=this.ck.qV,this.cM(!0)):this.oda(!0);this.Uf>b?(b=this.Uf,this.cM(!1)):this.oda(!1);var f=this.je<=b;a.Zd.C.xR.call(this,b,c,d,e);b=this.ck.tW;if(f)for(;0<this.ck.mp;)if(f=b[this.ck.mp-1],this.je>=
f)this.ck.eS(this.ck.mp-1),this.ck.hta();else break;else for(;this.ck.mp<b.length-1;)if(f=b[this.ck.mp],this.je<f)this.ck.eS(this.ck.mp+1),this.ck.Eva();else break;this.vx&&this.ee.Lm(this.yc,this.Td,this.de?this.ee.Jb:this.ee.xb);this.Wca();r.IH(this,this.Ul);this.Qxa();e&&this.dispatchEvent(this.Tz())};a.Zd.prototype.Qxa=function(){if(this.Tc){var b=this.Tc.length,c=this.rR(b);this.Qi=(this.cj-c)/b;for(var d=0;d<b;d++){var e=this.Tc[d];e.te(null);var f=new a.Cd;if(this.de){var h=this.No()?Math.abs(d-
1):d;this.No()&&1==this.Tc.length?(f.Pe(c,0,this.Qi,this.je),h=new a.Tb(1,0,0,1,c,0)):(f.Pe(h*(this.Qi+c),0,this.Qi,this.je),h=new a.Tb(1,0,0,1,h*(this.Qi+c),0));var k=this.Qi,l=this.je}else f.Pe(0,d*(this.Qi+c),this.je,this.Qi),h=new a.Tb(1,0,0,1,0,d*(this.Qi+c)),k=this.je,l=this.Qi;e.te(f);e.rb(h);e.ta(null,k,l)}}};a.Zd.prototype.eH=function(a,b){this.xb=a;this.Jb=b;this.IE();this.qz=0;this.Jv=this.de?b:a;this.lfa();r.Gr(this);if(this.hy()){if(this.wfa(this.nh),this.Wca(),this.Qxa(),r.IH(this,this.Ul),
r.pOa(this),r.nOa(this),r.e2(this),this.vx&&(r.jOa(this),this.Rc)){var c=this.Rc.rI();if(c&&0!=c.length)for(var d=0;d<c.length;d++)this.ee.aWa(c[d])}}else r.JH(this)};a.Zd.prototype.SS=function(b){a.KeyboardEvent.uf!=b.keyCode&&a.KeyboardEvent.Jf!=b.keyCode&&a.KeyboardEvent.Tf!=b.keyCode&&a.KeyboardEvent.kh!=b.keyCode||this.aXa(this.I.jf())};a.Zd.prototype.TF=function(a){this.Wk=this.l0(a.target)};a.Zd.prototype.dI=function(){this.Wk=null;this.rda()};a.Zd.prototype.rda=function(){this.VH&&(this.VH=
!1,this.dispatchEvent(this.Tz()))};a.Zd.prototype.Wi=function(a,b){var c=this.rR(this.Tc.length);if(this.de){if(this.Wk){var d=this.Wk.qa()-a;if(1<this.Tc.length&&(!this.No()&&this.Wk.zo||this.No()&&!this.Wk.zo))var e=c+2*this.Wk.xb-this.Wk.$k,c=this.Wk.xb+c;else this.No()&&!this.Wk.zo?e=this.Wk.xb-this.Wk.$k+c:(e=0,c=this.Wk.$k-this.Wk.xb);d<e?d=e:d>c&&(d=c);this.Wk.ga(d)}this.uwa(b);this.vx&&(d=this.ee.Jb,this.ee.Lm(this.yc,this.Td,d))}else this.uwa(a),this.vx&&(d=this.ee.xb,this.ee.Lm(this.yc,
this.Td,d)),this.Wk&&(d=this.Wk.pa()-b,this.Wk.zo?(e=c+2*this.Wk.Jb-this.Wk.$k,c=this.Wk.Jb+c):(e=0,c=this.Wk.$k-this.Wk.Jb),d<e?d=e:d>c&&(d=c),this.Wk.wa(d))};a.Zd.prototype.eZ=function(b){var c=b.type;if("selection"==c||"action"==c)a.IA.dispatchEvent(this.Cc,this.pb,this,b);else if("overview"==c){c=b.Zn();if("rangeChanging"==c||"rangeChange"==c){var d=this.Td-this.yc;this.yc=b.yua();this.Td=b.xua();var e=this.Td-this.yc;if(0<e){var f=this.Uf/e;this.qF(f*(this.Ic-this.Yb));this.yA(f*(this.Yb-this.yc));
f=this.ck.tW;if(d>e){d=f.length;for(e=f[d-1];this.je>=e&&0<d;)d--,e=f[d-1];d==f.length&&d--}else for(d=0,e=f[d];this.je<e&&d<f.length-1;)d++,e=f[d];this.ck.eS(d);this.ck.zt(this.ck.ZH[d]);this.Wca();r.IH(this,this.Ul);this.Qxa();this.AW()}"rangeChange"==c&&this.dispatchEvent(this.Tz())}if("scrollPos"==c||"scrollTime"==c)this.yc=b.yua(),this.Td=b.xua(),f=this.je/(this.Ic-this.Yb),this.yA(f*(this.Yb-this.yc)),this.AW(),this.dispatchEvent(this.Tz())}else if(c=b.Zn(),"selection"==c){var c=b.dR(),h=b.tob()&&
"multiple"==this.dw;for(b=0;b<this.Tc.length;b++)for(f=this.Tc[b],d=0;d<f.dc.length;d++)if(e=f.dc[d],e.getId()==c){this.Rc.b_(e,h);this.I.Su(e);this.xtb(e);break}}else if("highlight"==c)for(c=b.dR(),b=0;b<this.Tc.length;b++)for(f=this.Tc[b],d=0;d<f.dc.length;d++){if(e=f.dc[d],e.getId()==c){e.qd(!0);break}}else if("unhighlight"==c)for(c=b.dR(),b=0;b<this.Tc.length;b++)for(f=this.Tc[b],d=0;d<f.dc.length;d++)if(e=f.dc[d],e.getId()==c){e.Nc(!0);break}};a.Zd.prototype.xtb=function(a){var b=this.Td-this.yc;
this.yc=a.Ti()-b/2;this.yc<this.Yb?this.yc=this.Yb:this.yc+b>this.Ic&&(this.yc=this.Ic-b);this.Td=this.yc+b;this.yA(this.je/(this.Ic-this.Yb)*(this.Yb-this.yc));this.AW();this.dispatchEvent(this.Tz())};a.Zd.prototype.aXa=function(a){var b=this.de?a.getHeight():a.getWidth(),c=p.ESa(),d=a.CB-(this.de?b/2+c:p.k3()+c);a=this.DTa();this.No()&&!this.de&&(d-=c);b=d+b+2*c;c=a-this.Uf;-d>a?a=-d:-b<c&&(a=-b+this.Uf);d=this.je/(this.Ic-this.Yb);b=this.Td-this.yc;this.yc=this.Yb-a/d;this.yc<this.Yb&&(this.yc=
this.Yb,a=(this.Yb-this.yc)*d);this.Td=this.yc+b;this.Td>this.Ic&&(this.Td=this.Ic,this.yc=this.Td-b,a=(this.Yb-this.yc)*d);this.yA(a);this.AW();this.vx&&this.ee.Lm(this.yc,this.Td,this.de?this.ee.Jb:this.ee.xb);this.dispatchEvent(this.Tz())};a.Zd.prototype.uva=function(a){if(a&&(a=this.FU(a.target))){var b=this.l0(a);a.yd&&(b=this.l0(a),b.RZa(a.yd))}};a.Zd.prototype.uQa=function(){if(this.W.selection)for(var a=[],b=0;b<this.Tc.length;b++)for(var c=this.Tc[b],d=0;d<c.dc.length;d++)a.push(c.dc[d]);
this.Rc.tt(this.W.selection,a)};a.Zd.prototype.l0=function(a){if(this.hy()&&a&&a!=this){var b=a.getId();return a==this.Tc[0]||1<this.Tc.length&&a==this.Tc[1]?a:b&&"_s0"==b.substring(b.length-3,b.length)?this.Tc[0]:b&&"_s1"==b.substring(b.length-3,b.length)?this.Tc[1]:this.l0(a.getParent())}return null};a.Zd.prototype.FU=function(a){if(a){var b=a.getId();if(b&&"_duration_"==b.substring(0,10)&&a.yd)return a;var c=a.getParent();if(c){if(b&&"zoom"==b.substring(0,4))return a;if(b&&"_bubble_"==b.substring(0,
8)&&c.yd)return c;if(a=c.getParent()){if(b&&"_bubble_"==b.substring(0,8)&&a.yd)return a;if((b=a.getId())&&"_bubble_"==b.substring(0,8)&&a.getParent())return a.getParent()}}}return null};a.Zd.prototype.ph=function(){this.Rd||(this.Rd=new k(this));return this.Rd};a.Zd.prototype.kib=function(){this.nh&&this.nh.Hl();this.OQa()};a.Zd.prototype.OQa=function(){this.Hz&&(this.removeChild(this.Hz),this.Hz=null)};a.v.D(k,a.Rd);k.EDa="timelineItem";k.prototype.zn=function(b){if((b=this.Ho.I.mb(b))&&b instanceof
c)for(var d=0;d<this.Ho.Tc.length;d++){var e=a.na.kb(this.Ho.Tc[d].dc,b);if(-1!=e)return k.EDa+"["+d+"]["+e+"]"}return null};k.prototype.qh=function(a){if(a){var b=a.indexOf("[");if(0<b&&a.substring(0,b)===k.EDa){var c=a.indexOf("]");if(0<c){var d=parseInt(a.substring(c+2,a.length-1));if(a=this.Ho.Tc[parseInt(a.substring(b+1,c))])if(d=a.dc[d])return d.Qe()[0].Ua()}}}return null};a.v.D(h,a.bb);h.lh={animationOnDataChange:"none",animationOnDisplay:"none",orientation:"horizontal",overview:{rendered:"off"},
selectionMode:"none",styleDefaults:{animationDuration:500,borderColor:"#d9dfe3",item:{backgroundColor:"#ffffff",borderColor:"#648baf",descriptionStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; color: #084B8A; white-space: nowrap;"),hoverBorderColor:"#85bbe7",selectedBorderColor:"#000000",titleStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: bold; color: #000000; white-space: nowrap;")},majorAxis:{labelStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 14px; font-weight: bold; color: #4f4f4f; background-color: rgba(249,249,249,0.8); white-space: nowrap;"),
separatorColor:"#bcc7d2"},minorAxis:{backgroundColor:"#f9f9f9",borderColor:"#d9dfe3",labelStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; color: #333333;"),separatorColor:"#bcc7d2"},overview:{backgroundColor:"#e6ecf3",labelStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: bold; color: #4f4f4f;"),window:{backgroundColor:"#ffffff",borderColor:"#4f4f4f"}},referenceObject:{color:"#ff591f"},series:{backgroundColor:"#f9f9f9",
colors:a.j.Bya,emptyTextStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; font-weight: normal; color: #333333; white-space: nowrap;"),labelStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 13px; font-weight: bold; color: #252525; background-color: rgba(249,249,249,0.8); white-space: nowrap;")}}};a.v.D(f,a.v);f.prototype.parse=function(a){var b={};b.start=(new Date(a.start)).getTime();b.end=(new Date(a.end)).getTime();a.viewportStart&&
(b.Uxa=(new Date(a.viewportStart)).getTime());a.viewportEnd&&(b.Txa=(new Date(a.viewportEnd)).getTime());b.TR=a.selectionMode?a.selectionMode:"none";b.tX=a.style;var c=a.minorAxis;c&&(b.scale=c.scale,b.W2=c._cfs);if(c=a.majorAxis)b.lrb=c.scale,b.irb=c.converter,b.jrb=c._cfs;b.Gxa=a.shortDesc;b.orientation=a.orientation;if((c=a.referenceObjects)&&0<c.length){for(var d=[],e=0;e<c.length;e++)d.push(new Date(c[e].value));b.qqb=d}c=a.overview;b.Pnb=null!=c&&"on"==c.rendered?!0:!1;b.Ixa=a._tzo;b.VUa=a._ip;
b.X2=a._cts;return b};var r={};a.v.D(r,a.v);r.Oqb=function(b){r.Gr(b);r.c2(b);if(b.hy()){b.wfa(b.nh);var c=b.Ul;r.pfb(b,c);r.pOa(b);r.IH(b,c);b.vx?r.jOa(b):b.OQa();if(b.$D)for(c=0;c<b.Tc.length;c++){var d=b.Tc[c];if(d.dc&&0<d.dc.length){b.I.Su(d.dc[0]);break}}r.nOa(b);r.e2(b);b.Rc&&b.uQa();a.Ub.vn()&&b.m2("flowto",b.Tc[0].getId());for(c=0;c<b.Tc.length;c++)d=b.Tc[c],d.Lxa();a.B.xj()&&!b.Hva()&&b.w5()}else r.JH(b)};r.Gr=function(b){b.Gb?(b.Gb.te(null),b.Gb.Xa(b.Zt),b.Gb.qb(b.Yy)):b.Gb=new a.Rect(b.u(),
0,0,b.Zt,b.Yy,"bg");b.Gb.Bb(b.Gk);b.Gb.md();var c=new a.Cd;c.Pe(0,0,b.Zt,b.Yy);b.Gb.te(c);b.Gb.getParent()!=b&&b.A(b.Gb)};r.c2=function(b){b.nh||(b.nh=new a.la(b.u(),"canvas"),b.A(b.nh))};r.pfb=function(b,c){var d=b.BM();if(b.Tc){var e=a.B.da(b.u()),f=b.Tc.length,h=b.rR(f);!b.Sb()&&1<f&&b.cj%2!=h%2&&(d.kxa(d.Dv+1),h=b.rR(f));b.Qi=(b.cj-h)/f;for(d=0;d<f;d++){var k=b.Tc[d];k.te(null);var l=new a.Cd;if(b.Sb()){var n=e?Math.abs(d-1):d;e&&1==b.Tc.length?(l.Pe(h,0,b.Qi,b.je),n=new a.Tb(1,0,0,1,h,0)):(l.Pe(n*
(b.Qi+h),0,b.Qi,b.je),n=new a.Tb(1,0,0,1,n*(b.Qi+h),0));var m=b.Qi,p=b.je}else l.Pe(0,d*(b.Qi+h),b.je,b.Qi),n=new a.Tb(1,0,0,1,0,d*(b.Qi+h)),m=b.je,p=b.Qi;k.te(l);k.rb(n);k.getParent()!=c&&c.A(k);k.ta(b.dca[d],m,p)}}};r.pOa=function(b){if(b.Tc){var c=b.u(),d=a.B.da(c);if(b.UV)for(var e=0;e<b.UV.length;e++)b.removeChild(b.UV[e]);b.UV=[];for(var f=b.Tc.length,h=p.Gmb(),k=2*a.Ah.m8+6,l=2*h,e=0;e<f;e++){var n=b.Tc[e],m=n.ge();if(null!=m){var r=p.Hmb(b.W),m=new a.ca(c,m,0,0,"sl_s"+e);m.Bb(r);b.A(m);var w=
m.aa();b.removeChild(m);var x=b.Sb()?b.Qi:b.Uf,x=Math.min(w.a,x-(e-1)*-k-l),fa=p.Fmb(),ga=new a.Rect(c,0,0,x+2*fa,w.b+2*fa,"slb_s"+e);ga.Bb(r);ga.JC(3);if(b.Sb())r=d?Math.abs(e-1)*(b.cj-x-l)+h+b.bn+(e-1)*k:e*(b.cj-x-l)+h+b.bn+(e-1)*-k,aa=b.Un+h;else var r=d?b.Uf-x-h-(e-1)*-k:b.bn+h+(e-1)*-k,aa=e*(b.cj-w.b-l)+h+b.Un;w=new a.Tb(1,0,0,1,r,aa);m.rb(w);w=new a.Tb(1,0,0,1,r-fa,aa-fa);ga.rb(w);b.A(ga);a.Ca.kd(m,x,Infinity,b);b.UV.push(ga);b.UV.push(m)}n.Xbb&&(n=n.Vm,null!=n&&(n=new a.ca(c,n,0,0,"et_s"+e),
n.Bb(p.uSa(b.W)),b.A(n),w=n.aa(),b.removeChild(n),w=new a.Tb(1,0,0,1,(b.Uf-w.a)/2+b.bn,e*(b.Qi+b.rR(f))+(b.Qi-w.b)/2+b.Un),n.rb(w),b.A(n),b.UV.push(n)))}}};r.IH=function(b,c){var d=a.B.da(b.u()),e=b.BM(),f=b.Tc.length,h=b.gva(),k=b.rR(f),f=1==f?b.cj-k:b.cj/f-k/2;d&&b.Sb()&&1==b.Tc.length&&(f=0);e.getParent()!==c&&c.A(e);b.Sb()?(d=new a.Tb(1,0,0,1,f,0),e.ta(null,h,b.je)):(d=new a.Tb(1,0,0,1,0,f),e.ta(null,b.je,h));e.rb(d);r.ira(b,b.qz,b.Jv,b.Ul,b.je)};r.ira=function(b,c,d,e,f){var h=b.u(),k=a.B.da(h);
if(b.zP)for(var l=0;l<b.zP.length;l++)e.removeChild(b.zP[l]);b.zP=[];if(b.ou){var n,m,w=b.Yb,x=b.Ic;if(b.xo&&b.xo[b.ou])m=b.xo[b.ou],n=m.times,m=m.labels;else if(b.rQ&&b.rQ[b.ou])m=b.rQ[b.ou],n=m.times,m=m.labels;else for(n=[],m=[],l=a.Ub.Si(w,x,c,f),l=b.Mq.zW(l),c=a.Ub.bf(w,x,l,f),n.push(l.getTime());c<d;)m.push(b.Mq.tta(l)),l=b.Mq.eX(l.getTime()),c=a.Ub.bf(w,x,l,f),n.push(l.getTime());for(l=0;l<m.length;l++){d=m[l];c=a.Ub.bf(w,x,n[l],f);var O=a.Ub.bf(w,x,n[l+1],f)-c;(k?b.Sb()?r.I8(h,e,b.cj-5,d,
O,c+18,p.rea(b.W),"o_label"+c+"_s0",p.qea(),b.zP,k):r.I8(h,e,f-(c+5),d,O,b.Qi-2,p.rea(b.W),"o_label"+c+"_s0",p.qea(),b.zP,k):b.Sb()?r.I8(h,e,5,d,O,c+18,p.rea(b.W),"o_label"+c+"_s0",p.qea(),b.zP,k):r.I8(h,e,c+5,d,O,b.Qi-2,p.rea(b.W),"o_label"+c+"_s0",p.qea(),b.zP,k)).time=n[l]}}};r.jOa=function(b){var c=b.u(),d=a.B.da(c);if(null==b.Hz){var e=!0;b.Hz=new a.la(c,"oCanvas")}else b.Hz.Hl();var f=b.Gk.Pg(),h=f/2;if(b.Sb()){var k=b.vL,f=b.Jb-f;d?b.Hz.ga(h):b.Hz.ga(b.xb-b.vL-h);b.Hz.wa(h)}else k=b.xb-f,f=
b.vL,b.Hz.wa(b.Jb-b.vL-h),b.Hz.ga(h);e&&b.A(b.Hz);b.ee=new a.Hb(c,b.eZ,b);b.Hz.A(b.ee);c=b.Aab();b.ee.ta(c,k,f)};r.nOa=function(b){if(b.Tc){var c=b.u(),d=a.B.da(c),e=b.Tc.length,f=b.rR(e);if(b.j2)for(var h=0;h<b.j2.length;h++)b.j2[h].Hl();else{var k=!0;b.j2=[]}b.KL=[];for(var l=p.olb(),n=p.plb(),m=p.mlb(),r=p.jlb(),w=p.ilb(),x=p.klb(),fa=p.llb(),h=0;h<e;h++){if(k){var ga=new a.la(c,"hotspots_s"+h);b.A(ga);b.j2.push(ga)}else ga=b.j2[h];if(b.Sb())var aa=d?Math.abs(h-1):h,ea=U=b.bn+aa*(b.Qi+f)+(b.Qi-
n)/2,ia=b.Un+l,T=b.Un+b.Uf-m-l,aa=L=U+r/2,Z=ia+w/2,W=T+w/2,R=b.jj.scrollUp,X=b.jj.scrollDown;else var U=b.bn+l,ea=b.bn+b.Uf-n-l,ia=b.Un+h*(b.Qi+f)+(b.Qi-m)/2,T=ia,L=U+r/2,aa=ea+r/2,Z=ia+w/2,W=Z,R=b.jj.scrollLeft,X=b.jj.scrollRight;U=new a.Rect(c,U,ia,n,m,"lhs");U.fb(x,1);U.JC(fa);U.yR="left";U.T(0);U.nb(!1);L=new a.Image(c,R,L,Z,r,w,"lhs_arr");L.yR="left";U.A(L);ea=new a.Rect(c,ea,T,n,m,"rhs");ea.fb(x,1);ea.JC(fa);ea.yR="right";ea.T(0);ea.nb(!1);aa=new a.Image(c,X,aa,W,r,w,"rhs_arr");aa.yR="right";
ea.A(aa);ga.A(U);b.KL.push(U);ga.A(ea);b.KL.push(ea);b.Sb()?(aa=d?Math.abs(h-1):h,U=b.bn+aa*(b.Qi+f)+l,ea=b.bn+(aa+1)*b.Qi+aa*f-n-l,T=ia=b.Un+(b.Uf-m)/2,L=U+r/2,aa=ea+r/2,W=Z=ia+w/2,R=b.jj.scrollLeft,X=b.jj.scrollRight):(ea=U=b.bn+(b.Uf-n)/2,ia=b.Un+h*(b.Qi+f)+l,T=b.Un+(h+1)*b.Qi+h*f-m-l,aa=L=U+r/2,Z=ia+w/2,W=T+w/2,R=b.jj.scrollUp,X=b.jj.scrollDown);U=new a.Rect(c,U,ia,n,m,"ths");U.fb(x,1);U.JC(fa);U.yR="top";U.T(0);U.nb(!1);L=new a.Image(c,R,L,Z,r,w,"ths_arr");L.yR="top";U.A(L);ea=new a.Rect(c,ea,
T,n,m,"bhs");ea.fb(x,1);ea.JC(fa);ea.yR="bottom";ea.T(0);ea.nb(!1);aa=new a.Image(c,X,aa,W,r,w,"bhs_arr");aa.yR="bottom";ea.A(aa);ga.A(U);b.KL.push(U);ga.A(ea);b.KL.push(ea)}}};r.e2=function(b){var c=b.u(),d=a.B.da(c),e=b.BM(),f=b.jj,h=p.pnb(f),k=p.qnb(f),l=p.tnb(f),n=p.unb(f),m=p.nnb(f),r=p.onb(f),w=p.rnb(f),x=p.snb(f),h=a.Ah.mt(c,f.zoomIn,h,k),l=a.Ah.mt(c,f.zoomIn_h,l,n),m=a.Ah.mt(c,f.zoomIn_a,m,r),w=a.Ah.mt(c,f.zoomIn_d,w,x);null==b.Jh?(b.Jh=new a.Ah(c,h,l,m,w,b.I,b.I.iZ),b.I.lb(b.Jh,b.Jh)):(b.Jh.zF(h),
b.Jh.vF(l),b.Jh.sF(m),b.Jh.Z4(w));h=p.xnb(f);k=p.ynb(f);l=p.Bnb(f);n=p.Cnb(f);m=p.vnb(f);r=p.wnb(f);w=p.znb(f);x=p.Anb(f);h=a.Ah.mt(c,f.zoomOut,h,k);l=a.Ah.mt(c,f.zoomOut_h,l,n);m=a.Ah.mt(c,f.zoomOut_a,m,r);w=a.Ah.mt(c,f.zoomOut_d,w,x);null==b.Kh?(b.Kh=new a.Ah(c,h,l,m,w,b.I,b.I.jZ),b.I.lb(b.Kh,b.Kh)):(b.Kh.zF(h),b.Kh.vF(l),b.Kh.sF(m),b.Kh.Z4(w));b.Jh.tn(a.H.va(a.H.Ha,"ZOOM_IN",null));b.Kh.tn(a.H.va(a.H.Ha,"ZOOM_OUT",null));b.Jh.Vq();b.Kh.Vq();a.Ub.vn()&&(a.K.Y(b.Jh.Ua(),"role","button"),a.K.Y(b.Jh.Ua(),
"aria-label",a.H.va(a.H.Ha,"ZOOM_IN",null)),a.K.Y(b.Kh.Ua(),"role","button"),a.K.Y(b.Kh.Ua(),"aria-label",a.H.va(a.H.Ha,"ZOOM_OUT",null)));c=b.bn+p.UZ;d=d?b.Zt-c-p.aK:c;b.Jh.ga(d);b.Kh.ga(d);d=b.Un+p.UZ;b.Jh.wa(d);b.Kh.wa(d+p.aK+p.VZ);b.Jh.getParent()!=b.nh&&b.nh.A(b.Jh);b.Kh.getParent()!=b.nh&&b.nh.A(b.Kh);d=b.je;d>=e.qV&&b.cM(!0);b.Uf>=d&&b.cM(!1)};r.JH=function(b){var c=b.W.series?a.H.va(a.H.Ha,"INVALID_DATA",null):a.H.va(a.H.Ha,"NO_DATA",null);b.kib();a.Ca.vp(b.nh,c,new a.Z(0,0,b.Zt,b.Yy),b.I,
p.uSa(b.W))};r.I8=function(b,c,d,e,f,h,k,l,n,m,p){e=new a.ca(b,e,d,0,l);null!=k&&e.Bb(k);c.A(e);var r=e.aa();c.removeChild(e);h-=r.b;e.jb(h);p&&e.Fa(d-r.a);var w=Math.min(r.a+2*n,f);b=new a.Rect(b,(p?d-w+2*n:d)-n,h-n,w,r.b+2*n,"ob_"+l);b.Bb(k);b.JC(3);c.A(b);m&&m.push(b);a.Ca.kd(e,f,Infinity,c);m&&m.push(e);return e};var p={};a.v.D(p,a.v);p.X3a="border:1px #d9dfe3;background-color:#f9f9f9;";p.Vub="background-color:#f9f9f9;border:1px #d9dfe3;";p.l3a="color:#bcc7d2;";p.R3a="background-color:#f9f9f9;";
p.Q3a=20;p.P3a=2;p.O3a="color:#bcc7d2";p.N3a=1;p.M3a=60;p.L3a=100;p.K3a="#B3C6DB";p.x3a="#000000";p.y3a=2;p.A3a=.6;p.C3a=28;p.z3a=28;p.B3a=3;p.w3a=14;p.v3a=14;p.u3a=.3;p.F3a=1;p.G3a=2;p.J3a=2;p.H3a="rgba(249,249,249,0)";p.D3a="#e4f0fa";p.E3a="rgba(249,249,249,0)";p.I3a=2;p.m3a=20;p.n3a=15;p.o3a=10;p.W3a=32;p.V3a=32;p.pD="#ffffff";p.qD="#d6d7d8";p.aK=31;p.UZ=10.5;p.VZ=9;p.DSa=function(b){var c=b.Tc.F().styleDefaults.item.descriptionStyle;if(b=b.M())b=new a.j(b),c.lj(b);return c};p.KSa=function(b){var c=
b.Tc.F().styleDefaults.item.titleStyle;if(b=b.M())b=new a.j(b),c.lj(b);return c};p.CTa=function(a){return a.styleDefaults.referenceObject.color};p.Hmb=function(a){return a.styleDefaults.series.labelStyle};p.Fmb=function(){return p.P3a};p.Gmb=function(){return p.Q3a};p.uSa=function(a){return a.styleDefaults.series.emptyTextStyle};p.k3=function(){return p.m3a};p.Sx=function(){return p.n3a};p.nua=function(b){var c=b.M();return c&&(c=(new a.j(c)).M(a.j.Lb))?c:b.Tc.F().styleDefaults.item.backgroundColor};
p.F3=function(b){var c=b.M();return c&&(c=(new a.j(c)).M(a.j.ub))?c:b.Tc.F().styleDefaults.item.borderColor};p.oua=function(){return p.F3a};p.tlb=function(a){var b=a.Tc.F().styleDefaults.item.hoverBackgroundColor;return b?b:p.nua(a)};p.ulb=function(a){var b=a.Tc.F().styleDefaults.item.hoverBorderColor;return b?b:p.F3(a)};p.ESa=function(){return p.G3a};p.HSa=function(a){var b=a.Tc.F().styleDefaults.item.selectedBackgroundColor;return b?b:p.nua(a)};p.ISa=function(a){var b=a.Tc.F().styleDefaults.item.selectedBorderColor;
return b?b:p.F3(a)};p.JSa=function(){return p.J3a};p.Imb=function(){return p.R3a};p.qkb=function(a){return a.styleDefaults.series.colors};p.tSa=function(){return p.o3a};p.fva=function(){return p.W3a};p.STa=function(){return p.V3a};p.Emb=function(){return p.O3a};p.FSa=function(){return p.D3a};p.vlb=function(){return p.H3a};p.GSa=function(){return p.E3a};p.wlb=function(){return p.I3a};p.ySa=function(){return p.u3a};p.nlb=function(){return p.A3a};p.Zmb=function(){return p.X3a};p.dmb=function(){return p.M3a};
p.Hua=function(){return p.L3a};p.emb=function(a){return a.styleDefaults.overview.window.backgroundColor};p.fmb=function(a){return a.styleDefaults.overview.window.borderColor};p.bmb=function(a){return a.styleDefaults.overview.backgroundColor};p.cmb=function(a){return a.styleDefaults.overview.labelStyle};p.uTa=function(){return p.K3a};p.rea=function(a){return a.styleDefaults.majorAxis.labelStyle};p.RRa=function(){return p.l3a};p.qea=function(){return p.N3a};p.olb=function(){return p.B3a};p.plb=function(){return p.C3a};
p.mlb=function(){return p.z3a};p.jlb=function(){return p.w3a};p.ilb=function(){return p.v3a};p.klb=function(){return p.x3a};p.llb=function(){return p.y3a};p.ob=function(b){return a.Ta.Pr(b.styleDefaults.animationDuration)/1E3};p.pnb=function(a){return a.zoomIn_bgc?a.zoomIn_bgc:p.pD};p.nnb=function(a){return a.zoomIn_a_bgc?a.zoomIn_a_bgc:p.pD};p.tnb=function(a){return a.zoomIn_h_bgc?a.zoomIn_h_bgc:p.pD};p.rnb=function(a){return a.zoomIn_d_bgc?a.zoomIn_d_bgc:p.pD};p.qnb=function(a){return a.zoomIn_bc?
a.zoomIn_bc:p.qD};p.onb=function(a){return a.zoomIn_a_bc?a.zoomIn_a_bc:p.qD};p.unb=function(a){return a.zoomIn_h_bc?a.zoomIn_h_bc:p.qD};p.snb=function(a){return a.zoomIn_d_bc?a.zoomIn_d_bc:p.qD};p.xnb=function(a){return a.zoomOut_bgc?a.zoomOut_bgc:p.pD};p.vnb=function(a){return a.zoomOut_a_bgc?a.zoomOut_a_bgc:p.pD};p.Bnb=function(a){return a.zoomOut_h_bgc?a.zoomOut_h_bgc:p.pD};p.znb=function(a){return a.zoomOut_d_bgc?a.zoomOut_d_bgc:p.pD};p.ynb=function(a){return a.zoomOut_bc?a.zoomOut_bc:p.qD};p.wnb=
function(a){return a.zoomOut_a_bc?a.zoomOut_a_bc:p.qD};p.Cnb=function(a){return a.zoomOut_h_bc?a.zoomOut_h_bc:p.qD};p.Anb=function(a){return a.zoomOut_d_bc?a.zoomOut_d_bc:p.qD};a.v.D(e,a.Ie);e.prototype.Init=function(a,b,c){e.C.Init.call(this,a);this.Cc=b;this.pb=c;this.zO=[];this.f2=[];this.fca=[]};e.prototype.Lxa=function(){var b=this.u();this.FL&&0!=this.FL.length?(this.taa=!0,b=new a.Gg(b,new a.Xi(b,this.FL,p.ob(this.W))),b.play(),a.eb.Mb(b,this.rqa,this)):this.xH?(this.taa=!0,this.xH.play(),
a.eb.Mb(this.xH,this.qqa,this)):this.$G&&0!=this.$G.length&&(this.taa=!0,b=new a.Gg(b,new a.ih(b,this.$G,p.ob(this.W),0)),b.play(),a.eb.Mb(b,this.Tv,this))};e.prototype.rqa=function(){for(var b=0;b<this.FL.length;b++){var c=this.FL[b],d=c.getParent();d&&d.removeChild(c)}this.xH&&this.tKa?(this.xH.play(),a.eb.Mb(this.xH,this.qqa,this)):this.qqa()};e.prototype.qqa=function(){if(this.$G&&0!=this.$G.length){var b=new a.Gg(this.u(),new a.ih(this.u(),this.$G,p.ob(this.W),0));b.play();a.eb.Mb(b,this.Tv,
this)}else this.Tv()};e.prototype.Tv=function(){this.taa=!1;this.pb.Apb()};e.prototype.ta=function(b,c,d){if(b){if(this.vf(b),this.acb=this.xb?!1:!0,this.xb=c,this.Jb=d,(b=this.W.orientation)&&b==a.Zd.m7?(this.c_=0==this.de?!1:!0,this.de=!0):(this.c_=this.de?!1:!0,this.de=!1),this.W&&(b=this.eD(this.W),this.uv(b)),this.qz=0,this.de?(this.Jv=d,this.$k=c,this.Fj=d,this.ew=c):(this.Jv=c,this.$k=d,this.Fj=c,this.ew=d),this.zo=this.W.inverted,this.sH=this.JD=0,x.Mqb(this,c,d),a.Ub.vn()&&0<this.dc.length&&
this.m2("flowto","_bt_"+this.dc[0].getId()),c=this.gm())a.K.Y(this.Ua(),"role","group"),a.K.Y(this.Ua(),"aria-label",a.Nd.HI(c))}else this.eH(c,d)};e.prototype.gm=function(){var b=[a.H.va(a.H.Ha,"TIMELINE_SERIES")];this.Ec?b.push(this.Ec):b.push(this.W.index+1);return a.H.va(a.H.Ha,"COLON_SEP_LIST",b)};e.prototype.eH=function(a,b){this.nh.wa(0);this.nh.ga(0);this.xb=a;this.Jb=b;this.qz=0;this.de?(this.Jv=b,this.$k=a,this.Fj=b,this.ew=a):(this.Jv=a,this.$k=b,this.Fj=a,this.ew=b);this.Gb.Xa(a);this.Gb.qb(b);
x.ytb(this)};e.prototype.IE=function(){this.Gk=new a.j(p.Imb());this.sQ=this.W.seriesStyleDefaults;this.tGa=this.W.axisStyleDefaults;this.mHa=p.qkb(this.W);this.kQ=this.W.referenceObjects;if(this.sQ){var b=this.sQ.backgroundColor;b&&this.Gk.lj("background-color:"+b+";")}this.Gk.lj(this.bL)};e.prototype.vf=function(a){this.W=a};e.prototype.eD=function(a){this.Yv=new b;return this.Yv.parse(a,this.dc)};e.prototype.uv=function(b){this.dc&&(this.p1=this.dc);this.Xbb=(this.dc=b.items)&&0<this.dc.length?
!1:!0;this.bpa=b.Qva;this.Wbb=b.Kva;this.Ec=b.label;this.ck=b.itb;this.Vm=b.qjb;null==this.Vm&&(this.Vm=a.H.va(a.H.Ha,"NO_DATA",null));this.kcb=b.JM;this.yaa=b.Aob;this.xo=b.X2;this.PG=b.W2;this.Yb=b.start;this.Ic=b.end;this.bL=b.tX;this.nf=b.scale;this.Mp=b.UQa;this.IE()};e.prototype.JQa=function(a,b){if(null!=this.dc&&0!=this.dc.length){var c=this.$k,d=a.Nz;if(this.yaa){if(null==d){var c=a.getHeight(),d=this.xx,e=this.$k-c-d;0>e&&(e=0);d=Math.round(Math.random()*e)+d;this.$k<d+c&&(this.$k=d+c+p.Sx())}return d}null==
d&&(d=this.xx);if(this.de)for(l=0;l<b;l++)n=this.dc[l],m=n.getWidth()+10,c<d+m&&(c=d+m);else{for(var f=a.CB,h=a.getWidth()+10,e=p.Sx(),k=[],l=0;l<b;l++){var n=this.dc[l],m=n.getWidth()+10,r=n.CB;(f>=r&&f<=r+m||r>=f&&r<=f+h)&&k.push(n)}for(l=0;l<k.length;l++){f=!1;for(h=0;h<k.length;h++){var n=k[h],w=n.getHeight(),n=n.Nz;if(d>=n&&d<=n+w){d=n+w+e;a.p5(d);f=!0;break}}if(!f)break}c<d+w&&(c=d+w)}c>this.$k&&(this.$k=c+p.Sx());return d}};e.prototype.Xhb=function(a,b){if(null!=this.dc&&0!=this.dc.length){var c=
a.Ti(),d=a.hl();if(d&&d!=c){d=a.lz;null==d&&(d=1);for(var e=[],f=0;f<b;f++){var h=this.dc[f],k=h.Ti(),l=h.hl();l&&l!=k&&c>=k&&c<=l&&e.push(h)}for(f=0;f<e.length;f++){c=!1;for(k=0;k<e.length;k++)if(h=e[k],h=h.lz,d==h){d=h+1;a.txa(d);c=!0;break}if(!c)break}d>this.sH&&(this.sH=d);return d}}};e.prototype.Gwa=function(){for(var a=0;a<this.dc.length;a++){var b=this.dc[a],c=b.Ti(),d=b.hl();d&&d!=c&&(b.txa(this.Xhb(b,a)),b.Rrb(22+10*b.lz-5),null==b.XG&&(b.Qrb(this.mHa[this.JD]),this.JD++,this.JD==this.mHa.length&&
(this.JD=0)))}};e.prototype.Spb=function(b){this.Sb()?this.xx=20*(0<this.sH?1:0)+p.Sx()+10*this.sH:this.xx=20+p.Sx()+10*this.sH;for(var c=0;c<b.length;c++){var d=b[c],e=a.Ub.bf(this.Yb,this.Ic,d.Ti(),this.Fj),f=d.hl();f&&f!=d.Ti()&&(f=a.Ub.bf(this.Yb,this.Ic,f,this.Fj)-e,e+=Math.min(p.tSa(),f/2));d.zxa(e)}for(c=0;c<this.dc.length;c++)d=this.dc[c],e=a.Ub.bf(this.Yb,this.Ic,d.Ti(),this.Fj),e<this.qz||e>this.Jv||w.$nb(d,this,c)};e.prototype.ge=function(){return this.Ec};e.prototype.RZa=function(b){var c=
b.Ch();c&&(b=a.Za.FI("action",c,b.getId()),a.IA.dispatchEvent(this.Cc,this.pb,this,b))};e.prototype.JM=function(){return this.kcb};e.prototype.Sb=function(){return this.de};e.prototype.Gsa=function(b,c,d,e,f,h,k){c=new a.Gc(this.u(),c,e,d,f,k);c.Ga(h);c.md();b.A(c);return c};e.prototype.Ssb=function(a){null!=this.nh&&this.nh.wa(0-a)};e.prototype.Xrb=function(a){null!=this.nh&&this.nh.ga(0-a)};a.v.D(d,a.la);d.r6="en";d.A7="sel";d.C5="asel";d.AAa="hl";d.prototype.Init=function(a,b){d.C.Init.call(this,
a,"g",b)};d.prototype.kc=function(a){this.Ql!=a&&((this.Ql=a)?this.Qp?this.Pq(d.C5):this.Pq(d.A7):this.Pq(d.r6))};d.prototype.qd=function(a){this.Qp||(this.Qp=!0,this.Ql&&a?this.Pq(d.C5):this.Ql?this.Pq(d.A7):this.Pq(d.AAa))};d.prototype.Nc=function(a){this.Ql&&a?this.Pq(d.C5):this.Ql?this.Pq(d.A7):this.Pq(d.r6);this.Qp=!1};d.prototype.Pq=function(b){var c=this.yd,e=c.ej;if(null!=e){var f=e.hb(0),h=f.hb(0),e=c.xU;if(b==d.C5){b=p.HSa(c);var k=p.ISa(c),l=p.JSa(),n=p.FSa()}else b==d.A7?(b=p.HSa(c),k=
p.ISa(c),l=p.JSa(),n=p.GSa()):b==d.AAa?(b=p.tlb(c),k=p.ulb(c),l=p.ESa(),n=p.FSa()):(b=p.nua(c),k=p.F3(c),l=p.oua(),n=p.GSa());var m=p.wlb(),k=new a.ya(k,1,l),n=new a.ya(n,1,m);f.fb(b);f.Ga(k);h.Ga(n);(c=c.k0)&&c.Ga(k);e&&e.Ga(k)}};var w={};a.v.D(w,a.v);w.Lqb=function(a,b,c,d,e,f){a.sm?(w.Aeb(a,b,c,e),w.ena(a,b,d,null,!1)):(b.tKa=!0,w.ena(a,b,d,f,!0));b.Sb()||(a.k0&&b.c_?w.TPa(a,b,d,f):w.Oeb(a,b,c.pta,d,e))};w.$nb=function(a,b,c){a.ej&&b.c_?w.PPa(a,b,c):w.M8a(a,b,c)};w.M8a=function(a,b,c){var d=w.y$a(a,
b);b.A(d);var e=d.aa();b.removeChild(d);a.Xa(e.a+10);a.qb(e.b+10);a.sm=d;b=b.JQa(a,c);a.p5(b)};w.Aeb=function(b,c,e,f){var h=c.u(),k=a.B.da(h),l=b.getId(),n=b.sm;b.sm=null;var m=b.getWidth(),r=b.getHeight(),w="_bubble_"+l;if(c.Sb()){var x=r/2,O=x-6,fa=x+6;!k&&c.zo||k&&!c.zo?(k=[0,0,0,O,-6,x,0,fa,0,r,m,r,m,0,0,0],r=[2,2,2,O,-4,x,2,fa,2,r-2,m-2,r-2,m-2,2,2,2]):(k=[0,0,0,r,m,r,m,fa,m+6,x,m,O,m,0,0,0],r=[2,2,2,r-2,m-2,r-2,m-2,fa,m+4,x,m-2,O,m-2,2,2,2])}else x=k?m-p.k3():p.k3(),O=x-6,fa=x+6,c.zo?(k=[0,
0,O,0,x,-6,fa,0,m,0,m,r,0,r,0,0],r=[2,2,O,2,x,-4,fa,2,m-2,2,m-2,r-2,2,r-2,2,2]):(k=[0,0,0,r,O,r,x,r+6,fa,r,m,r,m,0,0,0],r=[2,2,2,r-2,O,r-2,x,r+4,fa,r-2,m-2,r-2,m-2,2,2,2]);m=new a.mi(h,k,w);w=new a.mi(h,r,w+"_i");w.fb(p.vlb());n.Ma(5,5);m.A(w);m.A(n);h=new d(h,"_bt_"+l);f&&(h.T(0),f.push(h));h.A(m);a.Ub.vn()&&a.K.Y(h.Xb,"id",h.xc);h.yd=b;b.vrb(h);h.Pq(d.r6);0<=b.CB&&e.A(h);h.cg("group");b.Hr();c.pb.I.lb(h,b)};w.ena=function(b,c,e,f,h){var k=a.B.da(c.u()),l=b.CB,n=b.getWidth(),m=b.getHeight(),r=b.Nz;
b=b.ej;h&&b.Pq(d.r6);c.Sb()?(m=l-m/2,k&&c.zo||!k&&!c.zo?k=c.ew-(n+c.xx)+e:(k=c.xx,e=0)):(k=k?c.Fj-l-n+p.k3():l-p.k3(),c.zo?(m=c.JM()?r:c.Jb-r-m+e+c.xx-p.Sx(),e=0):m=c.JM()?r-c.xx+p.Sx():c.Jb-r-m+e);f?(c.Sb()?b.ga(b.qa()+c.H9+e):b.wa(b.pa()+c.BO+e),f.N(a.G.V,b,b.qa,b.ga,k),f.N(a.G.V,b,b.pa,b.wa,m)):b.Ma(k,m)};w.y$a=function(b,c){var d=c.u(),e=a.B.da(d),f=b.pC(),h=b.sU,k=b.sPa,l=new a.la(d),m=0,n=0;if(e)f&&(r=new a.ca(d,f,0,n),r.Bb(p.KSa(b)),m=r.Pc().a+2,n=15,l.A(r)),h&&(h=new a.ca(d,h,0,n),h.Bb(p.DSa(b)),
f=h.Pc().a+2,0!=m&&f!=m?f>m?(r.Fa(f-m),m=f):h.Fa(m-f):m=f,l.A(h)),k&&(k=new a.Image(d,k,m,0,p.fva(),p.STa(),"_tn"),k.nb(!1),l.A(k));else{k&&(k=new a.Image(d,k,0,0,p.fva(),p.STa(),"_tn"),k.nb(!1),l.A(k),m=p.fva()+2);if(f){var r=new a.ca(d,f,m,n);r.Bb(p.KSa(b));n=15;l.A(r)}h&&(h=new a.ca(d,h,m,n),h.Bb(p.DSa(b)),l.A(h))}return l};w.PPa=function(a,b,c){b=b.JQa(a,c);a.p5(b)};w.Oeb=function(b,c,d,e,f){var h=c.u(),k=a.B.da(h),l=b.getId(),m=b.CB,n=b.Nz,l="_feeler_"+l;if(c.zo)r=b.f0,e=c.JM()?n:c.Jb-n-b.getHeight()+
e+c.xx-p.Sx();else{var r=c.Jb+e-b.f0;e=c.JM()?n-c.xx+p.Sx()+b.getHeight():c.Jb-n+e}c=k?c.Fj-m:m;h=new a.Gc(h,c,r,c,e,l);f&&(h.T(0),f.push(h));d.A(h);d=p.oua();f=p.F3(b);d=new a.ya(f,1,d);h.Ga(d);h.yd=b;b.qWa(h)};w.TPa=function(b,c,d,e){if(c.Sb())b.qWa(null);else{var f=a.B.da(c.u()),h=b.k0;if(c.zo)k=b.f0,l=c.JM()?b.Nz:c.Jb-b.Nz-b.getHeight()+d+c.xx-p.Sx(),d=0;else var k=c.Jb+d-b.f0,l=c.JM()?b.Nz-c.xx+p.Sx()+b.getHeight():c.Jb-b.Nz+d;b=f?c.Fj-b.CB:b.CB;e?(h.Il(h.Rr()+c.BO+d),h.Jl(h.ot()+c.BO+d),e.N(a.G.V,
h,h.Qr,h.eo,b),e.N(a.G.V,h,h.Rr,h.Il,k),e.N(a.G.V,h,h.nt,h.un,b),e.N(a.G.V,h,h.ot,h.Jl,l)):(h.eo(b),h.Il(k),h.un(b),h.Jl(l))}};w.Gqb=function(a,b,c,d,e,f){a.xU?w.cC(a,b,d,f):w.Meb(a,b,c,d,e)};w.Meb=function(b,c,d,e,f){var h=c.u(),k=a.B.da(h),l=b.hl(),m=a.Ub.bf(c.Yb,c.Ic,b.Ti(),c.Fj),n="_duration_"+b.getId(),r=22+10*b.lz,l=a.Ub.bf(c.Yb,c.Ic,l,c.Fj);c.Sb()?(!k&&!c.zo||k&&c.zo?h=new a.Rect(h,c.ew-r+5,m,r,l-m,n):(h=new a.Rect(h,-5,m,r,l-m,n),e=0),h.ga(e),h.jb(m),h.Xa(r),h.qb(l-m)):(l-=m,m=k?c.Fj-m-l:
m,c.zo?(h=new a.Rect(h,m,-5,l,r,n),h.wa(0)):(h=new a.Rect(h,m,c.ew-r+5,l,r,n),h.wa(e)));f&&(h.T(0),f.push(h));h.JC(5);h.fb(b.XG);e=p.oua();f=p.F3(b);e=new a.ya(f,1,e);h.Ga(e);h.yd=b;c.pb.I.lb(h,b);d.A(h);b.Prb(h)};w.cC=function(b,c,d,e){var f=a.B.da(c.u()),h=b.xU;if(null!=h){var k=a.Ub.bf(c.Yb,c.Ic,b.Ti(),c.Fj),l=22+10*b.lz,m=a.Ub.bf(c.Yb,c.Ic,b.hl(),c.Fj);if(c.Sb()){b=0;!f&&!c.zo||f&&c.zo?f=c.ew-l+5:(f=-5,d=0);var n=d,p=k,r=l,k=m-k}else n=0,m-=k,f=f?c.Fj-k-m:k,c.zo?(b=d=0,p=-5):(b=d,p=c.ew-l+5),
r=m,k=l;e?(c.Sb()?h.ga(h.qa()+c.H9+d):h.wa(h.pa()+c.BO+d),e.N(a.G.V,h,h.qa,h.ga,n),e.N(a.G.V,h,h.pa,h.wa,b),e.N(a.G.V,h,h.Va,h.Fa,f),e.N(a.G.V,h,h.ib,h.jb,p),e.N(a.G.V,h,h.getWidth,h.Xa,r),e.N(a.G.V,h,h.getHeight,h.qb,k)):(h.ga(n),h.wa(b),h.Fa(f),h.jb(p),h.Xa(r),h.qb(k))}};a.v.D(c,a.v);c.prototype.Init=function(a,b,c){this.Ho=a;this.xf=b;this.Tc=a.Tc[b];this.xc=c.id;this.TL=parseInt(c.startTime);c.endTime&&(this.MK=parseInt(c.endTime));this.Vn=c.title;this.sU=c.ida;this.sPa=c.TWa;this.Gk=c.style;
this.Nb=c.data;this.Vt=c.action;this.XG=c.mda;this.f0=0;this.aPa=c.ctb};c.prototype.getId=function(){return this.xc};c.prototype.vi=function(){return this.Tc};c.prototype.Fh=function(){return this.xf};c.prototype.Ti=function(){return this.TL};c.prototype.Msb=function(a){this.TL=a};c.prototype.hl=function(){return this.MK};c.prototype.Trb=function(a){this.MK=a};c.prototype.pC=function(){return this.Vn};c.prototype.M=function(){return this.Gk};c.prototype.fa=function(a){this.Gk=a};c.prototype.getData=
function(){return this.Nb};c.prototype.vrb=function(a){this.ej=a};c.prototype.qWa=function(a){this.k0=a};c.prototype.Prb=function(a){this.xU=a};c.prototype.zxa=function(a){this.CB=a};c.prototype.p5=function(a){this.Nz=a};c.prototype.txa=function(a){this.lz=a};c.prototype.Rrb=function(a){this.f0=a};c.prototype.Qrb=function(a){this.XG=a};c.prototype.ge=function(){return null!=this.hl()?"Start Time: "+(new Date(this.Ti())).toLocaleString()+"; End Time: "+(new Date(this.hl())).toLocaleString()+"; Title: "+
this.pC()+"; Description: "+this.sU:"Time: "+(new Date(this.Ti())).toLocaleString()+"; Title: "+this.pC()+"; Description: "+this.sU};c.prototype.getWidth=function(){return this.Vs};c.prototype.Xa=function(a){this.Vs=a};c.prototype.getHeight=function(){return this.gP};c.prototype.qb=function(a){this.gP=a};c.prototype.Ch=function(){return this.Vt};c.prototype.Fd=function(b){var c=this.Ho.I.Cb;if(b.type==a.MouseEvent.Be||c.Nu(b))return this;if(c.Vi(b)){for(var c=[],d=0;d<this.Ho.Tc.length;d++)c.push(this.Ho.Tc[d].dc);
return m.Fd(this,b,c)}return null};c.prototype.Jm=function(){return this.ej.Ua()};c.prototype.rf=function(a){return this.ej.aa(a)};c.prototype.Sf=function(){this.dd=!0;this.qd();this.Ho.aXa(this)};c.prototype.Qd=function(){this.dd=!1;this.Nc()};c.prototype.Kd=function(){return this.dd};c.prototype.Qe=function(){return[this.ej]};c.prototype.Ed=function(){var b=[];this.tb()&&b.push(a.H.va(a.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));return a.oa.Ik(this.ge(),b)};c.prototype.mj=function(a){this.icb=
a};c.prototype.tb=function(){return this.icb};c.prototype.wb=function(){return this.Ql};c.prototype.kc=function(a){this.Ql=a;this.ej.kc(a);this.Hr();this.Ho.vx&&this.Ho.ee&&(a?this.Ho.ee.aWa(this.getId()):this.Ho.ee.grb(this.getId()))};c.prototype.qd=function(a){this.ej.qd(this.Ho.I.jf()==this);!a&&this.Ho.vx&&this.Ho.ee.Wnb(this.getId());if(this.Ho.de||this.Tc.yaa)this.fp||(this.fp=this.Tc.zO[0].Bi(this.ej)),this.Tc.zO[0].A(this.ej)};c.prototype.Nc=function(a){this.ej.Nc(this.Ho.I.jf()==this);!a&&
this.Ho.vx&&this.Ho.ee.otb(this.getId());(this.Ho.de||this.Tc.yaa)&&this.fp&&!this.Ql&&this.Tc.zO[0].Ib(this.ej,this.fp)};c.prototype.zf=function(){if(!this.af&&(this.af=[],this.aPa))for(var b=this.aPa,c=0;c<b.length;c++)this.af.push(new a.Vc(b[c].popupId,b[c].triggerType,b[c].alignId,b[c].align));return this.af};c.prototype.Hr=function(){a.B.kj()||this.ej.Gd("label",this.Ed())};a.v.D(b,a.v);b.prototype.parse=function(a,b){var c=this.Phb(a),d={};d.start=(new Date(a.start)).getTime();d.end=(new Date(a.end)).getTime();
d.tX=a.style;d.scale=a.scale;d.itb=a.timeAxis;d.label=a.label;d.qjb=a.emptyText;d.Qva="auto"==a.animationOnDisplay;d.Kva="auto"==a.animationOnDataChange;d.items=this.Iqa(a.timeline,a.index,c.data,b,d.start,d.end);d.Gwb="false";d.Aob=a._isRandomItemLayout;d.X2=a._cts;d.W2=a._cfs;d.JM=null==a.itemLayout||"auto"==a.itemLayout?a.inverted:"topToBottom"==a.itemLayout;return d};b.prototype.Phb=function(a){var b={},c=[];if(a=a.items)for(var d=0;d<a.length;d++)c.push(a[d]);b.data=c;return b};b.prototype.Iqa=
function(b,d,e,f,h,k){var l=[],m=b.Tc[d];if(e)for(var n=0;n<e.length;n++){var p=this.Ria(e[n],h,k);if(p){if(m.c_){var r=this.Y9a(p,f);if(r){var w=a.na.kb(f,r);f.splice(w,1);r.p5(null);r.txa(null);r.zxa(null);r.kc(!1);r.Msb(p.startTime);r.Trb(p.endTime);r.fa(p.style)}else r=new c(b,d,p),r.mj(!0)}else r=new c(b,d,p),r.mj(!0);for(var p=r.Ti(),w=!0,x=0;x<l.length;x++)if(p<l[x].Ti()){l.splice(x,0,r);w=!1;break}w&&l.push(r)}}return l};b.prototype.Y9a=function(a,b){if(b)for(var c=0;c<b.length;c++){var d=
b[c];if(a.id==d.getId()&&a.title==d.pC()&&a.ida==d.sU&&a.TWa==d.sPa)return d}};b.prototype.getDate=function(a){return null==a?null:a.getTime?a.getTime():isNaN(a)?(new Date(a)).getTime()+0:a};b.prototype.Ria=function(a,b,c){var d={};d.id=a.id;d.brb=d.id;d.startTime=this.getDate(a.start);d.endTime=this.getDate(a.end);if((d.endTime?d.endTime:d.startTime)<b||d.startTime>c)return null;d.title=a.title;d.ida=a.description;d.TWa=a.thumbnail;d.data=a;d.style=a.style;d.action=a.action;d.mda=a.durationFillColor;
d.ctb=a.showPopupBehaviors;return d};var x={};a.v.D(x,a.v);x.Mqb=function(b,c,d){x.Gr(b,c,d);x.c2(b);x.lfb(b,b.nh);x.qfb(b);if(null!=b.dc){if(0==b.zO.length){d=b.u();c=new a.la(d,"itemBlock_"+b.qz+"_"+b.Jv);c.hN=b.qz;c.fI=b.Jv;var e=new a.la(d,"feelers");c.A(e);c.pta=e;d=new a.la(d,"durations");c.A(d);c.yRa=d;b.nh.A(c);b.zO.push(c)}else c=b.zO[0];b.Gwa(b.dc);b.Spb(b.dc);b.acb?(b.$G=b.bpa?[]:null,b.xH=null,b.FL=null):b.c_&&b.Wbb?(b.$G=[],b.xH=new a.G(b.u(),p.ob(b.W),0,a.Je.V2),b.FL=[]):(b.$G=null,
b.xH=null,b.FL=null);b.tKa=!1;d=Math.max(0,b.$k-b.ew);b.I1=d;x.XFa(b,d);b.p1&&x.oeb(b.p1,b,c,b.FL);b.p1=null;b.Sb()&&c.pta.Hl();x.ara(b.dc,b,c,b.qz,b.Jv,d,b.$G,b.xH);x.VPa(b);x.XPa(b)}};x.ytb=function(a){x.Bgb(a.dc,a);x.VPa(a);x.XPa(a)};x.Gr=function(b,c,d){if(b.Gb){var e=!1;b.Gb.Xa(c);b.Gb.qb(d)}else e=!0,b.Gb=new a.Rect(b.u(),0,0,c,d,"bg");b.Gb.Bb(b.Gk);b.Gb.md();b.Gb.setCursor("move");e&&b.A(b.Gb)};x.XFa=function(b,c){var d=a.B.da(b.u());0<c&&(b.Sb()?b.Gb.Xa(b.$k):b.Gb.qb(b.$k));if(b.Sb()){if(!b.zo&&
!d||b.zo&&d)b.Gb.ga(-c),b.Xrb(c)}else b.zo||(b.Gb.wa(-c),b.Ssb(c))};x.c2=function(b){b.nh?(b.H9=b.nh.qa(),b.BO=b.nh.pa(),b.nh.ga(0),b.nh.wa(0)):(b.nh=new a.la(b.u(),"canvas"),b.A(b.nh))};x.ara=function(b,c,d,e,f,h,k,l){for(var m=0;m<b.length;m++){var n=b[m],p=a.Ub.bf(c.Yb,c.Ic,n.Ti(),c.Fj);p<e||p>f||w.Lqb(n,c,d,h,k,l)}if(a.Ub.vn())for(m=0;m<b.length-1;m++)if(n=b[m],e=n.ej)if(f=b[m+1],f.ej)e.m2("flowto","_bt_"+f.getId());else break;x.Neb(b,c,d,h,k,l)};x.Bgb=function(b,c){if(null!=b&&0!=b.length){var d=
c.Jv,e=c.zO[0];e.hN=c.qz;e.fI=d;c.Sb()?c.xx=20*(0<c.sH?1:0)+p.Sx()+10*c.sH:c.xx=20+p.Sx()+10*c.sH;for(d=0;d<b.length;d++){var e=b[d],f=e.Ti(),h=a.Ub.bf(c.Yb,c.Ic,f,c.Fj),k=e.hl();k&&k!=f&&(f=a.Ub.bf(c.Yb,c.Ic,k,c.Fj)-h,h+=Math.min(p.tSa(),f/2));e.zxa(h);c.yaa||e.p5(null)}for(d=0;d<b.length;d++)e=b[d],h=e.Ti(),h<c.Yb||h>c.Ic||w.PPa(e,c,d);h=Math.max(0,c.$k-c.ew);x.XFa(c,h);for(d=0;d<b.length;d++)e=b[d],w.ena(e,c,h,null,!1),w.TPa(e,c,h,null),w.cC(e,c,h,null)}};x.Neb=function(a,b,c,d,e,f){c=c.yRa;for(var h=
b.sH;0<h;h--)for(var k=0;k<a.length;k++){var l=a[k],m=l.Ti(),n=l.hl();n&&n!=m&&h==l.lz&&w.Gqb(l,b,c,d,e,f)}};x.qfb=function(b){null==b.eca?(b.eca=new a.la(b.u()),b.nh.A(b.eca)):(b.eca.Hl(),b.fca=[]);if(b.nf&&b.ck){var c=new a.j(p.Emb());if(b.tGa){var d=b.tGa.separatorColor;d&&c.lj("color:"+d+";")}b.TV=new a.ya(c.M(a.j.mc));b.TV.fa(a.Xc.VC,3);x.ira(b,b.qz,b.Jv,b.eca)}};x.XPa=function(b){for(var c=a.B.da(b.u()),d=0;d<b.fca.length;d++){var e=b.fca[d],f=!b.Sb()&&c?b.Fj-a.Ub.bf(b.Yb,b.Ic,e.time,b.Fj):
a.Ub.bf(b.Yb,b.Ic,e.time,b.Fj);b.Sb()?(e.eo(0),e.Il(f),e.un(b.$k),e.Jl(f)):(e.eo(f),e.Il(0),e.un(f),e.Jl(b.$k))}};x.ira=function(b,c,d,e){var f=a.B.da(b.u()),h,k=b.Yb,l=b.Ic;if(b.xo&&b.xo[b.nf])h=b.xo[b.nf].times;else if(b.PG&&b.PG[b.nf])h=b.PG[b.nf].times;else{h=[];c=a.Ub.Si(k,l,c,b.Fj);var m=b.ck.zW(c);c=a.Ub.bf(k,l,m,b.Fj);for(h.push(m.getTime());c<d;)m=b.ck.eX(m.getTime()),c=a.Ub.bf(k,l,m,b.Fj),h.push(m.getTime())}for(d=0;d<h.length-1;d++){m=h[d];c=a.Ub.bf(k,l,m,b.Fj);var n=!b.Sb()&&f?b.Fj-c:
c;if(b.Sb())var p=0,r=n,w=b.$k;else p=n,r=0,w=n,n=b.$k;c=b.Gsa(e,p,w,r,n,b.TV,"o_tick"+c);c.time=m;b.fca.push(c)}};x.lfb=function(b,c){var d=b.u(),e=a.B.da(d);null==b.Iba&&(b.Iba=new a.la(d),c.A(b.Iba));var f=b.kQ;if(f)for(var h=Math.min(1,f.length),k=0;k<h;k++){var l=f[k];if(l){var m=a.Ub.bf(b.Yb,b.Ic,l,b.Fj);if(0==b.f2.length){b.Sb()?m=new a.Gc(d,0,m,b.$k,m,"zoomOrder[i]"):(e&&(m=b.Fj-m),m=new a.Gc(d,m,0,m,b.$k,"zoomOrder[i]"));var n=new a.ya(p.CTa(b.W));m.Ga(n);m.md();m.Zib=l;b.Iba.A(m);b.f2[k]=
m}}}else b.Iba.Hl(),b.f2=[]};x.VPa=function(b){for(var c=a.B.da(b.u()),d=0;d<b.f2.length;d++){var e=b.f2[d],f=a.Ub.bf(b.Yb,b.Ic,e.Zib,b.Fj);b.Sb()?(e.eo(0),e.Il(f),e.un(b.$k),e.Jl(f)):(c&&(f=b.Fj-f),e.eo(f),e.Il(0),e.un(f),e.Jl(b.$k))}};x.oeb=function(a,b,c,d){if(d)x.d7a(a,b,d);else for(d=0;d<a.length;d++){var e=a[d];c.removeChild(e.ej);b.Sb()||c.pta.removeChild(e.k0);var f=e.Ti(),h=e.hl();h&&h!=f&&c.yRa.removeChild(e.xU)}};x.d7a=function(a,b,c){for(var d=0;d<a.length;d++){var e=a[d],f=e.ej;b.Sb()?
f.ga(f.qa()+b.H9+b.I1):f.wa(f.pa()+b.BO+b.I1);c.push(f);b.Sb()||(f=e.k0,f.wa(f.pa()+b.BO+b.I1),c.push(f));var f=e.Ti(),h=e.hl();h&&h!=f&&(e=e.xU,b.Sb()?e.ga(e.qa()+b.H9+b.I1):e.wa(e.pa()+b.BO+b.I1),c.push(e))}};a.Ia(a,"Timeline",a.Zd);a.Ia(a.Zd,"newInstance",a.Zd.newInstance);a.Ia(a.Zd.prototype,"render",a.Zd.prototype.ta);a.Ia(a.Zd.prototype,"getAutomation",a.Zd.prototype.ph);a.Ia(a.Zd.prototype,"select",a.Zd.prototype.select);a.Ia(k.prototype,"getDomElementForSubId",k.prototype.qh)})(dvt);
  return dvt;
});
