/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(){}function c(a,b){this.Init(a,b)}function d(){this.Init({alta:d.lh})}function e(a){this.Init(a)}a.Ub=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Ub,a.Ie);a.Ub.m7="vertical";a.Ub.vn=function(){return a.B.Wa()};a.Ub.bf=function(a,b,c,d){c=(c-a)*d;a=b-a;return 0==c||0==a?0:c/a};a.Ub.Si=function(a,b,c,d){b=c*(b-a);return 0==b||0==d?a:b/d+a};a.Ub.newInstance=function(b,c,d){return new a.Ub(b,c,d)};a.Ub.Wka="seconds minutes hours days weeks months quarters years".split(" ");a.Ub.prototype.Init=
function(b,c,f){a.Ub.C.Init.call(this,b,c,f);this.aHa=new e;this.Tk=h.Wya;this.RX(!1,!1,!1,!1);this.pB=b.L3().dateToIsoConverter;this.iz={oRa:[a.H.va(a.H.Ha,"DAY_SHORT_SUNDAY",null),a.H.va(a.H.Ha,"DAY_SHORT_MONDAY",null),a.H.va(a.H.Ha,"DAY_SHORT_TUESDAY",null),a.H.va(a.H.Ha,"DAY_SHORT_WEDNESDAY",null),a.H.va(a.H.Ha,"DAY_SHORT_THURSDAY",null),a.H.va(a.H.Ha,"DAY_SHORT_FRIDAY",null),a.H.va(a.H.Ha,"DAY_SHORT_SATURDAY",null),a.H.va(a.H.Ha,"DAY_SUNDAY",null),a.H.va(a.H.Ha,"DAY_MONDAY",null),a.H.va(a.H.Ha,
"DAY_TUESDAY",null),a.H.va(a.H.Ha,"DAY_WEDNESDAY",null),a.H.va(a.H.Ha,"DAY_THURSDAY",null),a.H.va(a.H.Ha,"DAY_FRIDAY",null),a.H.va(a.H.Ha,"DAY_SATURDAY",null)],dfa:[a.H.va(a.H.Ha,"MONTH_SHORT_JANUARY",null),a.H.va(a.H.Ha,"MONTH_SHORT_FEBRUARY",null),a.H.va(a.H.Ha,"MONTH_SHORT_MARCH",null),a.H.va(a.H.Ha,"MONTH_SHORT_APRIL",null),a.H.va(a.H.Ha,"MONTH_SHORT_MAY",null),a.H.va(a.H.Ha,"MONTH_SHORT_JUNE",null),a.H.va(a.H.Ha,"MONTH_SHORT_JULY",null),a.H.va(a.H.Ha,"MONTH_SHORT_AUGUST",null),a.H.va(a.H.Ha,
"MONTH_SHORT_SEPTEMBER",null),a.H.va(a.H.Ha,"MONTH_SHORT_OCTOBER",null),a.H.va(a.H.Ha,"MONTH_SHORT_NOVEMBER",null),a.H.va(a.H.Ha,"MONTH_SHORT_DECEMBER",null),a.H.va(a.H.Ha,"MONTH_JANUARY",null),a.H.va(a.H.Ha,"MONTH_FEBRUARY",null),a.H.va(a.H.Ha,"MONTH_MARCH",null),a.H.va(a.H.Ha,"MONTH_APRIL",null),a.H.va(a.H.Ha,"MONTH_MAY",null),a.H.va(a.H.Ha,"MONTH_JUNE",null),a.H.va(a.H.Ha,"MONTH_JULY",null),a.H.va(a.H.Ha,"MONTH_AUGUST",null),a.H.va(a.H.Ha,"MONTH_SEPTEMBER",null),a.H.va(a.H.Ha,"MONTH_OCTOBER",null),
a.H.va(a.H.Ha,"MONTH_NOVEMBER",null),a.H.va(a.H.Ha,"MONTH_DECEMBER",null)]};this.Xg=new d};a.Ub.prototype.vf=function(a){this.W=this.Xg.en(a)};a.Ub.prototype.eD=function(a){this.Yv=new b;return this.Yv.parse(a)};a.Ub.prototype.uv=function(b){var c=b.orientation;this.de=c&&c==a.Ub.m7?!0:!1;this.uWa(this.de);this.pu=b.Gxa;this.ZH=b.iXa?b.iXa.reverse():[b.scale];this.BQ=b.Ixa;this.xo=b.X2;this.PG=b.W2;this.Yb=b.start;this.Ic=b.end;this.bL=b.tX;this.nf=b.scale;this.Mp=b.UQa;this.IE()};a.Ub.prototype.qF=
function(a,b){if("undefined"===typeof b||null===b)b=this.Uf;this.je=b<a?a:b};a.Ub.prototype.No=function(){return a.B.da(this.u())};a.Ub.prototype.Sb=function(){return this.de};a.Ub.prototype.ta=function(a,b,c){a&&!this.W&&(this.xb=b,this.Jb=c,this.ANa(),this.lea(a,this.Uf));this.eH(b,c)};a.Ub.prototype.lea=function(a,b){this.vf(a);this.jj=this.W._resources;null==this.jj&&(this.jj=[]);this.pB||(this.pB=this.u().L3().dateToIsoConverter);var c=this.eD(this.W);this.uv(c);this.nf&&this.Tpb(this.Yb,this.Ic,
b);return this.je};a.Ub.prototype.hy=function(){var b=this.nf&&-1!=a.na.kb(a.Ub.Wka,this.nf),c=this.nf&&this.xo&&this.xo[this.nf],d=this.Yb&&this.Ic&&this.Ic>this.Yb;return(b||c)&&d};a.Ub.prototype.gm=function(){return this.pu?this.pu:a.H.va(a.H.Ha,"TIMEAXIS")};a.Ub.prototype.IE=function(){this.a9=new a.j(h.Vjb(this.W));this.a9.lj(this.bL);var b=this.a9.Pg();this.a9.lj("border:"+2*b+"px;");this.gWa(b)};a.Ub.prototype.ANa=function(){this.de?(this.Uf=this.Jb,this.cj=this.xb):(this.Uf=this.xb,this.cj=
this.Jb)};a.Ub.prototype.Kfb=function(){null!==this.cj&&this.kxa(this.cj-this.Xua());this.nK=this.je+this.Xua()-h.HYa};a.Ub.prototype.Agb=function(a,b){this.xb=a;this.Jb=b;this.ANa();this.qF(this.Uf);this.Kfb()};a.Ub.prototype.eH=function(a,b){this.Agb(a,b);f.Nqb(this)};a.Ub.prototype.Tpb=function(a,b,c){this.jWa(this.Mp);this.bo("short",this.iz);this.aIa=[];this.Rn=[];this.tW=[];this.de?this.Kfa(this.jj.converterVert):this.Kfa(this.jj.converter);this.BQ&&this.IWa(this.BQ);for(var d=this.nf,e=0;e<
this.ZH.length;e++){var f=this.ZH[e],h=this.Odb(f,d,a,b);this.Pdb(e,f,a,b,h,c)}this.zt(d)};a.Ub.prototype.Odb=function(b,c,d,e){this.zt(b);var f=Infinity,p=0,w;if(this.xo&&this.xo[b])w=this.xo[b],b=w.times,w=w.labels;else if(this.PG&&this.PG[b])w=this.PG[b],b=w.times,w=w.labels;else for(b=[],w=[],d=this.zW(d).getTime(),b.push(d);d<e;)w.push(this.tta(new Date(d))),d=this.eX(d).getTime(),b.push(d);e=[];for(var x=0;x<w.length;x++){d=b[x];var v=new a.ca(this.u(),w[x],0,0,"s_label"+d);v.Bb(h.Tjb(this.W));
v.time=d;var A=b[x+1];this.A(v);var u=v.aa();this.removeChild(v);if(this.de)var D=u.b,u=u.a,B=h.Yya;else D=u.a,u=u.b,B=h.$ya;d=(A-d)/Math.max(B,D+2*h.Zya);d<f&&(f=d);u>p&&(p=u);e.push(v)}this.kxa(p+2*h.Zya);this.aIa.push(b);this.Rn.push(e);this.zt(c);return f};a.Ub.prototype.Pdb=function(a,b,c,d,e,f){c=null!==this.cj?f:(d-c)/e;this.tW.push(c);b==this.nf&&(this.mp=a,this.qF(c,f));0==a&&(this.qV=this.Rn[this.Rn.length-1].length*f)};a.Ub.prototype.zt=function(a){this.nf=a};a.Ub.prototype.IWa=function(a){this.BQ=
a};a.Ub.prototype.Eva=function(){for(var a=0;a<this.ZH.length-1;a++)if(this.ZH[a]==this.nf){this.nf=this.ZH[a+1];break}};a.Ub.prototype.hta=function(){for(var a=1;a<this.ZH.length;a++)if(this.ZH[a]==this.nf){this.nf=this.ZH[a-1];break}};a.Ub.prototype.jWa=function(a){this.Mp=a};a.Ub.prototype.Kfa=function(a){this.$ma=a};a.Ub.prototype.kxa=function(a){a>this.Dv&&(this.Dv=a)};a.Ub.prototype.sR=function(){null==this.C2&&(this.C2=30);return this.C2};a.Ub.prototype.gWa=function(a){this.Tk=a};a.Ub.prototype.RX=
function(a,b,c,d){this.PGa=(a|0)*this.Tk;this.R7a=(b|0)*this.Tk;this.MGa=(c|0)*this.Tk;this.Q7a=(d|0)*this.Tk};a.Ub.prototype.Vhb=function(){for(var a=this.de?{top:this.pe(),right:this.nK,bottom:this.pe(),left:this.nK}:{top:this.nK,right:this.pe(),bottom:this.nK,left:this.pe()},b=[],c=0,d=1,e=["top","right","bottom","left"],f=0;f<e.length;f++)0<this.Pg(e[f])==d?c+=a[e[f]]:(b.push(c),c=a[e[f]],d=Math.abs(d-1));b.push(c);return b.toString()};a.Ub.prototype.Xua=function(){return this.PGa+this.MGa};a.Ub.prototype.Pg=
function(a){switch(a){case "top":return this.PGa;case "right":return this.R7a;case "bottom":return this.MGa;case "left":return this.Q7a;default:return this.Tk}};a.Ub.prototype.pe=function(){return this.Dv+this.Xua()};a.Ub.prototype.bo=function(a,b){this.l$a=new c("short"==a?c.SHORT:c.O_a,b)};a.Ub.prototype.zW=function(a){return this.aHa.zW(new Date(a),this.nf)};a.Ub.prototype.eX=function(a){return this.aHa.eX(a,this.nf)};a.Ub.prototype.tta=function(a){if(this.Mp){var b;b=this.Mp[this.nf]?this.Mp[this.nf]:
this.Mp["default"]?this.Mp["default"]:this.Mp;if(b.format)return b.format(this.pB?this.pB(a):a);if(b.getAsString)return b.getAsString(a)}if(this.$ma&&this.$ma[this.nf]){b=this.$ma[this.nf];if(b.format)return b.format(this.pB?this.pB(a):a);if(b.getAsString)return b.getAsString(a)}return this.l$a.format(a,this.nf,this.BQ)};a.Ub.prototype.uWa=function(a){this.Dv=a?h.$ya:h.Yya};a.Ub.prototype.ixa=function(){this.cj=null};a.Ub.prototype.eS=function(a){this.mp=a};a.v.D(e,a.v);e.prototype.Init=function(){this.u9a=
864E5};e.prototype.zW=function(a,b){var c=new Date(a.getTime());if("weeks"==b){c.setHours(0,0,0);var d=(a.getDay()-0+7)%7;0<d&&c.setTime(c.getTime()-d*this.u9a)}else"months"==b?c.setDate(1):"days"==b?c.setHours(0,0,0):"hours"==b?c.setMinutes(0,0,0):"minutes"==b?c.setSeconds(0,0):"seconds"==b?c.setMilliseconds(0):"quarters"==b?(c.setDate(1),d=2-(a.getMonth()+11)%3,0<d&&c.setMonth(c.getMonth()+d)):"halfyears"==b?(c.setDate(1),d=5-(a.getMonth()+11)%6,0<d&&c.setMonth(c.getMonth()+d)):"years"==b?(c.setMonth(0),
c.setDate(1)):"twoyears"==b&&(c.setMonth(0),c.setDate(1));return c};e.prototype.eX=function(a,b){if("seconds"==b)return new Date(a+1E3);if("minutes"==b)return new Date(a+6E4);if("hours"==b)return new Date(a+36E5);var c=new Date(a);"days"==b?c.setDate(c.getDate()+1):"weeks"==b?c.setDate(c.getDate()+7):"months"==b?c.setMonth(c.getMonth()+1):"quarters"==b?c.setMonth(c.getMonth()+3):"halfyears"==b?c.setMonth(c.getMonth()+6):"years"==b?c.setFullYear(c.getFullYear()+1):"twoyears"==b?c.setFullYear(c.getFullYear()+
2):c.setYear(c.getYear()+1);return c};a.v.D(d,a.bb,"DvtTimeAxisDefaults");d.lh={backgroundColor:"rgba(255,255,255,0)",borderColor:"#d9dfe3",separatorColor:"#bcc7d2",labelStyle:new a.j("font-family: Helvetica Neue, Helvetica, Arial, sans-serif; font-size: 12px; color: #333333;")};a.v.D(c,a.v);c.O_a=0;c.SHORT=1;c.prototype.Init=function(a,b){this.bl=a;this.iz=b;this.Xm=[];this.Xm[0]={};this.Xm[0].seconds="HH:MM:ss";this.Xm[0].minutes="HH:MM";this.Xm[0].hours="HH:MM";this.Xm[0].days="dddd";this.Xm[0].weeks=
"m/dd";this.Xm[0].months="mmmm";this.Xm[0].quarters="mmmm";this.Xm[0].halfyears="yyyy";this.Xm[0].years="yyyy";this.Xm[0].twoyears="yyyy";this.Xm[1]={};this.Xm[1].seconds="HH:MM:ss";this.Xm[1].minutes="HH:MM";this.Xm[1].hours="HH:MM";this.Xm[1].days="m/dd";this.Xm[1].weeks="m/dd";this.Xm[1].months="mmm";this.Xm[1].quarters="mmm";this.Xm[1].halfyears="yy";this.Xm[1].years="yy";this.Xm[1].twoyears="yy"};c.prototype.format=function(a,b,c){b=this.Xm[this.bl][b];if(null!=b){var d=!1;if(c){a=a.getTime();
for(var d=Object.keys(c),e=0,f=0;f<d.length;f++)a>=parseInt(d[f],10)&&(e=c[d[f]]);a=new Date(a+e);d=!0}if(-1!=b.indexOf(":"))var h=":";else-1!=b.indexOf("/")&&(h="/");if(h){b=b.split(h);c=this.Sta(a,b[0],d);for(f=1;f<b.length;f++)c+=h+this.Sta(a,b[f],d);return c}return this.Sta(a,b,d)}return a.toLocaleString()};c.prototype.Sta=function(a,b,c){if(c)switch(b){case "ss":return a=a.getUTCSeconds(),10>a?"0"+a:a;case "HH":return a=a.getUTCHours(),10>a?"0"+a:a;case "MM":return a=a.getUTCMinutes(),10>a?"0"+
a:a;case "dd":return a=a.getUTCDate(),10>a?"0"+a:a;case "dddd":return this.iz.oRa[a.getUTCDay()+7];case "m":return a.getUTCMonth()+1;case "mmm":return this.iz.dfa[a.getUTCMonth()];case "mmmm":return this.iz.dfa[a.getUTCMonth()+12];case "yy":return a.getUTCFullYear().toString().substring(2,4);default:return a.getUTCFullYear()}else switch(b){case "ss":return a=a.getSeconds(),10>a?"0"+a:a;case "HH":return a=a.getHours(),10>a?"0"+a:a;case "MM":return a=a.getMinutes(),10>a?"0"+a:a;case "dd":return a=a.getDate(),
10>a?"0"+a:a;case "dddd":return this.iz.oRa[a.getDay()+7];case "m":return a.getMonth()+1;case "mmm":return this.iz.dfa[a.getMonth()];case "mmmm":return this.iz.dfa[a.getMonth()+12];case "yy":return a.getFullYear().toString().substring(2,4);default:return a.getFullYear()}};a.v.D(b,a.v,"DvtTimeAxisParser");b.prototype.parse=function(a){this.TL=new Date(a.start);this.MK=new Date(a.end);var b=this.CZ();b.tX=a.style;b.id=a.id;b.Gxa=a.shortDesc;b.Ixa=a._tzo;b.VUa=a._ip;b.X2=a._cts;b.W2=a._cfs;b.scale=a.scale;
b.UQa=a.converter;b.iXa=a.zoomOrder?a.zoomOrder:null;b.orientation=a.orientation?a.orientation:"horizontal";return b};b.prototype.CZ=function(){var a={};a.start=this.TL.getTime();a.end=this.MK.getTime();return a};var f={};a.v.D(f,a.v,"DvtTimeAxisRenderer");f.Nqb=function(a){if(a.hy()){var b=a.pe();f.seb(a,b,h.RRa(a.W))}};f.seb=function(b,c,d){var e=0,r=b.u();if(null==b.yg){var p=new a.Cd;b.Sb()?(b.yg=new a.Rect(r,e,-b.Pg("top"),c,b.nK,"axis"),p.Pe(e,0,c,b.je)):(b.yg=new a.Rect(r,-b.Pg("left"),e,b.nK,
c,"axis"),p.Pe(0,e,b.je,c));b.yg.Bb(b.a9);b.yg.md();b.yg.te(p);b.A(b.yg);(c=h.Rjb(b.W))&&b.yg.aA().Ua().setAttribute("class",c)}else b.yg.te(null),p=new a.Cd,b.Sb()?(b.yg.Fa(e),b.yg.jb(-b.Pg("top")),b.yg.Xa(c),b.yg.qb(b.nK),p.Pe(e,0,c,b.je)):(b.yg.Fa(-b.Pg("left")),b.yg.jb(e),b.yg.Xa(b.nK),b.yg.qb(c),p.Pe(0,e,b.je,c)),b.yg.te(p);b.yg.Hl();b.yg.aA().Ua().setAttribute("stroke-dasharray",b.Vhb());d=new a.j(d);b.TV=new a.ya(d.M(a.j.mc));c=b.Dv;e=e+b.Sb()?b.Pg("left"):b.Pg("top");f.teb(b,b.cj,b.yg,b.je,
e+c,e,e)};f.teb=function(b,c,d,e,r,p,w){var x=b.u(),v=a.B.da(x),A=new a.la(x,"block_0_"+c);A.hN=0;A.fI=c;d.A(A);c=h.Sjb(b.W);d=h.Ujb(b.W);for(var u=b.aIa[b.mp],D=b.Rn[b.mp],B=0;B<u.length-1;B++){var C=u[B],z=u[B+1],G=a.Ub.bf(b.Yb,b.Ic,C,e),z=a.Ub.bf(b.Yb,b.Ic,z,e),y=z-G;0!=G&&((b.Sb()?f.ola(x,A,r,p,G,G,b.TV,"s_tick"+C,d):v?f.ola(x,A,e-G,e-G,r,p,b.TV,"s_tick"+C,d):f.ola(x,A,G,G,r,p,b.TV,"s_tick"+C,d)).time=C);b.Sb()?f.kla(A,D[B],w+(r-w)/2,G+(z-G)/2,r-w,c):v?f.kla(A,D[B],e-(G+(z-G)/2),w+(r-w)/2,y,c):
f.kla(A,D[B],G+(z-G)/2,w+(r-w)/2,y,c)}};f.kla=function(b,c,d,e,f,h){c.Fa(d);c.jb(e);c.ao()&&c.xg(c.Uq());a.Ca.kd(c,f,Infinity,b);c.Yf();a.Ca.BW(c,e);h&&c.aA().Ua().setAttribute("class",h)};f.ola=function(b,c,d,e,f,h,w,x,v){b=new a.Gc(b,d,f,e,h,x);b.Ga(w);b.md();c.A(b);v&&b.aA().Ua().setAttribute("class",v);return b};var h={};a.v.D(h,a.v,"DvtTimeAxisStyleUtils");h.Wya=1;h.HYa=1;h.$ya=50;h.Yya=21;h.Zya=2;h.Vjb=function(a){var b="",c=h.Wjb(a);c&&(b=b+"background-color:"+c+";");(c=h.Xn(a))&&(b=b+"border-color:"+
c+";");(c=h.Pg())&&(b=b+"border-width:"+c+";");return b};h.Wjb=function(a){return a.backgroundColor};h.Xn=function(a){return a.borderColor};h.Pg=function(){return h.Wya};h.Tjb=function(a){return a.labelStyle};h.Vua=function(a){return a.separatorColor};h.RRa=function(a){var b="";(a=h.Vua(a))&&(b=b+"color:"+a+";");return b};h.Rjb=function(a){return a._resources?a._resources.axisClass:void 0};h.Svb=function(a){return a._resources?a._resources.axisBorderClass:void 0};h.Sjb=function(a){return a._resources?
a._resources.axisLabelClass:void 0};h.Ujb=function(a){return a._resources?a._resources.axisSeparatorClass:void 0};h.lwb=function(a){return a._resources?a._resources.borderTopVisible:!1};h.kwb=function(a){return a._resources?a._resources.borderRightVisible:!1};h.iwb=function(a){return a._resources?a._resources.borderBottomVisible:!1};h.jwb=function(a){return a._resources?a._resources.borderLeftVisible:!1};a.Ia(a,"TimeAxis",a.Ub);a.Ia(a.Ub,"newInstance",a.Ub.newInstance);a.Ia(a.Ub.prototype,"render",
a.Ub.prototype.ta)})(dvt);
  return dvt;
});
