/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a){this.Init(a)}function c(a,b,c,d){this.Init(b,c,d);this.ha=a}function d(){}function e(){this.Init({alta:e.lh})}function f(a,b,c){this.Init(a,b,c)}function h(a,b,c,d,e,f,h,k,l){this.Init(a,b,c,d,e,f,h,k,l)}function k(a){this.yE=a}a.$h=function(a,b,c){this.Init(a,b,c)};a.v.D(a.$h,a.Ie);a.$h.newInstance=function(b,c,d){return new a.$h(b,c,d)};a.$h.prototype.Init=function(d,f,h){a.$h.C.Init.call(this,d,f,h);this.u().Oe.Ua().setAttributeNS(null,"text-rendering","geometricPrecision");
this.I=new c(this,d,this.bg,this);this.I.Qf(this);a.B.Wa()||this.I.Xr(new b(this.I));this.Xg=new e;this.dc=[];this.Zv=[];this.kk=null;this.Xj=new a.Df(this.u());this.I.WR(this.Xj)};a.$h.prototype.ta=function(b,c,d){isNaN(c)||isNaN(d)||(this.xb=c,this.Jb=d);this.YZ();this.vf(b);this.fr();this.Hj=this.Ea;this.p1=this.dc;this.dc=[];this.aLa=[];this.Ea=new a.la(this.u());this.A(this.Ea);l.ta(this,this.Ea,new a.Z(0,0,this.xb,this.Jb));this.Rc&&this.Rc.tt(this.W.selection,this.sw());c=this.W.animationDuration;
d=new a.Z(0,0,this.xb,this.Jb);this.Hj?"none"!==this.W.animationOnDataChange&&b&&(this.di=new a.la(this.u()),this.A(this.di),b=new a.sq(this.u(),this.di),b.Io(this.p1,this.dc),this.lc=b.nw()):"none"!==this.W.animationOnDisplay&&(this.lc=a.pc.RE(this.u(),a.pc.OC,this.Ea,d,c));this.lc?(this.I.qe(),this.I.ll(this),this.lc.lg(this.gCa,this),this.lc.play()):this.gCa();this.hr()};a.$h.prototype.Twa=function(a){this.dc=a};a.$h.prototype.ph=function(){this.Rd||(this.Rd=new k(this));return this.Rd};a.$h.prototype.TM=
function(a,b){this.Zv.push(a);this.aLa[b]=a};a.$h.prototype.sw=function(){return this.Zv};a.$h.prototype.il=function(){return this.aLa};a.$h.prototype.Ve=function(b){this.W.highlightedCategories=a.ac.clone(b);a.vh.Ve(b,this.sw(),"any"===this.W.highlightMatch);this.kk&&this.kk.Ve(b)};a.$h.prototype.select=function(b){this.W.selection=a.ac.clone(b);this.Rc&&this.Rc.tt(this.W.selection,this.sw())};a.$h.prototype.vf=function(b){b?this.W=this.Xg.en(b):this.W||(this.W=this.NF());b=this.W.selectionMode;
this.Rc="single"===b?new a.Rc(a.Rc.Sy):"multiple"===b?new a.Rc(a.Rc.Ry):null;this.I.zA(this.Rc);a.B.xj()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange="none")};a.$h.prototype.gm=function(){return a.H.Bf(this.F(),"componentName",a.H.Ha,"TAG_CLOUD")};a.$h.prototype.gCa=function(){this.Hj&&(this.removeChild(this.Hj),this.Hj.xa(),this.Hj=null);this.di&&(this.removeChild(this.di),this.di.xa(),this.di=null);this.lc&&this.I.Qf(this);this.W.highlightedCategories&&0<this.W.highlightedCategories.length&&
this.Ve(this.W.highlightedCategories);this.wn||this.qs();this.lc=null;this.wn=!1};a.$h.prototype.YZ=function(){this.I.qe();this.Zv.length=0};a.$h.prototype.bg=function(b,c){var d=b.type;if("categoryHide"==d||"categoryShow"==d){var e=b.category,f=a.na.kb(this.W.hiddenCategories,e);"categoryHide"==d&&0>f&&this.W.hiddenCategories.push(e);"categoryShow"==d&&0<=f&&this.W.hiddenCategories.splice(f,1);this.ta(this.W,this.xb,this.Jb)}else"categoryHighlight"==d&&(this!=c?this.Ve(b.categories):this.kk&&this.kk!=
c&&this.kk.bg(b,c));b&&this.dispatchEvent(b)};a.$h.prototype.hob=function(a){return this.Rc?a[0]:null};a.$h.prototype.Mkb=function(a){a.wb()||(this.Rc.oq(a,!1),this.I.gI());a=[];for(var b=this.Rc.getSelection(),c=0;c<b.length;c++){var d=b[c];d instanceof f&&a.push(d.getId())}return a};a.$h.prototype.Zs=function(){for(var a=[],b=this.Rc.getSelection(),c=0;c<b.length;c++)a=a.concat(b[c].Qe());return a};a.$h.prototype.Zl=function(a,b,c){return this.Xj.Zl(c)};a.$h.prototype.Im=function(a,b){return this.Xj.Im(a,
b)};a.$h.prototype.Zz=function(a,b){return this.Xj.Zz(a,b)};a.$h.prototype.kC=function(a,b){return this.Xj.kC(a,b)};a.v.D(k,a.Rd);k.prototype.zn=function(a){return(a=this.yE.I.mb(a))&&a instanceof f?"item["+this.yE.il().indexOf(a)+"]":null};k.prototype.qh=function(b){if(b==a.Rd.lD)return this.RF(this.yE);var c=b.indexOf("[");return 0<c&&"item"===b.substring(0,c)&&(b=parseInt(b.substring(c+1,b.length-1)),b=this.yE.il()[b])?b.Qe()[0].Ua():null};k.prototype.getItem=function(a){if(a=this.yE.il()[a]){var b=
{};b.color=a.Xl();b.tooltip=a.me();b.label=a.ge();b.value=a.getValue();b.selected=a.wb();return b}return null};k.prototype.pM=function(){return this.yE.sw().length};a.v.D(h,a.He);h.p4a=.3;h.q4a=.6;h.pga=0;h.D5=1;h.qga=2;h.prototype.Init=function(a,b,c,d,e,f,k,l,m){h.C.Init.call(this,b,c,d,e,f,m);this.yE=a;this.HE();this.Ff.fa(k);this.Ff.Ue(l);f&&this.HHa(f)};h.prototype.kc=function(a){this.Ql!=a&&((this.Ql=a)?this.Qp?this.Bb(this.jaa):this.Bb(this.cca):this.Bb(this.pL))};h.prototype.qd=function(){this.Qp||
(this.Qp=!0,this.Ql?this.Bb(this.jaa):this.Bb(this.Goa))};h.prototype.Nc=function(){this.Ql?this.Bb(this.cca):this.Bb(this.pL);this.Qp=!1};h.prototype.sg=function(b,c){var d=new a.gd(this.u(),this,m.ob(this.yE)),e=this.Jd(),f=c.Jd(),k=!1,l=f.M(a.j.mc),u=e.M(a.j.mc);if(l!=u){var D=this;this.Bb(e.fa(a.j.mc,l));d.ja.N(a.G.NDa,this,function(){return D.Jd().M(a.j.mc)},function(b){D.Bb(D.Jd().fa(a.j.mc,b))},u)}f=parseFloat(f.M(a.j.ji));e=parseFloat(e.M(a.j.ji));f!=e&&(k=!0,D=this,this.fh(f),d.ja.N(a.G.V,
this,function(){return parseFloat(D.Jd().M(a.j.ji))},this.fh,e));e=c.Va();f=this.Va();l=c.Qq();u=this.Qq();if(f!=e||k&&u!=l)u!=l&&(e=h.S6a(c,e,l)),this.Fa(e),d.ja.N(a.G.V,this,this.Va,this.Fa,f);k=c.ib();e=this.ib();e!=k&&(this.jb(k),d.ja.N(a.G.V,this,this.ib,this.jb,e));c.T(0);b.add(d,h.D5)};h.prototype.Mj=function(b){b.add(new a.Xi(this.u(),this,m.ob(this.yE)),h.pga)};h.prototype.Ri=function(b){this.T(0);b.add(new a.ih(this.u(),this,m.ob(this.yE)),h.qga)};h.prototype.fh=function(a){h.C.fh.call(this,
a);this.HHa(this.Jd())};h.prototype.HHa=function(b){this.pL=b.clone();b=this.pL.M(a.j.mc);this.pL.fa(a.j.Lb,null);this.Goa=this.pL.clone();var c=h.wLa(b,h.p4a);this.Goa.fa(a.j.Lb,c);this.Goa.fa(a.j.mc,a.O.Wl(c));this.cca=this.pL.clone();this.cca.fa(a.j.Lb,b);this.cca.fa(a.j.mc,a.O.Wl(b));this.jaa=this.pL.clone();b=h.wLa(b,h.q4a);this.jaa.fa(a.j.Lb,b);this.jaa.fa(a.j.mc,a.O.Wl(b))};h.S6a=function(b,c,d){b=b.Xmb();return d==a.ca.Dp?c+b.a:d==a.ca.Kl?c-b.a:c};h.wLa=function(b,c){var d=a.O.Ug(b),e=a.O.Rg(b),
f=a.O.Og(b);return a.O.DI(Math.floor(255*(1-c)+c*d),Math.floor(255*(1-c)+c*e),Math.floor(255*(1-c)+c*f))};a.v.D(f,a.v);f.prototype.Init=function(b,c,d){this.ha=b;this.ej=c;this.Nb=d;this.yO=this.Ql=!1;d.url?(c.cg("link"),this.Bpa=a.K.uM("_blank",d.url)):c.cg("img");this.Hr()};f.prototype.getId=function(){return this.Nb.id};f.prototype.ge=function(){return this.Nb.label};f.prototype.getValue=function(){return this.Nb.value};f.prototype.me=function(){return this.Nb.shortDesc};f.prototype.Ch=function(){return this.Nb.action};
f.prototype.Qg=function(){var a=this.ha.F().tooltip;return(a=a?a.renderer:null)?this.ha.u().Af().Xx(a,this.hn()):this.me()};f.prototype.hn=function(){return{id:this.getId(),label:this.ge(),color:this.Xl(),value:this.getValue()}};f.prototype.uM=function(){return this.Bpa};f.prototype.Xl=function(){return this.ej.pL.M(a.j.mc)};f.prototype.mj=function(a){this.yO=a};f.prototype.tb=function(){return this.yO};f.prototype.wb=function(){return this.Ql};f.prototype.kc=function(a){this.Ql=a;this.ej.kc(a);this.Hr()};
f.prototype.qd=function(){this.ej.qd()};f.prototype.Nc=function(){this.ej.Nc()};f.prototype.Fd=function(c){var d=this.ha.I.Cb;return c.type==a.MouseEvent.Be||d.Nu(c)?this:d.Vi(c)?b.Fd(this,c,this.ha.sw()):null};f.prototype.rf=function(a){return this.ej.aa(a)};f.prototype.Jm=function(){return this.ej.Ua()};f.prototype.Sf=function(){this.dd=!0;this.qd()};f.prototype.Qd=function(){this.dd&&(this.dd=!1,this.Nc())};f.prototype.Kd=function(){return this.dd};f.prototype.Qe=function(){return[this.ej]};f.prototype.Ed=
function(){var b=[];this.tb()&&b.push(a.H.va(a.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));return a.oa.Ik(this.me(),b)};f.prototype.Xd=function(){return this.Nb.categories};f.prototype.Hr=function(){a.B.kj()||this.ej.Gd("label",this.Ed())};f.prototype.zf=function(){if(!this.af&&(this.af=[],this.Nb.showPopupBehaviors))for(var b=this.Nb.showPopupBehaviors,c=0;c<b.length;c++)this.af.push(new a.Vc(b[c].popupId,b[c].triggerType,b[c].alignId,b[c].align));return this.af};f.prototype.Zl=function(a){return this.ha.hob(a)};
f.prototype.Im=function(){return this.ha.Mkb(this)};f.prototype.Zs=function(){return this.ha.Zs()};a.v.D(e,a.bb);e.lh={animationOnDisplay:"none",animationOnDataChange:"none",emptyText:null,hiddenCategories:[],hideAndShowBehavior:"none",highlightedCategories:[],highlightMatch:"all",hoverBehavior:"none",layout:"rectangular",selectionMode:"none",_statusMessageStyle:new a.j(a.bb.Pm+"color: #333333;"),styleDefaults:{animationDuration:500,hoverBehaviorDelay:200,_style:new a.j(a.bb.Pm+"color: #333333;")},
touchResponse:"auto"};var l={};a.v.D(l,a.v);l.ta=function(a,b,c){l.Gr(a,b,c);l.EL(a,b,c);l.xD(c);var d=a.F();d.items&&0<d.items.length?(d=l.ara(a,b,c),0<d.length?(a.Twa(d),a.I.Su(a.sw()[0])):l.JH(a,b,c)):l.JH(a,b,c)};l.JH=function(b,c,d){var e=b.F(),f=e.emptyText;f||(f=a.H.Bf(e,"labelNoData",a.H.Ha,"NO_DATA",null));a.Ca.vp(c,f,new a.Z(d.x,d.y,d.a,d.b),b.I,e._statusMessageStyle)};l.Gr=function(b,c,d){b=new a.Rect(b.u(),d.x,d.y,d.a,d.b);b.Wb();c.A(b)};l.ara=function(b,c,e){for(var k=b.F(),l=[],v=k.items,
m=Number.MAX_VALUE,u=-Number.MAX_VALUE,D=0;D<v.length;D++)m=Math.min(m,v[D].value),u=Math.max(u,v[D].value);var m=d.alb(m,u),u=a.na.MQ(k.hiddenCategories),B=a.j.RTa(),C=k.styleDefaults.style;!C||C instanceof Object||(C=a.j.OQ(C));for(D=0;D<v.length;D++){var z=v[D];z.categories||(z.categories=[z.label]);if(!u||!a.na.qX(u,z.categories)){var G=k.styleDefaults._style.clone(),y=z.style;!y||y instanceof Object||(y=a.j.OQ(y));var E=y&&y.color?y.color:z.color?z.color:C&&C.color?C.color:null;if(y=a.ac.Vd(y,
C)){for(var M=0;M<B.length;M++){var S=a.j.bM(B[M]);y[S]&&(G.fa(B[M],y[S]),delete y[S])}delete y.color}E&&G.fa(a.j.mc,E);G.fa(a.j.ji,m.call(null,z.value).toString());G=new h(b,b.u(),z.label,0,0,G,y,z.className,z.id);y=new f(b,G,z);b.I.lb(G,y);b.TM(y,D);"none"!==k.selectionMode&&y.mj(!0);(y.tb()||z.url||y.Ch())&&G.setCursor("pointer");l.push(G);c.A(G)}}0<l.length&&("cloud"===k.layout?d.nib(e,l):d.pqb(e,l,a.B.da(b.u())));return l};l.EL=function(b,c,d){var e=b.F(),f=e.legend;if(f&&f.sections){f=a.ac.clone(f);
f.orientation="horizontal";f.halign="center";f.hoverBehavior=e.hoverBehavior;f.hideAndShowBehavior=e.hideAndShowBehavior;f.hiddenCategories=e.hiddenCategories;e=a.tf.newInstance(b.u(),b.bg,b);c.A(e);var h=e.ht(f,d.a,d.b/3);e.ta(f,h.a,h.b);a.Dn.position(d,"bottom",e,h.a,h.b,0);b.kk&&(b.kk.xa(),c.removeChild(b.kk));b.kk=e}};l.xD=function(a){a.x=Math.round(a.x);a.y=Math.round(a.y);a.a=Math.round(a.a);a.b=Math.round(a.b)};a.v.D(d,a.v);d.alb=function(a,b){return function(c){return 12+Math.ceil(2*(c-a)/
(b-a)*12)}};d.nib=function(b,c){var d=[],e=10/180,f=10/180;b.a>b.b?e*=b.a/b.b:f*=b.b/b.a;for(var h=2*Math.PI/180,k=null,l=0,m=[],B=[],C=0;C<c.length;C++)for(var z=!1,G=0,y=4,E=c[C],M=E.aa(),l=Math.max(l,parseFloat(E.Jd().M(a.j.ji))),S=-1;!z;){var O=G%180;void 0===m[O]&&(m[O]=Math.cos(G*h));void 0===B[O]&&(B[O]=Math.sin(G*h));var fa=e*G*m[O],ga=f*G*B[O],aa=new a.Z(fa,ga,M.a,M.b),z=!0;-1!=S&&d[S].Gva(aa)&&(z=!1);if(z)for(O=0;O<C;O++)if(d[O].Gva(aa)){S=O;z=!1;break}z&&(k=k?k.wj(aa):aa,S=-1,d[C]=aa,E.Fa(fa),
E.jb(-M.y+ga));3600===G?y=3:5400===G?y=2:10800===G&&(y=1);G+=y}d=Math.max(k.a/b.a,k.b/b.b);e=k.x+k.a/2;k=k.y+k.b/2;for(O=0;O<c.length;O++)E=c[O],E.Fa(b.x+E.Va()/d+(b.a/2-e/d)),E.jb(b.y+E.ib()/d+(b.b/2-k/d)),f=parseFloat(E.Jd().M(a.j.ji)),E.fh(f/d)};d.pqb=function(b,c,e){for(var f=[],h=0,k=0,l=0,m=0;m<c.length;m++){var D=c[m],B=D.aa(),h=Math.max(h,B.a),k=Math.max(k,B.b),l=Math.max(l,parseFloat(D.Jd().M(a.j.ji)));f.push(new a.yj(B.a,B.b))}m=0;for(D=(b.a-10)/h;.001<D-m;)h=(m+D)/2,l=d.YGa(f,(b.a-10)/
h),l.length*(h*k+2)-2>b.b-10?D=h:m=h;h=m;l=d.YGa(f,(b.a-10)/h);l.push(c.length);for(m=0;m<l.length-1;m++){var B=l[m],C=l[m+1],z=0,G=0,y=!0;if(1<C-B){for(var D=0,E=B;E<C;E++)D+=f[E].a*h,G=Math.max(G,f[E].b*h);z=(b.a-10-D)/(C-B-1);m==l.length-2&&(E=.5*G,E<z&&D+(C-B)*E<.9*(b.a-10)&&(z=E,y=!1))}for(var G=5+(m+1)*(k*h+2)-2,M=e?b.a-5:5,E=B;E<C;E++){var D=c[E],S=parseFloat(D.Jd().M(a.j.ji));D.fh(S*h);D.jb(b.y+G);y&&E==C-1&&E!=B?e?(D.Vh(),D.Fa(b.x+5)):(D.Wh(),D.Fa(b.x+b.a-5)):(D.Fa(b.x+M),e?(D.Wh(),M-=f[E].a*
h+z):(D.Vh(),M+=f[E].a*h+z))}}};d.YGa=function(a,b){var c=[0],d=a[0].a+2;if(1<a.length)for(var e=1;e<a.length;e++)d+a[e].a>b&&(c.push(e),d=0),d+=a[e].a+2;return c};var m={};a.v.D(m,a.v);m.ob=function(a){return a.F().styleDefaults.animationDuration/1E3};a.v.D(c,a.I);c.prototype.aT=function(a){a=this.mb(a.target);this.woa(a);this.fQ(a)};c.prototype.gZ=function(a){a=this.mb(a.target);this.fQ(a)};c.prototype.Sw=function(a){a=this.mb(a.target);this.woa(a);this.fQ(a)};c.prototype.woa=function(a){a instanceof
f&&(a=a.uM())&&a.call()};c.prototype.ol=function(b){var d=!0,e=this.jf();b.keyCode==a.KeyboardEvent.Zi?this.woa(e):d=c.C.ol.call(this,b);return d};c.prototype.uq=function(b,c,d){b=this.ha.F();"dim"==b.hoverBehavior&&(c=c.Xd?c.Xd():[],b.highlightedCategories=d?c.slice():null,d=a.Za.GI(b.highlightedCategories,d),c=a.Ta.Pr(b.styleDefaults.hoverBehaviorDelay),this.KJ.bg(d,this.ha.sw(),c,"any"==b.highlightMatch))};c.prototype.fQ=function(b){b&&b.Ch&&b.Ch()&&this.nl(a.Za.FI("action",b.Ch(),b.getId()))};
c.prototype.LA=function(){return this.ha.F().touchResponse};a.v.D(b,a.Cb);b.prototype.Init=function(a){b.C.Init.call(this,a)};b.prototype.iF=function(a){return this.Vi(a)&&!a.ctrlKey};b.prototype.Nu=function(b){return b.keyCode==a.KeyboardEvent.ni&&b.ctrlKey};b.Fd=function(b,c,d){c=c.keyCode==a.KeyboardEvent.uf||c.keyCode==a.KeyboardEvent.Tf?!0:!1;b=a.na.kb(d,b)+(c?1:-1);return b<d.length&&0<=b?d[b]:null};a.v.D(function(){},a.BS);a.Ia(a,"TagCloud",a.$h);a.Ia(a.$h,"newInstance",a.$h.newInstance);a.Ia(a.$h.prototype,
"render",a.$h.prototype.ta);a.Ia(a.$h.prototype,"getAutomation",a.$h.prototype.ph);a.Ia(a.$h.prototype,"highlight",a.$h.prototype.Ve);a.Ia(a.$h.prototype,"select",a.$h.prototype.select);a.Ia(k.prototype,"getDomElementForSubId",k.prototype.qh);a.Ia(k.prototype,"getItem",k.prototype.getItem);a.Ia(k.prototype,"getItemCount",k.prototype.pM)})(dvt);
  return dvt;
});
