/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){a.Lf=function(a,c,d){this.Init(a,c,d)};a.v.D(a.Lf,a.Ie);a.Lf.gEa=1.5;a.Lf.prototype.Init=function(b,c,d){a.Lf.C.Init.call(this,b,c,d);this.Igb=!1};a.Lf.prototype.ta=function(a,c,d){a&&(this.jj=a._resources,null==this.jj&&(this.jj=[]),this.vf(a));this.xb=c;this.Jb=d;this.W&&(a=this.eD(this.W),this.uv(a))};a.Lf.prototype.vf=function(b){this.W=this.Xg.en(b);a.B.xj()||(this.W.animationOnDisplay="none",this.W.animationOnDataChange="none")};a.Lf.prototype.uv=function(a){this.Yb=a.start;this.Ic=
a.end;this.bL=a.tX;this.IE()};a.Lf.prototype.IE=function(){this.Gk&&this.Gk.lj(this.bL)};a.Lf.prototype.qF=function(a){this.je=this.Uf<a?a:this.Uf;this.Igb||(this.qz=0,this.Jv=this.je)};a.Lf.prototype.No=function(){return a.B.da(this.u())};a.Lf.prototype.Sb=function(){return this.de};a.Lf.prototype.BM=function(){return null};a.Lf.prototype.lfa=function(){this.yA(0);if(this.yc&&this.Td){var a=this.Td-this.yc;0<a&&(a=this.Uf/a,this.qF(a*(this.Ic-this.Yb)),this.yA(a*(this.Yb-this.yc)))}else{var a=this.BM(),
a=a.tW[a.mp],c=this.Yb,d=this.Ic;null==this.yc?null!=this.Td?(this.yc=this.Td-this.Uf/a*(d-c),this.yc<this.Yb&&(this.yc=this.Yb),a=this.Td-this.yc,a=this.Uf/a,this.qF(a*(this.Ic-this.Yb)),this.yA(a*(this.Yb-this.yc))):(this.yc=this.Yb,this.yA(0),this.Td=this.Uf/a*(d-c)+this.yc,this.Td>this.Ic&&(this.Td=this.Ic)):(this.Td=this.Uf/a*(d-c)+this.yc,this.Td>this.Ic&&(this.Td=this.Ic),a=this.Td-this.yc,a=this.Uf/a,this.qF(a*(this.Ic-this.Yb)),this.yA(a*(this.Yb-this.yc)))}};a.Lf.prototype.wfa=function(b){this.Ul?
this.Ul.te(null):this.Ul=new a.la(this.u(),"iCanvas");var c=new a.Cd;this.Sb()?(c.Pe(this.bn,this.Un,this.cj,this.Uf),this.Ul.ga(this.bn),this.Ul.wa(this.Un+this.RL)):(c.Pe(this.bn,this.Un,this.Uf,this.cj),this.Ul.ga(this.bn+this.RL),this.Ul.wa(this.Un));b.te(c);this.Ul.getParent()!=b&&b.A(this.Ul)};a.Lf.prototype.VZa=function(b){a.I.sc(b);var c=b.wheelDelta;if(this.hy()&&c){var d=this.u().nC(),d=this.de?b.pageY-d.y:b.pageX-d.x,e=(this.Ic-this.Yb)/this.je,e=this.No()&&!this.de?this.Td-e*d:e*d+this.yc;
this.xR(this.je*(.02*c+1),e,d,!0,b)}};a.Lf.prototype.xR=function(a,c,d){var e=(this.Td-this.yc)/(this.Ic-this.Yb)*this.je;this.qF(a);a=e/this.je*(this.Ic-this.Yb);c?(e=(this.Ic-this.Yb)/this.je,this.No()&&!this.de?(this.Td=c+d*e,this.Td>this.Ic&&(this.Td=this.Ic),this.yc=this.Td-a,this.yc<this.Yb&&(this.yc=this.Yb,this.Td=this.yc+a,this.Td>this.Ic&&(this.Td=this.Ic))):(this.yc=c-d*e,this.yc<this.Yb&&(this.yc=this.Yb),this.Td=this.yc+a,this.Td>this.Ic&&(this.Td=this.Ic,this.yc=this.Td-a,this.yc<this.Yb&&
(this.yc=this.Yb))),this.yA(1/e*(this.Yb-this.yc))):(this.yc=this.Yb,this.Td=this.yc+a,this.yc<this.Yb&&(this.yc=this.Yb),this.yA(0));this.AW()};a.Lf.prototype.BA=function(a){var c=this.de?this.Jb/2:this.xb/2;this.xR(this.je*((1/a-1)/2+1),(this.Ic-this.Yb)/this.je*c+this.yc,c,!0)};a.Lf.prototype.Lhb=function(a,c,d,e){this.Roa=this.de?Math.sqrt((c-e)*(c-e))+(c<e?c:e):Math.sqrt((a-d)*(a-d))+(a<d?a:d);this.HKa=(this.Ic-this.Yb)/this.je*this.Roa+this.yc;this.Qoa=Math.sqrt((a-d)*(a-d)+(c-e)*(c-e));this.GKa=
this.je};a.Lf.prototype.oib=function(a,c,d,e){a=Math.sqrt((a-d)*(a-d)+(c-e)*(c-e));a!=this.Qoa&&(this.VH=!0);this.xR(a/this.Qoa*this.GKa,this.HKa,this.Roa,!1)};a.Lf.prototype.ujb=function(){this.HKa=this.GKa=this.Roa=this.Qoa=null;this.VH&&(this.VH=!1,this.dispatchEvent(this.Tz()))};a.Lf.prototype.uwa=function(a){if(this.de){a=this.Ul.pa()-a;var c=-(this.je-this.Uf-this.Un),d=this.Un;a<c?a=c:a>d&&(a=d);this.Ul.wa(a);a-=this.Un;this.bWa(a)}else a=this.Ul.qa()-a,c=-(this.je-this.Uf-this.bn),d=this.bn,
a<c?a=c:a>d&&(a=d),this.Ul.ga(a),this.bWa(a-this.bn),a=this.DTa();c=this.je/(this.Ic-this.Yb);d=this.Td-this.yc;this.yc=this.Yb-a/c;this.Td=this.yc+d};a.Lf.prototype.cUa=function(b){b?this.BA(1/a.Lf.gEa):this.BA(a.Lf.gEa)};a.Lf.prototype.oda=function(a){a?(this.Jh.sn(!0),this.Jh.KE()):(this.Kh.sn(!0),this.Kh.KE())};a.Lf.prototype.cM=function(a){a?(this.Jh.sn(!1),this.Jh.kda(),this.Jh.setCursor(null)):(this.Kh.sn(!1),this.Kh.kda(),this.Kh.setCursor(null))};a.Lf.prototype.AW=function(){this.de?this.Ul.wa(this.Un+
this.RL):this.Ul.ga(this.bn+this.RL)};a.Lf.prototype.bWa=function(a){this.RL=a};a.Lf.prototype.DTa=function(){return this.No()&&!this.de?this.Uf-this.je-this.RL:this.RL};a.Lf.prototype.yA=function(a){this.No()&&!this.de?this.RL=this.Uf-this.je-a:this.RL=a};a.Lf.prototype.aga=function(a){this.bn=a};a.Lf.prototype.GWa=function(a){this.Un=a};a.Lf.prototype.bg=function(a){a&&this.dispatchEvent(a)};a.Lf.prototype.Tz=function(){return null};a.Lf.prototype.SS=function(){};a.Lf.prototype.TF=function(){};
a.Lf.prototype.JQ=function(a,c){this.Sma=a;this.Tma=c};a.Lf.prototype.dI=function(){this.rda()};a.Lf.prototype.Y6=function(a){"none"!=this.dw&&this.uva(a,"multiple"==this.dw)};a.Lf.prototype.uva=function(){};a.Lf.prototype.UZa=function(a){this.uva(a,a.ctrlKey&&"multiple"==this.dw)};a.Lf.prototype.rda=function(){this.VH&&(this.VH=!1,this.dispatchEvent(this.Tz()))};a.Lf.prototype.S2=function(a,c){if(this.Sma&&this.Tma){var d=this.Sma-a,e=this.Tma-c;if(0==d&&0==e)return!1;this.VH=!0;this.Sma=a;this.Tma=
c;this.Wi(d,e);return!0}return!1};a.Lf.prototype.Wi=function(a){this.uwa(a)};a.ai=function(a){this.Init(a.u(),a.bg,a);this.Li=a;this.fpa=this.$oa=!1};a.v.D(a.ai,a.I);a.ai.Wza="wheel";a.ai.prototype.Qf=function(b){a.ai.C.Qf.call(this,b);a.Aj.P2(this.Li,this.TP,this.SP,this.RP,this);a.B.Wa()||(a.B.$n()?b.Ya(a.ai.Wza,this.cD,!1,this):b.Ya(a.MouseEvent.YF,this.cD,!1,this))};a.ai.prototype.ll=function(b){a.ai.C.ll.call(this,b);a.B.Wa()||(a.B.$n()?b.jc(a.ai.Wza,this.cD,!1,this):b.jc(a.MouseEvent.YF,this.cD,
!1,this))};a.ai.prototype.uZ=function(b){a.ai.C.uZ.call(this,b);this.Li.SS(b)};a.ai.prototype.Tj=function(b){this.$oa||(a.ai.C.Tj.call(this,b),this.Li.UZa(b))};a.ai.prototype.s7=function(b){this.$oa=!1;a.ai.C.s7.call(this,b);this.Li.TF(b)};a.ai.prototype.cD=function(a){this.Li.VZa(a)};a.ai.prototype.bT=function(b){a.ai.C.bT.call(this,b);this.Li.hZ(b);this.Li.u().Oe.nG.parentNode.focus()};a.ai.prototype.o7=function(b){a.ai.C.o7.call(this,b);this.Li.Y6(b)};a.ai.prototype.TP=function(b){if(this.Li.hy())return a.B.Wa()?
this.C1(b):this.z1(b)};a.ai.prototype.SP=function(b){return a.B.Wa()?this.B1(b):this.y1(b)};a.ai.prototype.RP=function(b){return a.B.Wa()?this.A1(b):this.x1(b)};a.ai.prototype.Oi=function(b,c){this.Dm||(this.Dm=this.Aa.nC());return new a.R(b-this.Dm.x,c-this.Dm.y)};a.ai.prototype.z1=function(b){return b.button!=a.MouseEvent.$ia?(b=this.Oi(b.pageX,b.pageY),this.Li.JQ(b.x,b.y),!0):!1};a.ai.prototype.y1=function(a){a=this.Oi(a.pageX,a.pageY);this.Li.S2(a.x,a.y)&&(this.$oa=!0)};a.ai.prototype.x1=function(){this.Li.dI();
this.Dm=null};a.ai.prototype.C1=function(b){var c=b.touches;if(1==c.length)return b=this.Oi(c[0].pageX,c[0].pageY),this.Li.JQ(b.x,b.y),!0;if(2==c.length){this.Li.dI();this.fpa=!0;var d=this.Oi(c[0].pageX,c[0].pageY),c=this.Oi(c[1].pageX,c[1].pageY);this.Li.Lhb(d.x,d.y,c.x,c.y);a.I.sc(b);return!0}return!1};a.ai.prototype.B1=function(a){var c=a.touches;if(1==c.length){var d=this.Oi(c[0].pageX,c[0].pageY);this.Li.S2(d.x,d.y);a.preventDefault()}else 2==c.length&&(d=this.Oi(c[0].pageX,c[0].pageY),c=this.Oi(c[1].pageX,
c[1].pageY),this.Li.oib(d.x,d.y,c.x,c.y),a.preventDefault())};a.ai.prototype.A1=function(a){this.fpa?(this.fpa=!1,this.Li.ujb()):this.Li.dI();a.preventDefault();this.Dm=null};a.ai.prototype.BA=function(a){this.Li.BA(a)};a.ai.prototype.Wi=function(b,c){var d=b*this.Li.Uf*(a.B.da(this.Aa)?-1:1),e=c*this.Li.cj;0!=d&&(this.Li.VH=!0);this.Li.Wi(d,e);this.Li.rda()};a.ai.prototype.iZ=function(){this.Li.cUa(!0)};a.ai.prototype.jZ=function(){this.Li.cUa(!1)};a.ai.prototype.LA=function(){return a.I.jG};a.dO=
function(a){this.Init(a)};a.v.D(a.dO,a.Cb);a.dO.prototype.iF=function(a){return this.Vi(a)&&!a.ctrlKey};a.dO.prototype.Nu=function(b){return b.keyCode==a.KeyboardEvent.ni&&b.ctrlKey};a.dO.prototype.mk=function(b){if(a.KeyboardEvent.Xea(b))this.yb.iZ();else if(a.KeyboardEvent.Uea(b))this.yb.jZ();else{var c=b.keyCode;c==a.KeyboardEvent.Iia?(b.shiftKey?this.yb.Wi(-.25,0):this.yb.Wi(0,-.25),a.I.sc(b)):c==a.KeyboardEvent.Hia&&(b.shiftKey?this.yb.Wi(.25,0):this.yb.Wi(0,.25),a.I.sc(b))}return a.dO.C.mk.call(this,
b)}})(dvt);
  return dvt;
});
