/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(['./DvtToolkit', './DvtPanZoomCanvas'], function(dvt) {
  // Internal use only.  All APIs and functionality are subject to change at any time.

var q;function ba(a,b){0==a.indexOf("dvt.")&&(a=a.substring(4));var c=a.split("."),d=eval("dvt");c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b}Math.floor(2147483648*Math.random()).toString(36);
(function(a){function b(a,b,c){this.Init(a,b,c)}function c(a){this.Init(a)}function d(a,b,c){this.Init(a,b,c)}function e(a,b){this.Init(a,b)}function f(a,b,c,d,e){this.Init(a,b,c,d,e)}function h(a,b,c,d,e){this.Init(a,b,c,d,e)}function k(a,b,c,d,e){this.Init(a,b,c,d,e)}function l(a,b,c){this.Init(a,b,c)}function m(a,b,c,d,e,f){this.Init(a,b,c,d,e,f)}function n(a,b,c,d,e,f,h){this.Init(a,b,c,d,e,f,h)}function r(a,b,c,d){this.Init(a,b,c,d)}function p(a,b,c,d,e){this.Init(a,b,c,d,e)}function w(a,b,c,
d,e,f){this.Init(a,b,c,d,e,f)}function x(a,b){this.Init(a,b)}function v(a,b,c){this.Init(a,b,c)}function A(a,b){this.Init(a,b)}function u(a){this.Da=a}function D(){this.Init({fusion:D.DEFAULT,alta:D.mf})}a.Qj=function(a,b,c){this.Init(a,b,c)};a.v.D(a.Qj,a.la);a.Qj.cK=10;a.Qj.prototype.Init=function(b,c,d){a.Qj.C.Init.call(this,b);this.Da=new a.$a(b,c,d);this.Aca=new a.la(b);this.Aca.A(this.Da);this.A(this.Aca);this.Xg=new D};a.Qj.newInstance=function(b,c,d){return new a.Qj(b,c,d)};a.Qj.prototype.ta=
function(b,c,d){this.W=this.Xg.en(b);this.zb=c;this.Qb=d;c=new a.Z(0,0,c,d);this.EL(this,c);this.Da.ta(b,c.a,c.b)};a.Qj.prototype.EL=function(b,c){this.Ac&&(b.removeChild(this.Ac),this.Ac=null);var d=new a.Z(a.Qj.cK,a.Qj.cK,c.a-2*a.Qj.cK,c.b-2*a.Qj.cK),e=this.W,f=e.legend.rendered,h=e.legend.scrolling,k=a.ac.clone(e.legend);this.nla(this.W,k);var l=k.sections;if(f&&(!l||0!=l.length)&&(f=e.legend.position,delete k.position,k.layout.gapRatio=this.wSa(),k.hideAndShowBehavior="none",k.rolloverBehavior=
"none",k.scrolling=e.legend.scrolling,l=a.tf.newInstance(this.Da.u()),b.A(l),"auto"==f&&"asNeeded"!==h?f="bottom":"auto"==f&&"asNeeded"==h&&(f="end"),h=a.B.da(b.u()),"start"==f?f=h?"right":"left":"end"==f&&(f=h?"left":"right"),k.orientation="left"==f||"right"==f?"vertical":"horizontal",h="top"==f||"bottom"==f,h=l.ht(k,h?d.a:e.layout.legendMaxSize*d.a,h?e.layout.legendMaxSize*d.b:d.b),0<h.a&&0<h.b))switch(l.ta(k,h.a,h.b),this.Ac=l,e=D.Dh(this,e.layout.legendGap),a.Dn.position(d,f,l,h.a,h.b,e),f){case "top":this.Aca.wa(h.b+
a.Qj.cK);case "bottom":c.b-=h.b+a.Qj.cK;break;case "left":this.Aca.ga(h.a+a.Qj.cK);case "right":c.a-=h.a+a.Qj.cK}};a.Qj.prototype.wSa=function(){return null===this.W.layout.gapRatio||isNaN(this.W.layout.gapRatio)?Math.min(Math.min(this.zb/400,1),Math.min(this.Qb/300,1)):this.W.layout.gapRatio};a.Qj.prototype.nla=function(a,b){b.title=a.legend?a.legend.title:null;b.sections=[];if(a&&a.legend&&a.legend.sections)for(var c=0;c<a.legend.sections.length;c++){var d=a.legend.sections[c];d&&b.sections.push({title:d.title,
items:d.items,sections:d.sections})}return b};a.Qj.prototype.qh=function(a){var b;this.Ac&&(b=this.Ac.ph().qh(a));return b?b:this.Da.ph().qh(a)};a.Qj.prototype.i4=function(a){var b;this.Ac&&(b=this.Ac.ph().i4(a));return b?b:this.Da.ph().i4(a)};a.$a=function(a,b,c){this.Init(a,b,c)};a.v.D(a.$a,a.fc);a.$a.h4a=1;a.$a.i4a=2;a.$a.OEa=3;a.$a.j4a=4;a.$a.PEa=5;a.$a.QEa=6;a.$a.Aka=7;a.$a.$2a=5;a.$a.avb="controlPanelResources";a.$a.bvb="legendResources";a.$a.cvb="panelDrawerResources";a.$a.$ub="resources";
a.$a.EYa=6;a.$a.prototype.Init=function(b,c,d){a.$a.C.Init.call(this,b,c,d);this.IHa();this.ei=[];this.WG=[];this.qH=this.$e=this.Ac=null;this.Cla=!1;this.e0=[];this.E0={};this.Eba=!1;this.B$={};this.nma={};this.fu=[];this.KHa();this.N1=this.N2=this.Uoa=!1;this.Spa=a.$a.EYa;this.mH=!0;this.RV={};this.r9=!1;this.af=null;this.rF(a.ua.nN);this.Xg=new D;this.I.lb(this,this);this.mh=!1};a.$a.prototype.KHa=function(){this.mGa=new a.la(this.u());this.h$=new a.la(this.u());this.SG=new a.la(this.u());this.pH=
new a.la(this.u());this.vP=new a.la(this.u())};a.$a.newInstance=function(b,c,d){return new a.$a(b,c,d)};a.$a.prototype.vf=function(b){a.$a.C.vf.call(this,b);a.B.xj()||(this.W.animationOnDisplay="none",this.W.animationOnMapChange="none",this.W.animationOnDrill="none");(new c(this)).parse(this.W)};a.$a.prototype.Osb=function(a){this.w2=a};a.$a.prototype.fTa=function(){return this.N2?this.Spa:1};a.$a.prototype.lsb=function(a){this.Spa=a};a.$a.prototype.jsb=function(a){this.mH="fixed"==a};a.$a.prototype.qhb=
function(a){this.ei.push(a)};a.$a.prototype.khb=function(a){this.ei.push(a)};a.$a.prototype.fR=function(a){for(var b=0;b<this.ei.length;b++)if(this.ei[b].vk==a)return this.ei[b]};a.$a.prototype.isb=function(a){this.Cla=this.Vp&&this.Vp!=a;this.Vp=a};a.$a.prototype.mrb=function(a){this.eGa=a};a.$a.prototype.orb=function(a){this.k7a=a};a.$a.prototype.IC=function(a){this.Ml=parseFloat(a)};a.$a.prototype.ob=function(){return this.Ml};a.$a.prototype.Orb=function(a){this.iIa=a};a.$a.prototype.Nfa=function(b){b=
parseInt(b);var c=this.PO;if(b==a.$a.h4a||b==a.$a.OEa||b==a.$a.PEa||b==a.$a.Aka)c&=~a.ua.dv,this.EWa(!1);if(b==a.$a.i4a||b==a.$a.OEa||b==a.$a.QEa||b==a.$a.Aka)c&=~a.ua.oN,this.MWa(!1);if(b==a.$a.j4a||b==a.$a.PEa||b==a.$a.QEa||b==a.$a.Aka)c&=~a.ua.pN;this.rF(c)};a.$a.prototype.rWa=function(a){this.Lbb=a};a.$a.prototype.sWa=function(a){this.Mbb=a};a.$a.prototype.tWa=function(a){this.IKa=a};a.$a.prototype.nrb=function(a){this.xla=a};a.$a.prototype.qxa=function(a){this.tr=a;this.I.qxa(a)};a.$a.prototype.csb=
function(a){this.Uoa=a};a.$a.prototype.fT=function(){a.$a.C.fT.call(this);!this.Ks&&this.geb&&(this.ei=[],this.e0=[],this.E0={},this.B$={},this.nma={},this.fu=[],this.removeChild(this.$e),this.qH=this.Ac=this.$e=null,this.rF(a.ua.nN),this.N1=this.N2=!0,this.yV=this.Id,this.KHa(),this.af=null,this.I.ll(this),this.IHa(),this.r9=!1,this.I.qe(),this.I.lb(this,this))};a.$a.prototype.IHa=function(){this.I=new d(this.u(),this.dispatchEvent,this);this.I.Qf(this);a.B.Wa()?this.$D=null:(this.$D=new e(this,
this.I),this.I.Xr(this.$D))};a.$a.prototype.TZa=function(b){a.B.da(this.u())||(b=this.getWidth()-5-b.getWidth(),this.$e.ga(b))};a.$a.prototype.EL=function(){if(this.qH){this.$e&&(this.$e.xa(),this.removeChild(this.$e));var b="true"==this.qH.disclosed,c="fixed"==this.qH.display||a.B.zw();if(!c||b){var d=this.qH.maxWidth,e=d.indexOf("%"),d=-1!=e?parseFloat(d.substring(0,e))/100*this.getWidth():parseFloat(d),e=this.getHeight()-2*a.$a.$2a;this.ke==a.j.mf?(this.$e=new a.ea(this.u(),null,this,"pd"),this.$e.Ya(a.ps.xe,
this.IAa,!1,this),this.$e.wA(d),this.$e.j5(e),this.$e.Wrb(c),a.B.da(this.u())?(this.$e.Lfa(a.ea.ho),this.$e.ga(0)):this.$e.ga(this.getWidth())):(this.$e=new a.Fc(this.u(),d,e,a.Fc.zY,this.hc(),this.vw(),b,c),this.$e.Ya(a.GA.xe,this.IAa,!1,this),this.$e.Ya(a.Gn.IJ,this.TZa,!1,this),this.$e.wrb(this.qH.expandTooltip,this.qH.collapseTooltip));d=this.qH;this.Ac=a.tf.newInstance(this.u(),this.Mwa,this);this.A(this.$e);this.A(this.Ac);e=this.Ac.ht(d,this.$e.N3(),this.$e.aX());this.Ac.ta(d,e.a,e.b);var f;
if(this.ke==a.j.mf){this.$e.Vfa(this.Ac.jC().b);this.removeChild(this.Ac);var d=new a.Image(this.u(),this.hc()[a.ea.kCa],0,0,a.ea.Nh,a.ea.Nh),e=new a.Image(this.u(),this.hc()[a.ea.lCa],0,0,a.ea.Nh,a.ea.Nh),h=new a.Image(this.u(),this.hc()[a.ea.jCa],0,0,a.ea.Nh,a.ea.Nh),k=a.H.va(a.H.Ha,"LEGEND");this.$e.yW(this.Ac,d,e,h,k,a.ea.vZ);this.$e.Dw();b&&this.$e.Di(!0,!0)}else this.$e.chb(this.Ac),f=this.$e.aa(),b=a.B.da(this.u())?5:this.getWidth()-5-f.a-f.x,this.$e.Ma(b,5),f.a+=5;if(this.QKa=c)f||(f=this.$e.aa()),
this.xpa=f.a,this.Id.Vu(this.getWidth()-this.xpa,this.getHeight(),!0)}}};a.$a.prototype.Fn=function(){a.$a.C.Fn.call(this);var b=new a.la(this.u()),c=new a.la(this.u());this.Id=this.Qa;this.Id.A(b);this.Id.Oa.A(c);this.Sl(b,c);if(this.Wn){(this.Ze=this.Id.Ze)&&this.Id.A(this.Ze);this.fr(!0);c=new a.Z(0,0,this.getWidth(),this.getHeight());if(this.mh||this.yV){var d=null;this.Cla&&!this.Ks?d=this.k7a:this.Wn&&this.Wn.vk!=this.Vcb&&(d=this.Wn.nw());a.pc.isSupported(d)&&(this.lc=a.pc.gM(this.u(),d,this.yV,
this.Id,c,this.Ml))&&this.A(this.yV)}else a.pc.isSupported(this.eGa)&&(this.lc=a.pc.RE(this.u(),this.eGa,this.Id,c,this.Ml));this.lc?(this.Ze&&this.A(this.Ze),this.I.qe(),this.I.ll(this),this.r9=!0,this.lc.lg(this.Uw,this),this.lc.play()):this.Uw();this.geb=b;this.Wn&&(this.Vcb=this.Wn.vk);this.u().YM([this]);this.mh=!0}};a.$a.prototype.c8a=function(){var a=this.Id.Px,b=this.Wn.gR(),c=this.Id.pe();return Math.min((c.a-2*a)/b.a,(c.b-2*a)/b.b)};a.$a.prototype.Sl=function(a,b){this.EL();b.A(this.mGa);
b.A(this.h$);this.mH?a.A(this.SG):b.A(this.SG);a.A(this.pH);a.A(this.vP);var c=this.Id.Oa.sb();this.ssa=!1;for(var d=0;d<this.ei.length;d++){var e=this.ei[d];if(!this.ssa&&e instanceof k||!(e instanceof k))e.ta(c),!this.ssa&&e instanceof k&&(this.ssa=!0,this.Wn=e)}this.Wn&&(c=this.Wn.aV,this.aV!=c&&(this.aV=c,this.rWa(null),this.sWa(null),this.tWa(null)),this.MOa(),this.Id.MC(null),this.Id.xA(null),this.Id.oY(!0),this.Id.NC(!0),this.Cla||this.Ks||null==this.IKa?this.Id.Dt(null,this.Wn.gR()):(this.Id.Ct(this.IKa),
this.Id.EC(this.Lbb,this.Mbb)),this.INa(),this.YPa(),this.Id.oY(this.N2),this.Id.NC(this.N1))};a.$a.prototype.MOa=function(){if(this.$D){var a=this.Q3();0==a.length&&(a=this.iR());0==a.length&&(a=this.R3());this.I.asb(a[0])}};a.$a.prototype.ttb=function(a,b,d){this.mh=!1;this.fr(!0);(new c(this)).q7([a],this.fR(b),this.Wn.vk,d);this.EL();this.mh=!0;this.MOa();this.u().YM([this]);this.YPa()};a.$a.prototype.dOa=function(){this.wn||this.qs();this.lc=null;this.wn=!1};a.$a.prototype.YPa=function(){var a=
this.c8a();this.Id.MC(a);this.Id.xA(a*this.fTa())};a.$a.prototype.iCa=function(){this.Wn.aV&&this.Id.Dt(null,this.Wn.gR());this.INa();this.Uoa&&this.eQa();this.dOa()};a.$a.prototype.wWa=function(a){this.qH=a};a.$a.prototype.Exa=function(a){this.sra=a};a.$a.prototype.HPa=function(b){var c=new a.Tb;c.translate(b.le,b.fe);this.mH&&this.SG.rb(c);this.pH.rb(c);this.vP.rb(c)};a.$a.prototype.IAa=function(b){b=a.Za.am(a.fc.CBa,b.Zn()==a.GA.PJ);this.dispatchEvent(b)};a.$a.prototype.y8a=function(b){var c=this.Id.Px,
d=this.Id.pe(),c=new a.Z(c,c,d.a-2*c,d.b-2*c),e=this.Wn.gR(),f=e.x*b,d=e.y*b,h=e.a*b;b*=e.b;e=0;h>c.a?(this.QKa&&a.B.da(this.u())&&(e=this.xpa),this.Id.hY(c.x+c.a+e-(f+h)),this.Id.fY(c.x-f+e)):(this.QKa&&a.B.da(this.u())&&(e=2*this.xpa),f=(c.x+c.a+e)/2-(f+h/2),this.Id.hY(f),this.Id.fY(f));b>c.b?(this.Id.iY(c.y+c.b-(d+b)),this.Id.gY(c.y-d)):(c=(c.y+c.b)/2-(d+b/2),this.Id.iY(c),this.Id.gY(c))};a.$a.prototype.NPa=function(b,c){var d=b.ja;if(d){var e=this.Id.Oa,f=d.$f(e,e.sb);c&&(this.WHa=e.sb(),d.N(a.G.aj,
this,this.B$a,this.Qfb,f));e=new a.Tb(1,0,0,1,f.le,f.fe);this.mH&&d.N(a.G.aj,this.SG,this.SG.sb,this.SG.rb,e);d.N(a.G.aj,this.pH,this.pH.sb,this.pH.rb,e);d.N(a.G.aj,this.vP,this.vP.sb,this.vP.rb,e)}};a.$a.prototype.uk=function(b){switch(b.Zn()){case a.xd.H7:this.N1&&this.y8a(b.GB);break;case a.xd.K7:case a.xd.HZ:this.NPa(b,!0);break;case a.xd.QJ:var c=b.GB;if(null!=c){var d=this.Id.Oa.sb();b.ja=null;this.dispatchEvent(a.Za.owa(d.le,d.fe,c));this.HPa(d);for(c=0;c<this.ei.length;c++)this.ei[c].uk(b,
d)}break;case a.xd.Hja:this.sta();break;case a.xd.M7:this.dispatchEvent(a.Za.owa())}};a.$a.prototype.$C=function(b){var c=b.Zn();if(c==a.wh.HZ)this.NPa(b,!1);else if(c==a.wh.Cja&&null!=b.nMa){var d=this.Id.Oa.sb();b.ja=null;this.dispatchEvent(a.Za.owa(d.le,d.fe,this.Id.wg()));this.HPa(d);for(b=0;b<this.ei.length;b++)this.ei[b].$C(d)}this.$e&&(this.ke==a.j.mf?c===a.wh.NJ?this.$e.nb(!1):c===a.wh.OJ&&this.$e.nb(!0):(d=this.vw(),b=this.$e.Gb.Ud().clone(),c===a.wh.NJ?(this.Ac.T(d[a.ua.tya]),b.T(d[a.ua.vha]),
this.$e.Gb.Ga(b),this.$e.Tm&&this.$e.Tm.T(d[a.ua.vha]),this.$e.nb(!1)):c===a.wh.OJ&&(this.Ac.T(1),b.T(d[a.ua.Cy]),this.$e.Gb.Ga(b),this.$e.Tm&&this.$e.Tm.T(d[a.ua.Cy]),this.$e.nb(!0))))};a.$a.prototype.rJ=function(){return"none"!=this.tr||this.N2||this.N1&&this.ke!=a.j.mf?a.$a.C.rJ.call(this):a.fc.GF};a.$a.prototype.B6=function(){var c=this.rJ();return c!=a.fc.GF?new b(this.u(),this,c==a.fc.gJ?a.ua.XN:a.ua.MJ):null};a.$a.prototype.MWa=function(a){this.N2=a};a.$a.prototype.EWa=function(a){this.N1=
a};a.$a.prototype.ghb=function(a,b){this.E0[a]=b};a.$a.prototype.INa=function(){this.Eba=!0;for(var a=0;a<this.ei.length;a++){var b=this.ei[a].vk;b in this.E0&&(this.RV[b]=this.E0[b][1],this.Cq=b,this.HD=this.E0[b][0],this.lda())}this.Eba=!1};a.$a.prototype.$wa=function(){this.fr(!0);for(var a=[],b=[],c=this.ei.length-1;-1<c;c--)this.ei[c].vk==this.Wn.vk?this.ei[c].reset(b):this.ei[c].reset(a);for(c=0;c<a.length;c++)if(a[c]){var d=a[c].getParent();d&&d.removeChild(a[c])}for(c=0;c<b.length;c++)b[c]&&
b[c].T(1);this.e0=[];this.Cjb();this.fu=[];this.Ze&&"none"!=this.tr&&(this.Ze.uxa(!1),this.Ze.vxa(!1))};a.$a.prototype.eQa=function(){var b=this.h$.aa(),c=this.SG.aa();if(this.mH){var d=this.Id.Oa.sb();c.a/=d.gg;c.b/=d.qj;c.x/=d.gg;c.y/=d.qj}b=b.wj(c);this.fr(!0);var e;this.Id.fB||(e=this.Id.WE(),this.Id.xA(e*this.Spa));var f;a.B.xj()&&(f=new a.G(this.u(),.3));0<b.a&&0<b.b?this.Id.Dt(f,b):this.Id.Dt(f,this.Wn.gR());f&&f.play();e&&this.Id.xA(e)};a.$a.prototype.uW=function(b){var c=new a.G(this.u(),
.3);this.Id.Dt(c,b);c.play()};a.$a.prototype.Djb=function(a){a||(a=this.fQa);a||(a=this.E_);this.uW(a.aa())};a.$a.prototype.sta=function(){if(this.HD){var a=this.fR(this.Cq).Oj(this.HD);if(a&&(a=a.Yc)){for(var a=a.getSelection(),b=0;b<a.length;b++)a[b]=a[b].Sa();if(0<a.length){for(var c=a[0].aa(),b=1;b<a.length;b++)c=c.wj(a[b].aa());this.uW(c)}}}};a.$a.prototype.Cjb=function(){var b=new a.G(this.u(),.3);this.Id.Dt(b);b.play()};a.$a.prototype.sSa=function(a){a=B.hmb(this.Vp,a);return this.fR(a)};a.$a.prototype.Yta=
function(a){a=B.fSa(this.Vp,a);return this.fR(a)};a.$a.prototype.Q3=function(){var a=[];if(this.Wn)for(var b=0;b<this.ei.length;b++){var c=this.ei[b].Om,d;for(d in c)a=this.Wn.vk==this.ei[b].vk?a.concat(c[d].Qlb()):a.concat(c[d].Rlb())}return a};a.$a.prototype.iR=function(){var a=[];if(this.Wn)for(var b=0;b<this.ei.length;b++){var c=this.ei[b].Om;if(this.Wn.vk==this.ei[b].vk||!(this.ei[b]instanceof k))for(var d in c)a=a.concat(c[d].Wp)}return a};a.$a.prototype.R3=function(){var a=[];if(this.Wn)for(var b=
0;b<this.ei.length;b++){var c=this.ei[b].Om;if(this.Wn.vk==this.ei[b].vk||!(this.ei[b]instanceof k))for(var d in c)a=a.concat(c[d].wP)}return a};a.$a.prototype.Qfb=function(a){this.WHa=a;if(this.mH){for(var b=this.iR(),c=0;c<b.length;c++)b[c].uk(a);b=this.pH.Rb();for(c=0;c<b;c++)for(var d=this.pH.hb(c),e=d.Rb(),f=0;f<e;f++){var h=d.hb(f);h instanceof w&&h.update(a)}}};a.$a.prototype.B$a=function(){return this.WHa};a.$a.prototype.lda=function(){this.fr(!0);var a=this.Yta(this.Cq),b=this.fR(this.Cq),
c=[];if(a){this.B$[this.Cq]=this.HD;for(var d=this.RV[this.Cq],e=[],f=0;f<d.length;f++)this.t$a(d[f],b.Oj(this.HD)).wC()||e.push(d[f]);this.Eba||"single"!=this.tr||(this.fu.pop(),b.reset(c,d),a.reset(this.WG));d=[];for(f=0;f<e.length;f++){var h=e[f],k=b.Ota(h);d.push(k[0]);for(var l=0;l<k.length;l++)this.nma[k[l]]=h;a.jta(k,c);(k=b.Oj(this.HD))&&k.djb(h,this.WG);this.fu.push(h)}this.kKa(this.WG,c,!1);this.Eca(a.vk,!0);this.Cq=a.vk;this.RV[this.Cq]=d}};a.$a.prototype.mta=function(){this.fr(!0);for(var b=
this.fR(this.Cq),c=this.sSa(this.Cq),d=[],e=[],f=this.RV[this.Cq],h=0;h<f.length;h++){var k=this.nma[f[h]];e.push(k);-1!=a.na.kb(this.fu,k)&&(b.B5(c.Ota(k),this.WG),c.Oj(this.B$[c.vk]).ntb(k,d),k=a.na.kb(this.fu,k),-1!=k&&this.fu.splice(k,1))}this.kKa(this.WG,d,!0);this.Cq=c.vk;this.HD=this.B$[this.Cq];this.RV[this.Cq]=e;this.Eca(this.Cq)};a.$a.prototype.kKa=function(b,c,d){this.Id.Oa.sb();if("zoomToFit"==this.xla&&!this.Eba){var e=new a.G(this.u(),.3);a.B.xj()||(e=null);d?this.Id.Dt(e):this.sta();
e&&e.play()}this.fr(!0);!a.B.xj()||"alphaFade"!=this.xla&&"auto"!=this.xla||(this.lc=a.pc.gM(this.u(),"alphaFade",b,c,null,.5));this.lc?(this.I.qe(),this.I.ll(this),this.lc.lg(this.w0a,this),this.lc.play()):this.fHa()};a.$a.prototype.yrb=function(a,b,c){this.Cq=b;this.HD=a;this.E_=c};a.$a.prototype.XR=function(a){this.AIa=a};a.$a.prototype.dispatchEvent=function(b){var c=b.type;if("selection"==c)this.mbb(b);else if(c==a.Nt.xe)this.fbb(b);else if("adfShowPopup"==c||"adfHidePopup"==c)b.clientId=this.AIa;
a.$a.C.dispatchEvent.call(this,b)};a.$a.prototype.mbb=function(b){this.HD?(this.Mra=b.selection,this.RV[this.Cq]=this.fR(this.Cq).Oj(this.HD).Bmb(this.Mra),this.Eca(this.Cq),b.clientId=this.HD,!this.E_||this.E_ instanceof a.za||this.E_ instanceof a.Ef||(this.fQa=this.E_)):(this.Eca(null),this.fQa=null)};a.$a.prototype.Eca=function(a,b){if(this.Ze&&this.tr&&"none"!=this.tr){var c=this.Yta(a),d=this.sSa(a);c&&!b?this.Ze.uxa(!0):this.Ze.uxa(!1);d?this.Ze.vxa(!0):this.Ze.vxa(!1)}};a.$a.prototype.fbb=
function(b){b.dl("clientId",this.AIa);this.e0="multiple"==this.tr?this.e0.concat(this.Mra):this.Mra;var c=b.N9a;c==a.Nt.OYa&&this.mta();c==a.Nt.iha?this.lda():c==a.Nt.U0a&&this.$wa();b.Di(this.e0)};a.$a.prototype.xa=function(){for(var b=this.ei,c=0;c<b.length;c++)b[c].xa();a.$a.C.xa.call(this)};a.$a.prototype.Uw=function(){this.Ze&&this.Id.A(this.Ze);this.yV&&(this.removeChild(this.yV),this.yV=null);this.dOa();this.Uoa&&this.eQa();this.W.highlightedCategories&&0<this.W.highlightedCategories.length&&
this.Ve(this.W.highlightedCategories);this.r9&&(this.I.Qf(this),this.r9=!1)};a.$a.prototype.w0a=function(){this.fHa();this.lc=null;this.I.Qf(this)};a.$a.prototype.fHa=function(){if(0<this.WG.length){for(var a=0;a<this.WG.length;a++){var b=this.WG[a];if(b)if(b instanceof w)b.reset();else if(b.wC&&b.wC())b.T(0);else{var c=b.getParent();c&&c.removeChild(b)}}this.WG=[]}};a.$a.prototype.zf=function(){return this.af};a.$a.prototype.lY=function(a){this.af=a};a.$a.prototype.ph=function(){this.Rd||(this.Rd=
new u(this));return this.Rd};a.$a.prototype.gm=function(){return a.H.va(a.H.Ha,"THEMATIC_MAP")};a.$a.prototype.Mwa=function(b){b.type==a.Gn.IJ&&this.Ac&&this.Ac.Te(b)};a.$a.prototype.Ve=function(b){this.W.highlightedCategories=a.ac.clone(b);a.vh.Ve(b,this.Q3().concat(this.iR()).concat(this.R3()),"any"==this.W.highlightMatch)};a.$a.prototype.ky=function(a,b){var c=this.Rna(a);c&&c.ky(b)};a.$a.prototype.II=function(a,b){var c=this.Rna(a);c&&c.II(b)};a.$a.prototype.FC=function(a,b){var c=this.Rna(a);
c&&c.FC(b)};a.$a.prototype.Rna=function(a){for(var b=0;b<this.ei.length;b++){var c=this.ei[b].Om,d;for(d in c)for(var e=c[d].Wp,f=0;f<e.length;f++)if(e[f].getId()===a)return e[f]}return null};a.$a.prototype.t$a=function(a,b){for(var c=b.Ye,d=0;d<c.length;d++)if(c[d].mn()===a)return c[d];return null};a.v.D(D,a.bb);D.DEFAULT={animationDuration:500,animationOnDisplay:"none",animationOnDrill:"none",animationOnMapChange:"none",controlPanelBehavior:"hidden",drilling:"none",highlightMatch:"all",hoverBehavior:"none",
initialZooming:"none",markerZoomBehavior:"fixed",panning:"none",tooltipDisplay:"auto",touchResponse:"auto",visualEffects:"none",zooming:"none",styleDefaults:{skin:"alta",_areaStyle:{backgroundColor:"#B8CDEC",borderColor:"#FFFFFF"},hoverBehaviorDelay:200,dataAreaDefaults:{borderColor:"#FFFFFF",drilledInnerColor:"#FFFFFF",drilledOuterColor:"#000000",hoverColor:"#FFFFFF",opacity:1,selectedInnerColor:"#FFFFFF",selectedOuterColor:"#000000"},dataMarkerDefaults:{borderColor:"#FFFFFF",borderStyle:"solid",
borderWidth:.5,color:"#000000",height:8,labelStyle:"font-family:Tahoma;font-size:13pt;color:#000000",opacity:.4,scaleX:1,scaleY:1,shape:"circle",width:8},linkDefaults:{color:"#9bb2c7",_hoverColor:"#FFFFFF",_selectedColor:"#000000",width:2},labelStyle:"font-family:Tahoma;font-size:11pt;"},legend:{position:"auto",rendered:!0,layout:{gapRatio:1}},layout:{gapRatio:null,legendMaxSize:.3,legendGap:10},resources:{images:{},translations:{}}};D.mf={styleDefaults:{_areaStyle:{backgroundColor:"#DDDDDD",borderColor:"#FFFFFF"},
dataAreaDefaults:{drilledOuterColor:"#0572CE"},dataMarkerDefaults:{color:"rgb(51,51,51)",labelStyle:a.bb.ar+"color:#333333",opacity:1},labelStyle:a.bb.ar}};D.uYa={animationOnLayerChange:"none",labelDisplay:"auto",labelType:"short"};D.wYa={animationOnDataChange:"none",selectionMode:"none"};D.prototype.Qhb=function(b){return a.ac.Vd(b,D.uYa)};D.prototype.Uhb=function(b){return a.ac.Vd(b,D.wYa)};D.Dh=function(a,b){return Math.ceil(b*a.wSa())};a.$a.prototype.M$=function(){for(var a=0;a<this.ei.length;a++){var b=
this.ei[a].Om,c;for(c in b){var d=b[c].Xj;if(d&&d.SO)return d}}return null};a.$a.prototype.Zl=function(a,b,c){return(a=this.M$())?a.Zl(c):!1};a.$a.prototype.Im=function(a,b){var c=this.M$();return c?c.Im(a,b):null};a.$a.prototype.Zz=function(a,b){var c=this.M$();return c?c.Zz(a,b):null};a.$a.prototype.kC=function(a,b){var c=this.M$();return c?c.kC(a,b):null};a.v.D(function(){},a.BS);a.v.D(u,a.Rd);u.prototype.zn=function(b){var c=this.Da.ab().mb(b);if(c&&(c instanceof r||c instanceof p))return this.Rab(c);
var d=this.Da.Qa.Ze;if(d&&(c=d.ab().mb(b))&&c instanceof a.ia){b="disclosure zoomIn zoomOut zoomToFit drillDown drillUp reset".split(" ");for(var e=0;e<b.length;e++)if(d.mw(b[e])===c)return"controlPanel#"+b[e]}return null};u.prototype.qh=function(b){if(b==a.Rd.lD)return this.RF(this.Da);var c=b.indexOf(":"),d=b.indexOf("[");return 0<c&&0<d?this.O$a(b.substring(0,c),b.substring(c+1,d),parseInt(b.substring(d+1,b.length-1))):0===b.lastIndexOf("controlPanel")&&(c=b.indexOf("#"),0<c&&(b=b.substring(c+
1),(c=this.Da.Qa.Ze)&&b))?(b=c.mw(b))?b.Ua():null:null};u.prototype.getData=function(a,b,c){return(a=this.pJa(a,b,c))?(b={},b.color=a.Xl(),b.tooltip=a.me(),c=a.ge(),b.label=c?c.lf():null,b.selected=a.wb(),b):null};u.prototype.O$a=function(a,b,c){return(a=this.pJa(a,b,c))?a.Sa().Ua():null};u.prototype.Rab=function(b){for(var c=b.Sa(),d=this.Da.ei,e=0;e<d.length;e++){var f=d[e].Om,h;for(h in f)if(c instanceof a.vb){for(var k=f[h].Ye,l=0;l<k.length;l++)if(k[l]===b)return this.N$(h)+":area["+l+"]";k=
f[h].wP;for(l=0;l<k.length;l++)if(k[l]===b)return this.N$(h)+":link["+l+"]"}else if(c instanceof a.za||c instanceof a.Ef)for(k=f[h].Wp,l=0;l<k.length;l++)if(k[l]===b)return this.N$(h)+":marker["+l+"]"}return null};u.prototype.pJa=function(a,b,c){for(var d=this.Da.ei,e=0;e<d.length;e++){var f=d[e].Om,h;for(h in f)if(this.N$(h)==a){if("area"==b)return f[h].g$[c];if("marker"==b)return f[h].n$[c];if("link"==b)return f[h].l$[c]}}return null};u.prototype.N$=function(a){var b=a.lastIndexOf(":");return 0<
b?a.substring(b+1):a};a.v.D(A,a.vb);A.vJ=2;A.y7=1;A.z7=4;A.x7=6;A.fha=2;A.gha=4;A.prototype.Init=function(a,b){A.C.Init.call(this,a);this.IK=this.HK=this.s$=this.r$=null;this.apa=!1;this.Zoom=1;this.Cj=b};A.prototype.wC=function(){return this.apa};A.prototype.WX=function(a){this.apa!=a&&(this.apa=a,this.wC()?(this.HK=this.fn(),this.HK.ra(null),this.HK.nb(!1),this.IK=this.fn(),this.IK.ra(null),this.IK.nb(!1),a=this.getParent(),a.A(this.IK),a.A(this.HK),this.HK.Ga(this.Uy(this.r$,A.fha)),this.IK.Ga(this.Uy(this.s$,
A.gha)),this.nb(!1),this.Yg=!1):(this.Yg&&(this.Pk(),this.Bn.Ga(this.Uy(this.MA,1),A.vJ)),this.IK.getParent().removeChild(this.IK),this.HK.getParent().removeChild(this.HK),this.nb(!0),this.T(1)))};A.prototype.kc=function(a){this.Cn!=a&&(a&&(this.Yg?(this.KY(),this.ss=this.Uy(this.ss,A.vJ),this.er=this.Uy(this.er,A.x7)):(this.VA=this.Uy(this.VA,A.y7),this.bx=this.Uy(this.bx,A.z7))),A.C.kc.call(this,a))};A.prototype.qd=function(){this.wb()?(this.KY(),this.ss=this.Uy(this.ss,A.vJ),this.er=this.Uy(this.er,
A.x7)):this.MA=this.Uy(this.MA,A.vJ);A.C.qd.call(this)};A.prototype.KY=function(){this.ss||(this.ss=this.MA.clone(),this.ss.Xa(A.vJ),this.Cj&&this.ss.If(!0));this.er||(this.er=this.bx.clone(),this.er.Xa(A.x7),this.Cj&&this.er.If(!0))};A.prototype.Nc=function(){this.wb()&&(this.VA=this.Uy(this.VA,A.y7),this.bx=this.Uy(this.bx,A.z7));A.C.Nc.call(this)};A.prototype.xt=function(a,b){A.C.xt.call(this,a,b);this.Cj&&(this.MA&&this.MA.If(!0),this.kZ&&this.kZ.If(!0));return this};A.prototype.At=function(a,
b){A.C.At.call(this,a,b);this.Cj&&(this.VA&&this.VA.If(!0),this.bx&&this.bx.If(!0));return this};A.prototype.Uu=function(a,b){A.C.Uu.call(this,a,b);this.Cj&&(this.ss&&this.ss.If(!0),this.er&&this.er.If(!0));return this};A.prototype.Nrb=function(a,b){(this.r$=a)&&this.Cj&&this.r$.If(!0);(this.s$=b)&&this.Cj&&this.s$.If(!0)};A.prototype.crb=function(a){this.feb=a};A.prototype.XL=function(a,b){if(!this.Cj){var c=a.Ud();c&&(c=c.clone(),c.Xa(b/this.Zoom),a.Ga(c))}};A.prototype.Uy=function(a,b){if(!this.Cj){var c=
a.clone();c.Xa(b/this.Zoom);return c}return a};A.prototype.dUa=function(a){this.Zoom=a.gg;this.wC()?(this.XL(this.HK,A.fha),this.XL(this.IK,A.gha)):this.wb()?this.Yg?(this.XL(this.Bn,A.vJ),this.XL(this,A.x7)):(this.XL(this.Bn,A.y7),this.XL(this,A.z7)):this.Yg?this.XL(this.Bn,A.vJ):this.XL(this,1)};a.v.D(v,a.la);v.y8=5;v.prototype.Init=function(b,c,d){v.C.Init.call(this,b);this.MD=c;c instanceof a.Ie?(this.zb=c.getWidth(),this.Qb=c.getHeight(),this.A(c)):(this.Ua().appendChild(c),c=a.Mh.jn(b,this),
this.zb=c.a,this.Qb=c.b);this.iB=new a.Rect(b,-v.y8,-v.y8,this.zb+2*v.y8,this.Qb+2*v.y8);this.iB.Wb();b=new a.ya(d.selectedInnerColor,1,2);c=new a.ya("rgb(235, 236, 237)",1,4);var e=new a.ya(d.selectedInnerColor,1,2),f=new a.ya(d.selectedOuterColor,1,4),h=new a.ya(d.selectedInnerColor,1,2);d=new a.ya(d.selectedOuterColor,1,6);this.iB.xt(b,c).At(e,f).Uu(h,d);this.Ib(this.iB,0)};v.prototype.Gd=function(b,c){a.B.Wa()?this.iB.Gd(b,c):v.C.Gd.call(this,b,c)};v.prototype.cg=function(b){a.B.Wa()?this.iB.cg(b):
v.C.cg.call(this,b)};v.prototype.getWidth=function(){return this.zb};v.prototype.getHeight=function(){return this.Qb};v.prototype.mj=function(a){this.iB.mj(a)};v.prototype.tb=function(){return this.iB.tb()};v.prototype.wb=function(){return this.iB.wb()};v.prototype.kc=function(a){this.iB.kc(a)};v.prototype.qd=function(){this.iB.qd()};v.prototype.Nc=function(){this.iB.Nc()};v.prototype.wtb=function(b){this.MD!==b&&(this.MD&&(this.MD instanceof a.Ie?this.removeChild(this.MD):this.Ua().removeChild(this.MD)),
b instanceof a.Ie?this.A(b):this.Ua().appendChild(b),this.MD=b)};v.prototype.JW=function(b){this.MD instanceof a.Ie&&this.MD.JW(b)};var B;this?this.DvtBaseMapManager?B=this.DvtBaseMapManager:(this.DvtBaseMapManager=B={},B._UNPROCESSED_MAPS=[[],[],[]],B._UNPROCESSED_PARENT_UPDATES=[[]]):window.DvtBaseMapManager?B=window.DvtBaseMapManager:(B={},window.DvtBaseMapManager=B,B._UNPROCESSED_MAPS=[[],[],[]],B._UNPROCESSED_PARENT_UPDATES=[[]]);a.v.D(B,a.v,"DvtBaseMapManager");B.cO=0;B.lm=1;B.bka=2;B.aka=3;
B.h8=4;B.sD="__index";B.mm={};B.URa=function(b,c){B.$v();var d=B.mm[b][c];return d&&(d=d[B.h8])?new a.Z(d[0],d[1],d[2],d[3]):null};B.Ojb=function(a,b){B.$v();var c=B.mm[a][b];return c?c[B.aka]:null};B.LRa=function(a,b){var c=[],d=B.Ata(a,b),e;for(e in d)c.push(e);return c};B.Pjb=function(a,b){B.$v();var c=B.mm[a][b];return c?c[B.cO]:null};B.Glb=function(a,b,c){B.$v();a=B.mm[a][b];var d;a&&(d=a[B.cO]);return d&&d[c]?d[c][1]:null};B.okb=function(b,c){B.$v();var d=B.mm[b];return d&&(d=d.cities)&&(d=
d[B.lm][c])?new a.R(d[0],d[1]):null};B.pkb=function(a,b){B.$v();var c=B.mm[a];return c&&(c=c.cities)&&(c=c[B.cO][b])?c[1]:null};B.Mjb=function(b,c,d){B.$v();var e=B.mm[b];if(e&&(e=e[c])){if((e=e[B.aka])&&e[d])return a.Z.create(e[d][0]).ye();b=B.mm[b][c][B.lm][d];if(!b)return null;b=a.P.T2(b);return a.P.aa(b).ye()}return null};B.fSa=function(a,b){B.$v();var c=B.mm[a][b];return c?B.mm[a][B.sD][c.__index+1]:null};B.hmb=function(a,b){B.$v();return B.mm[a][b]?B.mm[a][B.sD][B.mm[a][b].__index-1]:null};
B.Ata=function(a,b){B.$v();return B.mm[a][b][B.lm]};B.imb=function(a,b,c){B.$v();return B.mm[a][b][B.lm][c]};B.nkb=function(a,b){B.$v();var c=B.fSa(a,b);return c&&(c=B.mm[a][c][B.bka])?c:[]};B.Zvb=function(a,b){B.$v();return B.mm[a][B.sD][b]};B.NVa=function(a,b,c,d,e,f,h,k){var l=B.mm[a];l||(l={},l[B.sD]=[],B.mm[a]=l);a=l[b];a||(a={},l[b]=a,null!=h&&(l[B.sD][h]=b));a[B.cO]=c;a[B.lm]=d;a[B.bka]=e;a[B.aka]=f;a[B.h8]=k;a[B.sD]=h};B.tqb=function(a,b,c){var d=B.mm[a];d||(d={},B.mm[a]=d);a=d[b];a||(a={},
d[b]=a);(a=d[b])&&(a[B.cO]=c)};B.vtb=function(a,b,c){if(a=B.mm[a])if(b=a[b])for(var d in c)b[B.cO][d]=c[d]};B.$v=function(){var a,b,c=B._UNPROCESSED_MAPS;if(c){for(a=0;a<c[0].length;a++)b=c[0][a],B.NVa(b[0],b[1],b[2],b[3],b[4],b[5],b[6],b[7]);for(a=0;a<c[1].length;a++)b=c[1][a],B.tqb(b[0],b[1],b[2]);for(a=0;a<c[2].length;a++)b=c[2][a],B.vtb(b[0],b[1],b[2]);B._UNPROCESSED_MAPS=[[],[],[]]}if(c=B._UNPROCESSED_PARENT_UPDATES){for(a=0;a<c[0].length;a++){b=c[0][a];var d=b[1],e=b[2],f=B.mm[b[0]],h;if(f){if(d=
f[d])for(d[B.bka]=b[3],h=d[B.h8],a=d[B.sD],d=f[B.sD],d.splice(a,0,e),f[e][B.sD]=a,a+=1;a<d.length;a++)(e=f[d[a]])&&e[B.sD]++;(d=f[b[2]])&&(d[B.h8]=h)}}B._UNPROCESSED_PARENT_UPDATES=[[]]}};B.Zsb=function(b,c,d,e,f,h){if(0<h){c=1/(Math.min(e/c,f/d)*h);if(1>=c)return b;d=[];if(b)for(var k in b)e=b[k],isNaN(e)&&(e=a.P.T2(b[k])),d[k]=a.P.$sb(e,c);return d}return b};B.Blb=function(a,b){B.$v();var c=B.mm[a][b],d={};if(c){var c=c[B.cO],e;for(e in c)d[e]=c[e][1];if("cities"!==b&&!c)for(e=B.LRa(a,b),c=0;c<
e.length;c++)d[e[c]]=null}return d};a.v.D(x,a.v);x.prototype.Init=function(a,b){this.ej=a;this.CO=b};x.prototype.Xd=function(){return this.CO};x.prototype.Qe=function(){return[this.ej]};a.Nt=function(b){this.Init(a.Nt.xe);this.N9a=b};a.v.D(a.Nt,a.Vg);a.Nt.xe="drill";a.Nt.OYa=0;a.Nt.iha=1;a.Nt.U0a=2;a.Nt.prototype.Di=function(a){this.sr=a};a.XS=function(b,c,d){this.Init(a.XS.xe);this.item=b;this.rowKey=c;this.action=d};a.v.D(a.XS,a.Vg);a.XS.xe="action";a.XS.prototype.qw=function(){return this.item};
a.XS.prototype.Ch=function(){return this.action};a.v.D(w,a.ca);w.prototype.Init=function(b,c,d,e,f,h){w.C.Init.call(this,b,c,0,0);this.Cj=h;this.FD=[];this.nb(!1);this.Yf();this.Ng();this.Ol=null;this.Bx=e;this.aQ=f;if(d&&(this.FD.push(a.Z.create(d[0])),1<d.length))for(this.vpa=[],c=1;c<d.length;c++)e=d[c],this.FD.push(a.Z.create(e[0])),e=new a.Yw(b,e[1]),e.md(),f=new a.ya("#000000"),this.Cj&&f.If(!0),e.Ga(f),this.vpa.push(e)};w.prototype.Xgb=function(a){this.FD.push(a)};w.prototype.Mnb=function(){return 0<
this.FD.length};w.prototype.update=function(b){b=b.gg;for(var c=-1,d=a.Ca.Pj(this),e=!1,f=0;f<this.FD.length;f++){var h=this.FD[f].a*b;if(d.b<=this.FD[f].b*b)if(d.a<=h){c=f;break}else if(this.getParent()||(e=!0,this.aQ.A(this)),this.aa().a<=h){c=f;break}}-1==c&&"on"==this.Bx&&(c=this.FD.length-1);this.Qma!=c?(-1==c?this.reset():(this.getParent()||this.aQ.A(this),d=this.FD[c].ye(),this.uA(d),this.vpa&&(this.aQ.removeChild(this.Kq),this.Kq=null,0<c?(this.Kq=this.vpa[c-1],this.aQ.A(this.Kq),e=this.Jd(),
e.fa(a.j.mc,"#000000"),this.Bb(e),e=this.FD[c],f=this.Kq.ad(),h=f.length,e.x>f[h-2]?(this.Vh(),this.Ng(),this.uA(new a.R(e.x,d.y))):e.y>f[h-1]?(this.np(),this.Yf(),this.uA(new a.R(d.x,e.y))):e.x+e.a<f[h-2]?(this.Wh(),this.Ng(),this.uA(new a.R(e.x+e.a,d.y))):e.y+e.b<f[h-1]&&(this.Oq(),this.Yf(),this.uA(new a.R(d.x,e.y+e.b)))):(this.Yf(),this.Ng(),e=this.Jd(),e.fa(a.j.mc,this.cLa),this.Bb(e)))),this.Qma=c):-1==c&&e&&this.aQ.removeChild(this);-1!=this.Qma&&(c=new a.Tb,c.translate(b*this.Ol.x-this.Ol.x,
b*this.Ol.y-this.Ol.y),this.rb(c),this.Kq&&(this.Kq.rb(new a.Tb(b,0,0,b)),this.Cj||(c=this.Kq.Ud().clone(),c.Xa(1/b),this.Kq.Ga(c))))};w.prototype.uA=function(a){this.Ol=a;this.Fa(a.x);this.jb(a.y)};w.prototype.ye=function(){return this.Ol};w.prototype.Bb=function(b){w.C.Bb.call(this,b);this.cLa||(this.cLa=b.M(a.j.mc))};w.prototype.reset=function(){this.aQ.removeChild(this);this.Qma=-1;this.Kq&&(this.aQ.removeChild(this.Kq),this.Kq=null)};a.v.D(p,a.v,"DvtMapObjPeer");p.pga=0;p.D5=1;p.qga=2;p.prototype.Init=
function(b,c,d,e,f){this.Nb=b;this.qr=c;this.oa=d;this.dd=this.Qp=this.Ql=!1;this.oa.TX&&this.oa.TX(b.color);this.Ec=e;this.Ol=f;this.Zoom=1;this.ha=c.Da;this.Nb.categories||this.Ec&&(this.Nb.categories=[this.Ec.lf()]);d=b.location;this.V0;d&&(c=c.P1,this.V0=!(c instanceof k)||c instanceof h?B.pkb(this.ha.Vp,d):B.Glb(this.ha.Vp,c.vk,d));"auto"==this.ha.iIa&&this.V0&&(this.Nb.shortDesc=b.shortDesc?this.V0+": "+b.shortDesc:this.V0);this.oa&&(this.oa.fa(b.style).Ue(b.className),b.destination?(this.oa.cg("link"),
this.Bpa=a.K.uM("_blank",b.destination)):this.oa.cg("img"));this.ir();this.mj(this.tb())};p.prototype.getId=function(){return this.Nb.id};p.prototype.qw=function(){return this.Nb.clientId};p.prototype.mn=function(){return this.Nb.location};p.prototype.ye=function(){return this.Ol};p.prototype.IOa=function(a){this.Ol=a;this.$Z()};p.prototype.Sa=function(){return this.oa};p.prototype.ge=function(){return this.Ec};p.prototype.Oj=function(){return this.qr};p.prototype.fUa=function(){return null!=this.Ch()};
p.prototype.Ch=function(){return this.Nb.action};p.prototype.Jc=function(a){this.oa.Jc(a);this.Ec&&this.Ec.Jc(a)};p.prototype.me=function(){return this.Nb.shortDesc};p.prototype.Aqb=function(){this.Ec=null};p.prototype.pe=function(){return this.oa.getWidth?this.oa.getWidth()*this.oa.getHeight():0};p.prototype.Xd=function(){var a=this.Nb.categories;return a?a:[]};p.prototype.Qg=function(){if("none"!=this.ha.iIa){var a=this.ha.F()._tooltip;return a?this.ha.u().Af().Xx(a,this.hn()):this.me()}return null};
p.prototype.hn=function(){return{color:this.Xl(),component:this.ha.F()._widgetConstructor,data:this.Nb,id:this.getId(),label:this.Ec?this.Ec.lf():null,location:this.mn(),locationName:this.V0,tooltip:this.me(),x:this.Nb.x,y:this.Nb.y}};p.prototype.uM=function(){return this.Bpa};p.prototype.Xl=function(){return this.Nb.color?this.Nb.color:"#000000"};p.prototype.Ed=function(){var b=[];this.tb()&&b.push(a.H.va(a.H.Ha,this.wb()?"STATE_SELECTED":"STATE_UNSELECTED"));return a.oa.Ik(this.me(),b)};p.prototype.Qe=
function(){return[this.Sa()]};p.prototype.ir=function(){if(!a.B.kj()){var b=this.Ed();b&&this.oa.Gd("label",b)}};p.prototype.mj=function(a){var b=this.ge();this.oa.mj&&(this.oa.mj(a),b&&a&&b.setCursor("pointer"));this.Nb.destination&&(this.oa.setCursor("pointer"),b&&b.setCursor("pointer"))};p.prototype.tb=function(){return this.oa.tb?"off"!==this.Nb.selectable?this.qr.tb():!1:!1};p.prototype.wb=function(){return this.Ql};p.prototype.kc=function(a){if(this.tb()){var b=this.um();this.Ql=a;this.qr.F().selectionRenderer?
this.z_(this.qr.F().selectionRenderer,this.um(),b):this.II(a);this.ir()}};p.prototype.qd=function(){var a=this.um();this.Qp=!0;this.qr.F().hoverRenderer?this.z_(this.qr.F().hoverRenderer,this.um(),a):this.ky(!0)};p.prototype.Nc=function(){var a=this.um();this.Qp=!1;this.qr.F().hoverRenderer?this.z_(this.qr.F().hoverRenderer,this.um(),a):this.ky(!1)};p.prototype.lY=function(a){this.af=a};p.prototype.zf=function(){return this.af};p.prototype.Zl=function(a){for(var b=this.qr.qw(),c=0;c<a.length&&a[c]!=
b;c++);return b};p.prototype.Im=function(){return this.qr.hK(this)};p.prototype.Zs=function(){return this.qr.gK()};p.prototype.Fd=function(b){if(b.type==a.MouseEvent.Be||b.keyCode==a.KeyboardEvent.ni&&b.ctrlKey)return this;if((b.keyCode==a.KeyboardEvent.TA||a.KeyboardEvent.FA)&&b.altKey){var c=this.Oj().XE(this.getId());return e.TW(this,b,c)}return a.Cb.YE(this,b,this.E6())};p.prototype.E6=function(){return this.Oj().Da.iR()};p.prototype.rf=function(b){return this.oa.getParent()?this.oa.aa(b?b:this.oa.u().Oe):
new a.Z(0,0,0,0)};p.prototype.Jm=function(){return this.oa.Ua()};p.prototype.Sf=function(){var a=this.um();this.dd=!0;this.qr.F().focusRenderer?this.z_(this.qr.F().focusRenderer,this.um(),a):this.FC(!0)};p.prototype.Qd=function(){if(this.Kd()){var a=this.um();this.dd=!1;this.qr.F().focusRenderer?this.z_(this.qr.F().focusRenderer,this.um(),a):this.FC(!1)}};p.prototype.Kd=function(){return this.dd};p.prototype.uk=function(a){this.oa.getParent()&&(this.Zoom=a.gg,this.$Z())};p.prototype.jfa=function(){if(this.Ec){this.Ec.Yf();
var b=this.oa.gk()*this.Zoom,c=this.oa.hk()*this.Zoom,d=this.oa.getHeight(),e=this.oa instanceof a.za?this.oa.he():"image",f=this.Nb.labelPosition;"top"==f?(c=c-d/2-4,this.Ec.Oq()):"bottom"==f?(c+=d/2,this.Ec.np()):(c=e==a.za.TJ?c+d/6:e==a.za.SJ?c-d/6:c,this.Ec.Ng());this.Ec.Fa(b).jb(c)}};p.prototype.$Z=function(){var b=this.oa.getWidth(),c=this.oa.getHeight();if(null!=b&&null!=c&&this.oa.getParent()){var d=0,e=this.Ol.x,d=this.Ol.y;this.oa.yM&&(d=this.oa.yM(),e=this.Ol.x*Math.cos(d)-this.Ol.y*Math.sin(d),
d=this.Ol.x*Math.sin(d)+this.Ol.y*Math.cos(d));e=this.Ol.x*this.Zoom-e;d=this.Ol.y*this.Zoom-d;this.oa instanceof v&&(e+=this.Ol.x-b/2,d+=this.Ol.y-c/2);this.oa.Ma(e,d);a.B.dya(this.oa);this.jfa()}};p.prototype.sg=function(b,c){var d=new a.gd(this.ha.u(),this.oa,this.Oj().ob()),e=c.Sa();if(this.oa.fd){var f=e.fd(),h=this.oa.fd();h instanceof a.$b&&(h.ic()!=f.ic()||h.Ra()!=f.Ra())&&(this.oa.ra(f),c.ge()&&this.Ec&&(f=this.Ec.fd(),this.Ec.ra(c.ge().fd().clone()),d.ja.N(a.G.po,this.Ec,this.Ec.fd,this.Ec.ra,
f)),d.ja.N(a.G.po,this.oa,this.oa.fd,this.oa.ra,h))}this.oa.Yz&&(h=c.Sa().Yz(),f=this.oa.Yz(),h.x!=f.x||h.y!=f.y||h.a!=f.a||h.b!=f.b)&&(this.oa.OI(h),d.ja.N(a.G.mD,this.oa,this.oa.Yz,this.oa.OI,f));h=e.yM();f=this.oa.yM();if(h!=f){var k=h-f;k>Math.PI?h-=2*Math.PI:k<-Math.PI&&(h+=2*Math.PI);this.oa.zp(h);d.ja.N(a.G.V,this.oa,this.oa.yM,this.oa.zp,f)}var k=c.ye(),l=this.ye();k&&l&&(k.x!=l.x||k.y!=l.y||h!=f)&&(this.IOa(new a.R(k.x,k.y)),d.ja.N(a.G.lG,this,this.ye,this.IOa,new a.R(l.x,l.y)));this.Ec&&
c.ge()?(h=c.ge().Va(),f=this.Ec.Va(),h!=f&&(this.Ec.Fa(h),d.ja.N(a.G.V,this.Ec,this.Ec.Va,this.Ec.Fa,f)),h=c.ge().ib(),f=this.Ec.ib(),h!=f&&(this.Ec.jb(h),d.ja.N(a.G.V,this.Ec,this.Ec.ib,this.Ec.jb,f)),c.ge().T(0)):c.ge()&&c.ge().T(0);e.T(0);b.add(d,p.D5)};p.prototype.Mj=function(b){var c=[this.oa],d=this.ge();d&&c.push(d);c=new a.Xi(this.ha.u(),c,this.Oj().ob());b.add(c,p.pga)};p.prototype.Ri=function(b){var c=[this.oa];this.oa.T(0);var d=this.ge();d&&(d.T(0),c.push(d));c=new a.ih(this.ha.u(),c,
this.Oj().ob());b.add(c,p.qga)};p.prototype.II=function(a){this.oa.kc&&this.oa.kc(a)};p.prototype.FC=function(a){this.ky(a)};p.prototype.ky=function(a){a?this.oa.qd&&this.oa.qd():this.oa.Nc&&!this.Kd()&&this.oa.Nc()};p.prototype.z_=function(a,b,c){if(this.oa instanceof v){var d=this.ha.F()._contextHandler;d&&(b=d(this.oa.Ua(),this.oa.MD,this.Nb,b,c),a=a(b),this.oa.wtb(a))}};p.prototype.um=function(){return{hovered:this.Qp,selected:this.wb(),focused:this.Kd()}};a.v.D(r,p,"DvtMapAreaPeer");r.prototype.Init=
function(a,b,c,d){r.C.Init.call(this,a,b,c,d)};r.prototype.rrb=function(a){this.Fv=a};r.prototype.kc=function(a){this.tb()&&(a&&!this.Qp&&this.Fv.A(this.oa),r.C.kc.call(this,a))};r.prototype.qd=function(){this.Fv.A(this.oa);r.C.qd.call(this)};r.prototype.Nc=function(){this.wb()?this.Fv.A(this.oa):this.Fv.Ib(this.oa,0);r.C.Nc.call(this)};r.prototype.wC=function(){return this.oa.wC()};r.prototype.WX=function(a){a?this.Fv.A(this.oa):this.Fv.Ib(this.oa,0);this.oa.WX(a)};r.prototype.uk=function(a){r.C.uk.call(this,
a);this.oa.getParent()&&(this.oa.dUa(a),this.wC()||this.jfa(a))};r.prototype.jfa=function(a){this.ge()&&this.ge().update(a)};r.prototype.E6=function(){return this.Oj().Da.Q3()};r.prototype.sg=function(a,b){r.C.sg.call(this,a,b);this.Oj().P1.Bfa(this.mn(),!1)};r.prototype.$Z=function(){};a.v.D(n,p,"DvtMapLinkPeer");n.prototype.Init=function(a,b,c,d,e,f,h){n.C.Init.call(this,a,b,c);this.SL=d;this.LK=e;this.rca=f;this.una=h};n.prototype.Fd=function(b){var c=this.qr.Da.I.Cb;return b.type==a.MouseEvent.Be||
b.keyCode==a.KeyboardEvent.ni&&b.ctrlKey?this:c.Maa===e.DBa?b.keyCode===a.KeyboardEvent.kh?(b=c.BLa.getId(),b=this.Oj().XE(b),c=b.indexOf(this),c++,c===b.length&&(c=0),b[c]):b.keyCode===a.KeyboardEvent.Tf?(b=c.BLa.getId(),b=this.Oj().XE(b),c=b.indexOf(this),c--,-1===c&&(c=b.length-1),b[c]):b.keyCode===a.KeyboardEvent.Jf?this.SL.x<=this.LK.x?this.rca:this.una:b.keyCode===a.KeyboardEvent.uf?this.SL.x>=this.LK.x?this.rca:this.una:this:a.Cb.YE(this,b,this.E6())};n.prototype.E6=function(){return this.Oj().Da.R3()};
n.prototype.$Z=function(){if(this.oa.getParent()){var b=new a.R(this.SL.x*this.Zoom,this.SL.y*this.Zoom),d=new a.R(this.LK.x*this.Zoom,this.LK.y*this.Zoom),b=c.EQa(this.qr,this.SL,this.LK,b,d);this.oa.nk(b);a.B.dya(this.oa)}};n.prototype.sg=function(b,c){var d=new a.gd(this.ha.u(),this.oa,this.Oj().ob()),e=c.Sa(),f=e.Ud(),h=this.oa.Ud();h.ic()!=f.ic()&&(this.oa.Ga(f),d.ja.N(a.G.UJ,this.oa,this.oa.Ud,this.oa.Ga,h));var f=c.LK,h=this.LK,k=!0;c.SL.Fe(this.SL)&&f.Fe(h)||(k=!1,this.oa.T(0),d.ja.N(a.G.V,
this.oa,this.oa.Ra,this.oa.T,1),d.ja.N(a.G.V,e,e.Ra,e.T,0));k&&e.T(0);b.add(d,p.D5)};a.v.D(m,a.la);m.Zub=1;m.prototype.Init=function(a,b,c,d,e,f){m.C.Init.call(this,a);this.Ql=this.yO=!1;this.s7a=d;this.u7a=e;this.ba=c;this.A(this.ba);this.ha=b;this.Cj=f;if(a=c.Ud())this.nGa=a.getWidth()};m.prototype.Qg=function(){var a=this.ha.F()._tooltip;return a?this.ha.u().Af().Xx(a,this.hn()):this.Vl};m.prototype.mWa=function(a){this.Vl=a};m.prototype.hn=function(){return{color:null,component:this.ha.F()._widgetConstructor,
data:null,id:null,label:null,location:this.s7a,locationName:this.u7a,tooltip:this.Vl,x:null,y:null}};m.prototype.Ud=function(){return this.ba instanceof a.ue?this.ba.Ud():null};m.prototype.Ga=function(b){this.ba instanceof a.ue&&this.ba.Ga(b)};m.prototype.ra=function(b){this.ba instanceof a.ue&&this.ba.ra(b)};m.prototype.fd=function(){return this.ba instanceof a.ue?this.ba.fd():null};m.prototype.PW=function(){return this.ba instanceof a.vb?this.ba.PW():null};m.prototype.nk=function(b){this.ba instanceof
a.vb&&this.ba.nk(b)};m.prototype.aS=function(b){this.ba instanceof a.Image&&this.ba.aS(b)};m.prototype.contains=function(a,b){var c=this.aa();return a>=c.x&&a<=c.x+c.a&&b>=c.y&&b<=c.y+c.b};m.prototype.uk=function(a){if(!this.Cj&&this.ba&&this.nGa){var b=this.ba.Ud().clone();b.Xa(this.nGa/a.gg);this.ba.Ga(b)}};a.v.D(l,a.v);l.prototype.Init=function(b,c,d){this.Da=b;this.vk=c;this.pha=d;this.Om={};this.ov=new a.Tb};l.prototype.jQa=function(a){this.Om[a.qw()]=a};l.prototype.yCa=function(){};l.prototype.Wia=
function(){};l.prototype.Pxa=function(b,c){this.Xt&&this.Xt.stop(!0);this.ov=c;this.PP=this.Oj(b.qw());this.jQa(b);b.ta(this.ov);b.uk(new a.xd(a.xd.QJ),this.ov);if(this.PP){var d=b.nw(),e=b.ob();if("auto"==d){var f=new a.sq(this.Da.u());f.Io(this.PP.xda(),b.xda());this.Xt=f.nw()}else if(a.pc.isSupported(d)){this.XNa=!0;for(var h=new a.Z(0,0,this.Da.getWidth(),this.Da.getHeight()),k=this.PP.Bua(),f=0;f<k.length;f++){var l=new a.Rect(this.Da.u(),0,0,this.Da.getWidth(),this.Da.getHeight());l.ra(null);
k[f].A(l)}for(var v=b.Bua(),f=0;f<v.length;f++)l=new a.Rect(this.Da.u(),0,0,this.Da.getWidth(),this.Da.getHeight()),l.ra(null),v[f].A(l);h=a.pc.gM(this.Da.u(),d,k,v,h,e);k=new a.Z(0,0,this.Da.getWidth()/this.ov.gg,this.Da.getHeight()/this.ov.gg);v=this.PP.Qua();for(f=0;f<v.length;f++)l=new a.Rect(this.Da.u(),0,0,this.Da.getWidth()/this.ov.gg,this.Da.getHeight()/this.ov.gg),l.ra(null),v[f].A(l);for(var m=b.Qua(),f=0;f<m.length;f++)l=new a.Rect(this.Da.u(),0,0,this.Da.getWidth()/this.ov.gg,this.Da.getHeight()/
this.ov.gg),l.ra(null),m[f].A(l);f=a.pc.gM(this.Da.u(),d,v,m,k,e);this.Xt=new a.Gg(this.Da.u(),[h,f])}else for(d=this.PP.kSa(),f=0;f<d.length;f++)d[f].getParent().removeChild(d[f]);this.yCa();if(this.Xt){this.pha.ll(this.pb);var n=this;this.Xt.lg(function(){n.Uw(b)},this);this.Xt.play()}}else this.Wia(),this.Da.iCa()};l.prototype.Oj=function(a){return this.Om?this.Om[a]:null};l.prototype.ta=function(a){this.ov=a;for(var b in this.Om)this.Om[b].ta(a)};l.prototype.reset=function(a,b){for(var c in this.Om)this.Om[c].reset(a,
b)};l.prototype.uk=function(a,b){this.ov=b;for(var c in this.Om)this.Om[c].uk(a,b)};l.prototype.$C=function(a){this.ov=a;for(var b in this.Om)this.Om[b].$C(a)};l.prototype.Uw=function(a){if(this.PP)for(var b=this.PP.kSa(),c=0;c<b.length;c++){var d=b[c].getParent();d&&d.removeChild(b[c])}if(this.XNa){this.XNa=!1;b=a.Bua();for(c=0;c<b.length;c++)b[c].my(b[c].Rb()-1);a=a.Qua();for(c=0;c<a.length;c++)a[c].my(a[c].Rb()-1)}this.Wia();this.Da.iCa();this.Xt=null;this.pha.Qf(this.pb)};l.prototype.xa=function(){var a=
this.Om,b;for(b in a)a[b].xa()};a.v.D(k,l);k.tFa=0;k.Ika=1;k.prototype.Init=function(b,c,d,e,f){k.C.Init.call(this,b,c,f);this.Bx=d;this.eLa=e;this.f_={};this.wy={};this.QC={};this.fV=this.av=null;this.sr=[];this.HH={};this.KH={};this.Sba={};this.G5=new a.la(this.Da.u());this.qZ=new a.la(this.Da.u());this.Da.mGa.Ib(this.G5,0);this.Da.pH.Ib(this.qZ,0)};k.prototype.gxa=function(a){this.ula=a};k.prototype.nw=function(){return this.ula};k.prototype.IC=function(a){this.tla=a};k.prototype.ob=function(){return this.tla};
k.prototype.eWa=function(a){this.QC=a;for(var b in a)this.Bfa(b,!0)};k.prototype.dWa=function(a){this.av=a;for(var b in a)this.ZX(b,!0)};k.prototype.Kmb=function(a){return this.av&&this.av[a]?this.av[a][k.tFa]:null};k.prototype.Hlb=function(a){return this.av&&this.av[a]?this.av[a][k.Ika]:null};k.prototype.qrb=function(a){this.fV=a};k.prototype.MSa=function(a){return this.fV?this.fV[a]:null};k.prototype.prb=function(a){this.Lp=a};k.prototype.Ota=function(a){return this.Lp[a]?this.Lp[a].split(","):
[]};k.prototype.MRa=function(a){return this.QC[a]};k.prototype.Tda=function(){return this.Bx};k.prototype.fsb=function(a){this.tpa=a};k.prototype.Alb=function(){return new a.j(this.tpa)};k.prototype.Bfa=function(a,b){this.HH[a]=b};k.prototype.ZX=function(a,b){this.KH[a]=b};k.prototype.dsb=function(a){this.aV=a;this.hV=null;for(var b in this.QC)b!=a&&(this.HH[b]=!1)};k.prototype.gR=function(){if(!this.hV)if(this.aV)this.hV=a.P.aa(a.P.T2(B.imb(this.Da.Vp,this.vk,this.aV)));else if("world"!=this.Da.Vp&&
"worldRegions"!=this.Da.Vp&&(this.hV=B.URa(this.Da.Vp,this.vk)),!this.hV){var b=this.G5.aa().wj(this.Da.h$.aa()).wj(this.Da.SG.aa()).wj(this.Da.vP.aa());0<b.a&&0<b.b&&(this.hV=b)}return this.hV};k.prototype.Z9=function(b,c){var d=this.QC[b];if(d){!c&&this.wy[b]||this.ZWa(b);if(!this.wy[b]){var e=this.av&&this.av[b]?this.av[b][k.Ika]:null,f=new m(this.Da.u(),this.Da,d,b,e,this.Da.Cj);this.wy[b]=f;this.pha.lb(d,f);f.mWa(e)}this.KH[b]&&(e=this.f_[b],!e&&"off"!=this.Bx&&this.av&&(e="short"==this.eLa?
this.av[b][k.tFa]:this.av[b][k.Ika]))&&(this.fV&&this.fV[b]?e=new w(this.Da.u(),e,this.fV[b],this.Bx,this.qZ,this.Da.Cj):(d=a.Mh.jn(this.Da.u(),d),e=new w(this.Da.u(),e,[[d.x,d.y,d.a,d.b]],this.Bx,this.qZ,this.Da.Cj)),this.f_[b]=e,this.tpa&&e.Bb(this.tpa))}};k.prototype.G8=function(a,b){if(this.QC[a]){this.G5.A(this.wy[a]);var c=this.f_[a];c&&(this.KH[a]?c.update(this.ov):c.reset(),this.Sba[a]=this.KH[a]);b&&(b.push(this.wy[a]),c&&(b.push(c),b.push(c.Kq)))}};k.prototype.ZWa=function(a){if(!this.qNa||
this.GGa){this.GGa=!1;var b;this.qNa=(b="world"==this.Da.Vp||"worldRegions"==this.Da.Vp?B.URa(this.Da.Vp,this.vk):this.gR())?B.Zsb(B.Ata(this.Da.Vp,this.vk),b.a,b.b,this.Da.getWidth(),this.Da.getHeight(),this.Da.fTa()):B.Ata(this.Da.Vp,this.vk)}b=this.qNa[a];this.QC[a]&&b?this.QC[a].nk(b):delete this.QC[a]};k.prototype.Vqb=function(){for(var a in this.av)this.Bfa(a,!0),this.ZX(a,!0)};k.prototype.Pxa=function(a,b,c){k.C.Pxa.call(this,a,b,c);if(c==this.vk)for(var d in this.QC)this.Z9(d,!0),this.HH[d]&&
this.G8(d)};k.prototype.ta=function(a){this.GGa=!0;for(var b in this.QC)this.Z9(b,!0),this.HH[b]&&this.G8(b);k.C.ta.call(this,a)};k.prototype.yCa=function(){for(var a in this.HH)this.HH[a]||(this.Z9(a,!1),this.G8(a))};k.prototype.Wia=function(){for(var a in this.HH)if(!this.HH[a]){this.G5.removeChild(this.wy[a]);var b=this.f_[a];b&&(this.Sba[a]=!1,this.qZ.removeChild(b),(b=b.Kq)&&this.qZ.removeChild(b))}};k.prototype.ofb=function(a,b){for(var c=0;c<a.length;c++)this.Z9(a[c],!1),this.HH[a[c]]&&this.G8(a[c],
b)};k.prototype.jta=function(a,b){this.ofb(a,b);for(var c in this.Om)this.Om[c].jta(a,b,this.ov);this.sr=this.sr.concat(a)};k.prototype.B5=function(b,c){for(var d in this.Om)this.Om[d].B5(b,c);d=this.Da.Yta(this.vk);for(var e=0;e<b.length;e++){var f=b[e];if(this.wy[f]){var h=a.na.kb(this.sr,f);-1!==h&&(this.sr.splice(h,1),c.push(this.wy[f]))}d&&d.B5(this.Ota(f),c)}};k.prototype.reset=function(a,b){k.C.reset.call(this,a,b);"none"!=this.Da.tr&&(this.B5(this.sr,a),this.sr=[])};k.prototype.uk=function(a,
b){k.C.uk.call(this,a,b);if(!this.Da.Cj)for(var c in this.wy)this.wy[c].uk(b);for(c in this.Sba)if(this.Sba[c]){var d=this.f_[c];d&&d.update(b)}};a.v.D(h,k);h.prototype.Init=function(a,b,c,d,e){h.C.Init.call(this,a,b,c,d,e)};h.prototype.ZWa=function(){};h.prototype.gR=function(){return new a.Z(0,0,this.scb,this.rcb)};h.prototype.DOa=function(){for(var a=this.Da.getWidth(),b=this.Da.getHeight(),c=this.t7a,d=0;d<c.length;d++){var e=c[d],f=e.source,h=e.width,e=e.height;if(f&&-1<f.search(".svg")||h>=
a&&e>=b||d==c.length-1)return f}};h.prototype.srb=function(b){var c=null,d=a.B.da(this.Da.u());if(b&&0<b.length){var c=b[0].width,e=b[0].height;this.scb=c;this.rcb=e;for(var f=[],h=0;h<b.length;h++)d&&"rtl"==b[h].dir?f.push(b[h]):d||"ltr"!=b[h].dir||f.push(b[h]);this.t7a=0<f.length?f:b;this.kaa=this.DOa();c=new a.Image(this.Da.u(),this.kaa,0,0,c,e)}c&&(this.dWa({image:[null,null]}),this.eWa({image:c}))};h.prototype.uk=function(a,b){h.C.uk.call(this,a,b);if(this.wy.image){var c=this.DOa();c!=this.kaa&&
(this.kaa=c,this.wy.image.aS(this.kaa))}};a.v.D(f,a.v);f.prototype.Init=function(b,c,d,e,f){this.Da=b;this.hHa=d;this.Nf=f;this.Ye=[];this.Wp=[];this.wP=[];this.g$=[];this.n$=[];this.l$=[];this.mz=e;this.R0={};this.Xj=new a.Df(b.u());this.mz.WR(this.Xj);this.Fv=new a.la(this.Da.u());this.RG=new a.la(this.Da.u());this.j$=new a.la(this.Da.u());this.m$=new a.la(this.Da.u());this.Da.h$.Ib(this.Fv,0);this.Da.SG.Ib(this.RG,0);this.Da.pH.Ib(this.j$,0);this.Da.vP.Ib(this.m$,0);this.P1=c;this.sr=[];this.fu=
[]};f.prototype.F=function(){return this.Nf};f.prototype.kSa=function(){return[this.Fv,this.RG,this.j$,this.m$]};f.prototype.Qua=function(){return[this.Fv]};f.prototype.Bua=function(){var a=[this.j$,this.m$];this.Da.mH&&a.push(this.RG);return a};f.prototype.xda=function(){return this.Wp.concat(this.Ye).concat(this.wP)};f.prototype.Qlb=function(){for(var a=[],b=0;b<this.Ye.length;b++)this.Ye[b].wC()||a.push(this.Ye[b]);return a};f.prototype.Rlb=function(){for(var a=[],b=0;b<this.Ye.length;b++)for(var c=
0;c<this.sr.length;c++)this.Ye[b].mn()==this.sr[c]&&(this.Ye[b].wC()||a.push(this.Ye[b]));return a};f.prototype.Qca=function(a){this.n$.push(a);if(a){this.Wp.push(a);this.mz.lb(a.Sa(),a);var b=a.ge();b&&this.mz.lb(b,a)}};f.prototype.Esa=function(a){this.g$.push(a);a&&(this.Ye.push(a),this.mz.lb(a.Sa(),a),a.rrb(this.Fv))};f.prototype.lhb=function(a){this.l$.push(a);a&&(this.wP.push(a),this.mz.lb(a.Sa(),a))};f.prototype.jtb=function(a,b){var c=f.nab(a,b);this.R0[c]?this.R0[c]++:this.R0[c]=1;return this.R0[c]};
f.nab=function(a,b){return a.x<b.x?a.x.toString()+a.y.toString()+b.x.toString()+b.y.toString():b.x.toString()+b.y.toString()+a.x.toString()+a.y.toString()};f.prototype.leb=function(a){a=this.Ye.indexOf(a);-1!==a&&this.Ye.splice(a,1)};f.prototype.qw=function(){return this.hHa};f.prototype.gxa=function(a){this.ula=a};f.prototype.nw=function(){return this.ula};f.prototype.IC=function(a){this.tla=a};f.prototype.ob=function(){return this.tla};f.prototype.py=function(b){if(this.dw=b)this.Yc=new a.Rc(this.dw),
this.mz.zA(this.hHa,this.Yc)};f.prototype.tb=function(){return null!=this.dw};f.prototype.zgb=function(a){var b=a.Sa(),c=this.P1.MRa(a.mn());if(c)return b.nk(c.PW()),!0;this.leb(a);return!1};f.prototype.aOa=function(a){if(this.zgb(this.Ye[a])){var b=this.Ye[a].Sa();this.Fv.A(b);if(a=this.Ye[a].ge())a.Mnb()||(b=b.aa(),a.Xgb(b)),a.update(this.FV);return!0}return!1};f.prototype.ta=function(b){this.zGa=!0;this.FV=b;b={};var c=this.Wp.slice();c.sort(function(a,b){return a.pe()<b.pe()?1:a.pe()>b.pe()?-1:
0});for(var d=0;d<c.length;d++){var e=c[d],f=e.Sa(),h=e.ge();if(h){var k=new a.la(f.u());this.RG.A(k);k.A(f);k.A(h);e.jfa()}else this.RG.A(f);(e=e.mn())&&(b[e]=!0)}for(d=0;d<this.Ye.length;d++)b[this.Ye[d].mn()]&&this.Ye[d].Aqb(),this.aOa(d)||d--;for(d=0;d<this.wP.length;d++)this.m$.A(this.wP[d].Sa());this.Poa&&this.NB()};f.prototype.jta=function(a,b,c){this.FV=c;for(var d=[],e=0;e<a.length;e++)for(var f=0;f<this.Ye.length;f++)if(this.Ye[f].mn()==a[e]){d.push(this.Ye[f].mn());this.aOa(f);var h=this.Ye[f].Sa();
b.push(h);h.dUa(c);if(f=this.Ye[f].ge())b.push(f),(f=f.Kq)&&b.push(f);break}for(f=0;f<this.Wp.length;f++)for(e=0;e<a.length;e++)c=this.Wp[f].mn(),h=this.Wp[f].Sa(),null!=c?c==a[e]&&(this.RG.A(h),b.push(h)):(this.RG.A(h),b.push(h));this.sr=this.sr.concat(d)};f.prototype.B5=function(b,c){for(var d=0;d<b.length;d++)for(var e=0;e<this.Ye.length;e++)if(this.Ye[e].mn()==b[d]){this.Ye[e].wC()&&this.Ye[e].WX(!1);this.Ye[e].wb()&&this.Yc.S4(this.Ye[e]);var f=a.na.kb(this.sr,b[d]);-1<f&&(this.sr.splice(f,1),
c.push(this.Ye[e].Sa()),e=this.Ye[e].ge())&&(c.push(e),c.push(e.Kq));break}};f.prototype.djb=function(a,b){for(var c=0;c<this.Ye.length;c++)if(this.Ye[c].mn()==a){this.Ye[c].WX(!0);this.fu.push(a);b.push(this.Ye[c].Sa());if(c=this.Ye[c].ge())b.push(c),(c=c.Kq)&&b.push(c);break}for(c=0;c<this.Wp.length;c++)if(this.Wp[c].mn()==a){b.push(this.Wp[c].Sa());break}};f.prototype.ntb=function(b,c){for(var d=0;d<this.Ye.length;d++)if(this.Ye[d].mn()==b){var e=a.na.kb(this.fu,b);this.fu.splice(e,1);this.Ye[d].WX(!1);
e=this.Ye[d].Sa();this.Fv.A(e);c.push(e);if(d=this.Ye[d].ge())d.update(this.FV),c.push(d),c.push(d.Kq);break}for(d=0;d<this.Wp.length;d++)if(this.Wp[d].mn()==b){e=this.Wp[d].Sa();this.RG.A(e);c.push(e);break}};f.prototype.reset=function(b,c){if(this.Yc)for(var d=this.Yc.getSelection(),e=0;e<d.length;e++)(!c||c&&-1==a.na.kb(c,d[e].mn()))&&this.Yc.S4(d[e]);if("none"!=this.Da.tr)for(d=0;d<this.fu.length;d++){for(e=0;e<this.Ye.length;e++)if(this.Ye[e].mn()==this.fu[d]){this.Ye[e].WX(!1);var f=this.Ye[e].Sa();
this.Fv.A(f);b.push(f);if(e=this.Ye[e].ge())e.update(this.FV),b.push(e),b.push(e.Kq);break}for(e=0;e<this.Wp.length;e++)if(this.Wp[e].mn()==this.fu[d]){f=this.Wp[e].Sa();this.RG.A(f);b.push(f);break}}this.fu=[]};f.prototype.uk=function(b,c){this.FV=c;var d=c.gg,e=b.Zn();if(this.zGa&&e==a.xd.QJ)for(this.zGa=!1,e=0;e<this.Ye.length;e++){var f=this.Ye[e].Sa(),h=f.feb;if(h){var k=new a.wc;h.dh(k);k.rb(new a.Tb(1/d,null,null,1/d));f.ra(k)}}e=this.Ye;for(d=0;d<e.length;d++)e[d].uk(c);if(this.Da.mH)for(e=
this.Wp,d=0;d<e.length;d++)e[d].uk(c);this.R0={};e=this.wP;for(d=0;d<e.length;d++)e[d].uk(c)};f.prototype.$C=function(a){this.FV=a};f.prototype.bsb=function(a){this.Poa=a};f.prototype.NB=function(){this.Yc&&(this.Yc.tt(this.Poa,this.xda()),this.Poa=null)};f.prototype.hK=function(a){if(this.Yc){a.wb()||(this.Yc.oq(a,!1),this.mz.gI(a));a=[];for(var b=this.Yc.getSelection(),c=0;c<b.length;c++)a.push(b[c].getId());return a}return null};f.prototype.gK=function(){for(var a=[],b=this.Yc.getSelection(),c=
0;c<b.length;c++)a.push(b[c].Sa());return a};f.prototype.Bmb=function(a){for(var b=[],c=this.Ye,d=0;d<a.length;d++)for(var e=0;e<c.length;e++)if(c[e].getId()==a[d]){b.push(c[e].mn());break}return b};f.prototype.xa=function(){for(var a=this.xda(),b=0;b<a.length;b++){var c=a[b].Sa();c instanceof v&&(c=c.MD,c.xa&&c.xa())}this.mz=null};f.prototype.XE=function(a){for(var b=[],c=0;c<this.l$.length;c++){var d=this.l$[c],e=d.rca,f=d.una;e&&e.getId()===a?b.push(d):f&&f.getId()===a&&b.push(d)}return b};a.v.D(e,
a.QN);e.DBa="linkNode";e.qia="link";e.prototype.Init=function(a,b){e.C.Init.call(this,a,b);this.Da=a;this.Maa=e.qia};e.prototype.iF=function(a){return this.Vi(a)&&!a.ctrlKey};e.prototype.mk=function(b){var c=b.keyCode,d=this.yb.jf();if(c==a.KeyboardEvent.cv){this.Maa=e.qia;c=[];d instanceof r&&(c=this.Da.iR());if("DvtMapObjPeer"===d.getTypeName()||0===c.length)c=this.Da.R3();0<c.length&&(d=a.Cb.YE(d,b,c));this.yb.YN(d)}else if(c==a.KeyboardEvent.Tw){this.Maa=e.qia;c=[];d instanceof n&&(c=this.Da.iR());
if("DvtMapObjPeer"===d.getTypeName()||0===c.length)c=this.Da.Q3();0<c.length&&(d=a.Cb.YE(d,b,c));this.yb.YN(d)}else(b.keyCode==a.KeyboardEvent.TA||a.KeyboardEvent.FA)&&b.altKey&&(this.BLa=d,this.Maa=e.DBa),d=e.C.mk.call(this,b),this.Vi(b)&&!b.ctrlKey&&this.yb.YN(d);return d};e.prototype.Nu=function(b){return b.keyCode==a.KeyboardEvent.ni&&b.ctrlKey};e.prototype.Vi=function(b){var c=e.C.Vi.call(this,b);switch(b.keyCode){case a.KeyboardEvent.Tw:case a.KeyboardEvent.cv:c=!0;break;case a.KeyboardEvent.TA:case a.KeyboardEvent.FA:c=
b.altKey?!0:!1;break;default:c=e.C.Vi.call(this,b)}return c};e.TW=function(b,c,d){c=c.keyCode;if(!d||1>d.length||!b)return null;for(var e=b.ye(),f=0;f<d.length;f++){var h=d[f],k;k=b.getId()===h.rca.getId()?h.LK:h.SL;if(c==a.KeyboardEvent.TA&&k.x<=e.x||c==a.KeyboardEvent.FA&&k.x>=e.x)break}return h};a.v.D(d,a.I);d.prototype.Init=function(a,b,c){d.C.Init.call(this,a,b,c);this.QH={};this.Da=c;this.CD=!1};d.prototype.Xh=function(a){if(a&&a.Oj)return this.QH[a.Oj().qw()]};d.prototype.zA=function(a,b){this.QH[a]=
b};d.prototype.qxa=function(a){this.tr=a};d.prototype.S4=function(a,b){var c=this.QH[a];c&&c.S4(b)};d.prototype.EW=function(a){(a=this.QH[a])&&a.EW()};d.prototype.asb=function(a){a&&d.C.Fw.call(this,a)};d.prototype.My=function(a){var b=this.mb(a.target);b&&b.zf&&b.Oj&&this.Da.XR(b.Oj().qw());d.C.My.call(this,a)};d.prototype.To=function(a){this.Da.XR(null);d.C.To.call(this,a)};d.prototype.Tj=function(b){var c=this.mb(b.target);this.YN(c);if(!(c&&c.tb&&c.tb()))for(var e in this.QH)if(this.QH[e].oq(null,
b.ctrlKey)){var f=a.Za.G4([]);f.clientId=e;this.Cc.call(this.pb,f)}d.C.Tj.call(this,b);this.aaa(c,b.pageX,b.pageY)};d.prototype.aaa=function(a,b,c){if(a instanceof p){var d=a.uM();d?d.call():a.fUa()?this.CAa(a,b,c):a.zf()&&this.Da.XR(a.Oj().qw())}};d.prototype.CAa=function(b,c,d){var e=new a.XS(b.qw(),b.getId(),b.Ch());e.dl("clientId",b.Oj().qw());null!=c&&null!=d&&(b=this.Da.u().eh(c,d),e.dl("pointXY",{x:b.x,y:b.y}));this.qe();this.Cc.call(this.pb,e)};d.prototype.YN=function(a){var b=null,c=null,
d=null;a&&(a instanceof p?d=a.Sa():a instanceof m&&(d=a),a.Oj&&(a=a.Oj(),b=a.qw(),c=a.P1.vk));this.Da.yrb(b,c,d)};d.prototype.aG=function(b){b=this.mb(b.target);this.Xh(b)&&this.tr&&"none"!=this.tr&&(b=new a.Nt(a.Nt.iha),this.Cc.call(this.pb,b))};d.prototype.ol=function(b){var c=!0,e=b.keyCode,f=this.jf(),h=f.Sa();e!=a.KeyboardEvent.Qh&&this.CD?(h.JW(b),b.preventDefault()):(e==a.KeyboardEvent.ZERO||e==a.KeyboardEvent.l7)&&b.ctrlKey&&b.shiftKey?(this.Da.$wa(),b.preventDefault()):e==a.KeyboardEvent.tXa?
((f=this.Da.$e)&&(f instanceof a.Fc?f.jxa(!f.isCollapsed()):f instanceof a.ea&&f.Di(!f.Ab())),b.preventDefault()):e==a.KeyboardEvent.Zi?f instanceof p&&((e=f.uM())?e.call():f.fUa()?this.CAa(f):b.shiftKey?this.Da.mta():this.Da.lda(),b.preventDefault()):e==a.KeyboardEvent.ni&&b.ctrlKey?(this.YN(f),this.GJ(f,!0),b.preventDefault()):e!=a.KeyboardEvent.ZERO&&e!=a.KeyboardEvent.l7||!b.ctrlKey?e==a.KeyboardEvent.Qh&&h instanceof v?!b.shiftKey&&f.Kd()?(f.Qd(),h.JW(b),b.preventDefault(),this.CD=!0):(b.shiftKey&&
this.CD?(this.mT(b,f),b.preventDefault()):(this.CD&&f.Sf(),c=d.C.ol.call(this,b)),this.CD=!1):c=d.C.ol.call(this,b):(b.altKey?this.Da.Djb(h):this.Da.sta(),b.preventDefault());return c};d.prototype.CJ=function(b){if(!this.io(b,a.Sd.wN)){var c=this.mb(b.target);this.YN(c);if(c instanceof a.$a)for(var e in this.QH)if(this.QH[e].oq(null,b.ctrlKey)){for(var f=this.QH[e].getSelection(),h=[],k=0;k<f.length;k++)h.push(f[k].getId());f=a.Za.G4(h);this.Cc.call(this.pb,f)}d.C.CJ.call(this,b);this.aaa(c,b.Bt.pageX,
b.Bt.pageY)}};d.prototype.cia=function(a){(a=this.mb(a.target))&&a.zf&&a.Oj?this.Da.XR(a.Oj().qw()):this.Da.XR(null)};d.prototype.cBa=function(a){(a=this.mb(a.target))&&a.zf&&a.Oj?this.Da.XR(a.Oj().qw()):this.Da.XR(null)};d.prototype.wJ=function(b){var c=this.mb(b.target);c&&this.Xh(c)&&this.tr&&"none"!=this.tr&&(this.GJ(c,b.ctrlKey),b=new a.Nt(a.Nt.iha),this.Cc.call(this.pb,b))};d.prototype.X6=function(a,b){var c=this.mb(a.target);this.YN(c);d.C.X6.call(this,a,b)};d.prototype.uq=function(b,c,d){b=
this.Da.F();"dim"==b.hoverBehavior&&(c=c.Xd?c.Xd():[],b.highlightedCategories=d?c.slice():null,d=a.Za.GI(b.highlightedCategories,d),c=a.Ta.Pr(b.styleDefaults.hoverBehaviorDelay),this.KJ.bg(d,this.Da.Q3().concat(this.Da.iR()).concat(this.Da.R3()),c,"any"==b.highlightMatch))};d.prototype.LA=function(){var b=this.Da.F();return"none"!==b.panning||"none"!==b.zooming?a.I.jG:b.touchResponse===a.I.Qy?a.I.Qy:a.I.QZ};d.prototype.hD=function(b){return b==a.Sd.wN?!1:d.C.hD.call(this,b)};a.v.D(c,a.v);c.S4a=6;
c.L4a=.5;c.g5a=20;c.prototype.Init=function(a){this.Da=a;this.uaa=!1;this.g_=this.tO=null;this.YHa={}};c.prototype.parse=function(b){this.zdb(b);b._legend&&this.Da.wWa(b._legend);this.Adb(b.styleDefaults);if(this.uaa&&b.sourceXml){var c=(new a.fO(this.Da.u())).parse(b.sourceXml);this.wdb(c)}this.tdb(b.areaLayers);this.q7(b.pointDataLayers,null,null,!1)};c.prototype.zdb=function(a){var b=a.animationDuration;"string"==typeof b?"ms"==b.slice(-2)?b=parseInt(b.slice(0,-2))/1E3:"s"==b.slice(-1)&&(b=parseFloat(b.slice(0,
-1))):b/=1E3;this.Da.IC(b);this.Da.mrb("auto"==a.animationOnDisplay?"alphaFade":a.animationOnDisplay);this.Da.orb("auto"==a.animationOnMapChange?"alphaFade":a.animationOnMapChange);this.uaa=null!=a.source;this.Da.isb(this.uaa?"$"+a.basemap:a.basemap);this.Da.Nfa(a.featuresOff);this.Da.Ifa(a.controlPanelBehavior);b=a.tooltipDisplay;"shortDesc"==b?b="shortDescOnly":"labelAndShortDesc"==b&&(b="auto");this.Da.Orb(b);(b=a.popups)&&this.Da.lY(this.Hq(b));this.Da.qxa(a.drilling);this.Da.nrb(a.animationOnDrill);
this.Da.csb("auto"==a.initialZooming);this.Da.jsb(a.markerZoomBehavior);this.Da.EWa("auto"==a.panning);this.Da.MWa("auto"==a.zooming);this.Da.rWa(a.panX);this.Da.sWa(a.panY);this.Da.tWa(a.zoom);isNaN(a.maxZoom)||this.Da.lsb(Math.max(a.maxZoom,1))};c.prototype.tdb=function(b){for(var d=this.Da.Vp,e=0;e<b.length;e++){var f=this.Da.Xg.Qhb(b[e]),l=f.layer;if(l){var v;if(v=f.areaStyle){v instanceof Object||(v=a.j.OQ(v));var m=c.$Ia(v);this.g_=a.ac.Vd(v,this.g_);this.tO.Vd(m)}f.labelStyle&&this.tO.lj(f.labelStyle);
this.uaa?(v=new h(this.Da,l,f.labelDisplay,f.labelType,this.Da.ab()),v.srb(this.YHa[l])):(v=new k(this.Da,l,f.labelDisplay,f.labelType,this.Da.ab()),v.eWa(this.c9a(B.LRa(d,l))),v.dWa(B.Pjb(d,l)),v.qrb(B.Ojb(d,l)),v.prb(B.nkb(this.Da.Vp,l)));v.fsb(this.tO);v.gxa("auto"==f.animationOnLayerChange?"alphaFade":f.animationOnLayerChange);v.IC(this.Da.ob());this.Da.khb(v);f.areaDataLayer&&this.q7([f.areaDataLayer],v,null,!0);f.pointDataLayers&&this.q7(f.pointDataLayers,v,null,!1)}}};c.prototype.q7=function(b,
d,e,h){if(b)for(var v=0;v<b.length;v++){var m=this.Da.Xg.Uhb(b[v]);m.legend&&this.Da.wWa(m.legend);d?d instanceof k&&h&&d.Vqb():(d=new l(this.Da,m.id,this.Da.ab()),this.Da.qhb(d));var n=new f(this.Da,d,m.id,this.Da.ab(),m);h=m.selectionMode;"single"==h?n.py(a.Rc.Sy):"multiple"==h&&n.py(a.Rc.Ry);n.gxa(m.animationOnDataChange);n.IC(this.Da.ob());var p=null;d instanceof k&&(p=m.isolatedItem);var u=m.disclosedItems,r=[],A;h=d instanceof k;var D;m.popups&&(D=this.Hq(m.popups));var w=this.Da.F().hiddenCategories,
B=m.areas;if(B)for(var C=0;C<B.length;C++)if(w&&a.na.yw(w,B[C].categories))n.Esa(null);else{var x=B[C].location;if(p)if(p!=B[C].id)continue;else A=x;u&&-1!=a.na.kb(u,B[C].id)&&r.push(x);if(x=this.K8a(d,n,B[C]))D&&x.lY(D),n.Esa(x)}var B=m.renderer,X=m.markers;if(X&&!B)for(c.Y7a(this.Da,X),C=0;C<X.length;C++)if(w&&a.na.yw(w,X[C].categories))n.Qca(null);else{x=X[C].location;if(p)if(p!=X[C].id)continue;else A=x;if(x=this.fz(d,n,X[C],h))D&&x.lY(D),n.Qca(x)}var U=m.images;if(U)for(C=0;C<U.length;C++){x=
U[C].location;if(p)if(p!=U[C].id)continue;else A=x;if(x=this.Ema(d,n,U[C],h))D&&x.lY(D),n.Qca(x)}if(U=m.links)for(C=0;C<U.length;C++)w&&a.na.yw(w,U[C].categories)?n.Esa(null):(x=this.$8a(n,U[C]))&&n.lhb(x);if(B)for(C=0;C<X.length;C++){x=X[C].location;if(p)if(p!=X[C].id)continue;else A=x;u&&-1!=a.na.kb(u,X[C].id)&&r.push(x);w=this.Da.F()._contextHandler(this.Da.Ua(),null,X[C],{hovered:!1,selected:!1,focused:!1},null);w=B(w);x=this.P8a(d,n,X[C],w,h);D&&x.lY(D);x&&n.Qca(x)}A&&d.dsb(A);(m=m.selection)&&
0<m.length&&n.bsb(m);r&&0<r.length&&this.Da.ghb(d.vk,[n.qw(),r]);e?d.Pxa(n,this.Da.Qa.Oa.sb(),e):d.jQa(n)}};c.prototype.Adb=function(b){this.Da.wwa(b);var d=b.areaStyle;!d||d instanceof Object||(d=a.j.OQ(d));d=a.ac.Vd(d,b._areaStyle);this.tO=c.$Ia(d);this.g_=d;this.tO.lj(b.labelStyle);new a.j(b.dropTargetStyle);this.Da.Osb(b)};c.$Ia=function(b){var c=new a.j;a.na.forEach([a.j.ub,a.j.Lb],function(d){var e=null,f=a.j.bM(d);b&&null!=b[f]&&(e=b[f],delete b[f]);c.fa(d,e)});return c};c.prototype.wdb=function(a){a=
a.ze();for(var b,c,d=0;d<a.length;d++)b=a[d],c=b.getName(),"layer"==c?this.xdb(b):"points"==c&&this.ydb(b)};c.prototype.xdb=function(a){var b=a.ze();a=a.X("id");for(var c,d,e=[],f=0;f<b.length;f++)if(c=b[f],d=c.getName(),"image"==d){d={};d.source=c.X("source");d.width=Number(c.X("width"));d.height=Number(c.X("height"));var h=c.X("bidi");c=c.X("dir");d.dir="true"==h||"rtl"==c?"rtl":"ltr";e.push(d)}this.YHa[a]=e};c.prototype.ydb=function(a){a=a.ze();for(var b,c,d={},e={},f=0;f<a.length;f++)b=a[f],c=
b.getName(),"point"==c&&(d[b.X("name")]=[Number(b.X("x")),Number(b.X("y"))],e[b.X("name")]=[null,b.X("longLabel")]);B.NVa(this.Da.Vp,"cities",e,d,null,null,1)};c.prototype.c9a=function(b){for(var c={},d=this.Da.u(),e=0;e<b.length;e++){var f=b[e];c[f]=new a.vb(d);var h=this.tO.M(a.j.ub);h&&"transparent"!=h&&(h=new a.ya(h),this.Da.Cj&&h.If(!0),c[f].Ga(h));h=this.tO.M(a.j.Lb);"transparent"!=h?c[f].fb(h):c[f].ra(null);this.g_&&c[f].fa(this.g_)}return c};c.prototype.K8a=function(b,c,d){var e=d.location;
if(b.MRa(e)){b.Bfa(e,!1);e=new A(this.Da.u(),this.Da.Cj);d=a.ac.Vd(d,this.Da.w2.dataAreaDefaults);d.labelStyle||(d.labelStyle=this.Da.w2.labelStyle);var f=new a.ya(d.hoverColor,1,A.vJ),h=new a.ya(d.selectedInnerColor,1,A.y7),k=new a.ya(d.selectedOuterColor,1,A.z7);e.xt(f,null).At(h,k);f=new a.ya(d.drilledInnerColor,1,A.fha);h=new a.ya(d.drilledOuterColor,1,A.gha);e.Nrb(f,h);b.ZX(d.location,!1);this.jPa(d,e);b=this.HO(b,c,d,e,!0);return new r(d,c,e,b)}return null};c.prototype.fz=function(b,d,e,f){var h=
e._size,k;k=(k=this.Da.F().mapProvider)&&null!=k.geo?new a.R(e.x,-e.y):c.ye(d,e.location,e.x,e.y);if(!k||0===h)return null;var l=this.Da.w2.dataMarkerDefaults,v=new a.j(l.labelStyle);v.lj(e.labelStyle);e=a.ac.Vd(e,l);e.labelStyle=v.toString();if(null!=h)l=h;else{l=e.scaleX;null==l&&(l=1);h=e.scaleY;null==h&&(h=1);var m=e.width;null==m&&(m=this.Da.F().styleDefaults.dataMarkerDefaults.width);v=e.height;null==v&&(v=this.Da.F().styleDefaults.dataMarkerDefaults.height);l*=m;h*=v}v=e.borderRadius;e.source?
l=new a.Ef(this.Da.u(),k.x,k.y,l,h,v,e.source,e.sourceSelected,e.sourceHover,e.sourceHoverSelected):(m=e.shape?e.shape:this.Da.F().styleDefaults.dataMarkerDefaults.shape,l=new a.za(this.Da.u(),m,this.Da.ke,k.x,k.y,l,h,v));(h=e.rotation)&&l.zp(h*Math.PI/180);f&&b.ZX(e.location,!1);this.jPa(e,l);b=this.HO(b,d,e,l,f);return new p(e,d,l,b,k)};c.prototype.Ema=function(b,d,e,f){var h=c.ye(d,e.location,e.x,e.y);if(!h)return null;var k=new a.Image(this.Da.u(),e.url),l=e.width,v=e.height;null!=l&&null!=v&&
(k.Fa(h.x-l/2),k.jb(h.y-v/2),k.Xa(l),k.qb(v));f&&b.ZX(e.location,!1);var m=new p(e,d,k,null,h);l&&v||a.js.Ur(this.Da.u(),e.url,function(a){a&&a.width&&a.height&&(k.Xa(a.width),k.qb(a.height),k.Fa(h.x-a.width/2),k.jb(h.y-a.height/2),m.$Z())});return m};c.prototype.P8a=function(a,b,d,e,f){var h=c.ye(b,d.location,d.x,d.y);if(!h)return null;f&&a.ZX(d.location,!1);a=new v(this.Da.u(),e,this.Da.w2.dataAreaDefaults);return new p(d,b,a,null,h)};c.prototype.$8a=function(b,d){var e=d.startLocation,f=d.endLocation,
h,k;if(e.id){for(var l=b.n$,v=0;v<l.length;v++){var m=l[v];if(m&&m.getId()==e.id){k=m;h=m.ye();break}}if(!k)for(l=b.g$,v=0;v<l.length;v++)if((m=l[v])&&m.getId()==e.id){k=m;h=this.U$(b,{location:m.mn()});break}}else h=this.U$(b,e);var p,u;if(f.id){l=b.n$;for(v=0;v<l.length;v++)if((m=l[v])&&m.getId()==f.id){u=m;p=m.ye();break}if(!u)for(l=b.g$,v=0;v<l.length;v++)if((m=l[v])&&m.getId()==f.id){u=m;p=this.U$(b,{location:m.mn()});break}}else p=this.U$(b,f);if(!p||!h)return null;e=new a.vb(this.Da.u(),c.EQa(b,
h,p,h,p));e.ra(null);var v=this.Da.w2.linkDefaults,r=d.color;r||(r=v.color);(f=d.width)||(f=v.width);l=new a.ya(r,1,f);l.If(!0);e.Ga(l);var m=v._hoverColor,A=v._selectedColor,v=new a.ya(m,1,f),l=new a.ya(r,1,f+2),r=new a.ya(r,1,f),D=new a.ya(A,1,f+2),m=new a.ya(m,1,f),f=new a.ya(A,1,f+2);e.xt(v,l).At(r,D).Uu(m,f);return new n(d,b,e,h,p,k,u)};c.prototype.U$=function(b,d){var e=this.Da.F().mapProvider;return e&&null!=e.geo?new a.R(d.x,-d.y):c.ye(b,d.location,d.x,d.y)};c.prototype.HO=function(b,c,d,
e,f){var h=d.location,k=d.label,l=k?"on":"off";f&&(l=b.Tda());e=e instanceof a.vb;!k&&f&&(e&&"off"!=l||!e&&"on"==l)&&(k="long"==b.eLa?b.Hlb(h):b.Kmb(h));if(k){var v=this.Da.u(),v=e?new w(v,k,b.MSa?b.MSa(h):null,l,c.j$,this.Da.Cj):new a.ca(v,k,0,0);c=new a.j;e&&c.Vd(b.Alb());d.labelStyle&&c.lj(d.labelStyle);b=c.M(a.j.mc);c.fa(a.j.mc,null);v.Bb(c);d.color&&v instanceof w&&(a.B.GM()||!b)&&(b=a.O.Wl(d.color));b&&v.fb(b)}return v};c.prototype.jPa=function(b,c){var d=b.pattern,e=b.color,f=a.B.Wa()||this.Da.ke==
a.j.mf?"none":b.visualEffects;if(c instanceof a.za){if("none"!=b.borderStyle){var h=b.borderWidth;"string"==typeof h&&(h="px"==h.slice(-2)?parseFloat(b.borderWidth.slice(0,-2)):parseFloat(b.borderWidth));var k=new a.ya(b.borderColor,1,h);this.Da.mH||k.If(!0);k.bo(a.Xc.Qx(b.borderStyle));c.Ga(k)}h=b.opacity;"none"!=f?c.ra(new a.g7.fRa(e,c,h)):d?c.ra(new a.wc(d,e,"#FFFFFF")):e&&c.fb(e,h)}else if(c instanceof a.vb){if(f=b.borderColor)k=new a.ya(f),this.Da.Cj&&k.If(!0),c.Ga(k);d?c.crb(new a.wc(d,e,"#FFFFFF")):
c.fb(e,h)}};c.ye=function(a,b,c,d){var e=a.Da.Vp;return b?((a=B.Mjb(e,a.P1.vk,b))||(a=B.okb(e,b)),a):C.lqb(c,d,e)};c.prototype.Hq=function(b){for(var c=[],d=0;d<b.length;d++)c.push(new a.Vc(b[d].popupId,b[d].triggerType,null,b[d].align));return c};c.Y7a=function(b,d){for(var e=-Infinity,f=Infinity,h=0;h<d.length;h++){var k=d[h].value;null==k||0>=k||(e=Math.max(e,k),f=Math.min(f,k))}if(Infinity!==f){var k=2*c.g5a,h=b.getWidth()-k,k=b.getHeight()-k,l=h/k;1.3>l?k=2*h/3:1.7<l&&(h=1.5*k);l=c.L4a*Math.min(h,
k);for(h=0;h<d.length;h++)k=d[h].value,d[h]._size=null==k||0>=k?0:a.Dn.$Ra(k,f,e,c.S4a,l)}};c.EQa=function(b,c,d,e,f){var h=e.x,k=e.y;e=f.x;f=f.y;var l=b.Da,v=a.P.moveTo(h,k);c=b.jtb(c,d);d=Math.min(l.getWidth(),l.getHeight())/35;if(0===e-h||0===f-k){var m;1<c?(d*=c-1,0===e-h?(l=.3*Math.abs(k-f),b=h+d,c=k>f?k-l:k+l,m=b,h=f>k?f-l:f+l):(l=.3*Math.abs(h-e),b=h>e?h-l:h+l,c=k-d,m=e>h?e-l:e+l,h=c),v+=a.P.mRa(b,c,m,h,e,f)):v+=a.P.lineTo(e,f)}else{l=Math.sqrt(Math.pow(e-h,2),Math.pow(f-k,2));b=l/4;1<c&&(b+=
(c-1)*d);c=(f-k)/(e-h);d=-1/c;0<d&&(b*=-1);m=.3*l/Math.sqrt(1+Math.pow(c,2));var n=0<e-h,l=h+(n?1:-1)*m,n=e+(n?-1:1)*m;m=b/Math.sqrt(1+Math.pow(d,2));b=l+m;m=n+m;v+=a.P.mRa(b,d*(b-l)+(c*(l-h)+k),m,d*(m-n)+(c*(n-e)+f),e,f)}return v};var C={};a.v.D(C,a.v);C.ix=new a.Z(0,0,800,500);C.kO=6378206.4;C.Mka=new a.Z(500,200,200,200);C.Lka=new a.Z(163,-49,17,17);C.hEa=new a.Z(-17.379205428479874,-37.201510854305546,68.66391442808313,77.50071544582713);C.kEa=new a.Z(-.8436866097568272,-.7626456732012923,1.8336308036296942,
1.5748427214611724);C.uEa=new a.Z(113.29667079927977,-52.89550592498755,65.25257389065216,42.123114617504626);C.JEa=new a.Z(-.47944476148667076,-.0014669405958800579,.7364925893845453,.6293972741802124);C.jFa=new a.Z(-.6154469465354344,-.24589767758847714,1.2448236795108683,1.2631535127174947);C.wFa=new a.Z(-80.60817722658722,-60.796273249672765,46.608687602908056,66.96595767361796);C.jEa=new a.Z(68.20516856593524,-52.89892708045518,111.65739821771903,116.55460214469134);C.IEa=new a.Z(-24.543831069368586,
-37.202500659225905,204.54283106936856,164.9634493690208);C.bFa=new a.Z(-117.12451221229134,-54.95921623126266,82.33223251442891,87.67786623127876);C.AFa=new a.Z(-.6154656300926513,.0507209798775865,1.0153104799231851,.966537441082997);C.BFa=new a.Z(-171.9,-62.6,349.8,150.8);C.r2a=new a.Z(172,51,8,3);C.s2a=new a.Z(-180,51,51,21);C.m4a=new a.Z(-178.5,18.9,35,11);C.T5a=new a.Z(-124.8,24.4,58,25.5);C.iEa=new a.Z(-187.5517578125,59.82610321044922,57.562225341796875,43.83738708496094);C.WEa=new a.Z(-160.23606872558594,
18.91549301147461,5.4374847412109375,3.3189010620117188);C.zFa=new a.Z(-2386803.25,-1183550.5,4514111,2908402);C.Dka=new a.Z(165,400,100,100);C.pka=new a.Z(-75,350,240,150);C.vs=[[1,0],[.9986,.0314],[.9954,.0629],[.99,.0943],[.9822,.1258],[.973,.1572],[.96,.1887],[.9427,.2201],[.9216,.2515],[.8962,.2826],[.8679,.3132],[.835,.3433],[.7986,.3726],[.7597,.4008],[.6732,.4532],[.6213,.4765],[.5722,.4951],[.5322,.5072]];C.lqb=function(b,c,d){var e;switch(d){case "africa":e=C.aH(C.hEa,C.s0(b,c));break;case "asia":e=
C.aH(C.kEa,C.H$(40,95,20,60,b,c),C.Mm(5));break;case "australia":e=C.v$a(b,c);break;case "europe":e=C.aH(C.JEa,C.H$(35,25,40,65,b,c),C.Mm(10));break;case "northAmerica":e=C.aH(C.jFa,C.H$(23,-96,20,60,b,c));break;case "southAmerica":e=C.aH(C.wFa,new a.R(b,c),C.Mm(5));break;case "apac":e=C.aH(C.jEa,C.s0(b,c));break;case "emea":e=C.aH(C.IEa,C.s0(b,c));break;case "latinAmerica":e=C.aH(C.bFa,new a.R(b,c));break;case "usaAndCanada":e=C.aH(C.AFa,C.H$(23,-96,20,60,b,c));break;case "worldRegions":e=C.hKa(b,
c);break;case "usa":e=C.Uab(b,c);break;case "world":e=C.hKa(b,c)}return e?new a.R(10*e.x,10*e.y):null};C.Uab=function(b,c){var d;C.r2a.Nj(b,c)||C.s2a.Nj(b,c)?(d=C.Mv(C.iEa,C.pka),d=C.d_(d,C.s0(b,c))):C.m4a.Nj(b,c)?(d=C.Mv(C.WEa,C.Dka),d=C.d_(d,new a.R(b,c))):C.T5a.Nj(b,c)&&(d=C.Mv(C.zFa,C.ix),d=C.d_(d,C.xab(new a.R(-95,36),b,c)));return C.J$(C.ix,d)};C.hKa=function(a,b){var c=C.Mv(C.BFa,C.ix),c=C.d_(c,C.Jab(a,b));return C.J$(C.ix,c)};C.v$a=function(a,b){var c;c=C.Lka.Nj(a,b)?C.Mv(C.Lka,C.Mka):C.Mv(C.uEa,
C.ix);c=C.d_(c,C.s0(a,b));return C.J$(C.ix,c)};C.aH=function(b,c,d){b=C.Mv(b,C.ix);if(d){var e=new a.Tb;e.rotate(d);b=C.qHa(b,e)}c=b.ef(c);return C.J$(C.ix,c)};C.J$=function(a,b){return b&&a.Nj(b.x,b.y)?b:null};C.H$=function(b,c,d,e,f,h){c=C.Mm(c);b=C.Mm(b);d=C.Mm(d);e=C.Mm(e);e=.5*(Math.sin(d)+Math.sin(e));d=Math.pow(Math.cos(d),2)+2*e*Math.sin(d);b=d-2*e*Math.sin(b);b=Math.sqrt(b)/e;f=e*(C.Mm(f)-c);h=d-2*e*Math.sin(C.Mm(h));h=Math.sqrt(h)/e;return new a.R(h*Math.sin(f),b-h*Math.cos(f))};C.s0=function(b,
c){return new a.R(b,C.rY(Math.log(Math.tan(.25*Math.PI+.5*C.Mm(c)))))};C.xab=function(b,c,d){c=C.Mm(c);d=C.Mm(d);var e=C.Mm(b.x);b=C.Mm(b.y);return new a.R(Math.cos(d)*Math.sin(c-e)*C.kO,(Math.cos(b)*Math.sin(d)-Math.sin(b)*Math.cos(d)*Math.cos(c-e))*C.kO)};C.Jab=function(b,c){var d=Math.floor(Math.abs(c)/5);d>=C.vs.length-1&&(d=C.vs.length-2);var e=(Math.abs(c)-5*d)/5,f=b*(C.vs[d][0]+e*(C.vs[d+1][0]-C.vs[d][0])),d=C.vs[d][1]+e*(C.vs[d+1][1]-C.vs[d][1]);0>c&&(d*=-1);return new a.R(f,180*d)};C.d_=
function(b,c){return new a.R(c.x*b.gg+b.le,c.y*b.qj+b.fe)};C.qHa=function(b,c){var d=b.gg,e=b.qj;return new a.Tb(c.gg*d,c.rl*d,c.xk*e,c.qj*e,b.le+c.le*d,b.fe+c.fe*e)};C.Mv=function(b,c){var d=c.x,e=c.y,f=b.a,h=b.b,k=0,k=c.a/f,l=c.b/h,k=k<=l?k:l,d=d-b.x*k,e=e+b.y*k,d=d+(c.a-f*k)/2,e=e+(c.b-(c.b-h*k)/2);return new a.Tb(k,0,0,-k,d,e)};C.Mm=function(a){return Math.PI/180*a};C.rY=function(a){return 180/Math.PI*a};C.hwb=function(b,c,d){var e;b/=10;c/=10;switch(d){case "africa":e=C.bH(C.hEa,new a.R(b,c));
e=C.q0(e.x,e.y);break;case "asia":e=C.bH(C.kEa,new a.R(b,c),C.Mm(5));e=C.T$(40,95,20,60,e.x,e.y);break;case "australia":e=C.gab(b,c);break;case "europe":e=C.bH(C.JEa,new a.R(b,c),C.Mm(10));e=C.T$(35,25,40,65,e.x,e.y);break;case "northAmerica":e=C.bH(C.jFa,new a.R(b,c));e=C.T$(23,-96,20,60,e.x,e.y);break;case "southAmerica":e=C.bH(C.wFa,new a.R(b,c),C.Mm(5));break;case "apac":e=C.bH(C.jEa,new a.R(b,c));e=C.q0(e.x,e.y);break;case "emea":e=C.bH(C.IEa,new a.R(b,c));e=C.q0(e.x,e.y);break;case "latinAmerica":e=
C.bH(C.bFa,new a.R(b,c));break;case "usaAndCanada":e=C.bH(C.AFa,new a.R(b,c));e=C.T$(23,-96,20,60,e.x,e.y);break;case "worldRegions":e=C.CJa(b,c);break;case "usa":e=C.jab(b,c);break;case "world":e=C.CJa(b,c)}return e?e:new a.R(b,c)};C.jab=function(b,c){var d;return C.pka.Nj(b,c)?(d=C.Mv(C.iEa,C.pka),d.fF(),d=d.ef(new a.R(b,c)),C.q0(d.x,d.y)):C.Dka.Nj(b,c)?(d=C.Mv(C.WEa,C.Dka),d.fF(),d.ef(new a.R(b,c))):C.ix.Nj(b,c)?(d=C.Mv(C.zFa,C.ix),d.fF(),d=d.ef(new a.R(b,c)),C.hab(new a.R(-95,36),d.x,d.y)):new a.R(b,
c)};C.CJa=function(b,c){var d=C.Mv(C.BFa,C.ix);d.fF();d=d.ef(new a.R(b,c));return C.iab(d.x,d.y)};C.gab=function(b,c){var d;d=C.Mka.Nj(b,c)?C.Mv(C.Lka,C.Mka):C.Mv(C.uEa,C.ix);d.fF();d=d.ef(new a.R(b,c));return C.q0(d.x,d.y)};C.bH=function(b,c,d){b=C.Mv(b,C.ix);if(d){var e=new a.Tb;e.rotate(d);b=C.qHa(b,e)}b.fF();return b.ef(c)};C.T$=function(b,c,d,e,f,h){c=C.Mm(c);b=C.Mm(b);d=C.Mm(d);e=C.Mm(e);e=.5*(Math.sin(d)+Math.sin(e));d=Math.pow(Math.cos(d),2)+2*e*Math.sin(d);b=d-2*e*Math.sin(b);b=Math.sqrt(b)/
e;var k=Math.sqrt(f*f+(b-h)*(b-h));return new a.R(C.rY(c+Math.atan(f/(b-h))/e),C.rY(Math.asin((d-k*k*e*e)/(2*e))))};C.q0=function(b,c){return new a.R(b,C.rY(2*Math.atan(Math.exp(C.Mm(c)))-.5*Math.PI))};C.hab=function(b,c,d){c/=C.kO;d/=C.kO;var e=C.Mm(b.y),f=Math.sqrt(c*c+d*d),h=Math.asin(f);return new a.R(C.rY(C.Mm(b.x)+Math.atan(c*Math.sin(h)/(f*Math.cos(e)*Math.cos(h)-d*Math.sin(e)*Math.sin(h)))),C.rY(Math.asin(Math.cos(h)*Math.sin(e)+d*Math.sin(h)*Math.cos(e)/f)))};C.iab=function(b,c){var d=Math.floor(Math.abs(c)/
5);d>=C.vs.length-1&&(d=C.vs.length-2);var e=(Math.abs(c/180)-C.vs[d][1])/(C.vs[d+1][1]-C.vs[d][1]),f=5*e+5*d,d=b/(C.vs[d][0]+e*(C.vs[d+1][0]-C.vs[d][0]));0>c&&(f*=-1);return new a.R(d,f)};a.v.D(b,a.ua);b.prototype.Init=function(c,d,e){b.C.Init.call(this,c,d,e);this.tr=d.tr;this.ys=d.hc();this.O9a=a.v.ti(d,d.mta);this.M9a=a.v.ti(d,d.lda);this.vfb=a.v.ti(d,d.$wa);this.nx=this.ox=this.LH=null;this.rIa=this.qIa=!1;this.Ka=d.vw()};b.prototype.uxa=function(a){this.qIa=a;this.nx&&this.nx.sn(a)};b.prototype.vxa=
function(a){this.rIa=a;this.ox&&this.ox.sn(a)};b.prototype.DZ=function(b){if(this.tr&&"none"!=this.tr){var c=a.Ta.M(this.Ka,a.ua.qN,0);this.LH=a.U.Lib(this.u(),this.ys,this.Ka);this.LH.Ru(this.vfb,this);this.LH.tn(a.H.va(a.H.yh,"CONTROL_PANEL_RESET"));this.yb.lb(this.LH,this.LH);b.A(this.LH);this.nx=a.U.zib(this.u(),this.ys,this.Ka);this.nx.Ru(this.M9a,this);this.nx.tn(a.H.va(a.H.yh,"CONTROL_PANEL_DRILLDOWN"));this.yb.lb(this.nx,this.nx);this.nx.ga(c);this.nx.sn(this.qIa);b.A(this.nx);this.ox=a.U.Aib(this.u(),
this.ys,this.Ka);this.ox.Ru(this.O9a,this);this.ox.tn(a.H.va(a.H.yh,"CONTROL_PANEL_DRILLUP"));this.yb.lb(this.ox,this.ox);this.ox.ga(2*c);this.ox.sn(this.rIa);b.A(this.ox)}};b.prototype.mw=function(a,c){var d=b.C.mw.call(this,a,c);!d&&this.Ab()&&("drillDown"==a&&this.nx&&this.nx.isEnabled()?d=this.nx:"drillUp"==a&&this.ox&&this.ox.isEnabled()?d=this.ox:"reset"==a&&this.LH&&this.LH.isEnabled()&&(d=this.LH));return d};a.Ia(a,"AmxThematicMap",a.Qj);a.Ia(a.Qj,"newInstance",a.Qj.newInstance);a.Ia(a.Qj.prototype,
"render",a.Qj.prototype.ta);a.Ia(a.Qj.prototype,"getDomElementForSubId",a.Qj.prototype.qh);a.Ia(a.Qj.prototype,"getSubIdForDomElement",a.Qj.prototype.i4);a.Ia(B,"getLayerIds",B.Blb);a.Ia(a,"ThematicMap",a.$a);a.Ia(a.$a,"newInstance",a.$a.newInstance);a.Ia(a.$a.prototype,"updateLayer",a.$a.prototype.ttb);a.Ia(a.$a.prototype,"destroy",a.$a.prototype.xa);a.Ia(a.$a.prototype,"getAutomation",a.$a.prototype.ph);a.Ia(a.$a.prototype,"highlight",a.$a.prototype.Ve);a.Ia(a.$a.prototype,"processDefaultHoverEffect",
a.$a.prototype.ky);a.Ia(a.$a.prototype,"processDefaultSelectionEffect",a.$a.prototype.II);a.Ia(a.$a.prototype,"processDefaultFocusEffect",a.$a.prototype.FC);a.Ia(u.prototype,"getDomElementForSubId",u.prototype.qh);a.Ia(u.prototype,"getData",u.prototype.getData)})(dvt);
// To avoid changing the basemaps, which each call the basemap manager, we will
// put the basemap manager onto the returned object. We'll only do this if it's
// not defined, since in min/min-debug mode, the non-exported version is on the window.
if(!dvt['DvtBaseMapManager'])
  dvt['DvtBaseMapManager'] = DvtBaseMapManager;

  return dvt;
});
