/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","promise"],function(a,g){a.W={};o_("AnimationUtils",a.W,a);a.W.Tx=function(c,b,d,e,f,h){var k=g(c),l=[].concat(f);return(new Promise(function(c){function g(){r||(k.off("transitionend webkitTransitionEnd",t),c(!0),r=!0)}function t(a){a=l.indexOf(a.originalEvent.propertyName);-1<a&&(1<l.length?l.splice(a,1):g())}var r=!1;null==d.css&&(d.css={});d.css.transition=a.W.Fqa(f,e);var n=a.W.fBa(k,b,d,e,h||f);a.W.m3(k,b,1<n);k.on("transitionend webkitTransitionEnd",t);window.setTimeout(function(){a.W.m3(k,
d,1<n);setTimeout(g,a.W.L3(k)+100)},20)})).then(function(){b&&b.addClass&&k.removeClass(b.addClass);d&&d.addClass&&k.removeClass(d.addClass);a.W.aBa(k)})};a.W.aba=function(c,b,d,e){for(var f in b)if(b=a.W.n6(f),!(d.hasOwnProperty(b)||e&&-1!=e.indexOf(b))){var g=c[0].style;d[b]=void 0===g[b]?g[a.W.T7(b)]:g[b]}};a.W.fBa=function(c,b,d,e,f){var g=c.data("_ojSavedStyle")||{};b=b&&b.css?b.css:{};d=d&&d.css?d.css:{};e&&"all"===e.persist||(f=null);a.W.aba(c,b,g,f);a.W.aba(c,d,g,f);c.data("_ojSavedStyle",
g);e=c.data("_ojEffectCount")||0;c.data("_ojEffectCount",++e);return e};a.W.aBa=function(a){var b=a.data("_ojEffectCount");if(1<b)a.data("_ojEffectCount",b-1);else if(b=a.data("_ojSavedStyle"))a.css(b),a.removeData("_ojSavedStyle"),a.removeData("_ojEffectCount")};a.W.n6=function(a){if(0<=a.indexOf("-")){var b="";a=a.split("-");for(var d=0;d<a.length;d++){var e=a[d];e&&(b=b?b+(e.charAt(0).toUpperCase()+e.slice(1)):e)}return b}return a};a.W.dta=function(a){return a.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase()};
a.W.T7=function(a){return"webkit"+a.charAt(0).toUpperCase()+a.slice(1)};a.W.w4=function(c,b,d,e,f){b.css[d]&&(d=a.W.n6(d),(c=c[0].style[d]||c[0].style[a.W.T7(d)])&&0!=c.indexOf(e)&&(b.css[d]=c+f+b.css[d]))};a.W.m3=function(c,b,d){b&&(b.css&&(d&&(a.W.w4(c,b,"transform","none"," "),a.W.w4(c,b,"transition","all",", ")),c.css(b.css)),b.addClass&&c.addClass(b.addClass),b.removeClass&&c.removeClass(b.removeClass))};a.W.K3=function(a,b,d){b=a.css(b);var e=a.css(d+"Delay");d=a.css(d+"Duration");a=e.split(",");
d=d.split(",");b=b.split(",").length;for(var e=a.length,f=d.length,g=0,k=0;k<b;k++){var l=d[k%f],l=-1<l.indexOf("ms")?parseFloat(l):1E3*parseFloat(l);if(0<l)var m=a[k%e],m=-1<m.indexOf("ms")?parseFloat(m):1E3*parseFloat(m),g=Math.max(g,m+l)}return g};a.W.L3=function(c){var b=a.W.K3(c,"animationName","animation");c=a.W.K3(c,"transitionProperty","transition");return Math.max(b,c)};a.W.Wra=function(a,b){a.delay=a.delay||b.delay;a.duration=a.duration||b.duration;a.timingFunction=a.timingFunction||b.timingFunction;
a.persist=a.persist||b.persist};a.W.Nn=function(c,b,d){return new Promise(function(e){function f(){r=!0;k()}function h(){t=!0;k()}function k(){t&&r&&(l.removeClass(m),l.removeClass(s),e(!0),l.trigger("ojanimateend",{action:b}))}var l=g(c),m="oj-animate-"+b,s=m+"-active",t=!1,r=!1,n=g.Event("ojanimatestart");l.trigger(n,{action:b,endCallback:h});if(!n.isDefaultPrevented()){for(var n=[].concat(d),p=[],q={},u=0;u<n.length;u++){var v=n[u],w="",y;null!=v&&"none"!=v&&("string"==typeof v?(w=v,y={}):"object"==
typeof v&&(w=v.effect,y=g.extend({},v)),a.W.Wra(y,q),q=g.extend({},y));w&&a.W[w]&&p.push(a.W[w](c,y))}p.length?Promise.all(p).then(h):h()}l.addClass(m);window.setTimeout(function(){l.addClass(s);setTimeout(f,a.W.L3(l)+100)},20)})};o_("AnimationUtils.startAnimation",a.W.Nn,a);a.W.Xy=function(c,b){null==a.W.fy&&(a.W.fy=a.nd.uf("oj-animation-effect-default-options"));return g.extend({duration:"400ms"},a.W.fy?a.W.fy[c]:null,b)};a.W.Fqa=function(c,b){var d="";if(c)for(var e=0;e<c.length;e++){var f=a.W.dta(c[e]),
d=d+((0<e?", ":"")+f+" "+b.duration);b.timingFunction&&(d+=" "+b.timingFunction);b.delay&&(d+=" "+b.delay)}return d};a.W.J5=function(c,b,d,e,f){b=a.W.Xy(d,b);d={css:{opacity:e}};f={css:{opacity:f}};b&&(b.startOpacity&&(d.css.opacity=b.startOpacity),b.endOpacity&&(f.css.opacity=b.endOpacity));return a.W.Tx(c,d,f,b,["opacity"])};a.W.fadeIn=function(c,b){return a.W.J5(c,b,"fadeIn",0,1)};o_("AnimationUtils.fadeIn",a.W.fadeIn,a);a.W.fadeOut=function(c,b){return a.W.J5(c,b,"fadeOut",1,0)};o_("AnimationUtils.fadeOut",
a.W.fadeOut,a);a.W.expand=function(c,b){return a.W.G5(c,b,!0)};o_("AnimationUtils.expand",a.W.expand,a);a.W.collapse=function(c,b){return a.W.G5(c,b,!1)};o_("AnimationUtils.collapse",a.W.collapse,a);a.W.G5=function(c,b,d){b=a.W.Xy(d?"expand":"collapse",b);var e={},f={},h=b.direction||"height";c=g(c);var k=c.width(),l=c.height(),m=c.css("maxWidth"),s=c.css("maxHeight"),t=e.css={},r=f.css={};"none"!==m&&(k=m);"none"!==s&&(l=s);m=[];if("both"===h||"height"===h)t.maxHeight=d?0:l,r.maxHeight=d?l:0,m.push("maxHeight");
if("both"===h||"width"===h)t.maxWidth=d?0:k,r.maxWidth=d?k:0,m.push("maxWidth");return a.W.Tx(c[0],e,f,b,m)};a.W.VZ=function(c,b){return a.W.eda(c,b,!0)};o_("AnimationUtils.zoomIn",a.W.VZ,a);a.W.WZ=function(c,b){return a.W.eda(c,b,!1)};o_("AnimationUtils.zoomOut",a.W.WZ,a);a.W.eda=function(c,b,d){b=a.W.Xy(d?"zoomIn":"zoomOut",b);var e={},f={},h=b.axis||"both";c=g(c);var h="both"===h?"scale":"x"===h?"scaleX":"scaleY",k=e.css={},l=f.css={};k.transform=h+"("+(d?0:1)+") translateZ(0)";l.transform=h+"("+
(d?1:0)+") translateZ(0)";k.transformOrigin=b.transformOrigin||"center";return a.W.Tx(c[0],e,f,b,["transform"])};a.W.pJa=function(c,b){return a.W.To(c,b,!0)};o_("AnimationUtils.slideIn",a.W.pJa,a);a.W.qJa=function(c,b){return a.W.To(c,b,!1)};o_("AnimationUtils.slideOut",a.W.qJa,a);a.W.To=function(c,b,d){b=a.W.Xy(d?"slideIn":"slideOut",b);var e={},f={},h=b.direction||"start";c=g(c);var k="0",l="0",m=e.css={},s=f.css={};if(b.offsetX||b.offsetY)b.offsetX&&(k=b.offsetX),b.offsetY&&(l=b.offsetY);else{var t=
c.outerWidth(),r=c.outerHeight(),n="rtl"===a.u.wn();switch(h){case "left":k=(d?t:-t)+"px";break;case "right":k=(d?-t:t)+"px";break;case "top":l=(d?r:-r)+"px";break;case "bottom":l=(d?-r:r)+"px";break;case "end":k=(d?-t:t)*(n?-1:1)+"px";break;default:k=(d?t:-t)*(n?-1:1)+"px"}}d?(m.transform="translate("+k+","+l+") translateZ(0)",s.transform="translate(0,0) translateZ(0)"):(m.transform="translate(0,0) translateZ(0)",s.transform="translate("+k+","+l+") translateZ(0)");return a.W.Tx(c[0],e,f,b,["transform"])};
a.W.aJa=function(c,b){b=a.W.Xy("ripple",b);var d={},e={},f=g(c),h=f.outerWidth(),k=f.outerHeight(),l=g("\x3cdiv style\x3d'position:absolute; overflow:hidden'\x3e"),m=g("\x3cdiv class\x3d'oj-animation-effect-ripple oj-animation-rippler'\x3e"),s="static"==f.css("position")?f.position():{left:0,top:0};f.prepend(l);l.css({left:s.left+"px",top:s.top+"px",width:h+"px",height:k+"px"});l.prepend(m);f=d.css={};h=e.css={};a.W.dCa(f,m,l,b);f.transform="scale(0) translateZ(0)";f.opacity=b.startOpacity||m.css("opacity");
h.transform="scale(1) translateZ(0)";h.opacity=b.endOpacity||0;return a.W.Tx(m[0],d,e,b,["transform","opacity"]).then(function(){l.remove()})};o_("AnimationUtils.ripple",a.W.aJa,a);a.W.dCa=function(c,b,d,e){b=b.width();var f=d.width(),g=d.height();if(e.diameter){var k=e.diameter,l=parseInt(k,10);isNaN(l)||(b="%"==k.charAt(k.length-1)?Math.floor(Math.min(f,g)*(l/100)):l,c.width=b+"px",c.height=b+"px")}d="static"==d.css("position")?d.position():{left:0,top:0};f=a.W.Q3(e.offsetX,b,f,d.left);null!=f&&
(c.left=f+"px");f=a.W.Q3(e.offsetY,b,g,d.top);null!=f&&(c.top=f+"px");e.color&&(c.backgroundColor=e.color)};a.W.Q3=function(a,b,d,e){var f;a=a||"50%";var g=parseInt(a,10);isNaN(g)||(f="%"==a.charAt(a.length-1)?g/100*d-b/2:g-b/2,f=Math.floor(f+e));return f};a.W.$Ka=function(c,b){b=b||{};var d={fadeOut:1,collapse:1,zoomOut:1,slideOut:1},e=b.removeEffect||"fadeOut",f=g(".oj-animation-rippler",c);if(0===f.length)console.warn("No rippler so returning");else return e in d?a.W[e](f,b).then(function(){f.remove()}):
f.remove()};a.W.b6=function(c,b,d,e,f){b=a.W.Xy(d,b);d={};var g={},k={css:d},l={css:g},m="rotateY(",s="2000px",t="hidden",r="center";b&&("x"===b.axis&&(m="rotateX("),b.startAngle&&(e=b.startAngle),b.endAngle&&(f=b.endAngle),b.perspective&&(s=b.perspective),b.backfaceVisibility&&(t=b.backfaceVisibility),b.transformOrigin&&(r=b.transformOrigin));m="perspective("+s+") "+m;d.transform=m+e+")";d.backfaceVisibility=t;d.transformOrigin=r;g.transform=m+f+")";return a.W.Tx(c,k,l,b,["transform"],["transform",
"backfaceVisibility","transformOrigin"])};a.W.BFa=function(c,b){return a.W.b6(c,b,"flipIn","-180deg","0deg")};o_("AnimationUtils.flipIn",a.W.BFa,a);a.W.CFa=function(c,b){return a.W.b6(c,b,"flipOut","0deg","180deg")};o_("AnimationUtils.flipOut",a.W.CFa,a)});