/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(a,g){a.Ma=function(c,b){this.data=c||{};if(!(c instanceof Array)&&"function"!=typeof c&&"function"!=typeof c.xia)throw Error(a.aa.od._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.aa.od._ERR_DATA_INVALID_TYPE_DETAIL);null!=b&&null!=b.idAttribute||a.r.info(a.Ma.od._INFO_ARRAY_TABLE_DATASOURCE_IDATTR);a.Ma.t.constructor.call(this,c,b);this.Ue=[];this.ya={};if(null!=c&&void 0!==c&&(this.bU=null,null!=b&&null!=b.idAttribute&&(this.bU=b.idAttribute),
this.i=c instanceof Array?c:c(),this.Gf=this.i.length,!(c instanceof Array))){var d=this;c.subscribe(function(a){if(d.l9()){var b,c=[],g=[];for(b=0;b<a.length;b++)"deleted"===a[b].status&&c.push(a[b].value);d.remove(c,null);c=[];g=[];for(b=0;b<a.length;b++)"added"===a[b].status&&(c.push(a[b].value),g.push(a[b].index));d.add(c,{at:g})}},null,"arrayChange")}if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.lE=!0};o_("ArrayTableDataSource",a.Ma,a);a.b.ta(a.Ma,a.aa,"oj.ArrayTableDataSource");
a.Ma.prototype.Pl=null;a.b.g("ArrayTableDataSource.prototype.comparator",{Pl:a.Ma.prototype.Pl});a.Ma.prototype.sortCriteria=null;a.b.g("ArrayTableDataSource.prototype.sortCriteria",{sortCriteria:a.Ma.prototype.sortCriteria});a.Ma.prototype.Init=function(){a.Ma.t.Init.call(this)};a.b.g("ArrayTableDataSource.prototype.Init",{Init:a.Ma.prototype.Init});a.Ma.prototype.add=function(a,b){b=b||{};this.Su();return this.Ona(a,b.at,b)};a.b.g("ArrayTableDataSource.prototype.add",{add:a.Ma.prototype.add});a.Ma.prototype.at=
function(a){this.Su();var b;b=0>a||a>=this.ya.data.length?null:{data:this.ya.data[a],index:a,key:this.ty(this.ya.data[a])};return new Promise(function(a){a(b)})};a.b.g("ArrayTableDataSource.prototype.at",{at:a.Ma.prototype.at});a.Ma.prototype.change=function(c,b){b=b||{};this.Su();var d=b.silent,e,f,g,k,l={data:[],keys:[],indexes:[]};c instanceof Array||(c=[c]);for(e=0;e<c.length;e++)f=c[e],null!=f&&(g=this.ty(f),k=this.Ck(g,null),l.data.push(f),l.keys.push(g),l.indexes.push(k.index),this.ya.data[k.index]=
f);!d&&0<l.data.length&&a.aa.t.handleEvent.call(this,a.aa.Q.CHANGE,l);return Promise.resolve(l)};a.b.g("ArrayTableDataSource.prototype.change",{change:a.Ma.prototype.change});a.Ma.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||this.lE?this.Cg(a):Promise.resolve()};a.b.g("ArrayTableDataSource.prototype.fetch",{fetch:a.Ma.prototype.fetch});a.Ma.prototype.get=function(a,b){b=b||{};this.Su();return Promise.resolve(this.Ck(a,b))};a.b.g("ArrayTableDataSource.prototype.get",{get:a.Ma.prototype.get});
a.Ma.prototype.getCapability=function(){return"full"};a.b.g("ArrayTableDataSource.prototype.getCapability",{getCapability:a.Ma.prototype.getCapability});a.Ma.prototype.remove=function(a,b){b=b||{};this.Su();return this.Qv(a,b)};a.b.g("ArrayTableDataSource.prototype.remove",{remove:a.Ma.prototype.remove});a.Ma.prototype.reset=function(c,b){b=b||{};b.previousRows=this.ya;var d=b.silent;null!=c&&(this.i=c);this.ya={};this.Gf=0;d||a.aa.t.handleEvent.call(this,a.aa.Q.RESET,null);return Promise.resolve()};
a.b.g("ArrayTableDataSource.prototype.reset",{reset:a.Ma.prototype.reset});a.Ma.prototype.sort=function(c){null==c?c=this.sortCriteria:this.sortCriteria=c;this.Su();var b=this;return new Promise(function(d){c=c||{};var e=b.HC();b.ya.data.sort(function(c,d){return a.Ma.hca(c,d,e,b)});b.ECa=!0;var f={header:c.key,direction:c.direction};a.aa.t.handleEvent.call(b,a.aa.Q.SORT,f);d(f)})};a.b.g("ArrayTableDataSource.prototype.sort",{sort:a.Ma.prototype.sort});a.Ma.prototype.totalSize=function(){return this.Gf};
a.b.g("ArrayTableDataSource.prototype.totalSize",{totalSize:a.Ma.prototype.totalSize});a.Ma.prototype.Ona=function(c,b,d){var e,f;d=d||{};var g=d.silent,k={data:[],keys:[],indexes:[]};c instanceof Array||(c=[c]);null==b||b instanceof Array||(b=[b]);for(d=0;d<c.length;d++)if(f=c[d],null!=f){e=this.ty(f);k.data.push(f);k.keys.push(e);if(!0==this.ECa&&0<this.ya.data.length)for(e=0;e<this.ya.data.length;e++)if(0>a.Ma.hca(f,this.ya.data[e],this.HC(),this)){this.ya.data.splice(e,0,f);k.indexes.push(e);
break}else{if(e==this.ya.data.length-1){this.ya.data.push(f);k.indexes.push(e+1);break}}else null==b?(this.ya.data.push(f),k.indexes.push(this.ya.data.length-1)):(this.ya.data.splice(b[d],0,f),k.indexes.push(b[d]));this.Gf++;this.QD()}!g&&0<k.data.length&&a.aa.t.handleEvent.call(this,a.aa.Q.ADD,k);return Promise.resolve(k)};a.Ma.prototype.Su=function(){this.l9()||(this.data instanceof Array||"function"!=typeof this.data||"function"!=typeof this.data.xia||(this.i=this.data()),this.ya=this.zy(this.i),
this.Gf=this.i.length)};a.Ma.prototype.l9=function(){return null==this.ya||null==this.ya.data?!1:!0};a.Ma.prototype.Cg=function(c){c=c||{};this.kE(c);this.Su();var b;try{b=0<c.pageSize?c.pageSize:-1;this.pa||(this.pa=0);this.pa=null==c.startIndex?this.pa:c.startIndex;var d=a.Ma.KI(this.ya,this.pa,b),e=[],f=[],g,k;for(g=this.pa;g<=d;g++)k=this.Xo(g,this.ya.data[g]),e[g-this.pa]=k,f[g-this.pa]=this.ty(this.ya.data[g])}catch(l){return this.Tm(c,null,l),Promise.reject(l)}d<this.pa&&(this.pa=d+1);c.pageSize=
b;c.startIndex=this.pa;c.refresh=!0;b={data:e,keys:f,startIndex:this.pa};this.Tm(c,b,null);return Promise.resolve(b)};a.Ma.prototype.Ck=function(a){var b,d,e,f,h=null;for(b=0;b<this.ya.data.length;b++)if(e=this.ya.data[b],void 0!==e)if(f=this.ty(e),g.isArray(f)&&g.isArray(a)){if(f.length==a.length){var k=!0;for(d=0;d<a.length;d++)if(f[d]!=a[d]){k=!1;break}k&&(d=this.Xo(b,e),h={data:d,key:f,index:this.ya.indexes[b]})}}else f==a&&(d=this.Xo(b,e),h={data:d,key:f,index:this.ya.indexes[b]});return h};
a.Ma.prototype.HC=function(){var a=this.comparator;if(null==a){var b=this.sortCriteria.key,d=this.sortCriteria.direction;"ascending"==d?a=function(a){return g.isFunction(a[b])?a[b]():a[b]}:"descending"==d&&(a=function(a,c){var d,k;g.isFunction(a[b])?(d=a[b](),k=c[b]()):(d=a[b],k=c[b]);return d===k?0:d>k?-1:1})}return a};a.Ma.prototype.QD=function(){for(var a=0;a<this.ya.data.length;a++)this.ya.indexes[a]=a};a.Ma.prototype.Qv=function(c,b){var d,e;b=b||{};var f=b.silent,g={data:[],keys:[],indexes:[]};
c instanceof Array||(c=[c]);var k=[];for(d=0;d<c.length;d++)e=c[d],null!=e&&(e=this.ty(e),e=this.Ck(e,null),null!=e&&k.push({data:e.data,key:e.key,index:e.index}));k.sort(function(a,b){return a.index-b.index});for(d=0;d<k.length;d++)g.data.push(k[d].data),g.keys.push(k[d].key),g.indexes.push(k[d].index);for(d=g.indexes.length-1;0<=d;d--)this.ya.data.splice(g.indexes[d],1),this.ya.indexes.splice(g.indexes[d],1),this.Gf--,this.QD();!f&&0<g.data.length&&a.aa.t.handleEvent.call(this,a.aa.Q.REMOVE,g);
return Promise.resolve(g)};a.Ma.prototype.kE=function(c){c.silent||a.aa.t.handleEvent.call(this,a.aa.Q.REQUEST,{startIndex:c.startIndex})};a.Ma.prototype.Tm=function(c,b,d){null!=d?a.aa.t.handleEvent.call(this,a.aa.Q.ERROR,d):c.silent||a.aa.t.handleEvent.call(this,a.aa.Q.SYNC,b)};a.Ma.cq=function(a,b,d){if("descending"==d){if(a<b)return 1;if(b<a)return-1}else{if(a>b)return 1;if(b>a)return-1}return 0};a.Ma.KI=function(a,b,d){var e=a.data.length-1;0<d&&(e=b+d-1,e=e>a.data.length-1?a.data.length-1:e);
return e};a.Ma.jc=function(a,b){return g.isFunction(a[b])?a[b]():a[b]};a.Ma.prototype.zy=function(a){var b=a.length-1,d={},e,f;d.data=[];d.indexes=[];this.$r=null;for(e=0;e<=b;e++){var g={},k=a[e];for(f in k)k.hasOwnProperty(f)&&(g[f]=k[f],0==e&&(null==this.$r&&(this.$r=[]),this.$r.push(f)));d.data[e]=g;d.indexes[e]=e}return d};a.Ma.prototype.ty=function(c){var b,d=this.FS(c);if(g.isArray(d)){var e;b=[];for(e=0;e<d.length;e++)if(d[e]in c)b[e]=a.Ma.jc(c,d[e]);else throw c=a.va.Lc(a.Ma.od._ERR_ARRAY_TABLE_DATASOURCE_IDATTR_NOT_IN_ROW,
[d[e]]),Error(c);}else if(d in c)b=a.Ma.jc(c,d);else throw c=a.va.Lc(a.Ma.od._ERR_ARRAY_TABLE_DATASOURCE_IDATTR_NOT_IN_ROW,[d]),Error(c);return b};a.Ma.prototype.FS=function(a){if(null!=this.bU)return this.bU;if(null==this.$r){this.$r=[];for(var b in a)a.hasOwnProperty(b)&&this.$r.push(b)}return this.$r.hasOwnProperty("id")?"id":this.$r};a.Ma.hca=function(c,b,d,e){var f,h=e.sortCriteria.direction;if(g.isFunction(d)){if(1===d.length){f=d.call(e,c);e=d.call(e,b);c=a.bb.Ke(f)?f.split(","):[f];b=a.bb.Ke(e)?
e.split(","):[e];for(d=0;d<c.length;d++)if(f=a.Ma.cq(c[d],b[d],h),0!==f)return f;return 0}return d.call(e,c,b)}if(a.bb.Ke(d)){var k=d.split(",");for(d=0;d<k.length;d++)if(f=a.Ma.jc(c,k[d]),e=a.Ma.jc(b,k[d]),f=a.Ma.cq(f,e,h),0!==f)return f}return 0};a.Ma.prototype.Xo=function(a,b){var d={},e=this,f;for(f in b)b.hasOwnProperty(f)&&function(){var b=f;Object.defineProperty(d,f,{get:function(){return e.ya.data[a][b]},set:function(d){e.ya.data[a][b]=d},enumerable:!0})}();return d};a.Ma.od={_INFO_ARRAY_TABLE_DATASOURCE_IDATTR:"idAttribute option has not been specified. Will default to using 'id' if the field exists. If not, will use all the fields.",
_ERR_ARRAY_TABLE_DATASOURCE_IDATTR_NOT_IN_ROW:"Specified idAttribute {0} not in row data. Please ensure all specified idAttribute fields are in the row data or do not specify idAttribute and all fields will be used as id."}});