/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","knockout","ojs/ojdatasource-common"],function(a,g,c){a.vc=function(a){this.data=a;this.current=0;this.Init();this.NV(10)};o_("ArrayPagingDataSource",a.vc,a);a.b.ta(a.vc,a.vm,"oj.ArrayPagingDataSource");a.vc.prototype.Init=function(){a.vc.t.Init.call(this)};a.b.g("ArrayPagingDataSource.prototype.Init",{Init:a.vc.prototype.Init});a.vc.prototype.bT=function(){return this.$m()?this.Jq:this.totalSize()-this.current};a.vc.prototype.Nv=function(a){a=a||{};this.ei=Array(this.bT());
for(var c=0;c<this.ei.length;c++)this.ei[c]=this.data[this.current+c];this.UD();this.Bk=this.pa+this.ei.length-1;a.silent||this.handleEvent("sync",{data:this.ei,startIndex:this.current})};a.vc.prototype.UD=function(){if(void 0!==this.Jn){this.Jn.removeAll();for(var a=0;a<this.ei.length;a++)this.Jn.push(this.ei[a])}};a.vc.prototype.handleEvent=function(b,c){return a.vc.t.handleEvent.call(this,b,c)};a.vc.prototype.Wq=function(){return this.ei};a.b.g("ArrayPagingDataSource.prototype.getWindow",{Wq:a.vc.prototype.Wq});
a.vc.prototype.$E=function(){void 0===this.Jn&&(this.Jn=c.observableArray(),this.UD());return this.Jn};a.b.g("ArrayPagingDataSource.prototype.getWindowObservable",{$E:a.vc.prototype.$E});a.vc.prototype.getPage=function(){return this.ge};a.b.g("ArrayPagingDataSource.prototype.getPage",{getPage:a.vc.prototype.getPage});a.vc.prototype.setPage=function(b,c){c=c||{};b=parseInt(b,10);try{a.vc.t.handleEvent.call(this,a.$c.Q.BEFOREPAGE,{page:b,previousPage:this.ge})}catch(e){return Promise.reject(null)}this.pageSize=
null!=c.pageSize?c.pageSize:this.pageSize;c.startIndex=b*this.pageSize;var f=this.ge;this.ge=b;this.pa=c.startIndex;var g=this;return new Promise(function(b,e){g.Cg(c).then(function(){a.vc.t.handleEvent.call(g,a.$c.Q.PAGE,{page:g.ge,previousPage:f});b(null)},function(){g.ge=f;g.pa=g.ge*g.pageSize;e(null)})})};a.b.g("ArrayPagingDataSource.prototype.setPage",{setPage:a.vc.prototype.setPage});a.vc.prototype.getStartItemIndex=function(){return this.pa};a.b.g("ArrayPagingDataSource.prototype.getStartItemIndex",
{getStartItemIndex:a.vc.prototype.getStartItemIndex});a.vc.prototype.getEndItemIndex=function(){return this.Bk};a.b.g("ArrayPagingDataSource.prototype.getEndItemIndex",{getEndItemIndex:a.vc.prototype.getEndItemIndex});a.vc.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.pageSize)};a.b.g("ArrayPagingDataSource.prototype.getPageCount",{getPageCount:a.vc.prototype.getPageCount});a.vc.prototype.fetch=function(a){a=a||{};if(void 0!==a.pageSize&&void 0!==a.startIndex){if(!this.$m())return Promise.resolve();
this.Jq=a.startIndex+a.pageSize}this.Nv(null);return Promise.resolve()};a.b.g("ArrayPagingDataSource.prototype.fetch",{fetch:a.vc.prototype.fetch});a.vc.prototype.Cg=function(a){var c=a||{};void 0!==c.startIndex&&(this.current=c.startIndex);void 0!==c.pageSize&&(this.Jq=this.pageSize=c.pageSize);this.Nv(a);return Promise.resolve({data:this.ei,startIndex:this.current})};a.vc.prototype.$m=function(){return this.current+this.Jq<this.totalSize()};a.vc.prototype.NV=function(a){this.Jq=this.pageSize=a;
this.Nv(null)};a.vc.prototype.totalSize=function(){return this.data.length};a.vc.prototype.totalSizeConfidence=function(){return"actual"};a.b.g("ArrayPagingDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:a.vc.prototype.totalSizeConfidence});a.vc.prototype.getCapability=function(){return null};a.b.g("ArrayPagingDataSource.prototype.getCapability",{getCapability:a.vc.prototype.getCapability})});