/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(a){a.fb=function(g,c){if(!(g instanceof Array)&&"function"!=typeof g&&"function"!=typeof g.xia)throw Error("_ERR_DATA_INVALID_TYPE_SUMMARY\n_ERR_DATA_INVALID_TYPE_DETAIL");this.Ow=this.Lta(c);null!=c&&(this.columns=c.columns,this.sortCriteria=c.initialSort);a.fb.t.constructor.call(this,g)};o_("ArrayDataGridDataSource",a.fb,a);a.b.ta(a.fb,a.Dr,"oj.ArrayDataGridDataSource");a.fb.prototype.Init=function(){null==this.columns&&(this.columns=
this.Dsa(this.Tl()));this.cxa();"function"==typeof this.data&&this.data.subscribe(this.KCa.bind(this),null,"arrayChange");a.fb.t.Init.call(this)};a.b.g("ArrayDataGridDataSource.prototype.Init",{Init:a.fb.prototype.Init});a.fb.prototype.Pl=null;a.b.g("ArrayDataGridDataSource.prototype.comparator",{Pl:a.fb.prototype.Pl});a.fb.prototype.sortCriteria=null;a.b.g("ArrayDataGridDataSource.prototype.sortCriteria",{sortCriteria:a.fb.prototype.sortCriteria});a.fb.prototype.Lta=function(a){if(null!=a&&null!=
a.rowHeader)if(a=a.rowHeader,"object"===typeof a){if(null!=a["default"]&&"none"==a["default"])return}else if(null!=a)return a;return"m_defaultIndex"};a.fb.prototype.cxa=function(){var a;a=this.Tl();for(this.ww=0;this.ww<a.length;this.ww+=1)a[this.ww].ojKey=this.ww.toString()};a.fb.prototype.Dsa=function(a){var c,b;if("number"!==typeof a.length||0===a.length)return[];b=[];for(c in a[0])a[0].hasOwnProperty(c)&&(void 0!=this.Ow&&c==this.Ow||b.push(c));return b};a.fb.prototype.getCount=function(a){return"row"===
a?this.Ws():"column"===a?this.columns.length:0};a.b.g("ArrayDataGridDataSource.prototype.getCount",{getCount:a.fb.prototype.getCount});a.fb.prototype.getCountPrecision=function(){return"exact"};a.b.g("ArrayDataGridDataSource.prototype.getCountPrecision",{getCountPrecision:a.fb.prototype.getCountPrecision});a.fb.prototype.ES=function(a,c){var b;if("row"===a){if(void 0==this.Ow)return null;if("m_defaultIndex"==this.Ow)return this.cJ(c);b=this.Tl();return b[c][this.Ow]}if("column"===a)return this.columns[c]};
a.fb.prototype.bta=function(a,c){var b;if("row"===a)return{key:this.cJ(c)};if("column"===a)return b=this.ES(a,c),null!=this.sortCriteria&&this.sortCriteria.key===b?{key:this.ES(a,c),sortDirection:this.sortCriteria.direction}:{key:b}};a.fb.prototype.fetchHeaders=function(g,c,b){var d,e,f,h;d=g.axis;e=g.start;f=g.count;e=Math.max(0,e);"column"===d?f=Math.min(this.columns.length,e+f):(h=this.Tl(),f=void 0===this.Ow?e:Math.min(h.length,e+f));d=new a.xh(e,f,d,this);null!=c&&null!=c.success&&(null==b&&
(b={}),c.success.call(b.success,d,g,null))};a.b.g("ArrayDataGridDataSource.prototype.fetchHeaders",{fetchHeaders:a.fb.prototype.fetchHeaders});a.fb.prototype.tsa=function(a,c){var b=this.columns[c];return this.Tl()[a][b]};a.fb.prototype.uBa=function(a,c,b){this.Tl()[a][this.columns[c]]=b};a.fb.prototype.usa=function(a,c){return{keys:{row:this.cJ(a),column:this.columns[c]}}};a.fb.prototype.fetchCells=function(g,c,b){var d,e,f,h,k,l;for(d=0;d<g.length;d+=1)e=g[d],"row"===e.axis?(f=e.start,h=Math.min(this.Ws(),
f+e.count)):"column"===e.axis&&(k=e.start,l=Math.min(this.columns.length,k+e.count));void 0===h||void 0===l?null!=c&&null!=c.error&&(null==b&&(b={}),c.error.call(b.error)):(d=new a.kj(f,h,k,l,this),null!=c&&null!=c.success&&(null==b&&(b={}),c.success.call(b.success,d,g)))};a.b.g("ArrayDataGridDataSource.prototype.fetchCells",{fetchCells:a.fb.prototype.fetchCells});a.fb.prototype.keys=function(a){var c=a.row,b=a.column;return new Promise(function(a){a({row:this.cJ(c),column:this.columns[b]})}.bind(this))};
a.b.g("ArrayDataGridDataSource.prototype.keys",{keys:a.fb.prototype.keys});a.fb.prototype.indexes=function(a){var c=a.row,b=a.column;return new Promise(function(a){a({row:this.bJ(c),column:this.columns.indexOf(b)})}.bind(this))};a.b.g("ArrayDataGridDataSource.prototype.indexes",{indexes:a.fb.prototype.indexes});a.fb.prototype.sort=function(a,c,b){var d=[],e=[],f;null!=c&&null==b&&(b={});void 0==this.Jw&&(this.Zya=this.sortCriteria,this.Jw=this.data.slice());null==a?a=this.sortCriteria:this.sortCriteria=
a;if(null==a)this.zV(c,b);else if(f=a.axis,a=a.key,"column"===f)this.Tl().sort(this.HC()),null!=c&&null!=c.success&&c.success.call(b.success);else if("row"===f){a=this.bJ(a);for(f=0;f<this.columns.length;f+=1)d[f]=this.Tl()[a][this.columns[f]];d.sort(this.HC());for(f=0;f<this.columns.length;f+=1)e[f]=this.columns[d.indexOf(this.Tl()[a][this.columns[f]])];this.mha=this.columns;this.columns=e;null!=c&&null!=c.success&&c.success.call(b.success)}else null!==c&&null!=c.error&&c.error.call(b.error,"Invalid axis value")};
a.b.g("ArrayDataGridDataSource.prototype.sort",{sort:a.fb.prototype.sort});a.fb.prototype.zV=function(a,c){null!=this.Jw&&(this.data=this.Jw,this.sortCriteria=this.Zya);null!=this.mha&&(this.columns=this.mha);null!=a&&null!=a.success&&a.success.call(c.success)};a.fb.prototype.getCapability=function(a){return"sort"===a?"column":"move"===a?"row":null};a.b.g("ArrayDataGridDataSource.prototype.getCapability",{getCapability:a.fb.prototype.getCapability});a.fb.prototype.HC=function(){var a,c,b;a=this.comparator;
return null==a?(a=this.sortCriteria.key,c=this.sortCriteria.direction,b=this.sortCriteria.axis,this.Dya(c,a,b)):a};a.fb.prototype.Dya=function(a,c,b){if("ascending"===a)return function(a,e){var f,g;void 0!=c&&"column"==b&&(a instanceof Array?(a=a[parseInt(c,10)],e=e[parseInt(c,10)]):(a=a[c],e=e[c]));f=isNaN(a);g=isNaN(e);a instanceof Date&&(a=a.toISOString(),f=!0);e instanceof Date&&(e=e.toISOString(),g=!0);return f&&g?a<e?-1:a===e?0:1:f?1:g?-1:a-e};if("descending"===a)return function(a,e){var f,
g;void 0!=c&&"column"==b&&(a instanceof Array?(a=a[parseInt(c,10)],e=e[parseInt(c,10)]):(a=a[c],e=e[c]));f=isNaN(a);g=isNaN(e);a instanceof Date&&(a=a.toISOString(),f=!0);e instanceof Date&&(e=e.toISOString(),g=!0);return f&&g?a>e?-1:a===e?0:1:f?-1:g?1:e-a}};a.fb.prototype.move=function(a,c){var b,d;b=this.bJ(a);d=this.data.splice(b,1)[0];this.data instanceof Array&&(b=this.yo("delete",a,null,b,-1,!0),this.handleEvent("change",b));null===c?(this.data.push(d),b=this.data.length-1):(b=this.bJ(c),this.data.splice(b,
0,d));this.data instanceof Array&&(b=this.yo("insert",a,null,b,-1),this.handleEvent("change",b));null!=this.Jw&&(this.Jw=this.data.slice())};a.b.g("ArrayDataGridDataSource.prototype.move",{move:a.fb.prototype.move});a.fb.prototype.moveOK=function(){return"valid"};a.b.g("ArrayDataGridDataSource.prototype.moveOK",{moveOK:a.fb.prototype.moveOK});a.fb.prototype.Tl=function(){return"function"===typeof this.data?this.data():this.data};a.fb.prototype.bJ=function(a){var c,b=this.Tl();for(c=0;c<b.length;c++)if(b[c].ojKey===
a)return c;return-1};a.fb.prototype.cJ=function(a){var c=this.Tl();return c[a]?c[a].ojKey:null};a.fb.prototype.yo=function(a,c,b,d,e,f){var h={source:this};h.operation=a;h.keys={row:c,column:b};h.indexes={row:d,column:e};h.silent=f;return h};a.fb.prototype.KCa=function(a){var c,b,d,e=!1;b=!1;var f=[],h=[];for(c=0;c<a.length;c++){d=a[c];if(void 0!==d.moved){b=!0;d=this.yo("refresh",null,null);this.handleEvent("change",d);break}"added"===d.status&&(e=!0)}if(!b){for(c=0;c<a.length;c++)d=a[c],"deleted"===
d.status&&(b=d.value,d=d.index,b=b.ojKey,f.push({row:b,column:-1}),h.push({row:d,column:-1}));0<f.length&&(d={source:this,operation:"delete",keys:f,indexes:h,silent:e},this.handleEvent("change",d));for(c=0;c<a.length;c++)d=a[c],"added"===d.status&&(b=d.value,d=d.index,null==b.ojKey&&(b.ojKey=this.ww.toString(),this.ww++),b=b.ojKey,d=this.yo("insert",b,null,d,-1),this.handleEvent("change",d))}null!=this.Jw&&(this.Jw=this.data.slice())};a.fb.prototype.Ws=function(){return this.Tl().length};a.fb.prototype.efa=
function(){return this.Ow};a.b.g("ArrayDataGridDataSource.prototype.getRowHeaderKey",{efa:a.fb.prototype.efa});a.fb.prototype.nt=function(){return this.columns};a.b.g("ArrayDataGridDataSource.prototype.getColumns",{nt:a.fb.prototype.nt});a.fb.prototype.getData=function(){return this.data};a.b.g("ArrayDataGridDataSource.prototype.getData",{getData:a.fb.prototype.getData});a.xh=function(a,c,b,d){this.cd=a;this.ng=c;this.zga=b;this.Yl=d};o_("ArrayHeaderSet",a.xh,a);a.xh.prototype.getData=function(g,
c){if(null==this.Yl)return null;a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return this.Yl.ES(this.zga,g)};a.b.g("ArrayHeaderSet.prototype.getData",{getData:a.xh.prototype.getData});a.xh.prototype.getMetadata=function(g,c){if(null==this.Yl)return null;a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return this.Yl.bta(this.zga,g)};a.b.g("ArrayHeaderSet.prototype.getMetadata",{getMetadata:a.xh.prototype.getMetadata});
a.xh.prototype.getLevelCount=function(){return 0<this.getCount()?1:0};a.b.g("ArrayHeaderSet.prototype.getLevelCount",{getLevelCount:a.xh.prototype.getLevelCount});a.xh.prototype.getExtent=function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};a.b.g("ArrayHeaderSet.prototype.getExtent",{getExtent:a.xh.prototype.getExtent});a.xh.prototype.getDepth=function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,
"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return 1};a.b.g("ArrayHeaderSet.prototype.getDepth",{getDepth:a.xh.prototype.getDepth});a.xh.prototype.getCount=function(){return null==this.Yl?0:Math.max(0,this.ng-this.cd)};a.b.g("ArrayHeaderSet.prototype.getCount",{getCount:a.xh.prototype.getCount});a.xh.prototype.getStart=function(){return this.cd};a.b.g("ArrayHeaderSet.prototype.getStart",{getStart:a.xh.prototype.getStart});a.kj=function(a,c,b,d,e){this.Ba=a;this.jb=c;this.yp=
b;this.zw=d;this.Yl=e};o_("ArrayCellSet",a.kj,a);a.kj.prototype.getData=function(a){var c,b,d;c=this;b=a.row;d=a.column;a={};Object.defineProperty(a,"data",{get:function(){return c.Yl.tsa(b,d)},set:function(a){c.Yl.uBa(b,d,a)}});return a};a.b.g("ArrayCellSet.prototype.getData",{getData:a.kj.prototype.getData});a.kj.prototype.getMetadata=function(a){return this.Yl.usa(a.row,a.column)};a.b.g("ArrayCellSet.prototype.getMetadata",{getMetadata:a.kj.prototype.getMetadata});a.kj.prototype.getStart=function(a){return"row"==
a?this.Ba:"column"==a?this.yp:-1};a.b.g("ArrayCellSet.prototype.getStart",{getStart:a.kj.prototype.getStart});a.kj.prototype.getCount=function(a){return"row"===a?Math.max(0,this.jb-this.Ba):"column"===a?Math.max(0,this.zw-this.yp):0};a.b.g("ArrayCellSet.prototype.getCount",{getCount:a.kj.prototype.getCount});a.kj.prototype.lp=function(){return this.Ba};a.b.g("ArrayCellSet.prototype.getStartRow",{lp:a.kj.prototype.lp});a.kj.prototype.kp=function(){return this.yp};a.b.g("ArrayCellSet.prototype.getStartColumn",
{kp:a.kj.prototype.kp})});