/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,g){(function(){function c(b,c,d){a:{for(var e=r[b],f=0;f<e.length;++f){var g=e[f];if(0<=d.indexOf(g))for(;;c=c.parentNode){var h=a.Components.Mf(c,g);if(h){d=h;break a}}}d=null}return d?d("option","chroming"):(a.nd.uf("oj-"+b+"-option-defaults")||{}).chroming}function b(a,b){var c=a.name,d=a.form;c?(c=c.replace(/'/g,"\\'"),c=":radio[name\x3d'"+c+"']:oj-button",d=b?b.filter(c):d?g(d).find(c):g(c,a.ownerDocument).filter(function(){return!this.form})):
d=(b?b.filter(a):g(a)).filter(":oj-button");return d}function d(a,b){a.removeClass(s).addClass(t[b])}a.Na("oj.ojButton",g.oj.baseComponent,{defaultElement:"\x3cbutton\x3e",widgetEventPrefix:"oj",options:{chroming:"full",disabled:!1,display:"all",label:null,icons:{start:null,end:null},menu:null},Xf:function(a,b){this._super(a,b);this.Dwa();"disabled"in b||this.option("disabled",!!this.element.prop("disabled"),{_context:{ob:!0}});"label"in b||(this.QHa=!0,this.option("label","inputPush"===this.type?
this.Jf.val():this.Jf.html(),{_context:{ob:!0}}));!this.options.menu||b.icons&&void 0!==b.icons.end||this.option("icons.end","oj-component-icon oj-button-menu-dropdown-icon",{_context:{Ed:!0,ob:!0}})},_ComponentCreate:function(){function a(){b.DU=Date.now();b.tc.removeClass(l);b.tc.removeClass("oj-hover");b.Ol()}this._super();this.element.closest("form").unbind("reset"+h).bind("reset"+h,function(){var a=g(this);setTimeout(function(){a.find(":oj-button").each(function(){g(this).data("oj-ojButton").yH(!1)}).length||
a.unbind("reset"+h)},1)});this.JF=this.eventNamespace+"menu";this.Ewa();this.iY=!!this.tc.attr("title");var b=this,c=this.nD,l=c?"":"oj-active";this.tc.addClass(k);d(this.tc,this.options.chroming);this.document.bind("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,a);this.Jf.bind("touchstart"+this.eventNamespace,function(){b.Yf()||(g(this).addClass(l),b.Ol())}).bind("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,a).bind("mouseenter"+this.eventNamespace,function(){b.Yf()||
b.RD()||(this===e&&b.tc.addClass("oj-active"),b.tc.addClass("oj-hover").removeClass("oj-default oj-focus-only"))}).bind("mouseleave"+this.eventNamespace,function(){b.tc.removeClass("oj-hover");b.Yf()||(b.tc.removeClass(l),b.Ol())}).bind("click"+this.eventNamespace,function(a){b.Yf()&&(a.preventDefault(),a.stopImmediatePropagation())});this._focusable({element:this.tc,applyHighlight:!0,afterToggle:function(){b.Ol()}});c&&(this.element.bind("change"+this.eventNamespace,function(a){b.yH(!0);var c=g(this).closest(":oj-buttonset").data("oj-ojButtonset"),
d=c&&c.p6(c.wf);c&&void 0!==d&&c.option("checked",d,{_context:{Ed:!0,originalEvent:a,ob:!0}})}),this.Jf.bind("mousedown"+this.eventNamespace,function(){b.Yf()||(f=this,b.document.one("mouseup",function(){f=null}))}).bind("mouseup"+this.eventNamespace,function(){b.Yf()||this!==f||b.element.focus()}));"checkbox"===this.type?(this.Jf.bind("click"+this.eventNamespace,function(){if(b.Yf())return!1}),this.element.bind("keyup"+this.eventNamespace,function(a){a.keyCode===g.ui.keyCode.ENTER&&(b.Yf()||b.element.click())})):
"radio"===this.type?(this.Jf.bind("click"+this.eventNamespace,function(){if(b.Yf())return!1}),this.element.bind("keyup"+this.eventNamespace,function(a){a.keyCode!==g.ui.keyCode.ENTER||b.element[0].checked||b.Yf()||(b.element[0].checked=!0,b.element.change(),b.element.click())})):(this.Jf.bind("mousedown"+this.eventNamespace,function(a){if(b.Yf())return!1;1!==a.which||b.RD()||(g(this).addClass("oj-active").removeClass("oj-default oj-focus-only"),e=this,b.document.one("mouseup",function(){e=null}))}).bind("mouseup"+
this.eventNamespace,function(){if(b.Yf())return!1;g(this).removeClass("oj-active");b.Ol()}).bind("keydown"+this.eventNamespace,function(a){if(b.Yf())return!1;var c=a.keyCode===g.ui.keyCode.SPACE,d="anchor"===b.type;d&&c&&a.preventDefault();(c&&!d||a.keyCode===g.ui.keyCode.ENTER)&&g(this).addClass("oj-active").removeClass("oj-default oj-focus-only")}).bind("keyup"+this.eventNamespace+" blur"+this.eventNamespace,function(){g(this).removeClass("oj-active");b.Ol()}),"anchor"===this.type&&(c=this.Jf.attr("tabindex"),
("undefined"===c||null===c||isNaN(c))&&this.Jf.attr("tabindex","0")));this.KW();this.xva();this.Rba();this.Ol()},RD:function(){return 500>Date.now()-this.DU},ih:function(a,b,c){this.jh(b,c,{position:{of:"keyboard"===c?this.tc:b}})},Dwa:function(){if(this.element.is("input[type\x3dcheckbox]"))this.type="checkbox",this.nD=!0;else if(this.element.is("input[type\x3dradio]"))this.type="radio",this.nD=!0;else if(this.element.is("input[type\x3dbutton],input[type\x3dsubmit],input[type\x3dreset]"))this.type=
"inputPush";else if(this.element.is("button"))this.type="button";else if(this.element.is("a"))this.type="anchor";else throw Error("JET Button not supported on this element type");if(this.nD){var a="label[for\x3d'"+this.element.attr("id")+"']";this.Jf=this.element.siblings().filter(a)}else this.Jf=this.element},Ewa:function(){this.nD?(this.Jf.addClass("oj-button-label"),this.element.addClass("oj-button-input oj-helper-hidden-accessible").add(this.Jf).wrapAll("\x3cspan\x3e\x3c/span\x3e"),this.tc=this.element.parent(),
this.tc.addClass("oj-button-toggle"),this.element[0].checked&&this.tc.addClass("oj-selected").removeClass("oj-default oj-focus-only")):this.tc=this.element},widget:function(){return this.tc},_destroy:function(){this.Caa();this.document.off(this.eventNamespace);this.element.removeClass("oj-helper-hidden-accessible").removeAttr("aria-labelledby").removeUniqueId();var b=this.nD;b||this.tc.removeClass(k+" "+l+" "+m+" "+s);this.Jf.html(this.Jf.find(".oj-button-text").html());b?(this.Jf.removeClass("oj-button-label"),
a.u.unwrap(this.element)):this.iY||this.tc.removeAttr("title");f===this.Jf[0]&&(f=null)},sj:function(){this._super();this.Ol()},QB:function(a){this._super(a);this.KW()},KW:function(){var a=this.Yf();this.tc.toggleClass("oj-disabled",a);this.tc.toggleClass("oj-enabled",!a);"anchor"!==this.type?(this.element.prop("disabled",a),this.tc.removeAttr("aria-disabled")):this.tc.attr("aria-disabled",a);a?(this.widget().removeClass("oj-active oj-default oj-focus-only oj-hover oj-focus oj-focus-highlight"),e=
null,this.KR()):this.Ol()},_setOption:function(a,b,c){this._super(a,b,c);switch(a){case "chroming":d(this.tc,b);break;case "disabled":this.KW();break;case "label":this.QBa();break;case "display":"inputPush"!==this.type&&this.BK();break;case "icons":this.NBa(!0);break;case "menu":this.Rba()}},refresh:function(){this._super();this.h3&&!g(this).closest(":oj-buttonset").length&&this.QB(!1);d(this.tc,this.options.chroming)},yH:function(a){"radio"===this.type?(a?b(this.element[0]):this.element).each(function(){var a=
g(this).data("oj-ojButton");this.checked?a.tc.addClass("oj-selected").removeClass("oj-default oj-focus-only"):(a.tc.removeClass("oj-selected"),a.Ol())}):"checkbox"===this.type&&(this.element[0].checked?this.tc.addClass("oj-selected").removeClass("oj-default oj-focus-only"):(this.tc.removeClass("oj-selected"),this.Ol()))},xva:function(){if("inputPush"===this.type)this.zba();else{var a=this.PBa(),b=this.DK(!0),c=this.DK(!1);this.BK(a,b,c)}},PBa:function(){var a=this.Jf,b=g("\x3cspan class\x3d'oj-button-text'\x3e\x3c/span\x3e",
this.document[0]);this.QHa?b.append(a.contents()):(a.empty(),b.text(this.options.label));"button"===this.type?(a=g("\x3cdiv\x3e\x3c/div\x3e").addClass("oj-button-label"),a.append(b),this.element.append(a)):a.append(b);if("button"===this.type||"anchor"===this.type)b.uniqueId(),this.element.attr("aria-labelledby",b.attr("id"));return b},QBa:function(){if("inputPush"===this.type)this.zba();else{var a=this.Jf.find(".oj-button-text");a.text(this.options.label);this.BK(a)}},zba:function(){this.options.label&&
this.element.val(this.options.label)},NBa:function(){if("inputPush"!==this.type){var a=this.DK(!0),b=this.DK(!1);this.BK(void 0,a,b)}},DK:function(a){var b=this.Jf;"button"===this.type&&(b=this.element.children("div.oj-button-label"));if(a){var c=".oj-button-icon.oj-start";a="oj-button-icon oj-start";var d=this.options.icons.start,e="_lastStartIcon",f="prependTo"}else c=".oj-button-icon.oj-end",a="oj-button-icon oj-end",d=this.options.icons.end,e="_lastEndIcon",f="appendTo";c=b.find(c);d?(c.length?
c.removeClass(this[e]):c=g("\x3cspan\x3e\x3c/span\x3e").addClass(a)[f](b),c.addClass(d)):c.remove();this[e]=d;return!!d},BK:function(a,b,c){void 0===a&&(a=this.Jf.find(".oj-button-text"));void 0===b&&(b=!!this.options.icons.start);void 0===c&&(c=!!this.options.icons.end);var d=b&&c;c=b||c;var e="icons"===this.options.display;c&&e?(a.addClass("oj-helper-hidden-accessible"),this.iY||(a=a.text(),this.tc.attr("title",g.trim(a)))):(a.removeClass("oj-helper-hidden-accessible"),this.iY||this.tc.removeAttr("title"));
b=c?e?d?"oj-button-icons-only":"oj-button-icon-only":d?"oj-button-text-icons":b?"oj-button-text-icon-start":"oj-button-text-icon-end":"oj-button-text-only";this.tc.removeClass(m).addClass(b)},Rba:function(){if(this.options.menu&&this.element.is("input"))throw Error("Menu Button functionality is not supported on input elements.");this.Caa();if(this.options.menu){var a=this;this.element.attr("aria-haspopup",!0).on("keydown"+this.JF,function(b){if(b.which===g.ui.keyCode.DOWN)a.Yba(b,"firstItem"),b.preventDefault();
else if(b.which===g.ui.keyCode.ESCAPE){var c=a.$oa(a.tc);a.KR(b);return c}return!0}).on("click"+this.JF,function(b){var c=a.NS();c.rH||a.Yba(b,"firstItem");c.rH=!1;b.preventDefault();return!0})}},$oa:function(a){return!a.hasClass("oj-selected")},Caa:function(){this.element.removeAttr("aria-haspopup").off(this.JF);this.KR();this.Aa&&this.Aa.widget().off(this.JF);this.Aa=void 0},NS:function(){if(!this.Aa){this.Aa=g(this.options.menu).data("oj-ojMenu");if(!this.Aa)throw Error('JET Button: "menu" option specified, but does not reference a valid JET Menu.');
var a=this;this.Aa.widget().on("ojclose"+this.JF,function(b){a.lya(b)})}return this.Aa},Yba:function(a,b){if(!this.Yf()){var c=this.NS(),d=c.widget();c.open(a,{launcher:this.element,initialFocus:b});this.f$=!0;d.attr("aria-label")||d.attr("aria-labelledby")||(this.element.uniqueId(),this.oba=!0,d.attr("aria-labelledby",this.element.attr("id")));this.tc.addClass("oj-selected").removeClass("oj-default oj-focus-only")}},KR:function(a){this.f$&&(this.Aa.pH(a,!0),this.Aa.Nu(a))},lya:function(){this.oba&&
(this.NS().widget().removeAttr("aria-labelledby"),this.oba=!1);this.tc.removeClass("oj-selected");this.Ol();this.f$=!1},Ol:function(){var a,b;this.tc.is(".oj-hover, .oj-active, .oj-selected, .oj-disabled")?b=a=!1:(b=this.tc.is(".oj-focus"),a=!b);this.tc.toggleClass("oj-default",a);this.tc.toggleClass("oj-focus-only",b)}});a.Na("oj.ojButtonset",g.oj.baseComponent,{K9:"button, input[type\x3dbutton], input[type\x3dsubmit], input[type\x3dreset], input[type\x3dcheckbox], input[type\x3dradio], a",widgetEventPrefix:"oj",
options:{checked:null,chroming:"full",focusManagement:"oneTabstop"},dE:function(a,b){var c=g.type(a),d;if("null"===c||"array"===c)d=b.filter("input[type\x3dcheckbox]").length===b.length;if(d&&"null"===c)throw Error("Invalid 'checked' value set on JET Buttonset: "+a);if("string"===c||"null"===c)(c=((c=b[0].name)||1>=b.length)&&b.filter("input[type\x3dradio][name\x3d"+c+"]").length===b.length&&(null===a||b.filter("[value\x3d"+a+"]").length))&&b.each(function(){this.checked=this.value===a}),c=c||null===
a;else if("array"===c){var e;(c=d&&a.concat().sort().every(function(a){var c=a!==e&&b.filter("[value\x3d"+a+"]").length;e=a;return c}))&&b.each(function(){this.checked=-1<a.indexOf(this.value)})}else c=!1;if(!c)throw Error("Invalid 'checked' value set on JET Buttonset: "+a);},p6:function(a){var b=void 0,c=null,d=null;a.each(function(){if("input"!==this.tagName.toLowerCase())return b=void 0,!1;var a=this.type.toLowerCase(),e;if("radio"===a)a=!0,e=this.name.toLowerCase();else if("checkbox"===a)a=!1,
e=null;else return b=void 0,!1;if(void 0!==b&&(a!==c||e!==d||c&&!d))return b=void 0,!1;void 0===b?(b=a?this.checked?this.value:null:this.checked?[this.value]:[],c=a,d=e):this.checked&&(c?b=this.value:b.push(this.value))});return b},uB:function(a,b,c){return"checked"===a?b===c?!0:"array"===g.type(b)&&"array"===g.type(c)&&this.Dpa(b,c):this._superApply(arguments)},Dpa:function(a,b){return!a.some(function(a){return 0>b.indexOf(a)})&&!b.some(function(b){return 0>a.indexOf(b)})},Xf:function(a,b){this._super(a,
b);this.wf=this.element.find(this.K9);if(!("checked"in b)){this.kY=!0;var c=this.p6(this.wf);"array"===g.type(c)&&(this.options.checked=[]);void 0!==c&&this.option("checked",c,{_context:{ob:!0}})}},_ComponentCreate:function(){this._super();this.element.attr(a.Components.co,this.widgetName).addClass("oj-buttonset oj-component");this.Lba(this.options.focusManagement);this.$a(!0)},ih:function(a,b,c){a=this.element.find(":oj-button[tabindex\x3d0]");this.jh(b,c,{launcher:a,position:{of:"keyboard"===c?
a.ojButton("widget"):b}})},Rs:function(a){a=!!a;this.wf.each(function(){g(this).data("oj-ojButton").QB(a)})},Lba:function(a){"oneTabstop"===a?this.element.attr("role","toolbar"):this.element.removeAttr("role")},_setOption:function(a,b,c){this._superApply(arguments);"disabled"===a?this.Rs(b):"checked"===a?(this.dE(b,this.wf),this.wf.each(function(){g(this).data("oj-ojButton").yH(!1)})):"focusManagement"===a?this.Lba(b):"chroming"===a&&(d(this.element,b),this.wf.ojButton("refresh"))},refresh:function(){this._super();
this.$a(!1)},$a:function(a){var b=this;this.Xk="rtl"===this.hd();d(this.element,this.options.chroming);a?this.kY||this.dE(this.options.checked,this.wf):this.wf=this.element.find(this.K9);this.element.toggleClass("oj-buttonset-multi",1<this.wf.length);this.wf.filter(":oj-button").ojButton("refresh").each(function(){g(this).data("oj-ojButton").yH(!1)}).end().not(":oj-button").ojButton().end().map(function(){return g(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").filter(":first").addClass("oj-buttonset-first").end().filter(":last").addClass("oj-buttonset-last").end().end();
this.Rs(this.options.disabled);"oneTabstop"===this.options.focusManagement&&(this.wf.unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.pv(a,g(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){g(this).data("oj-ojButton").Yf()||b.Tv(g(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Tv(g(this))}),this.Ip=this.wf.filter(function(){return!g(this).data("oj-ojButton").Yf()}),this.hU(a))},
hU:function(a){var b=g(this.Fv);this.Fv=void 0;this.wf.attr("tabindex","-1");a=a||!b.is(this.Ip)?this.Ip.first():b;this.Tv(a)},HU:function(a){var c=this.Ip;return a.map(function(a,d){if("radio"!=d.type||d.checked||""==d.name)return d;var e=b(d,c).filter(":checked");return e.length?e[0]:d})},Tv:function(a){a=this.HU(a);var b=a[0],c=this.Fv;b!==c&&(g(c).attr("tabindex","-1"),a.attr("tabindex","0"),this.Fv=b)},pv:function(a,b){switch(a.which){case g.ui.keyCode.LEFT:case g.ui.keyCode.RIGHT:a.preventDefault();
var c=this.Ip,d=c.length;if(2>d)break;var e=c.index(b);c.eq((e+(a.which==g.ui.keyCode.RIGHT^this.Xk?1:-1)+d)%d).focus();break;case g.ui.keyCode.UP:case g.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-buttonset oj-component "+s).removeAttr(a.Components.co).removeAttr("role");"oneTabstop"===this.options.focusManagement&&this.wf.attr("tabindex","0");this.wf.map(function(){return g(this).ojButton("widget")[0]}).removeClass("oj-buttonset-first oj-buttonset-last").end().ojButton("destroy")}});
var e,f,h=".ojButton",k="oj-button oj-component oj-enabled oj-default",l="oj-hover oj-active oj-selected",m="oj-button-icons-only oj-button-icon-only oj-button-text-icons oj-button-text-icon-start oj-button-text-icon-end oj-button-text-only",s="oj-button-full-chrome oj-button-half-chrome oj-button-outlined-chrome",t={full:"oj-button-full-chrome",half:"oj-button-half-chrome",outlined:"oj-button-outlined-chrome"},r={button:["ojButtonset","ojToolbar"],buttonset:["ojToolbar"]};a.Components.Dp({ojButton:{chroming:a.Components.Lf(function(a){return c("button",
a.element,a.containers)})},ojButtonset:{chroming:a.Components.Lf(function(a){return c("buttonset",a.element,a.containers)})}})})();a.Components.Ta("ojButton","baseComponent",{properties:{chroming:{type:"string"},disabled:{type:"boolean"},display:{type:"string"},icons:{type:"Object"},label:{type:"string"},menu:{type:"string"}},methods:{destroy:{},refresh:{},widget:{}},extension:{_hasWrapper:!0,_innerElement:"button",_widgetName:"ojButton"}});a.Components.register("oj-button",a.Components.getMetadata("ojButton"));
a.Components.Ta("ojToggleButton","baseComponent",{properties:{chroming:{type:"string"},disabled:{type:"boolean"},display:{type:"string"},icons:{type:"Object"},label:{type:"string"},menu:{type:"string"}},methods:{destroy:{},refresh:{},widget:{}},extension:{_hasWrapper:!0,_defaultAttrs:{type:"checkbox"},_innerElement:"input",_widgetName:"ojButton"}});a.Components.register("oj-toggle-button",a.Components.getMetadata("ojToggleButton"));a.Components.Ta("ojButtonset","baseComponent",{properties:{checked:{type:"string|Array\x3cstring\x3e"},
chroming:{type:"string"},disabled:{type:"boolean"},focusManagement:{type:"string"}},methods:{destroy:{},refresh:{},widget:{}},extension:{_widgetName:"ojButtonset"}});a.Components.register("oj-buttonset",a.Components.getMetadata("ojButtonset"))});