/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
var o_a=this;function o_(a,g,c){a=a.split(".");c=c||o_a;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var b;a.length&&(b=a.shift());)a.length||void 0===g?c=c[b]?c[b]:c[b]={}:c[b]=g};/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["require","ojL10n!ojtranslations/nls/ojtranslations","promise"],function(a,g){var c={};"undefined"!==typeof window?c=window:"undefined"!==typeof self&&(c=self);var b=c.oj,d=c.oj={version:"2.1.0",build:"3074",revision:"27379",noConflict:function(){c.oj=b}};d.r={};o_("Logger",d.r,d);d.r.Fja=0;o_("Logger.LEVEL_NONE",d.r.Fja,d);d.r.pO=1;o_("Logger.LEVEL_ERROR",d.r.pO,d);d.r.Hr=2;o_("Logger.LEVEL_WARN",d.r.Hr,d);d.r.ou=3;o_("Logger.LEVEL_INFO",d.r.ou,d);d.r.D_=
4;o_("Logger.LEVEL_LOG",d.r.D_,d);d.r.Ila="error";d.r.Lla="warn";d.r.Jla="info";d.r.Kla="log";d.r.fy={level:d.r.pO,writer:null};d.r.Vb=d.r.fy;d.r.error=function(a){d.r.DE(d.r.pO,d.r.Ila,arguments)};o_("Logger.error",d.r.error,d);d.r.info=function(a){d.r.DE(d.r.ou,d.r.Jla,arguments)};o_("Logger.info",d.r.info,d);d.r.warn=function(a){d.r.DE(d.r.Hr,d.r.Lla,arguments)};o_("Logger.warn",d.r.warn,d);d.r.log=function(a){d.r.DE(d.r.D_,d.r.Kla,arguments)};o_("Logger.log",d.r.log,d);d.r.option=function(a,c){var b=
{},e;if(0==arguments.length){for(e in d.r.Vb)d.r.Vb.hasOwnProperty(e)&&(b[e]=d.r.Vb[e]);return b}if("string"===typeof a&&void 0===c)return void 0===d.r.Vb[a]?null:d.r.Vb[a];if("string"===typeof a)d.r.Vb[a]=c;else for(e in a)a.hasOwnProperty(e)&&d.r.option(e,a[e])};o_("Logger.option",d.r.option,d);d.r.DE=function(a,c,b){if(!(d.r.option("level")<a)){var e=d.r.eua();null!=e&&(1==b.length&&b[0]instanceof Function&&(b=[b[0]()]),e[c]&&e[c].apply?e[c].apply(e,b):e[c]&&(e[c]=Function.prototype.bind.call(e[c],
e),d.r.DE(a,c,b)))}};d.r.eua=function(){var a=null;d.r.option("writer")?a=d.r.option("writer"):"undefined"!==typeof window&&void 0!==window.console&&(a=window.console);return a};d.r.eLa=function(a){return void 0!==d.r.fy[a]};var e=c.__ojCheckpointManager;d.bl={};o_("CHECKPOINT_MANAGER",d.bl,d);d.bl.rJa=function(a,c){e&&e.startCheckpoint(a,c)};o_("CHECKPOINT_MANAGER.startCheckpoint",d.bl.rJa,d);d.bl.tFa=function(a){e&&e.endCheckpoint(a)};o_("CHECKPOINT_MANAGER.endCheckpoint",d.bl.tFa,d);d.bl.VX=function(a){return e?
e.getRecord(a):void 0};o_("CHECKPOINT_MANAGER.getRecord",d.bl.VX,d);d.bl.Wga=function(a){return e?e.matchRecords(a):[]};o_("CHECKPOINT_MANAGER.matchRecords",d.bl.Wga,d);d.bl.qFa=function(a){d.r.info(function(){for(var c="Checkpoint Records:",b=d.bl.Wga(a),e=0;e<b.length;e++){var f=b[e],c=c+"\n"+f.name,g=f.description;null!=g&&(c=c+" ("+g+")");c+=":\n";c=c+"start: "+f.start+"\tduration: "+f.duration}return c})};o_("CHECKPOINT_MANAGER.dump",d.bl.qFa,d);d.b=function(){this.Init()};o_("Object",d.b,d);
d.b.t=null;d.b.yW="oj.Object";d.b.kla=/function\s+([\w\$][\w\$\d]*)\s*\(/;d.b.prototype={};d.b.prototype.constructor=d.b;d.b.g=function(a,c){var b=null,e=null,f;for(f in c)if(c.hasOwnProperty(f)){b=f;e=c[f];break}var g=a.split(".");f=d[g[0]];g=g[2];if(b!=g&&null!=b){var r=f.iV;r||(r={},f.iV=r);r[b]=g;f.prototype[g]=e}};d.b.ta=function(a,c,b){d.o.et(a);d.o.Fz(c);d.o.YW(b);void 0===c&&(c=d.b);d.o.assert(a!==c,"Class can't extend itself");var e=d.b.TCa;e.prototype=c.prototype;a.prototype=new e;a.prototype.constructor=
a;a.t=a.superclass=c.prototype;b&&(a.yW=b)};o_("Object.createSubclass",d.b.ta,d);d.b.JEa=function(a,c){var b;d.o.et(a);d.o.assert(null!=c,"source object cannot be null");for(b in c)c.hasOwnProperty(b)&&(a.prototype[b]=c[b])};o_("Object.copyPropertiesForClass",d.b.JEa,d);d.b.TCa=function(){};d.b.prototype.zea=function(a){if(void 0===a)a=this;else if(null===a)return null;return a.constructor};d.b.g("Object.prototype.getClass",{zea:d.b.prototype.zea});d.b.prototype.clone=function(){var a=new this.constructor;
d.Wc.pf(a,this);return a};d.b.g("Object.prototype.clone",{clone:d.b.prototype.clone});d.b.prototype.toString=function(){return this.JZ()};d.b.g("Object.prototype.toString",{toString:d.b.prototype.toString});d.b.prototype.JZ=function(){return this.getTypeName()+" Object"};d.b.g("Object.prototype.toDebugString",{JZ:d.b.prototype.JZ});d.b.getTypeName=function(a){d.o.et(a);var c=a.yW;null==c&&(c=a.toString(),c=(c=d.b.kla.exec(c))?c[1]:"anonymous",a.yW=c);return c};o_("Object.getTypeName",d.b.getTypeName,
d);d.b.prototype.getTypeName=function(){return d.b.getTypeName(this.constructor)};d.b.g("Object.prototype.getTypeName",{getTypeName:d.b.prototype.getTypeName});d.b.prototype.Init=function(){d.o.qY()&&d.o.assert(this.getTypeName,"Not an oj.Object");var a=this.constructor;a.qq||d.b.fU(a)};d.b.g("Object.prototype.Init",{Init:d.b.prototype.Init});d.b.uFa=function(a){d.o.et(a);a.qq||d.b.fU(a)};o_("Object.ensureClassInitialization",d.b.uFa,d);d.b.prototype.Mq=function(a){return this===a};d.b.g("Object.prototype.equals",
{Mq:d.b.prototype.Mq});d.b.Oda=function(a,c){d.o.et(c);return c.bind(a)};o_("Object.createCallback",d.b.Oda,d);d.b.fU=function(a){d.o.qY()&&(d.o.et(a),d.o.assert(!a.qq));a.qq=!0;var c=a.t;c&&((c=c.constructor)&&!c.qq&&d.b.fU(c),d.b.ioa(a));(c=a.InitClass||null)||(c=a.InitClass);c&&c.call(a)};d.b.Rj=function(a,c){if(a===c)return!0;if(typeof a!==typeof c||null===a||null===c)return!1;if(a.constructor===c.constructor){if(Array.isArray(a))return d.b.Cpa(a,c);if(a.constructor===Object)return d.b.PB(a,c);
if(a.valueOf&&"function"===typeof a.valueOf)return a.valueOf()===c.valueOf()}return!1};o_("Object.compareValues",d.b.Rj,d);d.b.Cpa=function(a,c){if(a.length!==c.length)return!1;for(var b=0,e=a.length;b<e;b++)if(!d.b.Rj(a[b],c[b]))return!1;return!0};d.b.u4=function(a,c){if(!a)return!c||0==c.length;if(!c)return!a||0==a.length;if(a.length!=c.length)return!1;for(var b=0;b<a.length;b++)if(a[b]!=c[b]&&(-1==a.indexOf(c[b])||-1==c.indexOf(a[b])))return!1;return!0};d.b.PB=function(a,c){var b,e=!1;if(a===c)return!0;
if(!(a instanceof Object&&c instanceof Object)||a.constructor!==c.constructor)return!1;for(b in a)if(e||(e=!0),a.hasOwnProperty(b)&&(!c.hasOwnProperty(b)||a[b]!==c[b]&&("object"!==typeof a[b]||!d.b.PB(a[b],c[b]))))return!1;for(b in c)if(e||(e=!0),c.hasOwnProperty(b)&&!a.hasOwnProperty(b))return!1;return e?!0:JSON.stringify(a)===JSON.stringify(c)};d.b.mi=function(a){var c;if(void 0===a||null===a)return!0;for(c in a)if(a.hasOwnProperty(c))return!1;return!0};d.b.ioa=function(a){d.b.iV&&d.b.k3(a,a.t)};
d.b.k3=function(a,c){if(c){var b=c.constructor;d.b.k3(a,b.t);var b=b.iV,e;if(b)for(e in b)if(b.hasOwnProperty(e)){var f=b[e];if(e!=f){var g=a.prototype;!g.hasOwnProperty(e)&&g.hasOwnProperty(f)?g[e]=g[f]:!g.hasOwnProperty(f)&&g.hasOwnProperty(e)&&(g[f]=g[e])}}}};d.Rx=function(){return"function"===typeof define&&define.amd};d.o={};o_("Assert",d.o,d);d.o.EFa=function(){d.o.DEBUG=!0};o_("Assert.forceDebug",d.o.EFa,d);d.o.EEa=function(){d.o.DEBUG=!1};o_("Assert.clearDebug",d.o.EEa,d);d.o.qY=function(){return!0==
d.o.DEBUG};o_("Assert.isDebug",d.o.qY,d);d.o.assert=function(a,c){if(d.o.DEBUG&&!a){var b=c||"",e;if(2<arguments.length){b+="(";for(e=2;e<arguments.length;e+=1)b+=arguments[e];b+=")"}d.o.If(b)}};o_("Assert.assert",d.o.assert,d);d.o.kd=function(){d.o.DEBUG&&d.o.If("Abstract function called")};o_("Assert.failedInAbstractFunction",d.o.kd,d);d.o.ue=function(a,c,b){var e;d.o.DEBUG&&(null!=a?(d.o.Nk(c,"function",null,0,!1),e=c.prototype,e.isPrototypeOf(a)||d.o.If("object '"+a+"' doesn't match prototype "+
e,0,b)):d.o.If("null object doesn't match prototype "+e,0,b))};o_("Assert.assertPrototype",d.o.ue,d);d.o.gEa=function(a,c,b){var e;d.o.DEBUG&&null!=a&&(null!=a?(d.o.Nk(c,"function",null,0,!1),e=c.prototype,e.isPrototypeOf(a)||d.o.If("object '"+a+"' doesn't match prototype "+e,0,b)):d.o.If("null object doesn't match prototype "+e,0,b))};o_("Assert.assertPrototypeOrNull",d.o.gEa,d);d.o.hEa=function(a,c,b,e){d.o.DEBUG&&(c=c.prototype,b=b.prototype,c.isPrototypeOf(a)||b.isPrototypeOf(a)||d.o.If("object '"+
a+"' doesn't match prototype "+c+" or "+b,0,e))};o_("Assert.assertPrototypes",d.o.hEa,d);d.o.aEa=function(a){d.o.DEBUG&&a&&void 0===a.nodeType&&d.o.If(a+" is not a DOM Node")};o_("Assert.assertDomNodeOrNull",d.o.aEa,d);d.o.XW=function(a){d.o.DEBUG&&(a&&void 0!==a.nodeType||d.o.If(a+" is not a DOM Node"))};o_("Assert.assertDomNode",d.o.XW,d);d.o.WW=function(a,c){d.o.DEBUG&&(d.o.XW(a),1!==a.nodeType?d.o.If(a+" is not a DOM Element"):c&&a.nodeName!==c&&d.o.If(a+" is not a "+c+" Element"))};o_("Assert.assertDomElement",
d.o.WW,d);d.o.$Da=function(a,c){d.o.DEBUG&&null!=a&&(d.o.XW(a),1!==a.nodeType?d.o.If(a+" is not a DOM Element"):c&&a.nodeName!==c&&d.o.If(a+" is not a "+c+" Element"))};o_("Assert.assertDomElementOrNull",d.o.$Da,d);d.o.Nk=function(a,c,b,e,f){!d.o.DEBUG||null==a&&f||typeof a===c||(a=a+" is not of type "+c,b&&(a=b+a),d.o.If(a))};o_("Assert.assertType",d.o.Nk,d);d.o.di=function(a,c){d.o.DEBUG&&d.o.Nk(a,"object",c,0,!1)};o_("Assert.assertObject",d.o.di,d);d.o.pda=function(a,c){d.o.DEBUG&&d.o.Nk(a,"object",
c,0,!0)};o_("Assert.assertObjectOrNull",d.o.pda,d);d.o.cEa=function(a,c){d.o.DEBUG&&(d.o.Nk(a,"string",c,0,!1),d.o.assert(0<a.length,"empty string"))};o_("Assert.assertNonEmptyString",d.o.cEa,d);d.o.Gq=function(a,c){d.o.DEBUG&&d.o.Nk(a,"string",c,0,!1)};o_("Assert.assertString",d.o.Gq,d);d.o.YW=function(a,c){d.o.DEBUG&&d.o.Nk(a,"string",c,0,!0)};o_("Assert.assertStringOrNull",d.o.YW,d);d.o.et=function(a,c){d.o.DEBUG&&d.o.Nk(a,"function",c,0,!1)};o_("Assert.assertFunction",d.o.et,d);d.o.Fz=function(a,
c){d.o.DEBUG&&d.o.Nk(a,"function",c,0,!0)};o_("Assert.assertFunctionOrNull",d.o.Fz,d);d.o.oda=function(a,c){d.o.DEBUG&&d.o.Nk(a,"boolean",c,0,!1)};o_("Assert.assertBoolean",d.o.oda,d);d.o.Fq=function(a,c){d.o.DEBUG&&d.o.Nk(a,"number",c,0,!1)};o_("Assert.assertNumber",d.o.Fq,d);d.o.eEa=function(a,c){d.o.DEBUG&&d.o.Nk(a,"number",c,0,!0)};o_("Assert.assertNumberOrNull",d.o.eEa,d);d.o.sL=function(a,c){d.o.DEBUG&&!Array.isArray(a)&&(void 0===c&&(c=a+" is not an array"),d.o.If(c))};o_("Assert.assertArray",
d.o.sL,d);d.o.HE=function(a,c){d.o.DEBUG&&null!=a&&!Array.isArray(a)&&(void 0===c&&(c=a+" is not an array"),d.o.If(c))};o_("Assert.assertArrayOrNull",d.o.HE,d);d.o.dEa=function(a,c){d.o.DEBUG&&!isNaN(a)&&(void 0===c&&(c=a+" is convertible to a number"),d.o.If(c))};o_("Assert.assertNonNumeric",d.o.dEa,d);d.o.fEa=function(a,c){d.o.DEBUG&&isNaN(a)&&(void 0===c&&(c=a+" is not convertible to a number"),d.o.If(c))};o_("Assert.assertNumeric",d.o.fEa,d);d.o.bEa=function(a,c,b){var e;if(null==a||void 0===
c[a.toString()]){if(void 0===b){b=" is not in set: {";for(e in c)c.hasOwnProperty(e)&&(b+=e,b+=",");b=a+(b+"}")}d.o.If(b)}};o_("Assert.assertInSet",d.o.bEa,d);d.o.If=function(a,c,b){c="Assertion";b&&(c+=" ("+b+")");c+=" failed: ";void 0!==a&&(c+=a);throw Error(c);};o_("Assert.assertionFailed",d.o.If,d);var f=c.__oj_Assert_DEBUG;void 0!==f&&(d.o.DEBUG=f);d.mj=function(){this.Init()};o_("EventSource",d.mj,d);d.b.ta(d.mj,d.b,"oj.EventSource");d.mj.prototype.Init=function(){this.Ue=[];d.mj.t.Init.call(this)};
d.b.g("EventSource.prototype.Init",{Init:d.mj.prototype.Init});d.mj.prototype.on=function(a,c){var b=!1,d;for(d=0;d<this.Ue.length;d++)if(this.Ue[d].eventType==a&&this.Ue[d].eventHandlerFunc==c){b=!0;break}b||this.Ue.push({eventType:a,eventHandlerFunc:c})};d.b.g("EventSource.prototype.on",{on:d.mj.prototype.on});d.mj.prototype.off=function(a,c){var b;for(b=this.Ue.length-1;0<=b;b--)if(this.Ue[b].eventType==a&&this.Ue[b].eventHandlerFunc==c){this.Ue.splice(b,1);break}};d.b.g("EventSource.prototype.off",
{off:d.mj.prototype.off});d.mj.prototype.handleEvent=function(a,c){var b,d;for(b=0;b<this.Ue.length;b++)if(d=this.Ue[b],d.eventType==a&&(d=d.eventHandlerFunc.apply(this,Array.prototype.slice.call(arguments).slice(1)),!1===d))return!1;return!0};d.b.g("EventSource.prototype.handleEvent",{handleEvent:d.mj.prototype.handleEvent});d.fa={};o_("Config",d.fa,d);d.fa.Wi=function(){var a;if(d.Rx())return d.o.assert(void 0!==g,"ojtranslations module must be defined"),a=g._ojLocale_,"root"==a?"en":a;a=d.fa.Uy;
null==a&&((a=document.documentElement.lang)||(a=void 0===navigator?"en":(navigator.language||navigator.userLanguage||"en").toLowerCase()),d.fa.Uy=a=a.toLowerCase());return a};o_("Config.getLocale",d.fa.Wi,d);d.fa.hJa=function(c,b){if(d.Rx()){var e=["ojL10n!ojtranslations/nls/"+c+"/ojtranslations"],f=0;if(d.hb&&(e.push("ojL10n!ojtranslations/nls/"+c+"/localeElements"),d.Em)){var s=d.Em.kna(),f=s.length;s.forEach(function(a){e.push("ojL10n!ojtranslations/nls/"+c+a)})}a(e,function(a,c){g=a;c&&d.hb.ona(c);
for(var e=0;e<f;e++)d.Em.L2(arguments[e+2]);b&&b()})}else d.fa.Uy=c,b&&b()};o_("Config.setLocale",d.fa.hJa,d);d.fa.eb=function(c){var b=/^\/|:/;return null==c||b.test(c)?c:(b=d.fa.WAa)?b+("/"==b.charAt(b.length-1)?"":"/")+c:d.Rx()?(b=a.toUrl("ojs/_foo_"),b.replace(/[^\/]*$/,"../"+c)):c};o_("Config.getResourceUrl",d.fa.eb,d);d.fa.iJa=function(a){d.fa.WAa=a};o_("Config.setResourceBaseUrl",d.fa.iJa,d);d.fa.fJa=function(a){d.fa.poa=a};o_("Config.setAutomationMode",d.fa.fJa,d);d.fa.FX=function(){return d.fa.poa};
o_("Config.getAutomationMode",d.fa.FX,d);d.fa.yfa=function(){var a="Oracle JET Version: "+d.version+"\n",a=a+("Oracle JET Revision: "+d.revision+"\n"),c="undefined"!==typeof window;c&&window.navigator&&(a+="Browser: "+window.navigator.userAgent+"\n",a+="Browser Platform: "+window.navigator.platform+"\n");$&&($.fn&&(a+="jQuery Version: "+$.fn.jquery+"\n"),$.ui&&$.ui.version&&(a+="jQuery UI Version: "+$.ui.version+"\n"));d.za&&(a+="Knockout Version: "+d.za.mna()+"\n");c&&window.QIa&&(a+="Require Version: "+
window.QIa.version+"\n");return a};o_("Config.getVersionInfo",d.fa.yfa,d);d.fa.VHa=function(){console.log(d.fa.yfa())};o_("Config.logVersionInfo",d.fa.VHa,d);d.Za=function(){};d.Za.rm={mO:"ie",m_:"firefox",xO:"safari",aja:"chrome",nja:"edge",mB:"unknown"};d.Za.Tn={p0:"trident",NO:"webkit",p_:"gecko",$ia:"blink",oja:"edgehtml",mB:"unknown"};d.Za.zm={qka:"Windows",bka:"Solaris",F_:"Mac",mB:"Unknown",$Z:"Android",oO:"IOS",Gja:"Linux"};d.Za.Rz=function(){var a;d.bb.Vl(a)&&(a=navigator.userAgent);a=a.toLowerCase();
var c=d.bb.rw(a),b=d.Za.Mqa;if(b&&b.hashCode===c)return{os:b.os,browser:b.browser,browserVersion:b.browserVersion,engine:b.engine,engineVersion:b.engineVersion,hashCode:b.hashCode};var b=d.Za.zm.mB,e=d.Za.rm.mB,f=0,g=d.Za.Tn.mB,r=0;-1<a.indexOf("iphone")||-1<a.indexOf("ipad")?b=d.Za.zm.oO:-1<a.indexOf("mac")?b=d.Za.zm.F_:-1<a.indexOf("sunos")?b=d.Za.zm.bka:-1<a.indexOf("android")?b=d.Za.zm.$Z:-1<a.indexOf("linux")?b=d.Za.zm.Gja:-1<a.indexOf("win")&&(b=d.Za.zm.qka);-1<a.indexOf("msie")?(e=d.Za.rm.mO,
f=d.Za.Gk(a,/msie (\d+[.]\d+)/),a.indexOf("trident")&&(g=d.Za.Tn.p0,r=d.Za.Gk(a,/trident\/(\d+[.]\d+)/))):-1<a.indexOf("trident")?(e=d.Za.rm.mO,f=d.Za.Gk(a,/rv:(\d+[.]\d+)/),a.indexOf("trident")&&(g=d.Za.Tn.p0,r=d.Za.Gk(a,/trident\/(\d+[.]\d+)/))):-1<a.indexOf("edge")?(e=d.Za.rm.nja,f=r=d.Za.Gk(a,/edge\/(\d+[.]\d+)/),g=d.Za.Tn.oja):-1<a.indexOf("chrome")?(e=d.Za.rm.aja,f=d.Za.Gk(a,/chrome\/(\d+[.]\d+)/),28<=f?(g=d.Za.Tn.$ia,r=f):(g=d.Za.Tn.NO,r=d.Za.Gk(a,/applewebkit\/(\d+[.]\d+)/))):-1<a.indexOf("safari")?
(e=d.Za.rm.xO,f=d.Za.Gk(a,/version\/(\d+[.]\d+)/),g=d.Za.Tn.NO,r=d.Za.Gk(a,/applewebkit\/(\d+[.]\d+)/)):-1<a.indexOf("firefox")&&(e=d.Za.rm.m_,f=d.Za.Gk(a,/rv:(\d+[.]\d+)/),g=d.Za.Tn.p_,r=d.Za.Gk(a,/gecko\/(\d+)/));b=d.Za.Mqa={hashCode:c,os:b,browser:e,browserVersion:f,engine:g,engineVersion:r};return{os:b.os,browser:b.browser,browserVersion:b.browserVersion,engine:b.engine,engineVersion:b.engineVersion,hashCode:b.hashCode}};d.Za.Gk=function(a,c){var b=a.match(c);return b&&(b=b[1])?parseFloat(b):
0};d.nd=function(){};o_("ThemeUtils",d.nd,d);d.nd.qGa=function(){return(d.nd.uf("oj-theme-json")||{}).name};o_("ThemeUtils.getThemeName",d.nd.qGa,d);d.nd.rGa=function(){return(d.nd.uf("oj-theme-json")||{}).targetPlatform};o_("ThemeUtils.getThemeTargetPlatform",d.nd.rGa,d);d.nd.CEa=function(){this.IH=null};o_("ThemeUtils.clearCache",d.nd.CEa,d);d.nd.uf=function(a){null==this.IH&&(this.IH={},this.s$={},this.twa=window.getComputedStyle(document.head).getPropertyValue("font-family"));var c=this.IH[a];
if(c===this.s$)return null;if(null!=c)return c;var b=document.createElement("meta");b.className=a;document.head.appendChild(b);var e=window.getComputedStyle(b).getPropertyValue("font-family");if(null!=e)if(e==this.twa)d.r.warn("parseJSONFromFontFamily: When the selector ",a," is applied the font-family read off the dom element is ",e,". The parent dom elment has the same font-family value."," This is interpreted to mean that no value was sent down for selector ",a,". Null will be returned.");else if(e=
e.replace(/^['"]+|\s+|\\|(;\s?})+|['"]$/g,""))try{c=JSON.parse(e)}catch(f){throw d.r.error("Error parsing json for selector "+a+".\nString being parsed is "+e+". Error is:\n",f),document.head.removeChild(b),f;}document.head.removeChild(b);this.IH[a]=null==c?this.s$:c;return c};o_("ThemeUtils.parseJSONFromFontFamily",d.nd.uf,d);d.dc=function(){};o_("ResponsiveUtils",d.dc,d);d.dc.Am={SM:"sm",MD:"md",LG:"lg",XL:"xl",XXL:"xxl"};o_("ResponsiveUtils.SCREEN_RANGE",d.dc.Am,d);d.dc.cx={SM_UP:"sm-up",MD_UP:"md-up",
LG_UP:"lg-up",XL_UP:"xl-up",XXL_UP:"xxl-up",SM_ONLY:"sm-only",MD_ONLY:"md-only",LG_ONLY:"lg-only",XL_ONLY:"xl-only",MD_DOWN:"md-down",LG_DOWN:"lg-down",XL_DOWN:"xl-down",HIGH_RESOLUTION:"high-resolution"};o_("ResponsiveUtils.FRAMEWORK_QUERY_KEY",d.dc.cx,d);d.dc.Iu={};d.dc.Iu[d.dc.Am.SM]=0;d.dc.Iu[d.dc.Am.MD]=1;d.dc.Iu[d.dc.Am.LG]=2;d.dc.Iu[d.dc.Am.XL]=3;d.dc.Iu[d.dc.Am.XXL]=4;d.dc.qta=function(a){var c=document.getElementsByClassName(a).item(0);null===c&&(c=document.createElement("meta"),c.className=
a,document.head.appendChild(c));return window.getComputedStyle(c).getPropertyValue("font-family").replace(/^[\/\\'"]+|(;\s?})+|[\/\\'"]+$/g,"")};d.dc.Sz=function(a){a=d.dc.qta("oj-mq-"+a);return"null"==a?null:a};o_("ResponsiveUtils.getFrameworkQuery",d.dc.Sz,d);d.dc.compare=function(a,c){var b=d.dc.Iu[a],e=d.dc.Iu[c];if(void 0==b)throw"size1 param "+a+" illegal, please use one of the screen size constants like oj.ResponsiveUtils.SCREEN_RANGE.MD";if(void 0==e)throw"size2 param "+c+" illegal, please use one of the screen size constants like oj.ResponsiveUtils.SCREEN_RANGE.MD";
return b-e};o_("ResponsiveUtils.compare",d.dc.compare,d);d.bb={};o_("StringUtils",d.bb,d);d.bb.cna=/^\s*|\s*$/g;d.bb.mi=function(a){return null===a?!0:0===d.bb.trim(a).length};o_("StringUtils.isEmpty",d.bb.mi,d);d.bb.Vl=function(a){return void 0===a||d.bb.mi(a)?!0:!1};o_("StringUtils.isEmptyOrUndefined",d.bb.Vl,d);d.bb.Ke=function(a){return null!==a&&("string"===typeof a||a instanceof String)};o_("StringUtils.isString",d.bb.Ke,d);d.bb.trim=function(a){return d.bb.Ke(a)?a.replace(d.bb.cna,""):a};o_("StringUtils.trim",
d.bb.trim,d);d.bb.rw=function(a){var c=0;if(0===a.length)return c;for(var b=0;b<a.length;b++)c=(c<<5)-c+a.charCodeAt(b),c&=c;return c};d.Wc={};o_("CollectionUtils",d.Wc,d);d.Wc.pf=function(a,c,b,e,f){return d.Wc.E4(a,c,b,e,f,0)};o_("CollectionUtils.copyInto",d.Wc.pf,d);d.Wc.isPlainObject=function(a){if("object"===typeof a)try{if(a.constructor&&a.constructor.prototype.hasOwnProperty("isPrototypeOf"))return!0}catch(c){}return!1};o_("CollectionUtils.isPlainObject",d.Wc.isPlainObject,d);d.Wc.E4=function(a,
c,b,e,f,g){var r,n,p;if(void 0===f||null===f)f=Number.MAX_VALUE;if(a&&c&&a!==c){p=Object.keys(c);for(var q=0;q<p.length;q++){r=p[q];n=b?b(r):r;r=c[r];var u=!1;if(e&&g<f){var v=a[n];d.Wc.isPlainObject(r)&&(null==v||d.Wc.isPlainObject(v))&&(u=!0,a[n]=v||{},d.Wc.E4(a[n],r,b,!0,f,g+1))}u||(a[n]=r)}}return a};d.va={};o_("Translations",d.va,d);d.va.rZ=function(a){d.va.BQ=a};o_("Translations.setBundle",d.va.rZ,d);d.va.cfa=function(a){return d.va.u7(a)};o_("Translations.getResource",d.va.cfa,d);d.va.Lc=function(a,
c){return null==a?null:d.va.hsa(a,c)};o_("Translations.applyParameters",d.va.Lc,d);d.va.F=function(a,c){var b=d.va.u7(a);if(null==b)return a;var e={};2<arguments.length?e=Array.prototype.slice.call(arguments,1):2==arguments.length&&(e=arguments[1],"object"===typeof e||e instanceof Array||(e=[e]));return d.va.Lc(b,e)};o_("Translations.getTranslatedString",d.va.F,d);d.va.VL=function(a){a=d.va.m6()[a];var c,b;if(null==a)return{};c={};for(b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c};o_("Translations.getComponentTranslations",
d.va.VL,d);d.va.u7=function(a){a=a?a.split("."):[];var c=d.va.m6(),b=a.length,e=0,f=a[e];for(d.o.di(c);0<--b&&c;)c=c[f],e++,f=a[e];return c?c[f]||null:null};d.va.hsa=function(a,c){var b=a.length,d=[],e=null,f=!1,g=!1,n=!1,p=!1,q,u;for(u=0;u<b;u++){var v=a.charAt(u),w=!1;if(f)w=!0,f=!1;else switch(v){case "$":f=!0;break;case "{":p||(g||(q=!1,e=[]),g=!0);break;case "}":g&&0<e.length&&(g=c[e.join("")],d.push(void 0===g?"null":g));g=!1;break;case "[":g||(n?p=!0:n=!0);break;case "]":p?p=!1:n=!1;break;
default:w=!0}w&&(g?","==v||" "==v?q=!0:q||e.push(v):p||d.push(v))}return d.join("")};d.va.m6=function(){var a=d.va.BQ;return a?a:d.Rx()?(d.o.assert(void 0!==g,"ojtranslations module must be defined"),g):{}};d.eG=function(a){this.aI=a;this.Y2=window.performance.now();this.Fl=this.Y2.toString(36)+"_"+Math.random().toString(36)};Object.defineProperties(d.eG.prototype,{id:{get:function(){return this.Fl},enumerable:!0},description:{get:function(){if($.isFunction(this.aI))return this.aI();if(this.aI)return this.aI.toString()},
enumerable:!0}});d.eG.prototype.toString=function(){var a;a="oj.BusyState [id\x3d"+this.id;this.description&&(a+=", description\x3d"+this.description);return a+=", elapsed\x3d"+(window.performance.now()-this.Y2)+"]"};d.eG.prototype.Mq=function(a){return this.id===a.id&&this.description===a.description};d.ef=function(){this.Init()};o_("BusyContext",d.ef,d);d.b.ta(d.ef,d.b,"oj.BusyContext");d.ef.prototype.Init=function(){d.ef.t.Init.call(this);this.PK=new window.Map;this.c$={Vea:function(){this.IU||
(this.IU=new Promise(this.Voa.bind(this)));return this.IU},WIa:function(){this.gpa();this.JU&&this.JU(!0);this.JU=this.IU=null},hGa:function(a,c){var b,e=new Promise(function(e,f){b=window.setTimeout(function(){d.ef.X9(a);d.r.info("BusyContext.whenReady: rejected");var b=d.ef.Mg(a),e=Error("whenReady timeout of "+c+"ms expired with the following busy states: "+b.join(", "));e.busyStates=b;f(e)},c)});this.ZV.push(b);return Promise.race([this.Vea(),e])},gpa:function(){var a=this.ZV;this.ZV=[];for(var c=
0;c<a.length;c++)window.clearTimeout(a[c])},Voa:function(a){this.JU=a},ZV:[]}};d.ef.X9=function(a){d.r.option("level")===d.r.ou&&(d.r.info("\x3e\x3e Busy states: %d",a.size),a=d.ef.Mg(a),0<a.length&&d.r.info(a.join("\n")))};d.ef.Mg=function(a){var c=[];a.forEach(function(a){c.push(a)});return c};d.ef.prototype.RW=function(a){d.r.info("BusyContext.addBusyState: start");var c=this.PK;a=new d.eG(a.description);d.r.info("\x3e\x3e "+a);c.set(a.id,a);d.r.info("BusyContext.addBusyState: end");return this.iAa.bind(this,
a)};d.b.g("BusyContext.prototype.addBusyState",{RW:d.ef.prototype.RW});d.ef.prototype.whenReady=function(a){d.r.info("BusyContext.whenReady: start, timeout:%d",a);var c=this.PK;if(0===c.size)return d.r.info("BusyContext.whenReady: resolved"),Promise.resolve(!0);var b=this.c$;a=isNaN(a)?b.Vea():b.hGa(c,a);d.r.info("BusyContext.whenReady: end");return a};d.b.g("BusyContext.prototype.whenReady",{whenReady:d.ef.prototype.whenReady});d.ef.prototype.mga=function(){d.r.info("BusyContext.isReady: start");
var a=this.PK,c=0===a.size;d.ef.X9(a);d.r.info("BusyContext.isReady: end");return c};d.b.g("BusyContext.prototype.isReady",{mga:d.ef.prototype.mga});d.ef.prototype.iAa=function(a){var c=this.PK;if(!c["delete"](a.id))throw Error("Busy state has already been resolved:\n"+a);0===c.size&&(a=this.c$,d.r.info("BusyContext._removeBusyState: resolving whenReady promises"),a.WIa());d.r.info("BusyContext._removeBusyState: end")};d.ef.prototype.kda=function(){if("oj_whenReady"in window&&window.oj_whenReady){var a=
this.z3;this.z3=null;a?a():d.r.NLa("BusyContext.applicationBoostrapComplete already invoked.")}else d.r.info("BusyContext.applicationBoostrapComplete: strategy not enabled.")};d.b.g("BusyContext.prototype.applicationBoostrapComplete",{kda:d.ef.prototype.kda});d.ef.prototype.jna=function(){"oj_whenReady"in window&&window.oj_whenReady&&(this.z3=this.RW({description:'Application loading. Busy state enabled by setting the "window.oj_whenReady \x3d true;" global variable. Application bootstrap busy state is released by calling "oj.Context.getPageContext().getBusyContext().applicationBoostrapComplete();".'}))};
d.Context=function(){this.Init()};o_("Context",d.Context,d);d.b.ta(d.Context,d.b,"oj.Context");d.Context.prototype.Init=function(){d.Context.t.Init.call(this)};d.Context.getContext=function(){return d.Context.UX()};d.Context.UX=function(){d.Context.D$||(d.Context.D$=new d.Context);return d.Context.D$};o_("Context.getPageContext",d.Context.UX,d);d.Context.prototype.GX=function(){this.E3||(this.E3=new d.ef);return this.E3};d.b.g("Context.prototype.getBusyContext",{GX:d.Context.prototype.GX});d.Context.UX().GX().jna();
(function(){function a(c,b){b=b||{bubbles:!1,cancelable:!1,detail:void 0};var d=document.createEvent("CustomEvent");d.initCustomEvent(c,b.bubbles,b.cancelable,b.detail);return d}"undefined"!==typeof window&&"function"!==typeof window.CustomEvent&&(a.prototype=window.Event.prototype,window.CustomEvent=a)})();(function(){d.jf={};d.jf.QE=function(b){var d={};if(b){var e=a.exec(b),e=e?e[1]:null;e||(d.cea=!0,e=(e=c.exec(b))?e[1]:null);d.expr=e}return d};d.jf.ZW=function(a){return a.toLowerCase().replace(/-(.)/g,
function(a,c){return c.toUpperCase()})};d.jf.EA=function(a){return a.replace(/([A-Z])/g,function(a){return"-"+a.toLowerCase()})};d.jf.xL=function(a,c,b){var e;switch(b.toLowerCase()){case "boolean":null==c||"true"===c||""===c||c.toLowerCase()===d.jf.EA(a)?e=!0:"false"===c&&(e=!1);break;case "number":isNaN(c)||(e=Number(c));break;case "string":e=c;break;default:try{e=JSON.parse(c)}catch(h){}}null==e&&d.r.error("Unable to parse value %s for property %s with type %s.",c,a,b);return e};var a=/(?:\{\{\s*)([^\s]+)(?:\s*\}\})/,
c=/(?:\[\[\s*)([^\s]+)(?:\s*\]\])/})();return d});