/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(a){a.ke=function(g,c,b,d,e){a.o.HE(b);this.cd=g;this.ng=c;this.PM=b;this.oa=d;this.$d=e};o_("CollectionHeaderSet",a.ke,a);a.ke.prototype.eia=function(g){a.o.sL(g);null!=g&&g.length===this.getCount()&&(this.Cw=g)};a.ke.prototype.getData=function(g,c){var b;a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");if(null!=this.oa){if(null==this.Cw)return null;b=this.Cw[g-this.cd];
return b.get(this.oa)}return this.PM[g]};a.b.g("CollectionHeaderSet.prototype.getData",{getData:a.ke.prototype.getData});a.ke.prototype.getMetadata=function(g,c){var b;a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");if(null!=this.oa){if(null==this.Cw)return null;b=this.Cw[g-this.cd];return{key:a.au.uy(b)}}b=this.getData(g,c);return this.$d.key===b?{key:b,sortDirection:this.$d.direction}:{key:b}};a.b.g("CollectionHeaderSet.prototype.getMetadata",
{getMetadata:a.ke.prototype.getMetadata});a.ke.prototype.getLevelCount=function(){return 0<this.getCount()?1:0};a.b.g("CollectionHeaderSet.prototype.getLevelCount",{getLevelCount:a.ke.prototype.getLevelCount});a.ke.prototype.getExtent=function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return{extent:1,more:{before:!1,after:!1}}};a.b.g("CollectionHeaderSet.prototype.getExtent",{getExtent:a.ke.prototype.getExtent});a.ke.prototype.getDepth=
function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return 1};a.b.g("CollectionHeaderSet.prototype.getDepth",{getDepth:a.ke.prototype.getDepth});a.ke.prototype.getCount=function(){return Math.max(0,this.ng-this.cd)};a.b.g("CollectionHeaderSet.prototype.getCount",{getCount:a.ke.prototype.getCount});a.ke.prototype.getStart=function(){return this.cd};a.b.g("CollectionHeaderSet.prototype.getStart",{getStart:a.ke.prototype.getStart});a.ke.prototype.Kea=
function(){return this.ng};a.b.g("CollectionHeaderSet.prototype.getEnd",{Kea:a.ke.prototype.Kea});a.ke.prototype.Rea=function(){return this.PM};a.b.g("CollectionHeaderSet.prototype.getHeaders",{Rea:a.ke.prototype.Rea});a.ke.prototype.WE=function(){return this.oa};a.b.g("CollectionHeaderSet.prototype.getRowHeader",{WE:a.ke.prototype.WE});a.yf=function(g,c,b,d,e){a.o.HE(e);this.Ba=g;this.jb=c;this.yp=b;this.zw=d;this.Nf=e};o_("CollectionCellSet",a.yf,a);a.yf.prototype.eia=function(g){a.o.sL(g);null!=
g&&g.length===this.getCount("row")&&(this.Cw=g)};a.yf.prototype.getData=function(a){var c,b;b=this.Rc(a);if(null==b)return null;c=this.Nf[a.column];a={};Object.defineProperty(a,"data",{get:function(){return b.get(c)},set:function(a){b.set(c,a,{silent:!0})}});return a};a.b.g("CollectionCellSet.prototype.getData",{getData:a.yf.prototype.getData});a.yf.prototype.getMetadata=function(g){var c;c=this.Rc(g);return null==c?null:{keys:{row:a.au.uy(c),column:this.Nf[g.column]}}};a.b.g("CollectionCellSet.prototype.getMetadata",
{getMetadata:a.yf.prototype.getMetadata});a.yf.prototype.Rc=function(g){var c;if(null==this.Cw)return null;a.o.di(g);c=g.row;g=g.column;a.o.assert(c>=this.Ba&&c<=this.jb&&g>=this.yp&&g<=this.zw);return this.Cw[c-this.Ba]};a.yf.prototype.getCount=function(a){return"row"===a?Math.max(0,this.jb-this.Ba):"column"===a?Math.max(0,this.zw-this.yp):0};a.b.g("CollectionCellSet.prototype.getCount",{getCount:a.yf.prototype.getCount});a.yf.prototype.lp=function(){return this.Ba};a.b.g("CollectionCellSet.prototype.getStartRow",
{lp:a.yf.prototype.lp});a.yf.prototype.Mea=function(){return this.jb};a.b.g("CollectionCellSet.prototype.getEndRow",{Mea:a.yf.prototype.Mea});a.yf.prototype.kp=function(){return this.yp};a.b.g("CollectionCellSet.prototype.getStartColumn",{kp:a.yf.prototype.kp});a.yf.prototype.Lea=function(){return this.zw};a.b.g("CollectionCellSet.prototype.getEndColumn",{Lea:a.yf.prototype.Lea});a.yf.prototype.nt=function(){return this.Nf};a.b.g("CollectionCellSet.prototype.getColumns",{nt:a.yf.prototype.nt});a.au=
function(){};a.au.uy=function(a){var c;c=a.Ci();null==c&&(c=a.ku());return c};a.Ua=function(g,c){this.cb=g;null!=c&&(this.TF=c.rowHeader,this.columns=c.columns);this.Mba();a.Ua.t.constructor.call(this)};o_("CollectionDataGridDataSource",a.Ua,a);a.b.ta(a.Ua,a.Dr,"oj.CollectionDataGridDataSource");a.Ua.prototype.Init=function(){a.Ua.t.Init.call(this);this.qr={};this.XD()};a.b.g("CollectionDataGridDataSource.prototype.Init",{Init:a.Ua.prototype.Init});a.Ua.prototype.XD=function(){this.cb.on("add",this.yva.bind(this));
this.cb.on("remove",this.Cva.bind(this));this.cb.on("change",this.zva.bind(this));this.cb.on("refresh",this.xua.bind(this));this.cb.on("reset",this.yua.bind(this))};a.Ua.prototype.pxa=function(){return null!=this.data};a.Ua.prototype.getCount=function(a){var c;void 0==this.precision&&(this.precision={});if("row"==a){c=this.Gf();if(-1===c||0===c&&(!this.pxa()||0<this.Ws()))return this.precision[a]="estimate",-1;this.precision[a]="exact";return this.Ws()}if("column"==a){if(null!=this.columns)return this.precision[a]=
"exact",this.columns.length;this.precision[a]="estimate";return-1}return 0};a.b.g("CollectionDataGridDataSource.prototype.getCount",{getCount:a.Ua.prototype.getCount});a.Ua.prototype.getCountPrecision=function(a){null!=this.precision&&null!=this.precision[a]||this.getCount(a);return this.precision[a]};a.b.g("CollectionDataGridDataSource.prototype.getCountPrecision",{getCountPrecision:a.Ua.prototype.getCountPrecision});a.Ua.prototype.fetchHeaders=function(a,c,b){var d,e;null!=c&&(d=a.axis,e={},e.Ufa=
a,e.callbacks=c,e.IE=b,this.qr[d]=e)};a.b.g("CollectionDataGridDataSource.prototype.fetchHeaders",{fetchHeaders:a.Ua.prototype.fetchHeaders});a.Ua.prototype.jva=function(g,c,b,d){var e,f,h,k;e=g.axis;f=g.start;h=g.count;if("column"===e)null!=this.columns&&(d=Math.min(this.columns.length,f+h),k=new a.ke(f,d,this.columns,void 0,this.iE));else if("row"===e&&null!=this.TF){null!=d&&(h=d.count);d=Math.min(this.Ws(),f+h);k=new a.ke(f,d,this.columns,this.TF);this.Uaa(f,d,k,g,c,b);return}null!=c&&c.success&&
c.success.call(b.success,k,g,null)};a.Ua.prototype.q7=function(a){var c,b,d,e,f,h;for(c=0;c<a.length;c+=1)b=a[c],"row"===b.axis?(d=b.start,e=b.count):"column"===b.axis&&(f=b.start,h=b.count);return{rowStart:d,rowCount:e,colStart:f,colCount:h}};a.Ua.prototype.pua=function(g,c,b,d){var e,f,h;e=this.q7(g);f=e.rowStart;d=null!=d?Math.min(this.Ws(),f+d.count):Math.min(this.Ws(),f+e.rowCount);h=e.colStart;e=Math.min(null==this.columns?0:this.columns.length,h+e.colCount);e=new a.yf(f,d,h,e,this.columns);
this.Uaa(f,d,e,g,c,b)};a.Ua.prototype.Uaa=function(a,c,b,d,e,f){var h;for(h=[];a<c;a++)h.push(this.cb.at(a,{deferred:!0}));Promise.all(h).then(function(a){b.eia(a);e.success.call(f.success,b,d)})};a.Ua.prototype.fetchCells=function(a,c,b){null!=c&&(this.fj={},this.fj.Ada=a,this.fj.callbacks=c,this.fj.IE=b);this.Qra(a)};a.b.g("CollectionDataGridDataSource.prototype.fetchCells",{fetchCells:a.Ua.prototype.fetchCells});a.Ua.prototype.R$=function(a){var c,b,d,e,f;c=this.qr[a];null!=c&&(b=c.Ufa,d=c.callbacks,
e=c.IE,"row"===a&&(f=c.QW),this.jva(b,d,e,f),this.qr[a]=null)};a.Ua.prototype.zza=function(){this.pua(this.fj.Ada,this.fj.callbacks,this.fj.IE,this.fj.QW)};a.Ua.prototype.Qra=function(a){var c;a=this.q7(a);c=a.rowStart;this.cb.UF(c,a.rowCount).then(function(a){this.data=!0;this.rBa(a.start,a.count);void 0===this.columns?this.cb.at(c,{deferred:!0}).then(function(a){null!=a&&this.QV(a);this.M5()}.bind(this)):this.M5()}.bind(this),function(a){this.Rra(a)}.bind(this))};a.Ua.prototype.Rra=function(g){a.r.error(g);
null!=this.qr&&(this.S$("column",g),this.S$("row",g));null!=this.fj&&this.Aza(g)};a.Ua.prototype.S$=function(a,c){var b,d,e;b=this.qr[a];null!=b&&(d=b.callbacks,e=b.IE,b=b.Ufa,d.error&&d.error.call(e.error,c,b),this.qr[a]=null)};a.Ua.prototype.Aza=function(a){var c,b,d;c=this.fj.callbacks;b=this.fj.IE;d=this.fj.Ada;c.error&&c.error.call(b.error,a,d);this.fj=null};a.Ua.prototype.M5=function(){null!=this.qr&&(this.R$("column"),this.R$("row"));null!=this.fj&&this.zza()};a.Ua.prototype.rBa=function(a,
c){var b={start:a,count:c};null!=this.qr.row&&(this.qr.row.QW=b);null!=this.fj&&(this.fj.QW=b)};a.Ua.prototype.QV=function(a){this.columns=a.keys();-1!=this.columns.indexOf(this.TF)&&this.columns.splice(this.columns.indexOf(this.TF),1)};a.Ua.prototype.keys=function(g){var c,b,d,e,f;c=g.row;b=g.column;f=this;return new Promise(function(g){f.cb.at(c,{deferred:!0}).then(function(c){null==c?g({row:null,column:null}):(d=a.au.uy(c),null==f.columns&&f.QV(c),e=f.columns[b],g({row:d,column:e}))}.bind(f))})};
a.b.g("CollectionDataGridDataSource.prototype.keys",{keys:a.Ua.prototype.keys});a.Ua.prototype.indexes=function(a){var c,b,d,e;c=a.row;b=a.column;e=this;return new Promise(function(a){e.cb.indexOf(c,{deferred:!0}).then(function(c){-1===c?a({row:-1,column:-1}):null==e.columns?e.cb.at(c,{deferred:!0}).then(function(g){e.QV(g);d=e.columns.indexOf(b);-1===d&&(c=-1);a({row:c,column:d})}.bind(e)):(d=e.columns.indexOf(b),-1===d&&(c=-1),a({row:c,column:d}))}.bind(e))})};a.b.g("CollectionDataGridDataSource.prototype.indexes",
{indexes:a.Ua.prototype.indexes});a.Ua.prototype.getCapability=function(a){return"sort"===a?"column":"move"===a?"row":null};a.b.g("CollectionDataGridDataSource.prototype.getCapability",{getCapability:a.Ua.prototype.getCapability});a.Ua.prototype.sort=function(a,c,b){var d,e,f;null==b&&(b={});null==a?this.zV(c,b):(e=a.direction,f=a.key,a=a.axis,"column"===a?(this.cb.Hb()?(this.cb.comparator=f,this.cb.sortDirection="ascending"===e?1:-1):("ascending"===e&&(d=function(a,b){var c,d;a=a.get(f);b=b.get(f);
c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString(),c=!0);b instanceof Date&&(b=b.toISOString(),d=!0);return c&&d?a<b?-1:a===b?0:1:c?1:d?-1:a-b}),"descending"===e&&(d=function(a,b){var c,d;a=a.get(f);b=b.get(f);c=isNaN(a);d=isNaN(b);a instanceof Date&&(a=a.toISOString());b instanceof Date&&(b=b.toISOString());return c&&d?a>b?-1:a===b?0:1:c?-1:d?1:b-a}),this.cb.comparator=d),this.cb.sort(),this.Mba(f),null!=c&&null!=c.success&&c.success.call(b.success)):null!=c&&null!=c.error&&c.error.call(b.error,
"Axis value not supported"))};a.b.g("CollectionDataGridDataSource.prototype.sort",{sort:a.Ua.prototype.sort});a.Ua.prototype.zV=function(a,c){this.cb.comparator=null;this.cb.reset();null!=a&&null!=a.success&&a.success.call(c.success)};a.Ua.prototype.Mba=function(a){var c,b;c=this.cb.comparator;b=-1===this.cb.sortDirection?"descending":"ascending";null==a&&"function"===typeof c?this.iE={}:(this.iE={},this.iE.axis="column",this.iE.direction=b,this.iE.key=null==a?c:null)};a.Ua.prototype.move=function(a,
c,b,d,e){var f;this.cb.get(a,{deferred:!0}).then(function(b){null==c?(this.cb.remove(b),this.cb.add(b),null!=d&&null!=d.success&&d.success.call(e.success)):(a===c?(f=this.cb.indexOf(c,{deferred:!0}),this.cb.remove(b)):(this.cb.remove(b),f=this.cb.indexOf(c,{deferred:!0})),f.then(function(a){this.cb.add(b,{at:a,oLa:!0});null!=d&&null!=d.success&&d.success.call(e.success)}.bind(this)))}.bind(this))};a.b.g("CollectionDataGridDataSource.prototype.move",{move:a.Ua.prototype.move});a.Ua.prototype.moveOK=
function(){return"valid"};a.b.g("CollectionDataGridDataSource.prototype.moveOK",{moveOK:a.Ua.prototype.moveOK});a.Ua.prototype.yo=function(a,c,b,d,e){var f={source:this};f.operation=a;f.keys={row:c,column:b};f.indexes={row:d,column:e};return f};a.Ua.prototype.yva=function(g){this.handleEvent("change",this.yo("insert",a.au.uy(g),null,g.index,-1))};a.Ua.prototype.Cva=function(g,c,b){this.handleEvent("change",this.yo("delete",a.au.uy(g),null,b.index,-1))};a.Ua.prototype.zva=function(g){this.handleEvent("change",
this.yo("update",a.au.uy(g),null,g.index,-1))};a.Ua.prototype.xua=function(){this.data=null;this.handleEvent("change",this.yo("refresh",null,null))};a.Ua.prototype.yua=function(){this.data=null;this.handleEvent("change",this.yo("reset",null,null))};a.Ua.prototype.Ws=function(){return this.cb.size()};a.Ua.prototype.Gf=function(){return void 0===this.cb.totalResults?-1:this.cb.totalResults};a.Ua.prototype.Aea=function(){return this.cb};a.b.g("CollectionDataGridDataSource.prototype.getCollection",{Aea:a.Ua.prototype.Aea});
a.Ua.prototype.nt=function(){return this.columns};a.b.g("CollectionDataGridDataSource.prototype.getColumns",{nt:a.Ua.prototype.nt});a.Ua.prototype.WE=function(){return this.TF};a.b.g("CollectionDataGridDataSource.prototype.getRowHeader",{WE:a.Ua.prototype.WE});a.Ua.prototype.getData=function(){return this.data};a.b.g("CollectionDataGridDataSource.prototype.getData",{getData:a.Ua.prototype.getData})});