/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(a){a.pg=function(a,c,b,d,e){this.jN=a;this.cb=c;this.fX=[];this.ZF=b;this.start=d<c.length?d:c.length-1;this.count=-1===e?c.length:Math.min(c.length,e)};o_("CollectionNodeSet",a.pg,a);a.pg.prototype.o_=function(a){this.N5(this).then(function(){a.success&&a.success()})};a.pg.prototype.N5=function(a){return new Promise(function(c){function b(e){e<d?a.sja(e,{success:function(c){null!==c?a.N5(c).then(function(){b(e+1)}):b(e+
1)}}):c(void 0)}var d=a.getCount();b(0)})};a.pg.prototype.sja=function(a,c){var b=this.cb.at(a);if(this.ZF.AA(b).leaf)this.fX[a]=null,c.success(null);else{var d=this.ZF.iG(b),b=this.ZF.AA(b).key,e=this;this.ZF.TA(d,0,-1,{success:function(b){e.fX[a]=b;c.success(b)}},b)}};a.pg.prototype.getParent=function(){return this.jN};a.b.g("CollectionNodeSet.prototype.getParent",{getParent:a.pg.prototype.getParent});a.pg.prototype.getStart=function(){return this.start};a.b.g("CollectionNodeSet.prototype.getStart",
{getStart:a.pg.prototype.getStart});a.pg.prototype.getCount=function(){return this.count};a.b.g("CollectionNodeSet.prototype.getCount",{getCount:a.pg.prototype.getCount});a.pg.prototype.getData=function(a){this.WQ(a);return this.cb.at(a).attributes};a.b.g("CollectionNodeSet.prototype.getData",{getData:a.pg.prototype.getData});a.pg.prototype.WQ=function(a){if(a<this.start||a>this.start+this.count)throw"Out of range";};a.pg.prototype.getMetadata=function(a){this.WQ(a);var c={};a=this.cb.at(a);a=this.ZF.AA(a);
c.key=a.key;c.leaf=a.leaf;c.depth=a.depth;return c};a.b.g("CollectionNodeSet.prototype.getMetadata",{getMetadata:a.pg.prototype.getMetadata});a.pg.prototype.ki=function(a){this.WQ(a);return this.fX[a]};a.b.g("CollectionNodeSet.prototype.getChildNodeSet",{ki:a.pg.prototype.ki});a.mb=function(g){g=g||{};this.RF=g.root;this.AEa=g.childCollectionCallback;this.AA=g.parseMetadata;this.Qw=null;this.JA="none";this.Kf={};a.mb.t.constructor.call(this)};o_("CollectionTreeDataSource",a.mb,a);a.mb.prototype.AA=
function(a){return{key:a.idAttribute+"\x3d"+a.id}};a.b.ta(a.mb,a.tu,"oj.CollectionTreeDataSource");a.mb.prototype.Init=function(){a.mb.t.Init.call(this)};a.b.g("CollectionTreeDataSource.prototype.Init",{Init:a.mb.prototype.Init});a.mb.prototype.ph=function(a){var c=this.Kf[a];if(c&&0<c.length)return c.length;this.IX(a,{success:function(a){return a.length}});return-1};a.b.g("CollectionTreeDataSource.prototype.getChildCount",{ph:a.mb.prototype.ph});a.mb.prototype.IX=function(a,c){this.ii(a,null,{success:function(a){c.success(a.cb)},
error:c.error})};a.b.g("CollectionTreeDataSource.prototype.getChildCollection",{IX:a.mb.prototype.IX});a.mb.prototype.ii=function(a,c,b){c=c||{};var d=c.start?c.start:0,e=c.count?c.count:-1;if(null===a)this.TA(null,d,e,b,null);else{var f=this;this.PS(this.RF,a,0).then(function(c){if(c){c=f.iG(c.Mt);try{f.TA(c,d,e,b,a)}catch(k){b&&b.error&&b.error({status:k.message})}}else b&&b.error&&b.error(a)})}};a.b.g("CollectionTreeDataSource.prototype.fetchChildren",{ii:a.mb.prototype.ii});a.mb.prototype.Oja=
function(a,c,b){var d=0;b&&b.at&&(d=b.at);c=this.ZI(c);a=this.VH(this,"insert",d,c,this.W$(null!=c&&0<c.length?c[c.length-1]:null,a));this.handleEvent("change",a)};a.mb.prototype.Pja=function(a,c,b){var d=0;b&&b.index&&(d=b.index);this.kAa(a);a=this.VH(this,"delete",d,this.ZI(c),null);this.handleEvent("change",a)};a.mb.prototype.Qja=function(a){var c=this.zsa(a),b=null,d=null;c&&(b=c.index,d=this.ZI(c.cb));a=this.VH(this,"update",b,d,this.W$(null!=d&&0<d.length?d[d.length-1]:null,a));this.handleEvent("change",
a)};a.mb.prototype.hja=function(a){a=this.VH(this,"refresh",null,this.ZI(a),null);this.handleEvent("refresh",a)};a.mb.prototype.W$=function(g,c){var b=new a.l;b.add(c);return this.g7(b,g,0,1)};a.mb.prototype.ZI=function(g){var c=[],b=null;do b=this.Dta(g),null!==b&&(b!==a.mb.V_&&c.unshift(b),g=this.Asa(b));while(null!=b);return c};a.mb.V_="%!@ROOT%#@!";a.mb.prototype.BI=function(g){var c=g instanceof a.D?this.AA(g).key:g;return g?c:a.mb.V_};a.mb.prototype.K2=function(a){return this.Kf[this.BI(a)]};
a.mb.prototype.qba=function(g,c){c.on(a.ka.Q.ADD,this.Oja,this);c.on(a.ka.Q.REMOVE,this.Pja,this);c.on(a.ka.Q.CHANGE,this.Qja,this);c.on(a.ka.Q.SYNC,this.hja,this);this.Kf[this.BI(g)]=c};a.mb.prototype.kAa=function(a){a=this.BI(a);for(var c in this.Kf)if(this.Kf.hasOwnProperty(c)&&c===a){this.Kf[a].off(null,null,this);delete this.Kf[a];break}};a.mb.prototype.Oxa=function(a,c){for(var b=c.length,d=0;d<b;d++){var e=this.BI(c.at(d));if(a===e)return!0}return!1};a.mb.prototype.zsa=function(a){for(var c in this.Kf)if(this.Kf.hasOwnProperty(c))for(var b=
this.Kf[c],d=0;d<b.length;d++)if(b.at(d)===a)return{index:d,cb:b};return null};a.mb.prototype.Asa=function(a){for(var c in this.Kf)if(this.Kf.hasOwnProperty(c)){var b=this.Kf[c];if(this.Oxa(a,b))return b}return null};a.mb.prototype.Dta=function(a){for(var c in this.Kf)if(this.Kf.hasOwnProperty(c)&&this.Kf[c]===a)return c;return null};a.mb.prototype.iG=function(a){var c=!0,b=this.K2(a);b||(c=!1,b=this.AEa(this.RF,a),null!=b&&(this.l3(b),this.qba(a,b)));return{cb:b,cX:c}};a.mb.prototype.VH=function(a,
c,b,d,e){return{source:a,operation:c,index:b,parent:d,data:e}};a.mb.prototype.TA=function(a,c,b,d,e){var f=this;null===a&&((a=this.K2(null))?a={cb:a,cX:!0}:(a={cb:f.RF,cX:!1},f.qba(null,this.RF)));a&&f.K5(a,function(a){d.success&&d.success(f.g7(a,e,c,b))},d.error)};a.mb.prototype.g7=function(g,c,b,d){return new a.pg(c,g,this,b,d)};a.mb.prototype.kBa=function(a,c){var b=this;return new Promise(function(d){function e(a,c,g){a<c.length?c.at(a,{deferred:!0}).then(function(l){if(l){var m=b.AA(l);if(g===
m.key){d(l);return}}a++;e(a,c,g)}):d(null)}e(0,a,c)})};a.mb.prototype.PS=function(a,c,b){var d=this;return new Promise(function(e){d.kBa(a,c).then(function(f){function h(d,f){if(d<k){var s=f.iG(a.at(d));s.cb?f.K5(s,function(a){f.PS(a,c,b+1).then(function(a){a?e(a):(d++,h(d,f))})},null):(d++,h(d,f))}else e(null)}if(f)e({Mt:f,depth:b});else{var k=a.length;h(0,d)}})})};a.mb.prototype.K5=function(a,c,b){a.cX?c(a.cb):(this.Qw&&"none"!==this.Qw&&(a.cb.Pl=this.Qw,a.cb.CZ=this.JA),0<a.cb.length||!a.cb.Eja()?
c(a.cb):a.cb.fetch({success:function(a){c(a)},error:b}))};a.mb.prototype.Pz=function(a,c){var b=this;null===a?this.TA(null,0,-1,{success:function(a){a.o_({success:function(){c.success&&c.success(a)}})}},null):this.PS(this.RF,a,0).then(function(d){d&&(d=b.iG(d.Mt),b.TA(d,0,-1,{success:function(a){a.o_({success:function(){c.success&&c.success(a)}})}},a))})};a.b.g("CollectionTreeDataSource.prototype.fetchDescendants",{Pz:a.mb.prototype.Pz});a.mb.prototype.sort=function(a,c){var b=a.key,d=a.direction,
e=!1;b!==this.Qw&&(this.Qw=b,e=!0);d!==this.JA&&(this.JA=d,e=!0);if(e){"none"===this.JA&&(this.Kf={});for(var f in this.Kf)this.Kf.hasOwnProperty(f)&&this.l3(this.Kf[f])}c&&c.success&&c.success()};a.b.g("CollectionTreeDataSource.prototype.sort",{sort:a.mb.prototype.sort});a.mb.prototype.l3=function(a){a.comparator=this.Qw;a.sortDirection="ascending"===this.JA?1:-1;a.sort()};a.mb.prototype.Tq=function(){return{key:this.Qw,direction:this.JA}};a.b.g("CollectionTreeDataSource.prototype.getSortCriteria",
{Tq:a.mb.prototype.Tq});a.mb.prototype.move=function(){a.o.kd()};a.b.g("CollectionTreeDataSource.prototype.move",{move:a.mb.prototype.move});a.mb.prototype.moveOK=function(){return"invalid"};a.b.g("CollectionTreeDataSource.prototype.moveOK",{moveOK:a.mb.prototype.moveOK});a.mb.prototype.getCapability=function(a){return"sort"===a?"default":"move"===a?"none":"batchFetch"===a||"fetchDescendants"===a?"disable":null};a.b.g("CollectionTreeDataSource.prototype.getCapability",{getCapability:a.mb.prototype.getCapability})});