/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,g){(function(){var c=0;a.Na("oj.ojCollapsible",g.oj.baseComponent,{widgetEventPrefix:"oj",options:{expanded:!1,disabled:null,expandOn:"click",expandArea:"header",beforeExpand:null,expand:null,beforeCollapse:null,collapse:null,optionChange:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-collapsible oj-component");this.Q$();this.Ff();this.Ij=!0;var a=this.element[0];this.WR({type:this.options.expanded?"ojexpand":
"ojcollapse",target:a,currentTarget:a,preventDefault:g.noop});this.Ij=void 0},ih:function(a,c,e){this.jh(c,e,{launcher:this.GC().first()})},aqa:function(){var a=this.options.expanded?"oj-collapsible-open-icon":"oj-collapsible-close-icon";(this.Il()?g("\x3cspan\x3e"):g("\x3ca href\x3d'#'\x3e")).addClass("oj-component-icon oj-clickable-icon-nocontext oj-collapsible-header-icon "+a).attr("aria-labelledby",this.header.attr("id")).prependTo(this.header)},i5:function(){this.header.children(".oj-collapsible-header-icon").remove()},
_destroy:function(){this.lo();this.element.removeClass("oj-collapsible oj-component oj-expanded oj-collapsed oj-disabled");this.Il()&&this.bS(this.header).removeAttr("tabIndex");this.header.removeClass("oj-collapsible-header").each(function(){/^oj-collapsible/.test(this.id)&&this.removeAttribute("id")});this.BC().removeAttr("role").removeAttr("aria-controls").removeAttr("aria-expanded").removeAttr("aria-disabled");this.i5();this.content.css("display","").removeAttr("aria-hidden").removeAttr("tabIndex").removeClass("oj-component-content oj-collapsible-content").each(function(){/^oj-collapsible/.test(this.id)&&
this.removeAttribute("id")})},lo:function(){this.rz();this.content&&(a.u.unwrap(this.content),this.Gp=null)},Il:function(){return this.element.hasClass("oj-disabled")},F6:function(){return"header"==this.options.expandArea?"\x3e .oj-collapsible-header":"\x3e .oj-collapsible-header \x3e .oj-collapsible-header-icon"},GC:function(){return this.header.find(".oj-collapsible-header-icon")},_setOption:function(a,c,e){"expanded"===a?c!==this.options.expanded&&this.FBa(c):"disabled"===a?(this.header.add(this.header.next()),
this.element.toggleClass("oj-disabled",!!c)):"expandOn"===a||"expandArea"===a?(this.rz(),this._super(a,c,e),this.nn()):this._super(a,c,e)},Ev:function(a){if(!a.altKey&&!a.ctrlKey){var c=g.ui.keyCode;switch(a.keyCode){case c.SPACE:case c.ENTER:this.Gca(a)}}},refresh:function(){this._super();this.lo();this.Q$();this.i5();this.Ff()},Q$:function(){this.header=this.element.children(":first-child").addClass("oj-collapsible-header");this.content=this.header.next().addClass("oj-collapsible-content oj-component-content");
this.content.wrap("\x3cdiv\x3e\x3c/div\x3e");this.Gp=this.content.parent().addClass("oj-collapsible-wrapper");this.options.disabled&&this.element.addClass("oj-disabled");this.Il()&&this.bS(this.header).attr("tabIndex",-1)},Ff:function(){var a=this.header,d=this.content,e=this.options,f="oj-collapsible-"+(this.element.attr("id")||++c),g=a.attr("id"),k=d.attr("id");g||a.attr("id",f+"-header");k||(k=f+"-content",d.attr("id",k));this.aqa();a=this.BC();a.attr("role","button").attr("aria-controls",k).attr("aria-expanded",
e.expanded);this.Il()&&a.attr("aria-disabled","true");e.expanded?d.removeAttr("aria-hidden"):(this.Gp.css({"max-height":0,"overflow-y":"hidden",display:"none"}),this.Gp.css("max-height",0),d.attr("aria-hidden","true"));this.nn()},FBa:function(a){a?this.expand(!0):this.collapse(!0)},nn:function(){var b={keydown:this.Ev},c=this.options.expandOn;if(c){var e=this;g.each(c.split(" "),function(c,d){a.u.AM(d)&&(b[d]=e.Gca)})}c=this.element.find(this.F6());this._on(c,b);this._on(this.Gp,{transitionend:this.xz,
webkitTransitionEnd:this.xz,otransitionend:this.xz,oTransitionEnd:this.xz});this.Il()||(this._on(this.element,{ojexpand:this.WR,ojcollapse:this.WR,ojfocus:this.c6,ojfocusout:this.c6}),this._focusable({element:this.GC(),applyHighlight:!0}),this.Qe(c),this.ok(c))},rz:function(){this._off(this.element.find(this.F6()));this.Gp&&this._off(this.Gp);this._off(this.element.add(this.content))},Gca:function(a){this.Il()||a.isDefaultPrevented()||(this.options.expanded?this.collapse(!0,a):this.expand(!0,a),a.preventDefault(),
a.stopPropagation(),this.GC().focus())},WR:function(b){if(!this.Il()&&b.target===this.element[0]&&(this.Ij||!b.isDefaultPrevented())){var c=this.element,e=this.options,f=this.content,g=this.Gp,k="ojexpand"===b.type;b.preventDefault();this.Ij?(e.expanded=k)?(c.removeClass("oj-collapsed"),c.addClass("oj-expanded"),a.Components.yr(g[0])):(c.removeClass("oj-expanded"),c.addClass("oj-collapsed"),g.css("max-height",0),g.hide(),a.Components.Wt(g[0])):(this.Woa(k,b),g.BL=g.outerHeight(),k?(g.show(),setTimeout(function(){g.BL+=
f.outerHeight();g.addClass("oj-collapsible-transition").css({"max-height":g.BL});c.removeClass("oj-collapsed");c.addClass("oj-expanded");a.Components.yr(g[0])},1)):(g.removeClass("oj-collapsible-transition"),g.css({"max-height":g.BL,"overflow-y":"hidden"}),setTimeout(function(){g.addClass("oj-collapsible-transition").css({"max-height":0});c.removeClass("oj-expanded");c.addClass("oj-collapsed");a.Components.Wt(g[0])},10)));this.GC().toggleClass("oj-collapsible-open-icon",k).toggleClass("oj-collapsible-close-icon",
!k||!1).end();k?this.content.removeAttr("aria-hidden"):this.content.attr("aria-hidden","true");this.BC().attr("aria-expanded",k)}},c6:function(a){if(this.Il())return null;"ojfocusout"==a.type?(this.BC().attr("tabIndex",-1),a.preventDefault(),a.stopPropagation()):"ojfocus"==a.type&&(this.BC().attr("tabIndex",0).focus(),a.preventDefault(),a.stopPropagation())},BC:function(){return this.bS(this.header).first()},bS:function(a){return this.Il()?a.find("span"):a.find("a,:input")},expand:function(a,c){if(!this.Il()){var e=
{header:this.header,content:this.content};a&&!1===this._trigger("beforeExpand",c,e)||this._trigger("expand",c,e)}},collapse:function(a,c){if(!this.Il()){var e={header:this.header,content:this.content};a&&!1===this._trigger("beforeCollapse",c,e)||this._trigger("collapse",c,e)}},xz:function(a){this.Il()||("max-height"==(a.originalEvent?a.originalEvent.propertyName:null)&&(a.preventDefault(),a.stopPropagation()),this.options.expanded?this.Gp.css({"max-height":9999,"overflow-y":""}):this.Gp.hide(),this.Gp.removeClass("oj-collapsible-transition"))},
Woa:function(a,c){this.option("expanded",a,{_context:{originalEvent:c,Ed:!0,ob:!0}})},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;switch(a.subId){case "oj-collapsible-content":return this.content[0];case "oj-collapsible-header":return this.header[0];case "oj-collapsible-disclosure":case "oj-collapsible-header-icon":return this.GC()[0]}return null},getSubIdByNode:function(a){for(var c=this.getNodeBySubId({subId:"oj-collapsible-disclosure"});a;){if(a===this.content[0])return{subId:"oj-collapsible-content"};
if(a===this.header[0])return{subId:"oj-collapsible-header"};if(a===c)return{subId:"oj-collapsible-disclosure"};a=a.parentElement}return null}})})();a.Components.Ta("ojCollapsible","baseComponent",{properties:{disabled:{type:"boolean"},expandArea:{type:"string"},expanded:{type:"boolean"},expandOn:{type:"string"}},methods:{collapse:{},expand:{},refresh:{}},extension:{_widgetName:"ojCollapsible"}});a.Components.register("oj-collapsible",a.Components.getMetadata("ojCollapsible"))});