/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojmodel"],function(a,g){a.sd=function(c,b){this.data={};if(!(c instanceof a.l))throw Error(a.aa.od._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.aa.od._ERR_DATA_INVALID_TYPE_DETAIL);a.sd.t.constructor.call(this,c,b);this.te=c;this.qna();this.Init();if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.lE=!0};o_("CollectionTableDataSource",a.sd,a);a.b.ta(a.sd,a.aa,"oj.CollectionTableDataSource");a.sd.prototype.Pl=null;a.b.g("CollectionTableDataSource.prototype.comparator",
{Pl:a.sd.prototype.Pl});a.sd.prototype.Init=function(){a.sd.t.Init.call(this)};a.b.g("CollectionTableDataSource.prototype.Init",{Init:a.sd.prototype.Init});a.sd.prototype.at=function(c,b){b=b||{};b.deferred=!0;var d=this.te.at(c,b),e=this;e.kD=!0;var f;return new Promise(function(b,g){null!=d?d.then(function(a){e.kD=!1;f={data:a.attributes,index:c,key:a.id};b(f)},function(b){e.kD=!1;a.aa.t.handleEvent.call(e,a.aa.Q.ERROR,b);g(b)}):b(null)})};a.b.g("CollectionTableDataSource.prototype.at",{at:a.sd.prototype.at});
a.sd.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||this.lE?this.Cg(a):Promise.resolve()};a.b.g("CollectionTableDataSource.prototype.fetch",{fetch:a.sd.prototype.fetch});a.sd.prototype.get=function(c,b){b=b||{};b.deferred=!0;var d=this.te.get(c,b),e=this,f;return new Promise(function(b,c){null!=d?d.then(function(a){f={data:a.attributes,index:a.index,key:a.id};b(f)},function(b){a.aa.t.handleEvent.call(e,a.aa.Q.ERROR,b);c(b)}):b(null)})};a.b.g("CollectionTableDataSource.prototype.get",
{get:a.sd.prototype.get});a.sd.prototype.sort=function(a){null==a?a=this.sortCriteria:this.sortCriteria=a;var b=this.comparator,d=this;return new Promise(function(e){null==b?(d.te.comparator=a.key,d.te.sortDirection="ascending"==a.direction?1:-1):d.te.comparator=b;d.te.sort(null);e({header:a.key,direction:a.direction})})};a.b.g("CollectionTableDataSource.prototype.sort",{sort:a.sd.prototype.sort});a.sd.prototype.totalSize=function(){var a=0<=this.te.totalResults?this.te.totalResults:-1;if(-1<a){var b=
this.te.size();return b>a?b:a}if(0<this.ZR)a=this.ZR;else if("atLeast"==this.totalSizeConfidence())return this.te.size();return a};a.b.g("CollectionTableDataSource.prototype.totalSize",{totalSize:a.sd.prototype.totalSize});a.sd.prototype.totalSizeConfidence=function(){return 0<=this.te.totalResults?"actual":this.te.hasMore?"atLeast":"unknown"};a.b.g("CollectionTableDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:a.sd.prototype.totalSizeConfidence});a.sd.prototype.qna=function(){var c=
this;this.te.on(a.ka.Q.SYNC,function(b){if(b instanceof a.l&&!c.kD&&!c.o9){var d=b.offset,e=b.lastFetchCount||b.lastFetchSize;0<e?(c.pa=d,c.Db=e,c.kD=!0,b.hx(d,d+e).then(function(a){c.kD=!1;var b=[],e=[],g,m;for(g=0;g<a.length;g++)null!=a[g]&&(m=a[g].clone(),b.push(m.attributes),e.push(m.id));c.Tm.call(c,{silent:!1},{data:b,keys:e,startIndex:d},null)})):(b=c.zy(),c.Tm.call(c,{silent:!1},b,null))}});this.te.on(a.ka.Q.ALLADDED,function(b,d){var e=[],f=[],g=[],k,l;for(k=0;k<d.length;k++)l=d[k].clone(),
e.push(l.attributes),f.push(l.id),g.push(l.index);a.aa.t.handleEvent.call(c,a.aa.Q.ADD,{data:e,keys:f,indexes:g})});this.te.on(a.ka.Q.ALLREMOVED,function(b,d){var e=[],f=[],g=[],k,l;for(k=0;k<d.length;k++)l=d[k].clone(),e.push(l.attributes),f.push(l.id),g.push(l.index);a.aa.t.handleEvent.call(c,a.aa.Q.REMOVE,{data:e,keys:f,indexes:g})});this.te.on(a.ka.Q.RESET,function(b){a.aa.t.handleEvent.call(c,a.aa.Q.RESET,b)});this.te.on(a.ka.Q.SORT,function(b,d){if(null==d||!d.add){var e={};null==b||null==!b.comparator||
g.isFunction(b.comparator)||(e.header=b.comparator,e.direction=1===b.sortDirection?"ascending":"descending");a.aa.t.handleEvent.call(c,a.aa.Q.SORT,e)}});this.te.on(a.ka.Q.CHANGE,function(b){a.aa.t.handleEvent.call(c,a.aa.Q.CHANGE,{data:[b.attributes],keys:[b.id],indexes:[b.index]})});this.te.on(a.ka.Q.DESTROY,function(b){a.aa.t.handleEvent.call(c,a.aa.Q.DESTROY,b)});this.te.on(a.ka.Q.REFRESH,function(b){a.aa.t.handleEvent.call(c,a.aa.Q.REFRESH,b)});this.te.on(a.ka.Q.ERROR,function(b,d,e){a.aa.t.handleEvent.call(c,
a.aa.Q.ERROR,b,d,e)})};a.sd.prototype.Cg=function(a){this.kE(a);a=a||{};var b=this;this.y9=0<a.pageSize?!0:!1;this.pa=null==a.startIndex?this.pa:a.startIndex;this.Db=0<a.pageSize?a.pageSize:-1;a.pageSize=this.Db;a.startIndex=this.pa;a.refresh=!0;return new Promise(function(d,e){var f=b.Db;b.y9||(f=25);b.te.UF(b.pa,f).then(function(e){var f;if(b.y9){f=[];var g=[],m,s;for(m=0;m<e.models.length;m++)s=e.models[m].clone(),f[m]=s.attributes,g[m]=s.id;f={data:f,keys:g,startIndex:b.pa};e.models.length<b.Db?
0>b.totalSize()&&(b.ZR=b.pa+e.models.length):b.ZR=null}else f=b.zy();b.Tm.call(b,a,f,null);d(f)},function(d){b.Tm.call(b,a,null,d);e(d)})})};a.sd.prototype.kE=function(c){this.o9=!0;c.silent||a.aa.t.handleEvent.call(this,a.aa.Q.REQUEST,{startIndex:c.startIndex})};a.sd.prototype.Tm=function(c,b,d){this.o9=!1;null!=d?a.aa.t.handleEvent.call(this,a.aa.Q.ERROR,d):c.silent||a.aa.t.handleEvent.call(this,a.aa.Q.SYNC,b)};a.sd.prototype.zy=function(){var a=this.te.size()-1,b=[],d=[],e,f,g;for(e=0;e<=a;e++)f=
this.te.at(e),g=f.clone(),f=this.Xo(g,g.attributes),b[e]=f,d[e]=g.id;return{data:b,keys:d,startIndex:this.pa}};a.sd.prototype.getCapability=function(){return null};a.b.g("CollectionTableDataSource.prototype.getCapability",{getCapability:a.sd.prototype.getCapability});a.sd.prototype.Xo=function(a,b){var d={},e;for(e in b)b.hasOwnProperty(e)&&function(){var b=e;Object.defineProperty(d,e,{get:function(){return a.get(b)},set:function(d){a.set(b,d,{silent:!0})},enumerable:!0})}();return d}});