/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","knockout","ojs/ojdatasource-common","ojs/ojmodel","ojs/ojknockout-model"],function(a,g,c){a.$b=function(a){this.cb=a;this.current=0;this.Init();this.ei=[];this.NV(10)};o_("CollectionPagingDataSource",a.$b,a);a.b.ta(a.$b,a.vm,"oj.CollectionPagingDataSource");a.$b.prototype.Init=function(){a.$b.t.Init.call(this)};a.b.g("CollectionPagingDataSource.prototype.Init",{Init:a.$b.prototype.Init});a.$b.prototype.bT=function(){return this.$m()?this.Jq:this.totalSize()-this.current};
a.$b.prototype.Nv=function(){this.ei=Array(this.bT());var a=this;return this.cb.hx(this.current,this.current+this.ei.length).then(function(c){for(var e=0;e<c.length;e++)a.ei[e]=c[e];a.UD();a.Bk=a.pa+a.ei.length-1})};a.$b.prototype.UD=function(){if(void 0!==this.Jn){this.Jn.removeAll();for(var b=0;b<this.ei.length;b++)this.Jn.push(a.kb.map(this.ei[b]))}};a.$b.prototype.Wq=function(){return this.ei};a.b.g("CollectionPagingDataSource.prototype.getWindow",{Wq:a.$b.prototype.Wq});a.$b.prototype.$E=function(){void 0===
this.Jn&&(this.Jn=c.observableArray(),this.UD());return this.Jn};a.b.g("CollectionPagingDataSource.prototype.getWindowObservable",{$E:a.$b.prototype.$E});a.$b.prototype.getPage=function(){return this.ge};a.b.g("CollectionPagingDataSource.prototype.getPage",{getPage:a.$b.prototype.getPage});a.$b.prototype.setPage=function(b,c){c=c||{};b=parseInt(b,10);try{a.$b.t.handleEvent.call(this,a.$c.Q.BEFOREPAGE,{page:b,previousPage:this.ge})}catch(e){return Promise.reject(null)}this.pageSize=null!=c.pageSize?
c.pageSize:this.pageSize;c.startIndex=b*this.pageSize;var f=this.ge;this.ge=b;this.pa=c.startIndex;var g=this;return new Promise(function(b,e){g.Cg(c).then(function(){a.$b.t.handleEvent.call(g,a.$c.Q.PAGE,{page:g.ge,previousPage:f});b(null)},function(){g.ge=f;g.pa=g.ge*g.pageSize;e(null)})})};a.b.g("CollectionPagingDataSource.prototype.setPage",{setPage:a.$b.prototype.setPage});a.$b.prototype.getStartItemIndex=function(){return this.pa};a.b.g("CollectionPagingDataSource.prototype.getStartItemIndex",
{getStartItemIndex:a.$b.prototype.getStartItemIndex});a.$b.prototype.getEndItemIndex=function(){return this.Bk};a.b.g("CollectionPagingDataSource.prototype.getEndItemIndex",{getEndItemIndex:a.$b.prototype.getEndItemIndex});a.$b.prototype.getPageCount=function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.pageSize)};a.b.g("CollectionPagingDataSource.prototype.getPageCount",{getPageCount:a.$b.prototype.getPageCount});a.$b.prototype.fetch=function(a){var c=a||{};if(void 0!==c.pageSize&&void 0!==
c.startIndex){if(!this.$m())return this.gK(null),Promise.resolve();this.Jq=c.startIndex+c.pageSize;var e=this;return this.Nv().then(function(){e.gK(null)})}return this.Cg(a)};a.b.g("CollectionPagingDataSource.prototype.fetch",{fetch:a.$b.prototype.fetch});a.$b.prototype.Cg=function(a){var c=a||{};void 0!==c.startIndex&&(this.current=c.startIndex);void 0!==c.pageSize&&(this.Jq=this.pageSize=c.pageSize);var e=this;return new Promise(function(a){try{e.cb.fetch({success:function(){e.Nv().then(function(){e.gK(c);
a({data:e.Wq(),startIndex:e.current})})}})}catch(b){e.Nv().then(function(){e.gK(c);a({data:e.Wq(),startIndex:e.current})})}})};a.$b.prototype.gK=function(a){a=a||{};a.silent||this.handleEvent("sync",{data:this.Wq(),startIndex:this.current});a.success&&a.success()};a.$b.prototype.handleEvent=function(b,c){return a.$b.t.handleEvent.call(this,b,c)};a.$b.prototype.$m=function(){return this.current+this.Jq<this.totalSize()};a.$b.prototype.NV=function(a){this.Jq=this.pageSize=a};a.$b.prototype.size=function(){var a=
this.Wq();return a?a.length:0};a.b.g("CollectionPagingDataSource.prototype.size",{size:a.$b.prototype.size});a.$b.prototype.totalSize=function(){return this.cb.length};a.b.g("CollectionPagingDataSource.prototype.totalSize",{totalSize:a.$b.prototype.totalSize});a.$b.prototype.totalSizeConfidence=function(){return"actual"};a.b.g("CollectionPagingDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:a.$b.prototype.totalSizeConfidence});a.$b.prototype.getCapability=function(){return null};a.b.g("CollectionPagingDataSource.prototype.getCapability",
{getCapability:a.$b.prototype.getCapability})});