/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","jqueryui-amd/widget","jqueryui-amd/unique-id","jqueryui-amd/keycode","jqueryui-amd/focusable","jqueryui-amd/tabbable","ojs/ojmessaging"],function(a,g){function c(a,b){function c(){var a=g(this),d=a.data(m);if(null!=d)for(var e=0;e<d.length;e++){var h=a.data("oj-"+d[e]);null!=h&&b(h)}}var d=g(a);d.hasClass(s)&&c.call(a);d.find("."+s).each(c)}function b(a){this.SL=function(){return a}}function d(a,b,c){Object.keys(b).forEach(function(d){var e=a[d]||[],h=b[d];c?e=e.concat(h):
e.push(h);a[d]=e});return a}function e(a,b,c,d,e,k,f){var g=c,l=!1,m={};delete d[e];Object.defineProperty(d,e,{get:function(){if(l||null!=a.nz)return g;var c=k(f?f():e);return h([b,c,g],m)},set:function(b){g=b;null!=a.nz?m[a.nz]=!0:l=!0},enumerable:!0})}function f(a){if(1===a.length){var c=a[0];return c instanceof b?c.SL():null}for(var c=!1,d=0;d<a.length&&!c;d++){var e=a[d];null!=e&&e instanceof b&&(c=!0)}return c?function(c){var d=[];a.forEach(function(a){null!=a&&a instanceof b?d.push(a.SL()(c)):
d.push(a)});return h(d)}:null}function h(a,b){for(var c=void 0,d=0;d<a.length;d++){var e=a[d];void 0!==e&&(c=g.isPlainObject(e)?k(g.isPlainObject(c)?[c,e]:[e],d==a.length-1?null:b,null):e)}return c}function k(a,b,c){for(var d={},e=a.length,h=0;h<e;h++)for(var f=a[h],l=Object.keys(f),m=0;m<l.length;m++){var t=l[m],r=null==b?null:null==c?t:c+"."+t;if(null==b||!b[r]){var s=f[t];void 0!==s&&(d[t]=g.isPlainObject(s)?k(g.isPlainObject(d[t])?[d[t],s]:[s],b,r):s)}}return d}function l(){return!0}a.Components=
{};o_("Components",a.Components,a);a.Components.Dp=function(b){var c=a.Components.e5||{};Object.keys(b).forEach(function(e){var h=b[e];if(!a.Wc.isPlainObject(h))throw"Invalid default options";c[e]=d(c[e]||{},h,!1)});a.Components.e5=c};o_("Components.setDefaultOptions",a.Components.Dp,a);a.Components.Hea=function(){return a.Components.e5||{}};o_("Components.getDefaultOptions",a.Components.Hea,a);a.Components.Lf=function(a){return new b(a)};o_("Components.createDynamicPropertyGetter",a.Components.Lf,
a);a.Components.Mf=function(a,b){var c=g(a),d=c.data(m);return d&&(null==b?b=d[0]:0>d.indexOf(b)&&(b=void 0),null!=b&&(d=c[b],"function"===typeof d))?d.bind(c):null};o_("Components.getWidgetConstructor",a.Components.Mf,a);a.Components.Tg=function(b){a.u.mea(b);c(b,function(a){a.Or()})};o_("Components.subtreeAttached",a.Components.Tg,a);a.Components.ti=function(a){c(a,function(a){a.sj()})};o_("Components.subtreeDetached",a.Components.ti,a);a.Components.yr=function(b){a.u.mea(b);c(b,function(a){a.Sp()})};
o_("Components.subtreeShown",a.Components.yr,a);a.Components.Wt=function(a){c(a,function(a){a.Km()})};o_("Components.subtreeHidden",a.Components.Wt,a);a.Components.oY=function(a){var b=a.data(m);return g.isArray(b)&&-1<b.indexOf("ojPopup")&&a.is("."+s)?!0:!1};a.Components.lna=function(b){for(var c={},e=a.Components.Hea(),h=b.length-1;0<=h;h--){var f=e[b[h]];void 0!==f&&(c=d(c,f,!0))}return c};a.Components.co="data-oj-container";var m="oj-component-names",s="oj-component-initnode";a.Components.OB=
"_ojwidget";a.Components.wx="_createPromise";a.Components.XO="_resolve";a.Components.WO="_promise";a.Components.ZO={};a.Components.qP={};a.Components.Ta=function(b,c,d){b=a.jf.EA(b.toLowerCase());c?(c=a.jf.EA(c.toLowerCase()),c=a.Wc.pf({},a.Components.getMetadata(c),void 0,!0),a.Components.qP[b]=a.Wc.pf(c,d,void 0,!0)):a.Components.qP[b]=d};a.Components.getMetadata=function(b){return a.Components.qP[b.toLowerCase()]};a.Components.register=function(b,c){if(b&&document.registerElement){var d=b.toLowerCase();
if(!a.Components.ZO[d]){a.Components.ZO[d]=!0;var e=a.Components.Hta(c);document.registerElement(d,{prototype:e})}}};a.Components.nga=function(b){return b?a.Components.ZO[b.toLowerCase()]:!1};a.Components.NFa=function(b){var c=b[a.Components.wx];c||(c={},c[a.Components.WO]=new Promise(function(b){c[a.Components.XO]=b}),b[a.Components.wx]=c);return c[a.Components.WO]};a.Components.Hta=function(b){var c=Object.create(HTMLElement.prototype),d=b.properties,e=b.methods;b=b.extension;var h=b._widgetName;
a.Components.tna(d,c);a.Components.sna(e,c);a.Components.zna(h,d,b,c);return c};a.Components.tna=function(b,c){Object.keys(b).forEach(function(b){a.Components.una(b,c)})};a.Components.una=function(b,c){Object.defineProperty(c,b,{configurable:!0,enumerable:!0,get:function(){return this[a.Components.OB]("option",b)},set:function(c){if(this[a.Components.OB])this[a.Components.OB]("option",b,c)}})};a.Components.sna=function(a,b){Object.keys(a).forEach(function(c){var d=a[c].params,e=[];d&&d.forEach(function(a){a=
a.name;-1===a.indexOf(".")&&e.push(a)});b[c]=new Function(e,"return this._ojwidget('"+c+(0<e.length?"', "+e.join():"'")+");")})};a.Components.zna=function(b,c,d,e){e.createdCallback=function(){var b=this[a.Components.wx];if(b){if(b=b[a.Components.XO])b(),delete this[a.Components.wx][a.Components.XO]}else this[a.Components.wx]={},this[a.Components.wx][a.Components.WO]=Promise.resolve()};e.attachedCallback=function(){if(this[a.Components.OB])a.Components.Tg(this);else{var e=d._innerElement,h=this;e&&
(h=(h=this.firstElementChild)&&h.tagName.toLowerCase()===e?h:a.Components.dqa(e,this,d._defaultAttrs,d._transferAttrs));var f=d._hasWrapper?{_wrapper:this}:{},k=this,l=!1;Object.keys(c).forEach(function(b){var d=a.jf.EA(b);k.hasAttribute(d)&&(d=k.getAttribute(d),a.jf.QE(d).expr?l=!0:f[b]=a.jf.xL(b,d,c[b].type))});l||this.classList.add("oj-complete");f.optionChange=function(a,b){this.dispatchEvent(new CustomEvent(b.option+"-changed",{detail:{value:b.value,previousValue:b.previousValue}}))};g(h)[b](f);
this[a.Components.OB]=a.Components.Mf(h,b)}};e.detachedCallback=function(){a.Components.ti(this)};e.attributeChangedCallback=function(b,d,e){var h=a.jf.ZW(b),f=c[h];f&&(this.dispatchEvent(new CustomEvent("attribute-changed",{detail:{attribute:b,value:e,previousValue:d}})),a.jf.QE(e).expr||(this[h]=a.jf.xL(h,e,f.type)))}};a.Components.dqa=function(a,b,c,d){var e=document.createElement(a);b.appendChild(e);a=[];for(var h=0;h<b.childNodes.length;h++)a.push(b.childNodes[h]);for(h=0;h<a.length;h++)b.appendChild(a[h]);
if(c)for(var f in c)e.setAttribute(f,c[f]);d&&d.forEach(function(a){b.hasAttribute(a)&&e.setAttribute(a,b.getAttribute(a))});g(e).append(g(b).children());return e};(function(){g.widget("oj.baseComponent",{options:{contextMenu:null,rootAttributes:null,optionChange:void 0,destroy:void 0},refresh:function(){this.ez=null},_createWidget:function(a,b){a&&(this.oe=a._wrapper);this.B$=this.options||{};this.z4=a||{};this._super(a,b);this.w0()},gH:function(){var a=this.options.rootAttributes;if(a){var b=this.widget();
if(null!=b){var c=a["class"];c&&b.addClass(c);if(c=a.style){var d=b.attr("style");d?b.attr("style",d+";"+c):b.attr("style",c)}a=g.extend({},a);delete a["class"];delete a.style;b.attr(a);delete a.id;a=Object.keys(a);if(a.length)throw Error("Unsupported values passed to rootAttributes option: "+a.toString());}}},_create:function(){this.IB(this.element);this.Xf(this.B$,this.z4);delete this.B$;delete this.z4;this._ComponentCreate();this.Hh();this.element.addClass(s)},Xf:function(a,b){this.nCa(a,b);this.Gwa(b)},
_ComponentCreate:function(){var a=this.element,b=this.widgetName,c=a.data(m);c||(c=[],a.data(m,c));0>c.indexOf(b)&&c.push(b)},Hh:function(){this.gH();this.Ql=this.eventNamespace+"contextMenu";this.Pba(!0)},w0:g.noop,IB:function(){},Sma:function(a){var b=this;this.BV=[];g.each(a,function(a,c){var d={},e=c.attributes;b.BV.push({element:c,attributes:d});g.each(e,function(a,b){d[b.name]={attr:b.value}})})},mla:function(a){var b=this.BV;if(void 0===b)return null;a=a[0];for(var c=0,d=b.length;c<d;c++){var e=
b[c];if(e.element===a)return e.attributes}return{}},Lx:function(){},xma:function(){g.each(this.BV,function(a,b){var c=g(b.element),d=b.attributes;if(1===c.length){for(var e=b.element.attributes,h=[],f=0,k=e.length;f<k;f++)e[f].name in d||h.push(e[f].name);f=0;for(k=h.length;f<k;f++)c.removeAttr(h[f]);for(var l in d)c.attr(l,d[l].attr)}})},IG:function(){return this.widgetFullName},uB:function(a,b,c){return b==c},F:function(b,c){var d={},e;2<arguments.length?d=Array.prototype.slice.call(arguments,1):
2==arguments.length&&(d=arguments[1],"object"===typeof d||d instanceof Array||(d=[d]));e=this.option(r+b);return null==e?b:a.va.Lc(e.toString(),d)},getNodeBySubId:function(a){return null==a||null==a.subId?this.element?this.element[0]:null:null},getSubIdByNode:function(){return null},destroy:function(){this._trigger("destroy");a.u.dispatchEvent(this.element[0],new CustomEvent("_ojDestroy"));this._super();this.vaa();this.element.removeClass(s);this.widget().removeClass("oj-disabled");this.sV(this.element);
var b=this.element,c=this.widgetName,d=b.data(m);d&&(c=d.indexOf(c),0<=c&&(d.splice(c,1),0===d.length&&b.removeData(m)));this.Lx();this.Z8?this.element.attr("contextmenu",this.Z8):this.element.removeAttr("contextmenu");this.ez=null},option:function(a,b){if(0===arguments.length)return g.widget.extend({},this.options);var c=arguments[0],d=c,e=null,h={};if("string"===typeof c){var d={},f=c.split("."),c=f.shift();if(f.length){var e=f.join("."),k;try{1<arguments.length&&(this.nz=e),k=d[c]=g.widget.extend({},
this.options[c])}finally{this.nz=null}for(c=0;c<f.length-1;c++)k[f[c]]=k[f[c]]||{},k=k[f[c]];c=f.pop();if(1===arguments.length)return void 0===k[c]?null:k[c];k[c]=b}else{if(1===arguments.length)return void 0===this.options[c]?null:this.options[c];d[c]=b}h=arguments[2]||h}else h=arguments[1]||h;null!=e&&(h=g.widget.extend({},h,{subkey:e}));(e=h?h._context:null)&&e.ob?this.gxa(d,h):this._setOptions(d,h);return this},gxa:function(a,b){for(var c in a){var d=a[c],e=this.options[c];this.options[c]=d;this.z$(c,
d,e,b)}},_setOptions:function(a,b){for(var c in a)this._setOption(c,a[c],b);return this},_setOption:function(a,b,c){var d=this.options[a];if("disabled"===a)this.options[a]=b,this.widget().toggleClass("oj-disabled",!!b).attr("aria-disabled",b),b&&this.sV(this.widget());else{try{var e=null==c?null:c.subkey;null!=e&&(this.nz=e);this._super(a,b)}finally{this.nz=null}"contextMenu"===a&&this.Pba(!1)}this.z$(a,b,d,c);return this},z$:function(a,b,c,d){var e=!1,h=null,f=!1,k=!1,l=null,m=null,t;d&&(e=d.changed,
h=d._context)&&(l=h.originalEvent,f=void 0===h.Ed?null!=l:h.Ed,k=h.readOnly,m=h.Nt,t=h.Ok);if(e||!this.uB(a,c,b))m=m||{},m.writeback=f?"shouldWrite":"shouldNotWrite",k&&(m.readOnly=!0),a={option:a,previousValue:c,value:b,optionMetadata:m},null!=t&&(a=g.extend({},t,a)),this._trigger("optionChange",l,a)},_trigger:function(a,b,c){return this.xW(a,b,c).proceed},xW:function(a,b,c){var d=this.options[a];c=c||{};b=g.Event(b,n);b.type=(this.widgetEventPrefix+a).toLowerCase();b.target=this.element[0];this.element.trigger(b,
c);return{proceed:!(g.isFunction(d)&&!1===d.apply(this.element[0],[b].concat(c))||b.isDefaultPrevented()),event:b}},Gwa:function(a){var b=this.element.attr("contextmenu");this.Z8=b;!b||"contextMenu"in a||this.option("contextMenu",document.getElementById(b),{_context:{ob:!0}})},Pba:function(b){this.vaa();if(this.options.contextMenu){var c=this.widget(),d=this.element;b&&!d.is(c)&&d.removeAttr("contextmenu");(b=g(this.options.contextMenu).attr("id"))&&c.attr("contextmenu",b);var e=this;this.L$=function(a){121==
a.which&&a.shiftKey&&e.x6().is(":visible")&&a.preventDefault()};var h=a.u.vO,f=!1,k=!1,l,m,t,r=null,s=function(a,b,d){f=d;var h=e.tS();if(f)c.one("touchend"+e.Ql,function(){h.Px(!0);setTimeout(function(){h.Px(!1)},50)});"touchstart"===r&&"contextmenu"===a.type||"contextmenu"===r&&"touchstart"===a.type?(r=null,clearTimeout(t)):a.isDefaultPrevented()||a.originalEvent&&a.originalEvent.defaultPrevented||e.Yf()||(e.ih(h,a,b),!e.x6().is(":visible")||(a.preventDefault(),document.addEventListener("keyup",
e.L$),"touchstart"!==a.type&&"contextmenu"!==a.type))||(r=a.type,t=setTimeout(function(){r=null},300))};this.n4=function(a){f&&(a.preventDefault(),a.stopPropagation(),f=!1)};c[0].addEventListener("click",this.n4,!0);c.on("touchstart"+this.Ql+" mousedown"+this.Ql+" keydown"+this.Ql+" ",function(a){if("mousedown"!==a.type||!e.tS().Px()){f=!1;if("touchstart"===a.type&&1===a.originalEvent.touches.length){var b=a.originalEvent.touches[0];l=b.pageX;m=b.pageY;k=!0;this.lR=setTimeout(s.bind(void 0,a,"touch",
!0),h)}return!0}}).on("touchmove"+this.Ql,function(a){a=a.originalEvent.touches[0];if(5<Math.abs(l-a.pageX)||5<Math.abs(m-a.pageY))k=!1,clearTimeout(this.lR);return!0}).on("touchend"+this.Ql+" touchcancel"+this.Ql,function(){k=!1;clearTimeout(this.lR);return!0}).on("keydown"+this.Ql+" contextmenu"+this.Ql,function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&s(a,k?"touch":"keydown"===a.type?"keyboard":"mouse",!1);return!0}).addClass(a.u.af()?"oj-menu-context-menu-launcher":void 0)}},rba:function(){this.Vu=
g(this.options.contextMenu).first();this.TH=this.Vu.data("oj-ojMenu");if(!this.TH)throw Error('"contextMenu" option set to "'+this.options.contextMenu+'", which does not reference a valid JET Menu.');var a=this;this.Vu.on("ojclose"+this.Ql,function(){document.removeEventListener("keyup",a.L$)})},tS:function(){this.TH||this.rba();return this.TH},x6:function(){this.Vu||this.rba();return this.Vu},vaa:function(){this.widget().removeAttr("contextmenu").off(this.Ql).removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",
this.n4,!0);this.Vu&&this.Vu.off(this.Ql);clearTimeout(this.lR);this.Vu=this.TH=void 0},ih:function(a,b,c){this.jh(b,c)},jh:function(a,b,c,d,e){b={launcher:this.element,position:{mouse:{my:"start top",at:"start bottom",of:a,collision:"flipfit"},touch:{my:"start\x3e40 center",at:"start bottom",of:a,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher",collision:"flipfit"}}[b]};var h={initialFocus:"menu"};c=e?g.extend(b,c,h):g.extend(!0,b,c,h);e=this.tS();e.qH=!0;e.open(a,c,
d);e.qH=!1},sV:function(a){a.removeClass("oj-hover oj-focus oj-focus-highlight oj-active");a.find(".oj-hover").removeClass("oj-hover");a.find(".oj-focus").removeClass("oj-focus");a.find(".oj-focus-highlight").removeClass("oj-focus-highlight");a.find(".oj-active").removeClass("oj-active")},Cv:function(){return!a.u.CIa()},Qe:function(a){var b;g.isPlainObject(a)?b=a.element:(b=a,a={});a=a.afterToggle||g.noop;b.on("mouseenter"+this.eventNamespace,this.Awa.bind(this,a)).on("mouseleave"+this.eventNamespace,
this.aU.bind(this,"oj-hover",a))},IP:function(a){a&&g(a).off("mouseenter"+this.eventNamespace+" mouseleave"+this.eventNamespace)},ok:function(b){var c;g.isPlainObject(b)?c=b.element:(c=b,b={});b=b.afterToggle||g.noop;if(a.u.af())c.on("touchstart"+this.eventNamespace,this.P2.bind(this,b)).on("touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace,this.aU.bind(this,"oj-active",b));c.on("mousedown"+this.eventNamespace,this.P2.bind(this,b)).on("mouseup"+this.eventNamespace,this.aU.bind(this,
"oj-active",b))},HP:function(a){a&&g(a).off("touchstart"+this.eventNamespace+" touchend"+this.eventNamespace+" touchcancel"+this.eventNamespace+" mousedown"+this.eventNamespace+" mouseup"+this.eventNamespace)},P2:function(a,b){var c=g(b.currentTarget);c.hasClass("oj-disabled")||"touchstart"!==b.type&&!this.Cv(b)||(c.addClass("oj-active"),a(b.type))},Awa:function(a,b){var c=g(b.currentTarget);!c.hasClass("oj-disabled")&&this.Cv(b)&&(c.addClass("oj-hover"),a(b.type))},aU:function(a,b,c){g(c.currentTarget).removeClass(a);
b(c.type)},_focusable:function(b){g.isPlainObject(b)||(b={element:b});b.component=this;a.u.cN(b)},Lu:function(a){if(a){g(a).off(this.eventNamespace);var b=this.bindings;b&&(this.bindings=g(b.not(a)))}},cfa:function(a){return this.option(r+a)},hd:function(){return a.u.wn()},Or:function(){this.ez=null},sj:function(){this.ez=null;this.sV(this.widget())},Sp:function(){},Km:function(){},Yf:function(){return this.options.disabled||this.h3?!0:!1},QB:function(a){this.h3=a},Zta:function(){var b=[],c=this,
d=0;this.Mca(function(e){e=0==d?c.IG():e.widgetFullName;d++;var h=a.va.VL(e);null==h||g.isEmptyObject(h)||b.push(e)});var e=b.length;return 0<e?function(){if(1==e)return a.va.VL(b[0]);for(var c={},d=e-1;0<=d;d--)g.widget.extend(c,a.va.VL(b[d]));return c}:null},Psa:function(){if(!this.ez){var b={};this.ez=b;for(var c=this.element[0],d=c,e=[];d;){var h=d.getAttribute,h=h?h.call(d,a.Components.co):null;null!=h&&e.push(h);d=d.parentNode}b.containers=e;b.element=c}return this.ez},nCa:function(a,b){var c=
this.options,d=this.Zta(),h=b[t];null==d||void 0!==h&&!g.isPlainObject(h)||e(this,void 0,b[t],c,t,d);this.Yxa(a,b)},Yxa:function(b,c){var d=this.options,k=[];this.Mca(function(a){k.push(a.widgetName)});k.push("default");var l=a.Components.lna(k);if(!g.isEmptyObject(l)){var m=this,t=function(){return m.Psa()},r;for(r in l){var s=c[r];if(void 0===s||g.isPlainObject(s)){var n=l[r];if(n){var B=f(n);B?e(this,b[r],s,d,r,B,t):(n=[b[r]].concat(n),n.push(s),d[r]=h(n))}}}}},Mca:function(a){for(var b=this.constructor.prototype;null!=
b&&"oj"===b.namespace;)a(b),b=Object.getPrototypeOf(b)}});delete g.fn.baseComponent})();a.Na=function(a,b,c,d){g.widget(a,b,c);d&&delete g.fn[a.split(".")[1]];if("oj.oj"===a.substring(0,5)||"oj._oj"===a.substring(0,6)){b=a.split(".");a=b[0];b=b[1];var e=a+"-"+b;g.expr[":"][("_"===b.substring(0,1)?"_"+a+"-"+b.substring(3):a+"-"+b.substring(2)).toLowerCase()]=function(a){return!!g.data(a,e)}}};var t="translations",r=t+".",n={isDefaultPrevented:function(){return!1},preventDefault:function(){this.isDefaultPrevented=
l},stopPropagation:function(){this.isPropagationStopped=l},stopImmediatePropagation:function(){this.isImmediatePropagationStopped=l}};g(document).ready(function(){var a=g("\x3cdiv style\x3d'border: 1px solid;border-color:red green;position: absolute;top: -999px;background-image: url(data:image/gif;base64,R0lGODlhAQABAIAAAP///wAAACwAAAAAAQABAAACAkQBADs\x3d);'\x3e\x3c/div\x3e"),b;a.appendTo("body");b=a.css("backgroundImage");a.css("borderTopColor")!=a.css("borderRightColor")&&(null==b||"none"!=b&&"url (invalid-url:)"!=
b)||g("body").addClass("oj-hicontrast");a.remove()});a.u={};a.u.ola="\x3chtml\x3e";a.u.nla="\x3c/html\x3e";a.u.Fla={SPAN:1,B:1,I:1,EM:1,BR:1,HR:1,LI:1,OL:1,UL:1,P:1,TT:1,BIG:1,SMALL:1,PRE:1};a.u.Ela={"class":1,style:1};a.u.FHa=function(b){return 0===b.indexOf(a.u.ola)&&b.lastIndexOf(a.u.nla)===b.length-7?!0:!1};a.u.BEa=function(b){var c=g(document.createElement("span")).get(0);(c.innerHTML=b)&&0<=b.indexOf("\x3c")&&a.u.d4(c);return c};a.u.d4=function(b){for(var c=b.childNodes,d,e,h,f,k,l=c.length-
1;0<=l;){if((d=c.item(l))&&1===d.nodeType)if(a.u.Fla[d.nodeName]){e=d.attributes;for(k=e.length-1;0<=k;k--)h=e[k],(f=void 0!==g(d).attr(h.name))&&(a.u.Ela[h.name]||d.removeAttribute(h.nodeName));a.u.d4(d)}else d&&b.removeChild(d);l--}};a.u.op=function(a,b){for(var c=b.parentNode;c;){if(c==a)return!0;c=c.parentNode}return!1};a.u.vt=function(b,c){return c==b?!0:a.u.op(b,c)};a.u.Mk=function(b,c,d){var e=g(b),h=e.data(a.u.GB);null==h&&(h=new a.u.wma(b),e.data(a.u.GB,h),h.start());h.addListener(c,d)};
a.u.lm=function(b,c){var d=g(b),e=d.data(a.u.GB);null!=e&&(e.removeListener(c),e.mi()&&(e.stop(),d.removeData(a.u.GB)))};a.u.mea=function(b){g(b).find(".oj-helper-detect-expansion").parent().each(function(b,c){var d=g(c).data(a.u.GB);null!=d&&d.Yq(!0)})};a.u.$q=function(b){var c=a.Za.Rz();return a.Za.zm.F_===c.os?b.metaKey:b.ctrlKey};a.u.dispatchEvent=function(a,b){var c=a.disabled;try{a.disabled=!1,a.dispatchEvent(b)}finally{a.disabled=c}};a.u.hxa=(window.requestAnimationFrame||window.mozRequestAnimationFrame||
window.webkitRequestAnimationFrame||function(a){return window.setTimeout(a,0)}).bind(window);a.u.a4=(window.cancelAnimationFrame||window.mozCancelAnimationFrame||window.webkitCancelAnimationFrame||function(a){return window.clearTimeout(a)}).bind(window);a.u.wma=function(b){function c(a){var b=!1;if(null!=A.offsetParent){var e=A.offsetWidth,h=A.offsetHeight;if(n!==e||K!==h)r=t,f(e,h),b=!0,a&&d(!0)}return b}function d(c){var e=b.offsetWidth,h=b.offsetHeight;k.has()&&(c?(null!==s&&a.u.a4(s),s=a.u.hxa(function(){s=
null;k.fire(e,h)})):k.fire(e,h));for(c=0;c<l.length;c++)l[c].SL()(e,h)}function e(a){a.stopPropagation();!c(!0)&&0<r&&null!=A.offsetParent&&(0==A.scrollLeft||0==A.scrollTop)&&(r--,f(n,K))}function h(){d(!1)}function f(a,b){n=a;K=b;var c=A.firstChild.style,d=1;do c.width=a+d+"px",c.height=b+d+"px",A.scrollLeft=A.scrollTop=d,d++;while((0==A.scrollTop||0==A.scrollLeft)&&5>=d);J.scrollLeft=a;J.scrollTop=b}var k=g.Callbacks(),l=[],m=[],t=2,r=0,s=null,n=null,K=null,A=null,J=null,F=null,E=null;this.addListener=
function(b,c){void 0===c||0===c?k.add(b):(l.push(new a.u.zpa(b,c)),m.push(b))};this.removeListener=function(a){var b=m.indexOf(a);0<=b?(m.splice(b,1),l.splice(b,1)[0].stop()):k.remove(a)};this.mi=function(){return!k.has()&&0==m.length};this.start=function(){E=e.bind(this);if(b.attachEvent)F=h.bind(this),b.attachEvent("onresize",F);else{var a=b.childNodes[0];A=document.createElement("div");A.className="oj-helper-detect-expansion";var c=document.createElement("div");A.appendChild(c);null!=a?b.insertBefore(A,
a):b.appendChild(A);A.addEventListener("scroll",E,!1);J=document.createElement("div");J.className="oj-helper-detect-contraction";a=document.createElement("div");a.style.width="200%";a.style.height="200%";J.appendChild(a);b.insertBefore(J,A);J.addEventListener("scroll",E,!1);this.Yq(!1)}};this.stop=function(){null!=s&&(a.u.a4(s),s=null);null!=A?(A.removeEventListener("scroll",E),J.removeEventListener("scroll",E),b.removeChild(A),b.removeChild(J)):b.detachEvent("onresize",F)};this.Yq=function(a){var b=
c(a);a&&!b&&null!=A.offsetParent&&f(n,K)}};a.u.GB="_ojResizeTracker";a.u.AM=function(a){return/^[A-Za-z][0-9A-Z_a-z-]*$/.test(a)};a.u.zpa=function(a,b){function c(){e=Array.prototype.slice.call(arguments);null==h&&(h=window.setTimeout(d,b))}function d(){a.apply(null,e);h=null}var e=null,h=null;this.SL=function(){return c};this.stop=function(){null!=h&&(window.clearTimeout(h),h=null)}};a.u.af=function(){return"ontouchstart"in window||0<navigator.msMaxTouchPoints||0<navigator.maxTouchPoints};a.u.cia=
function(b){a.u.Pxa=b};a.u.unwrap=function(b,c){var d=a.u.Pxa;d&&d==b.parent().get(0)||(1<arguments.length?c.replaceWith(b):b.unwrap())};a.u.gga=function(b){function c(b){var d=b.target,e=g(d),h=d.getBoundingClientRect(),f=a.u.dM(),k="ltr"===a.u.wn();return k&&("HTML"===d.nodeName||"visible"!==e.css("overflow-x"))&&b.clientX>h.right-f?!0:!k&&"HTML"===d.nodeName&&b.clientX>h.left-f?!0:!k&&"visible"!==e.css("overflow-x")&&b.clientX<h.left+f?!0:("HTML"===d.nodeName||"visible"!==e.css("overflow-y"))&&
b.clientY>h.bottom-f?!0:!1}if(!("clientX"in b&&"clientY"in b))return!1;var d=a.Za.Rz();if(a.Za.zm.$Z===d.os||a.Za.zm.oO===d.os)b=!1;else{var e;if(a.Za.Tn.p_===d.engine)try{e=b.originalTarget.localName?!1:!0}catch(h){e=!0}else e=a.Za.Tn.NO===d.engine?c(b):a.Za.rm.mO===d.browser?c(b):!1;b=e}return b};a.u.dM=function(){var b=a.u.lBa;if(g.isNumeric(b))return b;b=g("\x3cdiv /\x3e");g(document.body).append(b);b.width(50).height(50).css({overflow:"scroll",visibility:"hidden",position:"absolute"});var c=
g("\x3cdiv /\x3e");c.height(1);b.append(c);var c=c.width(),d=b.width();b.remove();return b=a.u.lBa=d-c};a.u.wn=function(){var a=document.documentElement.getAttribute("dir");a&&(a=a.toLowerCase());return"rtl"===a?"rtl":"ltr"};a.u.Pq=function(a){return isNaN(a)?a&&0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0:a};a.u.LFa=function(a){return isNaN(a)?a&&0<a.length?(a=parseFloat(a),isNaN(a)&&(a=0),a):0:a};a.u.pP="oj-logical-parent";a.u.WFa=function(b){if(b)return b.data(a.u.pP)};a.u.dia=
function(b,c){b&&(null===c?b.removeData(a.u.pP):b.data(a.u.pP,c))};a.u.JHa=function(b,c){a.o.WW(b);a.o.WW(c);for(var d=c;d;){if(d==b)return!0;var e=a.u.WFa(g(d)),d=e?e[0]:d.parentNode}return!1};a.u.OJa=function(a){var b=document.createElement("a");b.href=a;a=b.protocol;null!=a&&(a=a.toLowerCase());if(0>["http:","https:"].indexOf(a))throw a+" is not a valid URL protocol";};a.u.LCa=function(){g(document.body).hasClass("oj-hybrid")&&document.body.addEventListener("contextmenu",function(a){a.preventDefault()},
!0)};a.u.LCa();a.u.vO=750;a.u.CIa=function(){function a(){b=Date.now()}var b=0;document.addEventListener("touchend",a,!0);document.addEventListener("touchcancel",a,!0);return function(){return 500>Date.now()-b}}();a.u.BIa=function(){var b=0,c,d=a.u.vO+600;document.addEventListener("mousedown",function(){var d=Date.now();if(!c||d>b+a.u.vO)b=d,c=!1},!0);document.addEventListener("touchstart",function(){b=Date.now();c=!0},!0);document.addEventListener("mouseup",function(){b=Date.now();c=!1},!0);document.addEventListener("touchend",
function(){b=Date.now();c=!1},!0);return function(){return Date.now()-b<(c?d:600)}}();a.u.cN=function(){var b=0,c=(a.nd.uf("oj-focus-config")||{}).focusHighlightPolicy;return function(d){var e=d.element;if(d.remove){e.removeClass("oj-focus oj-focus-highlight");var h=e.data("ojFocusable");void 0!=h&&e.off(".ojFocusable"+(""+h).split(",").join(" .ojFocusable")).removeData("ojFocusable")}else{var f=d.afterToggle||g.noop,h=function(a){a.addClass("oj-focus");f("focusin")},k=function(b){b.addClass("oj-focus");
var e;a:{e=d.getFocusHighlightPolicy;var h=d.recentPointer;switch(e?e():c){case "all":e=!0;break a;case "none":e=!1;break a;default:e=!(a.u.BIa()||h&&h())}}e&&b.addClass("oj-focus-highlight");f("focusin")};(d.setupHandlers||function(a,c){function h(a){c(g(a.currentTarget))}function f(b){a(g(b.currentTarget))}var k=d.component;if(k)k._on(e,{focusin:f,focusout:h});else{var k=b++,l=e.data("ojFocusable");e.data("ojFocusable",void 0==l?k:l+","+k);l={};k=".ojFocusable"+k;l["focusin"+k]=f;l["focusout"+k]=
h;e.on(l)}})(d.applyHighlight?k:h,function(a){a.removeClass("oj-focus oj-focus-highlight");f("focusout")})}}}();a.tb=function(a){this.Init(a)};a.b.ta(a.tb,a.b,"oj.ComponentMessaging");a.tb.Re={NONE:"none",pG:"notewindow",dB:"placeholder",$A:"inline"};a.tb.cP={};a.tb.rN=function(b,c){b&&"function"===typeof c&&(a.tb.cP[b]=c)};a.tb.prototype.Init=function(b){a.tb.t.Init.call(this);this.xa=b;this.SB=!1;this.bxa()};a.tb.prototype.dt=function(b,c,d){var e=this;a.o.di(d);this.Id=b;this.B4=c;this.UJ=a.Wc.pf(this.UJ||
{},d);this.SB?this.Lza():(g.each(this.Ys,function(a,b){b.dt(e)}),this.SB=!0)};a.tb.prototype.update=function(b){a.o.di(b);a.o.oda(this.SB);this.UJ=a.Wc.pf(this.UJ||{},b);this.SB&&g.each(this.Ys,function(a,c){c.BZ(b)&&c.update()})};a.tb.prototype.ep=function(){g.each(this.Ys,function(a,b){b.ep()});this.SB=!1;this.B4=this.Id=this.xa=null;this.Ys={}};a.tb.prototype.close=function(){g.each(this.Ys,function(a,b){b.close()})};a.tb.prototype.nC=function(b,c){return new (a.tb.cP[b]||a.tb.cP[a.tb.Re.NONE])(c)};
a.tb.prototype.Esa=function(){return this.xa||null};a.tb.prototype.kta=function(){return this.Id||null};a.tb.prototype.Fsa=function(){return this.B4||null};a.tb.prototype.Bl=function(){return this.UJ||{}};a.tb.prototype.t7=function(){var b={},c=!1,d,e,h=this.xa.options.placeholder,f,k,l,m,t=this.xa.options.displayOptions||{},r={};k=Object.keys(t);for(l=0;l<k.length;l++){e=k[l];d=t[e];c=!1;f=e+"";if(Array.isArray(d))for(m=0;m<d.length;m++)e=d[m],c||(c=this.Saa(f,e,h,r));else"string"===typeof d&&(c||
(c=this.Saa(f,d,h,r)));c||(r[f]=a.tb.Re.NONE)}g.each(a.tb.Re,function(a,c){b[c]=[]});g.each(r,function(a,c){b[c].push(a)});return b};a.tb.prototype.Saa=function(b,c,d,e){var h=!1;switch(c){case a.tb.Re.dB:"converterHint"!==b||h||d||(e[b]=c,h=!0);break;case a.tb.Re.$A:"messages"!==b||h||(e[b]=c,h=!0);break;default:h||(e[b]=c,h=!0)}return h};a.tb.prototype.bxa=function(){var b=this.t7(),c=b[a.tb.Re.pG],d=b[a.tb.Re.NONE],e=b[a.tb.Re.dB],b=b[a.tb.Re.$A],h={};0<c.length&&(h[a.tb.Re.pG]=this.nC(a.tb.Re.pG,
c));0<e.length&&(h[a.tb.Re.dB]=this.nC(a.tb.Re.dB,e));0<b.length&&(h[a.tb.Re.$A]=this.nC(a.tb.Re.$A,b));h[a.tb.Re.NONE]=this.nC(a.tb.Re.NONE,d);this.Ys=h};a.tb.prototype.Lza=function(){var b=this.t7(),c,d=this;g.each(b,function(b,e){b+="";c=d.Ys[b];e&&0<e.length?c?c&&c.Lw(e):(c=d.nC(b,e),d.Ys[b]=c,c.dt(d)):c&&a.tb.Re.NONE!==b&&(c.ep(),delete d.Ys[b])})};a.md=function(a){this.Init(a)};a.b.ta(a.md,a.b,"oj.MessagingStrategy");a.md.prototype.Init=function(b){a.o.sL(b);a.md.t.Init.call(this);this.hI=b};
a.md.prototype.dt=function(a){this.js=a};a.md.prototype.ep=function(){};a.md.prototype.close=function(){};a.md.prototype.Lw=function(a){this.Init(a)};a.md.prototype.BZ=function(){return!0};a.md.prototype.update=function(){};a.md.prototype.hl=function(){return this.js.kta()};a.md.prototype.s_=function(){return this.js.Fsa()};a.md.prototype.ym=function(){return this.js.Esa()};a.md.prototype.dO=function(){return this.fO().tD};a.md.prototype.cO=function(){return this.fO().Vz()};a.md.prototype.t_=function(){var a=
[],b=this.Bl();(b=b&&b.Nda)&&a.push(b);return a};a.md.prototype.Aja=function(){var a=[],b=this.Bl();g.each(b&&b.RJa||[],function(b,c){a.push(c)});return a};a.md.prototype.zja=function(){var a=this.Bl();return a&&a.title||""};a.md.prototype.fO=function(){var a=this.Bl();return a&&a.Sia||null};a.md.prototype.lO=function(){var a=this.dO();return a&&0<a.length?!0:!1};a.md.prototype.k0=function(){return-1!==this.hI.indexOf("messages")?!0:!1};a.md.prototype.GO=function(){return-1!==this.hI.indexOf("converterHint")?
!0:!1};a.md.prototype.m0=function(){return-1!==this.hI.indexOf("validatorHint")?!0:!1};a.md.prototype.l0=function(){return-1!==this.hI.indexOf("title")?!0:!1};a.md.prototype.Dja=function(){return this.fO().tY()};a.md.prototype.Bl=function(){return this.js?this.js.Bl():{}};a.zh=function(a){this.Init(a)};a.tb.rN(a.tb.Re.NONE,a.zh);a.zh.dH="oj-invalid";a.zh.eH="oj-warning";a.b.ta(a.zh,a.md,"oj.DefaultMessagingStrategy");a.zh.prototype.update=function(){a.zh.t.update.call(this);var b=this.hl(),c=this.cO(),
d=[],e=[],h=!1,f=this.ym().widget();b&&(this.Dja()?(d.push(a.zh.eH),e.push(a.zh.dH),h=!0):this.lO()&&c===a.ia.Xc.WARNING?(d.push(a.zh.dH),e.push(a.zh.eH)):(d.push(a.zh.dH),d.push(a.zh.eH)),f.removeClass(d.join(" ")).addClass(e.join(" ")),this.s_().attr({"aria-invalid":h}))};a.zh.prototype.ep=function(){this.ym().widget().removeClass(a.zh.dH).removeClass(a.zh.eH);this.s_().removeAttr("aria-invalid");a.zh.t.ep.call(this)};a.hk=function(a){this.Init(a)};a.tb.rN(a.tb.Re.dB,a.hk);a.b.ta(a.hk,a.md,"oj.PlaceholderMessagingStrategy");
a.hk.prototype.Init=function(b){a.hk.t.Init.call(this,b)};a.hk.prototype.dt=function(b){a.hk.t.dt.call(this,b);this.lV()};a.hk.prototype.Lw=function(b){a.hk.t.Lw.call(this,b);this.lV()};a.hk.prototype.BZ=function(a){return a&&void 0!==a.Nda?!0:!1};a.hk.prototype.update=function(){a.hk.t.update.call(this);this.lV()};a.hk.prototype.lV=function(){var a=this.hl();this.eka()&&a&&(a=this.t_(),a=a.length?a[0]:"",this.ym().option({placeholder:a},{_context:{BHa:!0}}))};a.hk.prototype.eka=function(){return this.GO()};
a.sm=function(a,b){this.Init(a,b)};a.sm.tY=function(b){return a.ia.Vz(b)>=a.ia.Xc.ERROR?!0:!1};a.b.ta(a.sm,a.b,"oj.ComponentValidity");a.sm.prototype.Init=function(b,c){a.sm.t.Init.call(this);this.a9(c)};a.sm.prototype.tY=function(){return this.Fs};a.sm.prototype.Vz=function(){return this.jya};a.sm.prototype.update=function(a,b){this.a9(b)};a.sm.prototype.a9=function(b){this.Apa=b;this.tD=this.eta();this.jya=a.ia.Vz(this.tD);this.Fs=a.sm.tY(this.tD)};a.sm.prototype.eta=function(){for(var b=this.Apa||
[],c=[],d,e=0;e<b.length;e++)d=b[e],d instanceof a.be&&!d.zda()||c.push(d);return c};a.le={};a.le.k2=":tabbable";a.le.AL=function(b){var c=document.activeElement;return b&&c?a.u.vt(b,c):!1};a.le.OE=function(a){a.focus()};a.le.CX=function(b){(b=a.le.Oea(b))&&a.le.OE(b)};a.le.Oea=function(b){var c=g(b);return c.is(a.le.k2)?b:(b=c.find(a.le.k2))&&0<b.length?b[0]:null};a.le.iA=function(b){return g(b).is(":focusable")&&("A"!==b.nodeName||b.hasAttribute("tabindex")||a.Za.Rz().browser!==a.Za.rm.xO)?!0:!1};
a.Dm={};o_("Test",a.Dm,a);a.Dm.ready=!1;o_("Test.ready",a.Dm.ready,a);a.Dm.nFa=function(b){var c=b;if(a.bb.Ke(b))try{c=JSON.parse(b)}catch(d){return null}return c&&c.element&&(b=g(c.element))?(b=a.Components.Mf(b[0],c.component),delete c.element,b("getNodeBySubId",c)):null};o_("Test.domNodeForLocator",a.Dm.nFa,a);a.Dm.TX=function(){return a.T.TX()};o_("Test.getOpenPopupCount",a.Dm.TX,a);a.Dm.uX=function(){return a.T.uX()};o_("Test.findOpenPopups",a.Dm.uX,a);a.Dm.iX=function(b,c){return a.T.iX(b,c)};
o_("Test.compareStackingContexts",a.Dm.iX,a);a.Components.Ta("baseComponent",null,{properties:{contextMenu:{type:"string"},rootAttributes:{type:"Object"},translations:{type:"Object"}},methods:{getNodeBySubId:{},option:{},refresh:{}},extension:{_widgetName:"baseComponent"}})});