/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore","jqueryui-amd/widgets/draggable","jqueryui-amd/widgets/mouse"],function(a,g){(function(){a.Na("oj.ojResizable",g.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancel:"input,textarea,button,select,option",distance:1,delay:0,maxHeight:null,maxWidth:null,minHeight:10,minWidth:10,alsoResize:!1,animate:!1,animateDuration:"slow",animateEasing:"swing",containment:!1,ghost:!1,grid:!1,handles:"e,s,se",helper:!1,resize:null,
start:null,stop:null},QU:function(a){return parseInt(a,10)||0},Ig:function(a){return!isNaN(parseInt(a,10))},A8:function(a,b){if("hidden"===g(a).css("overflow"))return!1;var d=b&&"left"===b?"scrollLeft":"scrollTop",e=!1;if(0<a[d])return!0;a[d]=1;e=0<a[d];a[d]=0;return e},_ComponentCreate:function(){this._super();var a,b,d,e,f,h=this;a=this.options;b=this.element.mouse.bind(this.element);b();this.jr=b("instance");this.jr._mouseCapture=function(a){return h.vya(a)};this.jr._mouseStart=function(a){return h.yya(a)};
this.jr._mouseDrag=function(a){return h.wya(a)};this.jr._mouseStop=function(a){return h.vD(a)};this.element.addClass("oj-resizable");g.extend(this,{iN:this.element,hK:[],Eo:null});this.handles=a.handles||(g(".oj-resizable-handle",this.element).length?{ALa:".oj-resizable-n",nLa:".oj-resizable-e",GLa:".oj-resizable-s",vi:".oj-resizable-w",HLa:".oj-resizable-se",JLa:".oj-resizable-sw",BLa:".oj-resizable-ne",CLa:".oj-resizable-nw"}:"e,s,se");if(this.handles.constructor===String)for("all"===this.handles&&
(this.handles="n,e,s,w,se,sw,ne,nw"),a=this.handles.split(","),this.handles={},b=0;b<a.length;b++)d=g.trim(a[b]),f="oj-resizable-"+d,e=g("\x3cdiv class\x3d'oj-resizable-handle "+f+"'\x3e\x3c/div\x3e"),this.handles[d]=".oj-resizable-"+d,this.element.append(e);this.JAa=function(){for(var a in this.handles)this.handles[a].constructor===String&&(this.handles[a]=this.element.children(this.handles[a]).first().show())};this.JAa();this.mwa=g(".oj-resizable-handle",this.element);this.mwa.mouseover(function(){h.Rha||
(this.className&&(e=this.className.match(/oj-resizable-(se|sw|ne|nw|n|e|s|w)/i)),h.axis=e&&e[1]?e[1]:"se")});this.jr._mouseInit()},_destroy:function(){this.jr&&this.jr._mouseDestroy();try{this.jr.destroy(),this.jr=null}catch(a){}g(this.iN).removeClass("oj-resizable oj-resizable-disabled oj-resizable-resizing").removeData("resizable").removeData("oj-resizable").unbind(".resizable").find(".oj-resizable-handle").remove();return this},vya:function(a){var b,d,e=!1;for(b in this.handles)if(d=g(this.handles[b])[0],
d===a.target||g.contains(d,a.target))e=!0;return!this.options.disabled&&e},yya:function(a){var b,d,e;e=this.options;b=this.element.position();var f=this.element;this.Rha=!0;/absolute/.test(f.css("position"))?f.css({position:"absolute",top:f.css("top"),left:f.css("left")}):f.is(".oj-draggable")&&f.css({position:"absolute",top:b.top,left:b.left});this.KAa();b=this.QU(this.helper.css("left"));d=this.QU(this.helper.css("top"));e.containment&&(b+=g(e.containment).scrollLeft()||0,d+=g(e.containment).scrollTop()||
0);this.offset=this.helper.offset();this.position={left:b,top:d};this.size={width:f.width(),height:f.height()};this.Kn={width:f.width(),height:f.height()};this.Ot={left:b,top:d};this.wN={width:f.outerWidth()-f.width(),height:f.outerHeight()-f.height()};this.pIa={left:a.pageX,top:a.pageY};this.Zo=this.Kn.width/this.Kn.height||1;e=g(".oj-resizable-"+this.axis).css("cursor");g("body").css("cursor","auto"===e?this.axis+"-resize":e);f.addClass("oj-resizable-resizing");this.gV("start",a);this.aoa(a);this.Jpa(a);
return!0},wya:function(a){var b,d=this.helper,e={},f=this.pIa;b=a.pageX-f.left||0;var f=a.pageY-f.top||0,h=this.xk[this.axis];this.BA={top:this.position.top,left:this.position.left};this.CA={width:this.size.width,height:this.size.height};if(!h)return!1;b=h.apply(this,[a,b,f]);this.GDa(a.shiftKey);a.shiftKey&&(b=this.EDa(b,a));b=this.XAa(b,a);this.tDa(b);this.gV("resize",a);this.$na(a,this.ui());this.Ipa(a,this.ui());this.position.top!==this.BA.top&&(e.top=this.position.top+"px");this.position.left!==
this.BA.left&&(e.left=this.position.left+"px");this.size.width!==this.CA.width&&(e.width=this.size.width+"px");this.size.height!==this.CA.height&&(e.height=this.size.height+"px");d.css(e);!this.Eo&&this.hK.length&&this.Eza();g.isEmptyObject(e)||this._trigger("resize",a,this.ui());return!1},vD:function(a){this.Rha=!1;g("body").css("cursor","auto");this.element.removeClass("oj-resizable-resizing");this.gV("stop",a);this.boa(a);this.Kpa(a);return!1},GDa:function(a){var b,d,e,f;f=this.options;f={minWidth:this.Ig(f.minWidth)?
f.minWidth:0,maxWidth:this.Ig(f.maxWidth)?f.maxWidth:Infinity,minHeight:this.Ig(f.minHeight)?f.minHeight:0,maxHeight:this.Ig(f.maxHeight)?f.maxHeight:Infinity};a&&(a=f.minHeight*this.Zo,d=f.minWidth/this.Zo,b=f.maxHeight*this.Zo,e=f.maxWidth/this.Zo,a>f.minWidth&&(f.minWidth=a),d>f.minHeight&&(f.minHeight=d),b<f.maxWidth&&(f.maxWidth=b),e<f.maxHeight&&(f.maxHeight=e));this.JDa=f},tDa:function(a){this.offset=this.helper.offset();this.Ig(a.left)&&(this.position.left=a.left);this.Ig(a.top)&&(this.position.top=
a.top);this.Ig(a.height)&&(this.size.height=a.height);this.Ig(a.width)&&(this.size.width=a.width)},EDa:function(a){var b=this.position,d=this.size,e=this.axis;this.Ig(a.height)?a.width=a.height*this.Zo:this.Ig(a.width)&&(a.height=a.width/this.Zo);"sw"===e&&(a.left=b.left+(d.width-a.width),a.top=null);"nw"===e&&(a.top=b.top+(d.height-a.height),a.left=b.left+(d.width-a.width));return a},XAa:function(a){var b=this.JDa,d=this.axis,e=this.Ig(a.width)&&b.maxWidth&&b.maxWidth<a.width,f=this.Ig(a.height)&&
b.maxHeight&&b.maxHeight<a.height,g=this.Ig(a.width)&&b.minWidth&&b.minWidth>a.width,k=this.Ig(a.height)&&b.minHeight&&b.minHeight>a.height,l=this.Ot.left+this.Kn.width,m=this.position.top+this.size.height,s=/sw|nw|w/.test(d),d=/nw|ne|n/.test(d);g&&(a.width=b.minWidth);k&&(a.height=b.minHeight);e&&(a.width=b.maxWidth);f&&(a.height=b.maxHeight);g&&s&&(a.left=l-b.minWidth);e&&s&&(a.left=l-b.maxWidth);k&&d&&(a.top=m-b.minHeight);f&&d&&(a.top=m-b.maxHeight);a.width||a.height||a.left||!a.top?a.width||
a.height||a.top||!a.left||(a.left=null):a.top=null;return a},Eza:function(){if(this.hK.length){var a,b,d,e,f,g=this.helper||this.element;for(a=0;a<this.hK.length;a++){f=this.hK[a];if(!this.Gz)for(this.Gz=[],d=[f.css("borderTopWidth"),f.css("borderRightWidth"),f.css("borderBottomWidth"),f.css("borderLeftWidth")],e=[f.css("paddingTop"),f.css("paddingRight"),f.css("paddingBottom"),f.css("paddingLeft")],b=0;b<d.length;b++)this.Gz[b]=(parseInt(d[b],10)||0)+(parseInt(e[b],10)||0);f.css({height:g.height()-
this.Gz[0]-this.Gz[2]||0,width:g.width()-this.Gz[1]-this.Gz[3]||0})}}},KAa:function(){this.element.offset();this.helper=this.element},xk:{e:function(a,b){return{width:this.Kn.width+b}},w:function(a,b){return{left:this.Ot.left+b,width:this.Kn.width-b}},n:function(a,b,d){return{top:this.Ot.top+d,height:this.Kn.height-d}},s:function(a,b,d){return{height:this.Kn.height+d}},se:function(a,b,d){return g.extend(this.xk.s.apply(this,arguments),this.xk.e.apply(this,[a,b,d]))},sw:function(a,b,d){return g.extend(this.xk.s.apply(this,
arguments),this.xk.w.apply(this,[a,b,d]))},ne:function(a,b,d){return g.extend(this.xk.n.apply(this,arguments),this.xk.e.apply(this,[a,b,d]))},nw:function(a,b,d){return g.extend(this.xk.n.apply(this,arguments),this.xk.w.apply(this,[a,b,d]))}},gV:function(a,b){"resize"!==a&&this._trigger(a,b,this.ui())},aoa:function(){function a(b){g(b).each(function(){var a=g(this);a.data("oj-resizable-alsoresize",{width:parseInt(a.width(),10),height:parseInt(a.height(),10),left:parseInt(a.css("left"),10),top:parseInt(a.css("top"),
10)})})}var b=this.options;"object"!==typeof b.alsoResize||b.alsoResize.parentNode?a(b.alsoResize):b.alsoResize.length?(b.alsoResize=b.alsoResize[0],a(b.alsoResize)):g.each(b.alsoResize,function(b){a(b)})},$na:function(a,b){function d(a,c){g(a).each(function(){var a=g(this),d=g(this).data("oj-resizable-alsoresize"),e={};g.each(c&&c.length?c:a.parents(b.iN[0]).length?["width","height"]:["width","height","top","left"],function(a,b){var c=(d[b]||0)+(k[b]||0);c&&0<=c&&(e[b]=c||null)});a.css(e)})}var e=
this.options,f=this.Kn,h=this.Ot,k={height:this.size.height-f.height||0,width:this.size.width-f.width||0,top:this.position.top-h.top||0,left:this.position.left-h.left||0};"object"!==typeof e.alsoResize||e.alsoResize.nodeType?d(e.alsoResize,null):g.each(e.alsoResize,function(a,b){d(a,b)})},boa:function(){g(this).removeData("oj-resizable-alsoresize")},Jpa:function(){var a,b,d,e,f,h=this,k=h.element;d=h.options.containment;if(k=d instanceof g?d.get(0):/parent/.test(d)?k.parent().get(0):d)h.yL=g(k),/document/.test(d)||
d===document?(h.zL={left:0,top:0},h.Kda={left:0,top:0},h.Qt={element:g(document),left:0,top:0,width:g(document).width(),height:g(document).height()||document.body.parentNode.scrollHeight}):(a=g(k),b=[],g(["Top","Right","Left","Bottom"]).each(function(d,e){b[d]=h.QU(a.css("padding"+e))}),h.zL=a.offset(),h.Kda=a.position(),h.Lda={height:a.innerHeight()-b[3],width:a.innerWidth()-b[1]},d=h.zL,e=h.Lda.height,f=h.Lda.width,f=h.A8(k,"left")?k.scrollWidth:f,e=h.A8(k)?k.scrollHeight:e,h.Qt={element:k,left:d.left,
top:d.top,width:f,height:e})},Ipa:function(a,b){var d,e,f,g;d=this.options;e=this.zL;g=this.position;var k=a.shiftKey;f={top:0,left:0};var l=this.yL,m=!0;l[0]!==document&&/static/.test(l.css("position"))&&(f=e);g.left<(this.Eo?e.left:0)&&(this.size.width+=this.Eo?this.position.left-e.left:this.position.left-f.left,k&&(this.size.height=this.size.width/this.Zo,m=!1),this.position.left=d.helper?e.left:0);g.top<(this.Eo?e.top:0)&&(this.size.height+=this.Eo?this.position.top-e.top:this.position.top,k&&
(this.size.width=this.size.height*this.Zo,m=!1),this.position.top=this.Eo?e.top:0);this.offset.left=this.Qt.left+this.position.left;this.offset.top=this.Qt.top+this.position.top;d=Math.abs((this.Eo?this.offset.left-f.left:this.offset.left-e.left)+this.wN.width);e=Math.abs((this.Eo?this.offset.top-f.top:this.offset.top-e.top)+this.wN.height);f=this.yL.get(0)===this.element.parent().get(0);g=/relative|absolute/.test(this.yL.css("position"));f&&g&&(d-=Math.abs(this.Qt.left));d+this.size.width>=this.Qt.width&&
(this.size.width=this.Qt.width-d,k&&(this.size.height=this.size.width/this.Zo,m=!1));e+this.size.height>=this.Qt.height&&(this.size.height=this.Qt.height-e,k&&(this.size.width=this.size.height*this.Zo,m=!1));m||(this.position.left=b.BA.left,this.position.top=b.BA.top,this.size.width=b.CA.width,this.size.height=b.CA.height)},Kpa:function(){var a=this.options,b=this.zL,d=this.Kda,e=this.yL,f=g(this.helper),h=f.offset(),k=f.outerWidth()-this.wN.width,f=f.outerHeight()-this.wN.height;this.Eo&&!a.animate&&
/relative/.test(e.css("position"))&&g(this).css({left:h.left-d.left-b.left,width:k,height:f});this.Eo&&!a.animate&&/static/.test(e.css("position"))&&g(this).css({left:h.left-d.left-b.left,width:k,height:f})},ui:function(){return{iN:this.iN,element:this.element,helper:this.helper,position:this.position,size:this.size,Kn:this.Kn,Ot:this.Ot,CA:this.CA,BA:this.BA}}})})();(function(){a.Na("oj.ojDialog",g.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{cancelBehavior:"icon",dragAffordance:"title-bar",
initialVisibility:"hide",modality:"modal",position:{my:"center",at:"center",of:window,collision:"fit",MLa:function(a){var b=g(this).css(a).offset().top;0>b&&g(this).css("top",a.top-b)}},resizeBehavior:"resizable",role:"dialog",title:null,beforeClose:null,beforeOpen:null,close:null,focus:null,open:null,resize:null,resizeStart:null,resizeStop:null},_ComponentCreate:function(){this._super();this.oIa={display:this.element[0].style.display,width:this.element[0].style.width,height:this.element[0].style.height};
this.Ot={parent:this.element.parent(),index:this.element.parent().children().index(this.element)};this.cZ=this.element.attr("title");this.options.title=this.options.title||this.cZ;this.Gqa();this.element.show().removeAttr("title").addClass("oj-dialog-content oj-dialog-default-content").appendTo(this.uc);this.aG=!1;if(this.element.find(".oj-dialog").length){var a=this;this.element.find(".oj-dialog-header").each(function(b,d){var e=g(d);if(!e.closest(".oj-dialog-body").length)return a.bt=e,a.aG=!0,
!1})}else this.bt=this.element.find(".oj-dialog-header"),this.bt.length&&(this.aG=!0);this.aG?(this.tqa(this.bt),this.bt.prependTo(this.uc),"icon"===this.options.cancelBehavior&&(this.UH(this.bt),this.yE=this.bt.find(".oj-dialog-title"),this.yE.length&&this.yE.insertAfter(this.Pn))):this.Eqa();this.zr=this.element.children(".oj-dialog-footer");this.sqa(this.zr);this.zr.length&&(this.zr.addClass("oj-helper-clearfix"),this.zr.appendTo(this.uc));"title-bar"===this.options.dragAffordance&&g.fn.draggable&&
this.Vy();this.Qba(this.uc);this.Js=!1},w0:function(){"show"===this.options.initialVisibility&&this.open()},_destroy:function(){this.Qqa&&window.clearTimeout(this.Qqa);this.isOpen()&&this.Uu();this.zq&&(this.zq("instance")&&this.zq("destroy"),this.zq=null);this.zr.length&&(this.zr.removeClass("oj-helper-clearfix"),g("#"+this.E$).replaceWith(this.zr));this.cI();if(this.aG){var a=this.uc.find(".oj-dialog-header");a&&g("#"+this.F$).replaceWith(a)}this.Mia&&(this.Mia.remove(),this.Mia=null);this.element.removeUniqueId().removeClass("oj-dialog-content oj-dialog-default-content").css(this.oIa);
this.uc&&this.uc.stop(!0,!0);this.element.unwrap();this.cZ&&this.element.attr("title",this.cZ);this.Ar&&(this.Ar.remove(),this.Ar=null);delete this.hn;delete this.Js;this._super()},widget:function(){return this.uc},disable:g.noop,enable:g.noop,close:function(c){if(this.isOpen()&&(!1!==this._trigger("beforeClose",c)||this.dD)){this.Js=!1;this.fsa=null;this.opener.filter(":focusable").focus().length||g(this.document[0].activeElement).blur();var b={};b[a.U.qb.Bh]=this.uc;a.U.Je().close(b);this._trigger("close",
c)}},isOpen:function(){return this.Js},open:function(c){if(!1!==this._trigger("beforeOpen",c)){if(!this.isOpen()){this.Js=!0;this.opener=g(this.document[0].activeElement);"resizable"===this.options.resizeBehavior&&this.a$();c="rtl"===this.hd();c=a.Qd.km(this.options.position,c);var b={};b[a.U.qb.Bh]=this.uc;b[a.U.qb.aB]=this.opener;b[a.U.qb.eB]=c;b[a.U.qb.gk]=this.options.modality;b[a.U.qb.fu]=this.wy();b[a.U.qb.Gr]="oj-dialog-layer";b[a.U.qb.Fr]=a.U.Fr.IO;a.U.Je().open(b);this._trigger("open")}this.h6()}},
refresh:function(){this._super()},h6:function(){var c=this.fsa;c&&0<c.length&&a.u.vt(this.uc[0],c[0])||(c||(c=this.element.find("[autofocus]")),c.length||(c=this.element.find(":tabbable")),c.length||this.zr.length&&(c=this.zr.find(":tabbable")),c.length||this.Nia&&this.Pn&&(c=this.Pn.filter(":focusable")),c.length||(c=this.uc),c.eq(0).focus(),this._trigger("focus"))},_keepFocus:function(a){a.preventDefault();a=this.document[0].activeElement;this.uc[0]===a||g.contains(this.uc[0],a)||this.h6()},Ig:function(a){return!isNaN(parseInt(a,
10))},Gqa:function(){this.D9=!1;this.element.uniqueId();this.UR=this.element.attr("id");this.oe?(this.uc=g(this.oe),this.uc.uniqueId(),this.dda=this.uc.attr("id")):(this.dda="ojDialogWrapper-"+this.UR,this.uc=g("\x3cdiv\x3e"),this.uc.insertBefore(this.element));this.uc.addClass("oj-dialog oj-component").hide().attr({tabIndex:-1,role:this.options.role,id:this.dda});this._on(this.uc,{keyup:function(){},keydown:function(a){if("none"!=this.options.cancelBehavior&&!a.isDefaultPrevented()&&a.keyCode&&a.keyCode===
g.ui.keyCode.ESCAPE)a.preventDefault(),a.stopImmediatePropagation(),this.close(a);else if(a.keyCode===g.ui.keyCode.TAB){var b=this.uc.find(":tabbable"),d=b.filter(":first"),e=b.filter(":last");a.shiftKey?a.shiftKey&&(a.target===d[0]||a.target===this.uc[0]?(e.focus(),a.preventDefault()):(d=b.index(document.activeElement),1==d&&b[0]&&(b[0].focus(),a.preventDefault()))):a.target===e[0]||a.target===this.uc[0]?(d.focus(),a.preventDefault()):(d=b.index(document.activeElement),0==d&&b[1]&&(b[1].focus(),
a.preventDefault()))}}});this.element.find("[aria-describedby]").length||this.uc.attr({"aria-describedby":this.element.uniqueId().attr("id")})},Qba:function(a){var b=this;this._focusable({applyHighlight:!0,setupHandlers:function(d,e){b._on(a,{focus:function(a){d(g(a.currentTarget))},blur:function(a){e(g(a.currentTarget))}})}})},cI:function(){this.Pn&&(this.Pn.remove(),this.Nia=this.Pn=null)},UH:function(a){this.Pn=g("\x3cdiv\x3e").addClass("oj-dialog-header-close-wrapper").attr("tabindex","1").attr("aria-label",
"close").attr("role","button").appendTo(a);this.Nia=g("\x3cspan\x3e").addClass("oj-component-icon oj-clickable-icon oj-dialog-close-icon").attr("alt","close icon").prependTo(this.Pn);this._on(this.Pn,{click:function(a){a.preventDefault();a.stopImmediatePropagation();this.close(a)},mousedown:function(a){g(a.currentTarget).addClass("oj-active")},mouseup:function(a){g(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){g(a.currentTarget).addClass("oj-hover")},mouseleave:function(a){a=a.currentTarget;
g(a).removeClass("oj-hover");g(a).removeClass("oj-active")},keydown:function(a){if(a.keyCode&&a.keyCode===g.ui.keyCode.SPACE||a.keyCode===g.ui.keyCode.ENTER)a.preventDefault(),a.stopImmediatePropagation(),this.close(a)}});this.Qba(this.Pn)},Eqa:function(){var a;this.Ar=g("\x3cdiv\x3e").addClass("oj-dialog-header oj-helper-clearfix").prependTo(this.uc);this._on(this.Ar,{mousedown:function(a){g(a.target).closest(".oj-dialog-close-icon")||this.uc.focus()}});"icon"===this.options.cancelBehavior&&this.UH(this.Ar);
a=g("\x3cspan\x3e").uniqueId().addClass("oj-dialog-title").appendTo(this.Ar);this.vz(a);this.uc.attr({"aria-labelledby":a.attr("id")})},vz:function(a){this.options.title||a.html("\x26#160;");a.text(this.options.title)},Vy:function(){function a(b){return{position:b.position,offset:b.offset}}var b=this,d=this.options;this.uc.draggable({hLa:!1,cancel:".oj-dialog-content, .oj-dialog-header-close",handle:".oj-dialog-header",containment:"document",start:function(d,f){g(this).addClass("oj-dialog-dragging");
b.FD();b._trigger("dragStart",d,a(f))},drag:function(d,f){b.FD();b._trigger("drag",d,a(f))},stop:function(e,f){d.position=[f.position.left-b.document.scrollLeft(),f.position.top-b.document.scrollTop()];g(this).removeClass("oj-dialog-dragging");b.FD();b._trigger("dragStop",e,a(f))}});this.uc.addClass("oj-draggable")},a$:function(){function a(b){return{originalPosition:b.Ot,originalSize:b.Kn,position:b.position,size:b.size}}var b=this;this.uc.css("position");this.zq=this.uc.ojResizable.bind(this.uc);
this.zq({cancel:".oj-dialog-content",containment:"document",handles:"n,e,s,w,se,sw,ne,nw",start:function(d,e){b.D9=!0;g(this).addClass("oj-dialog-resizing");b._trigger("resizeStart",d,a(e))},resize:function(d,e){b._trigger("resize",d,a(e))},stop:function(d,e){b.D9=!1;g(this).removeClass("oj-dialog-resizing");b._trigger("resizeStop",d,a(e))}})},$U:function(){var c="rtl"===this.hd(),c=a.Qd.km(this.options.position,c);this.uc.position(c);this.FD()},FD:function(){a.U.Je().DN(this.uc,a.U.Fd.Mp)},_setOption:function(c,
b,d){var e;e=this.uc;if("disabled"!==c)switch(this._super(c,b,d),c){case "dragAffordance":(c=e.hasClass("oj-draggable"))&&"none"===b&&(e.draggable("destroy"),this.uc.removeClass("oj-draggable"));c||"title-bar"!==b||this.Vy();break;case "position":this.$U();break;case "resizeBehavior":e=!1;this.zq&&(e=!0);e&&"resizable"!=b&&(this.zq("instance")&&this.zq("destroy"),this.zq=null);e||"resizable"!==b||this.a$();break;case "title":this.vz(this.Ar.find(".oj-dialog-title"));break;case "role":e.attr("role",
b);break;case "modality":this.isOpen()&&(e={},e[a.U.qb.Bh]=this.uc,e[a.U.qb.gk]=b,a.U.Je().Hz(e));break;case "cancelBehavior":"none"===b||"escape"===b?this.cI():"icon"===b&&(this.aG?(this.cI(),this.UH(this.bt),this.yE=this.bt.find(".oj-dialog-title"),this.yE.length&&this.yE.insertAfter(this.Pn)):(this.cI(),this.UH(this.Ar),this.ria=this.Ar.find(".oj-dialog-title"),this.ria.length&&this.ria.insertAfter(this.Pn)))}},sqa:function(a){this.E$="ojDialogPlaceHolderFooter-"+this.UR;this.hza=g("\x3cdiv\x3e").hide().attr({id:this.E$});
this.hza.insertBefore(a)},tqa:function(a){this.F$="ojDialogPlaceHolderHeader-"+this.UR;this.iza=g("\x3cdiv\x3e").hide().attr({id:this.F$});this.iza.insertBefore(a)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;switch(a){case "oj-dialog-header":case "oj-dialog-body":case "oj-dialog-footer":case "oj-dialog-content":case "oj-dialog-header-close-wrapper":case "oj-resizable-n":case "oj-resizable-e":case "oj-resizable-s":case "oj-resizable-w":case "oj-resizable-se":case "oj-resizable-sw":case "oj-resizable-ne":case "oj-resizable-nw":a=
"."+a;if(!this.widget().find(a))break;return this.widget().find(a)[0];case "oj-dialog-close-icon":case "oj-dialog-close":if(!this.widget().find(".oj-dialog-close-icon"))break;return this.widget().find(".oj-dialog-close-icon")[0]}return null},getSubIdByNode:function(a){if(null!=a){a=g(a);if(a.hasClass("oj-dialog-header"))return{subId:"oj-dialog-header"};if(a.hasClass("oj-dialog-footer"))return{subId:"oj-dialog-footer"};if(a.hasClass("oj-dialog-content"))return{subId:"oj-dialog-content"};if(a.hasClass("oj-dialog-header-close-wrapper"))return{subId:"oj-dialog-header-close-wrapper"};
if(a.hasClass("oj-dialog-close-icon"))return{subId:"oj-dialog-close"};if(a.hasClass("oj-resizable-n"))return{subId:"oj-resizable-n"};if(a.hasClass("oj-resizable-e"))return{subId:"oj-resizable-e"};if(a.hasClass("oj-resizable-s"))return{subId:"oj-resizable-s"};if(a.hasClass("oj-resizable-w"))return{subId:"oj-resizable-w"};if(a.hasClass("oj-resizable-se"))return{subId:"oj-resizable-se"};if(a.hasClass("oj-resizable-sw"))return{subId:"oj-resizable-sw"};if(a.hasClass("oj-resizable-ne"))return{subId:"oj-resizable-ne"};
if(a.hasClass("oj-resizable-nw"))return{subId:"oj-resizable-nw"}}return null},Xv:function(){this.element.remove()},wy:function(){if(!this.hn){var c=this.hn={};c[a.U.Fd.kx]=g.proxy(this.Uu,this);c[a.U.Fd.lx]=g.proxy(this.Xv,this);c[a.U.Fd.Mp]=g.proxy(this.FD,this)}return this.hn},Uu:function(){this.dD=!0;this.close();delete this.dD}})})();a.Components.Ta("ojDialog","baseComponent",{properties:{cancelBehavior:{type:"string"},dragAffordance:{type:"string"},initialVisibility:{type:"string"},modality:{type:"string"},
position:{type:"Object"},resizeBehavior:{type:"string"},role:{type:"string"},title:{type:"string"},widget:{}},methods:{close:{},destroy:{},isOpen:{},open:{},refresh:{}},extension:{_hasWrapper:!0,_innerElement:"div",_widgetName:"ojDialog"}});a.Components.register("oj-dialog",a.Components.getMetadata("ojDialog"))});