/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery"],function(a,g){a.Sf=function(a,b,d){d=d||{};this.i=b;this.bv=g(a)[0];this.ny=d.fetchSize;this.ny=0<this.ny?this.ny:25;this.Wy=d.maxCount;this.Wy=0<this.Wy?this.Wy:500;this.wK=0;this.qca=d.success;this.Gra=d.error;this.Ov();this.cv=d.fetchTrigger;if(null==this.cv||isNaN(this.cv))this.cv=0;this.Ywa=this.bv.scrollTop;g(this.x7()).on("scroll.domscroller",function(){var a=this.bv,b=this.Nta(a),a=a.scrollHeight-a.clientHeight;0<a&&this.NT(b,a)}.bind(this))};a.Sf.prototype.x7=
function(){return this.bv==document.body||this.bv==document.documentElement?window:this.bv};a.Sf.wEa=function(a,b){for(var d=0,e=b;e&&e!=a&&g.contains(a,e);)d+=e.offsetTop,e=e.offsetParent;return d};a.Sf.prototype.Nta=function(a){var b=this.cv;return a==document.documentElement&&(void 0===this.Yca&&(this.Yca=this.Ywa==a.scrollTop?!0:!1),this.Yca)?b+document.body.scrollTop:b+a.scrollTop};a.Sf.prototype.destroy=function(){this.Uo();g(this.x7()).off("scroll.domscroller")};a.b.g("DomScroller.prototype.destroy",
{destroy:a.Sf.prototype.destroy});a.Sf.prototype.checkViewport=function(){return 0<this.bv.clientHeight&&!this.apa()?this.P5():Promise.resolve(null)};a.b.g("DomScroller.prototype.checkViewport",{checkViewport:a.Sf.prototype.checkViewport});a.Sf.prototype.NT=function(a,b){if(1>=b-a&&!this.zC){var d=this;this.P5().then(function(a){null!=d.qca&&d.qca(a)},this.Gra)}};a.Sf.prototype.apa=function(){var a=this.bv;return a.scrollHeight>a.clientHeight+this.cv?!0:!1};a.Sf.prototype.P5=function(){if(this.zC)return this.zC;
var a=this.Wy-this.wK;if(0<a){var b=this.ny,d=this;a<this.ny&&(b=a);var e=this.Sra({pageSize:b});return this.zC=new Promise(function(b){e.then(function(e){d.zC=null;null!=e&&0<e.data.length&&(d.wK=e.data.length+e.startIndex,a<d.ny&&(e.maxCount=d.Wy,e.maxCountLimit=!0));b(e)})})}return Promise.resolve({maxCount:this.Wy,maxCountLimit:!0})};a.Sf.prototype.Sra=function(a){a=a||{};var b=a.pageSize;this.Li=this.Li?this.Li+b:b;if(-1==this.i.totalSize()||this.i.totalSize()>this.Li){var d=this;return new Promise(function(a,
c){d.i.fetch({startIndex:d.Li,pageSize:b}).then(function(b){a(b)},function(){c(null)})})}return Promise.resolve()};a.Sf.prototype.As=function(){this.Li=null;this.wK=0};a.Sf.prototype.Fua=function(a){this.Li=a.startIndex;0<a.data.length&&(this.wK=a.data.length+this.Li)};a.Sf.prototype.Ov=function(){var c=this.i;if(null!=c){this.Uo();this.Cb=[];this.Cb.push({eventType:a.aa.Q.SORT,eventHandler:this.As.bind(this)});this.Cb.push({eventType:a.aa.Q.REFRESH,eventHandler:this.As.bind(this)});this.Cb.push({eventType:a.aa.Q.RESET,
eventHandler:this.As.bind(this)});this.Cb.push({eventType:a.aa.Q.SYNC,eventHandler:this.Fua.bind(this)});var b,d;for(b=0;b<this.Cb.length;b++)(d=c.on(this.Cb[b].eventType,this.Cb[b].eventHandler))&&(this.Cb[b].eventHandler=d)}};a.Sf.prototype.Uo=function(){var a=this.i;if(null!=this.Cb&&null!=a){var b;for(b=0;b<this.Cb.length;b++)a.off(this.Cb[b].eventType,this.Cb[b].eventHandler)}}});