/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojvalidation","ojs/internal-deps/dvt/DvtToolkit","ojdnd","promise"],function(a,g,c,b,d){function e(a,b){this.eza=b;this.dBa=a;this.Rqa="/"}a.dk=function(a){this.Init(a)};o_("AttributeGroupHandler",a.dk,a);a.b.ta(a.dk,a.b,"oj.AttributeGroupHandler");a.dk.prototype.Init=function(a){this.ZB={};this.lL=0;this.LU={};for(var b in a)this.TW(b,a[b])};a.dk.prototype.yn=function(){return[]};a.b.g("AttributeGroupHandler.prototype.getValueRamp",{yn:a.dk.prototype.yn});
a.dk.prototype.ie=function(a){if(this.LU[a])return this.LU[a];this.ZB[a]||(this.Mg||(this.Mg=this.yn().slice()),this.ZB[a]=this.Mg[this.lL],this.lL++,this.lL==this.Mg.length&&(this.lL=0));return this.ZB[a]};a.b.g("AttributeGroupHandler.prototype.getValue",{ie:a.dk.prototype.ie});a.dk.prototype.wea=function(){var a=[],b;for(b in this.ZB)a.push({category:b,value:this.ZB[b]});return a};a.b.g("AttributeGroupHandler.prototype.getCategoryAssignments",{wea:a.dk.prototype.wea});a.dk.prototype.TW=function(a,
b){this.LU[a]=b};a.b.g("AttributeGroupHandler.prototype.addMatchRule",{TW:a.dk.prototype.TW});a.ox=function(a){this.Init(a)};o_("ShapeAttributeGroupHandler",a.ox,a);a.b.ta(a.ox,a.dk,"oj.ShapeAttributeGroupHandler");a.ox.$B="square circle diamond plus triangleDown triangleUp human".split(" ");a.ox.prototype.yn=function(){return a.ox.$B};a.b.g("ShapeAttributeGroupHandler.prototype.getValueRamp",{yn:a.ox.prototype.yn});e.prototype.UAa=function(a,b,c,d){for(var e={};a&&-1<b.indexOf(c);){var f=b.substring(0,
b.indexOf(c));d&&void 0===a[f]&&(a[f]={});a=a[f];b=b.substring(b.indexOf(c)+1,b.length)}a&&(e.object=a,e.parameter=b);return e};e.prototype.Vaa=function(a){void 0===this.qD&&(a=this.UAa(this.dBa,this.eza,this.Rqa,a),this.qD=a.object,this.XU=a.parameter)};e.prototype.ie=function(){this.Vaa(!1);return void 0===this.qD?void 0:this.qD[this.XU]};e.prototype.jia=function(a,b){this.Vaa(!0);if(b||!this.qD[this.XU])this.qD[this.XU]=a};a.qg=function(b){this.$B=[];if(g(document.body).hasClass("oj-hicontrast"))this.$B=
a.qg.P0.slice();else{if(!a.qg.kC){a.qg.kC=[];var c=g(document.createElement("div"));c.attr("style","display:none;");c.attr("id","attrGps");g(document.body).append(c);for(var d=0;d<a.qg.h2.length;d++){var e=g(document.createElement("div"));e.addClass(a.qg.h2[d]);c.append(e);(e=e.css("color"))&&a.qg.kC.push(e)}c.remove()}this.$B=0<a.qg.kC.length?a.qg.kC.slice():a.qg.P0.slice()}this.Init(b)};o_("ColorAttributeGroupHandler",a.qg,a);a.b.ta(a.qg,a.dk,"oj.ColorAttributeGroupHandler");a.qg.P0="#267db3 #68c182 #fad55c #ed6647 #8561c8 #6ddbdb #ffb54d #e371b2 #47bdef #a2bf39 #a75dba #f7f37b".split(" ");
a.qg.h2="oj-dvt-category1 oj-dvt-category2 oj-dvt-category3 oj-dvt-category4 oj-dvt-category5 oj-dvt-category6 oj-dvt-category7 oj-dvt-category8 oj-dvt-category9 oj-dvt-category10 oj-dvt-category11 oj-dvt-category12".split(" ");a.qg.kC=null;a.qg.prototype.yn=function(){return this.$B};a.b.g("ColorAttributeGroupHandler.prototype.getValueRamp",{yn:a.qg.prototype.yn});var f={CSS_TEXT_PROPERTIES:function(a){var b={};a&&(a.hasClass("oj-gauge-metric-label")&&a.hasClass(a.parentNode,"oj-ledgauge")?(b["font-size"]=
!0,b.color=!0):a.hasClass(a,"oj-chart-slice-label")?b.color=!0:a.hasClass("oj-treemap-node-header")&&(b["font-weight"]=!0));return f.Joa(a,b)},CSS_BACKGROUND_PROPERTIES:function(a){return f.Boa(a)},CSS_URL:function(a){return f.dza(a)},g1:"rgb(254, 0, 254)",pla:"Times",qla:"1px",i1:"1",h1:"normal",ila:4,QK:{},hFa:function(a,b){return a.css(b)},dza:function(a){return(a=a.css("background-image"))&&-1!==a.indexOf("url(")?a.slice(a.indexOf("url(")+4,a.length-1).replace(/"/g,""):a},Boa:function(a){var b=
{};a.css("border-top-color")&&(b["border-color"]=a.css("border-top-color"));a.css("border-width")&&a.css("border-style")&&"none"!=a.css("border-style")&&(b["border-width"]=a.css("border-width"));a.css("background-color")&&(b["background-color"]=a.css("background-color"));return b},Joa:function(a,b){var c={},d=a.css("font-family");d&&d!==f.pla&&(c["font-family"]=d.replace(/"/g,"'"));d=a.css("font-size");!d||-1<d.indexOf("px")&&parseFloat(d)<f.ila||b["font-size"]||(c["font-size"]=d);(d=a.css("font-weight"))&&
d!==f.i1&&!b["font-weight"]&&(c["font-weight"]=d);(d=a.css("color"))&&d!==f.g1&&!b.color&&(c.color=d);(d=a.css("font-style"))&&d!==f.h1&&(c["font-style"]=d);return c},wIa:function(a,b,c,d){var e=g(document.createElement("div"));e.attr("style","display:none;");a.append(e);a="";for(var t=0;t<c.length;t++)a=a+c[t]+" ";e.attr("class",a);g(document.body).append(e);c=g(document.createElement("div"));c.css("font-size",f.qla);c.css("color",f.g1);c.css("font-weight",f.i1);c.css("font-style",f.h1);e.append(c);
for(var r in d)a=d[r],a instanceof Array||(a=[a]),f.Bza(c,b,r,a);e.remove()},Bza:function(a,b,c,d){f.QK[c]||(f.QK[c]={});for(var s=null,t=0;t<d.length;t++){var r=d[t],n=r.property;if(n){var p=f.QK[c][n];"undefined"==typeof p&&(s||(s=g(document.createElement("div")),s.addClass(c),a.append(s)),p=f.VAa(s,n),f.QK[c][n]=p);if(null!=p){var r=new e(b,r.path),q=f[n];if(null!=q){var u=r.ie();if("CSS_URL"!==n){n="";if(null!=u){var u=f.Tta(u),v;for(v in p)-1===u.indexOf(v)&&(n+=v+":"+p[v]+";");n+=u}else for(v in p)n+=
v+":"+p[v]+";";p=n}}r.jia(p,null!=q)}}}},Tta:function(a){if(a instanceof Object){var b="",c;for(c in a)var d=c.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase(),b=b+(d+":"+a[c]+";");return b}return null!=a&&"string"==typeof a?a:""},VAa:function(a,b){var c=f[b],c=c?c(a):f.hFa(a,b);return null==c||"string"==typeof c&&""==c.replace(/^\s+/g,"")?null:c}};a.Na("oj.dvtBaseComponent",g.oj.baseComponent,{_ComponentCreate:function(){this._super();this.BD=this.vV=0;this.Mo=null;for(var b=this.Cf(),c=0;c<b.length;c++)this.element.addClass(b[c]);
this.jK=g(document.createElement("div"));this.jK.attr("style","visibility:hidden;");this.element.append(this.jK);this.ag=(b=this.element[0].parentElement)&&b.vC?b.vC:new d.Context(this.element[0],null,this.jK[0]);this.ag.setReadingDirection(this.hd());this.ag.setTooltipAttachedCallback(a.Components.Tg);this.ag.setOverlayAttachedCallback(a.Components.Tg);this.ag.setTooltipStyleClass("oj-dvt-tooltip");this.ag.setDatatipStyleClass("oj-dvt-datatip");this.ag.setDefaultFontFamily(this.jK.css("font-family"));
g(document.body).hasClass("oj-hicontrast")&&d.Agent.setHighContrast(!0);this.xa=this.zg(this.ag,this.ql,this);this.ag.getStage().addChild(this.xa);!1!==d.requireJS&&(this.VBa(),this.V$());this.Rp();this.options._environment="jet";this.options._widgetConstructor=a.Components.Mf(this.element)},Hh:function(){this._super();this.element.attr("tabIndex",0);"off"!=this.options.trackResize&&this.kQ();this.P$();this.Mh()},refresh:function(){this._super();this.ag.setReadingDirection(this.hd());this.V$();this.Mh()},
getNodeBySubId:function(a){var b=this.xa&&this.xa.getAutomation?this.xa.getAutomation():null;if(b)return a=this.pk(a),b.getDomElementForSubId(a)},getSubIdByNode:function(a){var b=this.xa&&this.xa.getAutomation?this.xa.getAutomation():null;if(b)return(a=b.getSubIdForDomElement(a))?this.Ih(a):null},pk:function(){return null},Ih:function(){return null},aH:function(){f.wIa(this.element,this.options,this.Cf(),this.qk())},Cf:function(){return["oj-dvtbase"]},qk:function(){return{"oj-dvt-no-data-message":{path:"_statusMessageStyle",
property:"CSS_TEXT_PROPERTIES"}}},rj:function(){return[]},Ji:function(){var b=this.options.translations,b={"DvtUtilBundle.CLEAR_SELECTION":b.labelClearSelection,"DvtUtilBundle.COLON_SEP_LIST":b.labelAndValue,"DvtUtilBundle.INVALID_DATA":b.labelInvalidData,"DvtUtilBundle.NO_DATA":b.labelNoData,"DvtUtilBundle.DATA_VISUALIZATION":b.labelDataVisualization,"DvtUtilBundle.STATE_SELECTED":b.stateSelected,"DvtUtilBundle.STATE_UNSELECTED":b.stateUnselected,"DvtUtilBundle.STATE_MAXIMIZED":b.stateMaximized,
"DvtUtilBundle.STATE_MINIMIZED":b.stateMinimized,"DvtUtilBundle.STATE_EXPANDED":b.stateExpanded,"DvtUtilBundle.STATE_COLLAPSED":b.stateCollapsed,"DvtUtilBundle.STATE_ISOLATED":b.stateIsolated,"DvtUtilBundle.STATE_HIDDEN":b.stateHidden,"DvtUtilBundle.STATE_VISIBLE":b.stateVisible,"DvtUtilBundle.SCALING_SUFFIX_THOUSAND":b.labelScalingSuffixThousand,"DvtUtilBundle.SCALING_SUFFIX_MILLION":b.labelScalingSuffixMillion,"DvtUtilBundle.SCALING_SUFFIX_BILLION":b.labelScalingSuffixBillion,"DvtUtilBundle.SCALING_SUFFIX_TRILLION":b.labelScalingSuffixTrillion,
"DvtUtilBundle.SCALING_SUFFIX_QUADRILLION":b.labelScalingSuffixQuadrillion},c=a.hb.UE("abbreviated");b["DvtUtilBundle.MONTH_SHORT_JANUARY"]=c[0];b["DvtUtilBundle.MONTH_SHORT_FEBRUARY"]=c[1];b["DvtUtilBundle.MONTH_SHORT_MARCH"]=c[2];b["DvtUtilBundle.MONTH_SHORT_APRIL"]=c[3];b["DvtUtilBundle.MONTH_SHORT_MAY"]=c[4];b["DvtUtilBundle.MONTH_SHORT_JUNE"]=c[5];b["DvtUtilBundle.MONTH_SHORT_JULY"]=c[6];b["DvtUtilBundle.MONTH_SHORT_AUGUST"]=c[7];b["DvtUtilBundle.MONTH_SHORT_SEPTEMBER"]=c[8];b["DvtUtilBundle.MONTH_SHORT_OCTOBER"]=
c[9];b["DvtUtilBundle.MONTH_SHORT_NOVEMBER"]=c[10];b["DvtUtilBundle.MONTH_SHORT_DECEMBER"]=c[11];return b},V$:function(){var a=this.Ji();d.Bundle.addLocalizedStrings(a)},VBa:function(){var b={};b.numberConverterFactory=a.Ea.Gea("number");b.dateToIsoConverter=function(b){return b instanceof Date?a.Qa.dateToLocalIso(b):b};b.isoToDateConverter=function(b){return"string"==typeof b?a.Qa.isoToLocalDate(b):b};this.ag.setLocaleHelpers(b)},_destroy:function(){this.ag.hideTooltips();this.ag=null;var a=this.element[0].parentElement;
a&&a.vC&&(a.vC=null);this.xa.destroy&&this.xa.destroy();this.xa=null;this.rV();this.element.children().remove();this.element.removeAttr("role").removeAttr("tabIndex").removeAttr("aria-activedescendant");for(var a=this.Cf(),b=0;b<a.length;b++)this.element.removeClass(a[b]);this._super()},_setOptions:function(a,b){this._superApply(arguments);var c=this.options.trackResize;"off"==c&&this.Ll?this.rV():"off"==c||this.Ll||this.kQ();this.P$();if(!this.v3){var d=!1,e=this.rj(),f=["highlightedCategories",
"selection","dataCursorPosition"];g.each(a,function(a){if(0>e.indexOf(a)&&0>f.indexOf(a))return d=!0,!1});d?this.Mh():(void 0!==a.highlightedCategories&&this.xa.highlight(a.highlightedCategories),void 0!==a.selection&&this.xa.select(a.selection),void 0!==a.dataCursorPosition&&this.xa.positionDataCursor&&this.xa.positionDataCursor(a.dataCursorPosition))}},zg:function(){return null},ql:function(a){var b=a.type;"selection"===b?this.ce("selection",a.selection):"categoryHide"===b||"categoryShow"===b?this.ce("hiddenCategories",
a.hiddenCategories):"categoryHighlight"===b?this.ce("highlightedCategories",a.categories):"optionChange"===b?this.ce(a.key,a.value,a.optionMetadata):"touchHoldRelease"===b&&this.options.contextMenu?this.jh(g.Event(a.nativeEvent),"touch"):"ready"===b&&0===this.BD&&(this.fV&&this.fV(!0),this.Y$=!0,this.eV=this.fV=null)},kQ:function(){this.Ll||(this.Ll=this.Hg.bind(this),a.u.Mk(this.element[0],this.Ll,250))},rV:function(){this.Ll&&(a.u.lm(this.element[0],this.Ll),this.Ll=null)},Hg:function(){var a=this.element.width(),
b=this.element.height();(null==this.mL||null==this.sJ||5<=Math.abs(a-this.mL)+Math.abs(b-this.sJ))&&this.Mh(!0)},Rp:function(){},Mh:function(b){this.ag.hideTooltips();this.J1();this.ag.isReadyToRender()?(this.mL=this.OG()?null:this.element.width(),this.sJ=this.OG()?null:this.element.height(),this.options._width=this.mL,this.options._height=this.sJ,this.options._locale=a.fa.Wi(),this.options.dnd&&this.element.attr("draggable",!0),this.aH(),this.vV++,b?this.Mo||this.tV(null):0===this.TAa().length&&
this.tV(this.options),this.xV=!1):this.xV=!0},Sp:function(){this._super();this.xV&&this.Mh()},Or:function(){this._super();this.xV&&this.Mh()},sj:function(){this._super();this.ag.hideTooltips()},Km:function(){this._super();this.ag.hideTooltips()},ce:function(a,b,c){this.v3=!0;this.option(a,b,{_context:{Ed:!0,Nt:c,ob:!0}});this.v3=!1},ih:function(a,b,c){"touch"!==c&&("keyboard"===c?this.jh(b,c,{position:{of:this.xa.getKeyboardFocus()}}):this._super(a,b,c))},wB:function(b){return(b=a.Components.Mf(b)("instance"))?
b.xa:null},Hi:function(a){if(a){var b={},c;for(c in a)this.Bna(a,c,b);Object.defineProperties(a,b)}},Bna:function(a,b,c){var d=("selected"==b?"is":"get")+b.charAt(0).toUpperCase()+b.slice(1);c[d]={value:function(){return a[b]}}},Bu:function(a){for(var b="",c=0;c<a.length;c++)b+="["+a[c]+"]";return b},Zn:function(a){for(var b=[],c=0;0<a.indexOf("[",c);){var d=a.indexOf("[",c)+1,c=a.indexOf("]",c);b.push(Number(a.substring(d,c)));c+=1}return b},tk:function(a){return Number(this.HG(a))},HG:function(a){var b=
a.indexOf("[")+1,c=a.indexOf("]");return a.substring(b,c)},rk:function(){return{}},TAa:function(){this.Mo=null;var a=this.rk(),b;for(b in a)for(var c=a[b],d=0;d<c.length;d++)if("root"===b){if(this.Wu(this.options,c[d]))break}else{var e=this.options[b];if(e)for(var f=0;f<e.length&&!this.Wu(e[f],c[d]);f++);}var g=[];this.BD=0;if(this.Mo){var n=this;for(b in a)c=a[b],c.forEach(function(a){var c;if("root"===b)(c=n.p7(n.Mo,a))&&g.push(c);else{var d=n.Mo[b];if(d)for(var e=0;e<d.length;e++)(c=n.p7(d[e],
a))&&g.push(c)}})}return g},Wu:function(a,b){if(!this.Mo){var c=(new e(a,b)).ie();c&&(c instanceof Function||c instanceof Promise)&&(this.Mo=d.JsonUtils.clone(this.options))}return null!==this.Mo},p7:function(a,b){var c=new e(a,b),d=c.ie();d instanceof Function&&(d=Promise.resolve(d(this.c1(a))));if(d&&d instanceof Promise){this.BD++;var f=this.vV,g=this;d.then(function(a){g.Haa(f,c,a)},function(){g.Haa(f,c,[])});return d}return null},Haa:function(a,b,c){a===this.vV&&(this.BD--,b.jia(c,!0),0===this.BD&&
(this.tV(this.Mo),this.Mo=null))},tV:function(a){var b=this.OG()&&this.Ll;b&&this.rV();this.xa.render(a,this.mL,this.sJ);b&&this.kQ()},c1:function(){return{}},OG:function(){return!1},whenReady:function(){if(this.Y$)return Promise.resolve(!0);if(!this.eV){var a=this;this.eV=new Promise(function(b){a.fV=b})}return this.eV},J1:function(){this.Y$=!1},P$:function(){var a=this.options.tooltip;"function"===typeof a&&(this.options.tooltip={renderer:a})}},!0);a.Components.Ta("dvtBaseComponent","baseComponent",
{properties:{trackResize:{type:"string"}},methods:{whenReady:{}},extension:{_widgetName:"dvtBaseComponent"}})});