/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","ojs/ojjquery-hammer","ojs/ojcomponentcore","ojs/ojvalidation","ojs/ojpopup"],function(a,g,c){a.Me={};o_("EditableValueUtils",a.Me,a);a.Me.KFa=function(a,b){var c,d,e={};if(a&&b)switch(b){case "disabled":c=void 0!==a.attr("disabled")?!!a.prop("disabled"):void 0;break;case "pattern":c=a.prop("pattern")||void 0;break;case "placeholder":c=a.prop("placeholder")||void 0;break;case "readonly":c=void 0!==a.attr("readonly")?!!a.prop("readonly"):void 0;break;case "required":c=
a.attr("required");d=a.prop("required");c=void 0!==c?void 0!==d?!!d:!!c:void 0;break;case "title":c=void 0!==a.attr("title")?a.prop("title"):void 0;break;case "value":c=a.val()||void 0;break;default:c=a.attr(b)||void 0}void 0!==c?(e.qea=!0,e.value=c):e.qea=!1;return e};a.Me.np=function(b,c,d,e){for(var h={},f=0;f<b.length;f++){var k,g=b[f];k=g.ga;var l=g.option||k,w=g.oh,g=g.Od,y=d.element,x=d.options[l];void 0===c[l]&&(x=d.options[l],k=a.Me.KFa(y,k),k.qea&&(k=k.value,w&&("boolean"===typeof w?k=a.Me.FEa(l,
k):"function"===typeof w&&(k=w.call(d,k))),h[l]=k));w=l in h?h[l]:x;g&&"boolean"===typeof g&&a.Me.PJa(l,w)}null!=e&&e(h);d.option(h,{_context:{Ed:!0,ob:!0}})};a.Me.PJa=function(a,b){var c=!1;switch(a){case "required":null!==b&&"boolean"!==typeof b&&(c=!0);break;case "readOnly":case "disabled":null!==b&&"boolean"!==typeof b&&(c=!0)}if(c)throw"Option '"+a+"' has invalid value set: "+b;};a.Me.FEa=function(a,b){var c=b;switch(a){case "required":c=b?!0:!1}return c};a.Me.vZ=function(a,b){if(a&&b){var c=
b["class"];c&&a.addClass(c);if(c=b.style){var d=a.attr("style");d?a.attr("style",d+";"+c):a.attr("style",c)}}};a.Kb=function(a){this.Init(a)};a.tb.rN(a.tb.Re.pG,a.Kb);a.b.ta(a.Kb,a.md,"oj.PopupMessagingStrategy");a.Kb.yx={ojRadioset:{position:"launcher",un:{open:"focusin mouseenter press",close:"mouseleave"}},ojCheckboxset:{position:"launcher",un:{open:"focusin mouseenter press",close:"mouseleave"}},ojInputText:{position:"launcher",un:{open:"focusin"}},ojTextArea:{position:"launcher",un:{open:"focusin"}},
ojInputPassword:{position:"launcher",un:{open:"focusin"}},ojSwitch:{position:"launcher",un:{open:"focusin mouseover",close:"mouseout"}},ojSlider:{position:"launcher",un:{open:"focusin mouseover",close:"mouseout"}},"default":{position:"launcher-wrapper",un:{open:"focusin"}}};a.Kb.KP="oj-form-control-hint";a.Kb.zma="oj-form-control-hint-converter";a.Kb.Bma="oj-form-control-hint-validator";a.Kb.Ama="oj-form-control-hint-title";a.Kb.prototype.dt=function(b){a.Kb.t.dt.call(this,b);this.Pwa()};a.Kb.prototype.Lw=
function(b){a.Kb.t.Lw.call(this,b);this.Vca()};a.Kb.prototype.update=function(){a.Kb.t.update.call(this);this.Vca()};a.Kb.prototype.ep=function(){this.mDa();this.Uqa();a.Kb.t.ep.call(this)};a.Kb.prototype.close=function(){this.fR()};a.Kb.prototype.fR=function(){this.B9()&&this.xf.ojPopup("close")};a.Kb.prototype.Pwa=function(){this.aK||this.cAa()};a.Kb.prototype.y$=function(b){var c,d;d=this.hl();if(this.Uoa()&&(c=this.B3(),!a.bb.Vl(c))){var e=this.n7(),h=e.ojPopup("isOpen");h?h&&(b=e[0],b.innerHTML=
"",b.innerHTML=c,e.ojPopup("refresh")):("press"===b.type&&this.Vya(d),b=e[0],b.innerHTML="",b.innerHTML=c,e.ojPopup("open",d))}};a.Kb.prototype.Vya=function(a){var b=!0;this.to=function(a){b&&(a.preventDefault(),a.stopPropagation(),"click"===a.type&&(b=!1))};a[0].addEventListener("click",this.to,!0);a[0].addEventListener("change",this.to,!0);a.one("touchend",function(){setTimeout(function(){b=!1},50)})};a.Kb.prototype.Uoa=function(){var a=this.ym().options,b=a.readOnly||!1;return!(a.disabled||b)};
a.Kb.prototype.Vca=function(){var a,b,c=!1,d;this.B9()&&(d=this.n7(),c=d.ojPopup("isOpen"),a=this.B3(),b=document.activeElement===this.hl()[0]?!0:!1,c?a?(b=d[0],b.innerHTML="",b.innerHTML=a,d.ojPopup("refresh")):d.ojPopup("close"):b&&a&&this.y$(void 0))};a.Kb.prototype.mDa=function(){var b,c,d,e,h;b=(b=a.Kb.yx[this.ym().widgetName])?b.un:a.Kb.yx["default"].un;if(d=b.open)c=this.aK,delete this.aK,c&&(h=d.indexOf("press"),e=d.replace("press"," "),d=this.hl(),d.off(e,c),this.to&&(d[0].removeEventListener("click",
this.to,!0),d[0].removeEventListener("change",this.to,!0),delete this.to),-1!==h&&(d.$j().off("press"),d.removeData("ojHammer")));(c=b.close)&&(b=this.q4)&&this.hl().off(c,b)};a.Kb.prototype.cAa=function(){var b,d,e,h=this.hl(),k;d=(d=a.Kb.yx[this.ym().widgetName])?d.un:a.Kb.yx["default"].un;d.open&&(b=this.aK,b||(b=this.aK=g.proxy(this.y$,this)),k=d.open.indexOf("press"),e=d.open.replace("press"," "),h.on(e,b),-1!==k&&(e={recognizers:[[c.Press,{time:750}]]},h.$j(e).on("press",b)));d.close&&(b=this.q4,
b||(b=this.q4=g.proxy(this.fR,this)),h.on(d.close,b))};a.Kb.prototype.Fta=function(){var b,c;(b=(b=a.Kb.yx[this.ym().widgetName])?b.position:a.Kb.yx["default"].position)&&("launcher"===b?c=this.hl():"launcher-wrapper"===b&&(c=this.hl().parent()));c||(c=this.ym().widget());return{my:"start bottom",at:"end top",collision:"flipcenter",of:c}};a.Kb.prototype.n7=function(){var b,c;if(this.xf)return this.xf;b=a.gf.Yea();c=this.Fta();b.ojPopup("option","position",c);b.ojPopup("option","close",g.proxy(this.kza,
this));b.ojPopup("option","open",g.proxy(this.lza,this));return this.xf=b};a.Kb.prototype.lza=function(b){var c=g(b.target),d=this;window.setTimeout(function(){a.Components.oY(c)?c.ojPopup("option","autoDismiss","focusLoss"):delete d.xf},10)};a.Kb.prototype.kza=function(b){var c=this.hl();b=g(b.target);a.Components.oY(b)&&(b.ojPopup("option","autoDismiss","none"),b.ojPopup("option","open",null),b.ojPopup("option","close",null));this.to&&(c[0].removeEventListener("click",this.to,!0),c[0].removeEventListener("change",
this.to,!0),delete this.to);delete this.xf;b.children().remove()};a.Kb.prototype.Uqa=function(){this.fR();a.gf.lFa()};a.Kb.prototype.B3=function(){var b=!1,c=this.ym().document[0],d=[],e="";this.k0()&&d.push(this.AQ(c));(this.GO()||this.m0()||this.l0())&&d.push(this.Coa(c));g.each(d,function(d,h){h&&(b?e=e.concat(a.rb.eGa(c)):b=!0,e=e.concat(h))});return e};a.Kb.prototype.AQ=function(b){var c="",d=this.cO();this.lO()&&(c=this.dO(),c=a.rb.uda(b,c,d,!1));return c};a.Kb.prototype.Coa=function(b){var c;
c=[];var d="",e;this.GO()&&(c=this.t_(),c=c.length?c[0]:"",d+=a.rb.aX(b,a.Kb.zma,c,!1,a.Kb.KP));if(this.m0())for(c=this.Aja(),e=0;e<c.length;e++)d+=a.rb.aX(b,a.Kb.Bma,c[e],!1,a.Kb.KP);this.l0()&&(d+=a.rb.aX(b,a.Kb.Ama,this.zja(),!0,a.Kb.KP));return d?"\x3cdiv class\x3d'oj-form-control-hints'\x3e"+d+"\x3c/div\x3e":""};a.Kb.prototype.B9=function(){return this.xf?a.Components.oY(this.xf):!1};a.rb={};a.rb.aX=function(b,c,d,e,h){var k;d&&(k=g(b.createElement("div")),k.addClass(h+(" "+c)),k.append(a.rb.I7(b,
d,e)));return k?k.get(0).outerHTML:""};a.rb.lfa=function(b){var c;switch(b){case a.ia.Xc.FATAL:c=a.va.F("oj-message.fatal");break;case a.ia.Xc.ERROR:c=a.va.F("oj-message.error");break;case a.ia.Xc.WARNING:c=a.va.F("oj-message.warning");break;case a.ia.Xc.INFO:c=a.va.F("oj-message.info");break;case a.ia.Xc.CONFIRMATION:c=a.va.F("oj-message.confirmation")}return c};a.rb.eGa=function(a){return(a=g(a.createElement("hr")))?a.get(0).outerHTML:""};a.rb.uda=function(b,c,d,e){var h="",k,f,g=[],l={},w;for(f=
0;f<c.length;f++)k=c[f],g=k instanceof a.ia?k:new a.ia(k.summary,k.detail,k.severity),w=a.ia.Zz(g.severity),l[w]||(l[w]=[]),l[w].push(g);for(f=d;f>=a.ia.Xc.CONFIRMATION;f--)for(g=l[f]||[],c=0;c<g.length;c++)k=g[c],a.o.ue(k,a.ia),w=a.ia.Zz(k.severity),d=a.rb.lfa(w),d=k.summary||d,k=k.detail||"",h=h.concat(a.rb.tda(b,d,k,w,e));return h};a.rb.tda=function(b,c,d,e,h){var k,f;f=a.rb.lfa(e);k=g(b.createElement("div"));k.addClass(a.rb.Cma);h&&k.addClass(a.rb.Pta(e));h=g(b.createElement("span"));h.addClass(a.rb.Ota(e)).attr("title",
f).attr("role","img");k.append(h);e=g(b.createElement("span"));e.addClass(a.rb.Fma);f=g(b.createElement("div"));f.addClass(a.rb.Jma).text(c);e.append(f);d&&(c=a.rb.I7(b,d,!0),b=g(b.createElement("div")),b.addClass(a.rb.Gma).append(c),e.append(b));k.append(e);return k?k.get(0).outerHTML:""};a.rb.Ota=function(b){var c;switch(b){case a.ia.Xc.FATAL:c=a.rb.g2;break;case a.ia.Xc.ERROR:c=a.rb.g2;break;case a.ia.Xc.WARNING:c=a.rb.Lma;break;case a.ia.Xc.INFO:c=a.rb.Ima;break;case a.ia.Xc.CONFIRMATION:c=a.rb.Ema}return a.rb.Jka+
c};a.rb.Pta=function(b){switch(b){case a.ia.Xc.FATAL:b=a.rb.e2;break;case a.ia.Xc.ERROR:b=a.rb.e2;break;case a.ia.Xc.WARNING:b=a.rb.Kma;break;case a.ia.Xc.INFO:b=a.rb.Hma;break;default:b=a.rb.Dma}return b};a.rb.I7=function(b,c,d){var e=null;a.bb.Ke(c)&&(d&&a.u.FHa(c)?e=a.u.BEa(c.substring(6,c.length-7)):(e=b.createElement("span"),e.textContent=c));return e};a.rb.Jka="oj-component-icon oj-message-status-icon ";a.rb.Cma="oj-message";a.rb.Jma="oj-message-summary";a.rb.Gma="oj-message-detail";a.rb.Fma=
"oj-message-content";a.rb.g2="oj-message-error-icon";a.rb.Lma="oj-message-warning-icon";a.rb.Ima="oj-message-info-icon";a.rb.Ema="oj-message-confirmation-icon";a.rb.e2="oj-message-error";a.rb.Kma="oj-message-warning";a.rb.Hma="oj-message-info";a.rb.Dma="oj-message-confirmation";a.gf={};a.gf.Yea=function(){var b=a.gf.m7(),c=b.find("."+a.gf.LP);0===c.length?(c=g(a.gf.Eta()).hide(),c.appendTo(b),c.ojPopup({rootAttributes:{"class":a.gf.Mma},initialFocus:"none",tail:"simple",autoDismiss:"none",modality:"modeless"})):
c=g(c[0]);return c};a.gf.lFa=function(){var b;0<a.gf.Ysa()&&(b=a.gf.Yea(),b.ojPopup("destroy"),b.remove())};a.gf.m7=function(){var b=g("#"+a.gf.A1);if(0<b.length)return b;b=g("\x3cdiv\x3e");b.attr("id",a.gf.A1);b.attr("role","presentation");b.appendTo(g(document.body));return b};a.gf.Ysa=function(){return a.gf.m7().find("."+a.gf.LP).length};a.gf.Eta=function(){return"\x3cdiv class\x3d'"+a.gf.LP+"'\x3e\x3c/div\x3e"};a.gf.LP="oj-messaging-popup-container";a.gf.Mma="oj-messaging-popup";a.gf.A1="__oj_messaging_popup_pool";
(function(){a.Na("oj._ojLabel",g.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3clabel\x3e",widgetEventPrefix:"oj",options:{ariaRequiredUnsupported:!1,describedById:null,help:{definition:null,source:null},required:!1,rootAttributes:null},Ja:{D2:"tooltipHelp",E2:"tooltipRequired"},widget:function(){return this.Uw},refresh:function(){this._super();this.haa();this.daa()},Xf:function(a,b){this._super(a,b);this.bpa();this.UQ()},_ComponentCreate:function(){this._super();this.VK=this.eventNamespace+
"TouchEatClick";this.Fy=this.eventNamespace+"HelpDefPopup";this.bs=a.u.af();this.xra()},IB:function(a){this.cE=a.attr("class")},Lx:function(){this.cE?this.element.attr("class",this.cE):this.element.removeAttr("class")},sj:function(){this._superApply(arguments);this.eR()},Km:function(){this._superApply(arguments);this.eR()},xra:function(){var a=this.options,b=a.required,a=a.ariaRequiredUnsupported,c=this.n$(),d=null;this.Uw=this.element.wrap(this.yqa()).closest(".oj-component");this.zya();c&&(d=this.pR());
this.G4(d);b&&(a?d.appendChild(this.YH()):this.element.before(this.YH()))},G4:function(a){var b=this.options,c=b.help.definition;if(b.help.source||c)this.dxa(a),this.loa()},bpa:function(){var a=this.options.required;if(null!==a&&"boolean"!==typeof a)throw Error("Option 'required' has invalid value set: "+a);},UQ:function(){var a=this.options;if(this.n$()&&null==a.describedById)throw Error("ojLabel's describedById option must be set if help source is set\n\r\n      or (ariaRequiredUnsupported and required is set).");
},zya:function(){var a;a=this.element.attr("class");var b,c;if(a&&(a=a.split(/\s+/),null!=a)){c=a.length;for(var d=0;d<c;d++)b=a[d],0<b.indexOf("-label")&&(this.Uw.addClass(b),this.element.removeClass(b))}},pR:function(){var a=this.Uw.find(".oj-label-group"),b=document.createElement("span");b.setAttribute("id",this.options.describedById);a.prepend(b);return b},yqa:function(){var a,b,c=this.options.rootAttributes;b="oj-label oj-component";c&&(a=c["class"]);null!==a&&(b=b+" "+a);a=document.createElement("div");
a.className=b;b=document.createElement("div");b.className="oj-label-group";a.appendChild(b);return a},YH:function(){var a=this.F(this.Ja.E2),b=document.createElement("span");b.className="oj-label-required-icon oj-component-icon";b.setAttribute("role","img");b.setAttribute("title",a);b.setAttribute("aria-label",a);return b},$pa:function(b,c){var d;if(this.WJ()){d=document.createElement("a");d.setAttribute("tabindex","0");d.setAttribute("target","_blank");d.className="oj-label-help-icon-anchor oj-label-help-icon oj-component-icon oj-clickable-icon-nocontext";
if(c)try{a.u.OJa(c),d.setAttribute("href",c)}catch(e){throw Error(e+". The source option ("+c+") is invalid.");}else d.setAttribute("role","img");b?d.setAttribute("aria-label",b):d.setAttribute("aria-label",this.F(this.Ja.D2))}return d},loa:function(){var a,b=this.options.help.definition,d,e;e=this.widget().find(".oj-label-help-icon-anchor");if(0!=e.length){a=b?b:this.F(this.Ja.D2);this.vv?(d=g(document.getElementById(this.vv)))&&d.text(a):(b=document.createElement("div"),b.style.display="none",d=
g(b),d.uniqueId(),this.vv=d.prop("id"),d.text(a),a=document.getElementsByTagName("body")[0],a.appendChild(b));this.bs&&(this.SR&&this.widget().off(this.VK),this.SR=function(){return!1});var h=this;this.bK||(this.bK=function(a){h.Pva(a,d,e)});this.gR||(this.gR=function(){h.eR()});if(this.bs)e.$j({recognizers:[[c.Press,{time:750}]]}).on("press",this.bK);else e.on("focusin"+this.Fy+" mousedown"+this.Fy+" mouseover"+this.Fy,this.bK),e.on("mouseout"+this.Fy,this.gR);b={my:"start bottom",at:"end top",collision:"flipcenter",
of:e};d.ojPopup({position:b,modality:"modeless"})}},Pva:function(a,b,c){if(this.bs)if("press"===a.type){var d=this.widget();d.on("click"+this.VK,this.SR);var e=this;b.on("ojclose",function(){d.off(e.VK)})}else b.off("ojclose");b.ojPopup("isOpen")||b.ojPopup("open",c)},eR:function(){var a;null!=this.vv&&(a=g(document.getElementById(this.vv)),a.ojPopup("close"))},Aaa:function(a){this.bs&&(this.widget().off(this.VK),this.SR=null,a.$j().off(this.Fy));a.off(this.Fy);this.gR=this.bK=null},Baa:function(){var a;
if(null!=this.vv){if(a=g(document.getElementById(this.vv)))a.ojPopup("destroy"),a.remove();this.vv=null}},dxa:function(a){var b=this.options.help.definition,c=this.options.help.source;this.WJ()&&g(a).prepend(this.$pa(b,c))},n$:function(){var a=this.options;return this.WJ()||a.ariaRequiredUnsupported&&a.required},WJ:function(){var a=this.options;return a.help.source||a.help.definition},daa:function(){var a,b;this.UQ();a=this.Uw.find(".oj-label-help-icon");1===a.length&&(this.Aaa(a),this.Baa(),a.remove());
b=this.WJ();a=document.getElementById(this.options.describedById);b&&null==a?a=this.pR():b||null===a||0===a.children.length&&a.parentNode.removeChild(a);this.G4(a)},haa:function(){var a,b;b=this.Uw.find(".oj-label-required-icon");a=this.options.describedById;this.options.required?(this.UQ(),0===b.length?this.options.ariaRequiredUnsupported?(b=document.getElementById(a),null==b&&(b=this.pR()),b.appendChild(this.YH())):this.element.before(this.YH()):(a=this.F(this.Ja.E2),b.attr("title",a))):(b.remove(),
b=document.getElementById(a),null!==b&&0===b.children.length&&b.parentNode.removeChild(b))},_setOption:function(a,b){this._superApply(arguments);"required"===a&&this.haa();"help"===a&&this.daa()},getNodeBySubId:function(a){var b;b=this._super(a);b||(a=a.subId,"oj-label-help-icon"===a&&(b=this.widget().find(".oj-label-help-icon")[0]),"oj-label-required-icon"===a&&(b=this.widget().find(".oj-label-required-icon")[0]));return b||null},getSubIdByNode:function(a){var b=null;null!=a&&(a===this.widget().find(".oj-label-help-icon")[0]?
b={subId:"oj-label-help-icon"}:a===this.widget().find(".oj-label-required-icon")[0]&&(b={subId:"oj-label-required-icon"}));return b||this._superApply(arguments)},_destroy:function(){var b=this.Uw.find(".oj-label-help-icon");this.Aaa(b);this.Baa();a.u.unwrap(this.element,this.Uw);return this._super()}})})();var b={cja:1,e_:2,i_:3,P_:4,Q_:5,R_:6,Wja:7,jka:8,r0:9,s0:10,mka:11},d={kt:!0,qm:b.e_},e={kt:!0,qm:b.i_},f={kt:!0,qm:b.R_},h={kt:!0,qm:b.P_},k={kt:!0,qm:b.Q_},l={kt:!0,qm:b.s0};a.Na("oj.editableValue",
g.oj.baseComponent,{widgetEventPrefix:"oj",options:{disabled:!1,displayOptions:void 0,help:{definition:null,source:null},messagesCustom:void 0,messagesHidden:void 0,messagesShown:void 0,required:!1,title:"",validators:void 0,value:void 0},getNodeBySubId:function(a){return this._super(a)},isValid:function(){void 0===this.NW&&(this.NW=this.aua());return this.NW},refresh:function(){this._super();this.v5(!0)},reset:function(){this.OH();this.bE(this.Nm.Wja);this.kV(this.options.value,!0)},showMessages:function(){var b=
[],c,d,e=this.options.messagesHidden,h=!1;for(c=0;c<e.length;c++)h=!0,d=e[c],d instanceof a.be&&d.gsa(),b.push(d.clone());h&&(this.iC("messagesHidden"),this.fL("messagesShown",b))},validate:function(){return this.ic(this.Ag(),null,this.MB)},NB:{n_:1,lka:2,S_:3},Nm:b,MB:{hw:!1,qm:b.r0},Xf:function(a,b){this._super(a,b)},_ComponentCreate:function(){var a=["required","title","pattern"],b=this.element,c=this.mla(b);this._super();this.options.messagesCustom=this.options.messagesCustom||[];this.options.messagesHidden=
[];this.options.messagesShown=0<this.options.messagesCustom.length?this.opa(this.options.messagesCustom):[];this.MP(b);this.Cu()&&(this.Ur(this.options.placeholder),this.xR=!0);"input"===b[0].tagName.toLowerCase()&&g.each(a,function(a,d){d in c&&b.removeAttr(d)})},Hh:function(){this._super();this.jqa();this.v5(!1);this.zJ();this.bE(this.Nm.cja);0<this.options.messagesShown.length&&this.gE("messagesShown",this.options.messagesShown,null,!0);this.widget().addClass("oj-form-control")},IB:function(a){this.Sma(a)},
Lx:function(a){this.xma(a)},x0:function(a,b){switch(a){case "disabled":this.y0(a,e);break;case "converter":this.ska(a);break;case "displayOptions":this.zJ();break;case "help":this.vj(a,this.options[a]);break;case "messagesCustom":this.qya(b);break;case "placeholder":this.jza(b);break;case "readOnly":this.y0(a,h);break;case "required":this.tka(a);break;case "title":this.YCa();break;case "translations":this.refresh();break;case "value":this.uka(a,b);break;case "validators":this.rx(a)}},ska:function(a){var b=
!1;this.vma();this.pJ()&&(b=!0);b?(this.PH(),this.hL(d)):this.vj(a,this.options[a],!0)},y0:function(a,b){var c=!this.options[a];this.vj(a,this.options[a]);c&&this.Zaa(b)},tka:function(a){this.vj(a,this.options[a]);this.Zaa(f)},uka:function(a,b){var c=b?b._context:null,d,e=!1;c&&(e=c.originalEvent?!0:!1,d=c.kt||!1);e||(d||this.OH(null),this.bE(this.Nm.mka));this.vj(a,this.options[a],!0)},rx:function(){var a=!1;this.d2();this.pJ()&&(a=!0);a&&(this.PH(),this.hL(l))},zu:function(){var a=this.options.readOnly||
!1;return this.options.disabled||a?!1:!0},_destroy:function(){var b,c,d=this._super();this.widget();this.OH(null,!0);this.rs().ep();if(this.mc)for(c=this.mc.length,b=0;b<c;b++)this.mc[b]&&null!=a.Components.Mf(this.mc[b])&&g(this.mc[b])._ojLabel("destroy");return d},Focus:function(){this.Wf().focus();return!0},_setOption:function(b,c,d){var e;e=!1;if("string"===typeof b&&void 0!==c)switch(b){case "messagesHidden":e=!0;break;case "messagesShown":e=!0;break;case "rawValue":e=!0}if(e)return a.r.error(b+
" option cannot be set"),this;e=this._superApply(arguments);this.x0(b,d);return e},Wf:function(){return this.element},d1:function(){var a;a=this.j6(this.element);if(null!==a&&0!==a.length)return a;a=this.element.prop("id");if(void 0!==a&&(a=g("label[for\x3d'"+a+"']"),0!==a.length))return a;a=this.element.closest("[aria-labelledby]");return 0!==a.length&&(a=this.j6(a),null!==a&&0!==a.length)?a:null},Bx:function(){return this.element.val()},_GetMessagingLauncherElement:function(){return this.Wf()},
Yc:function(){var b;this.Pc||(b=this.options.converter,this.Pc=a.Qa.getConverterInstance(b));return this.Pc||null},xB:function(){this.K8||(this.K8={});return this.K8},Ag:function(){return this.Wf().val()},b1:function(){var b,c,d,e,h=!0,k,f,g;if(!this.UB){b=[];f=this.options.validators;d=this.xB();e=[];k=Object.keys(d);var l=k.length;if(0<l){for(c=0;c<l;c++)g=k[c],e.push(d[g]);b=b.concat(e)}if(f){d=[];for(c=0;c<f.length;c++)k=f[c],"object"===typeof k?(k.validate&&"function"===typeof k.validate||(h=
!1),h||(g=k.type)&&"string"===typeof g&&((e=a.Ea.Vw(g))?(k=a.Wc.pf({},k.options)||{},k.converter=k.converter||this.Yc(),k.label=k.label||this.IS(),k=e.createValidator(k)):a.r.error("Unable to locate a validatorFactory for the requested type: "+g)),d.push(k)):a.r.error("Unable to parse the validator provided:"+k);b=b.concat(d)}this.UB=b}return this.UB||[]},d2:function(){this.UB&&(this.UB.length=0);this.UB=null;this.rs().update(this.Bl(this.vk.t0))},vma:function(){this.Pc=null;this.rs().update(this.Bl(this.vk.d_))},
ao:function(){return this.options.required},JG:function(a){var b=this.Ag();this.ic(b,a)},Vp:function(a,b){var c={};c._context={originalEvent:b,Ed:!0,ob:!0,readOnly:!0};this.options.rawValue!==a&&this.option("rawValue",a,c)},vj:function(a,b,c){var d=this.options.help.definition,e=this.options.help.source;switch(a){case "converter":b=this.options.value;this.kV(b,c);break;case "disabled":this.maa("disabled",this.options.disabled);break;case "help":this.mc&&(a=this.lS(),this.mc._ojLabel("option","describedById",
a),this.mc._ojLabel("option","help",{definition:d,source:e}),this.baa(a));break;case "required":this.maa("required",this.ao());this.GP(b);this.mc&&(a=this.lS(),this.mc._ojLabel("option",{describedById:a,ariaRequiredUnsupported:this.qB()}),this.mc._ojLabel("option","required",b),this.baa(a));break;case "value":this.kV(b,c)}},GP:function(a){var b=this.Wf();a&&b?b.attr("aria-required",a):b.removeAttr("aria-required")},qB:function(){return!1},Km:function(){this._superApply(arguments);this.rs().close()},
sj:function(){this._superApply(arguments);this.rs().close()},JP:function(){this.mc&&this.mc._ojLabel("refresh");this.Pc=this.eU=null;this.d2()},ul:function(a){var b=this.Wf();b.val()!==a&&b.val(a)},MP:function(a){"boolean"===typeof this.options.disabled&&a.prop("disabled",this.options.disabled)},Ur:function(a){this.Wf().attr("placeholder",a)},i2:function(a){this.options.placeholder=a},Cu:function(){return this.options.placeholder},K0:function(){this.i2("");this.Ur("")},ic:function(b,c,d){var e=d&&
"boolean"===typeof d.hw?d.hw:!0;if(void 0===b)return a.r.warn("Attempt to set a value of undefined"),!1;if(e&&b===this.hta())a.r.je>a.r.Hr&&a.r.info("Validation skipped and value option not updated as submitted value '"+b.toString?b.toString():b+" same as previous.");else if(b=this.fQ(b,c,d),void 0!==b&&this.isValid()){var h;d&&d._context&&(h=d._context);this.Xca(b,c,d&&d.qm,h);return!0}return!1},fQ:function(b,c,d){var e=d&&d.QJa?d.QJa:this.NB.n_,h=d&&d.qm?d.qm:this.Nm.jka;d=d&&d.kt||!1;if(void 0===
b)a.r.warn("Attempt to set a value of undefined");else if(this.zu()){d||this.OH(c);this.Aba(b);try{return this.eBa(b,e,h,c)}catch(k){}}else a.r.je>a.r.Hr&&a.r.info("Validation skipped and value option not set as component state does not  allow setting value. For example if the component is readonly or disabled.")},uB:function(b,c,d){return"value"===b?a.b.Rj(c,d):0===b.indexOf("messages")?this.rya(c,d):this._superApply(arguments)},_GetDefaultStyleClass:function(){a.o.kd();return""},vk:{OA:1,u0:2,d_:3,
t0:4,o0:5},Tr:{disabled:"oj-disabled",required:"oj-required"},OH:function(a,b){b?(this.options.messagesHidden=[],this.options.messagesShown=[],this.options.messagesCustom=[]):(this.iC("messagesHidden",a),this.iC("messagesShown",a),this.iC("messagesCustom",a))},PH:function(){var b=this.options.messagesShown,c=b.length,d;this.iC("messagesHidden");for(var e=c-1;0<=e;e--)d=b[e],d instanceof a.be&&b.splice(e,1);b.length!==c&&this.gE("messagesShown",b,null,!0)},gE:function(a,b,c,d){var e={},h=0===b.length&&
0===this.options[a].length;if(d||!h)e._context={originalEvent:c,Ed:!0,ob:!0,readOnly:!0},e.changed=d||!h,this.RAa(),this.option(a,b,e),this.CDa()},iC:function(a,b){this.gE(a,[],b)},opa:function(b){var c,d=[],e;if(b&&0<b.length)for(e=0;e<b.length;e++)c=b[e],c instanceof a.ia?d.push(c.clone()):(c=new a.ia(c.summary,c.detail,c.severity),c=Object.freeze?Object.freeze(c):c,d.push(c));return d},jqa:function(){if(this.mc=this.d1()){var a=this.options.help.definition,b=this.options.help.source,c=this.options.required,
d=this.qB(),e=this.lS();this.m$(b,a,c,d)&&this.sH(e);this.mc._ojLabel({rootAttributes:{"class":this._GetDefaultStyleClass()+"-label"},describedById:e,required:c,ariaRequiredUnsupported:d,help:{definition:a,source:b}})}},v5:function(a){var b=!1;a?(this.JP(),this.zJ(),this.pJ()&&(b=!0),this.PH(),b?this.hL(k):(this.ao()&&this.bE(k.qm),this.vj("value",this.options.value,!0))):(this.vj("value",this.options.value),this.vj("required",this.options.required));this.vj("disabled",this.options.disabled)},FKa:function(){return this.u$},
hta:function(){void 0===this.TU&&(this.TU="");return this.TU},j6:function(a){a=a.attr("aria-labelledby");return void 0!==a?g("label[id\x3d'"+a+"']"):null},lS:function(){this.element.uniqueId();return this.element.prop("id")+"Icons"},m$:function(a,b,c,d){return null!=a||null!=b||c&&d},sH:function(a){var b;this.Wf().each(function(){var c=g(this).attr("aria-describedby"),c=c?c.split(/\s+/):[];b=g.inArray(a,c);-1===b&&c.push(a);c=g.trim(c.join(" "));g(this).attr("aria-describedby",c)})},nV:function(a){this.Wf().each(function(){var b,
c;c=(b=g(this).attr("aria-describedby"))?b.split(/\s+/):[];b=g.inArray(a,c);-1!==b&&c.splice(b,1);(b=g.trim(c.join(" ")))?g(this).attr("aria-describedby",b):g(this).removeAttr("aria-describedby")})},baa:function(a){this.m$(this.options.help.source,this.options.help.definition,this.options.required,this.qB())?this.sH(a):this.nV(a)},VI:function(){return this.options.messagesShown.concat(this.options.messagesHidden)},IS:function(){if(this.mc)return this.mc.text()},Q7:function(){this.ada||(this.ada=new a.sm(this.isValid(),
this.VI()));return this.ada},WT:function(){return!a.ia.isValid(this.VI())},pJ:function(){return!this.isValid()&&0<this.options.messagesShown.length},owa:function(){for(var b=this.options.messagesShown,c,d,e=0;e<b.length;e++)c=b[e],c instanceof a.be&&c.u9()&&(d=d||[],d.push(c));return void 0===d?!1:!a.ia.isValid(d)},zJ:function(){var a=this.rs(),b=this._GetMessagingLauncherElement(),c=this.Wf(),d=this.Bl(this.vk.OA);this.xR||this.K0();a.dt(b,c,d)},qya:function(b){var c=this.options.messagesCustom,
d=[],e,h,k=this.options.messagesShown,f=b?b._context:null;for(h=0;h<k.length;h++)e=k[h],e instanceof a.be&&e.u9()&&d.push(e);for(h=0;h<c.length;h++)d.push(c[h]);this.gE("messagesShown",d,f?f.originalEvent:null,b&&b.changed)},jza:function(a){a=(a&&a._context||{}).BHa?!1:!0;this.Ur(this.options.placeholder);a?(this.xR=!0,this.Yc()&&this.zJ()):this.xR=!1},SBa:function(a){this.u$=a},Aba:function(a){this.TU=a},YCa:function(){this.rs().update(this.Bl(this.vk.o0))},fL:function(a,b,c){var d,e,h;if("object"===
typeof b&&Array.isArray(b))for(h=this.options[a],d=b.length,e=0;e<d;e++)h.push(b[e]);this.gE(a,h,c,!0)},CDa:function(){this.rs().update(this.Bl())},Xca:function(a,b,c,d){d=d||{};b&&(d.originalEvent=b);switch(c){case this.Nm.e_:case this.Nm.i_:case this.Nm.P_:case this.Nm.Q_:case this.Nm.R_:case this.Nm.r0:case this.Nm.s0:d.Ed=!0,d.kt=!0}this.option({value:a},{_context:d})},RAa:function(){this.NW=void 0},aua:function(){var a=this.VI(),b=!0;a&&0!==a.length&&(b=!this.WT());return b},ev:function(b){var c=
b,d=this.Yc();d&&"object"===typeof d&&(d.format&&"function"===typeof d.format?c=d.format(b):a.r.je>a.r.Hr&&a.r.info("converter does not support the format method."));return c},rs:function(){this.js||(this.js=new a.tb(this));return this.js},cta:function(a){var b,c=[];b="";var d;this.ao()&&(b=this.S6(),b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b));for(d=0;d<a.length;d++)b=a[d],"object"===typeof b&&b.getHint&&"function"===typeof b.getHint&&(b=b.getHint())&&c.push(b);return c},
S6:function(){var b;b={};var c;null==this.eU&&(b=this.options.translations?this.options.translations.required||{}:{},c={hint:b.hint||null,label:this.IS(),messageSummary:b.messageSummary||null,messageDetail:b.messageDetail||null},this.eU=(b=a.Ea.Vw(a.Pe.VALIDATOR_TYPE_REQUIRED))?b.createValidator(c):null);return this.eU},Bl:function(a){var b={},c=this.Yc(),d="",e=[];a=a||this.vk.u0;if(a===this.vk.OA||a===this.vk.u0)e=this.VI(),this.Q7().update(this.isValid(),e),b.Sia=this.Q7();if(a===this.vk.OA||a===
this.vk.d_)c&&"object"===typeof c&&c.getHint&&"function"===typeof c.getHint&&(d=c.getHint()||""),b.Nda=d;if(a===this.vk.OA||a===this.vk.t0)c=this.b1(),e=this.cta(c)||[],b.RJa=e;if(a===this.vk.OA||a===this.vk.o0)b.title=this.options.title||"";return b},rya:function(b,c){var d=-1,e,h=!0,k=g.extend([],b),f=g.extend([],c);if(k.length!==f.length)return!1;g.each(k,function(b,c){c instanceof a.ia?e=c:(e=new a.ia(c.summary,c.detail,c.severity),e=Object.freeze?Object.freeze(e):e);d=-1;g.each(f,function(a,
b){e.Mq(b)&&(d=a)});-1<d?f.splice(d,1):h=!1});return h},cK:function(b){var c=this.Yc(),d=b;c&&"object"===typeof c&&(c.parse&&"function"===typeof c.parse?d=c.parse(b):a.r.je>a.r.Hr&&a.r.info("converter does not support the parse method."));return d},mQ:function(b,c){var d,e,h;b instanceof a.tg||b instanceof a.nk?(d=b.Wz(),a.o.ue(d,a.ia),h=d.severity,e=d.summary,d=d.detail):(h=a.ia.Xc.ERROR,e=a.va.F("oj-message.error"),d=b.message||a.va.F("oj-converter.detail"));c.push({summary:e,detail:d,severity:h})},
dV:function(b,c,d){var e={},h=[],k=b.tD||[];e.context=c||0;e.display=d||a.be.$w.yO;0===k.length&&this.mQ(b,k);for(c=0;c<k.length;c++)b=k[c],h.push(this.Vpa(b.summary,b.detail,b.severity,e));return h||null},Vpa:function(b,c,d,e){b=new a.be(b,c,d,e);return b=Object.seal?Object.seal(b):b},kV:function(a,b){var c=a||this.options.value,d;d=this.u$;(b||c!==d)&&this.yDa(c)},maa:function(a,b){-1!==Object.keys(this.Tr).indexOf(a)&&this.widget().toggleClass(this.Tr[a],!!b)},bE:function(b){if(this.zu())try{this.$ca(this.options.value,
this.NB.S_)}catch(c){(b=this.dV(c,b,a.be.$w.gO))&&this.fL("messagesHidden",b)}else a.r.je>a.r.Hr&&a.r.info("Deferred validation skipped as component is readonly or disabled.")},eBa:function(a,b,c,d){var e=a;try{b===this.NB.n_&&(e=this.cK(a)),this.$ca(e,b===this.NB.S_)}catch(h){throw a=this.dV(h,c),this.fL("messagesShown",a,d),h;}return e},Zaa:function(a){var b=!0;this.pJ()&&(b=!1);this.PH();b?this.ao()&&this.bE(a.qm):this.hL(a)},yDa:function(a,b){var c,d;this.SBa(a);c=a;try{c=this.ev(a)}catch(e){d=
this.dV(e),this.fL("messagesShown",d,b)}this.ul(c);c=this.Ag();this.Aba(c);this.Vp(c,null)},hL:function(a){var b;b=this.fQ(this.Ag(),null,a);void 0===b||!this.isValid()&&this.owa()||this.Xca(b,null,a.qm)},$ca:function(b,c){var d=this.b1(),e,h,k=[];if(this.ao()){e=this.S6();try{e.validate(a.bb.trim(b))}catch(f){this.mQ(f,k)}}if(!c)for(h=0;h<d.length;h++)if(e=d[h],"object"===typeof e)if(e.validate&&"function"===typeof e.validate)try{e.validate(b)}catch(g){this.mQ(g,k)}else a.r.je>a.r.Hr&&a.r.info("validator does not support the validate method.");
if(0<k.length)throw d=Error(),d.tD=k,d;}},!0);a.Components.Dp({editableValue:{displayOptions:a.Components.Lf(function(a){return{messages:0<=a.containers.indexOf("ojDataGrid")||0<=a.containers.indexOf("ojTable")?["notewindow"]:["inline"],converterHint:["placeholder","notewindow"],validatorHint:["notewindow"],title:["notewindow"]}})}});a.$g=function(a){this.Init(a)};a.tb.rN(a.tb.Re.$A,a.$g);a.b.ta(a.$g,a.md,"oj.InlineMessagingStrategy");a.$g.prototype.Lw=function(b){a.$g.t.Lw.call(this,b);this.eaa()};
a.$g.prototype.BZ=function(a){return a&&void 0!==a.Sia?!0:!1};a.$g.prototype.update=function(){a.$g.t.update.call(this);this.eaa()};a.$g.prototype.ep=function(){this.Daa();a.$g.t.ep.call(this)};a.$g.prototype.eaa=function(){var a,b;b=this.ym().widget();(a=this.Doa())&&null==this.xf&&(this.xf=g("\x3cdiv class\x3d'oj-messaging-inline-container'\x3e\x3c/div\x3e"),this.sH(this.xf),this.pna(this.xf),b.append(this.xf));null!=this.xf&&(a?(b=this.xf[0],b.innerHTML=a):this.Daa())};a.$g.prototype.Daa=function(){null!=
this.xf&&(this.nV(this.xf),this.gAa(this.xf),this.xf.remove(),delete this.xf)};a.$g.prototype.sH=function(b){var c,d;d=this.hl();a.o.ue(d,jQuery);a.o.ue(b,jQuery);b=b.uniqueId().attr("id");c=(c=d.attr("aria-describedby"))?c.split(/\s+/):[];c.push(b);c=g.trim(c.join(" "));d.attr("aria-describedby",c)};a.$g.prototype.pna=function(b){a.o.ue(b,jQuery);b.attr("aria-live","polite")};a.$g.prototype.nV=function(b){var c,d;d=this.hl();a.o.ue(d,jQuery);a.o.ue(b,jQuery);b=b.attr("id");c=(c=d.attr("aria-describedby"))?
c.split(/\s+/):[];b=g.inArray(b,c);-1!==b&&c.splice(b,1);(c=g.trim(c.join(" ")))?d.attr("aria-describedby",c):d.removeAttr("aria-describedby")};a.$g.prototype.gAa=function(b){a.o.ue(b,jQuery);b.removeAttr("aria-live")};a.$g.prototype.Doa=function(){var a;return this.k0()?(a=this.ym().document[0],this.AQ(a)):""};a.$g.prototype.AQ=function(b){var c="",d=this.cO();this.lO()&&(c=this.dO(),c=a.rb.uda(b,c,d,!0));return c};a.Components.Ta("editableValue","baseComponent",{properties:{disabled:{type:"boolean"},
displayOptions:{type:"Object"},help:{type:"Object\x3cstring, string\x3e"},messagesCustom:{type:"Array"},messagesHidden:{type:"Array"},messagesShown:{type:"Array"},required:{type:"boolean"},title:{type:"string"},validators:{type:"Array"},value:{type:"Object",writeback:!0}},methods:{getNodeBySubId:{},isValid:{},refresh:{},reset:{},showMessages:{},validate:{}},extension:{_widgetName:"editableValue"}})});