/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise"],function(a,g){a.zf=function(){this.Init()};a.b.ta(a.zf,a.mj,"oj.FilmStripPagingModel");a.zf.prototype.Init=function(){a.zf.t.Init.call(this);this.ge=-1;this.Gf=0;this.Db=-1};a.b.g("FilmStripPagingModel.prototype.Init",{Init:a.zf.prototype.Init});a.zf.prototype.kJa=function(a){this.Gf=a};a.zf.prototype.getPage=function(){return this.ge};a.b.g("FilmStripPagingModel.prototype.getPage",{getPage:a.zf.prototype.getPage});a.zf.prototype.setPage=
function(a,b){a=parseInt(a,10);try{var d=this.getPageCount(),e=this.ge,f=this.Db,g=f;b&&b.pageSize&&(g=b.pageSize);if(0===this.Gf&&-1===g)return Promise.resolve();var k=Math.ceil(this.Gf/g);if(0>a||a>k-1)throw Error("JET FilmStrip: Invalid 'page' set: "+a);var l=!1;if(a!=e||g!=f){if(!1===this.handleEvent("beforePage",{page:a,previousPage:e}))return Promise.reject();l=!0}this.ge=a;this.Db=g;var m=this.getPageCount(),s=this;return new Promise(function(b){d!=m&&s.handleEvent("pageCount",{pageCount:m,
previousPageCount:d});l&&s.handleEvent("page",{page:a,previousPage:e});b(null)})}catch(t){return Promise.reject(t)}};a.b.g("FilmStripPagingModel.prototype.setPage",{setPage:a.zf.prototype.setPage});a.zf.prototype.getStartItemIndex=function(){return-1===this.ge&&-1===this.Db?-1:this.ge*this.Db};a.b.g("FilmStripPagingModel.prototype.getStartItemIndex",{getStartItemIndex:a.zf.prototype.getStartItemIndex});a.zf.prototype.getEndItemIndex=function(){return Math.min(this.getStartItemIndex()+this.Db,this.Gf)-
1};a.b.g("FilmStripPagingModel.prototype.getEndItemIndex",{getEndItemIndex:a.zf.prototype.getEndItemIndex});a.zf.prototype.getPageCount=function(){return Math.ceil(this.Gf/this.Db)};a.b.g("FilmStripPagingModel.prototype.getPageCount",{getPageCount:a.zf.prototype.getPageCount});a.zf.prototype.totalSize=function(){return this.Gf};a.b.g("FilmStripPagingModel.prototype.totalSize",{totalSize:a.zf.prototype.totalSize});a.zf.prototype.totalSizeConfidence=function(){return"actual"};a.b.g("FilmStripPagingModel.prototype.totalSizeConfidence",
{totalSizeConfidence:a.zf.prototype.totalSizeConfidence});(function(){function c(a){var b=g("\x3cdiv\x3e\x3c/div\x3e");b.text(a);return b[0].innerHTML}function b(a){a.css("-webkit-transform",t).css("-ms-transform",t).css("transform",t)}function d(a,b){a.css("-webkit-transform",b).css("-ms-transform",b).css("transform",b)}a.Na("oj.ojFilmStrip",g.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{maxItemsPerPage:0,orientation:"horizontal",currentItem:0,arrowPlacement:"adjacent",
arrowVisibility:"auto"},_ComponentCreate:function(){this._super();var b=this.element;b.addClass("oj-filmstrip oj-component").attr("tabindex",0).attr("role","region");b.uniqueId();b=this.options;b.disabled&&a.r.warn(ba);if(b.orientation!==y&&b.orientation!==ea)throw Error(n+b.orientation);if(b.arrowPlacement!==e&&b.arrowPlacement!==U)throw Error(p+b.arrowPlacement);if(b.arrowVisibility!==ga&&b.arrowVisibility!==v&&b.arrowVisibility!==x&&b.arrowVisibility!==h)throw Error(q+b.arrowVisibility);this.YF=
this.eventNamespace+"Touch";this.fN=this.eventNamespace+"Mouse";this.rga=this.eventNamespace+"Key";this.ZY=this.eventNamespace+"NavArrowHoverable";this.$a(!0)},refresh:function(){this._super();this.$a(!1)},getItemsPerPage:function(){return this.Dv},getPagingModel:function(){return this.Ef},Sp:function(){this._super();this.Ge&&this.$a(this.Ge[0])},Or:function(){this._super();this.Ge&&this.$a(this.Ge[0])},$a:function(b){b&&!this.Ef&&(this.Ef=new a.zf);if(this.cC()){this.Ge=null;this.Ph="rtl"===this.hd();
this.bs=a.u.af();var c=this.element,d=this;b?(this.Dv=0,this.KT=function(a){d.JT(a)},this.ks=0,this.oD=-1,this.Do=function(){d.tv()},this.Hj=function(){d.Hg()},this.bs&&(this.v8=function(a){d.VT(a)},this.u8=function(a){d.UT(a)},this.ST=function(a){d.RT(a)},this.Pna()),this.j8=function(a){d.Jva(a)},this.k8=function(a){d.Kva(a)},this.m8=function(a){d.Mva(a)},this.Jna(),this.i8=function(a){d.pv(a)},this.Hna()):this.j5();for(var e=c.children(),f=0;f<e.length;f++)a.Components.ti(e[f]);f=this.Ef;if(b)f.on("page",
this.KT);f.kJa(e.length);this.MDa();if(0<e.length){this.f3();for(f=0;f<e.length;f++)a.Components.Tg(e[f]);a.u.Mk(c[0],this.Hj)}}else c=!1,this.Ge&&(c=this.Ge[0]),this.Ge=[b||c]},_destroy:function(){this.bs&&(this.HAa(),this.ST=this.u8=this.v8=null);this.xAa();this.m8=this.k8=this.j8=null;this.vAa();this.i8=null;this.j5();this.Ef.off("page",this.KT);this.Do=this.Hj=this.Ef=this.KT=null;var a=this.element;a.removeClass("oj-filmstrip oj-component "+J).removeAttr("tabindex role");a.removeUniqueId();this._super()},
j5:function(){a.u.lm(this.element[0],this.Hj);this.oD=-1;this.OD&&(clearTimeout(this.OD),this.OD=null);for(var b=this.TI(),c=0;c<b.length;c++)a.Components.ti(b[c]);this.g4();this.GS().unwrap();this.oDa();for(c=0;c<b.length;c++)a.Components.Tg(b[c])},_setOption:function(b,c,d){var f=this.options,g=!1,k=-1,l=this.Ef,m=l.getPage();switch(b){case "disabled":a.r.warn(ba);break;case "orientation":if(c!==y&&c!==ea)throw Error(n+c);g=f.orientation!=c;break;case "maxItemsPerPage":g=f.maxItemsPerPage!=c;break;
case "arrowPlacement":if(c!==e&&c!==U)throw Error(p+c);g=f.arrowPlacement!=c;break;case "arrowVisibility":if(c!==ga&&c!==v&&c!==x&&c!==h)throw Error(q+c);g=f.arrowVisibility!=c;break;case z:if(f.currentItem!=c&&(k=this.cS(c),0>k||k>=l.getPageCount()))throw Error(r+c);}this._super(b,c,d);switch(b){case z:-1<k&&k!=m&&l.setPage(k)}g&&this.$a(!1)},Hg:function(){if(!this.t3)this.t3=!0,this.f3(!0),this.t3=!1;else if(!this.OD){var a=this;this.OD=setTimeout(function(){a.OD=null;a.Hg()},0)}},vd:function(){return this.options.orientation!==
ea},JC:function(){return this.vd()?this.Ph?"right":"left":"top"},fv:function(){return this.vd()?"width":"height"},cC:function(){var a=document.createElement("div"),b=a.style;b.position="absolute";b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},MDa:function(){var a=this.element,b=this.vd(),c=a.children();c.addClass(F).wrap("\x3cdiv class\x3d'"+A+" "+E+"'\x3e\x3c/div\x3e");var d=this.JC();this.gn=
d=a.children().wrapAll("\x3cdiv class\x3d'"+A+" "+L+"' style\x3d'"+d+": 0px;'\x3e\x3c/div\x3e").parent();var f=this.options;f.arrowVisibility!==v&&f.arrowPlacement===e&&(this.kR=d.wrap("\x3cdiv class\x3d'"+A+" oj-filmstrip-content-container'\x3e\x3c/div\x3e").parent());a.addClass(A);b||a.addClass(fa);f.arrowVisibility!==v&&0<c.length&&(this.Hk=this.vqa(),this.Mj=this.hqa(),this.OU()&&this.oCa())},oDa:function(){var a=this.element,b=this.TI();this.RCa();this.Hk&&(this.Lu(this.Hk),this.Hk=null);this.Mj&&
(this.Lu(this.Mj),this.Mj=null);var c=a.children(O+C);c&&c.remove();b.removeClass(F).unwrap().unwrap();this.gn=null;this.kR&&(b.unwrap(),this.kR=null);a.removeClass(A+" "+fa)},oCa:function(){this.element.on("mouseenter"+this.ZY,function(a){g(a.currentTarget).hasClass("oj-disabled")||g(a.currentTarget).addClass(J)}).on("mouseleave"+this.ZY,function(a){g(a.currentTarget).removeClass(J)})},RCa:function(){this.element.off(this.ZY)},OU:function(){var a=this.options,b=a.arrowVisibility;return b===x||b===
h&&a.arrowPlacement===U},qwa:function(){return 0<this.Ef.getPage()},pwa:function(){var a=this.Ef;return a.getPage()<a.getPageCount()-1},sza:function(){if(this.qwa()){var a=this.Ef;a.setPage(a.getPage()-1)}},Lya:function(){if(this.pwa()){var a=this.Ef;a.setPage(a.getPage()+1)}},r5:function(a,b){this.options.arrowPlacement===e?b.css("visibility",a?"":v):b.parent().css("display",a?"":D)},DDa:function(){if(this.options.arrowVisibility!==v){var a=this.Ef,b=a.getPage(),a=a.getPageCount();this.r5(0!==b,
this.Hk);this.r5(b!==a-1,this.Mj)}},vqa:function(){var a=this.element,b=this.vd()?ha:ca,d=this.J4(b);this.options.arrowPlacement===U?a.append(d):a.prepend(d);var a=c(this.F("labelAccArrowPreviousPage")),e=c(this.F("tipArrowPreviousPage")),b=this.I4(d,b,a,e),f=this;b.on("click",function(){f.sza()});return b},hqa:function(){var a=this.element,b=this.vd()?B:I,d=this.J4(b);a.append(d);var a=c(this.F("labelAccArrowNextPage")),e=c(this.F("tipArrowNextPage")),b=this.I4(d,b,a,e),f=this;b.on("click",function(){f.Lya()});
return b},J4:function(a){var b=g(document.createElement("div"));b.addClass(C+" "+a);this.options.arrowPlacement===U&&(b.addClass("oj-filmstrip-arrow-container-overlay"),this.OU()&&b.addClass(K));return b},I4:function(a,b,c,d){var f="\x3cdiv class\x3d'"+G+" oj-default oj-enabled "+b+"' role\x3d'button' tabindex\x3d'-1'";a.append(f+("\x3e\x3cspan class\x3d'oj-filmstrip-arrow-icon "+b+" oj-component-icon'\x3e\x3c/span\x3e\x3c/div\x3e"));b=this.element.attr("id");a=a.children(O+G).eq(0);a.uniqueId();
f=a.attr("id");c&&a.attr("aria-label",c);d&&a.attr("title",d);a.attr("aria-labelledby",f+" "+b);this.Qe(a);this.ok(a);this.options.arrowPlacement===e&&this.OU()&&a.addClass(K);return a},GS:function(){return this.gn.find(O+E)},TI:function(){return this.gn.find(O+F)},ws:function(){return this.gn.children(O+H)},g4:function(){var a=this.gn;this.ws().css(u,t).css(X,t);this.GS().css(u,t).css(X,t);a.css(this.fv(),t)},f3:function(b){this.g4();var c=this.options,d=this.vd(),h=c.maxItemsPerPage,l=1>h,m=this.element,
p=this.GS();if(0>this.oD){var q=this.U6(c.currentItem),q=g(p[q]),n=q.children(O+F);n.css(k,t);a.Components.yr(n[0]);this.oD=d?q.width():q.height()}q=d?m.width():m.height();c.arrowVisibility!==v&&c.arrowPlacement===e&&(m=m.children(O+C).eq(0),d=d?m.width():m.height(),q-=2*d);this.ks=q;l||(d=Math.max(Math.floor(q/this.oD),1),d<h&&(h=d));h=l?Math.max(Math.floor(q/this.oD),1):h;l=q/h;p.css(u,l+Z).css(X,l+Z);l=Math.ceil(p.length/h);n=this.ws();d=!1;m=this.Ef;if(m.getPageCount()!=l||this.Dv!=h||!n||1>n.length){d=
!0;if(b)for(var r=0;r<p.length;r++)a.Components.ti(p[r]);n&&0<n.length&&p.unwrap();for(r=0;r<p.length;r+=h)p.slice(r,r+h).wrapAll("\x3cdiv class\x3d'"+A+" "+H+"' style\x3d'"+k+": "+D+";' "+f+"\x3d'true'\x3e\x3c/div\x3e");if(b)for(r=0;r<p.length;r++)a.Components.Tg(p[r])}n=this.ws();n.css(u,q+Z).css(X,q+Z);b=this.kR;this.gn.css(this.fv(),q);b&&b.css(this.fv(),q);b=0;if(c.currentItem||0===c.currentItem)b=this.cS(c.currentItem,h);m.getPageCount()!=l||this.Dv!=h||m.getPage()!=b?m.setPage(b,{pageSize:h}):
d&&(c=m.getPage(),this.JT({previousPage:c,page:c}))},JT:function(a){var b=a.page,c=a.previousPage;a=this.gn;var d=this.ws(),e=this.Ef.Db,f=0>c||c==b||this.Dv!=e;this.Dv=e;e=null;f||(e=g(d[c]));var h=this.JC(),k=g(d[b]),l=k.is(w);l&&this.zW(k);var m=this.Vx;-1<c&&!f&&(m=!0,a.css(this.fv(),2*this.ks),b<c&&l&&a.css(h,-this.ks+Z),b>c?(e.addClass(Q),k.addClass(M)):(e.addClass(R),k.addClass(N)));if(m){var p=this,q=this.Vx;q&&0>c&&d.filter(W).addClass(P);setTimeout(function(){p.U5(b,c,f,q)},25)}else this.U5(b,
c,f)},U5:function(a,c,e,f){var h=this.gn;e||(this.u3=!0,h.on("transitionend"+this.eventNamespace+" webkitTransitionEnd"+this.eventNamespace,this.Do));e?this.tv():(e=this.ws(),f&&b(e),-1<c?(f=a>c,c=g(e[c]),a=g(e[a]),c.addClass(P),a.addClass(P),f?(c.removeClass(Q),a.removeClass(M),c.addClass(V),a.addClass(Y)):(c.removeClass(R),a.removeClass(N),c.addClass(S),a.addClass(T))):f&&(a=e.filter(W),d(a,"translate3d(0, 0, 0)")))},tv:function(){this.u3=!1;var c=this.gn,d=this.JC();c.off(this.eventNamespace).css(this.fv(),
this.ks).css(d,"0px");d=null;if(a.le.AL(c[0])||this.Mj&&a.le.AL(this.Mj[0])||this.Hk&&a.le.AL(this.Hk[0]))d=document.activeElement;for(var c=this.Ef.getPage(),e=this.ws(),f=0;f<e.length;f++)f!=c&&this.C8(g(e[f]));e.removeClass(P+" "+V+" "+Y+" "+S+" "+T);b(e);this.DDa();d&&g(d).is(w)&&(d=this.element,(e=a.le.Oea(e[c]))?a.le.OE(e):a.le.OE(d[0]));this.cS(this.options.currentItem)!=c&&(c=this.H6(c),-1!==c&&this.option(z,c,{_context:{Ed:!0}}))},U6:function(b){var c=-1,d=this.TI();if("number"===typeof b)0<=
b&&b<d.length&&(c=b);else if("string"===typeof b&&a.u.AM(b))for(var e=0;e<d.length;e++){var f=d[e].id;if(f&&0<f.length&&f===b){c=e;break}}return c},cS:function(a,b){var c=this.U6(a),d=-1;-1<c&&(void 0===b&&(b=this.Dv),d=Math.floor(c/b));return d},H6:function(a,b,c){var d=this.Ef;void 0===b&&(b=d.getPageCount());return 0<=a&&a<b&&(b=this.TI(),void 0===c&&(c=this.Dv),a*=c,a<b.length)?(c=b[a].id)&&0<c.length?c:a:-1},C8:function(b){a.Components.Wt(b[0]);b.css(k,D).attr(f,"true");b.find(O+F).css(k,D)},
zW:function(b){b.css(k,t).removeAttr(f);b.find(O+F).css(k,t);a.Components.yr(b[0])},Hna:function(){this.element.on("keydown"+this.rga,this.i8)},vAa:function(){this.element.off(this.rga)},Jna:function(){this.element.on("mousedown"+this.fN,this.j8).on("mousemove"+this.fN,this.k8).on("mouseup"+this.fN,this.m8)},xAa:function(){this.element.off(this.fN)},Pna:function(){this.element.on("touchstart"+this.YF,this.v8).on("touchmove"+this.YF,this.u8).on("touchend"+this.YF,this.ST).on("touchcancel"+this.YF,
this.ST)},HAa:function(){this.element.off(this.YF)},pv:function(a){var b=this.Ef,c=b.getPage(),d=-1;switch(a.keyCode){case g.ui.keyCode.RIGHT:d=this.Ph?c-1:c+1;break;case g.ui.keyCode.LEFT:d=this.Ph?c+1:c-1;break;case g.ui.keyCode.DOWN:d=c+1;break;case g.ui.keyCode.UP:d=c-1;break;case g.ui.keyCode.HOME:d=0;break;case g.ui.keyCode.END:d=b.getPageCount()-1;break;default:return}-1<d&&d<b.getPageCount()&&b.setPage(d);a.preventDefault()},Jva:function(a){this.C5(a.originalEvent)},Kva:function(a){this.B5(a,
a.originalEvent)},Mva:function(){this.A5()},VT:function(a){a=a.originalEvent.touches;1===a.length&&this.C5(a[0])},UT:function(a){this.B5(a,a.originalEvent.touches[0]);(this.xl||this.Rv)&&a.preventDefault()},RT:function(){this.A5()},C5:function(a){if(1<this.Ef.getPageCount()&&!this.u3){this.xl=!0;this.Vx=!1;var b=this.vd();this.XK=b?a.pageX:a.pageY;this.Ica=b?a.pageY:a.pageX}},Lwa:function(a){var b=this.vd();this.XK=b?a.pageX:a.pageY;this.Ica=b?a.pageY:a.pageX;a=this.JC();var b=this.gn,c=this.Ef,d=
this.ws(),e=1;0<c.getPage()&&(this.zW(g(d[c.getPage()-1])),b.css(a,-this.ks+Z),e++);c.getPage()<c.getPageCount()-1&&(this.zW(g(d[c.getPage()+1])),e++);1<e&&b.css(this.fv(),e*this.ks);this.lW=parseInt(b.css(a),10)},B5:function(a,b){if(this.xl){var c=this.vd(),e=(c?b.pageX:b.pageY)-this.XK;Math.abs((c?b.pageY:b.pageX)-this.Ica)>Math.abs(e)&&(this.Rv=this.xl=!1);if(this.Vx){var f=c&&this.Ph?0<e:0>e,h=this.Ef,k=h.getPage();if(f&&k<h.getPageCount()-1||!f&&0<k){var p=this.element[0],q=Math.min(m*(c?p.offsetWidth:
p.offsetHeight),s),n=this.JC(),r=this.gn,p=this.ws();Math.abs(e)>=q?(c=f?k+1:k-1,this.H6(c),k=f?k-1:k+1,-1<k&&k<h.getPageCount()&&this.C8(g(p[k])),f&&-1<k&&(p=parseInt(r.css(n),10),r.css(n,p+this.ks+Z)),r.css(this.fv(),2*this.ks),this.xl=!1,h.setPage(c)):(h=c&&this.Ph?-e:e,h=c?"translate3d("+h+"px, 0, 0)":"translate3d(0, "+h+"px, 0)",d(p.filter(W),h));this.Rv=!0}this.Rv&&(a.preventDefault(),a.stopPropagation())}else Math.abs(e)>l&&(this.Lwa(b),this.Vx=!0)}},A5:function(){if(this.xl&&this.Vx){var a=
this.Ef.getPage();this.JT({previousPage:a,page:a})}this.Rv=this.Vx=this.xl=!1},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-filmstrip-start-arrow"===a?this.widget().find(O+G+O+ha)[0]:"oj-filmstrip-end-arrow"===a?this.widget().find(O+G+O+B)[0]:"oj-filmstrip-top-arrow"===a?this.widget().find(O+G+O+ca)[0]:"oj-filmstrip-bottom-arrow"===a?this.widget().find(O+G+O+I)[0]:null},getSubIdByNode:function(a){for(var b=this.getNodeBySubId({subId:"oj-filmstrip-start-arrow"}),
c=this.getNodeBySubId({subId:"oj-filmstrip-end-arrow"}),d=this.getNodeBySubId({subId:"oj-filmstrip-top-arrow"}),e=this.getNodeBySubId({subId:"oj-filmstrip-bottom-arrow"}),f=this.element[0];a&&a!=f;){if(a===b)return{subId:"oj-filmstrip-start-arrow"};if(a===c)return{subId:"oj-filmstrip-end-arrow"};if(a===d)return{subId:"oj-filmstrip-top-arrow"};if(a===e)return{subId:"oj-filmstrip-bottom-arrow"};a=a.parentElement}return null}});var e="adjacent",f="aria-hidden",h="auto",k="display",l=3,m=.33,s=100,t=
"",r="JET FilmStrip: Value of 'currentItem' option not found: ",n="JET FilmStrip: Unsupported value set as 'orientation' option: ",p="Unsupported value set as 'arrowPlacement' option: ",q="Unsupported value set as 'arrowVisibility' option: ",u="flex-basis",v="hidden",w=":hidden",y="horizontal",x="hover",z="currentItem",D="none",I="oj-bottom",B="oj-end",G="oj-filmstrip-arrow",C="oj-filmstrip-arrow-container",K="oj-filmstrip-arrow-transition",A="oj-filmstrip-container",J="oj-filmstrip-hover",F="oj-filmstrip-item",
E="oj-filmstrip-item-container",H="oj-filmstrip-page",L="oj-filmstrip-pages-container",P="oj-filmstrip-transition",M="oj-filmstrip-transition-next-newpage-from",Q="oj-filmstrip-transition-next-oldpage-from",N="oj-filmstrip-transition-prev-newpage-from",R="oj-filmstrip-transition-prev-oldpage-from",Y="oj-filmstrip-transition-next-newpage-to",V="oj-filmstrip-transition-next-oldpage-to",T="oj-filmstrip-transition-prev-newpage-to",S="oj-filmstrip-transition-prev-oldpage-to",fa="oj-filmstrip-vertical",
ha="oj-start",ca="oj-top",U="overlay",O=".",Z="px",ea="vertical",ga="visible",W=":visible",X="-webkit-flex-basis",ba="JET FilmStrip: 'disabled' option not supported"})();a.Components.Ta("ojFilmStrip","baseComponent",{properties:{arrowPlacement:{type:"string"},arrowVisibility:{type:"string"},currentItem:{type:"string|number"},disabled:{type:"boolean"},maxItemsPerPage:{type:"number"},orientation:{type:"string"}},methods:{getItemsPerPage:{},getPagingModel:{},refresh:{}},extension:{_widgetName:"ojFilmStrip"}});
a.Components.register("oj-film-strip",a.Components.getMetadata("ojFilmStrip"))});