/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(a,g){a.Ob=function(c,b){b=b||{};if(!(c instanceof a.ua))throw Error(a.aa.od._ERR_DATA_INVALID_TYPE_SUMMARY+"\n"+a.aa.od._ERR_DATA_INVALID_TYPE_DETAIL);this.i=c;this.Ue=[];this.pa=0;this.Xh=[];this.$m=!0;null==this.i.VE("fetchSize")&&(this.i.Qk=function(){return-1});var d=this;this.i.tM=function(b,c,g){var k,l,m,s,t=[],r=[],n=[];for(c=0;c<g.getCount();c++){l=g.getData(c);s=g.getMetadata(c).key;m=b+c;d.Xh.splice(m,0,{});d.Xh[m].nodeSet=
g;d.Xh[m].startIndex=b;for(k=m+1;k<d.Xh.length;k++)d.Xh[k].startIndex+=1;t.push(d.Xo(m,l));r.push(s);n.push(m);d.ya.data.splice(m,0,l);d.ya.keys.splice(m,0,s);d.ya.indexes.splice(m,0,m)}d.QD();d.$m=!0;a.aa.t.handleEvent.call(d,a.aa.Q.ADD,{data:t,keys:r,indexes:n})};this.i.tN=function(b){var c,g,k,l=[],m=[],s=[];for(c=0;c<b.length;c++){k=b[c].index-c;l.push("");m.push("");s.push(k);d.Xh.splice(k,1);for(g=k+1;g<d.Xh.length;g++)d.Xh[g].startIndex-=1;d.ya.data.splice(k,1);d.ya.keys.splice(k,1);d.ya.indexes.splice(k,
1)}d.QD();d.$m=!0;a.aa.t.handleEvent.call(d,a.aa.Q.REMOVE,{data:l,keys:m,indexes:s})};this.Init();if(null!=b&&("enabled"==b.startFetch||null==b.startFetch)||null==b)this.lE=!0};o_("FlattenedTreeTableDataSource",a.Ob,a);a.b.ta(a.Ob,a.aa,"oj.FlattenedTreeTableDataSource");a.Ob.prototype.Init=function(){a.Ob.t.Init.call(this)};a.b.g("FlattenedTreeTableDataSource.prototype.Init",{Init:a.Ob.prototype.Init});a.Ob.prototype.getCapability=function(){return"full"};a.b.g("FlattenedTreeTableDataSource.prototype.getCapability",
{getCapability:a.Ob.prototype.getCapability});a.Ob.prototype.getWrappedDataSource=function(){return this.i};a.b.g("FlattenedTreeTableDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.Ob.prototype.getWrappedDataSource});a.Ob.prototype.fetch=function(a){a=a||{};return"init"!=a.fetchType||this.lE?this.Cg(a):Promise.resolve()};a.b.g("FlattenedTreeTableDataSource.prototype.fetch",{fetch:a.Ob.prototype.fetch});a.Ob.prototype.at=function(a){var b;b=0>a||a>=this.ya.length?null:{data:this.ya.data[a],
index:a,key:this.ya.keys[a]};return new Promise(function(a){a(b)})};a.b.g("FlattenedTreeTableDataSource.prototype.at",{at:a.Ob.prototype.at});a.Ob.prototype.collapse=function(a){this.i.collapse(a)};a.b.g("FlattenedTreeTableDataSource.prototype.collapse",{collapse:a.Ob.prototype.collapse});a.Ob.prototype.expand=function(a){this.i.expand(a)};a.b.g("FlattenedTreeTableDataSource.prototype.expand",{expand:a.Ob.prototype.expand});a.Ob.prototype.get=function(a){var b=this.i.Rk(Object(a));a={data:this.Xo(b,
this.ya.data[b]),key:a,index:b};return Promise.resolve(a)};a.b.g("FlattenedTreeTableDataSource.prototype.get",{get:a.Ob.prototype.get});a.Ob.prototype.on=function(c,b){if("expand"==c||"collapse"==c)this.i.on(c,b);else a.Ob.t.on.call(this,c,b)};a.b.g("FlattenedTreeTableDataSource.prototype.on",{on:a.Ob.prototype.on});a.Ob.prototype.off=function(c,b){"expand"==c||"collapse"==c?this.i.off(c,b):a.Ob.t.off.call(this,c,b)};a.b.g("FlattenedTreeTableDataSource.prototype.off",{off:a.Ob.prototype.off});a.Ob.prototype.sort=
function(c){null==c?c=this.sortCriteria:this.sortCriteria=c;var b=this;c.axis="column";return new Promise(function(d,e){b.i.getWrappedDataSource().sort(c,{success:function(){setTimeout(function(){b.i.refresh();b.ya=null;var e={header:c.key,direction:c.direction};a.aa.t.handleEvent.call(b,a.aa.Q.SORT,e);d(e)},0)}.bind(this),error:function(a){e(a)}.bind(this)})})};a.b.g("FlattenedTreeTableDataSource.prototype.sort",{sort:a.Ob.prototype.sort});a.Ob.prototype.totalSize=function(){return this.$m?-1:this.ya.data.length};
a.b.g("FlattenedTreeTableDataSource.prototype.totalSize",{totalSize:a.Ob.prototype.totalSize});a.Ob.prototype.totalSizeConfidence=function(){return this.$m?"unknown":"actual"};a.b.g("FlattenedTreeTableDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:a.Ob.prototype.totalSizeConfidence});a.Ob.prototype.OS=function(a){var b=this.Xh[a].nodeSet.getStart();return this.Xh[a].nodeSet.getMetadata(b+a-this.Xh[a].startIndex)};a.Ob.prototype.Cg=function(c){c=c||{};this.kE(c);this.pa=null==c.startIndex?
this.pa:c.startIndex;var b=Number.MAX_VALUE;this.Db=null==c.pageSize?this.Db:c.pageSize;null!=this.Db&&(b=this.Db);var d=this.pa;if(null!=this.ya)if(null!=this.Db){var e=this.ya.data.length-1;if(this.pa+this.Db-1<=e){var e=a.Ob.KI(this.ya,this.pa,this.Db),b=[],d=[],f;for(f=this.pa;f<=e;f++)b[f-this.pa]=this.Xo(f,this.ya.data[f]),d[f-this.pa]=this.ya.keys[f];e={data:b,keys:d,startIndex:this.pa};this.Tm(c,e,null);return Promise.resolve(e)}this.pa<=e&&(d=e+1)}else this.i.refresh(),this.ya=null;else d=
0;var g={start:d,count:b},k=this;return new Promise(function(b,d){k.i.gp(g,{success:function(d){k.FT(d);c.refresh=!0;d=a.Ob.KI(k.ya,k.pa,k.Db);var e=[],f=[],g;for(g=k.pa;g<=d;g++)e[g-k.pa]=k.Xo(g,k.ya.data[g]),f[g-k.pa]=k.ya.keys[g];k.$m=0<e.length?!0:!1;d={data:e,keys:f,startIndex:k.pa};k.Tm(c,d,null);b(d)}.bind(this),error:function(a){k.Tm(c,null,a);d(a)}.bind(this)})})};a.Ob.prototype.FT=function(c){var b=c.getStart(),d,e;for(d=0;d<c.getCount();d++)e=b+d,this.Xh[e]={},this.Xh[e].nodeSet=c,this.Xh[e].startIndex=
b;this.ya||(this.ya={},this.ya.data=[],this.ya.keys=[],this.ya.indexes=[]);a.Ob.zy(c,this,this.ya,b)};a.Ob.prototype.kE=function(c){c.silent||a.aa.t.handleEvent.call(this,a.aa.Q.REQUEST,{startIndex:c.startIndex})};a.Ob.prototype.Tm=function(c,b,d){null!=d?a.aa.t.handleEvent.call(this,a.aa.Q.ERROR,d):c.silent||a.aa.t.handleEvent.call(this,a.aa.Q.SYNC,b)};a.Ob.KI=function(a,b,d){var e=a.data.length-1;0<d&&(e=b+d-1,e=e>a.data.length-1?a.data.length-1:e);return e};a.Ob.zy=function(a,b,d,e){for(b=0;b<
a.getCount();b++){var f=a.getData(a.getStart()+b);d.data[e+b]=f;d.keys[e+b]=a.getMetadata(a.getStart()+b).key;d.indexes[e+b]=e+b}};a.Ob.prototype.QD=function(){for(var a=0;a<this.ya.data.length;a++)this.ya.indexes[a]=a};a.Ob.prototype.Xo=function(a,b){var d=g.extend(!0,{},b),e=this,f;for(f in d)d.hasOwnProperty(f)&&function(){var b=f;Object.defineProperty(d,f,{get:function(){return e.ya.data[a][b]},set:function(d){e.ya.data[a][b]=d}})}();return d}});