/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common","ojs/ojrowexpander"],function(a){a.Ah=function(g,c,b,d,e){a.o.HE(b);this.cd=g;this.ng=c;this.PM=b;this.pc=d;this.oa=e};o_("FlattenedTreeHeaderSet",a.Ah,a);a.Ah.prototype.getData=function(g,c){var b;a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return null!=this.oa&&null!=this.pc?(b=this.pc.getData(g-this.cd+this.pc.getStart()),null!=b?b.get?b.get(this.oa):b[this.oa]:null):this.PM[g]};
a.b.g("FlattenedTreeHeaderSet.prototype.getData",{getData:a.Ah.prototype.getData});a.Ah.prototype.getMetadata=function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return null!=this.oa&&null!=this.pc?this.pc.getMetadata(g-this.cd+this.pc.getStart()):{key:this.getData(g)}};a.b.g("FlattenedTreeHeaderSet.prototype.getMetadata",{getMetadata:a.Ah.prototype.getMetadata});a.Ah.prototype.getCount=function(){return null!=this.oa&&null!=this.pc?
Math.min(this.pc.getCount(),this.ng-this.cd):Math.max(0,this.ng-this.cd)};a.b.g("FlattenedTreeHeaderSet.prototype.getCount",{getCount:a.Ah.prototype.getCount});a.Ah.prototype.getLevelCount=function(){return 0<this.getCount()?1:0};a.b.g("FlattenedTreeHeaderSet.prototype.getLevelCount",{getLevelCount:a.Ah.prototype.getLevelCount});a.Ah.prototype.getExtent=function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return{extent:1,more:{before:!1,
after:!1}}};a.b.g("FlattenedTreeHeaderSet.prototype.getExtent",{getExtent:a.Ah.prototype.getExtent});a.Ah.prototype.getDepth=function(g,c){a.o.assert(g<=this.ng&&g>=this.cd,"index out of bounds");a.o.assert(null==c||0==c,"level out of bounds");return 1};a.b.g("FlattenedTreeHeaderSet.prototype.getDepth",{getDepth:a.Ah.prototype.getDepth});a.fl=function(g,c,b,d,e,f){a.o.HE(f);this.Ba=g;this.jb=c;this.yp=b;this.zw=d;this.pc=e;this.Nf=f};o_("FlattenedTreeCellSet",a.fl,a);a.fl.prototype.getData=function(g){var c,
b,d,e;c=this.r7(g);if(null==c)return null;g=c[0];c=c[1];a.o.assert(g<this.pc.getStart()+this.pc.getCount()&&c<this.Nf.length);b=this.Nf[c];d=this.pc.getData(g);return null!=d?(g={},c=d.get?function(){return d.get(b)}:function(){return d[b]},e=d.set?function(a){return d.set(b,a)}:function(a){d[b]=a},Object.defineProperty(g,"data",{get:c,set:e}),g):null};a.b.g("FlattenedTreeCellSet.prototype.getData",{getData:a.fl.prototype.getData});a.fl.prototype.getMetadata=function(g){var c;c=this.r7(g);if(null==
c)return null;g=c[0];c=c[1];a.o.assert(g<this.pc.getStart()+this.pc.getCount()&&c<this.Nf.length);c=this.Nf[c];g=this.pc.getMetadata(g);g.keys={row:g.key,column:c};return g};a.b.g("FlattenedTreeCellSet.prototype.getMetadata",{getMetadata:a.fl.prototype.getMetadata});a.fl.prototype.r7=function(g){var c;a.o.di(g);if(null==this.pc||0==this.pc.length)return null;c=g.row-this.Ba+this.pc.getStart();g=g.column;a.o.Fq(c,null);a.o.Fq(g,null);a.o.assert(0<=c&&0<=g);return[c,g]};a.fl.prototype.getStart=function(a){return"row"===
a?this.Ba:"column"===a?this.yp:0};a.b.g("FlattenedTreeCellSet.prototype.getStart",{getStart:a.fl.prototype.getStart});a.fl.prototype.getCount=function(a){return"row"===a?Math.min(this.jb-this.Ba,this.pc.getCount()):"column"===a?this.zw-this.yp:0};a.b.g("FlattenedTreeCellSet.prototype.getCount",{getCount:a.fl.prototype.getCount});a.xb=function(g,c){a.xb.t.constructor.call(this,g,c)};o_("FlattenedTreeDataGridDataSource",a.xb,a);a.b.ta(a.xb,a.ua,"oj.FlattenedTreeDataGridDataSource");a.xb.prototype.Init=
function(){a.xb.t.Init.call(this);this.Nf=a.xb.t.VE.call(this,"columns");this.oa=a.xb.t.VE.call(this,"rowHeader")};a.b.g("FlattenedTreeDataGridDataSource.prototype.Init",{Init:a.xb.prototype.Init});a.xb.prototype.getCountPrecision=function(a){return"row"===a?"estimate":"actual"};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCountPrecision",{getCountPrecision:a.xb.prototype.getCountPrecision});a.xb.prototype.getCount=function(a){return"row"===a?-1:"column"===a?this.Nf.length:0};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCount",
{getCount:a.xb.prototype.getCount});a.xb.prototype.fetchHeaders=function(g,c,b){var d,e;d=g.axis;if("column"===d)d=g.start+g.count,d>this.getCount("column")&&(d=this.getCount("column")-g.start),e=new a.Ah(g.start,d,this.Nf);else if("row"===d&&null!=this.oa){this.tp={range:g,callbacks:c,callbackObjects:b};return}null!=c&&null!=c.success&&(null==b&&(b={}),c.success.call(b.success,e,g,null))};a.b.g("FlattenedTreeDataGridDataSource.prototype.fetchHeaders",{fetchHeaders:a.xb.prototype.fetchHeaders});a.xb.prototype.fetchCells=
function(g,c,b){var d,e,f,h;for(d=0;d<g.length;d++)if(e=g[d],"row"==e.axis){f=e.start;h=e.count;break}a.xb.t.gp.call(this,{start:f,count:h},{success:function(a){this.FT(a,g,c,b,0)}.bind(this),error:function(a){this.Wua(a,{start:f,count:h},c,b)}.bind(this)})};a.b.g("FlattenedTreeDataGridDataSource.prototype.fetchCells",{fetchCells:a.xb.prototype.fetchCells});a.xb.prototype.keys=function(g){var c,b;c=g.row;b=g.column;return new Promise(function(d){c>a.xb.t.RFa.call(this).end||b>this.Nf.length?d(null):
d({row:a.xb.t.getKey.call(this,c),column:this.Nf[b]})}.bind(this))};a.b.g("FlattenedTreeDataGridDataSource.prototype.keys",{keys:a.xb.prototype.keys});a.xb.prototype.indexes=function(g){var c,b,d,e,f;d=g.row;e=g.column;return new Promise(function(g){c=a.xb.t.Rk.call(this,d);for(f=0;f<this.Nf.length;f++)if(this.Nf[f]===e){b=f;break}0<=c||0<=b?g({row:c,column:b}):g(null)}.bind(this))};a.b.g("FlattenedTreeDataGridDataSource.prototype.indexes",{indexes:a.xb.prototype.indexes});a.xb.prototype.sort=function(g,
c,b){return a.xb.t.getWrappedDataSource.call(this).sort(g,{success:function(){this.QT(c,b)}.bind(this),error:c.error})};a.b.g("FlattenedTreeDataGridDataSource.prototype.sort",{sort:a.xb.prototype.sort});a.xb.prototype.QT=function(a,c){this.refresh();a.success&&(null==c&&(c={}),a.success.call(c.success))};a.xb.prototype.move=function(g,c,b,d){a.xb.t.getWrappedDataSource.call(this).move(g,c,b,d)};a.b.g("FlattenedTreeDataGridDataSource.prototype.move",{move:a.xb.prototype.move});a.xb.prototype.getCapability=
function(g){return"default"===a.xb.t.getWrappedDataSource.call(this).getCapability(g)?"column":"none"};a.b.g("FlattenedTreeDataGridDataSource.prototype.getCapability",{getCapability:a.xb.prototype.getCapability});a.xb.prototype.cF=function(g,c){a.xb.t.cF.call(this,g,c)};a.xb.prototype.FT=function(g,c,b,d){var e,f,h,k,l,m;for(e=0;e<c.length;e++)f=c[e],"row"==f.axis?(h=f.start,k=f.count):"column"==f.axis&&(l=f.start,m=f.count,l+m>this.getCount("column")&&(m=this.getCount("column")-l));this.tp&&(e=this.tp.range,
e.start==h&&e.count==k&&this.LT(g,e,this.tp.callbacks,this.tp.callbackObjects),this.tp=null);g=new a.fl(h,h+k,l,l+m,g,this.Nf);b.success&&(null==d&&(d={}),b.success.call(d.success,g,c))};a.xb.prototype.Wua=function(a,c,b,d){var e;this.tp&&(e=this.tp.range,e.start==c.start&&e.count==c.count&&(c=this.tp.callbacks,e=this.tp.callbackObjects,c.error&&(null==e&&(e={}),c.error.call(e.error,a))),this.tp=null);b.error&&(null==d&&(d={}),b.success.call(d.error,a))};a.xb.prototype.LT=function(g,c,b,d){g=new a.Ah(c.start,
c.start+c.count,this.Nf,g,this.oa);b.success&&(null==d&&(d={}),b.success.call(d.success,g,c,null))};a.xb.prototype.tM=function(g,c,b){var d,e,f,h;d=null;this.oa&&(d=new a.Ah(g,g+b.getCount(),this.Nf,b,this.oa));c=new a.fl(g,g+b.getCount(),0,this.Nf.length,b,this.Nf);f=[];h=[];for(e=0;e<b.getCount();e++)f.push({row:this.Dj(g+e).key}),h.push({row:g+e,column:-1});g={source:this,operation:"insert"};g.result=c;d&&(g.header=d);g.keys=f;g.indexes=h;a.xb.t.handleEvent.call(this,"change",g)};a.xb.prototype.tN=
function(g){var c,b,d;c=[];d=[];for(b=0;b<g.length;b++)c.push({row:g[b].key}),d.push({row:g[b].index,column:-1});g={source:this,operation:"delete"};g.keys=c;g.indexes=d;a.xb.t.handleEvent.call(this,"change",g)};a.xb.prototype.gY=function(g,c){c.success.call(null,new a.Wg(null,g.start))}});