/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojtime-base","ojs/internal-deps/dvt/DvtGantt"],function(a,g,c,b,d){a.Na("oj.ojGantt",g.oj.dvtTimeComponent,{widgetEventPrefix:"oj",options:{viewportChange:null},zg:function(a,b,c){a.styleClasses={databody:"oj-gantt-container",nodata:"oj-gantt-no-data-message",hgridline:"oj-gantt-horizontal-gridline",vgridline:"oj-gantt-vertical-gridline",majorAxis:"oj-gantt-major-axis",majorAxisTicks:"oj-gantt-major-axis-separator",majorAxisLabels:"oj-gantt-major-axis-label",
minorAxis:"oj-gantt-minor-axis",minorAxisTicks:"oj-gantt-minor-axis-separator",minorAxisLabels:"oj-gantt-minor-axis-label",row:"oj-gantt-row",task:"oj-gantt-task",taskLabel:"oj-gantt-task-label",selected:"oj-selected",hover:"oj-hover"};return d.Gantt.newInstance(a,b,c)},Cf:function(){var a=this._super();a.push("oj-gantt");return a},yKa:function(){return{databody:"oj-gantt-container",nodata:"oj-gantt-no-data-message",hgridline:"oj-gantt-horizontal-gridline",vgridline:"oj-gantt-vertical-gridline",majorAxis:"oj-gantt-major-axis",
majorAxisTicks:"oj-gantt-major-axis-separator",majorAxisLabels:"oj-gantt-major-axis-label",minorAxis:"oj-gantt-minor-axis",minorAxisTicks:"oj-gantt-minor-axis-separator",minorAxisLabels:"oj-gantt-minor-axis-label",row:"oj-gantt-row",task:"oj-gantt-task",taskLabel:"oj-gantt-task-label",selected:"oj-selected",hover:"oj-hover"}},pk:function(a){var b=a.subId;"oj-gantt-taskbar"==b&&(b="taskbar["+a.rowIndex+"]["+a.index+"]");return b},Ih:function(a){var b={};0==a.indexOf("taskbar")&&(a=this.Zn(a),b.subId=
"oj-gantt-taskbar",b.rowIndex=a[0],b.index=a[1]);return b},qk:function(){var a=this._super();a["oj-gantt"]={path:"_resources/animationDuration",property:"animation-duration"};a["oj-gantt-zoomin-icon"]={path:"_resources/zoomIn",property:"CSS_URL"};a["oj-gantt-zoomin-icon oj-hover"]={path:"_resources/zoomIn_h",property:"CSS_URL"};a["oj-gantt-zoomin-icon oj-active"]={path:"_resources/zoomIn_a",property:"CSS_URL"};a["oj-gantt-zoomin-icon oj-disabled"]={path:"_resources/zoomIn_d",property:"CSS_URL"};a["oj-gantt-zoomout-icon"]=
{path:"_resources/zoomOut",property:"CSS_URL"};a["oj-gantt-zoomout-icon oj-hover"]={path:"_resources/zoomOut_h",property:"CSS_URL"};a["oj-gantt-zoomout-icon oj-active"]={path:"_resources/zoomOut_a",property:"CSS_URL"};a["oj-gantt-zoomout-icon oj-disabled"]={path:"_resources/zoomOut_d",property:"CSS_URL"};a["oj-gantt-container"]={path:"_resources/chartArea/strokeWidth",property:"stroke-width"};a["oj-gantt-horizontal-gridline"]={path:"_resources/horizontalGridlineWidth",property:"stroke-width"};a["oj-gantt-task-label"]=
{path:"_resources/taskLabelFontProp",property:"CSS_TEXT_PROPERTIES"};return a},rj:function(){return["optionChange","viewportChange"]},Ji:function(){var a=this.options.translations,b=this._super();b["DvtUtilBundle.GANTT"]=a.componentName;b["DvtUtilBundle.ZOOM_IN"]=a.tooltipZoomIn;b["DvtUtilBundle.ZOOM_OUT"]=a.tooltipZoomOut;return b},ql:function(a){if("viewportChange"===a.type){var b=(new Date(a.viewportStart)).toISOString(),c=(new Date(a.viewportEnd)).toISOString(),d=a.majorAxisScale;a=a.minorAxisScale;
var g={viewportStart:b,viewportEnd:c,majorAxisScale:d,minorAxisScale:a};this.ce("viewportStart",b);this.ce("viewportEnd",c);this.ce("majorAxis.scale",d);this.ce("minorAxis.scale",a);this._trigger("viewportChange",null,g)}else this._super(a)},rk:function(){return{root:["rows"]}},whenReady:function(){return this._super()}});a.Components.Ta("ojGantt","dvtTimeComponent",{properties:{animationOnDataChange:{type:"string"},animationOnDisplay:{type:"string"},axisPosition:{type:"string"},end:{type:"string|number"},
gridlines:{type:"object"},majorAxis:{type:"object"},minorAxis:{type:"object"},rows:{type:"Array\x3cobject\x3e"},selection:{type:"Array\x3cstring\x3e"},selectionMode:{type:"string"},start:{type:"string|number"},taskDefaults:{type:"object"},viewportEnd:{type:"string|number"},viewportStart:{type:"string|number"}},methods:{whenReady:{}},extension:{_widgetName:"ojGantt"}});a.Components.register("oj-gantt",a.Components.getMetadata("ojGantt"))});