/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojbutton"],function(a,g){(function(){a.Na("oj.ojInputNumber",g.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{converter:a.Ea.qn(a.Rn.CONVERTER_TYPE_NUMBER).createConverter(),max:null,min:null,placeholder:void 0,rawValue:void 0,readOnly:!1,step:1,value:null},getNodeBySubId:function(a){var c=this._superApply(arguments),e;c||(e=a.subId,"oj-inputnumber-up"===e&&(c=this.widget().find(".oj-inputnumber-up")[0]),
"oj-inputnumber-down"===e&&(c=this.widget().find(".oj-inputnumber-down")[0]),"oj-inputnumber-input"===e&&(c=this.widget().find(".oj-inputnumber-input")[0]));return c||null},getSubIdByNode:function(a){var c=null;null!=a&&(a===this.widget().find(".oj-inputnumber-up")[0]?c={subId:"oj-inputnumber-up"}:a===this.widget().find(".oj-inputnumber-down")[0]?c={subId:"oj-inputnumber-down"}:a===this.widget().find(".oj-inputnumber-input")[0]&&(c={subId:"oj-inputnumber-input"}));return c||this._superApply(arguments)},
refresh:function(){this._super();this.$a()},stepDown:function(a){this.lca(a,!1)},stepUp:function(a){this.lca(a,!0)},widget:function(){return this.om},Xf:function(b,c){var e=this.options,f=this;this._superApply(arguments);a.Me.np([{ga:"disabled",Od:!0},{ga:"placeholder"},{ga:"value"},{ga:"readonly",option:"readOnly",Od:!0},{ga:"required",oh:!0,Od:!0},{ga:"title"},{ga:"min"},{ga:"max"},{ga:"step"}],c,this,function(a){for(var b=["value","step","min","max"],c=0;c<b.length;c++){var d=b[c],g=d in a?a[d]:
e[d];null!=g&&(a[d]="step"===d?f.DD(g):f.No(d,g))}});if(void 0===e.value)throw Error("ojInputNumber has no value");if(null!=e.min&&null!=e.max&&e.max<e.min)throw Error("ojInputNumber's max must not be less than min");},_ComponentCreate:function(){this._super();this.uC();this.d9={};this.$a();this._on(this.hq);this._focusable(this.om)},x0:function(a,c,e){this._superApply(arguments);switch(a){case "min":case "max":this.vj(a,this.options[a])}},_setOption:function(a,c,e){var f;f="value"===a||"max"===a||
"min"===a?this.No(a,c):"step"===a?this.DD(c):c;this._super(a,f,e);if("max"===a||"min"===a)this.Q4(),this.rx();"disabled"===a&&this.element.prop("disabled",!!c);"readOnly"===a&&(this.element.prop("readonly",!!c),this.lK("readOnly",this.options.readOnly),this.iaa("readOnly",this.options.readOnly))},_destroy:function(){var b=this._super();this.bX.ojButtonset("destroy");this.bX.remove();this.bX=this.qX=this.OZ=null;a.u.unwrap(this.element,this.om);clearTimeout(this.Le);return b},vj:function(a,c,e){this._superApply(arguments);
var f="value"===a||"max"===a||"min"===a,g=f||"disabled"===a,k;g&&(k=this.FI());f&&this.kK(k);"converter"===a&&this.caa(k);g&&this.dL(k)},Yc:function(){return this.options.converter?this._superApply(arguments):g.oj.ojInputNumber.prototype.options.converter},xB:function(){var a=this._superApply(arguments);null==this.options.min&&null==this.options.max||this.Q4();return g.extend(this.d9,a)},_GetDefaultStyleClass:function(){return"oj-inputnumber"},hq:{input:function(a){this.Vp(this.element.val(),a)},
keydown:function(a){a.keyCode===g.ui.keyCode.ENTER?(this.y3(a),a.preventDefault()):this.Pj()&&this.Ev(a)&&a.preventDefault()},keyup:function(a){this.Wv(a)},blur:function(a){this.y3(a)},"touchstart .oj-inputnumber-button":function(a){this.Pj();this.iz(null,g(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a)},"touchend .oj-inputnumber-button":function(a){c=Date.now();this.Wv(a)},"touchcancel .oj-inputnumber-button":function(a){c=Date.now();this.Wv(a)},"mousedown .oj-inputnumber-button":function(a){this.Cv(a)&&
(this.Pj(),this.iz(null,g(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseup .oj-inputnumber-button":function(a){this.Cv(a)&&this.Wv(a)},"mouseenter .oj-inputnumber-button":function(a){g(a.currentTarget).hasClass("oj-active")&&this.Cv(a)&&(this.Pj(),this.iz(null,g(a.currentTarget).hasClass("oj-inputnumber-up")?1:-1,a))},"mouseleave .oj-inputnumber-button":function(a){this.Cv(a)&&this.Wv(a)}},Ja:{$ma:"tooltipDecrement",ana:"tooltipIncrement"},Tr:{readOnly:"oj-read-only"},$a:function(){var a=
this.F(this.Ja.ana),c=this.F(this.Ja.$ma),e=this.FI();this.OZ.ojButton({label:a});this.qX.ojButton({label:c});this.kK(e);this.dL(e);"boolean"===typeof this.options.readOnly&&this.element.prop("readonly",this.options.readOnly);this.lK("readOnly",this.options.readOnly);this.iaa("readOnly",this.options.readOnly)},iqa:function(){var a=this.om.find(".oj-inputnumber-up"),c=this.om.find(".oj-inputnumber-down"),e=a[0].parentNode;this.OZ=a.ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-up-icon"}});
this.qX=c.ojButton({display:"icons",icons:{start:"oj-component-icon oj-inputnumber-down-icon"}});this.bX=g(e).ojButtonset({focusManagement:"none"})},uC:function(){var a=this.element;this.om=a.addClass("oj-inputnumber-input").wrap("\x3cspan class\x3d'oj-inputnumber-wrapper'\x3e\x3c/span\x3e").parent().append("\x3cdiv class\x3d'oj-buttonset-width-auto'\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/button\x3e\x3c/div\x3e");
this.oe?(this.om=g(this.oe).append(this.om),this.om.addClass("oj-inputnumber oj-component")):this.om=this.om.wrap("\x3cdiv class\x3d'oj-inputnumber oj-component'\x3e\x3c/div\x3e").parent();this.saveType=a.prop("type");a.attr("type","text");this.om.find(".oj-inputnumber-button").attr("tabIndex","-1");this.iqa()},Ev:function(a){var c=g.ui.keyCode;switch(a.keyCode){case c.UP:return this.iz(null,1,a),!0;case c.DOWN:return this.iz(null,-1,a),!0}return!1},cLa:function(){return"\x3cspan class\x3d'oj-inputnumber-wrapper'\x3e\x3c/span\x3e"},
sKa:function(){return"\x3cdiv class\x3d'oj-buttonset-width-auto'\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-down'\x3e\x3c/button\x3e\x3cbutton type\x3d'button' class\x3d'oj-inputnumber-button oj-inputnumber-up'\x3e\x3c/button\x3e\x3c/div\x3e"},Pj:function(){return this.qia=!0},iz:function(a,c,e){a=a||500;clearTimeout(this.Le);this.Le=this._delay(function(){this.iz(40,c,e)},a);this.aW(c*this.options.step,e)},aW:function(a,c){var e=this.FI(),f=this.options,g=f.min,
k=f.max,f=f.step,l=this.mza(g,f),e=this.g3(e,a,g,k,f,l);this.zu()&&(this.element.val(e),this.kK(e),this.dL(e),this.Vp(e,c));this.ic(e,c,this.NB.lka)},mza:function(a,c){var e=this.J$(c);null!=a&&(e=Math.max(e,this.J$(a)));return e},J$:function(a){a=a.toString();var c=a.indexOf(".");return-1===c?0:a.length-c-1},g3:function(b,c,e,f,g,k){var l,m;if(0<k)return this.Vna(b,c,e,f,g,k);l=null!=e?e:0;try{b=parseFloat(b.toFixed(k))}catch(s){s instanceof TypeError&&(a.r.warn("inputNumber's value after conversion is not a number. \n\r\n                      The converter must convert the value to a Number. coercing using +"),
b=+b)}m=b-l;var t=Math.round(m/g)*g,t=parseFloat(t.toFixed(k));t!==m?(m=0>c?Math.ceil(m/g)*g:Math.floor(m/g)*g,b=l+m+c):b+=c;b=parseFloat(b.toFixed(k));return null!=e&&b<e?e:null!=f&&b>f?(e=Math.floor((f-l)/g)*g+l,e=parseFloat(e.toFixed(k))):b},Vna:function(b,c,e,f,g,k){a.o.assert(0<k);k=Math.pow(10,k);return this.g3(b*k,c*k,null!=e?e*k:e,null!=f?f*k:f,null!=g?g*k:g,0)/k},Wv:function(){this.qia&&(clearTimeout(this.Le),this.qia=!1)},Cv:function(){return a.u.af()?500<Date.now()-c:!0},dL:function(a){var c=
this.options,e=c.max,f=c.min,g=this.qX,k=this.OZ,l,m;this.om&&(g||k)&&(l=g.ojButton("option","disabled"),m=k.ojButton("option","disabled"),c.disabled||void 0===a?(l||g.ojButton("disable"),m||k.ojButton("disable")):null!=e&&a>=e?(l&&g.ojButton("enable"),m||k.ojButton("disable")):(null!=f&&a<=f?l||g.ojButton("disable"):l&&g.ojButton("enable"),m&&k.ojButton("enable")))},FI:function(){var a,c;try{c=this.Ag()||0,a=this.cK(c)}catch(e){a=void 0}return a},y3:function(a){var c=this.element.val(),e;this.Wv();
e=this.FI();this.kK(e);this.dL(e);this.ic(c,a)},Q4:function(){var b=this.options,c=b.min,e=b.max,f=(b=b.translations)?b.numberRange||{}:{},g,k,l,m,s,t,r,b=f.hint||{},n=f.messageDetail||{},f=f.messageSummary||{};null!==b&&(g=b.min||null,k=b.max||null,l=b.inRange||null);null!==n&&(m=n.rangeOverflow||null,s=n.rangeUnderflow||null);null!==f&&(t=f.rangeOverflow||null,r=f.rangeUnderflow||null);c={min:null!=c?c:void 0,max:null!=e?e:void 0,hint:{min:g||null,max:k||null,inRange:l||null},messageDetail:{rangeOverflow:m||
null,rangeUnderflow:s||null},messageSummary:{rangeOverflow:t||null,rangeUnderflow:r||null},converter:this.Yc()};this.d9[a.Pe.VALIDATOR_TYPE_NUMBERRANGE]=a.Ea.Vw(a.Pe.VALIDATOR_TYPE_NUMBERRANGE).createValidator(c)},No:function(a,c){var e;e=null!==c?+c:c;if(isNaN(e))throw Error("ojInputNumber's "+a+" option is not a number");return e},DD:function(a){if(null===a)return 1;a=this.No("step",a);if(0>=a)throw Error("Invalid step for ojInputNumber; step must be \x3e 0");if(null===a||0>=a)a=1;return a},lK:function(a,
c){-1!=Object.keys(this.Tr).indexOf(a)&&this.widget().toggleClass(this.Tr[a],!!c)},iaa:function(a,c){c?this.element.removeAttr("role"):this.element.attr("role","spinbutton")},kK:function(a){this.element.attr({"aria-valuemin":this.options.min,"aria-valuemax":this.options.max,"aria-valuenow":a});this.caa(a)},caa:function(a){var c=this.element,e=c.val();this.uB("value",""+a,e)||c.attr({"aria-valuetext":e})},lca:function(a,c){this.Pj();c?this.aW((a||1)*this.options.step):this.aW((a||1)*-this.options.step);
this.Wv()}});var c})();a.Components.Ta("ojInputNumber","editableValue",{properties:{converter:{type:"Object"},max:{type:"number"},min:{type:"number"},placeholder:{type:"string"},rawValue:{type:"string",writeback:!0,readOnly:!0},readOnly:{type:"boolean"},step:{type:"number"},value:{type:"number",writeback:!0}},methods:{destroy:{},refresh:{},stepDown:{},stepUp:{},widget:{}},extension:{_hasWrapper:!0,_innerElement:"input",_widgetName:"ojInputNumber"}});a.Components.register("oj-input-number",a.Components.getMetadata("ojInputNumber"))});