/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojdatasource-common"],function(a){a.Dx=function(){this.id=null;this.depth=0;this.parent=null;this.children=[];this.AY=this.attr=this.title=null};a.Dx.prototype.joa=function(a){return function(c,b){return null!=c.attr&&null!=b.attr&&null!=c.attr[a]&&null!=b.attr[a]?c.attr[a]<b.attr[a]?-1:c.attr[a]===b.attr[a]?0:1:c[a]<b[a]?-1:c[a]===b[a]?0:1}};a.Dx.prototype.Tqa=function(a){return function(c,b){return null!=c.attr&&null!=b.attr&&null!=c.attr[a]&&null!=b.attr[a]?c.attr[a]<
b.attr[a]?1:c.attr[a]===b.attr[a]?0:-1:c[a]<b[a]?1:c[a]===b[a]?0:-1}};a.Dx.prototype.ica=function(a){var c=a.key;"ascending"===a.direction?this.children.sort(this.joa(c)):"descending"===a.direction&&this.children.sort(this.Tqa(c));for(var c=0,b=this.children.length;c<b;c++)this.children[c].ica(a)};a.td=function(g){var c;c=new a.Dx;null==g.id&&(c.id="root");this.data=this.T4({count:0},c,g);a.td.t.constructor.call(this,c)};o_("JsonTreeDataSource",a.td,a);a.b.ta(a.td,a.tu,"oj.JsonTreeDataSource");a.td.prototype.Init=
function(){a.td.t.Init.call(this)};a.b.g("JsonTreeDataSource.prototype.Init",{Init:a.td.prototype.Init});a.td.prototype.T4=function(g,c,b,d){var e,f,h,k,l,m,s;null==d&&(d=0);for(k in b)if("children"==k||0==d&&b instanceof Array)for(e=0==d&&b instanceof Array?b:b[k],d++,s=0;s<e.length;s++){h=e[s];f=new a.Dx;null==h.id&&(g.count++,null==h.attr?f.id="rid_"+g.count:null==h.attr.id&&(h.attr.id="rid_"+g.count));for(l in h)for(m in f)l==m&&"children"!=l&&(f[m]=h[l]),"depth"==m&&(f[m]=d);c.children.push(f);
for(m in h)"children"==m&&this.T4(g,c.children[s],h,d)}return c};a.td.prototype.ph=function(a){null==a&&(a=this.data.id);a=this.Us(this.data,a);return a.children?a.children.length:0};a.b.g("JsonTreeDataSource.prototype.getChildCount",{ph:a.td.prototype.ph});a.td.prototype.ii=function(g,c,b){var d,e,f,h,k;f=[];null==g&&(g=this.data.id);h=this.Us(this.data,g);c||(c=[],c.start=0,c.count=h.children.length);c.count||(c.count=h.children.length);c.start||(c.start=0);d=c.start;e=Math.min(h.children.length,
d+c.count);for(c=d;c<e;c+=1)k=new a.Dx,null!=h.children[c].attr&&(k.attr=h.children[c].attr),null!=h.children[c].id&&(k.id=h.children[c].id),null!=h.children[c].depth&&(k.depth=h.children[c].depth),null!=h.children[c].title&&(k.title=h.children[c].title),null!=h.children[c].parent&&(k.parent=h.children[c].parent),k.AY=0<h.children[c].children.length?!1:!0,f.push(k);g=new a.ah(d,e,f,g);null!=b&&null!=b.success&&b.success.call(null,g)};a.b.g("JsonTreeDataSource.prototype.fetchChildren",{ii:a.td.prototype.ii});
a.td.prototype.Pz=function(g,c){var b,d,e,f;e=[];null==g&&(g=this.data.id);f=this.Us(this.data,g);b=[];b.start=0;b.count=f.children.length;d=b.start;for(b=Math.min(f.children.length,d+b.count);d<b;d+=1)f.children[d].AY=0<f.children[d].children.length?!1:!0,e.push(f.children[d]);e=new a.ah(0,e.length,e,g);null!=c&&null!=c.success&&c.success.call(null,e)};a.b.g("JsonTreeDataSource.prototype.fetchDescendants",{Pz:a.td.prototype.Pz});a.td.prototype.moveOK=function(){return"valid"};a.b.g("JsonTreeDataSource.prototype.moveOK",
{moveOK:a.td.prototype.moveOK});a.td.prototype.move=function(g,c,b,d){var e;e=c;if(null==e||e==this.data.id){if("inside"!=b){a.r.log("Error: root can not be the reference node if position equals to "+b);return}e||(e=this.data.id)}g=this.Us(null,g);this.Us(g,e)?a.r.log("Error: the node to move contains the reference node as its sub-tree."):(c=this.Us(null,e),e=this.XS(e),this.qAa(g),"inside"==b?(this.Dq(g,g.depth-(c.depth+1)),c.children.push(g)):"before"==b?(this.Dq(g,g.depth-c.depth),b=e.children.indexOf(c),
-1<b&&(0!=b?e.children.splice(b,0,g):e.children.unshift(g))):"after"==b?(this.Dq(g,g.depth-c.depth),b=e.children.indexOf(c),-1<b&&e.children.splice(b+1,0,g)):"first"==b?(this.Dq(g,g.depth-c.depth),e.children.unshift(g)):"last"==b&&(this.Dq(g,g.depth-c.depth),e.children.push(g)),null!=d&&null!=d.success&&d.success.call(null,this.data))};a.b.g("JsonTreeDataSource.prototype.move",{move:a.td.prototype.move});a.td.prototype.sort=function(a,c){var b;b=this.Us(this.data,this.data.id);b.ica(a);null!=c&&null!=
c.success&&c.success.call(null,b)};a.b.g("JsonTreeDataSource.prototype.sort",{sort:a.td.prototype.sort});a.td.prototype.Tq=function(){return{key:null,direction:"none"}};a.b.g("JsonTreeDataSource.prototype.getSortCriteria",{Tq:a.td.prototype.Tq});a.td.prototype.XS=function(a,c){var b,d=null;if(a==this.data.id)return null;null==c&&(c=this.data);if(c.children&&0<c.children.length){for(b=0;b<c.children.length;b++)if(c.children[b].id&&c.children[b].id==a||c.children[b].attr&&c.children[b].attr.id==a)return c;
for(b=0;b<c.children.length&&!(d=this.XS(a,c.children[b]));b++);}return d};a.td.prototype.Us=function(a,c){var b,d=null;null==a&&(a=this.data);if(a.id&&a.id==c||a.attr&&a.attr.id==c)return a;if(null!=a.children)for(b=0;b<a.children.length&&!d;b++)d=a.children[b].id&&a.children[b].id==c||a.children[b].attr&&a.children[b].attr.id==c?a.children[b]:this.Us(a.children[b],c);return d};a.td.prototype.Dq=function(a,c){var b;a.depth-=c;if(a.children&&0!=a.children.length)for(b=0;b<a.children.length;b++)this.Dq(a.children[b],
c)};a.td.prototype.qAa=function(a){var c;null!=a.id?c=a.id:null!=a.attr&&(c=a.attr.id);(c=this.XS(c))||(c=this.data);a=c.children.indexOf(a);-1<a&&c.children.splice(a,1)};a.td.prototype.getCapability=function(a){return"fetchDescendants"===a?"enable":"sort"===a?"default":"batchFetch"===a?"disable":"move"===a?"full":null};a.b.g("JsonTreeDataSource.prototype.getCapability",{getCapability:a.td.prototype.getCapability});a.ah=function(g,c,b,d){a.o.Fq(g,null);a.o.Fq(c,null);this.XHa=d;this.Jt=g;this.LM=
c;this.ri=b};o_("JsonNodeSet",a.ah,a);a.ah.prototype.getParent=function(){return this.XHa};a.b.g("JsonNodeSet.prototype.getParent",{getParent:a.ah.prototype.getParent});a.ah.prototype.getStart=function(){return this.Jt};a.b.g("JsonNodeSet.prototype.getStart",{getStart:a.ah.prototype.getStart});a.ah.prototype.getCount=function(){return Math.max(0,this.LM-this.Jt)};a.b.g("JsonNodeSet.prototype.getCount",{getCount:a.ah.prototype.getCount});a.ah.prototype.getData=function(g){a.o.assert(g<=this.LM&&g>=
this.Jt);g-=this.Jt;return this.ri[g]?this.ri[g].attr:null};a.b.g("JsonNodeSet.prototype.getData",{getData:a.ah.prototype.getData});a.ah.prototype.getMetadata=function(g){var c=[];a.o.assert(g<=this.LM&&g>=this.Jt);g-=this.Jt;c.key=this.ri[g].id?this.ri[g].id:this.ri[g].attr.id;c.leaf=this.ri[g].AY;c.depth=this.ri[g].depth;null==c.leaf&&(c.leaf=this.ri[g].children&&0<this.ri[g].children.length?!1:!0);return c};a.b.g("JsonNodeSet.prototype.getMetadata",{getMetadata:a.ah.prototype.getMetadata});a.ah.prototype.Dq=
function(a,c){var b;c++;a.depth=c;if(a.children&&0!=a.children.length)for(b=0;b<a.children.length;b++)this.Dq(a.children[b],c)};a.ah.prototype.ki=function(g){var c,b,d;a.o.assert(g<=this.LM&&g>=this.Jt);g-=this.Jt;b=this.ri[g].depth;c=this.ri[g].children;if(0==c.length)return null;g=this.ri[g].id?this.ri[g].id:this.ri[g].attr.id;for(d=0;d<c.length;d++)this.Dq(c[d],b);return new a.ah(0,c.length,c,g)};a.b.g("JsonNodeSet.prototype.getChildNodeSet",{ki:a.ah.prototype.ki})});