/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","knockout","jqueryui-amd/widget"],function(a,g,c){function b(){this.Init()}function d(a,b){var c={};c.value=b.value;return c}function e(a,b,c){b={};var d=c.optionMetadata;if(d&&"shouldWrite"===d.writeback){var e=c.option;b[e]=c.value;d.readOnly&&(a.Bha[e]=!0)}return b}function f(a,b,c){"pieCenter"===a&&b.template&&(b.renderer=D(c,b.template));return{pieCenter:b}}function h(a,b){return function(d){var e,h;e=d.parentElement;h=a.createChildContext(d.data,null,function(a){a.$optionContext=
d});c.renderTemplate(b,h,null,e);return null}}function k(a,b,c){return"optionTemplate"===a&&null!==b?{optionRenderer:h(c,String(b))}:null}function l(a,b){this.Init(a,b)}function m(b,c,d,e,h){b=r(b,c,d,e);d=b.iEa;if(null==d)return h;var f={};n(d,function(a,b){f[a]=b});h=a.Wc.pf({},h);h[c]=s(e,f,b.lEa);return h}function s(b,c,d){function e(){var d={};Object.keys(c).forEach(function(e){var h=a.za.nH(c[e]).bind(null,b);Object.defineProperty(d,e,{get:h,enumerable:!0})});Object.defineProperty(d,a.za.M1,
{value:c});return d}e.toString=function(){return d};return e}function t(a,b,c){var d=b.getBindingsString;if(d)return d.call(b,a,c);switch(a.nodeType){case 1:return a.getAttribute("data-bind");case 8:return(a=a.nodeValue.match(/^\s*ko(?:\s+([\s\S]+))?\s*$/))?a[1]:null}return null}function r(a,b,d,e){var h=null;a=t(a,d,e);a=c.jsonExpressionRewriting.parseObjectLiteral(a);var f=null;n(a,function(a,c){return a===b?(f=c,!0):!1});null!=f&&0===f.indexOf("{")&&(h=c.jsonExpressionRewriting.parseObjectLiteral(f));
return{iEa:h,lEa:f}}function n(a,b){for(var c=0;c<a.length;c++){var d=a[c],e=d.key,d=d.value;if(null!=e&&null!=d&&b(e.trim(),d.trim()))break}}function p(a,b){return function(d){var e,h,f;e=d.parentElement;h=a.createChildContext(d.data,null,function(a){a.$key=d.key;a.$metadata=d.metadata;a.$headerContext=d});f=u(b,d);c.renderTemplate(f,h,{afterRender:function(a){g(a)._ojDetectCleanData()}},e);return null}}function q(a,b){return function(d){var e,h,f;e=d.parentElement;h=a.createChildContext(d.data,
null,function(a){a.$keys=d.keys;a.$metadata=d.metadata;a.$cellContext=d;a.$cell=d.cell});f=u(b,d);c.renderTemplate(f,h,{afterRender:function(a){g(a)._ojDetectCleanData()}},e);return null}}function u(a,b){return"function"===typeof a?a(b):a}function v(a,b){return function(d){var e=a.createChildContext(d.data);c.renderTemplate(b,e,{afterRender:function(a){g(a)._ojDetectCleanData()}},d.parentElement);return null}}function w(a,b){return function(d){var e=a.createChildContext(d.data);c.renderTemplate(b,
e,{afterRender:function(a){g(a)._ojDetectCleanData()}},d.parentElement);return null}}function y(a,b,c){if("areaLayers"===a){for(a=0;a<b.length;a++){var d=b[a].areaDataLayer;if(d){var e=d.template;null!=e&&(d._templateRenderer=w(c,e))}}return{areaLayers:b}}if("pointDataLayers"===a){for(a=0;a<b.length;a++)e=b[a].template,null!=e&&(b[a]._templateRenderer=w(c,e));return{pointDataLayers:b}}return null}function x(a,b){return function(d){var e=document.createElement("div");e.style.display="none";d=a.createChildContext(d);
c.renderTemplate(b,d,{afterRender:function(a){g(a)._ojDetectCleanData()}},e);return(d=e.children[0])?(e.removeChild(d),g(e).remove(),d):null}}function z(a,b,c){"tooltip"===a&&b.template&&(b.renderer=x(c,b.template));return{tooltip:b}}function D(a,b){return function(d){var e=document.createElement("div");e.style.display="none";d=a.createChildContext(d);c.renderTemplate(b,d,{afterRender:function(a){g(a)._ojDetectCleanData()}},e);return(d=e.children[0])?(e.removeChild(d),g(e).remove(),d):null}}function I(a,
b,c){"center"===a&&b.template&&(b.renderer=D(c,b.template));return{center:b}}function B(a,b,d){var e={};(function(b,d){e=function(e){var h=null,f=null;"header"==d?(h=a.createChildContext(null,null,function(a){a.$columnIndex=e.columnIndex;a.$headerContext=e.headerContext;a.$data=e.data}),f=e.headerContext.parentElement):"cell"==d&&(h=a.createChildContext(e.row,null,function(a){a.$columnIndex=e.columnIndex;a.$cellContext=e.cellContext}),f=e.cellContext.parentElement);"footer"==d&&(h=a.createChildContext(null,
null,function(a){a.$columnIndex=e.columnIndex;a.$footerContext=e.footerContext}),f=e.footerContext.parentElement);c.renderTemplate(b,h,{afterRender:function(a){g(a)._ojDetectCleanData()}},f,"replaceNode")}})(d,b);return e}function G(a,b){return function(d){var e=a.createChildContext(d.row,null,function(a){a.$rowContext=d.rowContext});c.renderTemplate(b,e,{afterRender:function(a){g(a)._ojDetectCleanData()}},d.rowContext.parentElement,"replaceNode")}}function C(a,b){return function(d){var e,h;e=d.parentElement;
h=a.createChildContext(d.data,null,function(a){a.$itemContext=d});c.renderTemplate(b,h,{afterRender:function(a){g(a)._ojDetectCleanData()}},e,"replaceNode");return null}}function K(a,b,c){return"item"==a?(a=b.template,null!=a&&(b.renderer=C(c,a)),{item:b}):null}a.b.ta(b,a.b,"ComponentBinding.GlobalChangeQueue");b.prototype.Init=function(){b.t.Init.call(this);this.ZK=[];this.LD=[]};b.prototype.IIa=function(b){-1===this.ZK.indexOf(b)&&(this.ZK.push(b),this.$H||(this.$H=setTimeout(a.b.Oda(this,this.g5),
1)))};b.prototype.oX=function(){this.$H&&clearTimeout(this.$H);this.g5()};b.prototype.g5=function(){var a;this.$H=null;var b=this.ZK;this.ZK=[];for(a=0;a<b.length;a++){var c=b[a];this.LD.push({LZ:c,gt:c.DFa()})}for(;0<this.LD.length;)a=this.LD.shift(),a.LZ.ZDa(a.gt)};a.za=function(a,b){this.Init(a,b)};o_("ComponentBinding",a.za,a);a.b.ta(a.za,a.b,"oj.ComponentBinding");a.za.create=function(b,d){if(null==b)throw"Binding name is required!";var e=new a.za(b,d),h=c.bindingHandlers,f,k=Array.isArray(b)?
b:[b];for(f=0;f<k.length;f++){var g=k[f];a.za.b2.push(g);h[g]=e}return e};o_("ComponentBinding.create",a.za.create,a);a.za.Ng=function(){return a.za.ula};o_("ComponentBinding.getDefaultInstance",a.za.Ng,a);a.za.prototype.Sg=function(a){var b=a["for"],b=null==b?"@global":b,c=this.TJ[b]||[];c.push(a);this.TJ[b]=c};a.b.g("ComponentBinding.prototype.setupManagedAttributes",{Sg:a.za.prototype.Sg});a.za.oX=function(){a.za.b4.oX()};o_("ComponentBinding.deliverChanges",a.za.oX,a);a.za.prototype.Init=function(b,
c){a.za.t.Init.call(this);"string"===typeof c&&(c={componentName:c});this.xQ=c||{};Array.isArray(b);this.init=this._init.bind(this);this.update=this.$s.bind(this);this.TJ={}};a.za.prototype._init=function(a,b,d,e,h){c.applyBindingsToDescendants(h,a);return{controlsDescendantBindings:!0}};a.za.prototype.$s=function(b,d,e,h,f){function k(b){m.forEach(function(a){a.dispose()});m=[];b&&t&&(t("destroy"),t=null);p&&(p.Nz(),p=null);n.off(a.za.e1)}function q(c,d,h){if(null!=c){var k=n[c];if("function"!==
typeof k)a.r.error("Component %s is not found",c);else{k=k.bind(n);p=new l(k,a.za.b4);var g=Object.keys(h).filter(function(a){return!(null==a||a===d)});t=this.Fwa(b,{R:k,JE:p,Ida:c,VF:g,IEa:m,Zt:function(){return h},Ez:e,dw:f,kFa:function(){t=null},Bha:{}})}}}var m=[],r=0,t,p,n=g(b);c.ignoreDependencies(function(){c.computed(function(){var b=c.utils.unwrapObservable(d());"object"!==typeof b&&a.r.error("ojComponent binding should evaluate to an object");var e=this.xQ.componentName,h,f=!1;if(null==
e&null!=b){for(var g=[a.za.Eka,"role"],l=0;!f&&l<g.length;l++)h=g[l],h in b&&(f=!0,e=b[h]);f||a.r.error("component attribute is required for the ojComponent binding");e=c.utils.unwrapObservable(e)}0==r?r=1:c.ignoreDependencies(k,this,[!0]);c.ignoreDependencies(q,this,[e,h,b])},this,{disposeWhenNodeIsRemoved:b})},this);c.utils.domNodeDisposal.addDisposeCallback(b,k.bind(this,!1))};a.za.prototype.Fwa=function(b,d){function e(){var c=this.Dza,h=a.za.$Ca(d.Zt()[c]);if(0===k){var g=p[c];null!=g?(l[c]=
g,g=g.Yq,null!=g&&(c=g(c,h,b,m,d.Zt,d.Ez,d.dw)||{},a.Wc.pf(u,c))):u[c]=h}else if(!f)if(null!=p[c]){if(g=p[c].update,null!=g)for(c=g(c,h,b,m,d.Zt,d.Ez,d.dw)||{},h=Object.keys(c),g=0;g<h.length;g++){var q=h[g];d.JE.gda(q,c[q])}}else d.Bha[c]||d.JE.gda(c,h)}function h(c){c.target&&c.target==b&&(d.kFa(),(c=t.xQ.beforeDestroy)&&c(b,m,d.Zt,d.Ez,d.dw),a.za.h5(!1,l,b,m,d.Zt,d.Ez,d.dw),f=!0,d.JE.Nz(),b.removeEventListener("_ojDestroy",h))}var f=!1,k=0,l={},q=g(b),m=d.R,r=d.Ida,t=this;b.addEventListener("_ojDestroy",
h);var p=a.za.Taa(this.TJ,d.VF,r),n=a.za.Ng();this!==n&&(r=n.nta(d.VF,r),a.Wc.pf(r,p),p=r);for(var u={},r=0;r<d.VF.length;r++)d.IEa.push(c.computed(e,{Dza:d.VF[r]}));k=1;a.za.eAa(q,d);var s=a.za.N2(u);m(u);Object.keys(s).forEach(function(a){m("option",a,s[a])});(q=this.xQ.afterCreate)&&q(b,m,d.Zt,d.Ez,d.dw);a.za.h5(!0,l,b,m,d.Zt,d.Ez,d.dw);u=null;return m};a.za.nH=function(a){return new Function("$context","with($context){with($data||{}){return "+a+";}}")};a.za.prototype.nta=function(b,c){return a.za.Taa(this.TJ,
b,c)};a.za.Taa=function(a,b,c){function d(b,c){var e=a[b];if(null!=e)for(var f=e.length-1;0<=f;f--){var k=e[f];null!=k.attributes&&h.push(k);if(c&&(k=k.use,null!=k))for(var k=Array.isArray(k)?k:[k],g=0;g<k.length;g++)d(k[g],!0)}}var e={},h=[];d(c,!0);c=g.oj[c];if(null!=c)for(c=Object.getPrototypeOf(c.prototype);null!=c&&"oj"===c.namespace;)d(c.widgetName,!0),c=Object.getPrototypeOf(c);d("@global",!1);if(0<h.length)for(c=0;c<b.length;c++)for(var f=b[c],k=0;k<h.length;k++){var l=h[k];if(0<=l.attributes.indexOf(f)){e[f]=
{Yq:l.init,update:l.update,Cz:l.afterCreate,kEa:l.beforeDestroy};break}}return e};a.za.e1=".oj_ko";a.za.eAa=function(b,c){for(var h={"^slider$":[{event:"slidechange",getter:d}],"^oj*":[{event:"ojoptionchange",getter:e.bind(void 0,c)}]},f={},k=Object.keys(h),g=0;g<k.length;g++){var l=k[g];if(c.Ida.match(l)){h=h[l];for(k=0;k<h.length;k++)g=h[k],b.on(g.event+a.za.e1,{uGa:g.getter},function(d,e){if(d.target===b[0]){var h=d.data.uGa(d,e),k=c.Zt(),g;for(g in h){c.JE.wJa(g);try{if(0<=c.VF.indexOf(g)){var l=
k[a.za.M1];a.za.PDa(g,k[g],h[g],null==l?null:l[g],c.dw,f)}}finally{c.JE.YIa(g)}}}});break}}};a.za.PDa=function(b,d,e,h,f,k){null!=d&&c.isObservable(d)?c.isWriteableObservable(d)&&d(e):(b in k||(d=null,h=a.oH.$ea(h),null!=h&&(d=a.za.nH(h)),k[b]=d),(b=k[b])&&b(f)(e))};a.za.$Ca=function(b){b=c.utils.unwrapObservable(b);(Array.isArray(b)||a.Wc.isPlainObject(b))&&b.ojConvertToJS&&(b=c.toJS(b));return b};a.za.N2=function(a){for(var b={},c=Object.keys(a),d=0;d<c.length;d++){var e=c[d];0<=e.indexOf(".")&&
(b[e]=a[e],delete a[e])}return b};a.za.h5=function(a,b,c,d,e,h,f){for(var k=Object.keys(b),g=0;g<k.length;g++){var l=k[g],q=b[l];(q=a?q.Cz:q.kEa)&&q(l,c,d,e,h,f)}};a.za.b4=new b;a.za.mna=function(){return a.Rx()&&c?c.version:""};a.za.yxa=function(b){return 0<=a.za.b2.indexOf(b)};a.za.b2=[];a.za.Eka="component";a.za.M1="_ojOptions";(function(){var b=c.removeNode;c.removeNode=function(c){var d=a.Components;d&&a.u.cia(c);try{b(c)}finally{d&&a.u.cia(null)}}})();a.za.ula=a.za.create(["ojComponent","jqueryUI"]);
g.widget("oj._ojDetectCleanData",{_destroy:function(){var a,b;a=c.utils.domNodeDisposal;b=a.cleanExternalData;a.cleanExternalData=function(){};try{c.cleanNode(this.element[0])}finally{a.cleanExternalData=b}}});a.za.Ng().Sg({attributes:["pieCenter"],init:function(a,b,c,d,e,h,k){return f(a,b,k)},update:function(a,b,c,d,e,h,k){return f(a,b,k)},"for":"ojChart"});a.za.Ng().Sg({attributes:["optionTemplate"],init:function(a,b,c,d,e,h,f){a=k(a,b,f);if(null!==a)return a},update:function(a,b,c,d,e,h,f){return k(a,
b,f)},"for":"ComboboxOptionRenderer"});a.za.Ng().Sg({"for":"ojCombobox",use:"ComboboxOptionRenderer"});a.za.Ng().Sg({"for":"ojSelect",use:"ComboboxOptionRenderer"});a.za.Ng().Sg({"for":"ojInputSearch",use:"ComboboxOptionRenderer"});a.b.ta(l,a.b,"ComponentBinding.ComponentChangeTracker");l.prototype.Init=function(a,b){l.t.Init.call(this);this.xa=a;this.LD=b;this.TQ={};this.pz={}};l.prototype.gda=function(a,b){this.Exa(a)||this.s5||(this.TQ[a]=b,this.LD.IIa(this))};l.prototype.Nz=function(){this.s5=
!0};l.prototype.YIa=function(b){var c=this.pz[b]||0;c--;0>c?a.r.error("ComponentChangeTracker suspendCount underflow"):0==c?delete this.pz[b]:this.pz[b]=c};l.prototype.wJa=function(a){this.pz[a]=(this.pz[a]||0)+1};l.prototype.ZDa=function(b){if(!this.s5){var c=a.za.N2(b),d={changed:!0};this.xa("option",b,d);for(var e in c)this.xa("option",e,c[e],d)}};l.prototype.DFa=function(){var a=this.TQ;this.TQ={};return a};l.prototype.Exa=function(a){return 1<=(this.pz[a]||0)};c.bindingHandlers.ojContextMenu=
{update:function(b,d){function e(a,b,c){p=c;var d=k();if(p)q.one("touchend.ojContextMenu",function(){d.Px(!0);setTimeout(function(){d.Px(!1)},50)});"touchstart"===s&&"contextmenu"===a.type||"contextmenu"===s&&"touchstart"===a.type?(s=null,clearTimeout(u)):!a.isDefaultPrevented()&&(b={launcher:q,initialFocus:"menu",position:{mouse:{my:"start top",at:"start bottom",of:a},touch:{my:"start\x3e40 center",at:"start bottom",of:a,collision:"flipfit"},keyboard:{my:"start top",at:"start bottom",of:"launcher"}}[b]},
d.qH=!0,d.open(a,b),d.qH=!1,f().is(":visible")&&(a.preventDefault(),document.addEventListener("keyup",h),"touchstart"===a.type||"contextmenu"===a.type))&&(s=a.type,u=setTimeout(function(){s=null},300))}function h(a){121==a.which&&a.shiftKey&&f().is(":visible")&&a.preventDefault()}function f(){m||l();return m}function k(){r||l();return r}function l(){m=g(w).first();r=m.data("oj-ojMenu");if(!r)throw Error('"contextMenu" set to "'+w+'", which does not reference a valid JET Menu.');m.on("ojclose.ojContextMenu",
function(){document.removeEventListener("keyup",h)})}var q=g(b),m,r,t,p=!1,n=!1,u,s=null,v;q.off(".ojContextMenu").removeClass("oj-menu-context-menu-launcher")[0].removeEventListener("click",v,!0);m&&m.off(".ojContextMenu");clearTimeout(t);m=r=void 0;var w=c.utils.unwrapObservable(d());g.isPlainObject(w)&&(w=b.getAttribute("contextmenu"))&&(w=document.getElementById(w));v=function(a){if(p)return a.preventDefault(),a.stopPropagation(),p=!1};b.addEventListener("click",v,!0);q.on("touchstart.ojContextMenu mousedown.ojContextMenu keydown.ojContextMenu ",
function(a){if("mousedown"!==a.type||!k().Px())return p=!1,"touchstart"===a.type&&(n=!0,t=setTimeout(e.bind(void 0,a,"touch",!0),750)),!0}).on("touchend.ojContextMenu touchcancel.ojContextMenu",function(){n=!1;clearTimeout(t);return!0}).on("keydown.ojContextMenu contextmenu.ojContextMenu",function(a){("contextmenu"===a.type||121==a.which&&a.shiftKey)&&e(a,n?"touch":"keydown"===a.type?"keyboard":"mouse",!1);return!0}).addClass(a.u.af()?"oj-menu-context-menu-launcher":"")}};a.iQ=(new function(){function b(a,
c,e){var h=a[e];c[e]=function(){var b=h?h.apply(a,arguments):null,c=d[e];if(null!=c){var f=arguments;c.forEach(function(c){var d=Array.prototype.slice.call(f);d.push(b,a);b=c.apply(null,d)})}return b}}this.lY=function(){var d=c.bindingProvider,e=d.instance;if(!e.getBindingAccessors)return a.r.error("JET's Knockout bindings are not compatible with the current binding provider since it does not implement getBindingAccessors()"),this;var h=d.instance={},d=[];d.push("getBindingAccessors","nodeHasBindings",
"getBindings","preprocessNode");d.forEach(function(a){b(e,h,a)});return this};this.UW=function(a){Object.keys(a).forEach(function(b){d[b]=d[b]||[];d[b].push(a[b])})};var d={}}).lY();a.iQ.UW({getBindingAccessors:function(b,c,d,e){if(null==d)return null;var h;a:{h=Object.keys(d);for(var f=-0;f<h.length;f++){var k=h[f];if(a.za.yxa(k)){h=k;break a}}h=null}null!=h&&(d=m(b,h,e,c,d));return d}});a.iQ.UW({nodeHasBindings:function(b,c){return c||1===b.nodeType&&a.Components&&a.Components.nga(b.nodeName)},
getBindingAccessors:function(b,c,d){1===b.nodeType&&(b=b.nodeName,a.Components&&a.Components.nga(b)&&(d=d||{},d._ojCustomElement=function(){}));return d}});a.za.Ng().Sg({attributes:["header","cell"],init:function(a,b,c,d,e,h,f){if("header"===a)return a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),a=b.rowEnd,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),a=b.columnEnd,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,
c))),{header:b};if("cell"===a)return a=b.template,null!=a&&(b.renderer=q(f,a)),{cell:b}},update:function(a,b,c,d,e,h,f){return"header"===a?(a=b.row,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),a=b.column,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),a=b.rowEnd,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),a=b.columnEnd,null!=a&&(c=a.template,null!=c&&(a.renderer=p(f,c))),{header:b}):"cell"===a?(a=b.template,null!=a&&(b.renderer=q(f,a)),{cell:b}):null},"for":"ojDataGrid"});a.za.Ng().Sg({attributes:["template"],
init:function(a,b,c,d,e,h,f){return"template"===a?{_templateFunction:v(f,b)}:null},update:function(a,b,c,d,e,h,f){return"template"===a?{_templateFunction:v(f,b)}:null},"for":"ojDiagram"});(function(){a.oH={};a.oH.QE=function(a){var d={};if(a){var e=b.exec(a),e=e?e[1]:null;e||(d.cea=!0,e=(e=c.exec(a))?e[1]:null);d.expr=e}return d};a.oH.$ea=function(a){var b=["true","false","null","undefined"];if(null==a||0<=b.indexOf(a))return null;b=a.match(d);return null===b?null:"function(v){"+(b[1]?"Object("+b[1]+
")"+b[2]:a)+"\x3dv;}"};var b=/(?:\{\{\s*)([^\s]+)(?:\s*\}\})/,c=/(?:\[\[\s*)([^\s]+)(?:\s*\]\])/,d=/^(?:[$_a-z][$\w]*|(.+)(\.\s*[$_a-z][$\w]*|\[.+\]))$/i})();a.I2=function(b,d){function e(h,f,q,m){function r(b){var e=!1;g[h]||(m&&c.ignoreDependencies(function(){var h=b.detail.value,k=q(d);c.isWriteableObservable(k)?(e=!0,k(h)):(k=a.oH.$ea(f),null!=k&&(a.za.nH(k)(d)(h),e=!0))}),e||(k[h]=!0))}b.addEventListener(h+l,r);return r}this.AZ=function(q,m,r){q=a.jf.QE(q);k[m]&&(k[m]=null);var t=h[m];t&&(t.dispose(),
h[m]=null);if(t=f[m])b.removeEventListener(m+l,t),f[m]=null;var t=r.readOnly,p=q.expr;if(p){var n=a.za.nH(p);t||c.ignoreDependencies(function(){h[m]=c.computed(function(){if(!k[m]){var e=n(d),e=c.utils.unwrapObservable(e),h=g[m]||0;h++;g[m]=h;try{b[m]=e}finally{(e=g[m])?(e--,g[m]=0===e?null:e):a.r.error("Property count undefrlow")}}})});f[m]=e(m,p,n,r.writeback&&!q.cea);return!0}return!1};this.CN=function(a){for(var b=Object.keys(h),c=0;c<b.length;c++)h[b[c]].dispose();h={};b=Object.keys(f);for(c=
0;c<b.length;c++){var d=b[c];a.removeEventListener(d+l,f[d])}f={}};var h={},f={},k={},g={},l="-changed"};a.Wn={};o_("ResponsiveKnockoutUtils",a.Wn,a);a.Wn.Lz=function(a){if(null==a)throw Error("oj.ResponsiveKnockoutUtils.createMediaQueryObservable: aborting, queryString is null");a=window.matchMedia(a);var b=c.observable(a.matches);a.addListener(function(a){b(a.matches)});-1!=navigator.userAgent.indexOf("WebKit")&&-1==navigator.userAgent.indexOf("Chrome")&&g(window).resize(function(){0===g("body").has(".oj-webkit-bug-123293").length&&
g("body").append('\x3cdiv aria-hidden\x3d"true" class\x3d"oj-helper-hidden-accessible oj-webkit-bug-123293"\x3e');g(".oj-webkit-bug-123293").text((new Date).getMilliseconds().toString())});return b};o_("ResponsiveKnockoutUtils.createMediaQueryObservable",a.Wn.Lz,a);a.Wn.REa=function(){var b=a.dc.Sz(a.dc.cx.XXL_UP),d=a.dc.Sz(a.dc.cx.XL_UP),e=a.dc.Sz(a.dc.cx.LG_UP),h=a.dc.Sz(a.dc.cx.MD_UP),f=a.dc.Sz(a.dc.cx.SM_UP),k=null==b?null:a.Wn.Lz(b),g=null==d?null:a.Wn.Lz(d),l=null==e?null:a.Wn.Lz(e),q=null==
h?null:a.Wn.Lz(h),m=null==f?null:a.Wn.Lz(f);return c.computed(function(){if(k&&k())return a.dc.Am.XXL;if(g&&g())return a.dc.Am.XL;if(l&&l())return a.dc.Am.LG;if(q&&q())return a.dc.Am.MD;if(m&&m())return a.dc.Am.SM;throw Error(" NO MATCH in oj.ResponsiveKnockoutUtils.createScreenRangeObservable");})};o_("ResponsiveKnockoutUtils.createScreenRangeObservable",a.Wn.REa,a);a.za.Ng().Sg({attributes:["areaLayers","pointDataLayers"],init:function(a,b,c,d,e,h,f){return y(a,b,f)},update:function(a,b,c,d,e,h,
f){return y(a,b,f)},"for":"ojThematicMap"});a.za.Ng().Sg({attributes:["tooltip"],init:function(a,b,c,d,e,h,f){return z(a,b,f)},update:function(a,b,c,d,e,h,f){return z(a,b,f)},"for":"tooltipOptionRenderer"});(function(){for(var b="ojChart ojDiagram ojNBox ojPictoChart ojSunburst ojTagCloud ojThematicMap ojTreemap ojDialGauge ojLedGauge ojRatingGauge ojSparkChart ojStatusMeterGauge".split(" "),c=0;c<b.length;c++)a.za.Ng().Sg({"for":b[c],use:"tooltipOptionRenderer"})})();a.xY={};o_("koStringTemplateEngine",
a.xY,a);a.xY.lY=function(){if(!c.templates){var a={},b={},d=new c.nativeTemplateEngine,e=function(c){this.sz=c;this.text=function(b){if(!b)return a[this.sz];a[this.sz]=b};this.data=function(a,c){b[this.sz]||(b[this.sz]={});if(1===arguments.length)return b[this.sz][a];b[this.sz][a]=c}};d.makeTemplateSource=function(a,b){if("string"==typeof a){b=b||document;var d=b.getElementById(a);return d?new c.templateSources.domElement(d):new e(a)}if(a&&1==a.nodeType||8==a.nodeType)return new c.templateSources.anonymousTemplate(a)};
c.templates=a;c.setTemplateEngine(d)}};o_("koStringTemplateEngine.install",a.xY.lY,a);(function(){c.bindingHandlers._ojCustomElement={update:function(d,e,h,f,k){function g(){m&&(m.CN(),m=null);r&&(d.removeEventListener(b,r),r=null)}function l(){var c=a.Components.getMetadata(d.tagName);if(c){var e=c.properties;e&&(c=Object.keys(e),0!==c.length&&(m=new a.I2(d,k),c.forEach(function(b){var c=a.jf.EA(b);d.hasAttribute(b)&&(c=d.getAttribute(c),m.AZ(c,b,e[b]))}),r=function(b){b=b.detail;var c=a.jf.ZW(b.attribute);
m.AZ(b.value,c,e[c])},d.addEventListener(b,r),d.classList.add("oj-complete")))}}var q=0,m,r,t=a.Components.NFa(d);c.ignoreDependencies(function(){c.computed(function(){function b(a,c){return function(a,b){a===q&&c(b)}.bind(void 0,a)}e();c.computedContext.isInitial()||g();q++;t.then(b(q,function(){l()}),b(q,function(b){a.r.error("Component create Promise rejected. Reason: %o",b)}))},null,{disposeWhenNodeIsRemoved:d})});c.utils.domNodeDisposal.addDisposeCallback(d,g)}};var b="attribute-changed"})();
a.za.Ng().Sg({attributes:["center"],init:function(a,b,c,d,e,h,f){return I(a,b,f)},update:function(a,b,c,d,e,h,f){return I(a,b,f)},"for":"ojStatusMeterGauge"});a.za.Ng().Sg({attributes:["columns","columnsDefault","rowTemplate"],init:function(a,b,c,d,e,h,f){if("columns"==a||"columnsDefault"==a){for(c=0;c<b.length;c++){var k=b[c];d=k.template;e=k.footerTemplate;h=k.headerTemplate;null!=d&&(k.renderer=B(f,"cell",d));null!=e&&(k.footerRenderer=B(f,"footer",e));null!=h&&(k.headerRenderer=B(f,"header",h))}return"columns"==
a?{columns:b}:{columnsDefault:b}}if("rowTemplate"==a)return{rowRenderer:G(f,b)}},update:function(a,b,c,d,e,h,f){if("columns"==a||"columnsDefault"==a){var k;for(c=0;c<b.length;c++){var g=b[c];e=g.template;h=g.footerTemplate;k=g.headerTemplate;null!=e&&(g.renderer=B(f,"cell",e));null!=h&&(g.footerRenderer=B(f,"footer",h));null!=k&&(g.headerRenderer=B(f,"header",k))}"columns"==a?d({columns:b}):d({columnsDefault:b})}else if("rowTemplate"==a)return{rowRenderer:G(f,b)};return null},"for":"ojTable"});a.za.Ng().Sg({attributes:["item"],
init:function(a,b,c,d,e,h,f){a=K(a,b,f);if(null!=a)return a},update:function(a,b,c,d,e,h,f){return K(a,b,f)},"for":"ojListViewRenderer"});a.za.Ng().Sg({"for":"ojListView",use:"ojListViewRenderer"});a.za.Ng().Sg({"for":"ojNavigationList",use:"ojListViewRenderer"})});