/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojdnd","ojs/ojlistview"],function(a,g){a.gb=function(a){this.Ga=a};o_("ListViewDndContext",a.gb,a);a.b.ta(a.gb,a.b,"oj.ListViewDndContext");a.gb.gja=67;a.gb.MO=86;a.gb.OO=88;a.gb.prototype.wS=function(a){var b=this.Ga.me("dnd");return null!=b&&b[a]?b[a].items:null};a.gb.prototype.II=function(){return this.wS("drag")};a.gb.prototype.xS=function(){return this.wS("drop")};a.gb.prototype.rq=function(){return"enabled"==this.wS("reorder")};a.gb.prototype.cg=function(a){return this.Ga.xm(a)};
a.gb.prototype.aT=function(){var a,b,d,e;a=[];if(this.Ga.xc())for(b=this.Ga.me("selection"),d=0;d<b.length;d++)e=this.Ga.Ne(b[d]),null==e||this.Ga.lk(g(e))||a.push(e);else e=this.kS(),null!=e&&a.push(e);null!=this.xw&&0<this.xw.length&&-1==a.indexOf(this.xw.get(0))&&a.push(this.xw.get(0));return a};a.gb.prototype.kS=function(){return null==this.Ga.N?null:this.Ga.N.elem[0]};a.gb.prototype.uw=function(a){var b;g(a).hasClass(this.Ga.Vi())||(a=a.firstElementChild);a=g(a).find(".oj-listview-drag-handle");
null!=a&&0<a.length&&(b=a.attr("aria-labelledby"),null==b?a.attr("aria-labelledby",this.Ga.Yu("instr")):a.attr("aria-labelledby",b+" "+this.Ga.Yu("instr")),this.Ga.Jl()&&a.attr("draggable","true"))};a.gb.prototype.wba=function(a){var b,d;if(null!=this.II()||this.rq()){if(a.hasClass("oj-listview-drag-handle"))b=g(a);else{a=this.cg(a);if(null!=a){d=a.find(".oj-listview-drag-handle");if(null!=d&&0<d.length)return;a.addClass("oj-draggable")}d=this.kS();null!=d&&(null!=a&&0==a.find(".oj-listview-drag-handle").length&&
a[0]==d?b=a:g(d).removeClass("oj-draggable"))}null!=b&&b.attr("draggable",!0)}};a.gb.prototype.Qca=function(a){if(null!=this.II()||this.rq())a=a.hasClass("oj-listview-drag-handle")?g(a):this.cg(a),null!=a&&a.removeAttr("draggable")};a.gb.prototype.an=function(c,b,d,e){var f;if(c="drag"===c?this.II():this.xS())if((b=c[b])&&"function"==typeof b)try{d.dataTransfer=d.originalEvent.dataTransfer,f=b(d,e)}catch(g){a.r.error("Error: "+g)}else return-1;return f};a.gb.prototype.ABa=function(a,b,d){var e,f=
[],g;for(e=0;e<d.length;e++)(g=this.Ga.z6(d[e]))&&(g.innerHTML&&g.tagName&&"LI"==g.tagName?f.push(g.innerHTML):f.push(g));return 0<f.length?(this.zBa(a.originalEvent,b,f),this.BBa(a.originalEvent,d),{items:f}):null};a.gb.prototype.zBa=function(a,b,d){var e;a=a.dataTransfer;d=JSON.stringify(d);if("string"==typeof b)a.setData(b,d);else if(b)for(e=0;e<b.length;e++)a.setData(b[e],d);a.setData("text/ojlistview-dragsource-id",this.Ga.element.get(0).id)};a.gb.prototype.BBa=function(a,b){var d,e,f=Number.MAX_VALUE,
h,k,l,m=0,s=0;d=a.target;if(1<b.length){d=g(document.createElement("ul"));d.get(0).className=this.Ga.element.get(0).className;d.addClass("oj-listview-drag-image").css({width:this.Ga.element.css("width"),height:this.Ga.element.css("height")});for(e=0;e<b.length;e++)f=Math.min(f,b[e].offsetTop);for(e=0;e<b.length;e++)h=b[e].offsetTop-f,k=b[e].offsetWidth,l=g(b[e].cloneNode(!0)),l.removeClass("oj-selected oj-focus oj-hover").css({position:"absolute",top:h,width:k}),d.append(l)}else g(d).hasClass("oj-listview-drag-handle")&&
(m=Math.max(0,d.offsetLeft-b[0].offsetLeft)+d.offsetWidth/2,s=d.offsetTop+d.offsetHeight/2),l=g(b[0].cloneNode(!0)),l.removeClass("oj-selected oj-focus oj-hover").addClass("oj-drag"),d=g(document.createElement("ul")),d.get(0).className=this.Ga.element.get(0).className,d.addClass("oj-listview-drag-image").css({width:this.Ga.element.css("width"),height:2*b[0].offsetHeight}).append(l);g("body").append(d);this.KM=d;a.dataTransfer.setDragImage(d.get(0),m,s)};a.gb.prototype.BT=function(a){var b,d,e;b=this.II();
if(null!=b||this.rq())if(d=null!=b?b.dataTypes:"text/ojlistview-items-data",g(a.target).hasClass("oj-listview-drag-handle")?(e=[],e.push(this.cg(a.target)[0])):e=this.aT(),0<e.length){if(null==b&&1<e.length)return!1;this.dr=e;this.IM=g(e[0]);if(b=this.ABa(a,d,e)){if(a=this.an("drag","dragStart",a,b),-1!==a)return a}else return!1}};a.gb.prototype.Iua=function(a){return this.an("drag","drag",a)};a.gb.prototype.dI=function(){null!=this.KM&&(this.KM.remove(),this.KM=null)};a.gb.prototype.xT=function(a){var b;
if(null!=this.IM&&null!=this.dr)for(this.IM.find(".oj-listview-drag-handle").removeAttr("draggable"),this.IM.removeClass("oj-drag oj-draggable").removeAttr("draggable"),b=0;b<this.dr.length;b++)g(this.dr[b]).css("display","block");this.gC();this.dI();this.an("drag","dragEnd",a);this.IM=this.KM=null};a.gb.prototype.KU=function(a){var b,d;b=this.xS();if(this.rq()&&null==b)return!0;if(b&&b.dataTypes)for(b=b.dataTypes,b="string"==typeof b?[b]:b,a=a.originalEvent.dataTransfer.types,d=0;d<a.length;d++)if(0<=
b.indexOf(a[d]))return!0;return!1};a.gb.prototype.bn=function(a,b,d){a=this.an("drop",a,b,d);(void 0===a||-1===a)&&this.KU(b)&&b.preventDefault();return a};a.gb.prototype.F4=function(a){var b;null==this.bj&&(b=g(a.get(0).cloneNode(!1)),b.addClass("oj-drop").removeClass("oj-drag oj-draggable oj-hover oj-focus oj-selected").css({display:"block",height:a.outerHeight()}),this.bj=b);return this.bj};a.gb.prototype.f4=function(){null!=this.Bn&&-1===this.pA&&this.Bn.children("."+this.Ga.mg()).removeClass("oj-drop")};
a.gb.prototype.gC=function(){null!=this.bj&&(this.bj.css("height","0"),this.bj.remove(),this.bj=null);this.f4()};a.gb.prototype.yT=function(a){var b;b=this.cg(a.target);a=this.bn("dragEnter",a,{item:b.get(0)});if(-1!=a)return a};a.gb.prototype.tba=function(a){null!=this.Bn&&this.Bn.removeClass("oj-valid-drop oj-invalid-drop");this.Bn=a;this.Bn.addClass("oj-valid-drop")};a.gb.prototype.nba=function(a,b){var d;d=a.attr("aria-label");null==d&&(d=a.text());d=this.Ga.Y.F("accessibleReorder"+b.charAt(0).toUpperCase()+
b.substr(1)+"Item",{item:d});this.Ga.Kg(d)};a.gb.prototype.Rna=function(){null==this.Mga&&this.Ga.Jl()&&(this.Ga.element.find("ul."+this.Ga.li()).each(function(){g(this).attr("oldMaxHeight",g(this).css("maxHeight").toString());g(this).css("maxHeight",1E4)}),this.Mga="adjusted")};a.gb.prototype.Yaa=function(){this.Ga.Jl()&&this.Ga.element.find("ul."+this.Ga.li()).each(function(){g(this).css("maxHeight",parseInt(g(this).attr("oldMaxHeight"),10));g(this).removeAttr("oldMaxHeight")});this.Mga=null};a.gb.prototype.AT=
function(a){var b,d,e,f;if(null!=this.xS()||this.rq()){this.Rna();if(null!=this.dr&&"none"!=g(this.dr[0]).css("display")){b=g(this.dr[0]);d=this.F4(b);for(a=0;a<this.dr.length;a++)g(this.dr[a]).css("display","none");d.insertBefore(b);this.pA=d.index()}else b=this.cg(a.target),null!=b&&0<b.length&&(e=this.bn("dragOver",a,{item:b.get(0)}),-1===e&&this.rq()||!1===e||a.isDefaultPrevented()?(b.hasClass(this.Ga.Vi())?(this.f4(),b.hasClass("oj-drop")||(d=this.F4(b),f=b.index(),null==this.pA||this.pA<f?(d.insertAfter(b),
this.oA="after"):(d.insertBefore(b),this.oA="before"),this.nba(b,this.oA),this.tba(b),this.pA=d.index())):(this.gC(),b.children("."+this.Ga.mg()).addClass("oj-drop"),this.tba(b),this.pA=-1,this.oA="inside",this.nba(b,this.oA)),a.preventDefault()):g(a.target).hasClass(this.Ga.li())||(b.addClass("oj-invalid-drop"),this.gC()));return e}};a.gb.prototype.oU=function(a,b){var d,e;d=b.getBoundingClientRect();e=a.originalEvent;return e.clientX>=d.left&&e.clientX<d.right&&e.clientY>=d.top&&e.clientY<d.bottom};
a.gb.prototype.zT=function(a){var b,d;if(null!=this.Bn&&(b=this.cg(a.target),null!=b&&0<b.length&&(b.removeClass("oj-valid-drop oj-invalid-drop"),d=this.bn("dragLeave",a,{item:b.get(0)}),this.oU(a,a.currentTarget)||(this.gC(),this.Yaa())),-1!=d))return d};a.gb.prototype.CT=function(a){var b,d;if(null!=this.Bn&&(b=a.originalEvent.dataTransfer.getData("text/ojlistview-dragsource-id"),d={item:this.Bn.get(0),position:this.oA},this.rq()&&b===this.Ga.element.get(0).id?d.reorder=!0:d.reorder=!1,b=this.bn("drop",
a,d),d.reorder&&(d.items=this.dr,d.reference=d.item,this.Ga.mk("reorder",a,d),a.preventDefault()),null!=this.Bn&&this.Bn.removeClass("oj-valid-drop"),this.gC(),this.Yaa(),this.dI(),this.Bn=null,this.pA=-1,this.oA=null,-1!==b))return b};a.gb.prototype.SDa=function(a){var b=this,d,e;this.rq()&&(void 0==a&&(a=this.Ga.me("contextMenu")),null!=a&&(null==this.dm&&(this.dm=[]),a=g(a),d=a.find("[data-oj-command]"),e=[],d.each(function(){var a,c;0===g(this).children("a").length?0==g(this).attr("data-oj-command").indexOf("oj-listview-")&&
(a=g(this).attr("data-oj-command").substring(12),c=b.yj(a),c.get(0).className=g(this).get(0).className,g(this).replaceWith(c)):(a=g(this).attr("data-oj-command"),"pasteBefore"==a?a="paste-before":"pasteAfter"==a&&(a="paste-after"));null!=a&&e.push(a)}),this.dm=e,0<e.length&&(a.data("oj-ojMenu")&&a.ojMenu("refresh"),a.on("ojselect",this.Dk.bind(this)))))};a.gb.prototype.yj=function(a){return"paste-before"===a?this.$f("pasteBefore"):"paste-after"===a?this.$f("pasteAfter"):this.$f(a)};a.gb.prototype.$f=
function(a){var b=g("\x3cli\x3e\x3c/li\x3e");b.attr("data-oj-command",a);b.append(this.bC(a));return b};a.gb.prototype.bC=function(a){a="label"+a.charAt(0).toUpperCase()+a.slice(1);return g('\x3ca href\x3d"#"\x3e\x3c/a\x3e').text(this.Ga.Y.F(a))};a.gb.prototype.YC=function(a){var b;null!=this.An&&g(this.An).removeClass("oj-listview-cut");b=this.aT();g(b).addClass("oj-listview-cut");this.An=b;this.Ga.mk("cut",a,{items:b})};a.gb.prototype.X7=function(a){var b;null!=this.An&&g(this.An).removeClass("oj-listview-cut");
this.An=b=this.aT();this.Ga.mk("copy",a,{items:b})};a.gb.prototype.$C=function(a,b,d){this.Ga.mk("paste",a,{item:b.get(0)});g(this.An).removeClass("oj-listview-cut");this.Ga.mk("reorder",a,{items:this.An,position:d,reference:b.get(0)});this.An=null};a.gb.prototype.Dk=function(a,b){if(null!=this.xw)switch(b.item.attr("data-oj-command")){case "cut":this.YC(a);break;case "copy":this.X7(a);break;case "paste":var d=!0;case "pasteBefore":var e=!0;case "pasteAfter":var f="after";d?f="inside":e&&(f="before");
this.$C(a,this.xw,f);this.xw=null}};a.gb.prototype.VB=function(a,b){null!=this.dm&&("paste-before"==b?b="pasteBefore":"paste-after"==b&&(b="pasteAfter"),a.find("[data-oj-command\x3d'"+b+"']").removeClass("oj-disabled"))};a.gb.prototype.zua=function(a,b){var d;a.find("[data-oj-command]").addClass("oj-disabled");d=this.cg(b.originalEvent.target);null==d||null==this.dm||0==this.dm.length?a.ojMenu("refresh"):(d.children().first().hasClass(this.Ga.mg())?null!=this.An&&this.VB(a,"paste"):(this.VB(a,"cut"),
this.VB(a,"copy"),null!=this.An&&(this.VB(a,"paste-before"),this.VB(a,"paste-after"))),a.ojMenu("refresh"),this.xw=d)};a.gb.prototype.mG=function(c){var b,d;if(!this.rq()||null==this.dm||0==this.dm.length)return!1;if(c.ctrlKey||c.metaKey){b=c.keyCode;if(b===a.gb.OO&&-1<this.dm.indexOf("cut"))return this.YC(c),!0;if(b===a.gb.gja&&-1<this.dm.indexOf("copy"))return this.X7(c),!0;if(b===a.gb.MO&&null!=this.An&&(b=g(this.kS()),b.children().first().hasClass(this.Ga.mg())?-1<this.dm.indexOf("paste")&&(d=
"inside"):-1<this.dm.indexOf("paste-before")?d="before":-1<this.dm.indexOf("paste-after")&&(d="after"),null!=d))return this.$C(c,b,d),!0}return!1}});