/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdomscroller","ojs/ojanimation","promise"],function(a,g){a.Pd=function(a,b,d){this.ea=b;this.C=a;this.Bd=!1;this.aia(d);this.Init()};a.b.ta(a.Pd,a.b,"oj.DataSourceContentHandler");a.Pd.prototype.Init=function(){a.Pd.t.Init.call(this)};a.b.g("DataSourceContentHandler.prototype.Init",{Init:a.Pd.prototype.Init});a.Pd.prototype.dx=function(){};a.Pd.prototype.xA=function(){};a.Pd.prototype.Vg=function(){g(this.ea).empty();this.ea=this.C=null};a.Pd.prototype.gx=
function(){return!this.Bd};a.Pd.prototype.wZ=function(){this.Jp()?this.ea.setAttribute("role","tree"):this.ea.setAttribute("role","listbox")};a.Pd.prototype.X_=function(){this.Nb();this.gp(!1);this.wZ();this.Jb()};a.Pd.prototype.ug=function(a){return a.key};a.Pd.prototype.Ne=function(a){var b,d,e;b=g(this.ea).find("."+this.C.rh());for(d=0;d<b.length;d++)if(e=b[d],a==this.ug(e))return e;return null};a.Pd.prototype.Eea=function(){return this.Wa};a.Pd.prototype.aia=function(a){this.Wa=a};a.Pd.prototype.gp=
function(){this.C.IA()};a.Pd.prototype.SW=function(a,b,d,e,f){var h,k;h=document.createElement("li");g(h).uniqueId();k=g(a).children("."+this.C.rh()+", .oj-listview-no-data-message");a.insertBefore(h,b===k.length?null:k[b]);k=g(a).children().index(h);this.S2(h,k,a,b,d,e,f)};a.Pd.prototype.PIa=function(a,b,d,e,f){var h,k;this.Nb();g(a).empty();h=a.parentNode;k=g(h).children().index(a);this.S2(a,k,h,b,d,e,f)};a.Pd.prototype.S2=function(a,b,d,e,f,h,k){var l;void 0==k&&(k=this.cw.bind(this));e=this.jX(e,
f,h,a);h=this.C.fta();null!=h?(h=h.call(this,e),null!=h&&(null===h.parentNode||h.parentNode instanceof DocumentFragment?a.appendChild(h):null==h.parentNode&&h.toString&&(l=document.createElement("span"),l.appendChild(document.createTextNode(h.toString())),a.appendChild(l)))):(l=document.createElement("span"),l.appendChild(document.createTextNode(null==f?"":f.toString())),a.appendChild(l));a=d.children[b];e.parentElement=a;g.data(a,"data",f);k(a,e)};a.Pd.prototype.cw=function(a,b){var d;a.key=b.key;
a=g(a);a.uniqueId();d=this.C.eM(a);d.attr("role",this.Jp()?"treeitem":"option");d!=a&&a.attr("role","presentation");d.addClass(this.C.hp());this.iA(b)||a.addClass("oj-skipfocus");a.addClass(this.C.rh())};a.Pd.prototype.jX=function(a,b,d,e){var f,g;f={};f.parentElement=e;f.index=a;f.data=b;f.component=this.C.Mf();f.datasource=this.Wa;for(g in d)d.hasOwnProperty(g)&&(f[g]=d[g]);return f};a.Pd.prototype.iA=function(a){return this.C.RC("focusable",a,!0)};a.Pd.prototype.zM=function(a){return this.C.RC("selectable",
a,!0)};a.Pd.prototype.Nb=function(){this.C&&this.C.Nb()};a.Pd.prototype.Jb=function(){this.C&&this.C.Jb()};a.Xb=function(c,b,d){a.Xb.t.constructor.call(this,c,b,d)};a.b.ta(a.Xb,a.Pd,"oj.TableDataSourceContentHandler");a.Xb.prototype.Init=function(){a.Xb.t.Init.call(this)};a.Xb.prototype.Jp=function(){return!1};a.Xb.prototype.Vg=function(){a.Xb.t.Vg.call(this);this.YD();null!=this.nA&&(this.nA.destroy(),this.KY=this.nA=null);this.yF=null};a.Xb.prototype.dx=function(a,b){this.Jj()&&void 0!=this.Dt&&
this.Dt!=b&&(this.Dt=b,this.checkViewport())};a.Xb.prototype.xA=function(){this.Jj()&&this.checkViewport()};a.Xb.prototype.Jj=function(){return"loadMoreOnScroll"==this.C.options.scrollPolicy?!0:!1};a.Xb.prototype.wo=function(){return Math.max(0,this.C.options.scrollPolicyOptions.fetchSize)};a.Xb.prototype.YS=function(){var c=this.C.options.scrollPolicyOptions.scroller;return null!=c&&g.contains(c,this.ea)?(this.cv=a.Sf.wEa(c,this.ea),c):this.C.Uk()};a.Xb.prototype.KS=function(){return this.C.options.scrollPolicyOptions.maxCount};
a.Xb.prototype.aia=function(c){var b;this.YD();if(null!=c){this.Jj()&&(b=this,this.KY=function(a){null!=a?(b.Nb(),b.pV(),b.gx()&&b.Nb(),b.GT(a),a.maxCountLimit?b.MT():b.j3(),b.Jb(),b.Jb()):void 0===a&&(b.pV(),b.Jb())},this.nA=new a.Sf(this.YS(),c,{fetchSize:this.wo(),fetchTrigger:this.cv,maxCount:this.KS(),success:this.KY,error:this.Jb}),this.nA.NT=function(c,e){1>=e-c&&b.Nb();a.Sf.prototype.NT.call(this,c,e)});this.Jga=this.$Ga.bind(this);this.Iga=this.ZGa.bind(this);this.Ega=this.VGa.bind(this);
this.Hga=this.XGa.bind(this);this.Fga=this.WGa.bind(this);this.OM=this.YGa.bind(this);if(a.Fa&&c instanceof a.Fa)c.on("sync",this.Jga);c.on("sort",this.Iga);c.on("add",this.Ega);c.on("remove",this.Hga);c.on("change",this.Fga);c.on("reset",this.OM);c.on("refresh",this.OM)}this.Wa=c};a.Xb.prototype.j3=function(){var a,b;null==this.yF&&(a=g(document.createElement("li")),a.uniqueId().attr("role","presentation").addClass(this.C.Vi()),b=g(document.createElement("div")),b.addClass("oj-listview-loading-icon"),
a.append(b),g(this.ea).append(a),this.yF=a)};a.Xb.prototype.pV=function(){null!=this.yF&&this.yF.remove();this.yF=null};a.Xb.prototype.cw=function(c,b){var d;a.Xb.t.cw.call(this,c,b);g(c).addClass(this.C.Vi());this.C.xc()&&this.zM(b)&&this.C.lg(g(c)).attr("aria-selected",!1);this.Jj()&&(d=Math.min(this.Wa.totalSize(),this.KS()),-1===d&&(d=this.KS()),0<d&&g(c).attr("aria-setsize",d).attr("aria-posinset",b.index+1));this.C.uw(c,b)};a.Xb.prototype.WDa=function(c,b){var d,e;this.Nb();this.cw(c,b);d=g(c);
d.outerHeight();e=this.C.Vi();d.children().wrapAll("\x3cdiv\x3e\x3c/div\x3e");d.removeClass(e).addClass("oj-listview-item-add-remove-transition");d.children().first().addClass(e);this.Nb();d=this.C.lt("add");var f=this;a.W.Nn(c,"add",d).then(function(){f.lua(b,c)});this.Jb()};a.Xb.prototype.MT=function(){a.r.error("max count reached")};a.Xb.prototype.YD=function(){null!=this.Wa&&(this.Wa.off("sync",this.Jga),this.Wa.off("sort",this.Iga),this.Wa.off("add",this.Ega),this.Wa.off("remove",this.Hga),this.Wa.off("change",
this.Fga),this.Wa.off("reset",this.OM),this.Wa.off("refresh",this.OM))};a.Xb.prototype.gp=function(c){var b=!0,d;this.Nb();if(this.gx()&&(this.Bd=!0,a.Xb.t.gp.call(this,c),a.Fa&&this.Wa instanceof a.Fa&&(b=!1,this.Nb()),b||c)){b&&this.Nb();c={fetchType:"init",startIndex:0};this.Jj()&&(c.pageSize=this.wo());d=this;c=this.Wa.fetch(c);c.then(function(a){null!=d.C&&b&&(g(d.ea).empty(),d.GT(a),d.Jj()&&null!=a&&a.keys&&0<a.keys.length&&d.j3())},function(a){d.pq(a);d.Jb()});this.Jb();return}this.Jb()};a.Xb.prototype.pq=
function(c){a.r.error(c);this.Jj()&&this.pV();this.C.St()};a.Xb.prototype.Bs=function(a,b){var d,e,f;d=this.ea.childElementCount;for(e=0;e<a.length;e++)f=a[e],this.SW(this.ea,d,f,this.getMetadata(d,b[e],f)),d+=1};a.Xb.prototype.VGa=function(a){var b,d,e;if(null!=this.ea){this.Nb();b=a.data;d=a.keys;a=a.indexes;if(null!=b&&null!=d&&0<d.length&&0<b.length&&d.length==b.length&&null!=a&&d.length==a.length){for(e=0;e<b.length;e++)this.Nb(),this.SW(this.ea,a[e],b[e],this.getMetadata(a[e],d[e],b[e]),this.WDa.bind(this)),
this.Jb();this.gx()&&this.Nb();this.hea()}this.Jb()}};a.Xb.prototype.lua=function(a,b){g(b).removeClass("oj-listview-item-add-remove-transition").addClass(this.C.Vi()).children().children().unwrap();this.C.pga(b,a);this.Jb()};a.Xb.prototype.XGa=function(a){var b,d;a=a.keys;if(null!=this.ea&&null!=a&&0!=a.length){this.Nb();for(b=0;b<a.length;b++)d=this.Ne(a[b]),null!=d&&(this.Nb(),this.tAa(d),this.Jb());this.C.Yw();this.Jb()}};a.Xb.prototype.tAa=function(c){var b,d=this,e;this.Nb();b=this.C.Vi();c=
g(c);c.children().wrapAll("\x3cdiv class\x3d'"+b+"'\x3e\x3c/div\x3e");c.removeClass(b).addClass("oj-listview-item-add-remove-transition");this.Nb();b=this.C.lt("remove");e=c.get(0);a.W.Nn(e,"remove",b).then(function(){d.Uva(c)});this.Jb()};a.Xb.prototype.Uva=function(a){a=g(a);var b=a.parent();this.C.vY(a.get(0));a.remove();0==b.get(0).childElementCount&&this.C.St();this.Jb()};a.Xb.prototype.WGa=function(a){var b,d,e,f;b=a.keys;if(null!=this.ea&&null!=b&&0!=b.length){this.Nb();d=a.data;a=a.indexes;
for(e=0;e<b.length;e++)f=this.Ne(b[e]),null!=f&&(this.Nb(),this.PIa(f,a[e],d[e],this.getMetadata(a[e],b[e],d[e]),this.VDa.bind(this)),this.Jb());this.C.Yw();this.Jb()}};a.Xb.prototype.VDa=function(c,b){var d=this,e;this.Nb();this.cw(c,b);e=this.C.lt("update");a.W.Nn(c,"update",e).then(function(){d.Vva(c)});this.Jb()};a.Xb.prototype.Vva=function(a){g(a).removeClass("oj-listview-item-add-remove-transition");this.C.XIa();this.Jb()};a.Xb.prototype.YGa=function(){null!=this.ea&&(this.Nb(),this.C.Yw(),
this.gp(!0),this.Jb())};a.Xb.prototype.GT=function(a){var b;null!=this.ea&&(b=a.data,a=a.keys,Array.isArray(b)&&Array.isArray(a)&&b.length==a.length&&(this.Bs(b,a),this.hea()))};a.Xb.prototype.$Ga=function(a){null!=this.ea&&(this.Nb(),0===a.startIndex&&g(this.ea).empty(),this.C.Yw(),this.GT(a),this.Jb())};a.Xb.prototype.ZGa=function(){null!=this.ea&&(this.Nb(),this.C.Yw(),this.C.dn()&&this.C.yk(!0),this.gp(!0),this.Jb())};a.Xb.prototype.hea=function(){this.Bd=!1;this.C.St();this.checkViewport();this.Jb()};
a.Xb.prototype.checkViewport=function(){var a=this,b;this.Nb();null!=this.nA&&0<this.Wa.totalSize()&&this.gx()&&(b=this.nA.checkViewport(),null!=b&&(this.Nb(),b.then(function(b){a.KY(b);a.Jb()},null)));this.Jb()};a.Xb.prototype.getMetadata=function(a,b,d){d=d.context;null==d&&(d={});null==d.index&&(d.index=a);null==d.key&&(d.key=b);return d};a.Fi=function(c,b,d){a.Fi.t.constructor.call(this,c,b,d)};a.b.ta(a.Fi,a.Pd,"oj.TreeDataSourceContentHandler");a.Fi.prototype.Init=function(){a.Fi.t.Init.call(this)};
a.Fi.prototype.Jp=function(){return!0};a.Fi.prototype.gp=function(c){this.Nb();a.Fi.t.gp.call(this,c);this.ii(0,null,this.ea,null);this.Jb()};a.Fi.prototype.ii=function(a,b,d,e){this.Nb();this.Bd=!0;a={start:a,count:this.Wa.ph(b)};this.Wa.ii(b,a,{success:function(a){this.Bs(a,b,d,e)}.bind(this),error:function(a){this.pq(a)}.bind(this)});this.Jb()};a.Fi.prototype.Bs=function(a,b,d,e){var f,g,k,l;this.Nb();b=a.getStart();f=a.getCount();for(g=0;g<f;g++)k=a.getData(b+g),l=a.getMetadata(b+g),this.SW(d,
b+g,k,l);this.Bd=!1;null!=e&&e.call(null,d);this.C.St();this.$k=!0;this.Jb()};a.Fi.prototype.cw=function(c,b){var d,e,f,h,k,l;this.Nb();a.Fi.t.cw.call(this,c,b);d=this.C.li();e=this.C.Vi();f=this.C.mg();h=this.C.kw();l=this.C.vn();k=this.C.hp();c=g(c);!1==b.leaf?(c.children().wrapAll("\x3cdiv\x3e\x3c/div\x3e"),c.hasClass(k)?c.removeClass(k).children().first().addClass(k).attr("aria-expanded","false"):c.children().first().attr("role","presentation").find("."+k).attr("aria-expanded","false"),e=c.children().first(),
e.uniqueId().addClass(f),this.C.hA()&&(c.addClass("oj-collapsed"),f=document.createElement("a"),g(f).attr("href","#").attr("aria-labelledby",e.get(0).id).addClass("oj-component-icon oj-clickable-icon-nocontext").addClass(l),e.prepend(f)),l=document.createElement("ul"),g(l).addClass(d).addClass(h).attr("role","group"),c.append(l)):!0==b.leaf&&c.addClass(e);this.C.xc()&&this.zM(b)&&this.C.lg(c).attr("aria-selected",!1);this.C.uw(c[0],b);this.Jb()};a.Fi.prototype.pq=function(c){this.Nb();a.r.error(c);
this.C.St();this.Jb()};a.Fi.prototype.bx=function(a,b){var d,e;this.Nb();d=this.ug(a[0]);e=a.children("ul")[0];this.ii(0,d,e,b);this.Jb()};a.Fi.prototype.Zw=function(a){a.empty()};a.pe=function(a,b){this.C=a;this.ea=b};a.b.ta(a.pe,a.b,"oj.StaticContentHandler");a.pe.prototype.Init=function(){a.pe.t.Init.call(this)};a.pe.prototype.Vg=function(){this.Tha(this.ea,0);this.LJa()};a.pe.prototype.gx=function(){return!0};a.pe.prototype.dx=function(){};a.pe.prototype.xA=function(){};a.pe.prototype.X_=function(){this.aha(this.ea,
0);this.wZ();this.C.St()};a.pe.prototype.bx=function(a,b){var d;d="."+this.C.li();d=g(a).children(d)[0];g(d).css("display","block");b.call(null,d)};a.pe.prototype.Zw=function(){};a.pe.prototype.Jp=function(){null==this.PY&&(this.PY=0<g(this.ea).children("li").children("ul").length);return this.PY};a.pe.prototype.Tha=function(a,b){var d,e,f,h,k,l,m,s,t,r;d=this.C.li();e=this.C.kw();f=this.C.Tz();h=this.C.mg();k=this.C.Vi();l=this.C.rh();m=a.children;for(s=0;s<m.length;s++)t=m[s],this.KJa(t),t=g(t),
t.removeClass(l).removeClass(k).removeClass(this.C.LX(b)).removeClass("oj-skipfocus").removeClass("oj-focus").removeClass("oj-hover").removeClass("oj-expanded").removeClass("oj-collapsed").removeClass("oj-selected"),r=t.children("ul"),0<r.length&&(t.children("."+h).children().unwrap(),t.children(".oj-component-icon").remove(),t=g(r[0]),t.removeClass(d).removeClass(f).removeClass(e).removeAttr("role"),this.Tha(t[0],b+1))};a.pe.prototype.aha=function(a,b){var d,e,f,h,k,l,m,s,t,r,n,p,q,u,v;d=this.C.Vi();
e=this.C.rh();f=this.C.li();h=this.C.mg();k=this.C.kw();l=this.C.vn();m=this.C.hp();s=a.children;t=this.C.hA();for(r=0;r<s.length;r++)n=g(s[r]),p=this.jX(n),this.eJa(n),n.uniqueId().addClass(e),0<b&&n.addClass(this.C.LX(b)),this.iA(p)||n.addClass("oj-skipfocus"),q=n.children("ul"),0<q.length?(this.PY=!0,n.children(":not(ul)").wrapAll("\x3cdiv\x3e\x3c/div\x3e"),u=n.children().first(),u.addClass(h),this.pHa(q[0])&&(n.hasClass(m)?(n.removeClass(m),u.addClass(m).attr("aria-expanded","false")):(u.attr("role",
"presentation"),u.find("."+m).attr("aria-expanded","false")),t&&(n.addClass("oj-collapsed"),u.uniqueId(),v=document.createElement("a"),g(v).attr("href","#").attr("role","button").attr("aria-labelledby",u.get(0).id).addClass("oj-component-icon oj-clickable-icon-nocontext").addClass(l),u.prepend(v))),q=g(q[0]),q.addClass(f).addClass(k).attr("role","group").css("display","none"),this.aha(q[0],b+1)):n.addClass(d),this.C.xc()&&this.zM(p)&&this.C.lg(n).attr("aria-selected",!1),this.C.uw(n[0],p)};a.pe.prototype.wZ=
function(){this.Jp()?this.ea.setAttribute("role","tree"):this.ea.setAttribute("role","listbox")};a.pe.prototype.LJa=function(){this.ea.removeAttribute("role")};a.pe.prototype.pHa=function(a){return 0<g(a).children("li").length};a.pe.prototype.jX=function(a){var b;b={};b.key=a.attr("id");b.parentElement=a.children().first()[0];b.index=a.index();b.data=a[0];b.component=this.C.Mf();this.Jp()&&(b.leaf=0==a.children("ul").length,a=a.parents("li."+this.C.rh()),b.depth=a.length,b.parentKey=0==a.length?null:
a.first().attr("id"));return b};a.pe.prototype.eJa=function(a){var b=this.C.eM(a);b.attr("role",this.Jp()?"treeitem":"option");b!=a&&a.attr("role","presentation");b.addClass(this.C.hp())};a.pe.prototype.KJa=function(a){a=this.C.eM(g(a));a.removeAttr("role");a.removeAttr("aria-selected");a.removeAttr("aria-expanded");a.removeClass(this.C.hp())};a.pe.prototype.ug=function(a){return g(a).attr("id")};a.pe.prototype.Ne=function(a){return document.getElementById(a)};a.pe.prototype.iA=function(a){return this.C.RC("focusable",
a,!0)};a.pe.prototype.zM=function(a){return this.C.RC("selectable",a,!0)};a.SU=function(c,b){function d(){}a.b.ta(d,c,"");d.prototype=g.extend(d.prototype,b);return d}(Object,{wg:37,dh:39,cl:40,ll:38,HO:9,VN:13,XN:27,YN:113,zO:32,Cm:0,Bm:1,Z_:2,TJa:0,iu:1,Yq:function(c){var b=this,d;this.Rt=[];this.Nb();this.Y=c.Y;this.element=c.element;this.oe=c.oe;this.options=c;this.element.uniqueId().addClass(this.eO()+" oj-component-initnode");this.h0();"undefined"!=typeof a.gb&&(this.oi=d=new a.gb(this),this.Y._on(this.element,
{dragstart:function(a){return d.BT(a)},dragenter:function(a){return d.yT(a)},dragover:function(a){return d.AT(a)},dragleave:function(a){return d.zT(a)},dragend:function(a){return d.xT(a)},drag:function(a){return d.Iua(a)},drop:function(a){return d.CT(a)}}));this.Y._on(this.element,{click:function(a){b.jO(a)},touchstart:function(a){b.nG(a)},touchend:function(a){b.XA(a)},touchcancel:function(a){b.XA(a)},mousedown:function(a){0!==a.button||b.RD()||b.nG(a)},mouseup:function(a){b.n8(a);b.VY=!1},mouseout:function(a){b.l8(a)},
mouseover:function(a){b.Lva(a)},keydown:function(a){b.mG(a)},focus:function(a){b.iO(a)},blur:function(a){b.hO(a)},ojpanmove:function(a){b.n8(a)}});a.Za.Rz().browser===a.Za.rm.m_&&this.Y._on(this.Ve(),{focus:function(){b.element.focus()}});this.iu===this.iu?this.Y._on(this.element,{focusin:function(a){b.iO(a)},focusout:function(a){b.Cja(a)}}):this.Y._on(this.element,{focus:function(a){b.iO(a)},blur:function(a){b.hO(a)}});this.Y.document.bind("touchend.ojlistview touchcancel.ojlistview",this.XA.bind(this));
this.saa();this.Y._focusable({applyHighlight:b.i0(),recentPointer:b.W_(),setupHandlers:function(a,c){b.qy=a;b.dv=c}})},Cz:function(){var a;this.Foa();this.Yr();this.R8();a=this.Ve();this.jn(a[0]);this.Jb()},refresh:function(){this.Oaa();this.Nb();this.iB();this.Yr();this.R8();this.saa();this.Jb()},whenReady:function(){return this.Cha},destroy:function(){this.element.removeClass(this.eO()+" oj-component-initnode");this.Vo(this.Ve());this.Oaa();a.u.unwrap(this.element,this.Ve());this.Y.document.off(".ojlistview")},
Oaa:function(){var a=this;this.JO();this.dpa(this.element);null!=this.qf&&(this.qf.Vg(),delete this.qf,this.qf=null);this.N=null;this.Rt=[];this.Cha=new Promise(function(b){a.Dha=b});this.Yw()},jha:function(){this.Ve().removeClass("oj-focus-ancestor");null!=this.N&&g(this.N.elem).removeClass("oj-focus oj-focus-highlight");null!=this.QY&&this.Cq(this.QY,"oj-hover")},xA:function(){null!=this.qf&&this.qf.xA()},getNodeBySubId:function(a){var b;if(null==a)return this.element?this.element[0]:null;b=a.subId;
if("oj-listview-disclosure"===b||"oj-listview-icon"===b)if(a=a.key,a=this.Ne(a),null!=a&&a.firstElementChild&&(a=a.firstElementChild.firstElementChild,null!=a&&(g(a).hasClass(this.Rq())||g(a).hasClass(this.vn()))))return a;return null},getSubIdByNode:function(a){if(null!=a&&g(a).hasClass(this.Rq())||g(a).hasClass(this.vn()))if(a=this.xm(a),null!=a&&0<a.length&&(a=this.ug(a[0]),null!=a))return{subId:"oj-listview-disclosure",key:a};return null},getContextByNode:function(a){var b,d,e;a=this.xm(a);return null!=
a&&0<a.length&&(b=this.ug(a[0]),null!=b)?(d=a.parent(),e=d.children("li").index(a),b={subId:"oj-listview-item",key:b,index:e},d.get(0)!=this.element.get(0)&&(b.parent=d.parent().get(0)),a.children().first().hasClass(this.mg())?b.group=!0:b.group=!1,b):null},getDataForVisibleItem:function(a){var b;b=a.index;a=a.parent;a=null==a?this.element.get(0):g(a).children("ul."+this.li()).first();b=g(a).children("li").get(b);return null!=b&&g(b).hasClass(this.Vi())?this.z6(b):null},z6:function(a){return null==
this.me("data")?a:g.data(a,"data")},Yr:function(a){null!=this.oi&&this.oi.SDa(a)},Vo:function(c){c&&this.Jg&&a.u.lm(c,this.Jg)},jn:function(c){c&&(null==this.Jg&&(this.Jg=this.Hg.bind(this)),a.u.Mk(c,this.Jg))},Hg:function(a,b){0<a&&0<b&&null!=this.qf&&this.qf.dx(a,b)},i0:function(){return!1},W_:function(){return function(){return!1}},j0:function(a){return null!=a.data||null!=a.drillMode||null!=a.groupHeaderPosition||null!=a.item||null!=a.scrollPolicy||null!=a.scrollPolicyOptions},Pw:function(a){var b,
d;if(this.j0(a))return null!=a.data&&(null==a.currentItem&&this.ik("currentItem",null),null==a.selection&&this.yk(!0)),!0;if(null!=a.expanded&&this.qf.Jp()&&(d=a.expanded,Array.isArray(d))){this.Nb();this.wpa();this.J8=!0;try{b=this,g.each(d,function(a,c){b.tX(c,!0,!0,!0)})}finally{this.J8=void 0,this.Jb()}}null!=a.currentItem?(d=this.Ne(a.currentItem),null!=d&&(d=g(d),this.lk(d)||this.Xr(d,null))):null===a.currentItem&&(this.wG(),this.N=null,this.h0());this.kO(a);null!=a.selectionMode&&(this.yk(!0),
this.iB());null!=a.contextMenu&&this.Yr(a.contextMenu);return!1},kO:function(a){var b,d;if(null!=a.selection&&this.xc())for(a.selection=this.Yra(a.selection),b=a.selection,this.yk(!1),d=0;d<b.length;d++)a=this.Ne(b[d]),null!=a&&this.XB(a,b[d])},mk:function(a,b,d){return this.Y._trigger(a,b,d)},ik:function(a,b,d){this.Y.option(a,b,d)},me:function(a){return this.Y.option(a)},Nb:function(){var a=this;this.Rt&&(0==this.Rt.length&&(this.Cha=new Promise(function(b){a.Dha=b})),this.Rt.push(1))},Jb:function(){this.Rt&&
0<this.Rt.length&&(this.Rt.pop(),0==this.Rt.length&&this.Dha(null))},TFa:function(a){var b,d=this,e=[];g.each(a,function(a,c){b=d.Ne(c);null!=b&&e.push(b)});return e},R8:function(){var c;this.Nb();c=this.me("data");if(null!=c){if("undefined"===typeof a.aa||"undefined"===typeof a.tu)throw"oj.TableDataSource or oj.TreeDataSource not found. Ensure the required modules are imported";if(c instanceof a.aa)this.qf=new a.Xb(this,this.element[0],c);else if(c instanceof a.tu)this.qf=new a.Fi(this,this.element[0],
c);else throw"Invalid data";}else this.qf=new a.pe(this,this.element[0]);this.IA();this.qf.X_();this.Jb()},kka:function(a){this.element.attr("aria-activedescendant",a.attr("id"))},iB:function(){this.element.attr("aria-activedescendant","");this.dn()?this.element.attr("aria-multiselectable",!0):this.xc()&&this.element.attr("aria-multiselectable",!1)},JO:function(){this.element.removeAttr("aria-activedescendant").removeAttr("aria-multiselectable")},Foa:function(){var a,b;a=this.Ve();this.iB();b=this.Ioa();
a.append(b);this.gm=b;b=this.zoa();a.append(b);this.jA=b;this.Jl()&&a.append(this.Aoa())},Ioa:function(){var a=g(document.createElement("div"));a.addClass("oj-listview-status-message oj-listview-status").attr({id:this.Yu("status"),role:"status"});return a},zoa:function(){var a=g(document.createElement("div"));a.addClass("oj-helper-hidden-accessible").attr({id:this.Yu("info"),role:"status"});return a},Aoa:function(){var a=g(document.createElement("div"));a.addClass("oj-helper-hidden-accessible").attr({id:this.Yu("instr")});
a.text(this.Y.F("accessibleReorderTouchInstructionText"));return a},Kg:function(a){""!=a&&this.jA.text()!=a&&this.jA.text(a)},IA:function(){var a=this.Y.F("msgFetchingData");this.gm.text(a).css("left",this.element.outerWidth()/2-this.gm.outerWidth()/2).show()},Xq:function(){this.gm.hide()},Uk:function(){return this.Ve()},Ve:function(){null==this.mF&&(this.mF=this.fqa());return this.mF},fqa:function(){var a;this.oe?a=g(this.oe):(a=g(document.createElement("div")),this.element.parent()[0].replaceChild(a[0],
this.element[0]));a.addClass(this.r_()).addClass("oj-component");a.prepend(this.element);return a},Vsa:function(){return this.Y.F("msgNoData")},GH:function(){var a,b;a=this.Vsa();b=document.createElement("li");b.id=this.Yu("empty");b.className="oj-listview-no-data-message oj-listview-empty-text";b.textContent=a;return b},Zg:function(a){a=this.lg(a).attr("aria-expanded");return"true"==a?this.Cm:"false"==a?this.Bm:this.Z_},su:function(a,b){var d=this.hA();b==this.Cm?(this.lg(a).attr("aria-expanded",
"true"),d&&a.removeClass("oj-collapsed").addClass("oj-expanded")):b==this.Bm&&(this.lg(a).attr("aria-expanded","false"),d&&a.removeClass("oj-expanded").addClass("oj-collapsed"))},RC:function(a,b,d){a=this.options.item[a];return"function"==typeof a&&d?a.call(this,b):a},fta:function(){var a=this.RC("renderer",null,!1);return"function"!=typeof a?null:a},pga:function(){},vY:function(a){var b;null!=this.N&&this.N.elem&&g(this.N.elem).get(0)==a&&this.ik("currentItem",null);if(null!=a&&a.id&&null!=this.wp)for(b in this.wp)if(this.wp.hasOwnProperty(b)&&
this.wp[b]===a.id){delete this.wp[b];break}},uw:function(a,b){var d,e,f,h;null!=this.oi&&this.oi.uw(a);this.IR(a);if(this.xc())if(d=this.me("selection"),this.ek(a))for(f=0;f<d.length;f++){if(d[f]==b.key&&(this.XB(a,d[f]),!this.dn())){1<d.length&&(e=g(this.Ne(b.key)),this.ik("selection",[b.key],{_context:{originalEvent:null,ob:!0,Ok:{items:e}},changed:!0}));break}}else if(f=d.indexOf(b.key),-1<f){d=d.slice(0);d.splice(f,1);e=Array(d.length);for(f=0;f<d.length;f++)e[f]=this.Ne(d[f]);this.ik("selection",
d,{_context:{originalEvent:null,ob:!0,Ok:{items:g(e)}},changed:!0})}this.qf.Jp()&&void 0==this.J8&&this.Zg(g(a))==this.Bm&&(f=this.me("expanded"),this.My()?this.gu(g(a),null,!1,null,!1,!1,!1):Array.isArray(f)&&(h=this,g.each(f,function(d,e){e==b.key&&h.gu(g(a),null,!1,null,!1,!1,!1)})));null!=this.N&&b.key==this.N.key&&null!=this.N.elem&&a!=this.N.elem.get(0)&&(this.N.elem=g(a))},St:function(){var a;this.Xq();g(document.getElementById(this.Yu("empty"))).remove();0==this.element[0].childElementCount?
(a=this.GH(),this.element.append(a)):(this.qA=null,a=this.me("currentItem"),null!=a&&(a=this.Ne(a),null==a?this.ik("currentItem",null):null!=this.N||this.lk(g(a))||this.Xr(g(a),null)),this.Ve().hasClass("oj-focus-ancestor")&&null==this.N&&this.W8());this.mk("ready",null,{})},XIa:function(){var a=this.me("currentItem");null!=a&&(a=this.Ne(a),null==a||this.lk(g(a))||this.Xr(g(a),null))},Yw:function(){this.OY=this.qA=null},iha:function(a,b,d){var e;if(this.oG(g(b.target)))return!1;e=g(b.target).closest("."+
this.rh());0<e.length&&!this.lk(g(e[0]))&&this.Xr(g(e[0]),null);e=this.element;null!=this.N&&(e=this.N.elem);e={launcher:e,initialFocus:"menu"};"keyboard"===d&&(e.position={my:"start top",at:"start bottom",of:this.N.elem});null!=this.oi&&this.oi.zua(g(a.element),b);this.Y.jh(b,d,e)},z_:function(a){return null!=a.prop("nodeName").match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)},oG:function(a){for(;null!=a&&a[0]!=this.element[0]&&"LI"!=a.prop("nodeName");){if(3!=a[0].nodeType){var b=a.attr("tabIndex"),
d=a.attr("data-oj-tabindex");if(null!=b&&0<=b&&!a.hasClass(this.hp())||this.z_(a)&&(-1!=b||-1!=d))return!0}a=a.parent()}return!1},IR:function(a){var b;a=g(a);a.hasClass(this.Vi())||(a=g(a.get(0).firstElementChild));a.find("a, input, select, textarea, button, object, .oj-component-initnode").each(function(){g(this).removeAttr("data-first").removeAttr("data-last");b=parseInt(g(this).attr("tabIndex"),10);(isNaN(b)||0<=b)&&g(this).attr("tabIndex",-1).attr("data-tabmod",isNaN(b)?-1:b)})},Dra:function(a){var b;
a=g(a).find("[data-tabmod]").each(function(){b=parseInt(g(this).attr("data-tabmod"),10);g(this).removeAttr("data-tabmod");-1==b?g(this).removeAttr("tabIndex"):g(this).attr("tabIndex",b)});a.first().attr("data-first","true");a.last().attr("data-last","true")},dpa:function(a){g(a).find("[data-tabmod]").removeAttr("tabIndex").removeAttr("data-tabmod").removeAttr("data-first").removeAttr("data-last")},lk:function(a){return a.hasClass("oj-skipfocus")},iO:function(a){this.Ve().addClass("oj-focus-ancestor");
null==this.N?this.VY||this.W8(a):this.VY||this.YA()},W8:function(a){var b,d,e;if(!this.Jl())for(b=this.SC(),d=0;d<b.length;d++)if(e=g(b[d]),!this.lk(e)){this.Xr(e,a);break}},Cja:function(a){this.hO(a)},hO:function(a){null!=a.relatedTarget&&g.contains(this.element.get(0),a.relatedTarget)||(this.Ve().removeClass("oj-focus-ancestor"),this.wG())},l8:function(a){a=this.xm(a.target);null!=a&&(this.QY=null,this.Cq(a,"oj-hover"))},Lva:function(a){this.RD()||(a=this.xm(a.target),null==a||this.lk(a)||(this.QY=
a,this.yJ(a,"oj-hover")))},RD:function(){return 500>Date.now()-this.DU},mG:function(a){var b,d;if(this.hA()&&(b=a.keyCode,b===this.wg||b===this.dh))if(d=this.N.elem,b===this.wg){if(this.Zg(d)==this.Cm){this.Cr(d,a,!0,this.N.key,!0,!0);return}}else if(this.Zg(d)==this.Bm){this.gu(d,a,!0,this.N.key,!0,!0,!0);return}b=this.x_(a);null!=this.oi&&(b=b||this.oi.mG(a));!0===b&&a.preventDefault()},n8:function(a){this.rA&&this.Cq(this.rA,"oj-focus");null!=this.oi&&this.oi.Qca(g(a.target))},nG:function(a){var b,
d;this.VY=!0;d=g(a.target);null!=this.oi&&this.oi.wba(d);b=this.cg(d);null==b||0==b.length||this.lk(b)||d.hasClass("oj-listview-drag-handle")||(this.Ve().hasClass("oj-focus-ancestor")||this.Ve().addClass("oj-focus-ancestor"),this.rA=b,this.yJ(b,"oj-focus"),a.originalEvent.touches&&0<a.originalEvent.touches.length&&(this.bN={x:a.originalEvent.changedTouches[0].pageX,y:a.originalEvent.changedTouches[0].pageY}))},XA:function(c){var b,d;null!=this.rA&&(this.Cq(this.rA,"oj-focus"),null!=this.bN&&(b=this.rA.offset(),
d=this.lt("pointerUp"),d.offsetX=this.bN.x-b.left+"px",d.offsetY=this.bN.y-b.top+"px",b=this.rA.get(0),a.W.Nn(b,"pointerUp",d),this.bN=null));this.DU=Date.now();this.l8(c)},jO:function(a){var b,d,e,f;0===a.button&&(b=this.vn(),d=this.Rq(),e=this.mg(),f=g(a.target),f.hasClass(d)?(this.oo(a),a.preventDefault()):f.hasClass(b)?(this.bg(a),a.preventDefault()):(this.k9()&&null!=this.N&&(this.FV(!1),this.IR(this.N.elem)),b=this.cg(f),null==b||0==b.length||this.lk(b)||(this.Ve().hasClass("oj-focus-ancestor")||
this.Ve().addClass("oj-focus-ancestor"),this.xc()&&this.ek(b[0])?this.Jl()?this.kwa(b,a):this.Bja(b,a):this.lG(b,a),this.hA()&&f.closest("."+e)&&(this.Zg(b)==this.Bm?this.bg(a):this.Zg(b)==this.Cm&&this.oo(a)))))},Jl:function(){return a.u.af()},vR:function(c){return a.u.$q(c)},Yu:function(a){return[this.element.attr("id"),a].join(":")},xm:function(a){return g(a).closest("."+this.rh())},nxa:function(a){return a.hasClass("oj-clickthrough-disabled")||a.hasClass("oj-component-initnode")||a.hasClass("oj-component")},
cg:function(a){for(;0<a.length&&!this.nxa(a);){if(a.hasClass(this.rh()))return a;a=a.parent()}return null},lta:function(){null==this.Aga&&(this.Aga=parseInt(this.Ve().css("border-top-width"),10)+parseInt(this.Ve().css("border-bottom-width"),10));return this.Aga},iba:function(a){var b,d,e,f,h,k,l=0;b=a.offsetTop;d=a.offsetHeight;a=this.Ve()[0];e=a.scrollTop;f=a.offsetHeight;null!=this.Qg&&(h=parseInt(this.Qg.style.top,10),k=g(this.Qg).outerHeight(),b<=h&&h<b+d?l=(d+b-h)/2:b>=h&&b<h+k&&(l=(h+k-b)/2));
b>=e&&b+d<=e+f?0<l&&(a.scrollTop=e-l):(b=Math.max(0,Math.min(b-l,Math.abs(b+d-f))),b>e&&(b+=this.lta()),a.scrollTop=b)},ug:function(a){return this.qf.ug(a)},Ne:function(a){var b;return null!=this.wp&&(b=this.wp[a],null!=b)?document.getElementById(b):this.qf.Ne(a)},ex:function(a){return a==this.ll||a==this.cl},SC:function(){var a,b,d;null==this.qA&&(a=this.kw(),b="."+this.rh()+":visible",this.qA=this.element.find(b).filter(function(){return(d=g(this).parent().hasClass(a))?!g(this).parent().parent().hasClass("oj-collapsed"):
!0}));return this.qA},mu:function(a,b,d){var e,f,h;if(!this.qf.gx())return!0;e=!b||this.QM?this.N.elem:this.Zd;f=!1;h=this.SC();e=h.index(e);switch(a){case this.ll:e--;if(0<=e){for(a=g(h[e]);this.lk(a);){e--;if(0>e)return!1;a=g(h[e])}b?(this.XR(a,d),this.QM=!1):(this.Xr(a,d),this.QM=!0)}f=!0;break;case this.cl:e++;if(e<h.length){for(a=g(h[e]);this.lk(a);){e++;if(e==h.length)return!1;a=g(h[e])}b?(this.XR(a,d),this.QM=!1):(this.Xr(a,d),this.QM=!0)}f=!0}return f},k9:function(){return"actionable"==this.YHa},
FV:function(a){this.YHa=a?"actionable":"navigation";a||this.element[0].focus()},UJa:function(){return this.iu},lg:function(a){return a.hasClass(this.hp())?a:g(a.find("."+this.hp()).first())},h0:function(){this.element.attr("tabIndex",0)},Yja:function(){this.element.removeAttr("tabIndex")},Nba:function(a){this.lg(a).attr("tabIndex",0)},QAa:function(a){var b;b=!0;"presentation"===a.attr("role")&&(b=!1);a=this.lg(a);b?a.removeAttr("tabIndex"):a.attr("tabIndex",-1)},e6:function(a,b){this.iu===this.iu?
(null!=a&&this.QAa(a),this.Nba(b),this.Yja()):this.kka(b)},eM:function(a){var b;b=a.children("a, input, select, textarea, button");return 1===b.length&&0===b.first().find("a, input, select, textarea, button").length?b.first():a},Kc:function(a,b){var d,e,f;null!=a?(d=a[0],d=this.ug(d),null==this.N||d!=this.N.key?(e={key:d,item:a},null!=this.N&&(e.previousKey=this.N.key,e.previousItem=this.N.elem,null!=this.oi&&this.Jl()&&this.oi.Qca(e.previousItem)),f=!this.mk("beforeCurrentItem",b,e),f||(this.N=f=
{key:d,elem:a},null!=this.oi&&this.Jl()&&this.oi.wba(a),this.e6(e.previousItem,a),this.ik("currentItem",d,{_context:{originalEvent:b,ob:!0,Ok:{item:a}},changed:!0}))):d==this.N.key&&(this.N=f={key:d,elem:a},this.e6(null,a))):this.N=null},YA:function(a){var b,d;null!=this.N&&this.Ve().hasClass("oj-focus-ancestor")&&(a=a||!1,b=this.N.elem,this.yJ(b,"oj-focus"),this.iu===this.iu&&(b=this.lg(b),d=document.activeElement,!a&&b.get(0).contains(d)||b.get(0).focus()))},wG:function(){null!=this.N&&this.Cq(this.N.elem,
"oj-focus")},lG:function(a,b){this.Xr(a,b)},Xr:function(a,b){this.iba(a[0]);this.wG();this.Kc(a,b);this.YA()},xc:function(){return"none"!=this.me("selectionMode")},dn:function(){return"multiple"==this.me("selectionMode")},ek:function(a){a=this.lg(g(a)).get(0);return a.hasAttribute("aria-selected")},Yra:function(a){var b,d,e;b=[];for(d=0;d<a.length&&(e=this.Ne(a[d]),null==e||!this.ek(e)||(b.push(a[d]),this.dn()));d++);return b},lDa:function(){var a,b;null!=this.wp&&(a=this,g.each(this.me("selection"),
function(d,e){b=a.Ne(e);null!=b&&a.Cq(b,"oj-selected")}))},yJ:function(a,b){this.ZA(a,b,!0)},Cq:function(a,b){this.ZA(a,b,!1)},ZA:function(a,b,d){var e;a=g(a);"oj-selected"==b&&this.lg(a).attr("aria-selected",d?"true":"false");e=a.children("."+this.mg());0<e.length&&(a=g(e[0]));"oj-focus"===b?d?this.qy(a):this.dv(a):d?a.addClass(b):a.removeClass(b)},Bja:function(a,b){var d,e;this.iba(a[0]);d=this.vR(b);e=b.shiftKey;this.dn()?d||e?!d&&e?this.XR(a,b):this.tQ(a,b):this.hB(a,b):this.hB(a,b)},kwa:function(a,
b){this.dn()?this.tQ(a,b):this.hB(a,b)},yk:function(a){this.lDa();a&&this.ik("selection",[],{_context:{originalEvent:null,ob:!0,Ok:{items:g()}},changed:!0});this.Zd=null},hB:function(a,b){this.yk(!1);this.tQ(a,b,[])},XR:function(a,b){var d;null!=this.N&&(d=this.Zd,d!=a&&(this.Cq(a,"oj-focus"),this.I5(this.N.elem,a,b)))},I5:function(a,b,d){this.yk(!1);this.Zd=b;this.zwa(a,b,d);this.YA()},zwa:function(a,b,d){var e,f,h,k,l;e=[];f=[];h=this.SC();a=h.index(a);k=h.index(b);a>k?b=k:(b=a,a=k);for(;b<=a;b++)k=
h[b],this.ek(k)&&(l=this.qf.ug(k),this.XB(k,l),e.push(l),f.push(k));this.ik("selection",e,{_context:{originalEvent:d,ob:!0,Ok:{items:g(f)}},changed:!0})},XB:function(a,b){null==this.wp&&(this.wp={});this.wp[b]=g(a).attr("id");this.yJ(a,"oj-selected")},tQ:function(a,b,d){var e,f;e=this.ug(a[0]);void 0==d&&(d=this.me("selection").slice(0));this.wG();this.Kc(a,b);this.YA();if(null==this.N||this.N.elem.get(0)!=a.get(0))null!=d&&0==d.length&&this.ik("selection",d,{_context:{originalEvent:b,ob:!0,Ok:{items:g([])}},
changed:!0});else{f=d.indexOf(e);-1<f?(this.Cq(a,"oj-selected"),d.splice(f,1)):(this.Zd=a,this.XB(a,e),d.push(e));a=Array(d.length);for(e=0;e<d.length;e++)a[e]=this.Ne(d[e]);this.ik("selection",d,{_context:{originalEvent:b,ob:!0,Ok:{items:g(a)}},changed:!0})}},vG:function(a,b,d){var e,f,h,k;e=this.me("selection").slice(0);f=this.N.elem;h=this.N.key;k=e.indexOf(h);if(-1<k){if(d)return;this.Cq(f,"oj-selected");e.splice(k,1);0==e.length&&(this.Zd=null)}else this.ek(f[0])&&(b||(this.yk(!1),e.length=0),
this.Zd=f,this.XB(f,h),e.push(h));b=Array(e.length);for(d=0;d<e.length;d++)b[d]=this.Ne(e[d]);this.ik("selection",e,{_context:{originalEvent:a,ob:!0,Ok:{items:g(b)}},changed:!0})},x_:function(a){var b,d,e,f=!1;if(null==this.N)return!1;b=a.keyCode;d=this.N.elem;this.k9()?b==this.XN?(this.FV(!1),this.IR(d),this.YA(!0),this.Nba(d),f=!0):b===this.HO&&(b=d.find("[data-first]"),d=d.find("[data-last]"),a.shiftKey?0<b.length&&0<d.length&&b!=d&&a.target==b[0]&&(d[0].focus(),f=!0):0<b.length&&0<d.length&&b!=
d&&a.target==d[0]&&(b[0].focus(),f=!0)):b==this.YN?(this.Dra(d),b=d.find("[data-first]"),0<b.length&&(b[0].focus(),this.FV(!0))):b==this.zO&&this.xc()?(d=this.vR(a),(e=a.shiftKey)&&!d&&null!=this.Zd&&this.dn()?this.I5(this.Zd,this.N.elem,a):this.vG(a,d&&!e&&this.dn(),!1),f=!0):b==this.VN&&this.xc()?this.vG(a,!1,!0):this.ex(b)&&(d=this.vR(a),e=a.shiftKey,d||(f=this.mu(b,e&&this.xc()&&this.dn(),a)));return f},lt:function(c){var b;null==this.$da&&(b=a.nd.uf("oj-listview-option-defaults"),this.$da=b.animation);
return this.$da[c]},hA:function(){return"none"!=this.me("drillMode")},My:function(){var a=this.me("expanded");if("auto"===a){if(!this.hA())return!0}else if("all"===a)return!0;return!1},tX:function(a,b,d,e){var f=this.Ne(a);null!=f&&this.gu(g(f),null,!1,a,b,e,d)},bg:function(a){var b=this.xm(a.target);null!=b&&0<b.length&&this.gu(b,a,!0,null,!0,!0,!0)},gu:function(a,b,d,e,f,g,k){var l;if(this.Zg(a)==this.Bm){null==e&&(e=this.ug(a[0]));l={item:a,key:e};if(k&&(e=!this.mk("beforeExpand",b,l))&&f)return;
this.Nb();this.qf.bx(a,function(a){this.Nra(a,d,b,l,g)}.bind(this));this.qA=null;null!=b&&b.stopPropagation();this.Jb()}},Nra:function(a,b,d,e,f){var h,k,l=this;this.Nb();b=this.ON(g(a),b,d);a=a.parentNode;a=g(a);this.su(a,this.Cm);h=this.vn();k=this.Rq();a.children("."+this.mg()).find("."+h).removeClass(h).addClass(k);f&&b.then(function(){l.mk("expand",d,e)});this.Jb()},b3:function(a,b){var d;a.parentsUntil("ul.oj-component-initnode","ul."+this.li()).each(function(){d=parseInt(g(this).css("maxHeight"),
10);0<d&&g(this).css("maxHeight",d+b+"px")})},ON:function(c,b){var d=0,e,f,h=this,k,l;e=new Promise(function(a){f=a});b?(this.Nb(),c.children().each(function(){d+=g(this).outerHeight(!0)}),this.Jl()&&this.b3(c,d),c.css("maxHeight",d+"px"),k=this.lt("expand"),this.Nb(),l=c.get(0),k=a.W.Nn(l,"expand",k),k.then(function(){h.Qua(c,f)}),this.Jb()):(this.Jl()?(c.children().each(function(){d+=g(this).outerHeight(!0)}),c.css("maxHeight",d+"px"),this.b3(c,d)):c.css("maxHeight",""),this.PN(c),f(null));return e},
Qua:function(a,b){this.Jl()||a.css("maxHeight","");this.PN(a);b(null);this.Jb()},PN:function(a){a.removeClass(this.kw()).addClass(this.Tz())},Eda:function(a,b,d){var e=this.Ne(a);null!=e&&this.Cr(g(e),null,!1,a,b,d)},oo:function(a){var b=this.xm(a.target);null!=b&&0<b.length&&this.Cr(b,a,!0,null,!0,!0)},Cr:function(a,b,d,e,f,g){var k,l=this;this.Zg(a)==this.Cm&&(null==e&&(e=this.ug(a[0])),k={item:a,key:e},e=!this.mk("beforeCollapse",b,k),e&&f||(this.Nb(),e=this.MN(a,d,b),this.su(a,this.Bm),d=this.vn(),
f=this.Rq(),a.find("."+f).first().removeClass(f).addClass(d),this.qA=null,null!=b&&b.stopPropagation(),g&&e.then(function(){l.mk("collapse",b,k)}),this.Jb()))},MN:function(c,b){var d=0,e,f,h,k=this,l,m;f=new Promise(function(a){h=a});e=c.children("ul").first();b?(this.Nb(),e.children().each(function(){d+=g(this).outerHeight()}),e.css("maxHeight",d+"px"),l=this.lt("collapse"),l.persist="all",this.Nb(),m=e.get(0),l=a.W.Nn(m,"collapse",l),l.then(function(){k.wua(e,h)}),this.Jb()):(e.css("maxHeight",
"0px"),this.NN(e),h(null));return f},wua:function(a,b){this.NN(a);b(null);this.Jb()},NN:function(a){a.removeClass(this.Tz()).addClass(this.kw());null!=this.qf&&this.qf.Zw(a)},wpa:function(){var a;this.Nb();a=this;this.SC().each(function(){a.Cr(g(this),null,!1,null,!1,!1)});this.Jb()},getExpanded:function(){var a,b,d;a=[];b=this;this.SC().each(function(){d=g(this);b.Zg(d)==b.Cm&&a.push(b.ug(d[0]))});return a},Mf:function(){return a.Components.Mf(this.element)},r_:function(){return this.Jl()?"oj-listview oj-listview-container-touch":
"oj-listview oj-listview-container"},eO:function(){return"oj-listview-element"},Vi:function(){return"oj-listview-item"},hp:function(){return"oj-listview-focused-element"},rh:function(){return"oj-listview-item-element"},mg:function(){return"oj-listview-group-item"},li:function(){return"oj-listview-group"},Tz:function(){return"oj-listview-collapsible-transition"},kw:function(){return this.Tz()},vn:function(){return"oj-listview-collapse-icon"},Rq:function(){return"oj-listview-expand-icon"},rLa:function(){return"oj-listview-no-data-message"},
LX:function(){return""},sLa:function(){return"oj-listview-option-defaults"},saa:function(){var a=this;this.Y._off(this.Ve(),"scroll");this.z9()&&this.Y._on(this.Ve(),{scroll:function(){a.q8()}})},z9:function(){return"static"!=this.me("groupHeaderPosition")},OC:function(){var a;null==this.OY&&(a="."+this.mg()+":visible",this.OY=this.element.find(a).filter(function(){return!g(this).parent().hasClass("oj-collapsed")&&0<g(this).next().children().length?!0:!1}));return this.OY},DW:function(a){a.style.position=
"static";a.style.top="auto";a.style.width="auto"},f7:function(a){var b;b=this.OC();a=b.index(a);return-1<a&&a<b.length-1?b[a+1]:null},gza:function(a,b){var d,e,f;d=a.offsetWidth;e=a.offsetHeight;f=this.f7(a);null!=f&&f.offsetTop<=b+e+5&&(b-=e);a.style.position="absolute";a.style.top=b+"px";a.style.width=d+"px"},q8:function(){var a,b,d,e,f,g,k,l;a=this.Ve().get(0).scrollTop;if(null!=this.Qg&&0==a)this.DW(this.Qg),this.Qg=null;else{d=this.OC();e=0;null!=this.Qg&&(e=this.Qg.offsetHeight);for(f=0;f<d.length;f++)if(g=
d[f],this.Qg!=g&&(k=d[f].offsetTop,l=k+g.parentNode.offsetHeight,k<a&&l>a+e)){b=g;break}null!=b&&b!=this.Qg?(null!=this.Qg&&this.DW(this.Qg),this.gza(b,a),this.Qg=b):null!=this.Qg&&(b=this.f7(this.Qg),this.Qg.style.top=null!=b&&b.offsetTop<=a+e?b.offsetTop-e+"px":a+"px")}},YS:function(){var a;a=this.me("scrollPolicyOptions");return null!=a&&(a=a.scroller,null!=a)?a:this.Ve().get(0)},hba:function(a){var b,d;b=this.YS();d=b.scrollTop;null!=this.Qg&&(this.DW(this.Qg),this.Qg=null);b.scrollTop=a.offsetTop;
this.z9()&&d==b.scrollTop&&this.q8();this.JBa(a)},JBa:function(a){var b=this,d;g(a).next().children().each(function(){d=g(this);if(!b.lk(d))return b.ik("currentItem",this.key),!1})}});o_("_ojListView",a.SU,a);a.Na("oj.ojListView",g.oj.baseComponent,{widgetEventPrefix:"oj",options:{currentItem:null,data:null,dnd:{drag:null,drop:null,reorder:{items:"disabled"}},drillMode:"collapsible",expanded:"auto",groupHeaderPosition:"sticky",item:{focusable:!0,renderer:null,selectable:!0},scrollPolicy:"auto",scrollPolicyOptions:{fetchSize:25,
maxCount:500},selection:[],selectionMode:"none",animateStart:null,animateEnd:null,beforeCurrentItem:null,beforeExpand:null,beforeCollapse:null,collapse:null,copy:null,cut:null,expand:null,optionChange:null,paste:null,ready:null,reorder:null},_ComponentCreate:function(){this._super();this.$a()},$a:function(){var c={};c.element=this.element;c.oe=this.oe;c.Y=this;c=g.extend(this.options,c);this.Ga=new a.SU;this.Ga.Yq(c)},Hh:function(){this._super();this.Ga.Cz()},_destroy:function(){this.Ga.destroy();
this._super()},ih:function(a,b,d){this.Ga.iha(a,b,d)},_setOptions:function(a,b){var d=this.Ga.Pw(a,b);this._super(a,b);d&&(this.Ga.refresh(),this.X5())},_setOption:function(a,b,d){var e=!0;"selectionMode"==a?e="none"==b||"single"==b||"multiple"==b:"drillMode"==a?e="collapsible"==b||"none"==b:"scrollPolicy"==a?e="auto"==b||"loadMoreOnScroll"==b:"groupHeaderPosition"==a&&(e="static"==b||"sticky"==b);if(e)"selection"==a&&(d={_context:{Ok:{items:g(this.Ga.TFa(b))}}}),this._super(a,b,d);else throw"Invalid value: "+
b+" for key: "+a;},sj:function(){this.Ga.jha()},Sp:function(){this.Ga.xA()},widget:function(){return this.Ga.Uk()},refresh:function(){this._super();this.Ga.refresh();this.X5()},whenReady:function(){return this.Ga.whenReady()},getNodeBySubId:function(a){return this.Ga.getNodeBySubId(a)},getSubIdByNode:function(a){return this.Ga.getSubIdByNode(a)},getContextByNode:function(a){return this.Ga.getContextByNode(a)},getDataForVisibleItem:function(a){return this.Ga.getDataForVisibleItem(a)},expand:function(a,
b){this.Ga.tX(a,b,!0,!0)},collapse:function(a,b){this.Ga.Eda(a,b,!0)},getExpanded:function(){return this.Ga.getExpanded()},getIndexerModel:function(){null==this.bF&&a.Ei&&(this.bF=new a.Ei(this.Ga));return this.bF},X5:function(){null!=this.bF&&this.bF.lea&&this.bF.lea()}});a.Components.Ta("ojListView","baseComponent",{properties:{currentItem:{type:"Object"},data:{},dnd:{},drillMode:{type:"string"},expanded:{type:"Array\x3cObject\x3e|string"},groupHeaderPosition:{},item:{},scrollPolicy:{type:"string"},
scrollPolicyOptions:{type:"Object\x3cstring, number\x3e"},selection:{type:"Array\x3cObject\x3e"},selectionMode:{type:"string"}},methods:{collapse:{},expand:{},getContextByNode:{},getDataForVisibleItem:{},getExpanded:{},getIndexerModel:{},getNodeBySubId:{},getSubIdByNode:{},refresh:{},whenReady:{},widget:{}},extension:{_hasWrapper:!0,_innerElement:"ul",_widgetName:"ojListView"}});a.Components.register("oj-list-view",a.Components.getMetadata("ojListView"))});