/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojdnd"],function(a,g){function c(a,d,e,f,g,k){null==c.nQ&&(c.nQ=c.msa());this.pd=a;this.Zh=d;this.ooa=e;f&&f.Bia&&(this.WCa=f.Bia);g&&(g.Eia&&(this.nW=g.Eia),g.Dia&&(this.mW=g.Dia),g.Iia&&(this.sW=g.Iia),g.Hia&&(this.rW=g.Hia),g.Fia&&(this.pW=g.Fia),g.Gia&&(this.$K=g.Gia),g.Kia&&(this.uW=g.Kia),g.Lia&&(this.vW=g.Lia),g.Jia&&(this.tW=g.Jia));k&&(k.GE&&(this.xj=k.GE),k.QF&&(this.hg=k.QF),k.nfa&&(this.B7=k.nfa),k.wfa&&(this.jT=k.wfa),k.lia&&(this.Vs=
k.lia),k.Wfa&&(this.Hy=k.Wfa),k.wga&&(this.Ty=k.wga),k.vga&&(this.Jo=k.vga),k.uga&&(this.Ms=k.uga),k.oia&&(this.jE=k.oia),k.Tg&&(this.oca=k.Tg),k.ti&&(this.pca=k.ti));d=document.createElement("div");e=d.style;e.display="inline-block";e.overflow="hidden";e.visibility="hidden";f=document.createElement("div");e=f.style;e.display="inline-block";d.appendChild(f);a.insertBefore(d,a.firstChild);this.dca=d;this.Vv=f;var l=this;this.Do=function(a){l.tv(a)};this.F8=function(){l.xwa()};this.ov=function(a){l.HT(a)};
this.rv=function(a){l.OT(a)}}(function(){function b(a){for(;a;){a=a.nextSibling;var b=!0;if(a){var c=a.style;!c||c.visibility!==t&&c.display!==r||(b=!1)}if(a&&1===a.nodeType&&b)return a}return null}function d(a,b){for(var c=a;c;){var d=c.style;if(d&&(d.visibility===t||d.display===r))break;d=c.parentNode;if(d===b)return c;c=d}return null}function e(a,b){return b.Hd<a.Hd?1:a.Hd<b.Hd?-1:0}function f(a){a&&a.sort(e);return a}function h(a){var b=null;a=g(a);a.hasClass("oj-masonrylayout-tile-1x1")?b={colSpan:1,
rowSpan:1}:a.hasClass("oj-masonrylayout-tile-2x1")?b={colSpan:2,rowSpan:1}:a.hasClass("oj-masonrylayout-tile-3x1")?b={colSpan:3,rowSpan:1}:a.hasClass("oj-masonrylayout-tile-1x2")?b={colSpan:1,rowSpan:2}:a.hasClass("oj-masonrylayout-tile-1x3")?b={colSpan:1,rowSpan:3}:a.hasClass("oj-masonrylayout-tile-2x2")?b={colSpan:2,rowSpan:2}:a.hasClass("oj-masonrylayout-tile-2x3")?b={colSpan:2,rowSpan:3}:a.hasClass("oj-masonrylayout-tile-3x2")&&(b={colSpan:3,rowSpan:2});return b}function k(a){var b=null;a=g(a);
a.hasClass("oj-masonrylayout-tile-1x1")?b="oj-masonrylayout-tile-1x1":a.hasClass("oj-masonrylayout-tile-2x1")?b="oj-masonrylayout-tile-2x1":a.hasClass("oj-masonrylayout-tile-3x1")?b="oj-masonrylayout-tile-3x1":a.hasClass("oj-masonrylayout-tile-1x2")?b="oj-masonrylayout-tile-1x2":a.hasClass("oj-masonrylayout-tile-1x3")?b="oj-masonrylayout-tile-1x3":a.hasClass("oj-masonrylayout-tile-2x2")?b="oj-masonrylayout-tile-2x2":a.hasClass("oj-masonrylayout-tile-2x3")?b="oj-masonrylayout-tile-2x3":a.hasClass("oj-masonrylayout-tile-3x2")&&
(b="oj-masonrylayout-tile-3x2");return b}function l(a,b){g(a).removeClass(b)}function m(a,b){g(a).addClass(b)}a.Na("oj.ojMasonryLayout",g.oj.baseComponent,{defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{reorderHandle:null,beforeInsert:null,insert:null,beforeRemove:null,remove:null,beforeResize:null,resize:null,beforeReorder:null,reorder:null},_ComponentCreate:function(){this._super();this.element.addClass("oj-masonrylayout oj-component");this.options.disabled&&a.r.warn(w);this.Mw=this.eventNamespace+
"ReorderHandle";this.Aa={};this.Aa.wh=!1;this.Aa.df=!1;this.Aa.XZ=!1;this.Aa.Hp=!1;this.Aa.Br=!1;this.Ds();this.WB();this.$a(!0)},refresh:function(){this._super();var a="rtl"===this.hd()!==this.Ph;a&&this.k5();this.$a(a)},Sp:function(){this._super();this.Ge&&this.$a(this.Ge[0])},Or:function(){this._super();this.Ge&&this.$a(this.Ge[0])},ih:function(a,b,c){this.nza(b);(a=this.Aa.df.children().not(".oj-helper-hidden"))&&0<a.length&&this.jh(b,c,{launcher:g(b.target).closest(":tabbable")})},$a:function(b){if(this.cC()){this.Ge=
null;this.Ph="rtl"===this.hd();this.bs=a.u.af();var d=this.element,e=this.options;if(b){var g=this;this.Vs=function(a){g.DCa(a)};this.Hy=function(a){g.wwa(a)};this.Ty=function(){g.Vxa()};this.Jo=function(){g.Uxa()};this.Ms=function(){g.Txa()};if(!this.Vh){var p={};p.Bia=u;var q={Eia:"oj-masonrylayout-transition-resize-to",Dia:"oj-masonrylayout-transition-resize-to-fast",Iia:"oj-masonrylayout-tile-transition-move-to",Hia:"oj-masonrylayout-tile-transition-move-to-fast",Fia:"oj-masonrylayout-tile-transition-hide-from",
Gia:"oj-masonrylayout-tile-transition-hide-to"};q.Kia=v;q.Lia="oj-masonrylayout-tile-transition-show-to";q.Jia="oj-masonrylayout-tile-transition-resize-to";var n={};n.GE=m;n.QF=l;n.nfa=k;n.wfa=h;n.lia=this.Vs;n.Wfa=this.Hy;n.wga=this.Ty;n.vga=this.Jo;n.uga=this.Ms;n.oia=f;n.Tg=a.Components.Tg;n.ti=a.Components.ti;this.hBa();this.Vh=new c(d[0],this.Ph,"enabled"===a.fa.FX(),p,q,n)}this.d8=function(a){g.BT(a)};this.a8=function(a){g.yT(a)};this.c8=function(a){g.AT(a)};this.b8=function(a){g.zT(a)};this.Y7=
function(a){g.xT(a)};this.e8=function(a){g.CT(a)};e.reorderHandle&&this.Tba()}else e=d.children(),this.eW(e),this.SV(e),this.cpa();this.Vh.Mn(b);b&&(this.Hj=function(){g.Hg()},a.u.Mk(d[0],this.Hj))}else d=!1,this.Ge&&(d=this.Ge[0]),this.Ge=[b||d]},_destroy:function(){this.Tu();var b=this.element;a.u.lm(b[0],this.Hj);this.Hj=null;this.cBa();for(var c=this.Bo(),d=c.length,e=0;e<d;e++)delete c[e].Hd;this.k5();b.removeClass("oj-masonrylayout oj-component");this.options.reorderHandle&&this.Aca();this.Ux=
this.Ms=this.Jo=this.Ty=this.Hy=this.Vs=this.e8=this.Y7=this.b8=this.c8=this.a8=this.d8=null;this._super()},_setOption:function(b,c,d){var e=!1;switch(b){case "reorderHandle":this.Aca();e=!0;break;case "disabled":a.r.warn(w);break;case "contextMenu":a.u.af()||(this.Tu(),c&&this.Ds(c))}this._super(b,c,d);e&&c&&this.Tba()},resizeTile:function(a,b){var c=this.Vh;c.xM()&&c.QL();var d=g(a),e=d[0],f=k(e);if(b==f)throw Error("JET MasonryLayout: Unable to resize child "+a+" to style class "+b+" because "+
b+" is already applied.");!1!==this._trigger("beforeResize",null,{tile:d,previousSizeStyleClass:f,sizeStyleClass:b})&&(this.YB||(this.YB=[]),this.YB.push(e,f,b),c.resizeTile(a,b))},insertTile:function(b,c){var d=this.Vh;d.xM()&&d.QL();isNaN(c)&&(c=-1);var e=g(b),f=e[0];!1!==this._trigger("beforeInsert",null,{tile:e,index:c})&&(f.L9=c,d.Yi()&&e.addClass(v),e=f.style,e.top="-1px",this.Ph?e.right="-1px":e.left="-1px",this.Es(f,c),d.yHa(f,c),a.Components.Tg(f),this.Ux||(this.Ux=[]),this.Ux.push(b))},
removeTile:function(b){var c=this.Vh;c.xM()&&c.QL();var d=g(b),e=d[0];if(a.le.AL(e)){var f=this.Bo(!0),e=f.indexOf(e);0<e&&(this.ER=f[e-1])}!1!==this._trigger("beforeRemove",null,{tile:d})&&c.rHa(b)},Hg:function(){this.jo||this.L8||this.Vh.TIa()},DCa:function(a){var b=g(a),c=a.L9;delete a.L9;this.options.reorderHandle&&this.SV(b);this._trigger("insert",null,{tile:b,index:c})},wwa:function(b){var c=g(b);this.options.reorderHandle&&this.eW(c);a.Components.ti(b);b.parentNode.removeChild(b);this.tK(b);
this._trigger("remove",null,{tile:c})},Vxa:function(){if(this.Ux){for(var a=this.Vh,b=this.Ux,c=0;c<b.length;c++)a.oJa(b[c]);this.Ux=null}if(this.YB){a=this.YB;for(c=0;c<a.length;c+=3){var b=a[c+1],d=a[c+2],b={tile:g(a[c]),previousSizeStyleClass:b,sizeStyleClass:d};this._trigger("resize",null,b)}this.YB=null}this.jo&&(this.BH?this.Jua():this.uQ&&this.Z7())},Uxa:function(){this.L8=!0;this.SJ=null;var b=document.activeElement;b&&a.u.op(this.element[0],b)&&(this.SJ=b)},Txa:function(){this.L8=!1;var b=
this.element[0];if(this.SJ){var c=this.SJ;this.SJ=null;if(this.ER){if(c=this.ER,this.ER=null,c&&a.u.op(b,c)){var b=this.Bo(b,!0),d=b.indexOf(c);0<=d&&d<b.length-1?a.le.CX(b[d+1]):a.le.CX(c)}}else a.u.op(b,c)?a.le.OE(c):a.le.CX(b)}},k5:function(){var a=this.Vh;a&&a.destroy();this.Vh=null},cC:function(){var a=document.createElement("div"),b=a.style;b.width="10px";b.height="10px";b=this.element[0];b.appendChild(a);var c=!1;try{c=0<a.offsetWidth&&0<a.offsetHeight}catch(d){}b.removeChild(a);return c},
Bo:function(a){for(var b=this.element.children(u),c=b.length,d=[],e=0;e<c;e++){var f=b[e];if(!a||a&&f!==this.lf){var g=f.style;g.visibility!==t&&g.display!==r&&d.push(f)}}return d},hBa:function(){var a=this.Bo();if(a)for(var b=0;b<a.length;b++){var c=a[b];c.Hd||(c.Hd=b+1)}},cpa:function(){var a=this.Bo();if(a)for(var b=0;b<a.length;b++){var c=a[b];c.Hd||this.Es(c,b)}},cBa:function(){var b=this.Bo(),c=this.Bo();f(c);for(var d=0;d<b.length;d++){var e=b[d],g=c[d];e!=g&&(a.Components.ti(g),e.parentNode.insertBefore(g,
e),a.Components.Tg(g),e=b.indexOf(g),e>d&&(b.splice(e,1),b.splice(d,0,g)))}},Es:function(a,b){var c=this.Bo();0>b&&(b=c.length);if(c)for(var d=0;d<c.length;d++){var e=c[d];e.Hd&&e.Hd>=b+1&&e.Hd++}a.Hd=b+1},tK:function(a){if(a.Hd){var b=this.Bo();if(b)for(var c=0;c<b.length;c++){var d=b[c];d.Hd&&d.Hd>a.Hd&&d.Hd--}delete a.Hd}},Ds:function(a){var b=null,c=null;a||this.options.contextMenu||(b=this.element.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||this.options.contextMenu){b=a||this.options.contextMenu;
c=g.type(b);if("function"==c){try{b=b()}catch(d){b=null}g.type(b)}if(b){if(b=g(b)){b.css("display",r);c=this.Aa;if(!c)return;c.df=b;c.wh=!0}this.Aa.wh&&a&&this.WB()}}},WB:function(){if(this.Aa&&this.Aa.wh&&this.options.reorderHandle){var a=this.Aa.df,b=this;a.on("ojselect",g.proxy(this.Dk,this));var c=!1;a.find("[data-oj-command]").each(function(){if(0===g(this).children("a").length){var a=g(this).attr("data-oj-command").slice(17);g(this).replaceWith(b.yj(a));g(this).addClass("oj-menu-item");c=!0}});
c&&a.ojMenu("refresh");this.Aa.XZ=a.find("#"+y);this.Aa.Hp=a.find("#"+x);this.Aa.Br=a.find("#"+z)}},Tu:function(){var a=this.Aa;a&&a.wh&&(a.wh=!1,a.df.off("ojselect"),a.df=null)},nza:function(a){var c=this.element,e=a.originalEvent.target,f=this.options.reorderHandle;a=!1;f&&(f=g(e).closest(f))&&0<f.length&&(a=!0);c=d(e,c[0]);this.Aa.tile=c;if(this.Aa.wh){var e=this.Aa.DL,f=!1,h=this.Aa.XZ;if(h){var k=h.hasClass("oj-helper-hidden");a||k?a&&k&&(h.removeClass("oj-helper-hidden"),f=!0):(h.addClass("oj-helper-hidden"),
f=!0);var l=h.hasClass(p),k=!1;e&&c===e&&(k=!0);k&&!l?(h.addClass(p),f=!0):!k&&l&&(h.removeClass(p),f=!0)}if(h=this.Aa.Hp)k=h.hasClass("oj-helper-hidden"),a||k?a&&k&&(h.removeClass("oj-helper-hidden"),f=!0):(h.addClass("oj-helper-hidden"),f=!0),l=h.hasClass(p),k=!1,e&&c!==e&&c!==b(e)||(k=!0),k&&!l?(h.addClass(p),f=!0):!k&&l&&(h.removeClass(p),f=!0);if(h=this.Aa.Br)k=h.hasClass("oj-helper-hidden"),a||k?a&&k&&(h.removeClass("oj-helper-hidden"),f=!0):(h.addClass("oj-helper-hidden"),f=!0),a=h.hasClass(p),
k=!1,e&&e!==c&&e!==b(c)||(k=!0),k&&!a?(h.addClass(p),f=!0):!k&&a&&(h.removeClass(p),f=!0);f&&this.Aa.df.ojMenu("refresh")}},yj:function(a){var b=D[a];a=I[a];var c=g('\x3ca href\x3d"#"\x3e\x3c/a\x3e');c.text(this.F(a));c.wrap("\x3cli id\x3d"+b+"\x3e\x3c/li\x3e");return c.parent()},kya:function(a){a&&(this.Aa.DL=a)},e$:function(a,b){if(a&&this.Aa.DL){var c=this.Aa.DL;this.Aa.DL=!1;this.jra(c,a,b)}},jra:function(a,c,d){var e=a.Hd-1,f=g(a);if(!1!==this._trigger("beforeReorder",null,{tile:f,fromIndex:e})){this.tK(a);
var h=c.Hd-1;d||h++;var k=this.element[0];d||(c=b(c));this.Es(a,h);k.insertBefore(a,c);this.Vh.Mn(!0);this._trigger("reorder",null,{tile:f,fromIndex:e,toIndex:h})}},Dk:function(a,b){var c=b?b.item.attr("id"):void 0;c===y?this.kya(this.Aa.tile):c===x?this.e$(this.Aa.tile,!0):c===z&&this.e$(this.Aa.tile,!1)},J7:function(a){var b=this.Bo(!0);f(b);for(var c=b.length,d=0;d<c;d++)if(b[d]===a)return d;return-1},Tba:function(){var a=this.element,b=a.children();this.SV(b);a.on("dragstart"+this.Mw,this.d8).on("dragenter"+
this.Mw,this.a8).on("dragover"+this.Mw,this.c8).on("dragleave"+this.Mw,this.b8).on("dragend"+this.Mw,this.Y7).on("drop"+this.Mw,this.e8)},SV:function(a){var b=this.options;a.filter(b.reorderHandle).attr(n,"true").addClass(q);a.find(b.reorderHandle).attr(n,"true").addClass(q)},Aca:function(){var a=this.element,b=a.children();this.eW(b);a.off(this.Mw)},eW:function(a){var b=this.options;a.filter(b.reorderHandle).removeAttr(n).removeClass(q);a.find(b.reorderHandle).removeAttr(n).removeClass(q)},BT:function(a){var b=
this.options;if(b.reorderHandle){var c=a.originalEvent.target,c=g(c).closest(b.reorderHandle);if(!c||1>c.length)return}b.reorderHandle&&!this.jo&&(c=a.target,b=d(c,this.element[0]))&&(c=this.J7(b),b.xU=c,c={tile:g(b),fromIndex:c},!1!==this._trigger("beforeReorder",null,c)&&(a=a.originalEvent,this.QR(b,a.pageX,a.pageY,a.dataTransfer)))},yT:function(b){if(this.jo){b=b.originalEvent;var c=b.relatedTarget,d=this.element[0],e=!1;c?e=d!=c&&!a.u.op(d,c):this.y5&&(e=(c=document.elementFromPoint(b.clientX,
b.clientY))&&(c==d||a.u.op(d,c)));e&&((this.y5=!1,this.ns)?this.lf&&(g(this.lf).css("display",""),this.Vh.Mn(!1,!0)):b.dataTransfer.dropEffect="none")}},AT:function(a){if(!this.jo)return!1;var b=a.originalEvent;b.dataTransfer.dropEffect="move";this.rra(b.pageX,b.clientX,b.clientY);a.preventDefault();return!1},zT:function(b){if(this.jo){var c=b.originalEvent,d=c.relatedTarget;b=this.element[0];var e=!1;e=d?b!=d&&!a.u.op(b,d):(c=document.elementFromPoint(c.clientX,c.clientY))&&c!=b&&!a.u.op(b,c);e&&
(this.y5=!0,this.lf&&(g(this.lf).css("display",r),this.Vh.Mn(!1,!0)))}},h4:function(){if(this.lI){clearTimeout(this.lI);this.lI=null;var a=this.ns;a&&g(a).removeClass("oj-drag")}},xT:function(){this.h4();if(this.jo&&!this.wQ){var b=this.ns;if(b&&this.lf){var c=this.lf;a.u.op(this.element[0],b)&&(g(c).css("display",""),this.tK(c),c.parentNode.removeChild(c),g(b).css("display",""),this.Es(b,b.Hd-1),this.Vh.Mn(!1,!0));delete b.xU}this.lf=this.ns=null;this.DH=this.BH=!1;this.PR=null;this.jo=this.uQ=!1}},
CT:function(a){if(!this.jo)return!1;var b=this.Vh;b.xM()&&b.QL();this.h4();b=a.originalEvent;this.Bra(this.ns,b.pageX,b.pageY);a.stopPropagation();return!1},QR:function(b,c,d,e){this.jo=!0;this.vQ=this.DH=this.wQ=!1;this.ns=b;var f=this.element[0],h=k(b),l=this.lf=document.createElement("div");l.Hd=b.Hd;l.className=h+" oj-drop";var h=l.style,m=b.style;h.top=m.top;this.Ph?h.right=m.right:h.left=m.left;h=g(b).offset();f.insertBefore(l,b);this.PR=c={left:c-h.left,top:d-h.top};g(b).addClass("oj-drag");
e.effectAllowed="move";e.setData("text/html",b.outerHTML);e.setDragImage(b,c.left,c.top);var p=this;this.lI=setTimeout(function(){p.vQ=!0;m.display=r;g(b).removeClass("oj-drag");p.lI=null;a.Components.Wt(b)},0)},rra:function(a,c,e){this.DH=!0;if(this.vQ&&!this.BH){var f=this.element[0];c=document.elementFromPoint(c,e);c=d(c,f);e=!1;if(c){var h=g(c),k=this.options.reorderHandle;k&&(e=(e=h.find(k))&&0<e.length)}c&&c!==this.lf&&c!==this.ns&&e&&(h=g(f).offset(),e=b(this.lf),a=a-h.left>=c.offsetLeft+.5*
c.offsetWidth,this.tK(this.lf),a&&!this.Ph||!a&&this.Ph?(a=b(c))?(this.Es(this.lf,a.Hd-1),f.insertBefore(this.lf,a)):(this.Es(this.lf,c.Hd),f.appendChild(this.lf)):(this.Es(this.lf,c.Hd-1),f.insertBefore(this.lf,c)),e!==b(this.lf)&&(this.BH=this.Vh.Mn(!1,!0)))}},Jua:function(){this.BH=!1},Bra:function(b,c,d){this.wQ=!0;var e=this.element[0],f=this.lf;this.lf=null;a.Components.ti(b);e.replaceChild(b,f);a.Components.Tg(b);b.Hd=f.Hd;f=b.style;f.display="";a.Components.yr(b);var h=g(e).offset(),k=this.PR;
f.top=d-k.top-h.top+s;c=c-k.left-h.left;this.Ph?(f.right=e.offsetWidth-(c+g(b).outerWidth(!0))+s,f.left=""):f.left=c+s;this.PR=null;this.DH?this.uQ=this.Vh.Mn(!1,!0):this.Z7()},Z7:function(){this.vQ=this.DH=this.wQ=this.jo=this.uQ=!1;var a=this.ns;this.ns=null;var b=a.xU;delete a.xU;var c=this.J7(a),a={tile:g(a),fromIndex:b,toIndex:c};this._trigger("reorder",null,a)},getNodeBySubId:function(a){return this._super(a)},getSubIdByNode:function(a){return this._super(a)}});var s="px",t="hidden",r="none",
n="draggable",p="oj-disabled",q="oj-draggable",u=".oj-masonrylayout-tile-1x1, .oj-masonrylayout-tile-1x2, .oj-masonrylayout-tile-1x3, .oj-masonrylayout-tile-2x1, .oj-masonrylayout-tile-2x2, .oj-masonrylayout-tile-2x3, .oj-masonrylayout-tile-3x1, .oj-masonrylayout-tile-3x2",v="oj-masonrylayout-tile-transition-show-from",w="JET MasonryLayout: 'disabled' option not supported",y="ojmasonrylayoutcut",x="ojmasonrylayoutpastebefore",z="ojmasonrylayoutpasteafter",D={cut:y,"paste-before":x,"paste-after":z},
I={cut:"labelCut","paste-before":"labelPasteBefore","paste-after":"labelPasteAfter"}})();c.prototype.Mn=function(a,c){var e=!1;a?(e=this.Kj()?!0:!1,this.Iaa()):(this.Jo&&this.Jo(),this.wW(c),e=this.qW());return e};c.prototype.destroy=function(){for(var a=this.pd,c=this.nv(),e=0;e<c.length;e++){var f=c[e].style;this.Zh?f.right="":f.left="";f.top=""}a.removeChild(this.dca);this.pca=this.oca=this.jE=this.Ms=this.Jo=this.Ty=this.Hy=this.Vs=this.jT=this.B7=this.hg=this.xj=this.pd=this.$p=this.ho=this.wl=
this.io=this.Om=this.rv=this.ov=this.F8=this.Do=this.Vv=this.dca=null};c.prototype.resizeTile=function(a,c){var e=this.pd.querySelector(a);if(e){this.io||(this.io=[]);var f=this.io;f.push(e);f.push(c);this.Raa=!0;this.ND()}};c.prototype.yHa=function(a,c){var e=this.nv();this.jE&&this.jE(e);var f=null;0<=c&&c<e.length&&(f=e[c]);this.pd.insertBefore(a,f);this.ND()};c.prototype.oJa=function(a){if(a=this.pd.querySelector(a))this.wl||(this.wl=[]),this.wl.push(a),this.YV=!0,this.en!==c.Z1&&this.en!==c.$G?
this.ND():this.YV=!1};c.prototype.rHa=function(a){if(a=this.pd.querySelector(a))this.ho||(this.ho=[]),this.ho.push(a),this.G8=!0,this.ND()};c.prototype.TIa=function(){this.Raa||this.G8||this.YV||(this.Jo&&this.Jo(),this.wW(!1),this.qW())};c.prototype.Yi=function(){if(this.Cca)return!1;this.Moa||(this.foa=this.ooa?!1:c.xxa(c.nQ[0],c.nQ[1]),this.Moa=!0);return this.foa};c.prototype.xM=function(){return null!=this.en||null!=this.Om&&0<this.Om.length};c.prototype.QL=function(){this.Cca=!0;this.yq(this.sW);
this.yq(this.rW);this.yq(this.pW);this.yq(this.$K);this.yq(this.uW);this.yq(this.vW);this.yq(this.tW);this.hg(this.Vv,this.nW);this.hg(this.Vv,this.mW);c.gg(this.pd,"transitionend",this.Do);c.gg(this.pd,"webkitTransitionEnd",this.Do);for(var a=this.nv(),d=0;d<a.length;d++){var e=a[d];e.xH&&delete e.xH;c.gg(e,"transitionend",this.ov);c.gg(e,"webkitTransitionEnd",this.ov);c.gg(e,"transitionend",this.rv);c.gg(e,"webkitTransitionEnd",this.rv)}this.Iy?(clearTimeout(this.Iy),this.Iy=null,this.HT(null)):
this.oz?(clearTimeout(this.oz),this.oz=null,this.XV()):this.en===c.$G||null!=this.Om&&0<this.Om.length?this.tv(null):this.en===c.a2&&this.OT(null);this.Cca=!1};c.Usa=function(a){var d=c.IC(a);return{vi:a.offsetWidth+(c.Ni(d.marginLeft)+c.Ni(d.marginRight)),Vj:a.offsetHeight+(c.Ni(d.marginTop)+c.Ni(d.marginBottom))}};c.Tsa=function(a){a=c.IC(a);return{paddingLeft:c.Ni(a.paddingLeft),paddingRight:c.Ni(a.paddingRight),paddingTop:c.Ni(a.paddingTop),paddingBottom:c.Ni(a.paddingBottom),borderLeftWidth:c.Ni(a.borderLeftWidth),
borderRightWidth:c.Ni(a.borderRightWidth),borderTopWidth:c.Ni(a.borderTopWidth),borderBottomWidth:c.Ni(a.borderBottomWidth)}};c.IC=function(a){var c=a.ownerDocument.defaultView,e=null;return e=c?c.getComputedStyle(a,null):a.currentStyle};c.Ni=function(a){return 0<a.length&&"auto"!=a?(a=parseInt(a,10),isNaN(a)&&(a=0),a):0};c.Nh=function(a,c,e){a.addEventListener?a.addEventListener(c,e,!1):a.attachEvent&&a.attachEvent("on"+c,e)};c.gg=function(a,c,e){a.removeEventListener?a.removeEventListener(c,e,!1):
a.detachEvent&&a.detachEvent("on"+c,e)};c.q3=function(a,c){if(a)for(var e=0;e<a.length;e++)if(a[e]==c)return e;return-1};c.xxa=function(a,c){var e=["gecko",16,"trident",6,"webkit",533.1],f=e.length;if(0==f%2)for(var g=0;g<=f-2;g+=2)if(a==e[g]){if(c>=e[1+g])return!0;break}return!1};c.msa=function(){var a=c.Gk,d=null,e=-1,f=navigator.userAgent.toLowerCase();-1!=f.indexOf("msie")||-1!=f.indexOf("trident")?(d="trident",e=a(f,/trident\/(\d+[.]\d+)/),-1==e&&(e=a(f,/msie (\d+\.\d+);/),-1==e&&(e=a(f,/msie (\d+\.\d+)b;/)),
e-=4),null!=document.documentMode&&(e=Math.min(e,document.documentMode-4))):-1!=f.indexOf("applewebkit")?(d="webkit",e=a(f,/applewebkit\/(\d+([.]\d+)*)/)):-1!=f.indexOf("gecko/")&&(d="gecko",e=a(f,/rv:(\d+[.]\d+)/));return[d,e]};c.Gk=function(a,c){var e=a.match(c);return e&&(e=e[1])?parseFloat(e):-1};c.Fpa=function(a,c){return a.zN>c.zN?1:a.zN<c.zN?-1:a.yN>c.yN?1:a.yN<c.yN?-1:0};c.prototype.ND=function(){this.xJ||(this.en?this.hV||(this.hV=!0):this.xJ=setTimeout(this.F8,0))};c.prototype.nv=function(){for(var a=
this.pd.querySelectorAll(this.WCa),c=[],e=0;e<a.length;e++){var f=a[e],g=f.style;0<f.offsetWidth&&0<f.offsetHeight&&"hidden"!=g.visibility&&c.push(f)}return c};c.prototype.qW=function(){var a=this.Om,d=this.Kj();if(this.io){var e=this.io;d||(d=[]);for(var f=0;f<e.length;f+=2){var g=e[f];0>c.q3(d,g)&&d.push(g)}}e=!1;if(!d||1>d.length){if(!a||1>a.length)this.Om=null,this.tv(null),e=!0}else this.Om=d;a=null!=d&&0<d.length;this.Yi()||e||this.tv(null);return a};c.prototype.Kj=function(){var a=this.pd,
d=this.nv();this.jE&&this.jE(d);var e=this.SQ=null;this.gs=0;this.ya=1;this.$y=null;var f=[],g=[],k=[],l=this.Zh,m=c.Tsa(a),s=0,t=[];this.p3=t;for(var r=0;r<d.length;r++){var n=d[r],p=this.jT(n);(e=n.xH)&&delete n.xH;if(!this.SQ){var q=p;e&&(q=document.createElement("div"),q.className=e,q=this.jT(q));this.SQ=this.Noa(n,q)}e=this.SQ;this.$y||(this.gs=Math.max(Math.floor((a.offsetWidth-m.paddingLeft-m.paddingRight-m.borderLeftWidth-m.borderRightWidth)/e.vi),1),this.Qwa(this.gs,this.ya),s=this.gs);p.colSpan>
s&&(s=p.colSpan);p.colSpan>this.gs&&(p.colSpan=this.gs);for(var u=!1,q=0;q<this.ya;q++){for(var v=0;v<this.gs;v++)if(this.esa(v,q,p)){var u=n.style,w={top:u.top};l?w.right=u.right:w.left=u.left;g.push(w);this.$U(n,v,q,p,e,m);l&&k.push(v);u=!0;t.push({yN:v,zN:q,tile:n});break}if(u)break;q===this.ya-1&&this.U2()}}e&&(a=this.Vv.style,a.width=s*e.vi+"px",a.height=this.ya*e.Vj+"px");for(r=0;r<d.length;r++)n=d[r],u=n.style,w=g[r],""!=w.top&&(l&&parseInt(u.right,10)!==parseInt(w.right,10)||!l&&parseInt(u.left,
10)!==parseInt(w.left,10)||parseInt(u.top,10)!==parseInt(w.top,10))&&f.push(n);1>f.length&&(f=null);return f};c.prototype.Iaa=function(){var a=this.p3;this.p3=null;for(var a=a.sort(c.Fpa),d=this.nv(),e=0;e<d.length;e++){var f=d[e],g=a[e].tile;f!=g&&(this.pca(g),f.parentNode.insertBefore(g,f),this.oca(g),f=c.q3(d,g),f>e&&(d.splice(f,1),d.splice(e,0,g)))}};c.prototype.Qwa=function(a,c){for(var e=this.$y=[],f=0;f<c;f++){var g=[];e.push(g);for(var k=0;k<a;k++)g[k]=!1}};c.prototype.U2=function(){this.ya++;
var a=[];this.$y.push(a);for(var c=0;c<this.gs;c++)a[c]=!1};c.prototype.esa=function(a,c,e){var f=e.colSpan;e=e.rowSpan;for(var g=c;g<c+e;g++){g>=this.ya&&this.U2();for(var k=a;k<a+f;k++)if(k>=this.gs||this.$y[g][k])return!1}return!0};c.prototype.$U=function(a,c,e,f,g,k){var l=f.colSpan;f=f.rowSpan;for(var m=this.$y,s=e;s<e+f;s++)for(var t=c;t<c+l;t++)m[s][t]=!0;a=a.style;a.top=k.paddingTop+e*g.Vj+"px";this.Zh?a.right=k.paddingRight+c*g.vi+"px":a.left=k.paddingLeft+c*g.vi+"px"};c.prototype.Nna=function(a){for(var c=
this.nv(),e=0;e<c.length;e++)this.xj(c[e],a)};c.prototype.yq=function(a){for(var c=this.nv(),e=0;e<c.length;e++)this.hg(c[e],a)};c.prototype.wW=function(a){this.P9||(this.Jaa=a,this.Yi()&&(this.Nna(a?this.rW:this.sW),this.xj(this.Vv,a?this.mW:this.nW),c.Nh(this.pd,"transitionend",this.Do),c.Nh(this.pd,"webkitTransitionEnd",this.Do)),this.P9=!0)};c.prototype.tv=function(a){var d=!0;if(this.Om){var e=this.Om;if(a){var f=a.target;for(a=0;a<e.length;a++)if(f===e[a]){e.splice(a,1);break}}else this.Yi()||
(e=this.Om=[]);0<e.length&&(d=!1)}if(d){if(this.io&&(d=this.io,this.io=null,this.Yi()))for(a=0;a<d.length;a+=2)this.hg(d[a],this.tW);this.Jaa?(this.Yi()&&(this.yq(this.rW),this.hg(this.Vv,this.mW)),this.Jaa=!1):this.Yi()&&(this.yq(this.sW),this.hg(this.Vv,this.nW));this.Yi()&&(c.gg(this.pd,"transitionend",this.Do),c.gg(this.pd,"webkitTransitionEnd",this.Do));this.YV=this.G8=this.Raa=this.P9=!1;this.Iaa();this.Ty&&this.Ty();if(this.en===c.$G)if(this.Yi()){var g=this;this.oz=setTimeout(function(){g.XV()},
0)}else this.XV();else this.en||this.Ms&&this.Ms()}};c.prototype.Noa=function(a,d){var e=c.Usa(a);return{vi:e.vi/d.colSpan,Vj:e.Vj/d.rowSpan}};c.prototype.xwa=function(){this.xJ&&(clearTimeout(this.xJ),this.xJ=null);this.Jo&&this.Jo();this.en=c.Z1;if(this.ho&&this.Yi()){for(var a=this.ho,d=0;d<a.length;d++){var e=a[d];c.Nh(e,"transitionend",this.ov);c.Nh(e,"webkitTransitionEnd",this.ov);this.xj(e,this.pW)}var f=this;this.Iy=setTimeout(function(){for(var c=0;c<a.length;c++){var d=a[c];f.hg(d,f.pW);
f.xj(d,f.$K)}},0)}else this.HT(null)};c.prototype.HT=function(a){this.Iy&&(clearTimeout(this.Iy),this.Iy=null);if(a){a.preventDefault();a.stopPropagation();a=a.target;this.hg(a,this.$K);c.gg(a,"transitionend",this.ov);c.gg(a,"webkitTransitionEnd",this.ov);var d=this.ho;if(d){for(var e=0;e<d.length;e++){var f=d[e];if(f===a){d.splice(e,1);this.$p||(this.$p=[]);var g=this.$p;g.push(a);break}}1>d.length&&(this.ho=null)}}else if(!this.Yi()&&(d=this.ho)){for(e=0;e<d.length;e++)f=d[e],this.$p||(this.$p=
[]),g=this.$p,g.push(f);this.ho=null}if(!this.ho){if(this.$p){g=this.$p;for(e=0;e<g.length;e++)a=g[e],this.Yi()&&this.hg(a,this.$K),d=a.style,this.Zh?d.right="":d.left="",d.top="",this.Hy&&this.Hy(a);this.$p=null}this.en=c.$G;this.wW(!1);if(this.io)for(g=this.io,e=0;e<g.length;e+=2)a=g[e],d=g[e+1],f=this.B7(a),this.hg(a,f),this.xj(a,d),this.Yi()&&(this.xj(a,this.tW),a.xH=f);this.qW()}};c.prototype.XV=function(){this.oz&&(clearTimeout(this.oz),this.oz=null);this.en=c.a2;if(this.wl&&this.Yi())for(var a=
this.wl,d=0;d<a.length;d++){var e=a[d];c.Nh(e,"transitionend",this.rv);c.Nh(e,"webkitTransitionEnd",this.rv);this.xj(e,this.vW);this.hg(e,this.uW)}else{if(this.wl)for(a=this.wl,d=0;d<a.length;d++)e=a[d],this.hg(e,this.uW);this.OT(null)}};c.prototype.OT=function(a){if(a){a.preventDefault();a.stopPropagation();a=a.target;this.hg(a,this.vW);c.gg(a,"transitionend",this.rv);c.gg(a,"webkitTransitionEnd",this.rv);var d=this.wl;if(d){for(var e=0;e<d.length;e++){var f=d[e];if(f===a){d.splice(e,1);this.Vs&&
this.Vs(a);break}}1>d.length&&(this.wl=null)}}else if(!this.Yi()&&(d=this.wl)){for(e=0;e<d.length;e++)f=d[e],this.Vs&&this.Vs(f);this.wl=null}this.wl||(this.en=null,this.Ms&&this.Ms(),this.hV&&(this.hV=!1,this.ND()))};c.Z1=1;c.$G=2;c.a2=3;a.Components.Ta("ojMasonryLayout","baseComponent",{properties:{disabled:{type:"boolean"},reorderHandle:{type:"string"}},methods:{insertTile:{},refresh:{},removeTile:{},resizeTile:{}},extension:{_widgetName:"ojMasonryLayout"}});a.Components.register("oj-masonry-layout",
a.Components.getMetadata("ojMasonryLayout"))});