/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery"],function(a,g){a.ia=function(a,b,d){this.Init(a,b,d)};o_("Message",a.ia,a);a.ia.Xn={CONFIRMATION:"confirmation",INFO:"info",WARNING:"warning",ERROR:"error",FATAL:"fatal"};o_("Message.SEVERITY_TYPE",a.ia.Xn,a);a.ia.Xc={FATAL:5,ERROR:4,WARNING:3,INFO:2,CONFIRMATION:1};o_("Message.SEVERITY_LEVEL",a.ia.Xc,a);a.b.ta(a.ia,a.b,"oj.Message");a.ia.prototype.Init=function(c,b,d){a.ia.t.Init.call(this);this.summary=c;this.detail=b;this.severity=d||a.ia.Xn.ERROR};a.b.g("Message.prototype.Init",
{Init:a.ia.prototype.Init});a.ia.prototype.zda=function(){return!0};a.ia.prototype.Mq=function(c){return c&&a.ia.Zz(this.severity)===a.ia.Zz(c.severity)&&this.summary===c.summary&&this.detail===c.detail?!0:!1};a.b.g("Message.prototype.equals",{Mq:a.ia.prototype.Mq});a.ia.prototype.clone=function(){return new a.ia(this.summary,this.detail,this.severity)};a.b.g("Message.prototype.clone",{clone:a.ia.prototype.clone});a.ia.Zz=function(c){c&&("string"===typeof c?(c=a.ia.oP.indexOf(c,1),c=-1===c?a.ia.Xc.ERROR:
c):"number"===typeof c&&c<a.ia.Xc.CONFIRMATION&&c>a.ia.Xc.FATAL&&(c=a.ia.Xc.ERROR));return c?c:a.ia.Xc.ERROR};o_("Message.getSeverityLevel",a.ia.Zz,a);a.ia.fGa=function(c){var b;c&&("string"===typeof c?(b=a.ia.oP.indexOf(c,1),-1===b&&(c=a.ia.Xn.ERROR)):"number"===typeof c&&(c=c<a.ia.Xc.CONFIRMATION&&c>a.ia.Xc.FATAL?a.ia.Xn.ERROR:a.ia.oP[c]));return c||a.ia.Xn.ERROR};o_("Message.getSeverityType",a.ia.fGa,a);a.ia.Vz=function(c){var b=-1,d;c&&0<c.length&&g.each(c,function(c,f){f&&(d=a.ia.Zz(f.severity));
b=b<d?d:b});return b};o_("Message.getMaxSeverity",a.ia.Vz,a);a.ia.isValid=function(c){return a.ia.Vz(c)>=a.ia.Xc.ERROR?!1:!0};o_("Message.isValid",a.ia.isValid,a);a.ia.oP=["none",a.ia.Xn.CONFIRMATION,a.ia.Xn.INFO,a.ia.Xn.WARNING,a.ia.Xn.ERROR,a.ia.Xn.FATAL];a.be=function(a,b,d,e){this.Init(a,b,d,e)};a.b.ta(a.be,a.ia,"oj.ComponentMessage");a.be.$w={yO:"shown",gO:"hidden"};a.be.Ika={display:a.be.$w.yO,context:""};a.be.prototype.Init=function(c,b,d,e){a.be.t.Init.call(this,c,b,d);this.Vb=g.extend({},
a.be.Ika,e)};a.be.prototype.Mq=function(c){return a.be.t.Mq.call(this,c)&&this.Vb.display===c.Vb.display};a.be.prototype.clone=function(){return new a.be(this.summary,this.detail,this.severity,this.Vb)};a.be.prototype.zda=function(){return!(this.Vb&&this.Vb.display&&this.Vb.display===a.be.$w.gO)};a.be.prototype.gsa=function(){this.Vb&&a.be.$w.gO===this.Vb.display&&(this.Vb.display=a.be.$w.yO)};a.be.prototype.u9=function(){return this.Vb&&this.Vb.context?!0:!1}});