/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","hammerjs","ojs/ojjquery-hammer","ojs/ojcomponentcore","ojs/ojpopupcore"],function(a,g,c){(function(){a.Na("oj.ojMenu",g.oj.baseComponent,{defaultElement:"\x3cul\x3e",delay:300,role:"menu",widgetEventPrefix:"oj",options:{menuSelector:"ul",openOptions:{display:"auto",initialFocus:"menu",launcher:null,position:{my:"start top",at:"start bottom",collision:"flipfit"}},submenuOpenOptions:{position:{my:"start top",at:"end top",collision:"flipfit"}},beforeOpen:null,close:null,
open:null,select:null},_ComponentCreate:function(){this._super();var a=this;this._focusForTesting=this.Mi;this._nextForTesting=this.p$;this._selectForTesting=this.kn;this.bw=this.element;this.YY=!1;if(h&&"ul"!==this.element[0].tagName.toLowerCase())throw Error("Cancel item supported for \x3cul\x3e menus only.");this.qCa();this.element.uniqueId().addClass("oj-menu oj-component").hide().attr({role:this.role,tabIndex:"0"});this._on(!0,{"mousedown .oj-menu-item":function(a){this.options.disabled&&a.preventDefault()},
click:function(a){this.options.disabled&&a.preventDefault()},keydown:function(a){!this.options.disabled||a.keyCode!==g.ui.keyCode.ESCAPE&&a.keyCode!==g.ui.keyCode.TAB||(a.keyCode===g.ui.keyCode.TAB&&a.preventDefault(),this.Id&&this.EC(a))}});this.options.disabled&&this.element.addClass("oj-disabled").attr("aria-disabled","true");var b=function(a){if(!this.DX){this.DX=!0;var b=g(a.currentTarget);try{this.d6=!0,this.Mi(a,b)}finally{this.d6=!1}}}.bind(this);this._on({"mousedown .oj-menu-item \x3e a":function(a){a.preventDefault()},
"click .oj-disabled \x3e a":function(a){a.preventDefault()},click:function(){this.YY=!1},touchstart:function(){this.DX=!1},mouseover:function(){this.DX=!1},"click .oj-menu-item:has(a)":function(a){var b=g(a.target).closest(".oj-menu-item");!this.YY&&b.not(".oj-disabled").length&&(this.YY=!0,a.preventDefault(),this.ab&&this.ab.closest(b).length&&this.ab.get(0)!=b.get(0)||(b.has(".oj-menu").length?this.bg(a):(this.kn(a),this.element.is(":focus")||(this.element.trigger("focus",[!0]),this.ab&&1===this.ab.parents(".oj-menu").length&&
clearTimeout(this.Le)))))},"mouseenter .oj-menu-item":b,"touchstart .oj-menu-item":b,mouseleave:function(a){this.oo(a,"eventSubtree")},"mouseleave .oj-menu":function(a){this.oo(a,"eventSubtree")},focus:function(a,b){if(!b){var c=this.ab||this.element.children(".oj-menu-item").eq(0);this.Mi(a,c)}},keydown:this.Ev,keyup:function(a){if(a.keyCode==g.ui.keyCode.ENTER||a.keyCode==g.ui.keyCode.SPACE)this.rH=!1}});this._focusable({applyHighlight:!e,recentPointer:function(){return a.d6},setupHandlers:function(b,
c){a.qy=b;a.dv=c}});this.zE=g.proxy(this.AE,this);this.$a()},Px:function(a){if(arguments.length)d=a;else return d},dR:function(a){if(("focus"===a.type||"mousedown"===a.type||"touchstart"===a.type||93==a.which||121==a.which&&a.shiftKey||93==a.keyCode)&&("mousedown"!==a.type||!d)){var c=b.slice(0,b.length);g.each(c,function(b,c){!g(a.target).closest(c.element).length&&("keydown"===a.type||"mousedown"===a.type&&3===a.which||!g(a.target).closest(c.Id).length||c.Sxa&&("mousedown"===a.type&&3!==a.which||
"touchstart"===a.type))&&(c.oo(a,"eventSubtree"),c.Id&&c.Nu(a))})}},_setOption:function(a,b){this._superApply(arguments);switch(a){case "translations.labelCancel":case "translations":this.Z3&&this.Z3.text(this.options.translations.labelCancel)}},_destroy:function(){this.element.is(":visible")&&this.Nu();clearTimeout(this.Le);delete this.Le;this.element.removeAttr("aria-activedescendant").removeClass("oj-component").find(".oj-menu").addBack().removeClass("oj-menu oj-menu-submenu oj-menu-icons oj-menu-text-only").removeAttr("role").removeAttr("tabIndex").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-disabled").removeUniqueId().show();
this.element.find(".oj-menu-item").removeClass("oj-menu-item").removeAttr("role").children("a").removeAttr("aria-disabled").removeUniqueId().removeClass("oj-hover").removeAttr("tabIndex").removeAttr("role").removeAttr("aria-haspopup").children().each(function(){var a=g(this);a.data("oj-ojMenu-submenu-icon")&&a.remove()});this.element.find("a").removeAttr("aria-expanded");this.element.find(".oj-menu-divider").removeClass("oj-menu-divider").removeAttr("role");0<=b.indexOf(this)&&b.splice(b.indexOf(this),
1);delete this.hn;delete this.zE;var a=this.fs;isNaN(a)||(delete this.fs,window.clearTimeout(a));this.LH&&this.LH.remove();this.element.$j("destroy");this._super()},Ev:function(a){function b(a){return a.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g,"\\$\x26")}var c,d,e,f,h=!0;switch(a.keyCode){case g.ui.keyCode.HOME:this.VJ("first","first",a);break;case g.ui.keyCode.END:this.VJ("last","last",a);break;case g.ui.keyCode.UP:this.tza(a);break;case g.ui.keyCode.DOWN:this.p$(a);break;case g.ui.keyCode.LEFT:case g.ui.keyCode.RIGHT:a.keyCode===
g.ui.keyCode.RIGHT^this.Xk?this.ab&&!this.ab.is(".oj-disabled")&&this.bg(a):this.oo(a,"active");break;case g.ui.keyCode.ENTER:case g.ui.keyCode.SPACE:this.Lua(a);this.rH=!0;var k=this;setTimeout(function(){k.rH=!1},100);break;case g.ui.keyCode.TAB:a.preventDefault();this.Id&&this.EC(a);break;case g.ui.keyCode.ESCAPE:this.Id?(d=this.element.attr("aria-activedescendant"),e="#"+this.element.attr("id")+"\x3e*\x3ea",d&&!g("#"+d).is(e)?this.oo(a,"active"):this.EC(a)):this.oo(a,"active");break;default:h=
!1,c=this.mN||"",d=String.fromCharCode(a.keyCode),e=!1,clearTimeout(this.yFa),d===c?e=!0:d=c+d,f=new RegExp("^"+b(d),"i"),c=this.bw.children(".oj-menu-item").filter(function(){return f.test(g(this).children("a").text())}),c=e&&-1!==c.index(this.ab.next())?this.ab.nextAll(".oj-menu-item"):c,c.length||(d=String.fromCharCode(a.keyCode),f=new RegExp("^"+b(d),"i"),c=this.bw.children(".oj-menu-item").filter(function(){return f.test(g(this).children("a").text())})),c.length?(this.Mi(a,c),1<c.length?(this.mN=
d,this.yFa=this._delay(function(){delete this.mN},1E3)):delete this.mN):delete this.mN}h&&a.preventDefault()},Lua:function(a){this.ab&&!this.ab.is(".oj-disabled")&&(this.ab.children("a[aria-haspopup\x3d'true']").length?this.bg(a):this.kn(a))},refresh:function(){this._super();this.$a();var a=this.element;if(a.is(":visible")){var b=a.data("oj-menu-position");b&&a.position(b);a.find(".oj-menu").each(function(){var a=g(this);a.is(":visible")&&(b=a.data("oj-menu-position"))&&a.position(b)})}},$a:function(){this.Xk=
"rtl"===this.hd();var a=this,b=this.element.find(this.options.menuSelector),c=b.add(this.element),d=c.children();this.swa=!!b.length;d.filter(".oj-menu-divider").has("a").removeClass("oj-menu-divider oj-menu-item").removeAttr("role");var e=d.filter(":not(.oj-menu-item):has(a)"),f=e.children("a");this.Y8(e);this.N8(f);e=d.filter(function(a,b){var c=g(b);return c.is(":not(.oj-menu-item)")&&!/[^\-\u2014\u2013\s]/.test(c.text())});this.U8(e);this.Kwa(d,e);d.filter(".oj-disabled").children("a").attr("aria-disabled",
"true");d.filter(":not(.oj-disabled)").children("a").removeAttr("aria-disabled");b.filter(":not(.oj-menu)").addClass("oj-menu oj-menu-submenu oj-menu-dropdown").hide().attr({role:this.role,"aria-hidden":"true"}).each(function(){var b=g(this),c=a.dT(b),d=g("\x3cspan\x3e");d.addClass("oj-menu-submenu-icon oj-component-icon").data("oj-ojMenu-submenu-icon",!0);c.attr("aria-haspopup","true").attr("aria-expanded","false").append(d);c=c.attr("id");b.attr("aria-labelledby",c)});c.each(function(){var a=g(this),
b=a.children().children().children(".oj-menu-item-icon:not(.oj-menu-cancel-icon)").length;a.toggleClass("oj-menu-icons",!!b).toggleClass("oj-menu-text-only",!b)});this.ab&&!g.contains(this.element[0],this.ab[0])&&this.yQ()},Y8:function(a){a.addClass("oj-menu-item").attr("role","presentation")},N8:function(a){a.uniqueId().attr({tabIndex:"-1",role:"menuitem"})},U8:function(a){a.addClass("oj-menu-divider").attr("role","separator")},Kwa:function(a,b){a.removeClass("oj-menu-item-before-divider oj-menu-item-after-divider");
b.prev().addClass("oj-menu-item-before-divider");b.next().addClass("oj-menu-item-after-divider")},dT:function(a){return a.prev("a")},XKa:function(){return"menuitem"},zI:function(a,b){var c=a.prev(".oj-menu-divider").add(a.next(".oj-menu-divider"));b&&(c=c.add(a));return c},Mi:function(a,b){a&&"focus"===a.type||clearTimeout(this.Le);b=b.first();this.Y9(b,a);var c=b.parent(),d=c.closest(".oj-menu-item");c.find(".oj-focus-ancestor").removeClass("oj-focus-ancestor");this.zI(d,!0).addClass("oj-focus-ancestor");
a&&"keydown"===a.type?this.bq():this.Le=this._delay(function(){delete this.Le;this.bq()},this.delay);c=b.children(".oj-menu");c.length&&a&&/^mouse/.test(a.type)&&!this.ab.hasClass("oj-disabled")&&this.FCa(c);this.bw=b.parent()},Y9:function(a,b){if(!a.is(this.ab)){var c=this.ab?this.ab:g(),d=a.children("a");this.ab=a;this.element.attr("aria-activedescendant",d.attr("id"));this.dv(c);this.qy(a);this.zI(c).removeClass("oj-focus");this.zI(a).addClass("oj-focus");this._trigger("_activeItem",b,{previousItem:c,
item:a,privateNotice:"The _activeItem event is private.  Do not use."})}},fAa:function(a){if(this.ab){var b=this.ab;this.ab=null;this.element.removeAttr("aria-activedescendant");this.dv(b);this.zI(b).removeClass("oj-focus");this._trigger("_activeItem",a,{previousItem:b,item:g(),privateNotice:"The _activeItem event is private.  Do not use."})}},yQ:function(a){clearTimeout(this.Le);this.fAa(a)},EC:function(a,b){this.Id.focus();this.Nu(a,b)},Nu:function(c,d){var e=this.element.is(":visible"),f={};f[a.U.qb.Bh]=
this.element;a.U.Je().close(f);this.element.removeData("oj-menu-position");this.Id=void 0;this.Vba=!1;d&&(c=this.xW("select",c,d).event);e&&this._trigger("close",c,{});this.ls=null;0<=b.indexOf(this)&&b.splice(b.indexOf(this),1)},getCurrentOpenOptions:function(){return g.extend(!0,{},this.ls||this.options.openOptions)},open:function(c,d,e){d=g.extend({},this.options.openOptions,d);d.position=g.extend({},d.position);e=g.extend({},this.options.submenuOpenOptions,e);var f=this.ls;this.ls=d;a.Qd.Mya(c);
this.Sxa=this.qH;var h=this.xW("beforeOpen",c,{openOptions:d});if(h.proceed)if(this.element.is(":visible")&&(this.ls=f,this.Nu(h.event),this.ls=d),f=d.launcher,(f="string"===g.type(f)?g(f):f)&&f.length){h=this.rxa(d.display);this.cDa(h);var k,n;if(h){if(this.element.addClass("oj-menu-dropdown").removeClass("oj-menu-sheet"),n=l,k=a.Qd.km(d.position,this.Xk),k.of=a.Qd.mIa(k.of,f,c),null==k.of){a.r.warn("position.of passed to Menu.open() is 'event', but the event is null.  Ignoring the call.");this.ls=
null;return}}else this.element.addClass("oj-menu-sheet").removeClass("oj-menu-dropdown"),n=m,k={my:"bottom",at:s,of:window,collision:"flipfit"};var r=this.element[0],t=b.slice(0,b.length);g.each(t,function(a,b){b.element[0]!==r&&(b.oo(c,"eventSubtree"),b.Id&&b.Nu(c))});this.JCa=a.Qd.km(e.position,this.Xk);e=this.zE;g.isFunction(k.using)&&k.using!==e&&(k.origUsing=k.using);k.using=e;e={};e[a.U.qb.Bh]=this.element;e[a.U.qb.aB]=f;e[a.U.qb.eB]=k;e[a.U.qb.fu]=this.wy();e[a.U.qb.Gr]="oj-menu-layer";e[a.U.qb.gk]=
n;a.U.Je().open(e);this.element.data("oj-menu-position",k);d=d.initialFocus;((e="firstItem"===d)||"menu"===d)&&this.element.focus();e?this.Mi(c,this.element.children().first()):this.yQ(c);this.Id=f;this.Vba=!h;b.push(this);this._trigger("open",c,{})}else a.r.warn("When calling Menu.open(), must specify openOptions.launcher via the component option, method param, or beforeOpen listener.  Ignoring the call."),this.ls=null;else this.ls=f},FCa:function(a){clearTimeout(this.Le);"true"===a.attr("aria-hidden")&&
(this.Le&&clearTimeout(this.Le),this.Le=this._delay(function(){delete this.Le;this.bq();this.x$(a)},this.delay))},x$:function(a){var c=g.extend({of:this.ab},this.JCa);clearTimeout(this.Le);this.element.find(".oj-menu").not(a.parents(".oj-menu")).hide().attr("aria-hidden","true").removeData("oj-menu-position");a.show().removeAttr("aria-hidden").position(c).data("oj-menu-position",c);this.dT(a).attr("aria-expanded","true");!this.Id&&0>b.indexOf(this)&&b.push(this)},pH:function(a,b,c){function d(){delete e.Le;
var c=b?e.element:g(a&&a.target).closest(e.element.find(".oj-menu"));c.length||(c=e.element);e.bq(c);e.yQ(a);e.bw=c}clearTimeout(this.Le);var e=this;c?this.Le=this._delay(d,c):d()},bq:function(a){a||(a=this.ab?this.ab.parent():this.element);var c=a.find(".oj-menu");c.hide().attr("aria-hidden","true").removeData("oj-menu-position");this.dT(c).attr("aria-expanded","false");a.find(".oj-focus-ancestor").removeClass("oj-focus-ancestor");this.Id||0<=b.indexOf(this)&&a===this.element&&b.splice(b.indexOf(this),
1)},oo:function(b,c){if(null==c||"active"===c){var d=this.bw&&this.bw.closest(".oj-menu-item",this.element);d&&d.length&&(this.bq(),this.Mi(b,d))}else"all"===c||"eventSubtree"===c?this.pH(b,"all"===c,this.delay):a.r.warn("Invalid param "+c+" passed to Menu._collapse().  Ignoring the call.")},bg:function(a){var b=this.ab&&this.ab.children(".oj-menu ").children(".oj-menu-item").first();b&&b.length&&(this.x$(b.parent()),this.Le&&clearTimeout(this.Le),this.Le=this._delay(function(){delete this.Le;this.Mi(a,
b)}))},p$:function(a){this.VJ("next","first",a)},tza:function(a){this.VJ("prev","last",a)},TKa:function(){return this.ab&&!this.ab.prevAll(".oj-menu-item").length},UKa:function(){return this.ab&&!this.ab.nextAll(".oj-menu-item").length},VJ:function(a,b,c){var d;this.ab&&(d="first"===a||"last"===a?this.ab["first"===a?"prevAll":"nextAll"](".oj-menu-item").eq(-1):this.ab[a+"All"](".oj-menu-item").eq(0));d&&d.length&&this.ab||(d=this.bw.children(".oj-menu-item")[b]());this.Mi(c,d)},kn:function(b){if(!this.ab&&
b&&b.target){var c=g(b.target).closest(".oj-menu-item");c.closest(this.element).length&&this.Y9(c,b)}this.ab?this.ab.has(".oj-menu").length||this.ab.is(".oj-disabled")?a.r.warn("Selecting a disabled menu item or parent menu item is not allowed."):(c=this.ab.is(this.MH)?void 0:{item:this.ab},this.pH(b,!0),this.Id&&this.EC(b,c)):a.r.warn("Menu._select() called when no menu item is focused and no menu item can be inferred from event param.")},Xv:function(){this.element.remove()},wy:function(){if(!this.hn){var b=
this.hn={};b[a.U.Fd.kx]=g.proxy(this.p4,this);b[a.U.Fd.lx]=g.proxy(this.Xv,this);b[a.U.Fd.Mp]=g.proxy(this.refresh,this);b[a.U.Fd.jx]=g.proxy(this.dR,this)}return this.hn},p4:function(){this.bq(this.element);this.Nu(null)},AE:function(b,c){var d=c.element.element;d.css(b);(d=d.data("oj-menu-position"))&&(d=d.origUsing)&&d(b,c);a.Qd.nY(c)&&(this.fs=this._delay(g.proxy(this.p4,this),1))},getNodeBySubId:function(a){switch(a&&a.subId){case n:return this.RQ?this.MH[0]:null;default:return this._super(a)}},
getSubIdByNode:function(a){return this.MH&&this.MH.is(a)?n:this._super(a)},rxa:function(a){if(this.swa)return!0;switch(a){case "dropDown":return!0;case "sheet":return!1;case "auto":return r.matches;default:throw Error("Invalid value for Menu openOptions.display: "+a);}},cDa:function(a){h&&(a?this.RQ&&(this.o6().detach().eq(0).prev().removeClass("oj-menu-item-before-divider"),this.RQ=!1):(this.o6().appendTo(this.element).eq(0).prev().addClass("oj-menu-item-before-divider"),this.RQ=!0))},o6:function(){if(!this.LH){var a=
g("\x3cli\x3e\x3c/li\x3e",this.document[0]),b=g("\x3ca href\x3d'#'\x3e\x3c/a\x3e",this.document[0]).text(this.options.translations.labelCancel);g("\x3cspan class\x3d'oj-menu-item-icon oj-component-icon oj-menu-cancel-icon'\x3e\x3c/span\x3e",this.document[0]).prependTo(b);var c=g("\x3cli\x3e\x3c/li\x3e",this.document[0]).addClass("oj-menu-item-cancel oj-menu-item-after-divider").append(b);this.U8(a);this.N8(b);this.Y8(c);this.Z3=b;this.MH=c;this.LH=g([a[0],c[0]])}return this.LH},qCa:function(){k&&
(this.element.$j(t),this._on({swipedown:function(a){this.Vba&&"touch"===a.gesture.pointerType&&(this.pH(a,!0),this.EC(a))}}))}});var b=[],d=!1,e=-1<navigator.userAgent.indexOf("Macintosh")&&-1<navigator.userAgent.indexOf("Safari")&&-1===navigator.userAgent.indexOf("Chrome"),f=a.nd.uf("oj-menu-config")||{},h="menuItem"===f.sheetCancelAffordance,k="dismiss"===f.sheetSwipeDownBehavior,l=f.dropDownModality||"modeless",m=f.sheetModality||"modal",s="bottom-"+(f.sheetMarginBottom||0),t=k&&{recognizers:[[c.Swipe,
{direction:c.DIRECTION_DOWN}]]},r=function(){var a=f.dropDownThresholdWidth;null==a&&(a="768px");return window.matchMedia("(min-width: "+a+")")}(),n="oj-menu-cancel-command"})();a.Components.Ta("ojMenu","baseComponent",{properties:{disabled:{type:"boolean"},menuSelector:{type:"string"},openOptions:{type:"Object"},submenuOpenOptions:{type:"Object"}},methods:{destroy:{},getCurrentOpenOptions:{},getSubIdByNode:{},open:{},refresh:{},widget:{}},extension:{_hasWrapper:!0,_innerElement:"ul",_widgetName:"ojMenu"}});
a.Components.register("oj-menu",a.Components.getMetadata("ojMenu"))});