/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojbutton","ojs/ojmenu","ojs/ojlistview"],function(a,g){a.ff=function(a,c,e){this.C=a;this.ea=c;this.EY=e};a.ff.prototype.Vg=function(){this.ea.removeClass("oj-navigationlist-expanded oj-navigationlist-vertical")};a.ff.prototype.bx=function(){return Promise.resolve(null)};a.ff.prototype.Zw=function(){return Promise.resolve(null)};a.ff.prototype.w_=function(){return!1};a.ff.prototype.sO=function(){};a.ff.prototype.KO=function(a,c){a.attr("aria-selected",
c?"true":"false")};a.ff.prototype.RN=function(){};a.ff.prototype.A_=function(){};a.ff.prototype.B_=function(){};a.ff.prototype.mu=function(a,d,e){return c.t.mu.apply(this.C,arguments)};a.ff.prototype.ex=function(a){return c.t.ex.apply(this.C,arguments)};a.ff.prototype.Zg=function(a){return c.t.Zg.apply(this.C,arguments)};a.ff.prototype.su=function(a,d){c.t.su.apply(this.C,arguments)};a.ff.prototype.Init=function(){this.ea.addClass("oj-navigationlist-expanded oj-navigationlist-vertical")};a.ff.prototype.ek=
function(a){return c.t.ek.apply(this.C,arguments)};a.ff.prototype.fB=function(){};a.ff.prototype.f_=function(){};a.ff.prototype.Pw=function(){};a.Di=function(b,c,e){a.Di.t.constructor.call(this,b,c,e)};a.b.ta(a.Di,a.ff,"oj.HorizontalNavListHandler");a.Di.prototype.Vg=function(){this.ea.removeClass("oj-navigationlist-expanded oj-navigationlist-horizontal");this.ea.find("."+this.C.ax).remove()};a.Di.prototype.KO=function(a,c){a.attr("aria-pressed",c?"true":"false")};a.Di.prototype.mu=function(a,d,e){a===
g.ui.keyCode.LEFT?a=this.C.Xk()?g.ui.keyCode.DOWN:g.ui.keyCode.UP:a===g.ui.keyCode.RIGHT&&(a=this.C.Xk()?g.ui.keyCode.UP:g.ui.keyCode.DOWN);a=c.t.mu.call(this.C,a,d,e);"top"===this.C.Y.options.edge&&this.C.N.elem[0].scrollIntoView(!1);return a};a.Di.prototype.ex=function(a){return a===this.C.ll||a===this.C.cl||a===this.C.wg||a===this.C.dh};a.Di.prototype.sO=function(a){a=this.C.eM(a);a.attr("role","button");a[0].hasAttribute("aria-selected")&&(a.attr("aria-pressed","false"),a.removeAttr("aria-selected"))};
a.Di.prototype.RN=function(){var a=this;this.C.element.attr("role","toolbar");this.C.element.find("."+this.C.rh()+":visible").each(function(c){0<c&&a.V2(this,c)})};a.Di.prototype.V2=function(a,c){var e=g(a),f=e.prev();0<c&&e.is(":visible")&&f.length&&!f.is("li."+this.C.ax)&&e.before('\x3cli role\x3d"separator" class\x3d"'+this.C.ax+'"\x3e\x3c/li\x3e')};a.Di.prototype.A_=function(a,c){this.V2(a,c.index)};a.Di.prototype.B_=function(a){a=g(a);var c=a.prev();c.length&&c.is("li."+this.C.ax)?c.remove():
(a=a.next(),a.is("li."+this.C.ax)&&a.remove())};a.Di.prototype.ek=function(a){return this.C.lg(g(a))[0].hasAttribute("aria-pressed")};a.Di.prototype.Init=function(){this.ea.addClass("oj-navigationlist-expanded oj-navigationlist-horizontal")};a.Di.prototype.fB=function(){};a.Qn=function(b,c,e){a.Qn.t.constructor.call(this,b,c,e)};a.b.ta(a.Qn,a.ff,"oj.CollapsibleNavListHandler");a.Qn.prototype.Vg=function(){this.ea.removeClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};a.Qn.prototype.Init=
function(){this.ea.addClass("oj-navigationlist-collapsible oj-navigationlist-vertical")};a.Qn.prototype.bx=function(a,d,e){return c.t.ON.apply(this.C,arguments)};a.Qn.prototype.Zw=function(a,d,e){return c.t.MN.apply(this.C,arguments)};a.Qn.prototype.w_=function(a,c,e,f){var h=0<e.children("."+this.C.li()).length;if(c===this.C.wg||c===this.C.dh)return c===this.C.wg&&!this.C.Xk()||c===this.C.dh&&this.C.Xk()?this.C.Zg(e)===this.C.Cm&&this.C.Cr(e,a,!0,f,!0,!0):this.C.Zg(e)===this.C.Bm&&this.C.gu(e,a,
!0,f,!0,!0,!0),!0;if(h&&(c===g.ui.keyCode.ENTER||c===g.ui.keyCode.SPACE)){if(0>=e.length)return;this.C.Zg(e)===this.C.Bm?this.C.gu(e,null,!0,f,!0,!0,!0):this.C.Zg(e)===this.C.Cm&&this.C.Cr(e,null,!0,f,!0,!0);return!0}return!1};a.Qn.prototype.fB=function(){};a.Oe=function(b,c,e){a.Oe.t.constructor.call(this,b,c,e);this.MY=[]};a.b.ta(a.Oe,a.Qn,"oj.SlidingNavListHandler");a.Oe.prototype.Vg=function(){this.ea.removeClass("oj-navigationlist-slider oj-navigationlist-vertical");this.UK.remove()};a.Oe.prototype.eca=
function(a,c,e,f,g){var k=this,l=this.C.Uk(),m=l.outerWidth()/2,s=this.C.Xk();c||(m*=-1);var t=this.C.Uk().hasClass("oj-focus-ancestor");s?(l.css({"margin-right":m}),l.animate({"margin-right":"0px"},400,"swing",function(){k.OK(a,c,e,f,t);g(null)})):(l.css({"margin-left":m}),l.animate({"margin-left":"0px"},400,"swing",function(){k.OK(a,c,e,f,t);g(null)}))};a.Oe.prototype.OK=function(a,c,e,f,g){null!==this.C.qf&&(e&&(g&&this.C.Uk().addClass("oj-focus-ancestor"),f&&0===f.button&&this.C.a_(!0),this.C.lG(e,
f),this.C.a_(!1)),c?this.C.PN(a.children("."+this.C.li())):this.C.NN(a.children("."+this.C.li())))};a.Oe.prototype.bx=function(a,c,e){var f,h=new Promise(function(a){f=a}),k=g(a).parents(".oj-navigationlist-item-element:first"),l=k.children("."+this.C.li()),m,s=null,t=k.closest("."+this.C.Ir);if(0<t.length){t.removeClass(this.C.Ir);k.addClass(this.C.Ir);var s=l.find("."+this.C.rh()+":eq(0)"),r=k.parentsUntil(t,"ul"),r=t.is(this.C.element)?r.get().concat(t.get()):r.get(),n=this,p,r=g(r.reverse());
r.each(function(a,b){m=g(b).is(n.C.element)?n.C.cM():n.C.QX(g(b).parent());p=a===r.length-1?k:g(r.get(a+1)).parent();n.Gna(n.C.ug(p[0]),n.C.QX(p),m);n.MY.push(p)})}c?this.eca(k,!0,s,e,f):(this.OK(k,!0,s,e,!1),f(null));this.C.element.focus();k.siblings().attr("aria-hidden","true");k.children("."+this.C.mg()).children("."+this.C.Un).attr("aria-hidden","true");l.removeAttr("aria-hidden");a.css("display","");k.addClass("oj-skipfocus");return h};a.Oe.prototype.Zw=function(a,c,e){var f,g=new Promise(function(a){f=
a}),k=a.children("."+this.C.li()),l=a.parent();a.children("."+this.C.mg()).children("."+this.C.Un).removeAttr("aria-hidden");k.attr("aria-hidden","true");a.siblings().removeAttr("aria-hidden");a.removeClass("oj-skipfocus");a.removeClass(this.C.Ir);0===a.closest("."+this.C.Ir).length&&(l.closest("."+this.C.rh()).addClass(this.C.Ir),this.C.element.is(l)&&this.C.element.addClass(this.C.Ir));c?this.eca(a,!1,k.parent(),e,f):(this.OK(a,!1,k.parent(),e,!1),f(null));this.uAa();this.C.element.focus();return g};
a.Oe.prototype.KO=function(a,c){c?a.attr("aria-describedby","selectedLabel"):a.removeAttr("aria-describedby")};a.Oe.prototype.Zg=function(a){a=this.C.lg(a).attr("aria-expanded");return"true"===a?this.C.Cm:"false"===a?this.C.Bm:this.C.Z_};a.Oe.prototype.su=function(a,c){c===this.C.Cm?(this.C.lg(a).attr("aria-expanded","true"),a.removeClass(this.C.c_).addClass(this.C.l_)):c===this.C.Bm&&(this.C.lg(a).attr("aria-expanded","false"),a.removeClass(this.C.l_).addClass(this.C.c_))};a.Oe.prototype.sO=function(a,
c){var e=this.C.lg(a);e.attr("role","menuitem");c.attr("id")||c.uniqueId();var f=a.children("."+this.C.li());0<f.length&&(e.attr("aria-haspopup","true"),f.attr("role","menu"),f.css("display",""),a.removeAttr("aria-expanded"),e.attr("aria-expanded","false"))};a.Oe.prototype.RN=function(){this.C.element.attr("role","menu")};a.Oe.prototype.Init=function(a){this.ea.addClass("oj-navigationlist-slider oj-navigationlist-vertical");a.element.addClass("oj-navigationlist-current");this.Hoa(a);this.$wa()};a.Oe.prototype.Hoa=
function(a){var c;this.UK=g(document.createElement("div"));this.UK.addClass("oj-navigationlist-toolbar");this.xq=g(document.createElement("a"));this.JD=g(document.createElement("span"));this.JD.addClass("oj-navigationlist-previous-icon oj-component-icon oj-clickable-icon-nocontext").attr("role","img").attr("alt",this.EY.F("previousIcon"));this.JD.css("visibility","hidden");this.xq.addClass("oj-navigationlist-previous-link").attr("tabindex","-1").append(this.JD);this.bD=g(document.createElement("label"));
this.bD.addClass("oj-navigationlist-current-header").text(this.C.cM());this.jL=g(document.createElement("span"));this.jL.attr("role","separator").attr("aria-orientation","vertical").addClass("oj-navigationlist-toolbar-separator");this.Ek=g(document.createElement("button"));this.Ek.addClass("oj-navigationlist-hierarchical-button");this.Th=g(document.createElement("ul"));this.Th.addClass("oj-navigationlist-hierarchical-menu").hide();c=g(document.createElement("label"));c.addClass("oj-helper-hidden-accessible").attr("aria-hidden",
"true").attr("id","selectedLabel");c.text(this.EY.F("selectedLabel"));this.xq.append(this.bD);this.UK.append(this.xq).append(this.jL).append(this.Ek).append(this.Th).append(c);this.ea.prepend(this.UK);this.LK(a.hierarchyMenuDisplayThresholdLevel)};a.Oe.prototype.f_=function(a){var c=this.MY.pop();c&&this.C.Cr(c,a,!0,null,!0,!0)};a.Oe.prototype.$wa=function(){var a=this,c=this.Th.uniqueId().attr("id");this.Th.ojMenu({openOptions:{position:{my:"end top",at:"end bottom"}},select:function(c,d){for(var h=
d.item.nextAll(),k,l,m=a.MY,s=d.item.data("key");0<m.length&&(l=m.pop(),k=a.C.ug(l[0]),a.C.Cr(g(l),c,!0,k,!0,!0),s!==k););h.remove();d.item.remove();a.Th.ojMenu("refresh")}});this.Ek.ojButton({label:this.EY.F("hierMenuBtnLabel"),display:"icons",icons:{start:"oj-fwk-icon oj-hier-icon"},menu:"#"+c,disabled:!0,chroming:"half"})};a.Oe.prototype.Gna=function(a,c,e){var f;if(this.Ek){var h=this.Th.find("li").length,k=g(document.createElement("li")),l=g(document.createElement("a"));l.attr("href","#");k.append(l);
if(0<h){for(f=0;f<h;f++)0<f&&l.append(g(document.createElement("span")).addClass("oj-navigationlist-hvitem-space"));l.append(g(document.createElement("span")).addClass("oj-menu-item-icon oj-icon oj-navigationlist-level-indicator"))}f=g(document.createElement("span")).addClass("oj-navigationlist-hierarchical-menu-label");f.text(e);l.append(f);k.data("key",a);this.Th.append(k);this.Th.ojMenu("refresh");this.LK(this.C.me("hierarchyMenuDisplayThresholdLevel"));this.Ek.ojButton("option","disabled",!1);
this.JD.css("visibility","visible");this.xq.attr("tabindex","0");this.bD.text(c)}};a.Oe.prototype.Pw=function(a){this.C.me("hierarchyMenuDisplayThresholdLevel")!==a.hierarchyMenuDisplayThresholdLevel&&this.LK(a.hierarchyMenuDisplayThresholdLevel)};a.Oe.prototype.LK=function(a){var c=this.Th.find("li").length;-1===a||c<a?(this.jL.css("visibility","hidden"),this.Ek.css("visibility","hidden")):c>=a&&(this.jL.css("visibility","visible"),this.Ek.css("visibility","visible"))};a.Oe.prototype.uAa=function(){if(this.Ek){var a=
this.Th.find("li").last().remove();this.Th.ojMenu("refresh");this.LK(this.C.me("hierarchyMenuDisplayThresholdLevel"));0===this.Th.children("li").length?(this.Ek.ojButton("option","disabled",!0),this.JD.css("visibility","hidden"),this.xq.attr("tabindex","-1"),this.bD.text(this.C.cM())):this.bD.text(a.children("a").text())}};a.Oe.prototype.fB=function(a,c){a.removeClass(this.C.Ir);c.removeAttr("role").removeAttr("aria-expanded").removeAttr("aria-describedby").removeAttr("aria-hidden")};var c=function(b,
c){function e(){}a.b.ta(e,b,"");g.extend(e.prototype,c);return e}(a.SU,{Un:"oj-navigationlist-item-content",l_:"oj-expanded",c_:"oj-collapsed",Ir:"oj-navigationlist-current",ax:"oj-navigationlist-divider",yka:"oj-navigationlist-category-divider",kP:"oj-navigationlist-item-label",f1:"oj-navigationlist-icon-only",l1:"oj-navigationlist-item-icon",gKa:"oj-navigationlist-horizontal",F1:"oj-navigationlist-has-icons",G1:"oj-navigationlist-item-no-icon",Tla:"oj-navigationlist-item-title",H1:"oj-navigationlist",
I1:"oj-navigationlist-touch",Ula:"oj-navigationlist-listview-container",MG:"IsTitleAttrDueToTruncation",QO:"oj-navigationlist-app-level",yP:"oj-navigationlist-page-level",tP:"navigationListItemIconHastitle",Vla:"oj-navigationlist-nofollow-link",QX:function(a){a=this.$L(a);return a.is("a")?g.trim(a.text()):g.trim(a.find("."+this.Tla).text())},$L:function(a){var c=a.children("."+this.Un);0===c.length&&(c=a.children("."+this.mg()).children("."+this.Un),0===c.length&&(c=a.children("."+this.mg()).children(":not(."+
this.Rq()+"):not(."+this.vn()+")")));return c},Xk:function(){return"rtl"===this.Y.hd()},St:function(){this.bd.RN();c.t.St.apply(this,arguments)},pga:function(a,c){this.bd.A_(a,c)},vY:function(a){this.bd.B_(a);c.t.vY.apply(this,arguments)},Xaa:function(a){var c,e,f,h=a.children();a.removeAttr("style").removeClass(this.F1).removeAttr("aria-hidden");for(a=0;a<h.length;a++)c=h[a],c=g(c),c.hasClass(this.ax)?c.remove():(e=this.$L(c),e.removeClass(this.Un).removeClass(this.G1).removeAttr("aria-haspopup"),
(f=e.children("."+this.l1))&&0<f.length&&(f.removeAttr("role"),f.removeAttr("aria-label"),this.GAa(f)),c.removeClass("oj-default").removeAttr("role").removeAttr("aria-disabled").removeAttr("aria-expanded").removeAttr("aria-hidden").removeAttr("aria-pressed"),f=this.lg(c),f.removeAttr("role").removeAttr("aria-hidden").removeAttr("aria-pressed"),e.children("."+this.kP).contents().unwrap(),f.data(this.MG)&&f.removeAttr("title"),f=c.children("ul"),0<f.length?(this.bd.fB(c,e,f),this.Xaa(f)):this.bd.fB(c,
e))},oG:function(a){return a.hasClass(this.Un)||a.hasClass(this.Rq())||a.hasClass(this.vn())?!1:c.t.oG.apply(this,arguments)},z_:function(a){return a.prop("nodeName").match(/^INPUT|SELECT|OPTION|BUTTON|^A\b|TEXTAREA/)&&!a.hasClass(this.Un)||a.hasClass("oj-component")},oza:function(a){var c={drillMode:"none"!==a.drillMode?"collapsible":"none",selection:null!==a.selection?[a.selection]:[],item:a.item,data:a.data,selectionMode:"single"};c.element=this.Ns;c.item.focusable=function(a){return g(a.data).is("li")?
!g(a.data).hasClass("oj-disabled"):!g(a.parentElement).hasClass("oj-disabled")};return c=g.extend(g.extend({},a),c)},cM:function(){return this.Y.options.rootLabel?this.Y.options.rootLabel:this.Y.F("defaultRootLabel")},iB:function(){var a=this.Y.element.attr("aria-labelledby");a?(this.element.attr("aria-labelledby",a),this.Y.element.removeAttr("aria-labelledby")):this.element.attr("aria-label",this.cM());c.t.iB.apply(this,arguments)},JO:function(){this.element.attr("aria-labelledby")&&(this.Y.element.attr("aria-labelledby",
this.element.attr("aria-labelledby")),this.element.removeAttr("aria-labelledby"));this.element.attr("aria-label")&&this.element.removeAttr("aria-label");c.t.JO.apply(this,arguments)},Yq:function(b){var d=this,e=b.Y.element;e.addClass(this.H1);a.u.af()&&e.addClass(this.I1);this.Ns=e.children("ul:first");0===this.Ns.length&&(this.Ns=g(document.createElement("ul")),e.append(this.Ns));e=g(document.createElement("div"));e.addClass(this.Ula);this.Ns.wrap(e);b=this.oza(b);c.t.Yq.call(this,b);this.element.removeClass("oj-component-initnode");
this.Y._on(this.Y.element,{mouseup:function(a){d.aR(a)},"click .oj-navigationlist-previous-link":function(a){d.iR(a)},"keydown .oj-navigationlist-previous-link":function(a){a.keyCode===g.ui.keyCode.ENTER&&d.iR(a)},"keydown .oj-navigationlist-element":function(a){a.keyCode!==g.ui.keyCode.ESCAPE||a.isDefaultPrevented()||d.iR(a)},"mouseenter a.oj-navigationlist-item-content":function(a){a=g(a.currentTarget);var b=a.find("."+d.kP);b[0].offsetWidth<b[0].scrollWidth&&!a.attr("title")&&(a.attr("title",b.text().trim()),
a.data(d.MG,"true"))},"mouseleave a.oj-navigationlist-item-content":function(a){var b=g(a.currentTarget);b.data(d.MG)&&(b.removeData(d.MG),b.removeAttr("title"));d.aR(a)}})},iR:function(a){this.bd.f_(a)},X8:function(){var b=this.Y.options.drillMode,c=this.Y.options.edge;this.bd="sliding"===b?new a.Oe(this,this.Y.element,this.Y):"collapsible"===b?new a.Qn(this,this.Y.element,this.Y):"none"===b&&"top"===c?new a.Di(this,this.Y.element,this.Y):new a.ff(this,this.Y.element,this.Y);this.bd.Init(this.options);
this.Bba(this.Y.options.navigationLevel)},Bba:function(a){"none"===this.Y.options.drillMode&&("application"===a?(this.Y.element.addClass(this.QO),this.Y.element.removeClass(this.yP)):"page"===a&&(this.Y.element.addClass(this.yP),this.Y.element.removeClass(this.QO)))},aR:function(a){a=this.xm(g(a.target));null!=a&&this.ZA(a,"oj-active",!1)},Cz:function(){this.X8();c.t.Cz.apply(this,arguments)},nG:function(a){c.t.nG.apply(this,arguments);var d=this.xm(g(a.target));d&&!d.hasClass("oj-disabled")&&this.ZA(d,
"oj-active",!0)},XA:function(a){this.aR(a);c.t.XA.apply(this,arguments)},r_:function(){return"oj-navigationlist-listview"},eO:function(){return"oj-navigationlist-element"},Vi:function(){return"oj-navigationlist-item"},hp:function(){return"oj-navigationlist-focused-element"},rh:function(){return"oj-navigationlist-item-element"},vn:function(){return"oj-navigationlist-collapse-icon"},Rq:function(){return"oj-navigationlist-expand-icon"},LX:function(a){return"oj-navigationlist-depth-"+a},mg:function(){return"oj-navigationlist-group-item"},
li:function(){return"oj-navigationlist-group"},Tz:function(){return"oj-navigationlist-collapsible-transition"},kw:function(){return this.Tz()},ON:function(a,c,e){return this.bd.bx(a,c,e)},MN:function(a,c,e){return this.bd.Zw(a,c,e)},mu:function(a,c,e){return this.bd.mu(a,c,e)},ex:function(a){return this.bd.ex(a)},Zg:function(a){return this.bd.Zg(a)},su:function(a,c){this.bd.su(a,c)},jO:function(a){var d=this.xm(g(a.target));null!=d&&0!==d.length&&(this.lk(d)?a.preventDefault():this.oG(g(a.target))||
(d=this.$L(d).attr("href"),d&&"#"!==d&&0===a.button&&(a.shiftKey||a.ctrlKey)||(c.t.jO.apply(this,arguments),a.preventDefault())))},mG:function(a){var c,e,f;if(this.N)if(c=a.keyCode,e=this.N.elem,f=this.N.key,c===g.ui.keyCode.HOME||c===g.ui.keyCode.END){var h;h=c===g.ui.keyCode.HOME?this.element.find("."+this.Un+":visible").first().closest("."+this.rh()):this.element.find("."+this.Un+":visible").last().closest("."+this.rh());this.lG(h,a);a.preventDefault()}else h=this.x_(a),c=this.bd.w_(a,c,e,f),!0!==
h&&!0!==c||a.preventDefault()},a_:function(a){this.qoa=a},W_:function(){var a=this;return function(){return!!a.qoa}},i0:function(){return!0},vG:function(a,d,e){var f=this.N.elem;this.ek(f[0])&&!this.uU(f)&&this.eS(a,f)&&(c.t.vG.apply(this,arguments),this.iU(f))},ZA:function(a,c,e){var f;a=g(a);"oj-selected"===c&&this.bd.KO(this.lg(a),e);f=a.children("."+this.mg());0<f.length&&(a=g(f[0]));"oj-focus"===c?e?this.qy(a):this.dv(a):e?a.addClass(c):a.removeClass(c);a.hasClass("oj-selected")||a.hasClass("oj-hover")||
a.hasClass("oj-active")||a.hasClass("oj-disabled")?a.removeClass("oj-default"):a.addClass("oj-default")},ek:function(a){return!g(a).hasClass("oj-disabled")&&this.bd.ek(g(a))},mk:function(a,c,e){return"ready"!==a?this.Y._trigger(a,c,e):!0},ik:function(a,c,e){if("selection"===a){var f=e._context,g=f&&f.Ok&&f.Ok.items;g&&(f.Ok.item=g,f.Ok.items=void 0);c&&0<c.length?this.Y.option(a,c[0],e):this.Y.option(a,null,e)}else this.Y.option(a,c,e);this.options[a]=c},j0:function(a){return null!=a.data||null!=
a.drillMode||null!=a.item||null!=a.display||null!=a.edge},lt:function(a){return"pointerUp"===a?"none":c.t.lt.call(this,a)},Pw:function(a,d){var e={mia:[]},f;void 0!==a.hierarchyMenuDisplayThresholdLevel&&this.bd.Pw(a);void 0!==a.navigationLevel&&this.Bba(a.navigationLevel);void 0!==a.selection&&(f=a.selection);e.iIa=c.t.Pw.call(this,a,d);void 0!==f&&void 0===a.selection&&e.mia.push("selection");void 0!==f&&(a.selection=f);return e},kO:function(a){var d;if(void 0!==a.selection)if(d=a.selection){var e=
this.me("selection");e&&0!==e.length&&e[0]===d?delete a.selection:(e=this.Ne(d))&&this.ek(e)?this.eS(null,g(e))?(a.selection=[d],this.iU(g(e))):delete a.selection:delete a.selection}else a.selection=[];c.t.kO.call(this,a)},me:function(a){var c=this.Y.option(a);return"selection"===a?c?[c]:[]:null===c?this.options[a]:c},Mf:function(){return a.Components.Mf(this.Y.element)},hB:function(a,d){!a.hasClass("oj-disabled")&&this.ek(a[0])&&(!this.uU(a)&&this.eS(d,a)?(c.t.hB.apply(this,arguments),this.iU(a)):
this.lG(a,d))},eS:function(a,c){var e=this.ug(c[0]);return this.mk("beforeSelect",a,{item:c,key:e})},iU:function(a){return this.Y.element.hasClass(this.Vla)?!1:(a=this.$L(a).attr("href"))&&"#"!==a?(window.location.href=a,!0):!1},uU:function(a){var c;c=this.me("selection");a=this.ug(a[0]);return-1<c.indexOf(a)?!0:!1},hCa:function(a,c){a.attr("title")||a.attr("title",c)},GAa:function(a){a.data(this.tP)?a.removeData(this.tP):a.removeAttr("title")},uw:function(a,d){var e=g(a);if(e.hasClass(this.yka))e.removeClass(this.rh()),
e.removeClass(this.hp()),e.removeClass(this.Vi()),e.removeAttr("aria-selected"),e.children().remove(),e.attr("role","separator");else{var f=this.vn(),h=this.Rq(),k=this.l1,l=e.children("."+this.mg()),m;0<l.length?(l.addClass(this.Vi()),m=l.children(":not(."+h+"):not(."+f+")"),h=l.children("."+h),0===h.length&&(h=l.children("."+f)),h.attr("role","presentation"),h.removeAttr("aria-labelledby"),e.hasClass("oj-disabled")&&l.addClass("oj-disabled")):m=e.children().first();m.addClass(this.Un);f=m.wrapInner('\x3cspan class\x3d"'+
this.kP+'"\x3e\x3c/span\x3e').find("."+k);0<f.length?(f.insertBefore(f.parent()),f.attr("title")&&f.data(this.tP,f.attr("title")),"icons"===this.Y.options.display&&(this.Y.element.addClass(this.f1),k=this.QX(e),f.attr("aria-label",k),f.attr("role","img"),this.hCa(f,k)),e.closest("ul").addClass(this.F1)):m.addClass(this.G1);e.hasClass("oj-disabled")?this.lg(e).attr("aria-disabled","true"):0<l.length?l.addClass("oj-default"):e.addClass("oj-default");this.bd.sO(e,m);c.t.uw.apply(this,arguments)}},getNodeBySubId:function(a){var c;
if(null===a)return this.element?this.element[0]:null;c=a.subId;return"oj-navigationlist-item"===c?(a=a.key,a=this.Ne(a)):"oj-navigationlist-previous-link"===c?this.bd.xq?this.bd.xq[0]:null:"oj-navigationlist-hierarchical-button"===c?this.bd.Ek?this.bd.Ek[0]:null:"oj-navigationlist-hierarchical-menu"===c?this.bd.Th?this.bd.Th[0]:null:null},getSubIdByNode:function(a){if(this.bd.xq&&this.bd.xq[0]===a)return{subId:"oj-navigationlist-previous-link"};if(this.bd.Ek&&this.bd.Ek[0]===a)return{subId:"oj-navigationlist-hierarchical-button"};
if(this.bd.Th&&this.bd.Th[0]===a)return{subId:"oj-navigationlist-hierarchical-menu"};a=this.xm(a);return null!=a&&0<a.length&&(a=this.ug(a[0]),null!=a)?{subId:"oj-navigationlist-item",key:a}:null},getContextByNode:function(a){return(a=c.t.getContextByNode.call(this,a))&&"oj-listview-item"==a.subId?(a.subId="oj-navigationlist-item",a):null},refresh:function(){this.Paa();this.X8();c.t.refresh.apply(this,arguments)},Paa:function(){this.Y.element.removeClass(this.f1);this.Y.element.removeClass(this.QO);
this.Y.element.removeClass(this.yP);this.Xaa(this.element);this.bd.Vg()},destroy:function(){this.Paa();c.t.destroy.apply(this,arguments);this.Ns.unwrap();this.Ns.is(":empty")&&this.Ns.remove();this.Y.element.removeClass(this.H1+" "+this.I1);this.Y._off(this.element,"click");this.Y._off(this.element,"focus");this.Y._off(this.element,"blur");this.Y._off(this.element,"mouseover");this.Y._off(this.element,"mousein");this.Y._off(this.element,"mouseout");this.Y._off(this.element,"keydown")}});(function(){a.Na("oj.ojNavigationList",
g.oj.baseComponent,{widgetEventPrefix:"oj",options:{currentItem:null,drillMode:"none",edge:"start",hierarchyMenuDisplayThresholdLevel:0,rootLabel:null,selection:null,expanded:"auto",data:null,display:"all",navigationLevel:"page",item:{renderer:null,selectable:!0},beforeSelect:null,beforeCollapse:null,beforeCurrentItem:null,collapse:null,beforeExpand:null,expand:null,optionChange:null},_ComponentCreate:function(){this._super();this.$a()},Hh:function(){this._super();this.vh.Cz()},ih:function(a,c,e){this.vh.iha(a,
c,e)},$a:function(){for(var a in this.options)this.Zca(a,this.options[a]);this.kL(this.options.drillMode,this.options.display,this.options.edge);this.vh=new c;a={Y:this};a=g.extend(this.options,a);this.vh.Yq(a)},getNodeBySubId:function(a){return this.vh.getNodeBySubId(a)},getSubIdByNode:function(a){return this.vh.getSubIdByNode(a)},getContextByNode:function(a){return this.vh.getContextByNode(a)},expand:function(a,c){this.vh.tX(a,c,!0,!0)},collapse:function(a,c){this.vh.Eda(a,c,!0)},getExpanded:function(){return this.vh.getExpanded()},
kL:function(a,c,e){if("none"!==a){if("icons"===c)throw"Icon only navigation list should have drillMode set to 'none'.";if("top"===e)throw"Horizontal navigation list should have drillMode set to 'none'.";}},Zca:function(a,c){var e=!0;"drillMode"===a?e="none"===c||"collapsible"===c||"sliding"===c:"display"===a?e="all"===c||"icons"===c:"edge"===a&&(e="top"===c||"start"===c);if(!e)throw"Invalid value: "+c+" for key: "+a;},_setOption:function(a,c){this.Zca(a,c);switch(a){case "drillMode":this.kL(c,this.options.display,
this.options.edge);break;case "display":this.kL(this.options.drillMode,c,this.options.edge);break;case "edge":this.kL(this.options.drillMode,this.options.display,c)}return this._super(a,c)},_setOptions:function(a,c){var e,f=this.vh.Pw(a,c);for(e in a)0>f.mia.indexOf(e)&&this._setOption(e,a[e],c);f.iIa&&this.vh.refresh();return this},sj:function(){this.vh.jha()},Sp:function(){this.vh.xA()},refresh:function(){this._super();this.vh.refresh()},whenReady:function(){return this.vh.whenReady()},_destroy:function(){this.vh.destroy();
this._super();delete this.vh}});a.Components.Dp({ojNavigationList:{hierarchyMenuDisplayThresholdLevel:a.Components.Lf(function(){return(a.nd.uf("oj-navigationlist-option-defaults")||{}).hierarchyMenuDisplayThresholdLevel})}})})();a.Components.Ta("ojNavigationList","baseComponent",{properties:{currentItem:{type:"Object"},data:{},display:{type:"string"},drillMode:{type:"string"},edge:{type:"string"},expanded:{type:"Array|string"},hierarchyMenuDisplayThresholdLevel:{type:"number"},item:{},navigationLevel:{type:"string"},
rootLabel:{type:"string"},selection:{type:"string"}},methods:{collapse:{},expand:{},getContextByNode:{},getExpanded:{},refresh:{},whenReady:{}},extension:{_widgetName:"ojNavigationList"}});a.Components.register("oj-navigation-list",a.Components.getMetadata("ojNavigationList"))});