/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","hammerjs","promise","ojs/ojjquery-hammer","ojs/ojcomponentcore"],function(a,g,c){a.j={};o_("OffcanvasUtils",a.j,a);a.j.$O="oj-offcanvasEdge";a.j.Pp="oj-offcanvas";a.j.aP="oj-mediaQueryListener";a.j.M0="oj-offcanvasHammer";a.j.N0="oj-offcanvasStyle";a.j.gB="selector";a.j.Xw="content";a.j.eu="start";a.j.du="end";a.j.SA="top";a.j.gG="bottom";a.j.bu="displayMode";a.j.cu="push";a.j.TN="overlay";a.j.j_="pin";a.j.Kja="modality";a.j.VJa="none";a.j.Lja="modal";a.j.fG="_dismissHandler";
a.j.uO="_openPromise";a.j.QA="_closePromise";a.j.ju="_glassPane";a.j.$_="_surrogate";a.j.AO="data-oj-offcanvas-surrogate-id";a.j.Vja="oj-offcanvas-outer-wrapper";a.j.cB="oj-offcanvas-open";a.j.Fh="oj-offcanvas-transition";a.j.L_="oj-offcanvas-pin";a.j.K_="oj-offcanvas-pin-transition";a.j.tja="oj-offcanvas-glasspane";a.j.VA="oj-offcanvas-glasspane-dim";a.j.oka="ojbeforeopen veto";a.j.nka="ojbeforeclose veto";a.j.tCa={start:"oj-offcanvas-shift-start",end:"oj-offcanvas-shift-end",top:"oj-offcanvas-shift-down",
bottom:"oj-offcanvas-shift-up"};a.j.Ara={start:"oj-offcanvas-start",end:"oj-offcanvas-end",top:"oj-offcanvas-top",bottom:"oj-offcanvas-bottom"};a.j.Nsa=function(b){b=b[a.j.bu];b!==a.j.TN&&b!==a.j.cu&&b!==a.j.j_&&(b=(a.nd.uf("oj-offcanvas-option-defaults")||{}).displayMode);return b};a.j.Fg=function(b){return g(b[a.j.gB])};a.j.Ny=function(b){return b[a.j.Kja]===a.j.Lja};a.j.Js=function(b){return b.hasClass(a.j.cB)};a.j.vs=function(b){return b.closest("."+a.j.Vja)};a.j.AI=function(b){var c=a.j.Fg(b);
return a.j.q$(b)||b[a.j.bu]===a.j.TN?c:c.parent()};a.j.Qta=function(b){var c=a.j.tCa[b];if(!c)throw"Invalid edge: "+b;return c};a.j.dg=function(){return"rtl"===a.u.wn()};a.j.Jk=function(a,c){a.css({"-webkit-transform":c,transform:c})};a.j.iJ=function(b,c,e){b=b===a.j.du;if(a.j.dg()||e)b=!b;return"translate3d("+(b?"-":"")+c+", 0, 0)"};a.j.GK=function(b,c,e){a.j.Jk(b,a.j.iJ(c,e,!1))};a.j.N7=function(b,c){return"translate3d(0, "+(b===a.j.gG?"-":"")+c+", 0)"};a.j.iCa=function(b,c,e){a.j.Jk(b,a.j.N7(c,
e))};a.j.O7=function(a,c){return"translate3d(0, "+(c?"-":"")+a+", 0)"};a.j.sBa=function(b,c,e){b.addClass(a.j.Fh);a.j.Jk(b,"translate3d(0, 0, 0)");c.addClass(a.j.Fh);a.j.Jk(c,e)};a.j.bba=function(b){var c=b.edge;b=a.j.Fg(b);c&&c.length||(c=b.hasClass("oj-offcanvas-start")?a.j.eu:b.hasClass("oj-offcanvas-end")?a.j.du:b.hasClass("oj-offcanvas-top")?a.j.SA:b.hasClass("oj-offcanvas-bottom")?a.j.gG:a.j.eu);g.data(b[0],a.j.$O,c);return c};a.j.yS=function(b){return g.data(b[0],a.j.$O)};a.j.qE=function(b,
c,e){var f=b[a.j.bu],g=a.j.Fg(b),k=a.j.cB,f=f===a.j.TN?a.j.Fh+" oj-offcanvas-overlay":a.j.Fh;e?(g.addClass(k),c.addClass(f)):(b.makeFocusable&&a.u.cN({element:g,remove:!0}),b=b.tabindex,void 0===b?g.removeAttr("tabindex"):g.attr("tabindex",b),g.removeClass(k),c.removeClass(f))};a.j.Nj=function(b){var c=a.j.Fg(b),e=c.find(":focusable");0<e.length?e=e[0]:(e=c.attr("tabindex"),void 0!==e&&(b.tabindex=e),c.attr("tabindex","-1"),e=c,a.u.cN({element:c,applyHighlight:!0}),b.makeFocusable=!0);a.le.OE(e)};
a.j.kxa=function(a){return"none"!=a.autoDismiss};a.j.Lo=function(a,c){function e(){c(a);a.off("transitionend webkitTransitionEnd otransitionend oTransitionEnd",e)}a.on("transitionend webkitTransitionEnd otransitionend oTransitionEnd",e)};a.j.r4=function(b){a.j.close(b)["catch"](function(b){a.r.warn("Offcancas close failed: "+b)})};a.j.WD=function(b){a.j.FW(b);if(a.j.kxa(b)){var c=a.j.Fg(b),e=b[a.j.fG]=function(e){var f=e.target;a.u.gga(e)||"focus"===e.type&&!g(f).is(":focusable")||(null==g.data(c[0],
a.j.Pp)?a.j.FW(b):a.u.JHa(c[0],f)||a.j.r4(b))},f=document.documentElement;a.u.af()&&f.addEventListener("touchstart",e,!0);f.addEventListener("mousedown",e,!0);f.addEventListener("focus",e,!0)}a.j.nK(b)};a.j.FW=function(b){var c=b[a.j.fG];if(c){var e=document.documentElement;a.u.af()&&e.removeEventListener("touchstart",c,!0);e.removeEventListener("mousedown",c,!0);e.removeEventListener("focus",c,!0);delete b[a.j.fG];b[a.j.fG]=null}a.j.bL(b)};a.j.nK=function(b){if(a.u.af()){var d=b[a.j.gB],e=g(d),f=
a.j.yS(e),h,k;f===a.j.eu&&!a.j.dg()||f===a.j.du&&a.j.dg()?(k={recognizers:[[c.Swipe,{direction:c.DIRECTION_LEFT}]]},h="swipeleft"):f===a.j.eu&&a.j.dg()||f===a.j.du&&!a.j.dg()?(k={recognizers:[[c.Swipe,{direction:c.DIRECTION_RIGHT}]]},h="swiperight"):f===a.j.SA?(k={recognizers:[[c.Swipe,{direction:c.DIRECTION_UP}]]},h="swipeup"):f===a.j.gG&&(k={recognizers:[[c.Swipe,{direction:c.DIRECTION_DOWN}]]},h="swipedown");e=e.$j(k).on(h,function(c){c.preventDefault();a.j.r4(b)});g.data(g(d)[0],a.j.M0,{event:h,
hammer:e})}};a.j.bL=function(b){b=a.j.Fg(b);0<b.length&&(b=g.data(b[0],a.j.M0))&&b.hammer.off(b.event)};a.j.uxa=function(b){return a.j.vs(b).hasClass("oj-offcanvas-page")};a.j.JJ=function(b){return b[a.j.bu]===a.j.j_};a.j.q$=function(b){return b[a.j.Xw]||a.j.uxa(a.j.Fg(b))||a.j.JJ(b)};a.j.gBa=function(b){var c=b.attr("style");void 0!==c&&g.data(b[0],a.j.N0,c)};a.j.bBa=function(b){var c=g.data(b[0],a.j.N0);c?b.attr("style",c):b.removeAttr("style")};a.j.Bq=function(b,c){var e=a.j.yS(b),e=a.j.Qta(e),
f=a.j.vs(b);a.o.ue(f,jQuery);var g=f.hasClass(e);c||f.toggleClass(e,!g);return g};a.j.eI=function(a,c){function e(){null==("fixed"===g(a).css("position")?a.parentNode.offsetParent:a.offsetParent)?c():f=window.requestAnimationFrame(e)}var f=0,f=window.requestAnimationFrame(e);return function(){0!==f&&window.cancelAnimationFrame(f)}};a.j.Zr=function(b){var c=a.j.Fg(b),e=a.j.JJ(b);if(g.data(c[0],a.j.Pp)===b){a.j.yS(c);var f=a.j.AI(b);e?c.removeClass(a.j.cB+" "+a.j.K_):a.j.qE(b,f,!1);a.j.wAa(b);a.j.FW(b);
e&&(a.j.vs(c).removeClass(a.j.L_),a.j.bBa(c));c.trigger("ojclose",b);g.removeData(c[0],a.j.Pp)}};a.j.Oba=function(b,c,e){var f=g(b);(c=!!c)&&a.j.Js(f)&&a.j.bq(b,!1);f.toggleClass(a.j.Ara[e],!c)};a.j.mJa=function(b){var c=b.query;if(null!==c){var e=b[a.j.gB],c=window.matchMedia(c),f=a.j.bba(b);b=function(b){a.j.Oba(e,b.matches,f)};c.addListener(b);a.j.Oba(e,c.matches,f);g.data(g(e)[0],a.j.aP,{mqList:c,mqListener:b})}};o_("OffcanvasUtils.setupResponsive",a.j.mJa,a);a.j.BJa=function(b){b=a.j.Fg(b);var c=
g.data(b[0],a.j.aP);c&&(c.mqList.removeListener(c.mqListener),g.removeData(b[0],a.j.aP))};o_("OffcanvasUtils.tearDownResponsive",a.j.BJa,a);a.j.Xya=function(b,c,e){function f(e){e.removeClass(a.j.Fh);l?l=!1:(a.j.Nj(b),h.trigger("ojopen",b),a.j.WD(b),c(!0))}var h=a.j.Fg(b),k=g(b[a.j.Xw]);a.o.ue(k,jQuery);var l=!0,m=b.size,s;h.addClass(a.j.cB);window.setTimeout(function(){e===a.j.eu||e===a.j.du?(void 0===m&&(m=h.outerWidth(!0)+"px"),a.j.Jk(h,a.j.iJ(e,m,!0)),s=a.j.iJ(e,m,!1)):(void 0===m&&(m=h.outerHeight(!0)+
"px"),a.j.Jk(h,a.j.O7(m,e===a.j.SA)),s=a.j.O7(m,e!==a.j.SA));window.setTimeout(function(){a.j.sBa(h,k,s);a.j.Bq(h,!1)},0)},0);a.j.zH(b,h);a.j.Lo(k,f);a.j.Lo(h,f)};a.j.Sya=function(b,c,e){var f=a.j.Fg(b);a.j.qE(b,f,!0);var g=b.size;g&&(e===a.j.eu||e===a.j.du?a.j.Jk(f,a.j.iJ(e,g,!0)):a.j.Jk(f,a.j.N7(e,g)));window.setTimeout(function(){a.j.Bq(f,!1)},10);a.j.zH(b,f);a.j.Lo(f,function(){f.removeClass(a.j.Fh);a.j.Nj(b);f.trigger("ojopen",b);a.j.WD(b);c(!0)})};a.j.Tya=function(b,c){var e=a.j.Fg(b),f=g(b[a.j.Xw]);
a.o.ue(f,jQuery);var h=b.size;e.addClass(a.j.cB);window.setTimeout(function(){void 0===h&&(h=e.outerWidth(!0)+"px");e.addClass(a.j.K_);a.j.vs(e).addClass(a.j.L_);a.j.gBa(e);a.j.Jk(e,"none");window.setTimeout(function(){e.css("min-width",h);a.j.Bq(e,!1)},10)},0);a.j.zH(b,e);a.j.Lo(e,function(){a.j.Nj(b);e.trigger("ojopen",b);a.j.WD(b);c(!0)})};a.j.upa=function(b,c,e,f){function h(e){l&&e?l=!1:(k.removeClass(a.j.Fh),a.j.Jk(k,""),a.j.Zr(b),m&&m(),c(!0))}var k=g(b[a.j.Xw]),l=!0,m;f&&(a.j.Lo(e,h),a.j.Lo(k,
h),m=a.j.eI(e[0],h));a.j.Jk(e,"");a.j.Jk(k,"");a.j.Bq(e,!1);a.j.Ny(b)&&b[a.j.ju].removeClass(a.j.VA);f?(k.addClass(a.j.Fh),e.addClass(a.j.Fh)):(a.j.Zr(b),c(!0))};a.j.spa=function(b,c,e,f){function g(){a.j.Zr(b);k&&k();c(!0)}var k;f&&(a.j.Lo(e,g),k=a.j.eI(e[0],g));a.j.Bq(e,!1);a.j.Ny(b)&&b[a.j.ju].removeClass(a.j.VA);f?e.addClass(a.j.Fh):(a.j.Zr(b),c(!0))};a.j.Rya=function(b,c,e,f){var g=a.j.Fg(b),k=a.j.AI(b);a.o.ue(k,jQuery);a.j.qE(b,k,!0);var l;e===a.j.eu||e===a.j.du?(l=void 0===l?g.outerWidth(!0)+
"px":l,f===a.j.cu&&a.j.GK(k,e,l)):(l=void 0===l?g.outerHeight(!0)+"px":l,f===a.j.cu&&a.j.iCa(k,e,l));window.setTimeout(function(){a.j.Bq(g,!1)},10);a.j.zH(b,g);a.j.Lo(k,function(){k.removeClass(a.j.Fh);a.j.Nj(b);g.trigger("ojopen",b);a.j.WD(b);c(!0)})};a.j.tpa=function(b,c,e,f){function g(){a.j.Zr(b);k&&k();c(!0)}var k;f&&(a.j.Lo(e,g),k=a.j.eI(e[0],g));a.j.Bq(e,!1);a.j.Ny(b)&&b[a.j.ju].removeClass(a.j.VA);f?e.css("min-width","0"):(a.j.Zr(b),c(!0))};a.j.rpa=function(b,c,e,f){function g(){a.j.Zr(b);
m&&m();c(!0)}var k=b[a.j.bu],l=a.j.AI(b),m;f&&(a.j.Lo(l,g),m=a.j.eI(e[0],g));k===a.j.cu&&a.j.Jk(l,"");a.j.Bq(e,!1);a.j.Ny(b)&&b[a.j.ju].removeClass(a.j.VA);f?l.addClass(a.j.Fh):(a.j.Zr(b),c(!0))};a.j.open=function(b){var c=a.j.Fg(b),e=g.data(c[0],a.j.Pp);if(e){if(e[a.j.QA])return e[a.j.QA];if(e[a.j.uO])return e[a.j.uO]}var f=!1,h=new Promise(function(e,l){a.o.ue(c,jQuery);var m=a.j.bba(b),s=g.Event("ojbeforeopen");c.trigger(s,b);if(!1===s.result)return l(a.j.oka),f=!0,h;var s=a.j.Nsa(b),t=a.j.JJ(b);
!t||m!==a.j.SA&&m!==a.j.gG||(s=a.j.cu);var r=g.extend({},b);r[a.j.bu]=s;g.data(c[0],a.j.Pp,r);if(b[a.j.Xw]){if(!a.j.q$(b))throw"Error: Both main content selector and the inner wrapper \x3cdiv class\x3d'oj-offcanvas-inner-wrapper'\x3e are provided. Please remove the inner wrapper.";t?a.j.Tya(r,e):s===a.j.cu?a.j.Xya(r,e,m):a.j.Sya(r,e,m)}else a.j.Rya(r,e,m,s)});f||(e=g.data(c[0],a.j.Pp))&&(e[a.j.uO]=h);return h};o_("OffcanvasUtils.open",a.j.open,a);a.j.close=function(b){return a.j.bq(b[a.j.gB],!0)};
o_("OffcanvasUtils.close",a.j.close,a);a.j.bq=function(b,c){var e=g(b);a.o.ue(e,jQuery);var f=g.data(e[0],a.j.Pp);if(f&&f[a.j.QA])return f[a.j.QA];var h=!1,k=new Promise(function(l,m){if(a.j.Js(e)){b!=f[a.j.gB]&&l(!0);a.j.Bq(e,!0)||l(!0);var s=g.Event("ojbeforeclose");e.trigger(s,f);if(!1===s.result)return m(a.j.nka),h=!0,k;var s=a.j.JJ(f),t=f[a.j.bu];f[a.j.Xw]?t===a.j.cu?a.j.upa(f,l,e,c):s?a.j.tpa(f,l,e,c):a.j.spa(f,l,e,c):a.j.rpa(f,l,e,c)}else l(!0)});h||(f=g.data(e[0],a.j.Pp))&&(f[a.j.QA]=k);return k};
a.j.toggle=function(b){var c=a.j.Fg(b);a.o.ue(c,jQuery);return a.j.Js(c)?a.j.close(b):a.j.open(b)};o_("OffcanvasUtils.toggle",a.j.toggle,a);a.j.Cna=function(b){var c=g("\x3cdiv\x3e");c.addClass(a.j.tja);c.attr("role","presentation");c.attr("aria-hidden","true");c.appendTo(b.parent());c.on("keydown keyup keypress mousedown mouseup mouseover mouseout click focusin focus",function(a){a.stopPropagation();a.preventDefault()});return c};a.j.tR=function(b){var c=g("\x3cscript\x3e"),e=b.attr("id");e?(e=[e,
"surrogate"].join("_"),c.attr("id",e)):e=c.uniqueId();c.insertBefore(b);b.attr(a.j.AO,e);return c};a.j.NCa=function(b,c){b[a.j.$_]=a.j.tR(c);c.appendTo(c.parent())};a.j.$Aa=function(b){var c=a.j.Fg(b);b=b[a.j.$_];c&&b&&c.attr(a.j.AO)===b.attr("id")&&(c.insertAfter(b),c.removeAttr(a.j.AO),b.remove())};a.j.zH=function(b,c){a.j.Ny(b)&&(b[a.j.ju]=a.j.Cna(c),a.j.NCa(b,c),window.setTimeout(function(){b[a.j.ju].addClass(a.j.VA)},0))};a.j.wAa=function(b){a.j.Ny(b)&&(b[a.j.ju].remove(),a.j.$Aa(b))};a.j.kia=
function(b){var d,e,f,h,k,l,m,s,t,r,n,p;null==g(b).attr("oj-data-pansetup")&&(g(b).attr("oj-data-pansetup","true"),b.displayMode="push",d=a.j.Fg(b),e=b.size,null==e&&(e=d.outerWidth()),f=a.j.vs(d),h=a.j.AI(b),k={recognizers:[[c.Pan,{direction:c.DIRECTION_HORIZONTAL}]]},l=!1,g(f).$j(k).on("panstart",function(e){m=null;switch(e.gesture.direction){case c.DIRECTION_LEFT:Math.abs(e.gesture.deltaY)<Math.abs(e.gesture.deltaX)&&(m=a.j.dg()?"end":"start");break;case c.DIRECTION_RIGHT:Math.abs(e.gesture.deltaY)<
Math.abs(e.gesture.deltaX)&&(m=a.j.dg()?"start":"end")}null!=m&&(s={direction:m,distance:Math.abs(e.gesture.deltaX)},t=g.Event("ojpanstart"),d.trigger(t,s),t.isDefaultPrevented()||(b._closePromise=null,a.j.qE(b,h,!0),l=!0,e.stopPropagation()))}).on("panmove",function(b){l&&(r=Math.abs(b.gesture.deltaX),d.css("width",r),h.removeClass(a.j.Fh),a.j.GK(h,"start",b.gesture.deltaX+"px"),s={direction:m,distance:r},t=g.Event("ojpanmove"),d.trigger(t,s),b.stopPropagation())}).on("panend",function(c){l&&(l=
!1,r=Math.abs(c.gesture.deltaX),s={distance:r},t=g.Event("ojpanend"),d.trigger(t,s),c.stopPropagation(),t.isDefaultPrevented()?(p=function(){a.j.qE(b,h,!1);h.removeClass(a.j.Fh);h.off("transitionend webkitTransitionEnd otransitionend oTransitionEnd",p)},h.on("transitionend webkitTransitionEnd otransitionend oTransitionEnd",p),h.addClass(a.j.Fh),a.j.GK(h,"start","0px")):(h.addClass(a.j.Fh),d.css("width",e+"px"),n=b.edge,null==n&&(n=d.hasClass("oj-offcanvas-start")?"start":"end"),a.j.GK(h,n,e+"px"),
g.data(d[0],a.j.Pp,b),g.data(d[0],a.j.$O,n),a.j.WD(b)))}))};o_("OffcanvasUtils.setupPanToReveal",a.j.kia,a);a.j.zia=function(b){b=a.j.Fg(b);g(a.j.vs(b)).off("panstart panmove panend")};o_("OffcanvasUtils.tearDownPanToReveal",a.j.zia,a)});