/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","hammerjs","ojs/ojpagingtabledatasource","ojs/ojinputtext","ojs/ojjquery-hammer"],function(a,g,c,b){(function(){a.Na("oj.ojPagingControl",g.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{data:null,overflow:"fit",pageSize:25,pageOptions:{layout:["auto"],type:"numbers",maxPageLinks:6,orientation:"horizontal"},loadMoreOptions:{maxCount:500},mode:"page",ready:null},Ja:{Ala:"labelAccPaging",vla:"labelAccNavFirstPage",
wla:"labelAccNavLastPage",xla:"labelAccNavNextPage",zla:"labelAccNavPreviousPage",yla:"labelAccNavPage",Bla:"labelLoadMore",Cla:"labelLoadMoreMaxRows",w1:"labelNavInputPage",nP:"labelNavInputPageMax",iKa:"labelNavInputPageSummary",C1:"msgItemRangeCurrent",sP:"msgItemRangeCurrentSingle",D1:"msgItemRangeItems",Qla:"msgItemRangeOfAtLeast",Pla:"msgItemRangeOfApprox",Rla:"msgItemRangeOf",z2:"tipNavInputPage",Zma:"tipNavPageLink",B2:"tipNavNextPage",C2:"tipNavPreviousPage",y2:"tipNavFirstPage",A2:"tipNavLastPage",
Au:"pageInvalid.summary",dKa:"pageInvalid.detail",X0:"dataInvalidType.summary",W0:"dataInvalidType.detail",cla:"maxPageLinksInvalid.summary",bla:"maxPageLinksInvalid.detail"},Xa:{gQ:"oj-component",Gh:"oj-active",xu:"oj-clickable-icon-nocontext",ec:"oj-disabled",Jh:"oj-enabled",Hm:"oj-focus",$n:"oj-hover",Te:"oj-selected"},V:{ama:"oj-pagingcontrol",Q1:"oj-pagingcontrol-acc-label",R1:"oj-pagingcontrol-content",S1:"oj-pagingcontrol-loadmore",XG:"oj-pagingcontrol-loadmore-link",zP:"oj-pagingcontrol-loadmore-max-rows",
YG:"oj-pagingcontrol-loadmore-range",AP:"oj-pagingcontrol-loadmore-range-current",BP:"oj-pagingcontrol-loadmore-range-max",U1:"oj-pagingcontrol-nav",ZG:"oj-pagingcontrol-nav-arrow",T1:"oj-pagingcontrol-nav-arrow-section",EP:"oj-pagingcontrol-nav-page",nma:"oj-pagingcontrol-nav-page-ellipsis",cma:"oj-pagingcontrol-nav-dot",bma:"oj-pagingcontrol-nav-dot-bullet",mma:"oj-pagingcontrol-nav-page-acc-label",W1:"oj-pagingcontrol-nav-label",V1:"oj-pagingcontrol-nav-input-section",Hu:"oj-pagingcontrol-nav-input",
EB:"oj-pagingcontrol-nav-input-max",FB:"oj-pagingcontrol-nav-input-summary",CP:"oj-pagingcontrol-nav-input-summary-current",DP:"oj-pagingcontrol-nav-input-summary-max",Y1:"oj-pagingcontrol-nav-pages-section",X1:"oj-pagingcontrol-nav-pages-links",Gx:"oj-pagingcontrol-nav-first",dma:"oj-pagingcontrol-nav-first-acc-label",Jx:"oj-pagingcontrol-nav-previous",oma:"oj-pagingcontrol-nav-previous-acc-label",Ix:"oj-pagingcontrol-nav-next",jma:"oj-pagingcontrol-nav-next-acc-label",Hx:"oj-pagingcontrol-nav-last",
gma:"oj-pagingcontrol-nav-last-acc-label",ema:"oj-pagingcontrol-nav-first-icon",pma:"oj-pagingcontrol-nav-previous-icon",kma:"oj-pagingcontrol-nav-next-icon",hma:"oj-pagingcontrol-nav-last-icon",fma:"oj-pagingcontrol-nav-first-vertical-icon",qma:"oj-pagingcontrol-nav-previous-vertical-icon",lma:"oj-pagingcontrol-nav-next-vertical-icon",ima:"oj-pagingcontrol-nav-last-vertical-icon",Mu:"oj-component-icon",ol:"oj-helper-hidden-accessible"},L0:"data-oj-pagenum",uj:"enabled",Rr:"disabled",wj:"tabindex",
Jm:{Mr:"loadMore",xP:"page"},Lh:{qj:"auto",oB:"all",KG:"input",tma:"rangeText",Zla:"pages",E1:"nav"},$la:6,Yp:{kKa:"numbers",Vka:"dots"},firstPage:function(){return null!=this.Lb()?this.Gl(0,!1):this.xy()},previousPage:function(){if(null!=this.Lb()){var a=this.Eg();if(0<a)return this.Gl(a-1,!1)}return this.xy()},nextPage:function(){if(null!=this.Lb()){var a=this.Eg();if(this.eg()&&a+1<=this.We()-1||0>this.We()||!this.eg())return this.Gl(a+1,!1)}return this.xy()},lastPage:function(){return null!=this.Lb()&&
0<this.We()?this.Gl(this.We()-1,!1):this.xy()},page:function(a){return null!=this.Lb()&&(this.eg()&&a<=this.We()-1||0>this.We()||!this.eg())?this.Gl(a,!1):this.xy()},loadNext:function(){return null!=this.Lb()?this.ixa():this.xy()},refresh:function(){this._super();this.Ff()},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId,c=null;"oj-pagingcontrol-nav-input"===b?c=this.Df().find("."+this.V.Hu)[0]:"oj-pagingcontrol-nav-input-max"===b?c=this.Df().find("."+
this.V.EB)[0]:"oj-pagingcontrol-nav-input-summary"===b?c=this.Df().find("."+this.V.FB)[0]:"oj-pagingcontrol-nav-input-summary-current"===b?c=this.Df().find("."+this.V.CP)[0]:"oj-pagingcontrol-nav-input-summary-max"===b?c=this.Df().find("."+this.V.DP)[0]:"oj-pagingcontrol-nav-first"===b?c=this.Df().find("."+this.V.Gx)[0]:"oj-pagingcontrol-nav-next"===b?c=this.Df().find("."+this.V.Ix)[0]:"oj-pagingcontrol-nav-previous"===b?c=this.Df().find("."+this.V.Jx)[0]:"oj-pagingcontrol-nav-last"===b?c=this.Df().find("."+
this.V.Hx)[0]:"oj-pagingcontrol-nav-page"===b?(a=a.index,c=this.Df().find("["+this.L0+"\x3d"+a+"]")[0]):"oj-pagingcontrol-load-more-link"===b?c=this.Df().find("."+this.V.XG)[0]:"oj-pagingcontrol-load-more-range"===b?c=this.Df().find("."+this.V.YG)[0]:"oj-pagingcontrol-load-more-range-current"===b?c=this.Df().find("."+this.V.AP)[0]:"oj-pagingcontrol-load-more-range-max"===b?c=this.Df().find("."+this.V.BP)[0]:"oj-pagingcontrol-load-more-max-rows"===b&&(c=this.Df().find("."+this.V.zP)[0]);void 0===c&&
(c=null);return c},getSubIdByNode:function(a){return g(a).hasClass(this.V.Hu)?{subId:"oj-pagingcontrol-nav-input"}:g(a).hasClass(this.V.EB)?{subId:"oj-pagingcontrol-nav-input-max"}:g(a).hasClass(this.V.FB)?{subId:"oj-pagingcontrol-nav-input-summary"}:g(a).hasClass(this.V.CP)?{subId:"oj-pagingcontrol-nav-input-summary-current"}:g(a).hasClass(this.V.DP)?{subId:"oj-pagingcontrol-nav-input-summary-max"}:g(a).hasClass(this.V.Gx)?{subId:"oj-pagingcontrol-nav-first"}:g(a).hasClass(this.V.Ix)?{subId:"oj-pagingcontrol-nav-next"}:
g(a).hasClass(this.V.Jx)?{subId:"oj-pagingcontrol-nav-previous"}:g(a).hasClass(this.V.Hx)?{subId:"oj-pagingcontrol-nav-last"}:g(a).hasClass(this.V.EP)?{subId:"oj-pagingcontrol-nav-page",index:g(a).attr(this.L0)}:g(a).hasClass(this.V.XG)?{subId:"oj-pagingcontrol-load-more-link"}:g(a).hasClass(this.V.YG)?{subId:"oj-pagingcontrol-load-more-range"}:g(a).hasClass(this.V.AP)?{subId:"oj-pagingcontrol-load-more-range-current"}:g(a).hasClass(this.V.BP)?{subId:"oj-pagingcontrol-load-more-range-max"}:g(a).hasClass(this.V.zP)?
{subId:"oj-pagingcontrol-load-more-max-rows"}:null},_ComponentCreate:function(){this._super();this.Ov();this.uC();this.jn(this.Df());this._on(this.hq)},Hh:function(){this._super();this.nK();this.yba()},_destroy:function(){this.Uo();this.bL();this.lC=!0},uC:function(){var a=this.options;this.element.addClass(this.V.ama);this.element.addClass(this.Xa.gQ);this.kqa();this.qqa();this.h$=a.mode;a.mode==this.Jm.Mr?(this.K4(),this.L4(),this.M4()):this.N4()},hq:{"mouseup .oj-pagingcontrol-loadmore-link":function(a){this.loadNext();
g(a.target).data("_mouseup",!0);a.preventDefault()},"click .oj-pagingcontrol-loadmore-link":function(a){g(a.target).data("_mouseup")?g(a.target).data("_mouseup",!1):this.loadNext();a.preventDefault()},"click .oj-pagingcontrol-nav-dot":function(b){if(!g(b.currentTarget).hasClass(this.Xa.ec)){var c=g(b.currentTarget).attr("data-oj-pagenum"),f=this;this.page(c).then(function(){f=null},function(b){var c=f.F(f.Ja.Au);a.r.error(c+"\n"+b);f=null})}b.preventDefault()},"click .oj-pagingcontrol-nav-page":function(b){if(!g(b.currentTarget).hasClass(this.Xa.ec)){var c=
g(b.currentTarget).attr("data-oj-pagenum"),f=this;this.page(c).then(function(){f=null},function(b){var c=f.F(f.Ja.Au);a.r.error(c+"\n"+b);f=null})}b.preventDefault()},"click .oj-pagingcontrol-nav-first":function(b){if(!g(b.currentTarget).hasClass(this.Xa.ec)){var c=this;this.firstPage().then(function(){c=null},function(b){var d=c.F(c.Ja.Au);a.r.error(d+"\n"+b);c=null})}b.preventDefault()},"click .oj-pagingcontrol-nav-previous":function(b){if(!g(b.currentTarget).hasClass(this.Xa.ec)){var c=this;this.previousPage().then(function(){c=
null},function(b){var d=c.F(c.Ja.Au);a.r.error(d+"\n"+b);c=null})}b.preventDefault()},"click .oj-pagingcontrol-nav-next":function(b){if(!g(b.currentTarget).hasClass(this.Xa.ec)){var c=this;this.nextPage().then(function(){c=null},function(b){var d=c.F(c.Ja.Au);a.r.error(d+"\n"+b);c=null})}b.preventDefault()},"click .oj-pagingcontrol-nav-last":function(b){if(!g(b.currentTarget).hasClass(this.Xa.ec)){var c=this;this.lastPage().then(function(){c=null},function(b){var d=c.F(c.Ja.Au);a.r.error(d+"\n"+b);
c=null})}b.preventDefault()},"keypress .oj-pagingcontrol-nav-input":function(a){13==a.which&&a.preventDefault()},"mousedown .oj-pagingcontrol-nav-first":function(a){g(a.currentTarget).hasClass(this.Xa.ec)||g(a.target).addClass(this.Xa.Gh);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-previous":function(a){g(a.currentTarget).hasClass(this.Xa.ec)||g(a.target).addClass(this.Xa.Gh);a.preventDefault()},"mousedown .oj-pagingcontrol-nav-next":function(a){g(a.currentTarget).hasClass(this.Xa.ec)||g(a.target).addClass(this.Xa.Gh);
a.preventDefault()},"mousedown .oj-pagingcontrol-nav-last":function(a){g(a.currentTarget).hasClass(this.Xa.ec)||g(a.target).addClass(this.Xa.Gh);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-first":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-previous":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-next":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()},"mouseup .oj-pagingcontrol-nav-last":function(a){g(a.target).removeClass(this.Xa.Gh);
a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-first":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-previous":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-next":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()},"mouseleave .oj-pagingcontrol-nav-last":function(a){g(a.target).removeClass(this.Xa.Gh);a.preventDefault()}},Ff:function(){this.i!=this.options.data&&(this.bR(),
this.yba());var a=0,b=0;null!=this.i&&(b=this.i.getStartItemIndex());null!=this.i&&0!=this.i.totalSize()&&0<=this.i.getEndItemIndex()&&(a=this.i.getEndItemIndex()-b+1);if(this.h$!=this.options.mode)this.h$=this.options.mode,this.options.mode==this.Jm.Mr?this.faa(a,b):this.gaa(a,b);else if(this.options.mode==this.Jm.Mr){var c=this.Lb(),h=this.vy();null!=c&&(b+a==c.totalSize()&&this.eg()||0==c.totalSize())?h.css("display","none"):this.faa(a,b)}else this.gaa(a,b)},_setOption:function(a,b){this._superApply(arguments);
this.Gl(0,!0);if(this.options.mode!=this.Jm.Mr&&"pageOptions"==a){var c=this.Cl();null!=c&&(this.EW(c),this.bL(),c.empty());this.ipa();this.N4();this.nK()}this.Ff()},bR:function(){null!=this.i&&this.Uo();this.i=null},hpa:function(){this.EQ=this.DQ=this.CQ=null},ipa:function(){this.HQ=this.GQ=this.FQ=null},Eg:function(){var a=this.Lb(),b=0;null!=a&&(b=a.getPage());return b},Lb:function(){this.i||null==this.options.data||(this.i=this.options.data,this.Ov());return this.i},HS:function(a,b){var c=0<=
b?b:0,h=g(document.createElement("span")),k=g(document.createElement("span"));this.options.mode==this.Jm.Mr?k.addClass(this.V.AP):k.addClass(this.V.CP);h.append(k);var l=this.Lb();if(null!=l&&null!=l.totalSize()&&null!=a){var m=this.F(this.Ja.sP,{pageFrom:c}),m=parseInt(b,10)+parseInt(a,10),c=0<m?c+1:0;if(-1!=l.totalSize()){m=m>l.totalSize()?l.totalSize():m;if(c==m)m=this.F(this.Ja.sP,{pageFrom:c});else{if(c>m)return h;m=this.F(this.Ja.C1,{pageFrom:c,pageTo:m})}var c=this.F(this.Ja.Rla),s=null;"atLeast"==
l.totalSizeConfidence()?s=this.F(this.Ja.Qla):"estimate"==l.totalSizeConfidence()&&(s=this.F(this.Ja.Pla));var t=g(document.createElement("span"));null==s?t.text(" "+c+" "):t.text(" "+s+" ");h.append(t);c=g(document.createElement("span"));this.options.mode==this.Jm.Mr?c.addClass(this.V.BP):c.addClass(this.V.DP);c.text(l.totalSize());h.append(c)}else m=0==a?this.F(this.Ja.sP,{pageFrom:0}):this.F(this.Ja.C1,{pageFrom:c,pageTo:m});l=this.F(this.Ja.D1);c=g(document.createElement("span"));c.text(" "+l);
h.append(c);k.text(m)}return h},a7:function(){var a=this.options.pageOptions.maxPageLinks;this.options.pageOptions.type==this.Yp.Vka?a=Number.MAX_VALUE:a||(a=this.$la);return a},b7:function(a){var b=0;0<this.We()&&this.eg()?b=this.We():0<a?(a=this.Lb(),b=null==a||"atLeast"!=a.totalSizeConfidence()&&"estimate"!=a.totalSizeConfidence()?this.Eg()+2:this.We()+1):b=this.Eg()+1;return b},xy:function(){return Promise.reject()},We:function(){var a=this.Lb(),b=0;null!=a&&(b=a.getPageCount());return-1<=b?b:
0},tT:function(){var a=g(document.activeElement);if(a.hasClass(this.V.EP)){var b=a.attr("data-oj-pagenum"),c=this;setTimeout(function(){0<=b&&c.Cl().find("div[data-oj-pagenum\x3d"+b+"]").focus();c=b=null},100)}else a.hasClass(this.V.Gx)?(c=this,setTimeout(function(){c.Cl().find("."+c.V.Gx).focus();c=null},100)):a.hasClass(this.V.Jx)?(c=this,setTimeout(function(){c.Cl().find("."+c.V.Jx).focus();c=null},100)):a.hasClass(this.V.Ix)?(c=this,setTimeout(function(){c.Cl().find("."+c.V.Ix).focus();c=null},
100)):a.hasClass(this.V.Hx)?(c=this,setTimeout(function(){c.Cl().find("."+c.V.Hx).focus();c=null},100)):a.hasClass(this.V.Hu)&&(c=this,setTimeout(function(){c.Cl().find("."+c.V.Hu).focus();c=null},100));this.fz()},Dua:function(a){a.page!=a.previousPage&&this.fz()},As:function(){this.Gl(0,!1)},lJ:function(){this.fz()},wT:function(a){this.options.mode==this.Jm.Mr&&this.As(a)},uT:function(a){this.tU(a)?this.options.mode==this.Jm.xP?this.Gl(this.Eg(),!0):this.j9():this.fz()},vT:function(a){if(this.options.mode==
this.Jm.xP){if(0<this.We()&&this.Eg()>this.We()-1){this.Gl(this.We()-1,!0);return}if(this.tU(a)){this.Gl(this.Eg(),!0);return}}else if(this.tU(a)){this.j9();return}this.fz()},Rva:function(b,c){if("value"==c.option){var f=c.value;if(f!=this.Eg()+1&&!isNaN(f)&&0<f){var f=Math.round(f),h=this;this.page(f-1).then(function(){h=null},function(b){var c=h.F(h.Ja.Au);a.r.error(c+"\n"+b);h=null})}}},Gl:function(a,b){try{a=parseInt(a,10)}catch(c){return Promise.reject(c)}this.Li=0;if(b)return this.Jza(a),Promise.resolve();
var h=this.Lb(),k=this;return new Promise(function(b,c){null!=h?(h.setPage(a,{pageSize:k.options.pageSize}).then(function(){b(null)},function(a){c(a)}),k=h=null):(k=null,b(null))})},ixa:function(){var a=this.Lb(),b=this.options.pageSize;this.Li=this.Li?this.Li+b:b;if(!this.eg()||a.totalSize()>this.Li&&this.eg()){var c=this;return new Promise(function(h,k){a.fetch({startIndex:c.Li,pageSize:b}).then(function(a){h(a)},function(){k(null)});c=a=null})}return Promise.resolve()},j9:function(){var a=this.Lb(),
b=this.options.pageSize;if(!this.eg()||a.totalSize()>this.Li&&this.eg()){var c=this;return new Promise(function(h,k){a.fetch({startIndex:0,pageSize:c.Li+b}).then(function(a){h(a)},function(){k(null)});c=a=null})}return Promise.resolve()},tU:function(a){if(null==a)return!1;var b=this.Lb(),c=b.getStartItemIndex();this.options.mode==this.Jm.Mr&&(c=0);var b=b.getEndItemIndex(),h;if(null!=a.index){if(h=a.index,h>=c&&h<b)return!0}else if(null!=a.indexes){var k;for(k=0;k<a.indexes.length;k++)if(h=a.indexes[k],
h>=c&&h<b)return!0}return!1},eg:function(){var a=this.Lb();return null!=a&&"actual"==a.totalSizeConfidence()?!0:!1},Jza:function(b){var c=this;this.bz||(this.Lv=0,this.bz=Promise.resolve());this.Lv++;this.bza=b;this.bz=this.bz.then(function(){c.Lv--;if(0==c.Lv&&!c.lC){c.bz=void 0;var b=c.Lb();null!=b&&b.setPage(c.bza,{pageSize:c.options.pageSize}).then(function(){c=b=null},function(b){c.Lv--;0>=c.Lv&&(c.bz=void 0,a.r.error(b),c=null)})}},function(b){c.Lv--;0>=c.Lv&&(c.bz=void 0,a.r.error(b),c=null)})},
fz:function(){var b=this;this.ED||(this.TD=0,this.ED=Promise.resolve());this.TD++;this.ED=this.ED.then(function(){b.TD--;0!=b.TD||b.lC||(b.ED=void 0,b.Ff(),b._trigger("ready"),b=null)},function(c){b.TD--;0==b.TD&&(b.ED=void 0,a.r.error(c),b=null)})},faa:function(a,b){var c=this.Cl();null!=c&&c.empty();this.hpa();this.K4();c=-1;null!=a&&(c=b+a);0>c||c<this.options.loadMoreOptions.maxCount?(this.L4(),this.M4(a,b)):this.rqa()},gaa:function(a,b){var c=this.options.overflow;this.Tza(a,b);this.Sza();this.Rza();
this.Vza(a,b);this.Uza(a,b);this.Qza(a,b);if("fit"==c){var c=this.element.width(),h=this.k7(),k=this.WS(),g=this.Cta(),m=this.Bta(),s=null!=h?h[0].offsetWidth:0,t=null!=k?k[0].offsetWidth:0,k=null!=g?g.width():0,r=null!=m?m.width():0,s=s+t+r;s>c?s-k<=c?g.css("display","none"):s-k-r<=c?(null!=g&&g.css("display","none"),null!=m&&m.css("display","none")):(null!=g&&g.css("display","none"),null!=m&&m.css("display","none"),null!=h&&h.css("display","none")):0<s&&(null!=g&&g.css("display",""),null!=m&&m.css("display",
""),null!=h&&h.css("display",""))}},Qza:function(a){var b=this.options.pageSize,c=this.k7(),h=c.children("."+this.V.Gx);if(h&&0<h.length){var h=g(h[0]),k=this.F(this.Ja.y2);h.attr("title",k);0==this.Eg()?(h.addClass(this.Xa.ec),h.removeClass(this.Xa.Jh),h.attr("tabindex","-1")):(h.addClass(this.Xa.Jh),h.removeClass(this.Xa.ec),h.attr(this.wj,"0"))}(h=c.children("."+this.V.Jx))&&0<h.length&&(h=g(h[0]),k=this.F(this.Ja.C2),h.attr("title",k),0==this.Eg()?(h.addClass(this.Xa.ec),h.removeClass(this.Xa.Jh),
h.attr(this.wj,"-1")):(h.addClass(this.Xa.Jh),h.removeClass(this.Xa.ec),h.attr(this.wj,"0")));(h=c.children("."+this.V.Hx))&&0<h.length&&(h=g(h[0]),k=this.F(this.Ja.A2),h.attr("title",k),this.Eg()==this.We()-1||0>=this.We()||!this.eg()?(h.addClass(this.Xa.ec),h.removeClass(this.Xa.Jh),h.attr(this.wj,"-1")):(h.addClass(this.Xa.Jh),h.removeClass(this.Xa.ec),h.attr(this.wj,"0")));(c=c.children("."+this.V.Ix))&&0<c.length&&(c=g(c[0]),h=this.F(this.Ja.B2),c.attr("title",h),this.Eg()==this.We()-1&&this.eg()||
0===this.We()||0>this.We()&&0===a||0>this.We()&&a<b?(c.addClass(this.Xa.ec),c.removeClass(this.Xa.Jh),c.attr(this.wj,"-1")):(c.addClass(this.Xa.Jh),c.removeClass(this.Xa.ec),c.attr(this.wj,"0")))},Uza:function(a,b){var c=this.zo().find("."+this.V.Y1);null!=c&&0<c.length&&(c=g(c.get(0)),c.empty(),this.O4(c,this.a7(),a,b))},Sza:function(){var a=this.WS();if(null!=a&&(a=a.children("."+this.V.W1),null!=a&&0<a.length)){var a=g(a[0]),b=this.F(this.Ja.w1);a.text(b)}},Rza:function(){var a=this.Ata();if(null!=
a){var b=this.F(this.Ja.z2);a.attr("title",b);a.ojInputText("option","title",b)}},Vza:function(a,b){var c=this.zo().children("."+this.V.FB);if(null!=c&&0<c.length){var h=this.HS(a,b),c=g(c.get(0));c.empty();0<h.text().length&&(c.append("("),c.append(h),c.append(")"))}},Tza:function(a){a=this.b7(a);var b=this.zo().find("."+this.V.EB);if(null!=b&&0<b.length)if(b=g(b.get(0)),0<this.We()&&this.eg()){var c=this.F(this.Ja.nP,{pageMax:a});b.text(c)}else b.empty();else c=this.WS(),null!=c&&0<this.We()&&this.eg()&&
a>=this.Eg()+1&&(b=g(document.createElement("span")),b.addClass(this.V.EB),c.append(b),c=this.F(this.Ja.nP,{pageMax:a}),b.text(c));b=this.zo().find("."+this.V.Hu);null!=b&&0<b.length&&(b=g(b.get(0)),b.ojInputText("option","validators",[{type:"numberRange",options:{min:1,max:a}}]),b.ojInputText("option","value",this.Eg()+1))},Ov:function(){var b=this.Lb();if(null!=b){this.Uo();this.Cb=[];this.Cb.push({eventType:a.$c.Q.PAGE,eventHandler:this.Dua.bind(this)});this.Cb.push({eventType:a.$c.Q.PAGECOUNT,
eventHandler:this.lJ.bind(this)});this.Cb.push({eventType:a.Fa.Q.ADD,eventHandler:this.uT.bind(this)});this.Cb.push({eventType:a.Fa.Q.REMOVE,eventHandler:this.vT.bind(this)});this.Cb.push({eventType:a.Fa.Q.RESET,eventHandler:this.As.bind(this)});this.Cb.push({eventType:a.Fa.Q.REFRESH,eventHandler:this.lJ.bind(this)});this.Cb.push({eventType:a.Fa.Q.SYNC,eventHandler:this.tT.bind(this)});this.Cb.push({eventType:a.Fa.Q.SORT,eventHandler:this.wT.bind(this)});var c,f;for(c=0;c<this.Cb.length;c++)(f=b.on(this.Cb[c].eventType,
this.Cb[c].eventHandler))&&(this.Cb[c].eventHandler=f)}},jn:function(b){if(!this.LJ){var c=this;a.u.Mk(b[0],function(){c.fz()},50);this.LJ=!0}},nK:function(){if(a.u.af()&&this.options.mode==this.Jm.xP){var c=this.zo();if(null!=c){var e=this;if("vertical"==this.options.pageOptions.orientation){var f={recognizers:[[b.Swipe,{direction:b.DIRECTION_VERTICAL}]]};this.rT=c.$j(f).on("swipeup",function(a){a.preventDefault();e.nextPage()});this.oT=c.$j(f).on("swipedown",function(a){a.preventDefault();e.previousPage()})}else f=
{recognizers:[[b.Swipe,{direction:b.DIRECTION_HORIZONTAL}]]},this.pT=c.$j(f).on("swipeleft",function(a){a.preventDefault();e.nextPage()}),this.qT=c.$j(f).on("swiperight",function(a){a.preventDefault();e.previousPage()})}}},yba:function(){var a=this.Eg();0<a?this.Gl(a,!0):this.Gl(0,!0)},Uo:function(){var a=this.Lb();if(null!=this.Cb&&null!=a){var b;for(b=0;b<this.Cb.length;b++)a.off(this.Cb[b].eventType,this.Cb[b].eventHandler)}},EW:function(a){var b=this;a.find("*").each(function(){b.Lu(this)});b=
null},bL:function(){a.u.af()&&("vertical"==this.options.pageOptions.orientation?(null!=this.rT&&(this.rT.off("swipeup"),this.rT=null),null!=this.oT&&(this.oT.off("swipedown"),this.oT=null)):(null!=this.pT&&(this.pT.off("swipeleft"),this.pT=null),null!=this.qT&&(this.qT.off("swiperight"),this.qT=null)))},ay:function(a,b){var c=g(document.createElement("span"));c.addClass(b);c.addClass(this.V.ol);c.text(a);return c},kqa:function(){var a=this.Df(),b=this.F(this.Ja.Ala),b=this.ay(b,this.V.Q1),c=this.element.attr("id")+
"_oj_pgCtrl_acc_label";b.attr("id",c);a.append(b);return b},oqa:function(){var a=this.F(this.Ja.yla);return this.ay(a,this.V.mma)},lqa:function(){var a=this.F(this.Ja.vla);return this.ay(a,this.V.dma)},mqa:function(){var a=this.F(this.Ja.wla);return this.ay(a,this.V.gma)},nqa:function(){var a=this.F(this.Ja.xla);return this.ay(a,this.V.jma)},pqa:function(){var a=this.F(this.Ja.zla);return this.ay(a,this.V.oma)},qqa:function(){var a=this.Df(),b=g(document.createElement("div"));b.addClass(this.V.R1);
var c=this.zta().attr("id");b.attr("role","navigation");b.attr("aria-labelledby",c);a.append(b);return b},K4:function(){var a=this.Cl(),b=g(document.createElement("div"));b.addClass(this.V.S1);a.append(b);return b},L4:function(){var a=this.vy(),b=g(document.createElement("a"));b.addClass(this.V.XG);var c=this.F(this.Ja.Bla);b.text(c);b.attr(this.wj,"0");b.attr("href","#");a.append(b);return b},rqa:function(){var a=this.vy(),b=g(document.createElement("span"));b.addClass(this.V.zP);var c=this.F(this.Ja.Cla,
{maxRows:this.options.loadMoreOptions.maxCount});b.text(c);a.append(b);return b},M4:function(a,b){var c=this.vy(),h=g(document.createElement("span"));h.addClass(this.V.YG);var k=this.HS(a,b);h.append(k);c.append(h);return h},N4:function(a,b){var c="vertical"==this.options.pageOptions.orientation?!0:!1,h="dots"==this.options.pageOptions.type?!0:!1,k=this.options.pageOptions.layout;null==k&&(k=[this.Lh.qj]);var l=this.Cl(),m=g(document.createElement("div"));m.addClass(this.V.U1);l.append(m);if(-1!=
g.inArray(this.Lh.qj,k)&&!h||-1!=g.inArray(this.Lh.oB,k)||-1!=g.inArray(this.Lh.KG,k)){l=g(document.createElement("div"));l.addClass(this.V.V1);m.append(l);var s=g(document.createElement("label"));s.attr("for",this.element.attr("id")+"_nav_input");s.addClass(this.V.W1);s.addClass("oj-label-inline");var t=this.F(this.Ja.w1);s.text(t);l.append(s);s=g(document.createElement("input"));s.addClass(this.V.Hu);t=this.F(this.Ja.z2);this._focusable(this.element);s.attr("id",this.element.attr("id")+"_nav_input");
s.attr("title",t);s.attr(this.wj,"0");s.val(this.Eg()+1);l.append(s);t=this.b7(a);if(0<this.We()&&this.eg()){var r=g(document.createElement("span"));r.addClass(this.V.EB);var n=this.F(this.Ja.nP,{pageMax:t});r.text(n);l.append(r)}s.ojInputText({displayOptions:{messages:["notewindow"],converterHint:["notewindow"],validatorHint:["notewindow"]},rootAttributes:{style:"width: auto; min-width: 0;"},optionChange:this.Rva.bind(this),validators:[{type:"numberRange",options:{min:1,max:t}}]})}if(-1!=g.inArray(this.Lh.qj,
k)&&!h||-1!=g.inArray(this.Lh.oB,k)||-1!=g.inArray(this.Lh.tma,k))l=g(document.createElement("span")),l.addClass(this.V.FB),s=this.HS(a,b),0<s.text().length&&(l.append("("),l.append(s),l.append(")")),m.append(l);l=g(document.createElement("div"));l.addClass(this.V.T1);m.append(l);if(-1!=g.inArray(this.Lh.qj,k)&&!h||-1!=g.inArray(this.Lh.oB,k)||-1!=g.inArray(this.Lh.E1,k))s=g(document.createElement("a")),s.addClass(this.V.ZG),s.addClass(this.V.Gx),c?s.addClass(this.V.fma):s.addClass(this.V.ema),s.addClass(this.V.Mu),
s.addClass(this.Xa.xu),s.addClass(this.Xa.ec),t=this.F(this.Ja.y2),this.Qe(s),this._focusable(s),s.attr("title",t),s.attr(this.wj,"0"),s.attr("href","#"),s.attr("oncontextmenu","return false;"),t=this.lqa(),s.append(t),c&&s.css("display","block"),l.append(s),s=g(document.createElement("a")),s.addClass(this.V.ZG),s.addClass(this.V.Jx),c?s.addClass(this.V.qma):s.addClass(this.V.pma),s.addClass(this.V.Mu),s.addClass(this.Xa.xu),s.addClass(this.Xa.ec),t=this.F(this.Ja.C2),this.Qe(s),this._focusable(s),
s.attr("title",t),s.attr(this.wj,"0"),s.attr("href","#"),s.attr("oncontextmenu","return false;"),t=this.pqa(),s.append(t),c&&s.css("display","block"),l.append(s);if(-1!=g.inArray(this.Lh.qj,k)||-1!=g.inArray(this.Lh.oB,k)||-1!=g.inArray(this.Lh.Zla,k))s=g(document.createElement("div")),s.addClass(this.V.Y1),l.append(s),this.O4(s,this.a7(),a,b);if(-1!=g.inArray(this.Lh.qj,k)&&!h||-1!=g.inArray(this.Lh.oB,k)||-1!=g.inArray(this.Lh.E1,k))h=g(document.createElement("a")),h.addClass(this.V.ZG),h.addClass(this.V.Ix),
c?h.addClass(this.V.lma):h.addClass(this.V.kma),h.addClass(this.V.Mu),h.addClass(this.Xa.xu),h.addClass(this.Xa.ec),k=this.F(this.Ja.B2),this.Qe(h),this._focusable(h),h.attr("title",k),h.attr(this.wj,"0"),h.attr("href","#"),h.attr("oncontextmenu","return false;"),k=this.nqa(),h.append(k),c&&h.css("display","block"),l.append(h),h=g(document.createElement("a")),h.addClass(this.V.ZG),h.addClass(this.V.Hx),c?h.addClass(this.V.ima):h.addClass(this.V.hma),h.addClass(this.V.Mu),h.addClass(this.Xa.xu),h.addClass(this.Xa.ec),
k=this.F(this.Ja.A2),this.Qe(h),this._focusable(h),h.attr("title",k),h.attr(this.wj,"0"),h.attr("href","#"),h.attr("oncontextmenu","return false;"),k=this.mqa(),h.append(k),c&&h.css("display","block"),l.append(h);return m},O4:function(a,b,c){if(5>b){c=this.F(this.Ja.cla);var h=this.F(this.Ja.bla);throw Error(c+"\n"+h);}h=g(document.createElement("div"));h.addClass(this.V.X1);a.append(h);var k=this.We(),l=this.Eg();a=this.options.pageSize;var m=b;b=[];if(0<=l){if(this.eg()&&k<=m)for(b[0]=0,l=1;l<k;l++)b[l]=
l;else{b.push(0);0!=l&&b.push(l);l!=k-1&&this.eg()&&b.push(k-1);var m=m-b.length,s=l-1,t=1;for(!this.eg()||l!=k-1&&l!=k-2||(t=0);m>t&&1<=s;)b.push(s),s--,m--;l+=1;for(-1==k&&(m=0<c&&c>=a?1:0);0<m&&(l<=k||-1==k);)b.push(l),l++,m--}b.sort(function(a,b){return a-b});for(l=0;l<b.length;l++)k=b[l],this.rR(h,k),l!=b.length-1&&k!=b[l+1]-1&&this.rR(h,-1);!this.eg()&&c>=a&&this.rR(h,-1)}return h},rR:function(a,b){var c=this.Eg(),h=null,k="rtl"===this.hd(),l="vertical"==this.options.pageOptions.orientation?
!0:!1,m="dots"==this.options.pageOptions.type?!0:!1;if(-1==b)h=g(document.createElement("span")),h.addClass(this.V.nma),h.text("...");else{c==b?(h=g(document.createElement("div")),h.addClass(this.Xa.Te),h.addClass(this.Xa.Gh),h.addClass(this.Xa.ec),h.removeClass(this.Xa.Jh)):(h=g(document.createElement("a")),h.removeClass(this.Xa.Te),h.removeClass(this.Xa.Gh),h.removeClass(this.Xa.ec),h.addClass(this.Xa.Jh),h.attr("href","#"));h.attr("data-oj-pagenum",b);m?h.addClass(this.V.cma):h.addClass(this.V.EP);
var s=this.F(this.Ja.Zma,{pageNum:(b+1).toString()});this.Qe(h);this._focusable(h);h.attr("title",s);h.attr(this.wj,"0");h.attr("oncontextmenu","return false;");s=this.oqa();h.append(s);s=g(document.createElement("span"));s.append((b+1).toString());m&&(s.addClass(this.V.bma),this.Qe(s),c==b&&(s.addClass(this.Xa.Te),s.addClass(this.Xa.Gh)));s.attr("dir",k?"rtl":"ltr");h.append(s);this.Qe(h);l&&h.css("display","block")}a.append(h);return h},zta:function(){var a=this.Df(),b=null;a&&(b=a.find("."+this.V.Q1))&&
0<b.length&&(b=g(b.get(0)));return b},Df:function(){return g(this.element)},Cl:function(){if(!this.H3){var a=this.Df(),b=null;a&&(b=a.find("."+this.V.R1))&&0<b.length&&(this.H3=g(b.get(0)))}return this.H3},vy:function(){if(!this.CQ){var a=this.Cl(),b=null;a&&(b=a.children("."+this.V.S1))&&0<b.length&&(this.CQ=g(b.get(0)))}return this.CQ},IKa:function(){if(!this.DQ){var a=this.vy(),b=null;a&&(b=a.children("."+this.V.XG))&&0<b.length&&(this.DQ=g(b.get(0)))}return this.DQ},JKa:function(){if(!this.EQ){var a=
this.vy(),b=null;a&&(b=a.children("."+this.V.YG))&&0<b.length&&(this.EQ=g(b.get(0)))}return this.EQ},zo:function(){if(!this.FQ){var a=this.Cl(),b=null;a&&(b=a.children("."+this.V.U1))&&0<b.length&&(this.FQ=g(b.get(0)))}return this.FQ},Ata:function(){if(!this.GQ){var a=this.zo(),b=null;a&&(b=a.find("."+this.V.Hu))&&0<b.length&&(this.GQ=g(b.get(0)))}return this.GQ},Bta:function(){if(!this.HQ){var a=this.zo(),b=null;a&&(b=a.find("."+this.V.FB))&&0<b.length&&(this.HQ=g(b.get(0)))}return this.HQ},Cta:function(){var a=
this.zo(),b=null;a&&(b=a.find("."+this.V.X1))&&0<b.length&&(b=g(b.get(0)));return b},k7:function(){var a=this.zo(),b=null;if(a)if((b=a.find("."+this.V.T1))&&0<b.length)b=g(b.get(0));else return null;return b},WS:function(){var a=this.zo(),b=null;if(a)if((b=a.find("."+this.V.V1))&&0<b.length)b=g(b.get(0));else return null;return b}})})();a.Components.Ta("ojPagingControl","baseComponent",{properties:{data:{},loadMoreOptions:{type:"Object\x3cstring, number\x3e"},mode:{type:"string"},overflow:{type:"string"},
pageOptions:{type:"Object\x3cstring, Array|number\x3e"},pageSize:{type:"number"}},methods:{firstPage:{},getNodeBySubId:{},getSubIdByNode:{},lastPage:{},loadNext:{},nextPage:{},page:{},previousPage:{},refresh:{}},extension:{_widgetName:"ojPagingControl"}});a.Components.register("oj-paging-control",a.Components.getMetadata("ojPagingControl"))});