/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojpagingtabledatasource"],function(a){a.Tf=function(a,c){this.Aw=a;this.ir=c};o_("PagingHeaderSet",a.Tf,a);a.Tf.prototype.getData=function(a,c){return this.Aw.getData(a+this.ir,c)};a.b.g("PagingHeaderSet.prototype.getData",{getData:a.Tf.prototype.getData});a.Tf.prototype.getMetadata=function(a,c){return this.Aw.getMetadata(a+this.ir,c)};a.b.g("PagingHeaderSet.prototype.getMetadata",{getMetadata:a.Tf.prototype.getMetadata});a.Tf.prototype.getCount=function(){return this.Aw.getCount()};
a.b.g("PagingHeaderSet.prototype.getCount",{getCount:a.Tf.prototype.getCount});a.Tf.prototype.getLevelCount=function(){return this.Aw.getLevelCount()};a.b.g("PagingHeaderSet.prototype.getLevelCount",{getLevelCount:a.Tf.prototype.getLevelCount});a.Tf.prototype.getExtent=function(a,c){return this.Aw.getExtent(a+this.ir,c)};a.b.g("PagingHeaderSet.prototype.getExtent",{getExtent:a.Tf.prototype.getExtent});a.Tf.prototype.getDepth=function(a,c){return this.Aw.getDepth(a+this.ir,c)};a.b.g("PagingHeaderSet.prototype.getDepth",
{getDepth:a.Tf.prototype.getDepth});a.Tf.prototype.Qea=function(){return this.Aw};a.b.g("PagingHeaderSet.prototype.getHeaderSet",{Qea:a.Tf.prototype.Qea});a.Tf.prototype.XE=function(){return this.ir};a.b.g("PagingHeaderSet.prototype.getStartIndex",{XE:a.Tf.prototype.XE});a.nb=function(g){if(!(g instanceof a.Dr))throw new a.ia("Not a datagridatasource","Not a datagridatasource",a.ia.Xc.ERROR);this.Ld=g;this.pa=0;this.Init()};o_("PagingDataGridDataSource",a.nb,a);a.b.ta(a.nb,a.Dr,"oj.PagingDataGridDataSource");
a.nb.prototype.Init=function(){a.nb.t.Init.call(this);this.XD()};a.b.g("PagingDataGridDataSource.prototype.Init",{Init:a.nb.prototype.Init});a.nb.prototype.XD=function(){this.Ld.on("change",this.tua.bind(this))};a.nb.prototype.getPage=function(){return this.ge};a.b.g("PagingDataGridDataSource.prototype.getPage",{getPage:a.nb.prototype.getPage});a.nb.prototype.setPage=function(g,c){c=c||{};g=parseInt(g,10);try{a.nb.t.handleEvent.call(this,a.$c.Q.BEFOREPAGE,{page:g,previousPage:this.ge})}catch(b){return Promise.reject(null)}this.Db=
null!=c.pageSize?c.pageSize:this.Db;c.startIndex=g*this.Db;var d=this.ge;this.ge=g;this.pa=c.startIndex;var e=this;return new Promise(function(a,b){e.Cg(c).then(function(){a(null)},function(){e.ge=d;e.pa=e.ge*e.Db;b(null)})})};a.b.g("PagingDataGridDataSource.prototype.setPage",{setPage:a.nb.prototype.setPage});a.nb.prototype.Cg=function(a){this.qq=!0;this.pa=a.startIndex;var c=this;return new Promise(function(a){c.handleEvent("change",{operation:"sync",pageSize:c.Db});a(void 0)})};a.nb.prototype.fetch=
function(a){this.Db=a.pageSize+a.startIndex;a.startIndex=0;return this.Cg(a)};a.b.g("PagingDataGridDataSource.prototype.fetch",{fetch:a.nb.prototype.fetch});a.nb.prototype.getStartItemIndex=function(){return this.pa};a.b.g("PagingDataGridDataSource.prototype.getStartItemIndex",{getStartItemIndex:a.nb.prototype.getStartItemIndex});a.nb.prototype.getEndItemIndex=function(){return this.Bk};a.b.g("PagingDataGridDataSource.prototype.getEndItemIndex",{getEndItemIndex:a.nb.prototype.getEndItemIndex});a.nb.prototype.getPageCount=
function(){var a=this.totalSize();return-1==a?-1:Math.ceil(a/this.Db)};a.b.g("PagingDataGridDataSource.prototype.getPageCount",{getPageCount:a.nb.prototype.getPageCount});a.nb.prototype.tua=function(g){switch(g.operation){case "refresh":this.pa=0;this.handleEvent("change",{operation:"sync",pageSize:this.Db});this.handleEvent(a.Fa.Q.REFRESH,null);break;case "reset":this.handleEvent(a.Fa.Q.RESET,null);break;case "insert":this.handleEvent(a.Fa.Q.ADD,{index:g.indexes.row});break;case "delete":this.handleEvent(a.Fa.Q.REMOVE,
null);break;case "update":g.indexes.row=0<=g.indexes.row-this.pa?g.indexes.row-this.pa:-1;this.handleEvent("change",g);break;default:this.handleEvent("change",g),this.handleEvent(a.Fa.Q.SYNC,null)}};a.nb.prototype.getCount=function(a){var c=this.Ld.getCount(a);return"row"===a&&0<=c?this.pa+this.Db<c?this.Db:c-this.pa:c};a.b.g("PagingDataGridDataSource.prototype.getCount",{getCount:a.nb.prototype.getCount});a.nb.prototype.getCountPrecision=function(a){return this.Ld.getCountPrecision(a)};a.b.g("PagingDataGridDataSource.prototype.getCountPrecision",
{getCountPrecision:a.nb.prototype.getCountPrecision});a.nb.prototype.fetchHeaders=function(a,c,b){null==this.qq?null!=c&&c.success&&c.success.call(b.success,null,a,null):"row"===a.axis?(a.start+=this.pa,a.start+a.count>this.pa+this.Db&&(a.count=this.Db-a.start),this.cz={callbacks:c,callbackObjects:b},this.Ld.fetchHeaders(a,{success:this.LT.bind(this),error:this.Yva.bind(this)},b)):this.Ld.fetchHeaders(a,c,b)};a.b.g("PagingDataGridDataSource.prototype.fetchHeaders",{fetchHeaders:a.nb.prototype.fetchHeaders});
a.nb.prototype.LT=function(g,c,b){var d,e;c.start-=this.pa;c.count+=1;null!=g&&(d=new a.Tf(g,this.pa));null!=b&&(e=new a.Tf(b,this.pa));g=this.cz.callbacks.success;b=this.cz.callbackObjects.success;this.cz=null;g.call(b,d,c,e)};a.nb.prototype.Yva=function(a){var c,b;c=this.cz.callbacks.error;b=this.cz.callbackObjects.error;this.cz=null;c.call(b,a)};a.nb.prototype.fetchCells=function(a,c,b){var d;if(null==this.qq)d={getData:function(){return null},getMetaData:function(){return null},getStart:function(){return 0},
getCount:function(){return 0},getLevelCount:function(){return 0},getExtent:function(){return 0},getDepth:function(){return 1}},null!=c&&c.success&&c.success.call(b.success,d,a);else{for(d=0;d<a.length;d+=1)"row"===a[d].axis&&(a[d].start+=this.pa,a[d].start+a[d].count>this.pa+this.Db&&(a[d].count=this.Db-a[d].start));this.az={callbacks:c,callbackObjects:b};this.Ld.fetchCells(a,{success:this.sua.bind(this),error:this.rua.bind(this)},b)}};a.b.g("PagingDataGridDataSource.prototype.fetchCells",{fetchCells:a.nb.prototype.fetchCells});
a.nb.prototype.sua=function(g,c){var b,d,e;for(b=0;b<c.length;b+=1)"row"===c[b].axis&&(c[b].start-=this.pa,c[b].count+=1);b=new a.jl(g,this.pa);d=this.az.callbacks.success;e=this.az.callbackObjects.success;this.az=null;this.Bk=this.pa+g.getCount("row")-1;this.handleEvent("sync",{data:Array(g.getCount("row")),startIndex:this.pa});d.call(e,b,c)};a.nb.prototype.rua=function(a){var c,b;c=this.az.callbacks.error;b=this.az.callbackObjects.error;this.az=null;c.call(b,a)};a.nb.prototype.keys=function(a){return this.Ld.keys({column:a.column,
row:a.row+this.pa})};a.b.g("PagingDataGridDataSource.prototype.keys",{keys:a.nb.prototype.keys});a.nb.prototype.indexes=function(a){a=this.Ld.indexes(a);-1!=a.row&&(a.row-=this.pa);return a};a.b.g("PagingDataGridDataSource.prototype.indexes",{indexes:a.nb.prototype.indexes});a.nb.prototype.getCapability=function(a){return this.Ld.getCapability(a)};a.b.g("PagingDataGridDataSource.prototype.getCapability",{getCapability:a.nb.prototype.getCapability});a.nb.prototype.size=function(){var a;if(null==this.qq)return-1;
a=this.Ld.getCount("row");return this.Ld.getCount("row")>this.Db?this.Db:a};a.b.g("PagingDataGridDataSource.prototype.size",{size:a.nb.prototype.size});a.nb.prototype.sort=function(a,c,b){this.Ld.sort(a,c,b)};a.b.g("PagingDataGridDataSource.prototype.sort",{sort:a.nb.prototype.sort});a.nb.prototype.totalSize=function(){return null==this.qq?-1:this.Ld.getCount("row")};a.b.g("PagingDataGridDataSource.prototype.totalSize",{totalSize:a.nb.prototype.totalSize});a.nb.prototype.totalSizeConfidence=function(){return"actual"};
a.b.g("PagingDataGridDataSource.prototype.totalSizeConfidence",{totalSizeConfidence:a.nb.prototype.totalSizeConfidence});a.nb.prototype.moveOK=function(a,c,b){return this.Ld.moveOK(a,c,b)};a.b.g("PagingDataGridDataSource.prototype.moveOK",{moveOK:a.nb.prototype.moveOK});a.nb.prototype.move=function(a,c,b,d,e){this.Ld.move(a,c,b,d,e)};a.b.g("PagingDataGridDataSource.prototype.move",{move:a.nb.prototype.move});a.jl=function(a,c){this.CM=a;this.ir=c};o_("PagingCellSet",a.jl,a);a.jl.prototype.getData=
function(a){return this.CM.getData({column:a.column,row:a.row+this.ir})};a.b.g("PagingCellSet.prototype.getData",{getData:a.jl.prototype.getData});a.jl.prototype.getMetadata=function(a){return this.CM.getMetadata({column:a.column,row:a.row+this.ir})};a.b.g("PagingCellSet.prototype.getMetadata",{getMetadata:a.jl.prototype.getMetadata});a.jl.prototype.getCount=function(a){return this.CM.getCount(a)};a.b.g("PagingCellSet.prototype.getCount",{getCount:a.jl.prototype.getCount});a.jl.prototype.xea=function(){return this.CM};
a.b.g("PagingCellSet.prototype.getCellSet",{xea:a.jl.prototype.xea});a.jl.prototype.XE=function(){return this.ir};a.b.g("PagingCellSet.prototype.getStartIndex",{XE:a.jl.prototype.XE})});