/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","jqueryui-amd/position"],function(a,g){a.Qd={};a.Qd.km=function(c,b){for(var d=g.extend({},c),e=0;e<a.Qd.v0.length;e++){var f=a.Qd.v0[e],h=d[f];h&&(d[f]=h.replace("start",b?"right":"left").replace("end",b?"left":"right").replace("\x3c",b?"+":"-").replace("\x3e",b?"-":"+"))}return d};a.Qd.mIa=function(a,b,d){return"event"===a?d:null==a||"launcher"===a?b:a};a.Qd.Mya=function(a){g.each(["pageX","pageY"],function(b,d){if(a&&void 0===a[d]&&a.originalEvent){var e=
a.originalEvent,f=e.type;(f="touchstart"===f||"touchmove"===f?"touches":"touchend"===f?"changedTouches":null)&&(e=e[f][0])&&(a[d]=e[d])}})};a.Qd.v0=["my","at"];a.Qd.nY=function(c){return c.target&&0<c.target.height&&0<c.target.width?!a.Qd.OHa(c.target.element):!1};a.Qd.OHa=function(c){function b(b,c){if(-1<["hidden","scroll","auto"].indexOf(c.overflowY)){if(-1>b.bottom-c.top)return!1;var d="auto"===c.overflowX||"scroll"===c.overflowX?a.u.dM():0;if(1>c.bottom-d-b.top)return!1}if(-1<["hidden","scroll",
"auto"].indexOf(c.overflowX)){d="auto"!==c.overflowY&&"scroll"!==c.overflowY||"rtl"!==a.u.wn()?0:a.u.dM();if(-1>b.right-(c.left+d))return!1;d="auto"!==c.overflowX&&"scroll"!==c.overflowX||"ltr"!==a.u.wn()?0:a.u.dM();if(-1<b.left-(c.right-d))return!1}return!0}function d(a){return"visible"!==a.css("overflow-x")||"visible"!==a.css("overflow-y")}function e(a){var b=a[0];return 1===b.nodeType?(b=g.extend({},b.getBoundingClientRect()),b.overflowX=a.css("overflow-x"),b.overflowY=a.css("overflow-y"),b):{height:0,
width:0}}function f(b){return-1<["fixed","absolute","relative"].indexOf(b.css("position"))&&(0<Math.abs(a.u.Pq(b.css("top")))||0<Math.abs(a.u.Pq(b.css("bottom")))||0<Math.abs(a.u.Pq(b.css("left")))||0<Math.abs(a.u.Pq(b.css("right"))))}if(!c)return!1;if(g.isWindow(c[0])||f(c))return!0;var h=e(c),k=!0;for(c=c.parent();k&&c&&0<c.length&&"BODY"!==c[0].nodeName&&1===c[0].nodeType&&!f(c);){if(d(c)){var l=e(c);0<l.height&&0<l.width&&(k=b(h,l))}c=c.parent()}return k};g.ui.position.flipcenter={left:function(c,
b){var d=c.left;g.ui.position.flip.left.call(this,c,b);var e=b.within,f=e.isWindow?e.scrollLeft:e.offset.left,h=c.left-b.collisionPosition.marginLeft,e=h+b.collisionWidth-e.width-f;if(0<f-h||0<e)"right"===b.at[0]?d-=b.targetWidth/2:"left"===b.at[0]&&(d+=b.targetWidth/2),f="rtl"===a.u.wn()?-1:1,d-=b.elemWidth/2*f,c.left=Math.max(0,d)},top:function(a,b){var d=a.top;g.ui.position.flip.top.call(this,a,b);var e=b.within,e=e.isWindow?e.scrollTop:e.offset.top,f=a.top-b.collisionPosition.marginTop,h=f+b.collisionHeight-
b.within.height-e;if(0<e-f||0<h)"top"===b.at[1]?d+=b.targetHeight/2:"bottom"===b.at[1]&&(d-=b.targetHeight/2),d+=b.elemHeight/2,a.top=Math.max(0,d)}};g.ui.position.flip={left:g.ui.position.flip.left.bind(this),top:function(a,b){var d=b.within,e=d.offset.top+d.scrollTop,f=d.height,g=d.isWindow?d.scrollTop:d.offset.top,k=a.top-b.collisionPosition.marginTop,d=k-g,k=k+b.collisionHeight-f-g,l="top"===b.my[1]?-b.elemHeight:"bottom"===b.my[1]?b.elemHeight:0,m="top"===b.at[1]?b.targetHeight:"bottom"===b.at[1]?
-b.targetHeight:0,s=-2*b.offset[1];0>d?(e=a.top+l+m+s+b.collisionHeight-f-e,(0>e||e<Math.abs(d))&&0>k&&d>k&&(a.top+=l+m+s)):0<k&&(e=a.top-b.collisionPosition.marginTop+l+m+s-g,0<e||Math.abs(e)<k)&&(a.top+=l+m+s)}};a.U=function(){this.Init()};a.b.ta(a.U,a.b,"oj.PopupService");a.U.prototype.Init=function(){a.U.t.Init.call(this)};a.U.Je=function(){a.U.ZU||(a.U.ZU=new a.Pb);return a.U.ZU};a.U.prototype.open=function(){a.o.kd()};a.U.prototype.close=function(){a.o.kd()};a.U.prototype.Hz=function(){a.o.kd()};
a.U.prototype.DN=function(){a.o.kd()};a.U.prototype.destroy=function(){delete a.U.ZU};a.U.gk={NONE:"none",qO:"modal",Mja:"modeless"};a.U.Fd={lx:"ojPopupRemove",kx:"ojPopupClose",Mp:"ojPopupRefresh",jx:"ojPopupAutoDismiss"};a.U.Fr={IO:"topLevel",J_:"nearestAncestor"};a.U.qb={Bh:"popup",fu:"events",gk:"modality",aB:"launcher",eB:"position",Gr:"layerSelectors",Fr:"layerLevel"};a.Pb=function(){this.Init()};a.b.ta(a.Pb,a.U,"oj.PopupServiceImpl");a.Pb.prototype.open=function(c){a.o.di(c);var b=c[a.U.qb.Bh];
a.o.ue(b,jQuery);var d=c[a.U.qb.aB];a.o.ue(d,jQuery);var e=c[a.U.qb.eB];a.o.pda(e);var f=c[a.U.qb.fu];a.o.di(f);var g=c[a.U.qb.gk];if(!g||a.U.gk.Mja!==g&&a.U.gk.qO!==g)g=a.U.gk.NONE;var k=c[a.U.qb.Gr];a.o.Gq(k);c=c[a.U.qb.Fr];if(!c||a.U.Fr.IO!==c&&a.U.Fr.J_!==c)c=a.U.Fr.J_;a.u.dia(b,d);a.T.UDa(b,d,f,g,k,c);b.show();b.removeAttr("aria-hidden");e&&b.position(e);this.rQ();a.Components.yr(b[0])};a.Pb.prototype.close=function(c){a.o.di(c);c=c[a.U.qb.Bh];a.o.ue(c,jQuery);a.T.MIa(c);c.hide();c.attr("aria-hidden",
"true");c.css({top:"auto",bottom:"auto",left:"auto",right:"auto"});a.u.dia(c,null);this.rQ();a.Components.Wt(c[0])};a.Pb.prototype.Hz=function(c){a.o.di(c);var b=c[a.U.qb.Bh];a.o.ue(b,jQuery);b=a.T.RE(b);a.o.ue(b,jQuery);var d=c[a.U.qb.fu];d&&a.T.lda(b,d);(d=c[a.U.qb.gk])&&a.T.mda(b,d);c=c[a.U.qb.Gr];a.bb.Vl(c)||b.attr("class",c)};a.Pb.prototype.DN=function(c,b,d){var e={};e.event=b;e.argsArray=d;c=a.T.RE(c);a.T.kN(c,this.jDa,e)};a.Pb.prototype.jDa=function(c,b){var d=b.event,e=b.argsArray,f=a.T.OX(c);
f&&g.isFunction(f[d])&&f[d].apply(this,e);return a.T.pj.$t};a.Pb.prototype.rQ=function(){var c=a.T.Rfa(),b=this.V3;if(!c&&b){window.removeEventListener("resize",a.Pb.Ss,!0);window.removeEventListener("scroll",a.Pb.Ss,!0);c=document.documentElement;c.removeEventListener("mousewheel",a.Pb.Ss,!0);c.removeEventListener("DOMMouseScroll",a.Pb.Ss,!0);delete this.V3;for(var d=0;d<a.Pb.bH.length;d++){var e=a.Pb.bH[d];c.removeEventListener(e,b,!0)}if(b=this.cca)b.destroy(),delete this.cca}else if(c&&!b){window.addEventListener("resize",
a.Pb.Ss,!0);window.addEventListener("scroll",a.Pb.Ss,!0);c=document.documentElement;c.addEventListener("mousewheel",a.Pb.Ss,!0);c.addEventListener("DOMMouseScroll",a.Pb.Ss,!0);b=this.V3=g.proxy(this.Hra,this);for(d=0;d<a.Pb.bH.length;d++)e=a.Pb.bH[d],c.addEventListener(e,b,!0);a.u.af()&&(this.cca=new a.jk(b))}};a.Pb.prototype.Hra=function(c){var b=g(c.target);if(!a.T.Rfa())this.rQ();else if(!a.u.gga(c)&&("focus"!==c.type||b.is(":focusable"))){var d=a.T.ot();if("keydown"===c.type&&a.T.qHa()&&!a.u.op(d[0],
b[0]))a.T.rFa(g.Event(c));else{var e=a.T.RE(b);if(d[0]!==e[0]){if(!e.hasClass(a.Pb.FG)){var f=this.BU;f&&f.removeClass(a.Pb.FG);e.addClass(a.Pb.FG);this.BU=e}}else if(f=this.BU)f.removeClass(a.Pb.FG),delete this.BU;if("focus"!==c.type||"-1"!==b.attr("tabindex")){var b={},e={},h;for(h in c)a.Pb.Gka[h]&&!g.isFunction(c[h])&&(e[h]=c[h]);b.event=g.Event(c,e);a.T.kN(d,a.Pb.Oza,b)}}}};a.Pb.Oza=function(c,b){var d=a.T.OX(c),e=b.event;if(d&&g.isFunction(d[a.U.Fd.jx]))d[a.U.Fd.jx](e);return a.T.pj.$t};a.Pb.Ss=
function(){isNaN(a.Pb.naa)&&(a.Pb.naa=window.setTimeout(function(){delete a.Pb.naa;var c=a.T.ot();g.isFunction(window.requestAnimationFrame)?a.Pb.Wna=window.requestAnimationFrame(function(){delete a.Pb.Wna;a.T.kN(c,a.Pb.paa)}):a.T.kN(c,a.Pb.paa)},a.Pb.uma))};a.Pb.paa=function(c,b){if(0<b.level)return a.T.pj.sG;var d=a.T.OX(c);if(d&&g.isFunction(d[a.U.Fd.Mp]))d[a.U.Fd.Mp]();return a.T.pj.$t};a.Pb.prototype.destroy=function(){a.Pb.t.destroy.call(this)};a.Pb.FG="oj-focus-within";a.Pb.bH=["focus","mousedown",
"keydown"];a.Pb.Gka={altKey:!0,bubbles:!0,cancelable:!0,ctrlKey:!0,currentTarget:!0,eventPhase:!0,metaKey:!0,relatedTarget:!0,shiftKey:!0,target:!0,timeStamp:!0,view:!0,which:!0,button:!0,buttons:!0,clientX:!0,clientY:!0,offsetX:!0,offsetY:!0,pageX:!0,pageY:!0,screenX:!0,screenY:!0,toElement:!0,"char":!0,charCode:!0,key:!0,keyCode:!0};a.Pb.uma=10;a.T={};a.T.RE=function(c){if(!c)return a.T.ot();for(;c&&0<c.length&&c.attr("oj.ZOrderUtils._SURROGATE_ATTR")!==a.T.bP;){if(a.T.YT(c[0]))return c;c=c.parent()}return a.T.ot()};
a.T.ot=function(){var c=g(document.getElementById(a.T.bP));if(0<c.length)return c;c=g("\x3cdiv\x3e");c.attr("role","presentation");c.attr("id",a.T.bP);c.prependTo(g(document.body));return c};a.T.UDa=function(c,b,d,e,f,h){var k=c[0];if(a.T.YT(k.parentNode))throw Error("JET Popup is already open - id: "+k.getAttribute("id"));b=a.T.RE(h===a.U.Fr.IO?null:b);h=g("\x3cdiv\x3e");var l=c.attr("id");a.bb.Vl(l)?h.uniqueId():h.attr("id",[l,"layer"].join("_"));h.attr("role","presentation");h.addClass(f);c.after(h);
f=a.T.tR(h);a.Components.ti(k);c.appendTo(h);h.appendTo(b);a.Components.Tg(k);a.T.mda(h,e);a.T.lda(h,d,f)};a.T.lda=function(c,b,d){if(!d){var e=c.attr(a.T.HB);e&&(d=g(document.getElementById(e)))}c.data(a.T.EG,b);d&&b&&g.isFunction(b[a.U.Fd.lx])&&(d.surrogate(),d.surrogate("option","beforeDestroy",b[a.U.Fd.lx]))};a.T.OX=function(c){return c.data(a.T.EG)};a.T.tR=function(c){var b=g("\x3cscript\x3e"),d=c.attr("id");a.bb.Vl(d)?b.uniqueId():b.attr("id",[d,"surrogate"].join("_"));b.insertBefore(c);d=b.attr("id");
c.attr(a.T.HB,d);return b};a.T.BAa=function(c){var b=c.attr(a.T.HB);c.removeAttr(a.T.HB);b=g(document.getElementById(b));c.insertAfter(b);b.surrogate("option","beforeDestroy",null);b.remove()};a.T.MIa=function(c){var b=a.T.RE(c);a.T.fZ(b,a.T.qpa);a.T.qV(b);b.removeData(a.T.EG);b.removeData(a.T.rP);var d=c[0];a.Components.ti(d);a.T.BAa(b);a.u.unwrap(c,b);a.Components.Tg(d)};a.T.qpa=function(c,b){if(0<b.level)return a.T.pj.sG;var d=c.data(a.T.EG);if(d&&g.isFunction(d[a.U.Fd.kx]))d[a.U.Fd.kx]();return a.T.pj.$t};
a.T.mda=function(c,b){var d=c.data(a.T.rP);c.data(a.T.rP,b);a.bb.Vl(d)?a.U.gk.qO===b?a.T.T2(c):a.T.qV(c):d!==b&&(b!==d&&b===a.U.gk.qO?a.T.T2(c):a.T.qV(c))};a.T.qHa=function(){for(var c=a.T.ot().children(),b=c.length-1;-1<b;b--)if(g(c[b]).hasClass(a.T.O1))return!0;return!1};a.T.T2=function(c){var b=g("\x3cdiv\x3e");b.addClass(a.T.O1);b.addClass(c[0].className);b.attr("role","presentation");var d=c.attr("id");a.bb.Vl(d)?b.uniqueId():b.attr("id",[d,"overlay"].join("_"));c.before(b);b=b.attr("id");c.attr(a.T.wP,
b)};a.T.qV=function(c){var b=c.attr(a.T.wP);a.bb.Vl(b)||(c.removeAttr(a.T.wP),g(document.getElementById(b)).remove())};a.T.pj={$t:0,sG:1,SN:2};a.T.lH={N_:0,M_:1};a.T.kN=function(c,b,d){d||(d={});d.level=0;d.type=a.T.lH.M_;a.T.PW(c,b,d)};a.T.fZ=function(c,b,d){d||(d={});d.level=0;d.type=a.T.lH.N_;a.T.PW(c,b,d)};a.T.PW=function(c,b,d){var e=d.level;c=c.children();for(var f=c.length-1;-1<f;f--){var h=g(c[f]);if(a.T.YT(h[0])){var k;if(d.type===a.T.lH.N_){k=b(h,d);if(k===a.T.pj.SN)return k;if(k===a.T.pj.sG)break}d.level=
e+1;k=a.T.PW(h,b,d);d.level=e;if(k===a.T.pj.SN)return k;if(d.type===a.T.lH.M_){k=b(h,d);if(k===a.T.pj.SN)return k;if(k===a.T.pj.sG)break}}}return a.T.pj.$t};a.T.YT=function(c){return 1===c.nodeType&&c.hasAttribute(a.T.HB)?!0:!1};a.T.Rfa=function(){return 0<a.T.ot().children().length};a.T.TX=function(){var c={popupCount:0},b=a.T.ot();a.T.fZ(b,a.T.Uya,c);return c.popupCount};a.T.Uya=function(c,b){b.popupCount+=1;return a.T.pj.$t};a.T.uX=function(){var c={},b=[];c.popups=b;b=a.T.ot();a.T.fZ(b,a.T.Wya,
c);b=c.popups;return g(b)};a.T.Wya=function(c,b){b.popups.push(c[0]);return a.T.pj.$t};a.T.iX=function(c,b){function d(b,c){for(var d=["absolute","relative","fixed"],e=b.parents(),f=[],h=e.length-1;-1<h;h--)f.push(g(e[h]));e=f;e.push(b);for(var f=[],k=0,h=0;h<e.length;h++){var l=e[h],m=l.css("position"),s=a.u.LFa(l.css("opacity")),z=a.u.Pq(l.css("z-index")),l=g.inArray(l[0],l.parent().children());-1<g.inArray(m,d)?f.push({weight:[k++,z,l],order:[l]}):1>s?f.push({weight:[k++,1,l],order:[l]}):c&&f.push({weight:[0,
0,l],order:[l]})}return f}function e(a,b){for(var c=Math.max(a.length,b.length),d=0;d<c;d++){var e=d<a.length?a[d]:-1,f=d<b.length?b[d]:-1;if(e!==f)return e<f?-1:1}return 0}a.o.ue(c,jQuery);a.o.ue(b,jQuery);for(var f=d(c,!1),h=d(b,!1),k=Math.max(f.length,h.length),l=0;l<k;l++){var m=l<f.length?f[l].weight:[-1],s=l<h.length?h[l].weight:[-1],m=e(m,s);if(0!==m)return m}f=d(c,!0);h=d(b,!0);k=Math.max(f.length,h.length);for(l=0;l<k;l++)if(m=l<f.length?f[l].order:[-1],s=l<h.length?h[l].order:[-1],m=e(m,
s),0!==m)return m;return 0};a.T.rFa=function(a){a.stopPropagation();a.preventDefault()};a.T.EG="oj-popup-events";a.T.rP="oj-popup-modality";a.T.bP="__oj_zorder_container";a.T.HB="data-oj-surrogate-id";a.T.wP="data-oj-overlayid";a.T.O1="oj-component-overlay";g.widget("oj.surrogate",{options:{create:null,beforeDestroy:null},_create:function(){this._super();this.element.uniqueId()},_destroy:function(){this._trigger("beforeDestroy");this.element.removeUniqueId();this._super()}});a.jk=function(a){this.yca=
a;this.Init()};a.b.ta(a.jk,a.b,"oj.SimpleTapRecognizer");a.jk.prototype.Init=function(){a.jk.t.Init.call(this);for(var c=this.F5=g.proxy(this.pI,this),b=document.documentElement,d=0;d<a.jk.iH.length;d++)b.addEventListener(a.jk.iH[d],c,!0)};a.jk.prototype.pI=function(c){var b=this.yca,d=c.type;"touchstart"===d?(this.$v=c,this.$v.QCa=(new Date).getTime()):"touchmove"===d||"touchcancel"===d?delete this.$v:"touchend"===d&&(this.$v&&(c=this.$v.QCa,isNaN(c)?b(this.$v):(new Date).getTime()-c<a.jk.rma&&b(this.$v)),
delete this.$v)};a.jk.prototype.destroy=function(){delete this.yca;var c=this.F5;delete this.F5;for(var b=document.documentElement,d=0;d<a.jk.iH.length;d++)b.removeEventListener(a.jk.iH[d],c,!0)};a.jk.iH=["touchstart","touchmove","touchcancel","touchend"];a.jk.rma=700;a.xg=function(){this.Init()};a.b.ta(a.xg,a.b,"oj.PopupLiveRegion");a.xg.prototype.Init=function(){a.xg.t.Init.call(this);isNaN(a.xg.SD)?a.xg.SD=1:++a.xg.SD};a.xg.prototype.destroy=function(){if(!isNaN(a.xg.SD)&&(--a.xg.SD,1>a.xg.SD)){var c=
g(document.getElementById(a.xg.FP));0<c.length&&c.remove()}};a.xg.prototype.YDa=function(c){if(!a.bb.mi(c)){var b=a.xg.mta();b.children().remove();g("\x3cdiv\x3e").text(c).appendTo(b)}};a.xg.mta=function(){var c=g(document.getElementById(a.xg.FP));0===c.length&&(c=g("\x3cdiv\x3e"),c.attr({id:a.xg.FP,role:"log","aria-live":"polite","aria-relevant":"additions"}),c.addClass("oj-helper-hidden-accessible"),c.appendTo(document.body));return c};a.xg.FP="__oj_popup_arialiveregion";a.kl=function(c,b,d,e){a.o.ue(c,
jQuery);a.o.Gq(b);a.o.et(d);a.o.YW(e);this.MK=c;this.Yy=b;this.PQ=d;this.Fl=e?e:"";this.Init()};a.b.ta(a.kl,a.b,"oj.PopupSkipLink");a.kl.prototype.Init=function(){a.kl.t.Init.call(this);var c=this.MK,b=this.PQ,d=this.Yy;delete this.Yy;var e=this.Fl;delete this.Fl;var f=g("\x3ca\x3e").attr({tabindex:"-1",href:"#"});a.bb.mi(e)||f.attr("id",e);f.addClass("oj-helper-hidden-accessible");f.text(d);f.insertAfter(c);f.on("click",b);c.data(a.kl.fH,f)};a.kl.prototype.destroy=function(){var c=this.MK;delete this.MK;
var b=this.PQ;delete this.PQ;if(c){var d=c.data(a.kl.fH);c.removeData(a.kl.fH);d&&(d.off("click",b),d.remove())}};a.kl.prototype.getLink=function(){var c=this.MK,b;c&&(b=c.data(a.kl.fH));return b};a.kl.fH="oj-skiplink"});