/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojpopupcore"],function(a,g){(function(){var c="oj-left oj-center oj-right oj-top oj-middle oj-bottom".split(" "),b={"right-top":"oj-right oj-top","right-middle":"oj-right oj-middle","right-bottom":"oj-right oj-bottom","left-top":"oj-left oj-top","left-middle":"oj-left oj-middle","left-bottom":"oj-left oj-bottom","center-top":"oj-center oj-top","center-middle":"oj-left oj-middle","center-bottom":"oj-center oj-bottom"};a.Na("oj.ojPopup",g.oj.baseComponent,
{widgetEventPrefix:"oj",options:{autoDismiss:"focusLoss",chrome:"default",initialFocus:"auto",position:{my:"start top",at:"start bottom",of:"",collision:"flip"},tail:"none",modality:"modeless",role:"tooltip",beforeOpen:null,open:null,beforeClose:null,close:null,focus:null},_ComponentCreate:function(){this._super();var a;this.oe?a=g(this.oe):(a=g("\x3cdiv\x3e"),this.element.after(a));this.ig=a.hide().addClass("oj-popup").attr("aria-hidden","true");a.addClass("oj-component");var b=g("\x3cdiv\x3e").addClass("oj-popup-content");
b.attr("role","presentation");b.appendTo(a);this.element.appendTo(b);this.element.show();this.S4();this.pba();this.zE=g.proxy(this.AE,this)},_destroy:function(){this.isOpen()&&this.Uu();this.n5();delete this.zE;delete this.hn;a.u.unwrap(this.element,this.ig);this.element.hide();var b=this.fs;isNaN(b)||(delete this.fs,window.clearTimeout(b));this.o5();this._super()},widget:function(){return this.ig},open:function(b,c){if(this.isOpen()&&(this.close(),this.isOpen()))return;this.UBa(b);var f=this.ig;
b=this.Id;a.bb.Vl(f.attr("id"))&&f.attr("id",this.eJ("wrapper"));if(!1!==this._trigger("beforeOpen")){this.Fba(c);var g=this.options;this.GV(g.autoDismiss);this.xna();f.attr("role",g.role);c=g.position;var k="rtl"===this.hd();c=a.Qd.km(c,k);var k="oj-popup-layer",l=g.tail;"none"!==l&&(k+=" "+["oj-popup-tail",l].join("-"));l={};l[a.U.qb.Bh]=f;l[a.U.qb.aB]=b;l[a.U.qb.eB]=c;l[a.U.qb.fu]=this.wy();l[a.U.qb.Gr]=k;l[a.U.qb.gk]=g.modality;a.U.Je().open(l);this._trigger("open");this.lU();this.Xwa();this._on(f,
{keydown:this.Sy,keyup:this.Sy});b&&0<b.length&&this._on(b,{keydown:this.Sy,keyup:this.Sy})}},close:function(){if(this.isOpen()&&(!1!==this._trigger("beforeClose")||this.dD)){this.ZAa();var b=this.Id,c=this.ig;this._off(c,"keydown keyup");b&&0<b.length&&this._off(b,"keydown keyup");this.o5();b={};b[a.U.qb.Bh]=c;a.U.Je().close(b);this.mAa();this.GV();delete this.Id;c=this.options.position;c._ofo&&(delete c._ofo,delete c.of);this._trigger("close")}},isOpen:function(){return this.ig.is(":visible")},
refresh:function(){this._super();this.isOpen()&&this.Laa();var b=this.ig;a.U.Je().DN(b,a.U.Fd.Mp)},_setOption:function(b,c){var f=this.options;switch(b){case "tail":c!==f.tail&&this.gCa(c);break;case "chrome":c!==f.chrome&&this.pba(c);break;case "position":this.Fba(c);this.refresh();return;case "autoDismiss":this.isOpen()&&c!==f.autoDismiss&&this.GV(c);break;case "modality":this.isOpen()&&(f={},f[a.U.qb.Bh]=this.ig,f[a.U.qb.gk]=c,a.U.Je().Hz(f))}this._superApply(arguments)},KKa:function(){return"oj-popup"},
gCa:function(a){this.n5();this.S4(a);this.Laa()},S4:function(b){b=b?b:this.options.tail;if("none"!==b){b=["oj-popup-tail",b].join("-");var c=g("\x3cdiv\x3e").hide();c.addClass("oj-popup-tail").addClass(b);c.attr("role","presentation");this.xca=c.attr("id",this.eJ("tail")).attr("id");var f=this.ig;c.appendTo(f);f.addClass(b);this.isOpen()&&(c={},c[a.U.qb.Bh]=f,c[a.U.qb.Gr]="oj-popup-layer "+b,a.U.Je().Hz(c))}},H7:function(){var a=this.xca;return a?g(document.getElementById(a)):null},n5:function(){var b=
this.H7();b&&b.remove();delete this.xca;b=this.ig;b.removeClass(["oj-popup-tail",this.options.tail].join("-"));if(this.isOpen()){var c={};c[a.U.qb.Bh]=b;c[a.U.qb.Gr]="oj-popup-layer";a.U.Je().Hz(c)}},pba:function(a){a=a?a:this.options.chrome;var b=this.ig;"default"===a&&b.hasClass("oj-popup-no-chrome")?b.removeClass("oj-popup-no-chrome"):"none"!==a||b.hasClass("oj-popup-no-chrome")||b.addClass("oj-popup-no-chrome")},UBa:function(b){b?"string"===g.type(b)?b=g(b):1===b.nodeType&&(b=g(b)):b=g(document.activeElement);
if(b instanceof jQuery&&1<b.length)for(var c=this.ig,f=0;f<b.length;f++){var h=b[0];if(!a.u.vt(c[0],h)){b=g(h);break}}else if(!(b instanceof jQuery)||b instanceof jQuery&&0===b.length)b=g(document.activeElement);this.Id=b},Fba:function(a){var b=this.options;a&&(b.position=g.extend(b[a],a));a=b.position;b=this.zE;g.isFunction(a.using)&&a.using!==b&&(a.origUsing=a.using);a.using=b;b=this.Id;a.of||(a.of=b,a._ofo=!0)},AE:function(d,e){var f=e.element.element;if(d.top!==f.css("top")||d.left!==f.css("left")){var h=
this.H7();if(h){h.hide();for(var k=0;k<c.length;k++)h.removeClass(c[k]),f.removeClass(c[k]);h.removeAttr("style");if(e.target&&0===e.target.height&&0===e.target.width&&(k="rtl"===this.hd(),k=a.Qd.km(this.options.position,k).my,!a.bb.Vl(k))){var k=k.split(" "),l="center"===k[0]?k[0]:e.horizontal,m="middle";1<k.length&&(m="center"===k[1]?"middle":k[1]);e.horizontal=l;e.vertical=m}k=b[[e.horizontal,e.vertical].join("-")];h.addClass(k);f.addClass(k);h.show();"left"===e.horizontal?(k=h.outerWidth(),k-=
k+a.u.Pq(h.css("left")),d.left+=k-2):"right"===e.horizontal&&(k=h.outerWidth(),k-=k+a.u.Pq(h.css("right")),d.left-=k-2);"top"===e.vertical?(k=h.outerHeight(),k-=k+a.u.Pq(h.css(e.vertical)),d.top+=k-2):"bottom"===e.vertical&&(k=h.outerHeight(),k-=k+a.u.Pq(h.css(e.vertical)),d.top-=k-2);f.css(d);"center"===e.horizontal&&"middle"!==e.vertical?(f=f.width(),f=Math.round((f/2-h.outerWidth()/2)/f*100),h.css({left:f+"%"})):"middle"===e.vertical&&(f=f.height(),f=Math.round((f/2-h.outerHeight()/2)/f*100),h.css({top:f+
"%"}))}else f.css(d);h=this.options;(f=h.position.origUsing)&&f(d,e);"focusLoss"===h.autoDismiss&&a.Qd.nY(e)&&(this.dU=!0,this.fs=this._delay(g.proxy(this.Uu,this),1))}},Laa:function(){var b=this.ig,c=this.options.position,f="rtl"===this.hd();b.position(a.Qd.km(c,f))},lU:function(b){var c=this.Sqa();b&&"none"===c&&(c="popup");if("firstFocusable"===c){b=this.element.find(":focusable");for(var f,g=0;g<b.length;g++)if(a.le.iA(b[g])){f=b[g];break}f?(f.focus(),this._trigger("focus")):c="popup"}"popup"===
c&&(c=this.ig,c.attr("tabindex","-1"),c.focus(),this._trigger("focus"))},Sqa:function(){var b=this.options,c=b.initialFocus;"auto"===c&&(c="modal"===b.modality?a.u.af()?"popup":"firstFocusable":"none");return c},EJ:function(b,c){b||(b=document.activeElement);if(!b)return!1;var f=this.ig;c&&(f=f.parent());return a.u.vt(f[0],b)},p9:function(b){b||(b=document.activeElement);return a.u.vt(this.Id[0],b)},ZAa:function(){this.dU?delete this.dU:this.EJ(null,!0)&&this.Id.focus()},Sy:function(a){if(!a.isDefaultPrevented()){var b=
a.type,c=a.target;if("keyup"===b&&a.keyCode===g.ui.keyCode.ESCAPE&&(this.EJ(c)||this.p9(c)))a.preventDefault(),this.close();else if("keydown"===b&&117===a.keyCode)this.EJ(c)?(c=this.options,"modeless"===c.modality?(a.preventDefault(),a=this.Id,a.focus()):this.close()):this.p9(c)&&(a.preventDefault(),this.lU(!0));else if("keydown"===b&&a.keyCode===g.ui.keyCode.TAB&&this.EJ(c)){var h=this.element.find(":tabbable");if(0<h.length){var b=h[0],h=h[h.length-1],k=this.ig;b!==c&&k[0]!==c||!a.shiftKey?h!==
c||a.shiftKey||(a.preventDefault(),h===b?(k.attr("tabindex","-1"),k.focus()):g(b).focus()):(a.preventDefault(),b===h&&b===c?(k.attr("tabindex","-1"),k.focus()):g(h).focus())}else a.preventDefault(),c=this.options,"modeless"===c.modality?(a=this.Id,a.focus()):this.close()}}},GV:function(b){var c=this.f6,f=this.wy();c&&(delete f[a.U.Fd.jx],delete this.f6);"focusLoss"===b&&(c=this.f6=g.proxy(this.Xqa,this),f[a.U.Fd.jx]=c);this.isOpen()&&(b={},b[a.U.qb.Bh]=this.ig,b[a.U.qb.fu]=f,a.U.Je().Hz(b))},Xqa:function(b){var c=
this.Id,f=this.ig.parent(),g=b.target,k=this.vI;if(k&&(k=k.getLink())&&a.u.vt(k[0],g))return;if(!a.u.vt(c[0],g)&&!a.u.vt(f[0],g)){if(a.le.iA(g)){if("mousedown"===b.type||"touchstart"===b.type)return;this.dU=!0}this.close()}},xna:function(){var a=this.Id,b=this.ig.attr("id"),c=a.attr("aria-describedby"),c=c?c.split(/\s+/):[];c.push(b);c=g.trim(c.join(" "));a.attr("aria-describedby",c)},mAa:function(){var a=this.Id,b=this.ig.attr("id"),c=a.attr("aria-describedby"),c=c?c.split(/\s+/):[],b=g.inArray(b,
c);-1!==b&&c.splice(b,1);(c=g.trim(c.join(" ")))?a.attr("aria-describedby",c):a.removeAttr("aria-describedby")},Xwa:function(){var b=a.Za.Rz().os===a.Za.zm.oO,c=this.EU;c||(c=this.EU=new a.xg);var f;f=b?this.F("none"===this.options.initialFocus?"ariaLiveRegionInitialFocusNoneTouch":"ariaLiveRegionInitialFocusFirstFocusableTouch"):this.F("none"===this.options.initialFocus?"ariaLiveRegionInitialFocusNone":"ariaLiveRegionInitialFocusFirstFocusable");c.YDa(f);if(b){if(!this.vI){var c=this.eJ("focusSkipLink"),
h=this.Id,b=g.proxy(this.lU,this,!0);f=this.F("ariaFocusSkipLink");this.vI=new a.kl(h,f,b,c)}this.hR||(c=this.eJ("closeSkipLink"),h=this.element,b=g.proxy(this.Uu,this),f=this.F("ariaCloseSkipLink"),this.hR=new a.kl(h,f,b,c))}},o5:function(){var a=this.EU;a&&(a.destroy(),delete this.EU);if(a=this.vI)a.destroy(),delete this.vI;if(a=this.hR)a.destroy(),delete this.hR},eJ:function(b){var c=this.element.attr("id");a.bb.Vl(c)&&(c=this.uuid);return[c,b].join("_")},Xv:function(){this.element.remove()},wy:function(){if(!this.hn){var b=
this.hn={};b[a.U.Fd.kx]=g.proxy(this.Uu,this);b[a.U.Fd.lx]=g.proxy(this.Xv,this);b[a.U.Fd.Mp]=g.proxy(this.refresh,this)}return this.hn},Uu:function(){this.dD=!0;this.close();delete this.dD}});a.Components.Dp({ojPopup:{modality:a.Components.Lf(function(){return(a.nd.uf("oj-popup-option-defaults")||{}).modality})}})})();a.Components.Ta("ojPopup","baseComponent",{properties:{autoDismiss:{type:"string"},chrome:{type:"string"},initialFocus:{type:"string"},modality:{type:"string"},widget:{},position:{type:"Object"},
role:{type:"string"},tail:{type:"string"}},methods:{close:{},isOpen:{},open:{},refresh:{}},extension:{_hasWrapper:!0,_innerElement:"div",_widgetName:"ojPopup"}});a.Components.register("oj-popup",a.Components.getMetadata("ojPopup"))});