/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue","ojs/ojradiocheckbox"],function(a,g){(function(){a.Na("oj.ojRadioset",g.oj.editableValue,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{disabled:!1,value:void 0},refresh:function(){this._super();this.$a()},widget:function(){return this.IJa},Xf:function(b,c){var e;this._super(b,c);a.Me.np([{ga:"disabled",Od:!0},{ga:"placeholder"},{ga:"required",oh:!0,Od:!0},{ga:"title"}],c,this);this.xi=this.dS();void 0===c.value&&(e=
this.xi.filter(":checked"),e=0===e.length?void 0:e.val(),void 0!==e&&this.option("value",e,{_context:{Ed:!0,ob:!0}}),void 0===this.options.value&&(this.options.value=null))},_ComponentCreate:function(){var a=this.element;this._super();if(a.is("fieldset"))throw Error("ojRadioset cannot be bound to a fieldset. Use a div instead.");this.xi._ojRadioCheckbox();this.IJa=a.addClass("oj-radioset oj-component").attr("role","radiogroup").wrapInner("\x3cdiv class\x3d'oj-radioset-wrapper'\x3e\x3c/div\x3e");this._on(this.hq)},
Hh:function(){this._super();this.$a()},JP:function(){this.xi=this.dS();this.xi.filter(".oj-radio").each(function(){var a=void 0!==g(this).attr("disabled")?!!g(this).prop("disabled"):!1;g(this)._ojRadioCheckbox("option","disabled",a)});this.xi.not(".oj-radio")._ojRadioCheckbox()},Focus:function(){this.Wf().first().focus();return!0},MP:function(){},dS:function(){var b=this.element,c=b.find("input[type\x3dradio]:first");0===c.length&&a.r.warn("Could not find any input type\x3dradio within this element");
c=c.attr("name");return void 0===c?(b=b.find("input[type\x3dradio]"),b.not("[name]")):b.find("input[type\x3dradio][name\x3d"+c+"]")},ih:function(a,c,e){a=this.element.find("input[type\x3dradio]");var f=a.filter(":checked");a=f.length?f:a.filter(":enabled").first();this.jh(c,e,{launcher:a})},_GetMessagingLauncherElement:function(){return this.widget()},$a:function(){this.Rs(this.options.disabled)},hq:{change:function(a){this.JG(a)}},JG:function(a){var d=this.Ag();this.ic(d,a,c)},Ag:function(){return this.Bx()},
ul:function(a){var c=this.xi.length,e,f,h;for(f=0;f<c;f++){h=g(this.xi[f]);e=h[0].value;var k=h._ojRadioCheckbox("option","checked");a===e?k||h._ojRadioCheckbox("option","checked",!0):k&&h._ojRadioCheckbox("option","checked",!1)}},Bx:function(){var a=this.xi.filter(":checked");return 0===a.length?null:a.val()},_GetDefaultStyleClass:function(){return"oj-radioset"},Wf:function(){if(null!=this.xi)return this.xi;this.dS()},GP:function(){},qB:function(){return!0},Rs:function(a){a=!!a;this.xi.each(function(){g(this).data("oj-_ojRadioCheckbox").QB(a)});
this.xi._ojRadioCheckbox("refreshDisabled")},_setOption:function(a,c){this._superApply(arguments);"disabled"===a&&this.Rs(c)},getNodeBySubId:function(a){var c=this._super(a);c||(a=a.subId,"oj-radioset-inputs"===a&&(c=this.xi.get()));return c||null},_destroy:function(){var a=this._super(),c=this.element[0].firstChild;this.xi&&this.xi._ojRadioCheckbox("destroy");g(c).contents().unwrap();return a}});var c={hw:!1}})();a.Components.Ta("ojRadioset","editableValue",{properties:{disabled:{type:"boolean"},
value:{type:"string",writeback:!0}},methods:{destroy:{},refresh:{},widget:{}},extension:{_widgetName:"ojRadioset"}});a.Components.register("oj-radioset",a.Components.getMetadata("ojRadioset"))});