/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a,g){a.Na("oj._ojRadioCheckbox",g.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:null,checked:null,type:null},label:function(){void 0===this.mc&&(this.mc=this.JS());return this.mc},refresh:function(){this._super();this.$a()},refreshDisabled:function(){this.wV()},setSelectedClass:function(a){this.element.toggleClass("oj-selected",a);this.mc.toggleClass("oj-selected",a);this.wi&&
this.wi.toggleClass("oj-selected",a)},widget:function(){return this.Oia},Xf:function(a,b){var d;this._super(a,b);"checked"in b||(this.kY=!0,d=!!this.element.prop("checked"),this.option("checked",d,{_context:{ob:!0}}));if("boolean"!==typeof this.options.checked)throw Error("checked option must be a boolean");"disabled"in b||(d=!!this.element.prop("disabled"),this.option("disabled",d,{_context:{ob:!0}}));if("boolean"!==typeof this.options.disabled)throw Error("disabled option must be a boolean");"type"in
b||this.option("type",this.element.prop("type"),{_context:{ob:!0}})},_ComponentCreate:function(){this._super();var a=this.options.type;"checkbox"==a?(this.Oia=this.element.addClass("oj-checkbox oj-component"),this.mc=this.JS(),this.mc.addClass("oj-checkbox-label")):"radio"==a&&(this.Oia=this.element.addClass("oj-radio oj-component"),this.mc=this.JS(),this.mc.addClass("oj-radio-label"));this.wi=this.ysa();this._focusable(this.element);this.wi&&(this.Qe({element:this.wi}),this.ok({element:this.wi}),
this._focusable({element:this.wi,applyHighlight:!0}));this.Qe({element:this.mc});this.ok({element:this.mc});g.each(this.mc,function(){g(this.childNodes).wrapAll("\x3cspan class\x3d'oj-radiocheckbox-label-text'\x3e\x3c/span\x3e");var a=document.createElement("span");a.setAttribute("class","oj-radiocheckbox-icon");this.appendChild(a)});this.$a()},IB:function(a){this.cE=a.attr("class")},Lx:function(){this.cE?this.element.attr("class",this.cE):this.element.removeAttr("class")},$a:function(){this.wV();
this.kY||this.dE(this.options.checked);this.options.checked&&this.setSelectedClass(this.options.checked)},dE:function(a){this.element.prop("checked",!!a)},wV:function(){this.Yf()?(this.element.prop("disabled",!0).removeAttr("aria-disabled").removeClass("oj-enabled").addClass("oj-disabled"),this.mc.removeClass("oj-enabled").addClass("oj-disabled"),this.wi&&this.wi.removeClass("oj-enabled").addClass("oj-disabled")):(this.element.prop("disabled",!1).removeAttr("aria-disabled").removeClass("oj-disabled").addClass("oj-enabled"),
this.mc.addClass("oj-enabled").removeClass("oj-disabled"),this.wi&&this.wi.addClass("oj-enabled").removeClass("oj-disabled"))},_setOption:function(a,b){this._superApply(arguments);"disabled"===a&&(b=!!b,this.wV(b));"checked"===a&&(this.dE(b),this.setSelectedClass(b))},JS:function(){var c=this.element.closest("label"),b="label[for\x3d'"+this.element.prop("id")+"']",d=g(b),c=c.add(d);0===d.length&&(b=this.element.siblings(b),c.add(b));0===c.length&&a.r.warn("Could not find a label associated to the input element.");
return c},ysa:function(){var c;if(this.mc&&(c=this.mc.parent())&&(c.hasClass("oj-choice-row")||c.hasClass("oj-choice-row-inline")))return c;a.r.warn("The radioset/checkboxset's input and label dom should be wrapped in a dom node with class 'oj-choice-row' or 'oj-choice-row-inline'");return null},getNodeBySubId:function(a){var b=this._super(a);b||(a=a.subId,"oj-radiocheckbox-input"===a&&(b=this.element[0]),"oj-radiocheckbox-label"===a&&(b=this.label()[0]));return b||null},_destroy:function(){var a=
this._super();this.wi&&(this.IP(this.wi),this.HP(this.wi));this.IP(this.mc);this.HP(this.mc);var b=this.options.type;"checkbox"==b?this.mc.removeClass("oj-enabled oj-disabled oj-selected oj-checkbox-label"):"radio"==b&&this.mc.removeClass("oj-enabled oj-disabled oj-selected oj-radio-label");this.wi&&this.wi.removeClass("oj-enabled oj-disabled oj-selected");g.each(this.mc,function(){this.removeChild(this.getElementsByClassName("oj-radiocheckbox-icon")[0]);var a=this.getElementsByClassName("oj-radiocheckbox-label-text");
void 0!==a&&g(a[0].childNodes[0]).unwrap()});return a}})});