/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","knockout","signals","promise"],function(a,g,c){(function(){function b(){var a=window.location.href.split("#")[0];return a.substring(0,a.lastIndexOf("/"))}function d(a){var b={};a&&(a=a.split("\x26"),a.forEach(function(a){var c=a.split(/\=(.+)?/);a=c[0];a.length&&(b[a]||(b[a]=[]),c=c[1]&&decodeURIComponent(c[1].replace(/\+/g," ")),b[a].push(c))}));return b}function e(b,c){var d;c&&b.Xs&&(a.o.Gq(c),b.Xs.every(function(a){return a.Fl===c?(d=a,!1):!0}));return d}function f(){return window.location.href.split("#")[0].replace(J,
"")}function h(a){return a.uq?h(a.uq)+"."+a.fg:a.fg}function k(a){var b;if(a){if(b=k(a.uq))b=(a=a.lh())?b+(a+"/"):void 0}else b="/";return b}function l(a,b){var c;a.Ki.every(function(a){return a.vq&&a.vq!==b?!0:(c=a,!1)});return c}function m(){return M[0]&&M[0].cancel}function s(b){var c=b.charAt(0);b=b.slice(1);if("0"===c)b=decodeURIComponent(b);else if("1"===c)b=a.E_.gFa(b);else throw Error("Error retrieving bookmarkable data. Format is invalid");return JSON.parse(b)}function t(b,c){if(c&&0<Object.getOwnPropertyNames(c).length){var d;
d=-1===b.indexOf("?")?"?":"\x26";var e=b,f=JSON.stringify(c),g=encodeURIComponent(f),f=a.E_.HEa(f),h=!1,k="oj_Router\x3d";f.length<=g.length&&(h=!0);k=h?k+("1"+f):k+("0"+g);if(1024<k.length)throw Error("Size of bookmarkable data is too big.");b=e+(d+k)}return b}function r(a,b,c){var d;a.Ki.every(function(a){return a.vq&&a.vq!==c||!a.On(b)?!0:(d=a,!1)});return d}function n(a){if(!a)return{title:"",HA:""};var b=n(l(a,a.lh()));if(""===b.title&&(a=a.ZH())){var c=a.vz;void 0!==c?("function"===typeof c&&
(c=c()),b.title=String(c)):(c=a.AU,void 0!==c&&(c=String(c),""!==b.HA&&(c+=" | "+b.HA),b.HA=c))}return b}function p(a,b){var c=[],d=[],e=a,f=b.split("/"),g,h,k;for(f.splice(0,1);e;)d.unshift(e),e=e.uq;for(;g=f.shift();){e=d.shift();if(!e){if(e=r(h,g,k),!e){P=b;break}}else if(!e.On(g))throw Error('Invalid path "'+b+'". State id "'+g+'" does not exist on router "'+e.fg+'".');c.push({ae:e,KA:g});h=e;k=g}e=!0;for(d=c.length-1;0<=d&&e;d--)c[d].KA===c[d].ae.so?c[d].KA=null:e=!1;return c}function q(b,c,
d){(b=b())||a.r.info("%s is false for state: %s",c,d);return b}function u(a,b,c,d){"function"===typeof a&&(b=b?b.then(function(b){b&&(b=q(a,c,d));return b}):new Promise(function(b){b(q(a,c,d))}));return b}function v(a,b){var c=a.ZH(),d;if(c){for(d=0;d<a.Ki.length;d++)b=v(a.Ki[d],b);d=c.HN&&c.HN.canExit?c.HN.canExit:c.eC;b=u(d,b,"canExit",c.Fl)}return b}function w(b){if(m())return Promise.resolve(!1);a.r.info("Start _canExit.");b?(b=v(b,null),b=null===b?Promise.resolve(!0):b.then(function(a){return a&&
!m()})):b=Promise.resolve(!0);return b}function y(b,c){if(m())return Promise.resolve();a.r.info("Start _canEnter.");var d=null;b.forEach(function(a){(a=a.ae.On(a.value))&&(d=u(a.dC,d,"canEnter",a.Fl))});return d=null===d?Promise.resolve({VW:b,origin:c}):d.then(function(a){var d;a&&!m()&&(d={VW:b,origin:c});return d})}function x(b,c){var d=b.ae.On(b.ae.lh()),e=b.value?b.ae.On(b.value):void 0;return Promise.resolve().then(function(){a.r.info("Updating state of %s to %s.",h(b.ae),b.value)}).then(d?d.xC:
void 0).then(function(){var a=b.ae,d,e,f;if("popState"===c){e=a.Zy.length;for(d=e-1;0<=d;d--)if(a.Zy[d]===b.value){f=!0;a.Zy.splice(d,e-d);break}1===e-d&&(a.zD="back")}f||(delete a.zD,a.Zy.push(a.lh()));a.lh(b.value)}).then(e?e.wC:void 0)}function z(b){if(!b)return{hasChanged:!1};var c=Promise.resolve().then(function(){a.r.info("Entering _updateAll.");a.Ib.iL=!0});b.VW.forEach(function(a){c=c.then(function(){if(!m())return x(a,b.origin)})});return c.then(function(){var c=0<b.VW.length&&!m();a.Ib.iL=
!1;a.r.info("_updateAll returns %s.",String(c));return{hasChanged:c}},function(b){a.Ib.iL=!1;return Promise.reject(b)})}function D(b){var c={},d,e=b.split("?")[1]||"";a.r.info("Parsing: %s",b);b=H.KE(b);if(e=e.split("oj_Router\x3d")[1])e=e.split("\x26")[0],c=s(e);if(a.r.option("level")===a.r.ou)for(d in a.r.info("Bookmarkable data: "),c)a.r.info("   { router: %s, value: %s }",d,c[d]);b=H.parse(b).filter(function(a){var b=c[a.ae.fg];void 0!==b&&(a.ae.Al=b);return a.value!==a.ae.lh()});a.r.option("level")===
a.r.ou&&(a.r.info("Potential changes are: "),b.forEach(function(b){a.r.info("   { router: %s, value: %s }",h(b.ae),b.value)}));return b}function I(a,b){var c;try{c=D(a)}catch(d){return Promise.reject(d)}return y(c,b).then(z)}function B(b){a.r.info("\x3e\x3e Executing: path\x3d%s, url\x3d%s, origin\x3d%s",b.path,b.url,b.origin);return void 0!==b.url?"sync"===b.origin?I(b.url):w(b.ae).then(function(a){return a?I(b.url,b.origin):{hasChanged:!1}}):b.ae.gua(b.path||null,b.replace)}function G(){var b=M[0];
a.r.info("\x3e\x3e Resolving: path\x3d%s, url\x3d%s",b.path,b.url);b.cancel?(a.r.info("\x3e\x3e Cancelled: path\x3d%s, url\x3d%s",b.path,b.url),b=Promise.resolve({hasChanged:!1})):b=B(b);return b.then(function(b){var c=M.shift();a.r.info("\x3e\x3e Done with: path\x3d%s, url\x3d%s",c.path,c.url);if(!0===b.hasChanged){var c=n(N),d;""!==c.title?d=c.title:F&&0<F.length?(d=F,""!==c.HA&&(d+=" | "+c.HA)):d=c.HA;d!==window.document.title&&(window.document.title=d)}a.Ib.yz.dispatch(b);return b},function(b){M=
[];a.r.error("Error when executing transition: %s",b.message);a.Ib.yz.dispatch({hasChanged:!1});return Promise.reject(b)})}function C(b){var c;c=M.push(b);a.r.info("\x3e\x3e Queue transition for path\x3d%s, url\x3d%s",b.path,b.url);1===c?Q=G():(b=M[c-2],b.url||b.iFa||(a.r.info("\x3e\x3e Cancelling: path\x3d%s",b.path),b.cancel=!0),Q=Q.then(G));return Q}function K(){var b,c,d=N.lh(),e=null;a.r.info("Handling popState event with URL: %s",window.location.href);if(d)for(b=0;b<N.Ki.length;b++)if(c=N.Ki[b],
d===c.vq){e=c;break}C({ae:e,url:f(),origin:"popState"}).then(null,function(b){a.r.error("Error while changing state in handlePopState: %s",b.message)})}function A(){L||(H||(H=new a.Ib.QZ),J||(J=b()),F=window.document.title,window.addEventListener("popstate",K,!1),a.r.info("Initializing rootInstance."),a.r.info("Base URL is %s",J),a.r.info("This page is %s",E),a.r.info("Current URL is %s",window.location.href),L=!0)}var J,F,E=function(){var a="",b=window.location.pathname;-1!==b.indexOf(".html",b.length-
5)&&(a=b.split("/").pop());return a}(),H,L=!1,P,M=[],Q,N;a.Ib=function(a,b,c){var d=this;this.fg=a;this.vq=c||(b?b.lh():void 0);this.uq=b;this.Ki=[];this.Al=void 0;this.lh=g.observable();this.GCa=g.pureComputed({read:function(){return this.lh()},write:function(a){this.go(a).then(null,function(a){throw a;})},owner:d});this.Xs=null;this.so=void 0;this.ZH=g.pureComputed(function(){return g.ignoreDependencies(d.On,d,[d.lh()])});this.Nqa=g.pureComputed(function(){var a,b=g.ignoreDependencies(d.On,d,[d.lh()]);
b&&(a=b.value);return a});this.zD=void 0;this.Zy=[];this.uya=Object.create(null,{name:{value:g.pureComputed(function(){var a,b;b=this.lh()||this.so||this.Xs[0];if(b=this.On(b))a=b.value,a&&"string"===typeof a||(a=b.Fl);return a},d),enumerable:!0},params:{value:Object.create(null,{ojRouter:{value:new function(){Object.defineProperties(this,{parentRouter:{value:d,enumerable:!0},direction:{get:function(){return d.zD},enumerable:!0}})},enumerable:!0}}),enumerable:!0},lifecycleListener:{value:Object.create(null,
{attached:{value:function(a){var b=g.unwrap(a.valueAccessor()).params.ojRouter.parentRouter.ZH();b&&(b.HN=a.viewModel)},writable:!0,enumerable:!0}}),enumerable:!0}});Object.defineProperties(this,{parent:{value:this.uq,enumerable:!0}})};o_("Router",a.Ib,a);Object.defineProperties(a.Ib.prototype,{name:{get:function(){return this.fg},enumerable:!0},states:{get:function(){return this.Xs},enumerable:!0},stateId:{get:function(){return this.GCa},enumerable:!0},currentState:{get:function(){return this.ZH},
enumerable:!0},currentValue:{get:function(){return this.Nqa},enumerable:!0},defaultStateId:{get:function(){return this.so},set:function(a){this.so=a},enumerable:!0},moduleConfig:{get:function(){return this.uya},enumerable:!0}});N=new a.Ib("root",void 0,void 0);a.Ib.prototype.yea=function(a){var b;a&&"string"===typeof a&&(a=a.trim(),0<a.length&&this.Ki.every(function(c){return c.fg===a?(b=c,!1):!0}));return b};a.b.g("Router.prototype.getChildRouter",{yea:a.Ib.prototype.yea});a.Ib.prototype.Pda=function(b,
c){var d,e;a.o.Gq(b);c=c||this.lh();b=encodeURIComponent(b.trim());for(d=0;d<this.Ki.length;d++){e=this.Ki[d];if(e.fg===b)throw Error('Invalid router name "'+b+'", it already exists.');if(e.vq===c)throw Error('Cannot create more than one child router for parent state id "'+e.vq+'".');}d=new a.Ib(b,this,c);this.Ki.push(d);return d};a.b.g("Router.prototype.createChildRouter",{Pda:a.Ib.prototype.Pda});a.Ib.prototype.On=function(a){return e(this,a)};a.Ib.prototype.Jda=function(b){this.lh(void 0);delete this.so;
this.zD=void 0;this.Zy=[];"function"===typeof b?(this.Xs=null,this.On=b):(this.Xs=[],delete this.On,Object.keys(b).forEach(function(c){var d=b[c];this.Xs.push(new a.nx(c,d,this));"boolean"===typeof d.isDefault&&d.isDefault&&(this.so=c)},this));return this};a.b.g("Router.prototype.configure",{Jda:a.Ib.prototype.Jda});a.Ib.prototype.ofa=function(a){return this.On(a)};a.b.g("Router.prototype.getState",{ofa:a.Ib.prototype.ofa});a.Ib.prototype.go=function(a){A();return C({ae:this,path:a,origin:"go"})};
a.b.g("Router.prototype.go",{go:a.Ib.prototype.go});a.Ib.prototype.gua=function(b,c){function d(b){return b?I(g).then(function(b){if(b.hasChanged){var d=J+g;a.r.info("%s URL to %s",c?"Replacing":"Pushing",d);window.history[c?"replaceState":"pushState"](null,"",d)}return b}):{hasChanged:!1}}var e,g,q;e=!0;if(b)if("string"===typeof b)0<b.length&&(e=!1);else return Promise.reject(Error("Invalid object type for state id."));if(e&&(b=this.so||null,!b))return a.r.option("level")===a.r.ou&&a.r.info("Undefined state id with no default id on router %s",
h(this)),Promise.resolve({hasChanged:!1});if("/"===b.charAt(0))e=b;else{e=k(this.uq);if(!e)return Promise.reject(Error('Invalid path "'+b+'". The parent router does not have a current state.'));e+=b}a.r.info("Destination path: %s",e);try{q=p(this,e)}catch(l){return Promise.reject(l)}g=H.xda(q);a.r.option("level")===a.r.ou&&a.r.info("Going to URL %s on router %s",g,h(this));q=H.KE(f());return c||H.KE(g)!==q?(a.r.info("Deferred mode or new URL is different."),w(this).then(d)):Promise.resolve({hasChanged:!1})};
a.Ib.prototype.sia=function(a){this.Al=a;a={};for(var b=this;b;)void 0!==b.Al&&(a[b.fg]=b.Al),b=b.uq;for(var b=this,c,d,e;b;){for(d=0;d<b.Ki.length;d++)if(e=b.Ki[d],b.lh()&&b.lh()===e.vq){void 0!==e.Al&&(a[e.fg]=e.Al);c=e;break}b=c;c=void 0}c=J+H.KE(f());c=t(c,a);window.history.replaceState(null,"",c)};a.b.g("Router.prototype.store",{sia:a.Ib.prototype.sia});a.Ib.prototype.Uha=function(){return this.Al};a.b.g("Router.prototype.retrieve",{Uha:a.Ib.prototype.Uha});a.Ib.prototype.Nz=function(){for(var b,
c;0<this.Ki.length;)this.Ki[0].Nz();if(this.uq){b=this.uq.Ki;for(c=0;c<b.length;c++)if(b[c].fg===this.fg){b.splice(c,1);break}delete this.vq}else J="",H={},this.fg="root",window.document.title=F,window.removeEventListener("popstate",K),a.Ib.yz.removeAll(),L=!1;delete this.zD;this.Zy=[];this.Xs=null;delete this.so;delete this.Al};a.b.g("Router.prototype.dispose",{Nz:a.Ib.prototype.Nz});a.Ib.yz=new c.Signal;a.Ib.iL=!1;Object.defineProperties(a.Ib,{rootInstance:{value:N,enumerable:!0},transitionedToState:{value:a.Ib.yz,
enumerable:!0}});a.Ib.Zc={};o_("Router.defaults",a.Ib.Zc,a);Object.defineProperties(a.Ib.Zc,{urlAdapter:{get:function(){H||(H=new a.Ib.QZ);return H},set:function(a){if(L)throw Error("Incorrect operation. Cannot change URL adapter after calling sync() or go().");H=a},enumerable:!0,pN:!1},baseUrl:{get:function(){J||(J=b());return J},set:function(a){if(L)throw Error("Incorrect operation. Cannot change base URL after calling sync() or go().");J=a.replace(/\/$/,"")},enumerable:!0,pN:!1},rootInstanceName:{get:function(){return N.fg},
set:function(b){if(L)throw Error("Incorrect operation. Cannot change the name of the root instance after calling sync() or go().");a.o.Gq(b);N.fg=encodeURIComponent(b.trim())},enumerable:!0,pN:!1}});a.Ib.IZ=function(){var b;A();a.r.info("Entering sync.");if(P)return b={ae:N,path:P,iFa:!0,replace:!0},P=void 0,C(b);if(a.Ib.iL)return a.r.info("Sync called while updating, waiting for updates to end."),new Promise(function(b){a.Ib.yz.addOnce(function(c){a.r.info("Sync updates done.");b(c)})});b={ae:N,
url:f(),origin:"sync"};return C(b)};o_("Router.sync",a.Ib.IZ,a);a.Ib.QZ=function(){this.parse=function(a){var b=N;a=a.split("/");var c=[],d;a.shift();do(d=a.shift())&&(0===d.length||/\.html$/i.test(d))&&(d=void 0),d=d||b.so,c.push({value:d,ae:b}),b=l(b,d);while(b);return c};this.xda=function(b){var c="",d={};b.forEach(function(a){a.KA&&(c+="/"+a.KA);void 0!==a.ae.Al&&(d[a.ae.fg]=a.ae.Al)});""===c&&(c="/"+E);try{c=t(c,d)}catch(e){a.r.error("Error while building URL: %s",e)}return c};this.KE=function(a){return a.split("?")[0]};
this.afa=function(a){var b=a.indexOf("?"),c=null;-1!==b&&(c=a.substr(b+1));return d(c)}};o_("Router.urlPathAdapter",a.Ib.QZ,a);a.Ib.NJa=function(){this.parse=function(a){a=this.afa(a);var b=N,c=[],d;do{if(d=a[b.fg])d=d[0],delete a[b.fg];d=d||b.so;c.push({value:d,ae:b});b=l(b,d)}while(b);return c};this.xda=function(b){var c="/"+E,d={},e="?";b.forEach(function(a){a.KA&&(c+=e+a.ae.fg+"\x3d"+a.KA,e="\x26");void 0!==a.ae.Al&&(d[a.ae.fg]=a.ae.Al)});try{c=t(c,d)}catch(f){a.r.error("Error while building URL: %s",
f)}return c};this.KE=function(a){var b=a.indexOf("oj_Router\x3d");return-1!==b?a.substr(0,b-1):a};this.afa=function(a){var b=a.indexOf("?"),c=null,c={};-1!==b&&(c=a.substr(b+1),c=d(c));return c}};o_("Router.urlParamAdapter",a.Ib.NJa,a);return N})();(function(){a.nx=function(b,c,e){c=c||{};a.o.Gq(b);this.Fl=encodeURIComponent(b.trim());(this.dC=c.canEnter)&&a.o.Fz(this.dC);(this.wC=c.enter)&&a.o.Fz(this.wC);(this.eC=c.canExit)&&a.o.Fz(this.eC);(this.xC=c.exit)&&a.o.Fz(this.xC);this.bda=c.value;this.AU=
c.label;this.vz=c.title;this.vK=e;this.HN=void 0;Object.defineProperties(this,{id:{value:this.Fl,enumerable:!0},value:{get:function(){return this.bda},set:function(a){this.bda=a},enumerable:!0},label:{get:function(){return this.AU},set:function(a){this.AU=a},enumerable:!0},title:{get:function(){return this.vz},set:function(a){this.vz=a},enumerable:!0},canEnter:{get:function(){return this.dC},set:function(a){this.dC=a},enumerable:!0},enter:{get:function(){return this.wC},set:function(a){this.wC=a},
enumerable:!0},canExit:{get:function(){return this.eC},set:function(a){this.eC=a},enumerable:!0},exit:{get:function(){return this.xC},set:function(a){this.xC=a},enumerable:!0}})};o_("RouterState",a.nx,a);a.nx.prototype.go=function(){return this.vK?this.vK.go(this.Fl):(a.Ib.yz.dispatch({hasChanged:!1}),Promise.reject(Error("Router is not defined for this RouterState object.")))};a.b.g("RouterState.prototype.go",{go:a.nx.prototype.go});a.nx.prototype.hga=function(){if(!this.vK)throw Error("Router is not defined for this RouterState object.");
return this.vK.lh()===this.Fl};a.b.g("RouterState.prototype.isCurrent",{hga:a.nx.prototype.hga})})();(function(){function b(a,b){if(null===a)return"";var c,d,e={},f={},g="",h=2,q=3,u=2,v="",w=0,y=0,x,z,D,I=a.length;for(D=0;D<I;D++)if(x=a[D],Object.prototype.hasOwnProperty.call(e,x)||(e[x]=q++,f[x]=!0),z=g+x,Object.prototype.hasOwnProperty.call(e,z))g=z;else{if(Object.prototype.hasOwnProperty.call(f,g)){if(256>g.charCodeAt(0)){for(c=u;c--;)w<<=1,5==y?(y=0,v+=b(w),w=0):y++;d=g.charCodeAt(0);c=8}else{d=
1;for(c=u;c--;)w=w<<1|d,5==y?(y=0,v+=b(w),w=0):y++,d=0;d=g.charCodeAt(0);c=16}for(;c--;)w=w<<1|d&1,5==y?(y=0,v+=b(w),w=0):y++,d>>=1;h--;0==h&&(h=Math.pow(2,u),u++);delete f[g]}else for(d=e[g],c=u;c--;)w=w<<1|d&1,5==y?(y=0,v+=b(w),w=0):y++,d>>=1;h--;0==h&&(h=Math.pow(2,u),u++);e[z]=q++;g=String(x)}if(""!==g){if(Object.prototype.hasOwnProperty.call(f,g)){if(256>g.charCodeAt(0)){for(c=u;c--;)w<<=1,5==y?(y=0,v+=b(w),w=0):y++;d=g.charCodeAt(0);c=8}else{d=1;for(c=u;c--;)w=w<<1|d,5==y?(y=0,v+=b(w),w=0):
y++,d=0;d=g.charCodeAt(0);c=16}for(;c--;)w=w<<1|d&1,5==y?(y=0,v+=b(w),w=0):y++,d>>=1;h--;0==h&&(h=Math.pow(2,u),u++);delete f[g]}else for(d=e[g],c=u;c--;)w=w<<1|d&1,5==y?(y=0,v+=b(w),w=0):y++,d>>=1;h--;0==h&&u++}d=2;for(c=u;c--;)w=w<<1|d&1,5==y?(y=0,v+=b(w),w=0):y++,d>>=1;for(;;)if(w<<=1,5==y){v+=b(w);break}else y++;return v}function c(a,b){for(var d=[],f=4,g=4,h=3,n="",p="",q,u,v,w,y,x={val:b(0),position:32,index:1},p=0;3>p;p+=1)d[p]=p;n=0;v=Math.pow(2,2);for(w=1;w!=v;)u=x.val&x.position,x.position>>=
1,0==x.position&&(x.position=32,x.val=b(x.index++)),n|=(0<u?1:0)*w,w<<=1;switch(n){case 0:n=0;v=Math.pow(2,8);for(w=1;w!=v;)u=x.val&x.position,x.position>>=1,0==x.position&&(x.position=32,x.val=b(x.index++)),n|=(0<u?1:0)*w,w<<=1;y=e(n);break;case 1:n=0;v=Math.pow(2,16);for(w=1;w!=v;)u=x.val&x.position,x.position>>=1,0==x.position&&(x.position=32,x.val=b(x.index++)),n|=(0<u?1:0)*w,w<<=1;y=e(n);break;case 2:return""}for(q=p=d[3]=y;;){if(x.index>a)return"";n=0;v=Math.pow(2,h);for(w=1;w!=v;)u=x.val&x.position,
x.position>>=1,0==x.position&&(x.position=32,x.val=b(x.index++)),n|=(0<u?1:0)*w,w<<=1;switch(y=n){case 0:n=0;v=Math.pow(2,8);for(w=1;w!=v;)u=x.val&x.position,x.position>>=1,0==x.position&&(x.position=32,x.val=b(x.index++)),n|=(0<u?1:0)*w,w<<=1;d[g++]=e(n);y=g-1;f--;break;case 1:n=0;v=Math.pow(2,16);for(w=1;w!=v;)u=x.val&x.position,x.position>>=1,0==x.position&&(x.position=32,x.val=b(x.index++)),n|=(0<u?1:0)*w,w<<=1;d[g++]=e(n);y=g-1;f--;break;case 2:return p}0==f&&(f=Math.pow(2,h),h++);if(d[y])n=
d[y];else if(y===g)n=q+q[0];else return null;p+=n;d[g++]=q+n[0];f--;q=n;0==f&&(f=Math.pow(2,h),h++)}}a.E_={HEa:function(a){return null===a?"":b(a,function(a){return f.charAt(a)})},gFa:function(a){return null===a?"":""===a?null:c(a.length,function(b){var c=f;b=a.charAt(b);var d;g||(g={});if(!g[c])for(g[c]={},d=0;d<c.length;d++)g[c][c[d]]=d;return g[c][b]})}};var e=String.fromCharCode,f="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-$",g})()});