/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdatasource-common"],function(a,g){a.Wg=function(a,b){this.$Ha=a;this.cd=b};o_("EmptyNodeSet",a.Wg,a);a.Wg.prototype.getParent=function(){return this.$Ha};a.b.g("EmptyNodeSet.prototype.getParent",{getParent:a.Wg.prototype.getParent});a.Wg.prototype.getStart=function(){return this.cd};a.b.g("EmptyNodeSet.prototype.getStart",{getStart:a.Wg.prototype.getStart});a.Wg.prototype.getCount=function(){return 0};a.b.g("EmptyNodeSet.prototype.getCount",
{getCount:a.Wg.prototype.getCount});a.Wg.prototype.getData=function(){return null};a.b.g("EmptyNodeSet.prototype.getData",{getData:a.Wg.prototype.getData});a.Wg.prototype.getMetadata=function(){return null};a.b.g("EmptyNodeSet.prototype.getMetadata",{getMetadata:a.Wg.prototype.getMetadata});a.Xg=function(a,b){this.pc=a;this.cd=b};o_("FlattenedNodeSet",a.Xg,a);a.Xg.prototype.getParent=function(){return this.pc.getParent()};a.b.g("FlattenedNodeSet.prototype.getParent",{getParent:a.Xg.prototype.getParent});
a.Xg.prototype.getStart=function(){return void 0!=this.cd?this.cd:this.pc.getStart()};a.b.g("FlattenedNodeSet.prototype.getStart",{getStart:a.Xg.prototype.getStart});a.Xg.prototype.getCount=function(){void 0===this.GM&&(this.GM=this.y6(this.pc,0),void 0!=this.cd&&(this.GM-=this.cd));return this.GM};a.b.g("FlattenedNodeSet.prototype.getCount",{getCount:a.Xg.prototype.getCount});a.Xg.prototype.y6=function(a,b){var d,e,f,g;d=a.getStart();e=a.getCount();b+=e;if(a.ki)for(f=0;f<e;f++)g=a.ki(f+d),null!=
g&&(b=this.y6(g,b));return b};a.Xg.prototype.getData=function(a){return this.uS(this.pc,a,{index:this.pc.getStart()},this.Lb)};a.b.g("FlattenedNodeSet.prototype.getData",{getData:a.Xg.prototype.getData});a.Xg.prototype.getMetadata=function(a){return this.uS(this.pc,a,{index:this.pc.getStart()},this.OS)};a.b.g("FlattenedNodeSet.prototype.getMetadata",{getMetadata:a.Xg.prototype.getMetadata});a.Xg.prototype.OS=function(a,b){return a.getMetadata(b)};a.Xg.prototype.Lb=function(a,b){return a.getData(b)};
a.Xg.prototype.uS=function(a,b,d,e){var f,g,k,l;f=a.getStart();g=a.getCount();for(k=0;k<g;k++){l=d.index;if(l===b)return e.call(this,a,k+f);d.index=l+1;if(a.ki&&(l=a.ki(k+f),null!=l&&(l=this.uS(l,b,d,e),null!=l)))return l}return null};a.nj=function(a,b,d){this.Et=a;this.UY=b;this.TY=this.asa(d)};o_("MergedNodeSet",a.nj,a);a.nj.prototype.asa=function(a){var b,d,e;b=this.Et.getStart();for(d=b+this.Et.getCount();b<d;b++)if(e=this.Et.getMetadata(b).key,a===e)return b;return d-1};a.nj.prototype.getParent=
function(){return this.Et.getParent()};a.b.g("MergedNodeSet.prototype.getParent",{getParent:a.nj.prototype.getParent});a.nj.prototype.getStart=function(){return this.Et.getStart()};a.b.g("MergedNodeSet.prototype.getStart",{getStart:a.nj.prototype.getStart});a.nj.prototype.getCount=function(){return this.Et.getCount()+this.UY.getCount()};a.b.g("MergedNodeSet.prototype.getCount",{getCount:a.nj.prototype.getCount});a.nj.prototype.getData=function(a){a=this.s7(a);return a.set.getData(a.index)};a.b.g("MergedNodeSet.prototype.getData",
{getData:a.nj.prototype.getData});a.nj.prototype.getMetadata=function(a){a=this.s7(a);return a.set.getMetadata(a.index)};a.b.g("MergedNodeSet.prototype.getMetadata",{getMetadata:a.nj.prototype.getMetadata});a.nj.prototype.s7=function(a){if(a<=this.TY)return{set:this.Et,index:a};var b=this.UY.getCount();return a>this.TY+b?{set:this.Et,index:a-b}:{set:this.UY,index:a-(this.TY+1)}};a.bh=function(a,b,d,e){this.pc=a;this.Yl=b;this.sA=d;this.Zl=e};o_("NodeSetWrapper",a.bh,a);a.bh.prototype.getParent=function(){return this.pc.getParent()};
a.b.g("NodeSetWrapper.prototype.getParent",{getParent:a.bh.prototype.getParent});a.bh.prototype.getStart=function(){return null!=this.sA?this.sA.start:this.pc.getStart()};a.b.g("NodeSetWrapper.prototype.getStart",{getStart:a.bh.prototype.getStart});a.bh.prototype.getCount=function(){var a,b;a=this.pc.getStart();b=this.pc.getCount();null!=this.sA&&(this.sA.start>a?b=Math.min(0,b-(this.sA.start-a)):this.sA.start<a&&(b=0));return b};a.b.g("NodeSetWrapper.prototype.getCount",{getCount:a.bh.prototype.getCount});
a.bh.prototype.getData=function(a){return this.pc.getData(a)};a.b.g("NodeSetWrapper.prototype.getData",{getData:a.bh.prototype.getData});a.bh.prototype.getMetadata=function(a){var b;b=this.pc.getMetadata(a);b.index=a;b.parentKey=this.getParent();this.Yl.call(null,b.key,b);return b};a.b.g("NodeSetWrapper.prototype.getMetadata",{getMetadata:a.bh.prototype.getMetadata});a.bh.prototype.ki=function(c){return null!=this.Zl&&-1!=this.Zl.indexOf(this.pc.getMetadata(c).key)||!this.pc.ki||(c=this.pc.ki(c),
null==c)?null:new a.bh(c,this.Yl,null,this.Zl)};a.b.g("NodeSetWrapper.prototype.getChildNodeSet",{ki:a.bh.prototype.ki});a.ua=function(c,b){this.tf=c;this.qa=b||{};a.ua.t.constructor.call(this)};o_("FlattenedTreeDataSource",a.ua,a);a.b.ta(a.ua,a.vm,"oj.FlattenedTreeDataSource");a.ua.prototype.Init=function(){var c;a.ua.t.Init.call(this);this.tf.on("change",this.Dva.bind(this));this.NY=parseInt(this.qa.fetchSize,10);isNaN(this.NY)&&(this.NY=25);this.Bw=parseInt(this.qa.maxCount,10);isNaN(this.Bw)&&
(this.Bw=500);c=this.qa.expanded;Array.isArray(c)?this.er=c:("all"===c&&(this.Zl=[]),this.er=[]);this.br=[]};a.b.g("FlattenedTreeDataSource.prototype.Init",{Init:a.ua.prototype.Init});a.ua.prototype.handleEvent=function(c,b){return a.ua.t.handleEvent.call(this,c,b)};a.b.g("FlattenedTreeDataSource.prototype.handleEvent",{handleEvent:a.ua.prototype.handleEvent});a.ua.prototype.Vg=function(){delete this.br;delete this.er;delete this.Zl;this.tf.off("change");this.tf.Vg&&this.tf.Vg()};a.b.g("FlattenedTreeDataSource.prototype.Destroy",
{Vg:a.ua.prototype.Vg});a.ua.prototype.Qk=function(){return this.NY};a.ua.prototype.WL=function(){return this.er};a.b.g("FlattenedTreeDataSource.prototype.getExpandedKeys",{WL:a.ua.prototype.WL});a.ua.prototype.VE=function(a){return null!=this.qa?this.qa[a]:null};a.b.g("FlattenedTreeDataSource.prototype.getOption",{VE:a.ua.prototype.VE});a.ua.prototype.getWrappedDataSource=function(){return this.tf};a.b.g("FlattenedTreeDataSource.prototype.getWrappedDataSource",{getWrappedDataSource:a.ua.prototype.getWrappedDataSource});
a.ua.prototype.BS=function(a){var b,d;b=this.Qk();d=this.Bw;return-1===b?-1===a?d:a:-1===a?Math.min(b,a):b};a.ua.prototype.gp=function(a,b){this.My()?this.Vra(a,b):this.Ura(a,b)};a.ua.prototype.Ura=function(c,b){var d,e,f,g,k,l;if(c.start>this.Gg()){d=this.LS();if(0>this.Gg()){c.count=Math.min(d,c.count);this.tf.ii(null,c,{success:function(a){this.Bs(a,null,0,c,0,b)}.bind(this),error:function(a){this.pq(a,b)}.bind(this)});return}if(0<d){e=this.X6();f=e.parent;g=this.tf.ph(f);k=e.index;l=e.depth;-1===
g||k<g-1?(e=this.BS(g),c.start=k+1,c.count=-1===g?Math.min(e,c.count):Math.min(d,Math.min(Math.min(e,c.count),g-c.start)),this.tf.ii(f,c,{success:function(a){this.Bs(a,f,l,c,g,b)}.bind(this),error:function(a){this.pq(a,b)}.bind(this)})):k===g-1?(d=new a.Wg(null,c.start),null!=b&&null!=b.success&&b.success.call(null,d)):(d=this.O5(f,l,b,d),d||(d=new a.Wg(null,c.start),null!=b&&null!=b.success&&b.success.call(null,d)));return}}this.gY(c,b)};a.ua.prototype.moveOK=function(a,b,d){return this.tf.moveOK(a,
b,d)};a.b.g("FlattenedTreeDataSource.prototype.moveOK",{moveOK:a.ua.prototype.moveOK});a.ua.prototype.move=function(a,b,d,e){this.tf.move(a,b,d,e)};a.b.g("FlattenedTreeDataSource.prototype.move",{move:a.ua.prototype.move});a.ua.prototype.LS=function(){return this.Bw-(this.Gg()+1)};a.ua.prototype.pq=function(a,b){null!=b&&null!=b.error&&b.error.call(null,a)};a.ua.prototype.Bs=function(c,b,d,e,f,g){var k;k=[];c=new a.bh(c,this.cF.bind(this),e);this.yza(c,b,d,k);-1===f&&0===c.getCount()&&null!=b&&0<
d?(k=this.O5(b,d,g))||null!=g&&null!=g.success&&g.success.call(null,c):0===k.length?null!=g&&null!=g.success&&g.success.call(null,c):(b=[],b.push(k),k={},k.callbacks=g,k.nodeSet=c,k.keys=[],this.sca(b,k))};a.ua.prototype.ph=function(a){return this.tf.ph(a)};a.b.g("FlattenedTreeDataSource.prototype.getChildCount",{ph:a.ua.prototype.ph});a.ua.prototype.O5=function(a,b,d,e){var f,g,k,l,m,s,t,r,n;void 0===e&&(e=this.LS());this.lxa()&&(f={queueOnly:!0});g=n=this.BS(-1);for(k=this.Gg()-1;0<=k;k--)if(l=
this.Dj(k),m=l.depth,m<b&&(a=l.parent,s=this.tf.ph(a),l=l.index,(t=-1===s)||l<s-1)){r={};r.start=l+1;t?(r.count=Math.min(e,Math.max(0,g)),f=void 0):r.count=Math.min(e,Math.min(g,s-r.start));if(0==r.count)break;this.tf.ii(a,r,{success:function(b){this.Bs(b,a,m,r,s,d)}.bind(this),error:function(a){this.pq(a,d)}.bind(this)},f);b=m;g=Math.max(0,g-r.count);if(t||0===m||0===g)break}void 0!=f&&this.tf.ii(a,{start:r.count,count:0},{success:function(b){this.Bs(b,a,m,r,s,d)}.bind(this),error:function(a){this.pq(a,
d)}.bind(this)});return g!=n};a.ua.prototype.yza=function(a,b,d,e){var f,g,k,l;f=a.getStart();g=a.getCount();for(k=0;k<g;k++)l=a.getMetadata(f+k),l=l.key,this.tH(l,d,f+k,b),this.jD(l)&&e.push(l)};a.ua.prototype.cF=function(a,b){this.jD(a)&&!b.leaf?b.state="expanded":b.state=b.leaf?"leaf":"collapsed"};a.ua.prototype.Vra=function(a,b){var d={maxCount:this.Bw};0<=this.Gg()&&(d.start=this.Dj(this.Gg()).key);this.tf.Pz(null,{success:function(d){this.Vua(d,a,b)}.bind(this),error:function(a){this.pq(a,b)}.bind(this)},
d)};a.ua.prototype.Tq=function(){return this.tf.Tq()};a.b.g("FlattenedTreeDataSource.prototype.getSortCriteria",{Tq:a.ua.prototype.Tq});a.ua.prototype.Vua=function(c,b,d){var e,f,g;b.start>this.Gg()?(e=this.LS(),f=Math.min(e,b.count),c=new a.bh(c,this.cF.bind(this),null,this.Zl),0<=this.Gg()?(g=this.X6(),e={index:0,found:!1,count:0},this.cV(c,null,0,g,f,e),f=e.index+1):(e={count:0},this.cV(c,null,0,null,f,e),f=0),null!=d&&null!=d.success&&(c=null!=e?0===e.count?new a.Wg(null,b.start):new a.Xg(c,f):
new a.Xg(c),d.success.call(null,c))):this.gY(b,d)};a.ua.prototype.cV=function(a,b,d,e,f,g){var k,l,m,s,t;k=a.getStart();l=a.getCount();for(m=0;m<l&&g.count!=f;m++){s=a.getMetadata(k+m);t=s.key;g.checkDepth&&e.depth===d&&(g.found=!0,g.checkDepth=!1);if(null==e||g.found)this.tH(t,d,k+m,b),g.count+=1,s.state=s.leaf?"leaf":"expanded";null==e||g.found||(t===e.key?s.leaf||this.jD(t)?g.found=!0:g.checkDepth=!0:g.index+=1);a.ki&&this.jD(t)&&(s=a.ki(m),null!=s&&this.cV(s,t,d+1,e,f,g))}};a.ua.prototype.expand=
function(a){this.bg(a)};a.b.g("FlattenedTreeDataSource.prototype.expand",{expand:a.ua.prototype.expand});a.ua.prototype.bg=function(c,b){var d,e,f,g;d=this.tf.ph(c);e=this.BS(d);f=this.Bw;if(this.Gg()+1===f&&(g=this.Rk(c),g==f-1)){this.eY(c,new a.Wg(c,0),0,b);return}0==e?this.eY(c,new a.Wg(c,0),0,b):this.tf.ii(c,{start:0,count:e},{success:function(a){this.eY(c,a,d,b)}.bind(this),error:function(){this.PGa(c)}.bind(this)})};a.ua.prototype.collapse=function(a){var b,d,e,f,g;b=this.Rk(a)+1;d=this.Dj(b-
1);e=0;d=d.depth;f=this.Gg();for(g=b;g<f+1;g++){var k=this.Dj(g).depth;if(k>d)e+=1;else if(k==d)break}if(0!=e){this.My()?this.Zl.push(a):this.pAa(a);f=[];for(d=0;d<e;d++)f.push({key:this.Dj(b+d).key,index:b+d});this.xaa(b,e);this.tN(f)}this.handleEvent("collapse",{rowKey:a})};a.b.g("FlattenedTreeDataSource.prototype.collapse",{collapse:a.ua.prototype.collapse});a.ua.prototype.jD=function(a){return this.My()?this.Zl&&0<this.Zl.length?-1===this.q6(a):!0:this.er&&0<this.er.length?-1<this.G6(a):!1};a.ua.prototype.q6=
function(a){return this.V6(this.Zl,a)};a.ua.prototype.G6=function(a){return this.V6(this.er,a)};a.ua.prototype.V6=function(a,b){var d,e;e=-1;for(d=0;d<a.length;d++)a[d]===b&&(e=d);return e};a.ua.prototype.pAa=function(a){a=this.G6(a);-1<a&&this.er.splice(a,1)};a.ua.prototype.jAa=function(a){a=this.q6(a);-1<a&&this.Zl.splice(a,1)};a.ua.prototype.PGa=function(a){this.handleEvent("expand",{rowKey:a})};a.ua.prototype.eY=function(c,b,d,e){var f,g,k,l,m,s,t,r,n,p,q;b=new a.bh(b,this.cF.bind(this));g=f=
this.Rk(c)+1;k=b.getStart();l=b.getCount();m=this.Dj(f-1);s=m.depth+1;r=[];for(n=k;n<l;n++)k=b.getMetadata(n),t=k.key,this.jD(t)&&r.push(t),this.f9(f,k,m.key,n,s),f++;this.My()?this.jAa(c):-1===this.er.indexOf(c)&&this.er.push(c);void 0!=e&&(p=e.queue,q=e.prevNodeSetInfo);void 0!=q&&(b=new a.nj(q.nodeSet,b,c));if(0!=r.length||void 0!==p&&0!=p.length)void 0===p&&(p=[]),0<r.length&&p.push(r),void 0===q&&(q={},q.firstIndex=g,q.firstKey=c,q.keys=[]),q.nodeSet=b,q.keys.push(c),this.sca(p,q);else{if(void 0!=
q){e=q.callbacks;if(null!=e){e.success.call(null,b);return}this.tM(q.firstIndex,q.firstKey,b)}else this.tM(g,c,b);b=this.Bw;-1===d&&l===this.Qk()||d>l||f==b?this.DR(f):this.Gg()>=b&&this.DR(b);if(void 0!=q)for(d=0;d<q.keys.length;d++)this.handleEvent("expand",{rowKey:q.keys[d]});this.handleEvent("expand",{rowKey:c})}};a.ua.prototype.sca=function(a,b){var d,e;d=a[a.length-1];e=d.shift();0===d.length&&a.pop();this.bg(e,{prevNodeSetInfo:b,queue:a})};a.ua.prototype.f9=function(a,b,d,e,f){b=b.key;a<=this.Gg()?
this.tH(b,f,e,d,a):this.tH(b,f,e,d)};a.ua.prototype.DR=function(a,b){var d;void 0==b&&(b=this.Gg()+1-a);d=[];for(var e=0;e<b;e++)d.push({key:this.Dj(a+e).key,index:a+e});this.xaa(a,b);this.tN(d)};a.ua.prototype.Dva=function(a){var b,d,e;b=a.operation;d=a.parent;d=Array.isArray(d)?d[d.length-1]:d;e=a.index;"insert"===b?this.mva(d,e,a.data):"delete"===b?this.Gua(d,e):"refresh"===b&&this.Tva(d)};a.ua.prototype.mva=function(a,b,d){var e,f;e=this.Rk(a);f=this.Dj(e).depth+1;e=e+b+1;d=d.getMetadata(d.getStart());
this.f9(e,d,a,b,f)};a.ua.prototype.Gua=function(c,b){var d,e,f,g,k;d=this.Rk(c);e=this.Dj(d);d+=b;f=this.Dj(d);a.o.assert(f.parent===e&&f.depth===e.depth+1);e=d+1;for(g=this.Gg();e<=g;){k=this.Dj(e);if(k.depth!=f.depth)break;e++}this.DR(d,1)};a.ua.prototype.Tva=function(a){null==a&&this.refresh()};a.ua.prototype.My=function(){var a=this.tf.getCapability("fetchDescendants");return void 0!=this.Zl&&null!=a&&"disable"!=a};a.ua.prototype.lxa=function(){return"enable"===this.tf.getCapability("batchFetch")};
a.ua.prototype.refresh=function(){this.fpa()};a.ua.prototype.Rk=function(a){var b,d,e;b=this.Gg();for(d=0;d<=b;d++)if(e=this.Dj(d),e.key==a)return d;return-1};a.ua.prototype.getKey=function(a){return 0>a||a>this.Gg()?null:this.Dj(a).key};a.ua.prototype.RFa=function(){return{start:0,end:this.Gg()+1}};a.ua.prototype.JFa=function(a){var b;b=[];a=this.Rk(a);for(a=this.Zm(a);null!=a;)b.push(a),a=this.Rk(a),a=this.Zm(a);return b.reverse()};a.ua.prototype.gY=function(a,b){null!=b&&null!=b.error&&b.error.call(null)};
a.ua.prototype.tM=function(){a.o.kd()};a.ua.prototype.tN=function(){a.o.kd()};a.ua.prototype.Gg=function(){return this.br.length-1};a.ua.prototype.X6=function(){return this.br[this.Gg()]};a.ua.prototype.Dj=function(a){return this.br[a]};a.ua.prototype.Zm=function(a){a=this.br[a];return null!=a?a.parent:null};a.ua.prototype.tH=function(a,b,d,e,f){var g={};g.key=a;g.depth=b;g.index=d;g.parent=e;void 0===f?this.br.push(g):this.br.splice(f,0,g)};a.ua.prototype.xaa=function(a,b){this.br.splice(a,b)};a.ua.prototype.fpa=
function(){this.br.length=0};a.ua.prototype.getCapability=function(a){return this.tf.getCapability(a)};a.b.g("FlattenedTreeDataSource.prototype.getCapability",{getCapability:a.ua.prototype.getCapability});a.Na("oj.ojRowExpander",g.oj.baseComponent,{version:"1.0.0",widgetEventPrefix:"oj",options:{context:null,expand:null,collapse:null},bp:{root:"oj-rowexpander",icon:"oj-component-icon",clickable:"oj-clickable-icon-nocontext",expand:"oj-rowexpander-expand-icon",collapse:"oj-rowexpander-collapse-icon",
leaf:"oj-rowexpander-leaf-icon",lazyload:"oj-rowexpander-lazyload-icon",toucharea:"oj-rowexpander-touch-area",indent:"oj-rowexpander-indent",iconspacer:"oj-rowexpander-icon-spacer",depth0:"oj-rowexpander-depth-0",depth1:"oj-rowexpander-depth-1",depth2:"oj-rowexpander-depth-2",depth3:"oj-rowexpander-depth-3",depth4:"oj-rowexpander-depth-4",depth5:"oj-rowexpander-depth-5",depth6:"oj-rowexpander-depth-6",depth7:"oj-rowexpander-depth-7"},Jz:{bB:7,tO:53},_ComponentCreate:function(){this._super();this.element.addClass(this.bp.root);
this.Q8()},Q8:function(){var a=this,b;b=this.options.context;this.R="function"===typeof b.component?b.component("instance"):b.component;this.xd=b.datasource;this.depth=b.depth;this.Wk=b.state;this.sr=b.key;this.index=b.index;this.jN=b.parentKey;this.Ena();this.Dna();this.EK();"expanded"===this.Wk||"collapsed"===this.Wk?(g(this.KZ).on("touchend",function(b){b.preventDefault();a.gS()}),g(this.KZ).on("click",function(b){b.preventDefault();a.gS()}),g(this.element).on("keypress",function(b){var e=b.keyCode||
b.which;if(e===g.ui.keyCode.ENTER||e===g.ui.keyCode.SPACE)a.gS(),b.preventDefault(),b.target.focus()}),this.rM=this.h8.bind(this),g(this.R.element).on("ojkeydown",this.rM),this.Hfa=this.Pua.bind(this),this.Dfa=this.vua.bind(this),this.xd.on("expand",this.Hfa,this),this.xd.on("collapse",this.Dfa,this)):"leaf"===this.Wk&&(this.rM=this.h8.bind(this),g(this.R.element).on("ojkeydown",this.rM),g(this.icon).attr("tabindex",-1));this.Bfa=this.kua.bind(this);g(this.R.element).on("ojbeforecurrentcell",this.Bfa)},
refresh:function(){this.element.empty();this.Q8()},_destroy:function(){g(this.R.element).off("ojkeydown",this.rM);g(this.R.element).off("ojbeforecurrentcell",this.Bfa);this.xd.off("expand",this.Hfa,this);this.xd.off("collapse",this.Dfa,this);this.element.removeClass(this.bp.root);this.element.empty()},_setOption:function(a,b,d){this._super(a,b,d);"context"==a&&this.refresh()},Ena:function(){var a,b;b=this.depth-1;if(b<this.Jz.bB)this.qQ(b);else{for(a=1;a<=b/this.Jz.bB;a++)this.qQ(this.Jz.bB);a=b%
this.Jz.bB;a<this.Jz.bB&&this.qQ(a)}},qQ:function(a){a=g(document.createElement("span")).addClass(this.bp.indent).addClass(this.bp["depth"+a]);this.element.append(a)},Dna:function(){var a=g(document.createElement("div")).addClass(this.bp.iconspacer);this.KZ=g(document.createElement("div")).addClass(this.bp.toucharea);this.icon=g(document.createElement("a")).attr("href","#").attr("aria-labelledby",this.W6()).addClass(this.bp.icon).addClass(this.bp.clickable);this.element.append(a.append(this.KZ.append(this.icon)))},
Pu:function(a){this.icon.addClass(this.bp[a])},Pv:function(a){this.icon.removeClass(this.bp[a])},EK:function(){switch(this.Wk){case "leaf":this.Pv("icon");this.Pv("clickable");this.Pu("leaf");break;case "collapsed":this.Pu("expand");this.AH(!1);break;case "expanded":this.Pu("collapse");this.AH(!0);break;case "loading":this.Pv("clickable"),this.Pu("lazyload")}},oV:function(){switch(this.Wk){case "leaf":this.Pv("leaf");this.Pu("icon");this.Pu("clickable");break;case "collapsed":this.Pv("expand");break;
case "expanded":this.Pv("collapse");break;case "loading":this.Pv("lazyload"),this.Pu("clickable")}},kua:function(a,b){var d,e;null!=b.currentCell&&(d="cell"==b.currentCell.type?b.currentCell.keys.row:b.currentCell.key,null!=b.previousValue&&(e="cell"==b.previousCurrentCell.type?b.previousCurrentCell.keys.row:b.previousCurrentCell.key),this.sr===d&&e!=d&&this.R.yK&&(d=this.F("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.xd.getWrappedDataSource().ph(this.jN)}),e="collapsed"===
this.Wk?this.F("accessibleStateCollapsed"):"expanded"===this.Wk?this.F("accessibleStateExpanded"):"",this.R.yK({context:d,state:e})))},h8:function(c,b){var d,e,f;if(this.sr===b.rowKey&&(c=c.originalEvent,d=c.keyCode||c.which,a.u.$q(c))){if(d==g.ui.keyCode.RIGHT&&"collapsed"===this.Wk)return this.FU(),this.xd.expand(this.sr),!1;if(d==g.ui.keyCode.LEFT&&"expanded"===this.Wk)return this.FU(),this.xd.collapse(this.sr),!1;if(c.altKey&&d==this.Jz.tO&&this.R.yK){d=this.xd.JFa(this.sr);if(null!=d&&0<d.length)for(e=
[],f=0;f<d.length;f++)e.push({key:d[f],label:this.F("accessibleLevelDescription",{level:f+1})});d=this.F("accessibleRowDescription",{level:this.depth,num:this.index+1,total:this.xd.getWrappedDataSource().ph(this.jN)});this.R.yK({context:d,state:"",ancestors:e})}}return!0},FU:function(){this.oV();this.Wk="loading";this.EK()},Pua:function(a){a=a.rowKey;a===this.sr&&(this.oV(),this.Wk="expanded",this.EK(),this.AH(!0),this._trigger("expand",null,{rowKey:a}))},vua:function(a){a=a.rowKey;a===this.sr&&(this.oV(),
this.Wk="collapsed",this.EK(),this.AH(!1),this._trigger("collapse",null,{rowKey:a}))},gS:function(){var a=this.Wk;this.FU();"collapsed"===a?this.xd.expand(this.sr):"expanded"===a&&this.xd.collapse(this.sr)},AH:function(a){this.icon.attr("aria-expanded",a)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;a=a.subId;return"oj-rowexpander-disclosure"!==a&&"oj-rowexpander-icon"!==a||null==this.icon?null:this.icon.get(0)},getSubIdByNode:function(a){return a===this.icon.get(0)?
{subId:"oj-rowexpander-disclosure"}:null},Or:function(){this._super();this.icon.attr("aria-labelledby",this.W6())},W6:function(){return this.element.parent().closest("[id]").attr("id")}});a.Components.Ta("ojRowExpander","baseComponent",{properties:{context:{type:"Object"}},methods:{getNodeBySubId:{},getSubIdByNode:{},refresh:{}},extension:{_widgetName:"ojRowExpander"}});a.Components.register("oj-row-expander",a.Components.getMetadata("ojRowExpander"))});