/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojeditablevalue"],function(a){(function(){a.Na("oj.ojSwitch",$.oj.editableValue,{version:"1.1.0",defaultElement:"\x3cinput\x3e",widgetEventPrefix:"oj",options:{disabled:!1,readOnly:!1,required:!1,title:"",value:!1},refresh:function(){this._super();this.$a()},widget:function(){return this.uo},getNodeBySubId:function(a){var c,b=this.widget();c=null==a||null==a.subId?b:null;return c||(a=a.subId,"oj-switch-thumb"!==a&&"oj-switch-track"!==a)?c||null:b.find("."+a)[0]},
getSubIdByNode:function(a){var c=$(this.element).attr("id"),b,d=null;null!=a&&($(a).hasClass("oj-switch-track")||$(a).hasClass("oj-switch-thumb"))&&(b=$(a).parents("div.oj-switch").find("input.oj-component-initnode").attr("id"),c===b&&$(a).hasClass("oj-switch-track")?d={subId:"oj-switch-track"}:c===b&&$(a).hasClass("oj-switch-thumb")&&(d={subId:"oj-switch-thumb"}));return d},Ja:{Qma:"SwitchOFF",Rma:"SwitchON"},Xf:function(g,c){var b;this._super(g,c);a.Me.np([{ga:"disabled",Od:!0},{ga:"readonly",option:"readOnly",
Od:!0},{ga:"required",Od:!1,oh:function(){return!1}},{ga:"checked",option:"value",Od:!1,oh:function(a){return a?!0:!1}},{ga:"title"}],c,this);b=this.option("value");this.option({required:!1,value:!!b},{_context:{Ed:!0,ob:!0}})},_ComponentCreate:function(){this._super();if(!this.element.is("input"))throw Error("ojSwitch can be bound to INPUT only.");this.c9=this.element.css("display");this.element.css("display","none").attr("type","checkbox").attr("checked",this.option("value")).attr("tabindex","-1").attr("disabled",
this.option("disabled")).attr("readonly",this.option("readOnly"));this.uo=this.oe?$(this.oe):this.element.wrap("\x3cdiv\x3e\x3c/div\x3e").parent();this.uo.addClass("oj-switch oj-component oj-form-control");this.uo.append("\x3cdiv class\x3d'oj-switch-container'\x3e\x3cdiv class\x3d'oj-switch-track'\x3e\x3cdiv class\x3d'oj-switch-thumb' tabIndex\x3d'0'\x3e\x3c/div\x3e\x3c/div\x3e\x3c/div\x3e");this.nm=this.uo.find(".oj-switch-thumb");this.nm.attr("role","switch checkbox");this.tBa(this.element,this.nm);
this.$a()},tBa:function(a,c){var b=a.prop("id"),d=a.attr("aria-labelledby"),e=a.attr("aria-label");e?c.attr("aria-label",e):d?c.attr("aria-labelledby",d):b&&(b=$("label[for\x3d'"+b+"']"))&&(b.attr("id")?c.attr("aria-labelledby",b.attr("id")):c.attr("aria-label",$(b).text()))},$a:function(){var a=$(this.widget()),c=this.option("title");this.nn();if(void 0!==a){this.element.attr("checked",this.option("value"));a.removeClass("oj-disabled oj-read-only oj-selected oj-hover oj-active");$(this.nm).attr("tabindex",
"0");$(this.nm).html("");if(this.option("disabled")||this.option("readOnly"))this.option("disabled")?a.addClass("oj-disabled"):(a.addClass("oj-read-only"),$(this.nm).html(this.bCa())),$(this.nm).removeAttr("tabindex");this.option("value")&&a.addClass("oj-selected");void 0!==c&&$(this.nm).attr("title",c);$(this.nm).attr("aria-checked",this.option("value"));$(this.nm).removeAttr("aria-disabled");a.removeAttr("aria-disabled");this.zu()||$(this.nm).attr("aria-disabled","true")}},bCa:function(){var a=
this.Ja.Qma;this.option("value")&&(a=this.Ja.Rma);return this.F(a)},nn:function(){this._off(this.uo,"keydown keyup mousedown mouseup mouseleave mouseenter touchstart");this.zu()&&(this._on(this.uo,this.OCa),this.Qe(this.uo));this._focusable({element:this.nm,applyHighlight:!0})},OCa:{keydown:function(a){if(a.which===$.ui.keyCode.ENTER||a.which===$.ui.keyCode.SPACE)$(a.currentTarget).addClass("oj-active"),a.preventDefault()},keyup:function(a){a.which!==$.ui.keyCode.ENTER&&a.which!==$.ui.keyCode.SPACE||
this.ic(!this.option("value"),a)},mousedown:function(a){1===a.which&&$(a.currentTarget).addClass("oj-active")},mouseup:function(a){1===a.which&&this.ic(!this.option("value"),a)},mouseleave:function(a){1===a.which&&$(a.currentTarget).removeClass("oj-active")},mouseenter:function(a){1===a.which&&$(a.currentTarget).addClass("oj-active")},LLa:function(a){this.ic(!this.option("value"),a);a.preventDefault()}},_GetDefaultStyleClass:function(){return"oj-switch"},aLa:function(){return"switch checkbox"},_destroy:function(){this.zu()&&
this.IP(this.uo);this.uo.find(".oj-switch-track").remove();a.u.unwrap(this.element);this.Lx(this.element);return this._super()},_GetMessagingLauncherElement:function(){return this.uo},Wf:function(){return this.nm},_setOption:function(a,c,b){switch(a){case "disabled":case "readOnly":case "value":c=!!c;break;case "required":c=!1;break}this._super(a,c,b);this.$a()}})})();a.Components.Ta("ojSwitch","editableValue",{properties:{disabled:{type:"boolean"},readOnly:{type:"boolean"},title:{type:"string"},
value:{type:"boolean",writeback:!0}},methods:{getNodeBySubId:{},getSubIdByNode:{},refresh:{},widget:{}},extension:{_hasWrapper:!0,_innerElement:"input",_widgetName:"ojSwitch"}});a.Components.register("oj-switch",a.Components.getMetadata("ojSwitch"))});