/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojconveyorbelt","ojs/ojmenu","jqueryui-amd/widgets/sortable","ojs/ojtouchproxy"],function(a,g){(function(){var c={cut:"ojtabscut","paste-before":"ojtabspastebefore","paste-after":"ojtabspasteafter",remove:"ojtabsremove"},b={cut:"labelCut","paste-before":"labelPasteBefore","paste-after":"labelPasteAfter",remove:"labelRemove"};a.Na("oj.ojTabs",g.oj.baseComponent,{widgetEventPrefix:"oj",delay:300,options:{selected:0,disabledTabs:null,truncation:"auto",
selectOn:"click",orientation:"horizontal",edge:"top",removable:!1,reorderable:!1,beforeSelect:null,select:null,beforeDeselect:null,deselect:null,beforeRemove:null,remove:null,beforeReorder:null,reorder:null,optionChange:null},_ComponentCreate:function(){var a=this.options;this._super();this.oZ=!1;this.Ij=!0;this.RV(a.edge);this.w9=0==this.element.children("ul").length;this.Cqa();this.T$();this.Aa={};this.Aa.wh=!1;this.Aa.cG=[];this.Aa.df=null;this.Aa.Hp=null;this.Aa.Br=null;this.Ds();this.Ff();a=
this.T6(a.selected);void 0===a&&(a=0);this.DC(a);this.Ij=void 0},DC:function(a,b){this.NJ(a)&&(a=this.RS(a));this.RB(void 0===a?void 0:g(this.Sb[a]),b)},ih:function(a,b,c){if(this.wxa(b.target)&&(!this.jW||!this.jW.WK)){var h="keyboard"===c;if("contextmenu"==b.type||h||"touch"==c){var k=g(b.target).closest("li");a={launcher:k};this.Aa.tab=h?this.ab:a.launcher;if(this.Aa.tab){if(this.Aa.bG){if(((h=k.hasClass("oj-disabled"))||0==this.sy(k).length)&&1==this.Aa.df.children().length){b.preventDefault();
return}h||!this.vU(k)?this.Aa.bG.addClass("oj-disabled"):this.Aa.bG.removeClass("oj-disabled")}if(this.Aa.Hp||this.Aa.Br)k=!this.Aa.CL,this.Aa.Hp.hasClass("oj-disabled")!=k&&(k?(this.Aa.Hp.addClass("oj-disabled"),this.Aa.Br.addClass("oj-disabled")):(this.Aa.Hp.removeClass("oj-disabled"),this.Aa.Br.removeClass("oj-disabled")),this.Aa.df.ojMenu("refresh"));this.jh(b,c,a)}else b.preventDefault()}}},PCa:function(a){if(!this.p8(a)){var b=g(this.document[0].activeElement).closest("li"),c=this.NC(),h=c.index(b),
k=c.length;switch(a.keyCode){case g.ui.keyCode.RIGHT:case g.ui.keyCode.DOWN:h=(h+1)%k;break;case g.ui.keyCode.UP:case g.ui.keyCode.LEFT:h=((0==h?k:h)-1)%k;break;case g.ui.keyCode.END:h=k-1;break;case g.ui.keyCode.HOME:h=0;break;case 46:(b=this.ab)&&0<this.sy(b).length&&(a.preventDefault(),this.sK(b,null,a));return;default:return}a.preventDefault();clearTimeout(this.RDa);var l=g(c[h]);l.focus();if(!a.ctrlKey){b.attr("aria-selected","false");l.attr("aria-selected","true");var m=this;this.RDa=this._delay(function(){m&&
m.Sb&&m.RB(l,a)},this.delay)}}},cza:function(a){g(a.target).closest(".oj-tabs-selected").attr("id")===this.element.children(".oj-tabs-selected").attr("id")&&!this.p8(a)&&a.ctrlKey&&a.keyCode===g.ui.keyCode.UP&&(a.preventDefault(),this.ab.focus())},p8:function(a){var b=this.$S();if(a.ctrlKey&&a.keyCode===g.ui.keyCode.PAGE_UP)return this.RB(this.g6(b,!1)),!0;if(a.ctrlKey&&a.keyCode===g.ui.keyCode.PAGE_DOWN)return this.RB(this.g6(b,!0)),!0},NJ:function(a){return 0<=a&&a<this.Sb.length?g(this.Sb[a]).hasClass("oj-disabled"):
!1},g6:function(a,b){var c=this.NC(),h=c.index(this.Sb[a]),k=c.length,c=g(c[b?(h+1)%k:((0==h?k:h)-1)%k]);c.focus();return c},RS:function(a){for(var b=a+1,c=this.Sb.length-1;b<=c;){if(!this.NJ(b))return b;b++}for(b=a-1;0<=b;){if(!this.NJ(b))return b;b--}},vd:function(){return"top"==this.options.edge||"bottom"==this.options.edge},_setOption:function(a,b,c){"selected"===a?(b=this.fT(b),void 0!==b&&this.RB(b)):"disabledTabs"===a?(null===b&&(b=[]),Array.isArray(b)&&(this.Dba(b),a=this.$S(),this.NJ(a)&&
this.DC(a),this.refresh())):"removable"===a||"truncation"===a?b!=this.options[a]&&(this._super(a,b,c),this.refresh()):"reorderable"===a?b!==this.options.reorderable&&(this._super(a,b,c),this.refresh()):"orientation"===a?this.TR||(a=this.A$(b))&&this.RV(a)&&this.refresh():"edge"===a?this.RV(b)&&(this.TR=!0,this._super(a,b,c),this.refresh()):"selectOn"===a?(this.rz(!0),this._super(a,b,c),this.nn()):("contextMenu"===a&&(this.Tu(),b&&this.Ds(b)),this._super(a,b,c),"translations"===a&&c&&"removeCueText"===
c.subkey&&this.Nd&&this.sy(this.Nd).attr("aria-label",b?b.removeCueText:""))},refresh:function(){this._super();this.T$();this.Ff();if(!this.element.children(".oj-tabs-selected").length){var a=this.RS(-1);0<=a&&this.DC(a)}},Ff:function(){var a=this.element.children(".oj-tabs-selected");this.ab=a.length?this.Nd.children(".oj-selected"):g();this.Upa();this.nn();this.Sb.not(this.ab).attr({"aria-selected":"false",tabIndex:"-1"});this.al.not(this.xs(this.ab)).hide().attr({"aria-expanded":"false","aria-hidden":"true"});
this.ab.length?(this.ab.addClass("oj-selected").attr({"aria-selected":"true",tabIndex:"0"}),a.show().attr("aria-expanded","true").removeAttr("aria-hidden")):g(this.Sb[0]).attr("tabIndex","0");this.vd()&&(0<this.Sb.length?(this.kDa(),this.wna()):this.gT(),this.Ana());void 0===this.options.selected||0==this.$S()?this.element.addClass("oj-first-child-selected"):this.element.removeClass("oj-first-child-selected");this.pCa()},wna:function(){var a=this.Nd.uniqueId().attr("id");this.Iq=this.gT().parent().ojConveyorBelt({orientation:"horizontal",
contentParent:"#"+a});a=this.Iq.parent();if(a.hasClass("oj-tabs-conveyorbelt-wrapper")){var b="0 1 "+this.Hsa()+"px";a.css("flex",b);a.css("-webkit-flex",b);a.css("-ms-flex",b)}},T$:function(){var a=this,b=this.options.edge;this.m5();this.Bqa();this.Nd=this.element.children("ul").addClass("oj-tabs-nav oj-helper-clearfix").attr("role","tablist");var c=this.Nd.index(),h,k;this.element.children(".oj-tabs-facet").each(function(){var a=g(this);a.index()<c?(a.addClass("oj-start"),h=a):(k||(k=a),a.removeClass("oj-start"))});
this.element.children(".oj-tabs-panel");"start"==b||"top"==b?h?h.after(this.Nd):this.element.prepend(this.Nd):k?k.before(this.Nd):this.element.append(this.Nd);this.Sb=g();this.al=g();this.Nd.children("li").each(function(){var b=g(this).addClass("oj-tabs-tab").attr({role:"tab",tabIndex:"-1"}).removeAttr("aria-hidden"),c=b.children();c.addClass("oj-tabs-tab-content");c=c.children();c.addClass("oj-tabs-anchor").attr({role:"presentation",tabIndex:"-1"});c.children().addClass("oj-tabs-title").removeAttr("aria-hidden");
a.Sb=a.Sb.add(b);var c=c.uniqueId().attr("id"),e=b.attr("data-content"),f=a.element.find(a.Ts("#"+e));b.attr({"aria-controls":e,"aria-labelledby":c});a.al=a.al.add(f);f.attr("aria-labelledby",c).attr("role","tabpanel")});"start"!=b&&"end"!=b||a.Nd.addClass("oj-tabs-nav-root");this.Ij&&this.Dba(this.options.disabledTabs)},nn:function(){var b=this,c={keydown:this.PCa},f=this.options.selectOn,h=!1;f&&g.each(f.split(" "),function(f,g){"click"==g&&(h=!0);a.u.AM(g)&&(c[g]=b.pI)});var k=this.NC();this._on(k,
c);h||this._on(k,{click:function(a){a.preventDefault()}});this.al.on("keydown"+this.eventNamespace,this.cza.bind(this));if(this.options.removable){var f={click:this.CAa},l=this.sy(k);this._on(l,f);this.Qe(l);this.ok(l)}this._focusable({element:k,applyHighlight:!0});this.Qe(k);this.ok({element:k,afterToggle:function(a){"mousedown"===a&&k.filter(".oj-focus-highlight").blur()}})},rz:function(a){var b=this.NC();a||this.Lu(this.sy(b));this.Lu(b);this.al&&this.al.off("keydown"+this.eventNamespace)},pI:function(a,
b){var c=this.ab,h=g(a.currentTarget).closest("li"),k=c&&h[0]===c[0],l=this.xs(h),m=c&&c.length?this.xs(c):g(),c={fromTab:c,fromContent:m,toTab:h,toContent:l};a.preventDefault();var s=b?b:a;h.hasClass("oj-disabled")||this.oZ||k||m&&m.length&&!1===this._trigger("beforeDeselect",s,c)||!this.Ij&&!1===this._trigger("beforeSelect",s,c)||(this.Ij?this.options.selected=this.fJ(h):this.option("selected",this.fJ(h),{_context:{originalEvent:s,ob:!0}}),this.ab=h,l.addClass("oj-tabs-selected"),m&&m.length&&m.removeClass("oj-tabs-selected"),
this.bDa(s,c))},bDa:function(b,c){var f=c.toTab.closest("li"),h=c.toContent,k=c.fromContent;this.oZ=!0;var l=c.fromTab.closest("li").removeClass("oj-selected");k.hide();0<k.length&&a.Components.Wt(k[0]);f.addClass("oj-selected");this.vd()&&0<this.Sb.length&&(0==f.index()?this.element.addClass("oj-first-child-selected"):this.element.removeClass("oj-first-child-selected"));h.show();0<h.length&&a.Components.yr(h[0]);this.oZ=!1;this.Ij||(this._trigger("deselect",b,c),this._trigger("select",b,c));k.attr({"aria-expanded":"false",
"aria-hidden":"true"});l.attr("aria-selected","false");h.length&&k.length?l.attr("tabIndex","-1"):h.length&&this.Sb.filter(function(){return"0"===g(this).attr("tabIndex")}).attr("tabIndex","-1");h.attr("aria-expanded","true").removeAttr("aria-hidden");f.attr({"aria-selected":"true",tabIndex:"0"})},RB:function(a,b){if(void 0!==a){var c;this.ab&&a[0]===this.ab[0]||(c=a.find(".oj-tabs-anchor")[0],this.pI({target:c,currentTarget:c,preventDefault:g.noop},b))}},Upa:function(){if(this.options.removable&&
this.vd()){var a=this.F("removeCueText"),b=this;this.NC().each(function(c){if(b.vU(g(this))){var h=g(this).find("\x3e :first-child");h.addClass("oj-removable");c="ojtabs-id_rm_"+c;g(this).attr("aria-describedby",c);g("\x3ca href\x3d'#'\x3e").addClass("oj-tabs-icon oj-component-icon oj-clickable-icon-nocontext oj-tabs-close-icon").attr({id:c,tabIndex:"-1","aria-label":a,role:"presentation"}).appendTo(h)}})}},NC:function(){return g(this.Sb.not(".oj-disabled"))},sy:function(a){return a.find(".oj-tabs-close-icon")},
m5:function(){this.Sb&&this.rz();this.y8&&(a.u.lm(this.element[0],this.Jg),this.y8=!1,this.WU=void 0);this.$V&&(a.u.af()&&this.Bca(),this.Nd.sortable("instance")&&this.Nd.sortable("destroy"),this.$V=void 0);var b=this.element.children(".oj-tabs-nav-root"),c=!b.hasClass("oj-tabs-nav");if(this.Sb&&(this.sy(this.Sb).remove(),b.length)){var f=b,h=!0,k=this.Nd;b.children().each(function(){var a=g(this);if(a.hasClass("oj-tabs-conveyorbelt-wrapper"))a=k;else if(!a.hasClass("oj-tabs-facet"))return;h=!1;f.after(a);
f=a});h&&c&&b.after(k)}this.Iq&&(this.Iq.ojConveyorBelt("destroy"),this.Iq.remove(),this.ab=this.Iq=null);c&&b.remove();this.Nd=this.Sb=null},_destroy:function(){this.Tu();this.vd()?this.element.removeClass("oj-tabs oj-component oj-tabs-horizontal oj-tabs-top oj-tabs-bottom oj-first-child-selected"):this.element.removeClass("oj-tabs oj-component oj-tabs-vertical oj-tabs-start oj-tabs-end oj-helper-clearfix");var a=this,b,c,h,k;this.Sb.each(function(l){b=g(this);b.removeAttr("tabIndex").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("aria-controls").removeAttr("aria-disabled").removeAttr("aria-describedby").removeAttr("role").removeAttr("data-content").removeClass("oj-active oj-disabled oj-selected oj-tabs-gen-id oj-tabs-tab").removeUniqueId().css("display",
"");c=b.children("div").removeClass("oj-tabs-tab-content");h=c.children("a").removeClass("oj-tabs-anchor").removeAttr("tabIndex").removeAttr("role");k=h.children();k.removeClass("oj-tabs-title").removeAttr("aria-hidden");a.w9?k.prependTo(a.al.get(l)):c.hasClass("oj-tabs-gen-div")&&h.hasClass("oj-tabs-gen-a")?(k.prependTo(b),c.remove()):h.hasClass("oj-tabs-gen-a")?(k.prependTo(c),h.remove()):c.hasClass("oj-tabs-gen-div")&&(h.prependTo(b),c.remove())});var l=this.Nd;this.m5();l.removeAttr("tabIndex").removeAttr("role").removeClass("oj-tabs-nav oj-tabs-nav-root oj-helper-clearfix").removeUniqueId();
this.w9&&l.remove();this.al.each(function(){g(this).removeAttr("tabIndex").removeAttr("aria-expanded").removeAttr("aria-selected").removeAttr("aria-labelledby").removeAttr("aria-hidden").removeAttr("role").removeClass("oj-active oj-tabs-selected oj-tabs-gen-id oj-tabs-panel").removeUniqueId().css("display","")});this.element.children(".oj-tabs-facet").removeClass("oj-start")},vU:function(a){var b=this.options.removable;return b&&(!Array.isArray(b)||-1<b.indexOf(a.attr("id")))},sK:function(a,b,c){if(this.vU(a)){var h=
this.xs(a),k={tab:a,content:h};c=c?c:b?b:{target:a,currentTarget:a,preventDefault:g.noop};a&&!1!==this._trigger("beforeRemove",c,k)&&(b&&b.preventDefault(),a.hasClass("oj-selected")&&(b=this.RS(this.Sb.index(a)),void 0===b?(this.ab=void 0,this.option("selected",void 0,{_context:{originalEvent:c,ob:!0}})):(this.DC(b,c),this.option("selected",this.fJ(g(this.Sb[b])),{_context:{originalEvent:c,ob:!0}}))),this.rz(),this.Sb=this.Sb.not(a),a.remove(),h.remove(),this.IW(),this.refresh(),this._trigger("remove",
c,k))}},CAa:function(a,b){this.sK(g(a.currentTarget).closest("li"),a,b)},removeTab:function(a){if("string"!==typeof a)throw Error("'"+a+"' is not a tab id");this.sK(this.fT(a),null,null)},nL:function(a,b){var c;if("li"==a.prop("tagName").toLowerCase()){c=a;var g=c.children("div");1==g.length&&g.hasClass("oj-tabs-tab-content")?(g=g.children("a"),1!=g.length&&(c.wrapInner("\x3ca href\x3d'#'\x3e\x3c/a\x3e"),g.addClass("oj-tabs-gen-a"))):(g=c.wrapInner("\x3cdiv\x3e\x3ca href\x3d'#'\x3e\x3c/a\x3e\x3c/div\x3e").children(),
g.addClass("oj-tabs-gen-div oj-tabs-tab-content"),g.children().addClass("oj-tabs-gen-a"))}else c=a.wrap("\x3cli\x3e\x3cdiv\x3e\x3ca href\x3d'#'\x3e\x3c/a\x3e\x3c/div\x3e\x3c/li\x3e").parent().parent().parent(),c.addClass("oj-tabs-gen-li"),c.children().addClass("oj-tabs-gen-div oj-tabs-tab-content");b&&c.attr("data-content",b);return c},addTab:function(a){var b,c,h=-1;a.tab&&a.content?(c=a.content,b=this.nL(a.tab,this.jJ(c)),void 0!==a.index&&(h=a.index)):(c=a,b=this.nL(g(a).find("\x3e :first-child"),
this.jJ(c)));a=this.element.children(".oj-tabs-nav-root");a=a.hasClass("oj-tabs-nav")?a:a.length?a.find(".oj-tabs-nav"):this.element.children(".oj-tabs-nav");var k=!1;a.length||(a=g("\x3cul\x3e"),k=!0);k&&a.prependTo(this.element);0<=h&&h<a.children().length?(h=a.children(":eq("+h+")"),a=this.element.children(this.Ts("#"+h.attr("aria-controls"))),h.before(b),a.before(c)):(b.appendTo(a),c.appendTo(this.element));this.refresh();0==this.ab.length&&this.DC(0);var l=this;window.setTimeout(function(){l.Sb&&
b[0].scrollIntoView(!1)},0)},sCa:function(){this.jW=a.Bg.hda(this.Nd)},Bca:function(){a.Bg.Lha(this.Nd)},pCa:function(){if(this.options.reorderable){var b=this;a.u.af()&&this.sCa();this.Nd.sortable({axis:b.vd()?"x":"y",stop:function(a,c){var g=c.item;b.w5(a,g,g.prev())||b.Nd.sortable("cancel")}});this.$V=!0}else this.Bca(),this.$V=!1},Xf:function(a,b){var c=b.edge;this.TR="top"==c||"bottom"==c||"start"==c||"end"==c;this._super(a,b)},A$:function(a){return"horizontal"==a?"top":"vertical"==a?"start":
null},RV:function(a){if(this.Ij&&!this.TR||!a)a=this.A$(this.options.orientation);var b=this.options.edge;this.element.removeClass("oj-tabs-top oj-tabs-bottom oj-tabs-start oj-tabs-end");switch(a){case "top":case "bottom":!this.al||"start"!=b&&"end"!=b||this.element.removeClass("oj-tabs-vertical oj-helper-clearfix");this.element.addClass("oj-tabs oj-component oj-tabs-horizontal");"bottom"==a?this.element.addClass("oj-tabs-bottom"):this.element.addClass("oj-tabs-top");this.Ij?this.options.orientation=
"horizontal":"horizontal"!=this.options.orientation&&this.option("orientation","horizontal",{_context:{ob:!0},changed:!0});break;case "start":case "end":!this.al||"top"!=b&&"bottom"!=b||this.element.removeClass("oj-tabs-horizontal");this.element.addClass("oj-tabs oj-component oj-tabs-vertical oj-helper-clearfix");"end"==a?this.element.addClass("oj-tabs-end"):this.element.addClass("oj-tabs-start");this.Ij?this.options.orientation="vertical":"vertical"!=this.options.orientation&&this.option("orientation",
"vertical",{_context:{ob:!0},changed:!0});break;default:return!1}this.Ij?this.options.edge=a:this.options.edge!=a&&this.option("edge",a,{_context:{ob:!0},changed:!0});return!0},gT:function(){var a=this.Nd.parent();a.hasClass("oj-tabs-conveyor")||(a=this.Nd.wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-conveyor"),(0<this.element.children(".oj-tabs-facet").length?a.wrap("\x3cdiv\x3e").wrap("\x3cdiv\x3e").parent().parent().addClass("oj-tabs-conveyorbelt-wrapper"):a).wrap("\x3cdiv\x3e").parent().addClass("oj-tabs-nav-root").uniqueId().attr("id"));
return a},rKa:function(a){0>a.id.indexOf("ojtabs-id_")&&g(a).attr("id","ojtabs-id_"+a.id)},getNodeBySubId:function(a){if(null==a)return this.element?this.element[0]:null;var b=a.subId;a=a.index;if("oj-conveyorbelt"!=b&&("number"!==typeof a||0>a||a>=this.al.length))return null;switch(b){case "oj-conveyorbelt":return this.Iq?this.Iq[0]:null;case "oj-tabs-panel":return this.xs(this.Sb[a])[0];case "oj-tabs-tab":return this.Sb[a];case "oj-tabs-title":return g(this.Sb[a]).find(".oj-tabs-title")[0];case "oj-tabs-close-icon":case "oj-tabs-close":return g(this.Sb[a]).find(".oj-tabs-close-icon")[0]}return null},
getSubIdByNode:function(a){for(var b=[],c=0;c<this.Sb.length;c++)b.push(this.xs(this.Sb[c])[0]);for(var g=c=-1,k=a;k;){if(this.Iq&&k===this.Iq[0])return{subId:"oj-conveyorbelt"};c=Array.prototype.indexOf.call(this.Sb,k);if(-1!=c)break;g=b.indexOf(k);if(-1!=g)return{subId:"oj-tabs-panel",index:g};k=k.parentElement}if(-1!=c)for(b=this.getNodeBySubId({subId:"oj-tabs-title",index:c}),g=this.getNodeBySubId({subId:"oj-tabs-close",index:c}),k=a;k;){if(k===b)return{subId:"oj-tabs-title",index:c};if(k===g)return{subId:"oj-tabs-close",
index:c};if(k===this.Sb[c])return{subId:"oj-tabs-tab",index:c};k=k.parentElement}return null},Hsa:function(){return this.WU+10},G7:function(){var a=this.element.find(".oj-tabs-conveyorbelt-wrapper");return a.length?a[0].clientWidth:this.element[0].clientWidth},x9:function(){return this.WU>this.G7()},Vta:function(){var a=Math.floor(this.G7()/this.Sb.length);this.options.removable&&(a-=28);return a},n3:function(){var a=this.Vta();this.Nd.find(".oj-tabs-title").each(function(){g(this).css("max-width",
""+a+"px").addClass("oj-tabs-title-overflow")})},DAa:function(){this.Nd.find(".oj-tabs-title").each(function(){g(this).css("max-width","").removeClass("oj-tabs-title-overflow")})},YKa:function(){},Hg:function(){this.C9()&&(this.x9()?this.n3():this.DAa())},C9:function(){return"auto"==this.options.truncation||"progressive"==this.options.truncation},kDa:function(){this.vd()&&0<this.Sb.length&&(null==this.Jg&&(this.Jg=this.Hg.bind(this)),a.u.Mk(this.element[0],this.Jg),this.y8=!0,this.WU=this.gT()[0].scrollWidth,
this.C9()&&this.x9()&&this.n3())},Sp:function(){this._super();this.refresh()},Or:function(){this._super();this.refresh()},yj:function(a){return g("\x3ca\x3e").text(this.F(b[a])).attr("href","#").wrap("\x3cli\x3e").parent().attr("id",c[a]).addClass("oj-menu-item")},mya:function(a){if(!a||!a.length)return!1;this.Aa.CL=a},g$:function(a,b,c){if(!b||!b.length||!this.Aa.CL)return!1;var g=this.Aa.CL;this.Aa.CL=!1;this.w5(a,g,b,c)},nya:function(a,b){if(!b||!b.length)return!1;this.sK(b,null,a)},Dk:function(a,
b){var c=b?b.item.attr("id"):void 0;"ojtabscut"===c?this.mya(this.Aa.tab):"ojtabspastebefore"===c?this.g$(a,this.Aa.tab,!0):"ojtabspasteafter"===c?this.g$(a,this.Aa.tab,!1):"ojtabsremove"===c&&this.nya(a,this.Aa.tab)},Ds:function(a){if(a=a||this.options.contextMenu){if("function"==g.type(a)){try{a=a()}catch(b){a=null}g.type(a)}a&&g(a).length&&(this.options.contextMenu=a)}this.Aa.wh=!!a;this.Yr()},vH:function(a,b,c){-1==b.indexOf(c)&&(b=this.yj(c),a.append(b),this.Aa.cG.push(b))},Yr:function(){var a=
g(this.options.contextMenu);if(0!=a.length||this.options.reorderable||this.options.removable){var c=this;if(0==a.length){var f=this.options.reorderable?"labelReorder":b.remove,h=this.element.uniqueId().attr("id")+"contextmenu",a=g("\x3cul\x3e");a.css("display","none").attr("id",h).attr("aria-label",this.F(f));g(document.body).append(a);a.ojMenu();this.options.contextMenu=this.Ts("#"+h)}var k=[];a.find("[data-oj-command]").each(function(){if(0===g(this).children("a").length){var a=g(this).attr("data-oj-command").slice(8);
g(this).replaceWith(c.yj(a));g(this).addClass("oj-menu-item");k.push(a)}});this.options.reorderable&&(this.vH(a,k,"cut"),this.vH(a,k,"paste-before"),this.vH(a,k,"paste-after"),this.Aa.Hp=a.find("#ojtabspastebefore"),this.Aa.Br=a.find("#ojtabspasteafter"));this.options.removable&&(this.vH(a,k,"remove"),this.Aa.bG=a.find("#ojtabsremove"));this.Aa.df=a;a.ojMenu("refresh");a.on("ojselect",g.proxy(this.Dk,this))}},Tu:function(){var a=this.Aa;if(a&&a.df){a.df.off("ojselect");a.wh||(a.df.ojMenu("destroy"),
a.df.remove());if(a.cG)for(;0<a.cG.length;)a.cG.pop().remove();a.df=null}a.Hp=null;a.Br=null;a.bG=null},w5:function(a,b,c,g){var k=this.xs(b),l={tab:b,content:k};if(!1===this._trigger("beforeReorder",a,l))return!1;var m=this.Sb.index(b);if(c.length){if(this.Sb.index(c)==m)return!0;m=this.xs(c);g?(c.before(b),m.before(k)):(c.after(b),m.after(k))}else if(0<this.Sb.length){if(0==m)return!0;this.Sb.first().before(b);this.al.first().before(k)}this.IW();this.refresh();c.blur();b.focus();this._trigger("reorder",
a,l);return!0},Ts:function(a){return a?a.replace(/[!"$%&'()*+,.\/:;<=>?@\[\]\^`{|}~]/g,"\\$\x26"):""},xs:function(a){return this.element.find(this.Ts("#"+g(a).attr("aria-controls")))},jJ:function(a){var b=a.attr("id");b||(b=a.uniqueId().attr("id"),a.addClass("oj-tabs-gen-id"));return b},fT:function(a){a=this.T6(a);if(-1!==a)return g(this.Sb[a])},T6:function(b){var c=-1;"number"===typeof b?0<=b&&b<this.Sb.length&&(c=b):"string"===typeof b&&(b=this.Ts(b),a.u.AM(b)&&(b=this.element.find(this.Ts("#"+
b)),b.length&&(c=this.Sb.index(b),-1==c&&(c=this.al.index(b)))));return c},$S:function(){var a=this.options.selected;return"number"===typeof a?a:this.Sb.index(g(this.Ts("#"+a)))},fJ:function(a){if(a){var b=a.attr("id");return b?b:this.Sb.index(a)}},Dba:function(a){var b=(this.Nd?this.Nd:this.element.children("ul")).children("li");b.removeClass("oj-disabled").removeAttr("aria-disabled");var c=[];if(a&&0<a.length)for(var g,k,l=0;l<a.length;l++)if(k=this.fT(a[l]))k.addClass("oj-disabled"),k.attr("aria-disabled",
"true"),k.find(".oj-tabs-anchor").removeAttr("href"),g=k.attr("id"),c.push(g?g:b.index(k));this.IW(c)},IW:function(b){if(!b){b=[];var c=this;this.Nd.children().each(function(){var a=g(this);a.hasClass("oj-disabled")&&b.push(c.fJ(a))})}a.b.u4(this.options.disabledTabs,b)||(this.Ij?this.options.disabledTabs=b:this.option({disabledTabs:b},{_context:{ob:!0,Ed:!0},changed:!0}))},wxa:function(a){var b=!1;this.Sb.each(function(){if(this===a||g.contains(this,a))return b=!0,!1});return b},Bqa:function(){var a=
this.u6(),b=this,c=this.element.children("ul");0<c.length&&c.children("li").each(function(c){b.nL(g(this),a[c])})},Cqa:function(){var a=this.element.children("ul");if(0==a.length){var b=this,c=this.u6(),a=g("\x3cul\x3e");this.element.children().each(function(h){b.nL(g(this).find("\x3e :first-child"),c[h]).appendTo(a)});a.prependTo(this.element)}},Ana:function(){var a=this.element.children(".oj-tabs-nav-root"),b=this,c=a.children(".oj-tabs-conveyorbelt-wrapper");a.index();this.element.children(".oj-tabs-facet").each(function(){var h=
g(this),k=b.jJ(h);0==a.find(b.Ts("#"+k)).length&&(h.hasClass("oj-start")?c.before(h):h.appendTo(a))})},u6:function(){var a=[],b=this;this.element.children(":not(ul):not(.oj-tabs-facet)").each(function(){var c=g(this);c.addClass("oj-tabs-panel");a.push(b.jJ(c))});return a}})})();a.Components.Ta("ojTabs","baseComponent",{properties:{disabledTabs:{type:"Array"},edge:{type:"string"},orientation:{type:"string"},removable:{type:"boolean|Array"},reorderable:{type:"boolean"},selected:{type:"string|number"},
selectOn:{type:"string"},truncation:{type:"string"}},methods:{addTab:{},refresh:{},removeTab:{}},extension:{_widgetName:"ojTabs"}});a.Components.register("oj-tabs",a.Components.getMetadata("ojTabs"))});