/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
 Copyright (c) 2014, Oracle and/or its affiliates.
 All rights reserved.
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","promise","ojdnd","ojs/ojdomscroller","ojs/ojeditablevalue","ojs/ojmenu","ojs/ojdatasource-common","ojs/ojpagingtabledatasource","ojs/ojflattenedtreetabledatasource"],function(a,g){(function(){a.Na("oj.ojTable",g.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3ctable\x3e",widgetEventPrefix:"oj",options:{accessibility:null,currentRow:null,data:null,display:"list",dnd:{drag:null,drop:null,reorder:{columns:"disabled"}},editMode:"none",emptyText:null,
horizontalGridVisible:"auto",rowRenderer:null,scrollPolicy:"auto",scrollPolicyOptions:{fetchSize:25,maxCount:500},selection:[],selectionMode:null,verticalGridVisible:"auto",columns:[{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,id:null,sortable:"auto",sortProperty:null,style:null}],columnsDefault:{renderer:null,className:null,field:null,footerClassName:null,footerRenderer:null,
footerStyle:null,headerClassName:null,headerRenderer:null,headerStyle:null,headerText:null,sortable:"auto",sortProperty:null,style:null},beforeCurrentRow:null,beforeRowEdit:null,beforeRowEditEnd:null,ready:null,sort:null,optionChange:null},Ja:{Ola:"msgFetchingData",Sla:"msgNoData",Dla:"labelSelectColumn",y1:"labelSelectRow",v1:"labelEditRow",x1:"labelSelectAndEditRow"},od:{Z0:"Did not change current row due to error.",Y0:"Error detail: {error}.",Xka:"Did not change current row due to unavailable row index.",
Wka:"Unavailable row index: {rowIdx}.",ela:"Invalid row index value.",dla:"Row index: {rowIdx}.",X0:"Invalid data type.",W0:"Please specify the appropriate data type.",ala:"Invalid element type.",$ka:"Only a \x3ctable\x3e element can be specified for ojTable.",Zka:"Exceeded maximum rows for table scrolling.",Yka:"Please reload with smaller data set."},fP:"id",Fm:"data",tB:"indexes",Op:"key",vx:"keys",yg:"startIndex",fh:"endIndex",I0:"pageSize",Uf:"column",Vf:"row",bKa:"_headerColumn",cKa:"_headerColumnText",
ZJa:"_headerColumnAsc",aKa:"_headerColumnDsc",Dka:"_hdrCol",Ax:"_focusedCalled",VG:"auto",uj:"enabled",Rr:"disabled",N1:"none",BB:{sl:"none",c2:"rowEdit"},wk:{Mx:"single",Nr:"multiple"},Xla:{qj:"auto",Gla:"loadMoreOnScroll"},Ii:{wu:"ascending",Lr:"descending"},Uka:"oj-table-dnd-reorder-table-id",Tb:{t1:32,QG:13,RG:38,PG:40,r1:37,s1:39,q1:36,n1:35,lP:9,o1:27,p1:113,Im:"shiftKey"},getContextByNode:function(a){return this.getSubIdByNode(a,!0)},getDataForVisibleRow:function(a){var b=this.q().Ae(a);return null!=
b?{key:b.data("rowKey"),data:b.data("rowData"),index:a}:null},getNodeBySubId:function(c){if(null==c)return this.element?this.element[0]:null;var b=c.subId;if("oj-table-cell"===b)return b=parseInt(c.rowIndex,10),c=parseInt(c.columnIndex,10),this.q().mGa(b)[c];if("oj-table-header"===b||"oj-table-sort-ascending"===b||"oj-table-sort-descending"===b){if(c=c.index,c=g(this.q().oGa()[c]),null!=c){if("oj-table-header"===b)return c[0];b="oj-table-sort-ascending"===b?c.find("."+a.f.J.yu):c.find("."+a.f.J.ux);
if(0<b.length)return b[0]}}else if("oj-table-footer"===b&&(c=c.index,b=this.q().nGa()[c],null!=b))return b;return null},getSubIdByNode:function(c,b){var d=g(c).closest("."+a.f.J.Nx);if(0<d.length)return{subId:"oj-table-cell",rowIndex:this.q().Qq(d),columnIndex:this.q().xe(d)};d=g(c).closest("."+a.f.J.yu);if(0<d.length)return{subId:b?"oj-table-header":"oj-table-sort-ascending",index:this.q().xe(d)};d=g(c).closest("."+a.f.J.ux);if(0<d.length)return{subId:b?"oj-table-header":"oj-table-sort-descending",
index:this.q().xe(d)};d=g(c).closest("."+a.f.J.Kr);if(0<d.length)return{subId:"oj-table-header",index:this.q().xe(d)};d=g(c).closest("."+a.f.J.Ju);return 0<d.length?{subId:"oj-table-footer",index:this.q().xe(d)}:null},refresh:function(){this._super();this.Ff()},refreshRow:function(c){var b=this.Lb();if(!b)return Promise.resolve(!1);var d=this.q().$e();if(isNaN(c)||0>c||null!=d&&c>=d.length)throw b=this.od.ela,d=a.va.Lc(this.od.dla,{rowIdx:c.toString()}),new RangeError(b+"\n"+d);var d=this.Ao(c),e=
b.get(d);if(null==e)return Promise.resolve(!1);var f=this;return new Promise(function(a){e.then(function(b){null==b&&a(!1);f.Yh(function(){f.mK(c,b);f=null});a(!0)})})},widget:function(){var a=this.q().zd();return null!=a?a:this.element},_ComponentCreate:function(){this._super();this.uC();this.$za();this._on(this.hq);if(this.QJ()){var a=this.q().zd();this._on(a,this.Ira)}this.aAa();this.Ov();this.J3=g.extend(!0,{},this.options);this.KV(null)},Hh:function(){this._super();this.q().Qda(this.Dk.bind(this));
this.gU()},ih:function(a,b,d){var e={};this.Pm=b.originalEvent;if(!(this.sU(g(this.Pm.target))||this.zxa(g(this.Pm.target))||"touch"==d&&this.Axa(g(this.Pm.target)))){var f=this.q().qt(g(this.Pm.target),"oj-table-column-header-cell"),f=null==f?this.q().Wd(this.O2):f,h=this.q().qt(g(this.Pm.target),"oj-table-data-cell");null!=h&&(f=this.q().xe(h),f=this.q().Wd(f));"keydown"===this.Pm.type&&(h=this.cW.yd(),this.Pm.target==h[0]?null!=f&&null!=f[0]?e.position={my:"start top",at:"start bottom",of:f[0]}:
(h=this.Xm(),0<=h?(h=this.q().Ae(h),e.position={my:"start top",at:"start bottom",of:h[0]}):e.position={my:"start top",at:"start bottom",of:this.Pm.target}):e.position={my:"start top",at:"start bottom",of:this.Pm.target});f.attr("data-oj-sortable")==this.uj?(g(a.element).find("[data-oj-command\x3doj-table-sortAsc]").removeClass("oj-disabled"),g(a.element).find("[data-oj-command\x3doj-table-sortDsc]").removeClass("oj-disabled")):(g(a.element).find("[data-oj-command\x3doj-table-sortAsc]").addClass("oj-disabled"),
g(a.element).find("[data-oj-command\x3doj-table-sortDsc]").addClass("oj-disabled"));this.jh(b,d,e)}},_destroy:function(){this.Lb();this.Uo();this.Vo();this.q().ze().removeAttr(a.Components.co);this.element.children().remove("."+a.f.J.XP);this.element.children().remove("."+a.f.J.NP);this.element.children().remove("."+a.f.J.WP);this.element.children().remove("."+a.f.J.YP);this.element.children().remove("."+a.f.J.u2);a.u.unwrap(this.element,this.q().zd());this.element.removeClass(a.f.J.l2);this.lC=!0},
uC:function(){this.IBa(function(){this.q().qN();this.mz(this.options.selection);if(this.uv()){var c=this.Wm(),c=this.q().Ae(c);null!=c&&c.addClass(a.f.J.n2)}this.Jj()&&!this.Y4&&this.MR.checkViewport().then(this.x5,null)});if(!this.element.is("table"))throw new RangeError(this.od.ala+"\n"+this.od.$ka);this.element.addClass(a.f.J.Xma);this.q().QEa(this.OJ(),this.F9());this.q().tJa();this.laa();this.VD();this.kaa();this.q().qN();this.Jj()&&this.raa();this.options.disabled&&this.disable();this.jn()},
hq:{blur:function(a){var b=this.q().yd();0<b.has(a.relatedTarget).length||null!=a.originalEvent&&a.originalEvent.explicitOriginalTarget==b[0]||(this.lpa(),this.j4(),this.k4(!1),this.Uv(!1))},"blur .oj-table-data-cell":function(c){g(c.currentTarget).hasClass(a.f.J.PP)&&g(c.currentTarget).removeClass(a.f.J.PP)},focus:function(a){this.XQ(a)},focusin:function(a){0<this.q().ze().has(a.target).length&&!this.dW&&!this.uv()&&!this.Dca&&this.q().yd().focus()},"focus .oj-table-column-header-acc-asc-link":function(a){var b=
this;setTimeout(function(){b.XQ(a);b=null},0)},"focus .oj-table-data-cell":function(c){this.q().Qq(g(c.currentTarget))==this.Wm()&&g(c.currentTarget).addClass(a.f.J.PP)},"click .oj-table-checkbox-acc-select-column":function(a){var b=this.q().xe(g(a.currentTarget)),d=g(a.currentTarget).is(":checked");d&&this.Oo(b,!0,!0,null);this.Po(b,d,a.currentTarget,a,!0);a.stopPropagation()},"click .oj-table-checkbox-acc-select-row":function(a){var b=this.q().Qq(g(a.currentTarget)),d=g(a.currentTarget).is(":checked"),
e=!1;d?e=this.Ik(b,!0,!0,null,a,!0):this.ai(!1,!1,0,!0,a);e&&(this.Oj(b,d,a.currentTarget,a,!0),this.ai(!0,!1,0,!0,a));a.stopPropagation()},keydown:function(a){this.Ina(a.keyCode);if(this.Fj()[0]==this.Tb.lP||!(this.sU(g(a.target))||null!=this.q().mp()&&0<this.q().mp().has(a.target).length))if(1==this.Fj().length||2==this.Fj().length&&a[this.Tb.Im]){if(this.Uh(this.Tb.RG)||this.Uh(this.Tb.PG)||this.Uh(this.Tb.t1)||this.Uh(this.Tb.q1)||this.Uh(this.Tb.n1))a.preventDefault(),a.stopPropagation();this.Uh(this.Tb.RG)||
this.Uh(this.Tb.PG)?this.qva(a):this.Uh(this.Tb.r1)||this.Uh(this.Tb.s1)?this.ova(a):this.Uh(this.Tb.lP)&&this.pva(a)}},keyup:function(a){if(1==this.Fj().length){var b=this.Fj()[0];if(b!=this.Tb.o1&&b!=this.Tb.QG&&b!=this.Tb.p1&&b!=this.Tb.lP&&(this.sU(g(a.target))||null!=this.q().mp()&&0<this.q().mp().has(a.target).length)){this.qK(b);return}b==this.Tb.t1?this.wva(a):b==this.Tb.QG?this.sva(a):b==this.Tb.q1?this.vva(a):b==this.Tb.n1?this.rva(a):b==this.Tb.o1?this.tva(a):b==this.Tb.p1&&this.uva(a);
this.qK(b)}this.qK(a.keyCode)},"mousedown .oj-table-body":function(c){this.Pi=this.q().Qq(g(c.target));if(null!=this.Pi){var b=this.q().Ae(this.Pi);null!=b&&b.prop("draggable")?this.Pi=null:null==this.Pi||c[this.Tb.Im]||a.u.$q(c)||this.By(this.Pi)&&1==this.Cy().length||this.r$||this.Yx()}},"mouseup .oj-table-body":function(){this.Pi=null},"mouseenter .oj-table-body-row":function(c){g(c.currentTarget).addClass(a.f.Da.$n);this.IT(c.target)},"mouseleave .oj-table-body-row":function(c){g(c.currentTarget).removeClass(a.f.Da.$n)},
"mousedown .oj-table-column-header-cell":function(a){var b=this.q().xe(g(a.currentTarget));this.Oo(b,!0,!0,a);g(a.target).data(this.Ax,!0)},"mouseenter .oj-table-column-header-cell":function(c){g(c.currentTarget).addClass(a.f.Da.$n);c=this.q().xe(g(c.currentTarget));this.bca(c)},"mouseleave .oj-table-column-header-cell":function(c){g(c.currentTarget).removeClass(a.f.Da.$n);c=this.q().xe(g(c.currentTarget));this.wv(c,!0);this.wv(c,!1)},"mousedown .oj-table-data-cell":function(a){var b=this.q().Qq(g(a.currentTarget));
this.Ik(b,!0,!0,a.currentTarget,a);g(a.target).data(this.Ax,!0)},"mouseenter .oj-table-data-cell":function(c){g(c.currentTarget).addClass(a.f.Da.$n)},"mouseleave .oj-table-data-cell":function(c){g(c.currentTarget).removeClass(a.f.Da.$n)},"click .oj-table-column-header-asc-link":function(a){var b=this.q().xe(g(a.target)),d=this.q().Wd(b);d&&(d.data("sorted")==this.Ii.wu?this.El(b,!1,a):this.El(b,!0,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-asc-link":function(a){if(0<
this.Fj().length&&this.Fj()[0]==this.Tb.QG)a.preventDefault(),a.stopPropagation();else{var b=this.q().xe(g(a.target)),d=this.q().Wd(b);d&&(d.data("sorted")==this.Ii.Lr?this.El(b,!0,a):this.El(b,!1,a),a.preventDefault(),a.stopPropagation())}},"click .oj-table-column-header-dsc-link":function(a){var b=this.q().xe(g(a.target)),d=this.q().Wd(b);d&&(d.data("sorted")==this.Ii.Lr?this.El(b,!0,a):this.El(b,!1,a),a.preventDefault(),a.stopPropagation())},"click .oj-table-column-header-acc-dsc-link":function(a){if(0<
this.Fj().length&&this.Fj()[0]==this.Tb.QG)a.preventDefault(),a.stopPropagation();else{var b=this.q().xe(g(a.target)),d=this.q().Wd(b);d&&(d.data("sorted")==this.Ii.Lr?this.El(b,!0,a):this.El(b,!1,a),a.preventDefault(),a.stopPropagation())}},"click .oj-table-data-cell":function(c){var b=this.q().Qq(g(c.currentTarget));if(!g(c.target).data(this.Ax)){var d=this.Ik(b,!0,!0,c.currentTarget,c);g(c.target).data(this.Ax,!1);if(!d)return}if(c[this.Tb.Im]){if(d=this.jta(),null!=d)if(window.getSelection().removeAllRanges(),
b<d){var e;for(e=b;e<=d;e++)this.Oj(e,!0,c.currentTarget,c,!0)}else for(e=d;e<=b;e++)this.Oj(e,!0,c.currentTarget,c,!0)}else a.u.$q(c)?this.Oj(b,!this.By(b),c.currentTarget,c,!0):0==this.Fj().length&&(d=this.By(b),this.Oj(b,!d,c.currentTarget,c,!0),this.QJ()&&this.oq()==this.wk.Nr&&!d&&this.q().UEa(b))},"dblclick .oj-table-data-cell":function(a){var b=this.q().xe(g(a.target));this.ai(!0,!1,b,!0,a)},"contextmenu .oj-table-data-cell":function(a){var b=this.q().Qq(g(a.currentTarget)),b=this.Ao(b);this.mn({rowKey:b},
a,!1)},"click .oj-table-column-header-cell":function(c){var b=this.q().xe(g(c.currentTarget));g(c.target).data(this.Ax)||(this.Oo(b,!0,!0,c),g(c.target).data(this.Ax,!1));if(c[this.Tb.Im]){var d=this.ita();if(null!=d)if(b<d){var e;for(e=b;e<=d;e++)this.Po(e,!0,c.currentTarget,c,!0)}else for(e=d;e<=b;e++)this.Po(e,!0,c.currentTarget,c,!0)}else a.u.$q(c)?this.Po(b,!this.PC(b),c.currentTarget,c,!0):0==this.Fj().length&&(this.jC(),this.Po(b,!this.PC(b),c.currentTarget,c,!0),this.Gj().iia(b,!0))},"dragstart .oj-table-column-header-cell":function(a){return this.Gj().BGa(a)},
"dragenter .oj-table-column-header-cell":function(a){return this.Gj().yGa(a)},"dragover .oj-table-column-header-cell":function(a){return this.Gj().AGa(a)},"dragleave .oj-table-column-header-cell":function(a){return this.Gj().zGa(a)},"drop .oj-table-column-header-cell":function(a){return this.Gj().CGa(a)},"dragend .oj-table-column-header-cell":function(){return this.Gj().xGa()},"dragstart .oj-table-body-row":function(a){return this.Gj().kHa(a)},"drag .oj-table-body-row":function(a){return this.Gj().fHa(a)},
"dragend .oj-table-body-row":function(a){return this.Gj().gHa(a)},"dragenter .oj-table-body":function(a){return this.Gj().hHa(a)},"dragover .oj-table-body":function(a){return this.Gj().jHa(a)},"dragleave .oj-table-body":function(a){return this.Gj().iHa(a)},"drop .oj-table-body":function(a){return this.Gj().lHa(a)}},Ira:{touchstart:function(c){if(1==c.originalEvent.touches.length&&this.oq()==this.wk.Nr)if(g(c.target).hasClass(a.f.J.TP)||g(c.target).hasClass(a.f.J.p2))c.preventDefault(),this.Pi=this.q().qfa().data("rowIdx");
else if(g(c.target).hasClass(a.f.J.SP)||g(c.target).hasClass(a.f.J.o2))c.preventDefault(),this.Pi=this.q().rfa().data("rowIdx")},touchmove:function(a){null!=this.Pi&&(a.preventDefault(),a=this.M7(a),this.IT(a))},touchend:function(a){null!=this.Pi&&(a=this.M7(a),this.IT(a));this.Pi=null},"touchend .oj-table-body":function(a){var b=g(a.target);null!=this.CU&&250>(new Date).getTime()-this.CU&&this.O9[0]==b[0]?(this.O9=this.CU=null,b=this.q().xe(g(b)),this.ai(!0,!1,b,!0,a),a.preventDefault()):(this.O9=
b,this.CU=(new Date).getTime())},touchcancel:function(){this.Pi=null}},Ff:function(){var a=null,b=!1;this.i!=this.options[this.Fm]&&(this.bR(),null==this.i?b=!0:a=0,this.Jj()&&(null!=this.MR&&this.MR.destroy(),this.raa()));this.C4!=this.q().Cea()&&this.q().Qda(this.Dk.bind(this));this.q().DEa();this.q().DIa();this.Xza();if(b)return this.gU();var d=this;this.Yh(function(){var b=d.gD(a);d=a=null;return b})},_setOption:function(a,b){this._superApply(arguments);this.Gxa(a,b)?this.Ff():"selection"==a?
(this.Yx(),this.jC(),this.mz(b)):"currentRow"==a&&this.mn(b,null,!0)},Ina:function(a){var b=!1,d;for(d in this.Tb)this.Tb.hasOwnProperty(d)&&this.Tb[d]==a&&(b=!0);if(b){b=this.Fj();d=!1;var e,f=b.length;for(e=0;e<f;e++)if(b[e]==a){d=!0;break}d||b.push(a)}},W2:function(a,b,d,e){var f=this.q().Sda(a,b[this.Op]);this.q().FZ(f,!0);this.q().ega(a,f,b,d);this.mK(a,b,f,d,e,!0)},XQ:function(a){var b=this.Xm(),d=this.jq();null==b&&null==d&&(this.OJ()?this.Ik(0,!0,!0,null,a):this.Oo(0,!0,!1,a))},jpa:function(){this.hs=
null;this.Uv(!1)},bR:function(){null!=this.i&&this.Uo();this.i=null},mo:function(){this.uwa();this.vwa();this.Y4=!1},lpa:function(){this.zU=[]},j4:function(){var a=this.jq();null!=a&&this.Oo(a,!1,!1,null);this.O2=-1},k4:function(a){null!=this.Xm()&&this.Ik(-1,!0,a,null,null)},jC:function(){var a=this.y7(),b,d=a.length;for(b=0;b<d;b++)this.Po(a[b],!1,null,null,!1)},Yx:function(){var a=this.Cy(),b,d=a.length;for(b=0;b<d;b++)this.Oj(a[b],!1,null,null,!1);this.QJ()&&this.oq()==this.wk.Nr&&this.q().NIa()},
m4:function(c){var b=this.Sta();if(null!=b){var d=this.q().Wd(b),e=d.data("sorted");d.data("sorted",null);b!=c?e==this.Ii.wu?this.wv(b,!0):this.wv(b,!1):(d.find("."+a.f.J.yu).removeClass(a.f.Da.Te),d.find("."+a.f.J.ux).removeClass(a.f.Da.Te))}},Jra:function(c){var b=this;this.Yh(function(){var d=!1;if(1<c.length){var e,f=c.length,h=!0;for(e=0;e<f;e++)if(0!=e&&c[e-1].ak!=c[e].ak-1){h=!1;break}if(h){d=b.q().ze();h=g(document.createDocumentFragment());f=c.length;for(e=0;e<f;e++)b.W2(c[e].ak,c[e].row,
h,c[0].ak);0==c[0].ak?d.prepend(h):(e=b.q().Ae(c[0].ak),null!=e?d[0].insertBefore(h[0],e[0]):d[0].insertBefore(h[0],null));b.q().jt();a.Components.Tg(d[0]);d=!0}}if(!d)for(f=c.length,e=0;e<f;e++)b.W2(c[e].ak,c[e].row);b.q().jt();b.VD();b=null})},Kra:function(a){var b=this;this.Yh(function(){var d,e=a.length;for(d=0;d<e;d++)b.mK(a[d].ak,a[d].row);b.VD();b=null})},Lra:function(c){var b=this,d=this.LC(),e=null!=d?d.rowKey:null;this.Yh(function(){var d=[],g,k,l=c.length,m=!1;k=b.q().$e();if(null!=k&&
0<k.length){for(g=0;g<k.length;g++)d.push(g);for(g=0;g<l;g++)for(k=0;k<d.length;k++)if(d[k]==c[g].ak){d.splice(k,1);break}0==d.length&&(m=!0)}if(m)b.q().Fha();else for(g=0;g<l;g++)b.q().Kha(c[g].ak);if(null!=e)for(g=0;g<l;g++)if(d=c[g].row[b.Op],a.b.Rj(d,e)){b.mn(null,null,!1);break}b.VD();k=b.q().$e();null!=k&&0!=k.length||b.WV();b.XQ(null);b=null})},gc:function(){this.hs||(this.hs=this.t6());return this.hs},t6:function(){var a=this.options.columns,b=this.options.columnsDefault;if((0==a.length||
1==a.length&&null==a[0].id&&null==a[0].headerText&&null==a[0].field)&&null==b.headerText&&null==b.field)return[];var d=[],e,f=a.length;for(e=0;e<f;e++)d[e]=g.extend({},b,a[e]);a=[];b=d.length;for(e=0;e<b;e++)a.push(d[e]);e=this.Lb();d=!1;null!=e&&"full"==e.getCapability("sort")&&(d=!0);for(e=0;e<b;e++)null==a[e][this.fP]&&(a[e][this.fP]=this.Dka+e),null!=a[e].sortable&&a[e].sortable!=this.VG||!d||(a[e].sortable=this.uj);return a},r6:function(c){var b=this.gc();if(null!=b){var d,e,f=b.length;for(d=
0;d<f;d++)if(e=b[d],a.b.Rj(e.id,c))return d}return null},s6:function(a){a=this.q().yd().find(a);var b=[];if(a&&0<a.length){var d,e,f,h,k,l=a.length;for(d=0;d<l;d++){h=this.q().xe(g(a.get(d)));f=!1;k=b.length;for(e=0;e<k;e++)b[e]==h&&(f=!0);f||b.push(h)}}return b},DI:function(a){var b=this.gc();return null!=b&&a<b.length?b[a][this.fP]:null},qs:function(a,b){var d=this.gc()[a];return"cell"==b?d.renderer:"footer"==b?d.footerRenderer:"header"==b?d.headerRenderer:null},LC:function(){return this.Lb()?this.fq:
null},Lb:function(){if(!this.i&&null!=this.options.data){var c=this.options.data;if(c instanceof a.aa||c instanceof a.Fa)this.i=c;else throw Error(this.od.X0+"\n"+this.od.W0);this.Ov()}return this.i},jq:function(){return this.s6("."+a.f.J.Kr+"."+a.f.Da.Hm)[0]},Xm:function(){return this.v7("."+a.f.J.Wr+"."+a.f.Da.Hm)[0]},DKa:function(a){return this.DS(a).Sl},PC:function(a){return this.DS(a).selected},EI:function(){return null==this.options.selectionMode?null:this.options.selectionMode[this.Uf]},DS:function(c){c=
this.q().Wd(c);return{Sl:c.hasClass(a.f.Da.Hm),selected:c.hasClass(a.f.Da.Te)}},Fj:function(){this.zU||(this.zU=[]);return this.zU.reverse()},ita:function(){return null!=this.Ks&&0<this.Ks.length?this.Ks[0]:null},jta:function(){return null!=this.Ls&&0<this.Ls.length?this.Ls[0]:null},Mta:function(a,b){var d=[];if(null!=a){var e,f=a[this.tB].length;for(e=0;e<f;e++)d.push({row:{data:a[this.Fm][e],key:a[this.vx][e],index:a[this.tB][e]},ak:b+e})}return d},Ay:function(c){var b=this.q().$e();if(null!=b&&
0<b.length){var d,e=b.length;for(d=0;d<e;d++)if(a.b.Rj(g(b[d]).data("rowKey"),c))return d}return null},gv:function(c){var b=this.q().$e();if(null!=b&&0<b.length){var d,e=b.length;for(d=0;d<e;d++)if(a.b.Rj(g(b[d]).data("rowKey"),c))return c=this.Lb(),b=0,c instanceof a.Fa&&(b=c.getStartItemIndex()),d+b}return null},Wm:function(){var a=null;return null!=this.mI&&(a=this.Ay(this.mI),null!==a)?a:this.Cra},BKa:function(){return this.mI},v7:function(a){a=this.q().yd().find(a);var b=[];if(a&&0<a.length){var d,
e,f,h,k,l=a.length;for(d=0;d<l;d++){f=this.q().Qq(g(a.get(d)));k=!1;h=b.length;for(e=0;e<h;e++)b[e]==f&&(k=!0);k||b.push(f)}}return b},UC:function(c){var b=this.q().$e();if(null!=b&&0<b.length){var d=this.Lb(),e=0;d instanceof a.Fa&&(e=d.getStartItemIndex());for(var f=b.length,d=0;d<f;d++)if(e+d==c)return g(b[d]).data("rowKey")}return null},Ao:function(a){a=this.q().Ae(a);return null!=a?a.data("rowKey"):null},w7:function(){return this.options.rowRenderer},By:function(c){return this.q().Ae(c).hasClass(a.f.Da.Te)},
oq:function(){return null==this.options.selectionMode?null:this.options.selectionMode[this.Vf]},y7:function(){return this.s6("."+a.f.J.Kr+"."+a.f.Da.Te)},Cy:function(){return this.v7("."+a.f.J.Wr+"."+a.f.Da.Te)},z7:function(){var a=this.Cy(),b=this.y7(),d=null,e=!0;if(null!=a&&0<a.length)d=a;else if(null!=b&&0<b.length)d=b,e=!1;else return null;var a=[],b=0,f=null,g,k,l,m,s,t=d.length;for(s=0;s<t;s++)l=d[s],0==s?(g={},g[this.yg]={},g[this.fh]={},g.startKey={},g.endKey={},e?(m=this.Ao(l),k=this.gv(m),
g.startKey[this.Vf]=m,g.endKey[this.Vf]=m,g[this.yg][this.Vf]=k,g[this.fh][this.Vf]=k):(g[this.yg][this.Uf]=l,g[this.fh][this.Uf]=l,m=this.DI(l),g.startKey[this.Uf]=m,g.endKey[this.Uf]=m),a[0]=g):(g=a[b],e?(m=this.Ao(l),k=this.gv(m),g.endKey[this.Vf]=m,g[this.fh][this.Vf]=k):(g[this.fh][this.Uf]=l,m=this.DI(l),g.endKey[this.Uf]=m),l!=f+1&&(e?(m=this.Ao(f),k=this.gv(m),g.endKey[this.Vf]=m,g[this.fh][this.Vf]=k,g={},g[this.yg]={},g[this.fh]={},g.startKey={},g.endKey={},m=this.Ao(l),k=this.gv(m),g.startKey[this.Vf]=
m,g.endKey[this.Vf]=m,g[this.yg][this.Vf]=k,g[this.fh][this.Vf]=k):(g[this.fh][this.Uf]=f,m=this.DI(f),g.endKey[this.Uf]=m,g={},g[this.yg]={},g[this.fh]={},g.startKey={},g.endKey={},g[this.yg][this.Uf]=l,g[this.fh][this.Uf]=l,m=this.DI(l),g.startKey[this.Uf]=m,g.endKey[this.Uf]=m),b++,a[b]=g)),f=l;return a},Sta:function(){var a=this.q().aA(),b,d,e=a.length;for(b=0;b<e;b++)if(d=g(a[b]).data("sorted"),null!=d)return b;return null},VC:function(a){a=a.find(":tabbable");return null!=a&&0<a.length?a:null},
Gj:function(){this.uca||(this.uca=new a.Qb(this));return this.uca},q:function(){this.cW||(this.cW=new a.f(this));return this.cW},M7:function(a){a=a.originalEvent.changedTouches[0];return g(document.elementFromPoint(a.clientX,a.clientY))},Dk:function(a,b){var d=b.item.attr("data-oj-command"),e=this.q().qt(g(this.Pm.target),"oj-table-column-header-cell"),f=this.q().qt(g(this.Pm.target),"oj-table-data-cell"),h=null;null!=e&&(h=this.q().xe(e));null!=f&&(h=this.q().xe(f));"oj-table-sortAsc"==d?this.El(h,
!0,a):"oj-table-sortDsc"==d?this.El(h,!1,a):"oj-table-enableNonContiguousSelection"==d?(this.r$=!0,b.item.attr("data-oj-command","oj-table-disableNonContiguousSelection"),b.item.children().first().text(this.F("labelDisableNonContiguousSelection"))):"oj-table-disableNonContiguousSelection"==d&&(this.r$=!1,b.item.attr("data-oj-command","oj-table-enableNonContiguousSelection"),b.item.children().first().text(this.F("labelEnableNonContiguousSelection")))},Bua:function(c){this.mo();a.r.error(c)},Cua:function(){this.vba()},
tT:function(c){try{var b=this;this.Yh(function(){var d=0,f=b.Lb();f instanceof a.Fa&&(d=f.getStartItemIndex());var f=[],g,k=c[b.Fm].length;for(g=0;g<k;g++)f[g]=g+d+c[b.yg];b.aaa({data:c[b.Fm],keys:c[b.vx],indexes:f},c[b.yg]);b=null})}catch(d){a.r.error(d)}finally{this.mo()}},lJ:function(){try{var c=this.gD(),b=this;this.Yh(function(){b.mn(null,null,!1);b=null;return c})}catch(d){a.r.error(d)}finally{this.mo()}},As:function(){try{this.gU();var c=this;this.Yh(function(){c.mn(null,null,!1);c=null})}catch(b){a.r.error(b)}finally{this.mo()}},
uT:function(c){try{var b=this.Lb(),d=c[this.Fm],e=c[this.tB],f=c[this.vx];d instanceof Array||(d=[d]);c=0;b instanceof a.Fa&&(c=b.getStartItemIndex());var b=[],g,k=d.length;for(g=0;g<k;g++){var l=e[g]-c;void 0!==l&&b.push({row:{data:d[g],key:f[g],index:e[g]},ak:l})}0<b.length&&this.Jra(b)}catch(m){a.r.error(m)}finally{this.mo()}},Eua:function(c){try{var b=this.Lb(),d=c[this.Fm],e=c[this.tB],f=c[this.vx];d instanceof Array||(d=[d]);c=0;b instanceof a.Fa&&(c=b.getStartItemIndex());var b=[],g,k=d.length;
for(g=0;g<k;g++){var l=e[g]-c;void 0!==l&&b.push({row:{data:d[g],key:f[g],index:e[g]},ak:l})}0<b.length&&this.Kra(b)}catch(m){a.r.error(m)}finally{this.mo()}},vT:function(c){try{var b=this.Lb(),d=c[this.Fm],e=c[this.tB],f=c[this.vx];d instanceof Array||(d=[d]);c=0;b instanceof a.Fa&&(c=b.getStartItemIndex());var b=[],g;for(g=d.length-1;0<=g;g--){var k=e[g]-c;void 0!==k&&b.push({row:{data:d[g],key:f[g],index:e[g]},ak:k})}0<b.length&&this.Lra(b)}catch(l){a.r.error(l)}finally{this.mo()}},wT:function(c){try{var b;
if(null!=c){var d=this.gc(),e,f,g,k=d.length;for(e=0;e<k;e++)if(f=d[e],g=null==f.sortProperty?f.field:f.sortProperty,c.header==g){b=e;break}null!=b&&this.jaa(b,c.direction==this.Ii.wu)}var l=this.options.selection;if(null!=l){c=!1;if(1<l.length)c=!0;else if(null!=l[0]){var m=l[0][this.fh];a.b.Rj(l[0][this.yg],m)||null==m||(c=!0)}c&&(this.mz(null),this.option("selection",null,{_context:{Ed:!0,ob:!0}}))}this.mn(this.options.currentRow,null,!1);var s=this;this.Yh(function(){return s.Jj()?s.gD(0,null):
s.gD(null)}).then(function(){null!=b&&setTimeout(function(){s.cba(b);b=s=null},0)})}catch(t){a.r.error(t)}finally{this.mo()}},ova:function(a){var b=this.jq(),d=this.gc();if(null!=b){var e=b;this.Uh(this.Tb.r1)?e=0<b?b-1:b:this.Uh(this.Tb.s1)&&(e=b<d.length-1?b+1:b);e!=b&&(this.Oo(e,!0,!1,null),a[this.Tb.Im]&&(d=this.PC(e),this.Po(e,!d,null,a,!0),d&&this.PC(b)&&this.Po(b,!1,null,a,!0)))}},pva:function(a){var b=!1,d=this.Xm();if(null!=d&&this.dW){var e=document.activeElement,f=this.q().ze();if(this.Wm()===
d){var h=this.q().Ae(d),h=this.VC(h),k=null!=h?h.length:0,e=h.index(e);if(e!=k-1||a[this.Tb.Im])if(0==e&&a[this.Tb.Im])e=this.q().aA().length,this.Gba(e-1,a);else return;else this.Cba(0,a)}else if(g.contains(f[0],e))return;f=this.VC(f);null==f||a[this.Tb.Im]||(b=!0,h=this.q().Ae(d),h=this.VC(h),null!=h?g(h[0]).focus():g(f[0]).focus(),a.preventDefault(),a.stopPropagation())}if(!b){f=this.q().yd();b=this.VC(g(document));d=b.length;f=this.VC(f);e=null!=f?f.length:0;h=b.index(this.q().yd());if(a[this.Tb.Im])if(0<=
h){if(0==h)return;g(b[h-1]).focus()}else return;else if(h!=d-1&&h+e+1<=d-1)g(b[h+e+1]).focus();else{if(0<e){this.Dca=!0;f[e-1].focus();var l=this;setTimeout(function(){l.Dca=!1},0)}return}a.preventDefault();a.stopPropagation()}this.qK(a.keyCode)},qva:function(a){var b=this.Xm(),d=this.jq();if(null!=b){var d=this.q().$e(),e=null!=d?d.length:0,d=b;this.Uh(this.Tb.RG)?d=0<b?b-1:b:this.Uh(this.Tb.PG)&&(d=b<e-1?b+1:b);d!=b?this.Ik(d,!0,!0,null,a)&&a[this.Tb.Im]&&(e=this.By(d),this.Oj(d,!e,null,a,!0),e&&
this.By(b)&&this.Oj(b,!1,null,a,!0)):d==b&&0==b&&this.Uh(this.Tb.RG)&&this.Oo(0,!0,!1,null)}else null!=d&&this.Uh(this.Tb.PG)&&this.Ik(0,!0,!0,null,a)},rva:function(a){var b=this.jq();if(null!=b&&b!=this.gc().length-1)this.Oo(this.gc().length-1,!0,!1,null);else{var b=this.Xm(),d=this.q().$e(),d=null!=d?d.length:0;null!=b&&b!=d-1&&0<d&&this.Ik(d-1,!0,!0,null,a)}},sva:function(a){var b=this.jq();if(null!=b&&this.gc()[b].sortable==this.uj){var d=this.q().Wd(b).data("sorted");null==d||d==this.Ii.Lr?this.El(b,
!0,a):this.El(b,!1,a)}else b=(b=this.LC())||{},0<=b.rowIndex&&(this.q().$e(),this.uv()?(b=this.q().xe(g(a.target)),a[this.Tb.Im]?this.Gba(b,a):this.Cba(b,a)):this.ai(!0,!1,0,!0,a))},tva:function(a){a.preventDefault();a.stopPropagation();this.ai(!1,!0,0,!0,a);this.q().yd().focus();this.Uv(!1)},uva:function(a){a.preventDefault();a.stopPropagation();this.uv()?this.ai(!1,!1,0,!0,a):this.ai(!0,!1,0,!0,a);this.q().yd().focus();this.Uv(!1)},vva:function(a){var b=this.jq();null!=b&&0!=b?this.Oo(0,!0,!1,null):
(b=this.Xm(),null!=b&&0!=b&&this.Ik(0,!0,!0,null,a))},wva:function(a){var b=this.Xm();null!=b?this.Oj(b,!this.By(b),null,a,!0):(b=this.jq(),null!=b&&(this.Yx(),this.Po(b,!this.PC(b),null,a,!0)))},IT:function(a){var b=this.q().Qq(g(a));if(null!=b&&null!=this.Pi&&this.Pi!=b){var d=this.Pi,e=this.Cy();if(b<d){var f;for(f=0;f<e.length;f++)(e[f]<b||e[f]>d)&&this.Oj(e[f],!1,a,null,!0);for(f=d;f>=b;f--)this.Oj(f,!0,a,null,!0),this.q().cha(f)}else{for(f=0;f<e.length;f++)(e[f]>b||e[f]<d)&&this.Oj(e[f],!1,
a,null,!0);for(f=d;f<=b;f++)this.Oj(f,!0,a,null,!0),this.q().bha(f)}}},MT:function(){this.yCa(this.od.Zka,this.od.Yka,a.ia.Xc.WARNING)},$va:function(c){var b=this.q().Uq(),d=this.q().mp();this.q().pp()?(b&&("rtl"===this.hd()?b.css(a.f.O.cH,"-"+c+a.f.na.nc):b.css(a.f.O.bo,"-"+c+a.f.na.nc)),d&&("rtl"===this.hd()?d.css(a.f.O.cH,"-"+c+a.f.na.nc):d.css(a.f.O.bo,"-"+c+a.f.na.nc))):((b=this.q().pw())&&("rtl"===this.hd()?b.css(a.f.O.cH,"-"+c+a.f.na.nc):b.css(a.f.O.bo,"-"+c+a.f.na.nc)),(b=this.q().$z())&&
("rtl"===this.hd()?b.css(a.f.O.cH,"-"+c+a.f.na.nc):b.css(a.f.O.bo,"-"+c+a.f.na.nc)))},El:function(a,b,d){this.m4(a);var e=this.gc()[a];this.jxa(null==e.sortProperty?e.field:e.sortProperty,b,d);this.gca=e;this.jaa(a,b)},uv:function(){var a=this.options.editMode;return null==a||a==this.BB.sl?!1:null!==this.Wm()},z8:function(a){if(null!=this.w7())return!0;var b=null;if(null!=a)b=this.qs(a,"cell");else{var d=this.gc().length;for(a=0;a<d&&(b=this.qs(a,"cell"),null==b);a++);}return null!=b?!0:!1},uwa:function(){var c=
this.q().$X();if(c.css(a.f.O.hf)!=a.f.na.sl){var b=c.outerHeight(),d=this.q().zd(),e=parseInt(d.css(a.f.O.A0),10),f=parseInt(d.css(a.f.O.TG),10);d.css(a.f.O.TG,f-e-b+a.f.na.nc);d.removeClass(a.f.Da.mH);c.removeClass(a.f.Da.mH);c.css(a.f.O.SO,"");c.css(a.f.O.hf,a.f.na.sl)}},vJ:function(){var a=this.q().vfa();null!=a&&a.remove()},vwa:function(){this.q().YE().css(a.f.O.hf,a.f.na.sl)},wv:function(c,b){if(this.gc()[c].sortable==this.uj){var d=this.q().Wd(c),e=d.data("sorted");!b||null!=e&&e!=this.Ii.Lr?
b||null!=e&&e!=this.Ii.wu||(d=d.find("."+a.f.J.ux),d.addClass(a.f.Da.ec),d.removeClass(a.f.Da.Jh),d.removeClass(a.f.Da.Te)):(d=d.find("."+a.f.J.yu),d.addClass(a.f.Da.ec),d.removeClass(a.f.Da.Jh),d.removeClass(a.f.Da.Te))}},gU:function(){var c=this,b=this.Lb();null!=b&&b instanceof a.aa&&!(b instanceof a.Fa)?(this.q().ye()[0].scrollTop=0,this.Yh(function(){var a=c.gD(0,{fetchType:"init"});c=null;return a})):null==b&&this.Yh(function(){return Promise.resolve()})},gD:function(c,b){b=b||{};b[this.yg]=
c;!b[this.I0]&&this.Jj()&&(b[this.I0]=this.options.scrollPolicyOptions.fetchSize);b.silent=!0;var d="init"==b.fetchType?!0:!1,e=this.Lb(),f=this;return new Promise(function(c,g){null!=e?(f.vba(),e.fetch(b).then(function(b){if(null!=b&&null!=b[f.Fm]){var g=0;e instanceof a.Fa&&(g=e.getStartItemIndex());var k=[],t,r=b[f.Fm].length;for(t=0;t<r;t++)k[t]=t+g+b[f.yg];f.aaa({data:b[f.Fm],keys:b[f.vx],indexes:k},b[f.yg],d,d)}f.mo();f=null;c(null)},function(a){f.mo();f=null;g(a)})):c(null)})},jxa:function(a,
b,d){var e=this.Lb();if(!e)return null;this.aca();var f={};f[this.Op]=a;f.direction=b?this.Ii.wu:this.Ii.Lr;this._trigger("sort",d,{header:f[this.Op],direction:f.direction});e.sort(f)},oxa:function(){if(null!=this.hs){var a=this.t6();if(this.hs.length!=a.length)return!0;var b,d,e=a.length;for(b=0;b<e;b++)for(d in a[b])if(a[b].hasOwnProperty(d)&&a[b][d]!=this.hs[b][d])return!0;return!1}return!0},Uh:function(a){var b=this.Fj(),d,e=b.length;for(d=0;d<e;d++)if(b[d]==a)return!0;return!1},Jj:function(){return this.options.scrollPolicy==
this.Xla.Gla?!0:!1},sU:function(a){return this.v9(a,/^INPUT|TEXTAREA/)},zxa:function(a){return this.v9(a,/SELECT|OPTION|BUTTON|^A\b/)},Axa:function(a){return 0<a.closest("[draggable\x3d'true']").length},v9:function(c,b){for(var d,e=this.q().yd();null!=c&&c[0]!=e[0]&&"TD"!=(d=c.prop("nodeName"))&&"TH"!=d;)if(3==c[0].nodeType)c=c[0].parentNode;else{var f=c.attr(a.f.Gb.Vr);if(d.match(b)&&-1!=f)return!0;c=c.parentNode}return!1},F9:function(){var a,b,d=this.gc().length;for(a=0;a<d;a++)if(b=this.qs(a,"footer"),
null!=b)return!1;return!0},OJ:function(){var a=this.gc(),b,d=a.length;for(b=0;b<d;b++)if(null!=a[b].headerText||null!=a[b].headerStyle||null!=a[b].sortable&&a[b].sortable!=this.N1||null!=a[b].sortProperty||null!=a[b].headerRenderer)return!1;return!0},Fxa:function(){return!0==this.LAa},VKa:function(){return this.dW},Gxa:function(c,b){var d=this.J3,e=!1;"contextMenu"==c&&b=="#"+this.q().xn()+"_contextmenu"?e=!1:"selection"==c||"currentRow"==c||a.b.Rj(b,d[c])||(e=!0);this.J3=g.extend(!0,{},this.options);
return e},G9:function(){var a=this.gc(),b,d=a.length;for(b=0;b<d;b++)if(null!=a[b].sortable&&a[b].sortable!=this.N1)return!0;return!1},QJ:function(){if(void 0==this.Ry){var a=navigator.userAgent.toLowerCase();-1!=a.indexOf("mobile")||-1!=a.indexOf("android")?this.Ry=!0:this.Ry=!1}return this.Ry},aaa:function(c,b,d,e){if(this.oxa()||!this.Fxa()&&!this.OJ())if(this.jpa(),this.laa(),null!=this.gca){var f,g,k=!1,l=this.gc();if(null!=l){var m=l.length;for(f=0;f<m;f++)if(g=l[f],a.b.Rj(g,this.gca)){k=!0;
break}k||this.Lb().sort(null)}}this.VD();this.kaa(c,b,d,e)},jaa:function(c,b){this.m4(c);var d=this.q().Wd(c),e=d.data("sorted");b&&e!=this.Ii.wu?(d.data("sorted",this.Ii.wu),e=d.find("."+a.f.J.yu),e.addClass(a.f.Da.Jh),e.removeClass(a.f.Da.ec),e=d.find("."+a.f.J.yG),e.removeClass(a.f.Da.ec),e=d.find("."+a.f.J.CG),e.addClass(a.f.Da.ec),this.wv(c,!b)):b||e==this.Ii.Lr||(d.data("sorted",this.Ii.Lr),e=d.find("."+a.f.J.ux),e.addClass(a.f.Da.Jh),e.removeClass(a.f.Da.ec),e=d.find("."+a.f.J.CG),e.removeClass(a.f.Da.ec),
e=d.find("."+a.f.J.yG),e.addClass(a.f.Da.ec))},kaa:function(c,b,d,e){var f=this.q().ze();if(null!=f){c=this.Mta(c,b);var h;if(0==b)this.q().Fha();else if(h=f.children(),null!=h&&0<h.length)for(h=h.length-1;h>=b;h--)this.q().Kha(h);this.q().jt();this.vJ();h=f.children();if(0!=c.length||null!=h&&0!=h.length){var k=g(document.createDocumentFragment()),l,m,s,t=c.length;for(h=0;h<t;h++)l=c[h].row,m=c[h].ak,null!=l&&(s=this.q().Sda(m,l[this.Op]),this.q().FZ(s,!0),this.q().ega(m,s,l,k),this.mK(m,l,s,k,b,
!0));f.append(k);this.z8()&&(this.q().qN(null,null,d,e),a.Components.Tg(f[0]))}else this.WV()}},mK:function(c,b,d,e,f,h){var k=this.w7();this.gc();var l=this.q().ze();(isNaN(c)||0>c)&&a.r.error("Error: Invalid rowIdx value: "+c);var m=this.q().rw(b[this.Op]);if(null==d)if(d=this.q().Ae(c))d.empty(),h=!0,this.q().nX(c,b[this.Op],m,d,h);else return;this.vJ();h=(h=this.LC())||{};h={rowContext:a.eh.Xz(this,d[0],{row:b,isCurrentRow:h.rowIndex==c}),row:b[this.Fm]};if(k){k=k(h);null!=k?d.append(k):(null==
e?d=g(l.children()[c]):(f=null==f?0:f,d=g(e.children()[c-f])),this.q().jt(),this.q().zZ(b,d),this.q().FZ(d,!1));this.q().nX(c,b[this.Op],m,d,!1);f=d.children(a.f.Pa.Wp);l=f.length;for(e=1;e<l;e++)k=g(f[e]),this.q().yZ(c,b[this.Op],m,e-1,k),this.q().EZ(e-1,k,!1);if(null!=this.po)for(e=0;e<this.po.length-1;e++)this.po[e]>e&&(c=g(f[this.po[e]+1]),b=g(f[e+1]),c[0].parentNode.insertBefore(c[0],b[0]),f=d.children(a.f.Pa.Wp))}else a.eh.zJa(this,c,b,h)},VD:function(){var c=this.gc(),b=this.q().mp();if(!b){if(this.F9())return;
b=this.q().Tda();this.q().tia(b)}b=this.q().$z();b.empty();if(c&&0<c.length){this.q().Uda(b);for(var d,e,f=c.length,c=0;c<f;c++)d=this.qs(c,"footer"),e=this.q().XEa(),this.q().uia(c,e),this.q().wHa(c,e),d&&(d=d({footerContext:a.eh.Xz(this,e[0],{}),columnIndex:c}),null!=d?(e.empty(),e.append(d)):(e=g(b.children(":not(."+a.f.J.ol+")")[c]),this.q().uia(c,e)))}},laa:function(){var c=this,b=this.gc(),d=this.q().Uq();if(!d){if(this.OJ())return;d=this.q().Vda();this.q().via(d)}d=this.q().pw();this.EW(d);
d.empty();if(b&&0<b.length){var e=this.q().YEa();d.append(e);for(var f,h,k,l,m=b.length,e=0;e<m;e++)f=b[e],h=this.qs(e,"header"),k=this.q().ZEa(e),h&&(l=a.eh.Xz(this,k[0],{}),l={headerContext:l,columnIndex:e,data:f.headerText},f.sortable==a.f.uj?l.columnHeaderSortableIconRenderer=function(b,d){a.eh.Hda(c,this,d)}:l.columnHeaderDefaultRenderer=function(b,d){a.eh.Fda(c,this,d)},f=h(l),null!=f?(k.empty(),k.append(f)):(k=g(d.children(":not(."+a.f.J.VO+")")[e]),this.q().hia(e,k),this.q().wia(e,k,!1))),
this.q().$Ea(e,this.EI());this.LAa=!0}},Xza:function(){var a=this.q().YE();null!=a&&a.remove();this.q().Wda()},$za:function(){var a=g.event.special;a.ojtablebeforecurrentrow={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}};a.ojtablesort={handle:function(a,c){return a.handleObj.handler.apply(this,[a,c])}}},Ov:function(){var c=this.Lb();if(null!=c){this.Uo();this.Cb=[];this.Cb.push({eventType:a.aa.Q.REQUEST,eventHandler:this.Cua.bind(this)});this.Cb.push({eventType:a.aa.Q.SYNC,eventHandler:this.tT.bind(this)});
this.Cb.push({eventType:a.aa.Q.SORT,eventHandler:this.wT.bind(this)});this.Cb.push({eventType:a.aa.Q.ADD,eventHandler:this.uT.bind(this)});this.Cb.push({eventType:a.aa.Q.REMOVE,eventHandler:this.vT.bind(this)});this.Cb.push({eventType:a.aa.Q.CHANGE,eventHandler:this.Eua.bind(this)});this.Cb.push({eventType:a.aa.Q.REFRESH,eventHandler:this.lJ.bind(this)});this.Cb.push({eventType:a.aa.Q.RESET,eventHandler:this.As.bind(this)});this.Cb.push({eventType:a.aa.Q.ERROR,eventHandler:this.Bua.bind(this)});var b,
d,e=this.Cb.length;for(b=0;b<e;b++)(d=c.on(this.Cb[b].eventType,this.Cb[b].eventHandler))&&(this.Cb[b].eventHandler=d)}},aAa:function(){null!=this.q().ye()&&this.q().ye().scroll(function(a){this.$va(this.q().gfa(a.target))}.bind(this))},raa:function(){var c=this;this.x5=function(a){null!=a&&a.maxCountLimit&&c.MT()};this.MR=new a.Sf(this.q().ye(),this.Lb(),{fetchSize:this.options.scrollPolicyOptions.fetchSize,maxCount:this.options.scrollPolicyOptions.maxCount,success:this.x5})},jn:function(){var c=
this.q().zd();if(!this.Ll){var b=this;this.Ll=function(){var a=b.q().zd().outerHeight(),c=b.q().zd().outerWidth();b.q().qN(c,a)}}this.LJ||(a.u.Mk(c[0],this.Ll,50),this.LJ=!0)},qK:function(a){var b=this.Fj(),d,e=b.length;for(d=0;d<e;d++)b[d]==a&&b.splice(d,1)},cba:function(a){var b="rtl"===this.hd(),d=this.q().ze(),e=this.q().Wd(a);if(e){a=this.q().jfa();var e=e.get(0).getBoundingClientRect(),f=d.get(0).getBoundingClientRect(),g=!1;b?(e.left<f.left+a&&(b=f.left-e.left+a,this.q().FJ()||(b*=-1),d.scrollLeft(d.scrollLeft()+
b),g=!0),e.right>f.right&&!g&&(b=e.right-f.right,this.q().FJ()||(b*=-1),d.scrollLeft(d.scrollLeft()-b))):(e.left<f.left&&(b=f.left-e.left,d.scrollLeft(d.scrollLeft()-b),g=!0),e.right>f.right-a&&!g&&(b=e.right-f.right+a,d.scrollLeft(d.scrollLeft()+b)))}},CV:function(a){var b=this.q().Ae(a);a=this.q().dGa();var b=b.get(0).getBoundingClientRect(),d=this.q().ye(),e=d.get(0).getBoundingClientRect(),f=!1;b.bottom>e.bottom-a&&(a=b.bottom-e.bottom+a,d.scrollTop(d.scrollTop()+a),f=!0);b.top<e.top&&!f&&(a=
e.top-b.top,d.scrollTop(d.scrollTop()-a))},mn:function(c,b,d){var e=this.fq,f,g;f=!0;if(null==c){if(null!=e){try{f=this._trigger("beforeCurrentRow",b,{currentRow:null,previousCurrentRow:this.fq})}catch(k){c=this.od.Z0;var l=a.va.Lc(this.od.Y0,{error:k.toString()});a.r.info(c+"\n"+l);return!1}if(!f)return!1;this.fq=null;f=e.rowIndex;f=this.UC(f);g=this.Ay(f);f=this.ai(!1,!1,0,!0,b);if(!1===f){this.fq=e;var l=document.activeElement,m=this.q().xe(l),s=this;this.Yh(function(){var a=g,b=m;setTimeout(function(){s.zK(a,
b)},0)});return!1}this.option("currentRow",null,{_context:{Ed:!0,originalEvent:b,ob:!0}});null==b&&this.Ik(-1,!0,!1,null,b);f=this.q().Ae(g);null!=f&&f.removeClass(a.f.J.QP)}return!0}var t=this.Lb(),r=c.rowIndex,n=c.rowKey;null==n&&(n=this.UC(r));null==r&&(r=this.gv(n));l=this.Ay(n);c={rowIndex:r,rowKey:n};if(-1!=l&&(!t||0==t.totalSize()||-1>l||null===l||null===n)){c=this.od.Xka;l=a.va.Lc(this.od.Wka,{rowIdx:l});if(d)throw Error(c+"\n"+l);a.r.info(c+"\n"+l);return!1}d=this.Xm();if(t=!a.b.Rj(this.fq,
c)){try{f=this._trigger("beforeCurrentRow",b,{currentRow:{rowIndex:r,rowKey:n},previousCurrentRow:this.fq})}catch(p){return c=this.od.Z0,l=a.va.Lc(this.od.Y0,{error:p.toString()}),a.r.info(c+"\n"+l),!1}if(!f)return!1;this.fq={rowIndex:r,rowKey:n};null!=e&&(f=e.rowIndex,f=this.UC(f),g=this.Ay(f));f=this.ai(!1,!1,0,!0,b);if(!1===f)return this.fq=e,l=document.activeElement,m=this.q().xe(l),s=this,this.Yh(function(){var a=g,b=m;setTimeout(function(){s.zK(a,b)},0)}),!1;this.option("currentRow",this.fq,
{_context:{Ed:!0,originalEvent:b,ob:!0}});f=this.q().Ae(l);null!=f&&f.addClass(a.f.J.QP);null!=e&&(f=this.q().Ae(g),null!=f&&f.removeClass(a.f.J.QP))}(t||d!=c.rowIndex)&&null==b&&this.Ik(l,!0,!1,null,b);return!0},vba:function(){this.aca();this.vJ();this.Y4=!0},zK:function(a,b){var d=!1;this.q().tt(a,b).find("*").each(function(){!d&&g(this).is(":focusable")&&(this.focus(),d=g(this).is(":focus"))});return d},vBa:function(a,b,d){if(!this.zK(a,b)&&(b=this.q().gM(a))){var e,f=b.length;for(b=0;b<f&&(e=
b,d||(e=f-b-1),!this.zK(a,e));b++);}},KV:function(a){this.mI=this.Ao(a);this.Cra=a},Oo:function(a,b,d,e){var f=null;null!=e&&(f=e.currentTarget);if(b){var g=this.jq();null!=g&&g!=a&&this.Oo(g,!1,!1,e);this.k4(!0);d&&this.Yx();this.cba(a);this.O2=a}this.xba(a,{Sl:b},f)},Po:function(c,b,d,e,f){if(this.EI()==this.wk.Mx||this.EI()==this.wk.Nr)(isNaN(c)||0>c)&&a.r.error("Error: Invalid column selection value: "+c),this.EI()==this.wk.Mx&&b&&this.jC(),this.xba(c,{selected:b},d,e),this.RBa(c,b),c=this.q().ufa(c),
g(c.children("."+a.f.J.C0)[0]).prop("checked",b),f&&(b=this.z7(),this.option("selection",b,{_context:{Ed:!0,ob:!0}}))},xba:function(c,b){var d=this.q().Wd(c);if(d){var e=b.Sl,f=b.selected;null!=f&&d.hasClass(a.f.Da.Te)!=f&&(f?d.addClass(a.f.Da.Te):d.removeClass(a.f.Da.Te));null!=e&&(e?(d.addClass(a.f.Da.Hm),this.bca(c)):(d.removeClass(a.f.Da.Hm),this.wv(c,!0),this.wv(c,!1)));this.ADa(c)}},RBa:function(a,b){this.Ks||(this.Ks=[]);var d,e=this.Ks.length;for(d=0;d<e;d++)if(this.Ks[d]==a){this.Ks.splice(d,
1);break}b&&this.Ks.push(a)},TBa:function(a,b){this.Ls||(this.Ls=[]);var d,e=this.Ls.length;for(d=0;d<e;d++)if(this.Ls[d]==a){this.Ls.splice(d,1);break}b&&this.Ls.push(a)},Cba:function(a,b){var d=this.q().$e(),d=null!=d?d.length:0,e=this.Wm();0<=e&&e<d-1?(this.ai(!1,!1,a,!0,b),this.mn({rowIndex:e+1},b,!1),this.ai(!0,!1,a,!0,b)):e===d-1&&(this.ai(!1,!1,a,!0,b),this.q().yd().focus(),this.Uv(!1))},Gba:function(a,b){var d=this.Wm();1<=d?(this.ai(!1,!1,a,!1,b),this.mn({rowIndex:d-1},b,!1),this.ai(!0,!1,
a,!1,b)):0===d&&(this.ai(!1,!1,a,!1,b),this.q().yd().focus(),this.Uv(!1))},Ik:function(c,b,d,e,f){if(-1==c){var g=this.Xm();null!=g&&this.Ik(g,!1,d,null,null);return d&&(f=this.mn(null,f,!1),!f)?!1:!0}var k=this.q().Ae(c);if(!k)return!1;if(b){g=this.Xm();null!=g&&g!=c&&this.Ik(g,!1,d,e,null);if(d&&(d=this.Ao(c),f=this.mn({rowKey:d},f,!1),!f))return!1;k.addClass(a.f.Da.Hm);this.CV(c);this.gL(c,{Sl:!0,hover:!1});this.j4();this.jC();this.Uv(!0)}else k.removeClass(a.f.Da.Hm);this.gL(c,{Sl:b});return!0},
Oj:function(c,b,d,e,f){if(this.oq()==this.wk.Mx||this.oq()==this.wk.Nr)if((isNaN(c)||0>c)&&a.r.error("Error: Invalid row selection value: "+c),this.oq()==this.wk.Mx&&b&&this.Yx(),d=this.q().Ae(c),null!=d){e=!1;if(d.hasClass(a.f.Da.Te)!=b){b?d.addClass(a.f.Da.Te):d.removeClass(a.f.Da.Te);e=!0;var h=this.options.dnd.drag;h&&("rows"===h||h.rows)&&d.prop("draggable",b)}e&&(b?this.gL(c,{hover:!1,Sl:!1,selected:!0}):this.gL(c,{selected:!1}));this.TBa(c,b);c=this.q().pfa(d);g(c.children("."+a.f.J.D0)[0]).prop("checked",
b);f&&(b=this.z7(),this.option("selection",b,{_context:{Ed:!0,ob:!0}}))}},mz:function(c){if(null==c)this.Yx(),this.jC();else{var b,d,e,f,g,k,l=c.length;for(b=0;b<l;b++){e=c[b];if(null==e.startKey&&null==e[this.yg]||null==e.endKey&&null==e[this.fh])return a.r.error("Error: Invalid range object in selection. Both start and end objects must be specified"),null;f=k=d=g=null;null!=e.startKey&&null!=e.startKey[this.Vf]&&(g=this.gv(e.startKey[this.Vf]));null!=e.endKey&&null!=e.endKey[this.Vf]&&(d=this.gv(e.endKey[this.Vf]));
null!=e.startKey&&null!=e.startKey[this.Uf]&&(k=this.r6(e.startKey[this.Uf]));null!=e.endKey&&null!=e.endKey[this.Uf]&&(f=this.r6(e.endKey[this.Uf]));null==g&&null!=e[this.yg]&&(g=e[this.yg][this.Vf]);null==d&&null!=e[this.fh]&&(d=e[this.fh][this.Vf]);null==k&&null!=e[this.yg]&&(k=e[this.yg][this.Uf]);null==f&&null!=e[this.fh]&&(f=e[this.fh][this.Uf]);if(null!=g&&null!=d&&null!=k&&null!=f)return a.r.error("Error: Invalid range object in selection - Can only support row or column selection. Not both"),
null;if(null!=g&&0<=g&&null!=d&&0<=d)for(f=this.UC(g),d=this.UC(d),f=this.Ay(f),e=this.Ay(d),d=f;d<=e;d++)try{this.Oj(d,!0,null,null,!1)}catch(m){a.r.error("Error: "+m)}else if(null!=k&&null!=f)for(d=k;d<=f;d++)try{this.Po(d,!0,null,null,!1)}catch(s){a.r.error("Error: "+s)}else return a.r.error("Error: Invalid range object in selection - \n start row: "+g+"\nend row: "+d+"\nstart column: "+k+"\nend column: "+f),null}}},ai:function(c,b,d,e,f){var g=this.options.editMode;if(null!=g&&g!=this.BB.sl&&
(g=this.LC(),null!=g)){var k=g.rowIndex,l;try{if(c&&!this.uv()){var m=this.q().Ae(k),s=this.Ao(k),t=a.eh.Xz(this,m[0],{row:{key:s,index:k},isCurrentRow:!0});l=this._trigger("beforeEdit",f,{rowContext:t})}else if(!c&&this.uv())m=this.q().Ae(this.Wm()),s=this.Ao(this.Wm()),t=a.eh.Xz(this,m[0],{row:{key:s,index:this.Wm()},isCurrentRow:!0}),l=this._trigger("beforeEditEnd",f,{rowContext:t,cancelEdit:b});else return}catch(r){return!1}if(!l)return!1;var n=this.Wm(),p=this;c?(this.KV(k),this.refreshRow(k).then(function(){p.Yh(function(){p.vBa(k,
d,e)})})):this.KV(null);null!=n&&this.refreshRow(n).then(function(){p.Yh(function(){var b=this.q().Ae(n);null!=b&&b.removeClass(a.f.J.n2)})})}},Uv:function(a){this.dW=a},yCa:function(c,b,d){this.q().jJa(c,b,d);c=this.q().$X();if(c.css(a.f.O.hf)==a.f.na.sl){c.css(a.f.O.hf,a.f.na.sx);var e=parseInt(c.css(a.f.O.Fu),10),f=parseInt(c.css(a.f.O.Gu),10);b=this.q().zd();d==a.ia.Xc.WARNING&&(b.addClass(a.f.Da.mH),c.addClass(a.f.Da.mH));d=b.width();c.css(a.f.O.qe,d-e-f+a.f.na.nc);d=c.outerHeight();var e=parseInt(b.css(a.f.O.A0),
10),f=parseInt(b.css(a.f.O.xka),10),g=parseInt(b.css(a.f.O.TG),10),g=g+e+d;b.css(a.f.O.TG,g+a.f.na.nc);c.css(a.f.O.SO,-1*(g+e)+a.f.na.nc);c.css(a.f.O.bo,-1*f+a.f.na.nc)}},WV:function(){null==this.q().vfa()&&this.q().eFa(this.gc().length)},aca:function(){this.q().YE().css(a.f.O.hf,a.f.na.j1);this.q().Eha()},bca:function(c){if(this.gc()[c].sortable==this.uj&&(c=this.q().Wd(c))&&null==c.data("sorted")){var b=c.find("."+a.f.J.yu);b.addClass(a.f.Da.Jh);b.removeClass(a.f.Da.ec);c.find("."+a.f.J.yG).removeClass(a.f.Da.ec);
c.find("."+a.f.J.CG).addClass(a.f.Da.ec)}},EW:function(a){var b=this;a.find("*").each(function(){b.Lu(this)});b=null},Uo:function(){var a=this.Lb();if(null!=this.Cb&&null!=a){var b,d=this.Cb.length;for(b=0;b<d;b++)a.off(this.Cb[b].eventType,this.Cb[b].eventHandler)}},Vo:function(){var c=this.q().zd();a.u.lm(c[0],this.Ll);this.LJ=!1},ADa:function(c){var b=this.DS(c).selected,d=this.Cy(),e=this.q().$e();if(null!=e&&0<e.length)for(var f,h,k,l,m=e.length,e=0;e<m;e++)if(h=this.q().tt(e,c),b)g(h).addClass(a.f.Da.Te);
else{k=!1;l=d.length;for(f=0;f<l;f++)if(e==d[f]){k=!0;break}k||g(h).removeClass(a.f.Da.Te)}},gL:function(c,b){var d=this.q().gM(c),e=b.Sl,f=b.selected,h=b.hover;if(d){if(null!=h){var k,l=d.length;for(k=0;k<l;k++)h?g(d[k]).addClass(a.f.Da.$n):g(d[k]).removeClass(a.f.Da.$n)}if(null!=e)for(l=d.length,k=0;k<l;k++)e?g(d[k]).addClass(a.f.Da.Hm):g(d[k]).removeClass(a.f.Da.Hm);if(null!=f)for(l=d.length,k=0;k<l;k++)f?g(d[k]).addClass(a.f.Da.Te):g(d[k]).removeClass(a.f.Da.Te)}},IBa:function(a){this.Q5=a?a.bind(this):
void 0},Yh:function(c){var b=this;this.dz||(this.mE=0,this.dz=Promise.resolve());this.mE++;return this.dz=this.dz.then(function(){if(!b.lC)return c.bind(b)()}).then(function(a){b.mE--;0!=b.mE||b.lC||(b.dz=void 0,b.Q5&&b.Q5(),b._trigger("ready"),b=null);return a},function(c){b.mE--;0==b.mE&&(b.dz=void 0,a.r.error(c),b=null);return Promise.reject(c)})}})})();a.Components.Dp({ojTable:{display:a.Components.Lf(function(){return(a.nd.uf("oj-table-option-defaults")||{}).display})}});a.f=function(a){this.R=
a;this.options=a.options;this.element=a.element;this.oe=a.oe;this.Init()};o_("TableDomUtils",a.f,a);a.b.ta(a.f,a.b,"oj.TableDomUtils");a.f.prototype.Init=function(){a.f.t.Init.call(this)};a.b.g("TableDomUtils.prototype.Init",{Init:a.f.prototype.Init});a.f.prototype.DEa=function(){this.jt();this.Nl=null};a.f.prototype.jt=function(){this.JQ=null};a.f.prototype.Qda=function(c){var b=null,d=this,e=this.R.QJ()?this.R.oq()==this.R.wk.Nr:!1;if(null!=this.options.contextMenu||null!=this.yd().attr("contextmenu")){if(e=
this.Cea(),b=g(e),null!=b&&0<b.length){var f=b.find("[data-oj-command]");if(null!=f&&0<f.length){var h;f.each(function(){0===g(this).children(a.f.Pa.vu).length&&(h=g(this).attr("data-oj-command").split("-"),g(this).replaceWith(d.kX(h[h.length-1])))});this.d$=b;this.R.C4=e;b.data("oj-ojMenu")&&b.ojMenu("refresh");b.on("ojselect",c)}}}else if(this.R.G9()||e)b=g(document.createElement(a.f.Pa.fna)),b.css(a.f.O.hf,a.f.na.sl),b.attr(a.f.Gb.rl,this.xn()+"_contextmenu"),this.zd().append(b),this.R.G9()&&(f=
this.kX("sort"),b.append(f)),e&&(e=this.kX("enableNonContiguousSelection"),b.append(e)),b.ojMenu(),this.d$=b,this.R.C4="#"+b.attr(a.f.Gb.rl),b.on("ojselect",c),this.R._setOption("contextMenu","#"+b.attr(a.f.Gb.rl))};a.f.prototype.kX=function(a){return"sort"===a?g(this.Kz(a)).append(g("\x3cul\x3e\x3c/ul\x3e").append(g(this.Kz("sortAsc"))).append(g(this.Kz("sortDsc")))):"sortAsc"===a?g(this.Kz("sortAsc")):"sortDsc"===a?g(this.Kz("sortDsc")):"enableNonContiguousSelection"==a||"disableNonContiguousSelection"==
a?g(this.Kz(a)):null};a.f.prototype.Kz=function(a){var b=g(document.createElement("li"));b.attr("data-oj-command","oj-table-"+a);b.append(this.PEa(a));return b};a.f.prototype.PEa=function(c){var b=g(document.createElement(a.f.Pa.vu));b.attr(a.f.Gb.hP,"#");var d=null;"sort"==c?d=this.R.F("labelSort"):"sortAsc"==c?d=this.R.F("labelSortAsc"):"sortDsc"==c?d=this.R.F("labelSortDsc"):"enableNonContiguousSelection"==c?d=this.R.F("labelEnableNonContiguousSelection"):"disableNonContiguousSelection"==c&&(d=
this.R.F("labelDisableNonContiguousSelection"));b.text(d);return b};a.f.prototype.QEa=function(a,b){this.yd();this.VEa();this.pp()&&this.WEa();a||this.Vda();b||this.Tda();this.SEa();this.Wda();this.bFa()};a.f.prototype.SEa=function(){var c=this.yd(),b=g(document.createElement(a.f.Pa.KB));c.append(b);this.IQ=b};a.f.prototype.TEa=function(){return g(document.createElement(a.f.Pa.Wp))};a.f.prototype.nX=function(c,b,d,e,f){var h=null;f||(h=this.pfa(e));null==h&&(h=null!=b?b.toString():c.toString(),d=
null==d?this.rw(h):d,h=g(document.createElement(a.f.Pa.Wp)),h.addClass(a.f.J.OP),h.css("padding","0"),h.css("border","0"),null!=this.Uq()&&(b=this.options.accessibility,f=null,f=null!=b&&null!=b.rowHeader?b.rowHeader:this.R.gc()[0].id,b=this.xn()+":"+f+"_"+d,h.attr(a.f.Gb.gP,this.xn()+":"+a.f.G0+" "+b)),b=g(document.createElement(a.f.Pa.KG)),b.attr(a.f.Gb.rl,this.xn()+":acc_sel_row_"+d),b.attr(a.f.Gb.Yp,"checkbox"),b.attr(a.f.Gb.Vr,"-1"),d=null,d=null!=this.R.oq()?!0:!1,d=this.options.editMode==this.R.BB.c2?
d?this.R.F(this.R.Ja.x1):this.R.F(this.R.Ja.v1):this.R.F(this.R.Ja.y1),b.attr(a.f.Gb.hH,d),b.addClass(a.f.J.D0),b.addClass(a.f.J.ol),this.R.Wm()==c?b.prop("checked",!0):b.prop("checked",!1),h.append(b),e.prepend(h))};a.f.prototype.Sda=function(c,b){var d=g(document.createElement(a.f.Pa.Xp));this.nX(c,b,null,d,!0);return d};a.f.prototype.UEa=function(c){var b=g(document.createElement(a.f.Pa.gh));b.addClass(a.f.J.TP);b.addClass(a.f.J.VP);b.data("rowIdx",c);var d=g(document.createElement(a.f.Pa.gh));
d.addClass(a.f.J.p2);d.attr("role","button");d.attr("aria-label",this.R.F("labelAccSelectionAffordanceTop"));d.data("rowIdx",c);b.append(d);d=g(document.createElement(a.f.Pa.gh));d.addClass(a.f.J.SP);d.addClass(a.f.J.VP);d.data("rowIdx",c);var e=g(document.createElement(a.f.Pa.gh));e.addClass(a.f.J.o2);e.attr("role","button");e.attr("aria-label",this.R.F("labelAccSelectionAffordanceBottom"));e.data("rowIdx",c);d.append(e);e=this.zd();e.append(b);e.append(d);this.cha(c);this.bha(c)};a.f.prototype.VEa=
function(){var c;this.oe?c=g(this.oe):(c=g(document.createElement(a.f.Pa.gh)),this.element.parent()[0].replaceChild(c[0],this.element[0]),c.prepend(this.element));this.JH=c};a.f.prototype.Tda=function(){var c=this.yd(),b=g(document.createElement(a.f.Pa.ZP)),d=g(document.createElement(a.f.Pa.Xp));this.Uda(d);b.append(d);d=this.Uq();null!=d?d.after(b):(d=this.ze(),null!=d?d.before(b):c.append(b));return b};a.f.prototype.Uda=function(c){var b=c.children("."+a.f.J.ol);null!=b&&0<b.length?g(b[0]):(b=g(document.createElement(a.f.Pa.Wp)),
b.addClass(a.f.J.ol),b.attr(a.f.Gb.Vr,"-1"),c.prepend(b))};a.f.prototype.XEa=function(){return g(document.createElement(a.f.Pa.Wp))};a.f.prototype.Vda=function(){var c=this.yd(),b=g(document.createElement(a.f.Pa.$P)),d=g(document.createElement(a.f.Pa.Xp));this.MQ=d;b.append(d);d=this.mp();null!=d?d.before(b):(d=this.ze(),null!=d?d.before(b):c.append(b));return this.LQ=b};a.f.prototype.YEa=function(){var c=g(document.createElement(a.f.Pa.x2));c.addClass(a.f.J.VO);c.attr(a.f.Gb.rl,this.xn()+":"+a.f.G0);
var b;b=null!=this.R.oq()?!0:!1;b=this.options.editMode==this.R.BB.c2?b?this.R.F(this.R.Ja.x1):this.R.F(this.R.Ja.v1):this.R.F(this.R.Ja.y1);c.attr(a.f.Gb.hH,b);c.css("padding","0");c.css("border","0");var d=g(document.createElement(a.f.Pa.Oma));d.text(b);d.addClass(a.f.J.ol);c.append(d);return c};a.f.prototype.ZEa=function(c){var b=this.R.gc()[c],d=g(document.createElement(a.f.Pa.x2));this.wia(c,d,!0);d.attr("abbr",b.headerText);d.attr(a.f.Gb.hH,b.headerText);this.xHa(c,d);c={columnIndex:c,headerContext:{component:this.R,
parentElement:d}};b.sortable==a.f.uj?(d.attr("data-oj-sortable",a.f.uj),a.eh.Hda(this.R,c,null)):a.eh.Fda(this.R,c,null);return d};a.f.prototype.aFa=function(c){c=this.Wd(c).clone();c.removeClass(a.f.Da.zx);c.removeClass(a.f.Da.Hm);c.removeClass(a.f.Da.$n);c.addClass(a.f.J.F0);c.css(a.f.O.eo,a.f.na.PO);c.css(a.f.O.Ku,"0");c.css(a.f.O.bo,"-999em");c.css(a.f.O.hna,"-999");this.zd().append(c);return c};a.f.prototype.$Ea=function(c,b){if(b==a.f.wk.Mx||b==a.f.wk.Nr){var d=this.Wd(c),e=this.ufa(c);if(null==
e){e=g(document.createElement(a.f.Pa.gh));e.addClass(a.f.J.E0);e.addClass(a.f.J.ol);var f=g(document.createElement(a.f.Pa.KG));f.attr(a.f.Gb.rl,this.xn()+":acc_sel_col"+c);f.attr(a.f.Gb.Yp,"checkbox");f.attr(a.f.Gb.Vr,"-1");var h=this.R.F(this.R.Ja.Dla);f.attr(a.f.Gb.hH,h);f.addClass(a.f.J.C0);e.append(f);d.prepend(e)}}};a.f.prototype.WEa=function(){var c=this.yd(),b=this.zd(),d=g(document.createElement(a.f.Pa.gh));d.addClass(a.f.J.w2);b[0].replaceChild(d[0],c[0]);d.append(c);this.KQ=d};a.f.prototype.eFa=
function(c){var b=this.ze(),d=g(document.createElement(a.f.Pa.Xp));d.addClass(a.f.J.v2);this.cFa(d);this.dFa(d,c);b.append(d)};a.f.prototype.cFa=function(c){var b=g(document.createElement(a.f.Pa.Wp));b.addClass(a.f.J.ol);b.attr(a.f.Gb.Vr,"-1");c.prepend(b)};a.f.prototype.dFa=function(c,b){var d=g(document.createElement(a.f.Pa.Wp));d.attr(a.f.Gb.tx,b||1);d.addClass(a.f.J.u2);var e=null,e=null!=this.options.emptyText?this.options.emptyText:this.R.F(this.R.Ja.Sla);d.text(e);c.append(d)};a.f.prototype.bFa=
function(){var c=this.zd(),b=g(document.createElement(a.f.Pa.gh));b.addClass(a.f.J.t2);b.css(a.f.O.hf,a.f.na.sl);c.append(b);this.NQ=b};a.f.prototype.Wda=function(){var c=this.zd(),b=g(document.createElement(a.f.Pa.gh));b.addClass(a.f.J.YP);b.css(a.f.O.hf,a.f.na.sl);var d=g(document.createElement(a.f.Pa.gh));d.addClass(a.f.J.Yma);d.text(this.R.F(this.R.Ja.Ola));b.append(d);c.append(b);this.OQ=b};a.f.prototype.bea=function(c,b){this.sN();var d=this.pw(),e=this.Wd(c);if(null!=e)b?e.addClass(a.f.J.BG):
e.addClass(a.f.J.AG);else if(e=this.R.gc(),null==e||0==e.length)b?d.addClass(a.f.J.BG):d.addClass(a.f.J.AG)};a.f.prototype.mFa=function(c,b){this.jZ();var d=g(document.createElement(a.f.Pa.Xp));d.addClass(a.f.J.RP);b&&d.height(b.height());var e=g(document.createElement(a.f.Pa.Wp)),f=this.R.gc();e.attr(a.f.Gb.tx,f.length+1);d.append(e);e=this.Ae(c);null!=e?e.before(d):(e=this.$e(),null!=e&&0!=e.length||this.R.vJ(),this.ze().append(d))};a.f.prototype.Cea=function(){return null==this.options.contextMenu?
"#"+this.yd().attr("contextmenu"):this.options.contextMenu};a.f.prototype.xe=function(c){var b=this.qt(c,a.f.J.Nx);if(null!=b)return b.parent().children("."+a.f.J.Nx).index(b);b=this.qt(c,a.f.J.Kr);if(null!=b)return b.parent().children("."+a.f.J.Kr).index(b);c=this.qt(c,a.f.J.Ju);return null!=c?c.parent().children("."+a.f.J.Ju).index(c):null};a.f.prototype.Qq=function(c){c=this.qt(c,a.f.J.Wr);return null!=c?c.index():null};a.f.prototype.qt=function(a,b){var d;if(null==a)return null;a=g(a);if(a.hasClass(b))return a;
d=a.parents("."+b);return 0!=d.length?d.eq(0):null};a.f.prototype.dGa=function(){var a=this.ye();return 0<a.get(0).clientHeight?a.get(0).offsetHeight-a.get(0).clientHeight:0};a.f.prototype.jfa=function(){var a=this.ye();return 0<a.get(0).clientWidth?a.get(0).offsetWidth-a.get(0).clientWidth:0};a.f.prototype.ye=function(){return this.pp()?this.sfa():this.ze()};a.f.prototype.gfa=function(a){a=g(a);var b=a[0].scrollLeft;"rtl"===this.R.hd()&&(b=Math.abs(b),this.I9()&&(b=a[0].scrollWidth-a[0].clientWidth-
b));return b};a.f.prototype.yd=function(){return g(this.element)};a.f.prototype.ze=function(){if(!this.IQ){var c=this.yd(),b=null;c&&(b=c.children("."+a.f.J.NP))&&0<b.length&&(this.IQ=g(b.get(0)))}return this.IQ};a.f.prototype.tt=function(a,b,d){return(a=this.gM(a,d))?a.length>b?g(a[b]):null:null};a.f.prototype.pfa=function(c){return null!=c&&(c=c.children("."+a.f.J.OP),null!=c&&0<c.length)?g(c[0]):null};a.f.prototype.mGa=function(a){return(a=this.gM(a,void 0))?this.rS(a):null};a.f.prototype.gM=function(c,
b){b||(b=this.Ae(c));if(!b)return null;var d=b.children("."+a.f.J.Nx);return null!=d&&0<d.length?d:null};a.f.prototype.Ae=function(a){var b=this.$e();return b&&null!=a?b.length>a?g(b[a]):null:null};a.f.prototype.$e=function(){if(!this.JQ){var c=this.ze();null!=c&&(c=c.children("."+a.f.J.Wr),null!=c&&0<c.length&&(this.JQ=c))}return this.JQ};a.f.prototype.rfa=function(){var c=this.zd().children("."+a.f.J.TP);return null!=c&&0<c.length?c=g(c[0]):null};a.f.prototype.qfa=function(){var c=this.zd().children("."+
a.f.J.SP);return null!=c&&0<c.length?c=g(c[0]):null};a.f.prototype.zd=function(){this.JH||(this.pp()?this.JH=g(this.element.get(0).parentNode.parentNode):this.JH=g(this.element.get(0).parentNode));return this.JH};a.f.prototype.mp=function(){var c=this.yd(),b=null;return c&&(b=c.children("."+a.f.J.WP))&&0<b.length?g(b.get(0)):null};a.f.prototype.ZX=function(a){var b=this.tfa();return null!=b&&b.length>a?g(b[a]):null};a.f.prototype.tfa=function(){var c=this.$z(),c=g(c).children("."+a.f.J.Ju);return null!=
c&&0<c.length?c:null};a.f.prototype.nGa=function(){var a=this.tfa();return a?this.rS(a):null};a.f.prototype.$z=function(){if(!this.I3){var c=this.mp();if(!c)return null;this.I3=g(c.children("."+a.f.J.r2).get(0))}return this.I3};a.f.prototype.Uq=function(){if(!this.LQ){var c=this.yd(),b=null;c&&(b=c.children("."+a.f.J.XP))&&0<b.length&&(this.LQ=g(b.get(0)))}return this.LQ};a.f.prototype.Wd=function(a){var b=this.aA();return b?b.length>a?g(b[a]):null:null};a.f.prototype.ufa=function(c){c=this.Wd(c);
return null!=c&&(c=c.children("."+a.f.J.E0),null!=c&&0<c.length)?g(c[0]):null};a.f.prototype.aA=function(){var c=this.pw();return null!=c&&(c=c.children("."+a.f.J.Kr),null!=c&&0<c.length)?c:null};a.f.prototype.oGa=function(){var a=this.aA();return a?this.rS(a):null};a.f.prototype.pw=function(){if(!this.MQ){var c=this.Uq();if(!c)return null;this.MQ=g(c.children("."+a.f.J.s2).get(0))}return this.MQ};a.f.prototype.sfa=function(){if(!this.KQ){var c=this.zd();c&&(c=c.children("."+a.f.J.w2))&&0<c.length&&
(this.KQ=g(c.get(0)))}return this.KQ};a.f.prototype.xn=function(){this.vca||(this.vca=this.yd().attr(a.f.Gb.rl));return this.vca};a.f.prototype.$X=function(){if(!this.NQ){var c=this.zd();c&&(c=c.children("."+a.f.J.t2))&&0<c.length&&(this.NQ=g(c.get(0)))}return this.NQ};a.f.prototype.vfa=function(){var c=this.ze();return c&&(c=c.children("."+a.f.J.v2))&&0<c.length?g(c.get(0)):null};a.f.prototype.YE=function(){if(!this.OQ){var c=this.zd();c&&(c=c.children("."+a.f.J.YP))&&0<c.length&&(this.OQ=g(c.get(0)))}return this.OQ};
a.f.prototype.pGa=function(){if(!this.wca){var a=this.xn();null==a&&(a=(1E32*Math.random()).toString(36));this.wca=a}return this.wca};a.f.prototype.rw=function(a){"string"!=g.type(a)&&(a=a.toString());var b=0;if(0==a.length)return b;var d,e,f=a.length;for(e=0;e<f;e++)d=a.charCodeAt(e),b=(b<<5)-b+d,b&=b;return b};a.f.prototype.vHa=function(a,b,d,e,f,h){this.yZ(a,b,d,e,f);g(h).append(f)};a.f.prototype.ega=function(c,b,d,e){this.zZ(d,b);null==e?(d=this.ze(),e=d.children("."+a.f.J.Wr),0==c?d.prepend(b):
e.length>=c?g(e.get(c-1)).after(b):d.append(b)):e.append(b);this.jt()};a.f.prototype.wHa=function(c,b){var d=this.$z(),e=g(d).children("."+a.f.J.Ju);0==c?(e=d.children("."+a.f.J.ol),null!=e&&0<e.length?g(e[0]).after(b):d.prepend(b)):d.length>=c?g(e.get(c-1)).after(b):d.append(b)};a.f.prototype.xHa=function(c,b){var d=this.pw(),e=this.aA();this.hia(c,b);var f=this.Wd(c);f?f.replaceWith(b):0==c?(e=d.children("."+a.f.J.VO),null!=e&&0<e.length?g(e[0]).after(b):d.prepend(b)):e.length>=c?g(e.get(c-1)).after(b):
d.append(b)};a.f.prototype.pp=function(){return this.FJ()&&10>this.FJ()?!0:!1};a.f.prototype.oga=function(){var c=this.zd(),b=this.yd(),d=this.YE(),e=d.css(a.f.O.hf).toString();d.css(a.f.O.hf,a.f.na.sl);var f=[];f[0]=0<c[0].clientHeight?b[0].clientHeight>c[0].clientHeight?1:1<c[0].clientHeight-b[0].clientHeight?-1:0:0;f[1]=0<c[0].clientWidth?b[0].clientWidth>c[0].clientWidth?1:1<c[0].clientWidth-b[0].clientWidth?-1:0:0;d.css(a.f.O.hf,e);return f};a.f.prototype.cha=function(c){var b=this.rfa();if(null!=
b){b.data("rowIdx",c);g(b.children()[0]).data("rowIdx",c);var d=this.ze();c=this.Ae(c)[0].getBoundingClientRect();var e=this.zd()[0].getBoundingClientRect();b.css(a.f.O.Ku,c.top-e.top-b.height()/2);b.css(a.f.O.bo,d.width()/2+a.f.na.nc)}};a.f.prototype.bha=function(c){var b=this.qfa();if(null!=b){b.data("rowIdx",c);g(b.children()[0]).data("rowIdx",c);var d=this.ze();c=this.Ae(c)[0].getBoundingClientRect();var e=this.zd()[0].getBoundingClientRect();b.css(a.f.O.Ku,c.top-e.top+c.height-b.height()/2);
b.css(a.f.O.bo,d.width()/2+a.f.na.nc)}};a.f.prototype.fIa=function(c,b,d){var e=this.R.gc(),f=this.Wd(c),g=this.ZX(c),k=null,l=k=k=null,m=null,s=!1;b==e.length&&(b-=1,s=!0);null!=f&&(m=f.attr(a.f.Gb.tx),k=this.Wd(b),null==k||null!=m&&1!=m||(s?k.after(f):k.before(f)));null!=g&&(m=g.attr(a.f.Gb.tx),k=this.ZX(b),null==k||null!=m&&1!=m||(s?k.after(g):k.before(g)));f=this.$e();if(null!=f)for(e=0;e<f.length;e++)k=this.tt(e,c,null),null!=k&&(l=this.tt(e,b,null),m=k.attr(a.f.Gb.tx),null==l||null!=m&&1!=m||
(s?l.after(k):l.before(k)));m=this.options.columns;b=c<b&&!s?b-1:b;s=m.splice(c,1);m.splice(b,0,s[0]);m=m.slice(0);this.R.option("columns",m,{_context:{Ed:!0,originalEvent:d,ob:!0}});d=this.R.hs.splice(c,1);this.R.hs.splice(b,0,d[0]);if(!this.po)for(this.po=[],e=0;e<m.length;e++)this.po[e]=e;c=this.po.splice(c,1);this.po.splice(b,0,c[0]);this.R.Yh(function(){});return this.po};a.f.prototype.DIa=function(){var c=this,b=this.d$;b&&0<b.length&&b.find("[data-oj-command]").each(function(){var b=g(this).children(a.f.Pa.vu);
if(0<b.length){var e=g(this).attr("data-oj-command").split("-"),e=e[e.length-1],f;"sort"==e?f=c.R.F("labelSort"):"sortAsc"==e?f=c.R.F("labelSortAsc"):"sortDsc"==e&&(f=c.R.F("labelSortDsc"));b.contents().filter(function(){return 3===this.nodeType})[0].nodeValue=f}})};a.f.prototype.qN=function(a,b,d,e){this.R.Vo();this.Wza(a,b,d,e);this.R.jn();this.R.mn(this.options.currentRow,null)};a.f.prototype.sN=function(){var c=this.yd().find("."+a.f.J.BG+",."+a.f.J.AG),b=0;if(c&&0<c.length)for(var d=c.length,
b=0;b<d;b++)g(c[b]).removeClass(a.f.J.BG),g(c[b]).removeClass(a.f.J.AG)};a.f.prototype.jZ=function(){var c=this.ze(),b=c.children("."+a.f.J.RP),c=c.children("."+a.f.J.Vma),d=0;if(b&&0<b.length)for(var e=b.length,d=0;d<e;d++)g(b[d]).remove();if(c&&0<c.length)for(b=c.length,d=0;d<b;d++)g(c[d]).remove();b=this.$e();null!=b&&0!=b.length||this.R.WV()};a.f.prototype.Kha=function(c){c=this.Ae(c);null!=c&&(a.Components.ti(c[0]),c.remove(),this.jt())};a.f.prototype.Fha=function(){var c=this.$e();null!=c&&
0<c.length&&(c=this.ze(),a.Components.ti(c[0]),c.empty(),this.jt())};a.f.prototype.NIa=function(){var c=this.zd().children("."+a.f.J.VP);if(null!=c&&0<c.length){var b;for(b=0;b<c.length;b++)c[b].remove()}};a.f.prototype.OIa=function(){var c=this.zd().find("."+a.f.J.F0);if(c&&0<c.length){var b,d=c.length;for(b=0;b<d;b++)g(c[b]).remove()}};a.f.prototype.fia=function(a,b){a=g(a);"rtl"===this.R.hd()&&(b=Math.abs(b),this.I9()?b=a[0].scrollWidth-a[0].clientWidth-b:this.txa()&&(b*=-1));a[0].scrollLeft!=
b&&(a[0].scrollLeft=b)};a.f.prototype.yZ=function(c,b,d,e,f){var g=this.options.accessibility;e=this.R.gc()[e];var k=null,l=null==this.Uq()?!0:!1,k=null!=g&&null!=g.rowHeader?g.rowHeader:this.R.gc()[0].id;c=null!=b?b.toString():c.toString();d=null==d?this.rw(c):d;d=this.xn()+":"+k+"_"+d;c=this.xn()+":"+e.id;k==e.id?(f.attr(a.f.Gb.rl,d),l&&(c="")):c=l?d:c+" "+d;f.attr(a.f.Gb.gP)||f.attr(a.f.Gb.gP,c)};a.f.prototype.zZ=function(a,b){b.data("rowKey",a.key);b.data("rowData",a.data)};a.f.prototype.hia=
function(c,b){var d=this.R.gc()[c];b.attr(a.f.Gb.rl)||b.attr(a.f.Gb.rl,this.xn()+":"+d.id)};a.f.prototype.gia=function(a,b,d){var e=this.$e();if(null!=e&&0<e.length)if(null===a){if(a=null,a=b?this.ze().find("[td]"):this.ze().find("."+d),null!=a&&0<a.length)for(var f=a.length,e=0;e<f;e++)b?g(a[e]).addClass(d):g(a[e]).removeClass(d)}else for(var h=e.length,e=0;e<h;e++)f=this.tt(e,a,null),b?g(f).addClass(d):g(f).removeClass(d)};a.f.prototype.jJa=function(c,b,d){var e=this.$X();e.empty();e.append(a.rb.tda(document,
c,b,d,null))};a.f.prototype.tJa=function(){var c=this.yd(),b=this.zd(),d=c.children(a.f.Pa.$P),d=0<d.length?g(d[0]):null,e=c.children(a.f.Pa.ZP),e=0<e.length?g(e[0]):null,f=c.children(a.f.Pa.KB),f=0<f.length?g(f[0]):null;c.attr(a.f.Gb.Vr,"0");this.R._focusable(c);this.R._focusable(b);this.via(d);this.tia(e);this.uJa(f)};a.f.prototype.uJa=function(c){c.addClass(a.f.J.NP);c.attr(a.Components.co,this.R.widgetName)};a.f.prototype.EZ=function(c,b,d){c=this.R.gc()[c];if(d||!b.hasClass(a.f.J.Nx))b.addClass(a.f.J.Nx),
b.addClass(a.f.J.Wma),null==c.style||!d&&b.attr(a.f.Gb.fo)==c.style||b.attr(a.f.Gb.fo,c.style),null==c.className||!d&&b.hasClass(c.className)||b.addClass(c.className);this.wU()&&(!d&&b.hasClass(a.f.J.Ox)||b.addClass(a.f.J.Ox))};a.f.prototype.FZ=function(c,b){!b&&c.hasClass(a.f.J.Wr)||c.addClass(a.f.J.Wr);this.t9()&&(!b&&c.hasClass(a.f.J.JB)||c.addClass(a.f.J.JB))};a.f.prototype.vJa=function(c){c.addClass(a.f.J.l2);c.addClass(a.f.J.Uma);c.addClass(a.f.Da.gQ);this.options.display==a.f.L1.a1?c.addClass(a.f.J.m2):
c.removeClass(a.f.J.m2);var b=this.options.editMode;null!=b&&b!=this.R.BB.sl?c.addClass(a.f.J.q2):c.removeClass(a.f.J.q2)};a.f.prototype.tia=function(c){c&&(c.addClass(a.f.J.WP),g(c.children(a.f.Pa.Xp)[0]).addClass(a.f.J.r2))};a.f.prototype.uia=function(c,b){this.R.gc();var d=this.R.gc()[c];b.attr(a.f.Gb.fo,d.footerStyle);b.hasClass(a.f.J.Ju)||b.addClass(a.f.J.Ju);this.wU()&&!b.hasClass(a.f.J.Ox)&&b.addClass(a.f.J.Ox);d.footerClassName&&b.addClass(d.footerClassName)};a.f.prototype.via=function(c){c&&
(c.addClass(a.f.J.XP),c.css(a.f.O.hf,"table-header-group"),c=g(c.children(a.f.Pa.Xp)[0]),c.addClass(a.f.J.s2),c.css(a.f.O.eo,a.f.na.Kx))};a.f.prototype.wia=function(c,b,d){c=this.R.gc()[c];if(d||!b.hasClass(a.f.J.Kr))b.addClass(a.f.J.Kr),this.wU()&&(!d&&b.hasClass(a.f.J.Ox)||b.addClass(a.f.J.Ox)),null==c.headerStyle||!d&&b.attr(a.f.Gb.fo)==c.headerStyle||b.attr(a.f.Gb.fo,c.headerStyle),null==c.headerClassName||!d&&b.hasClass(c.headerClassName)||b.addClass(c.headerClassName)};a.f.prototype.rS=function(c){var b,
d,e=0,f=[],h=c.length;for(b=0;b<h;b++){var k=g(c[b]).attr(a.f.Gb.tx);if(null!=k){k=parseInt(k,10);for(d=0;d<k;d++)f[e+d]=c[b];e+=k}else f[e++]=c[b]}return g(f)};a.f.prototype.t9=function(){return this.options.horizontalGridVisible==a.f.uj||this.options.horizontalGridVisible==a.f.VG?!0:!1};a.f.prototype.wU=function(){return this.options.verticalGridVisible==a.f.uj||this.options.verticalGridVisible==a.f.VG&&this.options.display==a.f.L1.a1?!0:!1};a.f.prototype.txa=function(){return-1<navigator.userAgent.toLowerCase().indexOf("firefox")?
!0:!1};a.f.prototype.FJ=function(){if("undefined"==typeof this.FH){var a=navigator.userAgent;"Microsoft Internet Explorer"==navigator.appName?(a=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(a),null!=a&&(this.FH=parseFloat(a[1]))):0<=a.indexOf("Trident")?this.FH=11:this.FH=null}return this.FH};a.f.prototype.I9=function(){if("undefined"==typeof this.A3){var a=navigator.userAgent.toLowerCase();this.A3=/webkit/.test(a)&&!/edge/.test(a)}return this.A3};a.f.prototype.Wza=function(c,b,d,e){var f=this.yd(),h=this.Uq(),
k=this.mp(),l=this.$z(),m=this.pw(),s=this.zd(),t=this.ze(),r=null,n=null;if(null!=this.ye()){var p=this.ye()[0].scrollHeight-this.ye()[0].clientHeight,q=this.ye()[0].scrollWidth-this.ye()[0].clientWidth;0<p&&(r=this.ye()[0].scrollTop);0<q&&(n=this.gfa(this.ye()[0]))}this.FAa();this.vJa(s);p=this.oga();this.qz=1===p[0]?!0:!1;this.Yv=1===p[1]?!0:!1;if(null!=t){if(this.qz||this.Yv)this.Nl||(this.Nl={}),0<c||0<b?(0<c&&this.Yv&&(this.Nl[a.f.O.qe]=c),0<b&&this.qz&&(this.Nl[a.f.O.Qp]=b)):(this.Nl[a.f.O.Qp]=
this.qz?s[0].offsetHeight:0,this.Nl[a.f.O.qe]=this.Yv?s[0].offsetWidth:0),this.SK||(this.SK=s.outerWidth()-s.innerWidth()),this.tca||(this.tca=s.outerHeight()-s.innerHeight()),c=0,this.qz&&!this.Yv&&(s.css(a.f.O.DB,a.f.na.qj),c=s.get(0).offsetWidth-s.get(0).clientWidth,0<this.Nl[a.f.O.qe]?f.css(a.f.O.qe,s.get(0).clientWidth+a.f.na.nc):(f.css(a.f.O.qe,s.get(0).scrollWidth+c+a.f.na.nc),p=this.oga(),1===p[1]&&f.css(a.f.O.qe,s.get(0).clientWidth+a.f.na.nc)),s.css(a.f.O.DB,"")),b=f.width(),this.wBa(),
0<c&&f.css(a.f.O.qe,s.get(0).offsetWidth+a.f.na.nc),q=0,f=f.children("caption"),null!=f&&0<f.length&&(q=g(f[0]).outerHeight(),f.css(a.f.O.hf,a.f.na.j1),null!=h&&h.css(a.f.O.B0,s.css(a.f.O.B0).toString())),f=0,null!=h&&(h.css(a.f.O.hf,a.f.na.sx),this.pp()?(h.css(a.f.O.eo,a.f.na.PO),h.css(a.f.O.Ku,"0px")):h.css(a.f.O.eo,a.f.na.Kx),m.css(a.f.O.hf,a.f.na.sx),m.css(a.f.O.eo,a.f.na.Kx),f=h.outerHeight()),this.pp()&&s.css(a.f.O.Yla,f+q+a.f.na.nc),m=0,null!=k&&(this.pp()?(k.css(a.f.O.eo,a.f.na.PO),h.css(a.f.O.SO,
"0px")):k.css(a.f.O.eo,a.f.na.Kx),k.css(a.f.O.hf,a.f.na.sx),l.css(a.f.O.hf,a.f.na.sx),l.css(a.f.O.eo,a.f.na.Kx)),t.css(a.f.O.hf,a.f.na.sx),l=0,this.pp()||(t.css(a.f.O.WG,a.f.na.qj),t.css(a.f.O.eo,a.f.na.Kx),this.Yv?t.css(a.f.O.qe,this.Nl[a.f.O.qe]-this.SK):0<c&&t.css(a.f.O.qe,b-this.SK+c),t.width(),null!=k&&(m=k.outerHeight(),t.css(a.f.O.Ku,-1*m+a.f.na.nc)),this.qz?(l=this.Nl[a.f.O.Qp]-f-m-q-this.tca,0<l&&(t.css(a.f.O.Qp,l+a.f.na.nc),t.css(a.f.O.B1,l+a.f.na.nc))):l=t.outerHeight(),c=this.jfa(),this.Yv?
(b=this.$e(),null!=b&&0<b.length?(t.css(a.f.O.Fx,a.f.na.qj),s.css(a.f.O.Fx,a.f.na.ml),s.css(a.f.O.WG,a.f.na.ml),null!=h&&(b=this.Nl[a.f.O.qe]-this.SK,0<b&&(0<c?h.css(a.f.O.qe,b-c+a.f.na.nc):h.css(a.f.O.qe,b+a.f.na.nc)))):(t.css(a.f.O.Fx,a.f.na.ml),s.css(a.f.O.Fx,a.f.na.qj),s.css(a.f.O.WG,a.f.na.ml))):t.css(a.f.O.Fx,a.f.na.ml)),this.pp()&&(h=this.sfa(),h.css(a.f.O.DB,a.f.na.qj),this.Yv&&h.css(a.f.O.qe,this.Nl[a.f.O.qe]),this.qz&&h.css(a.f.O.Qp,this.Nl[a.f.O.Qp]-f-m),t.css(a.f.O.hla,a.f.na.bo),s.css(a.f.O.DB,
a.f.na.ml)),null!=k&&(this.pp()||k.css(a.f.O.Ku,l+a.f.na.nc));this.MBa();this.EAa(0>p[0]);this.Eha();null==r||d?d&&(this.ye()[0].scrollTop=0,this.ye().scroll()):(p=this.ye()[0].scrollHeight-this.ye()[0].clientHeight,r=r>p?p:r,this.R.Jj()&&p==r&&r--,this.ye()[0].scrollTop=r,this.ye().scroll());null==n||e?e&&(this.fia(this.ye()[0],0),this.ye().scroll()):(this.fia(this.ye()[0],n),this.ye().scroll())}};a.f.prototype.Eha=function(){var c=this.zd(),b=this.ze(),d=this.YE(),e=c;0<b.height()&&(e=b);d&&d[0].offsetParent&&
(d.css(a.f.O.Qp,b.height()+a.f.na.nc),d.css(a.f.O.qe,b.width()+a.f.na.nc),b=g(d[0].children[0]),c="rtl"===this.R.hd(),e={my:"center",at:"center",collision:"none",of:e},e=a.Qd.km(e,c),d.position(e),d={my:"center",at:"center",collision:"none",of:d},d=a.Qd.km(d,c),b.position(d))};a.f.prototype.rAa=function(){var c,b,d=this.R.gc().length;for(c=0;c<d;c++)b=this.Wd(c),null!=b&&b.css(a.f.O.AB,"");c=this.$e();if(null!=c&&0<c.length)for(c=0;c<d;c++)b=this.tt(0,c,null),null!=b&&b.css(a.f.O.AB,"")};a.f.prototype.EAa=
function(c){if(this.t9()){var b=this.$e();if(null!=b&&0<b.length){var d,e=b.length;for(d=0;d<e;d++)g(b[d]).hasClass(a.f.J.JB)||g(b[d]).addClass(a.f.J.JB);b=g(b[b.length-1]);c||b.removeClass(a.f.J.JB)}}};a.f.prototype.FAa=function(){var c=this.yd(),b=this.Uq(),d=this.pw(),e=this.mp(),f=this.$z(),h=this.ze();if(null!=b&&(b.attr(a.f.Gb.fo,""),d.attr(a.f.Gb.fo,""),(b=d.find("."+a.f.J.sB))&&0<b.length))for(var k=b.length,d=0;d<k;d++)g(b[d]).css(a.f.O.qe,"");null!=e&&(e.attr(a.f.Gb.fo,""),f.attr(a.f.Gb.fo,
""));c.css(a.f.O.hf,"");c.css(a.f.O.qe,"");null!=h&&h.attr(a.f.Gb.fo,"");this.rAa()};a.f.prototype.wBa=function(){var c=[],b=[],d=null,e,f,g,k,l,m=this.R.gc().length;for(k=0;k<m;k++)d=this.Wd(k),null!=d&&(l=window.getComputedStyle(d[0]),c[k]=parseInt(l[a.f.O.qe],10),g=this.R.qs(k,"header"),e||null!=g?b[k]=null!=g?parseInt(l[a.f.O.Gu],10)+parseInt(l[a.f.O.Fu],10):e:(e=parseInt(l[a.f.O.Gu],10)+parseInt(l[a.f.O.Fu],10),b[k]=e),g=null,(l=d.find("."+a.f.J.sB))&&0<l.length&&(g=l.get(0).clientHeight),null!=
g&&(d=d.find("."+a.f.J.zG),d.css(a.f.O.B1,g+a.f.na.nc)));e=[];k=this.$e();if(null!=k&&0<k.length)for(k=0;k<m;k++)d=this.tt(0,k,null),null!=d&&(this.R.qs(k,"cell"),this.R.z8(k)?(d=window.getComputedStyle(d[0]),d=parseInt(d[a.f.O.Gu],10)+parseInt(d[a.f.O.Fu],10)):(f||(d=window.getComputedStyle(d[0]),f=parseInt(d[a.f.O.Gu],10)+parseInt(d[a.f.O.Fu],10)),d=f),d=d>b[k]?c[k]-d+b[k]:c[k]+b[k]-d,e[k]=d);for(k=0;k<m;k++)d=this.Wd(k),null!=d&&d.css(a.f.O.AB,c[k]+a.f.na.nc),d=this.tt(0,k,null),null!=d&&d.css(a.f.O.AB,
e[k]+a.f.na.nc),f=this.ZX(k),null!=f&&(d=parseInt(f.css(a.f.O.Gu),10)+parseInt(f.css(a.f.O.Fu),10),d=d>b[k]?c[k]-d+b[k]:c[k]+b[k]-d,f.css(a.f.O.AB,d+a.f.na.nc))};a.f.prototype.MBa=function(){var c=this.R.gc(),b,d,e,f,h,k,l=c.length;for(b=0;b<l;b++)d=c[b],e=this.Wd(b),null!=e&&(f=e.children("."+a.f.J.zG),0<f.length&&(f=g(f[0]),(h=e.find("."+a.f.J.sB))&&0<h.length&&(k=0,d.sortable==a.f.uj&&(k=g(e.find("."+a.f.J.H0).get(0)).width()),0<f[0].clientWidth&&h.width()+k>f[0].clientWidth&&(h.css(a.f.O.qe,""),
d=h.width(),e=e.width()-k,d>e+1&&h.css(a.f.O.qe,e+a.f.na.nc)))))};a.f.J={C0:"oj-table-checkbox-acc-select-column",D0:"oj-table-checkbox-acc-select-row",Uma:"oj-table-container",w2:"oj-table-scroller",l2:"oj-table",m2:"oj-table-grid-display",q2:"oj-table-editable",Xma:"oj-table-element",WP:"oj-table-footer",r2:"oj-table-footer-row",XP:"oj-table-header",s2:"oj-table-header-row",Kr:"oj-table-column-header-cell",$Ja:"oj-table-column-header-drop-empty-cell",E0:"oj-table-column-header-acc-select-column",
VO:"oj-table-column-header-acc-select-row",YJa:"oj-table-column-header-acc-select-row-text",zG:"oj-table-column-header",sB:"oj-table-column-header-text",yG:"oj-table-column-header-asc",CG:"oj-table-column-header-dsc",H0:"oj-table-column-header-sort-placeholder",zka:"oj-table-column-header-acc-asc-link",Aka:"oj-table-column-header-acc-dsc-link",yu:"oj-table-column-header-asc-link",ux:"oj-table-column-header-dsc-link",Bka:"oj-table-column-header-asc-icon",Cka:"oj-table-column-header-dsc-icon",BG:"oj-table-column-header-drag-indicator-before",
AG:"oj-table-column-header-drag-indicator-after",F0:"oj-table-column-header-cell-drag-image",NP:"oj-table-body",Wr:"oj-table-body-row",RP:"oj-table-body-row-drag-indicator-before",Vma:"oj-table-body-row-drag-indicator-after",TP:"oj-table-body-row-touch-selection-affordance-top",SP:"oj-table-body-row-touch-selection-affordance-bottom",p2:"oj-table-body-row-touch-selection-affordance-top-icon",o2:"oj-table-body-row-touch-selection-affordance-bottom-icon",VP:"oj-table-body-row-touch-selection-affordance-touch-area",
n2:"oj-table-body-row-edit",QP:"oj-table-body-current-row",Nx:"oj-table-data-cell",OP:"oj-table-data-cell-acc-select",PP:"oj-table-data-cell-edit",Wma:"oj-form-control-inherit",Ox:"oj-table-vgrid-lines",JB:"oj-table-hgrid-lines",Ju:"oj-table-footer-cell",oKa:"oj-table-footer-drop-empty-cell",t2:"oj-table-inline-message",YP:"oj-table-status-message",Yma:"oj-table-status-message-text",u2:"oj-table-no-data-message",v2:"oj-table-no-data-row",Mu:"oj-component-icon",ol:"oj-helper-hidden-accessible"};a.f.O=
{hf:"display",eQ:"visibility",eo:"position",Qp:"height",qe:"width",Ku:"top",SO:"bottom",bo:"left",cH:"right",Yla:"padding-top",Fu:"padding-left",Gu:"padding-right",DB:"overflow",Fx:"overflow-x",WG:"overflow-y",AB:"min-width",B1:"min-height",hla:"float",B0:"border-top",A0:"border-bottom-width",xka:"border-left-width",TG:"margin-bottom",gna:"vertical-align",J0:"cursor",hna:"z-index",wka:"background-color"};a.f.na={sl:"none",sx:"block",rla:"inline-block",Kx:"relative",PO:"absolute",j1:"inline",qj:"auto",
ml:"hidden",bo:"left",nc:"px",Mla:"middle",Nla:"move",gla:"fixed",bna:"transparent"};a.f.Gb={fo:"style",Vr:"tabindex",Yp:"type",rl:"id",hH:"title",hP:"href",gP:"headers",tx:"colspan"};a.f.Pa={gh:"div",vu:"a",Xp:"tr",Wp:"td",x2:"th",Tma:"table",KB:"tbody",$P:"thead",ZP:"tfoot",KG:"input",fna:"ul",Oma:"span"};a.f.Da={gQ:"oj-component",Gh:"oj-active",xu:"oj-clickable-icon-nocontext",ec:"oj-disabled",Jh:"oj-enabled",Hm:"oj-focus",$n:"oj-hover",Te:"oj-selected",mH:"oj-warning",T0:"oj-draggable",zx:"oj-drag"};
a.f.G0="_hdrColRowSel";a.f.VG="auto";a.f.uj="enabled";a.f.Rr="disabled";a.f.wk={Mx:"single",Nr:"multiple"};a.f.L1={jKa:"list",a1:"grid"};a.Qb=function(a){this.R=a;this.options=a.options;this.Init()};o_("TableDndContext",a.Qb,a);a.b.ta(a.Qb,a.b,"oj.TableDndContext");a.Qb.prototype.Init=function(){a.Qb.t.Init.call(this)};a.b.g("TableDndContext.prototype.Init",{Init:a.Qb.prototype.Init});a.Qb.prototype.yna=function(c){this.q().Wd(c).addClass(a.f.Da.zx);this.q().gia(c,!0,a.f.Da.zx)};a.Qb.prototype.nAa=
function(){var c=this.q().Uq().find("."+a.f.Da.zx);if(null!=c&&0<c.length){var b,d=c.length;for(b=0;b<d;b++)g(c[b]).removeClass(a.f.Da.zx)}this.q().gia(null,!1,a.f.Da.zx)};a.Qb.prototype.ppa=function(c){var b=g(c.find(a.f.Pa.KB)[0]),d=b.scrollLeft(),e=b.scrollTop();c=c.clone();var f=g(c.find(a.f.Pa.KB)[0]);f.css(a.f.O.DB,a.f.na.ml);f.css(a.f.O.Fx,a.f.na.ml);f.css(a.f.O.WG,a.f.na.ml);f.css(a.f.O.wka,a.f.na.bna);f.css(a.f.O.qe,b.width()+a.f.na.nc);f.css(a.f.O.Qp,b.height()+a.f.na.nc);c.css(a.f.O.eo,
a.f.na.gla);c.css(a.f.O.Ku,1E4);f.scrollLeft(1*d);f.scrollTop(1*e);g("body").append(c);return c};a.Qb.prototype.dI=function(){this.OR&&(this.OR.remove(),this.OR=null)};a.Qb.prototype.hv=function(a){return this.q().xe(g(a.currentTarget))};a.Qb.prototype.xta=function(c){var b;b=g(c.target).closest(a.f.Pa.Xp);b=(c=this.R.getContextByNode(c.target))&&"oj-table-cell"==c.subId?c.rowIndex:b&&b.hasClass(a.f.J.RP)?this.ps:(b=this.q().$e())?b.length:0;return b};a.Qb.prototype.q=function(){return this.R.q()};
a.Qb.prototype.BGa=function(a){if(this.nU()){var b=this.hv(a);this.kI=b;this.cCa(a,b);this.R.mz(null);this.R.option("selection",null,{_context:{Ed:!0,ob:!0}});setTimeout(function(){window.getSelection().removeAllRanges()},0);this.yna(b);return!0}};a.Qb.prototype.xGa=function(){this.nU()&&(this.iia(null,!1),this.kI=null,this.q().sN(),this.q().OIa(),this.nAa())};a.Qb.prototype.yGa=function(a){if(!this.CJ()){var b=this.hv(a);return this.bn("columns","dragEnter",a,{columnIndex:b})}};a.Qb.prototype.DGa=
function(a){var b=this.hv(a),d=this.kI;null!=d&&d!=b&&((this.cy=this.pU(a))&&d==b-1||!this.cy&&d==b+1||this.q().bea(b,this.cy),a.preventDefault())};a.Qb.prototype.AGa=function(a){if(this.CJ())return this.DGa(a);var b=this.hv(a);this.cy=this.pU(a);var d=this.bn("columns","dragOver",a,{columnIndex:b});(!1===d||a.isDefaultPrevented())&&this.q().bea(b,this.pU(a));return d};a.Qb.prototype.zGa=function(a){if(!this.CJ()){this.q().sN();var b=this.hv(a);return this.an("drop","columns","dragLeave",a,{columnIndex:b})}};
a.Qb.prototype.EGa=function(a){var b=this.hv(a);this.cy||b++;this.R.po=this.q().fIa(this.kI,b,a);a.preventDefault()};a.Qb.prototype.CGa=function(a){if(this.CJ())return this.EGa(a);this.q().sN();var b=this.hv(a);this.cy||b++;return this.bn("columns","drop",a,{columnIndex:b})};a.Qb.prototype.kHa=function(a){var b=this.options.dnd.drag;if(b&&b.rows)return(b=this.DBa(a,b.rows.dataTypes,this.R.Cy()))?this.an("drag","rows","dragStart",a,b):!1};a.Qb.prototype.fHa=function(a){return this.an("drag","rows",
"drag",a)};a.Qb.prototype.gHa=function(a){this.dI();return this.an("drag","rows","dragEnd",a)};a.Qb.prototype.hHa=function(a){var b=this.xta(a),d=this.bn("rows","dragEnter",a,{rowIndex:b});(!1===d||a.isDefaultPrevented())&&this.xDa(a,b);return d};a.Qb.prototype.jHa=function(a){return this.bn("rows","dragOver",a,{rowIndex:this.ps})};a.Qb.prototype.iHa=function(a){var b=this.an("drop","rows","dragLeave",a,{rowIndex:this.ps});this.oU(a,a.currentTarget)||(this.q().jZ(),this.ps=null);return b};a.Qb.prototype.lHa=
function(a){var b=this.ps;this.q().jZ();this.ps=null;return this.bn("rows","drop",a,{rowIndex:b})};a.Qb.prototype.ywa=function(c,b){var d;d=c.find("."+a.f.J.Wr);for(var e=d.length-1;0<=e;e--)-1==b.indexOf(e)&&g(d[e]).css(a.f.O.eQ,a.f.na.ml);d=g(c.find(a.f.Pa.$P));null!=d&&0<d.length&&d.css(a.f.O.eQ,a.f.na.ml);d=g(c.find(a.f.Pa.ZP));null!=d&&0<d.length&&d.css(a.f.O.eQ,a.f.na.ml)};a.Qb.prototype.an=function(c,b,d,e,f){c=this.options.dnd[c];var g;if(c&&c[b]&&(b=c[b][d])&&"function"==typeof b)try{e.dataTransfer=
e.originalEvent.dataTransfer,g=b(e,f)}catch(k){a.r.error("Error: "+k)}return g};a.Qb.prototype.bn=function(a,b,d,e){b=this.an("drop",a,b,d,e);void 0===b&&this.KU(d,a)&&d.preventDefault();return b};a.Qb.prototype.nU=function(){var a=this.options.dnd;return a&&a.reorder&&a.reorder.columns==this.R.uj?!0:!1};a.Qb.prototype.CJ=function(){return null!=this.kI};a.Qb.prototype.oU=function(a,b){var d=b.getBoundingClientRect(),e=a.originalEvent;return e.clientX>=d.left&&e.clientX<d.right&&e.clientY>=d.top&&
e.clientY<d.bottom};a.Qb.prototype.pU=function(c){var b=c.currentTarget.getBoundingClientRect();return null!=c.originalEvent.clientX?(c=b.right-c.originalEvent.clientX<(b.right-b.left)/2,"rtl"===a.u.wn()?c:!c):!1};a.Qb.prototype.KU=function(a,b){var d=a.originalEvent.dataTransfer.types,e=this.options.dnd.drop;if(e&&e[b]&&e[b].dataTypes)for(var e=e[b].dataTypes,e="string"==typeof e?[e]:e,f=0;f<d.length;f++)if(0<=e.indexOf(d[f]))return!0;return!1};a.Qb.prototype.LBa=function(c,b){if(c.draggable=b)g(c).css(a.f.O.J0,
a.f.na.Nla),g(c).addClass(a.f.Da.T0)};a.Qb.prototype.kpa=function(c){c.draggable="";g(c).css(a.f.O.J0,a.f.na.qj);g(c).removeClass(a.f.Da.T0)};a.Qb.prototype.CBa=function(a,b,d){a=a.dataTransfer;d=JSON.stringify(d);if("string"==typeof b)a.setData(b,d);else if(b)for(var e=0;e<b.length;e++)a.setData(b[e],d)};a.Qb.prototype.DBa=function(c,b,d){for(var e=[],f=0;f<d.length;f++){var h=this.R.getDataForVisibleRow(d[f]);h&&e.push(h)}return e.length?(this.CBa(c.originalEvent,b,e),this.OR=this.EBa(c.originalEvent,
g(c.currentTarget).closest(a.f.Pa.Tma).parent(),d),{rows:e}):null};a.Qb.prototype.EBa=function(c,b,d){var e=this.ppa(b);this.ywa(e,d);d=b[0].getBoundingClientRect();var f=g(b.find(a.f.Pa.KB)[0]);b=f.scrollLeft();f=f.scrollTop();c.dataTransfer.setDragImage(e[0],c.clientX-d.left+b,c.clientY-d.top+f);return e};a.Qb.prototype.cCa=function(a,b){var d=a.originalEvent.dataTransfer,e=this.q().rw(this.q().pGa());d.setData("Text",this.R.Uka+":"+e+":"+b);e=this.q().aFa(b);try{d.setDragImage(e[0],0,0)}catch(f){}};
a.Qb.prototype.iia=function(a,b){if(this.nU()){var d=this.q().aA();if(null!=d&&0<d.length){var e;for(e=0;e<d.length;e++){var f=d[e];null!=a&&e==a?this.LBa(f,b):this.kpa(f)}}}};a.Qb.prototype.xDa=function(c,b){if(this.ps!=b){var d=g(c.target).closest(a.f.Pa.Xp);this.ps=b;this.q().mFa(this.ps,d)}};a.eh={};a.eh.Fda=function(c,b,d){var e=g(b.headerContext.parentElement),f=g(document.createElement(a.f.Pa.gh));f.addClass(a.f.J.zG);e.empty();e.append(f);e=g(document.createElement(a.f.Pa.gh));e.addClass(a.f.J.sB);
f.prepend(e);null!=d?d(e):this.Gda(c,e,b)};a.eh.Hda=function(c,b,d){var e=b.columnIndex,f=c.gc()[e],h=g(b.headerContext.parentElement),e=g(document.createElement(a.f.Pa.gh));e.addClass(a.f.J.zG);h.empty();h.append(e);"rtl"===c.hd()?e.css(a.f.O.Fu,"0px"):e.css(a.f.O.Gu,"0px");h=g(document.createElement(a.f.Pa.gh));h.addClass(a.f.J.yG);e.append(h);var k=g(document.createElement(a.f.Pa.vu));k.addClass(a.f.J.yu);k.addClass(a.f.J.Mu);k.addClass(a.f.J.Bka);k.addClass(a.f.Da.ec);k.addClass(a.f.Da.xu);c.Qe(k);
h.append(k);var k=h.width(),l=h.height(),m=g(document.createElement(a.f.Pa.vu));m.attr(a.f.Gb.Vr,"0");m.attr(a.f.Gb.hP,"#");m.addClass(a.f.J.zka);m.addClass(a.f.J.ol);m.text(c.F("labelSortAsc")+" "+f.headerText);h.append(m);h=g(document.createElement(a.f.Pa.gh));h.addClass(a.f.J.H0);h.css(a.f.O.hf,a.f.na.rla);h.css(a.f.O.gna,a.f.na.Mla);h.css(a.f.O.qe,k+a.f.na.nc);h.css(a.f.O.Qp,l+a.f.na.nc);e.append(h);h=g(document.createElement(a.f.Pa.gh));h.addClass(a.f.J.CG);h.addClass(a.f.Da.ec);e.append(h);
k=g(document.createElement(a.f.Pa.vu));k.addClass(a.f.J.ux);k.addClass(a.f.J.Mu);k.addClass(a.f.J.Cka);k.addClass(a.f.Da.ec);k.addClass(a.f.Da.xu);c.Qe(k);h.append(k);k=g(document.createElement(a.f.Pa.vu));k.attr(a.f.Gb.Vr,"0");k.attr(a.f.Gb.hP,"#");k.addClass(a.f.J.Aka);k.addClass(a.f.J.ol);k.text(c.F("labelSortDsc")+" "+f.headerText);h.append(k);f=g(document.createElement(a.f.Pa.gh));f.addClass(a.f.J.sB);e.prepend(f);null!=d?d(f):this.Gda(c,f,b)};a.eh.Gda=function(a,b,d){d=d.columnIndex;a=a.gc()[d];
b.text(a.headerText)};a.eh.zJa=function(a,b,d,e){var f=g(e.rowContext.parentElement),h=a.q().rw(d.key),k=a.gc();a.q().zZ(d,f);k=k.length;for(f=0;f<k;f++)this.yJa(a,b,f,d,h,e)};a.eh.yJa=function(c,b,d,e,f,h){h=g(h.rowContext.parentElement);var k=c.gc()[d],l=c.q().TEa();c.q().EZ(d,l,!0);c.q().vHa(b,e.key,f,d,l,h);var m=null;null!=k.field&&(m=e.data[k.field]);if(k=c.qs(d,"cell")){var s=this.Xz(c,l[0],{row:e}),m=k({cellContext:s,columnIndex:d,data:m,row:g.extend({},e.data)});null!=m?l.append(m):(l=g(h.children(":not(."+
a.f.J.OP+")")[d]),c.q().yZ(b,e.key,f,d,l),c.q().EZ(d,l,!1))}else l.text(m)};a.eh.Xz=function(c,b,d){var e={};e.component=a.Components.Mf(c.element,"ojTable");var f=c.Lb();f instanceof a.Fa&&(f=f.getWrappedDataSource());e.datasource=f;e.parentElement=b;if(null!=d.row&&(b=d.row,d=b.key,e.status=this.$Fa(c,b),c.uv()?a.b.Rj(d,c.mI)?e.mode="edit":e.mode="navigation":e.mode="navigation",f instanceof a.Ob)){c=f.OS(b.index);for(var g in c)c.hasOwnProperty(g)&&(e[g]=c[g])}return e};a.eh.$Fa=function(a,b){return{rowIndex:b.index,
rowKey:b.key,currentRow:g.extend({},a.LC())}};a.Components.Ta("ojTable","baseComponent",{properties:{accessibility:{type:"Object\x3cstring, string\x3e"},columns:{type:"Array\x3cObject\x3e"},columnsDefault:{type:"Object\x3cstring, string|null\x3e"},currentRow:{type:"Object"},data:{},display:{type:"string"},dnd:{type:"Object"},editMode:{type:"string"},emptyText:{type:"string"},horizontalGridVisible:{type:"string"},rowRenderer:{},scrollPolicy:{type:"string"},scrollPolicyOptions:{type:"Object\x3cstring, string\x3e"},
selection:{type:"Array\x3cObject\x3e"},selectionMode:{type:"Object\x3cstring, string\x3e"},verticalGridVisible:{type:"string"}},methods:{getContextByNode:{},getDataForVisibleRow:{},getNodeBySubId:{},getSubIdByNode:{},refresh:{},refreshRow:{},widget:{}},extension:{_hasWrapper:!0,_innerElement:"table",_widgetName:"ojTable"}});a.Components.register("oj-table",a.Components.getMetadata("ojTable"))});