/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojs/ojdvt-base","ojs/internal-deps/dvt/DvtThematicMap"],function(a,g,c,b,d){a.Na("oj.ojThematicMap",g.oj.dvtBaseComponent,{widgetEventPrefix:"oj",options:{load:null,optionChange:null},X4:"",rD:[],w3:"resources/internal-deps/dvt/thematicMap/basemaps/",rca:{ar:"ar",cs:"cs",da:"da",de:"de",el:"el",es:"es",fi:"fi",fr:"fr","fr-ca":"fr_CA",he:"iw",hu:"hu",it:"it",ja:"ja",ko:"ko",nl:"nl",no:"no",pl:"pl",pt:"pt_BR","pt-pt":"pt",ro:"ro",ru:"ru",sk:"sk",
sv:"sv",th:"th",tr:"tr","zh-hans":"zh_CN","zh-hant":"zh_TW"},_ComponentCreate:function(){this._super();this.Ru=[];this.b9=!1;this.dy=[]},zg:function(a,b,c){return d.ThematicMap.newInstance(a,b,c)},pk:function(a){var b=a.subId;"oj-thematicmap-area"==b?b=a.dataLayer+":area["+a.index+"]":"oj-thematicmap-marker"==b?b=a.dataLayer+":marker["+a.index+"]":"oj-thematicmap-link"==b?b=a.dataLayer+":link["+a.index+"]":"oj-thematicmap-tooltip"==b&&(b="tooltip");return b},Ih:function(a){var b={};0<a.indexOf(":area")?
(b.subId="oj-thematicmap-area",b.dataLayer=a.substring(0,a.indexOf(":")),b.index=this.tk(a)):0<a.indexOf(":marker")?(b.subId="oj-thematicmap-marker",b.dataLayer=a.substring(0,a.indexOf(":")),b.index=this.tk(a)):0<a.indexOf(":link")?(b.subId="oj-thematicmap-link",b.dataLayer=a.substring(0,a.indexOf(":")),b.index=this.tk(a)):"tooltip"==a&&(b.subId="oj-thematicmap-tooltip");return b},Cf:function(){var a=this._super();a.push("oj-thematicmap");return a},qk:function(){var a=this._super();a["oj-dvtbase oj-thematicmap"]=
{path:"animationDuration",property:"animation-duration"};a["oj-thematicmap-arealayer"]=[{path:"styleDefaults/areaStyle",property:"CSS_BACKGROUND_PROPERTIES"},{path:"styleDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"}];a["oj-thematicmap-area"]={path:"styleDefaults/dataAreaDefaults/borderColor",property:"border-top-color"};a["oj-thematicmap-area oj-hover"]={path:"styleDefaults/dataAreaDefaults/hoverColor",property:"border-top-color"};a["oj-thematicmap-area oj-selected"]=[{path:"styleDefaults/dataAreaDefaults/selectedInnerColor",
property:"border-top-color"},{path:"styleDefaults/dataAreaDefaults/selectedOuterColor",property:"border-bottom-color"}];a["oj-thematicmap-marker"]=[{path:"styleDefaults/dataMarkerDefaults/labelStyle",property:"CSS_TEXT_PROPERTIES"},{path:"styleDefaults/dataMarkerDefaults/color",property:"background-color"},{path:"styleDefaults/dataMarkerDefaults/opacity",property:"opacity"},{path:"styleDefaults/dataMarkerDefaults/borderColor",property:"border-top-color"}];a["oj-thematicmap-link"]={path:"styleDefaults/linkDefaults/color",
property:"color"};a["oj-thematicmap-link oj-hover"]={path:"styleDefaults/linkDefaults/_hoverColor",property:"color"};a["oj-thematicmap-link oj-selected"]={path:"styleDefaults/linkDefaults/_selectedColor",property:"border-color"};return a},rj:function(){return["load","optionChange"]},_setOptions:function(b,c){var d=Object.keys(b).length,g=b.areaLayers,l=this.options.areaLayers,m=b.pointDataLayers;if(1==d&&g&&l&&0<l.length)for(d=0;d<g.length;d++){var m=g[d],s=l[d],t=!0,r;for(r in m)"areaDataLayer"!=
r&&m[r]!=s[r]&&(t=t&&!1);t&&!a.b.Rj(s.areaDataLayer,m.areaDataLayer)&&this.dy.push({options:m.areaDataLayer,parentLayer:m.layer,isADL:!0})}else if(1==d&&m&&this.options.pointDataLayers&&0<this.options.pointDataLayers.length)for(d=0;d<m.length;d++)a.b.Rj(this.options.pointDataLayers[d],m[d])||this.dy.push({options:m[d],parentLayer:m[d].id,isADL:!1});this._super(b,c)},Mh:function(){this.J1();var b=this.options.areaLayers;if(this.options.basemap&&b&&!(1>b.length)){this.Xxa();for(var c=0;c<this.Ru.length;c++)if(!this.rD[this.Ru[c]])return;
this.Ru=[];this.wDa();var d=(c=this.options.tooltip)?c.renderer:null;d&&(this.options._tooltip=function(b){var c=b.tooltip;try{return d(b)||c}catch(e){return a.r.warn("Showing default tooltip. "+e),c}});if(b)for(c=0;c<b.length;c++){var g=b[c].areaDataLayer;if(g){var l=g._templateRenderer;l&&(g.renderer=this.gJ(l,g.markers))}}if(b=this.options.pointDataLayers)for(c=0;c<b.length;c++)(g=b[c])&&(l=g._templateRenderer)&&(g.renderer=this.gJ(l,g.markers));this.options._contextHandler=this.sS();if(this.b9&&
0<this.dy.length){if(this.ag.isReadyToRender()){for(c=0;c<this.dy.length;c++)l=this.dy[c],this.xa.updateLayer(l.options,l.parentLayer,l.isADL);this.dy=[]}}else this._super(),this.b9=!0;this._trigger("load",null,null)}},gJ:function(a){var b=this;return function(c){var d=document.createElement("div");d.style.display="none";d.vC=b.ag;b.element.append(d);a({parentElement:d,data:c.data});return(c=d.children[0])?"http://www.w3.org/2000/svg"===c.namespaceURI?(d.removeChild(c),g(d).remove(),c):b.wB(c):null}},
sS:function(){var b=this;return function(c,d,g,l,m){return{component:a.Components.Mf(b.element),parentElement:c,rootElement:d,data:g,state:l,previousState:m,id:g.id,label:g.label,color:g.color,location:g.location,x:g.x,y:g.y}}},renderDefaultHover:function(a){a.previousState&&a.state.hovered==a.previousState.hovered||this.xa.processDefaultHoverEffect(a.id,a.state.hovered)},renderDefaultSelection:function(a){a.previousState&&a.state.selected==a.previousState.selected||this.xa.processDefaultSelectionEffect(a.id,
a.state.selected)},renderDefaultFocus:function(a){a.previousState&&a.state.focused==a.previousState.focused||this.xa.processDefaultFocusEffect(a.id,a.state.focused)},Xxa:function(){var b=this.options.basemap;if(b){var c=a.fa.Wi();c!==this.X4&&(this.X4=c,this.rD=[]);var d=this.options.areaLayers;if(d)for(var g=0;g<d.length;g++){var l=d[g].layer;l&&this.S9(b,l,c)}d=this.options.pointDataLayers;!this.options.mapProvider&&d&&0<d.length&&this.S9(b,"cities",c)}},V9:function(b,c){if(!this.rD[b]){var d=this,
k=g.getScript(a.fa.eb(b),function(){d.rD[b]=!0;d.Mh()});c&&k.fail(function(){d.rD[b]=!0;d.Mh()})}},S9:function(b,c,g){var k=!0;try{k=0<Object.keys(d.DvtBaseMapManager.getLayerIds(b,c)).length}catch(l){k=!1}k||((k=this.options.mapProvider)?a.lb.GFa(b,c,k):(k=this.w3+"ojthematicmap-"+b+"-"+c+".js",-1==this.Ru.indexOf(k)&&(this.Ru.push(k),this.V9(k,!1))));if(-1===g.indexOf("en"))for(k=g.toLowerCase().split("-"),g=[k[0]],1<k.length&&g.unshift(k[0]+"-"+k[1]),2<k.length&&g.unshift(k[0]+"-"+k[2],k[0]+"-"+
k[1]+"-"+k[2]),b=b.charAt(0).toUpperCase()+b.slice(1),c=c.charAt(0).toUpperCase()+c.slice(1),b=this.w3+"resourceBundles/"+b+c+"Bundle_",c=0;c<g.length;c++)if(this.rca[g[c]]){b=b+this.rca[g[c]]+".js";-1==this.Ru.indexOf(b)&&(this.Ru.push(b),this.V9(b,!0));break}},ql:function(a){if("selection"===a.type){var b={},c=a.clientId;b[c]=a.selection;if(this.options.selection)for(var d in this.options.selection)c!==d&&(b[d]=this.options.selection[d]);this.ce("selection",b)}else this._super(a)},Ji:function(){var a=
this.options.translations,b=this._super();b["DvtUtilBundle.THEMATIC_MAP"]=a.componentName;return b},wDa:function(){var a=this.options.selection;if(a){var b=this.options.pointDataLayers;if(b)for(var c=0;c<b.length;c++)a[b[c].id]&&(b[c].selection=a[b[c].id]);if(b=this.options.areaLayers)for(c=0;c<b.length;c++){var d=b[c].areaDataLayer;d&&a[d.id]&&(d.selection=a[d.id])}}},getArea:function(a,b){var c=this.xa.getAutomation().getData(a,"area",b);this.Hi(c);return c},getMarker:function(a,b){var c=this.xa.getAutomation().getData(a,
"marker",b);this.Hi(c);return c},getLink:function(a,b){var c=this.xa.getAutomation().getData(a,"link",b);this.Hi(c);return c},getContextByNode:function(a){return(a=this.getSubIdByNode(a))&&"oj-thematicmap-tooltip"!==a.subId?a:null},rk:function(){return{areaLayers:["areaDataLayer/areas","areaDataLayer/markers"],pointDataLayers:["markers","links"]}},c1:function(a){var b=this.options.basemap;a=a.layer?a.layer:"cities";return{basemap:b,layer:a,ids:d.DvtBaseMapManager.getLayerIds(b,a)}}});a.lb={};a.lb.SG=
"DvtBaseMapManager";a.lb.H2="_UNPROCESSED_MAPS";a.lb.Yp="type";a.lb.jla="geometry";a.lb.Fka="coordinates";a.lb.fla="features";a.lb.sma="properties";a.lb.ena="FeatureCollection";a.lb.pKa="GeometryCollection";a.lb.dna="Feature";a.lb.G2="Polygon";a.lb.F2="MultiPolygon";a.lb.rl="id";a.lb.Nma="shortLabel";a.lb.Hla="longLabel";a.lb.GFa=function(b,c,d){var g={},l={},m=d.geo,s=d.propertiesKeys||{};d=m[a.lb.Yp];if(d===a.lb.ena)m[a.lb.fla].forEach(function(b){a.lb.oha(b,s,l,g)});else if(d===a.lb.dna)a.lb.oha(m,
s,l,g);else{a.r.error("GeoJSON type of "+d+" is not supported. Only Feature and FeatureCollection types are supported.");return}0===Object.keys(l).length?a.r.error("No valid Features found in GeoJSON."):(window[a.lb.SG]||(window[a.lb.SG]={},window[a.lb.SG][a.lb.H2]=[[],[],[]]),window[a.lb.SG][a.lb.H2][0].push([b,c,g,l,null,null,0]))};a.lb.oha=function(b,c,d,g){var l=b[a.lb.sma];b=b[a.lb.jla];if(a.lb.NHa(b)){var m=l[c[a.lb.rl]];if(m){var s=l[c[a.lb.Nma]];c=l[c[a.lb.Hla]];if(s||c)g[m]=[s,c];d[m]=a.lb.HFa(b)}else a.r.warn("No 'id' value found in the mapProvider.propertiesKey object. A Feature's 'properties' object must have an id in the field specified by the mapProvider.propertiesKey.id value.")}else a.r.warn("A geometry of type "+
b[a.lb.Yp]+" is not supported and will be skipped.")};a.lb.NHa=function(b){b=b[a.lb.Yp];return b===a.lb.G2||b===a.lb.F2?!0:!1};a.lb.HFa=function(b){var c="",d=b[a.lb.Yp];b=b[a.lb.Fka];d===a.lb.G2?c=a.lb.tha(b):d===a.lb.F2&&b.forEach(function(b){c+=a.lb.tha(b)});return c};a.lb.tha=function(b){var c="";b.forEach(function(b){c+=a.lb.SHa(b)});return c};a.lb.SHa=function(a){var b,c,d,g="M";a&&a.forEach(function(a){var e=a[0];a=-a[1];if("M"===g)c=e,d=a,g="x",b="M"+e+" "+a;else{var t=e-c,r=a-d;if("l"==g){if(c==
e){g="v";d=a;b=b+g+r;return}if(d==a){g="h";c=e;b=b+g+t;return}b=b+" "+t+" "+r}else g="l",b=b+"l"+t+" "+r;c=e;d=a}});return b+"Z"};a.Components.Ta("ojThematicMap","dvtBaseComponent",{properties:{animationDuration:{type:"number"},animationOnDisplay:{type:"string"},animationOnMapChange:{type:"string"},areaLayers:{type:"Array\x3cobject\x3e"},basemap:{type:"string"},hiddenCategories:{type:"Array\x3cstring\x3e"},highlightedCategories:{type:"Array\x3cstring\x3e"},highlightMatch:{type:"string"},hoverBehavior:{type:"string"},
initialZooming:{type:"string"},mapProvider:{type:"object"},markerZoomBehavior:{type:"string"},maxZoom:{type:"number"},panning:{type:"string"},pointDataLayers:{type:"Array\x3cobject\x3e"},selection:{type:"object"},styleDefaults:{type:"object"},tooltip:{type:"object"},tooltipDisplay:{type:"string"},touchResponse:{type:"string"},zooming:{type:"string"}},methods:{getArea:{},getContextByNode:{},getLink:{},getMarker:{},renderDefaultFocus:{},renderDefaultHover:{},renderDefaultSelection:{}},extension:{_widgetName:"ojThematicMap"}});
a.Components.register("oj-thematic-map",a.Components.getMetadata("ojThematicMap"))});