/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,g){(function(){a.Na("oj.ojToolbar",g.oj.baseComponent,{widgetEventPrefix:"oj",options:{chroming:"half"},Xf:function(c,b){this._super(c,b);"disabled"in b&&a.r.warn("Caller attempted to set the 'disabled' option on Toolbar, but Toolbar does not support the 'disabled' option.  See API doc.")},_ComponentCreate:function(){this._super();this.element.attr(a.Components.co,this.widgetName).addClass("oj-toolbar oj-component").attr("role","toolbar");
this.$a(!0)},ih:function(a,b,d){a=this.element.find(":oj-button[tabindex\x3d0]");this.jh(b,d,{launcher:a,position:{of:"keyboard"===d?a.ojButton("widget"):b}})},_setOption:function(c,b){"disabled"===c?a.r.warn("Caller attempted to set the 'disabled' option on Toolbar, but Toolbar does not support the 'disabled' option.  See API doc.  Ignoring the call."):(this._superApply(arguments),"chroming"===c&&(this.IN.ojButtonset("refresh"),this.YZ.ojButton("refresh")))},refresh:function(){this._super();this.$a(!1)},
$a:function(a){var b=this;this.Xk="rtl"===this.hd();this.wf=this.element.find(":oj-button").unbind("keydown"+this.eventNamespace).bind("keydown"+this.eventNamespace,function(a){b.pv(a,g(this))}).unbind("click"+this.eventNamespace).bind("click"+this.eventNamespace,function(){g(this).ojButton("option","disabled")||b.Tv(g(this))}).unbind("focus"+this.eventNamespace).bind("focus"+this.eventNamespace,function(){b.Tv(g(this))});this.IN=this.element.find(":oj-buttonset").ojButtonset("refresh");this.YZ=this.wf.not(this.IN.find(":oj-button")).ojButton("refresh");
this.Ip=this.wf.filter(function(){return!g(this).ojButton("option","disabled")});this.hU(a)},hU:function(a){var b=g(this.Fv);this.Fv=void 0;this.wf.attr("tabindex","-1");a=a||!b.is(this.Ip)?this.Ip.first():b;this.Tv(a)},HU:function(a){var b=this.Ip;return a.map(function(a,c){if("radio"!=c.type||c.checked||""==c.name)return c;var f=c.name;f?(f=f.replace(/'/g,"\\'"),f=b.filter(":radio[name\x3d'"+f+"']:oj-button")):f=b.filter(c).filter(":oj-button");f=f.filter(":checked");return f.length?f[0]:c})},Tv:function(a){a=
this.HU(a);var b=a[0],d=this.Fv;b!==d&&(g(d).attr("tabindex","-1"),a.attr("tabindex","0"),this.Fv=b)},pv:function(a,b){switch(a.which){case g.ui.keyCode.LEFT:case g.ui.keyCode.RIGHT:a.preventDefault();var d=this.Ip,e=d.length;if(2>e)break;var f=d.index(b);d.eq((f+(a.which==g.ui.keyCode.RIGHT^this.Xk?1:-1)+e)%e).focus();break;case g.ui.keyCode.UP:case g.ui.keyCode.DOWN:"radio"==b.attr("type")&&a.preventDefault()}},_destroy:function(){this.element.removeClass("oj-toolbar oj-component").removeAttr(a.Components.co).removeAttr("role");
this.wf.attr("tabindex","0");this.IN.ojButtonset("refresh");this.YZ.ojButton("refresh")}})})();a.Components.Dp({ojToolbar:{chroming:a.Components.Lf(function(){return(a.nd.uf("oj-toolbar-option-defaults")||{}).chroming})}});a.Components.Ta("ojToolbar","baseComponent",{properties:{chroming:{type:"string"},disabled:{}},methods:{destroy:{},refresh:{},widget:{}},extension:{_widgetName:"ojToolbar"}});a.Components.register("oj-toolbar",a.Components.getMetadata("ojToolbar"))});