/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
/*
 Copyright 2013 jQuery Foundation and other contributors
 Released under the MIT license.
 http://jquery.org/license
*/
define(["ojs/ojcore","jquery","ojs/ojcomponentcore"],function(a,g){(function(){a.Na("oj.ojTrain",g.oj.baseComponent,{version:"1.0.0",defaultElement:"\x3cdiv\x3e",widgetEventPrefix:"oj",options:{steps:[],selected:"",optionChange:null,beforeDeselect:null,deselect:null,beforeSelect:null,select:null},Lg:0,hc:null,_ComponentCreate:function(){this._super();this.Uba()},Uba:function(){var a=this.options,b=a.steps;this.Lg=b.length;this.Eq=g("\x3cdiv class\x3d'oj-train-wrapper'\x3e\x3c/div\x3e");this.Eq.appendTo(this.element);
this.SH=g("\x3cdiv class\x3d'oj-train-connector-wrapper'\x3e\x3c/div\x3e");this.SH.appendTo(this.Eq);var d=this.element.attr("class");(this.nca=null!=d&&0<=d.indexOf("oj-train-stretch"))&&this.SH.css("padding","0 "+100/(2*this.Lg)+"%");this.x4=g("\x3cdiv class\x3d'oj-train-connector'\x3e\x3c/div\x3e");this.x4.appendTo(this.SH);this.jg=g("\x3cul\x3e");this.jg.addClass("oj-train-step-list");this.jR=g("\x3cdiv class\x3d'oj-train-connector-fill'\x3e\x3c/div\x3e");this.jR.appendTo(this.SH);this.lCa();
this.ln=this.Ey(a.selected);-1===this.ln&&b[0]&&b[0].id&&(this.ln=0,a.selected=b[0].id);for(a=0;a<this.Lg;a++)b=g("\x3cli\x3e").addClass("oj-train-step-list-item").attr({id:this.hc[a][1]}),d=this.hc[a][4],"confirmation"===d?b.addClass("oj-confirmation"):"info"===d?b.addClass("oj-info"):"error"===d||"fatal"===d?b.addClass("oj-invalid"):"warning"===d&&b.addClass("oj-warning"),b.appendTo(this.jg),this.vra(a),this.yra(a),this.ura(a),this.tra(a),this.zra(a),this.wra(a),this.nca&&b.css("width",100/this.Lg+
"%");this.jR.css({width:(this.Lg-1===this.ln?100:100/(2*(this.Lg-1))+this.ln/(this.Lg-1)*100)+"%"});this.jg.appendTo(this.Eq);this.element.addClass("oj-train")},lCa:function(){var a=this.options;this.hc=[];for(var b=0;b<this.Lg;b++){var d=a.steps[b];this.hc[b]=Array(5);this.hc[b][0]=d.label?d.label:null;this.hc[b][1]=d.id?d.id:null;this.hc[b][2]=d.disabled?!0:!1;this.hc[b][3]=d.visited?!0:!1;this.hc[b][4]=d.messageType?d.messageType:null}},tra:function(a){var b=g("\x3cdiv/\x3e").addClass("oj-train-button"),
d=g("\x3cspan/\x3e"),e=this,f="";if(this.hc[a]){var h=this.hc[a][3],k=this.hc[a][2];this.ln===a?(b.addClass("oj-selected"),f=" current "):h&&!k?(b.addClass("oj-visited"),f=" visited "):h||k?b.addClass("oj-disabled"):(b.addClass("oj-default"),f=" not visited ");this.hc[a][2]||this.ln===a||(this.Qe(b),this.ok(b),b.on("click"+this.eventNamespace,function(a){e.tI("selected",e.options.selected,this.parentNode.parentNode.id,a);e.refresh()}));h=this.jg.children().eq(a).find(".oj-train-button-connector");
1<=h.length&&h.children().remove();h.append(b);d.text(f);d.addClass("oj-helper-hidden-accessible");this.jg.children().eq(a).find("a").append(d)}},wra:function(a){if(this.hc[a]&&this.hc[a][4]){var b=g("\x3cdiv/\x3e").addClass("oj-train-icon oj-component-icon"),d=g("\x3cspan/\x3e"),e="",f=this,h=this.hc[a][4];"confirmation"===h?(b.addClass("oj-confirmation"),e=" Confirmation "):"info"===h?(b.addClass("oj-info"),e=" Info "):"error"===h?(b.addClass("oj-error"),e=" Error "):"fatal"===h?(b.addClass("oj-error"),
e=" Error "):"warning"===h&&(b.addClass("oj-warning"),e=" Warning ");var k=this.jg.children().eq(a).find(".oj-train-button");2<=k.children().length&&k.children()[1].remove();if(!this.hc[a][2]&&this.ln!==a)b.on("click"+this.eventNamespace,function(a){f.tI("selected",f.options.selected,this.parentNode.parentNode.parentNode.id,a);f.refresh()});null!=h&&(d.text(e),d.addClass("oj-helper-hidden-accessible"),this.jg.children().eq(a).find("a").append(d),k.append(b))}},tI:function(a,b,d,e){a={option:a,fromStep:this.getStep(b),
toStep:this.getStep(d),optionMetadata:{writeback:e?"shouldWrite":"shouldNotWrite"}};!1!==this._trigger("beforeDeselect",e,a)&&!1!==this._trigger("beforeSelect",e,a)&&(b=this.Ey(b),-1!==b&&(this.options.steps[b].visited=!0),this._trigger("deselect",e,a),this.option("selected",d,{_context:{originalEvent:e,ob:!0}}),this._trigger("select",e,a))},zra:function(a){var b=g("\x3cdiv/\x3e").addClass("oj-train-button-text");b.append((a+1).toString());this.jg.children().eq(a).find(".oj-train-button").append(b)},
ura:function(a){if(a!=this.Lg-1){var b=g("\x3cdiv/\x3e").addClass("oj-train-step-individual-connector");this.jg.children().eq(a).prepend(b)}},yra:function(a){var b=g("\x3cdiv/\x3e");b.addClass("oj-train-button-connector");this.hc[a]&&(a<=this.ln&&b.addClass("oj-train-fill"),a=this.jg.children().eq(a).children(),b.insertBefore(a))},vra:function(a){var b=this;if(this.hc[a]){var d=g("\x3cdiv/\x3e").addClass("oj-train-label-wrapper"),e=g("\x3ca\x3e");e.text(this.hc[a][0]);var f=this.hc[a][2];d.append(e);
e.addClass("oj-train-label");a===this.ln?e.addClass("oj-selected"):this.hc[a][3]&&!f?e.addClass("oj-visited"):f&&e.addClass("oj-disabled");f||(e.attr("href","#"),this.Qe(e),this.ok(e),e.on("click keydown"+this.eventNamespace,function(a){if(a.keyCode===g.ui.keyCode.ENTER||"click"===a.type)a.preventDefault(),b.tI("selected",b.options.selected,this.parentNode.parentNode.id,a),b.refresh(),a.keyCode===g.ui.keyCode.ENTER&&b.Nj(this.parentNode.parentNode.id)}));e=this.jg.children().eq(a).children();2<=e.length&&
e[1].remove();this.jg.children().eq(a).append(d)}},Ey:function(a){for(var b=0;b<this.Lg;b++)if(this.hc[b]&&this.hc[b][1]===a)return b;return-1},getStep:function(a){for(var b=0;b<this.Lg;b++)if(this.hc[b]&&this.hc[b][1]===a)return jQuery.extend({},this.options.steps[b]);return null},nextSelectableStep:function(){for(var a=this.Ey(this.options.selected);a<this.Lg;a++)if(a+1<this.Lg&&this.hc[a+1]&&!this.hc[a+1][2])return this.hc[a+1][1];return null},previousSelectableStep:function(){for(var a=this.Ey(this.options.selected);0<=
a;a--)if(this.hc[a-1]&&!this.hc[a-1][2])return this.hc[a-1][1];return null},setStep:function(a){if(a.id){var b=this.getStep(a.id),d=this.Ey(a.id);-1!==d&&(d=this.options.steps[d],a.label&&(b[0]=a.label,d.label=a.label),"boolean"===typeof a.disabled&&(b[2]=a.disabled,d.disabled=a.disabled),"boolean"===typeof a.visited&&(b[3]=a.visited,d.visited=a.visited),a.messageType&&(b[4]=a.messageType,d.messageType=a.messageType));this.refresh()}},_setOptions:function(a){this._super(a);this.refresh()},_setOption:function(a,
b,d){"selected"===a&&this.options.selected&&this.hc&&this.hc[this.ln]&&this.tI("selected",this.hc[this.ln][1],b,null);this._super(a,b,d)},refresh:function(){this._super();this._destroy();this.Uba()},_destroy:function(){this.jg.children().each(function(){g(this).remove()});this.element.removeClass("oj-train");this.element.find(".oj-train-wrapper").remove();this.element.find(".oj-train-connector-wrapper").remove();this.element.find(".oj-train-step-list").remove();this.element.find(".oj-train-step-list").remove();
this._super()},Nj:function(a){a=this.Ey(a);for(var b=0;b<this.Lg;b++)if(this.hc[(a+b+1)%this.Lg]&&!this.hc[(a+b+1)%this.Lg][2]){this.jg.children().eq((a+b+1)%this.Lg).find(".oj-train-label").focus();break}},getNodeBySubId:function(a){if(null===a)return this.element?this.element[0]:null;var b=a.index;if("number"!==typeof b||0>b||b>=this.Lg)return null;switch(a.subId){case "oj-train-step":return this.jg.children().eq(b)[0];case "oj-train-button":return this.jg.children().eq(b).find(".oj-train-button")[0];
case "oj-train-button-connector":return this.jg.children().eq(b).find(".oj-train-button-connector")[0];case "oj-train-connector":return this.x4;case "oj-train-connector-fill":return this.jR;case "oj-train-icon":return this.jg.children().eq(b).find(".oj-train-icon")[0];case "oj-train-label":return this.jg.children().eq(b).find(".oj-train-label")[0]}return null},getSubIdByNode:function(a){for(var b=this.hc?this.hc.length:0,d=0;d<b;d++){var e={subId:"oj-train-step",index:d};if(a===this.getNodeBySubId(e))return e}return null}})})();
a.Components.Ta("ojTrain","baseComponent",{properties:{selected:{},steps:{}},methods:{getStep:{},nextSelectableStep:{},previousSelectableStep:{},refresh:{},setStep:{}},extension:{_widgetName:"ojTrain"}});a.Components.register("oj-train",a.Components.getMetadata("ojTrain"))});