/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojs/ojcomponentcore","ojdnd"],function(a,g){function c(){}c.tl="oj-expanded";c.Kh="oj-collapsed";c.Eu="oj-hover";c.Lm="oj-selected";c.Se="oj-disabled";c.mKa="oj-default";c.Ex="oj-treenode-temp";a.wa=function(a){this.Init(a)};a.b.ta(a.wa,a.b,"oj.TreeDndContext");a.wa.prototype.Init=function(b){a.wa.t.Init.call(this);this.R=b;this.options=b.options;this.Naa()};a.b.g("TreeDndContext.prototype.Init",{Init:a.wa.prototype.Init});a.wa.prototype.iga=function(){var a=this.Gd;
return a.reorder||a.Ui};a.wa.prototype.EHa=function(){var a=this.Gd;return a.reorder||a.tn};a.wa.prototype.OGa=function(){var b=this.Gd,c=a.wa,e=b.reorder,f=b.Ui;this.t5();this.dga();b=this.Gd;if(e!=b.reorder||f!=b.Ui)b.reorder||b.Ui||this.R.sa.find("li").removeClass(c.uP).removeClass(c.UG).removeClass(c.Pr).removeAttr("draggable");this.cga()};a.wa.prototype.dga=function(){var b=this.options.dnd,c=this.Gd,e=a.wa,f=!0,h;c.reorder=!1;"object"!=typeof b?this.options.dnd={reorder:"disable"}:(h=b[e.Tka],
"string"===typeof h&&("enable"===h?(c.reorder=!0,f=!1):"disable"==h&&(f=!1)),f&&(this.options.dnd.reorder="disable"),h=b[e.Kka],"object"==typeof h&&(h=h[e.S0],"object"==typeof h&&(f=h[e.Nka],"function"==typeof f&&(c.ME=f,c.Ui=!0),f=h[e.Lka],"function"==typeof f&&(c.HL=f,c.Ui=!0),f=h[e.Mka],"function"==typeof f&&(c.rX=f,c.Ui=!0),f=h[e.R0],g.isArray(f)?(c.iw=f.slice(),c.Ui=!0):"string"==typeof f&&(c.iw=[f],c.Ui=!0))),h=b[e.Oka],"object"==typeof h&&(h=h[e.S0],"object"==typeof h&&(f=h[e.Pka],"function"==
typeof f&&(c.JL=f,c.tn=!0),f=h[e.Rka],"function"==typeof f&&(c.ML=f,c.tn=!0),f=h[e.Qka],"function"==typeof f&&(c.KL=f,c.tn=!0),f=h[e.Ska],"function"==typeof f&&(c.NL=f,c.tn=!0),f=h[e.R0],g.isArray(f)?(c.IL=f.slice(),c.tn=!0):"string"==typeof f&&(c.IL=[f],c.tn=!0))),c.reorder||(c.iw||c.ME||(c.Ui=!1,c.ME=c.HL=c.rX=c.iw=null),c.NL||(c.tn=!1,c.JL=c.ML=c.KL=c.NL=c.IL=null)),c.nN=c.reorder&&!c.Ui)};a.wa.prototype.cga=function(){var b=this.Gd,c=b.vf,e=a.wa;if(b.Ui||b.tn||b.reorder){a.wa.z5?(c.qp=a.wa.z5,
c.jm=a.wa.qra):(c.qp=g("\x3cdiv class\x3d'oj-tree-drop-marker'\x3e\x3cspan class\x3d'oj-tree-drop-ptr oj-component-icon'\x3e\x26#160;\x3c/span\x3e\x3c/div\x3e").css("pointer-events","none").hide().appendTo("body"),c.jm=g("\x3cdiv /\x3e").addClass(e.Wla).css("pointer-events","none").hide().appendTo("body"),a.wa.z5=c.qp,a.wa.qra=c.jm);b.Xga=c.jm.width();var c=this.R.element[0],f=g(c).children("ul:eq(0)");if(b.reorder||b.Ui)b.BX=this.QR.bind(this),b.xX=this.nra.bind(this),g(c).on("dragstart",b.BX),g(c).on("dragend",
b.xX),f.length&&f.find("li").addClass(e.uP).addClass(e.UG).addClass(e.Pr).attr("draggable","true");if(b.reorder||b.tn)b.vX=this.lra.bind(this),b.yX=this.ora.bind(this),b.AX=this.sra.bind(this),b.zX=this.pra.bind(this),b.wX=this.mra.bind(this),g(c).on("drag",b.vX),g(c).on("dragenter",b.yX),g(c).on("dragover",b.AX),g(c).on("dragleave",b.zX),g(c).on("drop",b.wX)}};a.wa.prototype.vpa=function(){this.t5()};a.wa.prototype.QR=function(b){var d,e,f=g(b.target).closest("li"),h=b.originalEvent.dataTransfer,
k;d=this.Gd;e=d.vf;e.lc=null;e.Sa=null;d.Hw=null;d.$Y=null;d.KF=null;d.NE=!1;if(!d.reorder&&!d.Ui||f.hasClass(c.Se)||this.R.i.la.locked)b.preventDefault();else{e=this.R.isSelected(f)?this.R.Ka(null,!0):e=f;(d.Ui||d.nN)&&this.xBa(h,e);if(d.ME){k=d.ME(b,{item:void 0});if(b.isDefaultPrevented()||"boolean"===typeof k&&!k)return k;if(!d.iw&&!this.Zoa(h)&&!d.reorder)return b.preventDefault(),!1}"uninitialized"===h.effectAllowed&&(h.effectAllowed=d.nN?"move":a.u.$q(b)?"copy":"move");this.cra(e,f,b)}};a.wa.prototype.lra=
function(a){var c=this.Gd;c.HL&&c.HL(a)};a.wa.prototype.ora=function(b){this.R.sa[0].firstChild||this.Fna();var d=g(b.target),e=this.R.Ka(d),f=this.Gd,h=f.vf,k=e&&0<e.length&&e.hasClass("oj-tree-node"),l=b.originalEvent.dataTransfer,m=a.wa,s=!1,t=!1,r;k&&e.hasClass(c.Ex)&&(f.$o=!0);if(!k||"UL"!=b.target.tagName||"group"!=b.target.getAttribute("role"))if(f.ji=!f.NE,!f.ji&&!f.reorder||f.ji&&this.qU(l,m.eP))this.$u();else{if(f.ji&&(s=this.qU(l,m.dP),!f.tn)){this.$u();return}h.Sa=!1;f.Hw&&this.hC(f.Hw);
d.hasClass("oj-tree")&&(e=f.Hw);if(!e||!e.length||e.attr("id")!=f.KF){s&&k&&(f.Hw=null,h.lc=2);f.ji&&!s&&(h.lc=1);h.Sa=e;f.Hw=e;this.u5(b,e);if(this.Yqa()){h.Sa.removeClass(m.vP).addClass(m.Pr).addClass(m.K1);f.JL&&(r=f.JL(b,{item:f.$o?null:e,position:f.$o?"first":f.gj,reference:f.$o?null:h.Sa}));if(void 0===r)this.n9(l)?(b.preventDefault(),b.stopPropagation()):t=f.ji||!f.reorder;else if(!1===r||b.isDefaultPrevented())b.preventDefault(),b.stopPropagation();else if(f.ji||!f.reorder)t=f.ji||!f.reorder;
t&&this.$u();return r}this.hC(h.Sa);h.Sa=null}this.gy()}};a.wa.prototype.sra=function(a){var c=this.Gd,e=c.vf,f=a.originalEvent.dataTransfer,g=!1,k,l,m;if(e.Sa&&e.Sa.length&&(l=e.Sa,l.hasClass("oj-tree-node")&&(k=l.attr("id"),k!=c.KF&&(this.u5(a,l),this.LR())))){c.ML&&(m=c.ML(a,{item:c.$o?null:l,reference:c.$o?null:e.Sa,position:c.$o?"first":e.zY}));if(void 0===m)this.n9(f)?(a.preventDefault(),a.stopPropagation()):g=c.ji||!c.reorder;else if(!1===m||a.isDefaultPrevented())a.preventDefault(),a.stopPropagation();
else if(c.ji||!c.reorder)g=c.ji||!c.reorder;g&&this.$u();return m}this.gy()};a.wa.prototype.mra=function(a){var c=this.Gd,e=c.vf,f=!1,g;if(e.Sa){if(c.NL)g=c.NL(a,{reference:c.$o?null:e.Sa,position:c.$o?"first":e.zY,reorder:!c.ji&&c.reorder});else if(c.ji||!c.reorder)f=!0;f||g&&!a.isDefaultPrevented()||this.Zqa(a)}c.ji&&this.$u();f||(a.preventDefault(),a.stopPropagation());c.$Y=null;return g};a.wa.prototype.nra=function(a){var c=this.Gd,e=c.vf;c.rX&&c.rX(a,{reorder:c.reorder&&!1===e.lc});this.dra();
this.$u()};a.wa.prototype.Fna=function(){this.g9||(this.g9=g("\x3cli class\x3d'"+c.Ex+" oj-tree-node oj-tree-leaf oj-valid-drop' id\x3d'"+c.Ex+"'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e\x3ca href\x3d'#'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x3c/ins\x3e\x3cspan class\x3d'oj-tree-title'\x3e\x3c/span\x3e\x3c/a\x3e\x3c/li\x3e"));this.R.sa.append(this.g9)};a.wa.prototype.pra=function(a){var c=this.Gd,e=c.vf,f=g(a.target),h=f.closest("li"),k=h&&0<h.length&&h.hasClass("oj-tree-node");h.attr("id");
var l=a.originalEvent.dataTransfer;c.KL&&c.KL(a,{item:c.$o?null:h});f.hasClass("oj-tree")||!k||"none"==l.dropEffect?this.$qa(a):c.$Y=h;e.Sa&&this.hC(e.Sa)};a.wa.prototype.Yqa=function(){var a=this.Gd,d=a.vf,e;a.lN=!1;e=this.LR();var f=a.nIa;f&&(a.FLa&&clearTimeout(a.or),d.Sa&&d.Sa.length&&d.Sa.hasClass(c.Kh)&&(a.or=setTimeout(this.ara.bind(this),f)));a=typeof e;return"boolean"==a&&e||"string"==a};a.wa.prototype.ara=function(){var a=this.Gd,c=a.vf;a.or=!1;this.R.bg(c.Sa,this.LR.bind(this),!0)};a.wa.prototype.Zqa=
function(b){var c=this.Gd,e=c.vf;c.NE&&c.reorder&&"object"==typeof e.lc&&0<e.lc.length&&(this.R.yD(e.lc,e.Sa,e.zY,a.u.$q(b)),e.lc=!1)};a.wa.prototype.iI=function(a){a.hasClass(c.Lm)&&(a.removeClass(c.Lm),this.R.kn(a,!0));var d=(a=this.R.getChildren(a))&&a.length?a.length:0,e;for(e=0;e<d;e++)this.iI(g(a[e]))};a.wa.prototype.u5=function(a,d){var e=this.Gd;d&&(d.hasClass(c.Ex)?e.gj="after":(a=a.originalEvent,e.off=d.offset(),e.gj=a.pageY-(e.off.top||0),e.gj=e.gj>=this.R.i.la.wt?"after":0>e.gj?"before":
"inside","after"===e.gj&&d.hasClass(c.tl)&&(e.gj="first")))};a.wa.prototype.$qa=function(a){var c=this.Gd,e=c.vf;c.after=!1;c.before=!1;c.fA=!1;c.vLa=null;this.gy();e.Sa&&e.Sa[0]===a.target.parentNode&&c.or&&(clearTimeout(c.or),c.or=!1)};a.wa.prototype.$u=function(){this.gy();var a=this.Gd,c=a.vf;c.lc=!1;c.Sa=!1;a.or&&clearTimeout(a.or);a.KF=null;a.ji=!1;a.Hw=null;a.$Y=null;a.after=!1;a.before=!1;a.fA=!1;a.off=!1;a.lN=!1;a.or=!1;a.ji=!1;a.$o=!1};a.wa.prototype.t5=function(){var a=this.Gd,c;c=g(this.R.Ra[0]);
c.off("dragstart",a.BX);c.off("dragend",a.xX);c.off("drag",a.vX);c.off("dragenter",a.yX);c.off("dragover",a.AX);c.off("dragleave",a.zX);c.off("drop",a.wX);this.$u();this.Naa()};a.wa.prototype.LR=function(){var a=this.Gd,c=a.vf,e=this.R,f=!1;if(!c.Sa||!c.Sa.length)return!1;if("number"==typeof c.lc&&(1===c.lc||2===c.lc))f=!0;else if(!c.lc)return!1;a.off=c.Sa.offset();this.R.MJ&&(a.off.right=a.off.left+c.Sa.width()-c.Sa.find("\x3ea").width()-30);a.yia=c.Sa.find("a").width();f?(a.before="before"==a.gj,
a.after="after"==a.gj,a.fA="inside"==a.gj):(e.ID(c.lc,c.Sa,"before"),a.before=e.NH(),e.ID(c.lc,c.Sa,"after"),a.after=e.NH(),this.R.sq(c.Sa)?(e.ID(c.lc,c.Sa,"inside"),a.fA=e.NH()):a.fA=!1);a.lN=!0;return this.bra()};a.wa.prototype.bra=function(){var b=this.Gd,c=!1,e=a.wa,f=b.vf,g=this.R.MJ,k,l,m,s=this.R.i.la.wt,t=!1;if(!b.lN)return this.gy(),t;if("after"==b.gj&&b.after||"inside"==b.gj&&b.fA||"before"==b.gj&&b.before||"first"==b.gj)t=b.gj;"first"===t&&(c=f.Sa.find("li:eq(0)"),b.off=c.offset());l=g?
b.off.right-18:b.off.left+5;c=!this.R.isLeaf(f.Sa);k=g?l+b.yia+18:l;l=g?k-b.Xga:l+8;m=b.off.top-3;switch(t){case "before":case "first":this.xD(f.qp,{left:k,top:m-7});f.jm&&this.xD(f.jm,{left:l,top:m});break;case "after":m+=s;this.xD(f.qp,{left:k,top:m-2});f.jm&&this.xD(f.jm,{left:l,top:m+6});break;case "inside":this.xD(f.qp,{left:k+(g?c?-4:0:4),top:b.off.top+s/2-8});f.jm&&f.jm.hide();break;default:this.gy()}t?f.Sa.removeClass(e.vP).addClass(e.Pr):f.Sa.removeClass(e.Pr).removeClass(e.Pr);return f.zY=
t};a.wa.prototype.gy=function(){var a=this.Gd.vf;a&&(a.qp&&a.qp.hide(),a.jm&&a.jm.hide(),a.Sa&&this.hC(a.Sa))};a.wa.prototype.xD=function(a,c){c.left+="px";c.top+="px";a.css(c).show()};a.wa.prototype.cra=function(b,c,e){var f=this.Gd,g=f.vf,k=a.wa;g.lc=b;g.lc.addClass(k.UG);f.KF=c.attr("id");try{e.currentTarget.unselectable="on",e.currentTarget.onselectstart=function(){return!1},e.currentTarget.style&&(e.currentTarget.style.MozUserSelect="none")}catch(l){}this.R.Hxa()&&g.qp&&g.qp.addClass("oj-tree-"+
this.R.i.yc.MA);b=this.R.Ra;f.GEa=b.offset();f.fFa=parseInt(b.width(),10);f.ch=parseInt(b.height(),10);f.NE=!0};a.wa.prototype.dra=function(){var b=this.Gd,c=b.vf,e=a.wa;c.Sa&&this.hC(c.Sa);"number"!=typeof c.lc&&c.lc&&c.lc.removeClass(e.UG);b.NE=!1};a.wa.prototype.xBa=function(b,c){var e=this.Gd,f=a.wa,g,k;(g=this.R.J2(c))&&(k=JSON.stringify(g));if(e.iw)for(g=0;g<e.iw.length;g++)b.setData(e.iw[g],k);b.setData(f.dP,"0");e.nN&&b.setData(f.eP,"0")};a.wa.prototype.qU=function(a,c){var e=a.types,f=e.length,
g;for(g=0;g<f;g++)if(c==e[g])return!0;return!1};a.wa.prototype.n9=function(a){var c=this.Gd.IL,e=!1,f;if(c)for(e=!(0<c.length),f=0;f<c.length;f++){if(this.qU(a,c[f])){e=!0;break}}else e=!0;return e};a.wa.prototype.Zoa=function(b){var c=(b=b.types)&&b.length?b.length:0,e=a.wa,f=!1,g,k;for(k=0;k<c;k++)if(g=b[k],g!=e.dP&&g!=e.eP){f=!0;break}return f};a.wa.prototype.hC=function(b){var c=a.wa;b&&b.removeClass(c.Pr).removeClass(c.vP).removeClass(c.K1)};a.wa.prototype.Naa=function(){var a={};this.Gd=a;a.reorder=
!1;a.nN=!1;a.ji=!1;a.NE=!1;a.KF=null;a.Hw=null;a.BX=null;a.xX=null;a.vX=null;a.yX=null;a.AX=null;a.zX=null;a.wX=null;a.Ui=!1;a.tn=!1;a.ME=null;a.HL=null;a.lLa=null;a.JL=null;a.ML=null;a.KL=null;a.mLa=null;a.IL=null;a.after=!1;a.fA=!1;a.before=!1;a.off=!1;a.lN=!1;a.or=!1;a.GEa=!1;a.fFa=!1;a.ch=!1;a.Xga=100;a.yia=100;a.nIa=500;a.vf={};a.vf.lc=!1;a.vf.Sa=!1;a.vf.qp=!1;a.vf.jm=!1};a.wa.prototype.Lca=function(a){this.R.Lca(a)};a.wa.uP="oj-draggable";a.wa.UG="oj-drag";a.wa.K1="oj-active-drop";a.wa.Pr="oj-valid-drop";
a.wa.vP="oj-invalid-drop";a.wa.nKa="oj-drop";a.wa.lKa="oj-tree-drop-marker";a.wa.Wla="oj-tree-drop-marker-line";a.wa.Tka="reorder";a.wa.Kka="drag";a.wa.Oka="drop";a.wa.S0="node";a.wa.R0="dataTypes";a.wa.Nka="dragStart";a.wa.Lka="drag";a.wa.Mka="dragEnd";a.wa.Pka="dragEnter";a.wa.Rka="dragOver";a.wa.Qka="dragLeave";a.wa.Ska="drop";a.wa.dP="_ojtree";a.wa.eP="_ojtreereorder";(function(){function b(a){n.push(a);g(a.mba).keydown(d)}function d(b){var c="";a.u.$q(b)?c+="ctrl+":b.shiftKey&&(c+="shift+");
var d=b.which;switch(d){case 32:c+="space";break;case 37:c+="left";break;case 38:c+="up";break;case 39:c+="right";break;case 40:c+="down";break;case 46:c+="del";break;case 33:c+="pgup";break;case 34:c+="pgdn";break;case 35:c+="end";break;case 36:c+="home";break;case 56:c="*";break;case 113:case 121:c+="f"+(1-(112-d))}if(0===c.length||"shift+"==c||"ctrl+"==c)return!0;var e=null;g.each(n,function(a,d){if(d.oE.i.ui.Sl)return d.oE.i.ui.Tw=!1,"shift+f10"==c?d.oE.i.menu.oL=d.oE.i.ui.Fc:d.w8[c]&&(b.preventDefault(),
e=d.w8[c].call(d.oE,b)),!1});if(null!=e)return e}function e(a){g.each(n,function(b){if(n[b].mba===a)return g(a).off("keydown"),n[b]=null,n.splice(b,1),!1})}function f(a){var b=!0,c;for(c in a)if(a.hasOwnProperty(c)){b=!1;break}return b}function h(a){var b=!1,c=!0;a.AN&&(a.title&&(b=g("style[id\x3d'"+a.title+"-stylesheet']")[0]),b?c=!1:(b=document.createElement("style"),b.setAttribute("type","text/css"),a.title&&b.setAttribute("id",a.title+"-stylesheet")),b.styleSheet?c?(document.getElementsByTagName("head")[0].appendChild(b),
b.styleSheet.cssText=a.AN):b.styleSheet.cssText=b.styleSheet.cssText+" "+a.AN:(b.appendChild(document.createTextNode(a.AN)),document.getElementsByTagName("head")[0].appendChild(b)))}var k={cut:"ojtreecut",copy:"ojtreecopy",paste:"ojtreepaste",remove:"ojtreeremove",rename:"ojtreerename"},l={cut:"labelCut",copy:"labelCopy",paste:"labelPaste",remove:"labelRemove",rename:"labelRename"},m="id title class role draggable style".split(" "),s,t,r;g(function(){/msie/.test(navigator.userAgent.toLowerCase())?
(t=g('\x3ctextarea cols\x3d"10" rows\x3d"2"\x3e\x3c/textarea\x3e').css({position:"absolute",top:-1E3,left:0}).appendTo("body"),r=g('\x3ctextarea cols\x3d"10" rows\x3d"2" style\x3d"overflow: hidden;"\x3e\x3c/textarea\x3e').css({position:"absolute",top:-1E3,left:0}).appendTo("body"),s=t.width()-r.width(),t.add(r).remove()):(t=g("\x3cdiv /\x3e").css({width:100,height:100,overflow:"auto",position:"absolute",top:-1E3,left:0}).prependTo("body").append("\x3cdiv /\x3e").find("div").css({width:"100%",height:200}),
s=100-t.width(),t.parent().remove())});var n=[],p=-1;a.Na("oj.ojTree",g.oj.baseComponent,{widgetEventPrefix:"oj",defaultElement:"\x3cdiv\x3e",options:{dnd:{reorder:"disable"},expandParents:!1,initExpanded:null,uHa:[],selection:[],selectionMode:"single",selectedParentCollapse:!1,selectedParentExpand:!0,selectPrevOnDelete:!1,data:null,emptyText:null,icons:!0,types:null,before:null,collapse:null,create:null,collapseAll:null,cut:null,dehover:null,remove:null,destroy:null,expand:null,expandAll:null,hover:null,
loaded:null,move:null,optionChange:null,paste:null,refresh:null,rename:null},collapse:function(a,b){var d=(b=b||!1)?0:this.pQ;a=this.Ka(a);if(!a.length||-1===a||!a.hasClass(c.tl)||this.i.la.locked||a.hasClass(c.Se))return!1;var e=this.oc({obj:a,func:"collapse"},"before");if("boolean"!=typeof e||e)a.removeClass(c.tl).addClass(c.Kh).attr("aria-expanded","false"),g(a.children()[0]).removeClass(c.Lm).addClass("oj-default"),!b&&d?this.To(a,!0):this.oW(g(a.children("UL")[0]),a)},To:function(a,b){var c,
d,e;c=g(a.children("ul"));this.E9?c[0].addEventListener("webkitTransitionEnd",this.iK):c[0].addEventListener("transitionend",this.iK);b?(d=c[0].offsetHeight,e=0):(d=0,e=this.Qsa(c[0]));c.css("max-height",d+"px");c.css("overflow","hidden");b||(c[0].style.display="block");setTimeout(function(){c.addClass("oj-tree-transition");c.css("max-height",e+"px")},20)},Qsa:function(a){var b,c,d,e,f=g("\x3cdiv style\x3d'position: absolute'\x3e");b=a.parentNode;c=a.nextSibling;b.removeChild(a);e=a.style.display;
a.style.display="block";f.append(a);this.Ra[0].appendChild(f[0]);d=a.offsetHeight||a.scrollHeight;a.style.display=e;this.Ra[0].removeChild(f[0]);f[0].removeChild(a);c?b.insertBefore(a,c):b.appendChild(a);return d+10},xz:function(a){a=g(a.target);var b=a.closest("li");this.E9?a[0].removeEventListener("webkitTransitionEnd",this.iK):a[0].removeEventListener("transitionend",this.iK);a.removeClass("oj-tree-transition");this.oW(a,b)},oW:function(a,b){b.hasClass(c.Kh)?(a[0].style.display="none",a.css("max-height",
""),this.oc({obj:b},"collapse"),this.after_close(b)):(a[0].style.display="block",a.css("max-height",""),this.oc({obj:b},"expand"))},collapseAll:function(a,b){var d=a?a:-1,e=this;if(!this.i.la.locked&&((a=a?this.Ka(a):this.Ra)&&-1!==d&&(d=a),a&&-1!==d||(a=this.sa),!a.hasClass(c.Se))){var f;-1!==d&&this.isExpanded(a)&&(f=a[0]);var g=a.find("li.oj-expanded");g.length&&g.each(function(){e.collapse(this,!b)});f&&(this.collapse(f,!b),g.splice(0,0,f));g.length&&this.oc({obj:g,targ:d},"collapseAll")}},expand:function(a,
b){this.bg(a,!1,b)},expanded:function(a,b){var c,d,e=this;if(a&&"array"===g.type(a)){if(this.i.la.locked)return null;d=a.length;g.each(a,function(a,c){e.bg(c,!1,b)});return null}a=this.sa.find("li.oj-expanded");d=a.length;c=[];for(var f=0;f<d;f++)c.push(a[f]);return g(c)},expandAll:function(a,b){this.VR(a,b)},toggleExpand:function(a,b){if((a=this.Ka(a))&&a.length&&-1!==a&&!a.hasClass(c.Se)&&!this.i.la.locked){if(a.hasClass(c.Kh))return this.expand(a,b);if(a.hasClass(c.tl))return this.collapse(a,b)}},
deselect:function(a){var b=this.options.selection.slice(0);this.Zu(a);this.CC("selection",b,null,null)},deselectAll:function(a){if(!this.i.la.locked){var b=this.options.selection.slice(0);this.bI(a);this.CC("selection",b,null,null)}},select:function(a){this.kn(a,!0)},toggleSelect:function(a){a=this.Ka(a);if(!a.length||a.hasClass(c.Se)||this.i.la.locked)return!1;this.isSelected(a)?this.deselect(a):this.kn(a,!0);return!0},isCollapsed:function(a){return(a=this.Ka(a))&&-1!==a&&a.hasClass(c.Kh)},isExpanded:function(a){return(a=
this.Ka(a))&&-1!==a&&a.hasClass(c.tl)},isLeaf:function(a){return this.rU(a)},isSelected:function(a){a=this.Ka(a);var b=!1;a&&a.length&&this.i.ui.selected&&(b=0<=this.i.ui.selected.index(a));return b},create:function(a,b,c){var d,e,f;e=g.isArray(c);if(!e||1==c.length)return d=this.oC(a,b,e?c[0]:c),this.ts().iI(d),d;e=[];if("before"!=b)for(f=c.length-1;0<=f;f--)d=this.oC(a,b,c[f]),e.unshift(d[0]),this.ts().iI(d);else for(f=0;f<c.length;f++)d=this.oC(a,b,c[f]),e.push(d[0]),this.ts().iI(d);return g(e)},
remove:function(a){a=this.Ka(a);if(!a.length||a.hasClass(c.Se)||this.i.la.locked)return!1;var b=this.oc({obj:a,func:"remove"},"before");if("boolean"==typeof b&&!b)return!1;this.Ou();var b=this.Zm(a),d=g([]),e=this,f=this.nq(a);a.each(function(){d=d.add(e.nq(this))});a=a.detach();-1!==b&&0===b.find("\x3e ul \x3e li").length&&b.removeClass("oj-expanded oj-collapsed").addClass("oj-tree-leaf").removeAttr("aria-expanded");this.zj(b);this.oc({obj:a,prev:f,parent:b},"remove");return a},getText:function(a){a=
this.Ka(a);if(!a.length)return!1;a=a.children("a:eq(0)");a=a.find("span:eq(0)");return a[0].textContent},rename:function(a,b){this.Gaa(a,b)},hover:function(a){if(!this.i.menu.oL&&(a=this.Ka(a),a.length&&!a.hasClass(c.Se)&&!this.i.la.locked&&!a.hasClass(c.Eu))){var b=this.oc({obj:a,func:"hover"},"before");if("boolean"!=typeof b||b)a.hasClass(c.Eu)||this.dehover(),this.i.ui.Fc=a.children("a").addClass(c.Eu).parent(),this.sa.attr("aria-activedescendant",this.i.ui.Fc.attr("id")),this.a6(a),this.oc({obj:a},
"hover")}},dehover:function(){if(!this.i.menu.oL){var a=this.i.ui.Fc,b;if(a&&a.length&&!a.hasClass(c.Se)&&!this.i.la.locked){b=a.find("a.oj-hover");if(!b.length&&(b=this.sa.find("a.oj-hover"),!b.length))return;b.removeClass(c.Eu).parent();this.sa.removeAttr("aria-activedescendant");this.i.ui.Fc=null;void 0!=a.attr("id")&&this.oc({obj:a},"dehover")}}},getPath:function(a,b){var c=[],d=this;a=this.Ka(a);if(-1===a||!a||!a.length)return!1;a.parentsUntil(".oj-tree","li").each(function(){c.push(b?this.id:
d.getText(this))});c.reverse();c.push(b?a.attr("id"):this.getText(a));return c},getRoot:function(){return this.Ra.children("ul:eq(0)")},refresh:function(a){this._super();this.i.la.locked||this.Ff(a?a:-1)},move:function(a,b,c,d){this.yD(a,b,c,d)},getType:function(a){return this.mT(a)},setType:function(a,b){return this.jCa(a,b)},getNodeBySubId:function(a){return a?this.Cza(a):this.element?this.element[0]:null},getSubIdByNode:function(a){return this.Uta(a)},getContextByNode:function(a){var b,c;a=this.Ka(null==
a||void 0==a?0:a);b=-1!=a&&0<a.length;c=-1==a;return b||c?{subId:b?"oj-tree-node":"oj-tree",item:b?a[0]:null,node:b?a:!1,leaf:b?this.rU(a):!1}:null},getParent:function(a){return(a=this.Zm(a))&&0<a.length?a:null},getPrevSibling:function(a){return(a=this.nq(a,!0))&&0<a.length?a:null},getNextSibling:function(a){return(a=this.kv(a,!0))&&0<a.length?a:null},getChildren:function(a){return(a=(a=this.xsa(a?a:-1))&&a.length?a.not("."+c.Ex):a)&&0<a.length?a:null},scrollIntoView:function(a,b,c){a?(a=a.node,a=
this.Ka(a)):a=-1;-1==a&&(a=this.Ra.find("\x3e ul \x3e li:first-child"));if(a&&a.length)return b="top"==b,c&&(this.sa.focus(),this.hover(a)),a[0].scrollIntoView(b),this},_ComponentCreate:function(){this._super();this.Cwa=this.Hya();this.av=this.element.attr("id");void 0===this.av&&(this.av="oj-tree-"+this.Ej(),this.element.attr("id",this.av));this.Ra=this.element;this.sa=null;this.i={};this.zca=null;this.MJ="rtl"===this.hd();this.Ry=a.u.af();this.Swa();if(this.pQ=this.nsa())this.E9=a.Za.Rz().browser===
a.Za.rm.xO,this.iK=g.proxy(this.xz,this);this.Pj()},_destroy:function(){this.npa();this.i.html.vA&&(this.Ra.append(this.i.html.vA),this.i.html.eN.remove(),this.i.html.eN=!1,this.i.html.GN=!1);this.i.sb.type=0;this._super()},_setOption:function(a,b,c){var d;if("selection"===a)b="string"==typeof b?[b]:b&&b.length?b:[],this.i.la.Sw=!0,this.dwa(b),this.i.la.Sw=!1,b=this.ZS();else if("selectionMode"===a)"none"===b?d=0:"single"===b?d=1:"multiple"===b?d=-1:(d=0,b="none"),d!=this.i.la.wr&&(this.i.la.wr=d);
else if("icons"===a)"boolean"==g.type(b)&&b!=this.i.yc.icons&&((this.i.yc.icons=b)?this.UV():this.ZT());else if("contextMenu"===a)this.Tu(),b&&this.Ds(b);else if("disabled"===a)this.Hua(b);else{if("data"===a){this._super(a,b,c);this.S8();this.T8();this.V8();this.U9();return}if("dnd"===a){this._super(a,b,c);this.ts().OGa();return}"emptyText"==a&&(b=this.oI(b))}this._super(a,b,c)},uB:function(a,b,c){return"selection"===a?this.t4(b,c):this._superApply(arguments)},t4:function(a,b){var c,d,e,f,h,k=!1,
l=!1;f=a&&a.length?a.length:0;h=b&&b.length?b.length:0;if(f!==h)k=!0;else if(0==f&&0===h)k=!1;else for(c=0;c<f;c++){e=g(a[c]).attr("id");l=!1;for(d=0;d<h;d++)if(e==g(b[d]).attr("id")){l=!0;break}if(!l){k=!0;break}}return!k},npa:function(){this.LB&&(this.LB.vpa(),this.LB=null);var a=this.Ej();this.Ra.unbind(".oj-tree").undelegate(".oj-tree").removeData("oj-tree-instance-id").find("[class^\x3d'oj-tree']").addBack().attr("class",function(){return this.className.replace(/oj-tree[^ ]*|$/ig,"")});var b=
this.Ra.attr("class"),b=b.trim();0===b.length&&this.Ra.removeAttr("class");e(this.sa);g(document).unbind(".oj-tree-"+a).undelegate(".oj-tree-"+a);this.sa.remove();this.sa=null},Ka:function(a,b){if("undefined"===typeof a||null===a)return b?this.i.ui.selected:this.i.ui.Nc;var c=g(a,this.Ra);if(c.is(".oj-tree")||-1===a)return-1;c=c.closest("li",this.Ra);return c.length?c:!1},nq:function(a,b){a=this.Ka(a);if(-1===a)return this.Ra.find("\x3e ul \x3e li:last-child");if(!a.length)return!1;if(b)return 0<
a.prevAll("li").length?a.prevAll("li:eq(0)"):!1;if(a.prev("li").length){for(a=a.prev("li").eq(0);a.hasClass(c.tl);)a=a.children("ul:eq(0)").children("li:last");return a}var d=a.parentsUntil(".oj-tree","li:eq(0)");return d.length?d:!1},kv:function(a,b){a=this.Ka(a);return-1===a?this.Ra.find("\x3e ul \x3e li:first-child"):a.length?b?0<a.nextAll("li").length?a.nextAll("li:eq(0)"):!1:a.hasClass(c.tl)?a.find("li:eq(0)"):0<a.nextAll("li").length?a.nextAll("li:eq(0)"):a.parentsUntil(".oj-tree","li").next("li").eq(0):
!1},Zm:function(a){a=this.Ka(a);if(-1==a||!a.length)return!1;a=a.parentsUntil(".oj-tree","li:eq(0)");return a.length?a:-1},xsa:function(a){a=this.Ka(a);return-1===a?this.Ra.children("ul:eq(0)").children("li"):a.length?a.children("ul:eq(0)").children("li"):!1},rU:function(a){return(a=this.Ka(a))&&-1!==a&&a.hasClass("oj-tree-leaf")},uta:function(a){a=this.sa.find(a);var b=!1;a&&a.length&&0<a.length&&g(a).is("li")&&(b=a);return b},Pza:function(b,c){var d=b.parents("div").eq(0);(d=a.Components.Mf(d))&&
c&&d("getCI",c);return this},getCI:function(a){a.Cp=this},goa:function(a,b){void 0!=a&&void 0!=b&&g.each(b,function(b,c){void 0==a[b]&&(a[b]=c)})},Hua:function(a){var b;"undefined"!==typeof a&&((b=this.sa.hasClass(c.Se))||(b=!1),b!=a&&(a?(this.sa.addClass(c.Se),this.sa.prop("disabled",!0)):(this.sa.removeClass(c.Se),this.sa.prop("disabled",!1)),this.iDa(a)))},iDa:function(a){a?(this.i.la.locked=!0,this.i.ui.opacity=this.Ra.children("ul").css("opacity"),this.sa.addClass(c.Se).css("opacity","0.9")):
(this.i.la.locked=!1,this.sa.removeClass(c.Se).css("opacity",this.i.ui.opacity))},WKa:function(){return this.i.la.locked},dwa:function(a){var b=a.slice(0),c=[],d=this,e,f,h,k;g.grep(b,function(a,f){if(e=d.uta(a))c.push(e),b[f]=e[0];else return!1;return!0});a=this.ZS();g.each(a,function(a,b){k=c.length;f=g(b).attr("id");h=!1;for(a=0;a<k;a++)if(f==c[a].attr("id")){h=!0;break}h||d.Zu(b)});this.eCa(c,null)},ID:function(a,b,c,d,e){var f={};b=-1!==b&&b?this.Ka(b):-1;this.Pza(a,f);f.Tt=this;f.lc=f.Cp.Ka(a);
f.Sa=b;f.pr="undefined"===typeof c||!1===c?"last":c;if(!e&&this.i.la.hj.lc&&this.i.la.hj.lc[0]===f.lc[0]&&this.i.la.hj.Sa[0]===f.Sa[0]&&this.i.la.hj.pr===f.pr)d&&d.call(this,this.i.la.hj);else{if(-1!==f.Sa&&f.Sa){if(!/^(before|after)$/.test(f.pr)&&!this.sq(f.Sa))return this.tq(f.Sa,function(){this.ID(a,b,c,d,!0)});switch(f.pr){case "before":f.rn=f.Sa.index();f.gw=f.Tt.Zm(f.Sa);break;case "after":f.rn=f.Sa.index()+1;f.gw=f.Tt.Zm(f.Sa);break;case "inside":case "first":f.rn=0;f.gw=f.Sa;break;case "last":f.rn=
f.Sa.find(" \x3e ul \x3e li").length;f.gw=f.Sa;break;default:f.rn=f.pr,f.gw=f.Sa}}else switch(f.gw=-1,f.pr){case "first":case "before":case "inside":f.rn=0;break;case "after":case "last":f.rn=f.Tt.Ra.find(" \x3e ul \x3e li").length;break;default:f.rn=f.pr}f.kr=-1==f.gw?f.Tt.Ra:f.gw;f.nr=f.Cp.Zm(f.lc);f.iLa=f.lc.index();-1===f.nr&&(f.nr=f.Cp?f.Cp.Ra:this.Ra);!/^(before|after)$/.test(f.pr)&&f.nr&&f.kr&&f.nr[0]===f.kr[0]&&f.lc.index()<f.rn&&f.rn++;f.bZ=f.kr.find(" \x3e ul \x3e li:nth-child("+(f.rn+1)+
")");this.i.la.hj=f;d&&d.call(this,this.i.la.hj,"prepare_move")}},NH:function(){var a=this.i.la.hj,b=!0,c;c=-1===a.Sa?this.Ra:a.Sa;if(!a||!a.lc||a.bZ[0]===a.lc[0]||!a.Sa)return!1;if(!a.EL){if(a.nr&&a.kr&&a.nr[0]===a.kr[0]&&a.rn-1===a.lc.index())return!1;a.lc.each(function(){if(-1!==c.parentsUntil(".oj-tree","li").addBack().index(this))return b=!1})}return b},Gaa:function(a,b){var c;a=this.Ka(a);this.Ou();c=this.getText(a);if(a&&a.length){var d=this.oc({obj:a,func:"rename",title:b,prevTitle:c},"before");
if("boolean"==typeof d&&!d)return}a&&a.length&&this.PV.apply(this,Array.prototype.slice.call(arguments))&&this.oc({obj:a,title:b,prevTitle:c},"rename")},yD:function(a,b,d,e,f,h){f||(a=this.Ka(a));if(!(a.hasClass&&a.hasClass(c.Se)||this.i.la.locked)){if(!f)return this.ID(a,b,d,function(a){a.Cp===a.Tt||a.EL||a.Cp.deselect(a.lc);this.yD(a,!1,!1,e,!0,h)});e&&(this.i.la.hj.EL=!0);if(!h&&!this.NH())return!1;this.Ou();b=!1;e?(b=a.lc.clone(!0),b.find("*[id]").addBack().each(function(){this.id&&(this.id="copy_"+
this.id)})):b=a.lc;a.bZ.length?a.bZ.before(b):(a.kr.children("ul").length||g("\x3cul /\x3e").appendTo(a.kr),a.kr.children("ul:eq(0)").append(b));try{a.Cp.zj(a.nr),a.Tt.zj(a.kr),a.nr.find("\x3e ul \x3e li").length||a.nr.removeClass("oj-expanded oj-collapsed").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove()}catch(k){}e&&(this.i.la.hj.EL=!0,this.i.la.hj.aZ=b);b=g.extend(!0,{},this.i.la.hj);b.obj=a.lc;this.oc(b,"move");return this.i.la.hj}},GKa:function(){return this.i.Vd.hj},
mT:function(a){var b=null;this.options.types&&(b=this.Ka(a));return b&&b.length?b.attr(this.options.types.attr)||"default":!1},jCa:function(a,b){var c=this.options.types,d,e=!1;a=this.Ka(a);c&&a&&-1!=a&&a.length&&b&&(d=c.attr,c=c.types,d&&c&&c[b]&&(a.attr(d,b),a.addClass("oj-tree-type"),e=!0));return e},Xoa:function(a,b){b=this.Ka(b);var c=!1,d=this.mT(b),e=this.lv().types,f=!1;if(-1===b)if(e[a])c=e[a];else return;else{if(!1===d)return;(f=this.i.types.Zc.useData?b.data("oj-tree"):!1)&&f.types&&"undefined"!==
typeof f.types[a]?c=f.types[a]:e.types[d]&&"undefined"!==typeof e.types[d][a]?c=e.types[d][a]:e.types["default"]&&"undefined"!==typeof e.types["default"][a]&&(c=e.types["default"][a])}g.isFunction(c)&&(c=c.call(this,b));return c},zj:function(b){var d,e,f,h=this.ts(),k=a.wa;h.iga()&&(d=k.uP,e="draggable",f=!0);h.EHa()&&(d+=" "+k.Pr);b=b&&-1!=b?g(b):this.sa;b=b.is("li")?b.find("li").addBack():b.find("li");b.removeClass("oj-tree-last").addClass("oj-tree-node").addClass(d).attr(e,f).filter("li:last-child").addClass("oj-tree-last").end().filter(":has(li)").not(".oj-expanded").removeClass("oj-tree-leaf").addClass(c.Kh).attr("aria-expanded",
"false");b.not(".oj-expanded, .oj-collapsed").addClass("oj-tree-leaf").children("ul").remove();var l=this.options.types?this.options.types.attr:!1;b.find("li");var m,p;g.each(b,function(){p=g(this);m=p.find("\x3e ins");1<m.length&&(m=g(m[0]));p.hasClass("oj-tree-leaf")?(m.removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default"),m.addClass("oj-tree-icon")):(m.addClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default"),
m.removeClass("oj-tree-node-icon"));l&&p.attr(l)&&p.addClass("oj-tree-type")})},oC:function(a,b,d,e,f){a=a||-1;a=this.Ka(a);if(-1!==a&&!a.length)return null;var h;b="undefined"===typeof b?"last":b;if(!f&&!this.sq(a))return this.tq(a,function(){this.oC(a,b,d,e,!0)}),null;this.Ou();d=this.wq(d);if(!d)return null;d=d.children();f=g(d[0]);-1===a&&(a=this.Ra,"before"===b&&(b="first"),"after"===b&&(b="last"));switch(b){case "before":a.before(f);h=this.Zm(a);break;case "after":a.after(f);h=this.Zm(a);break;
case "inside":case "first":a.children("ul").length||a.append("\x3cul /\x3e");a.children("ul").prepend(f);h=a;break;case "last":a.children("ul").length||a.append("\x3cul /\x3e");a.children("ul").append(f);h=a;break;default:a.children("ul").length||a.append("\x3cul /\x3e"),b||(b=0),h=a.children("ul").children("li").eq(b),h.length?h.before(f):a.children("ul").append(f),h=a}if(-1===h||h.get(0)===this.Ra.get(0))h=-1;this.zj(h);this.oc({obj:f,parent:h},"create");e&&e.call(this,f);1<this.sa[0].childNodes.length&&
this.sa.find("."+c.Ex).remove();return f},bg:function(a,b,d){a=this.Ka(a);if(!a||!a.length)return!1;d=d||!1;if(!a.hasClass(c.Se)&&!this.i.la.locked){if(!a.hasClass(c.Kh))return b&&b.call(),!1;var e=this.oc({obj:a,func:"expand"},"before");if("boolean"!=typeof e||e){var e=d?0:this.pQ,f=this;this.sq(a)?(this.options.expandParents&&a.parentsUntil(".oj-tree",".oj-collapsed").each(function(){f.bg(this,!1,!0)}),a.removeClass(c.Kh).addClass(c.tl).attr("aria-expanded","true").children("a").removeClass("oj-tree-loading"),
g(a.children()[0]).removeClass(c.Lm).addClass("oj-default"),!d&&e?this.To(a,!1):this.oW(g(a.children("UL")[0]),a),b&&b.call()):(a.children("a").addClass("oj-tree-loading"),this.tq(a,function(){f.bg(a,b,d)},b))}}},VR:function(a,b,c){var d=a?a:-1;(a=a?this.Ka(a):-1)&&-1!==a?d=a:a=this.sa;c?a=a.find("li.oj-collapsed"):(c=a,a=a.is(".oj-collapsed")?a.find("li.oj-collapsed").addBack():a.find("li.oj-collapsed"));var e=this;a.each(function(){var a=this;e.sq(this)?e.bg(this,!1,!b):e.expand(this,function(){e.VR(a,
b,c)},!b)});0===c.find("li.oj-collapsed").length&&this.oc({obj:a,targ:d},"expandAll")},kn:function(b,d,e){var f=this.i.la,g=this.i.ui,h=f.wr;if(0==h)return!1;b=this.Ka(b);if(-1==b||!b||!b.length||b.hasClass(c.Se)||f.locked)return!1;e&&"touchend"==e.type||(g.Tw=!1);var k=this.isSelected(b);if(!k){var l=this.oc({obj:b,func:"select"},"before");if("boolean"==typeof l&&!l)return!1}var l=this.options.selection.slice(0),m=this.options,p=g.Zc.selectMultipleModifier,n=g.Zc.selectRangeModifier,s=g.Zc.disableSelectingChildren,
p="on"==p||!1!==p&&e&&a.u.$q(e),n=!1!==n&&e&&e[n+"Key"]&&g.Nc&&this.i.ui.Nc[0]!==b[0]&&g.Nc.parent()[0]===b.parent()[0],r=!0,t=this;if(d){if(s&&p&&(b.parentsUntil(".oj-tree","li").children("a.oj-selected").length||b.children("ul").find("a.oj-selected:eq(0)").length))return!1;r=!1;switch(!0){case n:g.Nc.addClass("oj-tree-last-selected");b=b[b.index()<g.Nc.index()?"nextUntil":"prevUntil"](".oj-tree-last-selected").addBack();-1==h||b.length<h?(g.Nc.removeClass("oj-tree-last-selected"),g.selected.each(function(){this!==
g.Nc[0]&&t.Zu(this)}),k=!1,r=!0):r=!1;break;case g.Tw&&-1==h:g.Tw=!1;this.toggleSelect(b);r=!1;break;case k&&!p:if(!e)break;this.bI();g.DZ||(k=!1);r=!0;break;case !k&&!p:e?g.selected&&1==g.selected.length?this.Zu(g.selected):this.bI(g.selected):1===h?this.Zu(g.selected):1<h&&this.bI();r=!0;break;case k&&p:this.deselect(b);break;case !k&&p:if(-1==h||g.selected.length+1<=h)r=!0}}d=!1;r&&!k&&(n||(g.Nc=b),b.children("a").addClass(c.Lm),b.attr("aria-selected","true"),d=!0,m.selectedParentExpand&&b.parents(".oj-collapsed").each(function(){t.bg(this,
!1,!0)}),g.selected=g.selected.add(b),this.a6(b.eq(0)),f.Sw||this.CC("selection",l,null,e));return d},Zu:function(a){a=this.Ka(a);if(!a.length)return!1;a.hasClass(c.Se)||this.i.la.locked||!this.isSelected(a)||(a.children("a").removeClass(c.Lm),a.removeAttr("aria-selected"),this.i.ui.selected=this.i.ui.selected.not(a),this.i.ui.Nc&&this.i.ui.Nc.length&&this.i.ui.Nc.get(0)===a.get(0)&&(this.i.ui.Nc=this.i.ui.selected.eq(0)))},bI:function(a){if(!this.i.la.locked&&(a=a?g(a).find("a.oj-selected").parent():
this.Ra.find("a.oj-selected").parent(),a.not(".oj-disabled"),0!==a.length)){var b=this;g.each(a,function(){b.Zu(this)})}},eCa:function(a,b){if(this.i.la.locked)return null;if(a&&0<a.length){var c=this;g.each(a,function(a,d){d&&c.kn(d,!0,b)})}},o8:function(a){a.preventDefault();a.currentTarget.blur();if(!g(a.currentTarget).hasClass("oj-tree-loading")){this.Nj();if(!this.i.ui.Sl){var b=this.Ka(a.currentTarget);0<b.length&&-1!=b&&(this.i.ui.Wl=b);this.sa.focus()}this.kn(a.currentTarget,!0,a)}this.i.ui.Tw=
!1},q5:function(a,b){a=g(a);if(!a.hasClass(c.Se)&&!this.i.la.locked){var d=a.parent(),e=d.hasClass(c.Kh);if(d.hasClass(c.tl)||e)b?(a.addClass(c.Eu),a.removeClass("oj-default"),a.removeClass(c.Lm)):(a.removeClass(c.Eu),a.addClass("oj-default"))}},Ff:function(a){this.qaa(a)},qaa:function(a){var b=a?a:-1,c=this;this.jBa();a||(a=-1);(a=this.Ka(a))?b=a:a=-1;-1!==a?a.children("UL").remove():(this.sa.empty(),this.N$());this.tq(a,function(){c.oc({obj:b},"refresh");c.pK()})},mV:function(a){this.saveSelected();
this.qaa(a)},after_close:function(a){this.oc({obj:a},"after_close",!0)},MAa:function(){var a=this;this.i.la.ij.length&&g.each(this.i.la.ij,function(b,c){a.bg(c,!1,!0)});this.oc({},"reopen",!0)},ZS:function(a){var b,c,d;a=a?g(a).find("a.oj-selected").parent():this.i.ui.selected;b=[];d=a.length;for(c=0;c<d;c++)b.push(a[c]);return b},PV:function(a,b){a=this.Ka(a);if(!a.length)return!1;a=a.children("a:eq(0)");a=a.find("span:eq(0)");this.oc({obj:a,name:b},"set_text",!0);return a[0].textContent=b},U9:function(){0!==
this.i.sb.type&&-1!==this.i.sb.type?this.tq(-1,function(){this.W9();this.pK()}):(this.hoa(),this.W9())},tq:function(a){this.oc({obj:a},"load_node",!0)},sq:function(){return!0},aya:function(a,b,c){var d=this;this.dya(a,function(){d.oc({obj:d.Ka(a)},"load_node",!0);b.call(this)},c)},Jxa:function(a){a=this.Ka(a);return-1===a||!a||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},Yza:function(a){(a=this.Ka(a))&&-1!==a&&a.removeData("oj-tree-children");return this.mV(a)},cya:function(a,
b,c){var d=this;this.$xa(a,function(){d.oc({obj:d.Ka(a)},"load_node",!0);b.call(this)},c)},Lxa:function(a){var b=this.options.data;a=this.Ka(a);return-1==a||!a||!b.ajax&&!this.i.sb.iZ&&!g.isFunction(b.data)||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},bya:function(a,b,c){var d=this;this.Zxa(a,function(){d.oc({obj:d.Ka(a)},"load_node",!0);b.call(this)},c)},Kxa:function(a){var b=this.options.data,c=null,d=null;b&&(c=b.data||null,d=b.ajax||null);a=this.Ka(a);return-1==
a||!a||!d&&!g.isFunction(c)||a.is(".oj-expanded, .oj-tree-leaf")||0<a.children("ul").children("li").length},reselect:function(){var a=this,b=this.i.ui.XF,b=g.map(g.makeArray(b),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});g.each(b,function(b,c){c&&"#"!==c&&a.select(c)});this.i.ui.selected=this.i.ui.selected.filter(function(){return this.parentNode});this.oc(null,"reselect",!0)},saveSelected:function(){var a=
this.i.ui;a.XF=[];a.selected.each(function(){this.id&&a.XF.push("#"+this.id.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:"))});this.oc(a.XF,"savedselected",!0)},rollback:function(a){a&&g.isArray(a)},get_rollback:function(){this.oc(null,"get_rollback",!0);return{uLa:this.Ej(),Vj:this.Ra.children("ul").clone(!0),jLa:this.data}},dya:function(a,b){var c=this.m1(a&&-1!=a?a[0].id:a?a:-1,a);if(c.success){var d=!a||-1===
a,e=this.options.data;if(e.data&&!e.ajax||e.data&&e.ajax&&d)d&&((c=this.wq(c.BM,a))?(this.sa.empty().append(c.children()),this.zj()):this.i.sb.Ti&&this.sa.empty()),b&&b.call(this);else if(!e.data&&e.ajax||e.data&&e.ajax&&!d)(c=this.wq(c.BM,a))?(d?(d=this.sa,d.empty().append(c.children()),d.attr("role","tree").attr("aria-labelledby",this.av).attr("tabindex","0").css("outline","none"),-1===this.i.la.wr&&d.attr("aria-multiselectable",!0)):(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),
a.removeData("oj-tree-is-loading")),this.zj(a),b&&b.call(this)):d?this.i.sb.Ti&&(this.sa.empty(),b&&b.call(this)):(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),e.correct_state&&(this.Xu(a),b&&b.call(this)))}},m1:function(a,b){var c=[],d=this.zca,e,f={},h={success:!1,BM:null};-1==a&&(a=null,f.start=0);e=d.ph(a);0<e?(f.count=e,d.ii(a,f,{success:g.proxy(function(a){for(var e=a.getCount(),f,g=0;g<e;g++){b={};(f=a.getData(g))&&(b.attr=f);b.title=a.ri[g].title;
f.xLa&&(b.metadata=a.ri[g].metadata);var k=b.attr.id;f=d.ph(k);0<f&&(f=this.m1(k,b),b.children=f.BM);c.push(b)}h.success=!0;h.BM=c},this),error:function(){h.success=!1}})):h.success=!0;return h},Zza:function(a){a=this.Ka(a);if(!this.i.la.locked){var b=!a||-1!==a||!a.length;if(b||!a.hasClass(c.Se)){var d=this.options.data.json;!b&&this.i.sb.DA&&(g.isFunction(d.data)||d.ajax)&&a.removeData("oj-tree-children");return this.mV(a)}}},$xa:function(a,b,c){function d(){}function e(){}var f=this.lv().data,
h=f&&f.data||null,k=f&&f.ajax||null;!f||h||k||(h=f);if((a=this.Ka(a))&&-1!==a&&(this.i.sb.iZ||this.i.sb.DA)&&!a.is(".oj-expanded, .oj-tree-leaf")&&0===a.children("ul").children("li").length&&a.data("oj-tree-children")){if(f=this.wq(a.data("oj-tree-children"),a))a.append(f),this.i.sb.DA||a.removeData("oj-tree-children");this.zj(a);b&&b.call(this)}else{if(a&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&!k:throw"ojTree - neither data nor ajax settings supplied.";
case g.isFunction(h):h.call(this,a,g.proxy(function(d){(d=this.wq(d,a))?(-1!==a&&a?(a.append(d).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):this.sa.empty().append(d.children()),this.zj(a),b&&b.call(this)):(-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.i.sb.Ti&&this.Xu(a)):this.i.sb.Ti&&this.sa.empty(),c&&c.call(this))},this));break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||
((f=this.wq(h,a))?(this.sa.empty().append(f.children()),this.zj()):this.i.sb.Ti&&this.sa.empty());b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:e=function(b,d,e){var f=this.lv().data.ajax.error;f&&f.call(this,d,e,b);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.i.sb.Ti&&this.Xu(a)):("error"==d||"success"===d&&this.i.sb.Ti)&&this.sa.empty();c&&c.call(this)},d=function(c,d,f){var g=this.lv().data.ajax.success;
g&&(c=g.call(this,c,d,f)||c);if("string"==typeof c){d=c.replace(/^[\s\n]+$/,"");try{d=JSON.parse(d)}catch(h){d=null}if(!d)return e.call(this,f,"Bad JSON","")}(c=this.wq(c,a))?(-1!==a&&a?(a.append(c).children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading")):(f=this.sa,f.empty().append(c.children()),f.attr("role","tree").attr("aria-labelledby",this.av).attr("tabindex","0").css("outline","none"),-1===this.i.la.wr&&f.attr("aria-multiselectable",!0)),this.zj(a),b&&
b.call(this)):-1!==a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.i.sb.Ti&&(this.Xu(a),b&&b.call(this))):this.i.sb.Ti&&(this.sa.empty(),b&&b.call(this))},f.ajax.context=this,f.ajax.error=e,f.ajax.success=d,f.dataType||(f.ajax.dataType="json"),g.isFunction(f.ajax.url)&&(f.ajax.url=f.ajax.url.call(this,a)),g.isFunction(f.ajax.data)&&(f.ajax.data=f.ajax.data.call(this,a)),g.ajax(f.ajax)}}},wq:function(a,b,d){var e=!1,f,h,k,l;if(!a)return e;
this.i.sb.DA&&b&&-1!==b&&b.data("oj-tree-children",e);if("string"==typeof a)try{a=JSON.parse(a)}catch(m){a=[]}if(g.isArray(a)){e=g("\x3cul\x3e");if(!a.length)return!1;h=0;for(k=a.length;h<k;h++)f=this.wq(a[h],b,!0),f.length&&(e=e.append(f));e=e.children()}else{"string"==typeof a&&(a={data:a});l="string"==typeof a.title?a.title:" ";e=g("\x3cli role\x3d'treeitem' /\x3e");a.attr&&(this.i.types.Mz&&!a.attr.type&&(a.attr.type="oj-tree-deftype",e.addClass("oj-tree-type")),e.attr(a.attr));a.metadata&&e.data(a.metadata);
a.children&&0===a.children.length&&e.addClass(c.Kh);a.state&&"s"===a.state&&e.addClass(c.Lm);a.data||(a.data={dummy:0});var p=!1,n;f=g("\x3ca tabindex\x3d'-1' /\x3e");g.each(a.data,function(b,c){g.isFunction(c)&&(c=c.call(this,a));"string"!=typeof c&&("attr"==b?f.attr(c):"style"==b&&f.css(c),"language"==b&&f.addClass(c));p||(n=g("\x3cspan class\x3d'oj-tree-title'\x3e"),n[0].textContent=l,f.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-node-icon oj-component-icon'\x3e\x26#160;\x3c/ins\x3e",n),p=
!0);!c.icon&&a.icon&&(c.icon=a.icon);c.icon&&(-1===c.icon.indexOf("/")?f.children("ins").addClass(c.icon):f.children("ins").css("background","url('"+c.icon+"') center center no-repeat"))});e.append(f);e.prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default'\x3e\x26#160;\x3c/ins\x3e");a.children&&(this.i.sb.iZ&&"expanded"!==a.state?e.addClass(c.Kh).attr("aria-expanded","false").data("oj-tree-children",a.children):(this.i.sb.DA&&e.data("oj-tree-children",
a.children),g.isArray(a.children)&&a.children.length&&(f=this.wq(a.children,b,!0),f.length&&(b=g("\x3cul role\x3d'group' /\x3e"),b.append(f),e.append(b)))))}d||(d=g("\x3cul /\x3e"),d.append(e),e=d);return e},J2:function(a,b,c,d){var e=[],h=this.options,k=this,l,m,p,n,s,r,t,J,F;(a=this.Ka(a))&&-1!==a||(a=this.Ra.find("\x3e ul \x3e li"));b=g.isArray(b)?b:["id","class"];!d&&h.types&&b.push(h.types.attr);c=g.isArray(c)?c:[];a.each(function(){n=g(this);l={};F=k.Pya(n);if(b.length||F&&F.length)l.attr={};
F&&g.each(F,function(a,b){0<n.attr(b).length&&(l.attr[b]=n.attr(b))});g.each(b,function(a,b){(m=n.attr(b))&&m.length&&m.replace(/oj-tree[^ ]*/ig,"").length&&(m=(" "+m).replace(/ oj-tree[^ ]*/ig,"").replace(/ oj-[^ ]*/ig,"").replace(/\s+$/ig," ").replace(/^ /,"").replace(/ $/,""),m.length&&(l.attr[b]=m))});k.ts().iga()&&k.isSelected(n)&&(l.state="s");p=n.data();f(p)||(l.metadata=p);s=n.children("a");m=null;s.each(function(){r=g(this);c.length||r.children("ins").get(0).style.backgroundImage.length||
r.children("ins").get(0).className&&r.children("ins").get(0).className.replace(/oj-tree[^ ]*|$/ig,"").length?(J=k.getText(r),g.each(c,function(a,b){t=(" "+(r.attr(b)||"")).replace(/ oj-tree[^ ]*/ig,"").replace(/ oj-[^ ]*/ig,"").replace(/\s+$/ig," ").replace(/^ /,"").replace(/ $/,"");t.length&&(m||(m={attr:{}}),m.attr[b]=t)}),r.children("ins").get(0).className.replace(/oj-tree[^ ]*|$/ig,"").replace(/^\s+$/ig,"").length&&(t=r.children("ins").get(0).className.replace(/oj-tree[^ ]*|$/ig,"").replace(/ oj-[^ ]*/ig,
"").replace(/\s+$/ig," ").replace(/^ /,"").replace(/ $/,""),t.length&&(m||(m={}),m.icon=t)),r.children("ins").get(0).style.backgroundImage.length&&(t=r.children("ins").get(0).style.backgroundImage.replace("url(","").replace(")",""),t.length&&(m||(m={}),m.icon=t))):J=k.getText(r);null!=m&&(l.data||(l.data=[]),1<s.length?l.data.push(m):l.data=m);l.title=J});n=n.find("\x3e ul \x3e li");n.length&&(l.children=k.J2(n,b,c,!0));e.push(l)});return e},Pya:function(a){var b,c,d;if((a=a[0].attributes)&&a.length){c=
[];d=m.length;for(var e=0;e<a.length;e++)if(b=a[e]){b=b.name;for(var f=0;f<d&&m[f]!=b&&0!=b.indexOf("aria-");f++);f>=d&&c.push(b)}}return c&&0<c.length?c:null},Xu:function(a){a=this.Ka(a);if(!a||-1===a)return!1;a.removeClass("oj-collapsed oj-expanded").removeAttr("aria-expanded").addClass("oj-tree-leaf").children("ul").remove();a.find("ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default").addClass("oj-tree-icon");this.oc({obj:a},
"correct_state",!0)},W9:function(){this.oc(null,"loaded")},Zxa:function(a,b,c){function d(){}function e(){}var f=this.lv().data,h=f&&f.data||null,k=f&&f.ajax||null;if((a=this.Ka(a))&&-1!==a){if(a.data("oj-tree-is-loading"))return;a.data("oj-tree-is-loading",!0)}switch(!0){case !h&&!k&&f&&"string"===typeof f:this.T9(f,a,b,c);break;case g.isFunction(h):h.call(this,a,g.proxy(function(d){this.T9(d,a,b,c)},this));break;case !h&&!k:a&&-1!=a||(this.sa.empty().append(this.i.html.wL).find("li, a").filter(function(){return!this.firstChild||
!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon' \x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.sa.find("li").children("ins:first-child").addClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default"),this.BJ(this.sa),this.i.types.Mz&&this.TB(this.sa),this.zj(),this.sa.find("ul").attr("role",
"group"),this.sa.find("li").attr("role","treeitem"),this.sa.find("a").attr("tabindex",-1));b&&b.call(this);break;case !!h&&!k||!!h&&!!k&&(!a||-1===a):a&&-1!=a||(f=g(h),f.is("ul")||(f=g("\x3cul /\x3e").append(f)),this.sa.empty().append(f.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
this.sa.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.BJ(this.sa),this.i.types.Mz&&this.TB(this.sa),this.zj(),this.sa.find("ul").attr("role","group"),this.sa.find("li").attr("role","treeitem"),this.sa.find("a").attr("tabindex","-1"));b&&b.call(this);break;case !h&&!!k||!!h&&!!k&&a&&-1!==a:a=this.Ka(a),e=function(b,d,e){var f=this.lv().data.ajax.error;
f&&f.call(this,b,d,e);-1!=a&&a.length?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),"success"===d&&this.i.sb.Ti&&this.Xu(a)):"success"===d&&this.i.sb.Ti&&this.sa.empty();c&&c.call(this)},d=function(c,d,f){var h=this.lv().data.ajax.success;h&&(c=h.call(this,c,d,f)||c);if(""===c||c&&c.toString&&""===c.toString().replace(/^[\s\n]+$/,""))return e.call(this,f,d,"");if(c){c=g(c);c.is("ul")||(c=g("\x3cul /\x3e").append(c));-1!=a&&a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),
this.oAa(a),a.append(c).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),a.removeData("oj-tree-is-loading"),a.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),
c=a):(this.sa.empty().append(c.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.sa.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),
c=this.sa);this.lva(c);this.BJ(c);d=c.children("UL");if(1<=d.length){d=d.first().find("span.oj-tree-title");var k=this;g.each(d,function(){this.textContent=k.oI(this.textContent)})}this.i.types.Mz&&c&&this.TB(this.sa);this.zj(a);b&&b.call(this)}else a&&-1!==a?(a.children("a.oj-tree-loading").removeClass("oj-tree-loading"),a.removeData("oj-tree-is-loading"),this.i.sb.Ti&&(this.Xu(a),b&&b.call(this))):this.i.sb.Ti&&(this.sa.empty(),b&&b.call(this)),this.sa.find("ul").attr("role","group"),this.sa.find("li").attr("role",
"treeitem")},f.ajax.context=this,f.ajax.error=e,f.ajax.success=d,f.ajax.dataType||(f.ajax.dataType="html"),g.isFunction(f.ajax.url)&&(f.ajax.url=f.ajax.url.call(this,a)),g.isFunction(f.ajax.data)&&(f.ajax.data=f.ajax.data.call(this,a)),g.ajax(f.ajax)}},lva:function(a){a=a.find(a.is("ul")?"li ul":"ul").filter(function(){return!this.firstChild||0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});g.each(a,function(){g(this).closest("li").addClass(c.Kh)})},oAa:function(a){a=
a.find("ul").filter(function(){return!this.firstChild||0==this.childNodes.length||1==this.childNodes.length&&3==this.firstChild.nodeType});0<a.length&&a.remove()},T9:function(a,b,c){if(a&&""!==a&&a.toString&&""!==a.toString().replace(/^[\s\n]+$/,"")){a=g(a);a.is("ul")||(a=g("\x3cul /\x3e").append(a));-1!=b&&b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),b.append(a).children("ul").find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),
b.removeData("oj-tree-is-loading"),a=b,this.TB(this.DLa)):(this.sa.empty().append(a.children()).find("li, a").filter(function(){return!this.firstChild||!this.firstChild.tagName||"INS"!==this.firstChild.tagName}).prepend("\x3cins class\x3d'oj-tree-icon oj-tree-disclosure-icon'\x3e\x26#160;\x3c/ins\x3e").end().filter("a").children("ins:first-child").not(".oj-tree-node-icon").addClass("oj-tree-node-icon").addClass("oj-tree-icon"),this.sa.find("li.oj-tree-leaf ins:first-child").removeClass("oj-tree-icon oj-tree-disclosure-icon oj-component-icon oj-clickable-icon-nocontext oj-default").removeClass("oj-tree-node-icon").addClass("oj-tree-icon"),
a=this.sa,this.TB(this.sa));a&&this.BJ(a);a=a.children("UL");if(1<=a.length){a=a.first().find("span.oj-tree-title");var d=this;g.each(a,function(){this.textContent=d.oI(this.textContent)})}this.zj(b);c&&c.call(this)}else b&&-1!==b?(b.children("a.oj-tree-loading").removeClass("oj-tree-loading"),b.removeData("oj-tree-is-loading"),this.i.sb.Ti&&(this.Xu(b),c&&c.call(this))):this.i.sb.Ti&&(this.sa.empty(),c&&c.call(this))},BJ:function(a){g.each(a.find("li a"),function(a,b){var c=b.innerHTML,c=c.replace("ins\x3e",
"ins\x3e\x3cspan class\x3d'oj-tree-title'\x3e");b.innerHTML=c+"\x3c/span\x3e"})},TB:function(a){var b,c;this.i.types.Mz&&(c=(b=this.options.types)?b.attr:this.i.types.Zc.attr,g.each(a.find("li"),function(a,b){b=g(b);b.attr(c)||b.attr(c,"oj-tree-deftype").addClass("oj-tree-type")}))},jBa:function(){var a=this;this.i.la.ij=[];this.sa.find("li.oj-expanded").each(function(){this.id&&a.i.la.ij.push("#"+this.id.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,
"\\.").replace(/\:/g,"\\:"))})},pK:function(a){var b=this,c=!0,d=[],e=[],f,h;a||(this.i.la.mZ=!1,this.i.la.EIa=!0);this.Cxa()&&(this.i.la.ij=[],this.sa.find("li.oj-collapsed").each(function(){h="#"+g(this).attr("id");b.isExpanded(h)||b.i.la.ij.push(h)}));this.i.la.ij=g.map(g.makeArray(this.i.la.ij),function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});this.i.la.Ep=g.map(g.makeArray(this.i.la.Ep),
function(a){return"#"+a.toString().replace(/^#/,"").replace(/\\\//g,"/").replace(/\//g,"\\/").replace(/\\\./g,".").replace(/\./g,"\\.").replace(/\:/g,"\\:")});this.i.la.ij.length&&(this.i.la.Ep=this.i.la.Ep.concat(this.i.la.ij),this.i.la.Ep=this.i.la.Ep.reduce(function(a,b){0>a.indexOf(b)&&a.push(b);return a},[]));this.i.la.Ep.length&&(g.each(this.i.la.Ep,function(a,c){if("#"==c)return!0;f=b.Ra.find(c);f.length?b.isExpanded(c)||d.push(c):e.push(c)}),d.length&&(this.i.la.Ep=e,g.each(d,function(a,d){b.sq(d)||
(b.tq(d,function(){b.pK(!0)},function(){b.pK(!0)}),c=!1)})));this.i.la.ij.length&&g.each(this.i.la.ij,function(a,c){b.isExpanded(c)||b.bg(c,!1,!0)});c&&(this.i.la.mZ&&clearTimeout(this.i.la.mZ),this.i.la.mZ=setTimeout(function(){b.oc({},"reload_nodes",!0)},50),this.i.la.EIa=!1,this.MAa())},setTheme:function(a,b){if(!a)return!1;b||(b=this.i.yc.nE+a+"/style.css");-1==g.inArray(b,this.i.yc.Aia)&&(h({url:b}),this.i.yc.Aia.push(b));this.i.yc.MA!=a&&(this.Ra.removeClass("oj-tree-"+this.i.yc.MA),this.i.yc.MA=
a);this.Ra.addClass("oj-tree-"+a);this.i.yc.LE?this.Xba():this.B8();this.i.yc.icons?this.UV():this.ZT()},Hxa:function(){return null!=this.i.yc},MKa:function(){return this.i.yc.MA},isIcons:function(){return this.i.yc.icons},UV:function(){this.i.yc.icons=!0;this.Ra.children("ul").removeClass("oj-tree-no-icons")},ZT:function(){this.i.yc.icons=!1;this.Ra.children("ul").addClass("oj-tree-no-icons")},toggleIcons:function(){},Era:function(){this.i.keys.sFa=!0},Swa:function(){this.Jwa();this.Iwa();this.S8(!0);
this.Uwa();this.ts().dga();this.Hwa();this.Wwa();this.Rwa();this.T8();this.Vwa();this.ts().cga();this.Ds()},oc:function(a,b,c){if(b&&"string"===g.type(b)&&(!0!==this.i.la.locked||"unlock"===b||"isLocked"===b||"lock"===b)){var d,e=Array.prototype.slice.call(arguments);d=this.Ra;var f="before"===b,h=c?!1:!0;h||(b="_tree"+b);var k={};k.item=a?a.obj:void 0;k.inst=d;f?(d=a.func,k.func=d,k.args=e,"rename"===d&&(k.title=a.title,k.prevTitle=a.prevTitle)):h&&("move"==b?(k.position=a.pr,k.reference=a.Sa,k.data=
a):"rename"==b?(k.title=a.title,k.prevTitle=a.prevTitle):"remove"==b?(k.parent=a.parent,k.prev=a.prev):"delete"==b?(k.prev=a.prev,k.parent=a.parent):"expandAll"===b||"collapseAll"===b||"deselectAll"===b?k.targ=a.targ:"loaded"===b&&(k.item=-1));if(h){if(e=this._trigger(b,new g.Event("oj"+b),k),f)return"undefined"!=typeof e&&(e=e?!0:!1),e}else this.Ra.trigger(b,k)}},CC:function(a,b,c,d){"selection"===a&&(null==c&&(c=this.ZS()),this.t4(b,c)||this.option(a,c,{_context:{originalEvent:d,ob:!0},changed:!0}))},
Ou:function(){return this.get_rollback()},Pj:function(){this.MJ&&this.Ra.addClass("oj-tree-rtl").css("direction","rtl");this.Ra.html("\x3cul role\x3d'tree' tabindex\x3d'0' class\x3d'oj-tree-list' style\x3d'outline:none'"+(-1===this.i.la.wr?" aria-multiselectable\x3d'true'":"")+" aria-labelledby\x3d'"+this.av+"'\x3e\x3cli class\x3d'oj-tree-last oj-tree-leaf'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e\x3ca class\x3d'oj-tree-loading' href\x3d'#'\x3e\x3cins class\x3d'oj-tree-icon'\x3e\x26#160;\x3c/ins\x3e"+
this.cT("stateLoading")+"\x3c/a\x3e\x3c/li\x3e\x3c/ul\x3e");this.sa=this.Ra.children("ul:eq(0)");this.Ra.data("oj-tree-instance-id",this.Ej());this.i.la.wt=this.sa.find("li.oj-collapsed, li.oj-tree-leaf").eq(0).height()||18;this.Ry&&this.Ra.delegate(".oj-tree-list ins.oj-tree-disclosure-icon","touchend.ojtree",g.proxy(function(a){a.preventDefault();a=g(a.target);this.toggleExpand(a)},this));this.Ra.delegate(".oj-tree-list ins.oj-tree-disclosure-icon","click.ojtree",g.proxy(function(a){a=g(a.target);
this.toggleExpand(a)},this)).delegate(".oj-tree-list ins.oj-tree-disclosure-icon","mousedown",g.proxy(function(a){this.i.ui.pX=!0;g(a.target).removeClass("oj-default").removeClass(c.Eu).addClass(c.Lm)},this)).delegate(".oj-tree-list ins.oj-tree-disclosure-icon","mouseup",g.proxy(function(a){g(a.target).removeClass(c.Lm).addClass("oj-default")},this)).bind("mousedown.ojtree",g.proxy(function(){this.Nj()},this)).bind("dblclick.ojtree",function(){var a;if(document.selection&&document.selection.empty)document.selection.empty();
else if(window.getSelection){a=window.getSelection();try{a.removeAllRanges(),a.collapse(document.getElementsByTagName("body")[0],0)}catch(b){}}});this.sa.focus(g.proxy(function(){if(this.i.ui.pX)this.i.ui.pX=!1;else{this.i.ui.Sl=!0;var a;this.i.ui.Wl?(this.i.ui.Fc=this.i.ui.Wl,a=this.i.ui.Fc):this.i.ui.Nc&&0<this.i.ui.Nc.length?(this.i.ui.Fc=this.i.ui.Nc,a=this.i.ui.Fc):a=this.sa.find("li:first");a&&(this.hover(a),this.i.ui.Wl=null,this.sa.find("a.oj-selected").removeClass("oj-tree-inactive"))}},
this)).blur(g.proxy(function(){this.i.ui.Sl=!1;this.i.ui.Wl=this.i.ui.Fc;this.i.ui.Wl&&this.dehover(this.i.ui.Fc);this.sa.find("a.oj-selected").addClass("oj-tree-inactive")},this));this.oc({},"init",!0);this.U9();this.i.menu.wh&&this.WB();b({w8:this.Sy,mba:this.sa,oE:this});this.Era()},Hwa:function(){this.i.la.locked=!1;this.Ra.addClass("oj-tree oj-tree-"+this.Ej());this.Ra.css("outline","none");this.Ra.css("MozUserSelect","none");this.Ra.css("WebkitTouchCallout","none");this.Ra.css("WebkitUserSelect",
"none");this.Ra.css("WebkitTapHighlightColor","rgba(0,0,0,0)")},Wwa:function(){this.i.ui.selected=g();this.i.ui.Nc=!1;this.i.ui.Fc=null;var a=this.options.selection;a&&"array"===g.type(a)&&0<a.length&&(this.i.ui.XF=a,this.options.selection=[]);this.Ry&&this.Ra.delegate(".oj-tree-list a","touchend.ojtree",g.proxy(function(a){this.i.ui.Tw=!0;this.o8(a);g(a.currentTarget).hasClass("oj-tree-loading")||this.dehover()},this));this.Ra.delegate(".oj-tree-list a","click.ojtree",g.proxy(function(a){this.i.ui.Tw=
!1;this.o8(a)},this)).delegate(".oj-tree-list a","mouseenter.ojtree",g.proxy(function(a){g(a.currentTarget).hasClass("oj-tree-loading")||this.hover(a.target)},this)).delegate(".oj-tree-list a","mouseleave.ojtree",g.proxy(function(a){g(a.currentTarget).hasClass("oj-tree-loading")||this.dehover(a.target)},this)).delegate(".oj-tree-list .oj-tree-disclosure-icon","mouseenter.ojtree",g.proxy(function(a){g(a.currentTarget).hasClass("oj-tree-loading")||this.q5(a.target,!0)},this)).delegate(".oj-tree-list .oj-tree-disclosure-icon",
"mouseleave.ojtree",g.proxy(function(a){g(a.currentTarget).hasClass("oj-tree-loading")||this.q5(a.target,!1)},this)).bind("_treereopen",g.proxy(function(){this.reselect()},this)).bind("_treeget_rollback",g.proxy(function(){this.dehover();this.saveSelected()},this)).bind("ojcollapse",g.proxy(function(a,b){var c=this.Ka(b.item),d=c&&c.length?c.children("ul").find("a.oj-selected"):g(),e=this;!1!==this.options.selectedParentCollapse&&d.length&&d.each(function(){"selectParent"===e.options.selectedParentCollapse?
(e.deselect(this),e.select(c)):"deselect"===e.options.selectedParentCollapse&&e.deselect(this)})},this)).bind("ojremove",g.proxy(function(a,b){var c=this.options.selectPrevOnDelete,d=this.Ka(b.item),d=d&&d.length?d.find("a.oj-selected"):[],e=this,f;d.each(function(){e.deselect(this);e.i.ui.Wl&&(f=e.Ka(this))&&e.i.ui.Wl.attr("id")==f.attr("id")&&(e.i.ui.Wl=null)});c&&d.length&&b.prev&&b.prev.each(function(){if(this.parentNode)return e.select(this),!1})},this)).bind("ojmove",g.proxy(function(a,b){var d=
b.data,e=d.EL;e&&d.aZ&&(d.aZ.find("a.oj-selected").removeClass(c.Lm),d.aZ.removeAttr("aria-selected"));d.Cp===d.Tt||e||(e=d.Cp.i.ui,e.Wl&&(d.lc.attr("id")==e.Wl.attr("id")&&(e.Wl=null),e.Nc&&d.lc.attr("id")==e.Nc.attr("id")&&(e.Nc=null)))},this))},T8:function(){this.Twa();this.Owa();this.Nwa()},Twa:function(){1===this.i.sb.type&&(this.zca=this.options.data||null,this.tq=this.aya,this.sq=this.Jxa,this.Ff=this.Yza)},Owa:function(){3===this.i.sb.type&&(this.i.sb.DA&&this.Ra.bind("_treeafter_close",function(a,
b){b.item.children("ul").remove()}),this.tq=this.cya,this.sq=this.Lxa,this.Ff=this.Zza)},Nwa:function(){4===this.i.sb.type&&(this.N$(),this.tq=this.bya,this.sq=this.Kxa,this.Ff=this.mV)},N$:function(){this.i.html.GN&&(this.i.html.vA||(this.i.html.vA=this.Ra.find(" \x3e ul"),this.i.html.eN=g("\x3cdiv id\x3d'oj-tree-existing-markup-"+this.Ej()+"' style\x3d'display:none'\x3e").append(this.i.html.vA),this.Ra.after(this.i.html.eN)),this.i.html.Vga=this.i.html.vA.find(" \x3e li"),this.i.html.wL=this.i.html.Vga.clone(!0),
this.i.html.wL.find("li").addBack().contents().filter(function(){return 3==this.nodeType}).remove())},Rwa:function(){!1===this.i.yc.nE&&g("script").each(function(){if(this.src.toString().match(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/))return this.i.yc.nE=this.src.toString().replace(/jquery\.oj-tree[^\/]*?\.js(\?.*)?$/,"")+"themes/",!1});!1===this.i.yc.nE&&(this.i.yc.nE="themes/");this.Ra.bind("_treeinit",g.proxy(function(){var a=this.options;this.i.yc.LE=a.dots;this.i.yc.icons=a.icons;this.setTheme(this.i.yc.MA,
this.i.yc.url)},this)).bind("ojloaded",g.proxy(function(){this.i.yc.LE?this.Xba():this.B8();this.i.yc.icons?this.UV():this.ZT()},this))},Vwa:function(){var a=this.options.types;a&&this.Ra.bind("_treeinit",g.proxy(function(){var b=g.extend(!0,{},a.types),c=a.attr||this.i.types.Zc.attr,d="",e=this;g.each(b,function(a,b){g.each(b,function(a){/^(maxDepth|maxChildren|icon|validChildren)$/.test(a)||e.i.types.qda.push(a)});var f=typeof b.icon;if("undefined"===f){f=typeof b.image;if("boolean"===f&&!b.image)b.image=
"ojt$none";else if(!b.image&&!b.position)return!0;b.icon={};b.image&&(b.icon.image=b.image,delete b.image);void 0!==b.position&&(b.icon.position=b.position,delete b.position)}if(b.icon.image||b.icon.position)"default"==a?(e.i.types.Mz=!0,d+=".oj-tree-"+e.Ej()+" .oj-tree-list li.oj-tree-type a \x3e .oj-tree-node-icon { ",d+=e.X2(b,d),d+="} ",d+=".oj-tree-"+e.Ej()+" .oj-tree-list li["+c+'\x3d"oj-tree-deftype"].oj-tree-type \x3e a ins.oj-tree-node-icon { '):b.icon.image&&(d+=".oj-tree-"+e.Ej()+" .oj-tree-list li["+
c+'\x3d"'+a+'"].oj-tree-type \x3e a \x3e ins.oj-tree-node-icon { '),d+=e.X2(b,d),d+="} "});""!==d&&h({AN:d,title:"oj-tree-types"})},this)).bind("ojbefore",g.proxy(function(a,b){var c,d,e=b.func,f=b.item;if((c=(c=this.i.types.Zc.useData?this.Ka(f):!1)&&-1!==c&&c.length?c.data("oj-tree"):!1)&&c.types&&!1===c[e]||-1!==g.inArray(e,this.i.types.qda)&&b.item&&(b.item.tagName||b.item.jquery)&&(c=this.options.types.types,d=this.mT(f),(c[d]&&"undefined"!==typeof c[d][e]||c["default"]&&"undefined"!==typeof c["default"][e])&&
!1===this.Xoa(e,f)))return a.stopImmediatePropagation(),!1},this))},X2:function(a){var b="",b="ojt$none"!==a.icon.image?b+(" background-image:url("+a.icon.image+"); "):b+" background-image:none; ";return b=a.icon.position?b+(" background-position:"+a.icon.position+"; "):b+" background-position:0 0; "},ts:function(){this.LB||(this.LB=new a.wa(this));return this.LB},PKa:function(){},Ds:function(a){var b;a||this.options.contextMenu||(b=this.Ra.attr("contextmenu"))&&(this.options.contextMenu="#"+b);if(a||
this.options.contextMenu)if(b=a||this.options.contextMenu){if(b=g(b)){b.css("display","none");var c=this.i.menu;c.df=b;c.wh=!0}this.i.menu.wh&&a&&this.WB()}},Dk:function(a,b){if(!b.inst&&this.i.menu.GJa==this.av){var c=b?b.item.attr("id"):void 0;"ojtreecopy"===c?this.Hqa(this.i.menu.In):"ojtreecut"===c?this.Jqa(this.i.menu.In):"ojtreepaste"===c?this.Kqa(this.i.menu.In):"ojtreeremove"===c?this.isSelected(this.i.menu.In)?this.U4():this.U4(this.i.menu.In):"ojtreerename"===c?this.V4(this.i.menu.In):"ojtreecreate"===
c&&this.Iqa(this.i.menu.In)}},ih:function(a,b,d){var e="keyboard"===d;if("contextmenu"==b.type||e||"touch"==d){this.i.menu.In=e?this.i.ui.Fc:g(b.target);var f=this.i.menu.In.find(".oj-tree-title")[0];this.i.menu.oL=null;this.i.menu.In?(this.i.menu.GJa=this.i.menu.In.closest("div").attr("id"),a={launcher:this.sa},e&&(a.position={of:f}),this.i.menu.wh&&this.i.menu.NA&&(e=!this.i.Vd.Rl&&!this.i.Vd.fw,!!this.i.menu.NA.hasClass(c.Se)!=e&&(e?this.i.menu.NA.addClass(c.Se):this.i.menu.NA.removeClass(c.Se),
this.i.menu.df.ojMenu("refresh"))),this.jh(b,d,a)):b.preventDefault()}},Iwa:function(){var a=this.options.selectionMode,a=void 0==a?"single":a;"none"===a?a=0:"single"===a?a=1:"multiple"===a&&(a=-1);this.i.la.wr=a;this.i.yc.icons=this.options.icons;this.V8();this.i.la.Ep=this.options.initLoaded},SKa:function(){},S8:function(b){var c=this.options.data,d;this.i.sb.type=0;this.i.html.GN=!1;this.i.html.wL=!1;if(c)if(d=g.type(c),"string"===d)this.vxa(c)?this.i.sb.type=4:this.i.sb.type=3;else if("array"===
d)this.i.sb.type=3;else if("object"===d){try{c instanceof a.td&&(this.i.sb.type=1)}catch(e){this.i.sb.type=-1}if(1!==this.i.sb.type)try{c instanceof a.mb&&(this.i.sb.type=2)}catch(f){this.i.sb.type=-1}1!==this.i.sb.type&&2!==this.i.sb.type&&(c.data||c.ajax)&&((d=c.dataType)?"json"===d?this.i.sb.type=3:"html"===d&&(this.i.sb.type=4):(c.dataType="json",this.i.sb.type=3))}b&&0==this.i.sb.type&&0<this.Ra.find("ul").length&&(this.i.sb.type=4,this.i.html.GN=!0)},RKa:function(){},OKa:function(){},NKa:function(){},
QKa:function(){},Uwa:function(){var a=this.options.types;"object"===typeof a&&this.goa(a,{attr:this.i.types.Zc.attr})},V8:function(){this.i.la.ij=this.LDa(this.options,"initExpanded");null==this.i.la.ij&&(this.i.la.ij=[])},Jwa:function(){var a=this.i;a.la={uHa:[],wr:1,wLa:!1,wt:0,ij:!1,Ep:!1,hj:{},Sw:!1,sJa:{}};a.ui={selected:g(),Nc:!1,Fc:null,Wl:null,pX:!1,XF:null,opacity:1,DZ:!1,Sl:!1,ida:null,Tw:!1};a.ui.Zc={selectMultipleModifier:"ctrl",selectRangeModifier:"shift",disableSelectingChildren:!1};
a.Vd={};a.Vd.fw=!1;a.Vd.Rl=!1;a.Vd.Zc={inputWidthLimit:200,move:{alwaysCopy:!1,openOnMove:!0,defaultPosition:"last",checkMove:function(){return!0}}};a.Vd.hj={};a.sb={};a.sb.iZ=!1;a.sb.DA=!1;a.sb.Ti=!0;a.sb.type=0;a.PHa={};a.PHa.Zc={data:!1,ajax:!1};a.html={};a.html.Zc={data:!1,ajax:!1};a.html.GN=!1;a.html.vA=!1;a.html.eN=!1;a.html.Vga=!1;a.html.wL=!1;a.yc={};a.yc.icons=!0;a.yc.LE=!1;a.yc.MA="default";a.yc.url=!1;a.yc.Aia=[];a.yc.nE=!1;a.types={};a.types.qda=[];a.types.Mz=!1;a.types.Zc={maxChildren:-1,
maxDepth:-1,validChildren:"all",useData:!1,attr:"type",types:{"default":{maxChildren:-1,maxDepth:-1,validChildren:"all"}}};a.menu={};a.menu.wh=!1;a.menu.df=!1;a.menu.NA=!1;a.menu.In=!1;a.menu.oL=!1;a.keys={};a.keys.sFa=!0;a.keys.bound=[]},a6:function(a){var b=this.Ra[0];b.scrollHeight>b.offsetHeight&&(a=this.Ka(a))&&-1!==a&&a.length&&a.is(":visible")&&(a=a.offset().top-this.Ra.offset().top,0>a&&(b.scrollTop=b.scrollTop+a-1),a+this.i.la.wt+(b.scrollWidth>b.offsetWidth?s:0)>b.offsetHeight&&(b.scrollTop+=
a-b.offsetHeight+this.i.la.wt+1+(b.scrollWidth>b.offsetWidth?s:0)))},Nj:function(){},dLa:function(){},Hya:function(){return++p},Ej:function(){return this.Cwa},lv:function(){return g.extend(!0,{},this.options)},zKa:function(){return this.Ra},AKa:function(){return this.sa},Sy:{up:function(){this.hover(this.nq(this.i.ui.Fc||this.i.ui.Nc||-1));return!1},"ctrl+up":function(){this.hover(this.nq(this.i.ui.Fc||this.i.ui.Nc||-1));return!1},"shift+up":function(){this.select(this.nq(this.i.ui.Fc||this.i.ui.Nc||
-1),-1!==this.i.ui.wr);return!1},down:function(){this.hover(this.kv(this.i.ui.Fc||this.i.ui.Nc||-1));return!1},"ctrl+down":function(){this.hover(this.kv(this.i.ui.Fc||this.i.ui.Nc||-1));return!1},"shift+down":function(){this.select(this.kv(this.i.ui.Fc||this.i.ui.Nc||-1),-1!==this.i.ui.wr);return!1},left:function(){var a=this.i.ui.Fc||this.i.ui.Nc;a&&(a.hasClass(c.tl)?this.collapse(a):this.hover(this.nq(a)));return!1},"ctrl+left":function(){var a=this.i.ui.Fc||this.i.ui.Nc;a&&(a.hasClass(c.tl)?this.collapse(a):
this.hover(this.nq(a)));return!1},"shift+left":function(){var a=this.i.ui.Fc||this.i.ui.Nc;a&&(a.hasClass(c.tl)?this.collapse(a):this.hover(this.nq(a)));return!1},right:function(){var a=this.i.ui.Fc||this.i.ui.Nc;a&&a.length&&(a.hasClass(c.Kh)?this.expand(a):this.hover(this.kv(a)));return!1},"ctrl+right":function(){var a=this.i.ui.Fc||this.i.ui.Nc;a&&a.length&&(a.hasClass(c.Kh)?this.expand(a):this.hover(this.kv(a)));return!1},"shift+right":function(){var a=this.i.ui.Fc||this.i.ui.Nc;a&&a.length&&
(a.hasClass(c.Kh)?this.expand(a):this.hover(this.kv(a)));return!1},space:function(){this.i.ui.Fc&&(this.i.ui.DZ=!0,this.i.ui.Fc.children("a:eq(0)").click(),this.i.ui.DZ=!1);return!1},home:function(){this.hover(this.sa.find("li:first"));return!1},end:function(){var a=this.sa.find("li.oj-tree-last:visible");a&&a.length&&this.hover(a[a.length-1]);return!1},"*":function(){this.sa.find("a");this.VR(-1,!1);return!1},"ctrl+space":function(){if(this.i.ui.Fc){var a=g.Event("click");a.ctrlKey=!0;this.i.ui.Fc.children("a:eq(0)").trigger(a)}return!1},
"shift+space":function(){if(this.i.ui.Fc){var a=g.Event("click");a.shiftKey=!0;this.i.ui.Fc.children("a:eq(0)").trigger(a)}return!1},"shift+home":function(a){var b,c=this.i.ui.Fc;if(c){var d=!0,e=this,f=this.sa.find("li:visible");this.i.la.Sw=!0;b=this.options.selection.slice(0);c=c[0];g.each(f,function(a,b){b==c&&(d=!1);e.kn(b,!0);return d});this.i.la.Sw=!1;this.CC("selection",b,null,a)}return!1},"shift+pgdn":function(a){var b,c=this.i.ui.Nc||this.i.ui.Fc;if(c){var d=!1,e=this,f=this.sa.find("li:visible");
this.i.la.Sw=!0;b=this.options.selection.slice(0);c=c[0];g.each(f,function(a,b){d||(d=b==c);d&&!e.isSelected(b)&&e.kn(b,!0);return!0});this.i.la.Sw=!1;this.CC("selection",b,null,a)}return!1},f2:function(){this.V4(this.i.ui.Fc||this.i.ui.Nc);return!1},del:function(){this.remove(this.i.ui.Fc||this.Ka(null));return!1}},WB:function(){if(this.i.menu.wh){var a=this.i.menu.df,b=this;a.on("ojselect",g.proxy(this.Dk,this));var c=!1;a.find("[data-oj-command]").each(function(){var a;0===g(this).children("a").length&&
(a=g(this).attr("data-oj-command").split("oj-tree-"),g(this).replaceWith(b.yj(a[a.length-1])),g(this).hasClass("oj-menu-divider")&&g(this).removeClass("oj-menu-divider").addClass("oj-menu-item"),c=!0)});c&&a.ojMenu("refresh");this.i.menu.NA=a.find("#ojtreepaste")}},Tu:function(){var a=this.i.menu;a.wh&&(a.wh=!1,a.df.off("ojselect"),a.df=null)},yj:function(a){return g(this.$f(a))},$f:function(a){return"\x3cli id\x3d"+k[a]+"\x3e"+this.bC(a)+"\x3c/li\x3e"},bC:function(a){return'\x3ca href\x3d"#"\x3e'+
this.cT(l[a])+"\x3c/a\x3e"},Jqa:function(a){a=this.Ka(a,!0);if(!a||!a.length)return!1;this.i.Vd.fw=!1;this.i.Vd.Rl=a;this.oc({obj:a},"cut")},Hqa:function(a){a=this.Ka(a,!0);if(!a||!a.length)return!1;this.i.Vd.Rl=!1;this.i.Vd.fw=a;this.oc({obj:a},"copy")},Kqa:function(a){a=this.Ka(a);if(!a||!a.length)return!1;var b=this.i.Vd.Rl?this.i.Vd.Rl:this.i.Vd.fw;if(!this.i.Vd.Rl&&!this.i.Vd.fw)return!1;this.i.Vd.Rl&&(this.uR(this.i.Vd.Rl,a),this.i.Vd.Rl=!1);this.i.Vd.Rl&&(this.uR(this.i.Vd.Rl,a),this.i.Vd.Rl=
!1);this.i.Vd.fw&&this.uR(this.i.Vd.fw,a,!1,!0);this.oc({obj:a,nodes:b},"paste")},uR:function(a,b,c,d,e,f){var g=this.i.Vd.Zc.move;if(!e)return"undefined"===typeof c&&(c=g.defaultPosition),"inside"!==c||g.defaultPosition.match(/^(before|after)$/)||(c=g.defaultPosition),this.yD(a,b,c,d,!1,f);if(!0===g.alwaysCopy||"multitree"===g.alwaysCopy&&a.Tt.Ej()!==a.Cp.Ej())d=!0;this.yD(a,b,c,d,!0,f)},U4:function(a){a=this.Ka(a,!0);this.Ou();this.remove(a)},V4:function(a){a=this.Ka(a);this.Ou();this.W4(a,function(){})},
W4:function(a,b){a=this.Ka(a);var c=this.MJ,d=this.i.Vd.Zc.inputWidthLimit,e=a.children("ins").width(),f=a.find("\x3e a:visible \x3e ins").width()*a.find("\x3e a:visible \x3e ins").length,h=this.getText(a),k=this,l=g("\x3cdiv /\x3e",{css:{position:"absolute",top:"-200px",left:c?"0px":"-1000px",visibility:"hidden"}}).appendTo("body"),m=a.css("position","relative").append(g("\x3cinput /\x3e",{value:h,"class":"oj-tree-rename-input",css:{padding:"0",border:"1px solid silver",position:"absolute",left:c?
"auto":e+f+4+"px",right:c?e+f+4+"px":"auto",top:"0px",height:this.i.la.wt-2+"px",lineHeight:this.i.la.wt-2+"px",width:"150px"},blur:g.proxy(function(){var c=a.children(".oj-tree-rename-input"),d=c.val();""===d&&(d=h);l.remove();c.remove();this.PV(a,h);this.Gaa(a,d);b.call(this,a,d,h);a.css("position","")},this),keyup:function(a){a=a.keyCode||a.which;if(!k.NR)return k.NR=!0,!1;27==a?(k.NR=!1,this.value=h,this.blur()):13==a?(k.NR=!1,this.blur()):m.width(Math.min(l.text("pW"+this.value).width(),d))},
keypress:function(a){if(13==(a.keyCode||a.which))return!1}})).children(".oj-tree-rename-input");this.PV(a,"");l.css({fontFamily:m.css("fontFamily")||"",fontSize:m.css("fontSize")||"",fontWeight:m.css("fontWeight")||"",fontStyle:m.css("fontStyle")||"",fontStretch:m.css("fontStretch")||"",fontVariant:m.css("fontVariant")||"",letterSpacing:m.css("letterSpacing")||"",wordSpacing:m.css("wordSpacing")||""});m.width(Math.min(l.text("pW"+m[0].value).width(),d))[0].select()},Iqa:function(a,b,d,e,f){var h=
this;(a=this.Ka(a))||(a=-1);this.Ou();return this.oC(a,b,d,function(a){var b=this.Zm(a),d=g(a).index();e&&e.call(this,a);b.length&&b.hasClass(c.Kh)&&this.expand(b,!1,!0);f?h.oc({obj:a,name:this.getText(a),parent:b,position:d}):this.W4(a,function(a,c){h.oc({obj:a,name:c,parent:b,position:d})})})},vxa:function(a){var b=!1;a&&3<=a.length&&(a=a.trim(),b="\x3c"===a.charAt(0));return b},hoa:function(){var a=this.options.emptyText;"string"!==typeof a&&(a=this.cT("labelNoData"));if(a&&0<a.length){var b=this.sa,
c=g("\x3cli class\x3d'oj-tree-empty'\x3e\x3c/li\x3e");c[0].textContent=a;b.empty().append(c)}},Cza:function(a){var b,c,d;d=null;var e;a&&(b=a.subId);if(!b)return null;d=b.split("[");if(3===d.length&&(d[0]=d[0].trim(),"oj-tree-node"===d[0]&&(d[1]=d[1].trim(),b=d[1].charAt(0),b=d[1].indexOf(b,1),0<=b&&(a=d[1].substring(1,b).trim(),d[2]=d[2].trim(),b=d[2].charAt(0),b=d[2].indexOf(b,1),0<=b)))){d=d[2].substring(1,b).trim();try{c=this.Ka(a)}catch(f){c=null}if(d&&c&&-1!==c)switch(d){case "icon":this.i.yc.icons&&
(e=c.find(" \x3e a \x3e ins:eq(0)"));break;case "link":e=c.find(" \x3e a:eq(0)");break;case "disclosure":this.rU(c)||(e=c.find(" \x3e ins:eq(0)"));break;case "title":e=c.find(" \x3e a \x3e span")}}return e?e.length?e[0]:null:null},Uta:function(a){var b=a?this.Ka(a):null,c,d=null;b&&-1!=b&&b.length&&b.hasClass("oj-tree-node")&&a.tagName&&a.parentNode&&(b=a.tagName,c=a.parentNode,c=c.tagName,"SPAN"===b?d="title":"A"===b?d="link":"INS"===b&&(a=g(a),"LI"===c&&a.hasClass("oj-tree-disclosure-icon")?d="disclosure":
"A"===c&&a.hasClass("oj-tree-node-icon")&&(d="icon")));return d},B8:function(){this.i.yc.LE=!1;this.Ra.children("ul").addClass("oj-tree-no-dots")},Xba:function(){this.i.yc.LE=!0;this.Ra.children("ul").removeClass("oj-tree-no-dots")},Cxa:function(){var a=this.options.initExpanded;return a&&"all"==a||g.isArray(a)&&a.length&&"all"==a[0]},cT:function(a){var b=this.i.la.sJa,c;c=b[a];c||(c=this.F(a),c=this.oI(c),b[a]=c);return c},oI:function(a){var b=document.createElement("div");g(b).text(a);return b.textContent},
HKa:function(){return this.i.la.wt},nsa:function(){var a=0,b,c;window.getComputedStyle&&(c=this.i.ui.ida,c||(c=g("\x3cdiv id\x3d'ojtree-comp-animduration'\x3e\x3cspan class\x3d'oj-tree-transition'\x3edummy\x3c/span\x3e\x3c/div\x3e"),this.i.ui.ida=c,g("body").append(c)),b=c[0].childNodes[0],b=window.getComputedStyle(b),b=b.transitionDuration?b.transitionDuration:b["-webkit-transition-duration"]?b["-webkit-transition-duration"]:0,c.detach(),"string"==typeof b&&1<b.length&&(c=b.charAt(b.length-1).toLowerCase(),
"s"==c?(b=b.substring(0,b.length-1),b=parseFloat(b),isNaN(b)||(a=1E3*b)):2<b.length&&(c=b.substring(b.length-2).toLowerCase(),"ms"==c&&(b=parseFloat(b),isNaN(b)||(a=b)))));return a},LDa:function(a,b){var c={};c[b]=a[b];return g.extend(!0,{},c)[b]},Lca:function(a){this.oc({obj:{msg:a}},"trace",!0)}})})();a.Components.Ta("ojTree","baseComponent",{properties:{data:{type:"Object|Array|string"},disabled:{type:"boolean"},dnd:{type:"Object"},emptyText:{type:"string"},expandParents:{type:"boolean"},icons:{type:"boolean"},
initExpanded:{type:"Array"},selectedParentCollapse:{type:"boolean|string"},selectedParentExpand:{type:"boolean"},selection:{type:"Array"},selectionMode:{type:"string"},selectPrevOnDelete:{type:"boolean"},types:{type:"Object"}},methods:{collapse:{},collapseAll:{},create:{},dehover:{},deselect:{},deselectAll:{},destroy:{},expand:{},expandAll:{},expanded:{},getChildren:{},getContextByNode:{},getNextSibling:{},getNodeBySubId:{},getParent:{},getPath:{},getPrevSibling:{},getRoot:{},getSubIdByNode:{},getText:{},
getType:{},hover:{},isCollapsed:{},isExpanded:{},isLeaf:{},isSelected:{},move:{},refresh:{},remove:{},rename:{},scrollIntoView:{},select:{},setType:{},toggleExpand:{},toggleSelect:{}},extension:{_widgetName:"ojTree"}});a.Components.register("oj-tree",a.Components.getMetadata("ojTree"))});