/**
 * Copyright (c) 2014, 2016, Oracle and/or its affiliates.
 * The Universal Permissive License (UPL), Version 1.0
 */
"use strict";
define(["ojs/ojcore","jquery","ojL10n!ojtranslations/nls/localeElements","ojs/ojmessaging"],function(a,g,c){a.hb={};o_("LocaleData",a.hb,a);a.hb.rZ=function(b){a.hb.BQ=b};o_("LocaleData.setBundle",a.hb.rZ,a);a.hb.Nea=function(){return a.hb.nT("firstDay")};o_("LocaleData.getFirstDayOfWeek",a.hb.Nea,a);a.hb.tGa=function(){return a.hb.nT("weekendStart")};o_("LocaleData.getWeekendStart",a.hb.tGa,a);a.hb.sGa=function(){return a.hb.nT("weekendEnd")};o_("LocaleData.getWeekendEnd",a.hb.sGa,a);a.hb.PE=function(b){if(null==
b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.hb.oS().days["stand-alone"][b];return[b.sun,b.mon,b.tue,b.wed,b.thu,b.fri,b.sat]};o_("LocaleData.getDayNames",a.hb.PE,a);a.hb.UE=function(b){if(null==b||"abbreviated"!==b&&"narrow"!==b)b="wide";b=a.hb.oS().months["stand-alone"][b];return[b["1"],b["2"],b["3"],b["4"],b["5"],b["6"],b["7"],b["8"],b["9"],b["10"],b["11"],b["12"]]};o_("LocaleData.getMonthNames",a.hb.UE,a);a.hb.kga=function(){var b=a.hb.oS().dateFormats["long"].toUpperCase(),c=b.indexOf("M"),
b=b.indexOf("Y");return c<b};o_("LocaleData.isMonthPriorToYear",a.hb.kga,a);a.hb.nT=function(b){var c=a.hb.vl(),d=a.hb.Jta()||"001";b=c.supplemental.weekData[b];d=b[d];void 0===d&&(d=b["001"]);return d};a.hb.oS=function(){var b=a.hb.vl().main,c,d;for(d in b)if(b.hasOwnProperty(d)){c=b[d];break}return c.dates.calendars.gregorian};a.hb.Jta=function(){var b=a.fa.Wi();if(b&&(b=b.toUpperCase().split(/-|_/),2<=b.length)){var c=b[1];if(4==c.length){if(3<=b.length)return b[2]}else return c}return null};a.hb.vl=
function(){var b=a.hb.BQ;return b?b:a.Rx()?(a.o.assert(void 0!==c,"LocaleElements module must be loaded"),c):{}};a.hb.ona=function(a){c=a};a.Ea={};o_("Validation",a.Ea,a);a.Ea.nR={};a.Ea.OW={};a.Ea.c5={};a.Ea.f5={};a.Ea.DG={converter:{name:"oj.ConverterFactory",type:a.Rn},validator:{name:"oj.ValidatorFactory",type:a.Pe}};a.Ea.qn=function(b,c){var d;b&&!c?d=a.Ea.MI(b,a.Ea.nR):b&&c&&(d=a.Ea.gz(b,c,a.Ea.nR,a.Ea.DG.converter));return d};o_("Validation.converterFactory",a.Ea.qn,a);a.Ea.Vw=function(b,c){var d;
b&&!c?d=a.Ea.MI(b,a.Ea.OW):b&&c&&(d=a.Ea.gz(b,c,a.Ea.OW,a.Ea.DG.validator));return d};o_("Validation.validatorFactory",a.Ea.Vw,a);a.Ea.Gea=function(b){return a.Ea.MI(b,a.Ea.c5)};o_("Validation.getDefaultConverterFactory",a.Ea.Gea,a);a.Ea.PFa=function(b){return a.Ea.MI(b,a.Ea.f5)};o_("Validation.getDefaultValidatorFactory",a.Ea.PFa,a);a.Ea.M2=function(b,c){var d=a.Ea.DG.converter;a.Ea.gz(b,c,a.Ea.c5,d);a.Ea.gz(b,c,a.Ea.nR,d)};a.Ea.Sx=function(b,c){var d=a.Ea.DG.validator;a.Ea.gz(b,c,a.Ea.f5,d);a.Ea.gz(b,
c,a.Ea.OW,d)};a.Ea.hra=function(b,c,d){if(c&&!a.Ea.Iza(b,c))throw Error("Factory instance does not implement the methods expected by the factory of type "+d);};a.Ea.MI=function(b,c){a.o.Gq(b);var d=null;b&&(b=b.toLowerCase(),d=(c[b]||{}).instance||null);return d};a.Ea.Iza=function(b,c){var d=!0,e;a.o.di(b);a.o.di(c);for(e in c)if(c.hasOwnProperty(e)&&"function"===typeof c[e]&&!b[e]&&"function"!==typeof b[e]){d=!1;break}return d};a.Ea.gz=function(b,c,d,e){a.o.Gq(b);a.o.di(c);if(b){var h={};h.instance=
c;a.Ea.hra(c,e.type,e.name);d[b.toLowerCase()]=h}};a.Rn={CONVERTER_TYPE_NUMBER:"number",CONVERTER_TYPE_DATETIME:"datetime",createConverter:function(){}};o_("ConverterFactory",a.Rn,a);a.Pe={VALIDATOR_TYPE_REQUIRED:"required",VALIDATOR_TYPE_REGEXP:"regexp",VALIDATOR_TYPE_NUMBERRANGE:"numberRange",VALIDATOR_TYPE_LENGTH:"length",VALIDATOR_TYPE_DATETIMERANGE:"dateTimeRange",VALIDATOR_TYPE_DATERESTRICTION:"dateRestriction",createValidator:function(){}};o_("ValidatorFactory",a.Pe,a);a.sg=function(a){this.Init(a)};
o_("Converter",a.sg,a);a.b.ta(a.sg,a.b,"oj.Converter");a.sg.prototype.Init=function(b){a.sg.t.Init.call(this);this.Vb=b};a.b.g("Converter.prototype.Init",{Init:a.sg.prototype.Init});a.sg.prototype.Md=function(){a.o.kd();return null};a.b.g("Converter.prototype.getHint",{Md:a.sg.prototype.Md});a.sg.prototype.Sk=function(){return this.Vb||{}};a.b.g("Converter.prototype.getOptions",{Sk:a.sg.prototype.Sk});a.sg.prototype.parse=function(){a.o.kd();return null};a.b.g("Converter.prototype.parse",{parse:a.sg.prototype.parse});
a.sg.prototype.format=function(){a.o.kd();return null};a.b.g("Converter.prototype.format",{format:a.sg.prototype.format});a.sg.prototype.resolvedOptions=function(){var a={};g.extend(a,this.Vb);return a};a.b.g("Converter.prototype.resolvedOptions",{resolvedOptions:a.sg.prototype.resolvedOptions});a.tg=function(b,c){var d=new a.ia(b,c,a.ia.Xc.ERROR);this.Init(d)};o_("ConverterError",a.tg,a);a.tg.prototype=Error();a.tg.prototype.Init=function(a){var b=a.detail,c=a.summary;this.Yy=a;this.name="Converter Error";
this.message=b||c};a.b.g("ConverterError.prototype.Init",{Init:a.tg.prototype.Init});a.tg.prototype.Wz=function(){return this.Yy};a.b.g("ConverterError.prototype.getMessage",{Wz:a.tg.prototype.Wz});a.il=function(){this.Init()};o_("NumberConverter",a.il,a);a.b.ta(a.il,a.sg,"oj.NumberConverter");a.il.prototype.Init=function(b){a.il.t.Init.call(this,b)};a.b.g("NumberConverter.prototype.Init",{Init:a.il.prototype.Init});a.il.prototype.format=function(b){return a.il.t.format.call(this,b)};a.b.g("NumberConverter.prototype.format",
{format:a.il.prototype.format});a.il.prototype.parse=function(b){return a.il.t.parse.call(this,b)};a.b.g("NumberConverter.prototype.parse",{parse:a.il.prototype.parse});a.zc=function(a){this.Init(a)};o_("DateTimeConverter",a.zc,a);a.b.ta(a.zc,a.sg,"oj.DateTimeConverter");a.zc.prototype.Init=function(b){a.zc.t.Init.call(this,b)};a.b.g("DateTimeConverter.prototype.Init",{Init:a.zc.prototype.Init});a.zc.prototype.format=function(b){return a.zc.t.format.call(this,b)};a.b.g("DateTimeConverter.prototype.format",
{format:a.zc.prototype.format});a.zc.prototype.gF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isHourInDaySet",{gF:a.zc.prototype.gF});a.zc.prototype.fF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isHourInAMPMSet",{fF:a.zc.prototype.fF});a.zc.prototype.iF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isMinuteSet",{iF:a.zc.prototype.iF});a.zc.prototype.kF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isSecondSet",{kF:a.zc.prototype.kF});a.zc.prototype.hF=
function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isMilliSecondSet",{hF:a.zc.prototype.hF});a.zc.prototype.lF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isYearSet",{lF:a.zc.prototype.lF});a.zc.prototype.jF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isMonthSet",{jF:a.zc.prototype.jF});a.zc.prototype.eF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isDaySet",{eF:a.zc.prototype.eF});a.zc.prototype.dF=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.isDayNameSet",
{dF:a.zc.prototype.dF});a.zc.prototype.ft=function(){a.o.kd()};a.b.g("DateTimeConverter.prototype.calculateWeek",{ft:a.zc.prototype.ft});a.zc.prototype.parse=function(b){return a.zc.t.parse.call(this,b)};a.b.g("DateTimeConverter.prototype.parse",{parse:a.zc.prototype.parse});a.zc.prototype.ve=function(b,c){return a.zc.t.ve.call(this,b,c)};a.b.g("DateTimeConverter.prototype.compareISODates",{ve:a.zc.prototype.ve});a.Gi=function(){this.Init()};o_("Validator",a.Gi,a);a.b.ta(a.Gi,a.b,"oj.Validator");
a.Gi.prototype.Init=function(){a.Gi.t.Init.call(this)};a.b.g("Validator.prototype.Init",{Init:a.Gi.prototype.Init});a.Gi.prototype.validate=function(){a.o.kd()};a.b.g("Validator.prototype.validate",{validate:a.Gi.prototype.validate});a.Gi.prototype.Md=function(){a.o.kd()};a.b.g("Validator.prototype.getHint",{Md:a.Gi.prototype.Md});a.nk=function(b,c){var d=new a.ia(b,c,a.ia.Xc.ERROR);this.Init(d)};o_("ValidatorError",a.nk,a);a.nk.prototype=Error();a.nk.prototype.Init=function(a){var b=a.detail,c=a.summary;
this.Yy=a;this.name="Validator Error";this.message=b||c};a.b.g("ValidatorError.prototype.Init",{Init:a.nk.prototype.Init});a.nk.prototype.Wz=function(){return this.Yy};a.b.g("ValidatorError.prototype.getMessage",{Wz:a.nk.prototype.Wz});a.Dh=function(a){this.Init(a)};o_("RequiredValidator",a.Dh,a);a.b.ta(a.Dh,a.Gi,"oj.RequiredValidator");a.Dh.TO="oj-validator.required.detail";a.Dh.UO="oj-validator.required.summary";a.Dh.prototype.Init=function(b){a.Dh.t.Init.call(this);this.Vb=b};a.b.g("RequiredValidator.prototype.Init",
{Init:a.Dh.prototype.Init});a.Dh.prototype.validate=function(b){var c,d="",e,h={};if("number"===typeof b&&0===b||b&&0!==b.length)return!0;this.Vb&&(c=this.Vb.messageDetail||this.Vb.message||null,e=this.Vb.messageSummary||null,d=this.Vb.label||"");h={label:d};b=e?a.va.Lc(e,h):a.va.F(this.eT(),h);c=c?a.va.Lc(c,h):a.va.F(this.vS(),h);throw new a.nk(b,c);};a.b.g("RequiredValidator.prototype.validate",{validate:a.Dh.prototype.validate});a.Dh.prototype.Md=function(){var b="";this.Vb&&this.Vb.hint&&(b=a.va.F(this.Vb.hint));
return b};a.b.g("RequiredValidator.prototype.getHint",{Md:a.Dh.prototype.Md});a.Dh.prototype.eT=function(){return a.Dh.UO};a.Dh.prototype.vS=function(){return a.Dh.TO};a.wm=function(a){this.Init(a)};o_("DateRestrictionValidator",a.wm,a);a.b.ta(a.wm,a.Gi,"oj.DateRestrictionValidator");a.wm.prototype.Init=function(b){a.wm.t.Init.call(this);this.Oqa=b.dayFormatter;this.Pc=a.Qa.getConverterInstance(b.converter);b&&(this.pya=b.messageSummary||null,this.oya=b.messageDetail||null)};a.b.g("DateRestrictionValidator.prototype.Init",
{Init:a.wm.prototype.Init});a.wm.prototype.Bwa=function(a){var b=this.Oqa;return b?(a=b({fullYear:a.fullYear,month:a.month+1,date:a.date}))&&a.disabled:!1};a.wm.prototype.validate=function(b){var c="",d="",d=a.va,c=this.pya,e=this.oya,h=b?this.Pc.format(b):b,f=b?a.Qa._dateTime(b,["fullYear","month","date"],!0):null;if(null===b)return b;if(this.Bwa(f))throw c=c?d.Lc(c,{value:h}):d.F("oj-validator.restriction.date.messageSummary",{value:h}),d=e?d.Lc(e,{value:h}):d.F("oj-validator.restriction.date.messageDetail",
{value:h}),new a.nk(c,d);return b};a.b.g("DateRestrictionValidator.prototype.validate",{validate:a.wm.prototype.validate});a.wm.prototype.Md=function(){return null};a.b.g("DateRestrictionValidator.prototype.getHint",{Md:a.wm.prototype.Md});a.Sn=function(a){this.Init(a)};o_("DateTimeRangeValidator",a.Sn,a);a.b.ta(a.Sn,a.Gi,"oj.DateTimeRangeValidator");a.Sn.prototype.Init=function(b){a.Sn.t.Init.call(this);this.Pc=a.Qa.getConverterInstance(b.converter);this.Oi=b.min||null;this.Lj=b.max||null;b&&(this.cD=
b.hint||{},this.sC=b.messageSummary||{},this.rC=b.messageDetail||{})};a.b.g("DateTimeRangeValidator.prototype.Init",{Init:a.Sn.prototype.Init});a.Sn.prototype.validate=function(b){var c=this.sC,d=this.rC,e=d.rangeOverflow,d=d.rangeUnderflow,h=c.rangeOverflow,c=c.rangeUnderflow,f=a.Qa,g=this.Oi,p=this.Lj,q="",u="",v=a.va,w=null,w=b?this.Pc.format(b):b,y,x;if(null===b)return b;w=this.Pc.format(b);g&&(g=f._minMaxIsoString(g,b),y=this.Pc?this.Pc.format(g):g);p&&(p=f._minMaxIsoString(p,b),x=this.Pc?this.Pc.format(p):
p);if(null!==g&&null!==p){if(0<=this.Pc.ve(b,g)&&0>=this.Pc.ve(b,p)||0<this.Pc.ve(g,p))return b}else if(null!==g){if(0<=this.Pc.ve(b,g))return b}else if(null===p||0>=this.Pc.ve(b,p))return b;null!==p&&0<this.Pc.ve(b,p)?(w={value:w,max:x},q=h?h:v.F("oj-validator.range.datetime.messageSummary.rangeOverflow"),u=e?v.Lc(e,w):v.F("oj-validator.range.datetime.messageDetail.rangeOverflow",w)):null!==g&&0>this.Pc.ve(b,g)&&(w={value:w,min:y},q=c?c:v.F("oj-validator.range.datetime.messageSummary.rangeUnderflow"),
u=d?v.Lc(d,w):v.F("oj-validator.range.datetime.messageDetail.rangeUnderflow",w));throw new a.nk(q,u);};a.b.g("DateTimeRangeValidator.prototype.validate",{validate:a.Sn.prototype.validate});a.Sn.prototype.Md=function(){var b=null,c=this.cD,d=c.inRange,e=c.min,c=c.max,h=this.Oi,f=this.Lj,g=h&&this.Pc?this.Pc.format(h):h,p=f&&this.Pc?this.Pc.format(f):f,q=null,u=a.va;null!==h&&null!==f?(q={min:g,max:p},b=d?u.Lc(d,q):u.F("oj-validator.range.datetime.hint.inRange",q)):null!==h?(q={min:g},b=e?u.Lc(e,q):
u.F("oj-validator.range.datetime.hint.min",q)):null!==f&&(q={max:p},b=c?u.Lc(c,q):u.F("oj-validator.range.datetime.hint.max",q));return b};a.b.g("DateTimeRangeValidator.prototype.getHint",{Md:a.Sn.prototype.Md});a.Sja=function(){return{createConverter:function(b){return new a.Af(b)}}}();a.Ea.M2(a.Rn.CONVERTER_TYPE_NUMBER,a.Sja);a.lja=function(){return{createConverter:function(b){return new a.zb(b)}}}();a.Ea.M2(a.Rn.CONVERTER_TYPE_DATETIME,a.lja);a.Zja=function(){return{createValidator:function(b){return new a.Dh(b)}}}();
a.Ea.Sx(a.Pe.VALIDATOR_TYPE_REQUIRED,a.Zja);a.Xja=function(){return{createValidator:function(b){return new a.Ch(b)}}}();a.Ea.Sx(a.Pe.VALIDATOR_TYPE_REGEXP,a.Xja);a.mja=function(){return{createValidator:function(b){return new a.Sn(b)}}}();a.Ea.Sx(a.Pe.VALIDATOR_TYPE_DATETIMERANGE,a.mja);a.kja=function(){return{createValidator:function(b){return new a.wm(b)}}}();a.Ea.Sx(a.Pe.VALIDATOR_TYPE_DATERESTRICTION,a.kja);a.Tja=function(){return{createValidator:function(b){return new a.Vn(b)}}}();a.Ea.Sx(a.Pe.VALIDATOR_TYPE_NUMBERRANGE,
a.Tja);a.Hja=function(){return{createValidator:function(b){return new a.fk(b)}}}();a.Ea.Sx(a.Pe.VALIDATOR_TYPE_LENGTH,a.Hja);var b={Bp:{latn:"0123456789",arab:"\u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669",thai:"\u0e50\u0e51\u0e52\u0e53\u0e54\u0e55\u0e56\u0e57\u0e58\u0e59"},FIa:/^\s+|\s+$|\u200f|\u200e/g,GIa:/\s+|\u200f|\u200e/g,HIa:/0+$/g,SJa:["0","00","000"],jP:/^\d{4}(?:-?\d{2}(?:-?\d{2})?)?(?:T\d{2}:?\d{2}(?::?\d{2}(?:\.\d{1,3})?)?(Z|[+-]\d{2}:\d{2})?)?$|^T\d{2}:?\d{2}(?::?\d{2}(?:\.\d{1,3})?)?(Z|[+-]\d{2}:\d{2})?$/,
getLocalTimeZoneOffset:function(){return b.bA("Etc/GMT",(new Date).getTimezoneOffset(),!1,!1)},L7:function(a){if(!a||"string"!==typeof a)return null;var c=b.jP.exec(a);null===c&&b.Eca(a);return void 0!==c[1]?c[1]:null},dateToLocalIso:function(a){var c=b.sc(a.getFullYear(),4)+"-"+b.sc(a.getMonth()+1,2)+"-"+b.sc(a.getDate(),2)+"T"+b.sc(a.getHours(),2)+":"+b.sc(a.getMinutes(),2)+":"+b.sc(a.getSeconds(),2);0<a.getMilliseconds()&&(c+="."+b.EN(b.sc(a.getMilliseconds(),3)));return c},rIa:function(a){var c=
b.sc(a[0],4)+"-"+b.sc(a[1],2)+"-"+b.sc(a[2],2)+"T"+b.sc(a[3],2)+":"+b.sc(a[4],2)+":"+b.sc(a[5],2);0<a[6]&&(c+="."+b.EN(b.sc(a[6],3)));return c},isoToLocalDate:function(a){return a&&"string"===typeof a?this.Mxa(a):null},Mxa:function(a){a=b.yB(a);return new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5],a[6])},yB:function(a){var c=a.split("T"),d=a.indexOf("T");a=new Date;var e=[a.getFullYear(),a.getMonth()+1,a.getDate(),0,0,0,0];if(""!==c[0]){var h=c[0].split("-");for(a=0;a<h.length;a++)e[a]=parseInt(h[a],10)}if(-1!==
d){c=c[1].split(".");d=c[0].split(":");for(a=0;a<d.length;a++)e[3+a]=parseInt(d[a],10);2===c.length&&c[1]&&(e[6]=parseInt(b.UZ(c[1],3,!1),10))}return e},YL:function(a){var c={format:null,dateTime:null,timeZone:"",isoStrParts:null},d=b.jP.exec(a);null===d&&b.Eca(a);if(void 0===d[1]&&void 0===d[2])return c.format="local",c.dateTime=a,c.isoStrParts=b.yB(c.dateTime),c;c.timeZone=void 0!==d[1]?d[1]:d[2];c.format="Z"===c.timeZone?"zulu":"offset";c.dateTime=a.substring(0,a.indexOf(c.timeZone));c.isoStrParts=
b.yB(c.dateTime);return c},bLa:function(){var a;a=Error("time zone is not supported");a.errorInfo={errorCode:"timeZoneNotSupported"};throw a;},Eca:function(a){var b;b=Error("The string "+a+" is not a valid ISO 8601 string.");b.errorInfo={errorCode:"invalidISOString",parameterMap:{isoStr:a}};throw b;},trim:function(a){return(a+"").replace(b.FIa,"")},EN:function(a){return(a+"").replace(b.HIa,"")},Fp:function(a){return(a+"").replace(b.GIa,"")},Rw:function(a,b){return 0===a.indexOf(b)},jj:function(a){return a.split("\u00a0").join(" ").toUpperCase()},
sc:function(a,c){var d;d=a+"";return 1<c&&d.length<c?(d=b.SJa[c-2]+d,d.substr(d.length-c,c)):d},UZ:function(a,b,c){a=""+a;var d;for(d=a.length;d<b;d+=1)a=c?"0"+a:a+"0";return a},bA:function(a,c,d,e){d=d?0<=c:0>c;c=Math.abs(c);var h=c/60<<0;c%=60;e&&(h=b.UZ(h,2,!0));a=a+(d?"-":"+")+h;if(0<c||e)a+=":"+b.UZ(c,2,!0);return a},YFa:function(a,c){if(void 0===c)return"latn";var d=b.bM(c);void 0===a.numbers["symbols-numberSystem-"+d]&&(d="latn");return d},qLa:function(a){return a.split("-")[0]},uea:function(a){a=
a.split("-");return 3===a.length?a[2]:2===a.length&&2===a[1].length?a[1]:"001"},bM:function(a){a=a||"en-US";var b=a.indexOf("-u-nu-"),c="latn";-1!==b&&(c=a.substr(b+6,4));return c},tLa:function(a){var b=0,c;for(c in a)b++;return b},sh:function(a){a=a.main;var b,c;for(c in a){b=c;break}return a[b]},rt:function(a){a=a.main;var b,c;for(c in a){b=c;break}return b},ZCa:function(a){if("string"===typeof a)switch(a.toLowerCase().trim()){case "true":case "1":return!0;case "false":case "0":return!1}return a},
Tj:function(a,c){if(void 0===a)throw Error("Internal "+c+" error. Default options missing.");return function(d,e,h,f){if(void 0!==a[d]){f=a[d];switch(e){case "boolean":f=b.ZCa(f);break;case "string":f=String(f);break;case "number":f=Number(f);break;default:throw Error("Internal error. Wrong value type.");}if(void 0!==h&&-1===h.indexOf(f)){e=[];for(f=0;f<h.length;f++)e.push(h[f]);h=new RangeError("The value '"+a[d]+"' is out of range for '"+c+"' options property '"+d+"'. Valid values: "+e);h.errorInfo=
{errorCode:"optionOutOfRange",parameterMap:{propertyName:d,propertyValue:a[d],propertyValueValid:e,caller:c}};throw h;}}return f}}},d={fullYear:{rr:0,Pt:4},month:{rr:1,Pt:2},date:{rr:2,Pt:2},hours:{rr:3,Pt:2},minutes:{rr:4,Pt:2},seconds:{rr:5,Pt:2},milliseconds:{rr:6,Pt:3},timeZone:{rr:7}};b.isoToDate=function(a){return new Date(this._normalizeIsoString(a))};b._copyTimeOver=function(a,b){if(!a||!b)throw Error("Provided invalid arguments");b=this._normalizeIsoString(b);var c=a.indexOf("T"),d=b.indexOf("T");
return b.substring(0,d)+(-1!==c?a.substring(c):"T00:00:00.000")};b._clearTime=function(a){return this._dateTime(a,{hours:0,minutes:0,seconds:0,milliseconds:0})};b._dateTime=function(a,b,c){if(!a||!b)throw Error("Invalid argument invocation");var e,h=null,f=null,f=this.sc;a=this._normalizeIsoString(a);var n=/(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):?(\d{2})?\.?(\d{3})?(.*)?/.exec(a);if(!n)throw Error("Unable to capture anything");n=n.slice(1);if(Array.isArray(b))for(var h={},p=0,q=b.length;p<q;p++){if(f=
b[p],f in d){a=d[f].rr;e=n[a];if(c&&"timeZone"===f)throw Error("Dude you tried to ask timezone to be parsed");c?(e=parseInt(e,10),h[f]=1===a?e-1:e):h[f]=e}}else if(g.isPlainObject(b)){for(p in b)c=d[p],a=c.rr,e=b[p],1===a&&"number"===typeof e&&e++,n[a]=c.Pt?f(e,c.Pt):e;h=n[0]+"-"+n[1]+"-"+n[2]+"T"+n[3]+":"+n[4]+":"+n[5]+(6<n.length&&n[6]?"."+n[6]+(8===n.length&&n[7]?n[7]:""):"")}return h};b._normalizeIsoString=function(a){if(!a)throw Error("Provided invalid arguments");var b=(new Date).toISOString(),
b=b.substring(0,b.indexOf("T")),c=a.indexOf("T"),d=-1===c?a:a.substring(0,c);-1!==c?(a=a.substring(c),a=1<a.split(":").length?a:a+":00"):a="T00:00:00.000";return(d||b)+a};a.zb=function(a){this.Init(a)};o_("IntlDateTimeConverter",a.zb,a);a.b.ta(a.zb,a.zc,"oj.IntlDateTimeConverter");a.zb.Hka=new Date(1998,10,29,15,45,31);a.zb.prototype.Init=function(b){a.zb.t.Init.call(this,b)};a.b.g("IntlDateTimeConverter.prototype.Init",{Init:a.zb.prototype.Init});a.zb.prototype.Co=function(){this.CE||(this.CE=h.Je());
return this.CE};a.zb.prototype.format=function(b){var c=a.hb.vl(),d=a.fa.Wi(),e=this.resolvedOptions();if(null==b||"string"===typeof b&&0===a.bb.trim(""+b).length)return"";try{return this.Co().format(b,c,e,d)}catch(h){throw b=this.Ps(h,b),b;}};a.b.g("IntlDateTimeConverter.prototype.format",{format:a.zb.prototype.format});a.zb.prototype.RL=function(b,c){var d=a.hb.vl(),e=a.fa.Wi();try{return this.Co().RL(b,d,c,e)}catch(h){throw d=this.Ps(h,b),d;}};a.b.g("IntlDateTimeConverter.prototype.formatRelative",
{RL:a.zb.prototype.RL});a.zb.prototype.Md=function(){var a=this.resolvedOptions().patternFromOptions||this.Sk().pattern;return a?a.toLowerCase():""};a.b.g("IntlDateTimeConverter.prototype.getHint",{Md:a.zb.prototype.Md});a.zb.prototype.RI=function(){var b="";try{b=this.format(a.Qa.dateToLocalIso(a.zb.Hka))}catch(c){c instanceof a.tg&&(b="")}finally{return b}};a.zb.prototype.Sk=function(){return a.zb.t.Sk.call(this)};a.b.g("IntlDateTimeConverter.prototype.getOptions",{Sk:a.zb.prototype.Sk});a.zb.prototype.resolvedOptions=
function(){var b,c=a.fa.Wi(),d=this.Sk();if(c!==this.Uy||!this.aE){b=a.hb.vl();try{if(!b)return a.r.error("locale bundle for the current locale %s is unavailable",c),{};this.aE=this.Co().resolvedOptions(b,d,c);this.Uy=c}catch(e){throw b=this.Ps(e),b;}}return this.aE};a.b.g("IntlDateTimeConverter.prototype.resolvedOptions",{resolvedOptions:a.zb.prototype.resolvedOptions});a.zb.prototype.gF=function(){var a=this.resolvedOptions(),b=a.hour12;return a.hour&&!b?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInDaySet",
{gF:a.zb.prototype.gF});a.zb.prototype.fF=function(){var a=this.resolvedOptions(),b=a.hour12;return a.hour&&b?!0:!1};a.b.g("IntlDateTimeConverter.prototype.isHourInAMPMSet",{fF:a.zb.prototype.fF});a.zb.prototype.iF=function(){return this.Bv("minute")};a.b.g("IntlDateTimeConverter.prototype.isMinuteSet",{iF:a.zb.prototype.iF});a.zb.prototype.kF=function(){return this.Bv("second")};a.b.g("IntlDateTimeConverter.prototype.isSecondSet",{kF:a.zb.prototype.kF});a.zb.prototype.hF=function(){return this.Bv("millisecond")};
a.b.g("IntlDateTimeConverter.prototype.isMilliSecondSet",{hF:a.zb.prototype.hF});a.zb.prototype.lF=function(){return this.Bv("year")};a.b.g("IntlDateTimeConverter.prototype.isYearSet",{lF:a.zb.prototype.lF});a.zb.prototype.jF=function(){return this.Bv("month")};a.b.g("IntlDateTimeConverter.prototype.isMonthSet",{jF:a.zb.prototype.jF});a.zb.prototype.eF=function(){return this.Bv("day")};a.b.g("IntlDateTimeConverter.prototype.isDaySet",{eF:a.zb.prototype.eF});a.zb.prototype.dF=function(){return this.Bv("weekday")};
a.b.g("IntlDateTimeConverter.prototype.isDayNameSet",{dF:a.zb.prototype.dF});a.zb.prototype.ft=function(b){return this.Co().ft(b,a.hb.vl(),a.fa.Wi())};a.b.g("IntlDateTimeConverter.prototype.calculateWeek",{ft:a.zb.prototype.ft});a.zb.prototype.parse=function(b){var c,d;if(null==b||""===b)return null;var e=a.hb.vl(),h=a.fa.Wi(),f=this.resolvedOptions();try{return c=this.Co().parse(b,e,f,h),(d=c.value)&&c.warning&&a.r.warn("The value "+b+" was leniently parsed to represent a date "+d.toString?d.toString():
d),d}catch(g){throw b=this.Ps(g,b),b;}};a.b.g("IntlDateTimeConverter.prototype.parse",{parse:a.zb.prototype.parse});a.zb.prototype.ve=function(b,c){var d=a.bb.Ke;if(!d(b)||!d(c))throw Error("Invalid arguments for compareISODates ",b,c);return this.Co().ve(b,c,a.hb.vl())};a.b.g("IntlDateTimeConverter.prototype.compareISODates",{ve:a.zb.prototype.ve});a.zb.prototype.Ps=function(b,c){var d=b.errorInfo,e,h,f,g;if(d)if(e=d.errorCode,d=d.parameterMap||{},a.o.di(d),f=d.propertyName,b instanceof TypeError){if("optionTypesMismatch"===
e||"optionTypeInvalid"===e)h=a.Qa.Qx(e,d)}else b instanceof RangeError?"optionOutOfRange"===e?h=a.Qa.Qx(e,d):"datetimeOutOfRange"===e&&(e=a.va.F("oj-converter.datetime.datetimeOutOfRange.summary",{propertyName:f,value:d.value}),h=a.va.F("oj-converter.datetime.datetimeOutOfRange.detail",{minValue:d.minValue,maxValue:d.maxValue}),h=new a.tg(e,h)):b instanceof SyntaxError?"optionValueInvalid"===e&&(h=a.Qa.Qx(e,d)):b instanceof Error&&("dateFormatMismatch"===e?g="oj-converter.datetime.dateFormatMismatch.summary":
"timeFormatMismatch"===e?g="oj-converter.datetime.timeFormatMismatch.summary":"datetimeFormatMismatch"===e?g="oj-converter.datetime.datetimeFormatMismatch.summary":"invalidTimeZoneID"===e?(e=a.va.F("oj-converter.datetime.invalidTimeZoneID.summary",{timeZoneID:d.timeZoneID}),h=a.va.F("oj-converter.hint.detail",{exampleValue:this.RI()}),h=new a.tg(e,h)):"nonExistingTime"===e?g="oj-converter.datetime.nonExistingTime.summary":"missingTimeZoneData"===e?g="oj-converter.datetime.missingTimeZoneData.summary":
"dateToWeekdayMismatch"===e&&(e=a.va.F("oj-converter.datetime.dateToWeekdayMismatch.summary",{date:d.date,weekday:d.weekday}),h=a.va.F("oj-converter.datetime.dateToWeekdayMismatch.detail"),h=new a.tg(e,h)),g&&(e=a.va.F(g,{value:c||d.value,format:d.format}),h=a.va.F("oj-converter.hint.detail",{exampleValue:this.RI()}),h=new a.tg(e,h)));h||(h=e=b.message,h=new a.tg(e,h));return h};a.zb.prototype.Bv=function(a){return this.resolvedOptions()[a]?!0:!1};a.Vn=function(a){this.Init(a)};o_("NumberRangeValidator",
a.Vn,a);a.b.ta(a.Vn,a.Gi,"oj.NumberRangeValidator");a.Vn.prototype.Init=function(b){a.Vn.t.Init.call(this);b&&(this.Oi=b.min,this.Lj=b.max,this.Pc=a.Qa.getConverterInstance(b.converter),this.cD=b.hint||{},this.sC=b.messageSummary||{},this.rC=b.messageDetail||{})};a.b.g("NumberRangeValidator.prototype.Init",{Init:a.Vn.prototype.Init});a.Vn.prototype.validate=function(b){var c=b?b.toString():b,d=parseFloat(c),e=this.sC,h=this.rC,f=h.rangeOverflow,h=h.rangeUnderflow,g=e.rangeOverflow,e=e.rangeUnderflow,
p=void 0!==this.Oi?parseFloat(this.Oi):null,q=void 0!==this.Lj?parseFloat(this.Lj):null,u=p&&this.Pc?this.Pc.format(p):p,v=q&&this.Pc?this.Pc.format(q):q,w="",y="",x=null,z=a.va;if(null===b)return b;if(null!==p&&null!==q){if(d>=p&&d<=q||p>q)return c}else if(null!==p){if(d>=p)return c}else if(null===q||d<=q)return c;null!==q&&d>q?(x={value:b,max:v},w=g?g:z.F("oj-validator.range.number.messageSummary.rangeOverflow"),y=f?z.Lc(f,x):z.F("oj-validator.range.number.messageDetail.rangeOverflow",x)):null!==
p&&d<p&&(x={value:b,min:u},w=e?e:z.F("oj-validator.range.number.messageSummary.rangeUnderflow"),y=h?z.Lc(h,x):z.F("oj-validator.range.number.messageDetail.rangeUnderflow",x));throw new a.nk(w,y);};a.b.g("NumberRangeValidator.prototype.validate",{validate:a.Vn.prototype.validate});a.Vn.prototype.Md=function(){var b=null,c=this.cD,d=c.inRange,e=c.min,c=c.max,h=a.va,f=void 0!==this.Oi?parseFloat(this.Oi):null,g=void 0!==this.Lj?parseFloat(this.Lj):null,p=f&&this.Pc?this.Pc.format(f):f,q=g&&this.Pc?this.Pc.format(g):
g;null!==f&&null!==g?b=d?h.Lc(d,{min:p,max:q}):h.F("oj-validator.range.number.hint.inRange",{min:p,max:q}):null!==f?b=e?h.Lc(e,{min:p}):h.F("oj-validator.range.number.hint.min",{min:p}):null!==g&&(b=c?h.Lc(c,{max:q}):h.F("oj-validator.range.number.hint.max",{max:q}));return b};a.b.g("NumberRangeValidator.prototype.getHint",{Md:a.Vn.prototype.Md});a.Af=function(a){this.Init(a)};o_("IntlNumberConverter",a.Af,a);a.b.ta(a.Af,a.il,"oj.IntlNumberConverter");a.Af.prototype.Init=function(b){a.Af.t.Init.call(this,
b)};a.b.g("IntlNumberConverter.prototype.Init",{Init:a.Af.prototype.Init});a.Af.prototype.Co=function(){this.CE||(this.CE=f.Je());return this.CE};a.Af.prototype.format=function(b){var c,d,e;if(null==b||"string"===typeof b&&0===a.bb.trim(""+b).length||"number"===typeof b&&isNaN(b))return"";c=a.fa.Wi();d=a.hb.vl();e=this.resolvedOptions();try{return this.Co().format(b,d,e,c)}catch(h){throw b=this.Ps(h,b),b;}};a.b.g("IntlNumberConverter.prototype.format",{format:a.Af.prototype.format});a.Af.prototype.Md=
function(){return null};a.b.g("IntlNumberConverter.prototype.getHint",{Md:a.Af.prototype.Md});a.Af.prototype.Sk=function(){return a.Af.t.Sk.call(this)};a.b.g("IntlNumberConverter.prototype.getOptions",{Sk:a.Af.prototype.Sk});a.Af.prototype.parse=function(b){var c,d,e;if(null==b||""===b)return null;c=a.fa.Wi();d=a.hb.vl();e=this.resolvedOptions();try{return this.Co().parse(a.bb.trim(b),d,e,c)}catch(h){throw b=this.Ps(h,b),b;}};a.b.g("IntlNumberConverter.prototype.parse",{parse:a.Af.prototype.parse});
a.Af.prototype.resolvedOptions=function(){var b;b=a.fa.Wi();var c;if(b!==this.Uy||!this.aE){c=a.hb.vl();try{if(!c)return a.r.error("locale bundle for the current locale %s is unavailable",b),{};this.aE=this.Co().resolvedOptions(c,this.Sk(),b);this.Uy=b}catch(d){throw b=this.Ps(d),b;}}return this.aE};a.b.g("IntlNumberConverter.prototype.resolvedOptions",{resolvedOptions:a.Af.prototype.resolvedOptions});a.Af.prototype.Ps=function(b,c){var d,e,h=b.errorInfo,f;if(h){e=h.errorCode;h=h.parameterMap;a.o.di(h);
switch(e){case "optionTypesMismatch":case "optionTypeInvalid":d=a.Qa.Qx(e,h);break;case "optionOutOfRange":d=a.Qa.Qx(e,h);break;case "optionValueInvalid":d=a.Qa.Qx(e,h);break;case "decimalFormatMismatch":f="oj-converter.number.decimalFormatMismatch.summary";break;case "currencyFormatMismatch":f="oj-converter.number.currencyFormatMismatch.summary";break;case "percentFormatMismatch":f="oj-converter.number.percentFormatMismatch.summary";break;case "unsupportedParseFormat":e=a.va.F("oj-converter.number.decimalFormatUnsupportedParse.summary"),
d=a.va.F("oj-converter.number.decimalFormatUnsupportedParse.detail"),d=new a.tg(e,d)}f&&(e=a.va.F(f,{value:c||h.value,format:h.format}),d=a.va.F("oj-converter.hint.detail",{exampleValue:this.RI()}),d=new a.tg(e,d))}d||(d=e=b.message,d=new a.tg(e,d));return d};a.Af.prototype.RI=function(){var b="";try{b=this.format(12345.98765)}catch(c){c instanceof a.tg&&(b="",a.r.error("error retrieving hint value in format"))}finally{return b}};var e;e=function(){function a(b,c){var d=c.zones[b];if(G.test(b)){var e=
0,h=b.replace(G,"").split(":"),d=60*parseInt(h[0],10);if(isNaN(d)||2===h.length&&(e=parseInt(h[1],10),isNaN(e)))return;d+=0<=d?e:-e;if(d<C||d>K)return;d=v(d,1);d=b.replace("/etc//i","").toUpperCase()+"|"+d+"|0|"}void 0!==d&&this.qBa(u(b,d))}function b(){return{zfa:function(a,b){var c=b.supplemental.timeZoneData;void 0===c&&B();var d=x(a,c);if(!d){var e=c.links[a];e&&(d=x(e,c))}d||D(a);return d}}}var c={},d,e,h,f,g,q,u,v,w,y,x,z,D,I,B,G=/^Etc\/GMT/i,C=-840,K=720;w=function(a,b){for(var c=".",d="",
e;0<b;)b-=1,a*=60,e=Math.floor(a+1E-6),c+="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWX"[e],a-=e,e&&(d+=c,c="");return d};v=function(a,b){for(var c="",d=Math.abs(a),e=Math.floor(d),d=w(d-e,Math.min(~~b,10));0<e;)c="0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWX"[e%60]+c,e=Math.floor(e/60);0>a&&(c="-"+c);return c&&d?c+d:d||"-"!==c?c||d||"0":"0"};e=function(a){return 96<a?a-87:64<a?a-29:a-48};h=function(a){var b=0,c=a.split("."),d=c[0],c=c[1]||"",h=1,f=0,k=1;45===a.charCodeAt(0)&&
(b=1,k=-1);for(;b<d.length;b++)a=e(d.charCodeAt(b)),f=60*f+a;for(b=0;b<c.length;b++)h/=60,a=e(c.charCodeAt(b)),f+=a*h;return f*k};f=function(a){for(var b=0;b<a.length;b++)a[b]=h(a[b])};g=function(a,b){for(var c=0;c<b;c++)a[c]=Math.round((a[c-1]||0)+6E4*a[c]);a[b-1]=Infinity};q=function(a,b){var c=[],d;for(d=0;d<b.length;d++)c[d]=a[b[d]];return c};u=function(a,b){var c=b.split("|"),d=c[1].split(" "),e=c[2].split(""),h=c[3].split(" ");f(d);f(e);f(h);g(h,e.length);return{name:a,fda:q(c[0].split(" "),
e),Iw:q(d,e),NZ:h}};D=function(a){var b;b=Error("invalid timeZone ID: "+a);b.errorInfo={errorCode:"invalidTimeZoneID",parameterMap:{timeZoneID:a}};throw b;};I=function(){var a;a=Error("The input time does not exist because it falls during the transition to daylight saving time.");a.errorInfo={errorCode:"nonExistingTime"};throw a;};B=function(){var a;a=Error("TimeZone data is missing. Please call require 'ojs/ojtimezonedata' in order to load the TimeZone data.");a.errorInfo={errorCode:"missingTimeZoneData"};
throw a;};a.prototype={qBa:function(a){this.name=a.name;this.fda=a.fda;this.NZ=a.NZ;this.Iw=a.Iw},parse:function(a,b,c,d){var e=this.Iw,h=this.NZ,f=h.length-1,k,g,l,q,m,r,t;for(l=0;l<f;l++){k=e[l];g=e[l+1];t=h[l];q=t-6E4*k;m=q+36E5;r=q-36E5;if(a>=q&&a<m&&k>g)if(!0===d)I();else return l+1;if(a>=r&&a<q&&k<g)return b?l:l+1;if(a<t-6E4*k){if(!1===c){if(b)return k<g?l:l+1;if(k<g)return l+1}return l}}return f},offset:function(a){var b=this.Iw.length;return 0<=a&&a<b?parseInt(this.Iw[a],10):parseInt(this.Iw[b-
1],10)},length:function(){return this.Iw.length}};y=function(a){return(a||"").toLowerCase().replace(/\//g,"_")};z=function(b,d){var e,h;e=new a(b,d);h=y(e.name);c[h]=e};x=function(a,b){var d=y(a);void 0===c[d]&&z(a,b);return c[y(a)]||null};return{Je:function(){d||(d=b());return d}}}();var f;f=function(){function a(){return{format:function(a,b,c,e){if(2>=arguments.length||void 0===c)c={useGrouping:!0,style:"decimal"};y(c,"OraNumberConverter.format");var h={};w(b,h,c,e);return d(a,c,b,h,e)},parse:function(a,
b,c,d){if("number"===typeof a)return a;if("[object Number]"===Object.prototype.toString.call(a))return Number(a);if(2>=arguments.length||void 0===c)c={useGrouping:!0,style:"decimal"};y(c,"OraNumberConverter.parse");return e(a,b,c,d)},resolvedOptions:function(a,c,d){if(3>arguments.length||void 0===d)d=b.rt(a);if(2>arguments.length||void 0===c)c={useGrouping:!0,style:"decimal"};var e=T(a,c,d);return S(e,c,d)}}}var c,d,e,h,f,g,p,q,u,v,w,y,x,z,D,I,B,G,C,K,A,J,F,E,H,L,P,M,Q,N,R,Y,V,T,S,fa=/^[+\-]?infinity$/i,
ha=/^[+\-]?\d*\.?\d*(e[+\-]?\d+)?$/,ca=/([^+-.0-9]*)([+\-]?\d*\.?\d*(E[+\-]?\d+)?).*$/,U=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,O=/(^0\.0*)([^0].*$)/,Z={trillion:[1E14,1E13,1E12],billion:[1E11,1E10,1E9],million:[1E8,1E7,1E6],thousand:[1E5,1E4,1E3]},ea={trillion:1E12,billion:1E9,million:1E6,thousand:1E3},ga={HALF_UP:"ceil",HALF_DOWN:"floor",DEFAULT:"round"};c=function(a,b,c){var d;for(d=a.length;d<b;d+=1)a=c?"0"+a:a+"0";return a};B=function(a,b,c,d){var e=new RangeError(a+" is out of range.  Enter a value between "+
b+" and "+c+" for "+d);e.errorInfo={errorCode:"numberOptionOutOfRange",parameterMap:{value:a,minValue:b,maxValue:c,propertyName:d}};throw e;};A=function(a,b,c,d,e){a=a[b];return void 0!==a?(a=Number(a),(isNaN(a)||a<c||a>d)&&B(a,c,d,b),Math.floor(a)):e};D=function(a,b){if(void 0===b)return"latn";var c=J(b);void 0===a.numbers["symbols-numberSystem-"+c]&&(c="latn");return c};I=function(a){return a.split("-")[0]};J=function(a){a=a||"en-US";var b=a.indexOf("-u-nu-"),c="latn";-1!==b&&(c=a.substr(b+6,4));
return c};w=function(a,c,d,e){var h=b.sh(a);e=D(h,e);c.numberingSystemKey=e;c.numberingSystem="symbols-numberSystem-"+e;if(void 0!==d.pattern&&0<d.pattern.length)e=d.pattern;else{switch(d.style){case "decimal":e="decimalFormats-numberSystem-";break;case "currency":e="currencyFormats-numberSystem-";break;case "percent":e="percentFormats-numberSystem-";break;default:e="decimalFormats-numberSystem-"}e+=c.numberingSystemKey;e=h.numbers[e].standard;var f=d.decimalFormat;void 0!==f&&"decimal"===d.style&&
(c.shortDecimalFormat=h.numbers["decimalFormats-numberSystem-latn"][f].decimalFormat)}f=I(b.rt(a));c.plurals=a.supplemental.plurals;c.lang=f;c.pat=e;c.minusSign=h.numbers[c.numberingSystem].minusSign;c.decimalSeparator=h.numbers[c.numberingSystem].decimal;c.exponential=h.numbers[c.numberingSystem].exponential;c.groupingSeparator=h.numbers[c.numberingSystem].group;c.currencyDisplay=d.currencyDisplay;void 0!==d.currency&&(c.currencyCode=d.currency.toUpperCase());c.style=d.style;p(d,e,h,c);void 0===
d.pattern&&(c.minimumIntegerDigits=A(d,"minimumIntegerDigits",1,21,c.minimumIntegerDigits),void 0!==d.maximumFractionDigits&&(c.maximumFractionDigits=A(d,"maximumFractionDigits",0,20,c.maximumFractionDigits),c.maximumFractionDigits<c.minimumFractionDigits&&(c.minimumFractionDigits=c.maximumFractionDigits)),void 0!==d.minimumFractionDigits&&(c.minimumFractionDigits=A(d,"minimumFractionDigits",0,20,c.minimumFractionDigits)),c.maximumFractionDigits<c.minimumFractionDigits&&(c.maximumFractionDigits=c.minimumFractionDigits))};
z=function(a){var b=new TypeError('The property "currency" is required whenthe property "'+a+'" is "currency". An accepted value is a three-letter ISO 4217 currency code.');b.errorInfo={errorCode:"optionTypesMismatch",parameterMap:{propertyName:a,propertyValue:"currency",requiredPropertyName:"currency",requiredPropertyValueValid:"a three-letter ISO 4217 currency code"}};throw b;};H=function(){var a;a=Error("long and short decimalFormats are not supported for parsing");a.errorInfo={errorCode:"unsupportedParseFormat",
parameterMap:{value:"decimal"}};throw a;};y=function(a,c){var d=b.Tj(a,c),e=d("style","string",["currency","decimal","percent","perMill"],"decimal");"decimal"===e&&(e=d("decimalFormat","string",["standard","short","long"]),"OraNumberConverter.parse"===c&&void 0!==e&&"standard"!==e&&H());var h=d("currency","string");"currency"===e&&void 0===h&&z("style");d("roundingMode","string",["HALF_UP","HALF_DOWN","HALF_EVEN"],"DEFAULT")};M=function(a,b,c){function d(a){var b=0,c=0,e=0,h="";if("0"!==a[0]){for(;"0"!==
a[b]&&b<a.length;)b++;h=a.substr(0,b);e=b}for(b=e;b<a.length;b++)if("0"===a[b])c++;else break;return[h,c]}var e=function(a){var b,c,d;for(b in Z)for(d=Z[b].length,c=0;c<d;c++)if(Z[b][c]<=a)return[b,Z[b][c]];return[a,null]}(a),h="";if(null!==e[1]){var h=c.plurals[c.lang](Math.floor(a/ea[e[0]])),f=""+e[1]+"-count-"+h,f=c.shortDecimalFormat[f];void 0===f&&(f=""+e[1]+"-count-other",f=c.shortDecimalFormat[f]);var k=d(f),g=k[1],h=k[0];if(g<f.length){var l=1*Math.pow(10,g),l=e[1]/l*10;a/=l}}e="";void 0!==
f&&(e=f.substr(g+k[0].length));a=L(a,b,c);return h+a+e};P=function(a,b){var d=a+"",e=0,h=d.split(/e/i),f=h[0];O.lastIndex=0;var k=O.exec(f);null!==k?(e=k[1].length-1,f=k[2]):f=f.replace(".","");var k=1<h.length?parseInt(h[1],10):0,h=parseInt(f,10),g=b.minimumIntegerDigits+b.maximumFractionDigits;f.length>g&&(g-=f.length,h=Math.round(h*Math.pow(10,g)));g=b.minimumIntegerDigits+b.minimumFractionDigits;h=c(h+"",g,!1);k=-1!==d.indexOf(".")?k-(b.minimumIntegerDigits-d.indexOf(".")+e):k-(g-f.length-b.minimumFractionDigits);
d=Math.abs(k);d=c(d+"",b.minExponentDigits,!0);0>k&&(d=b.minusSign+d);e=h.slice(0,b.minimumIntegerDigits);return e=0<h.slice(b.minimumIntegerDigits).length?e+(b.decimalSeparator+h.slice(b.minimumIntegerDigits)+b.exponential+d):e+(b.exponential+d)};L=function(a,b,d){var e=d.groupingSize,h=d.groupingSize0,f,k=(a+"").split(/e/i),g=1<k.length?parseInt(k[1],10):0;f=k[0];var k=f.split("."),q=1<k.length?k[1]:"";if(1<k.length&&q.length>g){var m=Math.min(d.maximumFractionDigits,q.length-g);a=G(a,m,b.roundingMode||
"DEFAULT")}k=(a+"").split(/e/i);g=1<k.length?parseInt(k[1],10):0;f=k[0];k=f.split(".");f=k[0];q=1<k.length?k[1]:"";0<g?(q=c(q,g,!1),f+=q.slice(0,g),q=q.substr(g)):0>g&&(g=-g,f=c(f,g+1,!0),q=f.slice(-g,f.length)+q,f=f.slice(0,-g));q=0<m?d.decimalSeparator+(q.length>m?q.slice(0,m):c(q,m,!1)):0<d.minimumFractionDigits?d.decimalSeparator:"";q=c(q,d.decimalSeparator.length+d.minimumFractionDigits,!1);a=d.groupingSeparator;k="";!1===b.useGrouping&&void 0===b.pattern&&(a="");f=c(f,d.minimumIntegerDigits,
!0);b=f.length-1;for(q=1<q.length?q:"";0<=b;){if(0===e||e>b)return e=f.slice(0,b+1)+(k.length?a+k+q:q);k=f.slice(b-e+1,b+1)+(k.length?a+k:"");b-=e;0<h&&(e=h)}return e=f.slice(0,b+1)+a+k+q};F=function(a,b,c){if("HALF_DOWN"===c||"HALF_EVEN"===c)a=a.substr(b),a=parseInt(a,10),5<a&&(c="HALF_UP");return c};G=function(a,b,c){var d=a.toString().split(".");if(void 0===d[1])return a;if("5"===d[1][b]&&"DEFAULT"!==c)return c=F(d[1],b,c),c=K(d,c,b),C(a,-b,c,d);b=Math.pow(10,b);b=Math.round(a*b)/b;return isFinite(b)?
b:a};K=function(a,b,c){var d=ga[b];"HALF_EVEN"===b&&(d=0==(0===c?parseInt(a[0][a[0].length-1],10):parseInt(a[1][c-1],10))%2?ga.HALF_DOWN:ga.HALF_UP);return d};C=function(a,b,c,d){if(0===b)return"5"===d[1][0]?Math[c](a):Math.round(a);d=a.toString().split("e");a=d[0];d=d[1];a=a+"e"+(d?parseInt(d,10)-b:-b);a=parseFloat(a);a=Math[c](a);d=a.toString().split("e");a=d[0];d=d[1];a=a+"e"+(d?parseInt(d,10)+b:b);return a=parseFloat(a)};d=function(a,c,d,e,h){d=b.sh(d);if(!isFinite(a))return Infinity===a||-Infinity===
a?d.numbers[e.numberingSystem].infinity:d.numbers[e.numberingSystem].nan;d=Math.abs(a);!0===e.isPercent||"percent"===c.style?d*=100:!0===e.isPerMill&&(d*=1E3);d="decimal"===c.style&&void 0!==c.decimalFormat&&"standard"!==c.decimalFormat?M(d,c,e):!0===e.useExponentialNotation?P(d,e):L(d,c,e);c="";c=0>a?c+(e.negativePrefix+d+e.negativeSuffix):c+(e.positivePrefix+d+e.positiveSuffix);a=J(h);void 0===b.Bp[a]&&(a="latn");if("latn"!==a){h=[];for(e=0;e<c.length;e++)"0"<=c[e]&&"9">=c[e]?h.push(b.Bp[a][c[e]]):
h.push(c[e]);return h.join("")}return c};q=function(a,c,d,e){a=b.Fp(a);var h="",f=!1,k=new RegExp("^"+e.numbers[d.numberingSystem].plusSign.replace(U,"\\$1"));a=a.replace(k,"");var g=b.Fp(d.positivePrefix),l=b.Fp(d.positiveSuffix),q=b.Fp(d.negativePrefix),k=b.Fp(d.negativeSuffix),m=new RegExp("^"+(g||"").replace(U,"\\$1")),r=new RegExp((l||"").replace(U,"\\$1")+"$"),t=new RegExp("^"+(q||"").replace(U,"\\$1")),p=new RegExp((k||"").replace(U,"\\$1")+"$");if(!0===t.test(a)&&!0===p.test(a))a=a.replace(t,
""),a=a.replace(p,""),h="-",f=!0;else if(!0===m.test(a)&&!0===r.test(a))a=a.replace(m,""),a=a.replace(r,""),h="+",f=!0;else if("currency"===c.style){c=m=d.currencyCode;var n;void 0!==e.numbers.currencies[m]&&(c=e.numbers.currencies[m].symbol);void 0===d.currencyDisplay||"symbol"===d.currencyDisplay?n=c:"code"===d.currencyDisplay&&(n=m);void 0!==n&&(m=(g||"").replace(n,""),l=(l||"").replace(n,""),q=(q||"").replace(n,""),n=(k||"").replace(n,""),m=new RegExp(("^"+m).replace(U,"\\$1")),r=new RegExp(l.replace(U,
"\\$1")+"$"),t=new RegExp(("^"+q).replace(U,"\\$1")),p=new RegExp(n.replace(U,"\\$1")+"$"),!0===t.test(a)&&!0===p.test(a)?(a=a.replace(t,""),a=a.replace(p,""),h="-",f=!0):!0===m.test(a)&&!0===r.test(a)&&(a=a.replace(m,""),a=a.replace(r,""),h="+",f=!0))}f?d=[h,a]:(d=u(a,d,e),d[2]=!0);return d};u=function(a,c,d){var e=d.numbers[c.numberingSystem].group,h=d.numbers[c.numberingSystem].decimal,f=d.numbers[c.numberingSystem].minusSign,k="",g="";c=b.jj(d.numbers[c.numberingSystem].exponential);a=b.jj(a);
a=a.split(c).join("E");a=a.split(e).join("");c=e.replace(/\u00A0/g," ");e!==c&&(a=a.split(c).join(""));a=a.split(h).join(".");"."===a.charAt(0)&&(a=a.substr(1),g=".");a=a.replace(f,"-");e=ca.exec(a);g+=e[2];b.Rw(g,"-")?(g=g.substr(1),k="-"):b.Rw(a,"+")&&(g=g.substr(1),k="+");return[k,g]};v=function(a,c,d){var e=c.numbers[d.numberingSystem].minusSign;c=c.numbers[d.numberingSystem].plusSign;var h;a=b.Fp(a);e=b.Fp(e);c=b.Fp(c);b.Rw(a,e)?h=["-",a.substr(e.length)]:b.Rw(a,b.Fp(c))&&(h=["+",a.substr(c.length)]);
return h||["",a]};h=function(a,c){var d=J(c);if(void 0===b.Bp[d])return a;var e,h=[];for(e=0;e<a.length;e++){var f=b.Bp[d].indexOf(a[e]);-1!==f?h.push(f):h.push(a[e])}return h.join("")};f=function(a,c,d){var e={},h=d.numbers[c.numberingSystem].decimal;d=d.numbers[c.numberingSystem].group;a=a.replace(/ /g,"");var f=c.exponential,k=a.indexOf(f.toLowerCase());0>k&&(k=a.indexOf(b.jj(f)));0>k?(c=a,e.exponent=null):(c=a.substr(0,k),e.exponent=a.substr(k+f.length));f=c.indexOf(h);0>f?(a=c,e.fraction=null):
(a=c.substr(0,f),e.fraction=c.substr(f+h.length));a=a.split(d).join("");h=d.replace(/\u00A0/g," ");d!==h&&(a=a.split(h).join(""));e.integer=a;return e};E=function(a,c,d,e){isNaN(a)&&g(c.style,d,e);!0===d.isPercent||"percent"===c.style?a/=100:!0===d.isPerMill&&(a/=1E3);b.Tj(c,"OraNumberConverter.parse")("roundDuringParse","boolean",[!0,!1],!1)&&(a=x(a,d,c));return a};g=function(a,b,c){var d,e;d="Unparsable number "+c+" The expected number pattern is "+b.pat;switch(a){case "decimal":e="decimalFormatMismatch";
break;case "currency":e="currencyFormatMismatch";break;case "percent":e="percentFormatMismatch"}a=Error(d);a.errorInfo={errorCode:e,parameterMap:{value:c,format:b.pat}};throw a;};e=function(a,c,d,e){var k=b.sh(c),g={},l=h(a,e);w(c,g,d,e);c=NaN;c=l.replace(/ /g,"");if(fa.test(c))return c=parseFloat(l);e=q(l,d,g,k);c=e[0];var m=e[1];c=c||"+";if(e[2])return c=parseFloat(c+m),E(c,d,g,a);var p=f(m,g,k);e=p.fraction;m=p.exponent;c+=p.integer;null!==e&&(c+="."+e);null!==m&&(e=v(m,k,g),c+="e"+(e[0]||"+")+
e[1]);ha.test(c)?c=parseFloat(c):(c=u(l,g,k),c=parseFloat(c[0]+c[1]));return E(c,d,g,a)};var W,X,ba,da;V=function(a){var b;b=new SyntaxError('Unexpected character(s) encountered in the pattern "'+a+' An example of a valid pattern is "#,##0.###".');b.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:a,propertyValueHint:"#,##0.###"}};throw b;};N=function(a,b,c){return null!==(new RegExp(c,"i")).exec(a.substr(b,c.length))};Y=function(a,b){var c={};null!==W&&
(b.positivePrefix=R(W,a,b,c));null!==X&&(b.positiveSuffix=R(X,a,b,c));null!==ba&&(b.negativePrefix=R(ba,a,b,c));null!==da&&(b.negativeSuffix=R(da,a,b,c));void 0!==c.name&&(b.positiveSuffix="\u00a0"+c.name,b.positivePrefix="","ar"===b.lang?(b.negativeSuffix=a.numbers[b.numberingSystem].minusSign+"\u00a0"+c.name,b.negativePrefix=""):(b.negativeSuffix="\u00a0"+c.name,b.negativePrefix=a.numbers[b.numberingSystem].minusSign))};R=function(a,b,c,d){for(var e="",h=0;h<a.length;){var f=a.charAt(h++);if("'"!==
f){switch(f){case "\u00a4":var k=f=c.currencyCode,g=f;void 0!==b.numbers.currencies[f]&&(k=b.numbers.currencies[f].displayName,g=b.numbers.currencies[f].symbol);void 0===c.currencyDisplay||"symbol"===c.currencyDisplay?f=g:"code"!==c.currencyDisplay&&(f=k,d.name=f);break;case "%":f=b.numbers[c.numberingSystem].percentSign;break;case "\u2030":f=b.numbers[c.numberingSystem].perMille;break;case "-":f=b.numbers[c.numberingSystem].minusSign}e=e.concat(f)}}return e};p=function(a,b,c,d){for(var e=!1,h=!1,
f=0,k=0,g=!0,l=1;0<=l&&k<b.length;--l){for(var q=!1,m="",r="",t=-1,p=1,n=0,u=0,s=0,v=-1,w=-1,y,x=0,g=!0,A=k;A<b.length;++A){var B=b.charAt(A);switch(x){case 0:case 2:if(q){if("'"===B){A+1<b.length&&"'"===b.charAt(A+1)?(++A,g?m=m.concat("''"):r=r.concat("''")):q=!1;continue}}else if("#"===B||"0"===B||","===B||"."===B){x=1;--A;continue}else if("\u00a4"===B){void 0===a.currency&&z("pattern");a.style="currency";(B=A+1<b.length&&"\u00a4"===b.charAt(A+1))&&++A;g?m=m.concat(B?"'\u00a4\u00a4":"'\u00a4"):
r=r.concat(B?"'\u00a4\u00a4":"'\u00a4");continue}else if("'"===B){if("'"===B){A+1<b.length&&"'"===b.charAt(A+1)?(++A,g?m=m.concat("''"):r=r.concat("''")):q=!0;continue}}else if(";"===B){0!==x&&0!==l||V(b);k=A+1;A=b.length;continue}else if("%"===B){a.style="percent";1!==p&&V(b);d.isPercent=!0;p=100;g?m=m.concat("'%"):r=r.concat("'%");continue}else if("\u2030"===B){1!==p&&V(b);a.style="perMill";d.isPerMill=!0;p=1E3;g?m=m.concat("'\u2030"):r=r.concat("'\u2030");continue}else if("-"===B){g?m=m.concat("'-"):
r=r.concat("'-");continue}g?m=m.concat(B):r=r.concat(B);break;case 1:if(1===l)++f;else{0===--f&&(x=2,g=!1);continue}if("#"===B)0<u?++s:++n,0<=v&&0>t&&++v;else if("0"===B)0<s&&V(b),++u,0<=v&&0>t&&++v;else if(","===B)w=v,v=0;else if("."===B)0<=t&&V(b),t=n+u+s;else if(N(b,A,"E")){h&&V(b);h=!0;y=0;for(A+=1;A<b.length&&"0"===b.charAt(A);)++y,++f,++A;(1>n+u||1>y)&&V(b);x=2;g=!1;--A}else x=2,g=!1,--A,--f}}0===u&&0<n&&0<=t&&(u=t,0===u&&++u,s=n-u,n=u-1,u=1);(0>t&&0<s||0<=t&&(t<n||t>n+u)||0===v||q)&&V(b);1===
l?(W=m,X=r,ba=W,da=X,q=n+u+s,d.minimumIntegerDigits=(0<=t?t:q)-n,d.maximumIntegerDigits=h?n+d.minimumIntegerDigits:2147483647,d.maximumFractionDigits=0<=t?q-t:0,d.minimumFractionDigits=0<=t?n+u-t:0,d.groupingSize=0<v?v:0,d.groupingSize0=w):(ba=m,da=r,e=!0)}0===b.length&&(W=X="",d.minimumIntegerDigits=0,d.maximumIntegerDigits=2147483647,d.minimumFractionDigits=0,d.maximumFractionDigits=2147483647);d.useExponentialNotation=h;d.minExponentDigits=y;if(!e||0===ba.localeCompare(W)&&0===da.localeCompare(X))"currency"===
a.style&&"ar"===d.lang?(da=X+"'\u200f-",ba=W):(da=X,ba="'-"+W);Y(c,d)};x=function(a,b,c){var d=0>a;a=G(Math.abs(a),b.maximumFractionDigits,c.roundingMode||"DEFAULT");return d?-a:a};T=function(a,c,d){var e={};y(c,"OraNumberConverter.resolvedOptions");w(a,e,c,d);e.numberingSystemKey=J(d);void 0===b.Bp[e.numberingSystemKey]&&(e.numberingSystemKey="latn");return e};S=function(a,b,c){c={locale:c,style:void 0===b.style?"decimal":b.style,useGrouping:void 0===b.useGrouping?!0:b.useGrouping,numberingSystem:a.numberingSystemKey};
c.minimumIntegerDigits=a.minimumIntegerDigits;c.minimumFractionDigits=a.minimumFractionDigits;c.maximumFractionDigits=a.maximumFractionDigits;"decimal"===b.style&&void 0!==b.decimalFormat&&(c.decimalFormat=b.decimalFormat);"currency"===b.style&&(c.currency=b.currency,c.currencyDisplay=void 0===b.currencyDisplay?"symbol":b.currencyDisplay);void 0!==b.pattern&&(c.pattern=b.pattern);a=b.roundingMode;b=b.roundDuringParse;void 0!==a&&(c.roundingMode=a);void 0!==b&&(c.roundDuringParse=b);return c};return{Je:function(){Q||
(Q=a());return Q}}}();a.Ch=function(a){this.Init(a)};o_("RegExpValidator",a.Ch,a);a.b.ta(a.Ch,a.Gi,"oj.RegExpValidator");a.Ch.TO="oj-validator.regExp.detail";a.Ch.UO="oj-validator.regExp.summary";a.Ch.prototype.Init=function(b){a.Ch.t.Init.call(this);this.Vb=b};a.b.g("RegExpValidator.prototype.Init",{Init:a.Ch.prototype.Init});a.Ch.prototype.validate=function(b){var c,d,e=this.Vb&&this.Vb.pattern||"",h;if(null===b||void 0===b||""===b)return!0;b=b||0===b?b.toString():b;var f;f=b.match("^("+e+")$");
if(null===f||f[0]!==b)throw this.Vb&&(h=this.Vb.messageSummary||null,c=this.Vb.messageDetail||null,d=this.Vb&&this.Vb.label||""),b={label:d,pattern:e,value:b},h=h?a.va.Lc(h,b):a.va.F(this.eT(),b),c=c?a.va.Lc(c,b):a.va.F(this.vS(),b),new a.nk(h,c);return!0};a.b.g("RegExpValidator.prototype.validate",{validate:a.Ch.prototype.validate});a.Ch.prototype.Md=function(){var b=null,c={};this.Vb&&this.Vb.hint&&(c={pattern:this.Vb.pattern},b=a.va.Lc(this.Vb.hint,c));return b};a.b.g("RegExpValidator.prototype.getHint",
{Md:a.Ch.prototype.Md});a.Ch.prototype.eT=function(){return a.Ch.UO};a.Ch.prototype.vS=function(){return a.Ch.TO};a.Qa={};o_("IntlConverterUtils",a.Qa,a);a.Qa.isoToDate=function(a){return b.isoToDate(a)};a.Qa.isoToLocalDate=function(a){return b.isoToLocalDate(a)};a.Qa.dateToLocalIso=function(a){return b.dateToLocalIso(a)};a.Qa.L7=function(a){return b.L7(a)};a.Qa.getLocalTimeZoneOffset=function(){return b.getLocalTimeZoneOffset()};a.Qa.getConverterInstance=function(b){var c="",d={},e=null;b&&("object"===
typeof b&&(b instanceof a.sg||b.parse&&"function"===typeof b.parse||b.format&&"function"===typeof b.format?e=b:(c=b.type,d=b.options||{})),e||(c=c||b)&&"string"===typeof c&&(b=a.Ea.qn(c),e=b.createConverter(d)));return e};a.Qa._minMaxIsoString=function(a,b){if(a){b=b||this.dateToLocalIso(new Date);var c=b.indexOf("T");0===a.indexOf("T")&&0<c&&(a=b.substring(0,c)+a)}return a};a.Qa.Qx=function(b,c){a.o.di(c);var d="",e="",h=c.propertyName,f;"optionTypesMismatch"===b?(e=c.requiredPropertyName,f=c.requiredPropertyValueValid,
d=a.va.F("oj-converter.optionTypesMismatch.summary",{propertyName:h,propertyValue:c.propertyValue,requiredPropertyName:e}),e=a.Qa.XI(e,f)):"optionTypeInvalid"===b?(h=c.propertyName,f=c.propertyValueValid,d=a.va.F("oj-converter.optionTypeInvalid.summary",{propertyName:h}),e=a.Qa.XI(h,f)):"optionOutOfRange"===b?(d=a.va.F("oj-converter.optionOutOfRange.summary",{propertyName:h,propertyValue:c.propertyValue}),f=c.propertyValueValid,e=a.Qa.XI(h,f)):"optionValueInvalid"===b&&(d=a.va.F("oj-converter.optionValueInvalid.summary",
{propertyName:h,propertyValue:c.propertyValue}),f=c.propertyValueHint,e=a.Qa.XI(h,f));return new a.tg(d,e)};a.Qa.XI=function(b,c){var d;return c?("string"===typeof c?d="oj-converter.optionHint.detail":(d="oj-converter.optionHint.detail-plural",c=c.join(a.va.F("oj-converter.plural-separator"))),a.va.F(d,{propertyName:b,propertyValueValid:c})):""};a.Qa.qKa=function(){return""};a.Qa._copyTimeOver=function(a,c){return b._copyTimeOver(a,c)};a.Qa._clearTime=function(a){return b._clearTime(a)};a.Qa._dateTime=
function(a,c,d){return b._dateTime(a,c,d)};a.Qa._normalizeIsoString=function(a){return b._normalizeIsoString(a)};var h;h=function(){function a(){return{format:function(a,c,d,e){var h;if("number"===typeof a)h=b.dateToLocalIso(new Date(a));else if("string"===typeof a){if(h=b.trim(a),""===h)return null}else return null;if(2>=arguments.length||void 0===d)d={year:"numeric",month:"numeric",day:"numeric"};h=b.YL(h);h=r(c,d,h,e);var f=b.bM(e);void 0===b.Bp[f]&&(f="latn");if("latn"!==f){var k,g=[];for(k=0;k<
h.length;k++)"0"<=h[k]&&"9">=h[k]?g.push(b.Bp[f][h[k]]):g.push(h[k]);return g.join("")}return h},RL:function(a,b,c){return p(a,b,c)},parse:function(a,b,c,d){return n(a,b,c,d)},resolvedOptions:function(a,c,d){if(3>arguments.length||void 0===d)d=b.rt(a);if(2>arguments.length||void 0===c)c={year:"numeric",month:"numeric",day:"numeric"};var e,h,f,k=b.Tj(c,"OraDateTimeConverter.resolvedOptions");void 0!==c&&(h=k("isoStrFormat","string",[la,ma,Ra,ka,sa],sa),f=k("dst","boolean",[!0,!1],!1),e=c.timeZone);
var g=b.bM(d);void 0===b.Bp[g]&&(g="latn");return void 0!==c&&void 0!==c.pattern?Ja(h,e,f,d,g,c):void 0!==c?qa(c,k,e,f,h,a,g,d):ba(a,d,g)},ft:function(a){a=b.isoToLocalDate(a);var c=new Date(a.getTime());c.setDate(c.getDate()+4-(c.getDay()||7));a=c.getTime();c.setMonth(0);c.setDate(1);return Math.floor(Math.round((a-c)/864E5)/7)+1},pLa:function(a){return Pa(a)},ve:function(a,c,d){var e=Ma(a,c);a=n(a,d,e,"en-US");c=n(c,d,e,"en-US");d=a.value.replace("Z","");c=c.value.replace("Z","");d=b.yB(d);d=Date.UTC(d[0],
d[1]-1,d[2],d[3],d[4],d[5],d[6]);c=b.yB(c);c=Date.UTC(c[0],c[1]-1,c[2],c[3],c[4],c[5],c[6]);return d-c}}}var c,d,f,g,r,n,p,q,u,v,w,y,x,z,D,I={},B={},G,C,K,A,J,F,E,H,L,P,M,Q,N,R,Y,V,T,S,fa,ha,ca,U,O,Z,ea,ga,W,X,ba,da,ja,qa,Ia,Ja,Ka,aa,Ma,ya,Na,Oa,ta,wa,ua,La,xa,za,Aa,Ba,Pa,Qa,Ca,Da,Ea,ra,Fa,na,oa,Ga=/(\d{1,4})\D+?(\d{1,4})/g,Ha=/(\d{1,4})\D+?(\d{1,4})\D+?(\d{1,4})/g,Sa=/^[M][^M]|[^M]M[^M]|[^M]M$|^M$/g,Za=/^[L][^L]|[^L]L[^L]|[^L]L$|^L$/g,Ta=/^[d][^d]|[^d]d[^d]|[^d]d$|^d$|^d[^d]/,Ua=/(?:^|[^h])h[^h]|[^H]H[^H]|[^k]k[^k]|[^K]K[^K]|^H[^H]|^H$|[^h]h$/,
Va=/'.*'/,Wa=/'[^d]*d[^d]*'/,Xa=/(\d{1,2})(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,2}))?(?:\D+?(\d{1,3}))?/g,va=/h|H|K|k/g,Ya=/([\^\$\.\*\+\?\|\[\]\(\)\{\}])/g,pa=/ccccc|cccc|ccc|cc|c|EEEEE|EEEE|EEE|EE|E|dd|d|MMMMM|MMMM|MMM|MM|M|LLLLL|LLLL|LLL|LL|L|yyyy|yy|y|hh|h|HH|H|KK|K|kk|k|mm|m|ss|s|aa|a|SSS|SS|S|zzzz|zzz|zz|z|v|ZZZ|ZZ|Z|XXX|XX|X|VV|GGGGG|GGGG|GGG|GG|G/g,$a={0:"sun",1:"mon",2:"tue",3:"wed",4:"thu",5:"fri",6:"sat"},la="zulu",ka="local",sa="auto",Ra="invariant",ma="offset",ia={MMM:{token:"months",style:"format",
mLen:"abbreviated",matchIndex:0,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMM:{token:"months",style:"format",mLen:"wide",matchIndex:0,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},MMMMM:{token:"months",style:"format",mLen:"narrow",matchIndex:0,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLL:{token:"months",style:"stand-alone",mLen:"abbreviated",matchIndex:1,key:"month",value:"short",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},
LLLL:{token:"months",style:"stand-alone",mLen:"wide",matchIndex:1,key:"month",value:"long",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},LLLLL:{token:"months",style:"stand-alone",mLen:"narrow",matchIndex:1,key:"month",value:"narrow",regExp:"(\\D+|\\d\\d?\\D|\\d\\d?|\\D+\\d\\d?)"},E:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},
EEE:{token:"days",style:"format",dLen:"abbreviated",matchIndex:0,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},EEEE:{token:"days",style:"format",dLen:"wide",matchIndex:0,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},EEEEE:{token:"days",style:"format",dLen:"narrow",matchIndex:0,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},c:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cc:{token:"days",style:"stand-alone",
dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},ccc:{token:"days",style:"stand-alone",dLen:"abbreviated",matchIndex:1,key:"weekday",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},cccc:{token:"days",style:"stand-alone",dLen:"wide",matchIndex:1,key:"weekday",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},ccccc:{token:"days",style:"stand-alone",dLen:"narrow",matchIndex:1,key:"weekday",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},h:{token:"time",timePart:"hour",start1:0,
end1:11,start2:1,end2:12,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},hh:{token:"time",timePart:"hour",start1:0,end1:11,start2:1,end2:12,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},K:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},KK:{token:"time",timePart:"hour",start1:0,end1:11,start2:0,end2:11,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},H:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"numeric",
regExp:"(\\d\\d?)"},HH:{token:"time",timePart:"hour",start1:0,end1:23,start2:0,end2:23,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},k:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"numeric",regExp:"(\\d\\d?)"},kk:{token:"time",timePart:"hour",start1:0,end1:23,start2:1,end2:24,key:"hour",value:"2-digit",regExp:"(\\d\\d?)"},m:{token:"time",timePart:"minute",start1:0,end1:59,start2:0,end2:59,key:"minute",value:"numeric",regExp:"(\\d\\d?)"},mm:{token:"time",timePart:"minute",
start1:0,end1:59,start2:0,end2:59,key:"minute",value:"2-digit",regExp:"(\\d\\d?)"},s:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"numeric",regExp:"(\\d\\d?)"},ss:{token:"time",timePart:"second",start1:0,end1:59,start2:0,end2:59,key:"second",value:"2-digit",regExp:"(\\d\\d?)"},S:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,
end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},SSS:{token:"time",timePart:"millisec",start1:0,end1:999,start2:0,end2:999,key:"millisecond",value:"numeric",regExp:"(\\d{1,3})"},d:{token:"dayOfMonth",key:"day",value:"numeric",getPartIdx:2,regExp:"(\\d\\d?)"},dd:{token:"dayOfMonth",key:"day",value:"2-digit",getPartIdx:2,regExp:"(\\d\\d?)"},M:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},MM:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,
regExp:"(\\d\\d?)"},L:{token:"monthIndex",key:"month",value:"numeric",getPartIdx:1,regExp:"(\\d\\d?)"},LL:{token:"monthIndex",key:"month",value:"2-digit",getPartIdx:1,regExp:"(\\d\\d?)"},y:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},yy:{token:"year",key:"year",value:"2-digit",regExp:"(\\d\\d?)"},yyyy:{token:"year",key:"year",value:"numeric",regExp:"(\\d{1,4})"},a:{token:"ampm",key:"hour12",value:!0,regExp:"(\\D*)"},z:{token:"tzAbbrev",regExp:"(.+?)"},v:{token:"tzAbbrev",key:"timeZoneName",
value:"short",regExp:"(.+?)"},zz:{token:"tzAbbrev",regExp:"(.+?)"},zzz:{token:"tzAbbrev",regExp:"(.+?)"},zzzz:{token:"tzFull",regExp:"(.+?)"},Z:{token:"tzhm",regExp:"([+-]?\\d{1,4})"},ZZ:{token:"tzhm",regExp:"([+-]?\\d{1,4})"},ZZZ:{token:"tzhm",regExp:"([+-]?\\d{1,4})"},X:{token:"tzh",regExp:"([+-]?\\d{1,2})"},XX:{token:"tzhm",key:"XX",regExp:"([+-]?\\d{1,4})"},XXX:{token:"tzhsepm",regExp:"([+-]?\\d{1,2}:\\d{1,2})"},VV:{token:"tzid",regExp:"(.+?)"},G:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},
GG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGG:{token:"era",key:"era",value:"short",regExp:"(\\D+|\\D+\\d\\d?)"},GGGG:{token:"era",key:"era",value:"long",regExp:"(\\D+|\\D+\\d\\d?)"},GGGGG:{token:"era",key:"era",value:"narrow",regExp:"(\\D+|\\D+\\d\\d?)"},"/":{token:"slash",regExp:"(\\/)"}};y=function(a){a=a["two-digit-year-start"];if(void 0===a||isNaN(a))a=1950;return a=parseInt(a,10)};x=function(a){return"h"===a.supplemental.prefferedHours[b.uea(b.rt(a))]};G=function(a){return 0===
a%400?!0:0===a%100?!1:0===a%4?!0:!1};C=function(a,b){switch(b){case 0:case 2:case 4:case 6:case 7:case 9:case 11:return 31;case 1:return G(a)?29:28;default:return 30}};D=function(a,c,d){c=b.sh(c);var e=b.Tj(a,d);a=e("formatType","string",["date","time","datetime"],"date");d=e("dateFormat","string",["short","medium","long","full"],"short");var e=e("timeFormat","string",["short","medium","long","full"],"short"),h=c.dates.calendars.gregorian;c=h.dateFormats;var h=h.timeFormats,f,k,g;switch(d){case "full":f=
c.full;break;case "long":f=c["long"];break;case "medium":f=c.medium;break;case "short":f=c["short"]}switch(e){case "full":k=h.full;break;case "long":k=h["long"];break;case "medium":k=h.medium;break;case "short":k=h["short"]}void 0===f||"datetime"!==a&&"date"!==a||(g=f);void 0===k||"datetime"!==a&&"time"!==a||(g=g?g+" "+k:k);return g};d=function(a,b){for(var c=0,d=!1,e=0,h=a.length;e<h;e++){var f=a.charAt(e);switch(f){case "'":d?b.push("'"):c++;d=!1;break;case "\\":d&&b.push("\\");d=!d;break;default:b.push(f),
d=!1}}return c};q=function(a,b,c){var d;d=void 0!==b.year||void 0!==b.month||void 0!==b.weekday||void 0!==b.day;b=void 0!==b.hour||void 0!==b.minute||void 0!==b.second;d=d&&b?"MM/dd/yy hh:mm:ss a":d?"MM/dd/yy":"hh:mm:ss a";c=new SyntaxError("Unexpected character(s) "+c+' encountered in the pattern "'+a+' An example of a valid pattern is "'+d+'".');c.errorInfo={errorCode:"optionValueInvalid",parameterMap:{propertyName:"pattern",propertyValue:a,"propertyValueHint ":d}};throw c;};F=function(a,c,d,e){c=
b.sh(c).dates.calendars.gregorian.dateTimeFormats.availableFormats;d="weekday era year month day hour minute second timeZoneName".split(" ");var h={"2-digit":0,numeric:1,narrow:2,"short":3,"long":4},f=-Infinity,k=void 0,g,l,q;for(q in c){l=!1;var m={};m.pattern=c[q];for(var r=0;null!==(g=pa.exec(q));)g=g[0],"h"!==g&&"hh"!==g||e?"H"!==g&&"HH"!==g||!e?void 0!==ia[g]&&(m[ia[g].key]=ia[g].value):l=!0:l=!0;if(!l){for(var t in d)l=a[d[t]],g=m[d[t]],void 0===l&&void 0!==g?r-=20:void 0!==l&&void 0===g?r-=
120:void 0!==l&&void 0!==g&&(l=Math.max(Math.min(h[g]-h[l],2),-2),2===l?r-=6:1===l?r-=3:-1===l?r-=6:-2===l&&(r-=8));r>f&&(f=r,k=m)}}return void 0!==k?k.pattern:null};K=function(a,c,d){var e="",h="",f={},k={};a=b.Tj(a,d);d=a("era","string",["narrow","short","long"]);e+=E(f,"era",d,{narrow:"GGGGG","short":"GGG","long":"GGGG"});d=a("year","string",["2-digit","numeric"]);e+=E(f,"year",d,{"2-digit":"yy",numeric:"y"});d=a("month","string",["2-digit","numeric","narrow","short","long"]);e+=E(f,"month",d,
{"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"});d=a("weekday","string",["narrow","short","long"]);e+=E(f,"weekday",d,{narrow:"EEEEE","short":"E","long":"EEEE"});d=a("day","string",["2-digit","numeric"]);var e=e+E(f,"day",d,{"2-digit":"dd",numeric:"d"}),g=a("hour12","boolean",[!0,!1]);void 0===g&&(g=x(c));d=a("hour","string",["2-digit","numeric"]);h=!0===g?h+E(k,"hour",d,{"2-digit":"hh",numeric:"h"}):h+E(k,"hour",d,{"2-digit":"HH",numeric:"H"});d=a("minute","string",["2-digit",
"numeric"]);h+=E(k,"minute",d,{"2-digit":"mm",numeric:"m"});d=a("second","string",["2-digit","numeric"]);h+=E(k,"second",d,{"2-digit":"ss",numeric:"s"});d=a("timeZoneName","string",["short","long"]);h+=E(k,"timeZoneName",d,{"short":"v","long":"v"});return[e,h,f,k]};E=function(a,b,c,d){return void 0!==c?(a[b]=c,d[c]):""};A=function(a,c,d){var e=a;c=b.Tj(c,d);d=c("year","string",["2-digit","numeric"]);var h={"2-digit":"yy",numeric:"yyyy"};void 0!==d&&(e=e.replace(/y{1,4}/,h[d]));d=c("month","string",
["2-digit","numeric","narrow","short","long"]);if(void 0!==d){var h={"2-digit":"MM",numeric:"M",narrow:"MMMMM","short":"MMM","long":"MMMM"},f={"2-digit":"LL",numeric:"L",narrow:"LLLLL","short":"LLL","long":"LLLL"};void 0!==h[d]&&2<h[d].length?(e=e.replace(/M{3,5}/,h[d]),e=e.replace(/L{3,5}/,f[d])):"2-digit"===d&&(Sa.lastIndex=0,(d=Sa.test(a))&&(e=e.replace("M","MM")),(d=Za.test(a))&&(e=e.replace("L","LL")))}d=c("weekday","string",["narrow","short","long"]);void 0!==d&&(e=e.replace(/E{1,5}/,{narrow:"EEEEE",
"short":"EEE","long":"EEEE"}[d]),e=e.replace(/c{1,5}/,{narrow:"ccccc","short":"ccc","long":"cccc"}[d]));d=c("day","string",["2-digit","numeric"]);void 0!==d&&"2-digit"===d&&(Ta.lastIndex=0,Wa.lastIndex=0,c=Wa.test(a),d=Ta.test(a),!0==d&&!1===c&&(e=e.replace("d","dd")));return e};J=function(a,c,d){var e=a;"2-digit"===b.Tj(c,d)("hour","string",["2-digit","numeric"])&&(Ua.lastIndex=0,Va.lastIndex=0,c=a.replace(Va,""),c=Ua.exec(c),null!==c&&(va.lastIndex=0,e=va.exec(c[0]),e=a.replace(e[0],e[0]+e[0])));
return e};wa=function(a,b,c){var d,e=0;for(d in b)e++;if(1<e)return null;for(d=a.length;0<d;d--)if(b=c[a.substr(0,d)],void 0!==b)return b;return a};Na=function(a,c){var d="symbols-numberSystem-"+b.YFa(a,c);return a.numbers[d].decimal};f=function(a,c,d,e){function h(b){if(void 0!==p){var c=Na(f,d),c=void 0===m&&void 0===r&&void 0===t?"S":"ss"+c+"SSS";b=b.replace("ss",c);void 0===t&&(a.second=void 0)}var c=g("timeZoneName","string",["short","long"]),e={"short":"z","long":"zzzz"};void 0!==c&&(b=b.replace(/v/,
e[c]));return b}var f=b.sh(c),k=b.rt(c),g=b.Tj(a,e),l=g("formatMatcher","string",["basic","munger"],"munger"),q=0;for(q in a)q++;0===q&&(a={year:"numeric",month:"numeric",day:"numeric"});var m,r,t,p;p=g("millisecond","string",["numeric","2-digit"]);t=g("second","string",["numeric","2-digit"]);void 0!==p&&(m=g("hour","string",["numeric","2-digit"]),r=g("minute","string",["numeric","2-digit"]),a.second="2-digit");q=K(a,c,e);if(void 0!==I[k]){var n=I[k].dates.calendars.gregorian.dateTimeFormats[q[0]+
q[1]];if(void 0!==n)return n=h(n)}if(""===q[0]&&""===q[1])return D(a,c,e);var u=f.dates.calendars.gregorian.dateTimeFormats.availableFormats,s=u[q[0]],v=g("hour12","boolean",[!0,!1]);void 0===v&&(v=x(c));void 0===s&&""!==q[0]&&(s=wa(q[0],q[2],u),null===s&&(s=F(q[2],c,0,v)),null!==s?"basic"!==l&&(s=A(s,a,e)):s=q[0]);n=u[q[1]];void 0===n&&""!==q[1]&&(n=wa(q[1],q[3],u),null===n&&(n=F(q[3],c,0,v)),null!==n?"basic"!==l&&(n=J(n,a,e)):n=q[1]);c=s||"";void 0!==n&&(c=""!==c?c+(" "+n):n);void 0===I[k]&&(I[k]=
{},I[k].dates={},I[k].dates.calendars={},I[k].dates.calendars.gregorian={},I[k].dates.calendars.gregorian.dateTimeFormats={});I[k].dates.calendars.gregorian.dateTimeFormats[q[0]+q[1]]=c;return c=h(c)};ra=function(a){a=a.split(" ");var b=a[0].split("-"),c=new Date(b[0],b[1]-1,b[2]);1<a.length&&(b=a[1].split(":"),c.setHours(b[0]),c.setMinutes(b[1]));return c.getTime()};Ea=function(a,b,c){a=new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5]);a=a.getTime();b=b.split("/");c=c[b[0]];if(void 0===c)return null;c=c[b[1]];
if(void 0===c)return null;var d=c.length,e,h,f,k,g;for(b=0;b<d;b++)if(f=c[b].usesMetazone._from,k=c[b].usesMetazone._to,g=c[b].usesMetazone._mzone,void 0===f&&void 0===k||void 0===f&&void 0!==k&&(h=ra(k),a<=h)||void 0!==f&&void 0===k&&(e=ra(f),a>=e)||void 0!==f&&void 0!==k&&(e=ra(f),h=ra(k),a>=e&&a<h))return g};Fa=function(a,c,d,e,h){var f=b.sh(a),k="",g=d.timeZone;d=b.Tj(d,"OraDateTimeConverter")("dst","boolean",[!0,!1],!1);if(void 0===g)return k;var l=Ea(c,g,a.supplemental.metazones),k="standard";
h=h?!1:!0;a=na(g,a);c=oa(a,c,d,h,!0);f=f.dates.timeZoneNames.metazone[l];if(void 0===f)return k=a.offset(c),b.bA("UTC",k,!0,!0);f=1===e?f["long"]:f["short"];e=a.offset(c);c=a.offset(c+1);e<c&&(k="daylight");return void 0!==f&&(k=f[k],void 0!==k)?k:b.bA("UTC",e,!0,!0)};na=function(a,b){return e.Je().zfa(a,b)};oa=function(a,b,c,d,e){return a.parse(Date.UTC(b[0],b[1]-1,b[2],b[3],b[4],b[5]),c,d,e)};r=function(a,c,e,h){function k(a,b){switch(b){case 0:return a[0];case 1:return a[1];case 2:return a[2];
case 3:return $a[(new Date(a[0],a[1]-1,a[2],a[3],a[4],a[5])).getDay()]}}function g(a,c,d,e){c=k(c,d);a.push(1<e?b.sc(c,e):c)}function l(a,d,e,h,f){var k;switch(h.timePart){case "hour":k=11===h.end1?d[3]%12:d[3];"h"===f||"hh"===f?0===k&&(k=12):"k"!==f&&"kk"!==f||0!==k||(k=24);break;case "minute":k=d[4];break;case "second":k=void 0===c.second&&void 0!==c.millisecond?0:d[5];break;case "millisec":k=d[6]}a.push(1<e?b.sc(k,e):k)}function r(c,d,h){var f,k=d.timeZone;d=v("dst","boolean",[!0,!1],!1);h=h?!1:
!0;if(void 0!==k)f=na(k,a),c=oa(f,c,d,h,!0),f=-f.offset(c);else if(e.format!==ka)switch(e.format){case ma:f=e.timeZone.split(":");c=parseInt(f[1],10);f=60*parseInt(f[0],10)+(b.Rw(e.timeZone,"-")?-c:c);break;case la:f=0;break;default:f=0}return f}var t,p=e.isoStrParts,n=0===e.dateTime.indexOf("T"),u=b.sh(a),v=b.Tj(c,"OraDateTimeConverter.format");t=c.pattern||f(c,a,h,"OraDateTimeConverter.format");h=[];var w,y=0,u=u.dates.calendars.gregorian,x=c.timeZone;for(e.format!==ka&&void 0!==x&&Aa(e,c,a);;){var A=
pa.lastIndex,B=pa.exec(t),A=t.slice(A,B?B.index:t.length),y=y+d(A,h);if(!B)break;if(y%2)h.push(B[0]);else switch(w=B[0],B=w.length,A=ia[w],A.token){case "days":w=u[A.token][A.style][A.dLen];h.push(w[k(p,3)]);break;case "months":w=u[A.token][A.style][A.mLen];h.push(w[k(p,1)]);break;case "dayOfMonth":case "monthIndex":h.push(g(h,p,A.getPartIdx,B));break;case "year":w=p[0];2===B&&(w%=100);h.push(b.sc(w,B));break;case "time":l(h,p,B,A,w);break;case "ampm":w=12>p[3]?u.dayPeriods.format.wide.am:u.dayPeriods.format.wide.pm;
h.push(w);break;case "tzhm":w=r(p,c,n);0===w?"XX"===A.key?h.push("Z"):h.push("+0000"):h.push((0>=w?"-":"+")+b.sc(Math.floor(Math.abs(w/60)),2)+b.sc(Math.floor(Math.abs(w%60)),2));break;case "tzhsepm":w=r(p,c,n);0===w?h.push("Z"):h.push((0>=w?"-":"+")+b.sc(Math.floor(Math.abs(w/60)),2)+":"+b.sc(Math.floor(Math.abs(w%60)),2));break;case "tzh":w=r(p,c,n);0===w?h.push("Z"):h.push((0>=w?"-":"+")+b.sc(Math.floor(Math.abs(w/60)),2));break;case "tzid":w=void 0!==x?x:e.format===la?"UTC":"";h.push(w);break;
case "tzAbbrev":w=Fa(a,p,c,0,n);h.push(w);break;case "tzFull":w=Fa(a,p,c,1,n);h.push(w);break;case "era":w=u.eras.eraAbbr;h.push(w["1"]);break;case "slash":h.push("/");break;default:q(t,c,w)}}return h.join("")};P=function(a,b){return a.getFullYear()===b.getFullYear()};M=function(a,b){return 1===b.getFullYear()-a.getFullYear()};Q=function(a,b){return M(b,a)};N=function(a,b){return P(a,b)&&a.getMonth()===b.getMonth()};R=function(a,b){return P(a,b)?1===b.getMonth()-a.getMonth():M(a,b)?11===a.getMonth()&&
0===b.getMonth():!1};Y=function(a,b){return R(b,a)};H=function(a,b){var c=a.getDate(),d=b.getDate();R(a,b)&&(d+=C(a.getFullYear,a.getMonth()));return d-c};L=function(a,c){var d=a.supplemental.weekData.firstDay,e=d[b.uea(b.rt(a))];void 0===e&&(e=d["001"]);d=c-e;0>d&&(d+=7);return d};V=function(a,b,c){if(b>c){var d=b;b=c;c=d}if(!N(b,c)&&!R(b,c))return!1;a=H(b,c)+L(a,b.getDay());return 0<=a&&6>=a};T=function(a,b,c){if(!N(b,c)&&!R(b,c))return!1;a=H(b,c)+L(a,b.getDay());return 7<=a&&13>=a};S=function(a,
b,c){return T(a,c,b)};fa=function(a,b){return P(a,b)&&N(a,b)&&a.getDate()===b.getDate()};ha=function(a,b){return N(a,b)||R(a,b)?1===H(a,b):!1};ca=function(a,b){return ha(b,a)};p=function(a,c,d){if("number"===typeof a)a=new Date(a);else if("string"===typeof a){if(""===b.trim(a))return null;a=b.isoToLocalDate(a)}else return null;var e=b.sh(c).dates.fields;d=b.Tj(d,"OraDateTimeConverter.formatRelative");d("formatUsing","string",["displayName"]);d=d("dateField","string",["day","week","month","year"]);
var h=new Date;switch(d){case "day":if(fa(h,a))return e.day["relative-type-0"];if(ha(h,a))return e.day["relative-type-1"];if(ca(h,a))return e.day["relative-type--1"];break;case "week":if(V(c,h,a))return e.week["relative-type-0"];if(T(c,h,a))return e.week["relative-type-1"];if(S(c,h,a))return e.week["relative-type--1"];break;case "month":if(N(h,a))return e.month["relative-type-0"];if(R(h,a))return e.month["relative-type-1"];if(Y(h,a))return e.month["relative-type--1"];break;case "year":if(P(h,a))return e.year["relative-type-0"];
if(M(h,a))return e.year["relative-type-1"];if(Q(h,a))return e.year["relative-type--1"]}return null};ua=function(a,b){var c;c=Error("The weekday "+a+" does not match the date "+b);c.errorInfo={errorCode:"dateToWeekdayMismatch",parameterMap:{weekday:a,date:b}};throw c;};ta=function(a,b,c){var d;2===c?(d='The value "'+a+'" does not match the expected date-time format "'+b+'"',c="datetimeFormatMismatch"):0===c?(d='The value "'+a+'" does not match the expected date format "'+b+'"',c="dateFormatMismatch"):
(d='The value "'+a+'" does not match the expected time format "'+b+'"',c="timeFormatMismatch");d=Error(d);d.errorInfo={errorCode:c,parameterMap:{value:a,format:b}};throw d;};U=function(a,b){100>b&&(b+=100*Math.floor(a/100)+(b<a%100?100:0));return b};ya=function(a,c){var d={sun:0,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6},e;for(e in a)if(b.trim(b.jj(a[e]))===b.trim(c))return d[e];return-1};Oa=function(a,c){for(var d in a)if(b.trim(b.jj(a[d]))===b.trim(c))return d-1;return-1};X=function(a,c,d){var e=b.sh(a),
h;a=e.dates.calendars.gregorian.days.format;e=e.dates.calendars.gregorian.days["stand-alone"];switch(d){case 0:h=[a.abbreviated,a.wide];break;case 1:h=[e.abbreviated,e.wide]}c=b.jj(c);d=ya(h[0],c);-1===d&&(d=ya(h[1],c));return d};da=function(a,c,d){var e=-1,h=b.sh(a);a=h.dates.calendars.gregorian.months.format;h=h.dates.calendars.gregorian.months["stand-alone"];switch(d){case 0:d=[a.wide,a.abbreviated];break;case 1:d=[h.wide,h.abbreviated];break;case 2:d=[a.wide,a.abbreviated,h.wide,h.abbreviated];
break;default:return-1}c=b.jj(c);for(var f in d)if(e=Oa(d[f],c),-1!==e)break;return e};Ia=function(a,b){for(var c=a.replace(Ya,"\\\\$1"),e=["^"],h=[],f=0,k=0,g;null!==(g=pa.exec(c));){var l=c.slice(f,g.index),f=pa.lastIndex,k=k+d(l,e);if(k%2)e.push(g[0]);else{var l=g[0],r;void 0!==ia[l]?r=ia[l].regExp:q(a,b,l);r&&e.push(r);h.push(g[0])}}d(c.slice(f),e);e.push("$");c={regExp:e.join("").replace(/\s+/g,"\\s+"),groups:h};return{}[a]=c};aa=function(a,b,c,d,e,h,f){if(b<c||b>d)throw b=new RangeError(e+" is out of range.  Enter a value between "+
h+" and "+f+" for "+a),b.errorInfo={errorCode:"datetimeOutOfRange",parameterMap:{value:e,minValue:h,maxValue:f,propertyName:a}},b;};O=function(a,b){for(var c=0;c<a.length;c++)for(var d in a[c])if(d===b)return parseInt(c,10);return 0};W=function(a,c,d,e,h){var f=b.sh(e).dates.calendars.gregorian.dayPeriods.format.wide.pm,k=e=Xa.lastIndex=0,g=0,l=0,q=Xa.exec(c);null===q&&ta(c,d,h);void 0!==q[1]&&(e=parseInt(q[1],10));void 0!==q[2]&&(k=parseInt(q[2],10));void 0!==q[3]&&(g=parseInt(q[3],10));void 0!==
q[4]&&(l=parseInt(q[4],10));va.lastIndex=0;q=va.exec(d);switch(q[0]){case "h":12===e&&(e=0);aa("hour",e,0,11,e,1,12);c=b.jj(c).indexOf(b.jj(f));-1!==c&&12>e&&(e+=12);break;case "K":aa("hour",e,0,11,e,0,11);c=b.jj(c).indexOf(b.jj(f));-1!==c&&12>e&&(e+=12);break;case "H":aa("hour",e,0,23,e,0,23);break;case "k":24===e&&(e=0),aa("hour",e,0,23,e,1,24)}aa("minute",k,0,59,k,0,59);aa("second",g,0,59,g,0,59);aa("millisec",l,0,999,l,0,999);a.setHours(e,k,g,l)};Da=function(a,c){var d=b.sh(c),e=d.dates.calendars.gregorian.days.format,
d=d.dates.calendars.gregorian.days["stand-alone"],e=[e.wide,e.abbreviated,d.wide,d.abbreviated],d=!1,h,f,k;for(f in e){for(k in e[f])if(h=e[f][k],(new RegExp(h+"\\b","i")).test(a)){d=!0;break}if(d)break;h=null}return h};ea=function(a,c,d,e,h){Ha.lastIndex=0;var f=Ha.exec(a);null===f&&ta(a,c,h?2:0);var k=[{y:c.indexOf("y")},{M:c.indexOf("M")},{d:c.indexOf("d")}];k.sort(function(a,b){for(var c in a)break;for(var d in b)break;return a[c]-b[d]});var g,l,q,m,r,t,p=O(k,"d"),n=!1,u=!1;for(t=1;3>=t;t++){var s=
f[t];if(2<s.length||31<s)g=s,n=!0,m=t-1}n||(m=O(k,"y"),g=f[O(k,"y")+1]);for(t=0;3>t;t++)if(t!==m&&12<f[t+1]){q=f[t+1];u=!0;r=t;break}if(u){for(t=0;3>t;t++)if(t!==r&&t!==m){l=f[t+1];break}void 0===l&&(l=f[O(k,"M")+1])}else m===O(k,"d")?(q=f[O(k,"y")+1],l=f[O(k,"M")+1]):m===O(k,"M")?(q=f[O(k,"d")+1],l=f[O(k,"y")+1]):(q=f[O(k,"d")+1],l=f[O(k,"M")+1]);l-=1;f=C(g,l);u&&p!==r&&12<l&&aa("month",q,0,11,q,1,12);aa("month",l,0,11,l+1,1,12);aa("day",q,1,f,q,1,f);g=U(y(d),parseInt(g,10));aa("year",g,0,9999,g,
0,9999);d=new Date(g,l,q);g=Da(a,e);null!==g&&(l=X(e,g,0),d.getDay()!==l&&ua(g,d.getDate()));d={value:d,offset:"",warning:"lenient parsing was used"};h&&(a=a.substr(Ha.lastIndex),0===a.length?d.value.setHours(0,0,0,0):W(d.value,a,c,e,2));d.value=b.dateToLocalIso(d.value);return d};ga=function(a,c,d,e,h){var f=a;a=b.jj(a);var k=b.sh(e),g=k.dates.calendars.gregorian.months.format,k=k.dates.calendars.gregorian.months["stand-alone"],g=[g.wide,g.abbreviated,k.wide,k.abbreviated],k=!1,l,q,m,r;for(q in g){l=
[];for(m in g[q])r=b.jj(g[q][m]),l.push({idx:m,name:r});l.sort(function(a,b){return b.idx-a.idx});for(m in l)if(r=l[m].name,-1!==a.indexOf(r)){k=!0;a=a.replace(r,"");break}if(k)break}if(!k)return ea(f,c,d,e,h);m=da(e,r,2);aa("month",m,0,11,m,1,12);r=Da(f,e);q=new RegExp(r+"\\W","i");null!==r&&(a=a.replace(q,""));Ga.lastIndex=0;g=Ga.exec(a);null===g&&ta(f,c,h?2:0);f=[{y:c.indexOf("y")},{d:c.indexOf("d")}];f.sort(function(a,b){for(var c in a)break;for(var d in b)break;return a[c]-b[d]});var t,p,k=!1;
for(q=1;2>=q;q++)if(l=g[q],2<l.length||31<l)t=l,k=!0,p=q-1;k||(p=O(f,"y"),t=g[O(f,"y")+1]);p=p===O(f,"d")?g[O(f,"y")+1]:g[O(f,"d")+1];t=U(y(d),parseInt(t,10));aa("year",t,0,9999,t,0,9999);d=new Date(t,m,p);null!==r&&(q=X(e,r,0),d.getDay()!==q&&ua(r,d.getDate()));t=C(t,m);aa("day",p,1,t,p,1,t);t={value:d,offset:"",warning:"lenient parsing was used"};h&&(a=a.substr(Ga.lastIndex),0===a.length?t.value.setHours(0,0,0,0):W(t.value,a,c,e,2));t.value=b.dateToLocalIso(t.value);return t};Z=function(a,c,d,e){switch(v(d,
"OraDateTimeConverter.parse")){case 0:return ga(a,c,d,e,!1);case 1:return d=new Date,W(d,a,c,e,1),{value:b.dateToLocalIso(d),offset:"",warning:"lenient parsing was used"};case 2:return ga(a,c,d,e,!0)}return null};Ca=function(a,c,d,e,h,f,k,g,l,q,m){h=b.sh(a).dates.calendars.gregorian[c][h];a="months"===c?da(a,d,f):X(a,d,f);aa(m,a,k,g,d,h[e][l],h[e][q]);return a};Qa=function(a,b,c,d){b[c.timePart]=a;"h"===d||"hh"===d?12===a&&(b[c.timePart]=0):"k"!==d&&"kk"!==d||24!==a||(b[c.timePart]=0);aa(c.timePart,
b[c.timePart],c.start1,c.end1,a,c.start2,c.end2)};g=function(a,c,d,e){var h=b.sh(e),f=h.dates.calendars.gregorian.eras.eraAbbr["1"],k=b.Fp(f);a=a.replace(f,k);var f=Ia(c,d),g=(new RegExp(f.regExp)).exec(a);if(null===g)return Z(a,c,d,e);for(var l=f.groups,q=null,m=null,r=null,t=null,f="",k=null,p=!1,n,u={hour:0,minute:0,second:0,millisec:0},h=h.dates.calendars.gregorian.dayPeriods.format.wide.pm,s=y(d),v=0,w=l.length;v<w;v++){var x=g[v+1];if(x){var A=l[v],B=parseInt(x,10),z=ia[A];switch(z.token){case "months":m=
Ca(e,z.token,x,z.mLen,z.style,z.matchIndex,0,11,"1","12","month name");break;case "days":n=x;t=Ca(e,z.token,x,z.dLen,z.style,z.matchIndex,0,6,"sun","sat","weekday");break;case "time":Qa(B,u,z,A);break;case "dayOfMonth":r=B;if(31<r)return Z(a,c,d,e);break;case "monthIndex":m=B-1;if(11<m)return Z(a,c,d,e);break;case "year":q=U(s,B);aa("year",q,0,9999,q,0,9999);break;case "ampm":p=-1!==b.jj(x).indexOf(b.jj(h));break;case "tzhm":f=x.substr(-2);f=x.substr(0,3)+":"+f;break;case "tzhsepm":f=x;break;case "tzh":f=
x+":00";break;case "tzid":k=x}}}a=new Date;null===q&&(q=a.getFullYear());null===m&&null===r?(m=a.getMonth(),r=a.getDate()):null===r&&(r=1);c=C(q,m);aa("day",r,1,c,r,1,c);a.setFullYear(q,m,r);null!==t&&a.getDay()!==t&&ua(n,a.getDate());p&&12>u.hour&&(u.hour+=12);a=[q,m+1,r,u.hour,u.minute,u.second,u.millisec];n=b.rIa(a);null!==k&&(e=na(k,e),f=oa(e,a,!1,!0,!0),f=-e.offset(f),f=b.bA("",f,!1,!0));""!==f&&(n+=f);return{value:n}};u=function(a,b,c){var e=c.replace(Ya,"\\\\$1"),h=["^"],f=0,k=0;for(a={locale:a,
numberingSystem:b,calendar:"gregorian"};null!==(b=pa.exec(e));){var g=e.slice(k,b.index),k=pa.lastIndex,f=f+d(g,h);if(!(f%2)&&(b=b[0],"/"!==b&&"zzzz"!==b&&"zzz"!==b&&"zz"!==b&&"z"!==b))if(void 0!==ia[b])if(void 0!==ia[b].key&&(a[ia[b].key]=ia[b].value),"kk"===b||"HH"===b||"H"===b||"k"===b)a.hour12=!1;else{if("KK"===b||"hh"===b||"h"===b||"K"===b)a.hour12=!0}else q(c,a,b)}return a};z=function(a){a=u("","",a);var b=void 0!==a.hour||void 0!==a.minute||void 0!==a.second||void 0!==a.millisecond;return void 0===
a.year&&void 0===a.month&&void 0===a.weekday&&void 0===a.day||!b?b?1:0:2};w=function(a){a=a.indexOf("T");return-1===a?0:0<a?2:1};v=function(a,c){if(void 0!==a.pattern)return z(a.pattern);var d=b.Tj(a,c),e=void 0!==d("hour","string",["2-digit","numeric"])||void 0!==d("minute","string",["2-digit","numeric"])||void 0!==d("second","string",["2-digit","numeric"])||void 0!==d("millisecond","string",["numeric"]),h=void 0!==d("year","string",["2-digit","numeric"])||void 0!==d("month","string",["2-digit",
"numeric","narrow","short","long"])||void 0!==d("day","string",["2-digit","numeric"])||void 0!==d("weekday","string",["narrow","short","long"]);if(h&&e)return 2;if(e)return 1;if(h)return 0;d=d("formatType","string",["date","time","datetime"],"date");return"datetime"===d?2:"time"===d?1:0};Ba=function(a,b){var c=oa(a,b,!1,!0,!1),d=a.offset(c),c=a.offset(c+1);return Math.max(d,c)};Aa=function(a,c,d){var e=a.isoStrParts,h=a.format,f=c.timeZone;b.Tj(c,"OraDateTimeConverter.parse");c=na(f,d);var k;d=Date.UTC(e[0],
e[1]-1,e[2],e[3],e[4],e[5]);switch(h){case ma:a=a.timeZone;k=a.split(":");h=parseInt(k[1],10);k=60*parseInt(k[0],10)+(b.Rw(a,"-")?-h:h);break;case la:k=0}a=Ba(c,e);a=c.parse(d-6E4*(a+k),!1,!0,!1);a=-c.offset(a);c=new Date(Date.UTC(e[0],e[1]-1,e[2],e[3],e[4],e[5]));k=c.getUTCMinutes()+(a-k);c.setUTCHours(c.getUTCHours()+(k/60<<0),k%60);e[0]=c.getUTCFullYear();e[1]=c.getUTCMonth()+1;e[2]=c.getUTCDate();e[3]=c.getUTCHours();e[4]=c.getUTCMinutes();e[5]=c.getUTCSeconds()};za=function(a,c){var d,e="";switch(a){case 0:e=
b.sc(c[0],4)+"-"+b.sc(c[1],2)+"-"+b.sc(c[2],2);break;case 1:e="T"+b.sc(c[3],2)+":"+b.sc(c[4],2)+":"+b.sc(c[5],2);d=c[6];0<d&&(e+="."+b.EN(b.sc(d,3)));break;default:e=b.sc(c[0],4)+"-"+b.sc(c[1],2)+"-"+b.sc(c[2],2)+"T"+b.sc(c[3],2)+":"+b.sc(c[4],2)+":"+b.sc(c[5],2),d=c[6],0<d&&(e+="."+b.EN(b.sc(d,3)))}return e};xa=function(a,c,d,e,h,f){a=na(a,h);c=oa(a,c,d,e,f);c=a.offset(c);return b.bA("",c,!0,!0)};La=function(a,c,d,e){var h,f=b.Tj(d,"OraDateTimeConverter.parse"),k=f("isoStrFormat","string",[la,ma,
Ra,ka,sa],sa);h=f("dst","boolean",[!0,!1],!1);var g=!0,f=c.isoStrParts,l=c.timeZone,q=d.timeZone;c=c.format;var m=d.isoStrFormat;d=za(a,f);if(0===a||"local"===m)return d;1===a&&(g=!1);switch(k){case ma:void 0===q&&c===ma?d+=l:void 0===q&&c===ka?d+="":void 0===q&&c===la?d+="+00:00":void 0!==q&&(e=xa(q,f,h,g,e,!0),d+=e);break;case la:k=0;void 0===q?c===ma&&(e=l.split(":"),h=parseInt(e[1],10),k=60*parseInt(e[0],10)+(b.Rw(e[0],"-")?-h:h),k=-k):(e=na(q,e),h=oa(e,f,h,g,!0),k=e=e.offset(h));0!==k&&(d=new Date(Date.UTC(f[0],
f[1]-1,f[2],f[3],f[4],f[5],f[6])),k=d.getUTCMinutes()+k,d.setUTCHours(d.getUTCHours()+(k/60<<0),k%60),f[0]=d.getUTCFullYear(),f[1]=d.getUTCMonth()+1,f[2]=d.getUTCDate(),f[3]=d.getUTCHours(),f[4]=d.getUTCMinutes(),f[5]=d.getUTCSeconds(),d=za(a,f));d+="Z";break;case sa:void 0!==q?(e=xa(q,f,h,g,e,!0),d+=e):(e=l)&&(d+=e)}return d};n=function(a,c,d,e){var h=b.bM(e);void 0===b.Bp[h]&&(h="latn");if("latn"!==h){var k,l=[];for(k=0;k<a.length;k++){var q=b.Bp[h].indexOf(a[k]);-1!==q?l.push(q):l.push(a[k])}a=
l.join("")}if(2>=arguments.length||void 0===d)d={year:"numeric",month:"numeric",day:"numeric"};k={};!0===b.jP.test(a)?(l=a,h=w(a)):(k=d.pattern||f(d,c,e,"OraDateTimeConverter.parse"),h=v(d,"OraDateTimeConverter.parse"),k=g(a,k,d,c),l=k.value);l=b.YL(l);void 0!==d.timeZone&&l.format!==ka&&Aa(l,d,c);l=La(h,l,d,c);k.value=l;return k};Ma=function(a,c){var d={isoStrFormat:ka},e=b.YL(a),h=b.YL(c).format;if(e.format===ka||h===ka)return d;d.isoStrFormat=la;return d};Ja=function(a,b,c,d,e,h){d=u(d,e,h.pattern);
d.pattern=h.pattern;void 0!==a&&(d.isoStrFormat=a);void 0!==b&&(d.timeZone=b);void 0!==c&&(d.dst=c);return d};Ka=function(a,b,c,d){var e=!1;void 0!==c&&(b.dst=c);c=a("year","string",["2-digit","numeric"]);void 0!==c&&(b.year=c,e=!0);c=a("era","string",["narrow","short","long"]);void 0!==c&&(b.era=c,e=!0);c=a("month","string",["2-digit","numeric","narrow","short","long"]);void 0!==c&&(b.month=c,e=!0);c=a("day","string",["2-digit","numeric"]);void 0!==c&&(b.day=c,e=!0);c=a("weekday","string",["narrow",
"short","long"]);void 0!==c&&(b.weekday=c,e=!0);c=a("hour","string",["2-digit","numeric"]);void 0!==c&&(b.hour=c,e=!0,c=a("hour12","boolean",[!0,!1]),void 0===c&&(c=x(d)),b.hour12=c);c=a("minute","string",["2-digit","numeric"]);void 0!==c&&(b.minute=c,e=!0);c=a("second","string",["2-digit","numeric"]);void 0!==c&&(b.second=c,e=!0);c=a("millisecond","string",["numeric"]);void 0!==c&&(b.millisecond=c,e=!0);return e};ja=function(a,b,c,d){b=D(b,c,h.resolvedOptions);c=d("formatType","string",["date","time",
"datetime"],"date");var e=d("dateFormat","string",["short","medium","long","full"],"short");d=d("timeFormat","string",["short","medium","long","full"],"short");a.formatType=c;if("datetime"===c||"date"===c)a.dateFormat=e;if("datetime"===c||"time"===c)a.timeFormat=d;a.patternFromOptions=b};qa=function(a,b,c,d,e,h,k,g){k={locale:g,numberingSystem:k,calendar:"gregorian"};var l,q=0;for(l in a)q++;if(0===q)return k.year="numeric",k.month="numeric",k.day="numeric",k;void 0!==c&&(k.timeZone=c,void 0!==e&&
(k.isoStrFormat=e));d=Ka(b,k,d,h);k["two-digit-year-start"]=y(a);if(!d)return ja(k,a,h,b),k;void 0!==c&&(l=b("timeZoneName","string",["short","long"],"short"),void 0!==l&&(k.timeZoneName=l));k.patternFromOptions=f(k,h,g,"OraDateTimeConverter.resolvedOptions");return k};ba=function(a,b,c){a=f({year:"numeric",month:"numeric",day:"numeric"},a,b,"OraDateTimeConverter.resolvedOptions");return{calendar:"gregorian",locale:b,numberingSystem:c,year:"numeric",month:"numeric",day:"numeric",patternFromOptions:a}};
Pa=function(a){function c(d){for(var e in d){d=f.zfa(e,a);d=Ba(d,t);var h;var k=e;h=d;var g=l,p=k.split("/"),k=p[0],n=p[1],u=p="",s={},v=q[k];void 0!==v&&(p=v[n],void 0!==p&&(p=p.exemplarCity,void 0!==p&&(p=" "+p)));k=k+"/"+n;k=Ea(t,k,a.supplemental.metazones);k=g[k];void 0!==k&&void 0!==k["long"]&&(u=k["long"].generic,void 0===u&&(u=k["long"].standard),void 0!==u&&(u=" - "+u));g="(UTC)";0!==h&&(g=b.bA("UTC",h,!0,!0),g="("+g+")");void 0===p||void 0===u?h=null:(s.offsetLocName=g+p+u,s.locName=p+u,
h=s);null!==h&&(m.push({id:e,displayName:h}),r[e]=d)}}var d=b.rt(a);if(void 0!==B[d]){var h=B[d].availableTimeZones;if(void 0!==h)return h}var f=e.Je(),k={ILa:"variant"},g=b.rt(a),h=b.sh(a),l=h.dates.timeZoneNames.metazone,q=h.dates.timeZoneNames.zone,m=[],r={},h=new Date,t=[h.getFullYear(),h.getMonth()+1,h.getDate(),h.getHours(),h.getMinutes(),h.getSeconds()],h=a.supplemental.timeZoneData;c(h.zones);c(h.links);m.sort(function(a,b){return r[b.id]-r[a.id]+a.displayName.locName.localeCompare(b.displayName.locName,
g,k)});for(var h=m.length,p=0;p<h;p++)m[p].displayName=m[p].displayName.offsetLocName;void 0===B[d]&&(B[d]={},B[d].availableTimeZones=m);return m};return{Je:function(){c||(c=a());return c}}}();a.fk=function(a){this.Init(a)};o_("LengthValidator",a.fk,a);a.fk.Zc={countBy:"codeUnit"};o_("LengthValidator.defaults",a.fk.Zc,a);a.b.ta(a.fk,a.Gi,"oj.LengthValidator");a.fk.prototype.Init=function(b){var c=b.countBy;a.fk.t.Init.call(this);this.Oi=void 0!==b.min?parseInt(b.min,10):null;this.Lj=void 0!==b.max?
parseInt(b.max,10):null;if(isNaN(this.Oi))throw Error("length validator's min option is not a number. min option is "+b.min);if(isNaN(this.Lj))throw Error("length validator's max option is not a number. max option is "+b.min);if(null!==this.Oi&&0>this.Oi)throw Error("length validator's min option cannot be less than 0. min option is "+b.min);if(null!==this.Lj&&1>this.Lj)throw Error("length validator's max option cannot be less than 1. max option is "+b.max);this.Qpa=void 0===c?a.fk.Zc.countBy:c;b&&
(this.cD=b.hint||{},this.sC=b.messageSummary||{},this.rC=b.messageDetail||{})};a.b.g("LengthValidator.prototype.Init",{Init:a.fk.prototype.Init});a.fk.prototype.Md=function(){var b=null,c=this.cD,d=c.exact,e=c.inRange,h=c.max,c=c.min,f=this.Lj,g=this.Oi,p=a.va;null!==g&&null!==f?g!==f?(b={min:g,max:f},b=e?p.Lc(e,b):p.F("oj-validator.length.hint.inRange",b)):(b={length:g},b=d?p.Lc(d,b):p.F("oj-validator.length.hint.exact",b)):null!==g?(b={min:g},b=c?p.Lc(c,b):p.F("oj-validator.length.hint.min",b)):
null!==f&&(b={max:f},b=h?p.Lc(h,b):p.F("oj-validator.length.hint.max",b));return b};a.fk.prototype.validate=function(b){var c=this.rC,d=this.sC,e="",h,f=this.Lj,e=d.tooLong,d=d.tooShort,g=c.tooLong,c=c.tooShort,p=this.Oi,q;h="";var u=a.va;q=""+b;h=this.mf(q);if((null===p||h>=this.Oi)&&(null===f||h<=this.Lj))return q;h<this.Oi?(b={value:b,min:p},h=d?u.Lc(d,b):u.F("oj-validator.length.messageSummary.tooShort"),e=c?u.Lc(c,b):u.F("oj-validator.length.messageDetail.tooShort",b)):(b={value:b,max:f},h=e?
u.Lc(e,b):u.F("oj-validator.length.messageSummary.tooLong"),e=g?u.Lc(g,b):u.F("oj-validator.length.messageDetail.tooLong",b));throw new a.nk(h,e);};a.b.g("LengthValidator.prototype.validate",{validate:a.fk.prototype.validate});a.fk.prototype.mf=function(b){var c=b.length,d,e=0;switch(this.Qpa.toLowerCase()){case "codepoint":for(d=0;d<c;d++)55296===(b.charCodeAt(d)&63488)&&e++;a.o.assert(0===e%2,"the number of surrogate chars must be an even number.");b=c-e/2;break;default:b=c}return b}});